CREATE TABLE atlas_driver_offer_bpp.pg_settlement_batch ();

ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN adjustment_amount double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN chargeback_amount double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN chargeback_reversal_amount double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN charges double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN created_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN currency text ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN merc_id text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN merchant_id text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN merchant_operating_city_id text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN object_id text ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN other_adjustments double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN payment_gateway text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN payout_amount double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN payout_merc_id text ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN pv_file text ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN pv_file_date text ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN pv_number text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN refund_amount double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN refund_reversal_amount double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN settlement_amount double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN settlement_date timestamp with time zone ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN status text ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN taxes double precision ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN updated_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN utr text ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD COLUMN utr_date timestamp with time zone ;
ALTER TABLE atlas_driver_offer_bpp.pg_settlement_batch ADD PRIMARY KEY ( id);
