CREATE TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ();

ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN actor_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN actor_type text NOT NULL default 'SYSTEM';
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN amount numeric(30,2) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN bap_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN bap_uri text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN bff_amount numeric(30,2) ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN bff_type text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN claim_status text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN collector_app_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN context_transaction_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN counterparty_recon_status text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN created_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN currency text NOT NULL default 'INR';
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN deduction_by_collector numeric(30,2) ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN diff_message_code text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN diff_message_name text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN driver_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN effective_at timestamp with time zone NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN entry_type text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN invoice_no text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN merchant_id text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN merchant_operating_city_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN message_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN order_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN order_payment_amount numeric(30,2) ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN order_state text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN order_transaction_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN raw_json text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN reason text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN rejection_diff numeric(30,2) ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN reported_at timestamp with time zone ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN reported_in_message_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN ride_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN settlement_id text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN settlement_reason_code text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN source text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN ttl text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN updated_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN utr text ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN withholding_tax_gst numeric(30,2) ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD COLUMN withholding_tax_tds numeric(30,2) ;
ALTER TABLE atlas_driver_offer_bpp.rsf_recon_ledger_entry ADD PRIMARY KEY ( id);
CREATE INDEX CONCURRENTLY rsf_recon_ledger_entry_idx_merchant_id_order_id ON atlas_driver_offer_bpp.rsf_recon_ledger_entry USING btree (merchant_id, order_id);
CREATE INDEX CONCURRENTLY rsf_recon_ledger_entry_idx_merchant_id_utr ON atlas_driver_offer_bpp.rsf_recon_ledger_entry USING btree (merchant_id, utr);
CREATE INDEX CONCURRENTLY rsf_recon_ledger_entry_idx_entry_type_merchant_id_message_id ON atlas_driver_offer_bpp.rsf_recon_ledger_entry USING btree (entry_type, merchant_id, message_id);