CREATE TABLE atlas_driver_offer_bpp.shared_booking ();

ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN booking_ids uuid[] NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN created_at timestamptz NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN distance_unit character varying(255) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN driver_id character varying(36) ;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN estimated_distance double precision ;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN estimated_duration integer ;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN estimated_total_fare numeric(30,10) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN from_location_ids uuid[] NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN merchant_id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN merchant_operating_city_id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN pairing_time timestamptz NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN provider_id character varying(255) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN provider_url character varying(255) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN shared_estimate_id uuid NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN status character varying(255) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN to_location_ids uuid[] NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN toll_names text[] ;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN transaction_id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN updated_at timestamptz NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD COLUMN vehicle_service_tier character varying(255) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.shared_booking ADD PRIMARY KEY ( id);
