# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def common_pods
 # Pods for app
 pod 'GoogleMaps', '6.2.1'
  
 pod 'HyperNYSDK', :http => 'https://public.releases.juspay.in/release/ios/hyper-ny-sdk/1.0.0/HyperNYSDK.zip'
  
 pod 'Firebase/AnalyticsWithoutAdIdSupport', '9.2.0'
 pod 'FirebaseMessaging', '9.2.0'
  
 pod 'lottie-ios', '4.0.1'
end

target 'NammaYatri-Debug' do
 # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!
 common_pods
  
 pod 'FLEX'
end

target 'NammaYatri-Release' do
 # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!
 common_pods
end

post_install do |installer|
 installer.pods_project.build_configurations.each do |config|
   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
 end
end