
export function getStringValue(key) {
	if (key in bengaliStrings) {
		return bengaliStrings[key];
	}
	console.error(key + " not found in bengaliStrings");
	return "";
}

const bengaliStrings = {
	INACCURATE_DATE_AND_TIME: "ভুল তারিখ ও সময়!",
	ADJUST_YOUR_DEVICE_DATE_AND_TIME_AND_TRY_AGAIN: "আপনার ডিভাইসের তারিখ এবং সময় সামঞ্জস্য করুন এবং আবার চেষ্টা করুন",
	THE_CURRENT_DATE_AND_TIME_IS: "বর্তমান তারিখ এবং সময় হল",
	GO_TO_SETTING: "সেটিংস এ যান",
	LETS_GET_STARTED: "চল শুরু করি",
	YOUR_APPLICATION_HAS_BEEN_SUBMITTED_SUCCESSFULLY_AND_IS_UNDER_VERIFICATION: "আপনার আবেদন সফলভাবে জমা দেওয়া হয়েছে এবং যাচাইয়ের অধীনে রয়েছে",
	VIEW_STATUS: "স্থিতি দেখুন",
	GO_HOME: "বরিতে জ",
	SELECT_LANGUAGE: "ভাষা নির্বাচন কর",
	WHICH_LANGUAGE_DO_YOU_PREFER: "আপনি কোন ভাষা পছন্দ করেন?",
	NEXT: "পরবর্তী",
	T_C: "শর্তাবলী",
	ENTER_MOBILE_NUMBER: "মোবাইল নম্বর লিখুন",
	BY_CLICKING_CONTINUE_YOU_WILL_BE_AGREEING_TO_OUR: "অবিরত ক্লিক করে, আপনি আমাদের সাথে সম্মত হন",
	ENTER_OTP: "ওটিপি লিখুন",
	DIDNT_RECIEVE_OTP: "ওটিপি গ্রহণ করেনি?",
	RESEND_OTP: "ওটিপি পুনরায় প্রেরণ করুন",
	PLEASE_ENTER_VALID_OTP: "বৈধ ওটিপি লিখুন দয়া করে",
	INVALID_MOBILE_NUMBER: "অকার্যকর মোবাইল নম্বর",
	REGISTER: "নিবন্ধন",
	MOBILE_NUMBER: "মোবাইল নম্বর",
	AUTO_READING_OTP: "অটো রিডিং ওটিপি ...",
	UPLOAD_DRIVING_LICENSE: "ড্রাইভিং লাইসেন্স আপলোড করুন",
	UPLOAD_BACK_SIDE: "পিছনে পিছনে আপলোড করুন",
	UPLOAD_FRONT_SIDE: "আপনার ডিএল এর ফটো সাইড আপলোড করুন",
	BACK_SIDE: "পিছন দিক",
	FRONT_SIDE: "আপনার ডিএল এর ফটো সাইড",
	LICENSE_INSTRUCTION_PICTURE: "দয়া করে লাইসেন্সের উভয় পক্ষের পরিষ্কার ছবি আপলোড করুন",
	LICENSE_INSTRUCTION_CLARITY: "ফটো নিশ্চিত করুন এবং সমস্ত বিবরণ স্পষ্টভাবে দৃশ্যমান",
	REGISTRATION_STEPS: "নিবন্ধকরণ পদক্ষেপ",
	PROGRESS_SAVED: "আপনার অগ্রগতি সংরক্ষণ করা হয়েছে, আপনি কোনও তথ্য পরিবর্তন করতে পূর্ববর্তী পদক্ষেপে ফিরে যেতে পারেন",
	DRIVING_LICENSE: "ড্রাইভিং লাইসেন্স",
	AADHAR_CARD: "আধার কার্ড",
	BANK_DETAILS: "ব্যাংক বিবরণ",
	VEHICLE_DETAILS: "গাড়ির বিবরণ",
	UPLOAD_FRONT_BACK: "সামনে এবং পিছনের দিক আপলোড করুন",
	EARNINGS_WILL_BE_CREDITED: "আপনার উপার্জন এখানে ক্রেডিট হবে",
	FILL_VEHICLE_DETAILS: "আপনার গাড়ির বিশদ পূরণ করুন",
	FOLLOW_STEPS: "নিবন্ধনের জন্য নীচের পদক্ষেপগুলি অনুসরণ করুন",
	REGISTRATION: "নিবন্ধকরণ",
	UPLOAD_ADHAAR_CARD: "আধার কার্ড আপলোড করুন",
	ADHAAR_INTRUCTION_PICTURE: "দয়া করে আধার কার্ডের উভয় পক্ষের পরিষ্কার ছবি আপলোড করুন",
	ADD_VEHICLE_DETAILS: "গাড়ির বিশদ যুক্ত করুন",
	VEHICLE_REGISTRATION_NUMBER: "গাড়ির রেজিস্ট্রেশন নম্বর",
	RE_ENTER_VEHICLE_REGISTRATION_NUMBER: "পুনরায় প্রবেশের যানবাহন নিবন্ধকরণ নম্বর",
	ENTER_VEHICLE_NO: "যানবাহন নং প্রবেশ করান",
	VEHICLE_TYPE: "গাড়ির ধরন",
	VEHICLE_MODEL_NAME: "গাড়ির মডেল নাম",
	ENTER_MODEL_NAME: "মডেল নাম লিখুন",
	VEHICLE_COLOUR: "গাড়ির রঙ",
	ENTER_VEHICLE_COLOUR: "গাড়ির রঙ প্রবেশ করুন",
	UPLOAD_REGISTRATION_CERTIFICATE: "নিবন্ধকরণ শংসাপত্র আপলোড করুন (আরসি)",
	UPLOAD_RC: "আপলোড আরসি",
	PREVIEW: "পূর্বরূপ",
	CHOOSE_VEHICLE_TYPE: "গাড়ির ধরণ চয়ন করুন",
	BENIFICIARY_NUMBER: "সুবিধাভোগী অ্যাকাউন্ট নং",
	RE_ENTER_BENIFICIARY_NUMBER: "পুনরায় প্রবেশের সুবিধাভোগী অ্যাকাউন্ট নং",
	IFSC_CODE: "আইএফএসসি কোড",
	SENDING_OTP: "ওটিপি প্রেরণ",
	PLEASE_WAIT_WHILE_IN_PROGRESS: "অগ্রগতির সময় অপেক্ষা করুন",
	YOUR_REQUEST_HAS_TIMEOUT_TRY_AGAIN: "আপনার অনুরোধে আবার চেষ্টা করুন",
	ERROR_OCCURED_PLEASE_TRY_AGAIN_LATER: "ত্রুটি ঘটেছে দয়া করে পরে আবার চেষ্টা করুন",
	ENTER_OTP_SENT_TO: " নম্বরে পাঠানো ওটিপি লিখুন",
	OTP_SENT_TO: " নম্বরে ওটিপি পাঠানো হয়েছে",
	COUNTRY_CODE_INDIA: "+91",
	ENTER_ACCOUNT_NUMBER: "অ্যাকাউন্ট নং প্রবেশ করান",
	ADD_BANK_DETAILS: "ব্যাংকের বিশদ যুক্ত করুন",
	ENTER_IFSC_CODE: "আইএফএসসি কোড প্রবেশ করান",
	SUBMIT: "জমা দিন",
	PERSONAL_DETAILS: "ব্যক্তিগত বিবরণ",
	LANGUAGES: "ভাষা",
	HELP_AND_FAQ: "সহায়তা",
	ABOUT: "অ্যাপ সম্পর্কিত",
	LOGOUT: "প্রস্থান",
	UPDATE: "আপডেট",
	EDIT: "সম্পাদনা",
	AUTO: "অটো",
	NAME: "নাম",
	PRIVACY_POLICY: "গোপনীয়তা নীতি",
	LOGO: "লোগো",
	ABOUT_APP_DESCRIPTION: "জাটি সাথি ড্রাইভার চালকদের সাথে ড্রাইভারদের সংযোগ করার জন্য একটি উন্মুক্ত প্ল্যাটফর্ম। অ্যাপটি প্রস্তাবিত পছন্দসই হার সহ চালকদের সন্ধান করা ড্রাইভারদের পক্ষে সুবিধাজনক করে তোলে। কোনও রাইড ভিত্তিক কমিশন নেই, কেবল মাসিক সাবস্ক্রিপশন আকারে অল্প পরিমাণে অর্থ প্রদান করুন",
	TERMS_AND_CONDITIONS: "শর্তাবলী",
	UPDATE_VEHICLE_DETAILS: "যানবাহন বিশদ আপডেট করুন",
	Help_AND_SUPPORT: "সাহায্য এবং সহযোগিতা",
	NOTE: "বিঃদ্রঃ:",
	VISIT_MY_RIDES_SCREEN_FOR_SPECIFIC_COMPLAINTS: "রাইড সংক্রান্ত অভিযোগের জন্য আমার রাইডস বিভাগে যান",
	THANK_YOU_FOR_WRTITTING_US: "আমাদের লেখার জন্য আপনাকে ধন্যবাদ!",
	WE_HAVE_RECIEVED_YOUR_ISSUE: "আমরা আপনার সমস্যাটি পুনরুদ্ধার করেছি। আমরা কিছু সময় আপনার কাছে পৌঁছে যাব।",
	GO_TO_HOME: "বাড়িতে যেতে",
	YOUR_RECENT_RIDE: "আপনার সাম্প্রতিক যাত্রা",
	YOUR_RECENT_TRIP: "আপনার সাম্প্রতিক ট্রিপ",
	ALL_TOPICS: "সমস্ত বিষয়",
	REPORT_AN_ISSUE_WITH_THIS_TRIP: "এই ট্রিপ দিয়ে একটি সমস্যা রিপোর্ট করুন",
	YOU_RATED: "আপনি রেট করেছেন:",
	VIEW_ALL_RIDES: "সমস্ত ট্রিপ্স দেখুন",
	WRITE_TO_US: "আমাদের লিখুন",
	SUBJECT: "বিষয়",
	YOUR_EMAIL_ID: "আপনার ইমেল আইডি",
	DESCRIBE_YOUR_ISSUE: "আপনার সমস্যাটি বর্ণনা",
	GETTING_STARTED_AND_FAQ: "শুরু করা এবং FAQss",
	FOR_OTHER_ISSUES_WRITE_TO_US: "অন্যান্য ইস্যুগুলির জন্য, আমাদের লিখুন",
	CALL_SUPPORT_CENTER: "কল সমর্থন কেন্দ্র",
	YOU_CAN_DESCRIBE_ISSUE_THAT_YOU_FACED_HERE: "আপনি এখানে যে সমস্যার মুখোমুখি হয়েছেন তা বর্ণনা করতে পারেন",
	REGISTRATION_CERTIFICATE_IMAGE: "নিবন্ধকরণ শংসাপত্র (আরসি) চিত্র",
	HOME: "বাড়ি",
	RIDES: "রাইডস",
	MY_RIDES: "আমার রাইডস",
	PROFILE: "প্রোফাইল",
	ENTER_DRIVING_LICENSE_NUMBER: "ড্রাইভিং লাইসেন্স নম্বর প্রবেশ করান",
	WHERE_IS_MY_LICENSE_NUMBER: "আমার লাইসেন্স নম্বরটি কোথায়?",
	TRIP_DETAILS: "ভ্রমণের বিশদ",
	BY_CASH: "নগদে",
	ONLINE_: "অনলাইন",
	GO_ONLINE_POPUP: "<u>যাওয়া অনলাইন</u>",
	REPORT_AN_ISSUE: "একটি সমস্যা রিপোর্ট",
	DISTANCE: "দূরত্ব",
	TIME_TAKEN: "সময় নিয়েছে",
	OPEN_GOOGLE_MAPS: "গুগল মানচিত্র",
	CALL: "কল",
	START_RIDE: "যাত্রা শুরু করুন",
	CANCEL_RIDE: "যাত্রা বাতিল করুন",
	PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL: "আপনি কেন বাতিল করতে চান দয়া করে আমাদের বলুন",
	MANDATORY: "বাধ্যতামূলক",
	END_RIDE: "শেষ যাত্রা",
	RIDE_COMPLETED_WITH: "গ্রাহকের সাথে যাত্রা সম্পূর্ণ",
	COLLECT_AMOUNT_IN_CASH: "নগদ অর্থ সংগ্রহ করুন",
	CASH_COLLECTED: "নগদ সংগ্রহ করা হয়েছে",
	OFFLINE: "অফলাইন",
	ACCEPT_FOR: "জন্য গ্রহণ:",
	DECLINE: "পতন",
	REQUEST: "অনুরোধ",
	YOU_ARE_OFFLINE: "আপনি অফলাইন",
	YOU_ARE_CURRENTLY_BUSY_GO_ONLINE_TO_RECIEVE_TRIP_REQUESTS: "আপনি বর্তমানে ব্যস্ত। ট্রিপ অনুরোধগুলি পেতে অনলাইনে যান",
	GOING_OFFLINE_WILL_NOT_GET_YOU_ANY_RIDE: "অফলাইনে যাওয়া আপনাকে কোনও যাত্রা পাবে না",
	CANCEL: "বাতিল",
	GO_OFFLINE: "অফলাইন যেতে",
	IS_WAITING_FOR_YOU: "তোমার জন্য অপেক্ষা করছে",
	YOU_ARE_ON_A_RIDE: "আপনি একটি যাত্রায় আছেন ...",
	PLEASE_ASK_RIDER_FOR_THE_OTP: "ওটিপির জন্য রাইডারকে জিজ্ঞাসা করুন",
	COMPLETED_: "সম্পূর্ণ",
	CANCELLED_: "বাতিল",
	WE_NEED_SOME_ACCESS: "আমাদের অ্যাক্সেস অনুসরণ করুন!",
	ALLOW_ACCESS: "ব্যবহারের অনুমতি",
	THANK_YOU_FOR_WRITING_TO_US: "আমাদের লেখার জন্য আপনাকে ধন্যবাদ!",
	RIDER: "রাইডার",
	TRIP_ID: "ট্রিপ আইডি",
	NEED_IT_TO_SHOW_YOU_INCOMING_RIDE_REQUEST: "অ্যাপটি ব্যাকগ্রাউন্ডে থাকাকালীন আগত রাইডের অনুরোধ পান",
	NEED_IT_TO_DISABLE_BATTERY_OPTIMIZATION_FOR_THE_APP: "প্রস্তাবিত, অ্যাপটিকে দীর্ঘকাল ব্যাকগ্রাউন্ডে চালাতে সক্ষম করে",
	NEED_IT_TO_AUTOSTART_YOUR_APP: "অ্যাপটিকে পটভূমিতে চালিয়ে রেখে সহায়তা করে",
	NEED_IT_TO_ENABLE_LOCATION: "জাটি সাথি ড্রাইভার ড্রাইভারের বর্তমান অবস্থান নিরীক্ষণের জন্য আপনার অবস্থানটি ভাগ করে নিতে সক্ষম করতে অবস্থানের ডেটা সংগ্রহ করে, এমনকি অ্যাপটি বন্ধ থাকলেও বা ব্যবহার না করা হয়।",
	OVERLAY_TO_DRAW_OVER_APPLICATIONS: "অ্যাপ্লিকেশনগুলি আঁকুন",
	BATTERY_OPTIMIZATIONS: "ব্যাটারি অপ্টিমাইজেশন",
	AUTO_START_APPLICATION_IN_BACKGROUND: "পটভূমিতে অটোস্টার্ট অ্যাপ",
	LOCATION_ACCESS: "অবস্থান অ্যাক্সেস",
	ENTER_RC_NUMBER: "আরসি নম্বর লিখুন",
	WHERE_IS_MY_RC_NUMBER: "আমার আরসি নম্বরটি কোথায়?",
	STEP: "পদক্ষেপ",
	PAID: "প্রদত্ত",
	ENTERED_WRONG_OTP: "ভুল ওটিপি প্রবেশ করেছে",
	OTP_INVALID_FOR_THIS_VEHICLE_VARIANT : "অবৈধ OTP - গাড়ির ধরন রাইডের প্রকারের সাথে মেলে না",
	COPIED: "অনুলিপি",
	BANK_NAME: "ব্যাংকের নাম",
	AADHAR_DETAILS: "আধারের বিবরণ",
	AADHAR_NUMBER: "আধার নম্বর",
	FRONT_SIDE_IMAGE: "সামনের দিকের চিত্র",
	BACK_SIDE_IMAGE: "পিছনের দিকের চিত্র",
	STILL_NOT_RESOLVED: "এখনও সমাধান না? আমাদের কল",
	CASE_TWO: "খ)",
	NON_DISCLOUSER_AGREEMENT: "কোন প্রকাশ চুক্তি নেই",
	DATA_COLLECTION_AUTHORITY: "গ) আমি এইভাবে আমার তথ্য সংগ্রহের জন্য জুস্পকে নিয়োগ ও অনুমোদন করি এবং চালিয়ে যাওয়ার মাধ্যমে আমি ব্যবহারের শর্তাদি এবং গোপনীয়তা নীতিমালার সাথে সম্মত হই",
	SOFTWARE_LICENSE: "সফ্টওয়্যার লাইসেন্স",
	LOAD_MORE: "আর ঢুকাও",
	ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: "আপনি লগ আউট করতে চান?",
	GO_BACK: "ফিরে যাও",
	THANK_YOU_FOR_REGISTERING_US: "আমাদের সাথে নিবন্ধনের জন্য আপনাকে ধন্যবাদ!",
	UNFORTANUTELY_WE_ARE_NOT_AVAILABLE__YET_FOR_YOU: "দুর্ভাগ্যক্রমে, আমরা আপনার জন্য এখনও উপলব্ধ নেই। আমরা শীঘ্রই আপনাকে অবহিত করব।",
	ARE_YOU_SURE_YOU_WANT_TO_END_THE_RIDE: "আপনি কি নিশ্চিত যে আপনি যাত্রাটি শেষ করতে চান?",
	EMPTY_RIDES: "খালি রাইড",
	YOU_HAVE_NOT_TAKEN_A_TRIP_YET: "আপনি এখনও একটি ট্রিপ নিচ্ছেন না",
	BOOK_NOW: "এখনই বুক করুন",
	RESEND_OTP_IN: "ওটিপি ইন পুনরায় পাঠান",
	WE_NEED_ACCESS_TO_YOUR_LOCATION: "আমাদের আপনার অবস্থানের অ্যাক্সেস দরকার!",
	YOUR_LOCATION_HELPS_OUR_SYSTEM: "আপনার অবস্থানটি আমাদের সিস্টেমকে অটোস দ্বারা সমস্ত কাছাকাছি মানচিত্র করতে এবং আপনাকে দ্রুততম যাত্রা সম্ভব করতে সহায়তা করে।",
	NO_INTERNET_CONNECTION: "কোনও ইন্টারনেট সংযোগ নেই",
	PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN: "দয়া করে আপনাকে ইন্টারনেট সংযোগটি পরীক্ষা করুন এবং আবার চেষ্টা করুন",
	TRY_AGAIN: "আবার চেষ্টা কর",
	GRANT_ACCESS: "অনুদান অ্যাক্সেস",
	YOUR_LIMIT_EXCEEDED_TRY_AGAIN_AFTER_10_MIN: "আপনি সীমা ছাড়িয়ে যান, 10 মিনিটের পরে আবার চেষ্টা করুন",
	ENTER_REFERRAL_MOBILE_NUMBER: "রেফারেল মোবাইল নম্বর প্রবেশ করান",
	APPLY: "প্রয়োগ করুন",
	HAVE_A_REFERRAL: "একটি রেফারেল আছে?",
	ADD_HERE: "এখানে যোগ করুন",
	REFERRAL_APPLIED: "রেফারেল প্রয়োগ!",
	SMALLEDIT: "সম্পাদনা",
	ADD_DRIVING_LICENSE: "ড্রাইভিং লাইসেন্স যুক্ত করুন",
	HELP: "সাহায্য?",
	INVALID_DL_NUMBER: "অবৈধ ডিএল নম্বর",
	DRIVING_LICENSE_NUMBER: "ড্রাইভিং লাইসেন্স নম্বর",
	RE_ENTER_DRIVING_LICENSE_NUMBER: "ড্রাইভিং লাইসেন্স নম্বর পুনরায় প্রবেশ করুন",
	ENTER_DL_NUMBER: "ডিএল নম্বর লিখুন",
	SELECT_DATE_OF_BIRTH: "জন্ম তারিখ নির্বাচন করুন",
	DATE_OF_BIRTH: "জন্ম তারিখ",
	WATCH_A_TUTORIAL_FOR_EASY_REGISTRATION: "সহজ \n নিবন্ধকরণের জন্য একটি টিউটোরিয়াল দেখুন",
	ENTER_MINIMUM_FIFTEEN_CHARACTERS: "মিনিয়াম 15 অক্ষর লিখুন",
	ADD_YOUR_FRIEND: "আপনার বন্ধু যোগ করুন",
	PLEASE_WAIT_WHILE_VALIDATING_THE_IMAGE: "চিত্রটি বৈধ করার সময় দয়া করে অপেক্ষা করুন",
	VALIDATING: "বৈধকরণ",
	VERIFICATION_PENDING: "যাচাইকরণ মুলতুবি",
	VERIFICATION_FAILED: "যাচাই ব্যর্থ",
	NO_DOC_AVAILABLE: "কোন নথি উপলব্ধ",
	ISSUE_WITH_DL_IMAGE: "আপনার ডিএল চিত্রের সাথে কিছু সমস্যা রয়েছে বলে মনে হচ্ছে, আমাদের সমর্থন দলটি শীঘ্রই আপনার সাথে যোগাযোগ করবে।",
	STILL_HAVE_SOME_DOUBT: "এখনও কিছু সন্দেহ আছে?",
	ISSUE_WITH_RC_IMAGE: "আপনার আরসি চিত্রের সাথে কিছু সমস্যা রয়েছে বলে মনে হচ্ছে, আমাদের সমর্থন দলটি শীঘ্রই আপনার সাথে যোগাযোগ করবে।",
	PLEASE_CHECK_FOR_IMAGE_IF_VALID_DOCUMENT_IMAGE_OR_NOT: "বৈধ ডকুমেন্ট ইমেজ কিনা দয়া করে চিত্রের জন্য চেক করুন",
	OOPS_YOUR_APPLICATION_HAS_BEEN_REJECTED: "ওফস! আপনার আবেদন প্রত্যাখ্যান করা হয়েছে। অনুগ্রহপূর্বক আবার চেষ্টা করুন",
	INVALID_DRIVING_LICENSE: "অবৈধ ড্রাইভিং লাইসেন্স",
	LIMIT_EXCEEDED_FOR_DL_UPLOAD: "ডিএল আপলোডের জন্য সীমাবদ্ধতা ছাড়িয়ে যায়",
	INVALID_VEHICLE_REGISTRATION_CERTIFICATE: "অবৈধ যানবাহন নিবন্ধকরণ শংসাপত্র",
	LIMIT_EXCEEDED_FOR_RC_UPLOAD: "আরসি আপলোডের জন্য সীমাবদ্ধতা ছাড়িয়ে গেছে",
	YOUR_DOCUMENTS_ARE_APPROVED: "আপনার নথি অনুমোদিত। সমর্থন দল শীঘ্রই আপনার অ্যাকাউন্ট সক্ষম করবে। আপনার অ্যাকাউন্ট সক্ষম করতে আপনি সমর্থন দলকে কল করতে পারেন",
	APPLICATION_STATUS: "আবেদনপত্রের অবস্থা",
	FOR_SUPPORT: "সমর্থন জন্য",
	CONTACT_US: "যোগাযোগ করুন",
	IMAGE_VALIDATION_FAILED: "চিত্রের বৈধতা ব্যর্থ হয়েছে",
	IMAGE_NOT_READABLE: "চিত্র পঠনযোগ্য নয়",
	IMAGE_LOW_QUALITY: "চিত্রের মান ভাল নয়",
	IMAGE_INVALID_TYPE: "প্রদত্ত চিত্রের ধরণটি প্রকৃত ধরণের সাথে মেলে না",
	IMAGE_DOCUMENT_NUMBER_MISMATCH: "এই চিত্রের ডকুমেন্ট নম্বরটি ইনপুটটির সাথে মেলে না",
	IMAGE_EXTRACTION_FAILED: "চিত্র নিষ্কাশন ব্যর্থ হয়েছে",
	IMAGE_NOT_FOUND: "ছবিটি খুঁজে পাওয়া যায়নি",
	IMAGE_NOT_VALID: "চিত্র বৈধ নয়",
	DRIVER_ALREADY_LINKED: "অন্যান্য ডক ইতিমধ্যে ড্রাইভারের সাথে যুক্ত",
	DL_ALREADY_UPDATED: "কর্ম প্রয়োজন. ড্রাইভার লাইসেন্স ইতিমধ্যে ড্রাইভারের সাথে যুক্ত",
	RC_ALREADY_LINKED: "যানবাহন আরসি উপলভ্য নয়। অন্যান্য ড্রাইভারের সাথে যুক্ত",
	RC_ALREADY_UPDATED: "কর্ম প্রয়োজন. যানবাহন আরসি ইতিমধ্যে ড্রাইভারের সাথে যুক্ত",
	DL_ALREADY_LINKED: "ড্রাইভার লাইসেন্স পাওয়া যায় না। অন্যান্য ড্রাইভারের সাথে যুক্ত",
	SOMETHING_WENT_WRONG: "কিছু ভুল হয়েছে",
	PICKUP: "পিকআপ",
	TRIP: "ট্রিপ",
	CURRENTLY_WE_ALLOW_ONLY_KARNATAKA_REGISTERED_NUMBER: "বর্তমানে, আমরা শুধুমাত্র পশ্চিমবঙ্গ নিবন্ধিত নম্বর অনুমোদন করি",
	UPDATED_AT: "ম্যাপ শেষ আপডেট",
	TRIP_COUNT: "আজকের ট্রিপস",
	TODAYS_EARNINGS: "আজকের উপার্জন",
	BONUS_EARNED : "বোনাস অর্জিত",
	GOT_IT : "বুঝেছি!",
	WHAT_IS_NAMMA_YATRI_BONUS : "বোনাস কি?",
	BONUS_PRIMARY_TEXT : "নম্মা যাত্রী বোনাস হল অতিরিক্ত পরিমাণ যা আপনি মিটার চার্জের উপরে পিকআপ চার্জ, গ্রাহকের টিপস এবং ড্রাইভার যোগের আকারে অর্জন করেছেন।",
    BONUS_SECONDARY_TEXT : "নম্মা যাত্রী বোনাসের পরিমাণ আপনার মোট উপার্জনের অংশ।",
	DATE_OF_REGISTRATION: "নিবন্ধনের তারিখ",
	SELECT_DATE_OF_ISSUE: "ইস্যুর তারিখ নির্বাচন করুন",
	DATE_OF_ISSUE: "প্রদান এর তারিখ",
	PROVIDE_DATE_OF_ISSUE_TEXT: "দুঃখিত, আমরা আপনার বিশদটি বৈধতা দিতে পারি না, আপনার ড্রাইভিং লাইসেন্সটি বৈধতা পেতে দয়া করে <b> ইস্যুর তারিখ </b> সরবরাহ করুন।",
	PROVIDE_DATE_OF_REGISTRATION_TEXT: "দুঃখিত আমরা আপনার বিশদটি বৈধতা দিতে পারি না, আপনার গাড়ির বিশদটি বৈধতা পেতে দয়া করে <b> নিবন্ধকরণের তারিখ </b> সরবরাহ করুন।",
	SELECT_DATE_OF_REGISTRATION: "নিবন্ধকরণের তারিখ নির্বাচন করুন",
	SAME_REENTERED_RC_MESSAGE: "দয়া করে নিশ্চিত হয়ে নিন",
	SAME_REENTERED_DL_MESSAGE: "পুনরায় প্রবেশ করা ডিএল নম্বর উপরে প্রদত্ত ডিএল নম্বরটির সাথে মেলে না",
	WHERE_IS_MY_ISSUE_DATE: "আমার ইস্যু তারিখ কোথায়?",
	WHERE_IS_MY_REGISTRATION_DATE: "নিবন্ধের তারিখ কোথায়?",
	EARNINGS_CREDITED_IN_ACCOUNT: "আপনার উপার্জন এই অ্যাকাউন্টে জমা দেওয়া হবে",
	INVALID_PARAMETERS: "অবৈধ পরামিতি",
	UNAUTHORIZED: "অননুমোদিত",
	INVALID_TOKEN: "অবৈধ টোকেন",
	SOME_ERROR_OCCURED_IN_OFFERRIDE: "অফারাইডে কিছু ত্রুটি ঘটেছিল",
	SELECT_VEHICLE_TYPE: "গাড়ির ধরণ নির্বাচন করুন",
	RIDE: "যাত্রা",
	NO_LOCATION_UPDATE: "কোনও অবস্থান আপডেট নেই",
	GOT_IT_TELL_US_MORE: "পেয়েছি, আরও বলুন?",
	WRITE_A_COMMENT: "একটি মন্তব্য লিখুন",
	HOW_WAS_YOUR_RIDE_WITH: "আপনার যাত্রা কেমন ছিল",
	RUDE_BEHAVIOUR: "অভদ্র আচরণ",
	LONG_WAITING_TIME: "দীর্ঘ সময় অপেক্ষা",
	DIDNT_COME_TO_PICUP_LOCATION: "পিকআপ লোকেশনে আসেনি",
	HELP_US_WITH_YOUR_REASON: "আপনার কারণ দিয়ে আমাদের সহায়তা করুন",
	MAX_CHAR_LIMIT_REACHED: "সর্বোচ্চ চরিত্রের সীমা পৌঁছেছে,",
	SHOW_ALL_OPTIONS: "সমস্ত বিকল্প দেখান",
	UPDATE_REQUIRED: "আপডেট প্রয়োজন",
	PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE: "পরিষেবা চালিয়ে যেতে অ্যাপ্লিকেশন আপডেট করুন",
	NOT_NOW: "এখন না",
	OF: "এর",
	DROP: "ড্রপ",
	PLEASE_WAIT: "অনুগ্রহপূর্বক অপেক্ষা করুন",
	SETTING_YOU_OFFLINE: "আমরা আপনাকে অফলাইন সেট করছি",
	SETTING_YOU_ONLINE: "আমরা আপনাকে অনলাইনে সেট করছি",
	SETTING_YOU_SILENT: "আমরা আপনাকে সাইলেন্ট সেট করছি",
	VIEW_BREAKDOWN: "ব্রেকডাউন দেখুন",
	APP_INFO: "অ্যাপ্লিকেশন তথ্য",
	OTHER: "অন্য",
	VEHICLE_ISSUE: "যানবাহন সমস্যা",
	FARE_UPDATED: "ভাড়া আপডেট হয়েছে",
	FREQUENT_CANCELLATIONS_WILL_LEAD_TO_LESS_RIDES: "ঘন ঘন বাতিলকরণগুলি কম রাইড এবং কম রেটিংয়ের দিকে পরিচালিত করবে",
	CONTINUE: "চালিয়ে যান",
	CONFIRM_PASSWORD: "পাসওয়ার্ড নিশ্চিত করুন",
	DEMO_MODE: "ডেমো মোড",
	PASSWORD: "পাসওয়ার্ড",
	ENTER_DEMO_MODE_PASSWORD: "ডেমো মোড পাসওয়ার্ড লিখুন",
	DEMO_MODE_DISABLED: "ডেমো মোড অক্ষম",
	ONLINE_VIA_DEMO_MODE: "অনলাইন (ডেমো)",
	MORE: "আরও",
	LESS: "কম",
	YOU_ARE_AT_PICKUP: "আপনি পিকআপ লোকেশনে আছেন",
	WAITING_FOR_CUSTOMER: "আপনি অপেক্ষা করছেন",
	CUSTOMER_NOTIFIED: "গ্রাহক বিজ্ঞপ্তি",
	I_ARRIVED: "আমি এসেছি",
	ESTIMATED_RIDE_FARE: "আনুমানিক রাইড ভাড়া:",
	PICKUP_TOO_FAR: "পিকআপ খুব দূরে",
	CUSTOMER_NOT_PICKING_CALL: "গ্রাহক কল বাছাই করছেন না",
	TRAFFIC_JAM: "ট্রাফিক জ্যাম",
	CUSTOMER_WAS_RUDE: "গ্রাহক অভদ্র ছিল",
	ALL_MESSAGES: "সমস্ত বার্তা",
	MESSAGES: "বার্তা",
	ADD_A_COMMENT: "একটি মন্তব্য যুক্ত করুন",
	POST_COMMENT: "পোস্ট মন্তব্য",
	ENTER_YOUR_COMMENT: "আপনার মন্তব্য লিখুন",
	NO_NOTIFICATIONS_RIGHT_NOW: "এখনই কোনও বিজ্ঞপ্তি নেই!",
	NO_NOTIFICATIONS_RIGHT_NOW_DESC: "যখন নতুন কোনও বিজ্ঞপ্তি আসবে তখন আমরা আপনাকে জানাব",
	ALERTS: "সতর্কতা",
	YOUR_COMMENT: "আপনার মন্তব্য",
	SHOW_MORE: "আরও দেখান",
	LOAD_OLDER_ALERTS: "পুরানো সতর্কতাগুলি লোড করুন",
	CONTEST: "প্রতিযোগিতা",
	YOUR_REFERRAL_CODE_IS_LINKED: "আপনার রেফারেল কোড লিঙ্কযুক্ত!",
	YOU_CAN_NOW_EARN_REWARDS: "আপনি এখন গ্রাহকদের উল্লেখ করার জন্য পুরষ্কার অর্জন করতে পারেন!",
	COMING_SOON: "শীঘ্রই আসছে!",
	COMING_SOON_DESCRIPTION: "আমরা আপনাকে রেফারেল প্রোগ্রামে বোর্ডে নিয়ে যাওয়ার কাজ করছি। আরও তথ্যের জন্য সতর্কতা পৃষ্ঠাটি দেখুন।",
	REFERRAL_CODE: "রেফারেল কোড",
	REFERRAL_CODE_HINT: "6-অঙ্কের রেফারেল কোড লিখুন",
	CONFIRM_REFERRAL_CODE: "রেফারেল কোড নিশ্চিত করুন",
	CONFIRM_REFERRAL_CODE_HINT: "রেফারাল কোড পুনরায় প্রবেশ করুন",
	YOUR_REFERRAL_CODE: "আপনার রেফারাল কোড",
	FIRST_REFERRAL_SUCCESSFUL: "প্রথম রেফারাল সফল! \n পুরষ্কার আনলক!",
	AWAITING_REFERRAL_RIDE: "রেফারাল রাইডের অপেক্ষায়",
	CHECK_THIS_SPACE_WHEN_YOU_GET_REFERRAL_ALERT: "আপনি যখন রেফারেল সতর্কতা পাবেন তখন এই স্থানটি পরীক্ষা করুন",
	REFERRED_CUSTOMERS: "গ্রাহকদের রেফারেন্স",
	ACTIVATED_CUSTOMERS: "সক্রিয় গ্রাহক",
	REFERRAL_CODE_LINKING: "রেফারেল কোড লিঙ্কিং",
	CONTACT_SUPPORT: "যোগাযোগ সমর্থন",
	CALL_SUPPORT: "কল সমর্থন",
	YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT: "আপনি জাত্রি সাথি সমর্থন দলকে কল করতে চলেছেন। আপনি কি এগিয়ে যেতে চান?",
	REFERRAL_ENROLMENT: "রেফারেল তালিকাভুক্তি",
	REFERRALS: "প্রচার",
	LINK_REFERRAL_CODE: "লিঙ্ক রেফারেল কোড",
	DRIVER_DETAILS: "ড্রাইভার বিবরণ",
	FOR_UPDATES_SEE_ALERTS: "আপডেটের জন্য, সতর্কতাগুলি দেখুন",
	SHARE_OPTIONS: "ভাগ বিকল্প",
	ENTER_PASSWORD: "পাসওয়ার্ড লিখুন",
	YOUR_VEHICLE: "আপনার বাহন",
	BOOKING_OPTIONS: "বুকিং অপশন",
	CONFIRM_AND_CHANGE: "পরিবর্তন নিশ্চিত করুন",
	OTP: "OTP",
	MAKE_YOURSELF_AVAILABLE_FOR : "এছাড়াও রাইড গ্রহণ করুন",
	SILENT_MODE_PROMPT : "আপনি যদি বিরক্ত হতে না চান তবে আপনি পরিবর্তে সাইলেন্ট মোডে স্যুইচ করতে পারেন",
	GO_SILENT : "চুপ করে যাও",
	TRY_SILENT_MODE : "নীরব মোড চেষ্টা করবেন?",
	RIDE_FARE : "রাইড ভাড়া" ,
	RIDE_DISTANCE : "যাত্রা দূরত্ব",
	FARE_UPDATED : "ভাড়া আপডেট হয়েছে",
	START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS : "এই দ্রুত চ্যাট পরামর্শগুলি ব্যবহার করে আপনার চ্যাট শুরু করুন",
	START_YOUR_CHAT_WITH_THE_DRIVER : "ড্রাইভারের সাথে আপনার চ্যাট শুরু করুন",
	MESSAGE : "বার্তা",
	I_AM_ON_MY_WAY : "আমি গন্তব্যের পথে",
	GETTING_DELAYED_PLEASE_WAIT : "বিলম্ব হচ্ছে, দয়া করে অপেক্ষা করুন",
	UNREACHABLE_PLEASE_CALL_BACK : "অ্যাক্সেসযোগ্য, দয়া করে ফিরে কল করুন",
	ARE_YOU_STARING : "আপনি কি শুরু করছেন?",
	PLEASE_COME_SOON : "দয়া করে শীঘ্রই আসুন",
	OK_I_WILL_WAIT : "আচ্ছা আমি অপেক্ষা করব",
	I_HAVE_ARRIVED : "আমি এসেছি",
	PLEASE_COME_FAST_I_AM_WAITING : "দয়া করে দ্রুত আসুন, আমি অপেক্ষা করছি",
	PLEASE_WAIT_I_WILL_BE_THERE : "দয়া করে অপেক্ষা করুন, আমি সেখানে থাকব",
	LOOKING_FOR_YOU_AT_PICKUP : "পিক-আপে আপনাকে খুঁজছেন",
	SILENT : "নীরব",
	GO_ONLINE : "যাওয়া!",
	GO_ONLINE_PROMPT : "আপনি বর্তমানে অফলাইনে রয়েছেন \ n n রাইডের অনুরোধগুলি পেতে, এখনই অনলাইনে যান!",
	LIVE_DASHBOARD : "লাইভ স্ট্যাটাস ড্যাশবোর্ড",
	CLICK_TO_ACCESS_YOUR_ACCOUNT : "আপনার অ্যাকাউন্ট অ্যাক্সেস করতে এখানে ক্লিক করুন",
	ADD_ALTERNATE_NUMBER : "বিকল্প নম্বর যুক্ত করুন",
	ENTER_ALTERNATE_MOBILE_NUMBER : "বিকল্প মোবাইল নম্বর লিখুন",
	EDIT_ALTERNATE_MOBILE_NUMBER : "বিকল্প মোবাইল নম্বর সম্পাদনা করুন",
	PLEASE_ENTER_A_VALID_10_DIGIT_NUMBER : "দয়া করে একটি বৈধ 10-অঙ্কের নম্বর লিখুন",
	ALTERNATE_MOBILE_NUMBER : "বিকল্প মোবাইল নম্বর",
	REMOVE : "অপসারণ",
	REMOVE_ALTERNATE_NUMBER : "বিকল্প নম্বর সরান",
	ARE_YOU_SURE_YOU_WANT_TO_REMOVE_YOUR_ALTERNATE_MOBILE_NUMBER : "আপনি কি নিশ্চিত যে আপনি আপনার বিকল্প মোবাইল নম্বরটি সরিয়ে ফেলতে চান?",
	YES_REMOVE_IT : "হ্যাঁ, এটি সরান",
	NUMBER_REMOVED_SUCCESSFULLY : "নম্বর সফলভাবে সরানো হয়েছে",
	NUMBER_ADDED_SUCCESSFULLY : "নম্বর সফলভাবে যুক্ত হয়েছে",
	NUMBER_EDITED_SUCCESSFULLY : "নম্বর সফলভাবে আপডেট হয়েছে",
	ALTERNATE_MOBILE_OTP_LIMIT_EXCEED : "ওটিপি সীমা ছাড়িয়ে গেছে, আবার নম্বর এবং ওটিপি প্রবেশ করান",
	WRONG_OTP : "বৈধ ওটিপি লিখুন দয়া করে ",
	ATTEMPTS_LEFT : " চেষ্টা বাকি",
	ATTEMPT_LEFT : " বাম চেষ্টা",
	OTP_LIMIT_EXCEEDED : "ওটিপি সীমা ছাড়িয়ে গেছে",
	OTP_LIMIT_EXCEEDED_MESSAGE : "আপনি আপনার ওটিপি সীমাতে পৌঁছেছেন। 10 মিনিটের পরে আবার চেষ্টা করুন।",
	TRY_AGAIN_LATER : "পরে আবার চেষ্টা করুন",
	NUMBER_ALREADY_EXIST_ERROR : "অন্য অ্যাকাউন্টের সাথে যুক্ত নম্বর! অন্য নম্বর ব্যবহার করুন",
	ADD_ALTERNATE_NUMBER_IN_MEANTIME : "এই প্রক্রিয়াটি 2 কার্যদিবসের সময় নিতে পারে \ n সম্পূর্ণ হতে পারে। ইতিমধ্যে, আপনি একটি বিকল্প মোবাইল নম্বর যুক্ত করুন।",
	VERIFICATION_IS_TAKING_A_BIT_LONGER : "দেখে মনে হচ্ছে আপনার যাচাইকরণটি প্রত্যাশার চেয়ে কিছুটা \ nlonger নিচ্ছে \ \ n আপনি আপনাকে সহায়তা করতে সহায়তার সাথে যোগাযোগ করতে পারেন।",
	COMPLETE_ONBOARDING : "অনবোর্ডিং সম্পূর্ণ",
	PERSON_WITH_THIS_NUMBER_ALREADY_EXISTS : "এই মোবাইল নম্বর সহ ব্যক্তি ইতিমধ্যে বিদ্যমান।",
	OTP_ : "OTP",
	MAPS: "Maps",
	Demo : "Demo",
	DELETE : "মুছে ফেলা",
	VIEW : "দেখুন",
	ISSUE_NO : "ইস্যু নং ",
	ADD_VOICE_NOTE : "ভয়েস নোট যোগ করুন",
	VOICE_NOTE_ADDED : "ভয়েস নোট যোগ করা হয়েছে",
	SUBMIT_ISSUE_DETAILS : "ইস্যু বিবরণ জমা দিন",
	IMAGE_PREVIEW : "ছবির পূর্বরূপ",
	RIDE_REPORT_ISSUE : "সমস্যা রিপোর্ট করার জন্য একটি রাইড নির্বাচন করুন",
	ADDED_IMAGES : "ছবি যোগ করা হয়েছে",
	NO_IMAGES_ADDED : "কোন ছবি যোগ করা হয়নি",
	ASK_DETAILS_MESSAGE : "অনুগ্রহ করে আরো কিছু বিস্তারিত জানান। আপনি আরও ভালভাবে বিস্তারিত জানাতে ছবি বা ভয়েস নোট পাঠাতে পারেন।",
	ASK_DETAILS_MESSAGE_REVERSED : "হারিয়ে যাওয়া আইটেম সম্পর্কে আরো বিস্তারিত শেয়ার করুন. আপনি আরও ভালভাবে বিস্তারিত জানাতে ছবি বা ভয়েস নোট পাঠাতে পারেন।",
	SELECT_OPTION : "আপনি যদি এইগুলির কোনটির মুখোমুখি হন তবে দয়া করে আমাদের বলুন",
	SELECT_OPTION_REVERSED : "আপনি কিভাবে এই সমস্যা সমাধান করতে চান?",
	ISSUE_SUBMITTED_MESSAGE : "বিস্তারিত প্রাপ্ত! আপনার সমস্যা সমাধানের জন্য আমাদের দল আপনাকে 24 ঘন্টার মধ্যে কল করবে।",
	I_DONT_KNOW_WHICH_RIDE : "আমি জানি না কোন রাইড",
	REPORT_ISSUE_CHAT_PLACEHOLDER : "আপনার সমস্যাটি বর্ণনা. আমরা 24 ঘন্টার মধ্যে এটি সমাধান করার চেষ্টা করব।",
	PLEASE_ASK_THE_CUSTOMER_FOR_THE_OTP : "অনুগ্রহ করে গ্রাহককে OTP-এর জন্য জিজ্ঞাসা করুন",
	ADDED_VOICE_NOTE : "ভয়েস নোট যোগ করা হয়েছে",
	NO_VOICE_NOTE_ADDED : "কোন ভয়েস নোট যোগ করা হয়নি",
	CALL_CUSTOMER_TITLE : "গ্রাহককে কল করবেন?",
	CALL_CUSTOMER_DESCRIPTION : "আপনি গ্রাহককে একটি কল করতে চলেছেন৷ আপনি কি এগিয়ে যেতে চান?",
	PLACE_CALL : "কল করুন",
	ADD_IMAGE : "ছবি যোগ কর",
	ADD_ANOTHER : "আরেকটি যোগ করুন",
	IMAGES_ADDED : "ছবি যোগ করা হয়েছে",
	ISSUE_SUBMITTED_TEXT : "অপেক্ষা কর! আমরা আপনার সমস্যা সমাধানে কাজ করছি",
	CHOOSE_AN_OPTION : "চালিয়ে যাওয়ার জন্য একটি বিকল্প বেছে নিন",
	IMAGE_ADDED : "ইমেজ যোগ করা হয়েছে",
	DONE : "সম্পন্ন",
	RECORD_VOICE_NOTE : "ভয়েস নোট রেকর্ড করুন",
	HELP_AND_SUPPORT : "সাহায্য সহযোগীতা",
	MORE_OPTIONS : "আরও বিকল্প",
	ONGOING_ISSUES : "চলমান সমস্যা",
	RESOLVED_ISSUES : "সমাধান করা সমস্যা",
	RESOLVED_ISSUE : "সমাধান করা সমস্যা",
	ONGOING_ISSUE : "চলমান সমস্যা",
	LOST_ITEM : "হারিয়ে যাওয়া আইটেম",
	RIDE_RELATED_ISSUE : "রাইড সম্পর্কিত সমস্যা",
	APP_RELATED_ISSUE : "অ্যাপ সম্পর্কিত সমস্যা",
	FARE_RELATED_ISSUE : "ভাড়া সম্পর্কিত সমস্যা",
	MAX_IMAGES : "সর্বোচ্চ ৩টি ছবি আপলোড করা যাবে",
	ISSUE_NUMBER : "ইস্যু নং  ",
	REMOVE_ISSUE : "সমস্যা সরান" ,
	CALL_SUPPORT_NUMBER : "যোগাযোগ সমর্থন",
	YEARS_AGO : " অনেক বছর আগে",
	MONTHS_AGO : " মাস কতক পূর্বে",
	DAYS_AGO : " দিন আগে",
	HOURS_AGO : " ঘন্টা আগে",
	MIN_AGO : " মিনিট আগে",
	SEC_AGO : " সেকেন্ড আগে",
	LOADING : "লোড হচ্ছে",
	APP_RELATED : "অ্যাপ সম্পর্কিত",
	FARE : "ভাড়া সম্পর্কিত",
	RIDE_RELATED : "রাইড সম্পর্কিত",
	LOST_AND_FOUND : "হারানো এবং প্রাপ্তি",
	REPORT_LOST_ITEM : "হারানো আইটেম রিপোর্ট করুন",
	SELECT_YOUR_GENDER : "আপনার লিঙ্গ নির্বাচন",
	FEMALE : "মহিলা",
	MALE : "পুরুষ",
	PREFER_NOT_TO_SAY : "বলতে না পছন্দ",
	GENDER : "লিঙ্গ",
	SET_NOW : "এখন সেট করুন",
	COMPLETE_YOUR_PROFILE_AND_FIND_MORE_RIDES : "আপনার প্রোফাইল সম্পূর্ণ করুন এবং আরো রাইড খুঁজুন!",
	UPDATE_NOW : "এখন হালনাগাদ করুন",
	CONFIRM : "নিশ্চিত করুন",
	GENDER_UPDATED : "লিঙ্গ আপডেট করা হয়েছে",
	COMPLAINTS_GRIEVANCES : "অভিযোগ এবং অভিযোগ",
	COMPLAINTS_DESCRIPTION : "কোনো অভিযোগের জন্য, অনুগ্রহ করে আমাদের সাথে <u>yatrisathi.support@wb.gov.in</u> এ যোগাযোগ করুন;",
	COMPLAINTS_DESCRIPTION_ADDITIONAL : "অভিযোগের প্রতিকারের জন্য, অনুগ্রহ করে আমাদের <u>গোপনীয়তা নীতি</u> পড়ুন",
	REGISTERED_ADDRESS : "নিবন্ধিত ঠিকানা",
	REGISTERED_ADDRESS_DESCRIPTION : "স্ট্যালিয়ন বিজনেস সেন্টার, নং 444, 3য় এবং 4র্থ তলা, 18 তম প্রধান, 6 তম ব্লক, কোরামঙ্গলা, বেঙ্গালুরু, কর্ণাটক- 560095, ভারত",
	ZONE_CANCEL_TEXT_DROP : "আপনার গ্রাহক সম্ভবত সময়মতো মেট্রো স্টেশনে পৌঁছানোর জন্য তাড়াহুড়ো করছেন! \n আমরা আপনাকে বাতিল না করার জন্য অনুরোধ করছি।",
	ZONE_CANCEL_TEXT_PICKUP : "আপনার গ্রাহক সম্ভবত তাদের গন্তব্যে পৌঁছানোর জন্য তাড়াহুড়ো করছেন। \n আমরা আপনাকে বাতিল না করার জন্য অনুরোধ করছি।",
	RANKINGS : "র‍্যাঙ্কিং",
	GETTING_THE_LEADERBOARD_READY : "লিডারবোর্ড তৈরি করা হচ্ছে!",
	PLEASE_WAIT_WHILE_WE_UPDATE_THE_DETAILS : "আমরা বিস্তারিত আপডেট করা পর্যন্ত অপেক্ষা করুন",
	LAST_UPDATED : "সর্বশেষ আপডেট: ",
	CONGRATULATIONS_YOU_ARE_RANK : "অভিনন্দন! আপনার র্যাঙ্ক হল ",
	YOU : " (আপনি)",
	DAILY : "দৈনিক",
	WEEKLY : "সাপ্তাহিক",
	ACCEPT_RIDES_TO_ENTER_RANKINGS : "র‌্যাঙ্কিং এ প্রবেশ করতে রাইড গ্রহণ করুন!",
	OTP_HAS_BEEN_RESENT : "ওটিপি আবার পাঠানো হয়েছে",
	OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_RESENDING_OTP : "OTP ইনপুট সীমা পৌঁছেছে, অনুগ্রহ করে আবার OTP পাঠানোর চেষ্টা করুন",
	OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER : "OTP পুনরায় পাঠানোর সীমা পৌঁছে গেছে, অনুগ্রহ করে পরে আবার চেষ্টা করুন",
	OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN : "OTP পৃষ্ঠার মেয়াদ শেষ হয়ে গেছে, অনুগ্রহ করে আবার OTP অনুরোধ করুন",
	SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN : "কিছু প্রযুক্তিগত সমস্যা হয়েছে, আবার চেষ্টা করুন",
	INVALID_REFERRAL_CODE : "অবৈধ রেফারেল কোড",
	ISSUE_REMOVED_SUCCESSFULLY : "সমস্যা সফলভাবে সমাধান করা হয়েছে",
	OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER : "OTP প্রবেশের সময়সীমা পৌঁছে গেছে, অনুগ্রহ করে পরে আবার চেষ্টা করুন",
	TOO_MANY_ATTEMPTS_PLEASE_TRY_AGAIN_LATER : "আপনি অনেকগুলি অবৈধ প্রচেষ্টা করেছেন, অনুগ্রহ করে পরে আবার চেষ্টা করুন৷",
	INVALID_REFERRAL_NUMBER : "অবৈধ রেফারেল নম্বর",
	SOMETHING_WENT_WRONG_TRY_AGAIN_LATER : "কিছু প্রযুক্তিগত সমস্যা হয়েছে, অনুগ্রহ করে পরে আবার চেষ্টা করুন",
	WAIT_TIME : "অপেক্ষার সময়",
	WAIT_TIMER : "টাইমার অপেক্ষা করুন",
  HOW_LONG_WAITED_FOR_PICKUP : "আপনি পিকআপে কতক্ষণ অপেক্ষা করেছেন তা দেখায়।",
  CUSTOMER_WILL_PAY_FOR_EVERY_MINUTE : "গ্রাহক ₹1.5\nপ্রথম 3 মিনিটের পর প্রতি মিনিট অপেক্ষার জন্য প্রদান করবেন",
	OTHERS : "অন্যান্য",
	ENTER_SECOND_SIM_NUMBER : "দ্বিতীয় সিম নম্বর লিখুন",
	ALTERNATE_NUMBER : "বিকল্প নম্বর",
	ALTERNATE_NUMBER_CANNOT_BE_ADDED : "বিকল্প নম্বর যুক্ত করা যাবে না",
	SELECT_THE_LANGUAGES_YOU_CAN_SPEAK : "আপনি কথা বলতে পারেন এমন ভাষা নির্বাচন করুন",
	LIMIT_EXCEEDED_FOR_ALTERNATE_NUMBER : "বিকল্প সংখ্যার জন্য সীমা অতিক্রম করেছে৷",
  OTP_RESENT : "OTP আবার পাঠান",
  OTP_RESEND_LIMIT_EXCEEDED : "ওটিপি পুনরায় পাঠানোর সীমা অতিক্রম করেছে৷",
	SEDAN : "সেডান",
  SUV : "SUV",
  HATCHBACK : "হ্যাচব্যাক",
  AUTO_RICKSHAW : "অটো রিক্সা",
  TAXI : "নন-এসি ট্যাক্সি",
  TAXI_PLUS : "এসি ট্যাক্সি",
	MY_PROFILE : "আমার প্রোফাইল",
  SETTINGS : "সেটিংস",
  REG_NUMBER : "রেজিস্ট্রেশন নম্বর",
  TYPE : "টাইপ",
  MODEL_NAME : "মডেলের নাম",
  COLOUR : "রঙ",
  BADGES: "ব্যাজ",
  FARE : "ভাড়া সম্পর্কিত",
  RIDE_RELATED : "রাইড সম্পর্কিত",
  LOST_AND_FOUND : "হারানো এবং প্রাপ্তি",
  REPORT_LOST_ITEM : "হারানো আইটেম রিপোর্ট করুন",
  COMPLAINTS_GRIEVANCES : "অভিযোগ এবং অভিযোগ",
  COMPLAINTS_DESCRIPTION : "কোনো অভিযোগের জন্য, অনুগ্রহ করে আমাদের সাথে <u>yatrisathi.support@wb.gov.in</u> এ যোগাযোগ করুন;",
  COMPLAINTS_DESCRIPTION_ADDITIONAL : "অভিযোগের প্রতিকারের জন্য, অনুগ্রহ করে আমাদের <u>গোপনীয়তা নীতি</u> পড়ুন",
  REGISTERED_ADDRESS : "নিবন্ধিত ঠিকানা",
  REGISTERED_ADDRESS_DESCRIPTION : "Stallion Business Centre, No. 444, 3rd & 4th Floor, 18th Main, 6th Block, Koramangala, Bengaluru, Karnataka- 560095, India",
  CALL_CUSTOMER_SUPPORT : "কাস্টমার সাপোর্টে কল করুন",
  EDIT_RC : "সম্পাদনা করুন RC",
  DELETE_RC : "মুছে ফেলা RC",
  DEACTIVATE_RC : "নিষ্ক্রিয় করুন RC",
  ACTIVATE_RC : "সক্রিয় করুন RC",
  ACTIVE_RC_ON_ANOTHER_DRIVER : " অন্য ড্রাইভার অ্যাকাউন্টে সক্রিয়!",
  CALL_DRIVER_OR_CONTACT_SUPPORT : "RC নিষ্ক্রিয় করতে ড্রাইভারকে কল করুন বা ড্রাইভারের সাথে যোগাযোগ করা সম্ভব না হলে সহায়তার সাথে যোগাযোগ করুন",
  CALL_DRIVER : "ড্রাইভারকে কল করুন",
  SKIP : "এড়িয়ে যান",
  ACTIVE_STR : "সক্রিয়",
  INACTIVE_RC : "নিষ্ক্রিয়",
  CONFIRMATION_FOR_DELETING_RC : "আপনি কি নিশ্চিত যে আপনি আপনার RC মুছে ফেলতে চান?",
  CONFIRMATION_FOR_DEACTIVATING_RC : "আপনি কি নিশ্চিত যে আপনি আপনার RC নিষ্ক্রিয় করতে চান?- ",
  CONFIRMATION_FOR_ACTIVATING_RC : "আপনি কি নিশ্চিত আপনি RC সক্রিয় করতে চান?- ",
  YES_DELETE : "হ্যাঁ, মুছুন",
  ADD_NEW_RC : "যোগ করুন RC",
  CONNECT_CALL_ANONYMOUSLY: "আমরা আপনাকে ড্রাইভারের সাথে বেনামে সংযোগ করার চেষ্টা করব RC নিষ্ক্রিয় করার অনুরোধ করার আগে দয়া করে নিজের পরিচয় দিন।",
  YES_ACTIVATE : "হ্যাঁ, সক্রিয় করুন",
  YES_DEACTIVATE : "হ্যাঁ, নিষ্ক্রিয় করুন",
  THIS_WILL_DEACTIVATE_CURRENTLY_ACTIVE_RC : "এটি আপনার বর্তমানে সক্রিয় RC নিষ্ক্রিয় করবে।",
  REMOVED : "সরানো হয়েছে",
  IS_ACTIVE_NOW : " এখন সক্রিয়.",
  DEACTIVATED : "নিষ্ক্রিয়",
  LANGUAGE_UPDATED : "ভাষা আপডেট করা হয়েছে",
  SINGLE_RC_CANNOT_BE_DELETED : "একক আরসি মুছে ফেলা যাবে না",
	CANCELLATION_RATE : "বাতিল করার হার",
  RIDES_CANCELLED : "বাতিল করা রাইডের সংখ্যা",
  EARNINGS_MISSED : "মিসড আর্নিংস",
  SUMMARY : "সারাংশ",
  NAMMA_BONUS  : "নাম্মা বোনাস",
  TRIPS_COMPLETED : "সমাপ্ত ভ্রমণ",
  LATE_NIGHT_TRIPS  : "লেট নাইট ট্রিপ",
  ABOUT_ME  : "আমার সম্পর্কে",
  ABOUT_VEHICLE : "বাহন সম্পর্কে",
  ADD : "যোগ করুন",
  YEARS_OLD  : "বছর বয়সী",
  HOMETOWN  : "হোম টাউন",
	MISSED_OPPORTUNITY : "সুযোগ মিস করেছে",
	HOW_OLD_IS_YOUR_VEHICLE : "আপনার গাড়ির বয়স কত (বছরে)?",
	ENTER_NAME_OF_VEHICLE : "আপনার গাড়ির নাম লিখুন",
	NEW_ : "নতুন",
	TODAY : "আজ",
	TOTAL_MONEY_COLLECTED : "মোট অর্থ সংগৃহীত",
	FARE_EARNED_OF_THE_DAY : "দিনের জন্য অর্জিত ভাড়া",
	GST_PLUS_PAYABLE : "GST + ফি প্রদেয়",
	TO_CONTINUE_USING_YATRI_SATHI : "Yatri Sathi ব্যবহার চালিয়ে যেতে, অনুগ্রহ করে আপনার অর্থপ্রদান সম্পূর্ণ করুন",
	PAY : "বেতন",
	LATER : "পরে",
	GREAT_JOB : "দারূন কাজ!",
	FEE_BREAKUP : "ফি ব্রেকআপ",
	YATRI_SATHI_FEE_PAYABLE_FOR_DATE : "Yatri Sathi ফি জন্য প্রদেয়",
	FEE_CORRESPONDING_TO_THE_DISTANCE : "প্রতি ট্রিপে ভ্রমণ করা দূরত্বের সাথে সম্পর্কিত একটি ফি, নীচে দেখানো হিসাবে গণনা করা হবে।",
	PLATFORM_FEE : "প্ল্যাটফর্ম ফি",
	GST  : "GST",
	TOTAL_PAYABLE : "মোট প্রদেয়",
	GOT_IT : "বুঝেছি",
	VIEW_DETAILS : "বিস্তারিত দেখুন",
	PAYMENT_SUCCESSFUL : "পেমেন্ট সফল!",
	PAYMENT_PENDING : "পেমেন্ট মুলতুবি",
	PAYMENT_FAILED : "পেমেন্ট ব্যর্থ হয়েছে",
	PAYMENT_PENDING_DESC : "চিন্তা করবেন না, আপনি এখনও দিনের জন্য রাইডগুলি চালিয়ে যেতে পারেন!",
	PAYMENT_FAILED_DESC : "আপনি আবার অর্থপ্রদানের চেষ্টা করতে পারেন, অথবা আপনার নিকটস্থ Yatri Sathi বুথে অর্থপ্রদান করতে পারেন",
	WE_WILL_NOTIFY_WHEN_PAYMENT_SUCCESS : "আপনার পেমেন্ট সফল হলে আমরা অবহিত করব",
	CONTINUE_TAKING_RIDES : "রাইড করা চালিয়ে যান",
	YOUR_PREVIOUS_PAYMENT_IS_PENDING : "আপনার পূর্বের অর্থপ্রদান এখনও বাকি আছে",
	GOVERMENT_CHARGES : "সরকারি চার্জ",
	OKAY : "ঠিক আছে",
	NO_PAYMENT_HISTORY_AVAILABLE : "কোন অর্থপ্রদানের ইতিহাস উপলব্ধ নেই",
	YOU_DONT_HAVEANY_PAYMENTS : "আপনি এখনও কোনো অর্থপ্রদান করেননি",
	ENTER_AADHAAR_NUMBER : "আধার নম্বর/ইউআইডি লিখুন",
	ENTER_AADHAAR_OTP_ : "আধার ওটিপি লিখুন",
	AADHAAR_LINKING_REQUIRED : "আধার লিঙ্ক করা আবশ্যক",
	AADHAAR_LINKING_REQUIRED_DESCRIPTION : "যাত্রী সাথীর জন্য গাড়ি চালানো শুরু করতে, দয়া করে \n আপনার আধার আইডি লিঙ্ক করুন",
	BY_CLICKING_THIS_YOU_WILL_BE_AGREEING_TO_OUR_TC : "চালিয়ে যান ক্লিক করে, আপনি আমাদের সাথে সম্মত হন ",
	TERMS_AND_CONDITIONS_SHORT : "T&C",
	TC_TAIL : "",
	OTP_SENT_TO_AADHAAR_NUMBER: "আপনার আধারের সাথে লিঙ্ক করা মোবাইল নম্বরে OTP পাঠানো হয়েছে",
	ENTER_SIX_DIGIT_OTP : "ছয় সংখ্যার ওটিপি লিখুন",
	LINK_AADHAAR_ID : "আধার আইডি লিঙ্ক করুন",
	NO_MOBILE_NUMBER_REGISTERED : "আধার নম্বরের সাথে নিবন্ধিত একটি মোবাইল নম্বর নেই।",
	EXCEED_OTP_GENERATION_LIMIT : "ওটিপি তৈরির সর্বোচ্চ সীমা ছাড়িয়ে গেছে। কিছু সময়ের মধ্যে আবার চেষ্টা করুন.",
	AADHAAR_NUMBER_NOT_EXIST : "আধার নম্বর নেই।",
	INVALID_OTP : "অবৈধ OTP",
	NO_SHARE_CODE : "কোন শেয়ার কোড প্রদান করা হয় না",
	WRONG_SHARE_CODE : "ভুল শেয়ার কোড",
	INVALID_SHARE_CODE : "অবৈধ শেয়ার কোড। দৈর্ঘ্য 4 হওয়া উচিত এবং শুধুমাত্র সংখ্যা থাকা উচিত।",
	SESSION_EXPIRED : "সময় মেয়াদ শেষ. আবার প্রক্রিয়া শুরু করুন.",
	OTP_ATTEMPT_EXCEEDED : "OTP প্রয়াস অতিক্রম করেছে৷ আবার প্রক্রিয়া শুরু করুন",
	UPSTREAM_INTERNAL_SERVER_ERROR : "আপস্ট্রিম উৎস/সরকারি উৎস অভ্যন্তরীণ সার্ভার ত্রুটি। আবার প্রক্রিয়া শুরু করুন.",
	TRANSACTION_ALREADY_COMPLETED : "লেনদেন ইতিমধ্যে সম্পন্ন হয়েছে. এই লেনদেনে আর কাজ করা যাবে না.",
	GOTO_YOUR_NEAREST_BOOTH : "আপনার আধার যাচাই করার জন্য অনুগ্রহ করে আপনার নিকটস্থ বুথে যোগাযোগ করুন",
	AADHAAR_ALREADY_LINKED : "আধার ইতিমধ্যেই লিঙ্ক করা হয়েছে",
	OPTIONAL : " (ঐচ্ছিক)",
	DOWNLOAD_STATEMENT : "বিবৃতি ডাউনলোড করুন",
	SELECT_A_DATE_RANGE : "বিবৃতিটি ডাউনলোড করতে একটি তারিখের সীমা নির্বাচন করুন",
	FEE_PAYMENT_HISTORY : "ফি প্রদানের ইতিহাস",
	LANGUAGES_SPOKEN : "কথিত ভাষা",
  	VIEW_PAYMENT_HISTORY : "পেমেন্ট ইতিহাস দেখুন",
	RIDE_TYPE : "রাইড টাইপ",
	PLACE_CALL_REQUEST : "স্থান কল অনুরোধ",
	RC_STATUS : "আরসি স্ট্যাটাস",
	RATED_BY_USERS1 : "",
	RATED_BY_USERS2 : "ব্যবহারকারী দ্বারা রেট",
	MONTHS : "মাস",
	ENTER_AADHAAR_DETAILS : "আধার বিবরণ লিখুন",
	CALL_REQUEST_HAS_BEEN_PLACED : "আপনার কলের অনুরোধ করা হয়েছে",
	RC_ADDED_SUCCESSFULLY : "নিবন্ধন শংসাপত্র সফলভাবে যোগ করা হয়েছে",
	OFFER_APPLIED : "অফার প্রযোজ্য",
	YOUR_EARNINGS : "আপনার উপার্জন",
	NUMBER_OF_RIDES : "রাইডের সংখ্যা",
	FARE_BREAKUP : "ফেয়ার ব্রেকআপ",
	MY_PLAN : "আমার পরিকল্পনা",
	YOUR_DUES : "আপনার পাওনা",
	YOUR_DUES_DESCRIPTION : "আপনি আপনার বকেয়া পরিশোধ করার জন্য একটি অটোপে সেট আপ করেছেন। আমরা স্বয়ংক্রিয়ভাবে নিশ্চিত করার চেষ্টা করব যে আপনার বকেয়া সবসময় সময়মতো পরিশোধ করা হয়।",
	CURRENT_DUES : "বর্তমান পাওনা",
	YOUR_LIMIT : "আপনার সীমা",
	DUE_DETAILS : "প্রাপ্য বিবরণ",
	TRIP_DATE : "ভ্রমণের তারিখ",
	AMOUNT : "পরিমাণ",
	VIEW_DUE_DETAILS : "নির্দিষ্ট বিবরণ দেখুন",
	SETUP_AUTOPAY : "অটোপে সেটআপ করুন",
	CURRENT_PLAN : "বর্তমান পরিকল্পনা",
	ALTERNATE_PLAN : "বিকল্প পরিকল্পনা",
	AUTOPAY_DETAILS : "স্বয়ংক্রিয় অর্থপ্রদানের বিবরণ",
	CANCEL_AUTOPAY_STR : "স্বয়ংক্রিয় অর্থপ্রদান বাতিল করুন",
	WE_MIGHT_BE_LOST : "ওহ! আমরা হারিয়ে যেতে পারি",
	EXEPERIENCING_ERROR : "ত্রুটির সম্মুখীন",
	ENJOY_THESE_BENEFITS : "এই সুবিধাগুলি উপভোগ করুন",
	CHOOSE_YOUR_PLAN : "এখন একটি পরিকল্পনা চয়ন করুন!",
	SKIP_FOR_NOW : "এখন জন্য লাফালাফি",
	NAMMAYATRI_PLANS  : "নম্মা যাত্রী পরিকল্পনা",
	SEVEN_DAY_FREE_TRIAL_ACTIVATED : "7-দিনের বিনামূল্যে ট্রায়াল সক্রিয়!",
	TAKE_UNLIMITED_RIDES_FOR_THE_NEXT_SEVEN_DAYS : "প্রথম 7 দিনের জন্য সীমাহীন রাইড নিন",
	EVERY_RIDE_AT_ZERO_COMMISSION : "জিরো কমিশনে প্রতিটি রাইড!",
	EARN_UPTO_PER_DAY : "প্রতিদিন ₹2500 পর্যন্ত উপার্জন করুন!",
	HOW_THIS_WORKS : "কিভাবে এই কাজ করে",
	SIGN_UP_FOR_AUTOPAY_BY_PAYING_JUST : "মাত্র ₹1 দিয়ে অটোপে-এর জন্য সাইন আপ করুন",
    GET_REMINDED_ABOUT_YOUR_PLAN_SETUP : "আপনার প্ল্যান সেটআপ সম্পর্কে মনে করিয়ে দিন",
    FREE_TRIAL_REMINDER : "দিন 5: বিনামূল্যে ট্রায়াল অনুস্মারক",
    PLAN_STARTS : "দিন 7: পরিকল্পনা শুরু",
    EASY_AUTOMATIC_PAYMENTS_START : "সহজ, স্বয়ংক্রিয় অর্থপ্রদান শুরু হয়",
	FREE_UNTIL : " বিনামূল্যে পর্যন্ত",
	PER_RIDE : "প্রতি যাত্রায়",
	PER_DAY : "প্রতিদিন",
	OFFER : "অফার",
    OFFERS : "অফার",
	YOU_ARE_ON_THE_FREE_TRIAL : "আপনি বিনামূল্যে ট্রায়াল আছে",
	SETUP_AUTOPAY_BEFORE_THE_TRAIL_PERIOD_EXPIRES : "ট্রায়ালের মেয়াদ শেষ হওয়ার আগে অটোপে সেটআপ করুন",
	GET_FREE_TRAIL_UNTIL : "পর্যন্ত বিনামূল্যে ট্রায়াল পান",
	CLEAR_DUES : "ক্লিয়ার বকেয়া",
	PAYMENT_PENDING_ALERT : "⚠️ পেমেন্ট বাকি আছে! ⚠️",
	PAYMENT_PENDING_ALERT_DESC : "নম্মা যাত্রীতে রাইড চালিয়ে যেতে, আপনার পেমেন্ট বকেয়া পরিশোধ করুন",
	LOW_ACCOUNT_BALANCE : "কম অ্যাকাউন্ট ব্যালেন্স",
	LOW_ACCOUNT_BALANCE_DESC : "আপনার ব্যাঙ্ক অ্যাকাউন্ট ব্যালেন্স কম। নিরবচ্ছিন্ন রাইড উপভোগ করতে টাকা যোগ করুন।",
	OKAY_GOT_IT : "ঠিক আছে, বুঝেছি",
	LIMITED_TIME_OFFER : "আপনার জন্য সীমিত সময়ের অফার!",
	JOIN_NOW : "এখনই যোগ দিন",
	AUTOMATIC_PAYMENTS_WILL_APPEAR_HERE : "স্বয়ংক্রিয় অর্থপ্রদান এখানে প্রদর্শিত হবে",
	MANUAL_PAYMENTS : "ম্যানুয়াল পেমেন্ট",
	MANUAL_PAYMENTS_WILL_APPEAR_HERE : "ম্যানুয়াল পেমেন্ট এখানে প্রদর্শিত হবে",
	NO_AUTOMATIC_PAYMENTS_DESC : "আপনার অটোপেই ইতিহাস এখানে প্রদর্শিত হবে একবার আপনি একই জন্য চার্জ করা হলে",
	NO_MANUAL_PAYMENTS_DESC : "বকেয়া পরিশোধের জন্য আপনার অর্থপ্রদানের ইতিহাস এখানে প্রদর্শিত হবে, যদি থাকে।",
	PAYMENT_HISTORY : "পেমেন্ট ইতিহাস",
	PLANS : "যোগ দিন",
  	PLAN : "পরিকল্পনা",
  	DAY : "দিন",
	TAP_A_PLAN_TO_VIEW_DETAILS: "বিস্তারিত দেখতে একটি পরিকল্পনা আলতো চাপুন",
	HOW_IT_WORKS : "এটি কিভাবে কাজ করে?",
	ZERO_COMMISION : "শূন্য কমিশন",
	EARN_TODAY_PAY_TOMORROW : "আজই উপার্জন করুন, আগামীকাল অর্থ প্রদান করুন",
	PAY_ONLY_IF_YOU_TAKE_RIDES : "শুধুমাত্র আপনি যদি রাইড করেন তবেই অর্থ প্রদান করুন",
	MANAGE_PLAN : "পরিকল্পনা পরিচালনা করুন",
	VIEW_AUTOPAY_DETAILS : "স্বয়ংক্রিয় অর্থপ্রদানের বিবরণ দেখুন",
	SWITCH_AND_SAVE : "সুইচ এবং সেভ করুন",
	SWITCH_AND_SAVE_DESC : "আপনি আজ 7টির বেশি রাইড সম্পূর্ণ করেছেন। দৈনিক আনলিমিটেড প্ল্যানে স্যুইচ করে ₹10 পর্যন্ত সঞ্চয় করুন",
	SWITCH_NOW : "এখনই পাল্টান",
	PAYMENT_MODE_CHANGED_TO_MANUAL : "পেমেন্ট মোড ম্যানুয়াল এ পরিবর্তিত হয়েছে",
	PAYMENT_MODE_CHANGED_TO_MANUAL_DESC : "আপনি আপনার UPI স্বয়ংক্রিয় অর্থপ্রদান বিরাম দিয়েছেন। আপনি আপনার বকেয়া ম্যানুয়ালি সাফ করতে পারেন।",
	AUTOPAY_PAYMENTS : "অটোপে পেমেন্ট",
	TRANSACTION_ON : "লেনদেন চালু",
	SUCCESS: "সফল",
	DEBITED_ON : "পেইড অন",
	RIDES_TAKEN_ON : "রাইড নেওয়া হয়েছে",
	JOIN_PLAN : "প্ল্যানে যোগদান করুন",
	JOIN_NAMMAA_YATRI : "নম্মা যাত্রীতে যোগ দিন",
	CANCEL_AUTOPAY_AND_PAY_MANUALLY : "স্বয়ংক্রিয় অর্থপ্রদান বাতিল করুন এবং ম্যানুয়ালি অর্থ প্রদান করুন",
	PLAN_ACTIVATED_SUCCESSFULLY : "প্ল্যান সফলভাবে সক্রিয় হয়েছে",
	DUES_CLEARED_SUCCESSFULLY : "বকেয়া সফলভাবে সাফ হয়েছে",
	NOT_PLANNING_TO_TAKE_RIDES : "রাইড করার পরিকল্পনা করছেন না?",
	RETRY_PAYMENT_STR : "পুনরায় অর্থপ্রদানের চেষ্টা করুন",
	PAUSE_AUTOPAY_STR : "অটোপে বিরাম দিন",
	SETUP_AUTOPAY_STR : "অটোপে আবার শুরু করুন",
  	VIEW_RIDE_DETAILS : "রাইডের বিবরণ দেখুন",
  	ACCOUNT : "অ্যাকাউন্ট",
	AUTOPAY_IS_NOT_ENABLED_YET : "অটোপে এখনো সক্ষম করা হয়নি!",
	ENABLE_AUTOPAY_DESC : "ঝামেলা-মুক্ত অর্থপ্রদান শুরু করতে এখনই স্বতঃপে সক্ষম করুন!",
	ENABLE_AUTOPAY_NOW : "এখনই স্বতঃপে সক্ষম করুন",
	AUTOPAY_SETUP_PENDING_STR : "অটোপে সেটআপ মুলতুবি আছে!",
  	AUTOPAY_PENDING_DESC_STR : "আপনার অর্থপ্রদান প্রক্রিয়া করা হচ্ছে। একটি আপডেট হলে আমরা আপনাকে জানাব।অপেক্ষা করুন বা আবার পেমেন্ট করার চেষ্টা করুন। অতিরিক্ত অর্থ ফেরত দেওয়া হবে।",
  	REFRESH_STR : "রিফ্রেশ করুন",
	TRANSACTION_DETAILS : "লেনদেনের বিবরণ",
	RIDE_DETAILS : "রাইডের বিবরণ",
	NAMMA_YATRI_PLANS : "আমাদের যাত্রী পরিকল্পনা",
	SWITCH_TO : "এতে পাল্টান {}",
	PLEASE_TRY_AGAIN : "অনুগ্রহপূর্বক আবার চেষ্টা করুন",
	PLEASE_TRY_AGAIN : "অনুগ্রহ করে আবার চেষ্টা করুন",
	PLAN_NOT_FOUND : "প্ল্যান পাওয়া যায়নি",
	MANDATE_NOT_FOUND : "ম্যান্ডেট পাওয়া যায়নি",
	ACTIVE_MANDATE_EXISTS : "সক্রিয় আদেশ ইতিমধ্যেই বিদ্যমান",
	NO_ACTIVE_MANDATE_EXIST : "কোন সক্রিয় আদেশ বিদ্যমান নেই",
	NO_PLAN_FOR_DRIVER : "কোন পরিকল্পনা পাওয়া যায়নি",
	INVALID_PAYMENT_MODE : "অবৈধ পেমেন্ট মোড",
	INVALID_AUTO_PAY_STATUS : "অবৈধ স্বতঃপ্রদান স্থিতি",
	MAX_AMOUNT : "সর্বোচ্চ পরিমাণ",
	FREQUENCY: "ফ্রিকোয়েন্সি",
	STATRED_ON : "শুরু হয়েছে",
	EXPIRES_ON : "মেয়াদ শেষ হবে",
	SWITCHED_PLAN : "সুইচড প্ল্যান",
	RESUME_AUTOPAY : "পুনরায় স্বতঃপ্রদান শুরু হয়েছে",
	PAYMENT_CANCELLED : "আপনি আপনার UPI অটোপে বাতিল করেছেন। আপনি আপনার বকেয়া ম্যানুয়ালি সাফ করতে পারেন",
	UPI_AUTOPAY_S : "UPI অটোপে",
	MANUAL_PAYMENT_STR : "ম্যানুয়াল পেমেন্ট",
	DAILY_UNLIMITED : "দৈনিক সীমাহীন",
    DAILY_PER_RIDE : "প্রতি যাত্রায় প্রতিদিন",
    DAILY_UNLIMITED_PLAN_DESC : "প্রতিদিন সীমাহীন রাইড উপভোগ করুন",
    DAILY_PER_RIDE_PLAN_DESC : "প্রতিদিন সর্বোচ্চ ₹35 পর্যন্ত",
	PAY_TO_JOIN_THIS_PLAN : "প্ল্যানে যোগ দিতে ₹1 পে করুন",
	OFFERS_NOT_APPLICABLE : "সম্পূর্ণ না হলে অফার প্রযোজ্য নয়",
	PAUSED_STR : "বিরতি দেওয়া হয়েছে",
	PENDING_STR : "বিচারাধীন",
	PLAN_SWITCHED_TO : "পরিকল্পনা স্যুইচ করা",
	SWITCH_PLAN_STR : "স্যুইচ প্ল্যান?",
	OFFERS_APPLICABLE_ON_DAILY_UNLIMITED : "দ্রষ্টব্য: অফারগুলি শুধুমাত্র ডেইলি আনলিমিটেড প্ল্যানে প্রযোজ্য",
	DAILY_UNLIMITED_OFFER_NOT_AVAILABLE : "দ্রষ্টব্য: প্রতিদিনের সীমাহীন অফারগুলি এই পরিকল্পনায় প্রযোজ্য নয়!" , 
	NO_RIDES_NO_CHARGE : "আপনি যদি রাইড করেন তবেই অর্থ প্রদান করুন",
	GET_SPECIAL_OFFERS : "Get Special Offers",
	VALID_ONLY_IF_PAYMENT : "valid only if payment is completed",
	HELP_STR : "HELP",
	REFRESH_STRING : "Refresh",
	CHAT_FOR_HELP : "সাহায্যের জন্য চ্যাট",
	VIEW_FAQs : "View FAQs",
	FIND_HELP_CENTRE : "সহায়তা কেন্দ্র খুঁজুন",
	CONTACT : "যোগাযোগ",
	GO_TO_LOCATION : "অবস্থানে যান",
	NO_HELP_CENTER_IS_ACTIVE_NOW : "এই মুহূর্তে কোনো সহায়তা কেন্দ্র সক্রিয় নেই",
	HELP_CENTERS_LOCATION_WILL_APPEAR_HERE_ONCE_THEY_ARE_ACTIVE : "সহায়তা কেন্দ্রগুলির অবস্থানগুলি সক্রিয় হয়ে গেলে এখানে উপস্থিত হবে৷",  
	SUPPORT : "সমর্থন",
	NEED_HELP_JOINING_THE_PLAN : "পরিকল্পনা বা অটোপেতে যোগদানের জন্য সহায়তা দরকার?",
	HELP_STR : "HELP", 
	GO_TO_VEHICLE_DETAILS : "যানবাহনের বিবরণে যান",
	CLOSE: "বন্ধ", 
	RC_DEACTIVATED : "RC নিষ্ক্রিয় করা হয়েছে", 
	RC_DEACTIVATED_DETAILS : "আপনার আরসি বর্তমানে অন্য ড্রাইভারের অ্যাকাউন্টে সক্রিয় আছে। রাইড নেওয়া শুরু করতে একটি RC সক্রিয় করুন",
	NEED_HELP : "সাহায্য দরকার?",
	NEED_HELP_CALL_SUPPORT : "সাহায্য দরকার? <span style='color:#2194FF'>কল সমর্থন</span>",
	SETUP_AUTOPAY_NOW_TO_GET_SPECIAL_DISCOUNTS  : "বিশেষ ছাড় পেতে এখনই অটোপে সেটআপ করুন",
	SETUP_NOW : "এখন সেটআপ",
	NEED_HELP_JOINING_THE_PLAN : "পরিকল্পনায় যোগদানের জন্য সাহায্যের প্রয়োজন? যোগাযোগ করুন",
  	NEED_HELP_CALL_SUPPORT : "সাহায্য দরকার? <span style='color:#2194FF'>কল সমর্থন</span>",
	CUSTOMER_HAS_LOW_MOBILITY: "গ্রাহকের চালনা সমস্যা রয়েছে",
	CUSTOMER_HAS_DISABILITY: "গ্রাহকের একটি প্রতিবন্ধি আছে",
	CUSTOMER_HAS_LOW_VISION: "গ্রাহকের দুর্দশার্য দর্শন রয়েছে",
	CUSTOMER_HAS_HEARING_IMPAIRMENT: "গ্রাহকের দুর্দশার্য শ্রবণ রয়েছে",
	HELP_WITH_THEIR_MOBILITY_AID: "তাদের চলনার সাহায্য করুন",
	PLEASE_ASSIST_THEM_IF_NEEDED: "প্রয়োজনে তাদের সাহায্য করুন",
	MESSAGE_THEM_AT_PICKUP: "পিকআপে তাদের মেসেজ পাঠান",
	SOUND_HORN_ONCE_AT_PICKUP: "পিকআপে একবার হর্ন বাজান",
	PLEASE_CALL_AND_AVOID_CHATS: "দয়া করে কল করুন এবং চ্যাট এড়িয়ে যান",
	PLEASE_CHAT_AND_AVOID_CALLS: "দয়া করে চ্যাট করুন এবং কল এড়িয়ে যান",
	PLEASE_GO_TO_EXACT_PICKUP: "দয়া করে নির্দিষ্ট পিকআপ স্থানে যান",
	CUSTOMER_HAS_POOR_VISION_SOUND_HORN_AT_PICKUP: "গ্রাহকের দুর্দশার্য দর্শন রয়েছে। পিকআপে একবার হর্ন বাজান।",
	CUSTOMER_HAS_POOR_HEARING_MESSAGE_THEM_AT_PICKUP: "রাইডারের দুর্দশার্য শ্রবণ রয়েছে। পিকআপে তাদের মেসেজ দিন।",
	CUSTOMER_HAS_LOW_MOBILITY_STORE_THEIR_SUPPORT_AT_PICKUP: "গ্রাহকের চালনা সমস্যা রয়েছে। দয়া করে তাদের সাহায্য করে প্যাসেঞ্জার আসনের পিছনে তাদের সাহায্য স্টোর করুন।",
	CUSTOMER_HAS_DISABILITY_PLEASE_ASSIST_THEM: "গ্রাহকের একটি প্রতিবন্ধি আছে। তাদের সাহায্য করুন যেতে পারে।",
	CUSTOMER_MAY_NEED_ASSISTANCE: "গ্রাহক সাহায্য প্রয়োজন করতে পারে",
	LEARN_MORE: "আরও জানুন",
	CUSTOMER_HAS_LOW_MOBILITY_GO_TO_EXACT_LOC: "গ্রাহকের চালনা সমস্যা রয়েছে। দয়া করে নির্দিষ্ট পিকআপ স্থানে যান।",
	CUSTOMER_HAS_POOR_HEARING_CHAT_WITH_THEM_INSTEAD_OF_CALLING: "রাইডারের দুর্দশার্য শ্রবণ রয়েছে। কল করার পরিবর্তে তাদের চ্যাট করুন।",
	CUSTOMER_HAS_LOW_VISION_CALL_THEM_INSTEAD_OF_CHATTING: "গ্রাহকের দুর্দশার্য দর্শন রয়েছে। চ্যাট করার পরিবর্তে তাদের কল করুন।",
	PLEASE_HELP_THEM_AS_YOU_CAN: "আপনি যেতে পারেন সেই মধ্যে তাদের সাহায্য করুন",
	LEARN_HOW_YOU_CAN_HELP_CUSTOMERS_REQUIRING_SPECIAL_ASSISTANCE: "বিশেষ সহায়তার প্রয়োজন এমন গ্রাহকদের আপনি কীভাবে সাহায্য করতে পারেন তা জানুন",
	ASSISTANCE_REQUIRED : "সহায়তা প্রয়োজন",
	NEED_HELP_CALL_SUPPORT : "সাহায্য দরকার? <span style='color:#2194FF'>কল সমর্থন</span>",
	SAVED_DUE_TO_ZERO_COMMISSION : "জিরো কমিশনের\nকারণে সংরক্ষিত", 
	TIP_EARNED_FROM_CUSTOMER : "গ্রাহকের কাছ থেকে\nঅর্জিত টিপ",
	COLLECT_VIA_CASE_UPI : "ক্যাশ/ইউপিআই এর মাধ্যমে সংগ্রহ করুন",
	FARE_COLLECTED :  "ভাড়া সংগৃহীত",
	RATE_YOUR_RIDE_WITH1 : "" ,
	RATE_YOUR_RIDE_WITH2 : "এর সাথে আপনার রাইডকে রেট দিন",
	HELP_US_WITH_YOUR_FEEDBACK : "আপনার প্রতিক্রিয়া আমাদের সাহায্য করে (ঐচ্ছিক)",
	COLLECT_CASH : "নগদ সংগ্রহ করুন",
	ONLINE_PAYMENT : "অনলাইন পেমেন্ট",
	RIDE_COMPLETED : "রাইড সম্পূর্ণ হয়েছে",
	SUBMIT_FEEDBACK : "প্রতিক্রিয়া জমা দিন",
	BADGE_EARNED : "ব্যাজ অর্জিত",
	PURPLE_RIDE_CHAMPION : "পার্পল রাইড চ্যাম্পিয়ন",
	PURPLE_RIDE : "বেগুনি রাইড",
	PROCEED_TO_CHAT : "চ্যাট দিয়ে এগিয়ে যান",
	PLEASE_CONSIDER_CALLING_THEM : "তারা চ্যাট পড়তে সক্ষম নাও হতে পারে. তাদের কল করুন",
	OR : "বা",
	COLLECT_CASH_DIRECTLY : "সরাসরি নগদ সংগ্রহ করুন",
	OR_COLLECT_CASH_DIRECTLY : "অথবা সরাসরি নগদ সংগ্রহ করুন",
	SETUP_AUTOPAY_TO_ACCEPT_PAYMENT : "সরাসরি আপনার ব্যাঙ্ক অ্যাকাউন্টে অর্থপ্রদান গ্রহণ করতে, আপনার প্ল্যানে অটোপে সেট আপ করুন",
	DOWNLOAD_QR : "QR ডাউনলোড করুন",
	USE_THIS_QR_TO_COLLECT_PAYMENT : "আপনি রাইড শেষ হওয়ার পরে অর্থ সংগ্রহ করতে এই QR কোড ব্যবহার করতে পারেন।",
	AMOUNT_WILL_DEPOSITED_TO_BANK_ACCOUNT : "আপনি যে ব্যাঙ্ক অ্যাকাউন্টটি UPI স্বয়ংক্রিয় অর্থপ্রদানের জন্য ব্যবহার করছেন তাতে অর্থ জমা করা হবে",
	GET_DIRECTLY_TO_YOUR_BANK_ACCOUNT : "UPI আইডিতে সরাসরি পেমেন্ট পান",
	PAYMENT : "পেমেন্ট",
	QR_CODE : "QR কোড",
	GET_QR_CODE : "QR কোড পান",
	HELP_US_WITH_YOUR_FEEDBACK : "আপনার প্রতিক্রিয়া আমাদের সাহায্য করে (ঐচ্ছিক)",
	COLLECT_CASH : "নগদ সংগ্রহ করুন",
	ONLINE_PAYMENT : "অনলাইন পেমেন্ট",
	RIDE_COMPLETED : "রাইড সম্পূর্ণ হয়েছে",
	SUBMIT_FEEDBACK : "প্রতিক্রিয়া জমা দিন",
	BADGE_EARNED : "ব্যাজ অর্জিত",
	PURPLE_RIDE_CHAMPION : "পার্পল রাইড চ্যাম্পিয়ন",
	PURPLE_RIDE : "বেগুনি রাইড",
	COMPLETE_PAYMENT_TO_CONTINUE : "Yatri Sathi ব্যবহার চালিয়ে যেতে, অনুগ্রহ করে আপনার অর্থপ্রদান সম্পূর্ণ করুন",
	COLLECT_VIA_UPI_QR_OR_CASH : "UPI QR বা ক্যাশের মাধ্যমে সংগ্রহ করুন",
	PENDING_CAPS : "পেন্ডিং",
	FAILURE: "ব্যর্থতা",
	PAYMENT_MODE : "পেমেন্ট মোড",
	TXN_ID : "অর্ডার আইডি",
	AMOUNT_PAID : "প্রদেয় পরিমাণ",
	OFFER: "অফার",
	NOTIFICATION_SCHEDULED : "বিজ্ঞপ্তি নির্ধারিত!",
	MANUAL_DUES : "ম্যানুয়াল বকেয়া",
	AUTOPAY_IN_PROGRESS : "অটোপে প্রগতিতে আছে",
	MANUAL_DUE_OVERVIEW : "ম্যানুয়াল ডিউ ওভারভিউ",
	AUTOPAY_DUE_OVERVIEW : "অটোপে ডিউ ওভারভিউ",
	MANUAL_DUE_AS_AUTOPAY_EXECUTION_FAILED : "অটোপে এক্সিকিউশন ব্যর্থ হওয়ায় ম্যানুয়াল বকেয়া",
	CLEAR_MANUAL_DUES : "ম্যানুয়াল বকেয়া পরিষ্কার করুন",
	DUE_OVERVIEW : "নির্ধারিত ওভারভিউ",
	MANUAL_DUE_DETAILS : "ম্যানুয়াল বকেয়া বিবরণ",
	AUTOPAY_DUE_DETAILS : "অটোপে বকেয়া বিবরণ",
	SWITCHED_TO_MANUAL : "*পেমেন্ট মোড ম্যানুয়ালে স্যুইচ করা হয়েছে যেহেতু স্বয়ংক্রিয় অর্থপ্রদান পূরণ করা যায়নি",
	SPLIT_PAYMENT : "*অটোপেই কার্যকর করতে অর্থপ্রদান বিভক্ত করা হয়েছে",
	GST_INCLUDE : "(18% GST সহ)",
	SCHEDULED_AT : "নির্ধারিত সময়ে",
	PAYMENT_STATUS : "পেমেন্ট স্ট্যাটাস",
	NOTIFICATION_SCHEDULED : "বিজ্ঞপ্তি নির্ধারিত",
	NOTIFICATION_ATTEMPTING : "বিজ্ঞপ্তির প্রচেষ্টা",
	EXECUTION_SCHEDULED : "সম্পাদনা নির্ধারিত",
	EXECUTION_ATTEMPTING : "সম্পাদনা করার প্রচেষ্টা",
	EXECUTION_SUCCESS : "সম্পাদনা সফল",
	নির্ধারিত : "নির্ধারিত",
	PAYMENT_SCHEDULED : "পেমেন্ট নির্ধারিত",
	OFFER_CARD_BANNER_TITLE : "অটোপে সেটআপ করুন এবং {} পর্যন্ত শুধুমাত্র ₹15/দিন পে করুন",
	OFFER_CARD_BANNER_DESC : "1 নভেম্বর পর্যন্ত শুধুমাত্র ₹15/দিন পে করুন",
	OFFER_CARD_BANNER_ALERT : "আপনার অটোপে সেটআপ মুলতুবি আছে!",
	EXECUTION_FAILED : "সম্পাদনা ব্যর্থ",
	NOTIFICATION_FAILED : "বিজ্ঞপ্তি ব্যর্থ হয়েছে",
	PAY_NOW : "এখনই অর্থ প্রদান করুন",
	CLEAR_DUES_BANNER_TITLE : "নন-স্টপ রাইড উপভোগ করতে আপনার বকেয়া সাফ করুন",
	TRANSACTION_DEBITED_ON : "লেনদেন ডেবিট করা হয়েছে",
	TRANSACTION_ATTEMPTED_ON : "লেনদেনের চেষ্টা করা হয়েছে",
	AUTOPAY_SETUP_AND_PAYMENT_SUCCESSFUL : "অটোপে সেটআপ এবং পেমেন্ট সফল!",
	AUTOPAY_SETUP_SUCCESSFUL : "অটোপে সেটআপ সফল!",
	AUTOPAY_SETUP_AND_PAYMENT_PENDING : "অটোপে সেটআপ এবং পেমেন্ট মুলতুবি!",
	AUTOPAY_SETUP_PENDING : "অটোপে সেটআপ মুলতুবি!",
	AUTOPAY_SETUP_AND_PAYMENT_FAILED : "অটোপে সেটআপ এবং পেমেন্ট ব্যর্থ হয়েছে!",
	AUTOPAY_SETUP_FAILED : "অটোপে সেটআপ ব্যর্থ হয়েছে!",
	ONE_TIME_REGISTERATION : "একবার নিবন্ধন",
   	CLEARANCE_AND_REGISTERATION : "ক্লিয়ারেন্স + রেজিস্ট্রেশন",
	UPI_AUTOPAY_SETUP : "UPI অটোপে সেটআপ",
	WATCH_VIDEO_FOR_HELP : "সাহায্যের জন্য ভিডিও দেখুন",
	PAYMENT_PENDING_SOFT_NUDGE : "প্রাপ্য সীমা শীঘ্রই পৌঁছে যাবে।নন-স্টপ রাইডগুলি উপভোগ করার জন্য সাফ বকেয়া পরিষ্কার করুন",
	CLEAR_YOUR_DUES_EARLY : "আপনার বকেয়া তাড়াতাড়ি সাফ করুন",
	DUE_LIMIT_WARNING_BANNER_TITLE : "আপনার যথাসময়ে ₹{} ডলার সীমা শীঘ্রই পৌঁছে যাবে",
	FREE_TRIAL_ENDING_IN_2_DAYS :"বিনামূল্যে ট্রায়াল 2 দিনের মধ্যে শেষ!",
	FREE_TRIAL_ENDING_TOMORROW : "বিনামূল্যে ট্রায়াল আগামীকাল শেষ!",
	FREE_TRIAL_ENDS_TONIGHT : "বিনামূল্যে ট্রায়াল আজ রাতে শেষ!",
	JOIN_A_PLAN_TO_CONTINUE_TAKING_RIDES : "রাইডগুলি চালিয়ে যাওয়ার পরিকল্পনায় যোগ দিন",
	SETUP_AUTOPAY_FOR_EASY_PAYMENTS : "সহজ অর্থপ্রদানের জন্য অটোপে সেটআপ করুন",
	SCHEDULED_ON : "ছাড়ের তারিখ",
	ATTEMPTED_ON : "প্রচেষ্টার তারিখ",
	LOW_DUES_CLEAR_POPUP_DESC : "অ-স্টপ রাইডগুলি উপভোগ করতে এখনই আপনার বকেয়া সাফ করুন",
	DUES_PENDING : "⚠️ বকেয়া মুলতুবি! ⚠️",
	DAYS : "দিন",
	ACTIVE_PLAN : "সক্রিয় পরিকল্পনা",
	DOWNGRADE_AVAILABLE_ONLY_FOR_AC_VEHICLES : "ডাউনগ্রেড গাড়ি অপশন শুধুমাত্র এসি গাড়ির জন্য উপলব্ধ",
	DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_1 : "আপনার যানবাহন ডাউনগ্রেড করলে আপনি",
	DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_2 : "এবং",
	DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_3 : "রাইড উভয়ই নিতে পারবেন",
	AC_CAB : "এসি ক্যাব",
  	AC_SUV : "এসি এসইউভি",
	DOWNGRADE_VEHICLE : "ডাউনগ্রেড যানবাহন",
	WHAT_ARE_PURPLE_RIDES : "পার্পল রাইডস কি?",
	ECONOMICAL : "অর্থনৈতিক",
	SPACIOUS : "প্রশস্ত",
	COMFY : "আরামদায়ক",
	PEOPLE : "মানুষ",
	GO_TO : "গো-টু",
	SELECT_ON_MAP : "মানচিত্রে নির্বাচন করুন",
	CONFIRM_LOCATION_STR : "অবস্থান নিশ্চিত করুন",
	SAVE_LOCATION_STR : "অবস্থান সংরক্ষণ করুন",
	REMOVE_PREF_LOC : "পছন্দের অবস্থান সরান",
	CONF_REMOVE_PREF_LOC : "আপনি কি নিশ্চিত যে আপনি পছন্দের অবস্থানটি সরাতে চান?",
	YES_REMOVE : "হ্যাঁ, সরান",
	ADD_LOCATION : "অবস্থান যোগ করুন",
	ADD_ANOTHER_LOCATION : "অন্য একটি অবস্থান যোগ করুন",
	ADD_A_GOTO_LOC : "যেতে যেতে অবস্থান যোগ করুন",
	GOTO_LOC_LEFT : "গো-টু অবস্থান বাকি আছে:",
	CURRENT_LOCATION : "বর্তমান অবস্থান",
	CONF_GOTO_LOC : "অবস্থানে যান নিশ্চিত করুন",
	GOTO_LOCS : "স্থানে যান",
	LOCATION_STR : "অবস্থান",
	ADD_TAG : "ট্যাগ যোগ করুন",
	ONLY_ONE_LOC_CAN_ADDED : "(শুধুমাত্র একটি স্থানে এই ট্যাগ থাকতে পারে)",
	SAVE_AS : "এভাবে সংরক্ষণ করুন",
	NO_GOTO_LOC_ADDED : "এখনও কোথাও যাওয়ার লোকেশন যোগ করা হয়নি",
	GOTO_LOC_HELPS_YOU : "লোকেশনে যান আপনাকে আপনার পছন্দের জায়গায় এবং আশেপাশে রাইড খুঁজে পেতে সহায়তা করে",
	YOU_ARE_VERY_CLOSE: "আপনি “গো-টু” অবস্থানের খুব কাছাকাছি",
	GOTO_IS_APPLICABLE_FOR : "“গো-টু” লোকেশনের ক্ষেত্রে প্রযোজ্য \n যেগুলি আপনার বর্তমান অবস্থান থেকে কমপক্ষে 3 কিমি দূরে \n।",
	CANCEL_Anyway : "যেভাবেই হোক বাতিল করুন",
	GOTO_MAYBE_REDUCED : "“গো-টু” কমে যেতে পারে",
	CANCEL_OF_GOTO : "একটি “গো-টু” রাইড বাতিল করলে আপনার “গো-টু” বিকল্পগুলি হ্রাস পাবে!",
	MORE_GOTO_RIDE_COMING : "আরো “গো-টু” রাইড আসছে!",
	MORE_GOTO_RIDE_COMING_DESC : "অনুগ্রহ করে অনলাইনে থাকুন; আমরা আপনার “গো-টু” অবস্থানের জন্য আরো রাইডের অনুরোধ পাচ্ছি",
	GOTO_REDUCED_TO_ZERO : "“গো-টু” কমে শূন্য হয়েছে",
	DUE_TO_MULTIPLE_CANCELLATIONS : "একাধিক বাতিলকরণের কারণে, গণনা কাটা হয়েছে",
	OK_GOT_IT : "ঠিক আছে, বুঝেছি",
	GOTO_REDUCED_TO : "কমিত “গো-টু”",
	VALIDITY_EXPIRED : "বৈধতার মেয়াদ শেষ!",
	VALIDITY_EXPIRED_DESC : "আপনার 30 মিনিটের মেয়াদ শেষ হয়ে গেছে। আমরা এই মুহূর্তে আপনার অনুরোধ পূরণ করতে পারছি না।",
	KNOW_MORE : "আরো জানুন",
	THIS_FEATURE_WILL_BE_APPLICABLE: "আপনি যখন আপনার বর্তমান অবস্থান থেকে কমপক্ষে 3 কিমি দূরে থাকবেন তখন এই বৈশিষ্ট্যটি প্রযোজ্য হবে৷\n\nঅবস্থানের পছন্দগুলি সক্রিয় করা হলে শুধুমাত্র 30 মিনিটের জন্য বৈধ।",
	GOTO_LOC_ADDED : "গো-টু অবস্থান সফলভাবে যোগ করা হয়েছে",
	GOTO_LOC_REMOVED : "“গো-টু” সফলভাবে পুনরুদ্ধার করা হয়েছে",
	GOTO_LOC_UPDATED : "“গো-টু” এর অবস্থান সফলভাবে আপডেট করা হয়েছে",
	GOTO_LOC_IS_ENABLED : "“গো-টু” অবস্থান সক্ষম করা হয়েছে",
	GOTO_LOC_IS_DISABLED : "“গো-টু” অক্ষম করা হয়েছে",
	GOTO_LOCATIONS : "গো-টু অবস্থান",
	CHOOSE_A_GOTO_LOC : "একটি গন্তব্য চয়ন করুন",
	YOU_HAVE_ONLY_LEFT_FOR_TODAY : "আপনি শুধুমাত্র আজকের জন্য রওয়ানা হয়েছেন",
	YES_ENABLE : "হ্যাঁ সক্ষম করুন",
	NO_GOTO_LOCS_ADDED_YET : "এখনও কোন গো-টু অবস্থান যোগ করা হয়নি",
	NO_GOTO_LOCS_ADDED_YET_DESC : "“গো-টু” অবস্থানগুলি আপনাকে আপনার পছন্দের জায়গায় এবং আশেপাশে রাইড খুঁজে পেতে সহায়তা করে",
	ENABLE_GOTO : "“গো-টু” সক্ষম করুন",
	GO_TO_CANCELLATION_TITLE : "“গো-টু” কমে যেতে পারে",
	GO_TO_CANCELLATION_DESC : "একটি “গো-টু” রাইড বাতিল করা হলে আপনার জন্য “গো-টু” বিকল্পগুলি হ্রাস পাবে!",
	REPORT_ISSUE : "রিপোর্ট সমস্যা",
	YOU_ARE_ALMOST_AT_LOCATION : "আপনি প্রায় চলে এসেছেন অবস্থানে।",
	DRIVER_HOME_LOCATION_NOT_FOUND : "অবস্থান পাওয়া যায়নি",
	DRIVER_HOME_LOCATION_DOES_NOT_EXIST : "অবস্থান বিদ্যমান নেই",
	DRIVER_HOME_LOCATION_LIMIT_REACHED : "অবস্থানের সীমা পৌঁছেছে",
	DRIVER_GO_HOME_REQUEST_NOT_FOUND : "অনুরোধ পাওয়া যায়নি",
	DRIVER_GO_HOME_REQUEST_DOES_NOT_EXIST : "অনুরোধ বিদ্যমান নেই",
	DRIVER_GO_HOME_REQUEST_DAILY_USAGE_LIMIT_REACHED : "দৈনিক ব্যবহারের সীমা পৌঁছেছে",
	DRIVER_GO_HOME_REQUEST_ALREADY_ACTIVE : "ইতিমধ্যেই সক্রিয়",
	DRIVER_HOME_LOCATION_OUTSIDE_SERVICE_AREA : "অবস্থান পরিষেবা এলাকার বাইরে",
	NEW_LOCATION_TOO_CLOSE_TO_PREVIOUS_HOME_LOCATION : "অবস্থানটি আগের অবস্থানের খুব কাছাকাছি",
	DRIVER_HOME_LOCATION_DOES_NOT_BELONG_TO_DRIVER : "অবস্থান আপনার নয়",
	DRIVER_HOME_LOCATION_DELETE_WHILE_ACTIVE_ERROR : "সক্রিয় থাকাকালীন অবস্থান মুছে ফেলা যাবে না",
	DISABLE_GOTO_STR : "যাতে অক্ষম করবেন?",
	YOU_STILL_HAVE_TIME_LEFT : "আপনার “গো-টু” অনুরোধে এখনও সময় বাকি আছে",
	YES_DISABLE : "হ্যাঁ, নিষ্ক্রিয় করুন",
	DRAG_TO_ADJUST : "আপনার অবস্থান সামঞ্জস্য করতে টেনে আনুন",
	LOCATION_ALREADY_EXISTS : "অবস্থান ইতিমধ্যেই বিদ্যমান",
	MIN_LEFT : "মিনিট বাকি",
	GOTO_LOC_REACHED : "“গো-টু” অবস্থানে পৌঁছে গেছে!"
}
