
export function getStringValue(key){
    if (key in bengaliStrings){
        return bengaliStrings[key];
    }
    console.error("string not found in bengaliStrings");
    return "";
}

const bengaliStrings = {
    LETS_GET_STARTED : "চল শুরু করি",
    YOUR_APPLICATION_HAS_BEEN_SUBMITTED_SUCCESSFULLY_AND_IS_UNDER_VERIFICATION : "আপনার আবেদন সফলভাবে জমা দেওয়া হয়েছে এবং যাচাইয়ের অধীনে রয়েছে",
    VIEW_STATUS : "স্থিতি দেখুন",
    GO_HOME : "বরিতে জ",
    SELECT_LANGUAGE : "ভাষা নির্বাচন কর",
    WHICH_LANGUAGE_DO_YOU_PREFER : "আপনি কোন ভাষা পছন্দ করেন?",
    NEXT : "পরবর্তী",
    T_C : "শর্তাবলী",
    ENTER_MOBILE_NUMBER : "মোবাইল নম্বর লিখুন",
    BY_CLICKING_NEXT_YOU_WILL_BE_AGREEING_TO_OUR : "পরবর্তী আলতো চাপ দিয়ে) ক) আপনি সম্মত হন যে আপনি বিটা টেস্টিংয়ের অংশগ্রহণকারী এবং জুস্পে কোনও ক্ষেত্রে আপনার বিরুদ্ধে কোনও দায়বদ্ধতা রাখবেন না",
    ENTER_OTP : "ওটিপি প্রবেশ করান",
    DIDNT_RECIEVE_OTP : "ওটিপি গ্রহণ করেনি?",
    RESEND_OTP : "ওটিপি পুনরায় প্রেরণ করুন",
    PLEASE_ENTER_VALID_OTP : "বৈধ ওটিপি লিখুন দয়া করে",
    INVALID_MOBILE_NUMBER : "অকার্যকর মোবাইল নম্বর",
    REGISTER : "নিবন্ধন",
    MOBILE_NUMBER : "মোবাইল নম্বর",
    AUTO_READING_OTP : "অটো রিডিং ওটিপি ...",
    UPLOAD_DRIVING_LICENSE : "ড্রাইভিং লাইসেন্স আপলোড করুন",
    UPLOAD_BACK_SIDE : "পিছনে পিছনে আপলোড করুন",
    UPLOAD_FRONT_SIDE : "আপনার ডিএল এর ফটো সাইড আপলোড করুন",
    BACK_SIDE : "পিছন দিক",
    FRONT_SIDE : "আপনার ডিএল এর ফটো সাইড",
    LICENSE_INSTRUCTION_PICTURE : "দয়া করে লাইসেন্সের উভয় পক্ষের পরিষ্কার ছবি আপলোড করুন",
    LICENSE_INSTRUCTION_CLARITY : "ফটো নিশ্চিত করুন এবং সমস্ত বিবরণ স্পষ্টভাবে দৃশ্যমান",
    REGISTRATION_STEPS : "নিবন্ধকরণ পদক্ষেপ",
    PROGRESS_SAVED : "আপনার অগ্রগতি সংরক্ষণ করা হয়েছে, আপনি কোনও তথ্য পরিবর্তন করতে পূর্ববর্তী পদক্ষেপে ফিরে যেতে পারেন",
    DRIVING_LICENSE : "ড্রাইভিং লাইসেন্স",
    AADHAR_CARD : "আধার কার্ড",
    BANK_DETAILS : "ব্যাংক বিবরণ",
    VEHICLE_DETAILS : "গাড়ির বিবরণ",
    UPLOAD_FRONT_BACK : "সামনে এবং পিছনের দিক আপলোড করুন",
    EARNINGS_WILL_BE_CREDITED : "আপনার উপার্জন এখানে ক্রেডিট হবে",
    FILL_VEHICLE_DETAILS : "আপনার গাড়ির বিশদ পূরণ করুন",
    FOLLOW_STEPS : "নিবন্ধনের জন্য নীচের পদক্ষেপগুলি অনুসরণ করুন",
    REGISTRATION : "নিবন্ধকরণ",
    UPLOAD_ADHAAR_CARD : "আধার কার্ড আপলোড করুন",
    ADHAAR_INTRUCTION_PICTURE : "দয়া করে আধার কার্ডের উভয় পক্ষের পরিষ্কার ছবি আপলোড করুন",
    ADD_VEHICLE_DETAILS : "গাড়ির বিশদ যুক্ত করুন",
    VEHICLE_REGISTRATION_NUMBER : "গাড়ির রেজিস্ট্রেশন নম্বর",
    RE_ENTER_VEHICLE_REGISTRATION_NUMBER : "পুনরায় প্রবেশের যানবাহন নিবন্ধকরণ নম্বর",
    ENTER_VEHICLE_NO : "যানবাহন নং প্রবেশ করান",
    VEHICLE_TYPE : "গাড়ির ধরন",
    VEHICLE_MODEL_NAME : "গাড়ির মডেল নাম",
    ENTER_MODEL_NAME : "মডেল নাম লিখুন",
    VEHICLE_COLOUR : "গাড়ির রঙ",
    ENTER_VEHICLE_COLOUR : "গাড়ির রঙ প্রবেশ করুন",
    UPLOAD_REGISTRATION_CERTIFICATE : "নিবন্ধকরণ শংসাপত্র আপলোড করুন (আরসি)",
    UPLOAD_RC : "আপলোড আরসি",
    PREVIEW : "পূর্বরূপ",
    CHOOSE_VEHICLE_TYPE : "গাড়ির ধরণ চয়ন করুন",
    BENIFICIARY_NUMBER : "সুবিধাভোগী অ্যাকাউন্ট নং",
    RE_ENTER_BENIFICIARY_NUMBER : "পুনরায় প্রবেশের সুবিধাভোগী অ্যাকাউন্ট নং",
    IFSC_CODE : "আইএফএসসি কোড",
    SENDING_OTP : "ওটিপি প্রেরণ",
    PLEASE_WAIT_WHILE_IN_PROGRESS : "অগ্রগতির সময় অপেক্ষা করুন",
    LIMIT_EXCEEDED : "সীমাবদ্ধতা ছাড়িয়ে গেছে",
    YOUR_REQUEST_HAS_TIMEOUT_TRY_AGAIN : "আপনার অনুরোধে আবার চেষ্টা করুন",
    ERROR_OCCURED_PLEASE_TRY_AGAIN_LATER : "ত্রুটি ঘটেছে দয়া করে পরে আবার চেষ্টা করুন",
    LIMIT_EXCEEDED_PLEASE_TRY_AGAIN_AFTER_10MIN : "সীমাবদ্ধতা ছাড়িয়ে গেছে দয়া করে আবার চেষ্টা করুন",
    ENTER_OTP_SENT_TO : "পাঠানো ওটিপি প্রবেশ করান",
    OTP_SENT_TO : "",
    COUNTRY_CODE_INDIA : "+91",
    ENTER_ACCOUNT_NUMBER : "অ্যাকাউন্ট নং প্রবেশ করান",
    ADD_BANK_DETAILS : "ব্যাংকের বিশদ যুক্ত করুন",
    ENTER_IFSC_CODE : "আইএফএসসি কোড প্রবেশ করান",
    SUBMIT : "জমা দিন",
    PERSONAL_DETAILS : "ব্যক্তিগত বিবরণ",
    LANGUAGES : "ভাষা",
    HELP_AND_FAQ : "সহায়তা এবং FAQs",
    ABOUT : "সম্পর্কিত",
    LOGOUT : "প্রস্থান",
    UPDATE : "হালনাগাদ",
    EDIT : "সম্পাদনা",
    AUTO : "অটো",
    NAME : "নাম",
    PRIVACY_POLICY : "গোপনীয়তা নীতি",
    LOGO : "লোগো",
    ABOUT_APP_DESCRIPTION : "জাটি সাথি ড্রাইভার চালকদের সাথে ড্রাইভারদের সংযোগ করার জন্য একটি উন্মুক্ত প্ল্যাটফর্ম। অ্যাপটি প্রস্তাবিত পছন্দসই হার সহ চালকদের সন্ধান করা ড্রাইভারদের পক্ষে সুবিধাজনক করে তোলে। কোনও রাইড ভিত্তিক কমিশন নেই, কেবল মাসিক সাবস্ক্রিপশন আকারে অল্প পরিমাণে অর্থ প্রদান করুন",
    TERMS_AND_CONDITIONS : "শর্তাবলী",
    UPDATE_VEHICLE_DETAILS : "যানবাহন বিশদ আপডেট করুন",
    Help_AND_SUPPORT : "সাহায্য এবং সহযোগিতা",
    NOTE : "বিঃদ্রঃ:",
    VISIT_MY_RIDES_SCREEN_FOR_SPECIFIC_COMPLAINTS : "নির্দিষ্ট অভিযোগের জন্য আমার রাইডস বিভাগটি দেখুন",
    THANK_YOU_FOR_WRTITTING_US : "আমাদের লেখার জন্য আপনাকে ধন্যবাদ!",
    WE_HAVE_RECIEVED_YOUR_ISSUE : "আমরা আপনার সমস্যাটি পুনরুদ্ধার করেছি। আমরা কিছু সময় আপনার কাছে পৌঁছে যাব।",
    GO_TO_HOME : "বাড়িতে যেতে",
    YOUR_RECENT_RIDE : "আপনার সাম্প্রতিক যাত্রা",
    ALL_TOPICS : "সমস্ত বিষয়",
    REPORT_AN_ISSUE_WITH_THIS_TRIP : "এই ট্রিপ দিয়ে একটি সমস্যা রিপোর্ট করুন",
    YOU_RATED : "আপনি রেট করেছেন:",
    VIEW_ALL_RIDES : "সমস্ত রাইড দেখুন",
    WRITE_TO_US : "আমাদের লিখুন",
    SUBJECT : "বিষয়",
    YOUR_EMAIL_ID : "আপনার ইমেল আইডি",
    DESCRIBE_YOUR_ISSUE : "আপনার সমস্যাটি বর্ণনা",
    GETTING_STARTED_AND_FAQ : "শুরু করা এবং FAQss",
    FOR_OTHER_ISSUES_WRITE_TO_US : "অন্যান্য ইস্যুগুলির জন্য, আমাদের লিখুন",
    CALL_SUPPORT_CENTER : "কল সমর্থন কেন্দ্র",
    YOU_CAN_DESCRIBE_ISSUE_THAT_YOU_FACED_HERE : "আপনি এখানে যে সমস্যার মুখোমুখি হয়েছেন তা বর্ণনা করতে পারেন",
    REGISTRATION_CERTIFICATE_IMAGE : "নিবন্ধকরণ শংসাপত্র (আরসি) চিত্র",
    HOME : "বাড়ি",
    RIDES : "রাইডস",
    PROFILE : "প্রোফাইল",
    ENTER_DRIVING_LICENSE_NUMBER : "ড্রাইভিং লাইসেন্স নম্বর প্রবেশ করান",
    WHERE_IS_MY_LICENSE_NUMBER : "আমার লাইসেন্স নম্বরটি কোথায়?",
    TRIP_DETAILS : "ভ্রমণের বিশদ",
    BY_CASH : "নগদে",
    ONLINE_ :  "অনলাইন",
    REPORT_AN_ISSUE : "একটি সমস্যা রিপোর্ট",
    DISTANCE : "দূরত্ব",
    TIME_TAKEN : "সময় নিয়েছে",
    OPEN_GOOGLE_MAPS : "গুগল মানচিত্র",
    CALL : "কল",
    START_RIDE : "যাত্রা শুরু করুন",
    CANCEL_RIDE : "যাত্রা বাতিল করুন",
    PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL : "আপনি কেন বাতিল করতে চান দয়া করে আমাদের বলুন",
    MANDATORY : "বাধ্যতামূলক",
    END_RIDE : "শেষ যাত্রা",
    RIDE_COMPLETED_WITH : "গ্রাহকের সাথে যাত্রা সম্পূর্ণ",
    COLLECT_AMOUNT_IN_CASH : "নগদ অর্থ সংগ্রহ করুন",
    CASH_COLLECTED : "নগদ সংগ্রহ করা হয়েছে",
    OFFLINE : "অফলাইন",
    ACCEPT_FOR : "জন্য গ্রহণ:",
    DECLINE : "পতন",
    REQUEST : "অনুরোধ",
    YOU_ARE_OFFLINE : "আপনি অফলাইন",
    YOU_ARE_CURRENTLY_BUSY_GO_ONLINE_TO_RECIEVE_TRIP_REQUESTS : "আপনি বর্তমানে ব্যস্ত। ট্রিপ অনুরোধগুলি পেতে অনলাইনে যান",
    GOING_OFFLINE_WILL_NOT_GET_YOU_ANY_RIDE : "অফলাইনে যাওয়া আপনাকে কোনও যাত্রা পাবে না",
    CANCEL : "বাতিল",
    GO_OFFLINE : "অফলাইন যেতে",
    IS_WAITING_FOR_YOU : "তোমার জন্য অপেক্ষা করছে",
    YOU_ARE_ON_A_RIDE : "আপনি একটি যাত্রায় আছেন ...",
    PLEASE_ASK_RIDER_FOR_THE_OTP : "ওটিপির জন্য রাইডারকে জিজ্ঞাসা করুন",
    COMPLETED_ : "সম্পূর্ণ",
    CANCELLED_ : "বাতিল",
    WE_NEED_SOME_ACCESS : "আমাদের অ্যাক্সেস অনুসরণ করুন!",
    ALLOW_ACCESS : "ব্যবহারের অনুমতি",
    THANK_YOU_FOR_WRITING_TO_US : "আমাদের লেখার জন্য আপনাকে ধন্যবাদ!",
    RIDER : "রাইডার",
    TRIP_ID : "ট্রিপ আইডি",
    NEED_IT_TO_SHOW_YOU_INCOMING_RIDE_REQUEST : "অ্যাপটি ব্যাকগ্রাউন্ডে থাকাকালীন আগত রাইডের অনুরোধ পান",
    NEED_IT_TO_DISABLE_BATTERY_OPTIMIZATION_FOR_THE_APP : "প্রস্তাবিত, অ্যাপটিকে দীর্ঘকাল ব্যাকগ্রাউন্ডে চালাতে সক্ষম করে",
    NEED_IT_TO_AUTOSTART_YOUR_APP : "অ্যাপটিকে পটভূমিতে চালিয়ে রেখে সহায়তা করে",
    NEED_IT_TO_ENABLE_LOCATION : "জাটি সাথি ড্রাইভার ড্রাইভারের বর্তমান অবস্থান নিরীক্ষণের জন্য আপনার অবস্থানটি ভাগ করে নিতে সক্ষম করতে অবস্থানের ডেটা সংগ্রহ করে, এমনকি অ্যাপটি বন্ধ থাকলেও বা ব্যবহার না করা হয়।",
    OVERLAY_TO_DRAW_OVER_APPLICATIONS : "অ্যাপ্লিকেশনগুলি আঁকুন",
    BATTERY_OPTIMIZATIONS : "ব্যাটারি অপ্টিমাইজেশন",
    AUTO_START_APPLICATION_IN_BACKGROUND : "পটভূমিতে অটোস্টার্ট অ্যাপ",
    LOCATION_ACCESS : "অবস্থান অ্যাক্সেস",
    ENTER_RC_NUMBER : "আরসি নম্বর লিখুন",
    WHERE_IS_MY_RC_NUMBER : "আমার আরসি নম্বরটি কোথায়?",
    STEP : "পদক্ষেপ",
    PAID : "প্রদত্ত",
    ENTERED_WRONG_OTP : "ভুল ওটিপি প্রবেশ করেছে",
    COPIED : "অনুলিপি",
    BANK_NAME : "ব্যাংকের নাম",
    AADHAR_DETAILS : "আধারের বিবরণ",
    AADHAR_NUMBER : "আধার নম্বর",
    FRONT_SIDE_IMAGE : "সামনের দিকের চিত্র",
    BACK_SIDE_IMAGE : "পিছনের দিকের চিত্র",
    STILL_NOT_RESOLVED : "এখনও সমাধান না? আমাদের কল",
    CASE_TWO : "খ)",
    NON_DISCLOUSER_AGREEMENT : "কোন প্রকাশ চুক্তি নেই",
    DATA_COLLECTION_AUTHORITY : "গ) আমি এইভাবে আমার তথ্য সংগ্রহের জন্য জুস্পকে নিয়োগ ও অনুমোদন করি এবং চালিয়ে যাওয়ার মাধ্যমে আমি ব্যবহারের শর্তাদি এবং গোপনীয়তা নীতিমালার সাথে সম্মত হই",
    SOFTWARE_LICENSE : "সফ্টওয়্যার লাইসেন্স",
    LOAD_MORE : "আর ঢুকাও",
    ARE_YOU_SURE_YOU_WANT_TO_LOGOUT : "আপনি লগ আউট করতে চান?",
    GO_BACK : "ফিরে যাও",
    THANK_YOU_FOR_REGISTERING_US : "আমাদের সাথে নিবন্ধনের জন্য আপনাকে ধন্যবাদ!",
    UNFORTANUTELY_WE_ARE_NOT_AVAILABLE__YET_FOR_YOU : "দুর্ভাগ্যক্রমে, আমরা আপনার জন্য এখনও উপলব্ধ নেই। আমরা শীঘ্রই আপনাকে অবহিত করব।",
    ARE_YOU_SURE_YOU_WANT_TO_END_THE_RIDE : "আপনি কি নিশ্চিত যে আপনি যাত্রাটি শেষ করতে চান?",
    EMPTY_RIDES : "খালি রাইড",
    YOU_HAVE_NOT_TAKEN_A_TRIP_YET : "আপনি এখনও একটি ট্রিপ নিচ্ছেন না",
    BOOK_NOW : "এখনই বুক করুন",
    RESEND_OTP_IN : "ওটিপি ইন পুনরায় পাঠান",
    WE_NEED_ACCESS_TO_YOUR_LOCATION : "আমাদের আপনার অবস্থানের অ্যাক্সেস দরকার!",
    YOUR_LOCATION_HELPS_OUR_SYSTEM : "আপনার অবস্থানটি আমাদের সিস্টেমকে অটোস দ্বারা সমস্ত কাছাকাছি মানচিত্র করতে এবং আপনাকে দ্রুততম যাত্রা সম্ভব করতে সহায়তা করে।",
    NO_INTERNET_CONNECTION : "কোনও ইন্টারনেট সংযোগ নেই",
    PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN : "দয়া করে আপনাকে ইন্টারনেট সংযোগটি পরীক্ষা করুন এবং আবার চেষ্টা করুন",
    TRY_AGAIN : "আবার চেষ্টা কর",
    GRANT_ACCESS : "অনুদান অ্যাক্সেস",
    YOUR_LIMIT_EXCEEDED_TRY_AGAIN_AFTER_10_MIN : "আপনি সীমা ছাড়িয়ে যান, 10 মিনিটের পরে আবার চেষ্টা করুন",
    ENTER_REFERRAL_MOBILE_NUMBER :  "রেফারেল মোবাইল নম্বর প্রবেশ করান",
    APPLY : "প্রয়োগ করুন",
    HAVE_A_REFERRAL : "একটি রেফারেল আছে?",
    ADD_HERE : "এখানে যোগ করুন",
    REFERRAL_APPLIED : "রেফারেল প্রয়োগ!",
    SMALLEDIT : "সম্পাদনা",
    ADD_DRIVING_LICENSE : "ড্রাইভিং লাইসেন্স যুক্ত করুন",
    HELP : "সাহায্য?",
    INVALID_DL_NUMBER : "অবৈধ ডিএল নম্বর",
    DRIVING_LICENSE_NUMBER : "ড্রাইভিং লাইসেন্স নম্বর",
    RE_ENTER_DRIVING_LICENSE_NUMBER : "ড্রাইভিং লাইসেন্স নম্বর পুনরায় প্রবেশ করুন",
    ENTER_DL_NUMBER : "ডিএল নম্বর লিখুন",
    SELECT_DATE_OF_BIRTH : "জন্ম তারিখ নির্বাচন করুন",
    DATE_OF_BIRTH : "জন্ম তারিখ",
    WATCH_A_TUTORIAL_FOR_EASY_REGISTRATION : "সহজ \n নিবন্ধকরণের জন্য একটি টিউটোরিয়াল দেখুন",
    ENTER_MINIMUM_FIFTEEN_CHARACTERS : "মিনিয়াম 15 অক্ষর লিখুন",
    ADD_YOUR_FRIEND : "আপনার বন্ধু যোগ করুন",
    PLEASE_WAIT_WHILE_VALIDATING_THE_IMAGE : "চিত্রটি বৈধ করার সময় দয়া করে অপেক্ষা করুন",
    VALIDATING : "বৈধকরণ",
    VERIFICATION_PENDING : "যাচাইকরণ মুলতুবি",
    VERIFICATION_FAILED : "যাচাই ব্যর্থ",
    NO_DOC_AVAILABLE : "কোন নথি উপলব্ধ",
    ISSUE_WITH_DL_IMAGE : "আপনার ডিএল চিত্রের সাথে কিছু সমস্যা রয়েছে বলে মনে হচ্ছে, আমাদের সমর্থন দলটি শীঘ্রই আপনার সাথে যোগাযোগ করবে।",
    STILL_HAVE_SOME_DOUBT : "এখনও কিছু সন্দেহ আছে?",
    ISSUE_WITH_RC_IMAGE : "আপনার আরসি চিত্রের সাথে কিছু সমস্যা রয়েছে বলে মনে হচ্ছে, আমাদের সমর্থন দলটি শীঘ্রই আপনার সাথে যোগাযোগ করবে।",
    PLEASE_CHECK_FOR_IMAGE_IF_VALID_DOCUMENT_IMAGE_OR_NOT : "বৈধ ডকুমেন্ট ইমেজ কিনা দয়া করে চিত্রের জন্য চেক করুন",
    OOPS_YOUR_APPLICATION_HAS_BEEN_REJECTED : "ওফস! আপনার আবেদন প্রত্যাখ্যান করা হয়েছে। অনুগ্রহপূর্বক আবার চেষ্টা করুন",
    INVALID_DRIVING_LICENSE : "অবৈধ ড্রাইভিং লাইসেন্স",
    LIMIT_EXCEEDED_FOR_DL_UPLOAD : "ডিএল আপলোডের জন্য সীমাবদ্ধতা ছাড়িয়ে যায়",
    INVALID_VEHICLE_REGISTRATION_CERTIFICATE : "অবৈধ যানবাহন নিবন্ধকরণ শংসাপত্র",
    LIMIT_EXCEEDED_FOR_RC_UPLOAD : "আরসি আপলোডের জন্য সীমাবদ্ধতা ছাড়িয়ে গেছে",
    YOUR_DOCUMENTS_ARE_APPROVED : "আপনার নথি অনুমোদিত। সমর্থন দল শীঘ্রই আপনার অ্যাকাউন্ট সক্ষম করবে। আপনার অ্যাকাউন্ট সক্ষম করতে আপনি সমর্থন দলকে কল করতে পারেন",
    APPLICATION_STATUS : "আবেদনপত্রের অবস্থা",
    FOR_SUPPORT : "সমর্থন জন্য",
    CONTACT_US : "যোগাযোগ করুন",
    IMAGE_VALIDATION_FAILED : "চিত্রের বৈধতা ব্যর্থ হয়েছে",
    IMAGE_NOT_READABLE : "চিত্র পঠনযোগ্য নয়",
    IMAGE_LOW_QUALITY : "চিত্রের মান ভাল নয়",
    IMAGE_INVALID_TYPE : "প্রদত্ত চিত্রের ধরণটি প্রকৃত ধরণের সাথে মেলে না",
    IMAGE_DOCUMENT_NUMBER_MISMATCH : "এই চিত্রের ডকুমেন্ট নম্বরটি ইনপুটটির সাথে মেলে না",
    IMAGE_EXTRACTION_FAILED : "চিত্র নিষ্কাশন ব্যর্থ হয়েছে",
    IMAGE_NOT_FOUND : "ছবিটি খুঁজে পাওয়া যায়নি",
    IMAGE_NOT_VALID : "চিত্র বৈধ নয়",
    DRIVER_ALREADY_LINKED : "অন্যান্য ডক ইতিমধ্যে ড্রাইভারের সাথে যুক্ত",
    DL_ALREADY_UPDATED : "কর্ম প্রয়োজন. ড্রাইভার লাইসেন্স ইতিমধ্যে ড্রাইভারের সাথে যুক্ত",
    RC_ALREADY_LINKED : "যানবাহন আরসি উপলভ্য নয়। অন্যান্য ড্রাইভারের সাথে যুক্ত",
    RC_ALREADY_UPDATED : "কর্ম প্রয়োজন. যানবাহন আরসি ইতিমধ্যে ড্রাইভারের সাথে যুক্ত",
    DL_ALREADY_LINKED : "ড্রাইভার লাইসেন্স পাওয়া যায় না। অন্যান্য ড্রাইভারের সাথে যুক্ত",
    SOMETHING_WENT_WRONG : "কিছু ভুল হয়েছে",
    PICKUP : "পিকআপ",
    TRIP : "ট্রিপ",
    CURRENTLY_WE_ALLOW_ONLY_KARNATAKA_REGISTERED_NUMBER : "বর্তমানে, আমরা শুধুমাত্র পশ্চিমবঙ্গ নিবন্ধিত নম্বর অনুমোদন করি",
    UPDATED_AT : "এ আপডেট",
    TRIP_COUNT : "আজকের ট্রিপস",
    TODAYS_EARNINGS : "আজকের উপার্জন",
    DATE_OF_REGISTRATION : "নিবন্ধনের তারিখ",
    SELECT_DATE_OF_ISSUE : "ইস্যুর তারিখ নির্বাচন করুন",
    DATE_OF_ISSUE : "প্রদান এর তারিখ",
    PROVIDE_DATE_OF_ISSUE_TEXT : "দুঃখিত, আমরা আপনার বিশদটি বৈধতা দিতে পারি না, আপনার ড্রাইভিং লাইসেন্সটি বৈধতা পেতে দয়া করে <b> ইস্যুর তারিখ </b> সরবরাহ করুন।",
    PROVIDE_DATE_OF_REGISTRATION_TEXT : "দুঃখিত আমরা আপনার বিশদটি বৈধতা দিতে পারি না, আপনার গাড়ির বিশদটি বৈধতা পেতে দয়া করে <b> নিবন্ধকরণের তারিখ </b> সরবরাহ করুন।",
    SELECT_DATE_OF_REGISTRATION : "নিবন্ধকরণের তারিখ নির্বাচন করুন",
    SAME_REENTERED_RC_MESSAGE : "দয়া করে নিশ্চিত হয়ে নিন",
    SAME_REENTERED_DL_MESSAGE : "পুনরায় প্রবেশ করা ডিএল নম্বর উপরে প্রদত্ত ডিএল নম্বরটির সাথে মেলে না",
    WHERE_IS_MY_ISSUE_DATE : "আমার ইস্যু তারিখ কোথায়?",
    WHERE_IS_MY_REGISTRATION_DATE : "নিবন্ধের তারিখ কোথায়?",
    OTP_RESENT : "ওটিপি বিরক্তি",
    EARNINGS_CREDITED_IN_ACCOUNT : "আপনার উপার্জন এই অ্যাকাউন্টে জমা দেওয়া হবে",
    INVALID_PARAMETERS : "অবৈধ পরামিতি",
    UNAUTHORIZED : "অননুমোদিত",
    INVALID_TOKEN : "অবৈধ টোকেন",
    SOME_ERROR_OCCURED_IN_OFFERRIDE : "অফারাইডে কিছু ত্রুটি ঘটেছিল",
    SELECT_VEHICLE_TYPE : "গাড়ির ধরণ নির্বাচন করুন",
    RIDE : "যাত্রা",
    NO_LOCATION_UPDATE : "কোনও অবস্থান আপডেট নেই",
    GOT_IT_TELL_US_MORE : "পেয়েছি, আরও বলুন?",
    WRITE_A_COMMENT : "একটি মন্তব্য লিখুন",
    HOW_WAS_YOUR_RIDE_WITH : "আপনার যাত্রা কেমন ছিল",
    RUDE_BEHAVIOUR : "অভদ্র আচরণ",
    LONG_WAITING_TIME : "দীর্ঘ সময় অপেক্ষা",
    DIDNT_COME_TO_PICUP_LOCATION : "পিকআপ লোকেশনে আসেনি",
    HELP_US_WITH_YOUR_REASON : "আপনার কারণ দিয়ে আমাদের সহায়তা করুন",
    MAX_CHAR_LIMIT_REACHED : "সর্বোচ্চ চরিত্রের সীমা পৌঁছেছে,",
    SHOW_ALL_OPTIONS : "সমস্ত বিকল্প দেখান",
    UPDATE_REQUIRED : "আপডেট প্রয়োজন",
    PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE : "পরিষেবা চালিয়ে যেতে অ্যাপ্লিকেশন আপডেট করুন",
    NOT_NOW : "এখন না",
    OF : "এর",
    DROP : "ড্রপ",
    PLEASE_WAIT : "অনুগ্রহপূর্বক অপেক্ষা করুন",
    SETTING_YOU_OFFLINE : "আমরা আপনাকে অফলাইন সেট করছি",
    SETTING_YOU_ONLINE : "আমরা আপনাকে অনলাইনে সেট করছি",
    VIEW_BREAKDOWN : "ব্রেকডাউন দেখুন",
    APP_INFO : "অ্যাপ্লিকেশন তথ্য",
    OTHER : "অন্য",
    VEHICLE_ISSUE : "যানবাহন সমস্যা",
    FARE_UPDATED : "ভাড়া আপডেট হয়েছে",
    FREQUENT_CANCELLATIONS_WILL_LEAD_TO_LESS_RIDES : "ঘন ঘন বাতিলকরণগুলি কম রাইড এবং কম রেটিংয়ের দিকে পরিচালিত করবে",
    CONTINUE : "চালিয়ে যান",
    CONFIRM_PASSWORD : "পাসওয়ার্ড নিশ্চিত করুন",
    DEMO_MODE : "ডেমো মোড",
    PASSWORD : "পাসওয়ার্ড",
    ENTER_DEMO_MODE_PASSWORD : "ডেমো মোড পাসওয়ার্ড লিখুন",
    DEMO_MODE_DISABLED : "ডেমো মোড অক্ষম",
    ONLINE_VIA_DEMO_MODE : "অনলাইন (ডেমো)",
    MORE : "আরও",
    LESS : "কম",
    YOU_ARE_AT_PICKUP : "আপনি পিকআপ লোকেশনে আছেন",
    WAITING_FOR_CUSTOMER : "আপনি অপেক্ষা করছেন",
    CUSTOMER_NOTIFIED : "গ্রাহক বিজ্ঞপ্তি",
    I_ARRIVED : "আমি এসেছি",
    ESTIMATED_RIDE_FARE : "আনুমানিক রাইড ভাড়া:",
    PICKUP_TOO_FAR : "পিকআপ খুব দূরে",
    CUSTOMER_NOT_PICKING_CALL : "গ্রাহক কল বাছাই করছেন না",
    TRAFFIC_JAM : "ট্রাফিক জ্যাম",
    CUSTOMER_WAS_RUDE : "গ্রাহক অভদ্র ছিল",
    ALERT :  "সতর্কতা",
    ALL_ALERTS : "সমস্ত সতর্কতা",
    ADD_A_COMMENT : "একটি মন্তব্য যুক্ত করুন",
    POST_COMMENT : "পোস্ট মন্তব্য",
    ENTER_YOUR_COMMENT : "আপনার মন্তব্য লিখুন",
    NO_NOTIFICATIONS_RIGHT_NOW : "এখনই কোনও বিজ্ঞপ্তি নেই!",
    NO_NOTIFICATIONS_RIGHT_NOW_DESC : "যখন নতুন কোনও বিজ্ঞপ্তি রয়েছে তখন আমরা আপনাকে জানাব",
    ALERTS : "সতর্কতা",
    YOUR_COMMENT : "আপনার মন্তব্য",
    SHOW_MORE : "আরও দেখান",
    LOAD_OLDER_ALERTS : "পুরানো সতর্কতাগুলি লোড করুন",
    CONTEST : "প্রতিযোগিতা",
    YOUR_REFERRAL_CODE_IS_LINKED : "আপনার রেফারেল কোড লিঙ্কযুক্ত!",
    YOU_CAN_NOW_EARN_REWARDS : "আপনি এখন গ্রাহকদের উল্লেখ করার জন্য পুরষ্কার অর্জন করতে পারেন!",
    COMING_SOON : "শীঘ্রই আসছে!",
    COMING_SOON_DESCRIPTION : "আমরা আপনাকে রেফারেল প্রোগ্রামে বোর্ডে নিয়ে যাওয়ার কাজ করছি। আরও তথ্যের জন্য সতর্কতা পৃষ্ঠাটি দেখুন।",
    REFERRAL_CODE : "রেফারেল কোড",
    REFERRAL_CODE_HINT : "6-অঙ্কের রেফারেল কোড লিখুন",
    CONFIRM_REFERRAL_CODE : "রেফারেল কোড নিশ্চিত করুন",
    CONFIRM_REFERRAL_CODE_HINT : "রেফারাল কোড পুনরায় প্রবেশ করুন",
    YOUR_REFERRAL_CODE : "আপনার রেফারাল কোড",
    FIRST_REFERRAL_SUCCESSFUL : "প্রথম রেফারাল সফল! \n পুরষ্কার আনলক!",
    AWAITING_REFERRAL_RIDE : "রেফারাল রাইডের অপেক্ষায়",
    CHECK_THIS_SPACE_WHEN_YOU_GET_REFERRAL_ALERT : "আপনি যখন রেফারেল সতর্কতা পাবেন তখন এই স্থানটি পরীক্ষা করুন",
    REFERRED_CUSTOMERS : "গ্রাহকদের রেফারেন্স",
    ACTIVATED_CUSTOMERS : "সক্রিয় গ্রাহক",
    REFERRAL_CODE_LINKING : "রেফারেল কোড লিঙ্কিং",
    CONTACT_SUPPORT : "যোগাযোগ সমর্থন",
    CALL_SUPPORT : "কল সমর্থন",
    YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT : "আপনি জাত্রি সাথি সমর্থন দলকে কল করতে চলেছেন। আপনি কি এগিয়ে যেতে চান?",
    REFERRAL_ENROLMENT : "রেফারেল তালিকাভুক্তি"    ,
    REFERRALS : "প্রচার",
    LINK_REFERRAL_CODE : "লিঙ্ক রেফারেল কোড",
    DRIVER_DETAILS : "ড্রাইভার বিবরণ",
    FOR_UPDATES_SEE_ALERTS : "আপডেটের জন্য, সতর্কতাগুলি দেখুন",
    SHARE_OPTIONS : "ভাগ বিকল্প",
    ENTER_PASSWORD : "পাসওয়ার্ড লিখুন",
    YOUR_VEHICLE : "আপনার বাহন",
    BOOKING_OPTIONS : "বুকিং অপশন"
}