const englishStrings = {
  INACCURATE_DATE_AND_TIME: "Inaccurate Date & Time!",
  ADJUST_YOUR_DEVICE_DATE_AND_TIME_AND_TRY_AGAIN: "Please set date and time to automatic (network-provided) from your settings app.",
  THE_CURRENT_DATE_AND_TIME_IS: "The current date and time is",
  GO_TO_SETTING: "Go to Settings",
  LETS_GET_STARTED: "Let's get started",
  YOUR_APPLICATION_HAS_BEEN_SUBMITTED_SUCCESSFULLY_AND_IS_UNDER_VERIFICATION: "Your Application has been submitted successfully and is under verification",
  VIEW_STATUS: "View Status",
  GO_HOME: "Go Home",
  SELECT_LANGUAGE: "Select Language",
  WHICH_LANGUAGE_DO_YOU_PREFER: "Which language do you prefer?",
  NEXT: "Next",
  T_C: "Terms & Conditions",
  ENTER_MOBILE_NUMBER: "Enter Mobile Number",
  BY_CLICKING_CONTINUE_YOU_WILL_BE_AGREEING_TO_OUR: "By clicking Continue, you agree to our",
  ENTER_OTP: "Enter OTP",
  DIDNT_RECIEVE_OTP: "Didn't recieve an OTP? ",
  RESEND_OTP: "Resend OTP",
  PLEASE_ENTER_VALID_OTP: "Please Enter Valid OTP",
  INVALID_MOBILE_NUMBER: "Invalid mobile number",
  REGISTER: "Register",
  MOBILE_NUMBER: "Mobile Number",
  AUTO_READING_OTP: "Auto Reading OTP...",
  UPLOAD_DRIVING_LICENSE: "Upload Driving Licence",
  UPLOAD_BACK_SIDE: "Upload Back Side",
  UPLOAD_FRONT_SIDE: "Upload Photo side of your DL",
  BACK_SIDE: "Back Side",
  FRONT_SIDE: "Photo side of your DL",
  LICENSE_INSTRUCTION_PICTURE: "Kindly upload clear pictures of both sides of the license",
  LICENSE_INSTRUCTION_CLARITY: "Ensure photo and all details are clearly visible",
  REGISTRATION_STEPS: "Registration Steps",
  PROGRESS_SAVED: "Your progress is saved, you can also go back to previous steps to change any information",
  DRIVING_LICENSE: "Driving License",
  AADHAR_CARD: "Aadhar Card",
  BANK_DETAILS: "Bank Details",
  VEHICLE_DETAILS: "Vehicle Details",
  UPLOAD_FRONT_BACK: "Upload front and back side",
  EARNINGS_WILL_BE_CREDITED: "Your earnings will be credit here",
  FILL_VEHICLE_DETAILS: "Fill your vehicle details",
  FOLLOW_STEPS: "Please follow below steps to register",
  REGISTRATION: "Registration",
  UPLOAD_ADHAAR_CARD: "Upload Aadhar Card",
  ADHAAR_INTRUCTION_PICTURE: "Kindly upload clear pictures of both sides of the Aadhar Card",
  ADD_VEHICLE_DETAILS: "Add Vehicle Details",
  VEHICLE_REGISTRATION_NUMBER: "Vehicle Registration Certificate Number",
  RE_ENTER_VEHICLE_REGISTRATION_NUMBER: "Re-enter Vehicle Registration Certificate Number",
  ENTER_VEHICLE_NO: "Enter Vehicle No.",
  VEHICLE_TYPE: "Vehicle Type",
  VEHICLE_MODEL_NAME: "Vehicle Model Name",
  ENTER_MODEL_NAME: "Enter Model Name",
  VEHICLE_COLOUR: "Vehicle Colour",
  ENTER_VEHICLE_COLOUR: "Enter Vehicle Colour",
  UPLOAD_REGISTRATION_CERTIFICATE: "Upload Registration Certificate (RC)",
  UPLOAD_RC: "Upload RC",
  PREVIEW: "Preview",
  CHOOSE_VEHICLE_TYPE: "Choose Vehicle Type",
  BENIFICIARY_NUMBER: "Beneficiary Account No",
  RE_ENTER_BENIFICIARY_NUMBER: "Re-enter Beneficiary Account No.",
  IFSC_CODE: "IFSC Code",
  SENDING_OTP: "Sending OTP",
  PLEASE_WAIT_WHILE_IN_PROGRESS: "Please wait while in progress",
  YOUR_REQUEST_HAS_TIMEOUT_TRY_AGAIN: "Your request has timeout try again",
  ERROR_OCCURED_PLEASE_TRY_AGAIN_LATER: "Error occured please try again later",
  ENTER_OTP_SENT_TO: "Enter OTP sent to ",
  OTP_SENT_TO: "OTP sent to ",
  COUNTRY_CODE_INDIA: "+91",
  ENTER_ACCOUNT_NUMBER: "Enter Account No.",
  ADD_BANK_DETAILS: "Add Bank Details",
  ENTER_IFSC_CODE: "Enter IFSC Code",
  SUBMIT: "Submit",
  PERSONAL_DETAILS: "Personal Details",
  LANGUAGES: "Languages",
  HELP_AND_FAQ: "Help & FAQs",
  ABOUT: "About",
  LOGOUT: "Logout",
  UPDATE: "Update",
  EDIT: "Edit",
  AUTO: "Auto",
  NAME: "Name",
  PRIVACY_POLICY: "Privacy Policy",
  LOGO: "Logo",
  ABOUT_APP_DESCRIPTION: "Namma Yatri partner is an open platform to connect drivers with riders. The app makes it convenient for drivers to find riders with proposed desired rates. No ride based commission, just pay small amount in the form of monthly subscription",
  TERMS_AND_CONDITIONS: "Terms & Conditions",
  UPDATE_VEHICLE_DETAILS: "Update Vehicle Details",
  Help_AND_SUPPORT: "Help And Support",
  NOTE: "Note:",
  VISIT_MY_RIDES_SCREEN_FOR_SPECIFIC_COMPLAINTS: "Visit My Rides Section for specific complaints",
  THANK_YOU_FOR_WRTITTING_US: "Thank you for writing us!",
  WE_HAVE_RECIEVED_YOUR_ISSUE: "We have recieved your issue. We'll reachout to you in sometime.",
  GO_TO_HOME: "Go To Home",
  YOUR_RECENT_RIDE: "Your Recent Ride",
  YOUR_RECENT_TRIP: "Your Recent Trip",
  ALL_TOPICS: "All Topics",
  REPORT_AN_ISSUE_WITH_THIS_TRIP: "Report an issue with this trip",
  YOU_RATED: "You Rated:",
  VIEW_ALL_RIDES: "View All Rides",
  WRITE_TO_US: "Write To Us",
  SUBJECT: "Subject",
  YOUR_EMAIL_ID: "Your Email ID",
  DESCRIBE_YOUR_ISSUE: "Describe Your issue",
  GETTING_STARTED_AND_FAQ: "Getting started and FAQs",
  FOR_OTHER_ISSUES_WRITE_TO_US: "For other issues, write to us",
  CALL_SUPPORT_CENTER: "Call support center",
  YOU_CAN_DESCRIBE_ISSUE_THAT_YOU_FACED_HERE: "You can describe issue that you faced here",
  REGISTRATION_CERTIFICATE_IMAGE: "Registration Certificate (RC) Image",
  HOME: "Home",
  RIDES: "Rides",
  MY_RIDES: "My Rides",
  PROFILE: "Profile",
  ENTER_DRIVING_LICENSE_NUMBER: "Enter Driving License Number",
  WHERE_IS_MY_LICENSE_NUMBER: "Where is my License Number?",
  TRIP_DETAILS: "Trip Details",
  BY_CASH: "by Cash",
  ONLINE_: "Online",
  GO_ONLINE_POPUP: "<u>Go Online</u>",
  REPORT_AN_ISSUE: "Report an Issue",
  DISTANCE: "Distance",
  TIME_TAKEN: "Time Taken",
  MAPS: "Maps",
  CALL: "Call",
  START_RIDE: "Start Ride",
  CANCEL_RIDE: "Cancel Ride",
  PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL: "Please tell us why you want to cancel",
  MANDATORY: "Mandatory",
  END_RIDE: "End Ride",
  RIDE_COMPLETED_WITH: "Ride Completed with customer",
  COLLECT_AMOUNT_IN_CASH: "Collect the amount in cash",
  CASH_COLLECTED: "Cash Collected",
  OFFLINE: "Offline",
  ACCEPT_FOR: "Accept for:",
  DECLINE: "Decline",
  REQUEST: "Request",
  YOU_ARE_OFFLINE: "You're offline",
  YOU_ARE_CURRENTLY_BUSY_GO_ONLINE_TO_RECIEVE_TRIP_REQUESTS: "You are currently Busy. Go online to recieve trip requests",
  GOING_OFFLINE_WILL_NOT_GET_YOU_ANY_RIDE: "Going offline will not get you any ride",
  CANCEL: "Cancel",
  GO_OFFLINE: "Go Offline",
  IS_WAITING_FOR_YOU: "is waiting for you",
  YOU_ARE_ON_A_RIDE: "You are on a ride...",
  PLEASE_ASK_RIDER_FOR_THE_OTP: "Please ask rider for the OTP",
  COMPLETED_: "Completed",
  CANCELLED_: "Cancelled",
  WE_NEED_SOME_ACCESS: "Grant us following access!",
  ALLOW_ACCESS: "Allow Access",
  THANK_YOU_FOR_WRITING_TO_US: "Thank you for Writing to us!",
  RIDER: "Rider",
  TRIP_ID: "Trip Id",
  NEED_IT_TO_SHOW_YOU_INCOMING_RIDE_REQUEST: "Get incoming ride request while the app is in background",
  NEED_IT_TO_DISABLE_BATTERY_OPTIMIZATION_FOR_THE_APP: "Recommended, enables the app to run in background for longer",
  NEED_IT_TO_AUTOSTART_YOUR_APP: "Helps by keeping the app running in background",
  NEED_IT_TO_ENABLE_LOCATION: "Namma Yatri Partner collect location data to enable share your location to monitor driver current location, even when the app is closed or not in use.",
  OVERLAY_TO_DRAW_OVER_APPLICATIONS: "Draw over applications",
  BATTERY_OPTIMIZATIONS: "Battery Optimization",
  AUTO_START_APPLICATION_IN_BACKGROUND: "Autostart in background",
  LOCATION_ACCESS: "Location Access",
  ENTER_RC_NUMBER: "Enter RC  Number",
  WHERE_IS_MY_RC_NUMBER: "Where is my RC Number?",
  STEP: "Step",
  PAID: "Paid",
  ENTERED_WRONG_OTP: "Entered wrong OTP",
  OTP_INVALID_FOR_THIS_VEHICLE_VARIANT : "Invalid OTP - Vehicle type is not matching with ride type",
  COPIED: "Copied",
  BANK_NAME: "Bank Name",
  AADHAR_DETAILS: "Aadhar Details",
  AADHAR_NUMBER: "Aadhar Number",
  FRONT_SIDE_IMAGE: "Front Side Image",
  BACK_SIDE_IMAGE: "Back Side Image",
  STILL_NOT_RESOLVED: "Still not resolved? Call Us",
  CASE_TWO: "b) To the ",
  NON_DISCLOUSER_AGREEMENT: "no discloure agreement",
  DATA_COLLECTION_AUTHORITY: "c) I hereby appoint and authorize Juspay to collect my information and by continuing, I agree to the Terms of Use and Privacy Policy.",
  SOFTWARE_LICENSE: "Software License",
  LOAD_MORE: "Load More",
  ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: "Are you sure you want to logout?",
  GO_BACK: "Go Back",
  THANK_YOU_FOR_REGISTERING_US: "Thank You for register with us!",
  UNFORTANUTELY_WE_ARE_NOT_AVAILABLE__YET_FOR_YOU: "Unfortunately, we are not available yet for you. We’ll notify you soon.",
  ARE_YOU_SURE_YOU_WANT_TO_END_THE_RIDE: "Are you sure you want to end the ride?",
  EMPTY_RIDES: "Empty Rides",
  YOU_HAVE_NOT_TAKEN_A_TRIP_YET: "You haven't taken a trip yet",
  BOOK_NOW: "Book Now",
  RESEND_OTP_IN: "Resend OTP in ",
  WE_NEED_ACCESS_TO_YOUR_LOCATION: "We need access to your location!",
  YOUR_LOCATION_HELPS_OUR_SYSTEM: "Your location helps our system to map down all the near by autos and get you the quickest ride possible.",
  NO_INTERNET_CONNECTION: "No Internet Connection",
  PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN: "Please check you internet connection and try again",
  TRY_AGAIN: "Try Again",
  GRANT_ACCESS: "Grant Access",
  YOUR_LIMIT_EXCEEDED_TRY_AGAIN_AFTER_10_MIN: "You exceed limit ,Try again after 10min ",
  ENTER_REFERRAL_MOBILE_NUMBER: "Enter Referral Mobile Number",
  APPLY: "Apply",
  HAVE_A_REFERRAL: "Have a referral?",
  ADD_HERE: "Add here",
  REFERRAL_APPLIED: "Referral applied!",
  SMALLEDIT: "edit",
  ADD_DRIVING_LICENSE: "Add Driving License",
  HELP: "Help?",
  INVALID_DL_NUMBER: "Invalid DL Number",
  DRIVING_LICENSE_NUMBER: "Driving Licence Number",
  RE_ENTER_DRIVING_LICENSE_NUMBER: "Re-enter Driving Licence Number",
  ENTER_DL_NUMBER: "Enter DL Number",
  SELECT_DATE_OF_BIRTH: "Select date of birth",
  DATE_OF_BIRTH: "Date of Birth",
  WATCH_A_TUTORIAL_FOR_EASY_REGISTRATION: "Watch a tutorial for easy \nregistration",
  ENTER_MINIMUM_FIFTEEN_CHARACTERS: "Enter minium 15 characters",
  ADD_YOUR_FRIEND: "Add your friend",
  PLEASE_WAIT_WHILE_VALIDATING_THE_IMAGE: "Please wait while validating the image",
  VALIDATING: "Validating",
  VERIFICATION_PENDING: "Verification Pending",
  VERIFICATION_FAILED: "Verification Failed",
  NO_DOC_AVAILABLE: "No document available",
  ISSUE_WITH_DL_IMAGE: "There seems to be some issue with your DL image, Our support team will contact you soon.",
  STILL_HAVE_SOME_DOUBT: "Still have some doubt?",
  ISSUE_WITH_RC_IMAGE: "There seems to be some issue with your RC image, Our support team will contact you soon.",
  PLEASE_CHECK_FOR_IMAGE_IF_VALID_DOCUMENT_IMAGE_OR_NOT: "Please check for image if valid Document image or not",
  OOPS_YOUR_APPLICATION_HAS_BEEN_REJECTED: "Ooops! Your application has been rejected. Please try again",
  INVALID_DRIVING_LICENSE: "Invalid Driving License",
  LIMIT_EXCEEDED_FOR_DL_UPLOAD: "Limit exceed for DL upload",
  INVALID_VEHICLE_REGISTRATION_CERTIFICATE: "Invalid Vehicle Registration Certificate",
  LIMIT_EXCEEDED_FOR_RC_UPLOAD: "Limit exceed for RC upload",
  YOUR_DOCUMENTS_ARE_APPROVED: "Your documents are approved. Support team will enable your account sooner. You can also call support team to enable your account",
  APPLICATION_STATUS: "Application Status",
  FOR_SUPPORT: "For Support",
  CONTACT_US: " contact us",
  IMAGE_VALIDATION_FAILED: "Validation of Image failed",
  IMAGE_NOT_READABLE: "Image is not readable",
  IMAGE_LOW_QUALITY: "Image quality is not good",
  IMAGE_INVALID_TYPE: "Provided image type doesn't match with actual type",
  IMAGE_DOCUMENT_NUMBER_MISMATCH: "Document number in this image is not matching with input",
  IMAGE_EXTRACTION_FAILED: "Image extraction failed",
  IMAGE_NOT_FOUND: "Image not found",
  IMAGE_NOT_VALID: "Image not valid",
  DRIVER_ALREADY_LINKED: "Other doc is already linked with driver",
  DL_ALREADY_UPDATED: "No action required. Driver license is already linked to driver",
  RC_ALREADY_LINKED: "Vehicle RC not available. Linked to other driver",
  RC_ALREADY_UPDATED: "No action required. Vehicle RC is already linked to driver",
  DL_ALREADY_LINKED: "Driver license not available. Linked to other driver",
  SOMETHING_WENT_WRONG: "Something went wrong",
  PICKUP: "Pickup",
  TRIP: "Trip",
  CURRENTLY_WE_ALLOW_ONLY_KARNATAKA_REGISTERED_NUMBER: "RC location is not matching with your location",
  UPDATED_AT: "Map updated at",
  TRIP_COUNT: "Trip Count",
  TODAYS_EARNINGS: "Earnings",
  BONUS_EARNED : "Bonus Earned",
  GOT_IT : "Got It!",
  WHAT_IS_NAMMA_YATRI_BONUS : "What is Bonus?",
  BONUS_PRIMARY_TEXT : "Namma Yatri Bonus is the  additional amount you have  earned above the meter charge in the form of pickup charges,  customer tips and driver additions.",
  BONUS_SECONDARY_TEXT : "The Namma Yatri  Bonus amount is part of your total earnings.",
  DATE_OF_REGISTRATION: "Date Of Registration",
  SELECT_DATE_OF_ISSUE: "Select date of issue",
  DATE_OF_ISSUE: "Date Of Issue",
  PROVIDE_DATE_OF_ISSUE_TEXT: "Sorry we could't validate your detail, Please provide<b> Date of issue </b> to get your Driving License validated.",
  PROVIDE_DATE_OF_REGISTRATION_TEXT: "Sorry we could't validate your detail, Please provide<b> Date of Registration </b> to get your Vehicle details validated.",
  SELECT_DATE_OF_REGISTRATION: "Select date of registration",
  SAME_REENTERED_RC_MESSAGE: "Please make sure re-entered RC number is same as RC number provided above",
  SAME_REENTERED_DL_MESSAGE: "Re-entered DL number doesn't match with the DL number provided above",
  WHERE_IS_MY_ISSUE_DATE: "Where is my Issue Date?",
  WHERE_IS_MY_REGISTRATION_DATE: "Where is the Registration Date?",
  EARNINGS_CREDITED_IN_ACCOUNT: "Your earnings will be credited in this account",
  INVALID_PARAMETERS: "Invalid Parameters",
  UNAUTHORIZED: "Unauthorized",
  INVALID_TOKEN: "Invalid Token",
  SOME_ERROR_OCCURED_IN_OFFERRIDE: "Some error occured in offerRide",
  SELECT_VEHICLE_TYPE: "Select Vehicle Type",
  RIDE: "Ride",
  NO_LOCATION_UPDATE: "No location update",
  GOT_IT_TELL_US_MORE: "Got it, Tell us more ?",
  WRITE_A_COMMENT: "Write a comment",
  HOW_WAS_YOUR_RIDE_WITH: "How was your ride with",
  RUDE_BEHAVIOUR: "Rude Behaviour",
  LONG_WAITING_TIME: "Longer Wait Time",
  DIDNT_COME_TO_PICUP_LOCATION: "Didn’t come to pickup location",
  HELP_US_WITH_YOUR_REASON: "Help us with your reason",
  MAX_CHAR_LIMIT_REACHED: "Max character limit reached,",
  SHOW_ALL_OPTIONS: "Show all options",
  UPDATE_REQUIRED: "Update Available",
  PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE: "We're excited to announce that there's a new update available for our app. This update includes a fresh new design and several new features to make your experience even better.",
  NOT_NOW: "Not now",
  OF: "of",
  DROP: "Drop",
  PLEASE_WAIT: "Please wait",
  SETTING_YOU_OFFLINE: "We are setting you offline",
  SETTING_YOU_ONLINE: "We are setting you online",
  SETTING_YOU_SILENT : "We are setting you silent",
  VIEW_BREAKDOWN: "View Breakdown",
  APP_INFO: "App Info",
  OTHER: "Other",
  VEHICLE_ISSUE: "Vehicle issue",
  FARE_UPDATED: "Fare updated",
  FREQUENT_CANCELLATIONS_WILL_LEAD_TO_LESS_RIDES: "Frequent cancellations will lead to less rides and lower rating",
  CONTINUE: "Continue",
  CONFIRM_PASSWORD: "Confirm Password",
  DEMO_MODE: "Demo Mode",
  PASSWORD: "Password",
  ENTER_DEMO_MODE_PASSWORD: "Enter Demo Mode Password",
  DEMO_MODE_DISABLED: "Demo mode disabled",
  ONLINE_VIA_DEMO_MODE: "Online (Demo)",
  MORE: "more",
  LESS: "less",
  YOU_ARE_AT_PICKUP: "You are at pickup location",
  WAITING_FOR_CUSTOMER: "You are waiting for ",
  CUSTOMER_NOTIFIED: "Customer Notified",
  I_ARRIVED: "I've Arrived",
  ESTIMATED_RIDE_FARE: "Estimated Ride Fare: ",
  PICKUP_TOO_FAR: "Pickup too far",
  CUSTOMER_NOT_PICKING_CALL: "Customer not picking call",
  TRAFFIC_JAM: "Traffic jam",
  CUSTOMER_WAS_RUDE: "Customer was rude",
  ALL_MESSAGES: "All Messages",
  MESSAGES: "Alerts",
  ADD_A_COMMENT: "Add a comment",
  POST_COMMENT: "Post Comment",
  ENTER_YOUR_COMMENT: "Enter your comment",
  NO_NOTIFICATIONS_RIGHT_NOW: "No notifications right now!",
  NO_NOTIFICATIONS_RIGHT_NOW_DESC: "We will let you know when there are new any notifications",
  ALERTS: "Alerts",
  YOUR_COMMENT: "Your comment",
  SHOW_MORE: "Show More",
  LOAD_OLDER_ALERTS: "Load Older Alerts",
  CONTEST: "Contest",
  YOUR_REFERRAL_CODE_IS_LINKED: "Your Referral Code is Linked!",
  YOU_CAN_NOW_EARN_REWARDS: "You can now earn rewards for referring customers!",
  COMING_SOON: "Coming Soon!",
  COMING_SOON_DESCRIPTION: "We are working on getting you on board the referral program. Check out the alerts page for more info. ",
  REFERRAL_CODE: "Referral Code",
  REFERRAL_CODE_HINT: "Enter 6-digit Referral Code",
  CONFIRM_REFERRAL_CODE: "Confirm Referral Code",
  CONFIRM_REFERRAL_CODE_HINT: "Re-enter Referral Code",
  YOUR_REFERRAL_CODE: "Your Referral Code",
  FIRST_REFERRAL_SUCCESSFUL: "First Referral Successful!\nReward Unlocked!",
  AWAITING_REFERRAL_RIDE: "Awaiting referral ride",
  CHECK_THIS_SPACE_WHEN_YOU_GET_REFERRAL_ALERT: "Check this space when you \nget a referral alert",
  REFERRED_CUSTOMERS: "Referred Customers",
  ACTIVATED_CUSTOMERS: "Activated Customers",
  REFERRAL_CODE_LINKING: "Referral Code Linking",
  CONTACT_SUPPORT: "Contact Support",
  CALL_SUPPORT: "Call Support",
  YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT: "You are about to place a call to the Namma Yatri Support Team. Do you want to proceed?",
  REFERRAL_ENROLMENT: "Referral Enrolment",
  REFERRALS: "Referrals",
  LINK_REFERRAL_CODE: "Link Referral Code",
  DRIVER_DETAILS: "Driver Details",
  FOR_UPDATES_SEE_ALERTS: "For updates, see Alerts",
  SHARE_OPTIONS: "Share Options",
  ENTER_PASSWORD: "Enter Password",
  YOUR_VEHICLE: "Your Vehicle",
  BOOKING_OPTIONS: "Booking Option",
  CONFIRM_AND_CHANGE: "Confirm & Change",
  OTP_: "OTP",
  MAKE_YOURSELF_AVAILABLE_FOR : "Make Yourself Available for",
  SILENT_MODE_PROMPT : "If you don't want to be disturbed, you may switch to silent mode instead",
  GO_SILENT : "Go Silent",
  TRY_SILENT_MODE : "Try silent mode?",
  RIDE_FARE : "Ride Fare" ,
  RIDE_DISTANCE : "Ride Distance",
  START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS : "Start your chat using these quick chat suggestions",
  START_YOUR_CHAT_WITH_THE_DRIVER : "Start your chat with the driver",
  MESSAGE : "Message",
  I_AM_ON_MY_WAY : "I'm on my way",
  GETTING_DELAYED_PLEASE_WAIT : "Getting delayed, Please wait",
  UNREACHABLE_PLEASE_CALL_BACK : "Unreachable, Please call back",
  ARE_YOU_STARING : "Are you starting?",
  PLEASE_COME_SOON : "Please come soon",
  OK_I_WILL_WAIT : "Ok, I'll wait",
  I_HAVE_ARRIVED : "I've arrived",
  PLEASE_COME_FAST_I_AM_WAITING : "Please come fast, I'm waiting",
  PLEASE_WAIT_I_WILL_BE_THERE : "Please wait, I'll be there",
  LOOKING_FOR_YOU_AT_PICKUP : "Looking for you at pick-up",
  SILENT : "Silent",
  GO_ONLINE : "GO!",
  GO_ONLINE_PROMPT : "You are currently offline.\nTo get ride requests, go online now!",
  LIVE_DASHBOARD : "Live Stats Dashboard",
  CLICK_TO_ACCESS_YOUR_ACCOUNT : "Click here to access your account",
  ADD_ALTERNATE_NUMBER : "Add Alternate Number",
  ENTER_ALTERNATE_MOBILE_NUMBER : "Enter Alternate Mobile Number",
  EDIT_ALTERNATE_MOBILE_NUMBER : "Edit Alternate Mobile Number",
  PLEASE_ENTER_A_VALID_10_DIGIT_NUMBER : "Please enter a valid 10-digit number",
  ALTERNATE_MOBILE_NUMBER : "Alternate Mobile Number",
  REMOVE : "Remove",
  REMOVE_ALTERNATE_NUMBER : "Remove Alternate Number",
  ARE_YOU_SURE_YOU_WANT_TO_REMOVE_YOUR_ALTERNATE_MOBILE_NUMBER : "Are you sure you want to remove your alternate mobile number?",
  YES_REMOVE_IT : "Yes, Remove It",
  NUMBER_REMOVED_SUCCESSFULLY : "Number Removed Successfully",
  NUMBER_ADDED_SUCCESSFULLY : "Number Added Successfully",
  NUMBER_EDITED_SUCCESSFULLY : "Number Updated Successfully",
  ALTERNATE_MOBILE_OTP_LIMIT_EXCEED : "OTP Limit Exceeded , Enter Number And OTP Again",
  WRONG_OTP : "Please Enter Valid OTP ",
  ATTEMPTS_LEFT : " attempts left",
  ATTEMPT_LEFT : " attempt left",
  OTP_LIMIT_EXCEEDED : "OTP Limit Exceeded",
  OTP_LIMIT_EXCEEDED_MESSAGE : "You have reached your OTP limit. Please try again after 10 minutes.",
  TRY_AGAIN_LATER : "Try Again Later",
  NUMBER_ALREADY_EXIST_ERROR : "Number linked to another account! Please use another number",
  ADD_ALTERNATE_NUMBER_IN_MEANTIME : "This process can take upto 2 working days \nto be completed. In the meantime,  you \ncan add an alternate mobile number.",
  VERIFICATION_IS_TAKING_A_BIT_LONGER : "Looks like your verification is taking a bit \nlonger than expected.\nYou can contact support to help you out.",
  COMPLETE_ONBOARDING : "Complete Onboarding",
  PERSON_WITH_THIS_NUMBER_ALREADY_EXISTS : "Person with this mobile number already exists.",
  DEMO : "Demo",
  PLEASE_ASK_THE_CUSTOMER_FOR_THE_OTP : "Please ask the customer for the OTP",
  DELETE : "Delete",
  VIEW : "View",
  ISSUE_NO : "Issue No.",
  ADD_VOICE_NOTE : "Add Voice Note",
  VOICE_NOTE_ADDED : "Voice Note Added",
  SUBMIT_ISSUE_DETAILS : "Submit Issue Details",
  IMAGE_PREVIEW : "Image Preview",
  RIDE_REPORT_ISSUE : "Select ride to report issue on",
  ADDED_IMAGES : "Added Images",
  NO_IMAGES_ADDED : "No Images Added",
  ASK_DETAILS_MESSAGE : "Please give some more details. You can also send images or voice notes to elaborate better.",
  ASK_DETAILS_MESSAGE_REVERSED : "Please share more details on the lost item. You can also send images or voice notes to elaborate better.",
  SELECT_OPTION : "Please tell us if you are facing any of these",
  SELECT_OPTION_REVERSED : "How do you wish to resolve this issue?",
  ISSUE_SUBMITTED_MESSAGE : "Details received! Our team will call you within 24 hours to help you out with your issue.",
  I_DONT_KNOW_WHICH_RIDE : "I don't know which ride",
  REPORT_ISSUE_CHAT_PLACEHOLDER : "Describe your issue. Namma Yatri will try to resolve it in under 24 hours.",
  ADDED_VOICE_NOTE : "Added Voice Note",
  NO_VOICE_NOTE_ADDED : "No Voice Note Added",
  CALL_CUSTOMER_TITLE : "Call Customer",
  CALL_CUSTOMER_DESCRIPTION : "You are about to place a call to the Customer. Do you want to proceed?",
  PLACE_CALL : "Place Call",
  ADD_IMAGE : "Add Image(s)",
  ADD_ANOTHER : "Add Another",
  IMAGES_ADDED : "Images Added",
  ISSUE_SUBMITTED_TEXT : "Hold on! We are working on solving your issue",
  CHOOSE_AN_OPTION : "Choose an option to continue",
  IMAGE_ADDED : "Image Added",
  DONE : "Done",
  RECORD_VOICE_NOTE : "Record Voice Note",
  HELP_AND_SUPPORT : "Help & Support",
  MORE_OPTIONS : "More Options",
  ONGOING_ISSUES : "Ongoing issues",
  RESOLVED_ISSUES : "Resolved Issues",
  RESOLVED_ISSUE : "Resolved issue",
  ONGOING_ISSUE : "Ongoing Issues",
  LOST_ITEM : "Lost Item",
  RIDE_RELATED_ISSUE : "Ride Related Issue",
  APP_RELATED_ISSUE : "App Related Issue",
  FARE_RELATED_ISSUE : "Fare Related Issue",
  MAX_IMAGES : "Maximum 3 images can be uploaded",
  ISSUE_NUMBER : "Issue No.   ",
  REMOVE_ISSUE : "Remove Issue" ,
  CALL_SUPPORT_NUMBER : "Contact Support",
  YEARS_AGO : " years ago",
  MONTHS_AGO : " months ago",
  DAYS_AGO : " days ago",
  HOURS_AGO : " hrs ago",
  MIN_AGO : " min ago",
  SEC_AGO : " sec ago",
  LOADING : "Loading",
  APP_RELATED : "App Related",
  FARE : "Fare Related",
  RIDE_RELATED : "Ride Related",
  LOST_AND_FOUND : "Lost and Found",
  REPORT_LOST_ITEM : "Report Lost Item",
  SELECT_YOUR_GENDER: "Select Your Gender",
  FEMALE: "Female",
  MALE: "Male",
  PREFER_NOT_TO_SAY: "Prefer not to say",
  GENDER : "Gender",
  SET_NOW : "Set Now",
  COMPLETE_YOUR_PROFILE_AND_FIND_MORE_RIDES : "Complete your profile and find more rides!",
  UPDATE_NOW : "Update Now",
  CONFIRM : "Confirm",
  GENDER_UPDATED : "Gender Updated",
  CORPORATE_ADDRESS : "Corporate Address",
  CORPORATE_ADDRESS_DESCRIPTION : "Juspay Technologies Private Limited <br> Girija Building, Number 817, Ganapathi Temple Rd, 8th Block, Koramangala, Bengaluru, Karnataka 560095, India.",
  CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL :  "Website: <u>https://nammayatri.in/</u>",
  REGISTERED_ADDRESS : "Registered Address",
  REGISTERED_ADDRESS_DESCRIPTION : "Juspay Technologies Private Limited <br> Stallion Business Centre, No. 444, 3rd & 4th Floor, 18th Main, 6th Block, Koramangala Bengaluru, Karnataka- 560095, India.",
  REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL : "Website: <u>https://nammayatri.in/</u>",
  ZONE_CANCEL_TEXT_DROP : "Your customer is probably in a rush to reach the metro station on time! \n We urge you not to cancel.",
  ZONE_CANCEL_TEXT_PICKUP : "Your customer is probably in a rush to reach their destination. \n We urge you not to cancel.",
  RANKINGS : "Contest",
  GETTING_THE_LEADERBOARD_READY : "Getting the leaderboard ready!",
  PLEASE_WAIT_WHILE_WE_UPDATE_THE_DETAILS : "Please wait while we update the details",
  LAST_UPDATED : "Last Updated: ",
  CONGRATULATIONS_YOU_ARE_RANK : "Congratulations! You are RANK ",
  YOU : " (you)",
  DAILY : "Daily",
  WEEKLY : "Weekly",
  ACCEPT_RIDES_TO_ENTER_RANKINGS : "Accept rides to enter rankings!",
  OTP_HAS_BEEN_RESENT : "OTP has been resent",
  OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_RESENDING_OTP : "OTP entering limit exhausted, please try resending OTP",
  OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER : "OTP resend limit exhausted, please try again later",
  OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN : "OTP page has been expired, please request OTP again",
  SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN : "Something went wrong, please try again",
  INVALID_REFERRAL_CODE : "Invalid referal code",
  ISSUE_REMOVED_SUCCESSFULLY : "Issue removed successfully",
  OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER : "OTP entering limit exhausted, please try again later",
  TOO_MANY_ATTEMPTS_PLEASE_TRY_AGAIN_LATER : "Too many invalid attempts, please try again later",
  INVALID_REFERRAL_NUMBER : "Invalid Referral Number",
  SOMETHING_WENT_WRONG_TRY_AGAIN_LATER : "Something went wrong, please try again later",
  WAIT_TIME : "Wait Time",
  WAIT_TIMER : "Wait Timer",
  HOW_LONG_WAITED_FOR_PICKUP : "Shows you how long you\nhave waited at pickup.",
  CUSTOMER_WILL_PAY_FOR_EVERY_MINUTE : "The customer will pay ₹1.5\nfor every minute of wait time after \nfirst 3 minutes",
  OTHERS : "Others",
  ENTER_SECOND_SIM_NUMBER : "Enter Second SIM Number",
  ALTERNATE_NUMBER : "Alternate Number",
  SELECT_THE_LANGUAGES_YOU_CAN_SPEAK : "Select the languages you can speak",
  OTP_RESEND_LIMIT_EXCEEDED : "Resend OTP Limit Exceeded",
  LIMIT_EXCEEDED_FOR_ALTERNATE_NUMBER : "Please try again after sometime",
  ALTERNATE_NUMBER_CANNOT_BE_ADDED : "Alternate Number Cannot Be Added",
  OTP_RESENT: "OTP Resent",
  SEDAN : "Sedan",
  SUV : "SUV",
  HATCHBACK : "Hatchback",
  AUTO_RICKSHAW : "Auto Rickshaw",
  TAXI : "Non-AC Taxi",
  TAXI_PLUS : "AC Taxi",
  MY_PROFILE : "My Profile",
  SETTINGS : "Settings",
  REG_NUMBER : "Reg. Number",
  TYPE : "Type",
  MODEL_NAME : "Model Name",
  COLOUR : "Colour",
  BADGES : "Badges",
  CALL_CUSTOMER_SUPPORT : "Call Customer Support",
  EDIT_RC : "Edit RC",
  DELETE_RC : "Delete RC",
  DEACTIVATE_RC : "Deactivate RC",
  ACTIVATE_RC : "Activate RC",
  ACTIVE_RC_ON_ANOTHER_DRIVER : " is active on another driver account!",
  CALL_DRIVER_OR_CONTACT_SUPPORT : "Call the driver to deactivate RC or contact support if driver is not reachable",
  CALL_DRIVER : "Call Driver",
  SKIP : "Skip",
  ACTIVE_STR : "Active",
  INACTIVE_RC : "Inactive",
  CONFIRMATION_FOR_DELETING_RC : "Are you sure you want to delete your RC",
  CONFIRMATION_FOR_DEACTIVATING_RC : "Are you sure you want to deactivate your RC- ",
  CONFIRMATION_FOR_ACTIVATING_RC : "Are you sure you want to activate RC- ",
  YES_DELETE : "Yes, Delete",
  ADD_NEW_RC : "Add RC",
  CONNECT_CALL_ANONYMOUSLY: "We will attempt to connect you anonymously with the driver please introduce yourself before requesting to deactivate the rc.",
  YES_ACTIVATE : "Yes, Activate",
  YES_DEACTIVATE : "Yes, Deactivate",
  THIS_WILL_DEACTIVATE_CURRENTLY_ACTIVE_RC : "This will deactivate your currently active RC.",
  REMOVED : "Removed",
  IS_ACTIVE_NOW : " is active now.",
  DEACTIVATED : "Deactivated",
  LANGUAGE_UPDATED : "Language Updated",
  SINGLE_RC_CANNOT_BE_DELETED : "Single RC cannot be deleted",
  CANCELLATION_RATE : "Cancellation Rate",
  RIDES_CANCELLED : "Rides Cancelled",
  EARNINGS_MISSED : "Earnings Missed",
  SUMMARY : "Summary",
  NAMMA_BONUS  : "Namma Bonus",
  TRIPS_COMPLETED : "Trips Completed",
  LATE_NIGHT_TRIPS  : "Late night trips",
  ABOUT_ME  : "About me",
  ABOUT_VEHICLE : "About vehicle",
  ADD : "Add",
  YEARS_OLD  : "years Old",
  HOMETOWN  : "Home Town",
  MISSED_OPPORTUNITY : "Missed Opportunities",
  HOW_OLD_IS_YOUR_VEHICLE : "How old is your vehicle (in years)?",
  ENTER_NAME_OF_VEHICLE : "Enter the name of your vehicle",
  NEW_ : "NEW",
  WITH : "with",
  CHOOSE_LANGUAGE : "Choose Language",
  TOTAL_MONEY_COLLECTED : "Total Money Collected",
  FARE_EARNED_OF_THE_DAY : "Fare Earned for the day",
  GST_PLUS_PAYABLE : "GST + Fee Payable",
  TO_CONTINUE_USING_YATRI_SATHI : "To continue using Yatri Sathi, please complete your payment for",
  PAY : "Pay",
  LATER : "Later",
  GREAT_JOB : "Great Job!",
  YOU_HAVE_COMPLETED_RIDES_YESTERDAY : "You have completed X Rides yesterday!",
  FEE_BREAKUP : "Fee breakup",
  YATRI_SATHI_FEE_PAYABLE_FOR_DATE : "Yatri Sathi fee payable for",
  FEE_CORRESPONDING_TO_THE_DISTANCE : "A fee corresponding to the distance travelled per trip, will be calculated as shown below.",
  PLATFORM_FEE : "Platform Fee",
  GST  : "GST",
  TOTAL_PAYABLE : "Total Payable",
  VIEW_DETAILS : "View Details",
  PAYMENT_SUCCESSFUL : "Payment Successful!",
  PAYMENT_PENDING : "Payment Pending!",
  PAYMENT_FAILED : "Payment Failed!",
  PAYMENT_PENDING_DESC : "Don’t worry, you can still continue taking rides for the day!",
  PAYMENT_FAILED_DESC : "You may retry payment, or make the payment at your nearest Yatri Sathi booth",
  WE_WILL_NOTIFY_WHEN_PAYMENT_SUCCESS : "We will notify when your payment is successful",
  CONTINUE_TAKING_RIDES : "Continue taking rides",
  YOUR_PREVIOUS_PAYMENT_IS_PENDING : "Your  previous payment is still pending",
  GOVERMENT_CHARGES : "Government Charges",
  TODAY : "Today",
  OKAY : "Okay",
  NO_PAYMENT_HISTORY_AVAILABLE : "No payment history available",
  YOU_DONT_HAVE_ANY_PAYMENTS : "You haven’t done any payment yet",
  ENTER_AADHAAR_NUMBER : "Enter Aadhaar Number/UID",
  ENTER_AADHAAR_OTP_ : "Enter Aadhaar OTP",
  AADHAAR_LINKING_REQUIRED : "Aadhaar linking required",
  AADHAAR_LINKING_REQUIRED_DESCRIPTION : "To start driving for Yatri Sathi, please \n link your Aadhaar ID",
  BY_CLICKING_THIS_YOU_WILL_BE_AGREEING_TO_OUR_TC : "By clicking Continue, you agree to our ",
  TERMS_AND_CONDITIONS_SHORT : "T&C",
  TC_TAIL : "",
  OTP_SENT_TO_AADHAAR_NUMBER: "OTP sent to mobile number linked with your aadhar",
  ENTER_SIX_DIGIT_OTP : "Enter six digit OTP",
  LINK_AADHAAR_ID : "Link Aadhaar ID",
  NO_MOBILE_NUMBER_REGISTERED : "Aadhaar number does not have a mobile number registered with it.",
  EXCEED_OTP_GENERATION_LIMIT : "Exceeded Maximum OTP generation Limit. Please try again in some time.",
  AADHAAR_NUMBER_NOT_EXIST : "Aadhaar number does not exist.",
  INVALID_OTP : "Invalid OTP",
  NO_SHARE_CODE : "No share code provided",
  WRONG_SHARE_CODE : "Wrong share code",
  INVALID_SHARE_CODE : "Invalid share code. Length should be 4 and should only contain numbers.",
  SESSION_EXPIRED : "Session Expired. Please start the process again.",
  OTP_ATTEMPT_EXCEEDED : "OTP attempts exceeded. Please start the process again",
  UPSTREAM_INTERNAL_SERVER_ERROR : "Upstream source/Government source internal server error. Please start the process again.",
  TRANSACTION_ALREADY_COMPLETED : "Transaction already completed. Cannot do further operation on this transaction.",
  ENTER_AADHAAR_DETAILS : "Enter Aadhaar Details",
  GOTO_YOUR_NEAREST_BOOTH : "Please reach out to your nearest booth to get your Aadhaar verified",
  AADHAAR_ALREADY_LINKED : "Aadhaar already linked",
  OPTIONAL : " (Optional)",
  DOWNLOAD_STATEMENT : "Download statement",
  SELECT_A_DATE_RANGE : "Select a date range to download the statement",
  FEE_PAYMENT_HISTORY : "Fee payment history",
  LANGUAGES_SPOKEN : "Languages spoken",
  VIEW_PAYMENT_HISTORY : "View Payment History",
  RIDE_TYPE : "Ride Type",
  PLACE_CALL_REQUEST : "Place Call Request",
  RC_STATUS : "Rc Status",
  RATED_BY_USERS1 : "Rated By",
  RATED_BY_USERS2 : "Users",
  MONTHS : "Months",
  CALL_REQUEST_HAS_BEEN_PLACED : "Your call request has been placed",
  RC_ADDED_SUCCESSFULLY : "RC added Successfully",
  OFFER_APPLIED : "Offer Applied",
  YOUR_EARNINGS : "Your earnings",
  NUMBER_OF_RIDES : "No. of Rides",
  FARE_BREAKUP : "Fare Breakup",
  MY_PLAN : "My Plan",
  YOUR_DUES : "Your Dues",
  YOUR_DUES_DESCRIPTION : "You have set up an autopay to clear your dues. We will automatically try to ensure that your dues are always paid on time.",
  YOUR_DUES_DESCRIPTION_MANUAL : "Please clear your dues before it reaches the limit to continue uninterrupted rides. You can also <b>set up an UPI Autopay</b> for easier, hassle-free payments.",
  CURRENT_DUES : "Current Dues",
  YOUR_LIMIT : "Your Limit",
  DUE_DETAILS : "Due Overview",
  TRIP_DATE : "Trip Date",
  AMOUNT : "Amount",
  VIEW_DUE_DETAILS : "View Due Details",
  SETUP_AUTOPAY : "Setup Autopay",
  CURRENT_PLAN : "CURRENT PLAN",
  ALTERNATE_PLAN : "ALTERNATE PLAN",
  AUTOPAY_DETAILS : "Autopay Details",
  CANCEL_AUTOPAY_STR : "Cancel Autopay",
  WE_MIGHT_BE_LOST : "Uh oh! We might be lost",
  EXEPERIENCING_ERROR : "Experiencing error",
  ENJOY_THESE_BENEFITS : "Enjoy these benefits ",
  CHOOSE_YOUR_PLAN : "Choose a Plan Now!",
  SKIP_FOR_NOW : "Skip For Now",
  NAMMAYATRI_PLANS  : "Namma Yatri Plans",
  SEVEN_DAY_FREE_TRIAL_ACTIVATED : "7-Day FREE TRIAL Activated!",
  TAKE_UNLIMITED_RIDES_FOR_THE_NEXT_SEVEN_DAYS : "Take unlimited rides for the first 7 days",
  EVERY_RIDE_AT_ZERO_COMMISSION : "Every ride at ZERO Commission!",
  EARN_UPTO_PER_DAY : "Earn upto ₹2500 a day!",
  HOW_THIS_WORKS : "How this Works",
  SIGN_UP_FOR_AUTOPAY_BY_PAYING_JUST : "Sign up for Autopay by paying just ₹1",
  GET_REMINDED_ABOUT_YOUR_PLAN_SETUP : "Get reminded about your plan setup",
  FREE_TRIAL_REMINDER : "Day 5: FREE TRIAL reminder",
  PLAN_STARTS : "Day 7: Plan Starts",
  EASY_AUTOMATIC_PAYMENTS_START : "Easy, automatic payments start",
  FREE_UNTIL : "Free until ",
  PER_RIDE : "per ride",
  PER_DAY : "per day",
  OFFER : "Offer",
  OFFERS : "Offers",
  YOU_ARE_ON_THE_FREE_TRIAL : "You are on the FREE TRIAL",
  SETUP_AUTOPAY_BEFORE_THE_TRAIL_PERIOD_EXPIRES : "Setup Autopay before the trial period expires",
  GET_FREE_TRAIL_UNTIL : "Get Free Trial until ",
  CLEAR_DUES : "Clear Dues",
  PAYMENT_PENDING_ALERT : "⚠️ Payment Pending! ⚠️",
  PAYMENT_PENDING_ALERT_DESC : "To continue taking rides on Namma Yatri, clear your payment dues",
  LOW_ACCOUNT_BALANCE : "Low Account Balance",
  LOW_ACCOUNT_BALANCE_DESC : "Your bank account balance is low. Add ₹<X> by today to enjoy uninterrupted rides.",
  OKAY_GOT_IT : "Okay, Got it",
  LIMITED_TIME_OFFER : "Limited Time Offer for you!",
  JOIN_NOW : "Join Now",
  AUTOMATIC_PAYMENTS_WILL_APPEAR_HERE : "Automatic payments will appear here",
  MANUAL_PAYMENTS : "Manual Payments",
  MANUAL_PAYMENTS_WILL_APPEAR_HERE : "Manual payments will appear here",
  NO_AUTOMATIC_PAYMENTS_DESC : "Your autopay history will appear here once you are charged for the same",
  NO_MANUAL_PAYMENTS_DESC : "Your payment history for clearing dues will appear here, if any.",
  PAYMENT_HISTORY : "Payment History",
  TAP_A_PLAN_TO_VIEW_DETAILS : "Tap a plan to view details",
  HOW_IT_WORKS : "How this works?",
  ZERO_COMMISION : "ZERO commission",
  EARN_TODAY_PAY_TOMORROW : "Earn Today, Pay Tomorrow",
  PAY_ONLY_IF_YOU_TAKE_RIDES : "Pay only if you take rides",
  PLAN : "Plan",
  DAY : "Day",
  PLANS : "Plans",
  MANAGE_PLAN : "Manage Plan",
  VIEW_AUTOPAY_DETAILS : "View Autopay Details",
  SWITCH_AND_SAVE : "Switch and Save",
  SWITCH_AND_SAVE_DESC : "You have completed over 7 rides today. Save up to ₹10 by switching to the DAILY UNLIMITED plan",
  SWITCH_NOW : "Switch Now",
  PAYMENT_MODE_CHANGED_TO_MANUAL : "Payment mode changed to manual",
  PAYMENT_MODE_CHANGED_TO_MANUAL_DESC : "<b>You have paused your UPI Autopay. It can be resumed from your UPI app.</b><br>You can also clear your dues manually.",
  AUTOPAY_PAYMENTS : "Autopay Payments",
  TRANSACTION_ON : "Transaction On",
  SUCCESS : "SUCCESS",
  DEBITED_ON : "Debited on",
  RIDES_TAKEN_ON : "Rides on",
  JOIN_PLAN : "Join Plan",
  JOIN_NAMMAA_YATRI : "Join Namma Yatri",
  CANCEL_AUTOPAY_AND_PAY_MANUALLY : "Cancel Autopay and Pay Manually",
  PLAN_ACTIVATED_SUCCESSFULLY : "Plan Activated Successfully",
  DUES_CLEARED_SUCCESSFULLY : "Dues Cleared Successfully",
  NOT_PLANNING_TO_TAKE_RIDES : "Not planning to take rides?",
  RETRY_PAYMENT_STR : "Retry Payment",
  PAUSE_AUTOPAY_STR : "Pause AutoPay",
  SETUP_AUTOPAY_STR : "Setup AutoPay",
  VIEW_RIDE_DETAILS : "View Ride Details",
  ACCOUNT : "Account",
  AUTOPAY_IS_NOT_ENABLED_YET : "Autopay is not enabled yet!",
  ENABLE_AUTOPAY_DESC : "Enable Autopay now to start hassle-free payments!",
  ENABLE_AUTOPAY_NOW : "Enable Autopay Now",
  AUTOPAY_SETUP_PENDING_STR : "Autopay Setup Pending!",
  AUTOPAY_PENDING_DESC_STR : "Wait or retry payment. Extra payment will be refunded.",
  REFRESH_STR : "Check Status",
  TRANSACTION_DETAILS : "Transaction Details",
  RIDE_DETAILS : "Ride Details",
  MY_PLAN_TITLE : "Namma Yatri Plans",
  SWITCH_TO : "Switch to {} Plan",
  PLEASE_TRY_AGAIN : "Please try again",
  PLAN_NOT_FOUND : "Plan not found",
  MANDATE_NOT_FOUND : "Mandate not found",
  ACTIVE_MANDATE_EXISTS : "Active mandate already exists",
  NO_ACTIVE_MANDATE_EXIST : "No active mandate exist",
  NO_PLAN_FOR_DRIVER : "No plan found",
  INVALID_PAYMENT_MODE : "Invalid payment mode",
  INVALID_AUTO_PAY_STATUS : "Invalid autopay status",
  MAX_AMOUNT : "Max Amount",
  FREQUENCY : "Frequency",
  STATRED_ON : "Started On",
  EXPIRES_ON : "Expires On",
  SWITCHED_PLAN : "Switched plan",
  RESUME_AUTOPAY : "Resumed autopay",
  ONETIME : "One time",
  FORTNIGHTLY : "Fortnightly",
  MONTHLY : "Monthly",
  BIMONTHLY : "Bimonthly",
  QUARTERLY : "Quarterly",
  HALFYEARLY : "Half yearly",
  YEARLY : "Yearly",
  ASPRESENTED : "As and when presented",
  DAILY_PER_RIDE_DESC : "No charges till Sep 19",
  FIRST_FREE_RIDE : "First Ride FREE",
  JOIN_THE_UNLIMITED_PLAN : "Join DAILY UNLIMITED plan now to get special discounts",
  MAYBE_LATER : "Maybe Later",
  DO_YOU_WANT_TO_CANCEL : "Do you want to cancel?",
  DO_YOU_WANT_TO_CANCEL_DESC : "You are about to cancel Autopay.\nYou will have to set up autopay again to resume automatic payments.",
  YOUR_PAYMENT_WAS_UNSUCCESSFUL : "Your payment attempt was unsuccessful.",
  PAYMENT_CANCELLED : "You have cancelled your UPI Autopay. You can clear your dues manually.",
  UPI_AUTOPAY_S : "UPI Autopay",
  MANUAL_PAYMENT_STR : "Manual Payment",
  DAILY_UNLIMITED : "DAILY UNLIMITED",
  DAILY_PER_RIDE : "DAILY PER RIDE",
  DAILY_UNLIMITED_PLAN_DESC : "Enjoy UNLIMITED rides, every day",
  DAILY_PER_RIDE_PLAN_DESC : "Up to a maximum of ₹35 per day",
  AUTOPAY_CANCELLED : "Autopay Cancelled",
  NO : "No",
  YES_CANCEL : "Yes, Cancel",
  PAY_TO_JOIN_THIS_PLAN : "Pay only ₹1 to join plan",
  OFFERS_NOT_APPLICABLE : "Offers not applicable unless completed",
  PAUSED_STR : "Paused",
  PENDING_STR : "Pending",
  SWITCH_PLAN_STR : "Switch Plan?",
  PLAN_SWITCHED_TO : "Plan Switched to ",
  OFFERS_APPLICABLE_ON_DAILY_UNLIMITED : "Note: Offers applicable only if Autopay is setup on DAILY UNLIMITED plan",
  DAILY_UNLIMITED_OFFER_NOT_AVAILABLE : "Note: Daily Unlimited offers are not applicable on this plan!", 
  NO_RIDES_NO_CHARGE : "Pay only if you take rides",
  GET_SPECIAL_OFFERS : "Get Special Offers",
  VALID_ONLY_IF_PAYMENT : "valid only if payment is completed",
  HELP_STR : "HELP",
  REFRESH_STRING : "Refresh",
  CHAT_FOR_HELP : "Chat for Help",
  VIEW_FAQs : "View FAQs",
  FIND_HELP_CENTRE : "Find Help Centre",
  CONTACT : "Contact",
  GO_TO_LOCATION : "Go To Location",
  NO_HELP_CENTER_IS_ACTIVE_NOW : "No help center is active right now",
  HELP_CENTERS_LOCATION_WILL_APPEAR_HERE_ONCE_THEY_ARE_ACTIVE : "Help Centers' locations will appear here once they are active",
  SUPPORT : "Support",
  GO_TO_VEHICLE_DETAILS : "Go to Vehicle Details",
  CLOSE: "Close", 
  RC_DEACTIVATED : "RC is Deactivated", 
  RC_DEACTIVATED_DETAILS : "Your RC is currently active on another driver's account. Activate an RC to start taking rides",
  NEED_HELP_JOINING_THE_PLAN : "Need help with joining the plan or Autopay?",
  NEED_HELP : "Need Help?",
  SETUP_AUTOPAY_NOW_TO_GET_SPECIAL_DISCOUNTS  : "Setup Autopay to get special discounts",
  SETUP_NOW : "Setup Now",
  NEED_HELP_CALL_SUPPORT : "Need Help? <span style='color:#2194FF'>Call Support</span>",
  CUSTOMER_HAS_LOW_MOBILITY: "Customer has low mobility",
  CUSTOMER_HAS_DISABILITY: "Customer has a disability",
  CUSTOMER_HAS_LOW_VISION: "Customer has poor vison",
  CUSTOMER_HAS_HEARING_IMPAIRMENT: "Customer has poor hearing",
  HELP_WITH_THEIR_MOBILITY_AID: "Help with their mobility aid",
  PLEASE_ASSIST_THEM_IF_NEEDED: "Please assist them if needed",
  MESSAGE_THEM_AT_PICKUP: "Message them at pickup",
  SOUND_HORN_ONCE_AT_PICKUP: "Sound horn once at pickup",
  PLEASE_CALL_AND_AVOID_CHATS: "Please call and avoid chats",
  PLEASE_CHAT_AND_AVOID_CALLS: "Please chat and avoid calls",
  PLEASE_GO_TO_EXACT_PICKUP: "Please go to exact pick up",
  CUSTOMER_HAS_POOR_VISION_SOUND_HORN_AT_PICKUP : "Customer has poor vision. Please sound horn once at pickup.",
  CUSTOMER_HAS_POOR_HEARING_MESSAGE_THEM_AT_PICKUP : "Customer has poor hearing. Please message them once at pickup.",
  CUSTOMER_HAS_LOW_MOBILITY_STORE_THEIR_SUPPORT_AT_PICKUP : "Customer has low mobility. Please help them store their supports behind the passenger seat.",
  CUSTOMER_HAS_DISABILITY_PLEASE_ASSIST_THEM : "Customer has a disability. Please assist them as you can.",
  CUSTOMER_MAY_NEED_ASSISTANCE : "Customer may need assistance",
  LEARN_MORE : "Learn More",
  CUSTOMER_HAS_LOW_MOBILITY_GO_TO_EXACT_LOC : "Customer has low mobility. Please go to exact pick up location.",
  CUSTOMER_HAS_POOR_HEARING_CHAT_WITH_THEM_INSTEAD_OF_CALLING : "Customer has poor hearing. Please chat with them instead of calling.",
  CUSTOMER_HAS_LOW_VISION_CALL_THEM_INSTEAD_OF_CHATTING : "Customer has poor vision. Please call them instead of chatting.",
  PLEASE_HELP_THEM_AS_YOU_CAN : "Please help them as you can",
  LEARN_HOW_YOU_CAN_HELP_CUSTOMERS_REQUIRING_SPECIAL_ASSISTANCE : "Learn how you can help customers requiring special assistance",
  ASSISTANCE_REQUIRED : "Assistance Required",
  SAVED_DUE_TO_ZERO_COMMISSION : "Saved due to\nZero Commission", 
  TIP_EARNED_FROM_CUSTOMER : "Tip earned\nfrom customer",
  COLLECT_VIA_CASE_UPI : "Collect via Cash/UPI",
  FARE_COLLECTED :  "Fare Collected",
  RATE_YOUR_RIDE_WITH1 : "Rate your ride with" ,
  RATE_YOUR_RIDE_WITH2 : "",
  HELP_US_WITH_YOUR_FEEDBACK : "Helps us with your feedback (Optional)",
  COLLECT_CASH : "Collect Cash",
  ONLINE_PAYMENT : "Online Payment",
  RIDE_COMPLETED : "Ride Completed",
  SUBMIT_FEEDBACK : "Submit Feedback",
  BADGE_EARNED : "Badge Earned",
  PURPLE_RIDE_CHAMPION : "Purple Ride Champion",
  PURPLE_RIDE : "Purple Ride",
  PROCEED_TO_CHAT : "Proceed to Chat",
  PLEASE_CONSIDER_CALLING_THEM : "They might not be able to read the chats. Please consider calling them",
  JOIN_A_PLAN_TO_START_EARNING : "Join a Plan to Start Earning!",
  GO_ONLINE_PROMPT_SUBSCRIBE : "You are currently offline.\nJoin a plan to take rides",
  GO_ONLINE_PROMPT_PAYMENT_PENDING : "You are currently offline.\nComplete your plan payment to take rides",
  COMPLETE_PAYMENT_TO_CONTINUE : "To continue using Yatri Sathi, please complete your payment",
  PENDING_CAPS : "PENDING",
  FAILURE : "FAILURE",
  PAYMENT_MODE : "Payment Mode",
  TXN_ID : "Order ID",
  AMOUNT_PAID : "Amount Paid",
  NOTIFICATION_SCHEDULED : "Notification Scheduled!",
  MANUAL_DUES : "Manual dues",
  AUTOPAY_IN_PROGRESS : "Autopay in progress",
  MANUAL_DUE_OVERVIEW : "Manual Due Overview",
  AUTOPAY_DUE_OVERVIEW : "Autopay Due Overview",
  MANUAL_DUE_AS_AUTOPAY_EXECUTION_FAILED : "Manual due as autopay execution failed",
  CLEAR_MANUAL_DUES : "Clear Manual Dues",
  DUE_OVERVIEW : "Due Overview",
  MANUAL_DUE_DETAILS : "Manual Due Details",
  AUTOPAY_DUE_DETAILS : "Autopay Due Details",
  SWITCHED_TO_MANUAL : "*Payment mode switched to manual since autopay could not be fulfilled",
  SPLIT_PAYMENT : "*Payment has been split to execute autopay",
  GST_INCLUDE : "(incl. 18% GST)",
  SCHEDULED_AT : "Scheduled at",
  PAYMENT_STATUS : "Payment Status",
  NOTIFICATION_ATTEMPTING :  "Notification Attempting", 
  EXECUTION_SCHEDULED :  "Execution Scheduled", 
  EXECUTION_ATTEMPTING : "Execution Attempting", 
  EXECUTION_SUCCESS : "Execution Success",
  SCHEDULED : "SCHEDULED",
  ONE_TIME_SETTLEMENT : "Do a one-time Payment",
  PAYMENT_SCHEDULED : "Payment Scheduled",
  RETRY_AUTOPAY : "Retry Autopay",
  RETRY_STR : "Retry ",
  ONGOING_PAYMENT_EXECUTION : "There is ongoing manual payment pls wait",
  OFFER_CARD_BANNER_TITLE : "Setup Autopay and pay only ₹15/day until {}",
  OFFER_CARD_BANNER_DESC : "Pay only ₹15/Day until Nov 1",
  OFFER_CARD_BANNER_ALERT : "Your Autopay Setup is Pending!",
  OR : "OR",
  COLLECT_CASH_DIRECTLY : "Collect cash directly ",
  OR_COLLECT_CASH_DIRECTLY : "or Collect cash directly",
  SETUP_AUTOPAY_TO_ACCEPT_PAYMENT : "To accept payments directly to your bank account, setup  Autopay on your Plan",
  DOWNLOAD_QR : "Download QR",
  USE_THIS_QR_TO_COLLECT_PAYMENT : "You can use this QR Code to collect payment after the ride ends.",
  AMOUNT_WILL_DEPOSITED_TO_BANK_ACCOUNT : "The amount will be deposited into the bank account that you are using for UPI Autopay",
  GET_DIRECTLY_TO_YOUR_BANK_ACCOUNT : "Get direct payment to UPI ID",
  PAYMENT : "Payment",
  QR_CODE : "QR Code",
  GET_QR_CODE : "Get QR Code",
  EXECUTION_FAILED : "Execution Failed", 
  NOTIFICATION_FAILED : "Notification Failed",
  PAY_NOW : "Pay Now",
  CLEAR_DUES_BANNER_TITLE : "Clear your Dues (₹{}) \nto enjoy non-stop rides",
  COLLECT_VIA_UPI_QR_OR_CASH : "Collect via UPI QR or Cash",
  TRANSACTION_DEBITED_ON : "Transaction Debited On",
  TRANSACTION_ATTEMPTED_ON : "Transaction Attempted On",
  AUTOPAY_SETUP_AND_PAYMENT_SUCCESSFUL : "Autopay Setup & Payment Successful!",
  AUTOPAY_SETUP_SUCCESSFUL : "Autopay Setup Successful!",
  AUTOPAY_SETUP_AND_PAYMENT_PENDING : "Autopay Setup & Payment Pending!",
  AUTOPAY_SETUP_PENDING : "Autopay Setup Pending!",
  AUTOPAY_SETUP_AND_PAYMENT_FAILED : "Autopay Setup & Payment Failed!",
  AUTOPAY_SETUP_FAILED : "Autopay Setup Failed!",
  ONE_TIME_REGISTERATION : "One time registration",
  CLEARANCE_AND_REGISTERATION : "Clearance + Registration",
  UPI_AUTOPAY_SETUP : "UPI Autopay Setup",
  WATCH_VIDEO_FOR_HELP : "Watch video for help",
  PAYMENT_PENDING_SOFT_NUDGE : "Dues limit will be reached soon. Clear dues to enjoy non-stop rides",
  CLEAR_YOUR_DUES_EARLY : "Clear your Dues Early",
  DUE_LIMIT_WARNING_BANNER_TITLE : "Your due limit of ₹{} will be reached soon",
  SCHEDULED_ON : "Scheduled On",
  ATTEMPTED_ON : "Attempted On",
  FREE_TRIAL_ENDING_IN_2_DAYS :"Free trial ending in 2 days!",
  FREE_TRIAL_ENDING_TOMORROW : "Free trial ending tomorrow!",
  FREE_TRIAL_ENDS_TONIGHT : "Free trial ends tonight!",
  JOIN_A_PLAN_TO_CONTINUE_TAKING_RIDES : "Join a plan to continue taking rides",
  SETUP_AUTOPAY_FOR_EASY_PAYMENTS : "Setup Autopay for easy payments",
  LOW_DUES_CLEAR_POPUP_DESC : "Clear your dues now to enjoy non-stop rides.",
  DUES_PENDING : "⚠️ Dues Pending! ⚠️",
  DAYS : "Days",
  ACTIVE_PLAN : "Active Plan",
  DOWNGRADE_AVAILABLE_ONLY_FOR_AC_VEHICLES : "Downgrade vehicle option is only available for AC vehicles",
  DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_1 : "Downgrading your vehicle will allow you to take both",
  DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_2 : "rides and",
  DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_3 : "rides",
  AC_CAB : "AC Cab",
  AC_SUV : "AC SUV",
  DOWNGRADE_VEHICLE : "Downgrade Vehicle",
  WHAT_ARE_PURPLE_RIDES : "What are Purple Rides?",
  ECONOMICAL : "Economical",
  SPACIOUS : "Spacious",
  COMFY : "Comfy",
  PEOPLE : "people",
  GO_TO : "Go-To",
  SELECT_ON_MAP : "Select on Map",
  CONFIRM_LOCATION_STR : "Confirm Location",
  SAVE_LOCATION_STR : "Save Location",
  REMOVE_PREF_LOC : "Remove preferred location ",
  CONF_REMOVE_PREF_LOC : "Are you sure you want to remove a preferred  location?",
  YES_REMOVE : "Yes, Remove",
  ADD_LOCATION : "Add New Go To Location",
  ADD_ANOTHER_LOCATION : "Add another location",
  ADD_A_GOTO_LOC : "Add a Go-To Location",
  GOTO_LOC_LEFT : "Go-To locations left:",
  CURRENT_LOCATION : "Current Location",
  CONF_GOTO_LOC : "Confirm Go-To location",
  GOTO_LOCS : "Go-To Locations",
  LOCATION_STR : "Location",
  ADD_TAG : "Add Tag",
  ONLY_ONE_LOC_CAN_ADDED : "(Only one location can have this tag)",
  SAVE_AS : "Save As",
  NO_GOTO_LOC_ADDED : "No Go-To location added yet",
  GOTO_LOC_HELPS_YOU : "Go-To location helps you find rides in and around your preferred locations",
  YOU_ARE_VERY_CLOSE : "You are very close to the\n “Go-To” location",
  GOTO_IS_APPLICABLE_FOR : "\"Go-To\" is applicable for locations \n which are at least <b>3km</b> away from \n your current location.",
  CANCEL_ANYWAY : "Cancel Anyway",
  GOTO_MAYBE_REDUCED : "“Go To” may be reduced",
  CANCEL_OF_GOTO : "Cancellation of a “Go To” ride will \n reduce “Go To” options for you!",
  MORE_GOTO_RIDE_COMING : "More “Go To” rides coming!",
  MORE_GOTO_RIDE_COMING_DESC : "Please stay ONLINE; we are fetching more ride requests towards your “Go To” location",
  GOTO_REDUCED_TO_ZERO : "“Go To” reduced to zero",
  DUE_TO_MULTIPLE_CANCELLATIONS : "Due to multiple cancellations, the count has been reduced to",
  OK_GOT_IT : "Ok, Got it",
  GOTO_REDUCED_TO : "“Go To” reduced to",
  VALIDITY_EXPIRED : "Validity Expired!",
  VALIDITY_EXPIRED_DESC : "Your 30-minute validity has ended. We are unable to fulfill your request at this time.",
  KNOW_MORE : "Know More",
  THIS_FEATURE_WILL_BE_APPLICABLE : "This feature will be applicable if you are at least 3 km away from your current location.\n\nLocation preferences are valid for only 30 minutes upon activation.",
  GOTO_LOC_ADDED : "Go-To Location Added Successfully",
  GOTO_LOC_REMOVED : "Go-To Location Removed Successfully",
  GOTO_LOC_UPDATED : "Go-To Location  Updated Successfully",
  GOTO_LOC_IS_ENABLED : "Go-To Location is enabled",
  GOTO_LOC_IS_DISABLED : "Go-To Location is disabled",
  GOTO_LOCATIONS : "Go To Locations",
  CHOOSE_A_GOTO_LOC : "Choose a Go-To location",
  YOU_HAVE_ONLY_LEFT_FOR_TODAY : "You have only left for today",
  YES_ENABLE : "Yes, Enable",
  NO_GOTO_LOCS_ADDED_YET : "No Go To Locations Added Yet",
  NO_GOTO_LOCS_ADDED_YET_DESC : "Go-To location helps you find rides in and around your preferred locations",
  ENABLE_GOTO : "Enable Go-To",
  GO_TO_CANCELLATION_TITLE : "“Go To” may be reduced",
  GO_TO_CANCELLATION_DESC : "Cancellation of a “Go To” ride will reduce “Go To” options for you!",
  VALIDITY_EXPIRED_STR : "Validity Expired!",
  DISABLE_GOTO_STR : "Disable Go-To?",
  YOU_STILL_HAVE_TIME_LEFT : "You still have time left on your “Go-To” Request",
  YES_DISABLE : "Yes, Disable",
  GOTO_LOC_REACHED : "“Go To” Location Reached!",
  REPORT_ISSUE : "Report Issue",
  YOU_ARE_ALMOST_AT_LOCATION : "You are almost at the Go To Location.",
  DRIVER_HOME_LOCATION_NOT_FOUND : "Location not found",
  DRIVER_HOME_LOCATION_DOES_NOT_EXIST : "Location doesn't exist",
  DRIVER_HOME_LOCATION_LIMIT_REACHED : "Location limit reached",
  DRIVER_GO_HOME_REQUEST_NOT_FOUND : "Request not found",
  DRIVER_GO_HOME_REQUEST_DOES_NOT_EXIST : "Request doesn't exist",
  DRIVER_GO_HOME_REQUEST_DAILY_USAGE_LIMIT_REACHED : "Daily usage limit reached",
  DRIVER_GO_HOME_REQUEST_ALREADY_ACTIVE : "Already Active",
  DRIVER_HOME_LOCATION_OUTSIDE_SERVICE_AREA : "Location is outside service area",
  NEW_LOCATION_TOO_CLOSE_TO_PREVIOUS_HOME_LOCATION : "Location is too close to previous location",
  DRIVER_HOME_LOCATION_DOES_NOT_BELONG_TO_DRIVER : "Location does not belong to you",
  DRIVER_HOME_LOCATION_DELETE_WHILE_ACTIVE_ERROR : "Cannot delete location while active",
  DRAG_TO_ADJUST : "Drag to adjust your location",
  LOCATION_ALREADY_EXISTS : "Location already exists as",
  MIN_LEFT : "Min left",
  GET_READY_FOR_YS_SUBSCRIPTION : "Get ready for\nYatri Sathi Plans!",
  SIGNUP_EARLY_FOR_SPECIAL_OFFERS : "Signup early for special offers",
  GUARANTEED_FIXED_PRICE : "Guaranteed fixed price until \nJan 1, 2025",
  INTRODUCTORY_OFFER_TO_BE_ANNOUNCED_SOON : "Introductory offer will be announced soon!",
  NO_CHARGES_TILL : "No charges till April 1, 2024",
  DIRECT_PAYMENT_NO_COMMISSIONS : "Direct payment.\nNo commissions",
  CUSTOMER_PAYS_DIRECTLY : "Customer pays to you directly via \ncash or UPI",
  HUNDRED_PERCENT_FARE_GOES_TO_YOU : "100% of the fare\ngoes to you!",
  FARE_SHOWN_IS_FARE_YOU_GET : "The fare shown is the fare you get.\nNo hidden charges.",
  BE_A_PART_OF_OPEN_MOBILITY_REVOLUTION : "Be a part of the Open\nMobility Revolution!",
  OUR_DATA_AND_PRODUCT_ARE_TRANSPARENT : "Our data and product roadmap are\ntransparent for all.",
  YOUR_DETECTED_LOCATION_IS : "Your detected location is",
  LANGUAGE_DETECTED : "Language detected",
  CHANGE_LANGUAGE_STR : "Change Language",
  SELECT_LOCATION : "Select Location",
  SELECT_LOCATION_DESC : "Select the location where you want to take rides",
  SELECT_LANGUAGE_DESC : "Select the language you can read",
  CONFIRM_LANGUAGE : "Confirm Language",
  GET_STARTED : "Get Started",
  ENABLE_LOCATION_PERMISSION : "Enable Location Permission",
  PLEASE_ENABLE_LOCATION_PERMISSION_FOR : "Please enable location permission for ",
  ENABLE_LOCATION : "Enable Location",
  ENTER_YOUR_MOBILE_NUMBER: "Enter your Mobile Number",
  NOTIFICATION_ACCESS : "Notification Access",
  NOTIFICATION_ACCESS_DESC : "Recommended, ensures that you never miss out on messages",
  WATCH_VIDEO : "Watch Video",
  DL_VERIFICATION_FAILED : "DL Verification Failed. Please enter date of issue and try again",
  RC_VERIFICATION_FAILED : "RC Verification Failed. Please enter date of issue and try again",
  DL_UPLOAD_FAILED : "DL Upload Failed",
  RC_UPLOAD_FAILED : "RC Upload Failed",
  PLEASE_RETRY_THE_UPLOAD_AGAIN : "Please retry the upload again.",
  RC_AND_DL_UPLOAD_FAILED : "RC and DL Upload Failed.",
  RC_UPLOAD_LIMIT_REACHED : "RC upload limit exceeded.",
  DL_UPLOAD_LIMIT_REACHED : "DL upload limit exceeded.",
  RETRY_UPLOAD : "Retry Upload",
  VEHICLE_REGISTERATON_CERTIFICATE : "Vehicle Registeration Certificate",
  GRANT_PERMISSIONS : "Grant Permissions",
  SUBSCRIPTION_PLAN_STR : "Subscription Plan",
  COMPLETE_AUTOPAY_LATER : "Complete Autopay from ‘My Plan’ section later.",
  START_EARNING_IN_FOUR_STEPS : "Start earning in {} simple steps",
  COMPLETE : "Complete",
  HOW_TO_UPLOAD : "How to upload",
  TAKE_CLEAR_PICTURE_DL : "Take a clear picture of the photo side of your Driving Licence on a flat surface.",
  ENSURE_ADEQUATE_LIGHT : "Ensure that the lighting is adequate and all the details are clearly visible",
  FIT_DL_CORRECTLY : "Fit the Driving License in the marked area correctly as shown below",
  TAKE_PHOTO : "Take Photo",
  FIT_RC_CORRECTLY : "Fit the Registeration Certificate in the marked area correctly as shown below",
  TAKE_CLEAR_PICTURE_RC : "Take a clear picture of the photo side of your Registration Certificate on a flat surface.",
  DL_UPLOADED : "Driving License Uploaded",
  RC_UPLOADED : "Registration Certificate Uploaded",
  DL_UPLOADING : "Uploading Driving License",
  RC_UPLOADING : "Uploading Registration Certificate",
  RETAKE_RC : "\nPlease retake photo with RC inside marked area",
  RETAKE_DL : "\nPlease retake photo with DL inside marked area",
  LETS_GET_YOUR_TRIP_READY : "Let's get your trip ready!",
  GOT_AN_OTP : "Got an OTP?",
  DRIVING_LICENSE_DETAILS : "Driving Licence Details",
  VEHICLE_REGISTRATION_DETAILS : "Vehicle Registration Details",
  UPLOAD_PHOTO : "Upload Photo",
  CONFIRM_AND_UPLOAD : "Confirm and Upload",
  RETAKE_PHOTO : "Retake Photo",
  CLEAR_IMAGE : "Clear Image",
  BLURRY_IMAGE : "Blurry Image",
  CROPPED_CORRECTLY : "Cropped Correctly",
  WRONG_CROPPING : "Wrong Cropping",
  CHANGE_LOCATION : "Change Location",
  RC_VERIFICATION_IN_PROGRESS : "RC verification is in progress...",
  RC_VERIFICATION_FAILED_STATUS : "RC verification failed!",
  RC_VERIFICATION_SUCCESS : "RC verification is successful!",
  RC_IN_PROGRESS_DESC : "RC will be added to your profile once verified",
  RC_FAILED_DESC : "Please try to add RC after some time",
  CHANGE_CITY : "Change City",
  UPLOAD_REGISTRATION_CERTIFICATE_STR : "Upload Registration Certificate",
  TAKE_A_PHOTO : "Take a Photo", 
  GALLERY : "Gallery",
  GET_FULL_PAYMENT : "Get direct, full payment from customers",
  UNABLE_TO_DETECT_YOUR_LOCATION : "Unable to detect your location",
  DETECTING_LOCATION : "Detecting Location",
}


export function getStringValue(key) {
  if (key in englishStrings) {
    return englishStrings[key];
  }
  console.error(key + " not found in englishStrings");
  return "";
}
