const teluguStrings = {
  INACCURATE_DATE_AND_TIME: "తేదీ మరియు సమయం సరిగా లేవు!",
  ADJUST_YOUR_DEVICE_DATE_AND_TIME_AND_TRY_AGAIN: "దయచేసి మీ సెట్టింగ్‌ల యాప్ నుండి తేదీ మరియు సమయాన్ని ఆటోమేటిక్‌గా (నెట్‌వర్క్ అందించినది) సెట్ చేయండి.",
  THE_CURRENT_DATE_AND_TIME_IS: "ప్రస్తుత తేదీ మరియు సమయం",
  GO_TO_SETTING: "సెట్టింగ్స్ కి వెళ్ళండి",
  LETS_GET_STARTED: "ప్రారంభిద్దాం",
  YOUR_APPLICATION_HAS_BEEN_SUBMITTED_SUCCESSFULLY_AND_IS_UNDER_VERIFICATION: "మీ దరఖాస్తు విజయవంతంగా సమర్పించబడింది మరియు ధృవీకరణలో ఉంది",
  VIEW_STATUS: "స్టేటస్ చూడండి",
  GO_HOME: "ఇంటికి వెళ్ళండి",
  SELECT_LANGUAGE: "భాషను ఎంచుకోండి",
  WHICH_LANGUAGE_DO_YOU_PREFER: "మీరు ఏ భాషను ఇష్టపడతారు?",
  NEXT: "నెక్స్ట్",
  T_C: "నిబంధనలు & షరతులు",
  ENTER_MOBILE_NUMBER: "మొబైల్ నంబర్ ఎంటర్ చేయండి",
  BY_CLICKING_CONTINUE_YOU_WILL_BE_AGREEING_TO_OUR: "కొనసాగించు క్లిక్ చేయడం ద్వారా, మీరు మా",
  ENTER_OTP: "OTP ఎంటర్ చేయండి",
  DIDNT_RECIEVE_OTP: "OTP అందలేదా? ",
  RESEND_OTP: "OTPను మళ్ళీ పంపు",
  PLEASE_ENTER_VALID_OTP: "సరైన OTP ఎంటర్ చేయండి",
  INVALID_MOBILE_NUMBER: "మొబైల్ నంబర్ చెల్లదు",
  REGISTER: "నమోదు చేసుకోండి",
  MOBILE_NUMBER: "మొబైల్ నంబర్",
  AUTO_READING_OTP: "ఆటో రీడింగ్ OTP...",
  UPLOAD_DRIVING_LICENSE: "డ్రైవింగ్ లైసెన్స్ అప్లోడ్ చేయండి",
  UPLOAD_BACK_SIDE: "బ్యాక్ సైడ్ అప్లోడ్ చేయండి",
  UPLOAD_FRONT_SIDE: "మీ డ్రైవింగ్ లైసెన్స్ ముందు భాగాన్ని అప్లోడ్ చేయండి",
  BACK_SIDE: "వెనుక వైపు",
  FRONT_SIDE: "మీ డ్రైవింగ్ లైసెన్స్ ముందు భాగం",
  LICENSE_INSTRUCTION_PICTURE: "దయచేసి లైసెన్స్ యొక్క రెండు వైపుల స్పష్టమైన చిత్రాలను అప్లోడ్ చేయండి",
  LICENSE_INSTRUCTION_CLARITY: "ఫోటో మరియు అన్ని వివరాలు స్పష్టంగా కనిపిస్తున్నాయని నిర్ధారించుకోండి",
  REGISTRATION_STEPS: "నమోదు దశలు",
  PROGRESS_SAVED: "మీ ప్రోగ్రెస్ సేవ్ చేయబడింది, మీరు ఏదైనా సమాచారాన్ని మార్చడానికి మునుపటి దశలకు కూడా వెళ్లవచ్చు",
  DRIVING_LICENSE: "డ్రైవింగ్ లైసెన్స్",
  AADHAR_CARD: "ఆధార్ కార్డ్",
  BANK_DETAILS: "బ్యాంక్ వివరాలు",
  VEHICLE_DETAILS: "వాహనం వివరాలు",
  UPLOAD_FRONT_BACK: "ముందు మరియు వెనుక వైపు అప్లోడ్ చేయండి",
  EARNINGS_WILL_BE_CREDITED: "మీ ఆదాయాలు ఇక్కడ క్రెడిట్ చేయబడతాయి",
  FILL_VEHICLE_DETAILS: "మీ వాహన వివరాలను పూరించండి",
  FOLLOW_STEPS: "దయచేసి నమోదు చేసుకోవడానికి క్రింది దశలను అనుసరించండి",
  REGISTRATION: "నమోదు",
  UPLOAD_ADHAAR_CARD: "ఆధార్ కార్డును అప్లోడ్ చేయండి",
  ADHAAR_INTRUCTION_PICTURE: "దయచేసి ఆధార్ కార్డ్‌కి రెండు వైపులా స్పష్టమైన చిత్రాలను అప్లోడ్ చేయండి",
  ADD_VEHICLE_DETAILS: "వాహనం వివరాలు ఎంటర్ చేయండి",
  VEHICLE_REGISTRATION_NUMBER: "వాహనం రిజిస్ట్రేషన్ సర్టిఫికేట్ నంబర్",
  RE_ENTER_VEHICLE_REGISTRATION_NUMBER: "వాహనం రిజిస్ట్రేషన్ సర్టిఫికేట్ నంబర్‌ను మళ్లీ నమోదు చేయండి",
  ENTER_VEHICLE_NO: "వాహనం నంబర్ ఎంటర్ చేయండి",
  VEHICLE_TYPE: "వాహనం రకం",
  VEHICLE_MODEL_NAME: "వాహనం మోడల్ పేరు",
  ENTER_MODEL_NAME: "వాహనం మోడల్ పేరు ఎంటర్ చేయండి",
  VEHICLE_COLOUR: "వాహనం రంగు",
  ENTER_VEHICLE_COLOUR: "వాహనం రంగు ఎంటర్ చేయండి",
  UPLOAD_REGISTRATION_CERTIFICATE: "రిజిస్ట్రేషన్ సర్టిఫికెట్ (RC) అప్లోడ్ చేయండి",
  UPLOAD_RC: "RC అప్లోడ్ చేయండి",
  PREVIEW: "ప్రివ్యూ",
  CHOOSE_VEHICLE_TYPE: "వాహనం రకాన్ని ఎంచుకోండి",
  BENIFICIARY_NUMBER: "లబ్ధిదారుల ఖాతా సంఖ్య",
  RE_ENTER_BENIFICIARY_NUMBER: "లబ్ధిదారు ఖాతా నంబర్‌ను మళ్లీ నమోదు చేయండి.",
  IFSC_CODE: "IFSC కోడ్‌",
  SENDING_OTP: "OTPని పంపిస్తున్నాము",
  PLEASE_WAIT_WHILE_IN_PROGRESS: "దయచేసి వేచి ఉండండి",
  YOUR_REQUEST_HAS_TIMEOUT_TRY_AGAIN: "మీ అభ్యర్థన టైం అవుట్ అయ్యింది. మళ్లీ ప్రయత్నించండి",
  ERROR_OCCURED_PLEASE_TRY_AGAIN_LATER: "ఎర్రర్ సంభవించింది. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి",
  ENTER_OTP_SENT_TO: "ఈ నంబర్ కు పంపిన OTPని ఎంటర్ చేయండి",
  OTP_SENT_TO: "OTP ఈ నంబర్ కు పంపించబడింది",
  COUNTRY_CODE_INDIA: "+91",
  ENTER_ACCOUNT_NUMBER: "అకౌంట్ నంబర్ ఎంటర్ చేయండి",
  ADD_BANK_DETAILS: "బ్యాంక్ వివరాలను ఇవ్వండి",
  ENTER_IFSC_CODE: "IFSC కోడ్‌ని ఎంటర్ చేయండి",
  SUBMIT: "సమర్పించండి",
  PERSONAL_DETAILS: "వ్యక్తిగత వివరాలు",
  LANGUAGES: "భాషలు",
  HELP_AND_FAQ: "సహాయం & తరచుగా అడిగే ప్రశ్నలు",
  ABOUT: "యాప్ గురించి",
  LOGOUT: "లాగౌట్",
  UPDATE: "అప్డేట్",
  EDIT: "ఎడిట్",
  AUTO: "ఆటో",
  NAME: "పేరు",
  PRIVACY_POLICY: "గోప్యతా విధానం",
  LOGO: "లోగో",
  ABOUT_APP_DESCRIPTION: "డ్రైవర్లను రైడర్‌లతో కనెక్ట్ చేయడానికి నమ్మ యాత్రి పార్టనర్ ఒక ఓపెన్ ప్లాట్‌ఫారమ్. ప్రతిపాదిత కావలసిన రేట్లతో రైడర్‌లను కనుగొనడం డ్రైవర్‌లకు యాప్ సౌకర్యంగా ఉంటుంది. రైడ్ ఆధారిత కమీషన్ లేదు, రోజువారీ సబ్‌స్క్రిప్షన్ రూపంలో చిన్న అమౌంట్ చెల్లించండి",
  TERMS_AND_CONDITIONS: "నిబంధనలు & షరతులు",
  UPDATE_VEHICLE_DETAILS: "వాహన వివరాలను అప్‌డేట్ చేయండి",
  Help_AND_SUPPORT: "సహాయం మరియు మద్దతు",
  NOTE: "గమనిక:",
  VISIT_MY_RIDES_SCREEN_FOR_SPECIFIC_COMPLAINTS: "నిర్దిష్ట ఫిర్యాదుల కోసం నా రైడ్స్ విభాగాన్ని సందర్శించండి",
  THANK_YOU_FOR_WRTITTING_US: "మాకు వ్రాసినందుకు ధన్యవాదాలు!",
  WE_HAVE_RECIEVED_YOUR_ISSUE: "మీ సమస్య మేము నమోదు చేసుకున్నాము. మిమ్మల్ని త్వరలో సంప్రదిస్తాము",
  GO_TO_HOME: "ఇంటికి వెళ్లుము",
  YOUR_RECENT_RIDE: "మీ రీసెంట్ రైడ్",
  YOUR_RECENT_TRIP: "మీ ఇటీవలి పర్యటన",
  ALL_TOPICS: "అన్ని అంశాలు",
  REPORT_AN_ISSUE_WITH_THIS_TRIP: "ఈ పర్యటనలో సమస్యను నివేదించండి",
  YOU_RATED: "మీరు రేట్ చేసారు:",
  VIEW_ALL_RIDES: "అన్ని రైడ్‌లను వీక్షించండి",
  WRITE_TO_US: "మాకు వ్రాయండి",
  SUBJECT: "విషయం",
  YOUR_EMAIL_ID: "మీ ఇమెయిల్ ID",
  DESCRIBE_YOUR_ISSUE: "మీ సమస్య ని వర్ణించండి",
  GETTING_STARTED_AND_FAQ: "ప్రారంభించడం మరియు తరచుగా అడిగే ప్రశ్నలు",
  FOR_OTHER_ISSUES_WRITE_TO_US: "ఇతర సమస్యల కోసం, మాకు వ్రాయండి",
  CALL_SUPPORT_CENTER: "మద్దతు కేంద్రానికి కాల్ చేయండి",
  YOU_CAN_DESCRIBE_ISSUE_THAT_YOU_FACED_HERE: "మీరు ఎదుర్కొన్న సమస్యను మీరు ఇక్కడ వివరించవచ్చు",
  REGISTRATION_CERTIFICATE_IMAGE: "రిజిస్ట్రేషన్ సర్టిఫికేట్ (RC) చిత్రం",
  HOME: "హోమ్",
  RIDES: "రైడ్స్",
  MY_RIDES: "నా రైడ్స్",
  PROFILE: "ప్రొఫైల్",
  ENTER_DRIVING_LICENSE_NUMBER: "డ్రైవింగ్ లైసెన్స్ నంబర్ ఎంటర్ చేయండి",
  WHERE_IS_MY_LICENSE_NUMBER: "నా లైసెన్స్ నంబర్ ఎక్కడ ఉంది?",
  TRIP_DETAILS: "పర్యటన వివరాలు",
  BY_CASH: "నగదు ద్వారా",
  ONLINE_: "ఆన్‌లైన్",
  GO_ONLINE_POPUP: "<u>ఆన్‌లైన్‌కి వెళ్లండి</u>",
  REPORT_AN_ISSUE: "ఒక సమస్యను నివేదించండి",
  DISTANCE: "దూరం",
  TIME_TAKEN: "తీసుకున్న సమయం",
  MAPS: "మప్స్",
  CALL: "కాల్",
  START_RIDE: "రైడ్ ప్రారంభించండి",
  CANCEL_RIDE: "రైడ్ రద్దు చేయి",
  PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL: "దయచేసి మీరు ఎందుకు రద్దు చేయాలనుకుంటున్నారో మాకు చెప్పండి",
  MANDATORY: "తప్పనిసరి",
  END_RIDE: "రైడ్ ముగించుము",
  RIDE_COMPLETED_WITH: "కస్టమర్‌తో రైడ్ పూర్తయింది",
  COLLECT_AMOUNT_IN_CASH: "అమౌంట్ కాష్ రూపంలో సేకరించండి",
  CASH_COLLECTED: "కాష్ సేకరించబడింది",
  OFFLINE: "ఆఫ్‌లైన్",
  ACCEPT_FOR: "దీనికి అంగీకరించు:",
  DECLINE: "తిరస్కరించు",
  REQUEST: "అభ్యర్థన",
  YOU_ARE_OFFLINE: "మీరు ఆఫ్‌లైన్‌లో ఉన్నారు",
  YOU_ARE_CURRENTLY_BUSY_GO_ONLINE_TO_RECIEVE_TRIP_REQUESTS: "మీరు ప్రస్తుతం బిజీగా ఉన్నారు. ట్రిప్ అభ్యర్థనలను స్వీకరించడానికి ఆన్‌లైన్‌కి వెళ్లండి",
  GOING_OFFLINE_WILL_NOT_GET_YOU_ANY_RIDE: "ఆఫ్‌లైన్‌కి వెళ్లడం వల్ల మీకు ఎలాంటి ప్రయాణం లభించదు",
  CANCEL: "రద్దు చేయండి",
  GO_OFFLINE: "ఆఫ్లైన్లో వెళ్ళండి",
  IS_WAITING_FOR_YOU: "మీ కోసం ఎదురు చూస్తున్నాను",
  YOU_ARE_ON_A_RIDE: "మీరు ప్రయాణంలో ఉన్నారు...",
  PLEASE_ASK_RIDER_FOR_THE_OTP: "దయచేసి OTP కోసం రైడర్‌ని అడగండి",
  COMPLETED_: "పూర్తయింది",
  CANCELLED_: "రద్దు",
  WE_NEED_SOME_ACCESS: "మాకు ఈ యాక్సెస్‌ను మంజూరు చేయండి!",
  ALLOW_ACCESS: "యాక్సెస్ అనుమతించు",
  THANK_YOU_FOR_WRITING_TO_US: "మాకు వ్రాసినందుకు ధన్యవాదాలు!",
  RIDER: "రైడర్",
  TRIP_ID: "ట్రిప్ ఐడి",
  NEED_IT_TO_SHOW_YOU_INCOMING_RIDE_REQUEST: "యాప్ నేపథ్యంలో ఉన్నప్పుడు ఇన్‌కమింగ్ రైడ్ అభ్యర్థనను పొందండి",
  NEED_IT_TO_DISABLE_BATTERY_OPTIMIZATION_FOR_THE_APP: "సిఫార్సు చేయబడింది, బ్యాక్‌గ్రౌండ్‌లో ఎక్కువసేపు రన్ అయ్యేలా యాప్‌ని ప్రారంభిస్తుంది",
  NEED_IT_TO_AUTOSTART_YOUR_APP: "యాప్‌ను బ్యాక్‌గ్రౌండ్‌లో రన్ చేయడం ద్వారా సహాయపడుతుంది",
  NEED_IT_TO_ENABLE_LOCATION: "యాప్ మూసివేయబడినప్పుడు లేదా ఉపయోగంలో లేనప్పుడు కూడా డ్రైవర్ ప్రస్తుత స్థానాన్ని పర్యవేక్షించడానికి మీ లొకేషన్‌ను షేర్ చేయడానికి నమ్మ యాత్రి పార్టనర్ లొకేషన్ డేటాను సేకరిస్తారు.",
  OVERLAY_TO_DRAW_OVER_APPLICATIONS: "అప్లికేషన్లపై చూపించు",
  BATTERY_OPTIMIZATIONS: "బ్యాటరీ ఆప్టిమైజేషన్",
  AUTO_START_APPLICATION_IN_BACKGROUND: "నేపథ్యంలో యాప్ ఆటోస్టార్ట్",
  LOCATION_ACCESS: "లొకేషన్ యాక్సెస్",
  ENTER_RC_NUMBER: "RC నంబర్‌ని నమోదు చేయండి",
  WHERE_IS_MY_RC_NUMBER: "నా RC నంబర్ ఎక్కడ ఉంది?",
  STEP: "దశ",
  PAID: "చెల్లించిన",
  ENTERED_WRONG_OTP: "తప్పు OTP నమోదు చేయబడింది",
  OTP_INVALID_FOR_THIS_VEHICLE_VARIANT : "చెల్లని OTP - వాహనం రకం రైడ్ రకంతో సరిపోలడం లేదు",
  COPIED: "కాపీ చేయబడింది",
  BANK_NAME: "బ్యాంక్ పేరు",
  AADHAR_DETAILS: "ఆధార్ వివరాలు",
  AADHAR_NUMBER: "ఆధార్ నంబర్",
  FRONT_SIDE_IMAGE: "ముందు వైపు చిత్రం",
  BACK_SIDE_IMAGE: "వెనుక వైపు చిత్రం",
  STILL_NOT_RESOLVED: "ఇంకా పరిష్కారం కాలేదా? మాకు కాల్ చేయండి",
  CASE_TWO: "బి) కు",
  NON_DISCLOUSER_AGREEMENT: "బహిర్గత ఒప్పందం లేదు",
  DATA_COLLECTION_AUTHORITY: "సి) నేను నా సమాచారాన్ని సేకరించడానికి Juspayని నియమించి, అధికారం ఇస్తాను మరియు కొనసాగించడం ద్వారా నేను ఉపయోగ నిబంధనలు మరియు గోప్యతా విధానాన్ని అంగీకరిస్తున్నాను.",
  SOFTWARE_LICENSE: "సాఫ్ట్‌వేర్ లైసెన్స్",
  LOAD_MORE: "మరింత లోడ్ చేయి",
  ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: "మీరు ఖచ్చితంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?",
  GO_BACK: "వెనక్కి వెళ్ళు",
  THANK_YOU_FOR_REGISTERING_US: "మాతో నమోదు చేసుకున్నందుకు ధన్యవాదాలు!",
  UNFORTANUTELY_WE_ARE_NOT_AVAILABLE__YET_FOR_YOU: "దురదృష్టవశాత్తు, మేము మీ కోసం ఇంకా అందుబాటులో లేము. మేము మీకు త్వరలో తెలియజేస్తాము.",
  ARE_YOU_SURE_YOU_WANT_TO_END_THE_RIDE: "మీరు ఖచ్చితంగా రైడ్‌ని ముగించాలనుకుంటున్నారా?",
  EMPTY_RIDES: "ఖాళీ రైడ్స్",
  YOU_HAVE_NOT_TAKEN_A_TRIP_YET: "మీరు ఇంకా పర్యటనకు వెళ్లలేదు",
  BOOK_NOW: "ఇప్పుడే బుక్ చేయండి",
  RESEND_OTP_IN: "OTPని మళ్లీ పంపు",
  WE_NEED_ACCESS_TO_YOUR_LOCATION: "మాకు మీ లొకేషన్ యాక్సెస్ అవసరం!",
  YOUR_LOCATION_HELPS_OUR_SYSTEM: "మీ లొకేషన్ మా సిస్టమ్‌కి సమీపంలోని అన్ని ఆటోల ద్వారా మ్యాప్ చేయడంలో సహాయపడుతుంది మరియు మీకు వీలైనంత వేగంగా ప్రయాణించేలా చేస్తుంది.",
  NO_INTERNET_CONNECTION: "ఇంటర్నెట్ కనెక్షన్ లేదు",
  PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN: "దయచేసి మీ ఇంటర్నెట్ కనెక్షన్‌ని తనిఖీ చేసి, మళ్లీ ప్రయత్నించండి",
  TRY_AGAIN: "మళ్లీ ప్రయత్నించండి",
  GRANT_ACCESS: "యాక్సెస్ ఆమోదించండి",
  YOUR_LIMIT_EXCEEDED_TRY_AGAIN_AFTER_10_MIN: "మీరు పరిమితిని మించిపోయారు, 10నిమి తర్వాత మళ్లీ ప్రయత్నించండి ",
  ENTER_REFERRAL_MOBILE_NUMBER: "రెఫరల్ మొబైల్ నంబర్‌ను నమోదు చేయండి",
  APPLY: "దరఖాస్తు చేసుకోండి",
  HAVE_A_REFERRAL: "రెఫరల్ ఉందా?",
  ADD_HERE: "ఇక్కడ జోడించండి",
  REFERRAL_APPLIED: "రెఫరల్ వర్తింపజేయబడింది!",
  SMALLEDIT: "ఎడిట్",
  ADD_DRIVING_LICENSE: "డ్రైవింగ్ లైసెన్స్ జోడించండి",
  HELP: "సహాయం?",
  INVALID_DL_NUMBER: "చెల్లని DL నంబర్",
  DRIVING_LICENSE_NUMBER: "డ్రైవింగ్ లైసెన్స్ నంబర్" ,
  RE_ENTER_DRIVING_LICENSE_NUMBER: "డ్రైవింగ్ లైసెన్స్ నంబర్‌ని మళ్లీ నమోదు చేయండి",
  ENTER_DL_NUMBER: "DL నంబర్‌ని నమోదు చేయండి",
  SELECT_DATE_OF_BIRTH: "పుట్టిన తేదీని ఎంచుకోండి",
  DATE_OF_BIRTH: "పుట్టిన తేది",
  WATCH_A_TUTORIAL_FOR_EASY_REGISTRATION: "సులభంగా రిజిస్ట్రేషన్ కోసం ట్యుటోరియల్ చూడండి",
  ENTER_MINIMUM_FIFTEEN_CHARACTERS: "కనిష్టంగా 15 అక్షరాలను నమోదు చేయండి",
  ADD_YOUR_FRIEND: "మీ స్నేహితుడిని చేర్చుకోండి",
  PLEASE_WAIT_WHILE_VALIDATING_THE_IMAGE: "దయచేసి చిత్రాన్ని ధృవీకరిస్తున్నప్పుడు వేచి ఉండండి",
  VALIDATING: "ధృవీకరిస్తోంది",
  VERIFICATION_PENDING: "ధృవీకరణ పెండింగ్‌లో ఉంది",
  VERIFICATION_FAILED: "ధృవీకరణ విఫలమైంది",
  NO_DOC_AVAILABLE: "పత్రం అందుబాటులో లేదు",
  ISSUE_WITH_DL_IMAGE: "మీ DL ఇమేజ్‌తో కొంత సమస్య ఉన్నట్లు కనిపిస్తోంది, మా మద్దతు బృందం త్వరలో మిమ్మల్ని సంప్రదిస్తుంది.",
  STILL_HAVE_SOME_DOUBT: "ఇంకా ఏమైనా సందేహం ఉందా?",
  ISSUE_WITH_RC_IMAGE: "మీ RC చిత్రంతో కొంత సమస్య ఉన్నట్లు కనిపిస్తోంది, మా మద్దతు బృందం త్వరలో మిమ్మల్ని సంప్రదిస్తుంది.",
  PLEASE_CHECK_FOR_IMAGE_IF_VALID_DOCUMENT_IMAGE_OR_NOT: "దయచేసి చిత్రం చెల్లుబాటు అయ్యే డాక్యుమెంట్ ఇమేజ్ కాదా అని తనిఖీ చేయండి",
  OOPS_YOUR_APPLICATION_HAS_BEEN_REJECTED: "అయ్యో! మీ దరఖాస్తు తిరస్కరించబడింది. దయచేసి మళ్లీ ప్రయత్నించండి",
  INVALID_DRIVING_LICENSE: "చెల్లని డ్రైవింగ్ లైసెన్స్",
  LIMIT_EXCEEDED_FOR_DL_UPLOAD: "DL అప్‌లోడ్ కోసం పరిమితి మించిపోయింది",
  INVALID_VEHICLE_REGISTRATION_CERTIFICATE: "చెల్లని వాహన రిజిస్ట్రేషన్ సర్టిఫికేట్",
  LIMIT_EXCEEDED_FOR_RC_UPLOAD: "RC అప్‌లోడ్ కోసం పరిమితి మించిపోయింది",
  YOUR_DOCUMENTS_ARE_APPROVED: "మీ పత్రాలు ఆమోదించబడ్డాయి. సపోర్ట్ టీమ్ మీ ఖాతాను త్వరగా ఎనేబుల్ చేస్తుంది. మీ ఖాతాను ప్రారంభించడానికి మీరు మద్దతు బృందానికి కూడా కాల్ చేయవచ్చు",
  APPLICATION_STATUS: "అప్లికేషన్ స్థితి",
  FOR_SUPPORT: "మద్దతు కోసం",
  CONTACT_US: " మమ్మల్ని సంప్రదించండి",
  IMAGE_VALIDATION_FAILED: "చిత్రం ధ్రువీకరణ విఫలమైంది",
  IMAGE_NOT_READABLE: "చిత్రం చదవదగినది కాదు",
  IMAGE_LOW_QUALITY: "చిత్ర నాణ్యత బాగా లేదు",
  IMAGE_INVALID_TYPE: "అందించిన చిత్రం రకం అసలు రకంతో సరిపోలడం లేదు",
  IMAGE_DOCUMENT_NUMBER_MISMATCH: "ఈ చిత్రంలోని పత్రం సంఖ్య ఇన్‌పుట్‌తో సరిపోలడం లేదు",
  IMAGE_EXTRACTION_FAILED: "చిత్రం వెలికితీత విఫలమైంది",
  IMAGE_NOT_FOUND: "చిత్రం కనుగొనబడలేదు",
  IMAGE_NOT_VALID: "చిత్రం చెల్లదు",
  DRIVER_ALREADY_LINKED: "ఇతర పత్రం ఇప్పటికే డ్రైవర్‌తో లింక్ చేయబడింది",
  DL_ALREADY_UPDATED: "చర్య అవసరం లేదు. డ్రైవర్ లైసెన్స్ ఇప్పటికే డ్రైవర్‌తో లింక్ చేయబడింది",
  RC_ALREADY_LINKED: "వాహనం RC అందుబాటులో లేదు. ఇతర డ్రైవర్‌కి లింక్ చేయబడింది",
  RC_ALREADY_UPDATED: "చర్య అవసరం లేదు. వాహనం RC ఇప్పటికే డ్రైవర్‌కి లింక్ చేయబడింది",
  DL_ALREADY_LINKED: "డ్రైవింగ్ లైసెన్స్ అందుబాటులో లేదు. ఇతర డ్రైవర్‌కి లింక్ చేయబడింది",
  SOMETHING_WENT_WRONG: "ఎక్కడో తేడ జరిగింది",
  PICKUP: "పికప్",
  TRIP: "పర్యటన",
  CURRENTLY_WE_ALLOW_ONLY_KARNATAKA_REGISTERED_NUMBER: "ప్రస్తుతం, మేము కర్ణాటక రిజిస్టర్డ్ నంబర్‌ను మాత్రమే అనుమతిస్తున్నాము",
  UPDATED_AT: "మ్యాప్ ఇక్కడ అప్‌డేట్ చేయబడింది",
  TRIP_COUNT: "ట్రిప్ కౌంట్",
  TODAYS_EARNINGS: "సంపాదన",
  BONUS_EARNED : "సంపాదించిన బోనస్",
  GOT_IT : "అర్ధం అయ్యింది!",
  WHAT_IS_NAMMA_YATRI_BONUS : "బోనస్ అంటే ఏమిటి?",
  BONUS_PRIMARY_TEXT : "నమ్మ యాత్రి బోనస్ అనేది మీరు పికప్ ఛార్జీలు, కస్టమర్ టిప్స్ మరియు డ్రైవర్ జోడింపుల రూపంలో మీటర్ ఛార్జీకి మించి సంపాదించిన అదనపు అమౌంట్.",
  BONUS_SECONDARY_TEXT : "నమ్మ యాత్రి బోనస్ అమౌంట్ మీ మొత్తం సంపాదనలో భాగం.",
  DATE_OF_REGISTRATION: "నమోదు తేదీ",
  SELECT_DATE_OF_ISSUE: "జారీ చేసిన తేదీని ఎంచుకోండి",
  DATE_OF_ISSUE: "జారీ చేసిన తేది",
  PROVIDE_DATE_OF_ISSUE_TEXT: "క్షమించండి, మేము మీ వివరాలను ధృవీకరించలేకపోయాము, దయచేసి మీ డ్రైవింగ్ లైసెన్స్‌ని ధృవీకరించడానికి జారీ చేసిన తేదీ అందించండి.",
  PROVIDE_DATE_OF_REGISTRATION_TEXT: "క్షమించండి, మేము మీ వివరాలను ధృవీకరించలేకపోయాము, దయచేసి మీ వాహన వివరాలను ధృవీకరించడానికి నమోదు తేదీ అందించండి.",
  SELECT_DATE_OF_REGISTRATION: "రిజిస్ట్రేషన్ తేదీని ఎంచుకోండి",
  SAME_REENTERED_RC_MESSAGE: "దయచేసి మళ్లీ నమోదు చేసిన RC నంబర్ పైన అందించిన RC నంబర్‌తో సమానంగా ఉందని నిర్ధారించుకోండి",
  SAME_REENTERED_DL_MESSAGE: "మళ్లీ నమోదు చేసిన DL నంబర్ పైన అందించిన DL నంబర్‌తో సరిపోలడం లేదు",
  WHERE_IS_MY_ISSUE_DATE: "నా ఇష్యూ తేదీ ఎక్కడ ఉంది?",
  WHERE_IS_MY_REGISTRATION_DATE: "రిజిస్ట్రేషన్ తేదీ ఎక్కడ ఉంది?",
  EARNINGS_CREDITED_IN_ACCOUNT: "మీ ఆదాయాలు ఈ ఖాతాలో జమ చేయబడతాయి",
  INVALID_PARAMETERS: "చెల్లని పారామితులు",
  UNAUTHORIZED: "అనధికార",
  INVALID_TOKEN: "చెల్లని టోకేను",
  SOME_ERROR_OCCURED_IN_OFFERRIDE: "ఆఫర్‌రైడ్‌లో కొంత లోపం సంభవించింది",
  SELECT_VEHICLE_TYPE: "వాహనం రకాన్ని ఎంచుకోండి",
  రైడ్: "రైడ్",
  NO_LOCATION_UPDATE: "లొకేషన్ అప్డేట్ లేదు",
  GOT_IT_TELL_US_MORE: "అర్థమైంది, మాకు మరింత చెప్పండి?",
  WRITE_A_COMMENT: "వ్యాఖ్య రాయండి",
  HOW_WAS_YOUR_RIDE_WITH: "మీ ప్రయాణం ఎలా అయ్యింది",
  RUDE_BEHAVIOUR: "మొరటు ప్రవర్తన",
  LONG_WAITING_TIME: "వెయిట్ టైమ్ ఎక్కువ",
  DIDNT_COME_TO_PICUP_LOCATION: "పికప్ లొకేషన్‌కు రాలేదు",
  HELP_US_WITH_YOUR_REASON: "మీ కారణంతో మాకు సహాయం చేయండి",
  MAX_CHAR_LIMIT_REACHED: "గరిష్ట అక్షర పరిమితిని చేరుకున్నారు,",
  SHOW_ALL_OPTIONS: "అన్ని ఎంపికలను చూపు",
  UPDATE_REQUIRED: "అప్డేట్ అందుబాటులో ఉంది",
  PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE: "మా యాప్‌కి కొత్త అప్‌డేట్ అందుబాటులో ఉందని ప్రకటించడానికి మేము సంతోషిస్తున్నాము. ఈ అప్‌డేట్ మీ అనుభవాన్ని మరింత మెరుగ్గా చేయడానికి సరికొత్త డిజైన్ మరియు అనేక కొత్త ఫీచర్‌లను కలిగి ఉంది.",
  NOT_NOW: "ఇప్పుడు కాదు",
  OF: "యొక్క",
  DROP: "డ్రాప్",
  PLEASE_WAIT: "దయచేసి వేచి ఉండండి",
  SETTING_YOU_OFFLINE: "మేము మిమ్మల్ని ఆఫ్‌లైన్‌లో సెట్ చేస్తున్నాము",
  SETTING_YOU_ONLINE: "మేము మిమ్మల్ని ఆన్‌లైన్‌లో సెట్ చేస్తున్నాము",
  SETTING_YOU_SILENT : "మేము మిమ్మల్ని సైలెంట్ లో ఉంచుతున్నాము",
  VIEW_BREAKDOWN: "విభజనను వీక్షించండి",
  APP_INFO: "యాప్ సమాచారం",
  OTHER: "ఇతర",
  VEHICLE_ISSUE: "వాహన సమస్య",
  FARE_UPDATED: "ఛార్జీ నవీకరించబడింది",
  FREQUENT_CANCELLATIONS_WILL_LEAD_TO_LESS_RIDES: "తరచుగా రద్దు చేయడం వలన తక్కువ రైడ్‌లు మరియు తక్కువ రేటింగ్‌లు వస్తాయి",
  CONTINUE: "కొనసాగించు",
  CONFIRM_PASSWORD: "పాస్‌వర్డ్‌ని నిర్ధారించండి",
  DEMO_MODE: "డెమో మోడ్",
  PASSWORD: "పాస్వర్డ్",
  ENTER_DEMO_MODE_PASSWORD: "డెమో మోడ్ పాస్‌వర్డ్‌ని నమోదు చేయండి",
  DEMO_MODE_DISABLED: "డెమో మోడ్ నిలిపివేయబడింది",
  ONLINE_VIA_DEMO_MODE: "ఆన్‌లైన్ (డెమో)",
  MORE: "మరింత",
  LESS: "తక్కువ",
  YOU_ARE_AT_PICKUP: "మీరు పికప్ లొకేషన్‌లో ఉన్నారు",
  WAITING_FOR_CUSTOMER: "మీరు వీరి కోసం వేచి ఉన్నారు",
  CUSTOMER_NOTIFIED: "కస్టమర్ కి తెలియజేయబడింది",
  I_ARRIVED: "నేను వచ్చేసాను",
  ESTIMATED_RIDE_FARE: "రైడ్ ఛార్జీ అంచనా:",
  PICKUP_TOO_FAR: "పికప్ చాలా దూరం",
  CUSTOMER_NOT_PICKING_CALL: "కస్టమర్ కాల్ ఎత్తట్లేదు",
  TRAFFIC_JAM: "ట్రాఫిక్ జాం",
  CUSTOMER_WAS_RUDE: "కస్టమర్ అసభ్యంగా ప్రవర్తించారు",
  ALL_MESSAGES: "అన్ని సందేశాలు",
  MESSAGES: "సందేశాలు",
  ADD_A_COMMENT: "కామెంట్ చేయండి",
  POST_COMMENT: "కామెంట్ చేయండి",
  ENTER_YOUR_COMMENT: "మీ కామెంట్ని నమోదు చేయండి",
  NO_NOTIFICATIONS_RIGHT_NOW: "నోటిఫికేషన్లు లేవు!",
  NO_NOTIFICATIONS_RIGHT_NOW_DESC: "కొత్త నోటిఫికేషన్‌లు వచ్చినప్పుడు మేము మీకు తెలియజేస్తాము",
  ALERTS: "అలర్ట్స్",
  YOUR_COMMENT: "మీ కామెంట్",
  SHOW_MORE: "ఇంకా చూపించు",
  LOAD_OLDER_ALERTS: "పాత అలర్ట్స్ ను లోడ్ చేయి",
  CONTEST: "పోటీ",
  YOUR_REFERRAL_CODE_IS_LINKED: "మీ రెఫరల్ కోడ్ లింక్ చేయబడింది!",
  YOU_CAN_NOW_EARN_REWARDS: "కస్టమర్‌లను రెఫెర్ చేసినందుకు మీరు ఇప్పుడు రివార్డ్‌లను పొందవచ్చు!",
  COMING_SOON: "త్వరలో!",
  COMING_SOON_DESCRIPTION: "మిమ్మల్ని రిఫరల్ ప్రోగ్రామ్‌లో చేర్చడానికి మేము పని చేస్తున్నాము. మరింత సమాచారం కోసం అలర్ట్స్ పేజీని చూడండి. ",
  REFERRAL_CODE: "రెఫరల్ కోడ్",
  REFERRAL_CODE_HINT: "6-అంకెల రెఫరల్ కోడ్‌ని నమోదు చేయండి",
  CONFIRM_REFERRAL_CODE: "రెఫరల్ కోడ్‌ని నిర్ధారించండి",
  CONFIRM_REFERRAL_CODE_HINT: "రెఫరల్ కోడ్‌ని మళ్లీ నమోదు చేయండి",
  YOUR_REFERRAL_CODE: "మీ రెఫరల్ కోడ్",
  FIRST_REFERRAL_SUCCESSFUL: "మొదటి రెఫరల్ విజయవంతమైంది!\nరివార్డ్ అన్‌లాక్ చేయబడింది!",
  AWAITING_REFERRAL_RIDE: "రిఫరల్ రైడ్ కోసం వేచి ఉంది",
  CHECK_THIS_SPACE_WHEN_YOU_GET_REFERRAL_ALERT: "మీరు రిఫరల్ అలెర్ట్ను పొందినప్పుడు \nఈ స్థలాన్ని తనిఖీ చేయండి",
  REFERRED_CUSTOMERS: "రెఫెర్ చేసిన వినియోగదారులు",
  ACTIVATED_CUSTOMERS: "ఆక్టివేట్ అయిన వినియోగదారులు",
  REFERRAL_CODE_LINKING: "రెఫరల్ కోడ్ లింకింగ్",
  CONTACT_SUPPORT: "మద్దతును సంప్రదించండి",
  CALL_SUPPORT: "మద్దతుకు కాల్ చేయండి",
  YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT: "మీరు నమ్మ యాత్రి సపోర్ట్ టీమ్‌కి కాల్ చేయబోతున్నారు. మీరు కొనసాగించాలనుకుంటున్నారా?",
  REFERRAL_ENROLMENT: "రెఫరల్ నమోదు",
  REFERRALS: "రిఫరల్స్",
  LINK_REFERRAL_CODE: "లింక్ రిఫరల్ కోడ్",
  DRIVER_DETAILS: "డ్రైవర్ వివరాలు",
  FOR_UPDATES_SEE_ALERTS: "నవీకరణల కోసం, అలర్ట్స్ చూడండి",
  SHARE_OPTIONS: "షేర్ ఎంపికలు",
  ENTER_PASSWORD: "పాస్వర్డ్ తెలపండి",
  YOUR_VEHICLE: "మీ వాహనం",
  BOOKING_OPTIONS: "బుకింగ్ ఎంపికలు",
  CONFIRM_AND_CHANGE: "నిర్ధారించండి & మార్చండి",
  OTP_: "OTP",
  MAKE_YOURSELF_AVAILABLE_FOR : "మిమ్మల్ని మీరు అందుబాటులో ఉంచుకోండి",
  SILENT_MODE_PROMPT : "మీకు డిస్టర్బన్స్ వద్దు అనుకుంటే, మీరు సైలెంట్ మోడ్‌కి మారవచ్చు",
  GO_SILENT : "సైలెంట్ మోడ్ ఆక్టివేట్ చేయి",
  TRY_SILENT_MODE : "సైలెంట్ మోడ్‌ని ప్రయత్నిస్తారా?",
  RIDE_FARE : "రైడ్ ఛార్జీలు" ,
  RIDE_DISTANCE : "రైడ్ దూరం",
  START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS : "ఈ క్విక్ చాట్ సూచనలను ఉపయోగించి మీ చాట్‌ని ప్రారంభించండి",
  START_YOUR_CHAT_WITH_THE_DRIVER : "డ్రైవర్‌తో మీ చాట్‌ను ప్రారంభించండి",
  MESSAGE : "సందేశం",
  I_AM_ON_MY_WAY : "నేను నా దారిలో ఉన్నాను",
  GETTING_DELAYED_PLEASE_WAIT : "ఆలస్యం అవుతోంది, దయచేసి వేచి ఉండండి",
  UNREACHABLE_PLEASE_CALL_BACK : "అందుబాటులో లేరు, దయచేసి తిరిగి కాల్ చేయండి",
  ARE_YOU_STARING : "మీరు వస్తున్నారా?",
  PLEASE_COME_SOON : "దయచేసి త్వరగా రండి",
  OK_I_WILL_WAIT : "సరే నేను వేచి ఉంటాను",
  I_HAVE_ARRIVED : "నేను వచ్చేసాను",
  PLEASE_COME_FAST_I_AM_WAITING : "దయచేసి త్వరగా రండి, నేను వేచి ఉన్నాను",
  PLEASE_WAIT_I_WILL_BE_THERE : "దయచేసి వేచి ఉండండి, నేను ఇక్కడ ఉంటాను",
  LOOKING_FOR_YOU_AT_PICKUP : "పికప్ వద్ద మీ కోసం వెతుకుతున్నాను",
  SILENT : "సైలెంట్",
  GO_ONLINE : "గో ఆన్లైన్!",
  GO_ONLINE_PROMPT : "మీరు ప్రస్తుతం ఆఫ్‌లైన్‌లో ఉన్నారు.\nరైడ్ అభ్యర్థనలను పొందడానికి, ఇప్పుడే ఆన్‌లైన్‌కి వెళ్లండి!",
  LIVE_DASHBOARD : "ప్రత్యక్ష గణాంకాల డాష్‌బోర్డ్",
  CLICK_TO_ACCESS_YOUR_ACCOUNT : "మీ ఖాతాను యాక్సెస్ చేయడానికి ఇక్కడ క్లిక్ చేయండి",
  ADD_ALTERNATE_NUMBER : "ఆల్టర్నేట్ నంబర్ జోడించండి",
  ENTER_ALTERNATE_MOBILE_NUMBER : "ఆల్టర్నేట్ మొబైల్ నంబర్‌ను నమోదు చేయండి",
  EDIT_ALTERNATE_MOBILE_NUMBER : "ఆల్టర్నేట్ మొబైల్ నంబర్‌ని ఎడిట్ చేయండి",
  PLEASE_ENTER_A_VALID_10_DIGIT_NUMBER : "దయచేసి చెల్లుబాటు అయ్యే 10-అంకెల సంఖ్యను నమోదు చేయండి",
  ALTERNATE_MOBILE_NUMBER : "ఆల్టర్నేట్ మొబైల్ నంబర్",
  REMOVE : "తొలగించు",
  REMOVE_ALTERNATE_NUMBER : "ఆల్టర్నేట్ సంఖ్యను తీసివేయండి",
  ARE_YOU_SURE_YOU_WANT_TO_REMOVE_YOUR_ALTERNATE_MOBILE_NUMBER : "మీరు ఖచ్చితంగా మీ ఆల్టర్నేట్ మొబైల్ నంబర్‌ను తీసివేయాలనుకుంటున్నారా?",
  YES_REMOVE_IT : "అవును, దాన్ని తీసివేయండి",
  NUMBER_REMOVED_SUCCESSFULLY : "నంబర్ విజయవంతంగా తీసివేయబడింది",
  NUMBER_ADDED_SUCCESSFULLY : "నంబర్ విజయవంతంగా జోడించబడింది",
  NUMBER_EDITED_SUCCESSFULLY : "నంబర్ విజయవంతంగా నవీకరించబడింది",
  ALTERNATE_MOBILE_OTP_LIMIT_EXCEED : "OTP పరిమితి మించిపోయింది, నంబర్‌ని నమోదు చేసి మళ్లీ OTP ఎంటర్ చేయండి",
  WRONG_OTP : "దయచేసి చెల్లుబాటు అయ్యే OTPని నమోదు చేయండి",
  ATTEMPTS_LEFT : "ప్రయత్నాలు మిగిలి ఉన్నాయి",
  ATTEMPT_LEFT : "ప్రయత్నం మిగిలి ఉంది",
  OTP_LIMIT_EXCEEDED : "OTP పరిమితి మించిపోయింది",
  OTP_LIMIT_EXCEEDED_MESSAGE : "మీరు మీ OTP పరిమితిని చేరుకున్నారు. దయచేసి 10 నిమిషాల తర్వాత మళ్లీ ప్రయత్నించండి.",
  TRY_AGAIN_LATER : "తరువాత మళ్ళీ ప్రయత్నించండి",
  NUMBER_ALREADY_EXIST_ERROR : "నంబర్ మరొక ఖాతాకు లింక్ చేయబడింది! దయచేసి మరొక నంబర్ ఉపయోగించండి",
  ADD_ALTERNATE_NUMBER_IN_MEANTIME : "ఈ ప్రక్రియ పూర్తి కావడానికి 2 పనిదినాలు పట్టవచ్చు.\nఈలోగా, మీరు ఒక ఆల్టర్నేట్ మొబైల్ నంబర్‌ని జోడించవచ్చు.",
  VERIFICATION_IS_TAKING_A_BIT_LONGER : "మీ ధృవీకరణకు అనుకున్న దానికంటే కొంచెం ఎక్కువ సమయం తీసుకుంటున్నట్లు కనిపిస్తోంది.\nమీకు సహాయం చేయడానికి మీరు మద్దతును సంప్రదించవచ్చు.",
  COMPLETE_ONBOARDING : "పూర్తి ఆన్‌బోర్డింగ్",
  PERSON_WITH_THIS_NUMBER_ALREADY_EXISTS : "ఈ మొబైల్ నంబర్‌ను కలిగి ఉన్న వ్యక్తి ఇప్పటికే ఉన్నారు.",
  DEMO : "డెమో",
  PLEASE_ASK_THE_CUSTOMER_FOR_THE_OTP : "దయచేసి OTP కోసం కస్టమర్‌ని అడగండి",
  DELETE : "తొలగించు",
  VIEW : "చూడు",
  ISSUE_NO : "సంచిక నం.",
  ADD_VOICE_NOTE : "వాయిస్ నోట్‌ని జోడించండి",
  VOICE_NOTE_ADDED : "Voice గమనిక జోడించబడింది",
  SUBMIT_ISSUE_DETAILS : "సమస్య వివరాలను సమర్పించండి",
  IMAGE_PREVIEW : "చిత్రం ప్రివ్యూ",
  RIDE_REPORT_ISSUE : "సమస్యను నివేదించడానికి రైడ్‌ని ఎంచుకోండి",
  ADDED_IMAGES : "జోడించిన చిత్రాలు",
  NO_IMAGES_ADDED : "చిత్రాలు ఏవీ జోడించబడలేదు",
  ASK_DETAILS_MESSAGE : "దయచేసి మరికొన్ని వివరాలు ఇవ్వండి. మీరు మరింత మెరుగ్గా వివరించడానికి చిత్రాలు లేదా వాయిస్ నోట్స్‌ను కూడా పంపవచ్చు.",
  ASK_DETAILS_MESSAGE_REVERSED : "దయచేసి పోగొట్టుకున్న వస్తువు గురించి మరిన్ని వివరాలను షేర్ చేయండి. మీరు మరింత మెరుగ్గా వివరించడానికి చిత్రాలు లేదా వాయిస్ నోట్‌లను కూడా పంపవచ్చు.",
  SELECT_OPTION : "మీరు వీటిలో దేనినైనా ఎదుర్కొంటున్నట్లయితే దయచేసి మాకు చెప్పండి",
  SELECT_OPTION_REVERSED : "మీరు ఈ సమస్యను ఎలా పరిష్కరించాలనుకుంటున్నారు?",
  ISSUE_SUBMITTED_MESSAGE : "వివరాలు అందాయి! మీ సమస్యతో మీకు సహాయం చేయడానికి మా బృందం త్వరలో మీకు కాల్ చేస్తుంది.",
  I_DONT_KNOW_WHICH_RIDE : "నాకు ఏ రైడ్ ఓ తెలియదు",
  REPORT_ISSUE_CHAT_PLACEHOLDER : "మీ సమస్యను వివరించండి. నమ్మ యాత్రి త్వరలో దాన్ని పరిష్కరించడానికి ప్రయత్నిస్తుంది.",
  ADDED_VOICE_NOTE : "వాయిస్ నోట్ జోడించబడింది",
  NO_VOICE_NOTE_ADDED : "వాయిస్ నోట్ జోడించబడలేదు",
  CALL_CUSTOMER_TITLE : "కస్టమర్‌కి కాల్ చేయండి",
  CALL_CUSTOMER_DESCRIPTION : "మీరు కస్టమర్‌కు కాల్ చేయబోతున్నారు. మీరు కొనసాగించాలనుకుంటున్నారా?",
  PLACE_CALL : "కాల్ చేయండి",
  ADD_IMAGE : "చిత్రాన్ని జోడించండి",
  ADD_ANOTHER : "మరొకటి జోడించండి",
  IMAGES_ADDED : "చిత్రాలు జోడించబడ్డాయి",
  ISSUE_SUBMITTED_TEXT : "మేము మీ సమస్యను పరిష్కరించే పనిలో ఉన్నాము",
  CHOOSE_AN_OPTION : "కొనసాగించడానికి ఒక ఎంపికను ఎంచుకోండి",
  IMAGE_ADDED : "చిత్రం జోడించబడింది",
  DONE : "ముగించు",
  RECORD_VOICE_NOTE : "వాయిస్ నోట్ రికార్డు చేయండి",
  HELP_AND_SUPPORT : "సహాయం & మద్దతు",
  MORE_OPTIONS : "మరిన్ని ఎంపికలు",
  ONGOING_ISSUES : "కొనసాగుతున్న సమస్యలు",
  RESOLVED_ISSUES : "పరిష్కరించబడిన సమస్యలు",
  RESOLVED_ISSUE : "సమస్య పరిష్కరించబడింది",
  ONGOING_ISSUE : "కొనసాగుతున్న సమస్య",
  LOST_ITEM : "పోయిన వస్తువు",
  RIDE_RELATED_ISSUE : "రైడ్ సంబంధిత సమస్య",
  APP_RELATED_ISSUE : "యాప్ సంబంధిత సమస్య",
  FARE_RELATED_ISSUE : "ఛార్జీల సంబంధిత సమస్య",
  MAX_IMAGES : "గరిష్టంగా 3 చిత్రాలను అప్‌లోడ్ చేయవచ్చు",
  ISSUE_NUMBER : "సంచిక నం.   ",
  REMOVE_ISSUE : "సమస్యను తొలగించు",
  CALL_SUPPORT_NUMBER : "మద్దతును సంప్రదించండి",
  YEARS_AGO : "సంవత్సరాల క్రితం",
  MONTHS_AGO : "మాసాల క్రితం",
  DAYS_AGO : "రోజుల క్రితం",
  HOURS_AGO : "గంటల క్రితం",
  MIN_AGO : "నిమిషాల క్రితం",
  SEC_AGO : "సెకన్ల క్రితం",
  LOADING : "లోడింగ్",
  APP_RELATED : "యాప్ సంబంధిత",
  FARE : "ఛార్జీలకు సంబంధించినది",
  RIDE_RELATED : "రైడ్ సంబంధిత",
  LOST_AND_FOUND : "లాస్ట్ అండ్ ఫౌండ్",
  REPORT_LOST_ITEM : "కోల్పోయిన అంశాన్ని నివేదించండి",
  SELECT_YOUR_GENDER: "మీ లింగాన్ని ఎంచుకోండి",
  FEMALE: "స్త్రీ",
  MALE: "పురుషుడు",
  PREFER_NOT_TO_SAY: "చెప్పకపోవడమే ఇష్టం",
  GENDER : "లింగం",
  SET_NOW : "ఇప్పుడే సెట్ చేయి",
  COMPLETE_YOUR_PROFILE_AND_FIND_MORE_RIDES : "మీ ప్రొఫైల్‌ని పూర్తి చేయండి మరియు మరిన్ని రైడ్‌లను కనుగొనండి!",
  UPDATE_NOW : "అప్డేట్ చేయండి",
  CONFIRM : "నిర్ధారించండి",
  GENDER_UPDATED : "లింగం అప్డేట్ చేయబడింది",
  CORPORATE_ADDRESS : "కార్పొరేట్ చిరునామా",
  CORPORATE_ADDRESS_DESCRIPTION : "జుస్పే టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్ <br> గిరిజా బిల్డింగ్, నంబర్ 817, గణపతి టెంపుల్ రోడ్, 8వ బ్లాక్, కోరమంగళ, బెంగళూరు, కర్ణాటక 560095, ఇండియా.",
  CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL : "వెబ్సైటు: <u>https://nammayatri.in/</u>",
  REGISTERED_ADDRESS : "రిజిస్టర్డ్ చిరునామా",
  REGISTERED_ADDRESS_DESCRIPTION : "జుస్పే టెక్నాలజీస్ ప్రైవేట్ లిమిటెడ్ <br> స్టాలియన్ బిజినెస్ సెంటర్, నం. 444, 3వ & 4వ అంతస్తు, 18వ ప్రధాన, 6వ బ్లాక్, కోరమంగళ బెంగళూరు, కర్ణాటక- 560095, ఇండియా.",
  REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL : "వెబ్సైటు: <u>https://nammayatri.in/</u>",
  ZONE_CANCEL_TEXT_DROP : "మీ కస్టమర్ బహుశా రద్దీలో ఉండవచ్చు సమయానికి మెట్రో స్టేషన్ చేరుకోవడానికి! \n రద్దు చేయవద్దని మేము మిమ్మల్ని కోరుతున్నాము.",
  ZONE_CANCEL_TEXT_PICKUP : "మీ కస్టమర్ బహుశా తమ గమ్యస్థానాన్ని చేరుకోవడానికి ఆతురుతలో ఉన్నారు. \n రద్దు చేయవద్దని మేము మిమ్మల్ని కోరుతున్నాము.",
  RANKINGS : "పోటీ",
  GETTING_THE_LEADERBOARD_READY : "లీడర్‌బోర్డ్‌ను సిద్ధం చేస్తున్నాము!",
  PLEASE_WAIT_WHILE_WE_UPDATE_THE_DETAILS : "మేము వివరాలను అప్‌డేట్ చేసే వరకు దయచేసి వేచి ఉండండి",
  LAST_UPDATED : "చివరిగా అప్డేట్ చేసింది: ",
  CONGRATULATIONS_YOU_ARE_RANK : "అభినందనలు! మీ ర్యాంకు",
  YOU : "మీరు",
  DAILY : "రోజువారీ",
  WEEKLY : "వారానికోసారి",
  ACCEPT_RIDES_TO_ENTER_RANKINGS : "ర్యాంకింగ్స్‌లోకి ప్రవేశించడానికి రైడ్‌లను అంగీకరించండి!",
  OTP_HAS_BEEN_RESENT : "OTP మళ్లీ పంపబడింది",
  OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_RESENDING_OTP : "OTP నమోదు పరిమితి అయిపోయింది, దయచేసి OTPని మళ్లీ పంపడానికి ప్రయత్నించండి",
  OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER : "OTP రీసెండ్ పరిమితి అయిపోయింది, దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి",
  OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN : "OTP పేజీ గడువు ముగిసింది, దయచేసి OTPని మళ్లీ అభ్యర్థించండి",
  SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN : "ఏదో తప్పు జరిగింది, దయచేసి మళ్లీ ప్రయత్నించండి",
  INVALID_REFERRAL_CODE : "చెల్లని రిఫరల్ కోడ్",
  ISSUE_REMOVED_SUCCESSFULLY : "సమస్య విజయవంతంగా తీసివేయబడింది",
  OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER : "OTP నమోదు పరిమితి అయిపోయింది, దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి",
  TOO_MANY_ATTEMPTS_PLEASE_TRY_AGAIN_LATER : "చాలా చెల్లని ప్రయత్నాలు. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి",
  INVALID_REFERRAL_NUMBER : "చెల్లని రెఫరల్ నంబర్",
  SOMETHING_WENT_WRONG_TRY_AGAIN_LATER : "ఏదో తప్పు జరిగినది. దయచేసి కాసేపు ఆగాక ప్రయత్నించండి",
  WAIT_TIME : "వేచి ఉండే సమయం",
  WAIT_TIMER : "వెయిట్ టైమర్",
  HOW_LONG_WAITED_FOR_PICKUP : "మీరు పికప్ వద్ద ఎంతసేపు వేచి ఉన్నారో మీకు చూపుతుంది.",
  CUSTOMER_WILL_PAY_FOR_EVERY_MINUTE : "కస్టమర్ మొదటి 3 నిమిషాల తర్వాత ప్రతి నిమిషానికి ₹1.50 చెల్లిస్తారు",
  OTHERS : "ఇతరులు",
  ENTER_SECOND_SIM_NUMBER : "రెండవ SIM నంబర్‌ని నమోదు చేయండి",
  ALTERNATE_NUMBER : "ఆల్టర్నేట్ నంబర్‌",
  SELECT_THE_LANGUAGES_YOU_CAN_SPEAK : "మీరు మాట్లాడగల భాషలను ఎన్నుకోండి",
  OTP_RESEND_LIMIT_EXCEEDED : "OTP పరిమితిని మించారు",
  LIMIT_EXCEEDED_FOR_ALTERNATE_NUMBER : "దయచేసి కొంత సమయం తర్వాత మళ్లీ ప్రయత్నించండి",
  ALTERNATE_NUMBER_CANNOT_BE_ADDED : "ఆల్టర్నేట్ నంబర్‌ జోడించబడలేదు",
  OTP_RESENT: "OTP మళ్ళి పంపించాము",
  SEDAN : "సెడాన్",
  SUV : "ఎస్యూవీ",
  HATCHBACK : "హ్యాచ్‌బ్యాక్",
  AUTO_RICKSHAW : "ఆటో రిక్షా",
  TAXI : "నాన్-AC టాక్సీ",
  TAXI_PLUS : "AC టాక్సీ",
  MY_PROFILE : "నా ప్రొఫైల్",
  SETTINGS : "సెట్టింగులు",
  REG_NUMBER : "రెగ్. సంఖ్య",
  TYPE : "రకం",
  MODEL_NAME : "మోడల్ పేరు",
  COLOUR : "రంగు",
  BADGES : "బ్యాడ్జీలు",
  CALL_CUSTOMER_SUPPORT : "కస్టమర్ సపోర్ట్‌కి కాల్ చేయండి",
  EDIT_RC : "RCని ఎడిట్ చేయండి",
  DELETE_RC : "RCని తొలగించండి",
  DEACTIVATE_RC : "RC డీఆక్టివేట్ చేయి",
  ACTIVATE_RC : "RCని ఆక్టివేట్  చేయి",
  ACTIVE_RC_ON_ANOTHER_DRIVER : "మరొక డ్రైవర్ ఖాతాలో సక్రియంగా ఉంది!",
  CALL_DRIVER_OR_CONTACT_SUPPORT : "RC డీఆక్టివేట్ చేయడానికి డ్రైవర్‌కు కాల్ చేయండి లేదా డ్రైవర్ అందుబాటులో లేకుంటే మద్దతును సంప్రదించండి",
  CALL_DRIVER : "డ్రైవర్‌కి కాల్ చేయండి",
  SKIP : "స్కిప్",
  ACTIVE_STR : "యాక్టివ్",
  INACTIVE_RC : "ఇనాక్టివ్",
  CONFIRMATION_FOR_DELETING_RC : "మీరు ఖచ్చితంగా మీ RCని తొలగించాలనుకుంటున్నారా",
  CONFIRMATION_FOR_DEACTIVATING_RC : "మీరు ఖచ్చితంగా మీ RC డీఆక్టివేట్ చేయాలనుకుంటున్నారా- ",
  CONFIRMATION_FOR_ACTIVATING_RC : "మీరు ఖచ్చితంగా RC-ని యాక్టివేట్ చేయాలనుకుంటున్నారా",
  YES_DELETE : "అవును, తొలగించు",
  ADD_NEW_RC : "RC జోడించు",
  CONNECT_CALL_ANONYMOUSLY: "మేము మిమ్మల్ని డ్రైవర్‌తో అనామకంగా కనెక్ట్ చేయడానికి ప్రయత్నిస్తాము, దయచేసి RCని డీఆక్టివేట్ చేయమని అభ్యర్థించడానికి ముందు మిమ్మల్ని మీరు పరిచయం చేసుకోండి.",
  YES_ACTIVATE : "అవును, యాక్టివేట్ చేయి",
  YES_DEACTIVATE : "అవును, డియాక్టివేట్ చేయి",
  THIS_WILL_DEACTIVATE_CURRENTLY_ACTIVE_RC : "ఇది మీ ప్రస్తుతం యాక్టివ్‌గా ఉన్న RCని డీఆక్టివేట్ చేస్తుంది.",
  REMOVED : "తీసివేయబడింది",
  IS_ACTIVE_NOW : " ఇప్పుడు ఆక్టివ్ గా ఉంది.",
  DEACTIVATED : "డీఆక్టివేట్ చేయబడింది",
  LANGUAGE_UPDATED : "భాష నవీకరించబడింది",
  SINGLE_RC_CANNOT_BE_DELETED : "సింగిల్ RC తొలగించబడదు",
  CANCELLATION_RATE : "రద్దు రేటు",
  RIDES_CANCELLED : "రైడ్‌లు రద్దు చేయబడ్డాయి",
  EARNINGS_MISSED : "తప్పిన సంపాదన",
  SUMMARY : "సారాంశం",
  NAMMA_BONUS  : "నమ్మ బోనస్",
  TRIPS_COMPLETED : "పూర్తయిన పర్యటనలు",
  LATE_NIGHT_TRIPS  : "అర్థరాత్రి పర్యటనలు",
  ABOUT_ME  : "నా గురించి",
  ABOUT_VEHICLE : "వాహనం గురించి",
  ADD : "జోడించు",
  YEARS_OLD  : "ఏళ్ళ వయసు",
  HOMETOWN  : "స్వస్థలo",
  MISSED_OPPORTUNITY : "కోల్పోయిన అవకాశాలు",
  HOW_OLD_IS_YOUR_VEHICLE : "మీ వాహనం (సంవత్సరాలలో) ఎంత పాతది?",
  ENTER_NAME_OF_VEHICLE : "మీ వాహనం పేరును నమోదు చేయండి",
  NEW_ : "కొత్తది",
  WITH : "తో",
  CHOOSE_LANGUAGE : "భాషను ఎంచుకోండి",
  TOTAL_MONEY_COLLECTED : "సేకరించిన మొత్తం డబ్బు",
  FARE_EARNED_OF_THE_DAY : "ఈరోజు సంపాదించిన ఛార్జీ",
  GST_PLUS_PAYABLE : "GST + చెల్లించవలసిన రుసుము",
  TO_CONTINUE_USING_YATRI_SATHI : "యాత్రి సాతిని ఉపయోగించడం కొనసాగించడానికి, దయచేసి మీ చెల్లింపును పూర్తి చేయండి",
  PAY : "చెల్లించు",
  LATER : "తరువాత",
  GREAT_JOB : "గుడ్ జాబ్!",
  YOU_HAVE_COMPLETED_RIDES_YESTERDAY : "మీరు నిన్న X రైడ్‌లను పూర్తి చేసారు!",
  FEE_BREAKUP : "రుసుము విచ్ఛిన్నం",
  YATRI_SATHI_FEE_PAYABLE_FOR_DATE : "యాత్రి సాతి ఫీజు చెల్లించాలి",
  FEE_CORRESPONDING_TO_THE_DISTANCE : "ఒక్కో ట్రిప్‌కు ప్రయాణించిన దూరానికి సంబంధించిన రుసుము, దిగువ చూపిన విధంగా లెక్కించబడుతుంది.",
  PLATFORM_FEE : "ప్లాట్‌ఫారమ్ రుసుము",
  GST  : "GST",
  TOTAL_PAYABLE : "చెల్లించవలసిన మొత్తం",
  VIEW_DETAILS : "వివరాలను చూడండి",
  PAYMENT_SUCCESSFUL : "పేమెంట్ విజయవంతమైంది!",
  PAYMENT_PENDING : "పేమెంట్ పెండింగ్‌లో ఉంది!",
  PAYMENT_FAILED : "పేమెంట్ విఫలమైంది!",
  PAYMENT_PENDING_DESC : "చింతించకండి, మీరు ఇప్పటికీ రోజంతా రైడ్‌లను కొనసాగించవచ్చు!",
  PAYMENT_FAILED_DESC : "మీరు చెల్లింపును మళ్లీ ప్రయత్నించవచ్చు లేదా మీ సమీపంలోని యాత్రి సాతి బూత్‌లో చెల్లింపు చేయవచ్చు",
  WE_WILL_NOTIFY_WHEN_PAYMENT_SUCCESS : "మీ చెల్లింపు విజయవంతం అయినప్పుడు మేము తెలియజేస్తాము",
  CONTINUE_TAKING_RIDES : "రైడ్‌లను కొనసాగించండి",
  YOUR_PREVIOUS_PAYMENT_IS_PENDING : "మీ మునుపటి చెల్లింపు ఇప్పటికీ పెండింగ్‌లో ఉంది",
  GOVERMENT_CHARGES : "ప్రభుత్వ ఛార్జీలు",
  TODAY : "ఈరోజు",
  OKAY : "సరే",
  NO_PAYMENT_HISTORY_AVAILABLE : "చెల్లింపు చరిత్ర లేదు",
  YOU_DONT_HAVE_ANY_PAYMENTS : "మీరు ఇంకా ఎలాంటి చెల్లింపు చేయలేదు",
  ENTER_AADHAAR_NUMBER : "ఆధార్ నంబర్/UIDని నమోదు చేయండి",
  ENTER_AADHAAR_OTP_ : "ఆధార్ OTPని నమోదు చేయండి",
  AADHAAR_LINKING_REQUIRED : "ఆధార్ లింకింగ్ అవసరం",
  AADHAAR_LINKING_REQUIRED_DESCRIPTION : "యాత్రి సాతి కోసం డ్రైవింగ్ ప్రారంభించడానికి, దయచేసి \n మీ ఆధార్ IDని లింక్ చేయండి",
  BY_CLICKING_THIS_YOU_WILL_BE_AGREEING_TO_OUR_TC : "కొనసాగించు క్లిక్ చేయడం ద్వారా, మీరు మా ",
  TERMS_AND_CONDITIONS_SHORT : "నిబంధనలు & షరతులు",
  TC_TAIL : "",
  OTP_SENT_TO_AADHAAR_NUMBER: "మీ ఆధార్‌తో లింక్ చేయబడిన మొబైల్ నంబర్‌కు OTP పంపబడింది",
  ENTER_SIX_DIGIT_OTP : "6 అంకెల OTPని ఎంటర్ చేయండి",
  LINK_AADHAAR_ID : "ఆధార్ IDని లింక్ చేయండి",
  NO_MOBILE_NUMBER_REGISTERED : "ఆధార్ నంబర్కు మీ మొబైల్ నంబర్  రిజిస్టర్ అయ్యి లేదు.",
  EXCEED_OTP_GENERATION_LIMIT : "గరిష్ట OTP ఉత్పత్తి పరిమితి మించిపోయింది. దయచేసి కొంత సమయం తర్వాత మళ్లీ ప్రయత్నించండి.",
  AADHAAR_NUMBER_NOT_EXIST : "ఆధార్ నంబర్ లేదు.",
  INVALID_OTP : "చెల్లని OTP",
  NO_SHARE_CODE : "షేర్ కోడ్ అందించబడలేదు",
  WRONG_SHARE_CODE : "తప్పు షేర్ కోడ్",
  INVALID_SHARE_CODE : "చెల్లని షేర్ కోడ్. కోడ్ పొడవు 4 ఉండాలి మరియు సంఖ్యలను మాత్రమే కలిగి ఉండాలి.",
  SESSION_EXPIRED : "సెషన్ ముగిసిపోయింది. దయచేసి ప్రక్రియను మళ్లీ ప్రారంభించండి.",
  OTP_ATTEMPT_EXCEEDED : "OTP ప్రయత్నాలు మించిపోయాయి. దయచేసి ప్రక్రియను మళ్లీ ప్రారంభించండి",
  UPSTREAM_INTERNAL_SERVER_ERROR : "అప్‌స్ట్రీమ్ మూలం/ప్రభుత్వ మూలం అంతర్గత సర్వర్ లోపం. దయచేసి ప్రక్రియను మళ్లీ ప్రారంభించండి.",
  TRANSACTION_ALREADY_COMPLETED : "ఇప్పటికే లావాదేవీ పూర్తయింది. దీనిపై తదుపరి ఆపరేషన్ చేయలేము",
  ENTER_AADHAAR_DETAILS : "ఆధార్ వివరాలను నమోదు చేయండి",
  GOTO_YOUR_NEAREST_BOOTH : "మీ ఆధార్ వెరిఫై చేసుకోవడానికి దయచేసి మీ సమీప బూత్‌ను సంప్రదించండి",
  AADHAAR_ALREADY_LINKED : "ఇప్పటికే ఆధార్ లింక్ చేయబడింది",
  OPTIONAL : "(ఐచ్ఛికం)",
  DOWNLOAD_STATEMENT : "స్టేట్మెంట్ డౌన్‌లోడ్ చేయండి",
  SELECT_A_DATE_RANGE : "స్టేట్‌మెంట్‌ను డౌన్‌లోడ్ చేయడానికి తేదీ పరిధిని ఎంచుకోండి",
  FEE_PAYMENT_HISTORY : "ఫీజు చెల్లింపు చరిత్ర",
  LANGUAGES_SPOKEN : "మాట్లాడగల భాషలు",
  VIEW_PAYMENT_HISTORY : "చెల్లింపు చరిత్రను వీక్షించండి",
  RIDE_TYPE : "రైడ్ రకం",
  PLACE_CALL_REQUEST : "కాల్ అభ్యర్థన చేయండి",
  RC_STATUS : "RC స్టేటస్",
  RATED_BY_USERS1 : "రేట్ చేసింది",
  RATED_BY_USERS2 : "వినియోగదారులు",
  MONTHS : "నెలలు",
  CALL_REQUEST_HAS_BEEN_PLACED : "మీ కాల్ అభ్యర్థన చేయబడింది",
  RC_ADDED_SUCCESSFULLY : "RC జోడించబడింది",
  OFFER_APPLIED : "ఆఫర్ వర్తింపజేయబడింది",
  YOUR_EARNINGS : "మీ సంపాదన",
  NUMBER_OF_RIDES : "రైడ్‌ల సంఖ్య",
  FARE_BREAKUP : "ఛార్జీల విచ్ఛిన్నం",
  MY_PLAN : "నా ప్లాన్",
  YOUR_DUES : "మీ బకాయిలు",
  YOUR_DUES_DESCRIPTION : "మా బకాయిలు మీ బకాయిలను క్లియర్ చేయడానికి మీరు ఆటోపేను సెటప్ చేసారు. మేము స్వయంచాలకంగా సమయానికి చెల్లించినట్లు నిర్ధారించడానికి ప్రయత్నిస్తాము.",
  YOUR_DUES_DESCRIPTION_MANUAL : "అంతరాయం లేని రైడ్‌లను కొనసాగించడానికి దయచేసి మీ బకాయిలను పరిమితిని చేరుకోవడానికి ముందే క్లియర్ చేయండి. మీరు <b>సెటప్ కూడా చేయవచ్చు an UPI Autopay</b> for easier, hassle-free payments.",
  CURRENT_DUES : "ప్రస్తుత బాకీలు",
  YOUR_LIMIT : "మీ పరిమితి",
  DUE_DETAILS : "బాకీల వివరాలు",
  TRIP_DATE : "పర్యటన తేదీ",
  AMOUNT : "మొత్తం",
  VIEW_DUE_DETAILS : "బాకీల వివరాలను వీక్షించండి",
  SETUP_AUTOPAY : "ఆటోపే సెటప్ చేయండి",
  CURRENT_PLAN : "ప్రస్తుత ప్రణాళిక",
  ALTERNATE_PLAN : "ఆల్టర్నేట్ ప్రణాళిక",
  AUTOPAY_DETAILS : "ఆటోపేయ్ వివరాలు",
  CANCEL_AUTOPAY_STR : "ఆటోపేయ్ రద్దు చేయండి",
  WE_MIGHT_BE_LOST : "ఎర్రర్ సంభవించింది",
  EXEPERIENCING_ERROR : "ఎర్రర్ సంభవించింది",
  ENJOY_THESE_BENEFITS : "మీరు చేరితే ప్రయోజనాలు",
  CHOOSE_YOUR_PLAN : "ఇప్పుడే ప్రణాళికను ఎంచుకోండి!",
  SKIP_FOR_NOW : "ప్రస్తుతానికి దాటవేయి",
  NAMMAYATRI_PLANS  : "నమ్మ యాత్రి ప్రణాళిక",
  SEVEN_DAY_FREE_TRIAL_ACTIVATED : "7-రోజుల ఉచిత ట్రయల్ ఆక్టివేట్ చేయబడింది!",
  TAKE_UNLIMITED_RIDES_FOR_THE_NEXT_SEVEN_DAYS : "మొదటి 7 రోజులు అపరిమిత రైడ్‌లను తీసుకోండి",
  EVERY_RIDE_AT_ZERO_COMMISSION : "ప్రతి రైడ్ జీరో కమిషన్ తో!",
  EARN_UPTO_PER_DAY : "రోజుకు ₹2500 వరకు సంపాదించండి!",
  HOW_THIS_WORKS : "ఇది ఎలా పని చేస్తుంది",
  SIGN_UP_FOR_AUTOPAY_BY_PAYING_JUST : "కేవలం ₹1 చెల్లించడం ద్వారా ఆటోపేయ్ సైన్ అప్ చేయండి" ,
  GET_REMINDED_ABOUT_YOUR_PLAN_SETUP : "నా ప్లాన్ సెటప్ గురించి నాకు గుర్తు చేయండి",
  FREE_TRIAL_REMINDER : "5వ రోజు: ఉచిత ట్రయల్ రిమైండర్",
  PLAN_STARTS : "7వ రోజు: ప్రణాళిక ప్రారంభమవుతుంది",
  EASY_AUTOMATIC_PAYMENTS_START : "సులభమైన, స్వయంచాలక చెల్లింపులు ప్రారంభం",
  FREE_UNTIL : "ఈరోజు వరకు ఉచితం", 
  PER_RIDE : "ప్రతి రైడ్",
  PER_DAY : "రోజుకు",
  OFFER : "ఆఫర్",
  OFFERS : "ఆఫర్లు",
  YOU_ARE_ON_THE_FREE_TRIAL : "మీరు ఉచిత ట్రయల్‌లో ఉన్నారు",
  SETUP_AUTOPAY_BEFORE_THE_TRAIL_PERIOD_EXPIRES : "ట్రయల్ వ్యవధి ముగిసేలోపు ఆటోపేయ్ సెటప్ చేయండి",
  GET_FREE_TRAIL_UNTIL : "ఉచిత ట్రయల్ ఈ రోజు వరకు",
  CLEAR_DUES : "బాకీలు క్లియర్ చేయండి",
  PAYMENT_PENDING_ALERT : "⚠️ చెల్లింపు పెండింగ్‌లో ఉంది! ⚠️",
  PAYMENT_PENDING_ALERT_DESC : "నమ్మ యాత్రిలో ప్రయాణించడం కొనసాగించడానికి, మీ చెల్లింపు బాకీలను క్లియర్ చేయండి",
  LOW_ACCOUNT_BALANCE : "తక్కువ ఖాతా బ్యాలెన్స్",
  LOW_ACCOUNT_BALANCE_DESC : "మీ బ్యాంక్ ఖాతా బ్యాలెన్స్ తక్కువగా ఉంది. అంతరాయం లేని రైడ్‌లను ఆస్వాదించడానికి ఈరోజులోపు ₹<X> జోడించండి.",
  OKAY_GOT_IT : "సరే, అర్థమైంది",
  LIMITED_TIME_OFFER : "మీ కోసం పరిమిత కాల ఆఫర్!",
  JOIN_NOW : "ఇప్పుడే చేరండి",
  AUTOMATIC_PAYMENTS_WILL_APPEAR_HERE : "ఆటోమేటిక్ చెల్లింపులు ఇక్కడ కనిపిస్తాయి",
  MANUAL_PAYMENTS : "మాన్యువల్ చెల్లింపులు",
  MANUAL_PAYMENTS_WILL_APPEAR_HERE : "మాన్యువల్ చెల్లింపులు ఇక్కడ కనిపిస్తాయి",
  NO_AUTOMATIC_PAYMENTS_DESC : "మీకు ఛార్జీ విధించిన తర్వాత మీ ఆటోపేయ్ చరిత్ర ఇక్కడ కనిపిస్తుంది",
  NO_MANUAL_PAYMENTS_DESC : "బాకీలు క్లియర్ చేయడానికి మీ చెల్లింపు చరిత్ర ఏదైనా ఉంటే ఇక్కడ కనిపిస్తుంది.",
  PAYMENT_HISTORY : "చెల్లింపు చరిత్ర",
  TAP_A_PLAN_TO_VIEW_DETAILS : "వివరాలను వీక్షించడానికి ప్లాన్‌ను నొక్కండి",
  HOW_IT_WORKS : "ఇది ఎలా పని చేస్తుంది?",
  ZERO_COMMISION : "జీరో కమీషన్",
  EARN_TODAY_PAY_TOMORROW : "ఈ రోజు సంపాదించండి, రేపు చెల్లించండి",
  PAY_ONLY_IF_YOU_TAKE_RIDES : "మీరు రైడ్ చేస్తేనే చెల్లించండి",
  ప్రణాళిక: "ప్రణాళిక",
  DAY : "రోజు",
  PLANS : "ప్రణాళికలు",
  MANAGE_PLAN : "ప్రణాళికను నిర్వహించండి",
  VIEW_AUTOPAY_DETAILS : "ఆటోపాయ్ వివరాలను వీక్షించండి",
  SWITCH_AND_SAVE : "మారండి మరియు సేవ్ చేయండి",
  SWITCH_AND_SAVE_DESC : "మీరు ఈరోజు 7 రైడ్‌లను పూర్తి చేసారు. రోజువారీ అన్‌లిమిటెడ్ ప్లాన్‌కి మారడం ద్వారా ₹10 వరకు ఆదా చేసుకోండి",
  SWITCH_NOW : "ఇప్పుడే మారండి",
  PAYMENT_MODE_CHANGED_TO_MANUAL : "చెల్లింపు మోడ్ మాన్యువల్‌కి మార్చబడింది",
  PAYMENT_MODE_CHANGED_TO_MANUAL_DESC : "<b>మీరు మీ UPI ఆటోపే పాజ్ చేసారు. ఇది మీ UPI యాప్ నుండి పునఃప్రారంభించబడుతుంది.</b><br>మీరు మీ బాకీలను మాన్యువల్‌గా కూడా క్లియర్ చేయవచ్చు.",
  AUTOPAY_PAYMENTS : "ఆటోపే పేమెంట్స్",
  TRANSACTION_ON : "లావాదేవీ తేదీ",
  SUCCESS : "విజయం",
  DEBITED_ON : "డెబిట్ చేయబడింది",
  RIDES_TAKEN_ON : "రైడ్స్ తేదీ",
  JOIN_PLAN : "ప్లాన్‌లో చేరండి",
  JOIN_NAMMAA_YATRI : "నమ్మ యాత్రిలో చేరండి",
  CANCEL_AUTOPAY_AND_PAY_MANUALLY : "ఆటోపేను రద్దు చేసి, మాన్యువల్‌గా చెల్లించండి",
  PLAN_ACTIVATED_SUCCESSFULLY : "ప్లాన్ విజయవంతంగా ఆక్టివేట్ చేయబడింది",
  DUES_CLEARED_SUCCESSFULLY : "బాకీలు విజయవంతంగా క్లియర్ చేయబడ్డాయి",
  NOT_PLANNING_TO_TAKE_RIDES : "రైడ్ చేయాలనుకోట్లేదా?",
  RETRY_PAYMENT_STR : "చెల్లింపును మళ్లీ ప్రయత్నించండి",
  PAUSE_AUTOPAY_STR : "ఆటోపే పాజ్ చేయండి",
  SETUP_AUTOPAY_STR : "ఆటోపే సెటప్",
  VIEW_RIDE_DETAILS : "రైడ్ వివరాలను చూడండి",
  ACCOUNT : "ఖాతా",
  AUTOPAY_IS_NOT_ENABLED_YET : "ఆటోపే ఇంకా ప్రారంభించబడలేదు!",
  ENABLE_AUTOPAY_DESC : "అవాంతరాలు లేని చెల్లింపులను ప్రారంభించడానికి ఇప్పుడే ఆటోపేను ప్రారంభించండి!",
  ENABLE_AUTOPAY_NOW : "ఇప్పుడే ఆటోపాయ్ ప్రారంభించు",
  AUTOPAY_SETUP_PENDING_STR : "ఆటోపే సెటప్ పెండింగ్‌లో ఉంది!",
  AUTOPAY_PENDING_DESC_STR : "వేచి ఉండండి లేదా చెల్లింపును మళ్లీ ప్రయత్నించండి. అదనపు చెల్లింపు తిరిగి ఇవ్వబడుతుంది.",
  REFRESH_STR : "స్థితిని తనిఖీ చేయండి",
  TRANSACTION_DETAILS : "లావాదేవీ వివరాలు",
  RIDE_DETAILS : "రైడ్ వివరాలు",
  MY_PLAN_TITLE : "నమ్మ యాత్రి ప్రణాళికలు",
  SWITCH_TO : "{} ప్లాన్‌కి మారండి",
  PLEASE_TRY_AGAIN : "దయచేసి మళ్లీ ప్రయత్నించండి",
  PLAN_NOT_FOUND : "ప్లాన్ దొరకలేదు",
  MANDATE_NOT_FOUND : "మ్యాండేట్ కనుగొనబడలేదు",
  ACTIVE_MANDATE_EXISTS : "సక్రియ మ్యాండేట్ ఇప్పటికే ఉంది",
  NO_ACTIVE_MANDATE_EXIST : "సక్రియ మ్యాండేట్ లేదు",
  NO_PLAN_FOR_DRIVER : "ప్లాన్ దొరకలేదు",
  INVALID_PAYMENT_MODE : "చెల్లని చెల్లింపు మోడ్",
  INVALID_AUTO_PAY_STATUS : "చెల్లని ఆటోపే స్థితి",
  MAX_AMOUNT : "గరిష్ట మొత్తం",
  FREQUENCY : "తరచుదనం",
  STATRED_ON : "ప్రారంభించిన తేదీ",
  EXPIRES_ON : "గడువు ముగిసే తేదీ",
  SWITCHED_PLAN : "ప్లాన్ మార్చారు",
  RESUME_AUTOPAY : "ఆటోపే పునఃప్రారంభించబడింది",
  ONETIME : "ఒక్కసారి",
  FORTNIGHTLY : "పక్షంవారీ",
  MONTHLY : "నెలవారీ",
  BIMONTHLY : "ద్వైమాసిక",
  QUARTERLY : "త్రైమాసిక",
  HALFYEARLY : "అర్ధ సంవత్సరానికి",
  YEARLY : "వార్షిక",
  ASPRESENTED : "సమర్పించినప్పుడు",
  DAILY_PER_RIDE_DESC : "సెప్టెంబర్ 19 వరకు ఎటువంటి ఛార్జీలు లేవు",
  FIRST_FREE_RIDE : "మొదటి రైడ్ ఉచితం",
  JOIN_THE_UNLIMITED_PLAN : "ప్రత్యేక తగ్గింపులను పొందడానికి ఇప్పుడే డైలీ అన్‌లిమిటెడ్ ప్లాన్‌లో చేరండి",
  MAYBE_LATER : "తర్వాత చూద్దాం",
  DO_YOU_WANT_TO_CANCEL : "మీరు రద్దు చేయాలనుకుంటున్నారా?",
  DO_YOU_WANT_TO_CANCEL_DESC : "మీరు ఆటోపే రద్దు చేయబోతున్నారు.\nఆటోమేటిక్ పేమెంట్‌లను తిరిగి ప్రారంభించడానికి మీరు మళ్లీ ఆటోపేను సెటప్ చేయాలి.",
  YOUR_PAYMENT_WAS_UNSUCCESSFUL : "మీ చెల్లింపు ప్రయత్నం విఫలమైంది.",
  PAYMENT_CANCELLED : "మీరు మీ UPI ఆటోపేను రద్దు చేసారు. మీరు మీ బాకీలు మాన్యువల్‌గా క్లియర్ చేయవచ్చు.",
  UPI_AUTOPAY_S : "UPI ఆటోపే",
  MANUAL_PAYMENT_STR : "మాన్యువల్ చెల్లింపు",
  DAILY_UNLIMITED : "డైలీ అన్లిమిటెడ్",
  DAILY_PER_RIDE : "డైలీ పర్ రైడ్",
  DAILY_UNLIMITED_PLAN_DESC : "ప్రతిరోజూ అపరిమిత రైడ్‌లను ఆస్వాదించండి",
  DAILY_PER_RIDE_PLAN_DESC : "రోజుకు గరిష్టంగా ₹35 వరకు",
  AUTOPAY_CANCELLED : "ఆటోపే రద్దు చేయబడింది",
  NO : "వద్దు",
  YES_CANCEL : "అవును, రద్దు చేయి",
  PAY_TO_JOIN_THIS_PLAN : "ప్లాన్‌లో చేరడానికి ₹1 మాత్రమే చెల్లించండి",
  OFFERS_NOT_APPLICABLE : "పూర్తయితే తప్ప ఆఫర్‌లు వర్తించవు",
  PAUSED_STR : "పాజ్ చేయబడింది",
  PENDING_STR : "పెండింగ్‌లో ఉంది",
  SWITCH_PLAN_STR : "ప్లాన్ మార్చాలా?",
  PLAN_SWITCHED_TO : "ఈ ప్లాన్ కి మార్చబడింది",
  OFFERS_APPLICABLE_ON_DAILY_UNLIMITED : "గమనిక: డైలీ అన్‌లిమిటెడ్ ప్లాన్‌లో ఆటోపే సెటప్ చేస్తే మాత్రమే ఆఫర్‌లు వర్తిస్తాయి",
  DAILY_UNLIMITED_OFFER_NOT_AVAILABLE : "గమనిక: ఈ ప్లాన్‌పై డైలీ అన్‌లిమిటెడ్ ఆఫర్‌లు వర్తించవు!", 
  NO_RIDES_NO_CHARGE : "మీరు రైడ్ చేస్తే మాత్రమే చెల్లించండి",
  GET_SPECIAL_OFFERS : "ప్రత్యేక ఆఫర్లను పొందండి",
  VALID_ONLY_IF_PAYMENT : "చెల్లింపు పూర్తయితే మాత్రమే చెల్లుతుంది",
  HELP_STR : "సహాయం",
  REFRESH_STRING : "రిఫ్రెష్ చేయండి",
  CHAT_FOR_HELP : "సహాయం కోసం చాట్ చేయండి",
  VIEW_FAQs : "తరచుగా అడిగే ప్రశ్నలను వీక్షించండి",
  FIND_HELP_CENTRE : "సహాయ కేంద్రాన్ని కనుగొనండి",
  CONTACT : "సంప్రదించండి",
  GO_TO_LOCATION : "గో-టు స్థానానికి వెళ్లు",
  NO_HELP_CENTER_IS_ACTIVE_NOW : "ప్రస్తుతం ఏ సహాయ కేంద్రం యాక్టివ్‌గా లేదు",
  HELP_CENTERS_LOCATION_WILL_APPEAR_HERE_ONCE_THEY_ARE_ACTIVE : "సహాయ కేంద్రాల స్థానాలు సక్రియం అయిన తర్వాత ఇక్కడ కనిపిస్తాయి",
  SUPPORT : "మద్దతు",
  GO_TO_VEHICLE_DETAILS : "గో-టు వాహన వివరాలకు వెళ్లండి",
  CLOSE: "మూసివేయండి",
  RC_DEACTIVATED : "RC డియాక్టివేట్ చేయబడింది", 
  RC_DEACTIVATED_DETAILS : "మీ RC ప్రస్తుతం మరొక డ్రైవర్ ఖాతాలో సక్రియంగా ఉంది. రైడ్‌లను ప్రారంభించడానికి RCని యాక్టివేట్ చేయండి",
  NEED_HELP_JOINING_THE_PLAN : "ప్లాన్‌లో చేరడం లేదా ఆటోపే చేయడంలో సహాయం కావాలా?",
  NEED_HELP : "సహాయం కావాలా?",
  SETUP_AUTOPAY_NOW_TO_GET_SPECIAL_DISCOUNTS  : "ప్రత్యేక తగ్గింపులను పొందడానికి ఆటోపే సెటప్ చేయండి",
  SETUP_NOW : "ఇప్పుడే సెటప్ చేయండి",
  NEED_HELP_CALL_SUPPORT : "సహాయం కావాలా? <span style='color:#2194FF'>కాల్ సపోర్ట్</span>",
  CUSTOMER_HAS_LOW_MOBILITY: "కస్టమర్ తక్కువ మొబిలిటీని కలిగి ఉన్నారు",
  CUSTOMER_HAS_DISABILITY: "కస్టమర్ వైకల్యాన్ని కలిగి ఉన్నారు",
  CUSTOMER_HAS_LOW_VISION: "కస్టమర్‌కు కంటిచూపు బలహీనంగా ఉంది",
  CUSTOMER_HAS_HEARING_IMPAIRMENT: "కస్టమర్ వినికిడి శక్తి సరిగా లేదు",
  HELP_WITH_THEIR_MOBILITY_AID: "వారి కదలిక సహాయంతో సహాయం చేయండి",
  PLEASE_ASSIST_THEM_IF_NEEDED: "అవసరమైతే వారికి సహాయం చేయండి",
  MESSAGE_THEM_AT_PICKUP: "పికప్ వద్ద వారికి మెసేజ్ చేయండి",
  SOUND_HORN_ONCE_AT_PICKUP: "పికప్‌లో ఒకసారి హార్న్‌ వినిపించండి",
  PLEASE_CALL_AND_AVOID_CHATS: "దయచేసి కాల్ చేయండి మరియు చాట్‌లను నివారించండి",
  PLEASE_CHAT_AND_AVOID_CALLS: "దయచేసి చాట్ చేయండి మరియు కాల్‌లను నివారించండి",
  PLEASE_GO_TO_EXACT_PICKUP: "దయచేసి ఖచ్చితంగా సరైన పికప్ కి వెళ్లండి",
  CUSTOMER_HAS_POOR_VISION_SOUND_HORN_AT_PICKUP : "కస్టమర్ దృష్టి సరిగా లేదు. దయచేసి పికప్‌లో ఒకసారి హారన్‌ను వినిపించండి.",
  CUSTOMER_HAS_POOR_HEARING_MESSAGE_THEM_AT_PICKUP : "కస్టమర్ వినికిడి శక్తి తక్కువగా ఉంది. దయచేసి పికప్ సమయంలో వారికి ఒకసారి మెసేజ్ చేయండి.",
  CUSTOMER_HAS_LOW_MOBILITY_STORE_THEIR_SUPPORT_AT_PICKUP : "కస్టమర్ తక్కువ మొబిలిటీని కలిగి ఉన్నారు. దయచేసి ప్రయాణీకుల సీటు వెనుక వారి మద్దతును నిల్వ చేయడంలో వారికి సహాయపడండి.",
  CUSTOMER_HAS_DISABILITY_PLEASE_ASSIST_THEM : "కస్టమర్‌కు వైకల్యం ఉంది. దయచేసి వారికి వీలైనంత సహాయం చేయండి.",
  CUSTOMER_MAY_NEED_ASSISTANCE : "కస్టమర్‌కు సహాయం అవసరం కావచ్చు",
  LEARN_MORE : "ఇంకా తెలుసుకోండి",
  CUSTOMER_HAS_LOW_MOBILITY_GO_TO_EXACT_LOC : "కస్టమర్ తక్కువ మొబిలిటీని కలిగి ఉన్నారు. దయచేసి ఖచ్చితమైన పికప్ స్థానానికి వెళ్లండి.",
  CUSTOMER_HAS_POOR_HEARING_CHAT_WITH_THEM_INSTEAD_OF_CALLING : "కస్టమర్ వినికిడి శక్తి తక్కువగా ఉంది. దయచేసి కాల్ చేయడానికి బదులుగా వారితో చాట్ చేయండి.",
  CUSTOMER_HAS_LOW_VISION_CALL_THEM_INSTEAD_OF_CHATTING : "కస్టమర్ దృష్టి సరిగా లేదు. దయచేసి చాటింగ్ చేయడానికి బదులుగా వారికి కాల్ చేయండి.",
  PLEASE_HELP_THEM_AS_YOU_CAN : "దయచేసి వారికి వీలైనంత సహాయం చేయండి",
  LEARN_HOW_YOU_CAN_HELP_CUSTOMERS_REQUIRING_SPECIAL_ASSISTANCE : "ప్రత్యేక సహాయం అవసరమయ్యే కస్టమర్‌లకు మీరు ఎలా సహాయం చేయవచ్చో తెలుసుకోండి",
  ASSISTANCE_REQUIRED : "సహాయం అవసరం",
  SAVED_DUE_TO_ZERO_COMMISSION : "జీరో కమిషన్ కారణంగా సేవ్ చేయబడింది", 
  TIP_EARNED_FROM_CUSTOMER : "కస్టమర్ నుండి సంపాదించిన టిప్",
  COLLECT_VIA_CASE_UPI : "కాష్/UPI ద్వారా సేకరించండి",
  FARE_COLLECTED :  "ఛార్జీలు సేకరించబడ్డాయి",
  RATE_YOUR_RIDE_WITH1 : "మీ రైడ్ ని రేట్ చేయండి" ,
  RATE_YOUR_RIDE_WITH2 : "",
  HELP_US_WITH_YOUR_FEEDBACK : "మీ అభిప్రాయంతో మాకు సహాయం చేయండి (ఐచ్ఛికం)",
  COLLECT_CASH : "కాష్ సేకరించండి",
  ONLINE_PAYMENT : "ఆన్లైన్ చెల్లింపు",
  RIDE_COMPLETED : "రైడ్ పూర్తయింది",
  SUBMIT_FEEDBACK : "అభిప్రాయాన్ని సమర్పించండి",
  BADGE_EARNED : "బ్యాడ్జ్ సంపాదించారు",
  PURPLE_RIDE_CHAMPION : "పర్పుల్ రైడ్ ఛాంపియన్",
  PURPLE_RIDE : "పర్పుల్ రైడ్",
  PROCEED_TO_CHAT : "చాట్‌కి వెళ్లండి",
  PLEASE_CONSIDER_CALLING_THEM : "వారు చాట్‌లను చదవలేకపోవచ్చు. దయచేసి వారికి కాల్ చేయండి",
  JOIN_A_PLAN_TO_START_EARNING : "సంపాదించడం ప్రారంభించడానికి ప్లాన్‌లో చేరండి!",
  GO_ONLINE_PROMPT_SUBSCRIBE : "మీరు ప్రస్తుతం ఆఫ్‌లైన్‌లో ఉన్నారు.\nసవారీలు చేయడానికి ప్లాన్‌లో చేరండి",
  GO_ONLINE_PROMPT_PAYMENT_PENDING : "మీరు ప్రస్తుతం ఆఫ్‌లైన్‌లో ఉన్నారు.\nరైడ్ చేయడానికి మీ ప్లాన్ చెల్లింపును పూర్తి చేయండి",
  COMPLETE_PAYMENT_TO_CONTINUE : "యాత్రి సాతి ని ఉపయోగించడం కొనసాగించడానికి, దయచేసి మీ చెల్లింపును పూర్తి చేయండి",
  PENDING_CAPS : "పెండింగ్‌లో ఉంది",
  FAILURE : "వైఫల్యం",
  PAYMENT_MODE : "చెల్లింపు మోడ్",
  TXN_ID : "ఆర్డర్ గుర్తింపు సంఖ్యా",
  AMOUNT_PAID : "డబ్బులు చెల్లించబడినవి",
  NOTIFICATION_SCHEDULED : "నోటిఫికేషన్ షెడ్యూల్ చేయబడింది!",
  MANUAL_DUES : "మాన్యువల్ బాకీలు",
  AUTOPAY_IN_PROGRESS : "ఆటోపే ప్రోగ్రెస్‌లో ఉంది",
  MANUAL_DUE_OVERVIEW : "మాన్యువల్ డ్యూ ఓవర్‌వ్యూ",
  AUTOPAY_DUE_OVERVIEW : "ఆటోపే ఓవర్‌వ్యూ",
  MANUAL_DUE_AS_AUTOPAY_EXECUTION_FAILED : "ఆటోపే ఎగ్జిక్యూషన్ విఫలమైనందున మాన్యువల్ బకాయి ఉంది",
  CLEAR_MANUAL_DUES : "మాన్యువల్ బకాయిలను క్లియర్ చేయండి",
  DUE_OVERVIEW : "డ్యూ ఓవర్‌వ్యూ",
  MANUAL_DUE_DETAILS : "మాన్యువల్ బకాయి వివరాలు",
  AUTOPAY_DUE_DETAILS : "ఆటోపే బకాయి వివరాలు",
  SWITCHED_TO_MANUAL : "*ఆటోపే పూర్తి చేయలేనందున చెల్లింపు మోడ్ మాన్యువల్‌కి మార్చబడింది",
  SPLIT_PAYMENT : "*ఆటోపే అమలు చేయడానికి చెల్లింపు విభజించబడింది",
  GST_INCLUDE : "(18% GSTతో సహా)",
  SCHEDULED_AT : "షెడ్యూల్ చేయబడింది",
  PAYMENT_STATUS : "చెల్లింపు స్థితి",
  NOTIFICATION_ATTEMPTING :  "నోటిఫికేషన్ ప్రయత్నం", 
  EXECUTION_SCHEDULED :  "అమలు షెడ్యూల్ చేయబడింది", 
  EXECUTION_ATTEMPTING : "అమలు ప్రయత్నం", 
  EXECUTION_SUCCESS : "అమలు విజయం",
  SCHEDULED : "షెడ్యూల్ చేయబడింది",
  ONE_TIME_SETTLEMENT : "వన్-టైమ్ పేమెంట్ చేయండి",
  PAYMENT_SCHEDULED : "చెల్లింపు షెడ్యూల్ చేయబడింది",
  RETRY_AUTOPAY : "ఆటోపే మళ్లీ ప్రయత్నించండి",
  RETRY_STR : "మళ్లీ ప్రయత్నించండి ",
  ONGOING_PAYMENT_EXECUTION : "మాన్యువల్ చెల్లింపు కొనసాగుతోంది, దయచేసి వేచి ఉండండి",
  OFFER_CARD_BANNER_TITLE : "ఆటోపే సెటప్ చేయండి మరియు {} వరకు రోజుకు ₹15 మాత్రమే చెల్లించండి",
  OFFER_CARD_BANNER_DESC : "నవంబర్ 1 వరకు రోజుకు ₹15 మాత్రమే చెల్లించండి",
  OFFER_CARD_BANNER_ALERT : "మీ ఆటోపే సెటప్ పెండింగ్‌లో ఉంది!",
  OR: "లేదా",
  COLLECT_CASH_DIRECTLY : "నేరుగా కాష్ సేకరించండి",
  OR_COLLECT_CASH_DIRECTLY : "లేదా నేరుగా కాష్ సేకరించండి",
  SETUP_AUTOPAY_TO_ACCEPT_PAYMENT : "మీ బ్యాంక్ ఖాతాకు నేరుగా చెల్లింపులను అంగీకరించడానికి, మీ ప్లాన్‌లో ఆటోపేను సెటప్ చేయండి",
  DOWNLOAD_QR : "QRని డౌన్‌లోడ్ చేయండి",
  USE_THIS_QR_TO_COLLECT_PAYMENT : "రైడ్ ముగిసిన తర్వాత చెల్లింపును సేకరించేందుకు మీరు ఈ QR కోడ్‌ని ఉపయోగించవచ్చు.",
  AMOUNT_WILL_DEPOSITED_TO_BANK_ACCOUNT : "మీరు UPI ఆటోపే కోసం ఉపయోగిస్తున్న బ్యాంక్ ఖాతాలో మొత్తం జమ చేయబడుతుంది",
  GET_DIRECTLY_TO_YOUR_BANK_ACCOUNT : "UPI IDకి నేరుగా చెల్లింపు పొందండి",
  PAYMENT : "చెల్లింపు",
  QR_CODE : "QR కోడ్",
  GET_QR_CODE : "QR కోడ్ పొందండి",
  EXECUTION_FAILED : "అమలు విఫలమైంది", 
  NOTIFICATION_FAILED : "నోటిఫికేషన్ విఫలమైంది",
  PAY_NOW : "ఇప్పుడే చెల్లించండి",
  CLEAR_DUES_BANNER_TITLE : "నాన్‌స్టాప్ రైడ్‌లను ఆస్వాదించడానికి \nమీ బకాయిలను (₹{}) క్లియర్ చేయండి",
  COLLECT_VIA_UPI_QR_OR_CASH : "UPI QR లేదా కాష్ ద్వారా సేకరించండి",
  TRANSACTION_DEBITED_ON : "లావాదేవీ డెబిట్ తేదీ",
  TRANSACTION_ATTEMPTED_ON : "లావాదేవీకి ప్రయత్నించిన తేదీ",
  AUTOPAY_SETUP_AND_PAYMENT_SUCCESSFUL : "ఆటోపే సెటప్ & చెల్లింపు విజయవంతమైంది!",
  AUTOPAY_SETUP_SUCCESSFUL : "ఆటోపే సెటప్ విజయవంతమైంది!",
  AUTOPAY_SETUP_AND_PAYMENT_PENDING : "ఆటోపే సెటప్ & చెల్లింపు పెండింగ్‌లో ఉంది!",
  AUTOPAY_SETUP_PENDING : "ఆటోపే సెటప్ పెండింగ్‌లో ఉంది!",
  AUTOPAY_SETUP_AND_PAYMENT_FAILED : "ఆటోపే సెటప్ & చెల్లింపు విఫలమైంది!",
  AUTOPAY_SETUP_FAILED : "ఆటోపే సెటప్ విఫలమైంది!",
  ONE_TIME_REGISTERATION : "వన్ టైమ్ రిజిస్ట్రేషన్",
  CLEARANCE_AND_REGISTERATION : "క్లియరెన్స్ + రిజిస్ట్రేషన్",
  UPI_AUTOPAY_SETUP : "UPI ఆటోపే సెటప్",
  WATCH_VIDEO_FOR_HELP : "సహాయం కోసం వీడియో చూడండి",
  PAYMENT_PENDING_SOFT_NUDGE : "బకాయిల పరిమితి త్వరలో చేరుకుంటుంది. నాన్‌స్టాప్ రైడ్‌లను ఆస్వాదించడానికి బకాయిలను క్లియర్ చేయండి",
  CLEAR_YOUR_DUES_EARLY : "మీ బకాయిలను ముందుగానే క్లియర్ చేయండి",
  DUE_LIMIT_WARNING_BANNER_TITLE : "మీ బకాయి పరిమితి ₹{} త్వరలో చేరుకుంటుంది",
  SCHEDULED_ON : "షెడ్యూల్ చేసిన తేదీ",
  ATTEMPTED_ON : "ప్రయత్నించిన తేదీ",
  FREE_TRIAL_ENDING_IN_2_DAYS :"ఉచిత ట్రయల్ 2 రోజుల్లో ముగుస్తుంది!",
  FREE_TRIAL_ENDING_TOMORROW : "ఉచిత ట్రయల్ రేపటితో ముగుస్తుంది!",
  FREE_TRIAL_ENDS_TONIGHT : "ఉచిత ట్రయల్ ఈ రాత్రికి ముగుస్తుంది!",
  JOIN_A_PLAN_TO_CONTINUE_TAKING_RIDES : "రైడ్‌లను కొనసాగించడానికి ప్లాన్‌లో చేరండి",
  SETUP_AUTOPAY_FOR_EASY_PAYMENTS : "సులభమైన చెల్లింపుల కోసం ఆటోపే సెటప్ చేయండి",
  LOW_DUES_CLEAR_POPUP_DESC : "నాన్‌స్టాప్ రైడ్‌లను ఆస్వాదించడానికి మీ బకాయిలను ఇప్పుడే క్లియర్ చేయండి.",
  DUES_PENDING : "⚠️ బకాయిలు పెండింగ్‌లో ఉన్నాయి! ⚠️",
  DAYS : "రోజులు",
  ACTIVE_PLAN : "ఆక్టివ్ ప్రణాళిక",
  DOWNGRADE_AVAILABLE_ONLY_FOR_AC_VEHICLES : "డౌన్‌గ్రేడ్ వెహికల్ ఆప్షన్ AC వాహనాలకు మాత్రమే అందుబాటులో ఉంది",
  DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_1 : "మీ వాహనాన్ని డౌన్‌గ్రేడ్ చేయడం వలన మీరు రెండింటినీ తీసుకోవచ్చు",
  DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_2 : "రైడ్స్ మరియు",
  DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_3 : "రైడ్స్",
  AC_CAB : "AC క్యాబ్",
  AC_SUV : "AC ఎస్యువీ",
  DOWNGRADE_VEHICLE : "వాహనాన్ని డౌన్‌గ్రేడ్ చేయండి",
  WHAT_ARE_PURPLE_RIDES : "పర్పుల్ రైడ్స్ అంటే ఏమిటి?",
  ECONOMICAL : "ఆర్థికపరమైన",
  SPACIOUS : "విశాలమైన",
  COMFY : "సౌకర్యవంతమైన",
  PEOPLE : "ప్రజలు",
  GO_TO : "గో-టు",
  SELECT_ON_MAP : "మ్యాప్‌లో ఎంచుకోండి",
  CONFIRM_LOCATION_STR : "లొకేషన్ని నిర్ధారించండి",
  SAVE_LOCATION_STR : "లొకేషన్ని సేవ్ చేయండి",
  REMOVE_PREF_LOC : "ప్రాధాన్య లొకేషన్ని తీసివేయండి",
  CONF_REMOVE_PREF_LOC : "మీరు ఖచ్చితంగా ప్రాధాన్య లొకేషన్ని తీసివేయాలనుకుంటున్నారా?",
  YES_REMOVE : "అవును, తొలగించు",
  ADD_LOCATION : "కొత్త గో-టు లొకేషన్ని జోడించండి",
  ADD_ANOTHER_LOCATION : "మరొక లొకేషన్ని జోడించండి",
  ADD_A_GOTO_LOC : "గో-టు లొకేషన్‌ను జోడించండి",
  GOTO_LOC_LEFT : "మిగిలి ఉన్న లొకేషన్ని లొకేషన్లు:",
  CURRENT_LOCATION : "ప్రస్తుత లొకేషన్",
  CONF_GOTO_LOC : "గో-టు లొకేషన్‌ను నిర్ధారించండి",
  GOTO_LOCS : "గో-టు లొకేషన్లు",
  LOCATION_STR : "లొకేషన్",
  ADD_TAG : "ట్యాగ్ జోడించండి",
  ONLY_ONE_LOC_CAN_ADDED : "(ఒక ప్రదేశం మాత్రమే ఈ ట్యాగ్‌ని కలిగి ఉండగలదు)",
  SAVE_AS : "ఇలాగ సేవ్ చేయండి",
  NO_GOTO_LOC_ADDED : "గో-టు లొకేషన్ ఇంకా జోడించబడలేదు",
  GOTO_LOC_HELPS_YOU : "గో-టు లొకేషన్ మీ ప్రాధాన్య లొకేషన్లలో మరియు చుట్టుపక్కల రైడ్‌లను కనుగొనడంలో మీకు సహాయపడుతుంది",
  YOU_ARE_VERY_CLOSE : "మీరు “గో-టు” లొకేషన్కి చాలా దగ్గరగా ఉన్నారు",
  GOTO_IS_APPLICABLE_FOR : "మీ ప్రస్తుత స్థానానికి కనీసం <b>3km</b> దూరంలో ఉన్న స్థానాలకు \"గో-టు\" వర్తిస్తుంది.",
  CANCEL_ANYWAY : "ఏమైనప్పటికీ రద్దు చేయి",
  GOTO_MAYBE_REDUCED : "గో-టు తగ్గవచ్చు",
  CANCEL_OF_GOTO : "గో-టు రైడ్‌ని రద్దు చేస్తే మీ కోసం గో-టు ఎంపికలు తగ్గుతాయి!",
  MORE_GOTO_RIDE_COMING : "మరిన్ని గో-టు రైడ్‌లు వస్తున్నాయి!",
  MORE_GOTO_RIDE_COMING_DESC : "దయచేసి ఆన్‌లైన్‌లో ఉండండి; మేము మీ గో-టు స్థానం వైపు మరిన్ని రైడ్ అభ్యర్థనలను పొందుతున్నాము",
  GOTO_REDUCED_TO_ZERO : "గో-టు సున్నాకి తగ్గించబడింది",
  DUE_TO_MULTIPLE_CANCELLATIONS : "అనేక రద్దుల కారణంగా, కౌంట్ తగ్గించబడింది",
  OK_GOT_IT : "సరే అర్థమయ్యింది",
  GOTO_REDUCED_TO : "గో-టు తగ్గించబడింది",
  VALIDITY_EXPIRED : "చెల్లుబాటు గడువు ముగిసింది!",
  VALIDITY_EXPIRED_DESC : "మీ 30 నిమిషాల వ్యాలిడిటీ ముగిసింది. మేము ఈ సమయంలో మీ అభ్యర్థనను నెరవేర్చలేకపోయాము.",
  KNOW_MORE : "మరింత తెలుసుకోండి",
  THIS_FEATURE_WILL_BE_APPLICABLE : "మీరు మీ ప్రస్తుత స్థానానికి కనీసం 3 కి.మీ దూరంలో ఉన్నట్లయితే ఈ ఫీచర్ వర్తిస్తుంది.\n\nసక్రియం అయిన తర్వాత స్థాన ప్రాధాన్యతలు కేవలం 30 నిమిషాలు మాత్రమే చెల్లుబాటు అవుతాయి.",
  GOTO_LOC_ADDED : "గో-టు లొకేషన్ విజయవంతంగా జోడించబడింది",
  GOTO_LOC_REMOVED : "గో-టు లొకేషన్ విజయవంతంగా తీసివేయబడింది",
  GOTO_LOC_UPDATED : "గో-టు లొకేషన్ విజయవంతంగా నవీకరించబడింది",
  GOTO_LOC_IS_ENABLED : "గో-టు లొకేషన్ ప్రారంభించబడింది",
  GOTO_LOC_IS_DISABLED : "గో-టు లొకేషన్ నిలిపివేయబడింది",
  GOTO_LOCATIONS : "గో-టు లొకేషన్లు",
  CHOOSE_A_GOTO_LOC : "గో-టు లొకేషన్‌ను ఎంచుకోండి",
  YOU_HAVE_ONLY_LEFT_FOR_TODAY : "ఒకటే మిగిలి ఉంది",
  YES_ENABLE : "అవును, ప్రారంభించు",
  NO_GOTO_LOCS_ADDED_YET : "ఇంకా గో-టు లొకేషన్లు జోడించలేదు",
  NO_GOTO_LOCS_ADDED_YET_DESC : "గో-టు లొకేషన్ మీ ప్రాధాన్య స్థానాల్లో మరియు చుట్టుపక్కల రైడ్‌లను కనుగొనడంలో మీకు సహాయపడుతుంది",
  ENABLE_GOTO : "గో-టును ప్రారంభించు",
  GO_TO_CANCELLATION_TITLE : "గో-టు తగ్గవచ్చు",
  GO_TO_CANCELLATION_DESC : "గో-టు రైడ్‌ని రద్దు చేయడం వలన మీ కోసం గో-టు ఎంపికలు తగ్గుతాయి!",
  VALIDITY_EXPIRED_STR : "చెల్లుబాటు గడువు ముగిసింది!",
  DISABLE_GOTO_STR : "గో-టును నిలిపివేయాలా?",
  YOU_STILL_HAVE_TIME_LEFT : "మీ గో-టు అభ్యర్థనలో మీకు ఇంకా సమయం మిగిలి ఉంది",
  YES_DISABLE : "అవును, ఆపివేయి",
  GOTO_LOC_REACHED : "గో-టు లొకేషన్కి చేరుకున్నారు!",
  REPORT_ISSUE : "సమస్యను నివేదించండి",
  YOU_ARE_ALMOST_AT_LOCATION : "మీరు దాదాపు గో-టు లొకేషన్కి చేరుకున్నారు.",
  DRIVER_HOME_LOCATION_NOT_FOUND : "లొకేషన్ కనుగొనబడలేదు",
  DRIVER_HOME_LOCATION_DOES_NOT_EXIST : "లొకేషన్ లేదు",
  DRIVER_HOME_LOCATION_LIMIT_REACHED : "లొకేషన్ పరిమితి చేరుకుంది",
  DRIVER_GO_HOME_REQUEST_NOT_FOUND : "అభ్యర్థన కనుగొనబడలేదు",
  DRIVER_GO_HOME_REQUEST_DOES_NOT_EXIST : "అభ్యర్థన ఉనికిలో లేదు",
  DRIVER_GO_HOME_REQUEST_DAILY_USAGE_LIMIT_REACHED : "రోజువారీ వినియోగ పరిమితిని చేరుకుంది",
  DRIVER_GO_HOME_REQUEST_ALREADY_ACTIVE : "ఆల్రెడీ యాక్టివ్",
  DRIVER_HOME_LOCATION_OUTSIDE_SERVICE_AREA : "లొకేషన్ సేవా ప్రాంతం వెలుపల ఉంది",
  NEW_LOCATION_TOO_CLOSE_TO_PREVIOUS_HOME_LOCATION : "లొకేషన్ మునుపటి లొకేషన్కి చాలా దగ్గరగా ఉంది",
  DRIVER_HOME_LOCATION_DOES_NOT_BELONG_TO_DRIVER : "లొకేషన్ మీకు చెందినది కాదు",
  DRIVER_HOME_LOCATION_DELETE_WHILE_ACTIVE_ERROR : "యాక్టీవ్గా ఉన్నప్పుడు లొకేషన్ని తొలిగించలేము",
  DRAG_TO_ADJUST : "మీ స్థానాన్ని సర్దుబాటు చేయడానికి లాగండి",
  LOCATION_ALREADY_EXISTS : "స్థానం ఇప్పటికే ఇలా ఉంది",
  MIN_LEFT : "నిముషాలు మిగిలి ఉన్నాయి",
  GET_READY_FOR_YS_SUBSCRIPTION : "నమ్మ యాత్రి ప్రణాళికల కోసం సిద్ధంగా ఉండండి!",
  SIGNUP_EARLY_FOR_SPECIAL_OFFERS : "ప్రత్యేక ఆఫర్‌ల కోసం ముందుగానే సైన్ అప్ చేయండి",
  GUARANTEED_FIXED_PRICE : "ఏప్రిల్ 1, 2025 వరకు స్థిర ధరకు హామీ ఇవ్వబడుతుంది",
  INTRODUCTORY_OFFER_TO_BE_ANNOUNCED_SOON : "పరిచయ ఆఫర్ త్వరలో ప్రకటించబడుతుంది!",
  NO_CHARGES_TILL : "మార్చ్ 31, 2024 వరకు ఛార్జీలు లేవు",
  DIRECT_PAYMENT_NO_COMMISSIONS : "ప్రత్యక్ష చెల్లింపు.\nకమీషన్లు లేవు",
  CUSTOMER_PAYS_DIRECTLY : "కస్టమర్ మీకు నేరుగా \nనగదు లేదా UPI ద్వారా చెల్లిస్తారు",
  HUNDRED_PERCENT_FARE_GOES_TO_YOU : "100% ఛార్జీలు\nమీకే చెందుతాయి!",
  FARE_SHOWN_IS_FARE_YOU_GET : "చూపిన ఛార్జీ మీరు పొందే ఛార్జీ.\nదాచిన ఛార్జీలు లేవు.",
  BE_A_PART_OF_OPEN_MOBILITY_REVOLUTION : "ఓపెన్\nమొబిలిటీ రివల్యూషన్‌లో భాగం అవ్వండి!",
  OUR_DATA_AND_PRODUCT_ARE_TRANSPARENT : "మా డేటా మరియు ఉత్పత్తి రోడ్‌మ్యాప్\nఅందరికీ పారదర్శకంగా ఉంటాయి.",
  YOUR_DETECTED_LOCATION_IS : "మీరు గుర్తించిన స్థానం",
  LANGUAGE_DETECTED : "భాష కనుగొనబడింది",
  CHANGE_LANGUAGE_STR : "భాష మార్చు",
  SELECT_LOCATION : "స్థానాన్ని ఎంచుకోండి",
  SELECT_LOCATION_DESC : "మీరు రైడ్ చేయాలనుకుంటున్న ప్రదేశాన్ని ఎంచుకోండి",
  SELECT_LANGUAGE_DESC : "మీరు చదవగలిగే భాషను ఎంచుకోండి",
  CONFIRM_LANGUAGE : "భాషను నిర్ధారించండి",
  GET_STARTED : "ప్రారంభించడానికి",
  ENABLE_LOCATION_PERMISSION : "స్థాన అనుమతిని ప్రారంభించండి",
  PLEASE_ENABLE_LOCATION_PERMISSION_FOR : "దయచేసి దీని కోసం స్థాన అనుమతిని ప్రారంభించండి ",
  ENABLE_LOCATION : "స్థానాన్ని ప్రారంభించండి",
  ENTER_YOUR_MOBILE_NUMBER: "మీ మొబైల్ నెంబర్ ను ఎంటర్ చేయండి",
  NOTIFICATION_ACCESS : "నోటిఫికేషన్ యాక్సెస్",
  NOTIFICATION_ACCESS_DESC : "సిఫార్సు చేయబడింది, మీరు సందేశాలను ఎప్పటికీ కోల్పోకుండా చూస్తారు",
  WATCH_VIDEO : "వీడియో చూడండి",
  DL_VERIFICATION_FAILED : "DL ధృవీకరణ విఫలమైంది. దయచేసి సమస్య తేదీని నమోదు చేసి, మళ్లీ ప్రయత్నించండి",
  RC_VERIFICATION_FAILED : "RC ధృవీకరణ విఫలమైంది. దయచేసి సమస్య తేదీని నమోదు చేసి, మళ్లీ ప్రయత్నించండి",
  DL_UPLOAD_FAILED : "DL అప్‌లోడ్ విఫలమైంది",
  RC_UPLOAD_FAILED : "RC అప్‌లోడ్ విఫలమైంది",
  PLEASE_RETRY_THE_UPLOAD_AGAIN : "దయచేసి అప్‌లోడ్ చేయడానికి మళ్లీ ప్రయత్నించండి.",
  RC_AND_DL_UPLOAD_FAILED : "RC మరియు DL అప్‌లోడ్ విఫలమైంది.",
  RC_UPLOAD_LIMIT_REACHED : "RC అప్‌లోడ్ పరిమితి మించిపోయింది",
  DL_UPLOAD_LIMIT_REACHED : "DL అప్‌లోడ్ పరిమితి మించిపోయింది.",
  RETRY_UPLOAD : "అప్‌లోడ్ చేయడానికి మళ్లీ ప్రయత్నించండి",
  VEHICLE_REGISTERATON_CERTIFICATE : "వాహనం రిజిస్ట్రేషన్ సర్టిఫికేట్",
  GRANT_PERMISSIONS : "అనుమతులు మంజూరు చేయండి",
  SUBSCRIPTION_PLAN_STR : "సబ్‌స్క్రిప్షన్ ప్లాన్",
  COMPLETE_AUTOPAY_LATER : "తర్వాత ‘మై ప్లాన్’ విభాగం నుండి ఆటోపేను పూర్తి చేయండి.",
  START_EARNING_IN_FOUR_STEPS : "{} సాధారణ దశల్లో సంపాదించడం ప్రారంభించండి",
  COMPLETE : "పూర్తి",
  HOW_TO_UPLOAD : "ఎలా అప్‌లోడ్ చేయాలి",
  TAKE_CLEAR_PICTURE_DL : "ఫ్లాట్ ఉపరితలంపై మీ డ్రైవింగ్ లైసెన్స్ ఫోటో వైపు స్పష్టమైన చిత్రాన్ని తీయండి.",
  ENSURE_ADEQUATE_LIGHT : "లైటింగ్ తగినంతగా ఉందని మరియు అన్ని వివరాలు స్పష్టంగా కనిపించేలా చూసుకోండి",
  FIT_DL_CORRECTLY : "క్రింద చూపిన విధంగా గుర్తించబడిన ప్రదేశంలో డ్రైవింగ్ లైసెన్స్‌ను సరిగ్గా అమర్చండి",
  TAKE_PHOTO : "ఫోటో తీసుకో",
  FIT_RC_CORRECTLY : "క్రింద చూపిన విధంగా గుర్తించబడిన ప్రదేశంలో నమోదు ధృవీకరణ పత్రాన్ని సరిగ్గా అమర్చండి",
  TAKE_CLEAR_PICTURE_RC : "ఫ్లాట్ ఉపరితలంపై మీ రిజిస్ట్రేషన్ సర్టిఫికేట్ యొక్క ఫోటో వైపు స్పష్టమైన చిత్రాన్ని తీయండి.",
  DL_UPLOADED : "డ్రైవింగ్ లైసెన్స్ అప్‌లోడ్",
  RC_UPLOADED : "రిజిస్ట్రేషన్ సర్టిఫికేట్ అప్‌లోడ్ చేయబడింది",
  DL_UPLOADING : "డ్రైవింగ్ లైసెన్స్ అప్‌లోడ్ చేస్తోంది",
  RC_UPLOADING : "రిజిస్ట్రేషన్ సర్టిఫికేట్ అప్‌లోడ్ చేస్తోంది",
  RETAKE_RC : "\nదయచేసి గుర్తుపెట్టిన ప్రదేశంలో RCతో ఫోటోను మళ్లీ తీయండి",
  RETAKE_DL : "\nదయచేసి గుర్తించబడిన ప్రదేశంలో DLతో ఫోటోను మళ్లీ తీయండి",
  CONFIRM_AND_UPLOAD : "నిర్ధారించి అప్‌లోడ్ చేయండి",
  RETAKE_PHOTO : "ఫోటోను మళ్లీ తీయండి",
  CHANGE_CITY : "నగరాన్ని మార్చండి",
  LETS_GET_YOUR_TRIP_READY : "మిమ్మల్ని యాత్రకు సిద్ధం చేద్దాం!",
  GOT_AN_OTP : "OTP వచ్చిందా?",
  DRIVING_LICENSE_DETAILS : "డ్రైవింగ్ లైసెన్స్ వివరాలు",
  VEHICLE_REGISTRATION_DETAILS : "వాహన రిజిస్ట్రేషన్ వివరాలు",
  UPLOAD_REGISTRATION_CERTIFICATE_STR : "రిజిస్ట్రేషన్ సర్టిఫికేట్‌ను అప్‌లోడ్ చేయండి",
  UPLOAD_PHOTO : "ఫోటోను అప్‌లోడ్ చేయండి",
  TAKE_A_PHOTO : "ఒక ఫోటో తీసుకుని", 
  GALLERY : "గ్యాలరీ",
  GET_FULL_PAYMENT : "కస్టమర్ల నుండి డైరెక్టుగా, పూర్తి చెల్లింపు పొందండి",
  SELECT_CITY : "నగరాన్ని ఎంచుకోండి",
}
  
  
export function getStringValue(key) {
  if (key in teluguStrings) {
    return teluguStrings[key];
  }
  console.error(key + " not found in teluguStrings");
  return "";
}
  