# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

flavors = ["nyUserProd"]

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "List Apps"
  lane :list_apps_metadata do
    flavors.each { |flavor|
      # gradle(
      #   task: 'clean assemble' + flavor + 'Release',
      #   properties: {
      #     'android.injected.signing.store.file' => 'xxx',
      #     'android.injected.signing.store.password' => 'xxx',
      #     'android.injected.signing.key.alias' => 'xxx',
      #     'android.injected.signing.key.password' => 'xxx'
      #   }
      # )
  
      # Generate AAB
      # gradle(
      #   task: 'bundle' + flavor + 'Release',
      #   properties: {
      #     'android.injected.signing.store.file' => 'xxx',
      #     'android.injected.signing.store.password' => 'xxx',
      #     'android.injected.signing.key.alias' => 'xxx',
      #     'android.injected.signing.key.password' => 'xxx'
      #   }
      # )
  
      # Supply metadata and AAB to Google Play
      supply(
        track: 'internal',
        json_key: 'xxx',
        package_name: 'in.juspay.nammayatri',
        metadata_path: 'fastlane/metadata/',
        aab: "./app/build/outputs/bundle/" + flavor + "Release/app-" + "nyUser-prod" + "-release.aab",
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_changelogs: true,
        skip_upload_screenshots: true,
        timeout: 600
      )
    }
  
    # Print app metadata
    # metadata = lane_context[SharedValues::APP_METADATA]
    # UI.message("App metadata: #{metadata}")
  end
end
