module Resources.Localizable.KN where

import Language.Types (STR(..))

getKN :: STR -> String
getKN stringKey =
    case stringKey of
        INACCURATE_DATE_AND_TIME -> "ತಪ್ಪಾದ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ!"
        ADJUST_YOUR_DEVICE_DATE_AND_TIME_AND_TRY_AGAIN -> "ನಿಮ್ಮ ಮೊಬೈಲ್ ದಿನಾಂಕ ಮತ್ತು ಸಮಯವನ್ನು ಹೊಂದಿಸಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        THE_CURRENT_DATE_AND_TIME_IS -> "ಪ್ರಸ್ತುತ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ"
        GO_TO_SETTING -> "ಸೆಟ್ಟಿಂಗ್‌ಗಳಿಗೆ ಹೋಗಿ"
        LETS_GET_STARTED -> "ಪ್ರಾರಂಭಿಸೋಣ"
        YOUR_APPLICATION_HAS_BEEN_SUBMITTED_SUCCESSFULLY_AND_IS_UNDER_VERIFICATION -> "ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ ಮತ್ತು ಪರಿಶೀಲನೆ ಹಂತದಲ್ಲಿದೆ"
        VIEW_STATUS -> "ಸ್ಥಿತಿಯನ್ನು ವೀಕ್ಷಿಸಿ"
        GO_HOME -> "ಮನೆಗೆ ಹೋಗು"
        SELECT_LANGUAGE -> "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        WHICH_LANGUAGE_DO_YOU_PREFER -> "ನೀವು ಯಾವ ಭಾಷೆಗೆ ಆದ್ಯತೆ ನೀಡುತ್ತೀರಿ?"
        NEXT -> "ಮುಂದೆ"
        T_C -> "ಬಳಕೆಯ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿ"
        ENTER_MOBILE_NUMBER -> "ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        BY_CLICKING_CONTINUE_YOU_WILL_BE_AGREEING_TO_OUR -> "ಮುಂದುವರಿಸು ಕ್ಲಿಕ್ ಮಾಡುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ ಸಮ್ಮತಿಸುತ್ತೀರಿ"
        ENTER_OTP -> "OTP ನಮೂದಿಸಿ"
        DIDNT_RECIEVE_OTP -> "OTP ಸ್ವೀಕರಿಸಲಿಲ್ಲವೇ? "
        RESEND_OTP -> "OTP ಅನ್ನು ಮರುಕಳುಹಿಸಿ"
        PLEASE_ENTER_VALID_OTP -> "ದಯವಿಟ್ಟು ಮಾನ್ಯ OTP ಅನ್ನು ನಮೂದಿಸಿ"
        INVALID_MOBILE_NUMBER -> "ಅಮಾನ್ಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ"
        REGISTER -> "ನೋಂದಣಿ"
        MOBILE_NUMBER -> "ಮೊಬೈಲ್ ನಂಬರ"
        AUTO_READING_OTP -> "ಸ್ವಯಂ ಓದುವಿಕೆ OTP..."
        UPLOAD_DRIVING_LICENSE -> "ಚಾಲನಾ ಪರವಾನಗಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ"
        UPLOAD_BACK_SIDE -> "ಬ್ಯಾಕ್ ಸೈಡ್ ಅನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ"
        UPLOAD_FRONT_SIDE -> "ನಿಮ್ಮ ಡಿಎಲ್‌ನ ಫೋಟೋ ಭಾಗವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ"
        BACK_SIDE -> "ಬ್ಯಾಕ್ ಸೈಡ್"
        FRONT_SIDE -> "ನಿಮ್ಮ DL ನ ಫೋಟೋ ಸೈಡ್"
        LICENSE_INSTRUCTION_PICTURE -> "ದಯವಿಟ್ಟು ಪರವಾನಗಿಯ ಎರಡೂ ಬದಿಗಳ ಸ್ಪಷ್ಟ ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ"
        LICENSE_INSTRUCTION_CLARITY -> "ಫೋಟೋ ಮತ್ತು ಎಲ್ಲಾ ವಿವರಗಳು ಸ್ಪಷ್ಟವಾಗಿ ಗೋಚರಿಸುತ್ತವೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ"
        REGISTRATION_STEPS -> "ನೋಂದಣಿ ಹಂತಗಳು"
        PROGRESS_SAVED -> "ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ಉಳಿಸಲಾಗಿದೆ, ಯಾವುದೇ ಮಾಹಿತಿಯನ್ನು ಬದಲಾಯಿಸಲು ನೀವು ಹಿಂದಿನ ಹಂತಗಳಿಗೆ ಹಿಂತಿರುಗಬಹುದು"
        DRIVING_LICENSE -> "ಚಾಲನಾ ಪರವಾನಿಗೆ"
        AADHAR_CARD -> "ಆಧಾರ್ ಕಾರ್ಡ್"
        BANK_DETAILS -> "ಬ್ಯಾಂಕ್ ವಿವರಗಳು"
        VEHICLE_DETAILS -> "ವಾಹನದ ವಿವರಗಳು"
        UPLOAD_FRONT_BACK -> "ಮುಂಭಾಗ ಮತ್ತು ಹಿಂಭಾಗವನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ"
        EARNINGS_WILL_BE_CREDITED -> "ನಿಮ್ಮ ಗಳಿಕೆಯು ಇಲ್ಲಿ ಕ್ರೆಡಿಟ್ ಆಗಿರುತ್ತದೆ"
        FILL_VEHICLE_DETAILS -> "ನಿಮ್ಮ ವಾಹನದ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ"
        FOLLOW_STEPS -> "ನೋಂದಾಯಿಸಲು ದಯವಿಟ್ಟು ಕೆಳಗಿನ ಹಂತಗಳನ್ನು ಅನುಸರಿಸಿ"
        REGISTRATION -> "ನೋಂದಣಿ"
        UPLOAD_ADHAAR_CARD -> "ಆಧಾರ್ ಕಾರ್ಡ್ ಅನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ"
        ADHAAR_INTRUCTION_PICTURE -> "ದಯವಿಟ್ಟು ಆಧಾರ್ ಕಾರ್ಡ್‌ನ ಎರಡೂ ಬದಿಗಳ ಸ್ಪಷ್ಟ ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ"
        ADD_VEHICLE_DETAILS -> "ವಾಹನದ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ"
        VEHICLE_REGISTRATION_NUMBER -> "ವಾಹನ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ ಸಂಖ್ಯೆ"
        RE_ENTER_VEHICLE_REGISTRATION_NUMBER -> "ವಾಹನ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ ಸಂಖ್ಯೆಯನ್ನು ಮರು-ನಮೂದಿಸಿ"
        ENTER_VEHICLE_NO -> "ವಾಹನದ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ."
        VEHICLE_TYPE -> "ವಾಹನದ ಪ್ರಕಾರ"
        VEHICLE_MODEL_NAME -> "ವಾಹನದ ಮಾದರಿ ಹೆಸರು"
        ENTER_MODEL_NAME -> "ಮಾದರಿ ಹೆಸರನ್ನು ನಮೂದಿಸಿ"
        VEHICLE_COLOUR -> "ವಾಹನದ ಬಣ್ಣ"
        ENTER_VEHICLE_COLOUR -> "ವಾಹನದ ಬಣ್ಣವನ್ನು ನಮೂದಿಸಿ"
        UPLOAD_REGISTRATION_CERTIFICATE -> "ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (RC)"
        UPLOAD_RC -> "ಆರ್ಸಿ ಅಪ್ಲೋಡ್ ಮಾಡಿ"
        PREVIEW -> "ಮುನ್ನೋಟ"
        CHOOSE_VEHICLE_TYPE -> "ವಾಹನದ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ"
        BENIFICIARY_NUMBER -> "ಫಲಾನುಭವಿ ಖಾತೆ ಸಂಖ್ಯೆ"
        RE_ENTER_BENIFICIARY_NUMBER -> "ಫಲಾನುಭವಿ ಖಾತೆ ಸಂಖ್ಯೆ ಮರು-ನಮೂದಿಸಿ."
        IFSC_CODE -> "IFSC ಕೋಡ್"
        SENDING_OTP -> "OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ"
        PLEASE_WAIT_WHILE_IN_PROGRESS -> "ಪ್ರಗತಿಯಲ್ಲಿರುವಾಗ ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ"
        YOUR_REQUEST_HAS_TIMEOUT_TRY_AGAIN -> "ನಿಮ್ಮ ವಿನಂತಿಯ ಅವಧಿ ಮೀರಿದೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        ERROR_OCCURED_PLEASE_TRY_AGAIN_LATER -> "ದೋಷ ಸಂಭವಿಸಿದೆ ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        ENTER_OTP_SENT_TO -> " ಗೆ ಕಳುಹಿಸಲಾದ ಒಟಿಪಿಯನ್ನು ನಮೂದಿಸಿ"
        OTP_SENT_TO -> " ಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ"
        COUNTRY_CODE_INDIA -> "+91"
        ENTER_ACCOUNT_NUMBER -> "ಖಾತೆ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ."
        ADD_BANK_DETAILS -> "ಬ್ಯಾಂಕ್ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ"
        ENTER_IFSC_CODE -> "IFSC ಕೋಡ್ ನಮೂದಿಸಿ"
        SUBMIT -> "ಸಲ್ಲಿಸು"
        PERSONAL_DETAILS -> "ವೈಯಕ್ತಿಕ ವಿವರಗಳು"
        LANGUAGES -> "ಭಾಷೆಗಳು"
        HELP_AND_FAQ -> "ಸಹಾಯ ಮತ್ತು FAQ ಗಳು"
        ABOUT -> "ಬಗ್ಗೆ"
        LOGOUT -> "ಲಾಗ್ ಔಟ್"
        UPDATE -> "ನವೀಕರಿಸಿ"
        EDIT -> "ತಿದ್ದು"
        AUTO -> "ಆಟೋ"
        NAME -> "ಹೆಸರು"
        PRIVACY_POLICY -> "ಗೌಪ್ಯತಾ ನೀತಿ"
        LOGO -> "ಲೋಗೋ"
        ABOUT_APP_DESCRIPTION -> "ಯಾತ್ರಿ ಪಾಲುದಾರರು ಪ್ರಯಾಣಿಕರೊಂದಿಗೆ ಚಾಲಕರನ್ನು ಸಂಪರ್ಕಿಸಲು ಮುಕ್ತ ವೇದಿಕೆಯಾಗಿದೆ. ಅಪ್ಲಿಕೇಶನ್ ಚಾಲಕರು ಪ್ರಯಾಣಿಕರನ್ನು ಹುಡುಕಲು ಅನುಕೂಲವಾಗುವಂತೆ ಮಾಡುತ್ತದೆ. ಮತ್ತು ಅವುಗಳನ್ನು ಸೇವಾ ಪೂರೈಕೆದಾರರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುವ ಮೂಲಕ ಈ ಆಯ್ಕೆಗಳನ್ನು ಪಡೆದುಕೊಳ್ಳಿ"
        TERMS_AND_CONDITIONS -> "ನಿಯಮ ಮತ್ತು ಶರತ್ತುಗಳು"
        UPDATE_VEHICLE_DETAILS -> "ವಾಹನದ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ"
        HELP_AND_SUPPORT -> "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ"
        NOTE -> "ಗಮನಿಸಿ:"
        VISIT_MY_RIDES_SCREEN_FOR_SPECIFIC_COMPLAINTS -> "ನಿರ್ದಿಷ್ಟ ದೂರುಗಳಿಗಾಗಿ ನನ್ನ ರೈಡ್ಸ್ ವಿಭಾಗಕ್ಕೆ ಭೇಟಿ ನೀಡಿ"
        THANK_YOU_FOR_WRTITTING_US -> "ನಮಗೆ ಬರೆದಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!"
        WE_HAVE_RECIEVED_YOUR_ISSUE -> "ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ನಾವು ಸ್ವೀಕರಿಸಿದ್ದೇವೆ. ನಾವು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ."
        GO_TO_HOME -> "ಮನೆಗೆ ಹೋಗು"
        YOUR_RECENT_RIDE -> "ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಸವಾರಿ"
        YOUR_RECENT_TRIP -> "Your Recent Trip"
        ALL_TOPICS -> "ಎಲ್ಲಾ ವಿಷಯಗಳು"
        REPORT_AN_ISSUE_WITH_THIS_TRIP -> "ಈ ಪ್ರವಾಸದಲ್ಲಿ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ"
        YOU_RATED -> "ನೀವು ರೇಟ್ ಮಾಡಿದ್ದೀರಿ"
        VIEW_ALL_RIDES -> "ಎಲ್ಲಾ ರೈಡ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ"
        WRITE_TO_US -> "ನಮಗೆ ಬರೆಯಿರಿ"
        SUBJECT -> "ವಿಷಯ"
        YOUR_EMAIL_ID -> "ನಿಮ್ಮ ಇಮೇಲ್ ಐಡಿ"
        DESCRIBE_YOUR_ISSUE -> "ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ"
        GETTING_STARTED_AND_FAQ -> "ಪ್ರಾರಂಭಿಸುವಿಕೆ ಮತ್ತು FAQ ಗಳು"
        FOR_OTHER_ISSUES_WRITE_TO_US -> "ಇತರ ಸಮಸ್ಯೆಗಳಿಗಾಗಿ, ನಮಗೆ ಬರೆಯಿರಿ"
        YOU_CAN_DESCRIBE_ISSUE_THAT_YOU_FACED_HERE -> "ನೀವು ಎದುರಿಸಿದ ಸಮಸ್ಯೆಯನ್ನು ಇಲ್ಲಿ ವಿವರಿಸಬಹುದು"
        REGISTRATION_CERTIFICATE_IMAGE -> "ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ (RC) ಚಿತ್ರ"
        HOME -> "ಮುಖಪುಟ"
        RIDES -> "ಸವಾರಿಗಳು"
        MY_RIDES -> "ನನ್ನ ಸವಾರಿಗಳು"
        PROFILE -> "ಪ್ರೊಫೈಲ್"
        ENTER_DRIVING_LICENSE_NUMBER -> "ಚಾಲನಾ ಪರವಾನಗಿ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        WHERE_IS_MY_LICENSE_NUMBER -> "ನನ್ನ ಪರವಾನಗಿ ಸಂಖ್ಯೆ ಎಲ್ಲಿದೆ?"
        TRIP_DETAILS -> "ಪ್ರವಾಸದ ವಿವರಗಳು"
        BY_CASH -> "ನಗದು ಮೂಲಕ"
        ONLINE_ -> "ಆನ್ಲೈನ್"
        GO_ONLINE_POPUP -> "<u>ಗೋ ಆನ್ಲೈನ್</u>"
        REPORT_AN_ISSUE -> "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ"
        DISTANCE -> "ದೂರ"
        TIME_TAKEN -> "ತೆಗೆದುಕೊಂಡ ಸಮಯ"
        CALL -> "ಕರೆ ಮಾಡಿ"
        START_RIDE -> "ರೈಡ್ ಪ್ರಾರಂಭಿಸಿ"
        CANCEL_RIDE -> "ರೈಡ್ ರದ್ದುಮಾಡಿ"
        END_RIDE -> "ಎಂಡ್ ರೈಡ್"
        RIDE_COMPLETED_WITH -> "ಗ್ರಾಹಕರೊಂದಿಗೆ ಸವಾರಿ ಪೂರ್ಣಗೊಂಡಿದೆ"
        COLLECT_AMOUNT_IN_CASH -> "ಮೊತ್ತವನ್ನು ನಗದು ರೂಪದಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ"
        CASH_COLLECTED -> "ನಗದು ಸಂಗ್ರಹಿಸಲಾಗಿದೆ"
        OFFLINE -> "ಆಫ್‌ಲೈನ್"
        ACCEPT_FOR -> "ಇದಕ್ಕಾಗಿ ಸ್ವೀಕರಿಸಿ:"
        DECLINE -> "ನಿರಾಕರಿಸು"
        REQUEST -> "ವಿನಂತಿ"
        YOU_ARE_OFFLINE -> "ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿರುವಿರಿ"
        YOU_ARE_CURRENTLY_BUSY_GO_ONLINE_TO_RECIEVE_TRIP_REQUESTS -> "ನೀವು ಪ್ರಸ್ತುತ ಕಾರ್ಯನಿರತರಾಗಿದ್ದೀರಿ. ಟ್ರಿಪ್ ವಿನಂತಿಗಳನ್ನು ಸ್ವೀಕರಿಸಲು ಆನ್‌ಲೈನ್‌ಗೆ ಹೋಗಿ"
        GOING_OFFLINE_WILL_NOT_GET_YOU_ANY_RIDE -> "ಆಫ್‌ಲೈನ್‌ಗೆ ಹೋಗುವುದರಿಂದ ನಿಮಗೆ ಯಾವುದೇ ಸವಾರಿ ಸಿಗುವುದಿಲ್ಲ"
        CANCEL -> "ರದ್ದುಮಾಡು"
        GO_OFFLINE -> "ಆಫ್‌ಲೈನ್‌ಗೆ ಹೋಗಿ"
        IS_WAITING_FOR_YOU -> "ಪಿಕಪ್‌ಗೆ ಹೋಗುತ್ತಿದ್ದೇನೆ"
        YOU_ARE_ON_A_RIDE -> "ಸವಾರಿ ಪ್ರಾರಂಭವಾಯಿತು..."
        PLEASE_ASK_RIDER_FOR_THE_OTP -> "ದಯವಿಟ್ಟು OTP ಗಾಗಿ ಸವಾರನನ್ನು ಕೇಳಿ"
        COMPLETED_ -> "ಪೂರ್ಣಗೊಂಡಿದೆ"
        CANCELLED_ -> "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ"
        WE_NEED_SOME_ACCESS -> "ನಮಗೆ ಸ್ವಲ್ಪ ಪ್ರವೇಶ ಬೇಕು!"
        ALLOW_ACCESS -> "ಪ್ರವೇಶವನ್ನು ಅನುಮತಿಸಿ"
        ENTER_RC_NUMBER -> "RC ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        WHERE_IS_MY_RC_NUMBER -> "ನನ್ನ RC ಸಂಖ್ಯೆ ಎಲ್ಲಿದೆ?"
        THANK_YOU_FOR_WRITING_TO_US -> "ನಮಗೆ ಬರೆದಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!"
        RIDER -> "ಸವಾರ"
        TRIP_ID -> "ಪ್ರವಾಸದ ಐಡಿ"
        NEED_IT_TO_SHOW_YOU_INCOMING_RIDE_REQUEST -> "ಅಪ್ಲಿಕೇಶನ್ ಮುಚ್ಚಿದಾಗ ಒಳಬರುವ ಸವಾರಿ ವಿನಂತಿಯನ್ನು ನಿಮಗೆ ತೋರಿಸಲು ಇದು ಅಗತ್ಯವಿದೆ"
        NEED_IT_TO_DISABLE_BATTERY_OPTIMIZATION_FOR_THE_APP -> "ಅಪ್ಲಿಕೇಶನ್ ಮುಚ್ಚಿದಾಗ ನಿಮ್ಮನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಇರಿಸಲು ಅಪ್ಲಿಕೇಶನ್‌ಗಾಗಿ ಬ್ಯಾಟರಿ ಆಪ್ಟಿಮೈಸೇಶನ್ ಅನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲು ಇದು ಅಗತ್ಯವಿದೆ"
        NEED_IT_TO_AUTOSTART_YOUR_APP -> "ಅಪ್ಲಿಕೇಶನ್ ಮುಚ್ಚಿದಾಗ ನಿಮ್ಮನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಇರಿಸಲು ನಿಮ್ಮ ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ಆಟೋಸ್ಟಾರ್ಟ್ ಅಗತ್ಯವಿದೆ"
        NEED_IT_TO_ENABLE_LOCATION -> "ಅಪ್ಲಿಕೇಶನ್ ಮುಚ್ಚಿದಾಗ ಅಥವಾ ಬಳಕೆಯಲ್ಲಿಲ್ಲದಿದ್ದರೂ ಸಹ ಚಾಲಕ ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳಲು ಸಕ್ರಿಯಗೊಳಿಸಲು ನಮ್ಮ ಯಾತ್ರಿ ಪಾಲುದಾರರು ಸ್ಥಳ ಡೇಟಾವನ್ನು ಸಂಗ್ರಹಿಸುತ್ತಾರೆ."
        OVERLAY_TO_DRAW_OVER_APPLICATIONS -> "ಅಪ್ಲಿಕೇಶನ್‌ಗಳನ್ನು ಸೆಳೆಯಲು ಒವರ್ಲೆ"
        BATTERY_OPTIMIZATIONS -> "ಬ್ಯಾಟರಿ ಆಪ್ಟಿಮೈಸೇಶನ್"
        AUTO_START_APPLICATION_IN_BACKGROUND -> "ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಆಟೋಸ್ಟಾರ್ಟ್ ಅಪ್ಲಿಕೇಶನ್"
        LOCATION_ACCESS -> "ಸ್ಥಳ ಪ್ರವೇಶ"
        STEP -> "ಹಂತ"
        PAID -> "ಪಾವತಿಸಲಾಗಿದೆ"
        PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL -> "ನೀವು ಏಕೆ ರದ್ದುಗೊಳಿಸಬೇಕೆಂದು ದಯವಿಟ್ಟು ನಮಗೆ ತಿಳಿಸಿ"
        MANDATORY -> "ಕಡ್ಡಾಯ"
        ENTERED_WRONG_OTP -> "ತಪ್ಪು ಒಟಿಪಿಗೆ ಪ್ರವೇಶಿಸಿದೆ"
        OTP_INVALID_FOR_THIS_VEHICLE_VARIANT ->  "ಅಮಾನ್ಯ OTP - ವಾಹನದ ಪ್ರಕಾರವು ರೈಡ್ ಪ್ರಕಾರದೊಂದಿಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ"
        COPIED -> "ನಕಲಿಸಿದ"
        BANK_NAME -> "ಬ್ಯಾಂಕ್ ಹೆಸರು"
        AADHAR_DETAILS -> "ಆಧಾರ್ ವಿವರಗಳು"
        AADHAR_NUMBER -> "ಆಧರ್ ಸಂಖ್ಯೆ"
        FRONT_SIDE_IMAGE -> "ಮುಂಭಾಗದ ಚಿತ್ರ"
        BACK_SIDE_IMAGE -> " ಬ್ಯಾಕ್ ಸೈಡ್ ಇಮೇಜ್"
        CALL_SUPPORT_CENTER -> "ಬೆಂಬಲ ಕೇಂದ್ರಕ್ಕೆ ಕರೆ ಮಾಡಿ"
        STILL_NOT_RESOLVED -> "ಇನ್ನೂ ಪರಿಹರಿಸಲಾಗಿಲ್ಲವೇ? ನಮಗೆ ಕರೆ ಮಾಡಿ"
        CASE_TWO -> "ಬಿ) ಬಹಿರಂಗಪಡಿಸದಿರುವ "
        NON_DISCLOUSER_AGREEMENT -> " ಒಪ್ಪಂದಕ್ಕೆ"
        DATA_COLLECTION_AUTHORITY -> "ಸಿ) ನಾನು ಈ ಮೂಲಕ ನನ್ನ ಮಾಹಿತಿಯನ್ನು ಸಂಗ್ರಹಿಸಲು Juspay ಗೆ ನೇಮಿಸುತ್ತೇನೆ ಮತ್ತು ಅಧಿಕಾರ ನೀಡುತ್ತೇನೆ ಮತ್ತು ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನಾನು ಬಳಕೆಯ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿಗೆ ಸಮ್ಮತಿಸುತ್ತೇನೆ"
        SOFTWARE_LICENSE -> "ಸಾಫ್ಟ್‌ವೇರ್ ಪರವಾನಗಿ"
        LOAD_MORE -> "ಇನ್ನಷ್ಟು ಲೋಡ್ ಮಾಡಿ"
        ARE_YOU_SURE_YOU_WANT_TO_LOGOUT -> "ನೀವು ಲಾಗ್‌ಔಟ್ ಮಾಡಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದು ಖಚಿತವೇ?"
        GO_BACK -> "ಹಿಂದೆ ಹೋಗು"
        ARE_YOU_SURE_YOU_WANT_TO_END_THE_RIDE -> "ನೀವು ರೈಡ್ ಅನ್ನು ಕೊನೆಗೊಳಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂದು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ"
        THANK_YOU_FOR_REGISTERING_US -> "ನಮ್ಮೊಂದಿಗೆ ನೋಂದಾಯಿಸಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!"
        UNFORTANUTELY_WE_ARE_NOT_AVAILABLE__YET_FOR_YOU -> "ದುರದೃಷ್ಟವಶಾತ್, ನಾವು ನಿಮಗಾಗಿ ಇನ್ನೂ ಲಭ್ಯವಿಲ್ಲ. ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ."
        EMPTY_RIDES -> "ಖಾಲಿ ಸವಾರಿಗಳು"
        YOU_HAVE_NOT_TAKEN_A_TRIP_YET -> "ನೀವು ಇನ್ನೂ ಪ್ರವಾಸ ಕೈಗೊಂಡಿಲ್ಲ"
        BOOK_NOW -> "ಈಗ ಪುಸ್ತಕ"
        RESEND_OTP_IN -> "OTP ಅನ್ನು ಮರುಕಳುಹಿಸಿ - "
        WE_NEED_ACCESS_TO_YOUR_LOCATION -> "ನಮಗೆ ನಿಮ್ಮ ಸ್ಥಳದ ಅನುಮತಿಯ ಅಗತ್ಯವಿದೆ"
        YOUR_LOCATION_HELPS_OUR_SYSTEM _ -> "ನಿಮ್ಮ ಸ್ಥಳದ ಅನುಮತಿಯು ಸಿಸ್ಟಂ ಅನ್ನು ಆಟೋಗಳ ಮೂಲಕ ಮ್ಯಾಪ್ ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ ಮತ್ತು ನಿಮಗೆ ಸಾಧ್ಯವಿರುವ ಸವಾರಿಯನ್ನು ಪಡೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ."
        NO_INTERNET_CONNECTION -> "ಯಾವುದೇ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ"
        PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN -> "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಹಾಗೂ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        TRY_AGAIN -> "ಮತ್ತೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ"
        GRANT_ACCESS -> "ಅನುಮತಿ ನೀಡಿ"
        YOUR_LIMIT_EXCEEDED_TRY_AGAIN_AFTER_10_MIN -> "ನೀವು ಮಿತಿಯನ್ನು ಮೀರಿದ್ದೀರಿ, 10 ನಿಮಿಷಗಳ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        ENTER_REFERRAL_MOBILE_NUMBER -> "ರೆಫರಲ್ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        APPLY -> "ಅನ್ವಯಿಸು"
        HAVE_A_REFERRAL -> "ಉಲ್ಲೇಖವಿದೆಯೇ?"
        ADD_HERE -> "ಇಲ್ಲಿ ಸೇರಿಸಿ"
        REFERRAL_APPLIED -> "ಉಲ್ಲೇಖವನ್ನು ಅನ್ವಯಿಸಲಾಗಿದೆ!"
        SMALLEDIT -> "ತಿದ್ದು"
        ADD_DRIVING_LICENSE -> "ಡಿಎಲ್ ಸೇರಿಸಿ"
        HELP -> "ಸಹಾಯ?"
        INVALID_DL_NUMBER -> "ಅಮಾನ್ಯ ಡಿಎಲ್ ಸಂಖ್ಯೆ"
        DRIVING_LICENSE_NUMBER -> "ಡಿಎಲ್ ಸಂಖ್ಯೆ"
        RE_ENTER_DRIVING_LICENSE_NUMBER -> "ಮತ್ತೆ ಡಿಎಲ್ ಸಂಖ್ಯೆ"
        ENTER_DL_NUMBER -> "ಡಿಎಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        SELECT_DATE_OF_BIRTH -> "ಹುಟ್ಟಿದ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        DATE_OF_BIRTH -> "ಹುಟ್ಟಿದ ದಿನಾಂಕ"
        WATCH_A_TUTORIAL_FOR_EASY_REGISTRATION -> "ಸುಲಭ ನೋಂದಣಿಗಾಗಿ ಟ್ಯುಟೋರಿಯಲ್ ವೀಕ್ಷಿಸಿ"
        ENTER_MINIMUM_FIFTEEN_CHARACTERS -> "ಕನಿಷ್ಠ 15 ಅಕ್ಷರಗಳನ್ನು ನಮೂದಿಸಿ"
        ADD_YOUR_FRIEND -> "ನಿಮ್ಮ ಸ್ನೇಹಿತನನ್ನು ಸೇರಿಸಿ"
        PLEASE_WAIT_WHILE_VALIDATING_THE_IMAGE -> "ಚಿತ್ರವನ್ನು ಮೌಲ್ಯೀಕರಿಸುವಾಗ ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ"
        VALIDATING -> "ಮೌಲ್ಯೀಕರಿಸುವುದು"
        VERIFICATION_PENDING -> "ಪರಿಶೀಲನೆ ಬಾಕಿಯಿದೆ"
        VERIFICATION_FAILED -> "ಪರಿಶೀಲನೆ ವಿಫಲವಾಗಿದೆ"
        NO_DOC_AVAILABLE -> "ಯಾವುದೇ ದಾಖಲೆ ಲಭ್ಯವಿಲ್ಲ"
        ISSUE_WITH_DL_IMAGE -> "ನಿಮ್ಮ DL ಚಿತ್ರದಲ್ಲಿ ಕೆಲವು ಸಮಸ್ಯೆ ಇರುವಂತಿದೆ, ನಮ್ಮ ಬೆಂಬಲ ತಂಡವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ."
        STILL_HAVE_SOME_DOUBT -> "ಇನ್ನೂ ಸ್ವಲ್ಪ ಅನುಮಾನವಿದೆಯೇ?"
        ISSUE_WITH_RC_IMAGE -> "ನಿಮ್ಮ RC ಚಿತ್ರದಲ್ಲಿ ಕೆಲವು ಸಮಸ್ಯೆ ಇರುವಂತಿದೆ, ನಮ್ಮ ಬೆಂಬಲ ತಂಡವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ."
        PLEASE_CHECK_FOR_IMAGE_IF_VALID_DOCUMENT_IMAGE_OR_NOT -> "ದಯವಿಟ್ಟು ಚಿತ್ರವು ಮಾನ್ಯವಾದ ಡಾಕ್ಯುಮೆಂಟ್ ಚಿತ್ರವೇ ಅಥವಾ ಇಲ್ಲವೇ ಎಂಬುದನ್ನು ಪರಿಶೀಲಿಸಿ"
        OOPS_YOUR_APPLICATION_HAS_BEEN_REJECTED -> "ಓಹ್! ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ತಿರಸ್ಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಪುನಃ ಪ್ರಯತ್ನಿಸಿ"
        INVALID_DRIVING_LICENSE -> "ಅಮಾನ್ಯ DL"
        LIMIT_EXCEEDED_FOR_DL_UPLOAD -> "DL ಅಪ್‌ಲೋಡ್‌ಗೆ ಮಿತಿ ಮೀರಿದೆ"
        INVALID_VEHICLE_REGISTRATION_CERTIFICATE -> "ಅಮಾನ್ಯವಾದ ವಾಹನ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ"
        LIMIT_EXCEEDED_FOR_RC_UPLOAD -> "ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ ಅಪ್‌ಲೋಡ್‌ಗೆ ಮಿತಿ ಮೀರಿದೆ"
        YOUR_DOCUMENTS_ARE_APPROVED -> "ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಅನುಮೋದಿಸಲಾಗಿದೆ. ಬೆಂಬಲ ತಂಡವು ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಶೀಘ್ರದಲ್ಲೇ ಸಕ್ರಿಯಗೊಳಿಸುತ್ತದೆ. ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲು ನೀವು ಬೆಂಬಲ ತಂಡಕ್ಕೆ ಕರೆ ಮಾಡಬಹುದು"
        APPLICATION_STATUS -> "ಅಪ್ಲಿಕೇಶನ್ ಸ್ಥಿತಿ"
        FOR_SUPPORT -> "ಬೆಂಬಲಕ್ಕಾಗಿ"
        CONTACT_US -> " ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ"
        IMAGE_VALIDATION_FAILED -> "ಚಿತ್ರದ ಮೌಲ್ಯಿಕರಣ ವಿಫಲವಾಗಿದೆ"
        IMAGE_NOT_READABLE -> "ಚಿತ್ರವನ್ನು ಓದಲು ಆಗುತ್ತಿಲ್ಲ"
        IMAGE_LOW_QUALITY -> "ಚಿತ್ರದ ಗುಣಮಟ್ಟ ಕಡಿಮೆ ಇದೆ"
        IMAGE_INVALID_TYPE -> "ಚಿತ್ರದ ಪ್ರಕಾರ ಅಮಾನ್ಯವಾಗಿದೆ"
        IMAGE_DOCUMENT_NUMBER_MISMATCH -> "ಚಿತ್ರದ ದಾಖಲೆ ಸಂಖ್ಯೆ ಹಾಗು ನಮೂದಿಸಿದ ದಾಖಲೆ ಸಂಖ್ಯೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ"
        IMAGE_EXTRACTION_FAILED -> "ಚಿತ್ರದ ಸಾರಾಂಶ ಓದಲು ವಿಫಲವಾಗಿದೆ"
        IMAGE_NOT_FOUND -> "ಚಿತ್ರ ಸಿಗಲಿಲ್ಲ"
        IMAGE_NOT_VALID -> "ಅಮಾನ್ಯ ಚಿತ್ರ"
        DRIVER_ALREADY_LINKED -> "ಚಾಲಕನನ್ನು ಈಗಾಗಲೇ ಲಿಂಕ್ ಮಾಡಲಾಗಿದೆ"
        DL_ALREADY_UPDATED -> "ಯಾವುದೇ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳುವ ಅವಶ್ಯಕತೆ ಇಲ್ಲ. ಲೈಸೆನ್ಸ್ ಈಗಾಗಲೇ ಲಿಂಕ್ ಆಗಿದೆ"
        RC_ALREADY_LINKED -> "ಈ RC ಈಗಾಗಲೇ ಬೇರೆ ಚಾಲಕನಿಗೆ ಲಿಂಕ್ ಆಗಿದೆ"
        RC_ALREADY_UPDATED -> "ಯಾವುದೇ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳುವ ಅವಶ್ಯಕತೆ ಇಲ್ಲ. RC ಈಗಾಗಲೇ ಲಿಂಕ್ ಆಗಿದೆ."
        DL_ALREADY_LINKED -> "ಈ DL ಈಗಾಗಲೇ ಬೇರೆ ಚಾಲಕನಿಗೆ ಲಿಂಕ್ ಆಗಿದೆ"
        SOMETHING_WENT_WRONG -> "ಏನೋ ತಪ್ಪಾಗಿದೆ"
        PICKUP -> "ಪಿಕಪ್"
        TRIP -> "ಪ್ರವಾಸ"
        CURRENTLY_WE_ALLOW_ONLY_KARNATAKA_REGISTERED_NUMBER _ -> "ಪ್ರಸ್ತುತ, ನಾವು ಕರ್ನಾಟಕ ನೋಂದಾಯಿತ ಸಂಖ್ಯೆಯನ್ನು ಮಾತ್ರ ಅನುಮತಿಸುತ್ತೇವೆ"
        UPDATED_AT -> "ಕೊನೆಯ ಸ್ಥಳ ನವೀಕರಣ"
        DATE_OF_REGISTRATION -> "ನೋಂದಣಿ ದಿನಾಂಕ"
        DATE_OF_ISSUE -> "ವಿತರಣೆಯ ದಿನಾಂಕ"
        SELECT_DATE_OF_ISSUE -> "ವಿತರಣೆಯ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        PROVIDE_DATE_OF_ISSUE_TEXT -> "ಕ್ಷಮಿಸಿ ನಿಮ್ಮ ವಿವರವನ್ನು ಮೌಲ್ಯೀಕರಿಸಲು ನಮಗೆ ಸಾಧ್ಯವಾಗಲಿಲ್ಲ, ದಯವಿಟ್ಟು ನಿಮ್ಮ DL ವಿವರವನ್ನು ಮೌಲ್ಯೀಕರಿಸಲು<b> ವಿತರಣೆಯ ದಿನಾಂಕ</b>ವನ್ನು ಒದಗಿಸಿ"
        PROVIDE_DATE_OF_REGISTRATION_TEXT -> "ಕ್ಷಮಿಸಿ ನಿಮ್ಮ ವಿವರವನ್ನು ಮೌಲ್ಯೀಕರಿಸಲು ನಮಗೆ ಸಾಧ್ಯವಾಗಲಿಲ್ಲ, ದಯವಿಟ್ಟು ನಿಮ್ಮ RC ವಿವರವನ್ನು ಮೌಲ್ಯೀಕರಿಸಲು<b> ನೋಂದಣಿ ದಿನಾಂಕ</b>ವನ್ನು ಒದಗಿಸಿ"
        SELECT_DATE_OF_REGISTRATION -> "ನೋಂದಣಿ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        TRIP_COUNT -> "ಇಂದಿನ ಪ್ರವಾಸಗಳು"
        TODAYS_EARNINGS -> "ಇಂದಿನ ಗಳಿಕೆ"
        BONUS_EARNED ->  "ಬೋನಸ್ ಗಳಿಸಲಾಗಿದೆ"
        GOT_IT ->  "ಅರ್ಥವಾಯಿತು!"
        WHAT_IS_NAMMA_YATRI_BONUS _ ->  "ಬೋನಸ್ ಎಂದರೇನು?"
        BONUS_PRIMARY_TEXT ->  "ನಮ್ಮ ಯಾತ್ರಿ ಬೋನಸ್ ಎಂದರೆ ನೀವು ಪಿಕಪ್ ಶುಲ್ಕಗಳು, ಗ್ರಾಹಕರ ಸಲಹೆಗಳು ಮತ್ತು ಚಾಲಕ ಸೇರ್ಪಡೆಗಳ ರೂಪದಲ್ಲಿ ಮೀಟರ್ ಶುಲ್ಕಕ್ಕಿಂತ ಹೆಚ್ಚಿನ ಮೊತ್ತವನ್ನು ಗಳಿಸಿದ್ದೀರಿ."
        BONUS_SECONDARY_TEXT ->  "ನಮ್ಮ ಯಾತ್ರಿ ಬೋನಸ್ ಮೊತ್ತವು ನಿಮ್ಮ ಒಟ್ಟು ಗಳಿಕೆಯ ಭಾಗವಾಗಿದೆ."
        SAME_REENTERED_RC_MESSAGE -> "ದಯವಿಟ್ಟು ಮರು-ನಮೂದಿಸಿದ ಆರ್‌ಸಿ ಸಂಖ್ಯೆಯು ಮೇಲೆ ಒದಗಿಸಿದ ಆರ್‌ಸಿ ಸಂಖ್ಯೆಯಂತೆಯೇ ಇದೆಯೇ ಎಂಬುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ"
        SAME_REENTERED_DL_MESSAGE -> "ಮರು-ನಮೂದಿಸಿದ DL ಸಂಖ್ಯೆಯು ಮೇಲೆ ಒದಗಿಸಲಾದ DL ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ"
        WHERE_IS_MY_ISSUE_DATE -> "ನನ್ನ ವಿತರಣೆಯ ದಿನಾಂಕ ಎಲ್ಲಿದೆ?"
        WHERE_IS_MY_REGISTRATION_DATE -> "ನೋಂದಣಿ ದಿನಾಂಕ ಎಲ್ಲಿದೆ?"
        EARNINGS_CREDITED_IN_ACCOUNT -> "ನಿಮ್ಮ ಗಳಿಕೆಯನ್ನು ಈ ಖಾತೆಯಲ್ಲಿ ಜಮಾ ಮಾಡಲಾಗುತ್ತದೆ"
        INVALID_PARAMETERS -> "ಅಮಾನ್ಯ ನಿಯತಾಂಕಗಳು"
        UNAUTHORIZED -> "ಅನಧಿಕೃತ"
        INVALID_TOKEN -> "ಅಮಾನ್ಯ ಟೋಕನ್"
        SOME_ERROR_OCCURED_IN_OFFERRIDE -> "ಆಫರ್ ರೈಡ್ ನಲ್ಲಿ ಕೆಲವು ದೋಷ ಸಂಭವಿಸಿದೆ"
        SELECT_VEHICLE_TYPE -> "ವಾಹನದ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        RIDE -> "ಸವಾರಿ"
        NO_LOCATION_UPDATE -> "ಸ್ಥಳ ನವೀಕರಣವಿಲ್ಲ"
        GOT_IT_TELL_US_MORE -> "ಅರ್ಥವಾಯಿತು, ನಮಗೆ ಇನ್ನಷ್ಟು ಹೇಳಿ?"
        WRITE_A_COMMENT -> "ಅನಿಸಿಕೆಯನ್ನು ಬರೆಯಿರಿ"
        HOW_WAS_YOUR_RIDE_WITH -> "ಜೊತೆಗಿನ ನಿಮ್ಮ ಪ್ರಯಾಣ ಹೇಗಿತ್ತು?"
        RUDE_BEHAVIOUR -> "ಒರಟು ನಡವಳಿಕೆ"
        LONG_WAITING_TIME -> "ಹೆಚ್ಚು ಕಾಯುವ ಸಮಯ"
        DIDNT_COME_TO_PICUP_LOCATION -> "ಪಿಕಪ್ ಸ್ಥಳಕ್ಕೆ ಬಂದಿರಲಿಲ್ಲ"
        HELP_US_WITH_YOUR_REASON -> "ನಿಮ್ಮ ಕಾರಣದೊಂದಿಗೆ ನಮಗೆ ಸಹಾಯ ಮಾಡಿ"
        MAX_CHAR_LIMIT_REACHED -> "ಗರಿಷ್ಠ ಅಕ್ಷರ ಮಿತಿಯನ್ನು ತಲುಪಿದೆ,"
        SHOW_ALL_OPTIONS -> "ಎಲ್ಲಾ ಆಯ್ಕೆಗಳನ್ನು ತೋರಿಸಿ"
        UPDATE_REQUIRED -> "ಅಪ್ಡೇಟ್ ಅಗತ್ಯವಿದೆ"
        PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE -> "ಸೇವೆಯನ್ನು ಮುಂದುವರಿಸಲು ದಯವಿಟ್ಟು ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ನವೀಕರಿಸಿ"
        NOT_NOW -> "ಈಗಲ್ಲ"
        OF -> "ರಲ್ಲಿ"
        DROP -> "ಡ್ರಾಪ್"
        PLEASE_WAIT -> "ದಯಮಾಡಿ ನಿರೀಕ್ಷಿಸಿ"
        SETTING_YOU_OFFLINE -> "ನಾವು ನಿಮ್ಮ ಆಫ್‌ಲೈನ್ ಅನ್ನು ಹೊಂದಿಸುತ್ತಿದ್ದೇವೆ"
        SETTING_YOU_ONLINE -> "ನಾವು ನಿಮ್ಮನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಹೊಂದಿಸುತ್ತಿದ್ದೇವೆ"
        SETTING_YOU_SILENT -> "ನಾವು ನಿಮ್ಮನ್ನು ಸೈಲೆಂಟ್  ಹೊಂದಿಸುತ್ತಿದ್ದೇವೆ"
        VIEW_BREAKDOWN -> "ವಿಭಜನೆಯನ್ನು ವೀಕ್ಷಿಸಿ"
        APP_INFO -> "ಅಪ್ಲಿಕೇಶನ್ ಮಾಹಿತಿ"
        OTHER -> "ಬೇರೆ"
        VEHICLE_ISSUE -> "ವಾಹನ ಸಮಸ್ಯೆ"
        FARE_UPDATED -> "ದರವನ್ನು ನವೀಕರಿಸಲಾಗಿದೆ"
        FREQUENT_CANCELLATIONS_WILL_LEAD_TO_LESS_RIDES -> "ಪದೇ ಪದೇ ರದ್ದುಗೊಳಿಸುವುದರಿಂದ ಕಡಿಮೆ ರೈಡ್‌ಗಳು ಮತ್ತು ಕಡಿಮೆ ರೇಟಿಂಗ್‌ಗೆ ಕಾರಣವಾಗುತ್ತದೆ"
        CONTINUE -> "ಮುಂದುವರಿಸಿ"
        CONFIRM_PASSWORD -> "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ"
        DEMO_MODE -> "ಡೆಮೊ ಮೋಡ್"
        PASSWORD -> "ಪಾಸ್ವರ್ಡ್"
        ENTER_DEMO_MODE_PASSWORD -> "ಡೆಮೊ ಮೋಡ್ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ"
        DEMO_MODE_DISABLED -> "ಡೆಮೊ ಮೋಡ್ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ"
        ONLINE_VIA_DEMO_MODE -> "ಆನ್‌ಲೈನ್ (ಡೆಮೊ)"
        MORE -> "more"
        LESS -> "less"
        YOU_ARE_AT_PICKUP -> "ನೀವು ಪಿಕಪ್ ಸ್ಥಳದಲ್ಲಿದ್ದೀರಿ"
        WAITING_FOR_CUSTOMER -> "ನೀವು ಗ್ರಾಹಕರಿಗಾಗಿ ಕಾಯುತ್ತಿದ್ದೀರಿ :"
        CUSTOMER_NOTIFIED -> "ಗ್ರಾಹಕರು ಸೂಚಿಸಿದ್ದಾರೆ"
        I_ARRIVED -> "ನಾನು ಆಗಮಿಸಿದ್ದೇನೆ"
        ESTIMATED_RIDE_FARE -> "ಅಂದಾಜು ರೈಡ್ ದರ: "
        PICKUP_TOO_FAR -> "ಪಿಕಪ್ ತುಂಬಾ ದೂರದಲ್ಲಿದೆ"
        CUSTOMER_NOT_PICKING_CALL -> "ಗ್ರಾಹಕರು ಕರೆಯನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತಿಲ್ಲ"
        TRAFFIC_JAM -> "ಟ್ರಾಫಿಕ್ ಜಾಮ್"
        CUSTOMER_WAS_RUDE -> "ಗ್ರಾಹಕರು ಅಸಭ್ಯವಾಗಿ ವರ್ತಿಸಿದರು"
        ALL_MESSAGES -> "ಎಲ್ಲಾ ಸಂದೇಶಗಳು"
        MESSAGES -> "ಸಂದೇಶಗಳು"
        ADD_A_COMMENT -> "ಕಾಮೆಂಟ್ ಸೇರಿಸಿ"
        POST_COMMENT -> "ಕಾಮೆಂಟ್ ಪೋಸ್ಟ್ ಮಾಡಿ"
        ENTER_YOUR_COMMENT -> "ನಿಮ್ಮ ಕಾಮೆಂಟ್ ಅನ್ನು ನಮೂದಿಸಿ"
        NO_NOTIFICATIONS_RIGHT_NOW -> "ಇದೀಗ ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ!"
        NO_NOTIFICATIONS_RIGHT_NOW_DESC -> "ಹೊಸ ಅಧಿಸೂಚನೆಗಳು ಬಂದಾಗ ನಾವು ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ"
        ALERTS -> "ಘೋಷಣೆಗಳು"
        YOUR_COMMENT -> "ನಿಮ್ಮ ಅನಿಸಿಕೆ"
        SHOW_MORE -> "ಇನ್ನು ಹೆಚ್ಚು ತೋರಿಸು"
        LOAD_OLDER_ALERTS -> "ಇನ್ನಷ್ಟು ಲೋಡ್ ಮಾಡಿ"
        CONTEST -> "ಸ್ಪರ್ಧೆ"
        YOUR_REFERRAL_CODE_IS_LINKED -> "ನಿಮ್ಮ ರೆಫರಲ್ ಕೋಡ್ ಲಿಂಕ್ ಆಗಿದೆ!"
        YOU_CAN_NOW_EARN_REWARDS -> "ಗ್ರಾಹಕರನ್ನು ಉಲ್ಲೇಖಿಸುವುದಕ್ಕಾಗಿ ನೀವು ಈಗ ಬಹುಮಾನಗಳನ್ನು ಗಳಿಸಬಹುದು!"
        COMING_SOON -> "ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!"
        COMING_SOON_DESCRIPTION -> "ನಿಮ್ಮನ್ನು ರೆಫರಲ್ ಪ್ರೋಗ್ರಾಂಗೆ ಸೇರಿಸಲು ನಾವು ಕೆಲಸ ಮಾಡುತ್ತಿದ್ದೇವೆ. ಹೆಚ್ಚಿನ ಮಾಹಿತಿಗಾಗಿ ಘೋಷಣೆಗಳು ಪುಟವನ್ನು ಪರಿಶೀಲಿಸಿ."
        REFERRAL_CODE_HINT -> "6-ಅಂಕಿಯ ರೆಫರಲ್ ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ"
        CONFIRM_REFERRAL_CODE -> "ರೆಫರಲ್ ಕೋಡ್ ಅನ್ನು ದೃಢೀಕರಿಸಿ"
        CONFIRM_REFERRAL_CODE_HINT -> "ರೆಫರಲ್ ಕೋಡ್ ಅನ್ನು ಮರು-ನಮೂದಿಸಿ"
        YOUR_REFERRAL_CODE -> "ನಿಮ್ಮ ರೆಫರಲ್ ಕೋಡ್"
        FIRST_REFERRAL_SUCCESSFUL -> "ಮೊದಲ ರೆಫರಲ್ ಯಶಸ್ವಿಯಾಗಿದೆ!\nರಿವಾರ್ಡ್ ಅನ್‌ಲಾಕ್ ಮಾಡಲಾಗಿದೆ!"
        AWAITING_REFERRAL_RIDE -> "ರೆಫರಲ್ ರೈಡ್‌ಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ"
        CHECK_THIS_SPACE_WHEN_YOU_GET_REFERRAL_ALERT -> "ನೀವು ರೆಫರಲ್ ಘೋಷಣೆಗಳು ಪಡೆದಾಗ \nಈ ಜಾಗವನ್ನು ಪರಿಶೀಲಿಸಿ"
        REFERRED_CUSTOMERS -> "ಉಲ್ಲೇಖಿಸಿದ ಗ್ರಾಹಕರು"
        ACTIVATED_CUSTOMERS -> "ಸಕ್ರಿಯ ಗ್ರಾಹಕರು"
        REFERRAL_CODE_LINKING -> "ರೆಫರಲ್ ಕೋಡ್ ಲಿಂಕ್ ಮಾಡುವುದು"
        CONTACT_SUPPORT -> "ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ"
        CALL_SUPPORT -> "ಬೆಂಬಲಕ್ಕೆ ಕರೆ ಮಾಡಿ"
        YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT _ -> "ನೀವು ನಮ್ಮ ಯಾತ್ರಿ ಬೆಂಬಲ ತಂಡಕ್ಕೆ ಕರೆ ಮಾಡಲಿರುವಿರಿ. ನೀವು ಮುಂದುವರೆಯಲು ಬಯಸುವಿರಾ?"
        REFERRAL_ENROLMENT -> "ರೆಫರಲ್ ದಾಖಲಾತಿ"
        REFERRALS -> "ಉಲ್ಲೇಖಗಳು"
        LINK_REFERRAL_CODE -> "ಲಿಂಕ್ ರೆಫರಲ್ ಕೋಡ್"
        DRIVER_DETAILS -> "ಚಾಲಕ ವಿವರಗಳು"
        FOR_UPDATES_SEE_ALERTS -> "ನವೀಕರಣಗಳಿಗಾಗಿ ಘೋಷಣೆಗಳನ್ನು ನೋಡಿ"
        SHARE_OPTIONS -> "ಆಯ್ಕೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ"
        ENTER_PASSWORD -> "ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ"
        RIDE_FARE ->  "ರೈಡ್ ದರ"
        RIDE_DISTANCE ->  "ಸವಾರಿ ದೂರ"
        START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS ->  "ಈ ತ್ವರಿತ ಚಾಟ್ ಸಲಹೆಗಳನ್ನು ಬಳಸಿಕೊಂಡು ನಿಮ್ಮ ಚಾಟ್ ಅನ್ನು ಪ್ರಾರಂಭಿಸಿ"
        MESSAGE ->  "ಸಂದೇಶ"
        START_YOUR_CHAT_WITH_THE_DRIVER ->  "ಚಾಲಕನೊಂದಿಗೆ ನಿಮ್ಮ ಚಾಟ್ ಅನ್ನು ಪ್ರಾರಂಭಿಸಿ"
        I_AM_ON_MY_WAY ->  "ನಾನು ಬರುತ್ತಿರುವೆ"
        GETTING_DELAYED_PLEASE_WAIT ->  "ತಡವಾಗುತ್ತಿದೆ, ನಿರೀಕ್ಷಿಸಿ"
        UNREACHABLE_PLEASE_CALL_BACK ->  "ನನಗೆ ಕರೆ ಮಾಡಿ"
        ARE_YOU_STARING ->  "ನೀವು ಪ್ರಾರಂಭಿಸುತ್ತಿದ್ದೀರಾ?"
        PLEASE_COME_SOON ->  "ದಯವಿಟ್ಟು ಬೇಗ ಬನ್ನಿ"
        OK_I_WILL_WAIT ->  "ಸರಿ, ನಾನು ಕಾಯುತ್ತೇನೆ"
        I_HAVE_ARRIVED ->  "ನಾನು ಆಗಮಿಸಿದೆ"
        PLEASE_COME_FAST_I_AM_WAITING ->  "ಬೇಗ ಬನ್ನಿ, ನಾನು ಕಾಯುತ್ತಿದ್ದೇನೆ"
        PLEASE_WAIT_I_WILL_BE_THERE ->  "ನಾನು ಬರುತ್ತಿದ್ದೇನೆ"
        LOOKING_FOR_YOU_AT_PICKUP ->  "ನಾನು ಪಿಕಪ್‌ನಲ್ಲಿದ್ದೇನೆ"
        SILENT ->  "ಸೈಲೆಂಟ್"
        TRY_SILENT_MODE ->  "ಸೈಲೆಂಟ್ ಮೋಡ್ ಅನ್ನು ಪ್ರಯತ್ನಿಸಿ?"
        SILENT_MODE_PROMPT ->  "ನೀವು ಅಡಚಣೆಯನ್ನು ಬಯಸದಿದ್ದರೆ, ಬದಲಿಗೆ ನೀವು ಸೈಲೆಂಟ್ ಮೋಡ್ ಅನ್ನು ಬಳಸಬಹುದು"
        GO_SILENT ->  "ಸೈಲೆಂಟ್ ಸಕ್ರಿಯಗೊಳಿಸಿ"
        GO_ONLINE ->  "ಗೋ!"
        GO_ONLINE_PROMPT ->  "ನೀವು ಪ್ರಸ್ತುತ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿರುವಿರಿ. \n ಸವಾರಿ ವಿನಂತಿಗಳನ್ನು ಪಡೆಯಲು, ಈಗಲೇ ಆನ್‌ಲೈನ್‌ಗೆ ಹೋಗಿ!"
        LIVE_DASHBOARD ->  "ಲೈವ್ ಸ್ಥಿತಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್"
        CLICK_TO_ACCESS_YOUR_ACCOUNT ->  "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ"
        ADD_ALTERNATE_NUMBER ->  "ಪರ್ಯಾಯ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ"
        ENTER_ALTERNATE_MOBILE_NUMBER ->  "ಪರ್ಯಾಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        PLEASE_ENTER_A_VALID_10_DIGIT_NUMBER ->  "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10-ಅಂಕಿಯ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        ALTERNATE_MOBILE_NUMBER ->  "ಪರ್ಯಾಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ"
        REMOVE ->  "ತೆಗೆದುಹಾಕಿ"
        REMOVE_ALTERNATE_NUMBER ->  "ಪರ್ಯಾಯ ಸಂಖ್ಯೆಯನ್ನು ತೆಗೆದುಹಾಕಿ"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_YOUR_ALTERNATE_MOBILE_NUMBER ->  "ನಿಮ್ಮ ಪರ್ಯಾಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ತೆಗೆದುಹಾಕಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?"
        YES_REMOVE_IT ->  "ಹೌದು, ಅದನ್ನು ತೆಗೆದುಹಾಕಿ"
        NUMBER_REMOVED_SUCCESSFULLY ->  "ಸಂಖ್ಯೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ತೆಗೆದುಹಾಕಲಾಗಿದೆ"
        EDIT_ALTERNATE_MOBILE_NUMBER ->  "ಪರ್ಯಾಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಸಂಪಾದಿಸಿ"
        NUMBER_ADDED_SUCCESSFULLY ->  "ಸಂಖ್ಯೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ"
        NUMBER_EDITED_SUCCESSFULLY ->  "ಸಂಖ್ಯೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ"
        ALTERNATE_MOBILE_OTP_LIMIT_EXCEED ->  "ಪರ್ಯಾಯ ಮೊಬೈಲ್ OTP ಮಿತಿ ಮೀರಿದೆ"
        WRONG_OTP ->  "ದಯವಿಟ್ಟು ಮಾನ್ಯ OTP ಅನ್ನು ನಮೂದಿಸಿ "
        ATTEMPTS_LEFT ->  " ಪ್ರಯತ್ನಗಳು ಉಳಿದಿವೆ"
        OTP_LIMIT_EXCEEDED ->  "OTP ಮಿತಿ ಮೀರಿದೆ"
        OTP_LIMIT_EXCEEDED_MESSAGE ->  "ನಿಮ್ಮ OTP ಮಿತಿಯನ್ನು ನೀವು ತಲುಪಿರುವಿರಿ. ದಯವಿಟ್ಟು 10 ನಿಮಿಷಗಳ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ."
        TRY_AGAIN_LATER ->  "ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        ATTEMPT_LEFT ->  " ಪ್ರಯತ್ನ ಉಳಿದಿದೆ"
        NUMBER_ALREADY_EXIST_ERROR ->  "ಮತ್ತೊಂದು ಖಾತೆಗೆ ಸಂಖ್ಯೆಯನ್ನು ಲಿಂಕ್ ಮಾಡಲಾಗಿದೆ! ದಯವಿಟ್ಟು ಇನ್ನೊಂದು ಸಂಖ್ಯೆಯನ್ನು ಬಳಸಿ"
        ADD_ALTERNATE_NUMBER_IN_MEANTIME ->  "ಈ ಪ್ರಕ್ರಿಯೆಯು ಪೂರ್ಣಗೊಳ್ಳಲು 2 ಕೆಲಸದ ದಿನಗಳವರೆಗೆ ತೆಗೆದುಕೊಳ್ಳಬಹುದು. ಈ ಮಧ್ಯೆ, ನೀವು \nಪರ್ಯಾಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಬಹುದು."
        VERIFICATION_IS_TAKING_A_BIT_LONGER ->  "ನಿಮ್ಮ ಪರಿಶೀಲನೆಯು \nನಿರೀಕ್ಷೆಗಿಂತ ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತಿರುವಂತೆ ತೋರುತ್ತಿದೆ.\nನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ನೀವು ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಬಹುದು."
        COMPLETE_ONBOARDING ->  "ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಅನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ"
        PERSON_WITH_THIS_NUMBER_ALREADY_EXISTS ->  "ಈ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಹೊಂದಿರುವ ವ್ಯಕ್ತಿ ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದ್ದಾರೆ."
        OTP_ ->  "OTP"
        MAPS -> "Maps"
        DEMO ->  "ಡೆಮೊ"
        PLEASE_ASK_THE_CUSTOMER_FOR_THE_OTP ->  "ದಯವಿಟ್ಟು OTP ಗಾಗಿ ಗ್ರಾಹಕರನ್ನು ಕೇಳಿ"
        DELETE ->  "ಅಳಿಸಿ"
        VIEW ->  "ನೋಟ"
        ISSUE_NO ->  "ಸಂಚಿಕೆ ಸಂಖ್ಯೆ"
        ADD_VOICE_NOTE ->  "ಧ್ವನಿ ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ"
        VOICE_NOTE_ADDED ->  "ಧ್ವನಿ ಟಿಪ್ಪಣಿ ಸೇರಿಸಲಾಗಿದೆ"
        ADDED_IMAGES ->  "ಚಿತ್ರಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ"
        NO_IMAGES_ADDED ->  "ಯಾವುದೇ ಚಿತ್ರಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ"
        ASK_DETAILS_MESSAGE ->  "ದಯವಿಟ್ಟು ಇನ್ನೂ ಕೆಲವು ವಿವರಗಳನ್ನು ನೀಡಿ. ಉತ್ತಮವಾಗಿ ವಿವರಿಸಲು ನೀವು ಚಿತ್ರಗಳನ್ನು ಅಥವಾ ಧ್ವನಿ ಟಿಪ್ಪಣಿಗಳನ್ನು ಸಹ ಕಳುಹಿಸಬಹುದು."
        ASK_DETAILS_MESSAGE_REVERSED ->  "ಕಳೆದುಹೋದ ವಸ್ತುವಿನ ಕುರಿತು ಹೆಚ್ಚಿನ ವಿವರಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ. ಉತ್ತಮವಾಗಿ ವಿವರಿಸಲು ನೀವು ಚಿತ್ರಗಳನ್ನು ಅಥವಾ ಧ್ವನಿ ಟಿಪ್ಪಣಿಗಳನ್ನು ಸಹ ಕಳುಹಿಸಬಹುದು."
        SELECT_OPTION ->  "ನೀವು ಇವುಗಳಲ್ಲಿ ಯಾವುದನ್ನಾದರೂ ಎದುರಿಸುತ್ತಿದ್ದರೆ ದಯವಿಟ್ಟು ನಮಗೆ ತಿಳಿಸಿ"
        SELECT_OPTION_REVERSED ->  "ಈ ಸಮಸ್ಯೆಯನ್ನು ಹೇಗೆ ಪರಿಹರಿಸಲು ನೀವು ಬಯಸುತ್ತೀರಿ?"
        ISSUE_SUBMITTED_MESSAGE ->  "ವಿವರಗಳನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿದೆ! ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಪರಿಹರಿಸಲು ನಮ್ಮ ತಂಡವು 24 ಗಂಟೆಗಳ ಒಳಗೆ ನಿಮಗೆ ಕರೆ ಮಾಡುತ್ತದೆ."
        SUBMIT_ISSUE_DETAILS ->  "ಸಂಚಿಕೆಯ ವಿವರಗಳನ್ನು ಸಲ್ಲಿಸಿ"
        IMAGE_PREVIEW ->  "ಚಿತ್ರ ಪೂರ್ವವೀಕ್ಷಣೆ"
        RIDE_REPORT_ISSUE ->  "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಲು ಸವಾರಿ ಆಯ್ಕೆಮಾಡಿ"
        I_DONT_KNOW_WHICH_RIDE ->  "ಯಾವ ಸವಾರಿ ಎಂದು ನನಗೆ ಗೊತ್ತಿಲ್ಲ"
        REPORT_ISSUE_CHAT_PLACEHOLDER _ ->  "ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ. ನಮ್ಮ ಯಾತ್ರಿ ಇದನ್ನು 24 ಗಂಟೆಗಳಲ್ಲಿ ಪರಿಹರಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತದೆ."
        ADDED_VOICE_NOTE ->  "ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ಸೇರಿಸಲಾಗಿದೆ"
        NO_VOICE_NOTE_ADDED ->  "ಯಾವುದೇ ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ"
        CALL_CUSTOMER_TITLE ->  "ಗ್ರಾಹಕರನ್ನು ಕರೆಯುವುದೇ"
        CALL_CUSTOMER_DESCRIPTION ->  "ನೀವು ಗ್ರಾಹಕರಿಗೆ ಕರೆ ಮಾಡಲಿರುವಿರಿ. ನೀವು ಮುಂದುವರೆಯಲು ಬಯಸುವಿರಾ?"
        PLACE_CALL ->  "ಕರೆ ಮಾಡಿ"
        ADD_IMAGE ->  "ಚಿತ್ರವನ್ನು ಸೇರಿಸಿ"
        ADD_ANOTHER ->  "ಮತ್ತೊಂದನ್ನು ಸೇರಿಸಿ"
        IMAGES_ADDED ->  "ಚಿತ್ರಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ"
        ISSUE_SUBMITTED_TEXT ->  "ಸ್ವಲ್ಪ ತಡಿ! ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಪರಿಹರಿಸುವಲ್ಲಿ ನಾವು ಕೆಲಸ ಮಾಡುತ್ತಿದ್ದೇವೆ"
        CHOOSE_AN_OPTION ->  "ಮುಂದುವರಿಸಲು ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ"
        IMAGE_ADDED ->  "ಚಿತ್ರವನ್ನು ಸೇರಿಸಲಾಗಿದೆ"
        DONE ->  "ಮಾಡಲಾಗಿದೆ"
        RECORD_VOICE_NOTE ->  "ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ"
        LOADING ->  "ಲೋಡ್ ಆಗುತ್ತಿದೆ"
        MAX_IMAGES ->  "ನೀವು ಕೇವಲ 3 ಚಿತ್ರಗಳನ್ನು ಮಾತ್ರ ಸೇರಿಸಬಹುದು"
        MORE_OPTIONS ->  "ಹೆಚ್ಚಿನ ಆಯ್ಕೆಗಳು"
        ONGOING_ISSUES ->  "ನಡೆಯುತ್ತಿರುವ ಸಮಸ್ಯೆಗಳು"
        RESOLVED_ISSUES ->  "ಪರಿಹರಿಸಿದ ಸಮಸ್ಯೆಗಳನ್ನು"
        RESOLVED_ISSUE ->  "ಪರಿಹರಿಸಿದ ಸಮಸ್ಯೆಗಳು"
        ONGOING_ISSUE ->  "ನಡೆಯುತ್ತಿರುವ ಸಮಸ್ಯೆಗಳು"
        LOST_ITEM ->  "ಕಳೆದುಹೋದ ಐಟಂ"
        RIDE_RELATED_ISSUE ->  "ಸವಾರಿ ಸಂಬಂಧಿತ ಸಮಸ್ಯೆ"
        APP_RELATED_ISSUE ->  "ಅಪ್ಲಿಕೇಶನ್ ಸಂಬಂಧಿತ ಸಮಸ್ಯೆ"
        FARE_RELATED_ISSUE ->  "ಶುಲ್ಕ ಸಂಬಂಧಿತ ಸಮಸ್ಯೆ"
        ISSUE_NUMBER ->  "ಸಂಚಿಕೆ ಸಂಖ್ಯೆ   "
        REMOVE_ISSUE ->  "ಸಮಸ್ಯೆಯನ್ನು ತೆಗೆದುಹಾಕಿ"
        CALL_SUPPORT_NUMBER ->  "ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ"
        YEARS_AGO ->  "ವರ್ಷಗಳ ಹಿಂದೆ"
        MONTHS_AGO ->  "ತಿಂಗಳುಗಳ ಹಿಂದೆ"
        DAYS_AGO ->  "ದಿನಗಳ ಹಿಂದೆ"
        HOURS_AGO ->  "ಗಂಟೆಗಳ ಹಿಂದೆ"
        MIN_AGO ->  "ನಿಮಿಷದ ಹಿಂದೆ"
        SEC_AGO ->  "ಎರಡನೇ ಹಿಂದೆ"
        APP_RELATED ->  "ಅಪ್ಲಿಕೇಶನ್ ಸಂಬಂಧಿತ"
        FARE ->  "ಶುಲ್ಕ ಸಂಬಂಧಿತ"
        RIDE_RELATED ->  "ಸವಾರಿ ಸಂಬಂಧಿತ"
        LOST_AND_FOUND ->  "ಕಳೆದು ಮತ್ತೆ ದೊರಕಿದ"
        REPORT_LOST_ITEM ->  "ಕಳೆದುಹೋದ ಐಟಂ ಅನ್ನು ವರದಿ ಮಾಡಿ"
        SELECT_YOUR_GENDER -> "ನಿಮ್ಮ ಲಿಂಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        FEMALE -> "ಸ್ತ್ರೀ"
        MALE -> "ಪುರುಷ"
        PREFER_NOT_TO_SAY -> "ಹೇಳದಿರಲು ಆದ್ಯತೆ"
        GENDER ->  "ಲಿಂಗ"
        SET_NOW ->  "ಈಗ ಹೊಂದಿಸಿ"
        COMPLETE_YOUR_PROFILE_AND_FIND_MORE_RIDES ->  "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ ಮತ್ತು ಹೆಚ್ಚಿನ ಸವಾರಿಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ!"
        UPDATE_NOW ->  "ಈಗ ನವೀಕರಿಸಿ"
        CONFIRM ->  "ದೃಢೀಕರಿಸಿ"
        GENDER_UPDATED ->  "ಲಿಂಗವನ್ನು ನವೀಕರಿಸಲಾಗಿದೆ"
        CORPORATE_ADDRESS _ ->  "ಕಾರ್ಪೊರೇಟ್ ವಿಳಾಸ"
        CORPORATE_ADDRESS_DESCRIPTION _ ->  "ಜಸ್ಪೇ ಟೆಕ್ನಾಲಜೀಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್ <br> ಗಿರಿಜಾ ಬಿಲ್ಡಿಂಗ್, ಸಂಖ್ಯೆ 817, ಗಣಪತಿ ದೇವಸ್ಥಾನ ರಸ್ತೆ, 8ನೇ ಬ್ಲಾಕ್, ಕೋರಮಂಗಲ, ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ 560095, ಭಾರತ."
        CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL _ ->  "ವೆಬ್‌ಸೈಟ್ : <u>https://nammayatri.in/</u>"
        REGISTERED_ADDRESS _ ->  "ನೋಂದಾಯಿಸಿದ ವಿಳಾಸ"
        REGISTERED_ADDRESS_DESCRIPTION _ ->  "ಜಸ್ಪೇ ಟೆಕ್ನಾಲಜೀಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್ <br> ಸ್ಟಾಲಿಯನ್ ಬಿಸಿನೆಸ್ ಸೆಂಟರ್, ನಂ. 444, 3ನೇ ಮತ್ತು 4ನೇ ಮಹಡಿ, 18ನೇ ಮುಖ್ಯ ರಸ್ತೆ, 6ನೇ ಬ್ಲಾಕ್, ಕೋರಮಂಗಲ ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ- 560095, ಭಾರತ"
        REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL _ ->  "ವೆಬ್‌ಸೈಟ್ : <u>https://nammayatri.in/</u>"
        ZONE_CANCEL_TEXT_DROP ->  "ನಿಮ್ಮ ಗ್ರಾಹಕರು ಬಹುಶಃ ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ ಮೆಟ್ರೋ ನಿಲ್ದಾಣವನ್ನು ತಲುಪುವ ಧಾವಂತದಲ್ಲಿದ್ದಾರೆ! \n ರದ್ದು ಮಾಡದಂತೆ ನಾವು ನಿಮ್ಮನ್ನು ಒತ್ತಾಯಿಸುತ್ತೇವೆ."
        ZONE_CANCEL_TEXT_PICKUP ->  "ನಿಮ್ಮ ಗ್ರಾಹಕರು ಬಹುಶಃ ತಮ್ಮ ಗಮ್ಯಸ್ಥಾನವನ್ನು ತಲುಪುವ ಆತುರದಲ್ಲಿರುತ್ತಾರೆ. \n ರದ್ದು ಮಾಡದಂತೆ ನಾವು ನಿಮ್ಮನ್ನು ಒತ್ತಾಯಿಸುತ್ತೇವೆ."
        RANKINGS ->  "ಶ್ರೇಯಾಂಕ"
        GETTING_THE_LEADERBOARD_READY ->  "ಲೀಡರ್‌ಬೋರ್ಡ್ ರಚಿಸಲಾಗುತ್ತಿದೆ!"
        PLEASE_WAIT_WHILE_WE_UPDATE_THE_DETAILS ->  "ನಾವು ವಿವರಗಳನ್ನು ನವೀಕರಿಸುವವರೆಗೆ ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ"
        LAST_UPDATED ->  "ಕೊನೆಯ ನವೀಕರಣ: "
        CONGRATULATIONS_YOU_ARE_RANK ->  "ಅಭಿನಂದನೆಗಳು ! ನಿಮ್ಮ ಶ್ರೇಣಿ "
        YOU ->  " (ನೀವು)"
        DAILY ->  "ಪ್ರತಿದಿನ"
        WEEKLY ->  "ಸಾಪ್ತಾಹಿಕ"
        ACCEPT_RIDES_TO_ENTER_RANKINGS ->  "ಶ್ರೇಯಾಂಕಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಸವಾರಿಗಳನ್ನು ಸ್ವೀಕರಿಸಿ!"
        OTP_HAS_BEEN_RESENT ->  "OTP ಅನ್ನು ಮರು ಕಳುಹಿಸಲಾಗಿದೆ"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_RESENDING_OTP ->  "OTP ಇನ್‌ಪುಟ್ ಮಿತಿಯನ್ನು ತಲುಪಿದೆ, ದಯವಿಟ್ಟು ಮತ್ತೆ OTP ಕಳುಹಿಸಲು ಪ್ರಯತ್ನಿಸಿ"
        OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER ->  "OTP ಮರುಕಳುಹಿಸುವ ಮಿತಿಯನ್ನು ತಲುಪಿದೆ, ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN ->  "OTP ಪುಟದ ಅವಧಿ ಮುಗಿದಿದೆ, ದಯವಿಟ್ಟು OTP ಗೆ ಮತ್ತೊಮ್ಮೆ ವಿನಂತಿಸಿ"
        SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN ->  "ಕೆಲವು ತಾಂತ್ರಿಕ ಸಮಸ್ಯೆ ಸಂಭವಿಸಿದೆ, ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        INVALID_REFERRAL_CODE ->  "ಅಮಾನ್ಯವಾದ ರೆಫರಲ್‌ ಕೋಡ್"
        ISSUE_REMOVED_SUCCESSFULLY ->  "ಸಮಸ್ಯೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪರಿಹರಿಸಲಾಗಿದೆ"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER ->  "OTP ಇನ್‌ಪುಟ್ ಮಿತಿಯನ್ನು ತಲುಪಿದೆ, ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        TOO_MANY_ATTEMPTS_PLEASE_TRY_AGAIN_LATER ->  "ನೀವು ಹಲವಾರು ಅಮಾನ್ಯ ಪ್ರಯತ್ನಗಳನ್ನು ಮಾಡಿದ್ದೀರಿ, ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        INVALID_REFERRAL_NUMBER ->  "ಅಮಾನ್ಯ ರೆಫರಲ್ ಸಂಖ್ಯೆ"
        SOMETHING_WENT_WRONG_TRY_AGAIN_LATER ->  "ಕೆಲವು ತಾಂತ್ರಿಕ ಸಮಸ್ಯೆ ಸಂಭವಿಸಿದೆ, ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        WAIT_TIME ->  "ಕಾಯುವ ಸಮಯ"
        WAIT_TIMER ->  "ಟೈಮರ್ ನಿರೀಕ್ಷಿಸಿ"
        HOW_LONG_WAITED_FOR_PICKUP ->  "ಪಿಕಪ್‌ನಲ್ಲಿ ನೀವು ಎಷ್ಟು ಸಮಯ ಕಾಯುತ್ತಿದ್ದೀರಿ ಎಂಬುದನ್ನು ತೋರಿಸುತ್ತದೆ."
        CUSTOMER_WILL_PAY_FOR_EVERY_MINUTE ->  "ಗ್ರಾಹಕರು \nಮೊದಲ {} ನಿಮಿಷಗಳ ನಂತರ ಪ್ರತಿ ನಿಮಿಷ ಕಾಯುವ ಸಮಯಕ್ಕೆ ₹1.5\n ಪಾವತಿಸುತ್ತಾರೆ."
        OTHERS ->  "ಇತರರು"
        ENTER_SECOND_SIM_NUMBER ->  "ಎರಡನೇ ಸಿಮ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        ALTERNATE_NUMBER ->  "ಪರ್ಯಾಯ ಸಂಖ್ಯೆ"
        SELECT_THE_LANGUAGES_YOU_CAN_SPEAK ->  "ನೀವು ಮಾತನಾಡಬಹುದಾದ ಭಾಷೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        OTP_RESEND_LIMIT_EXCEEDED ->  "OTP ಮಿತಿಯನ್ನು ಮರುಕಳುಹಿಸಲಾಗಿದೆ"
        LIMIT_EXCEEDED_FOR_ALTERNATE_NUMBER ->  "ಅನೇಕ ತಪ್ಪು ಪ್ರಯತ್ನಗಳು. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        ALTERNATE_NUMBER_CANNOT_BE_ADDED ->  "ಪರ್ಯಾಯ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಲಾಗುವುದಿಲ್ಲ"
        OTP_RESENT -> "OTP ಮರು ಕಳುಹಿಸಲಾಗಿದೆ"
        SEDAN ->  "ಸೆಡಾನ್"
        SUV ->  "SUV"
        HATCHBACK ->  "ಹ್ಯಾಚ್ಬ್ಯಾಕ್"
        AUTO_RICKSHAW ->  "ಆಟೋ ರಿಕ್ಷಾ"
        TAXI ->  "ನಾನ್-ಎಸಿ ಟ್ಯಾಕ್ಸಿ"
        TAXI_PLUS ->  "ಎಸಿ ಟ್ಯಾಕ್ಸಿ"
        MY_PROFILE ->  "ನನ್ನ ಪ್ರೊಫೈಲ್"
        SETTINGS ->  "ಸೆಟ್ಟಿಂಗ್‌ಗಳು"
        REG_NUMBER ->  "ನೋಂದಣಿ ಸಂಖ್ಯೆ"
        TYPE ->  "ಟೈಪ್"
        MODEL_NAME ->  "ಮಾದರಿ ಹೆಸರು"
        COLOUR ->  "ಬಣ್ಣ"
        BADGES ->  "ಬ್ಯಾಡ್ಜ್‌ಗಳು"
        CALL_CUSTOMER_SUPPORT ->  "ಗ್ರಾಹಕ ಬೆಂಬಲಕ್ಕೆ ಕರೆ ಮಾಡಿ"
        EDIT_RC ->  "RC ಸಂಪಾದಿಸಿ"
        DELETE_RC ->  "RC ಅಳಿಸಿ"
        DEACTIVATE_RC ->  "RC ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ"
        ACTIVATE_RC ->  "ಆರ್ಸಿ ಸಕ್ರಿಯಗೊಳಿಸಿ"
        ACTIVE_RC_ON_ANOTHER_DRIVER ->  " ಮತ್ತೊಂದು ಚಾಲಕ ಖಾತೆಯಲ್ಲಿ ಸಕ್ರಿಯವಾಗಿದೆ!"
        CALL_DRIVER_OR_CONTACT_SUPPORT ->  "RC ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲು ಚಾಲಕನಿಗೆ ಕರೆ ಮಾಡಿ ಅಥವಾ ಚಾಲಕವನ್ನು ತಲುಪಲು ಸಾಧ್ಯವಾಗದಿದ್ದರೆ ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ"
        CALL_DRIVER ->  "ಚಾಲಕನಿಗೆ ಕರೆ ಮಾಡಿ"
        SKIP ->  "ಬಿಟ್ಟುಬಿಡಿ"
        ACTIVE_STR ->  "ಸಕ್ರಿಯ"
        INACTIVE_RC ->  "ನಿಷ್ಕ್ರಿಯ"
        CONFIRMATION_FOR_DELETING_RC ->  "ನಿಮ್ಮ RC ಅನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ"
        CONFIRMATION_FOR_DEACTIVATING_RC ->  "ನಿಮ್ಮ RC ಅನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ- "
        CONFIRMATION_FOR_ACTIVATING_RC ->  "ನೀವು RC ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ- "
        YES_DELETE ->  "ಹೌದು, ಅಳಿಸಿ"
        ADD_NEW_RC ->  "ಆರ್ಸಿ ಸೇರಿಸಿ"
        CONNECT_CALL_ANONYMOUSLY -> "ನಾವು ನಿಮ್ಮನ್ನು ಚಾಲಕನೊಂದಿಗೆ ಅನಾಮಧೇಯವಾಗಿ ಸಂಪರ್ಕಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತೇವೆ ದಯವಿಟ್ಟು RC ಅನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲು ವಿನಂತಿಸುವ ಮೊದಲು ನಿಮ್ಮನ್ನು ಪರಿಚಯಿಸಿಕೊಳ್ಳಿ."
        YES_ACTIVATE ->  "ಹೌದು, ಸಕ್ರಿಯಗೊಳಿಸಿ"
        YES_DEACTIVATE ->  "ಹೌದು, ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ"
        THIS_WILL_DEACTIVATE_CURRENTLY_ACTIVE_RC ->  "ಇದು ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸಕ್ರಿಯವಾಗಿರುವ RC ಅನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸುತ್ತದೆ."
        REMOVED ->  "ತೆಗೆದುಹಾಕಲಾಗಿದೆ"
        IS_ACTIVE_NOW ->  " ಈಗ ಸಕ್ರಿಯವಾಗಿದೆ."
        DEACTIVATED ->  "ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ"
        LANGUAGE_UPDATED ->  "ಭಾಷೆಯನ್ನು ನವೀಕರಿಸಲಾಗಿದೆ"
        SINGLE_RC_CANNOT_BE_DELETED ->  "ಏಕ RC ಅನ್ನು ಅಳಿಸಲಾಗುವುದಿಲ್ಲ"
        CANCELLATION_RATE ->  "ರದ್ದತಿ ದರ"
        RIDES_CANCELLED ->  " ರದ್ದಾದ ಸವಾರಿಗಳು"
        EARNINGS_MISSED ->  "ತಪ್ಪಿದ ಗಳಿಕೆಗಳು"
        SUMMARY ->  "ಸಾರಾಂಶ"
        NAMMA_BONUS -> "ನಮ್ಮ ಬೋನಸ್"
        TRIPS_COMPLETED ->  "ಸಂಪೂರ್ಣ ಪ್ರವಾಸಗಳು"
        LATE_NIGHT_TRIPS ->  "ಲೇಟ್ ನೈಟ್ ಟ್ರಿಪ್ಸ್"
        ABOUT_ME ->  "ನನ್ನ ಬಗ್ಗೆ"
        ABOUT_VEHICLE ->  "ವಾಹನದ ಬಗ್ಗೆ"
        ADD ->  "ಸೇರಿಸು"
        YEARS_OLD ->  "ವರ್ಷ ಹರೆಯ"
        HOMETOWN ->  "ಹೋಮ್ ಟೌನ್"
        MISSED_OPPORTUNITY ->  "ತಪ್ಪಿದ ಅವಕಾಶಗಳು"
        HOW_OLD_IS_YOUR_VEHICLE ->  "ನಿಮ್ಮ ವಾಹನ ಎಷ್ಟು ಹಳೆಯದು (ವರ್ಷಗಳಲ್ಲಿ)?"
        NEW_ ->  "ಹೊಸದು"
        TODAY ->  "ಇಂದು"
        OKAY ->  "ಸರಿ"
        NO_PAYMENT_HISTORY_AVAILABLE ->  "ಯಾವುದೇ ಪಾವತಿ ಇತಿಹಾಸ ಲಭ್ಯವಿಲ್ಲ"
        ENTER_AADHAAR_NUMBER ->  "ಆಧಾರ್ ಸಂಖ್ಯೆ/ಯುಐಡಿ ನಮೂದಿಸಿ"
        AADHAAR_LINKING_REQUIRED ->  "ಆಧಾರ್ ಲಿಂಕ್ ಅಗತ್ಯವಿದೆ"
        AADHAAR_LINKING_REQUIRED_DESCRIPTION _ ->  "ಯಾತ್ರಿ ಸತಿಗೆ ಚಾಲನೆಯನ್ನು ಪ್ರಾರಂಭಿಸಲು, ದಯವಿಟ್ಟು \n ನಿಮ್ಮ ಆಧಾರ್ ಐಡಿಯನ್ನು ಲಿಂಕ್ ಮಾಡಿ"
        BY_CLICKING_THIS_YOU_WILL_BE_AGREEING_TO_OUR_TC ->  "ಮುಂದುವರಿಸು ಕ್ಲಿಕ್ ಮಾಡುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ "
        TERMS_AND_CONDITIONS_SHORT ->  "T&C ಗೆ ಸಮ್ಮತಿಸುತ್ತೀರಿ"
        TC_TAIL ->  ""
        OTP_SENT_TO_AADHAAR_NUMBER -> "ನಿಮ್ಮ ಆಧಾರ್‌ನೊಂದಿಗೆ ಲಿಂಕ್ ಮಾಡಲಾದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ"
        ENTER_SIX_DIGIT_OTP ->  "ಆರು ಅಂಕಿಯ OTP ನಮೂದಿಸಿ"
        LINK_AADHAAR_ID ->  "ಲಿಂಕ್ ಆಧಾರ್ ಐಡಿ"
        NO_MOBILE_NUMBER_REGISTERED ->  "ಆಧಾರ್ ಸಂಖ್ಯೆಯು ಅದರೊಂದಿಗೆ ನೋಂದಾಯಿಸಲಾದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಹೊಂದಿಲ್ಲ."
        EXCEED_OTP_GENERATION_LIMIT ->  "ಗರಿಷ್ಠ OTP ಉತ್ಪಾದನೆಯ ಮಿತಿಯನ್ನು ಮೀರಿದೆ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ."
        AADHAAR_NUMBER_NOT_EXIST ->  "ಆಧಾರ್ ಸಂಖ್ಯೆ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ."
        INVALID_OTP ->  "ಅಮಾನ್ಯ OTP"
        NO_SHARE_CODE ->  "ಯಾವುದೇ ಹಂಚಿಕೆ ಕೋಡ್ ಒದಗಿಸಲಾಗಿಲ್ಲ"
        WRONG_SHARE_CODE ->  "ತಪ್ಪಾದ ಹಂಚಿಕೆ ಕೋಡ್"
        INVALID_SHARE_CODE ->  "ಅಮಾನ್ಯ ಹಂಚಿಕೆ ಕೋಡ್. ಉದ್ದವು 4 ಆಗಿರಬೇಕು ಮತ್ತು ಸಂಖ್ಯೆಗಳನ್ನು ಮಾತ್ರ ಒಳಗೊಂಡಿರಬೇಕು."
        SESSION_EXPIRED ->  "ಅವಧಿ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ."
        OTP_ATTEMPT_EXCEEDED ->  "OTP ಪ್ರಯತ್ನಗಳನ್ನು ಮೀರಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ"
        UPSTREAM_INTERNAL_SERVER_ERROR ->  "ಅಪ್‌ಸ್ಟ್ರೀಮ್ ಮೂಲ/ಸರ್ಕಾರಿ ಮೂಲ ಆಂತರಿಕ ಸರ್ವರ್ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ."
        TRANSACTION_ALREADY_COMPLETED ->  "ವಹಿವಾಟು ಈಗಾಗಲೇ ಪೂರ್ಣಗೊಂಡಿದೆ. ಈ ವಹಿವಾಟಿನ ಮೇಲೆ ಹೆಚ್ಚಿನ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ."
        GOTO_YOUR_NEAREST_BOOTH -> "ನಿಮ್ಮ ಆಧಾರ್ ಅನ್ನು ಪರಿಶೀಲಿಸಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹತ್ತಿರದ ಬೂತ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ."
        AADHAAR_ALREADY_LINKED ->  "ಈಗಾಗಲೇ ಆಧಾರ್ ಲಿಂಕ್ ಮಾಡಲಾಗಿದೆ"
        OPTIONAL ->  " (ಐಚ್ಛಿಕ)"
        DOWNLOAD_STATEMENT ->  "ಡೌನ್‌ಲೋಡ್ ಹೇಳಿಕೆ"
        SELECT_A_DATE_RANGE ->  "ಹೇಳಿಕೆಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ದಿನಾಂಕ ಶ್ರೇಣಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        FEE_PAYMENT_HISTORY ->  "ಶುಲ್ಕ ಪಾವತಿ ಇತಿಹಾಸ"
        LANGUAGES_SPOKEN ->  "ಮಾತನಾಡುವ ಭಾಷೆಗಳು"
        VIEW_PAYMENT_HISTORY ->  "ಪಾವತಿ ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಿ"
        RIDE_TYPE ->  "ರೈಡ್ ಪ್ರಕಾರ"
        PLACE_CALL_REQUEST ->  "ಕರೆ ವಿನಂತಿಯನ್ನು ಇರಿಸಿ"
        RC_STATUS ->  "RC ಸ್ಥಿತಿ"
        RATED_BY_USERS1 ->  ""
        RATED_BY_USERS2 ->  "ಬಳಕೆದಾರರು ಇವರಿಂದ ರೇಟ್ ಮಾಡಲಾಗಿದೆ"
        MONTHS ->  "ತಿಂಗಳುಗಳು"
        RC_ADDED_SUCCESSFULLY ->  "ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ"
        OFFER_APPLIED ->  "ಆಫರ್ ಅನ್ವಯಿಸಲಾಗಿದೆ"
        YOUR_EARNINGS ->  "ನಿಮ್ಮ ಗಳಿಕೆ"
        NUMBER_OF_RIDES ->  "ಸವಾರಿಗಳ ಸಂಖ್ಯೆ"
        FARE_BREAKUP ->  "ಶುಲ್ಕ ವಿಭಜನೆ"
        MY_PLAN ->  "ನನ್ನ ಪ್ಲಾನ್"
        YOUR_DUES ->  "ನಿಮ್ಮ ಬಾಕಿಗಳು"
        YOUR_DUES_DESCRIPTION ->  "ನಿಮ್ಮ ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಲು ನೀವು ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಹೊಂದಿಸಿರುವಿರಿ. ನಿಮ್ಮ ಬಾಕಿಗಳನ್ನು ಯಾವಾಗಲೂ ಸಮಯಕ್ಕೆ ಪಾವತಿಸಲಾಗಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನಾವು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪ್ರಯತ್ನಿಸುತ್ತೇವೆ."
        CURRENT_DUES ->  "ಪ್ರಸ್ತುತ ಬಾಕಿಗಳು"
        YOUR_LIMIT ->  "ನಿಮ್ಮ ಮಿತಿ"
        DUE_DETAILS ->  "ಬಾಕಿ ವಿವರಗಳು"
        TRIP_DATE ->  "ಪ್ರವಾಸದ ದಿನಾಂಕ"
        AMOUNT ->  "ಮೊತ್ತ"
        VIEW_DUE_DETAILS ->  "ಬಾಕಿಯಿರುವ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ"
        SETUP_AUTOPAY ->  "ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಹೊಂದಿಸಿ"
        CURRENT_PLAN ->  "ಪ್ರಸ್ತುತ ಯೋಜನೆ"
        ALTERNATE_PLAN ->  "ಪರ್ಯಾಯ ಯೋಜನೆ"
        AUTOPAY_DETAILS ->  "ಸ್ವಯಂ ಪಾವತಿ ವಿವರಗಳು"
        CANCEL_AUTOPAY_STR ->  "ಸ್ವಯಂ ಪಾವತಿ ರದ್ದುಮಾಡಿ"
        WE_MIGHT_BE_LOST ->  "ಉಹ್ ಓಹ್! ನಾವು ಕಳೆದುಹೋಗಬಹುದು"
        EXEPERIENCING_ERROR ->  "ದೋಷವನ್ನು ಅನುಭವಿಸುತ್ತಿದೆ"
        ENJOY_THESE_BENEFITS ->  "ಈ ಪ್ರಯೋಜನಗಳನ್ನು ಆನಂದಿಸಿ"
        CHOOSE_YOUR_PLAN _ ->  "ಈಗ ಯೋಜನೆಯನ್ನು ಆರಿಸಿ!"
        SKIP_FOR_NOW ->  "ಇದೀಗ ಬಿಟ್ಟುಬಿಡಿ"
        SEVEN_DAY_FREE_TRIAL_ACTIVATED ->  "7-ದಿನದ ಉಚಿತ ಪ್ರಯೋಗವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ!"
        TAKE_UNLIMITED_RIDES_FOR_THE_NEXT_SEVEN_DAYS ->  "ಮೊದಲ 7 ದಿನಗಳವರೆಗೆ ಅನಿಯಮಿತ ಸವಾರಿಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ"
        EVERY_RIDE_AT_ZERO_COMMISSION ->  "ZERO ಆಯೋಗದಲ್ಲಿ ಪ್ರತಿ ಸವಾರಿ!"
        EARN_UPTO_PER_DAY ->  "ದಿನಕ್ಕೆ ₹2500 ವರೆಗೆ ಗಳಿಸಿ!"
        HOW_THIS_WORKS ->  "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ"
        SIGN_UP_FOR_AUTOPAY_BY_PAYING_JUST ->  "ಕೇವಲ ₹1 ಪಾವತಿಸುವ ಮೂಲಕ ಸ್ವಯಂ ಪಾವತಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ"
        GET_REMINDED_ABOUT_YOUR_PLAN_SETUP ->  "ನಿಮ್ಮ ಪ್ಲಾನ್ ಸೆಟಪ್ ಕುರಿತು ನೆನಪಿಸಿಕೊಳ್ಳಿ"
        FREE_TRIAL_REMINDER ->  "ದಿನ 5: ಉಚಿತ ಪ್ರಯೋಗ ಜ್ಞಾಪನೆ"
        PLAN_STARTS ->  "ದಿನ 7: ಯೋಜನೆ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ"
        EASY_AUTOMATIC_PAYMENTS_START ->  "ಸುಲಭ, ಸ್ವಯಂಚಾಲಿತ ಪಾವತಿಗಳು ಪ್ರಾರಂಭವಾಗುತ್ತವೆ"
        FREE_UNTIL ->  " ತನಕ ಉಚಿತ"
        PER_RIDE ->  "ಪ್ರತಿ ಸವಾರಿಗೆ"
        PER_DAY ->  "ಪ್ರತಿ ದಿನಕ್ಕೆ"
        OFFER ->  "ಆಫರ್"
        OFFERS ->  "ಕೊಡುಗೆಗಳು"
        YOU_ARE_ON_THE_FREE_TRIAL ->  "ನೀವು ಉಚಿತ ಪ್ರಯೋಗದಲ್ಲಿರುವಿರಿ"
        SETUP_AUTOPAY_BEFORE_THE_TRAIL_PERIOD_EXPIRES ->  "ಪ್ರಾಯೋಗಿಕ ಅವಧಿ ಮುಗಿಯುವ ಮೊದಲು ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಹೊಂದಿಸಿ"
        GET_FREE_TRAIL_UNTIL ->  "ತನಕ ಉಚಿತ ಪ್ರಯೋಗವನ್ನು ಪಡೆಯಿರಿ"
        CLEAR_DUES ->  "ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ"
        PAYMENT_PENDING_ALERT ->  "⚠️ ಪಾವತಿ ಬಾಕಿಯಿದೆ! ⚠️"
        PAYMENT_PENDING_ALERT_DESC ->  "ನಮ್ಮ ಯಾತ್ರಿಯಲ್ಲಿ ಸವಾರಿ ಮಾಡುವುದನ್ನು ಮುಂದುವರಿಸಲು, ನಿಮ್ಮ ಪಾವತಿ ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ"
        LOW_ACCOUNT_BALANCE ->  "ಕಡಿಮೆ ಖಾತೆ ಬಾಕಿ"
        LOW_ACCOUNT_BALANCE_DESC ->  "ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯ ಬ್ಯಾಲೆನ್ಸ್ ಕಡಿಮೆಯಾಗಿದೆ. ತಡೆರಹಿತ ಸವಾರಿಗಳನ್ನು ಆನಂದಿಸಲು ಹಣವನ್ನು ಸೇರಿಸಿ."
        OKAY_GOT_IT ->  "ಸರಿ, ಅರ್ಥವಾಯಿತು"
        LIMITED_TIME_OFFER ->  "ನಿಮಗಾಗಿ ಸೀಮಿತ ಸಮಯದ ಕೊಡುಗೆ!"
        JOIN_NOW ->  "ಈಗ ಸೇರಿ"
        AUTOMATIC_PAYMENTS_WILL_APPEAR_HERE ->  "ಸ್ವಯಂಚಾಲಿತ ಪಾವತಿಗಳು ಇಲ್ಲಿ ಗೋಚರಿಸುತ್ತವೆ"
        MANUAL_PAYMENTS ->  "ಹಸ್ತಚಾಲಿತ ಪಾವತಿಗಳು"
        MANUAL_PAYMENTS_WILL_APPEAR_HERE ->  "ಹಸ್ತಚಾಲಿತ ಪಾವತಿಗಳು ಇಲ್ಲಿ ಗೋಚರಿಸುತ್ತವೆ"
        NO_AUTOMATIC_PAYMENTS_DESC ->  "ಒಮ್ಮೆ ನಿಮಗೆ ಶುಲ್ಕ ವಿಧಿಸಿದರೆ ನಿಮ್ಮ ಸ್ವಯಂ ಪಾವತಿ ಇತಿಹಾಸವು ಇಲ್ಲಿ ಗೋಚರಿಸುತ್ತದೆ"
        NO_MANUAL_PAYMENTS_DESC ->  "ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಲು ನಿಮ್ಮ ಪಾವತಿ ಇತಿಹಾಸವು ಯಾವುದಾದರೂ ಇದ್ದರೆ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ."
        PAYMENT_HISTORY ->  "ಪಾವತಿ ಇತಿಹಾಸ"
        TAP_A_PLAN_TO_VIEW_DETAILS ->  "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಯೋಜನೆಯನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ"
        HOW_IT_WORKS ->  "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ"
        ZERO_COMMISION ->  "ZERO ಕಮಿಷನ್"
        EARN_TODAY_PAY_TOMORROW ->  "ಇಂದು ಗಳಿಸಿ, ನಾಳೆ ಪಾವತಿಸಿ"
        PAY_ONLY_IF_YOU_TAKE_RIDES ->  "ನೀವು ಸವಾರಿ ಮಾಡಿದರೆ ಮಾತ್ರ ಪಾವತಿಸಿ"
        PLANS ->  "ಪ್ಲಾನ್"
        PLAN ->  "ಯೋಜನೆ"
        DAY ->  "ದಿನ"
        MANAGE_PLAN ->  "ಯೋಜನೆಯನ್ನು ನಿರ್ವಹಿಸಿ"
        VIEW_AUTOPAY_DETAILS ->  "ಸ್ವಯಂ ಪಾವತಿ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ"
        SWITCH_AND_SAVE ->  "ಸ್ವಿಚ್ ಮತ್ತು ಸೇವ್"
        SWITCH_AND_SAVE_DESC ->  "ನೀವು ಇಂದು 7 ರೈಡ್‌ಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದ್ದೀರಿ. ದೈನಂದಿನ ಅನ್ಲಿಮಿಟೆಡ್ ಯೋಜನೆಗೆ ಬದಲಾಯಿಸುವ ಮೂಲಕ ₹10 ವರೆಗೆ ಉಳಿಸಿ"
        SWITCH_NOW ->  "ಈಗ ಬದಲಿಸಿ"
        PAYMENT_MODE_CHANGED_TO_MANUAL ->  "ಪಾವತಿ ಮೋಡ್ ಅನ್ನು ಹಸ್ತಚಾಲಿತವಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ"
        PAYMENT_MODE_CHANGED_TO_MANUAL_DESC ->  "ನಿಮ್ಮ UPI ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ನೀವು ವಿರಾಮಗೊಳಿಸಿರುವಿರಿ. ನಿಮ್ಮ ಬಾಕಿಯನ್ನು ನೀವು ಹಸ್ತಚಾಲಿತವಾಗಿ ತೆರವುಗೊಳಿಸಬಹುದು."
        AUTOPAY_PAYMENTS ->  "ಸ್ವಯಂ ಪಾವತಿಗಳು"
        TRANSACTION_ON ->  "ವಹಿವಾಟು ಆನ್"
        SUCCESS ->  "ಯಶಸ್ಸು"
        RIDES_TAKEN_ON ->  "ಸವಾರಿ ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ"
        JOIN_PLAN ->  "ಸೇರಿ ಯೋಜನೆ"
        JOIN_NAMMAA_YATRI ->  "ನಮ್ಮ ಯಾತ್ರಿ ಸೇರಿ"
        CANCEL_AUTOPAY_AND_PAY_MANUALLY ->  "ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ರದ್ದುಮಾಡಿ ಮತ್ತು ಹಸ್ತಚಾಲಿತವಾಗಿ ಪಾವತಿಸಿ"
        PLAN_ACTIVATED_SUCCESSFULLY ->  "ಯೋಜನೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ"
        DUES_CLEARED_SUCCESSFULLY ->  "ಬಾಕಿಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ತೆರವುಗೊಳಿಸಲಾಗಿದೆ"
        NOT_PLANNING_TO_TAKE_RIDES ->  "ಸವಾರಿ ತೆಗೆದುಕೊಳ್ಳಲು ಯೋಜಿಸುತ್ತಿಲ್ಲವೇ?"
        RETRY_PAYMENT_STR ->  "ಪಾವತಿಯನ್ನು ಮರುಪ್ರಯತ್ನಿಸಿ"
        PAUSE_AUTOPAY_STR ->  "ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ವಿರಾಮಗೊಳಿಸಿ"
        SETUP_AUTOPAY_STR ->  "ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಹೊಂದಿಸಿ"
        VIEW_RIDE_DETAILS ->  "ರೈಡ್ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ"
        ACCOUNT ->  "ಖಾತೆ"
        AUTOPAY_IS_NOT_ENABLED_YET ->  "ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಇನ್ನೂ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿಲ್ಲ!"
        ENABLE_AUTOPAY_DESC ->  "ತೊಂದರೆ-ಮುಕ್ತ ಪಾವತಿಗಳನ್ನು ಪ್ರಾರಂಭಿಸಲು ಈಗ ಸ್ವಯಂಪಾವತಿಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ!"
        ENABLE_AUTOPAY_NOW ->  "ಈಗ ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ"
        AUTOPAY_SETUP_PENDING_STR ->  "ಆಟೋಪೆ ಸೆಟಪ್ ಬಾಕಿಯಿದೆ!"
        AUTOPAY_PENDING_DESC_STR ->  "ನಿರೀಕ್ಷಿಸಿ ಅಥವಾ ಮರುಪ್ರಯತ್ನಿಸಿ, ಹೆಚ್ಚುವರಿ ಪಾವತಿಯನ್ನು ಮರುಪಾವತಿಸಲಾಗುತ್ತದೆ"
        REFRESH_STR ->  "ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ"
        TRANSACTION_DETAILS ->  "ವಹಿವಾಟು ವಿವರಗಳು"
        RIDE_DETAILS ->  "ಸವಾರಿ ವಿವರಗಳು"
        MY_PLAN_TITLE _ ->  "ನಮ್ಮ ಯಾತ್ರಿ ಪ್ಲಾನ್ ಗಳು"
        SWITCH_TO ->  "{} ಯೋಜನೆಗೆ ಬದಲಿಸಿ"
        PLEASE_TRY_AGAIN ->  "ದಯವಿಟ್ಟು ಪುನಃ ಪ್ರಯತ್ನಿಸಿ"
        PLAN_NOT_FOUND ->  "ಯೋಜನೆ ಕಂಡುಬಂದಿಲ್ಲ"
        MANDATE_NOT_FOUND ->  "ಮ್ಯಾಂಡೇಟ್ ಕಂಡುಬಂದಿಲ್ಲ"
        ACTIVE_MANDATE_EXISTS ->  "ಸಕ್ರಿಯ ಆದೇಶ ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ"
        NO_ACTIVE_MANDATE_EXIST ->  "ಯಾವುದೇ ಸಕ್ರಿಯ ಆದೇಶ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ"
        NO_PLAN_FOR_DRIVER ->  "ಯಾವುದೇ ಯೋಜನೆ ಕಂಡುಬಂದಿಲ್ಲ"
        INVALID_PAYMENT_MODE ->  "ಅಮಾನ್ಯ ಪಾವತಿ ಮೋಡ್"
        INVALID_AUTO_PAY_STATUS ->  "ಅಮಾನ್ಯ ಸ್ವಯಂ ಪಾವತಿ ಸ್ಥಿತಿ"
        MAX_AMOUNT ->  "ಗರಿಷ್ಠ ಮೊತ್ತ"
        FREQUENCY -> "ಫ್ರೀಕ್ವೆನ್ಸಿ"
        STATRED_ON ->  "ಆರಂಭಗೊಂಡಿದೆ"
        EXPIRES_ON ->  "ಅವಧಿ ಮುಕ್ತಾಯವಾಗುತ್ತದೆ"
        SWITCHED_PLAN ->  "ಬದಲಾದ ಯೋಜನೆ"
        PAYMENT_PENDING ->  "ಪಾವತಿ ಬಾಕಿ ಇದೆ"
        PAYMENT_FAILED ->  "ಪಾವತಿ ವಿಫಲವಾಗಿದೆ"
        ONETIME ->  "ಒಂದು ಬಾರಿ"
        FORTNIGHTLY ->  "ಪಾಕ್ಷಿಕ"
        MONTHLY ->  "ಮಾಸಿಕ"
        BIMONTHLY ->  "ದ್ವೈಮಾಸಿಕ"
        QUARTERLY ->  "ತ್ರೈಮಾಸಿಕ"
        ASPRESENTED -> "ಯಾವಾಗ ಪ್ರಸ್ತುತಪಡಿಸಿದರೂ"
        DAILY_PER_RIDE_DESC ->  "ಸೆಪ್ಟೆಂಬರ್ 19 ರವರೆಗೆ ಯಾವುದೇ ಶುಲ್ಕವಿಲ್ಲ"
        FIRST_FREE_RIDE ->  "ಮೊದಲ ಸವಾರಿ ಉಚಿತ"
        JOIN_THE_UNLIMITED_PLAN ->  "ವಿಶೇಷ ರಿಯಾಯಿತಿಗಳನ್ನು ಪಡೆಯಲು ಈಗಲೇ ಡೈಲಿ ಅನ್‌ಲಿಮಿಟೆಡ್ ಪ್ಲಾನ್‌ಗೆ ಸೇರಿಕೊಳ್ಳಿ"
        MAYBE_LATER ->  "ಬಹುಶಃ ನಂತರ"
        YOUR_DUES_DESCRIPTION_MANUAL ->  "ತಡೆರಹಿತ ರೈಡ್‌ಗಳನ್ನು ಮುಂದುವರಿಸಲು ಮಿತಿಯನ್ನು ತಲುಪುವ ಮೊದಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ. ನೀವು ಸುಲಭವಾಗಿ, ತೊಂದರೆ-ಮುಕ್ತ ಪಾವತಿಗಳಿಗಾಗಿ <b>UPI ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಹೊಂದಿಸಬಹುದು</b>."
        DO_YOU_WANT_TO_CANCEL ->  "ನೀವು ರದ್ದುಗೊಳಿಸಲು ಬಯಸುವಿರಾ?"
        DO_YOU_WANT_TO_CANCEL_DESC ->  "ನೀವು ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಲಿರುವಿರಿ.\nಸ್ವಯಂಚಾಲಿತ ಪಾವತಿಗಳನ್ನು ಪುನರಾರಂಭಿಸಲು ನೀವು ಮತ್ತೆ ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಹೊಂದಿಸಬೇಕಾಗುತ್ತದೆ."
        YOUR_PAYMENT_WAS_UNSUCCESSFUL ->  "ನಿಮ್ಮ ಪಾವತಿಯ ಪ್ರಯತ್ನವು ವಿಫಲವಾಗಿದೆ."
        PAYMENT_CANCELLED -> "ನಿಮ್ಮ UPI ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ನೀವು ರದ್ದುಗೊಳಿಸಿದ್ದೀರಿ. ನಿಮ್ಮ ಬಾಕಿಯನ್ನು ನೀವು ಹಸ್ತಚಾಲಿತವಾಗಿ ತೆರವುಗೊಳಿಸಬಹುದು"
        UPI_AUTOPAY_S ->  "UPI ಸ್ವಯಂ ಪಾವತಿ"
        MANUAL_PAYMENT_STR ->  "ಹಸ್ತಚಾಲಿತ ಪಾವತಿ"
        DAILY_UNLIMITED ->  "ದೈನಂದಿನ ಅನಿಯಮಿತ"
        DAILY_PER_RIDE ->  "ಪ್ರತಿದಿನ ಪ್ರತಿ ಸವಾರಿಗೆ"
        DAILY_UNLIMITED_PLAN_DESC ->  "ಪ್ರತಿದಿನ ಅನ್ಲಿಮಿಟೆಡ್ ರೈಡ್‌ಗಳನ್ನು ಆನಂದಿಸಿ"
        DAILY_PER_RIDE_PLAN_DESC ->  "ದಿನಕ್ಕೆ ಗರಿಷ್ಠ ₹35"
        AUTOPAY_CANCELLED ->  "ಸ್ವಯಂ ಪಾವತಿ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ"
        NO ->  "ಇಲ್ಲ"
        YES_CANCEL ->  "ಹೌದು, ರದ್ದುಮಾಡಿ"
        PLAN_SWITCHED_TO ->  "ಪ್ಲಾನ್ ಬದಲಾಯಿಸಲು "
        PAY_TO_JOIN_THIS_PLAN ->  "ಯೋಜನೆಗೆ ಸೇರಲು ₹1 ಪಾವತಿಸಿ"
        OFFERS_NOT_APPLICABLE ->  "ಪೂರ್ಣಗೊಳ್ಳದ ಹೊರತು ಆಫರ್‌ಗಳು ಅನ್ವಯವಾಗುವುದಿಲ್ಲ"
        PAUSED_STR ->  "ವಿರಾಮಗೊಳಿಸಲಾಗಿದೆ"
        PENDING_STR ->  "ಬಾಕಿಯಿದೆ"
        SWITCH_PLAN_STR ->  "ಪ್ಲಾನ್ ಬದಲಾಯಿಸುವುದೇ?"
        OFFERS_APPLICABLE_ON_DAILY_UNLIMITED ->  "ಗಮನಿಸಿ: ದೈನಂದಿನ ಅನಿಯಮಿತ ಯೋಜನೆಯಲ್ಲಿ ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಸೆಟಪ್ ಮಾಡಿದರೆ ಮಾತ್ರ ಆಫರ್‌ಗಳು ಅನ್ವಯಿಸುತ್ತವೆ"
        DAILY_UNLIMITED_OFFER_NOT_AVAILABLE ->  "ಗಮನಿಸಿ: ಈ ಪ್ಲಾನ್ ನಲ್ಲಿ  ದೈನಂದಿನ ಅನಿಯಮಿತ ಪ್ಲಾನ್ ಆಫರ್ಗಳು ಅನ್ವಯಿಸುವುದಿಲ್ಲ"
        NO_RIDES_NO_CHARGE ->  "ನೀವು ಸವಾರಿ ಮಾಡಿದರೆ ಮಾತ್ರ ಪಾವತಿಸಿ" 
        GET_SPECIAL_OFFERS ->  "ಸ್ಪೆಷಲ್ ಆಫರ್ಗಳು ಪಡೆಯಿರಿ"
        VALID_ONLY_IF_PAYMENT ->  "ಪಾವತಿ ಪೂರ್ಣಗೊಂಡರೆ ಮಾತ್ರ ಮಾನ್ಯವಾಗಿರುತ್ತದೆ"
        HELP_STR ->  "ಸಹಾಯ"
        REFRESH_STRING ->  "ರಿಫ್ರೆಶ್"
        CHAT_FOR_HELP ->  "ಚಾಟ್?"
        VIEW_FAQs ->  "ಎಫ್.ಎ.ಕ್ಯೂ ವೀಕ್ಷಿಸಿ"
        FIND_HELP_CENTRE ->  "ಸಹಾಯ ಕೇಂದ್ರವನ್ನು ಹುಡುಕಿ"
        CONTACT ->  "ಸಂಪರ್ಕಿಸಿ"
        GO_TO_LOCATION ->  "ಸ್ಥಳಕ್ಕೆ ಹೋಗಿ"
        NO_HELP_CENTER_IS_ACTIVE_NOW ->  "ಸದ್ಯಕ್ಕೆ ಯಾವುದೇ ಸಹಾಯ ಕೇಂದ್ರ ಸಕ್ರಿಯವಾಗಿಲ್ಲ"
        HELP_CENTERS_LOCATION_WILL_APPEAR_HERE_ONCE_THEY_ARE_ACTIVE ->  "ಸಹಾಯ ಕೇಂದ್ರಗಳ ಸ್ಥಳಗಳು ಸಕ್ರಿಯವಾದ ನಂತರ ಇಲ್ಲಿ ಗೋಚರಿಸುತ್ತವೆ"
        SUPPORT ->  "ಬೆಂಬಲ"
        NEED_HELP_JOINING_THE_PLAN ->  "ಯೋಜನೆ ಅಥವಾ ಆಟೋಪೇಗೆ ಸೇರಲು ಸಹಾಯ ಬೇಕೇ?"
        GO_TO_VEHICLE_DETAILS ->  "ವಾಹನದ ವಿವರಗಳಿಗೆ ಹೋಗಿ"
        CLOSE -> "ಮುಚ್ಚಿ"
        RC_DEACTIVATED ->  "RC ನಿಷ್ಕ್ರಿಯಗೊಂಡಿದೆ"
        RC_DEACTIVATED_DETAILS ->  "ನಿಮ್ಮ RC ಪ್ರಸ್ತುತ ಮತ್ತೊಂದು ಚಾಲಕ ಖಾತೆಯಲ್ಲಿ ಸಕ್ರಿಯವಾಗಿದೆ. ಸವಾರಿಗಳನ್ನು ಪ್ರಾರಂಭಿಸಲು RC ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ"
        NEED_HELP ->  "ಸಹಾಯ ಬೇಕೇ?"
        SETUP_AUTOPAY_NOW_TO_GET_SPECIAL_DISCOUNTS -> "ಡಿಸ್ಕೌಂಟ್ಸ್ ಪಡೆಯಲು ಆಟೋಪೆ ಸೆಟಪ್ ಮಾಡಿ"
        SETUP_NOW ->  "ಈಗ ಸೆಟಪ್ ಮಾಡಿ"
        CUSTOMER_HAS_LOW_MOBILITY -> "ಗ್ರಾಹಕನಲ್ಲಿ ಕಡಿಮೆ ಚಲನಶೀಲತೆ ಇದೆ"
        CUSTOMER_HAS_DISABILITY -> "ಗ್ರಾಹಕನಲ್ಲಿ ಅಂಗವೈಕಲ್ಯ ಇದೆ"
        CUSTOMER_HAS_LOW_VISION -> "ಗ್ರಾಹಕನಲ್ಲಿ ಕಡಿಮೆ ದೃಷ್ಟಿ ಇದೆ"
        CUSTOMER_HAS_HEARING_IMPAIRMENT -> "ಗ್ರಾಹಕರು ಶ್ರವಣದೋಷವನ್ನು ಹೊಂದಿದ್ದಾರೆ"
        HELP_WITH_THEIR_MOBILITY_AID -> "ಅವರ ಚಲನಶೀಲತೆಗೆ ಸಹಾಯ ಮಾಡಿ "
        PLEASE_ASSIST_THEM_IF_NEEDED -> "ಅಗತ್ಯವಾದಾಗ ಅವರಿಗೆ ಸಹಾಯ ಮಾಡಿ"
        MESSAGE_THEM_AT_PICKUP -> "ಪಿಕಪ್ ನಲ್ಲಿ ಅವರಿಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ"
        SOUND_HORN_ONCE_AT_PICKUP -> "ಪಿಕಪ್ ನಲ್ಲಿ ಒಂದು ಸಲ ಹಾರ್ನ್ ಮಾಡಿ"
        PLEASE_CALL_AND_AVOID_CHATS -> "ದಯವಿಟ್ಟು ಕರೆಮಾಡಿ ಚಾಟ್‌ಗಳನ್ನು ತಡೆಹಿಡಿಯಿರಿ"
        PLEASE_CHAT_AND_AVOID_CALLS -> "ದಯವಿಟ್ಟು ಚಾಟ್‌ ಮಾಡಿ ಕರೆಗಳನ್ನು ತಡೆಹಿಡಿಯಿರಿ"
        PLEASE_GO_TO_EXACT_PICKUP -> "ದಯವಿಟ್ಟು ಪಿಕಪ್ ಸ್ಥಳಕ್ಕೆ ಹೋಗಿ"
        CUSTOMER_HAS_POOR_VISION_SOUND_HORN_AT_PICKUP -> "ಗ್ರಾಹಕನಲ್ಲಿ ಕಡಿಮೆ ದೃಷ್ಟಿ ಇದೆ. ಪಿಕಪ್ ಗೆ ಬಂದು ಹಾರ್ನ್ ಮಾಡಿ."
        CUSTOMER_HAS_POOR_HEARING_MESSAGE_THEM_AT_PICKUP -> "ರೈಡರಿಗೆ ಕಡಿಮೆ ಕೇಳಿಸುತ್ತದೆ . ಪಿಕಪ್ ನಲ್ಲಿ ಅವರಿಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ."
        CUSTOMER_HAS_LOW_MOBILITY_STORE_THEIR_SUPPORT_AT_PICKUP -> "ಗ್ರಾಹಕನಲ್ಲಿ ಕಡಿಮೆ ಚಲನಶೀಲತೆ ಇದೆ. ಅವರಿಗೆ ಬೇಕಾದ ಬೆಂಬಲವನ್ನು ನೀಡಿ ಸಹಾಯಿಸಿ."
        CUSTOMER_HAS_DISABILITY_PLEASE_ASSIST_THEM -> "ಗ್ರಾಹಕನಲ್ಲಿ ಅಂಗವೈಕಲ್ಯ ಇದೆ. ಅವರಿಗೆ ಸಹಾಯ ಮಾಡಿ."
        CUSTOMER_MAY_NEED_ASSISTANCE -> "ಗ್ರಾಹಕನಿಗೆ ಸಹಾಯ ಬೇಕಾಗಬಹುದು"
        LEARN_MORE -> "ಇನ್ನಷ್ಟು ಕಲಿಯಿರಿ"
        CUSTOMER_HAS_LOW_MOBILITY_GO_TO_EXACT_LOC -> "ಗ್ರಾಹಕನಲ್ಲಿ ಕಡಿಮೆ ಚಲನಶೀಲತೆ ಇದೆ. ಖಚಿತ ಪಿಕಪ್ ಸ್ಥಳಕ್ಕೆ ಹೋಗಿ."
        CUSTOMER_HAS_POOR_HEARING_CHAT_WITH_THEM_INSTEAD_OF_CALLING -> "ರೈಡರಿಗೆ ಕಡಿಮೆ ಕೇಳಿಸುವ ಶಕ್ತಿ ಇದೆ. ಅವರಿಗೆ ಕರೆ ಬದಲಾಗಿ ಚಾಟ್ ಮಾಡಿ."
        CUSTOMER_HAS_LOW_VISION_CALL_THEM_INSTEAD_OF_CHATTING -> "ಗ್ರಾಹಕನಲ್ಲಿ ಕಡಿಮೆ ದೃಷ್ಟಿ ಇದೆ. ಅವರಿಗೆ ಚಾಟ್ ಮಾಡುವ ಬದಲಾಗಿ ಅವರಿಗೆ ಕರೆ ಮಾಡಿ."
        PLEASE_HELP_THEM_AS_YOU_CAN -> "ನೀವು ಸಹಾಯ ಮಾಡಬಹುದಾದ ರೀತಿಯಲ್ಲಿ ಅವರಿಗೆ ಸಹಾಯ ಮಾಡಿ"
        LEARN_HOW_YOU_CAN_HELP_CUSTOMERS_REQUIRING_SPECIAL_ASSISTANCE -> "ವಿಶೇಷ ಸಹಾಯದ ಅಗತ್ಯವಿರುವ ಗ್ರಾಹಕರಿಗೆ ನೀವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು ಎಂಬುದನ್ನು ತಿಳಿಯಿರಿ"
        ASSISTANCE_REQUIRED ->  "ನೆರವು ಅಗತ್ಯವಿದೆ"
        SAVED_DUE_TO_ZERO_COMMISSION ->  "ಶೂನ್ಯ ಆಯೋಗದ\nಕಾರಣ ಉಳಿಸಲಾಗಿದೆ"
        TIP_EARNED_FROM_CUSTOMER ->  "ಗ್ರಾಹಕರಿಂದ ಗಳಿಸಿದ\nಸಲಹೆ"
        COLLECT_VIA_CASE_UPI ->  "ನಗದು/UPI ಮೂಲಕ ಸಂಗ್ರಹಿಸಿ"
        FARE_COLLECTED ->   "ಶುಲ್ಕ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ"
        RATE_YOUR_RIDE_WITH1 ->  "" 
        RATE_YOUR_RIDE_WITH2 ->  "ಯೊಂದಿಗೆ ನಿಮ್ಮ ಸವಾರಿಯನ್ನು ರೇಟ್ ಮಾಡಿ"
        HELP_US_WITH_YOUR_FEEDBACK ->  "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯೊಂದಿಗೆ ನಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ (ಐಚ್ಛಿಕ)"
        COLLECT_CASH ->  "ನಗದು ಸಂಗ್ರಹಿಸಿ"
        ONLINE_PAYMENT ->  "ಆನ್ಲೈನ್ ಪಾವತಿ"
        RIDE_COMPLETED ->  "ಸವಾರಿ ಪೂರ್ಣಗೊಂಡಿದೆ"
        SUBMIT_FEEDBACK ->  "ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಸಲ್ಲಿಸಿ"
        BADGE_EARNED ->  "ಬ್ಯಾಡ್ಜ್ ಗಳಿಸಲಾಗಿದೆ"
        PURPLE_RIDE_CHAMPION ->  "ಪರ್ಪಲ್ ರೈಡ್ ಚಾಂಪಿಯನ್"
        PURPLE_RIDE ->  "ಪರ್ಪಲ್ ರೈಡ್"
        PROCEED_TO_CHAT ->  "ಚಾಟ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿರಿ"
        PLEASE_CONSIDER_CALLING_THEM ->  "ಅವರು ಚಾಟ್‌ಗಳನ್ನು ಓದಲು ಸಾಧ್ಯವಾಗದೇ ಇರಬಹುದು. ದಯವಿಟ್ಟು ಅವರಿಗೆ ಕರೆ ಮಾಡಲು ಪರಿಗಣಿಸಿ"
        JOIN_A_PLAN_TO_START_EARNING ->  "ಗಳಿಕೆಯನ್ನು ಪ್ರಾರಂಭಿಸಲು ಯೋಜನೆಗೆ ಸೇರಿ!"
        GO_ONLINE_PROMPT_SUBSCRIBE ->  "ನೀವು ಪ್ರಸ್ತುತ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ.\nಸವಾರಿ ಮಾಡಲು ಯೋಜನೆಗೆ ಸೇರಿಕೊಳ್ಳಿ"
        GO_ONLINE_PROMPT_PAYMENT_PENDING ->  "ನೀವು ಪ್ರಸ್ತುತ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿರುವಿರಿ.\nರೈಡ್‌ಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ನಿಮ್ಮ ಪಾವತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ"
        COMPLETE_PAYMENT_TO_CONTINUE _ ->  "ಯಾತ್ರಿ ಸತಿ ಬಳಸುವುದನ್ನು ಮುಂದುವರಿಸಲು, ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಾವತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ"
        PENDING_CAPS ->  "ಬಾಕಿ"
        FAILURE ->  "ವೈಫಲ್ಯ"
        PAYMENT_MODE ->  "ಪಾವತಿ ಮೋಡ್"
        TXN_ID ->  "ಆರ್ಡರ್ ಐಡಿ"
        AMOUNT_PAID ->  "ಪಾವತಿಸಿದ ಮೊತ್ತ"
        NOTIFICATION_SCHEDULED ->  "ಅಧಿಸೂಚನೆಯನ್ನು ನಿಗದಿಪಡಿಸಲಾಗಿದೆ!"
        MANUAL_DUES ->  "ಮ್ಯಾನುವಲ್ ಬಾಕಿಗಳು"
        AUTOPAY_IN_PROGRESS ->  "ಸ್ವಯಂ ಪಾವತಿ ಪ್ರಗತಿಯಲ್ಲಿದೆ"
        MANUAL_DUE_OVERVIEW ->  "ಮ್ಯಾನುವಲ್ ಬಾಕಿ ಅವಲೋಕನ"
        AUTOPAY_DUE_OVERVIEW ->  "ಸ್ವಯಂ ಪಾವತಿ ಬಾಕಿ ಅವಲೋಕನ"
        MANUAL_DUE_AS_AUTOPAY_EXECUTION_FAILED ->  "ಹಸ್ತಚಾಲಿತ ಕಾರಣ ಸ್ವಯಂ ಪಾವತಿ ಕಾರ್ಯಗತಗೊಳಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ"
        CLEAR_MANUAL_DUES ->  "ಮ್ಯಾನುವಲ್ ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ"
        DUE_OVERVIEW ->  "ಡ್ಯೂ ಅವಲೋಕನ"
        MANUAL_DUE_DETAILS ->  "ಮ್ಯಾನುವಲ್ ಬಾಕಿ ವಿವರಗಳು"
        AUTOPAY_DUE_DETAILS ->  "ಸ್ವಯಂ ಪಾವತಿ ಬಾಕಿ ವಿವರಗಳು"
        SWITCHED_TO_MANUAL ->  "*ಪಾವತಿ ಮೋಡ್ ಅನ್ನು ಮ್ಯಾನುವಲ್ ಗೆ ಬದಲಾಯಿಸಲಾಗಿದೆ ಏಕೆಂದರೆ ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಪೂರೈಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ"
        SPLIT_PAYMENT ->  "*ಪಾವತಿಯನ್ನು ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಕಾರ್ಯಗತಗೊಳಿಸಲು ವಿಭಜಿಸಲಾಗಿದೆ"
        GST_INCLUDE ->  "(18% GST ಸೇರಿದಂತೆ)"
        SCHEDULED_AT ->  "ನಿಗದಿಪಡಿಸಲಾಗಿದೆ"
        PAYMENT_STATUS ->  "ಪಾವತಿ ಸ್ಥಿತಿ"
        NOTIFICATION_ATTEMPTING ->  "ಅಧಿಸೂಚನೆ ಪ್ರಯತ್ನ"
        EXECUTION_SCHEDULED ->  "ಎಕ್ಸಿಕ್ಯೂಶನ್ ಶೆಡ್ಯೂಲ್"
        EXECUTION_ATTEMPTING ->  "ಎಕ್ಸಿಕ್ಯೂಶನ್ ಪ್ರಯತ್ನ"
        EXECUTION_SUCCESS ->  "ಕಾರ್ಯನಿರ್ವಹಣೆಯ ಯಶಸ್ಸು"
        SCHEDULED ->  "ಶೆಡ್ಯೂಲ್ಡ್"
        ONE_TIME_SETTLEMENT ->  "ಒಂದೇ ಬಾರಿಗೆ ಪಾವತಿ ಮಾಡಿ"
        PAYMENT_SCHEDULED ->  "ಪಾವತಿಯನ್ನು ನಿಗದಿಪಡಿಸಲಾಗಿದೆ"
        VIEW_DETAILS ->  "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ"
        RETRY_AUTOPAY ->  "ಸ್ವಯಂಪಾವತಿಯನ್ನು ಮರುಪ್ರಯತ್ನಿಸಿ"
        RETRY_STR ->  "ಮರುಪ್ರಯತ್ನಿಸಿ"
        ONGOING_PAYMENT_EXECUTION ->  "ಹಸ್ತಚಾಲಿತ ಪಾವತಿ ನಡೆಯುತ್ತಿದೆ ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ"
        OFFER_CARD_BANNER_TITLE _ ->  "ಆಟೋಪೆ ಸೆಟಪ್ ಮಾಡಿ ಮತ್ತು {} ರವರೆಗೆ ₹15/ದಿನ ಮಾತ್ರ ಪಾವತಿಸಿ"
        OFFER_CARD_BANNER_DESC ->  "ಆಟೋಪೆಯನ್ನು ಸೆಪ್ಟೆಂ 25 ರೊಳಗೆ ಹೊಂದಿಸಿದರೆ ಮಾತ್"
        OFFER_CARD_BANNER_ALERT ->  "ನಿಮ್ಮ ಆಟೋಪೆ ಸೆಟಪ್ ಬಾಕಿಯಿದೆ!"
        OR ->  "ಅಥವಾ"
        COLLECT_CASH_DIRECTLY ->  "ನೇರವಾಗಿ ಹಣವನ್ನು ಸಂಗ್ರಹಿಸಿ"
        OR_COLLECT_CASH_DIRECTLY ->  "ಅಥವಾ ನೇರವಾಗಿ ಹಣವನ್ನು ಸಂಗ್ರಹಿಸಿ"
        SETUP_AUTOPAY_TO_ACCEPT_PAYMENT ->  "ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ನೇರವಾಗಿ ಪಾವತಿಗಳನ್ನು ಸ್ವೀಕರಿಸಲು, ನಿಮ್ಮ ಯೋಜನೆಯಲ್ಲಿ ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಸೆಟಪ್ ಮಾಡಿ"
        DOWNLOAD_QR ->  "QR ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ"
        USE_THIS_QR_TO_COLLECT_PAYMENT ->  "ಸವಾರಿ ಮುಗಿದ ನಂತರ ಪಾವತಿಯನ್ನು ಸಂಗ್ರಹಿಸಲು ನೀವು ಈ QR ಕೋಡ್ ಅನ್ನು ಬಳಸಬಹುದು."
        AMOUNT_WILL_DEPOSITED_TO_BANK_ACCOUNT ->  "ನೀವು UPI ಸ್ವಯಂ ಪಾವತಿಗಾಗಿ ಬಳಸುತ್ತಿರುವ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಮೊತ್ತವನ್ನು ಠೇವಣಿ ಮಾಡಲಾಗುತ್ತದೆ"
        GET_DIRECTLY_TO_YOUR_BANK_ACCOUNT ->  "UPI ಐಡಿಗೆ ನೇರ ಪಾವತಿಯನ್ನು ಪಡೆಯಿರಿ"
        PAYMENT ->  "ಪಾವತಿ"
        QR_CODE ->  "QR ಕೋಡ್"
        GET_QR_CODE ->  "QR ಕೋಡ್ ಪಡೆಯಿರಿ"
        EXECUTION_FAILED ->  "ಎಕ್ಸಿಕ್ಯೂಶನ್ ವಿಫಲವಾಗಿದೆ"
        NOTIFICATION_FAILED ->  "ಅಧಿಸೂಚನೆ ವಿಫಲವಾಗಿದೆ"
        PAY_NOW ->  "ಈಗ ಪಾವತಿಸಿ"
        CLEAR_DUES_BANNER_TITLE ->  "ತಡೆರಹಿತ ರೈಡ್‌ಗಳನ್ನು ಆನಂದಿಸಲು ನಿಮ್ಮ ಬಾಕಿಯನ್ನು (₹{}) ತೆರವುಗೊಳಿಸಿ"
        COLLECT_VIA_UPI_QR_OR_CASH ->  "UPI QR ಅಥವಾ ನಗದು ಮೂಲಕ ಸಂಗ್ರಹಿಸಿ"
        TRANSACTION_DEBITED_ON ->  "ವ್ಯವಹಾರ ಡೆಬಿಟ್ ಮಾಡಲಾಗಿದೆ"
        TRANSACTION_ATTEMPTED_ON ->  "ವಹಿವಾಟು ಪ್ರಯತ್ನಿಸಲಾಗಿದೆ"
        AUTOPAY_SETUP_AND_PAYMENT_SUCCESSFUL ->  "ಸ್ವಯಂ ಪಾವತಿ ಸೆಟಪ್ ಮತ್ತು ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ!"
        AUTOPAY_SETUP_SUCCESSFUL ->  "ಸ್ವಯಂ ಪಾವತಿ ಸೆಟಪ್ ಯಶಸ್ವಿಯಾಗಿದೆ!"
        AUTOPAY_SETUP_AND_PAYMENT_PENDING ->  "ಸ್ವಯಂ ಪಾವತಿ ಸೆಟಪ್ ಮತ್ತು ಪಾವತಿ ಬಾಕಿಯಿದೆ!"
        AUTOPAY_SETUP_PENDING ->  "ಸ್ವಯಂ ಪಾವತಿ ಸೆಟಪ್ ಬಾಕಿಯಿದೆ!"
        AUTOPAY_SETUP_AND_PAYMENT_FAILED ->  "ಸ್ವಯಂ ಪಾವತಿ ಸೆಟಪ್ ಮತ್ತು ಪಾವತಿ ವಿಫಲವಾಗಿದೆ!"
        AUTOPAY_SETUP_FAILED ->  "ಸ್ವಯಂ ಪಾವತಿ ಸೆಟಪ್ ವಿಫಲವಾಗಿದೆ!"
        ONE_TIME_REGISTERATION ->  "ಒಂದು ಬಾರಿ ನೋಂದಣಿ"
        CLEARANCE_AND_REGISTERATION ->  "ತೆರವು + ನೋಂದಣಿ"
        UPI_AUTOPAY_SETUP ->  "UPI ಸ್ವಯಂ ಪಾವತಿ ಸೆಟಪ್"
        WATCH_VIDEO_FOR_HELP ->  "ಸಹಾಯಕ್ಕಾಗಿ ವೀಡಿಯೊ ನೋಡಿ"
        PAYMENT_PENDING_SOFT_NUDGE ->  "ಮಿತಿಯನ್ನು ಶೀಘ್ರದಲ್ಲೇ ತಲುಪಲಾಗುವುದು.ತಡೆರಹಿತ ಸವಾರಿಗಳನ್ನು ಆನಂದಿಸಲು ಬಾಕಿ ತೆರವುಗೊಳಿಸಿ"
        CLEAR_YOUR_DUES_EARLY ->  "ನಿಮ್ಮ ಬಾಕಿಗಳನ್ನು ಮುಂಚಿತವಾಗಿ ತೆರವುಗೊಳಿಸಿ"
        DUE_LIMIT_WARNING_BANNER_TITLE ->  "ನಿಮ್ಮ ಬಾಕಿಯ ಮಿತಿ ಶೀಘ್ರದಲ್ಲೇ ₹{} ಕ್ಕೆ ತಲುಪಲಿದೆ."
        SCHEDULED_ON ->  "ಕಡಿತ ದಿನಾಂಕ"
        ATTEMPTED_ON ->  "ಪ್ರಯತ್ನದ ದಿನಾಂಕ"
        DEBITED_ON ->  "ಡೆಬಿಟ್ ದಿನಾಂಕ"
        FREE_TRIAL_ENDING_IN_2_DAYS -> "ಫ್ರೀ ಅವಧಿಯು 2 ದಿನಗಳಲ್ಲಿ ಕೊನೆಗೊಳ್ಳುತ್ತದೆ!"
        FREE_TRIAL_ENDING_TOMORROW ->  "ಫ್ರೀ ಅವಧಿಯು ನಾಳೆ ಕೊನೆಗೊಳ್ಳಲಿದೆ!"
        FREE_TRIAL_ENDS_TONIGHT ->  "ಫ್ರೀ ಅವಧಿಯು ಇಂದು ರಾತ್ರಿ ಕೊನೆಗೊಳ್ಳುತ್ತದೆ!"
        JOIN_A_PLAN_TO_CONTINUE_TAKING_RIDES ->  "ಸವಾರಿಗಳನ್ನು ಮುಂದುವರಿಸಲು ಯೋಜನೆಗೆ ಸೇರಿಕೊಳ್ಳಿ"
        SETUP_AUTOPAY_FOR_EASY_PAYMENTS ->  "ಸುಲಭ ಪಾವತಿಗಳಿಗಾಗಿ ಸ್ವಯಂ ಪಾವತಿಯನ್ನು ಸೆಟಪ್ ಮಾಡಿ"
        LOW_DUES_CLEAR_POPUP_DESC ->  "ತಡೆರಹಿತ ಸವಾರಿಗಳನ್ನು ಆನಂದಿಸಲು ಈಗ ನಿಮ್ಮ ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ"
        DUES_PENDING ->  "⚠️ ಪಾವತಿ ಬಾಕಿ ಇದೆ! ⚠️"
        DAYS ->  "ದಿನಗಳು"
        ACTIVE_PLAN ->  "ಸಕ್ರಿಯ ಯೋಜನೆ"
        DOWNGRADE_AVAILABLE_ONLY_FOR_AC_VEHICLES ->  "ವಾಹನ ಅಪಗ್ರೇಡ್ ಆಯ್ಕೆ ಕೇವಲ ಏಸಿ ವಾಹನಗಳಿಗೆ ಮಾತ್ರ ಲಭ್ಯವಿದೆ"
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_1 ->  "ನಿಮ್ಮ ವಾಹನವನ್ನು ಡೌನ್‌ಗ್ರೇಡ್ ಮಾಡುವುದರಿಂದ "
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_2 ->  "ಸವಾರಿಗಳು ಮತ್ತು"
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_3 ->  " ರೈಡ್‌ಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ನಿಮಗೆ ಅನುಮತಿಸುತ್ತದೆ"
        AC_CAB ->  "ಎಸಿ ಕ್ಯಾಬ್"
        AC_SUV ->  "ಎಸಿ ಎಸ್ಯುವಿ"
        DOWNGRADE_VEHICLE ->  "ಡೌನ್‌ಗ್ರೇಡ್ ವಾಹನ"
        WHAT_ARE_PURPLE_RIDES ->  "ಪರ್ಪಲ್ ರೈಡ್ಸ್ ಎಂದರೇನು?"
        ECONOMICAL ->  "ಆರ್ಥಿಕ"
        SPACIOUS ->  "ವಿಶಾಲವಾದ"
        COMFY ->  "ಆರಾಮದಾಯಕ"
        PEOPLE ->  "ಜನರು"
        GO_TO ->  "ಗೋ-ಟು"
        SELECT_ON_MAP ->  "ನಕ್ಷೆಯಲ್ಲಿ ಆಯ್ಕೆಮಾಡಿ"
        CONFIRM_LOCATION_STR ->  "ಸ್ಥಳವನ್ನು ದೃಢೀಕರಿಸಿ"
        SAVE_LOCATION_STR ->  "ಸ್ಥಳವನ್ನು ಉಳಿಸಿ"
        REMOVE_PREF_LOC ->  "ಆದ್ಯತೆಯ ಸ್ಥಳವನ್ನು ತೆಗೆದುಹಾಕುವುದೇ"
        CONF_REMOVE_PREF_LOC ->  "ನೀವು ಆದ್ಯತೆಯ ಸ್ಥಳವನ್ನು ತೆಗೆದುಹಾಕಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?"
        YES_REMOVE ->  "ಹೌದು, ತೆಗೆದುಹಾಕಿ"
        ADD_LOCATION ->  "ಸ್ಥಳವನ್ನು ಸೇರಿಸಿ"
        ADD_ANOTHER_LOCATION ->  "ಮತ್ತೊಂದು ಸ್ಥಳವನ್ನು ಸೇರಿಸಿ"
        ADD_A_GOTO_LOC ->  "ಹೋಗಲು ಸ್ಥಳವನ್ನು ಸೇರಿಸಿ"
        GOTO_LOC_LEFT ->  "ಉಳಿದಿರುವ ಗೋ-ಟು ಸ್ಥಳಗಳು:"
        CURRENT_LOCATION ->  "ಪ್ರಸ್ತುತ ಸ್ಥಳ"
        CONF_GOTO_LOC ->  "ಸ್ಥಳಕ್ಕೆ ಹೋಗುವುದನ್ನು ದೃಢೀಕರಿಸಿ"
        GOTO_LOCS ->  "ಸ್ಥಳಗಳಿಗೆ ಹೋಗಿ"
        LOCATION_STR ->  "ಸ್ಥಳ"
        ADD_TAG ->  "ಟ್ಯಾಗ್ ಸೇರಿಸಿ"
        ONLY_ONE_LOC_CAN_ADDED ->  "(ಒಂದು ಸ್ಥಳ ಮಾತ್ರ ಈ ಟ್ಯಾಗ್ ಅನ್ನು ಹೊಂದಬಹುದು)"
        SAVE_AS ->  "ಹೀಗೆ ಉಳಿಸಿ"
        NO_GOTO_LOC_ADDED ->  "ಇನ್ನೂ ಯಾವುದೇ ಗೋ-ಟು ಸ್ಥಳವನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ"
        GOTO_LOC_HELPS_YOU ->  "ಗೋ-ಟು ಸ್ಥಳಗಳು ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಸ್ಥಳಗಳಲ್ಲಿ ಮತ್ತು ಸುತ್ತಮುತ್ತ ಸವಾರಿಗಳನ್ನು ಹುಡುಕಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ"
        YOU_ARE_VERY_CLOSE -> "ನೀವು “ಗೋ-ಟು” ಸ್ಥಳಕ್ಕೆ ಬಹಳ ಸಮೀಪದಲ್ಲಿರುವಿರಿ"
        GOTO_IS_APPLICABLE_FOR ->  "“ಗೋ-ಟು” ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳದಿಂದ ಕನಿಷ್ಠ 3 ಕಿಮೀ ದೂರದಲ್ಲಿರುವ \n ಸ್ಥಳಗಳಿಗೆ ಅನ್ವಯಿಸುತ್ತದೆ \n."
        GOTO_MAYBE_REDUCED ->  "“ಗೋ-ಟು” ಕಡಿಮೆಯಾಗಬಹುದು"
        CANCEL_OF_GOTO ->  "“ಗೋ-ಟು” ರೈಡ್ ಅನ್ನು ರದ್ದುಗೊಳಿಸುವುದರಿಂದ ನಿಮ್ಮ “ಗೋ-ಟು” ಆಯ್ಕೆಗಳನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ! "
        MORE_GOTO_RIDE_COMING ->  "ಇನ್ನಷ್ಟು “ಗೋ-ಟು” ರೈಡ್‌ಗಳು ಬರಲಿವೆ!"
        MORE_GOTO_RIDE_COMING_DESC ->  "ದಯವಿಟ್ಟು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿರಿ; ನಿಮ್ಮ “ಗೋ-ಟು” ಸ್ಥಳಕ್ಕಾಗಿ ನಾವು ಹೆಚ್ಚಿನ ಸವಾರಿ ವಿನಂತಿಗಳನ್ನು ಸ್ವೀಕರಿಸುತ್ತಿದ್ದೇವೆ"
        GOTO_REDUCED_TO_ZERO ->  " “ಗೋ-ಟು” ಅನ್ನು ಶೂನ್ಯಕ್ಕೆ ಇಳಿಸಲಾಗಿದೆ"
        DUE_TO_MULTIPLE_CANCELLATIONS ->  "ಅನೇಕ ರದ್ದತಿಗಳ ಕಾರಣದಿಂದಾಗಿ, ಎಣಿಕೆಯನ್ನು ಮೊಟಕುಗೊಳಿಸಲಾಗಿದೆ"
        OK_GOT_IT ->  "ಸರಿ, ಅರ್ಥವಾಯಿತು"
        GOTO_REDUCED_TO ->  "“ಗೋ-ಟು” ಅನ್ನು ಕಡಿಮೆ ಮಾಡಲಾಗಿದೆ"
        VALIDITY_EXPIRED_DESC ->  "ನಿಮ್ಮ 30 ನಿಮಿಷಗಳ ಮಾನ್ಯತೆಯ ಅವಧಿ ಮುಗಿದಿದೆ. ಈ ಸಮಯದಲ್ಲಿ ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಪೂರೈಸಲು ನಮಗೆ ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ."
        KNOW_MORE ->  "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ"
        THIS_FEATURE_WILL_BE_APPLICABLE -> "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳದಿಂದ ಕನಿಷ್ಠ 3 ಕಿಮೀ ದೂರದಲ್ಲಿರುವಾಗ ಈ ವೈಶಿಷ್ಟ್ಯವು ಅನ್ವಯಿಸುತ್ತದೆ.\n\nಸಕ್ರಿಯಗೊಳಿಸಿದಾಗ ಸ್ಥಳ ಪ್ರಾಶಸ್ತ್ಯಗಳು ಕೇವಲ 30 ನಿಮಿಷಗಳವರೆಗೆ ಮಾನ್ಯವಾಗಿರುತ್ತವೆ."
        GOTO_LOC_ADDED ->  "ಸ್ಥಳಕ್ಕೆ ಹೋಗುವುದನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ"
        GOTO_LOC_REMOVED ->  "ಗೋ-ಟು ಸ್ಥಳವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ತೆಗೆದುಹಾಕಲಾಗಿದೆ"
        GOTO_LOC_UPDATED ->  "“ಗೋ-ಟು” ನ ಸ್ಥಳವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ"
        GOTO_LOC_IS_ENABLED ->  "“ಗೋ-ಟು” ಸ್ಥಳವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ"
        GOTO_LOC_IS_DISABLED ->  "“ಗೋ-ಟು” ಅನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ"
        GOTO_LOCATIONS ->  "ಗೋ-ಟು ಸ್ಥಳ"
        CHOOSE_A_GOTO_LOC ->  "ಗಮ್ಯಸ್ಥಾನವನ್ನು ಆರಿಸಿ"
        YOU_HAVE_ONLY_LEFT_FOR_TODAY ->  "ನೀವು ಇಂದಿಗೆ ಮಾತ್ರ ಹೊರಟಿದ್ದೀರಿ"
        YES_ENABLE ->  "ಹೌದು, ಸಕ್ರಿಯಗೊಳಿಸಿ"
        NO_GOTO_LOCS_ADDED_YET ->  "ಯಾವುದೇ “ಗೋ-ಟು” ಸ್ಥಳಗಳನ್ನು ಇನ್ನೂ ಸೇರಿಸಲಾಗಿಲ್ಲ"
        NO_GOTO_LOCS_ADDED_YET_DESC ->  "“ಗೋ-ಟು” ಸ್ಥಳಗಳು ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಸ್ಥಳಗಳಲ್ಲಿ ಮತ್ತು ಸುತ್ತಮುತ್ತ ಸವಾರಿಗಳನ್ನು ಹುಡುಕಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ"
        ENABLE_GOTO ->  "ಗೋ-ಟು ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ"
        GO_TO_CANCELLATION_TITLE ->  "“ಗೋ-ಟು” ಕಡಿಮೆಯಾಗಬಹುದು"
        GO_TO_CANCELLATION_DESC ->  "“ಗೋ-ಟು” ರೈಡ್ ಅನ್ನು ರದ್ದುಗೊಳಿಸುವುದರಿಂದ ನಿಮಗಾಗಿ “ಗೋ-ಟು” ಆಯ್ಕೆಗಳನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ!"
        REPORT_ISSUE ->  "ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ"
        YOU_ARE_ALMOST_AT_LOCATION ->  "ನೀವು ಬಹುತೇಕ ಗೋ-ಟು ಸ್ಥಳ ತಲುಪಿದ್ದೀರಿ."
        DRIVER_HOME_LOCATION_NOT_FOUND ->  "ಸ್ಥಳ ಕಂಡುಬಂದಿಲ್ಲ"
        DRIVER_HOME_LOCATION_DOES_NOT_EXIST ->  "ಸ್ಥಳ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ"
        DRIVER_HOME_LOCATION_LIMIT_REACHED ->  "ಸ್ಥಳ ಮಿತಿಯನ್ನು ತಲುಪಿದೆ"
        DRIVER_GO_HOME_REQUEST_NOT_FOUND ->  "ವಿನಂತಿ ಕಂಡುಬಂದಿಲ್ಲ"
        DRIVER_GO_HOME_REQUEST_DOES_NOT_EXIST ->  "ವಿನಂತಿಯು ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ"
        DRIVER_GO_HOME_REQUEST_DAILY_USAGE_LIMIT_REACHED ->  "ದೈನಂದಿನ ಬಳಕೆಯ ಮಿತಿಯನ್ನು ತಲುಪಿದೆ"
        DRIVER_GO_HOME_REQUEST_ALREADY_ACTIVE ->  "ಈಗಾಗಲೇ ಸಕ್ರಿಯವಾಗಿದೆ"
        DRIVER_HOME_LOCATION_OUTSIDE_SERVICE_AREA ->  "ಸ್ಥಳವು ಸೇವಾ ಪ್ರದೇಶದ ಹೊರಗಿದೆ"
        NEW_LOCATION_TOO_CLOSE_TO_PREVIOUS_HOME_LOCATION ->  "ಸ್ಥಳವು ಹಿಂದಿನ ಸ್ಥಳಕ್ಕೆ ತುಂಬಾ ಹತ್ತಿರದಲ್ಲಿದೆ"
        DRIVER_HOME_LOCATION_DOES_NOT_BELONG_TO_DRIVER ->  "ಸ್ಥಳವು ನಿಮಗೆ ಸೇರಿದ್ದಲ್ಲ"
        DRIVER_HOME_LOCATION_DELETE_WHILE_ACTIVE_ERROR ->  "ಸಕ್ರಿಯವಾಗಿರುವಾಗ ಸ್ಥಳವನ್ನು ಅಳಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ"
        DISABLE_GOTO_STR ->  "ಗೋ-ಟು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸುವುದೇ?"
        YOU_STILL_HAVE_TIME_LEFT ->  "ನಿಮ್ಮ “ಗೋ-ಟು” ವಿನಂತಿಯಲ್ಲಿ ಇನ್ನೂ ಸಮಯ ಉಳಿದಿದೆ"
        YES_DISABLE ->  "ಹೌದು, ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ"
        DRAG_TO_ADJUST ->  "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹೊಂದಿಸಲು ಎಳೆಯಿರಿ"
        LOCATION_ALREADY_EXISTS ->  "ಸ್ಥಳ ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ"
        MIN_LEFT ->  "ನಿಮಿಷ ಬಾಕಿ"
        GOTO_LOC_REACHED ->  "“ಗೋ-ಟು” ಸ್ಥಳವನ್ನು ತಲುಪಿದೆ!"
        GET_READY_FOR_YS_SUBSCRIPTION _ ->  "ಯಾತ್ರಿ ಸತಿ ಯೋಜನೆಗಳಿಗೆ ಸಿದ್ಧರಾಗಿ!"
        SIGNUP_EARLY_FOR_SPECIAL_OFFERS ->  "ವಿಶೇಷ ಕೊಡುಗೆಗಳಿಗಾಗಿ ಮುಂಚಿತವಾಗಿ ಸೈನ್ ಅಪ್ ಮಾಡಿ"
        GUARANTEED_FIXED_PRICE _ ->  "ಜನವರಿ 1, 2025 ರವರೆಗೆ ಖಾತರಿಪಡಿಸಿದ ಸ್ಥಿರ ಬೆಲೆ"
        INTRODUCTORY_OFFER_TO_BE_ANNOUNCED_SOON ->  "ಪರಿಚಯಾತ್ಮಕ ಕೊಡುಗೆಯನ್ನು ಶೀಘ್ರದಲ್ಲೇ ಪ್ರಕಟಿಸಲಾಗುವುದು!"
        NO_CHARGES_TILL ->  "ಡಿಸೆಂಬರ್ 31 ರವರೆಗೆ ಯಾವುದೇ ಶುಲ್ಕಗಳಿಲ್ಲ"
        AND -> " ಮತ್ತು "
        DIRECT_PAYMENT_NO_COMMISSIONS -> "ನೇರ ಪಾವತಿ.\nಯಾವುದೇ ಆಯೋಗಗಳು"
        CUSTOMER_PAYS_DIRECTLY -> "ಗ್ರಾಹಕರು ನಿಮಗೆ ನೇರವಾಗಿ \nನಗದು ಅಥವಾ UPI ಮೂಲಕ ಪಾವತಿಸುತ್ತಾರೆ"
        HUNDRED_PERCENT_FARE_GOES_TO_YOU -> "100% ದರವು ನಿಮಗೆ ಹೋಗುತ್ತದೆ!"
        FARE_SHOWN_IS_FARE_YOU_GET -> "ತೋರಿಸಿರುವ ದರವು ನೀವು ಪಡೆಯುವ ದರವಾಗಿದೆ.\nಯಾವುದೇ ಗುಪ್ತ ಶುಲ್ಕಗಳಿಲ್ಲ."
        BE_A_PART_OF_OPEN_MOBILITY_REVOLUTION -> "ಮುಕ್ತ\nಮೊಬಿಲಿಟಿ ಕ್ರಾಂತಿಯ ಭಾಗವಾಗಿರಿ!"
        OUR_DATA_AND_PRODUCT_ARE_TRANSPARENT -> "ನಮ್ಮ ಡೇಟಾ ಮತ್ತು ಉತ್ಪನ್ನದ ಮಾರ್ಗಸೂಚಿ\nಎಲ್ಲರಿಗೂ ಪಾರದರ್ಶಕವಾಗಿದೆ."
        ENABLE_LOCATION_PERMISSION -> "ಸ್ಥಳ ಅನುಮತಿಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ"
        PLEASE_ENABLE_LOCATION_PERMISSION_FOR -> "ದಯವಿಟ್ಟು ಇದಕ್ಕಾಗಿ ಸರಿಯಾದ ಜಾಗವನ್ನು ಪಡೆಯಿರಿ"
        ENABLE_LOCATION -> "ಸ್ಥಳವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ"
        YOUR_DETECTED_LOCATION_IS -> "ನಿಮ್ಮ ಪತ್ತೆಯಾದ ಸ್ಥಳ"
        LANGUAGE_DETECTED -> "ಭಾಷೆ ಪತ್ತೆಯಾಗಿದೆ"
        CHANGE_LANGUAGE_STR -> "ಭಾಷೆ ಬದಲಾಯಿಸಿ"
        SELECT_LOCATION -> "ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        SELECT_LOCATION_DESC -> "ನೀವು ಸವಾರಿ ಮಾಡಲು ಬಯಸುವ ಸ್ಥಳ"
        SELECT_LANGUAGE_DESC -> "ನೀವು ಓದಬಹುದಾದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        CONFIRM_LANGUAGE -> "ಭಾಷೆಯನ್ನು ದೃಢೀಕರಿಸಿ"
        GET_STARTED -> "ಪ್ರಾರಂಭಿಸಿ"
        ENTER_YOUR_MOBILE_NUMBER -> "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ"
        NOTIFICATION_ACCESS -> "ಅಧಿಸೂಚನೆ ಪ್ರವೇಶ"
        NOTIFICATION_ACCESS_DESC -> "ಶಿಫಾರಸು ಮಾಡಲಾಗುತ್ತದೆ, ನೀವು ಯಾವಾಗಲೂ ಸಂದೇಶಗಳನ್ನು ಮಿಸ್ ಮಾಡದಂತೆ ಮಾಡುತ್ತದೆ"
        WATCH_VIDEO -> "ವೀಡಿಯೊ ವೀಕ್ಷಿಸಿ"
        DL_VERIFICATION_FAILED -> "ಡಿಎಲ್ ಪರಿಶೀಲನೆ ವಿಫಲವಾಯಿತು. ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        RC_VERIFICATION_FAILED -> "ಆರ್ಸಿ ಪರಿಶೀಲನೆ ವಿಫಲವಾಯಿತು. ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        DL_UPLOAD_FAILED -> "ಡಿಎಲ್ ಅಪ್ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ"
        RC_UPLOAD_FAILED -> "ಆರ್ಸಿ ಅಪ್ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ"
        PLEASE_RETRY_THE_UPLOAD_AGAIN -> "ದಯವಿಟ್ಟು ಅಪ್ಲೋಡ್ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        RC_AND_DL_UPLOAD_FAILED -> "ಆರ್ಸಿ ಮತ್ತು ಡಿಎಲ್ ಅಪ್ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ"
        RC_UPLOAD_LIMIT_REACHED -> "ಆರ್ಸಿ ಅಪ್ಲೋಡ್ ಮಿತಿ ತಲುಪಿದೆ"
        DL_UPLOAD_LIMIT_REACHED -> "ಡಿಎಲ್ ಅಪ್ಲೋಡ್ ಮಿತಿ ತಲುಪಿದೆ"
        RETRY_UPLOAD -> "ಅಪ್ಲೋಡ್ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
        VEHICLE_REGISTERATON_CERTIFICATE -> "ವಾಹನ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ"
        GRANT_PERMISSIONS -> "ಅನುಮತಿಗಳನ್ನು ನೀಡಿ"
        SUBSCRIPTION_PLAN_STR -> "ಚಂಚಲೀಕರಣ ಯೋಜನೆ"
        COMPLETE_AUTOPAY_LATER -> "ನಂತರ 'ನನ್ನ ಯೋಜನೆ' ವಿಭಾಗದಿಂದ ಸ್ವಯಂಚಾಲಿತ ಪಾವತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ."
        START_EARNING_IN_FOUR_STEPS -> "{} ಸರಳ ಹಂತಗಳಿಂದ ಗಳಿಸಲು ಪ್ರಾರಂಭಿಸಿ"
        COMPLETE -> "ಪೂರ್ಣಗೊಳಿಸಿ"
        HOW_TO_UPLOAD -> "ಹೇಗೆ ಅಪ್ಲೋಡ್ ಮಾಡಬೇಕು"
        TAKE_CLEAR_PICTURE_DL -> "ಸಮತಲ ಸಾಮಗ್ರಿಯ ಮೇಲೆ ನಿಮ್ಮ ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್ ಯಾವಾಗಲೂ ಸ್ಪಷ್ಟ ಚಿತ್ರವನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ."
        ENSURE_ADEQUATE_LIGHT -> "ಬೆಳಕು ಸಾಕಷ್ಟು ಇದ್ದಿದ್ದರೆ ಮತ್ತು ಎಲ್ಲಾ ವಿವರಗಳು ಸ್ಪಷ್ಟವಾಗಿ ಕಾಣುತ್ತವೆಯೆಂದು ನಿಶ್ಚಯಿಸಿ"
        FIT_DL_CORRECTLY -> "ದಯವಿಟ್ಟು ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್ ಅನ್ನು ಕೆಳಗಿನ ಪ್ರದೇಶದಲ್ಲಿ ಸರಿಯಾಗಿ ಹೊಂದಿಸಿ"
        TAKE_PHOTO -> "ಫೋಟೊ ತೆಗೆ"
        FIT_RC_CORRECTLY -> "ದಯವಿಟ್ಟು ನೋಂದಣಿ ಸರ್ಟಿಫಿಕೇಟ್ ಅನ್ನು ಕೆಳಗಿನ ಪ್ರದೇಶದಲ್ಲಿ ಸರಿಯಾಗಿ ಹೊಂದಿಸಿ"
        TAKE_CLEAR_PICTURE_RC -> "ಸಮತಲ ಸಾಮಗ್ರಿಯ ಮೇಲೆ ನಿಮ್ಮ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರದ ಪುಟದ ಚಿತ್ರವನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ."
        DL_UPLOADED -> "ಡಿಎಲ್ ಅಪ್ಲೋಡ್ ಮಾಡಲಾಗಿದೆ"
        RC_UPLOADED -> "ಆರ್ಸಿ ಅಪ್ಲೋಡ್ ಮಾಡಲಾಗಿದೆ"
        DL_UPLOADING -> "ಡಿಎಲ್ ಅಪ್ಲೋಡ್ ಆಗುತ್ತಿದೆ"
        RC_UPLOADING -> "ಆರ್ಸಿ ಅಪ್ಲೋಡ್ ಆಗುತ್ತಿದೆ"
        RETAKE_RC -> "\nದಯವಿಟ್ಟು ನಿರ್ದಿಷ್ಟ ಪ್ರದೇಶದಲ್ಲಿ ರೆಜಿಸ್ಟ್ರೇಶನ್ ಸರ್ಟಿಫಿಕೇಟ್ ಜೊತೆ ಫೋಟೊವನ್ನು ಪುನಃ ತೆಗೆದುಕೊಳ್ಳಿ"
        RETAKE_DL -> "\nದಯವಿಟ್ಟು ನಿರ್ದಿಷ್ಟ ಪ್ರದೇಶದಲ್ಲಿ ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್ ಜೊತೆ ಫೋಟೊವನ್ನು ಪುನಃ ತೆಗೆದುಕೊಳ್ಳಿ"
        CONFIRM_AND_UPLOAD -> "ದೃಢೀಕರಿಸಿ ಮತ್ತು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ"
        RETAKE_PHOTO-> "ಫೋಟೊ ಪುನಃ ತೆಗೆದುಕೊಳ್ಳಿ"
        LETS_GET_YOU_TRIP_READY -> "ನಿಮ್ಮ ಪ್ರವಾಸವನ್ನು ಸಿದ್ಧಗೊಳಿಸೋಣ!"
        GOT_AN_OTP -> "ಒಟಿಪಿ ಸಿಕ್ಕಿತೇ?"
        DRIVING_LICENSE_DETAILS -> "ಚಾಲನಾ ಪರವಾನಗಿ ವಿವರಗಳು"
        VEHICLE_REGISTRATION_DETAILS -> "ವಾಹನ ನೋಂದಣಿ ವಿವರಗಳು"
        UPLOAD_PHOTO -> "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ"
        CLEAR_IMAGE -> "ಸ್ಪಷ್ಟ ಚಿತ್ರ"
        BLURRY_IMAGE -> "ಕೆಂಪು ಚಿತ್ರ"
        CROPPED_CORRECTLY -> "ಸರಿಯಾಗಿ ಕ್ರಾಪ್ ಮಾಡಲಾಗಿದೆ"
        WRONG_CROPPING -> "ತಪ್ಪಾಗಿ ಕ್ರಾಪ್ ಮಾಡಲಾಗಿದೆ"
        CHANGE_LOCATION -> "ಸ್ಥಳ ಬದಲಾಯಿಸಿ"
        CHANGE_CITY-> "ನಗರವನ್ನು ಬದಲಾಯಿಸಿ"
        UPLOAD_REGISTRATION_CERTIFICATE_STR -> "ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರವನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ"
        TAKE_A_PHOTO -> "ಫೋಟೋ ತೆಗೆಯಿರಿ"
        GALLERY -> "ಗ್ಯಾಲರಿ"
        GET_FULL_PAYMENT -> "ಗ್ರಾಹಕನಿಂದ ಸರಿಯಾಗಿ ಮತ್ತು ಪೂರ್ಣವಾಗಿ ಪಾವತಿ ಪಡೆಯಿರಿ"
        SELECT_CITY_STR -> "ನಗರವನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        DETECTING_LOCATION -> "ಸ್ಥಳವನ್ನು ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ"
        UNABLE_TO_DETECT_YOUR_LOCATION -> "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ"
        RC_FAILED_DESC -> "ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ RC ಸೇರಿಸಲು ಪ್ರಯತ್ನಿಸಿ"
        RC_IN_PROGRESS_DESC -> "ಒಮ್ಮೆ ಪರಿಶೀಲಿಸಿದ ನಂತರ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ RC ಅನ್ನು ಸೇರಿಸಲಾಗುತ್ತದೆ"
        RC_VERIFICATION_SUCCESS -> "ಆರ್‌ಸಿ ಪರಿಶೀಲನೆ ಯಶಸ್ವಿಯಾಗಿದೆ!"
        RC_VERIFICATION_FAILED_STATUS -> "RC ಪರಿಶೀಲನೆ ವಿಫಲವಾಗಿದೆ!"
        RC_VERIFICATION_IN_PROGRESS -> "ಆರ್‌ಸಿ ಪರಿಶೀಲನೆ ಪ್ರಗತಿಯಲ್ಲಿದೆ..."
        WE_ARE_NOT_LIVE_IN_YOUR_AREA -> "ನಾವು ಇನ್ನೂ ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ವಾಸಿಸುತ್ತಿಲ್ಲ!\nನಿಮ್ಮ ನಗರಕ್ಕೆ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!"
        LOCATION_UNSERVICEABLE -> "ಸ್ಥಳ ಸೇವೆಗೆ ಅರ್ಹವಲ್ಲ"
        UNABLE_TO_GET_YOUR_LOCATION -> "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪಡೆಯಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ!"
        TURN_OFF_ANY_MOCK_LOCATION_APP_AND_RESTART -> "ನೀವು ಬಳಸುತ್ತಿರುವ ಯಾವುದೇ ಮೋಕ್ ಸ್ಥಳ ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ಆಫ್ ಮಾಡಿ ಮತ್ತು ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ಮರುಪ್ರಾರಂಭಿಸಿ."
        REFERRAL_CODE_NUMBER -> ""
        WELCOME_TEXT _ -> ""
        ABOUT_TEXT _ -> ""
        CHOOSE_LANGUAGE -> ""
        EARNED_ON_APP _ -> ""
        TRAVELLED_ON_APP _ -> ""
        WITH -> ""
        YOU_DONT_HAVE_ANY_PAYMENTS -> ""
        RESUMED_AUTOPAY -> ""
        HALFYEARLY -> ""
        YEARLY -> ""
        CANCEL_ANYWAY -> ""
        VALIDITY_EXPIRED_STR -> ""
        DRIVER_GO_HOME_REQUEST_NOT_PRESENT -> ""
        YOUR_VEHICLE -> ""
        BOOKING_OPTIONS -> ""
        CONFIRM_AND_CHANGE -> ""
        MAKE_YOURSELF_AVAILABLE_FOR -> ""
        ENTER_NAME_OF_VEHICLE -> ""
        TOTAL_MONEY_COLLECTED -> ""
        FARE_EARNED_OF_THE_DAY -> ""
        GST_PLUS_PAYABLE -> ""
        TO_CONTINUE_USING_YATRI_SATHI -> ""
        PAY -> ""
        LATER -> ""
        GREAT_JOB -> ""
        FEE_BREAKUP -> ""
        YATRI_SATHI_FEE_PAYABLE_FOR_DATE _ -> ""
        FEE_CORRESPONDING_TO_THE_DISTANCE -> ""
        PLATFORM_FEE -> ""
        GST -> ""
        TOTAL_PAYABLE -> ""
        PAYMENT_SUCCESSFUL -> ""
        PAYMENT_PENDING_DESC -> ""
        PAYMENT_FAILED_DESC _ -> ""
        WE_WILL_NOTIFY_WHEN_PAYMENT_SUCCESS -> ""
        CONTINUE_TAKING_RIDES -> ""
        YOUR_PREVIOUS_PAYMENT_IS_PENDING -> ""
        GOVERMENT_CHARGES -> ""
        ENTER_AADHAAR_DETAILS -> ""
        ENTER_AADHAAR_OTP_ -> ""
        CALL_REQUEST_HAS_BEEN_PLACED -> ""
        BY_CLICKING_NEXT_YOU_WILL_BE_AGREEING_TO_OUR -> ""
        THIS_EXTRA_AMOUNT_THE_CUSTOMER_WILL_PAY -> "ಇದು ಗ್ರಾಹಕರು ನಿಮಗೆ ಪಾವತಿಸುವ ಹೆಚ್ಚುವರಿ ಮೊತ್ತವಾಗಿದೆ ಏಕೆಂದರೆ ನೀವು {} ನಿಮಿಷಗಳಿಗಿಂತ ಹೆಚ್ಚು ಕಾಯುತ್ತಿದ್ದೀರಿ"
        TEN_DIGIT_MOBILE_NUMBER -> "10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ"