module Resources.Localizable.ML where

import Language.Types (STR(..))

getML :: STR -> String
getML stringKey =
    case stringKey of
        INACCURATE_DATE_AND_TIME -> "കൃത്യമല്ലാത്ത തീയതിയും സമയവും!"
        ADJUST_YOUR_DEVICE_DATE_AND_TIME_AND_TRY_AGAIN -> "നിങ്ങളുടെ സെറ്റിംഗ്സ് ആപ്പിൾ നിന്ന് ഓട്ടോമാറ്റിക് ഡേറ്റും ടൈമും സെറ്റ് ചെയ്യുക"
        THE_CURRENT_DATE_AND_TIME_IS -> "നിലവിലെ തീയതിയും സമയവുമാണ്"
        GO_TO_SETTING -> "ക്രമീകരണങ്ങളിലേക്ക് പോകുക"
        LETS_GET_STARTED -> "ആരംഭിക്കുക"
        YOUR_APPLICATION_HAS_BEEN_SUBMITTED_SUCCESSFULLY_AND_IS_UNDER_VERIFICATION -> "നിങ്ങളുടെ അപേക്ഷ വിജയകരമായി സമർപ്പിക്കപ്പെട്ടു. ഞങ്ങൾ അത് തുടർന്നു സ്ഥിതികരിക്കുകയാണ് "
        VIEW_STATUS -> "സ്റ്റാറ്റസ് അറിയുക"
        GO_HOME -> "ഹോമിലേക്ക് പോകുക"
        SELECT_LANGUAGE -> "ഭാഷ തിരഞ്ഞെടുക്കുക"
        WHICH_LANGUAGE_DO_YOU_PREFER -> "ഏത് ഭാഷയ്ക്കാണ് നിങ്ങൾ മുൻഗണന നൽകുന്നത്?"
        NEXT -> "അടുത്തത്"
        T_C -> "നിബന്ധനകളും വ്യവസ്ഥകളും"
        ENTER_MOBILE_NUMBER -> "മൊബൈൽ നമ്പർ നൽകുക"
        BY_CLICKING_CONTINUE_YOU_WILL_BE_AGREEING_TO_OUR -> "തുടരുക ക്ലിക്ക് ചെയ്യുന്നതിലൂടെ, നിങ്ങൾ ഞങ്ങളുടെ ഉപാധികളും നിബന്ധനകളും അംഗീകരിക്കുന്നു:"
        ENTER_OTP -> "OTP നൽകുക"
        DIDNT_RECIEVE_OTP -> "OTP കിട്ടിയില്ലേ? "
        RESEND_OTP -> "<a href=\"\">OTP വീണ്ടും അയക്കുക</a>"
        PLEASE_ENTER_VALID_OTP -> "സാധുവായ OTP നൽകുക"
        INVALID_MOBILE_NUMBER -> "അസാധുവായ മൊബൈൽ നമ്പർ"
        REGISTER -> "രജിസ്റ്റർ ചെയ്യുക"
        MOBILE_NUMBER -> "മൊബൈൽ നമ്പർ"
        AUTO_READING_OTP -> "OTP ഓട്ടോ-റീഡ് ചെയ്യുന്നു…"
        UPLOAD_DRIVING_LICENSE -> "ഡ്രൈവിംഗ് ലൈസൻസ് അപ്ലോഡു ചെയ്യുക"
        UPLOAD_BACK_SIDE -> "DL- ന്റെ പിൻവശം അപ്ലോഡ് ചെയ്യുക"
        UPLOAD_FRONT_SIDE -> "DL- ന്റെ മുൻവശം  അപ്ലോഡ് ചെയ്യുക"
        BACK_SIDE -> "പിൻവശം"
        FRONT_SIDE -> "മുൻവശം"
        LICENSE_INSTRUCTION_PICTURE -> "ദയവായി ലൈസൻസിന്റെ ഇരുവശവും അപ്ലോഡുചെയ്യുക"
        LICENSE_INSTRUCTION_CLARITY -> "ഫോട്ടോയും എല്ലാ വിശദാംശങ്ങളും വ്യക്തമായി കാണാൻപറ്റുമെന്നു ഉറപ്പാക്കുക"
        REGISTRATION_STEPS -> "രജിസ്ട്രേഷൻ ഘട്ടങ്ങൾ"
        PROGRESS_SAVED -> "നിങ്ങളുടെ പുരോഗതി സേവ് ചെയ്തു, ഏതെങ്കിലും വിവരങ്ങൾ മാറ്റുന്നതിന് നിങ്ങൾക്ക് മുമ്പത്തെ ഘട്ടങ്ങളിലേക്കും മടങ്ങാം"
        DRIVING_LICENSE -> "ഡ്രൈവിംഗ് ലൈസൻസ്"
        AADHAR_CARD -> "ആധാർ കാർഡ്"
        BANK_DETAILS -> "ബാങ്ക് വിശദാംശങ്ങൾ"
        VEHICLE_DETAILS -> "വാഹന വിശദാംശങ്ങൾ"
        UPLOAD_FRONT_BACK -> "ഇരുവശത്തിന്റെയും ചിത്രങ്ങൾ ദയവായി അപ്ലോഡുചെയ്യുക"
        EARNINGS_WILL_BE_CREDITED -> "നിങ്ങളുടെ വരുമാനം ഇവിടെ ക്രെഡിറ്റ് ചെയ്യും"
        FILL_VEHICLE_DETAILS -> "നിങ്ങളുടെ വാഹന വിശദാംശങ്ങൾ പൂരിപ്പിക്കുക"
        FOLLOW_STEPS -> "രജിസ്റ്റർ ചെയ്യുന്നതിന് ദയവായി ചുവടെയുള്ള നടപടികൾ പാലിക്കുക"
        REGISTRATION -> "രജിസ്ട്രേഷൻ"
        UPLOAD_ADHAAR_CARD -> "ആധാർ കാർഡ് അപ്ലോഡുചെയ്യുക"
        ADHAAR_INTRUCTION_PICTURE -> "ആധാർ കാർഡിന്റെ ഇരുവശത്തിന്റെയും ചിത്രങ്ങൾ ദയവായി അപ്ലോഡുചെയ്യുക"
        ADD_VEHICLE_DETAILS -> "വാഹന വിശദാംശങ്ങൾ ചേർക്കുക"
        VEHICLE_REGISTRATION_NUMBER -> "വാഹന രജിസ്ട്രേഷൻ നമ്പർ"
        RE_ENTER_VEHICLE_REGISTRATION_NUMBER -> "വാഹന രജിസ്ട്രേഷൻ  നമ്പർ വീണ്ടും നൽകുക"
        ENTER_VEHICLE_NO -> "വാഹന നമ്പർ നൽകുക."
        VEHICLE_TYPE -> "വാഹന തരം"
        VEHICLE_MODEL_NAME -> "വാഹന മോഡലിന്റെ പേര്"
        ENTER_MODEL_NAME -> "മോഡൽ പേര് നൽകുക"
        VEHICLE_COLOUR -> "വാഹനത്തിന്റെ നിറം"
        ENTER_VEHICLE_COLOUR -> "വാഹനത്തിന്റെ നിറം നൽകുക"
        UPLOAD_REGISTRATION_CERTIFICATE -> "രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ് അപ്ലോഡുചെയ്യുക (ആർസി)"
        UPLOAD_RC -> "ആർസി അപ്ലോഡുചെയ്യുക"
        PREVIEW -> "പ്രിവ്യൂ"
        CHOOSE_VEHICLE_TYPE -> "വാഹന തരം തിരഞ്ഞെടുക്കുക"
        BENIFICIARY_NUMBER -> "ഗുണഭോക്തൃ അക്കൗണ്ട് നമ്പർ"
        RE_ENTER_BENIFICIARY_NUMBER -> "ഗുണഭോക്തൃ അക്കൗണ്ട് നമ്പർ വീണ്ടും നൽകുക."
        IFSC_CODE -> "Ifsc കോഡ്"
        SENDING_OTP -> "OTP അയയ്ക്കുന്നു"
        PLEASE_WAIT_WHILE_IN_PROGRESS -> "പുരോഗതിയിൽ; ദയവായി കാത്തിരിക്കുക"
        YOUR_REQUEST_HAS_TIMEOUT_TRY_AGAIN -> "നിങ്ങളുടെ അഭ്യർത്ഥനയുടെ സമയപരിധി അവസാനിച്ചു. വീണ്ടും ശ്രമിക്കുക."
        ERROR_OCCURED_PLEASE_TRY_AGAIN_LATER -> "പിശക് സംഭവിച്ചിട്ടുണ്ട്; ദയവായി അല്പസമയത്തിനുള്ളിൽ വീണ്ടും ശ്രമിക്കുക"
        ENTER_OTP_SENT_TO -> " എന്ന നമ്പറിലേക്ക് അയച്ച ഒടിപി നൽകുക"
        OTP_SENT_TO -> " എന്ന നമ്പറിലേക്ക് OTP അയച്ചു"
        COUNTRY_CODE_INDIA -> "91"
        ENTER_ACCOUNT_NUMBER -> "അക്കൗണ്ട് നമ്പർ നൽകുക."
        ADD_BANK_DETAILS -> "ബാങ്ക് വിശദാംശങ്ങൾ ചേർക്കുക"
        ENTER_IFSC_CODE -> "IFSC കോഡ് നൽകുക"
        SUBMIT -> "സമർപ്പിക്കുക"
        PERSONAL_DETAILS -> "വ്യക്തിഗത വിശദാംശങ്ങൾ"
        LANGUAGES -> "ഭാഷകൾ"
        HELP_AND_FAQ -> "സഹായവും പതിവുചോദ്യങ്ങളും"
        ABOUT -> "ആപ്പിനെ കുറിച്ച്"
        LOGOUT -> "ലോഗൗട്ട്"
        UPDATE -> "അപ്ഡേറ്റ്"
        EDIT -> "എഡിറ്റ് ചെയ്യുക"
        AUTO -> "ഓട്ടോ"
        NAME -> "പേര്"
        PRIVACY_POLICY -> "സ്വകാര്യതാ നയം"
        LOGO -> "ലോഗോ"
        ABOUT_APP_DESCRIPTION -> "യാത്രക്കാരെ ഡ്രൈവർമാരുമായി ബന്ധിപ്പിക്കുന്നതിനുള്ള ഒരു ഓപ്പൺ പ്ലാറ്റ്ഫോമാണ് നമ്മ യാത്രി പാർട്ട്നർ. നിർദ്ദിഷ്ട നിരക്കുകളിൽ റൈഡറുകളെ കണ്ടെത്താൻ ഡ്രൈവർമാർക്ക് അപ്ലിക്കേഷൻ സൗകര്യപ്രദമാക്കും. റൈഡ് അടിസ്ഥാനമാക്കിയുള്ള കമ്മീഷനൊന്നും തന്നെ ഇല്ല, പ്രതിമാസ സബ്സ്ക്രിപ്ഷന്റെ രൂപത്തിൽ ചെറിയ തുക മാത്രമേ അടക്കേണ്ടതൊള്ളൂ"
        TERMS_AND_CONDITIONS -> "നിബന്ധനകളും വ്യവസ്ഥകളും"
        UPDATE_VEHICLE_DETAILS -> "വാഹന വിശദാംശങ്ങൾ അപ്ഡേറ്റുചെയ്യുക"
        NOTE -> "കുറിപ്പ്:"
        VISIT_MY_RIDES_SCREEN_FOR_SPECIFIC_COMPLAINTS -> "നിർദ്ദിഷ്ട പരാതികൾക്കായി എന്റെ റൈഡുകൾ വിഭാഗം സന്ദർശിക്കുക"
        THANK_YOU_FOR_WRTITTING_US -> "ഞങ്ങൾക്ക് എഴുതിയതിന് നന്ദി!"
        WE_HAVE_RECIEVED_YOUR_ISSUE -> "നിങ്ങളുടെ പ്രശ്നം ഞങ്ങൾക്ക് ലഭിച്ചു. ഞങ്ങൾ കുറച്ച് സമയത്തിനുള്ളിൽ നിങ്ങളെ ബന്ധപ്പെടും."
        GO_TO_HOME -> "ഹോം -ലേയ്ക്ക് പോകൂ"
        YOUR_RECENT_RIDE -> "സമീപകാലത്തെ നിങ്ങളുടെ റൈഡ്"
        YOUR_RECENT_TRIP -> "Your Recent Trip"
        ALL_TOPICS -> "എല്ലാ വിഷയങ്ങളും"
        REPORT_AN_ISSUE_WITH_THIS_TRIP -> "ഈ യാത്രയെ സംബന്ധിച്ച് ഒരു പ്രശ്നം  റിപ്പോർട്ടുചെയ്യുക"
        YOU_RATED -> "നിങ്ങൾ റേറ്റു ചെയ്തു:"
        VIEW_ALL_RIDES -> "എല്ലാ റൈഡുകളും കാണുക"
        WRITE_TO_US -> "ഞങ്ങൾക്ക് എഴുതുക"
        SUBJECT -> "വിഷയം"
        YOUR_EMAIL_ID -> "നിങ്ങളുടെ ഇമെയിൽ ഐഡി"
        DESCRIBE_YOUR_ISSUE -> "നിങ്ങളുടെ പ്രശ്നത്തെക്കുറിച്ച് വിവരിക്കുക"
        GETTING_STARTED_AND_FAQ -> "ആരംഭവും പതിവുചോദ്യങ്ങളും"
        FOR_OTHER_ISSUES_WRITE_TO_US -> "മറ്റ് പ്രശ്നങ്ങൾക്കായി ഞങ്ങൾക്ക് എഴുതുക"
        CALL_SUPPORT_CENTER -> "സപ്പോർട് സെന്ററിൽ വിളിക്കുക"
        YOU_CAN_DESCRIBE_ISSUE_THAT_YOU_FACED_HERE -> "നിങ്ങളുടെ പ്രശ്നം ഇവിടെ വിവരിക്കാം"
        REGISTRATION_CERTIFICATE_IMAGE -> "രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ് (ആർസി) ചിത്രം"
        HOME -> "ഹോം"
        RIDES -> "റൈഡ്സ്"
        MY_RIDES -> "എന്റെ റൈഡുകൾ"
        PROFILE -> "പ്രൊഫൈൽ"
        ENTER_DRIVING_LICENSE_NUMBER -> "ഡ്രൈവിംഗ് ലൈസൻസ് നമ്പർ നൽകുക"
        WHERE_IS_MY_LICENSE_NUMBER -> "എന്റെ ലൈസൻസ് നമ്പർ എവിടെയാണ്?"
        TRIP_DETAILS -> "യാത്ര വിശദാംശങ്ങൾ"
        BY_CASH -> "പണമായി"
        ONLINE_ -> "ഓൺ"
        GO_ONLINE_POPUP -> "<u>പോകൂ ഓൺ</u>"
        REPORT_AN_ISSUE -> "ഒരു പ്രശ്നം റിപ്പോർട്ടുചെയ്യുക"
        DISTANCE -> "അകലം"
        TIME_TAKEN -> "എടുത്ത സമയം"
        CALL -> "കാൾ"
        START_RIDE -> "റൈഡ് ആരംഭിക്കുക"
        CANCEL_RIDE -> "റൈഡ് റദ്ദാക്കുക"
        PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL -> "എന്തുകൊണ്ടാണ് നിങ്ങൾ റൈഡ് റദ്ദാക്കാൻ ആഗ്രഹിക്കുന്നതെന്ന് ഞങ്ങളോട് പറയുക"
        MANDATORY -> "നിർബന്ധമാണ്"
        END_RIDE -> "റൈഡ് അവസാനിപ്പിക്കുക"
        RIDE_COMPLETED_WITH -> "യാത്ര പൂർണമായി; ഉപഭോക്താവ്:"
        COLLECT_AMOUNT_IN_CASH -> "തുക പണമായി കൈപ്പറ്റുക"
        CASH_COLLECTED -> "പണം കൈപ്പറ്റി"
        OFFLINE -> "ഓഫ്"
        ACCEPT_FOR -> "ഈ നിരക്കിൽ സ്വീകരിക്കുക:"
        DECLINE -> "നിരസിക്കുക"
        REQUEST -> "അപേക്ഷിക്കുക"
        YOU_ARE_OFFLINE -> "നിങ്ങൾ ഓഫ്ലൈനാണ്"
        YOU_ARE_CURRENTLY_BUSY_GO_ONLINE_TO_RECIEVE_TRIP_REQUESTS -> "നിങ്ങൾ നിലവിൽ തിരക്കിലാണ്. യാത്രാ അഭ്യർത്ഥനകൾ സ്വീകരിക്കുന്നതിന് ഓൺലൈനിൽ പോകുക"
        GOING_OFFLINE_WILL_NOT_GET_YOU_ANY_RIDE -> "ഓഫ്‌ലൈൻ ആയാൽ നിങ്ങള്ക്ക് റൈഡുകൾ ലഭിക്കില്ല "
        CANCEL -> "റദ്ദാക്കുക"
        GO_OFFLINE -> "ഓഫ്‌ലൈൻ ആകുക"
        IS_WAITING_FOR_YOU -> "നിങ്ങൾക്കായി കാത്തിരിക്കുന്നു"
        YOU_ARE_ON_A_RIDE -> "നിങ്ങൾ ഒരു റൈഡിലാണ് ..."
        PLEASE_ASK_RIDER_FOR_THE_OTP -> "OTP-ക്കായി റീഡറിനോട് ചോദിക്കുക"
        COMPLETED_ -> "പൂർത്തിയായത്"
        CANCELLED_ -> "റദ്ദായത്"
        WE_NEED_SOME_ACCESS -> "ഞങ്ങൾക്ക് അക്സസ്സ് നൽകാൻ അഭ്യർത്ഥിക്കുന്നു"
        ALLOW_ACCESS -> "അക്സസ്സ് അനുവദിക്കുക"
        THANK_YOU_FOR_WRITING_TO_US -> "ഞങ്ങൾക്ക് എഴുതിയതിന് നന്ദി!"
        RIDER -> "റൈഡർ"
        TRIP_ID -> "യാത്രാ ഐഡി"
        NEED_IT_TO_SHOW_YOU_INCOMING_RIDE_REQUEST -> "അപ്ലിക്കേഷൻ പശ്ചാത്തലത്തിൽ ആയിരിക്കുമ്പോഴും, വരുന്ന റൈഡ് റിക്വസ്റ്റ് കാണുവാൻ സാധിക്കുക"
        NEED_IT_TO_DISABLE_BATTERY_OPTIMIZATION_FOR_THE_APP -> "ആപ്പ് ദീർഘനേരം പശ്ചാത്തലത്തിൽ പ്രവർത്തിക്കാൻ അനുവദിക്കുന്നു. ശുപാർശ ചെയ്യപ്പെട്ടത്"
        NEED_IT_TO_AUTOSTART_YOUR_APP -> "പശ്ചാത്തലത്തിൽ അപ്ലിക്കേഷൻ പ്രവർത്തിക്കുന്നതിനാൽ സഹായകമാകുന്നു"
        NEED_IT_TO_ENABLE_LOCATION _ -> "അപ്ലിക്കേഷൻ ഉപയോഗത്തിൽ ഇല്ലാത്തപ്പോൾ പോലും  , നിങ്ങളുടെ നിലവിലെ സ്ഥാനം നിർണ്ണയിക്കാൻ നമ്മ യാത്രി പാർട്ട്നർ ആപ്പ് ലൊക്കേഷൻ ഡാറ്റ ശേഖരിക്കുന്നതായിരിക്കും."
        OVERLAY_TO_DRAW_OVER_APPLICATIONS -> "മറ്റു അപ്ലിക്കേഷനുകളുടെ മുകളിലൂടെ കാണിക്കുവാൻ അനുവദിക്കുക"
        BATTERY_OPTIMIZATIONS -> "ബാറ്ററി ഒപ്റ്റിമൈസേഷൻ"
        AUTO_START_APPLICATION_IN_BACKGROUND -> "പശ്ചാത്തലത്തിൽ അപ്ലിക്കേഷൻ ഓട്ടോസ്റ്റാർട്ട് ചെയ്യുക"
        LOCATION_ACCESS -> "ലൊക്കേഷൻ ആക്സസ്"
        ENTER_RC_NUMBER -> "ആർസി നമ്പർ നൽകുക"
        WHERE_IS_MY_RC_NUMBER -> "എന്റെ ആർസി നമ്പർ എവിടെയാണ്?"
        STEP -> "ഘട്ടം"
        PAID -> "തുക അടച്ചു"
        ENTERED_WRONG_OTP -> "തെറ്റായ OTP നൽകി"
        OTP_INVALID_FOR_THIS_VEHICLE_VARIANT ->  "അസാധുവായ OTP - വാഹന തരം റൈഡ് തരവുമായി പൊരുത്തപ്പെടുന്നില്ല"
        COPIED -> "പകർത്തി"
        BANK_NAME -> "ബാങ്കിന്റെ പേര്"
        AADHAR_DETAILS -> "ആധാർ വിശദാംശങ്ങൾ"
        AADHAR_NUMBER -> "ആധാർ നമ്പർ"
        FRONT_SIDE_IMAGE -> "മുൻവശത്തെ ചിത്രം"
        BACK_SIDE_IMAGE -> "പിൻവശത്തെ ചിത്രം"
        STILL_NOT_RESOLVED -> "ഇപ്പോഴും പരിഹരിക്കപ്പെട്ടിട്ടില്ലെങ്കിൽ ഞങ്ങളെ വിളിക്കൂ"
        CASE_TWO -> "b)"
        NON_DISCLOUSER_AGREEMENT -> "നോൺ ഡിസ്‌ക്ലോഷർ കരാർ (എൻഡിഎ)"
        DATA_COLLECTION_AUTHORITY -> "c) തുടരുന്നതിലൂടെ, ഞാൻ ഇതിനാൽ ജസ്പേയെ എന്റെ വിവരങ്ങൾ ശേഖരിക്കുന്നതിന് നിയമിക്കുകയും അംഗീകാരം നൽകുകയും ചെയ്യുന്നു. ഉപയോഗ നിബന്ധനകളും സ്വകാര്യതാ നയവും ഞാൻ അംഗീകരിക്കുന്നു."
        SOFTWARE_LICENSE -> "സോഫ്റ്റ്വെയർ ലൈസൻസ്"
        LOAD_MORE -> "കൂടുതൽ ലോഡു ചെയ്യുക"
        ARE_YOU_SURE_YOU_WANT_TO_LOGOUT -> "നിങ്ങൾക്ക് ലോഗൗട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?"
        GO_BACK -> "മടങ്ങിപ്പോവുക"
        THANK_YOU_FOR_REGISTERING_US -> "ഞങ്ങളുമായി രജിസ്റ്റർ ചെയ്തതിന് നന്ദി!"
        UNFORTANUTELY_WE_ARE_NOT_AVAILABLE__YET_FOR_YOU -> "നിർഭാഗ്യവശാൽ, ഞങ്ങളുടെ സേവനം ഇപ്പോൾ നിങ്ങൾക്കായി ലഭ്യമല്ല. ഞങ്ങൾ നിങ്ങളെ ഉടൻ അറിയിക്കും."
        ARE_YOU_SURE_YOU_WANT_TO_END_THE_RIDE -> "സവാരി അവസാനിപ്പിക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?"
        EMPTY_RIDES -> "റൈഡുകൾ ഇതുവരെ ഇല്ല"
        YOU_HAVE_NOT_TAKEN_A_TRIP_YET -> "നിങ്ങൾ ഇതുവരെ ഒരു യാത്ര നടത്തിയിട്ടില്ല"
        BOOK_NOW -> "ഇപ്പോൾ ബുക്ക് ചെയ്യു"
        RESEND_OTP_IN -> "<u>OTP  വീണ്ടും അയയ്ക്കുക "
        WE_NEED_ACCESS_TO_YOUR_LOCATION -> "ഞങ്ങൾക്ക് നിങ്ങളുടെ ലൊക്കേഷൻ ആക്സസ് ആവശ്യമാണ്!"
        YOUR_LOCATION_HELPS_OUR_SYSTEM _ -> "നിങ്ങളുടെ ലൊക്കേഷൻ, വേഗത്തിൽ സവാരി കണ്ടെത്താൻ ഞങ്ങളുടെ സിസ്റ്റത്തെ സഹായിക്കുന്നു."
        NO_INTERNET_CONNECTION -> "ഇന്റർനെറ്റ് കണക്ഷൻ ഇല്ല"
        PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN -> "ദയവായി ഇന്റർനെറ്റ് കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക"
        TRY_AGAIN -> "വീണ്ടും ശ്രമിക്കുക"
        GRANT_ACCESS -> " ആക്സസ് നൽകുക"
        YOUR_LIMIT_EXCEEDED_TRY_AGAIN_AFTER_10_MIN -> "നിങ്ങളുടെ പരിധി കഴിഞ്ഞു, 10 മിനിറ്റ് കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കുക"
        ENTER_REFERRAL_MOBILE_NUMBER -> "റഫറൽ മൊബൈൽ നമ്പർ നൽകുക"
        APPLY -> "അപേക്ഷിക്കുക"
        HAVE_A_REFERRAL -> "റഫറൽ ഉണ്ടോ?"
        ADD_HERE -> "ഇവിടെ ചേർക്കുക"
        REFERRAL_APPLIED -> "റഫറൽ ഉപയോഗിച്ചു!"
        SMALLEDIT -> "തിരുത്തുക"
        ADD_DRIVING_LICENSE -> "ഡ്രൈവിംഗ് ലൈസൻസ് ചേർക്കുക"
        HELP -> "സഹായം?"
        INVALID_DL_NUMBER -> "DL നമ്പർ അസാധുവാണ്"
        DRIVING_LICENSE_NUMBER -> "ഡ്രൈവിംഗ് ലൈസൻസ് നമ്പർ"
        RE_ENTER_DRIVING_LICENSE_NUMBER -> "ഡ്രൈവിംഗ് ലൈസൻസ് നമ്പർ വീണ്ടും നൽകുക"
        ENTER_DL_NUMBER -> "DL നമ്പർ നൽകുക"
        SELECT_DATE_OF_BIRTH -> "ജനനത്തീയതി തിരഞ്ഞെടുക്കുക"
        DATE_OF_BIRTH -> "ജനന തീയതി"
        WATCH_A_TUTORIAL_FOR_EASY_REGISTRATION -> "രെജിസ്ട്രേഷനെ പറ്റി എളുപ്പത്തിൽ പഠിക്കാൻ  ഒരു ട്യൂട്ടോറിയൽ കാണുക"
        ENTER_MINIMUM_FIFTEEN_CHARACTERS -> "കുറഞ്ഞത്  15 അക്ഷരങ്ങൾ നൽകുക"
        ADD_YOUR_FRIEND -> "നിങ്ങളുടെ സുഹൃത്തിനെ ചേർക്കുക"
        PLEASE_WAIT_WHILE_VALIDATING_THE_IMAGE -> "ചിത്രം സ്ഥിരീകരിക്കുന്നത് വരെ  ദയവായി കാത്തിരിക്കുക"
        VALIDATING -> "സ്ഥിരീകരിക്കുന്നു"
        VERIFICATION_PENDING -> "സ്ഥിരീകരണം കഴിഞ്ഞിട്ടില്ല"
        VERIFICATION_FAILED -> "സ്ഥിരീകരണം പരാജയപ്പെട്ടു"
        NO_DOC_AVAILABLE -> "ഡോക്യുമെന്റ് ലഭ്യമല്ല"
        ISSUE_WITH_DL_IMAGE -> "നിങ്ങളുടെ DL ചിത്രത്തിനു കുറച്ച് പ്രശ്നങ്ങളുണ്ടെന്ന് തോന്നുന്നു, ഞങ്ങളുടെ സപ്പോർട്ട് ടീം ഉടൻ നിങ്ങളെ ബന്ധപ്പെടും."
        STILL_HAVE_SOME_DOUBT -> "ഇപ്പോഴും എന്തെങ്കിലും സംശയമുണ്ടോ?"
        ISSUE_WITH_RC_IMAGE -> "നിങ്ങളുടെ  ആർസി ചിത്രത്തിനു കുറച്ച് പ്രശ്നങ്ങളുണ്ടെന്ന് തോന്നുന്നു, ഞങ്ങളുടെ സപ്പോർട്ട് ടീം ഉടൻ നിങ്ങളെ ബന്ധപ്പെടും."
        PLEASE_CHECK_FOR_IMAGE_IF_VALID_DOCUMENT_IMAGE_OR_NOT -> "ഡോക്യൂമെന്റിന്റെ ചിത്രം സാധുവാണോ എന്നു പരിശോധിക്കുക     "
        OOPS_YOUR_APPLICATION_HAS_BEEN_REJECTED -> "ക്ഷമിക്കണം! നിങ്ങളുടെ അപേക്ഷ നിരസിക്കപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക"
        INVALID_DRIVING_LICENSE -> "ഡ്രൈവിംഗ് ലൈസൻസ് അസാധുവാണ്"
        LIMIT_EXCEEDED_FOR_DL_UPLOAD -> "DL അപ്ലോഡിനായുള്ള പരിധി കഴിഞ്ഞു "
        INVALID_VEHICLE_REGISTRATION_CERTIFICATE -> "വാഹന രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ് അസാധുവാണ്"
        LIMIT_EXCEEDED_FOR_RC_UPLOAD -> "ആർസി അപ്ലോഡിനായുള്ള പരിധി കഴിഞ്ഞു"
        YOUR_DOCUMENTS_ARE_APPROVED -> "നിങ്ങളുടെ ഡോക്യൂമെന്റസ് അംഗീകരിച്ചു. സപ്പോർട്ട് ടീം നിങ്ങളുടെ അക്കൗണ്ടിനെ ഉടൻ സജീവം ആക്കും. നിങ്ങളുടെ അക്കൗണ്ട് പ്രവർത്തനക്ഷമമാക്കുന്നതിന് നിങ്ങൾക്ക് സപ്പോർട്ട് ടീമിനെ വിളിക്കാം"
        APPLICATION_STATUS -> "അപേക്ഷയുടെ സ്റ്റാറ്റസ്"
        FOR_SUPPORT -> "പിന്തുണയ്ക്കായി"
        CONTACT_US -> " ഞങ്ങളെ സമീപിക്കുക"
        IMAGE_VALIDATION_FAILED -> "ഇമേജ് സ്ഥിരീകരണം പരാജയപ്പെട്ടു"
        IMAGE_NOT_READABLE -> "ചിത്രം വായിക്കാൻ കഴിയില്ല"
        IMAGE_LOW_QUALITY -> "ചിത്രത്തിന്റെ നിലവാരം നല്ലതല്ല"
        IMAGE_INVALID_TYPE -> "നൽകിയ ചിത്രം അസാധുവാണ്"
        IMAGE_DOCUMENT_NUMBER_MISMATCH -> "ഈ ചിത്രത്തിലെ ഡോക്യുമെന്റ് നമ്പർ, തന്ന വിവരവും ആയി പൊരുത്തപ്പെടുന്നില്ല"
        IMAGE_EXTRACTION_FAILED -> "ചിത്രം സ്വീകരിക്കാൻ പരാജയപ്പെട്ടു"
        IMAGE_NOT_FOUND -> "ചിത്രം കണ്ടെത്തിയില്ല"
        IMAGE_NOT_VALID -> " ചിത്രം അസാധുവാണ്"
        DRIVER_ALREADY_LINKED -> "ഡോക്യുമെന്റ് മറ്റൊരു ഡ്രൈവറുമായി ഇതിനകം ബന്ധപ്പെട്ടിരിക്കുന്നു"
        DL_ALREADY_UPDATED -> "മാറ്റങ്ങൾ ഒന്നും  ആവശ്യമില്ല. ഡ്രൈവർ ലൈസൻസ് ഇതിനകം ഡ്രൈവറുമായി ബന്ധപ്പെട്ടിരിക്കുന്നു"
        RC_ALREADY_LINKED -> "വെഹിക്കിൾ ആർസി ലഭ്യമല്ല. മറ്റൊരു ഡ്രൈവറുമായി ഇതിനകം ബന്ധപ്പെട്ടിരിക്കുന്നു"
        RC_ALREADY_UPDATED -> "മാറ്റങ്ങൾ ഒന്നും  ആവശ്യമില്ല. വാഹനം ഇതിനകം ഡ്രൈവറുമായി ബന്ധപ്പെട്ടിരിക്കുന്നു"
        DL_ALREADY_LINKED -> "ഡ്രൈവർ ലൈസൻസ് ലഭ്യമല്ല. മറ്റൊരു ഡ്രൈവറുമായി ഇതിനകം ബന്ധപ്പെട്ടിരിക്കുന്നു"
        SOMETHING_WENT_WRONG -> "എന്തോ കുഴപ്പം സംഭവിച്ചു"
        PICKUP -> "പിക്കപ്പ്"
        TRIP -> "യാത്ര"
        CURRENTLY_WE_ALLOW_ONLY_KARNATAKA_REGISTERED_NUMBER _ -> "നിലവിൽ, കർണാടകയിൽ രജിസ്റ്റർ ചെയ്ത നമ്പർ മാത്രമേ അനുവദനീയമായുള്ളു"
        UPDATED_AT -> "മാപ് അപ്ഡേറ്റ്"
        TRIP_COUNT -> "ഇന്നത്തെ യാത്രകൾ"
        TODAYS_EARNINGS -> "ഇന്നത്തെ വരുമാനം"
        TODAYS_EARNINGS_STR -> "ഇന്നത്തെ വരുമാനം"
        BONUS_EARNED ->  "ബോണസ് നേടി"
        GOT_IT ->  "മനസ്സിലായി!"
        WHAT_IS_NAMMA_YATRI_BONUS _ ->  "എന്താണ് ബോണസ്?"
        BONUS_PRIMARY_TEXT ->  "പിക്കപ്പ് ചാർജുകൾ, കസ്റ്റമർ ടിപ്പുകൾ, ഡ്രൈവർ കൂട്ടിച്ചേർക്കലുകൾ എന്നിവയുടെ രൂപത്തിൽ മീറ്റർ ചാർജിന് മുകളിൽ നിങ്ങൾ നേടിയ അധിക തുകയാണ് നമ്മ യാത്രി ബോണസ്."
        BONUS_SECONDARY_TEXT ->  "നിങ്ങളുടെ മൊത്തം വരുമാനത്തിന്റെ ഭാഗമാണ് നമ്മ യാത്രി ബോണസ് തുക."
        DATE_OF_REGISTRATION -> "രജിസ്ട്രേഷൻ തീയതി"
        SELECT_DATE_OF_ISSUE -> "പ്രശ്നത്തിന്റെ തീയതി തിരഞ്ഞെടുക്കുക"
        DATE_OF_ISSUE -> " ഇഷ്യൂ ചെയ്‍ത തീയതി"
        PROVIDE_DATE_OF_ISSUE_TEXT -> "ക്ഷമിക്കണം, നിങ്ങളുടെ വിശദാംശങ്ങൾ സാധൂകരിക്കാൻ കഴിഞ്ഞില്ല. ലൈസെൻസ് വിശദാംശങ്ങൾ സാധൂകരിക്കുന്നതിനായി<b> ഇഷ്യു ചെയ്ത തീയതി </ b> നൽകുക."
        PROVIDE_DATE_OF_REGISTRATION_TEXT -> "ക്ഷമിക്കണം, നിങ്ങളുടെ വിശദാംശങ്ങൾ സാധൂകരിക്കാൻ കഴിഞ്ഞില്ല. വാഹന വിശദാംശങ്ങൾ സാധൂകരിക്കുന്നതിനായി<b> രെജിസ്ട്രേഷൻ ചെയ്ത തീയതി </ b> നൽകുക."
        SELECT_DATE_OF_REGISTRATION -> "രജിസ്ട്രേഷൻ തീയതി തിരഞ്ഞെടുക്കുക"
        SAME_REENTERED_RC_MESSAGE -> "വീണ്ടും നൽകിയ ആർസി നമ്പർ, മുകളിൽ ഉള്ള ആർസി നമ്പറിന് തുല്യമാണെന്ന് ഉറപ്പാക്കുക"
        SAME_REENTERED_DL_MESSAGE -> "വീണ്ടും നൽകിയ ഡി എൽ നമ്പർ, മുകളിൽ ഉള്ള ഡി എൽ നമ്പറിന് തുല്യമാണെന്ന് ഉറപ്പാക്കുക"
        WHERE_IS_MY_ISSUE_DATE -> "എന്റെ ഇഷ്യു ചെയ്ത തീയതി എവിടെയാണ്?"
        WHERE_IS_MY_REGISTRATION_DATE -> "എന്റെ രജിസ്ട്രേഷൻ തീയതി എവിടെയാണ്?"
        EARNINGS_CREDITED_IN_ACCOUNT -> "നിങ്ങളുടെ വരുമാനം ഈ അക്കൗണ്ടിൽ ക്രെഡിറ്റ് ചെയ്തു"
        INVALID_PARAMETERS -> "അസാധുവായ വിവരങ്ങൾ "
        UNAUTHORIZED -> "അനധികൃതം"
        INVALID_TOKEN -> "അസാധുവായ ടോക്കൺ"
        SOME_ERROR_OCCURED_IN_OFFERRIDE -> "റൈഡ് ഓഫറിൽ എന്തോ പിശക് സംഭവിച്ചു"
        SELECT_VEHICLE_TYPE -> "വാഹനത്തിന്റെ തരം തിരഞ്ഞെടുക്കുക"
        RIDE -> "റൈഡ്"
        NO_LOCATION_UPDATE -> "ലൊക്കേഷൻ അപ്ഡേറ്റൊന്നുമില്ല"
        GOT_IT_TELL_US_MORE -> "ഓക്കേ, കൂടുതൽ പറയാൻ ആഗ്രഹിക്കുന്നുവോ?"
        WRITE_A_COMMENT -> " അഭിപ്രായം എഴുതുക"
        HOW_WAS_YOUR_RIDE_WITH -> "നിങ്ങളുടെ റൈഡ് എങ്ങനെ ഉണ്ടായിരുന്നു"
        RUDE_BEHAVIOUR -> "അപമര്യാദയായ പെരുമാറ്റം"
        LONG_WAITING_TIME -> "ദൈർഘ്യമേറിയ കാത്തിരിപ്പ്"
        DIDNT_COME_TO_PICUP_LOCATION -> "പിക്കപ്പ് ലൊക്കേഷനിൽ വന്നില്ല"
        HELP_US_WITH_YOUR_REASON -> "നിങ്ങളുടെ കാരണം രേഖപ്പെടുത്തി ഞങ്ങളെ സഹായിക്കൂ"
        MAX_CHAR_LIMIT_REACHED -> "പരിധിക്കപ്പുറം  അക്ഷരങ്ങൾ ആയി"
        SHOW_ALL_OPTIONS -> "എല്ലാ ഓപ്ഷനുകളും കാണിക്കുക"
        UPDATE_REQUIRED -> "അപ്ഡേറ്റ് ആവശ്യമാണ്"
        PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE -> "ഞങ്ങളുടെ ആപ്പിനായി ഒരു പുതിയ അപ്‌ഡേറ്റ് ലഭ്യമാണെന്ന് അറിയിക്കുന്നതിൽ ഞങ്ങൾക്ക് സന്തോഷമുണ്ട്. ഈ അപ്‌ഡേറ്റിൽ നിങ്ങളുടെ അനുഭവം കൂടുതൽ മികച്ചതാക്കുന്നതിന് പുതിയ ഡിസൈനും നിരവധി പുതിയ ഫീച്ചറുകളും ഉൾപ്പെടുന്നു"
        NOT_NOW -> "ഇപ്പോൾ വേണ്ട"
        OF -> "ആല്"
        DROP -> "ഡ്രോപ്പ്"
        PLEASE_WAIT -> "കാത്തിരിക്കൂ"
        SETTING_YOU_OFFLINE -> "താങ്കളെ ഓഫ്‌ലൈൻ ആക്കുകയാണ്"
        SETTING_YOU_ONLINE -> "താങ്കളെ ഓൺലൈൻ ആക്കുകയാണ്"
        SETTING_YOU_SILENT -> "താങ്കളെ സൈലന്റ്  ആക്കുകയാണ്"
        VIEW_BREAKDOWN -> "വിഘടിച്ചു കാണുക"
        APP_INFO -> "അപ്ലിക്കേഷനെ കുറിച്ചുള്ള വിവരങ്ങൾ"
        OTHER -> "മറ്റുളവ"
        VEHICLE_ISSUE -> "വാഹന പ്രശ്നം"
        FARE_UPDATED -> "നിരക്ക് പുതുക്കി"
        FREQUENT_CANCELLATIONS_WILL_LEAD_TO_LESS_RIDES -> "പതിവ് റദ്ദാക്കലുകൾ കുറഞ്ഞ സവാരിക്കും കുറഞ്ഞ റേറ്റിംഗിലേക്കും നയിക്കും"
        CONTINUE -> "തുടരുക"
        CONFIRM_PASSWORD -> "പാസ്സ്‌വേർഡ് സ്ഥിരീകരിക്കുക"
        DEMO_MODE -> "ഡെമോ മോഡ്"
        PASSWORD -> "പാസ്സ്‌വേർഡ്"
        ENTER_DEMO_MODE_PASSWORD -> "ഡെമോ മോഡ് പാസ്സ്‌വേർഡ് നൽകുക"
        DEMO_MODE_DISABLED -> "ഡെമോ മോഡ് നിർത്തി വെച്ചിരിക്കുന്നു"
        ONLINE_VIA_DEMO_MODE -> "ഓൺലൈൻ (ഡെമോ)"
        MORE -> "കൂടുതൽ"
        LESS -> "കുറവ്"
        YOU_ARE_AT_PICKUP -> "നിങ്ങൾ പിക്കപ്പ് ലൊക്കേഷനിലാണ്"
        WAITING_FOR_CUSTOMER -> "കസ്റ്റമർക്കായി കാത്തുനിൽക്കുന്നു: "
        CUSTOMER_NOTIFIED -> "ഉപഭോക്താവിനെ അറിയിച്ചു"
        I_ARRIVED -> "ഞാൻ എത്തി"
        ESTIMATED_RIDE_FARE -> "ഏകദേശ യാത്ര നിരക്ക്:"
        PICKUP_TOO_FAR -> "പിക്കപ്പ് വളരെ ദൂരെ"
        CUSTOMER_NOT_PICKING_CALL -> "ഉപഭോക്താവ് കോൾ എടുക്കുന്നില്ല"
        TRAFFIC_JAM -> "ഗതാഗതക്കുരുക്ക്"
        CUSTOMER_WAS_RUDE -> "ഉപഭോക്താവ് അപമര്യാദയോടെ പെരുമാറി"
        ALL_MESSAGES -> "എല്ലാ സന്ദേശങ്ങളും"
        MESSAGES -> "അലർട്സ്"
        ADD_A_COMMENT -> "കമന്റ് രേഖപ്പെടുത്തുക"
        POST_COMMENT -> " കമന്റ് പോസ്റ്റ് ചെയ്യുക   "
        ENTER_YOUR_COMMENT -> "കമന്റ് നൽകുക"
        NO_NOTIFICATIONS_RIGHT_NOW -> "ഇപ്പോൾ അറിയിപ്പുകളൊന്നുമില്ല!"
        NO_NOTIFICATIONS_RIGHT_NOW_DESC -> "പുതിയ അറിയിപ്പുകളുണ്ടെങ്കിൽ ഞങ്ങൾ നിങ്ങളെ അറിയിക്കുന്നതാണ്"
        ALERTS -> "അലേർട്ടുകൾ"
        YOUR_COMMENT -> "നിങ്ങളുടെ കമന്റ്"
        SHOW_MORE -> "കൂടുതൽ കാണിക്കുക"
        LOAD_OLDER_ALERTS -> "പഴയ അലേർട്ടുകൾ ലോഡു ചെയ്യുക"
        CONTEST -> "മത്സരം"
        YOUR_REFERRAL_CODE_IS_LINKED -> "നിങ്ങളുടെ റഫറൽ കോഡ് ലിങ്ക് ചെയ്യപ്പെട്ടിരിക്കുന്നു!"
        YOU_CAN_NOW_EARN_REWARDS -> "ഉപയോക്താക്കളെ റഫർ ചെയ്യുന്നതിലൂടെ നിങ്ങൾക്ക് ഇപ്പോൾ പ്രതിഫലം നേടാൻ കഴിയും!"
        COMING_SOON -> "ഉടൻ വരുന്നു!"
        COMING_SOON_DESCRIPTION -> " നിങ്ങളെ റഫറൽ പ്രോഗ്രാമിൽ പ്രവേശിപ്പിക്കുന്നതിനു ഞങ്ങൾ ശ്രമം തുടരുകയാണ്  . കൂടുതൽ വിവരങ്ങൾക്ക് അലേർട്ട്സ് പേജ് പരിശോധിക്കുക."
        REFERRAL_CODE_HINT -> "6 അക്ക റഫറൽ കോഡ് നൽകുക"
        CONFIRM_REFERRAL_CODE -> "റഫറൽ കോഡ് സ്ഥിരീകരിക്കുക"
        CONFIRM_REFERRAL_CODE_HINT -> "റഫറൽ കോഡ് വീണ്ടും നൽകുക"
        YOUR_REFERRAL_CODE -> "നിങ്ങളുടെ റഫറൽ കോഡ്"
        FIRST_REFERRAL_SUCCESSFUL -> "ആദ്യ റഫറൽ വിജയകരമാണ്! \n സമ്മാനം അൺലോക്കു ചെയ്തു!"
        AWAITING_REFERRAL_RIDE -> "റഫറൽ റൈഡിനായി  കാത്തിരിക്കുന്നു"
        CHECK_THIS_SPACE_WHEN_YOU_GET_REFERRAL_ALERT -> "റഫറൽ അലേർട്ട് കിട്ടുമ്പോൾ ഇവിടം സന്ദർശിക്കുക"
        REFERRED_CUSTOMERS -> "റഫർ ചെയ്‍ത ഉപഭോക്താക്കൾ "
        ACTIVATED_CUSTOMERS -> "സജീവമായ ഉപഭോക്താക്കൾ"
        REFERRAL_CODE_LINKING -> "റഫറൽ കോഡ് ലിങ്കു ചെയ്യുന്നു"
        CONTACT_SUPPORT -> "സപ്പോർട്ട് ടീമിനെ ബന്ധപെടുക"
        CALL_SUPPORT -> "സപ്പോർട്ട് ടീമിനെ വിളിക്കുക"
        YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT _ -> "നിങ്ങൾ നമ്മ യാത്രി സപ്പോർട്ട് ടീമുമായി ബന്ധപ്പെടാൻ പോകുന്നു. തുടരണോ?"
        REFERRAL_ENROLMENT -> "റഫറൽ എൻറോൾമെന്റ്"
        REFERRALS -> "റഫറലുകൾ"
        LINK_REFERRAL_CODE -> "ലിങ്ക് റഫറൽ കോഡ്"
        DRIVER_DETAILS -> "ഡ്രൈവർ വിശദാംശങ്ങൾ"
        FOR_UPDATES_SEE_ALERTS -> "അപ്ഡേറ്റുകൾക്കായി, അലേർട്ടുകൾ കാണുക"
        SHARE_OPTIONS -> "ഷെയർ ചെയ്യുന്നതിനുള്ള ഓപ്ഷൻസ്"
        ENTER_PASSWORD -> "പാസ്സ്‌വേർഡ് നൽകുക"
        BOOKING_OPTIONS -> "ബുക്കിംഗ് ഓപ്ഷനുകൾ"
        CONFIRM_AND_CHANGE -> "സ്ഥിരീകരിക്കുകയും മാറ്റുകയും ചെയ്യുക"
        YOUR_VEHICLE ->  "നിങ്ങളുടെ വാഹനം"
        MAKE_YOURSELF_AVAILABLE_FOR ->  "ഇതിനായി നിങ്ങളെത്തന്നെ ലഭ്യമാക്കുക"
        SILENT_MODE_PROMPT ->   "അല്പം ഏകാഗ്രത ആണ് താങ്കൾ ആഗ്രഹിക്കുന്നതെങ്കിൽ, സൈലന്റ് മോഡിലേക്ക് മാറാവുന്നതാണ്"
        GO_SILENT ->  "സൈലന്റ് മോഡിലേക്ക് മാറ്റുക"
        TRY_SILENT_MODE ->  "സൈലന്റ് മോഡ് ട്രൈ ചെയ്യാം?"
        RIDE_FARE ->  "റൈഡ് നിരക്ക്"
        RIDE_DISTANCE ->  "യാത്ര ദൂരം"
        START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS ->  "ചുവടെ കാണുന്ന ക്വിക്ക് ചാറ്റ് ഓപ്ഷനുകൾ ഉപയോഗിച്ച് നിങ്ങൾക്കു ചാറ്റ് ആരംഭിക്കാവുന്നതാണ്"
        START_YOUR_CHAT_WITH_THE_DRIVER ->  "ഡ്രൈവറുമായി ചാറ്റ് ആരംഭിക്കുക"
        MESSAGE ->  "സന്ദേശം അയക്കുക:"
        I_AM_ON_MY_WAY ->  "ഞാൻ എത്തിക്കൊണ്ടിരിക്കുകയാണ്"
        GETTING_DELAYED_PLEASE_WAIT ->  "അല്പം വൈകും, ദയവായി കാത്തിരിക്കുക"
        UNREACHABLE_PLEASE_CALL_BACK ->  "പരിധിക്കു പുറത്താണ്, ദയവായി വീണ്ടും വിളിക്കുക"
        ARE_YOU_STARING ->  "താങ്കൾ വരികയാണോ?"
        PLEASE_COME_SOON ->  "ദയവായി വേഗം വരിക"
        OK_I_WILL_WAIT ->  "ഓക്കേ, ഞാൻ കാത്തിരിക്കാം"
        I_HAVE_ARRIVED ->  "ഞാൻ എത്തി"
        PLEASE_COME_FAST_I_AM_WAITING ->  "ദയവായി വേഗം വരിക, ഞാൻ കാത്തിരിക്കുകയാണ്"
        PLEASE_WAIT_I_WILL_BE_THERE ->  "ദയവായി കാത്തിരിക്കൂ, ഞാൻ വന്നുകൊണ്ടിരിക്കുകയാണ് "
        LOOKING_FOR_YOU_AT_PICKUP ->  "പിക്കപ്പ് സ്ഥലത്തു താങ്കളെ തേടിക്കൊണ്ടിരിക്കുന്നു "
        SILENT ->  "സൈലന്റ് "
        GO_ONLINE ->   "പോകൂ"
        GO_ONLINE_PROMPT ->  "താങ്കൾ ഇപ്പോൾ ഓഫ്‌ലൈൻ ആണ്.\nറൈഡ് റിക്വസ്റ്റുകൾ ലഭിക്കാനായി ഓൺലൈൻ ആകൂ "
        LIVE_DASHBOARD ->  "തത്സമയ സ്ഥിതിവിവരക്കണക്ക് ഡാഷ്‌ബോർഡ്"
        CLICK_TO_ACCESS_YOUR_ACCOUNT ->  "നിങ്ങളുടെ അക്കൗണ്ട് ആക്സസ് ചെയ്യാൻ ഇവിടെ ക്ലിക്ക് ചെയ്യുക"
        ADD_ALTERNATE_NUMBER ->  "ഇതര നമ്പർ ചേർക്കുക"
        ENTER_ALTERNATE_MOBILE_NUMBER ->  "ഇതര മൊബൈൽ നമ്പർ നൽകുക"
        EDIT_ALTERNATE_MOBILE_NUMBER ->  "ഇതര മൊബൈൽ നമ്പർ എഡിറ്റ് ചെയ്യുക"
        PLEASE_ENTER_A_VALID_10_DIGIT_NUMBER ->  "സാധുവായ 10 അക്ക നമ്പർ നൽകുക"
        ALTERNATE_MOBILE_NUMBER ->  "ഇതര മൊബൈൽ നമ്പർ"
        REMOVE ->  "ഡിലീറ്റ്"
        REMOVE_ALTERNATE_NUMBER ->  "ഇതര നമ്പർ ഡിലീറ്റ് ചെയ്യുക"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_YOUR_ALTERNATE_MOBILE_NUMBER ->  "നിങ്ങളുടെ ഇതര മൊബൈൽ നമ്പർ ഡിലീറ്റ് ചെയ്യണമെന്ന് തീർച്ചയാണോ?"
        YES_REMOVE_IT ->  "അതെ, അത് ഡിലീറ്റ് ചെയ്യുക"
        NUMBER_REMOVED_SUCCESSFULLY ->  "നമ്പർ ഡിലീറ്റ് ചെയ്യപ്പെട്ടു"
        NUMBER_ADDED_SUCCESSFULLY ->  "നമ്പർ ചേർത്തു"
        NUMBER_EDITED_SUCCESSFULLY ->  "നമ്പർ അപ്‌ഡേറ്റ് ചെയ്‌തു"
        ALTERNATE_MOBILE_OTP_LIMIT_EXCEED ->  "ഓടിപി പരിധി കവിഞ്ഞു, വീണ്ടും നമ്പറും ഓടിപിയും നൽകുക"
        WRONG_OTP ->  "ദയവായി സാധുവായ ഓടിപി നൽകുക"
        ATTEMPTS_LEFT ->  " ശ്രമങ്ങൾ ശേഷിക്കുന്നു"
        ATTEMPT_LEFT ->  " ശ്രമം ശേഷിക്കുന്നു"
        OTP_LIMIT_EXCEEDED ->  "ഓടിപി പരിധി കവിഞ്ഞു"
        OTP_LIMIT_EXCEEDED_MESSAGE ->  "ഓടിപി പരിധി കവിഞ്ഞു. 10 മിനിറ്റിന് ശേഷം വീണ്ടും ശ്രമിക്കുക."
        TRY_AGAIN_LATER ->  "അൽപസമയത്തിനു ശേഷം വീണ്ടും ശ്രമിക്കുക"
        NUMBER_ALREADY_EXIST_ERROR ->  "ഈ നമ്പർ മറ്റൊരു അക്കൗണ്ടുമായി ലിങ്ക് ചെയ്യപ്പെട്ടിരിക്കുന്നു! ദയവായി മറ്റൊരു നമ്പർ ഉപയോഗിക്കുക"
        ADD_ALTERNATE_NUMBER_IN_MEANTIME ->  "ഈ പ്രക്രിയ പൂർത്തിയാകാൻ 2 പ്രവൃത്തി ദിവസങ്ങൾ വരെ എടുത്തേക്കാം. അതിനിടയിൽ, നിങ്ങൾക്ക് ഒരു ഇതര മൊബൈൽ നമ്പർ ചേർക്കാം."
        VERIFICATION_IS_TAKING_A_BIT_LONGER ->  "നിങ്ങളുടെ രെജിസ്ട്രേഷൻ പ്രതീക്ഷിച്ചതിലും കൂടുതൽ സമയമെടുക്കുന്നതായി തോന്നുന്നു. നിങ്ങളെ സഹായിക്കാൻ നിങ്ങൾക്ക് സപ്പോർട്ടുമായി ബന്ധപ്പെടാവുന്നതാണ്."
        COMPLETE_ONBOARDING ->  "ഓൺബോർഡിംഗ് പൂർത്തിയാക്കുക"
        PERSON_WITH_THIS_NUMBER_ALREADY_EXISTS ->  "ഈ മൊബൈൽ നമ്പറുള്ള വ്യക്തി നിലവിലുണ്ട്."
        OTP_ ->  "ഓടിപി"
        MAPS -> "മാപ്‌സ്"
        DEMO ->  "ഡെമോ"
        PLEASE_ASK_THE_CUSTOMER_FOR_THE_OTP ->  "ഉപഭോക്താവിനോട് OTP ചോദിക്കുക"
        DELETE ->  "ഇല്ലാതാക്കുക"
        VIEW ->  "കാണുക"
        ISSUE_NO ->  "ഇഷ്യൂ നം."
        ADD_VOICE_NOTE ->  "വോയ്സ് നോട്ട് ചേർക്കുക"
        VOICE_NOTE_ADDED ->  "വോയ്സ് നോട്ട് ചേർത്തു"
        SUBMIT_ISSUE_DETAILS ->  "പ്രശ്നത്തിന്റെ വിശദാംശങ്ങൾ സമർപ്പിക്കുക"
        IMAGE_PREVIEW ->  "ചിത്ര പ്രിവ്യൂ"
        RIDE_REPORT_ISSUE ->  "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യാൻ ഒരു റൈഡ് തിരഞ്ഞെടുക്കുക"
        ADDED_IMAGES ->  "ചിത്രങ്ങൾ ചേർത്തു"
        NO_IMAGES_ADDED ->  "ചിത്രങ്ങളൊന്നും ചേർത്തിട്ടില്ല"
        ASK_DETAILS_MESSAGE ->  "ദയവായി കുറച്ചുകൂടി വിശദാംശങ്ങൾ നൽകുക. മികച്ച രീതിയിൽ വിശദീകരിക്കാൻ നിങ്ങൾക്ക് ചിത്രങ്ങളോ ശബ്ദ കുറിപ്പുകളോ അയയ്‌ക്കാനും കഴിയും."
        ASK_DETAILS_MESSAGE_REVERSED ->  "നഷ്ടപ്പെട്ട ഇനത്തെക്കുറിച്ചുള്ള കൂടുതൽ വിശദാംശങ്ങൾ ദയവായി പങ്കിടുക. മികച്ച രീതിയിൽ വിശദീകരിക്കാൻ നിങ്ങൾക്ക് ചിത്രങ്ങളോ ശബ്ദ കുറിപ്പുകളോ അയയ്‌ക്കാനും കഴിയും."
        SELECT_OPTION ->  "നിങ്ങൾ ഇവയിലേതെങ്കിലും അഭിമുഖീകരിക്കുകയാണെങ്കിൽ ഞങ്ങളോട് പറയുക"
        SELECT_OPTION_REVERSED ->  "ഈ പ്രശ്നം എങ്ങനെ പരിഹരിക്കാനാണ് നിങ്ങൾ ആഗ്രഹിക്കുന്നത്?"
        ISSUE_SUBMITTED_MESSAGE ->  "വിശദാംശങ്ങൾ ലഭിച്ചു! നിങ്ങളുടെ പ്രശ്‌നത്തിൽ നിങ്ങളെ സഹായിക്കുന്നതിന് ഞങ്ങളുടെ ടീം 24 മണിക്കൂറിനുള്ളിൽ നിങ്ങളെ വിളിക്കും."
        I_DONT_KNOW_WHICH_RIDE ->  "ഏത് സവാരിയാണെന്ന് എനിക്കറിയില്ല"
        REPORT_ISSUE_CHAT_PLACEHOLDER _ ->  "നിങ്ങളുടെ പ്രശ്നം വിവരിക്കുക. 24 മണിക്കൂറിനുള്ളിൽ ഞങ്ങൾ അത് പരിഹരിക്കാൻ ശ്രമിക്കും."
        ADDED_VOICE_NOTE ->  "വോയ്സ് നോട്ട് ചേർത്തു"
        NO_VOICE_NOTE_ADDED ->  "വോയിസ് നോട്ട് ചേർത്തിട്ടില്ല"
        CALL_CUSTOMER_TITLE ->  "ഉപഭോക്താവിനെ വിളിക്കണോ"
        CALL_CUSTOMER_DESCRIPTION ->  "നിങ്ങൾ ഉപഭോക്താവിനെ വിളിക്കാൻ പോകുകയാണ്. നിങ്ങൾക്ക് തുടരണോ?"
        PLACE_CALL ->  "വിളിക്കുക"
        ADD_IMAGE ->  "ചിത്രം ചേർക്കുക"
        ADD_ANOTHER ->  "മറ്റൊന്ന് ചേർക്കുക"
        IMAGES_ADDED ->  "ചിത്രങ്ങൾ ചേർത്തു"
        ISSUE_SUBMITTED_TEXT ->  "ഹോൾഡ് ഓൺ ചെയ്യുക! നിങ്ങളുടെ പ്രശ്നം പരിഹരിക്കാൻ ഞങ്ങൾ പ്രവർത്തിക്കുന്നു"
        CHOOSE_AN_OPTION ->  "തുടരാൻ ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക"
        IMAGE_ADDED ->  "ചിത്രം ചേർത്തു"
        DONE ->  "ചെയ്തു"
        RECORD_VOICE_NOTE ->  "വോയ്സ് നോട്ട് രേഖപ്പെടുത്തുക"
        HELP_AND_SUPPORT ->  "സഹായവും പിന്തുണയും"
        MORE_OPTIONS ->  "കൂടുതൽ ഓപ്ഷനുകൾ"
        ONGOING_ISSUES ->  "തുടരുന്ന പ്രശ്നങ്ങൾ"
        RESOLVED_ISSUES ->  "പരിഹരിച്ച പ്രശ്നങ്ങൾ"
        RESOLVED_ISSUE ->  "പരിഹരിച്ച പ്രശ്നം"
        ONGOING_ISSUE ->  "നടന്നുകൊണ്ടിരിക്കുന്ന പ്രശ്നങ്ങൾ"
        LOST_ITEM ->  "നഷ്ടപ്പെട്ട ഇനം"
        RIDE_RELATED_ISSUE ->  "റൈഡുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        APP_RELATED_ISSUE ->  "ആപ്പുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        FARE_RELATED_ISSUE ->  "യാത്രാക്കൂലിയുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        MAX_IMAGES ->  "പരമാവധി 3 ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യാം"
        ISSUE_NUMBER ->  "ഇഷ്യൂ നം   "
        REMOVE_ISSUE ->  "പ്രശ്നം നീക്കം ചെയ്യുക" 
        CALL_SUPPORT_NUMBER ->  "സപ്പോർട് വേണം"
        YEARS_AGO ->  " വർഷങ്ങൾക്ക് മുമ്പ്"
        MONTHS_AGO ->  " മാസം മുമ്പ്"
        DAYS_AGO ->  " ദിവസങ്ങൾക്ക് മുൻപ്"
        HOURS_AGO ->  " മണിക്കൂർ മുമ്പ്"
        MIN_AGO ->  " മിനിറ്റ് മുമ്പ്"
        SEC_AGO ->  " സെക്കന്റ് മുമ്പ്"
        LOADING ->  "ലോഡിംഗ്"
        APP_RELATED ->  "ആപ്പ് ബന്ധപ്പെട്ടത്"
        FARE ->  "യാത്രാക്കൂലിയുമായി ബന്ധപ്പെട്ടത്"
        RIDE_RELATED ->  "റൈഡ് ബന്ധപ്പെട്ടത്"
        LOST_AND_FOUND ->  "നഷ്ടപ്പെട്ടതും കണ്ടെത്തിയതും"
        REPORT_LOST_ITEM ->  "നഷ്ടപ്പെട്ട ഇനം റിപ്പോർട്ട് ചെയ്യുക"
        REGISTERED_ADDRESS _ ->  "രേഖപ്പെടുത്തിയ വിലാസം"
        REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL _ ->  "സ്റ്റാലിയൻ ബിസിനസ് സെന്റർ, നമ്പർ 444, 3rd & 4th നിലകൾ, 18th മെയിൻ, 6th ബ്ലോക്ക്, കോറമംഗല, ബെംഗളൂരു, കർണാടക- 560095, ഇന്ത്യ"
        SELECT_YOUR_GENDER ->  "നിങ്ങളുടെ ലിംഗഭേദം തിരഞ്ഞെടുക്കുക"
        FEMALE ->  "സ്ത്രീ"
        MALE ->  "പുരുഷൻ"
        PREFER_NOT_TO_SAY ->  "പറയാൻ ആഗ്രഹിക്കുന്നില്ല"
        GENDER ->  "ലിംഗഭേദം"
        SET_NOW ->  "ഇപ്പോൾ സജ്ജമാക്കുക"
        COMPLETE_YOUR_PROFILE_AND_FIND_MORE_RIDES ->  "പ്രൊഫൈൽ പൂർത്തിയാക്കി, കൂടുതൽ റൈഡുകൾ ലഭിക്കൂ!"
        UPDATE_NOW ->  "അപ്ഡേറ്റ് ചെയ്യൂ"
        CONFIRM ->  "സ്ഥിരീകരിക്കുക"
        GENDER_UPDATED ->  "ലിംഗഭേദം അപ്ഡേറ്റ് ചെയ്തു"
        ZONE_CANCEL_TEXT_DROP ->  "നിങ്ങളുടെ ഉപഭോക്താവ് കൃത്യസമയത്ത് മെട്രോ സ്റ്റേഷനിൽ എത്താനുള്ള തിരക്കിലായിരിക്കാം! \n റദ്ദാക്കരുതെന്ന് ഞങ്ങൾ നിങ്ങളോട് അഭ്യർത്ഥിക്കുന്നു."
        ZONE_CANCEL_TEXT_PICKUP ->  "നിങ്ങളുടെ ഉപഭോക്താവ് അവരുടെ ലക്ഷ്യസ്ഥാനത്ത് എത്താനുള്ള തിരക്കിലായിരിക്കാം. \n റദ്ദാക്കരുതെന്ന് ഞങ്ങൾ നിങ്ങളോട് അഭ്യർത്ഥിക്കുന്നു."
        REGISTERED_ADDRESS_DESCRIPTION _ ->  "Stallion Business Centre, No. 444, 3rd & 4th Floor, 18th Main, 6th Block, Koramangala, Bengaluru, Karnataka- 560095, India"
        RANKINGS ->  "മത്സരം"
        GETTING_THE_LEADERBOARD_READY ->  "ലീഡർബോർഡ് സൃഷ്ടിക്കുന്നു!"
        PLEASE_WAIT_WHILE_WE_UPDATE_THE_DETAILS ->  "ഞങ്ങൾ വിശദാംശങ്ങൾ അപ്ഡേറ്റ് ചെയ്യുമ്പോൾ ദയവായി കാത്തിരിക്കുക"
        LAST_UPDATED ->  "അവസാന പരിഷ്കാരം: "
        CONGRATULATIONS_YOU_ARE_RANK ->  "അഭിനന്ദനങ്ങൾ ! നിങ്ങളുടെ റാങ്ക് ആണ് "
        YOU ->  " (നിങ്ങൾ)"
        DAILY ->  "ദിവസേന"
        WEEKLY ->  "പ്രതിവാരം"
        ACCEPT_RIDES_TO_ENTER_RANKINGS ->  "റാങ്കിംഗിൽ പ്രവേശിക്കാൻ റൈഡുകൾ സ്വീകരിക്കുക!"
        OTP_HAS_BEEN_RESENT ->  "OTP വീണ്ടും അയച്ചു"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_RESENDING_OTP ->  "OTP ഇൻപുട്ട് പരിധി എത്തി, OTP വീണ്ടും അയയ്‌ക്കാൻ ശ്രമിക്കുക"
        OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER ->  "OTP വീണ്ടും അയയ്ക്കുന്നതിനുള്ള പരിധി എത്തിയിരിക്കുന്നു, ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക"
        OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN ->  "OTP പേജ് കാലഹരണപ്പെട്ടു, ദയവായി OTP വീണ്ടും അഭ്യർത്ഥിക്കുക"
        SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN ->  "ചില സാങ്കേതിക പ്രശ്നം സംഭവിച്ചു, വീണ്ടും ശ്രമിക്കുക"
        INVALID_REFERRAL_CODE ->  "അസാധുവായ റഫറൽ കോഡ്"
        ISSUE_REMOVED_SUCCESSFULLY ->  "പ്രശ്നം വിജയകരമായി പരിഹരിച്ചു"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER ->  "OTP ഇൻപുട്ട് പരിധി എത്തിയിരിക്കുന്നു, ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക"
        TOO_MANY_ATTEMPTS_PLEASE_TRY_AGAIN_LATER ->  "നിങ്ങൾ വളരെയധികം അസാധുവായ ശ്രമങ്ങൾ നടത്തി, ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക"
        INVALID_REFERRAL_NUMBER ->  "അസാധുവായ റഫറൽ നമ്പർ"
        SOMETHING_WENT_WRONG_TRY_AGAIN_LATER ->  "ചില സാങ്കേതിക പ്രശ്നം സംഭവിച്ചു, ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക"
        WAIT_TIME ->  "കാത്തിരിപ്പ് സമയം"
        WAIT_TIMER ->  "ടൈമർ കാത്തിരിക്കുക"
        HOW_LONG_WAITED_FOR_PICKUP ->  "പിക്കപ്പിൽ നിങ്ങൾ\nഎത്ര നേരം കാത്തിരുന്നുവെന്ന് കാണിക്കുന്നു."
        CUSTOMER_WILL_PAY_FOR_EVERY_MINUTE ->  "ഉപഭോക്താവ് \nആദ്യ {} മിനിറ്റിന് ശേഷം ഓരോ മിനിറ്റിലും കാത്തിരിപ്പ് സമയത്തിന് ₹1.5\n നൽകും."
        OTHERS ->  "മറ്റുള്ളവ"
        ENTER_SECOND_SIM_NUMBER ->  "രണ്ടാമത്തെ സിം നമ്പർ നൽകുക"
        ALTERNATE_NUMBER ->  "ഇതര നമ്പർ"
        SELECT_THE_LANGUAGES_YOU_CAN_SPEAK ->  "നിങ്ങൾക്ക് സംസാരിക്കാൻ കഴിയുന്ന ഭാഷകൾ തിരഞ്ഞെടുക്കുക"
        LIMIT_EXCEEDED_FOR_ALTERNATE_NUMBER ->  "അൽപസമയത്തിനു ശേഷം വീണ്ടും ശ്രമിക്കുക"
        ALTERNATE_NUMBER_CANNOT_BE_ADDED ->  "ഇതര നമ്പർ ചേർക്കാൻ കഴിയില്ല"
        OTP_RESENT -> "ഒടിപി വീണ്ടും അയച്ചിരിക്കുന്നു"
        OTP_RESEND_LIMIT_EXCEEDED ->  "OTP വീണ്ടും അയയ്ക്കുന്നതിനുള്ള പരിധി കവിഞ്ഞു"
        SEDAN ->  "സെഡാൻ"
        SUV ->  "SUV"
        HATCHBACK ->  "ഹാച്ച്ബാക്ക്"
        AUTO_RICKSHAW ->  "ഓട്ടോ റിക്ഷ"
        TAXI ->  "നോൺ എസി ടാക്സി"
        TAXI_PLUS ->  "എസി ടാക്സി"
        MY_PROFILE ->  "എന്റെ പ്രൊഫൈൽ"
        SETTINGS ->  "സെറ്റിംഗ്സ്"
        REG_NUMBER ->  "രജിസ്‌ട്രേഷൻ നമ്പർ"
        TYPE ->  "തരം"
        MODEL_NAME ->  "മോഡലിന്റെ പേര്"
        COLOUR ->  "നിറം"
        BADGES -> "ব্যাজ"
        CANCELLATION_RATE ->  "റദ്ദാക്കൽ നിരക്ക്"
        RIDES_CANCELLED ->  "റദ്ദാക്കിയ റൈഡുകളുടെ എണ്ണം"
        EARNINGS_MISSED ->  "നഷ്‌ടമായ വരുമാനം"
        SUMMARY ->  "റിപ്പോർട്ട്"
        NAMMA_BONUS -> "നമ്മ ബോണസ്"
        TRIPS_COMPLETED ->  "പൂർത്തിയായ യാത്രകൾ"
        CALL_CUSTOMER_SUPPORT ->  "കസ്റ്റമർ സപ്പോർട്ടിലേക്ക് വിളിക്കുക"
        EDIT_RC ->  "RC എഡിറ്റ് ചെയ്യുക"
        DELETE_RC ->  "RC ഇല്ലാതാക്കുക"
        DEACTIVATE_RC ->  "RC നിർജ്ജീവമാക്കുക"
        ACTIVATE_RC ->  "RC സജീവമാക്കുക"
        ACTIVE_RC_ON_ANOTHER_DRIVER ->  " മറ്റൊരു ഡ്രൈവർ അക്കൗണ്ടിൽ സജീവമാണ്!"
        CALL_DRIVER_OR_CONTACT_SUPPORT ->  "ആർ‌സി നിർജ്ജീവമാക്കാൻ ഡ്രൈവറെ വിളിക്കുക അല്ലെങ്കിൽ ഡ്രൈവർക്ക് ലഭ്യമല്ലെങ്കിൽ പിന്തുണയുമായി ബന്ധപ്പെടുക"
        CALL_DRIVER ->  "ഡ്രൈവറെ വിളിക്കുക"
        SKIP ->  "ഒഴിവാക്കുക"
        ACTIVE_STR ->  "സജീവമാണ്"
        INACTIVE_RC ->  "നിഷ്ക്രിയം"
        CONFIRMATION_FOR_DELETING_RC ->  "നിങ്ങളുടെ RC ഇല്ലാതാക്കണമെന്ന് തീർച്ചയാണോ"
        CONFIRMATION_FOR_DEACTIVATING_RC ->  "നിങ്ങളുടെ RC നിർജ്ജീവമാക്കണമെന്ന് തീർച്ചയാണോ- "
        CONFIRMATION_FOR_ACTIVATING_RC ->  "RC സജീവമാക്കണമെന്ന് തീർച്ചയാണോ- "
        YES_DELETE ->  "അതെ, ഇല്ലാതാക്കുക"
        ADD_NEW_RC ->  "RC ചേർക്കുക"
        CONNECT_CALL_ANONYMOUSLY -> "നിങ്ങളെ ഡ്രൈവറുമായി അജ്ഞാതമായി ബന്ധിപ്പിക്കാൻ ഞങ്ങൾ ശ്രമിക്കും, ആർസി നിർജ്ജീവമാക്കാൻ അഭ്യർത്ഥിക്കുന്നതിന് മുമ്പ് ദയവായി സ്വയം പരിചയപ്പെടുത്തുക."
        YES_ACTIVATE ->  "അതെ, സജീവമാക്കുക"
        YES_DEACTIVATE ->  "അതെ, നിർജ്ജീവമാക്കുക"
        THIS_WILL_DEACTIVATE_CURRENTLY_ACTIVE_RC ->  "ഇത് നിങ്ങളുടെ നിലവിൽ സജീവമായ RC നിർജ്ജീവമാക്കും."
        REMOVED ->  "നീക്കം ചെയ്തു"
        IS_ACTIVE_NOW ->  " ഇപ്പോൾ സജീവമാണ്."
        DEACTIVATED ->  "നിർജ്ജീവമാക്കി"
        LANGUAGE_UPDATED ->  "ഭാഷ അപ്ഡേറ്റ് ചെയ്തു"
        SINGLE_RC_CANNOT_BE_DELETED ->  "സിംഗിൾ RC ഇല്ലാതാക്കാൻ കഴിയില്ല"
        LATE_NIGHT_TRIPS ->  "രാത്രി വൈകിയുള്ള യാത്രകൾ"
        ABOUT_ME ->  "എന്നെ കുറിച്ച്"
        ABOUT_VEHICLE ->  "വാഹനത്തെക്കുറിച്ച്"
        ADD ->  "ചേർക്കുക"
        YEARS_OLD ->  "yവയസ്സ്"
        HOMETOWN ->  "ഹോം ടൗൺn"
        MISSED_OPPORTUNITY ->  "അവസരങ്ങൾ നഷ്ടപ്പെടുത്തി"
        HOW_OLD_IS_YOUR_VEHICLE ->  "നിങ്ങളുടെ വാഹനത്തിന് എത്ര പഴക്കമുണ്ട് (വർഷങ്ങളിൽ)?"
        ENTER_NAME_OF_VEHICLE ->  "നിങ്ങളുടെ വാഹനത്തിന്റെ പേര് നൽകുക"
        NEW_ ->  "പുതിയത്"
        TODAY ->  "ഇന്ന്"
        OKAY -> "ശരി ശരി"
        NO_PAYMENT_HISTORY_AVAILABLE ->  "പേയ്‌മെന്റ് ചരിത്രമൊന്നും ലഭ്യമല്ല"
        ENTER_AADHAAR_NUMBER ->  "ആധാർ നമ്പർ/യുഐഡി നൽകുക"
        ENTER_AADHAAR_OTP_ ->  "ആധാർ OTP നൽകുക"
        AADHAAR_LINKING_REQUIRED ->  "ആധാർ ലിങ്കിംഗ് ആവശ്യമാണ്"
        AADHAAR_LINKING_REQUIRED_DESCRIPTION _ ->  "യാത്രി സതിക്കായി ഡ്രൈവിംഗ് ആരംഭിക്കാൻ, ദയവായി \n നിങ്ങളുടെ ആധാർ ഐഡി ലിങ്ക് ചെയ്യുക"
        BY_CLICKING_THIS_YOU_WILL_BE_AGREEING_TO_OUR_TC ->  "തുടരുക ക്ലിക്കുചെയ്യുന്നതിലൂടെ, നിങ്ങൾ ഞങ്ങളുടെ &nbsp; <a href=\"\">T&Cs</a>"
        TERMS_AND_CONDITIONS_SHORT ->  "T&C"
        TC_TAIL ->  "അംഗീകരിക്കുന്നു"
        OTP_SENT_TO_AADHAAR_NUMBER -> "നിങ്ങളുടെ ആധാറുമായി ലിങ്ക് ചെയ്‌തിരിക്കുന്ന മൊബൈൽ നമ്പറിലേക്ക് OTP അയച്ചു"
        ENTER_SIX_DIGIT_OTP ->  "ആറക്ക OTP നൽകുക"
        LINK_AADHAAR_ID ->  "ലിങ്ക് ആധാർ ഐഡി"
        AADHAAR_ALREADY_LINKED ->  "ആധാർ ഇതിനകം ലിങ്ക് ചെയ്തിട്ടുണ്ട്"
        OPTIONAL ->  " (ഓപ്ഷണൽ)"
        DOWNLOAD_STATEMENT ->  "പ്രസ്താവന ഡൗൺലോഡ് ചെയ്യുക"
        SELECT_A_DATE_RANGE ->  "പ്രസ്താവന ഡൗൺലോഡ് ചെയ്യുന്നതിന് ഒരു തീയതി ശ്രേണി തിരഞ്ഞെടുക്കുക"
        FEE_PAYMENT_HISTORY ->  "ഫീസ് പേയ്‌മെന്റ് ചരിത്രം"
        LANGUAGES_SPOKEN ->  "സംസാരിക്കുന്ന ഭാഷകൾ"
        VIEW_PAYMENT_HISTORY ->  "പേയ്മെന്റ് ചരിത്രം കാണുക"
        RIDE_TYPE ->  "റൈഡ് തരം"
        PLACE_CALL_REQUEST ->  "കോൾ അഭ്യർത്ഥന സ്ഥാപിക്കുക"
        RC_STATUS ->  "RC നില"
        RATED_BY_USERS1 ->  ""
        RATED_BY_USERS2 ->  "ഉപയോക്താക്കൾ റേറ്റുചെയ്തത്"
        MONTHS ->  "മാസങ്ങൾ"
        RC_ADDED_SUCCESSFULLY ->  "രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ് വിജയകരമായി ചേർത്തു"
        OFFER_APPLIED ->  "ഓഫർ പ്രയോഗിച്ചു"
        YOUR_EARNINGS ->  "നിങ്ങളുടെ വരുമാനം"
        NUMBER_OF_RIDES ->  "റൈഡുകളുടെ എണ്ണം"
        FARE_BREAKUP ->  "ഫെയർ ബ്രേക്കപ്പ്"
        MY_PLAN ->  "എന്റെ പ്ലാൻ"
        YOUR_DUES ->  "നിങ്ങളുടെ കുടിശ്ശിക"
        YOUR_DUES_DESCRIPTION ->  "നിങ്ങളുടെ കുടിശ്ശിക തീർക്കാൻ നിങ്ങൾ ഒരു ഓട്ടോപേ സജ്ജീകരിച്ചു. നിങ്ങളുടെ കുടിശ്ശിക എപ്പോഴും കൃത്യസമയത്ത് അടച്ചിട്ടുണ്ടെന്ന് ഉറപ്പാക്കാൻ ഞങ്ങൾ സ്വയമേവ ശ്രമിക്കും."
        CURRENT_DUES ->  "നിലവിലെ കുടിശ്ശിക"
        YOUR_LIMIT ->  "നിങ്ങളുടെ പരിധി"
        DUE_DETAILS ->  "കൃത്യമായ വിശദാംശങ്ങൾ"
        TRIP_DATE ->  "യാത്രാ തീയതി"
        AMOUNT ->  "തുക"
        VIEW_DUE_DETAILS ->  "തീരുമാനമായ വിശദാംശങ്ങൾ കാണുക"
        SETUP_AUTOPAY ->  "ഓട്ടോപേ സജ്ജീകരിക്കുക"
        CURRENT_PLAN ->  "നിലവിലെ പ്ലാൻ"
        ALTERNATE_PLAN ->  "ഇതര പദ്ധതി"
        AUTOPAY_DETAILS ->  "സ്വയമേവ പണമടയ്ക്കൽ വിശദാംശങ്ങൾ"
        CANCEL_AUTOPAY_STR ->  "ഓട്ടോപേ റദ്ദാക്കുക"
        WE_MIGHT_BE_LOST ->  "അയ്യോ! നമ്മൾ നഷ്ടപ്പെട്ടേക്കാം"
        EXEPERIENCING_ERROR ->  "പിശക് അനുഭവപ്പെടുന്നു"
        ENJOY_THESE_BENEFITS ->  "ഈ ആനുകൂല്യങ്ങൾ ആസ്വദിക്കൂ"
        CHOOSE_YOUR_PLAN _ ->  "ഇപ്പോൾ ഒരു പ്ലാൻ തിരഞ്ഞെടുക്കുക!"
        SKIP_FOR_NOW ->  "ഇപ്പോൾ ഒഴിവാക്കുക"
        SEVEN_DAY_FREE_TRIAL_ACTIVATED ->  "7 ദിവസത്തെ സൗജന്യ ട്രയൽ സജീവമാക്കി!"
        TAKE_UNLIMITED_RIDES_FOR_THE_NEXT_SEVEN_DAYS ->  "ആദ്യത്തെ 7 ദിവസത്തേക്ക് പരിധിയില്ലാത്ത റൈഡുകൾ എടുക്കുക"
        EVERY_RIDE_AT_ZERO_COMMISSION ->  "ZERO കമ്മീഷനിലെ ഓരോ റൈഡും!"
        EARN_UPTO_PER_DAY ->  "ഒരു ദിവസം ₹{} വരെ സമ്പാദിക്കുക!"
        HOW_THIS_WORKS ->  "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു"
        SIGN_UP_FOR_AUTOPAY_BY_PAYING_JUST ->  "വെറും ₹1 നൽകി സ്വയമേവ പണമടയ്ക്കാൻ സൈൻ അപ്പ് ചെയ്യുക"
        GET_REMINDED_ABOUT_YOUR_PLAN_SETUP ->  "നിങ്ങളുടെ പ്ലാൻ സജ്ജീകരണത്തെക്കുറിച്ച് ഓർമ്മപ്പെടുത്തുക"
        FREE_TRIAL_REMINDER ->  "ദിവസം 5: സൗജന്യ ട്രയൽ റിമൈൻഡർ"
        PLAN_STARTS ->  "ദിവസം 7: പ്ലാൻ ആരംഭിക്കുന്നു"
        EASY_AUTOMATIC_PAYMENTS_START ->  "എളുപ്പമുള്ള, സ്വയമേവയുള്ള പേയ്‌മെന്റുകൾ ആരംഭിക്കുന്നു"
        FREE_UNTIL ->  " വരെ സൗജന്യം"
        PER_RIDE ->  "ഓരോ യാത്രയ്ക്കും"
        PER_DAY ->  "പ്രതിദിനം"
        OFFER ->  "ഓഫർ"
        OFFERS ->  "ഓഫറുകൾ"
        YOU_ARE_ON_THE_FREE_TRIAL ->  "നിങ്ങൾ സൗജന്യ ട്രയലിലാണ്"
        SETUP_AUTOPAY_BEFORE_THE_TRAIL_PERIOD_EXPIRES ->  "ട്രയൽ കാലയളവ് അവസാനിക്കുന്നതിന് മുമ്പ് സ്വയമേവ പണമടയ്ക്കൽ സജ്ജീകരിക്കുക"
        GET_FREE_TRAIL_UNTIL ->  "വരെ സൗജന്യ ട്രയൽ നേടൂ"
        CLEAR_DUES ->  "കുടിശ്ശിക മായ്‌ക്കുക"
        PAYMENT_PENDING_ALERT ->  "⚠️ പേയ്‌മെന്റ് തീർച്ചപ്പെടുത്തിയിട്ടില്ല! ⚠️"
        PAYMENT_PENDING_ALERT_DESC _ ->  "നമ്മ യാത്രിയിൽ യാത്ര തുടരാൻ, നിങ്ങളുടെ പേയ്‌മെന്റ് കുടിശ്ശിക തീർക്കുക"
        LOW_ACCOUNT_BALANCE ->  "കുറഞ്ഞ അക്കൗണ്ട് ബാലൻസ്"
        LOW_ACCOUNT_BALANCE_DESC ->  "നിങ്ങളുടെ ബാങ്ക് അക്കൗണ്ട് ബാലൻസ് കുറവാണ്. തടസ്സമില്ലാത്ത റൈഡുകൾ ആസ്വദിക്കാൻ പണം ചേർക്കുക."
        OKAY_GOT_IT ->  "ശരി, മനസ്സിലായി"
        LIMITED_TIME_OFFER ->  "നിങ്ങൾക്ക് പരിമിതമായ സമയ ഓഫർ!"
        JOIN_NOW ->  "ഇപ്പോൾ ചേരുക"
        AUTOMATIC_PAYMENTS_WILL_APPEAR_HERE ->  "സ്വയമേവയുള്ള പേയ്‌മെന്റുകൾ ഇവിടെ ദൃശ്യമാകും"
        MANUAL_PAYMENTS ->  "മാനുവൽ പേയ്‌മെന്റുകൾ"
        MANUAL_PAYMENTS_WILL_APPEAR_HERE ->  "മാനുവൽ പേയ്‌മെന്റുകൾ ഇവിടെ ദൃശ്യമാകും"
        NO_AUTOMATIC_PAYMENTS_DESC ->  "നിങ്ങളിൽ നിന്ന് പണം ഈടാക്കിയാൽ നിങ്ങളുടെ ഓട്ടോപേ ചരിത്രം ഇവിടെ ദൃശ്യമാകും"
        NO_MANUAL_PAYMENTS_DESC ->  "കുടിശ്ശിക തീർക്കുന്നതിനുള്ള നിങ്ങളുടെ പേയ്‌മെന്റ് ചരിത്രം എന്തെങ്കിലും ഉണ്ടെങ്കിൽ ഇവിടെ ദൃശ്യമാകും."
        PAYMENT_HISTORY ->  "പേയ്‌മെന്റ് ചരിത്രം"
        TAP_A_PLAN_TO_VIEW_DETAILS ->  "വിശദാംശങ്ങൾ കാണാൻ ഒരു പ്ലാൻ ടാപ്പ് ചെയ്യുക"
        HOW_IT_WORKS _ ->  "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു"
        ZERO_COMMISION ->  "ZERO കമ്മീഷൻ"
        EARN_TODAY_PAY_TOMORROW ->  "ഇന്ന് സമ്പാദിക്കുക, നാളെ പണമടയ്ക്കുക"
        PAY_ONLY_IF_YOU_TAKE_RIDES ->  "നിങ്ങൾ സവാരി നടത്തിയാൽ മാത്രം പണം നൽകുക"
        PLANS ->  "പ്ലാൻസ്"
        PLAN ->  "പ്ലാൻ ചെയ്യുക"
        DAY ->  "ദിവസം"
        MANAGE_PLAN ->  "പ്ലാൻ നിയന്ത്രിക്കുക"
        VIEW_AUTOPAY_DETAILS ->  "ഓട്ടോപേ വിശദാംശങ്ങൾ കാണുക"
        SWITCH_AND_SAVE ->  "സ്വിച്ച് ചെയ്ത് സംരക്ഷിക്കുക"
        SWITCH_AND_SAVE_DESC ->  "നിങ്ങൾ ഇന്ന് 7-ലധികം റൈഡുകൾ പൂർത്തിയാക്കി. ഡെയ്‌ലി അൺലിമിറ്റഡ് പ്ലാനിലേക്ക് മാറുന്നതിലൂടെ ₹10 വരെ ലാഭിക്കൂ"
        SWITCH_NOW ->  "ഇപ്പോൾ മാറുക"
        PAYMENT_MODE_CHANGED_TO_MANUAL ->  "പേയ്‌മെന്റ് മോഡ് മാനുവലിലേക്ക് മാറ്റി"
        PAYMENT_MODE_CHANGED_TO_MANUAL_DESC ->  "നിങ്ങളുടെ UPI ഓട്ടോപേ താൽക്കാലികമായി നിർത്തി. നിങ്ങൾക്ക് കുടിശ്ശിക നേരിട്ട് തീർക്കാനാകും."
        AUTOPAY_PAYMENTS ->  "ഓട്ടോപേ പേയ്‌മെന്റുകൾ"
        TRANSACTION_ON ->  "ഇടപാട് ഓൺ"
        SUCCESS ->  "വിജയം"
        RIDES_TAKEN_ON ->  "റൈഡുകൾ എടുത്തു"
        JOIN_PLAN ->  "പദ്ധതിയിൽ ചേരുക"
        JOIN_NAMMAA_YATRI ->  "നമ്മ യാത്രിയിൽ ചേരൂ"
        CANCEL_AUTOPAY_AND_PAY_MANUALLY ->  "സ്വയം പണമടയ്ക്കൽ റദ്ദാക്കി സ്വമേധയാ പണമടയ്ക്കുക"
        PLAN_ACTIVATED_SUCCESSFULLY ->  "പ്ലാൻ വിജയകരമായി സജീവമാക്കി"
        DUES_CLEARED_SUCCESSFULLY ->  "കുടിശ്ശിക വിജയകരമായി തീർത്തു"
        NOT_PLANNING_TO_TAKE_RIDES ->  "റൈഡുകൾ എടുക്കാൻ ആസൂത്രണം ചെയ്യുന്നില്ലേ?"
        RETRY_PAYMENT_STR ->  "പേയ്‌മെന്റ് വീണ്ടും ശ്രമിക്കുക"
        PAUSE_AUTOPAY_STR ->  "ഓട്ടോപേ താൽക്കാലികമായി നിർത്തുക"
        SETUP_AUTOPAY_STR ->  "ഓട്ടോപേ പുനരാരംഭിക്കുക"
        VIEW_RIDE_DETAILS ->  "റൈഡ് വിശദാംശങ്ങൾ കാണുക"
        ACCOUNT ->  "അക്കൗണ്ട്"
        AUTOPAY_IS_NOT_ENABLED_YET ->  "ഓട്ടോപേ ഇതുവരെ പ്രവർത്തനക്ഷമമാക്കിയിട്ടില്ല!"
        ENABLE_AUTOPAY_DESC ->  "തടസ്സരഹിതമായ പേയ്‌മെന്റുകൾ ആരംഭിക്കാൻ ഇപ്പോൾ സ്വയമേവ പണമടയ്ക്കൽ പ്രവർത്തനക്ഷമമാക്കുക!"
        ENABLE_AUTOPAY_NOW ->  "ഇപ്പോൾ സ്വയമേവ പണമടയ്ക്കൽ പ്രവർത്തനക്ഷമമാക്കുക"
        AUTOPAY_SETUP_PENDING_STR ->  "സ്വയമേവ പണമടയ്ക്കൽ സജ്ജീകരണം തീർച്ചപ്പെടുത്തിയിട്ടില്ല!"
        AUTOPAY_PENDING_DESC_STR ->  "കാത്തിരിക്കുക അല്ലെങ്കിൽ പണമടയ്ക്കാൻ വീണ്ടും ശ്രമിക്കുക. അധിക തുക തിരികെ നൽകും."
        REFRESH_STR ->  "പുതുക്കുക"
        TRANSACTION_DETAILS ->  "ഇടപാട് വിശദാംശങ്ങൾ"
        RIDE_DETAILS ->  "റൈഡ് വിശദാംശങ്ങൾ"
        MY_PLAN_TITLE _ ->  "ഞങ്ങളുടെ യാത്രാ പദ്ധതികൾ"
        SWITCH_TO ->  "ഇതിലേക്ക് മാറുക {}"
        PLEASE_TRY_AGAIN ->  "ദയവായി വീണ്ടും ശ്രമിക്കുക"
        PLAN_NOT_FOUND ->  "പ്ലാൻ കണ്ടെത്തിയില്ല"
        MANDATE_NOT_FOUND ->  "മാൻഡേറ്റ് കണ്ടെത്തിയില്ല"
        ACTIVE_MANDATE_EXISTS ->  "സജീവമായ മാൻഡേറ്റ് ഇതിനകം നിലവിലുണ്ട്"
        NO_ACTIVE_MANDATE_EXIST ->  "സജീവമായ മാൻഡേറ്റ് നിലവിലില്ല"
        NO_PLAN_FOR_DRIVER ->  "പ്ലാൻ ഒന്നും കണ്ടെത്തിയില്ല"
        INVALID_PAYMENT_MODE ->  "അസാധുവായ പേയ്‌മെന്റ് മോഡ്"
        INVALID_AUTO_PAY_STATUS ->  "അസാധുവായ ഓട്ടോപേ സ്റ്റാറ്റസ്"
        MAX_AMOUNT ->  "പരമാവധി തുക"
        FREQUENCY ->  "ഫ്രീക്വൻസി"
        STATRED_ON ->  "ആരംഭിച്ചു"
        EXPIRES_ON ->  "കാലഹരണപ്പെടുന്നു"
        SWITCHED_PLAN ->  "സ്വിച്ച്ഡ് പ്ലാൻ"
        PAYMENT_CANCELLED ->  "നിങ്ങൾ യുപിഐ ഓട്ടോപേ റദ്ദാക്കി. നിങ്ങൾക്ക് കുടിശ്ശിക സ്വമേധയാ ക്ലിയർ ചെയ്യാം"
        UPI_AUTOPAY_S ->  "UPI സ്വയമേവ പണമടയ്ക്കുക"
        MANUAL_PAYMENT_STR ->  "മാനുവൽ പേയ്മെന്റ്"
        DAILY_UNLIMITED ->  "ദിവസേന അൺലിമിറ്റഡ്"
        DAILY_PER_RIDE ->  "ദിവസേന ഓരോ റൈഡിനും"
        DAILY_UNLIMITED_PLAN_DESC ->  "എല്ലാ ദിവസവും പരിധിയില്ലാത്ത റൈഡുകൾ ആസ്വദിക്കൂ"
        DAILY_PER_RIDE_PLAN_DESC ->  "പ്രതിദിനം പരമാവധി ₹35 വരെ"
        PAY_TO_JOIN_THIS_PLAN ->  "പ്ലാനിൽ ചേരാൻ ₹1 അടയ്ക്കുക"
        OFFERS_NOT_APPLICABLE ->  "പൂർത്തിയാക്കിയില്ലെങ്കിൽ ഓഫറുകൾ ബാധകമല്ല"
        PAUSED_STR ->  "താൽക്കാലികമായി നിർത്തി"
        PENDING_STR ->  "തീർപ്പാക്കാത്തത്"
        PLAN_SWITCHED_TO ->  "പ്ലാൻ സ്വിച്ചുചെയ്തു"
        SWITCH_PLAN_STR ->  "സ്വിച്ച് പ്ലാൻ?"
        OFFERS_APPLICABLE_ON_DAILY_UNLIMITED ->  "കുറിപ്പ്: ദൈനംദിന പരിധിയില്ലാത്ത പ്ലാനിൽ ഓട്ടോപെ സജ്ജമാക്കിയിട്ടുണ്ടെങ്കിൽ മാത്രമേ ബാധകമായ ഓഫറുകൾ."
        DAILY_UNLIMITED_OFFER_NOT_AVAILABLE ->  "കുറിപ്പ്: ദൈനംദിന പരിധിയില്ലാത്ത ഓഫറുകൾ ഈ പ്ലാനിൽ ബാധകമല്ല!"
        NO_RIDES_NO_CHARGE ->  "നിങ്ങൾ സവാരി നടത്തിയാൽ മാത്രം പണം നൽകുക" 
        GET_SPECIAL_OFFERS _ ->  "Get Special Offers"
        VALID_ONLY_IF_PAYMENT ->  "valid only if payment is completed"
        HELP_STR ->  "HELP"
        REFRESH_STRING ->  "Refresh"
        CHAT_FOR_HELP ->  "സഹായത്തിനായി ചാറ്റ് ചെയ്യുക"
        VIEW_FAQs ->  "പതിവുചോദ്യങ്ങൾ കാണുക"
        FIND_HELP_CENTRE _ ->  "സഹായ കേന്ദ്രം കണ്ടെത്തുക"
        CONTACT ->  "ബന്ധപ്പെടുക"
        GO_TO_LOCATION ->  "ലൊക്കേഷനിലേക്ക് പോകുക"
        NO_HELP_CENTER_IS_ACTIVE_NOW ->  "ഒരു സഹായ കേന്ദ്രവും ഇപ്പോൾ സജീവമല്ല"
        HELP_CENTERS_LOCATION_WILL_APPEAR_HERE_ONCE_THEY_ARE_ACTIVE ->  "സഹായ കേന്ദ്രങ്ങൾ സജീവമായാൽ അവയുടെ ലൊക്കേഷനുകൾ ഇവിടെ ദൃശ്യമാകും"
        SUPPORT ->  "പിന്തുണ"
        NEED_HELP_JOINING_THE_PLAN ->  "പദ്ധതിയിലോ ഓട്ടോപേയ്യിലോ ചേരാൻ സഹായം ആവശ്യമുണ്ടോ?"
        NEED_HELP ->  "സഹായം ആവശ്യമുണ്ട്?"
        SETUP_AUTOPAY_NOW_TO_GET_SPECIAL_DISCOUNTS -> "പ്രത്യേക കിഴിവുകൾ ലഭിക്കുന്നതിന് ഇപ്പോൾ ഓട്ടോപേ അപ്പ് സജ്ജമാക്കുക"
        SETUP_NOW ->  "ഇപ്പോൾ സജ്ജീകരണം"
        GO_TO_VEHICLE_DETAILS ->  "വാഹന വിശദാംശങ്ങളിലേക്ക് പോകുക"
        CLOSE -> "അടയ്ക്കുക"
        RC_DEACTIVATED ->  "RC നിർജ്ജീവമാണ്"
        RC_DEACTIVATED_DETAILS ->  "നിങ്ങളുടെ RC നിലവിൽ മറ്റൊരു ഡ്രൈവറുടെ അക്കൗണ്ടിൽ സജീവമാണ്. റൈഡുകൾ ആരംഭിക്കാൻ ഒരു RC സജീവമാക്കുക"
        CUSTOMER_HAS_LOW_MOBILITY -> "ഗ്രാഹകൻ കുറഞ്ഞ ചാലനത്തിൽ നിന്നുണ്ട്"
        CUSTOMER_HAS_DISABILITY -> "ഗ്രാഹകൻ ഒരു പ്രതിബന്ധം ഉണ്ട്"
        CUSTOMER_HAS_LOW_VISION -> "ഗ്രാഹകൻ കുറഞ്ഞ ദർശനം ഉണ്ട്"
        CUSTOMER_HAS_HEARING_IMPAIRMENT -> "ഗ്രാഹകൻ കുറഞ്ഞ കേർണ്ണൽ കഴിഞ്ഞിരിക്കുന്നു"
        HELP_WITH_THEIR_MOBILITY_AID -> "അവർക്ക് അവരുടെ ചാലന സഹായിക്കുക"
        PLEASE_ASSIST_THEM_IF_NEEDED -> "ആവശ്യമുണ്ടെങ്കിൽ അവർക്ക് സഹായിക്കുക"
        MESSAGE_THEM_AT_PICKUP -> "പിക്കപ്പിൽ അവർക്ക് സന്ദേശം അയയ്ക്കുക"
        SOUND_HORN_ONCE_AT_PICKUP -> "പിക്കപ്പിൽ ഒരാഴ്ച ഹോൺ കട്ടിക്കൊണ്ടു ചെയ്യുക"
        PLEASE_CALL_AND_AVOID_CHATS -> "ദയവായി അഴൈക്കുക ആൻഡ് ചാറ്റുകൾ ഒഴിവാക്കുക"
        PLEASE_CHAT_AND_AVOID_CALLS -> "ദയവായി ചാറ്റുകൾ അയയ്ക്കുക ആൻഡ് അഴൈക്കുക"
        PLEASE_GO_TO_EXACT_PICKUP -> "ദയവായി ശരിയായ പിക്കപ്പ് സ്ഥലത്തേക്ക് പോവുക"
        CUSTOMER_HAS_POOR_VISION_SOUND_HORN_AT_PICKUP -> "ഗ്രാഹകൻ കുറഞ്ഞ ദർശനം ഉണ്ട്. പിക്കപ്പിൽ ഒരാഴ്ച ഹോൺ കട്ടിക്കൊണ്ടു ചെയ്യുക."
        CUSTOMER_HAS_POOR_HEARING_MESSAGE_THEM_AT_PICKUP -> "റൈഡർ കുറഞ്ഞ കേർണ്ണൽ ഉണ്ട്. പിക്കപ്പിൽ അവർക്ക് സന്ദേശം അയയ്ക്കുക."
        CUSTOMER_HAS_LOW_MOBILITY_STORE_THEIR_SUPPORT_AT_PICKUP -> "ഗ്രാഹകൻ കുറഞ്ഞ ചാലനത്തിൽ നിന്നുണ്ട്. അവർക്ക് അവരുടെ പിന്നായ്ക്ക് സഹായിക്കാൻ സഹായിക്കുക."
        CUSTOMER_HAS_DISABILITY_PLEASE_ASSIST_THEM -> "ഗ്രാഹകൻ ഒരു പ്രതിബന്ധം ഉണ്ട്. അവർക്ക് സാധാരണമായി സഹായിക്കുക."
        CUSTOMER_MAY_NEED_ASSISTANCE -> "ഗ്രാഹകൻ സഹായം ആവശ്യമാകുന്നുവെന്ന് ആക്കുക"
        LEARN_MORE -> "കൂടുതലും അറിഞ്ഞേക്കുക"
        CUSTOMER_HAS_LOW_MOBILITY_GO_TO_EXACT_LOC -> "ഗ്രാഹകൻ കുറഞ്ഞ ചാലനത്തിൽ നിന്നുണ്ട്. ദയവായി ശരിയായ ലോക്കേഷൻ പോയിക്കുക."
        CUSTOMER_HAS_POOR_HEARING_CHAT_WITH_THEM_INSTEAD_OF_CALLING -> "റൈഡർ കുറഞ്ഞ കേർണ്ണൽ ഉണ്ട്. അവർക്ക് അഴൈക്കുക അല്ലെങ്കിൽ അവരുടെ മോനോളി അയയ്ക്കുക."
        CUSTOMER_HAS_LOW_VISION_CALL_THEM_INSTEAD_OF_CHATTING -> "ഗ്രാഹകൻ കുറഞ്ഞ ദർശനം ഉണ്ട്. അവർക്ക് ചാറ്റിംഗ് അയയ്ക്കാൻ അല്ലെങ്കിൽ അവരുടെ ഫോൺ അയയ്ക്കുക."
        PLEASE_HELP_THEM_AS_YOU_CAN -> "നിങ്ങൾ ചെയ്യാനാകുന്നത് പ്രകാരം അവർക്ക് സഹായിക്കുക"
        LEARN_HOW_YOU_CAN_HELP_CUSTOMERS_REQUIRING_SPECIAL_ASSISTANCE -> "പ്രത്യേക സഹായം ആവശ്യമുള്ള ഉപഭോക്താക്കളെ നിങ്ങൾക്ക് എങ്ങനെ സഹായിക്കാമെന്ന് അറിയുക"
        ASSISTANCE_REQUIRED ->  "സഹായം ആവശ്യമാണ്"
        SAVED_DUE_TO_ZERO_COMMISSION ->  "പൂജ്യം കമ്മീഷൻ\nകാരണം സംരക്ഷിച്ചു"
        TIP_EARNED_FROM_CUSTOMER ->  "ഉപഭോക്താവിൽ നിന്ന്\nലഭിച്ച നുറുങ്ങ്"
        COLLECT_VIA_CASE_UPI ->  "പണം/UPI വഴി ശേഖരിക്കുക"
        FARE_COLLECTED ->  "ക്കൂലി ശേഖരിച്ചു"
        RATE_YOUR_RIDE_WITH1 ->  ""
        RATE_YOUR_RIDE_WITH2 ->  "ഉപയോഗിച്ച് നിങ്ങളുടെ യാത്ര റേറ്റ്"
        HELP_US_WITH_YOUR_FEEDBACK ->  "നിങ്ങളുടെ ഫീഡ്‌ബാക്കിൽ ഞങ്ങളെ സഹായിക്കുന്നു (ഓപ്ഷണൽ)"
        COLLECT_CASH ->  "പണം ശേഖരിക്കുക"
        ONLINE_PAYMENT ->  "ഓൺലൈൻ പേയ്‌മെന്റ്"
        RIDE_COMPLETED ->  "റൈഡ് പൂർത്തിയായി"
        SUBMIT_FEEDBACK ->  "ഫീഡ്‌ബാക്ക് സമർപ്പിക്കുക"
        BADGE_EARNED ->  "ബാഡ്ജ് സമ്പാദിച്ചു"
        PURPLE_RIDE_CHAMPION ->  "പർപ്പിൾ റൈഡ് ചാമ്പ്യൻ"
        PURPLE_RIDE ->  "പർപ്പിൾ റൈഡ്"
        PROCEED_TO_CHAT ->  "ചാറ്റുമായി മുന്നോട്ട് പോകൂ"
        PLEASE_CONSIDER_CALLING_THEM ->  "കസ്റ്റമറിനു ചാറ്റ് വായിക്കാൻ കഴിഞ്ഞേക്കില്ല. അവരെ വിളിക്കുന്നത് പരിഗണിക്കുക"
        PENDING_CAPS ->  "തീർച്ചപ്പെടുത്തുന്നില്ല"
        FAILURE ->  "പരാജയം"
        PAYMENT_MODE ->  "പേയ്‌മെന്റ് മോഡ്"
        TXN_ID ->  "ഓർഡർ ഐഡി"
        AMOUNT_PAID ->  "അടച്ച തുക"
        NOTIFICATION_SCHEDULED ->  "അറിയിപ്പ് ഷെഡ്യൂൾ ചെയ്തു!"
        MANUAL_DUES ->  "മാനുവൽ കുടിശ്ശിക"
        AUTOPAY_IN_PROGRESS ->  "ഓട്ടോപേ പുരോഗതിയിലാണ്"
        MANUAL_DUE_OVERVIEW ->  "മാനുവൽ ഡ്യൂ ഓവർവ്യൂ"
        AUTOPAY_DUE_OVERVIEW ->  "ഓട്ടോപേ ഡ്യൂ ഓവർവ്യൂ"
        MANUAL_DUE_AS_AUTOPAY_EXECUTION_FAILED ->  "സ്വയം പേയ്‌മെന്റ് നടപ്പിലാക്കുന്നതിൽ പരാജയപ്പെട്ടതിനാൽ സ്വമേധയാ ഉള്ള തുക"
        CLEAR_MANUAL_DUES ->  "മാനുവൽ കുടിശ്ശിക മായ്‌ക്കുക"
        DUE_OVERVIEW ->  "ഡ്യൂ ഓവർവ്യൂ"
        MANUAL_DUE_DETAILS ->  "മാനുവൽ ഡ്യൂ ഡീറ്റെയിൽസ്"
        AUTOPAY_DUE_DETAILS ->  "ഓട്ടോപേ ഡ്യൂ ഡീറ്റെയിൽസ്"
        SWITCHED_TO_MANUAL ->  "*ഓട്ടോപേ പൂർത്തീകരിക്കാൻ കഴിയാത്തതിനാൽ പേയ്‌മെന്റ് മോഡ് മാനുവലിലേക്ക് മാറി"
        SPLIT_PAYMENT ->  "*ഓട്ടോപേ എക്സിക്യൂട്ട് ചെയ്യാൻ പേയ്മെന്റ് വിഭജിച്ചു"
        GST_INCLUDE ->  "(18% GST ഉൾപ്പെടെ)"
        SCHEDULED_AT ->  "ഷെഡ്യൂൾ ചെയ്തത്"
        PAYMENT_STATUS ->  "പേയ്‌മെന്റ് നില"
        NOTIFICATION_ATTEMPTING ->  "അറിയിപ്പ് ശ്രമിക്കുന്നു"
        EXECUTION_SCHEDULED ->  "നിർവ്വഹണം ഷെഡ്യൂൾ ചെയ്തു"
        EXECUTION_ATTEMPTING ->  "നിർവ്വഹണശ്രമം"
        EXECUTION_SUCCESS ->  "നിർവ്വഹണ വിജയം"
        SCHEDULED ->  "ഷെഡ്യൂൾഡ്"
        ONE_TIME_SETTLEMENT ->  "ഒറ്റത്തവണ സെറ്റിൽമെന്റ് നടത്തുക"
        PAYMENT_SCHEDULED ->  "പേയ്‌മെന്റ് ഷെഡ്യൂൾ ചെയ്തു"
        OFFER_CARD_BANNER_TITLE _ ->  "ഓട്ടോപേ സജ്ജീകരിച്ച് {} വരെ പ്രതിദിനം ₹15 മാത്രം നൽകുക"
        OFFER_CARD_BANNER_DESC ->  "നവംബർ 1 വരെ പ്രതിദിനം ₹15 മാത്രം നൽകുക"
        OFFER_CARD_BANNER_ALERT ->  "നിങ്ങളുടെ ഓട്ടോപേ സെറ്റപ്പ് തീർച്ചപ്പെടുത്തിയിട്ടില്ല!"
        OR ->  "അല്ലെങ്കിൽ"
        COLLECT_CASH_DIRECTLY ->  "നേരിട്ട് പണം സ്വികരിക്കുക"
        OR_COLLECT_CASH_DIRECTLY ->  "അല്ലെങ്കിൽ നേരിട്ട് പണം ശേഖരിക്കുക"
        SETUP_AUTOPAY_TO_ACCEPT_PAYMENT ->  "നിങ്ങളുടെ ബാങ്ക് അക്കൗണ്ടിലേക്ക് നേരിട്ട് പേയ്‌മെന്റുകൾ സ്വീകരിക്കുന്നതിന്, നിങ്ങളുടെ പ്ലാനിൽ ഓട്ടോപേ സജ്ജീകരിക്കുക"
        DOWNLOAD_QR ->  "QR ഡൗൺലോഡ് ചെയ്യുക"
        USE_THIS_QR_TO_COLLECT_PAYMENT ->  "റൈഡ് അവസാനിച്ചതിന് ശേഷം പേയ്‌മെന്റ് സ്വീകരിക്കാൻ നിങ്ങൾക്ക് ഈ QR കോഡ് ഉപയോഗിക്കാം."
        AMOUNT_WILL_DEPOSITED_TO_BANK_ACCOUNT ->  "യുപിഐ ഓട്ടോപേയ്‌ക്കായി നിങ്ങൾ ഉപയോഗിക്കുന്ന ബാങ്ക് അക്കൗണ്ടിലേക്ക് തുക നിക്ഷേപിക്കപെടും"
        GET_DIRECTLY_TO_YOUR_BANK_ACCOUNT ->  "UPI ഐഡിയിലേക്ക് നേരിട്ട് പണമടയ്ക്കുക"
        PAYMENT ->  "പേയ്മെന്റ്"
        QR_CODE ->  "QR കോഡ്"
        GET_QR_CODE ->  "QR കോഡ് നേടുക"
        COLLECT_VIA_UPI_QR_OR_CASH ->  "UPI QR അല്ലെങ്കിൽ പണം വഴി ശേഖരിക്കുക"
        EXECUTION_FAILED ->  "সম্পাদনা ব্যর্থ"
        NOTIFICATION_FAILED ->  "বিজ্ঞপ্তি ব্যর্থ হয়েছে"
        PAY_NOW ->  "এখনই অর্থ প্রদান করুন"
        CLEAR_DUES_BANNER_TITLE ->  "নন-স্টপ রাইড উপভোগ করতে আপনার বকেয়া সাফ করুন"
        TRANSACTION_DEBITED_ON ->  "লেনদেন ডেবিট করা হয়েছে"
        TRANSACTION_ATTEMPTED_ON ->  "লেনদেনের চেষ্টা করা হয়েছে"
        AUTOPAY_SETUP_AND_PAYMENT_SUCCESSFUL ->  "ഓട്ടോപേ സജ്ജീകരണവും പേയ്‌മെന്റും വിജയകരം!"
        AUTOPAY_SETUP_SUCCESSFUL ->  "ഓട്ടോപേ സജ്ജീകരണം വിജയകരം!"
        AUTOPAY_SETUP_AND_PAYMENT_PENDING ->  "ഓട്ടോപേ സെറ്റപ്പും പേയ്‌മെന്റും തീർച്ചപ്പെടുത്തിയിട്ടില്ല!"
        AUTOPAY_SETUP_PENDING ->  "ഓട്ടോപേ സെറ്റപ്പ് തീർച്ചപ്പെടുത്തിയിട്ടില്ല!"
        AUTOPAY_SETUP_AND_PAYMENT_FAILED ->  "ഓട്ടോപേ സെറ്റപ്പും പേയ്‌മെന്റും പരാജയപ്പെട്ടു!"
        AUTOPAY_SETUP_FAILED ->  "ഓട്ടോപേ സജ്ജീകരണം പരാജയപ്പെട്ടു!"
        ONE_TIME_REGISTERATION ->  "ഒറ്റത്തവണ രജിസ്ട്രേഷൻ"
        CLEARANCE_AND_REGISTERATION ->  "ക്ലിയറൻസ് + രജിസ്ട്രേഷൻ"
        UPI_AUTOPAY_SETUP ->  "UPI ഓട്ടോപേ സെറ്റപ്പ്"
        WATCH_VIDEO_FOR_HELP ->  "സഹായത്തിനായി വീഡിയോ കാണുക"
        PAYMENT_PENDING_SOFT_NUDGE ->  "കുടിശ്ശിക പരിധി ഉടൻ എത്തും.നിർത്താതെയുള്ള റൈഡുകൾ ആസ്വദിക്കാൻ കുടിശ്ശിക മായ്ക്കുക"
        CLEAR_YOUR_DUES_EARLY ->  "നിങ്ങളുടെ കുടിശ്ശിക നേരത്തെ മായ്ക്കുക"
        DUE_LIMIT_WARNING_BANNER_TITLE ->  "നിങ്ങളുടെ അവസാനത്തെ {} നിങ്ങളുടെ പരിധി ഉടൻ എത്തും"
        SCHEDULED_ON ->  "ഡിഡക്ഷൻ തീയതി"
        ATTEMPTED_ON ->  "ശ്രമിച്ച തീയതി"
        DEBITED_ON ->  "ഡെബിറ്റ് തീയതി"
        FREE_TRIAL_ENDING_IN_2_DAYS -> "സൗജന്യ ട്രയൽ 2 ദിവസത്തിനുള്ളിൽ അവസാനിക്കും"
        FREE_TRIAL_ENDING_TOMORROW ->  "സൗജന്യ ട്രയൽ നാളെ അവസാനിക്കും"
        FREE_TRIAL_ENDS_TONIGHT ->  "സൗജന്യ ട്രയൽ ഇന്ന് രാത്രി അവസാനിക്കും"
        JOIN_A_PLAN_TO_CONTINUE_TAKING_RIDES ->  "റൈഡുകൾ തുടരാനുള്ള പ്ലാനിൽ ചേരുക"
        SETUP_AUTOPAY_FOR_EASY_PAYMENTS ->  "എളുപ്പമുള്ള പേയ്‌മെന്റുകൾക്കായി ഓട്ടോപേ സജ്ജീകരിക്കുക"
        LOW_DUES_CLEAR_POPUP_DESC ->  "നിർത്താതെയുള്ള റൈഡുകൾ ആസ്വദിക്കാൻ ഇപ്പോൾ നിങ്ങളുടെ കുടിശ്ശിക മായ്ക്കുക"
        DUES_PENDING ->  "⚠️ കുടിശ്ശിക ശേഷിക്കുന്നു! ⚠️"
        DAYS ->  "ദിവസങ്ങൾ"
        ACTIVE_PLAN ->  "സജീവ പദ്ധതി"
        PAYMENT_PENDING ->  "പെയ്‌മെന്റ് പെൻഡിംഗ്"
        DOWNGRADE_AVAILABLE_ONLY_FOR_AC_VEHICLES ->  "ഡൌൺഗ്രേഡ് വാഹന ഓപ്ഷനുകൾ കേവലായത് ഏസി വാഹനങ്ങൾക്ക് മാത്രമേ ലഭ്യമാകുക"
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_1 ->  "നിങ്ങളുടെ വാഹനം തരംതാഴ്ത്തുന്നത് "
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_2 ->  "റൈഡുകളും"
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_3 ->  " റൈഡുകളും എടുക്കാൻ നിങ്ങളെ അനുവദിക്കും"
        AC_CAB ->  "എസി ക്യാബ്"
        AC_SUV ->  "എസി എസ്‌യുവി"
        DOWNGRADE_VEHICLE ->  "വാഹനം തരംതാഴ്ത്തുക"
        WHAT_ARE_PURPLE_RIDES ->  "എന്താണ് പർപ്പിൾ റൈഡുകൾ?"
        ECONOMICAL ->  "സാമ്പത്തിക"
        SPACIOUS ->  "വിശാലമായത്"
        COMFY ->  "സുഖപ്രദമായ"
        PEOPLE ->  "പേർ"
        GO_TO ->  "ഗോ റ്റു"
        SELECT_ON_MAP ->  "മാപ്പിൽ തിരഞ്ഞെടുക്കുക"
        CONFIRM_LOCATION_STR ->  "ലൊക്കേഷൻ സ്ഥിരീകരിക്കുക"
        SAVE_LOCATION_STR ->  "ലൊക്കേഷൻ സംരക്ഷിക്കുക"
        REMOVE_PREF_LOC ->  "ഇഷ്ടപ്പെട്ട സ്ഥലം നീക്കം ചെയ്യണോ "
        CONF_REMOVE_PREF_LOC ->  "ഇഷ്ടപ്പെട്ട സ്ഥലം നീക്കം ചെയ്യണമെന്ന് തീർച്ചയാണോ?"
        YES_REMOVE ->  "അതെ, നീക്കം ചെയ്യുക"
        ADD_LOCATION ->  "ലൊക്കേഷൻ ചേർക്കുക"
        ADD_ANOTHER_LOCATION ->  "മറ്റൊരു ലൊക്കേഷൻ ചേർക്കുക"
        ADD_A_GOTO_LOC ->  "പോകാൻ ലൊക്കേഷൻ ചേർക്കുക"
        GOTO_LOC_LEFT ->  "ഗോ റ്റു ലൊക്കേഷനുകൾ അവശേഷിക്കുന്നു:"
        CURRENT_LOCATION ->  "നിലവിലെ സ്ഥാനം"
        CONF_GOTO_LOC ->  "ലൊക്കേഷനിലേക്ക് പോകുന്നത് സ്ഥിരീകരിക്കുക"
        GOTO_LOCS ->  "ലൊക്കേഷനുകളിലേക്ക് പോകുക"
        LOCATION_STR ->  "ലൊക്കേഷൻ"
        ADD_TAG ->  "ടാഗ് ചേർക്കുക"
        ONLY_ONE_LOC_CAN_ADDED ->  "(ഒരു ലൊക്കേഷനിൽ മാത്രമേ ഈ ടാഗ് ഉണ്ടാകൂ)"
        SAVE_AS ->  "ഇതായി സംരക്ഷിക്കുക"
        NO_GOTO_LOC_ADDED ->  "ഗോ-ടു ലൊക്കേഷൻ ഇതുവരെ ചേർത്തിട്ടില്ല"
        GOTO_LOC_HELPS_YOU ->  "നിങ്ങളുടെ പ്രിയപ്പെട്ട സ്ഥലങ്ങളിലും പരിസരങ്ങളിലും റൈഡുകൾ കണ്ടെത്താൻ ഗോ-ടു ലൊക്കേഷനുകൾ നിങ്ങളെ സഹായിക്കുന്നു"
        YOU_ARE_VERY_CLOSE -> "നിങ്ങൾ “ഗോ റ്റു” ലൊക്കേഷന് വളരെ അടുത്താണ്"
        GOTO_IS_APPLICABLE_FOR ->  "“ഗോ റ്റു” എന്നത് നിങ്ങളുടെ നിലവിലെ ലൊക്കേഷനിൽ നിന്ന് കുറഞ്ഞത് 3 കിലോമീറ്റർ അകലെയുള്ള \n ലൊക്കേഷനുകൾക്ക് ബാധകമാണ് \n."
        GOTO_MAYBE_REDUCED ->  "“ഗോ റ്റു” കുറച്ചേക്കാം"
        CANCEL_OF_GOTO ->  "“ഗോ റ്റു” റൈഡ് റദ്ദാക്കുന്നത് നിങ്ങളുടെ “ഗോ റ്റു” ഓപ്ഷനുകൾ കുറയ്ക്കും! "
        MORE_GOTO_RIDE_COMING ->  "കൂടുതൽ “ഗോ റ്റു” റൈഡുകൾ വരുന്നു!"
        MORE_GOTO_RIDE_COMING_DESC ->  "ദയവായി ഓൺലൈനിൽ തുടരുക; നിങ്ങളുടെ “ഗോ റ്റു” ലൊക്കേഷനായി ഞങ്ങൾക്ക് കൂടുതൽ റൈഡ് അഭ്യർത്ഥനകൾ ലഭിക്കുന്നുണ്ട്"
        GOTO_REDUCED_TO_ZERO ->  "“ഗോ റ്റു” പൂജ്യമായി കുറച്ചു"
        DUE_TO_MULTIPLE_CANCELLATIONS ->  "ഒന്നിലധികം റദ്ദാക്കലുകൾ കാരണം, എണ്ണം വെട്ടിച്ചുരുക്കി"
        OK_GOT_IT ->  "ശരി, മനസ്സിലായി"
        GOTO_REDUCED_TO ->  "“ഗോ റ്റു” കുറച്ചു"
        VALIDITY_EXPIRED_DESC ->  "നിങ്ങളുടെ 30 മിനിറ്റ് സാധുത കാലഹരണപ്പെട്ടു. ഇപ്പോൾ നിങ്ങളുടെ അഭ്യർത്ഥന നിറവേറ്റാൻ ഞങ്ങൾക്ക് കഴിയുന്നില്ല."
        KNOW_MORE ->  "കൂടുതൽ അറിയുക"
        THIS_FEATURE_WILL_BE_APPLICABLE -> "നിങ്ങളുടെ നിലവിലെ ലൊക്കേഷനിൽ നിന്ന് കുറഞ്ഞത് 3 കിലോമീറ്റർ അകലെയായിരിക്കുമ്പോൾ ഈ സവിശേഷത ബാധകമാകും.\n\nലൊക്കേഷൻ മുൻഗണനകൾ സജീവമാകുമ്പോൾ 30 മിനിറ്റ് മാത്രമേ സാധുതയുള്ളൂ."
        GOTO_LOC_ADDED ->  "ഗോ-ടു ലൊക്കേഷൻ വിജയകരമായി ചേർത്തു"
        GOTO_LOC_REMOVED ->  "ഗോ റ്റു ലൊക്കേഷൻ വിജയകരമായി നീക്കം ചെയ്തു"
        GOTO_LOC_UPDATED ->  "“ഗോ റ്റു” യുടെ സ്ഥാനം വിജയകരമായി അപ്ഡേറ്റ് ചെയ്തു"
        GOTO_LOC_IS_ENABLED ->  "“ഗോ റ്റു” ലൊക്കേഷൻ പ്രവർത്തനക്ഷമമാക്കി"
        GOTO_LOC_IS_DISABLED ->  "“ഗോ റ്റു” പ്രവർത്തനരഹിതമാക്കി"
        GOTO_LOCATIONS ->  "ഗോ റ്റു സ്ഥാനം"
        CHOOSE_A_GOTO_LOC ->  "ഒരു ലക്ഷ്യസ്ഥാനം തിരഞ്ഞെടുക്കുക"
        YOU_HAVE_ONLY_LEFT_FOR_TODAY ->  "നിങ്ങൾ ഇന്നത്തേക്ക് മാത്രമേ പോയിട്ടുള്ളൂ"
        YES_ENABLE ->  "അതെ പ്രവർത്തനക്ഷമമാക്കുക"
        NO_GOTO_LOCS_ADDED_YET ->  "ഗോ-ടു ലൊക്കേഷനുകളൊന്നും ഇതുവരെ ചേർത്തിട്ടില്ല"
        NO_GOTO_LOCS_ADDED_YET_DESC ->  "“ഗോ റ്റു” ലൊക്കേഷനുകൾ നിങ്ങളുടെ പ്രിയപ്പെട്ട സ്ഥലങ്ങളിലും പരിസരങ്ങളിലും റൈഡുകൾ കണ്ടെത്താൻ സഹായിക്കുന്നു"
        ENABLE_GOTO ->  "ഗോ റ്റു ஐ இயக்கு"
        GO_TO_CANCELLATION_TITLE ->  "“ഗോ റ്റു” കുറച്ചേക്കാം"
        GO_TO_CANCELLATION_DESC ->  "“ഗോ റ്റു” റൈഡ് റദ്ദാക്കുന്നത് നിങ്ങൾക്കുള്ള “ഗോ റ്റു” ഓപ്‌ഷനുകൾ കുറയ്ക്കും!"
        REPORT_ISSUE ->  "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക"
        YOU_ARE_ALMOST_AT_LOCATION ->  "നിങ്ങൾ ഏകദേശം ലൊക്കേഷനിലേക്ക് പോകുക"
        DRIVER_HOME_LOCATION_NOT_FOUND ->  "ലൊക്കേഷൻ കണ്ടെത്തിയില്ല"
        DRIVER_HOME_LOCATION_DOES_NOT_EXIST ->  "ലൊക്കേഷൻ നിലവിലില്ല"
        DRIVER_HOME_LOCATION_LIMIT_REACHED ->  "ലൊക്കേഷൻ പരിധി എത്തി"
        DRIVER_GO_HOME_REQUEST_NOT_FOUND ->  "അഭ്യർത്ഥന കണ്ടെത്തിയില്ല"
        DRIVER_GO_HOME_REQUEST_DOES_NOT_EXIST ->  "അഭ്യർത്ഥന നിലവിലില്ല"
        DRIVER_GO_HOME_REQUEST_DAILY_USAGE_LIMIT_REACHED ->  "പ്രതിദിന ഉപയോഗ പരിധി എത്തി"
        DRIVER_GO_HOME_REQUEST_ALREADY_ACTIVE ->  "ഇതിനകം സജീവമാണ്"
        DRIVER_HOME_LOCATION_OUTSIDE_SERVICE_AREA ->  "ലൊക്കേഷൻ സേവന മേഖലയ്ക്ക് പുറത്താണ്"
        NEW_LOCATION_TOO_CLOSE_TO_PREVIOUS_HOME_LOCATION ->  "ലൊക്കേഷൻ മുമ്പത്തെ സ്ഥലത്തിന് വളരെ അടുത്താണ്"
        DRIVER_HOME_LOCATION_DOES_NOT_BELONG_TO_DRIVER ->  "ലൊക്കേഷൻ നിങ്ങളുടേതല്ല"
        DRIVER_HOME_LOCATION_DELETE_WHILE_ACTIVE_ERROR ->  "സജീവമായിരിക്കുമ്പോൾ ലൊക്കേഷൻ ഇല്ലാതാക്കാൻ കഴിയില്ല"
        DISABLE_GOTO_STR ->  "ഗോ-ടു പ്രവർത്തനരഹിതമാക്കണോ?"
        YOU_STILL_HAVE_TIME_LEFT ->  "നിങ്ങളുടെ “ഗോ റ്റു” അഭ്യർത്ഥനയിൽ ഇനിയും സമയമുണ്ട്"
        YES_DISABLE ->  "അതെ, പ്രവർത്തനരഹിതമാക്കുക"
        DRAG_TO_ADJUST ->  "നിങ്ങളുടെ സ്ഥാനം ക്രമീകരിക്കാൻ വലിച്ചിടുക"
        LOCATION_ALREADY_EXISTS ->  "ലൊക്കേഷൻ ഇതിനകം നിലവിലുണ്ട്"
        MIN_LEFT ->  "മിനിറ്റ്"
        GOTO_LOC_REACHED ->  "“ഗോ റ്റു” ലൊക്കേഷനിൽ എത്തി!"
        GET_READY_FOR_YS_SUBSCRIPTION _ ->  "യാത്രി സതി പദ്ധതികൾക്കായി തയ്യാറാകൂ!"
        SIGNUP_EARLY_FOR_SPECIAL_OFFERS ->  "പ്രത്യേക ഓഫറുകൾക്കായി നേരത്തെ സൈൻ അപ്പ് ചെയ്യുക"
        GUARANTEED_FIXED_PRICE _ ->  "ജനുവരി 1, 2025 വരെ ഉറപ്പുള്ള സ്ഥിര വില"
        INTRODUCTORY_OFFER_TO_BE_ANNOUNCED_SOON ->  "ആമുഖ ഓഫർ ഉടൻ പ്രഖ്യാപിക്കും!"
        NO_CHARGES_TILL ->  "ഡിസംബർ 31 വരെ നിരക്കുകളൊന്നുമില്ല"
        DO_YOU_WANT_TO_CANCEL ->  "നിങ്ങൾക്ക് റദ്ദാക്കണോ?"
        DO_YOU_WANT_TO_CANCEL_DESC ->  "നിങ്ങൾ ഓട്ടോപേ റദ്ദാക്കാൻ പോവുകയാണ്.\nയാന്ത്രിക പേയ്‌മെന്റുകൾ പുനരാരംഭിക്കുന്നതിന് നിങ്ങൾ വീണ്ടും ഓട്ടോപേ സജ്ജീകരിക്കേണ്ടതുണ്ട്."
        NO ->  "ഇല്ല"
        YES_CANCEL ->  "അതെ, റദ്ദാക്കുക"
        AUTOPAY_CANCELLED ->  "ഓട്ടോപേ റദ്ദാക്കി"
        AND -> " ഒപ്പം "
        DIRECT_PAYMENT_NO_COMMISSIONS -> "നേരിട്ടുള്ള പേയ്‌മെന്റ്.\nകമ്മീഷനുകളൊന്നുമില്ല"
        CUSTOMER_PAYS_DIRECTLY -> "ഉപഭോക്താവ് നിങ്ങൾക്ക് നേരിട്ട് \nപണം അല്ലെങ്കിൽ UPI വഴി പണം നൽകുന്നു"
        HUNDRED_PERCENT_FARE_GOES_TO_YOU -> "നിരക്കിന്റെ 100%\nനിങ്ങൾക്കായി!"
        FARE_SHOWN_IS_FARE_YOU_GET -> "കാണിച്ചിരിക്കുന്ന നിരക്ക് നിങ്ങൾക്ക് ലഭിക്കുന്ന നിരക്കാണ്.\nമറഞ്ഞിരിക്കുന്ന നിരക്കുകളൊന്നുമില്ല."
        BE_A_PART_OF_OPEN_MOBILITY_REVOLUTION -> "ഓപ്പൺ\nമൊബിലിറ്റി വിപ്ലവത്തിന്റെ ഭാഗമാകൂ!"
        OUR_DATA_AND_PRODUCT_ARE_TRANSPARENT -> "ഞങ്ങളുടെ ഡാറ്റയും ഉൽപ്പന്ന റോഡ്‌മാപ്പും\nഎല്ലാവർക്കും സുതാര്യമാണ്."
        ENABLE_LOCATION_PERMISSION -> "ലൊക്കേഷൻ അനുമതി പ്രവർത്തനക്ഷമമാക്കുക"
        PLEASE_ENABLE_LOCATION_PERMISSION_FOR -> "ദയവായി ഇതിന് അനുയോജ്യമായ ഇടം നേടുക"
        ENABLE_LOCATION -> "ലൊക്കേഷൻ പ്രവർത്തനക്ഷമമാക്കുക"
        YOUR_DETECTED_LOCATION_IS -> "നിങ്ങളുടെ കണ്ടെത്തിയ ലൊക്കേഷൻ ഇതാണ്"
        LANGUAGE_DETECTED -> "ഭാഷ കണ്ടെത്തി"
        CHANGE_LANGUAGE_STR -> "ഭാഷ മാറ്റുക"
        SELECT_LOCATION -> "ലൊക്കേഷൻ തിരഞ്ഞെടുക്കുക"
        SELECT_LOCATION_DESC -> "നിങ്ങൾ സവാരി ചെയ്യാൻ ആഗ്രഹിക്കുന്ന സ്ഥലം തിരഞ്ഞെടുക്കുക"
        SELECT_LANGUAGE_DESC -> "നിങ്ങൾക്ക് വായിക്കാൻ കഴിയുന്ന ഭാഷ തിരഞ്ഞെടുക്കുക"
        CONFIRM_LANGUAGE -> "ഭാഷ സ്ഥിരീകരിക്കുക"
        GET_STARTED -> "തുടങ്ങി"
        ENTER_YOUR_MOBILE_NUMBER -> "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക"
        NOTIFICATION_ACCESS -> "അറിയിപ്പ് പ്രവേശനം"
        NOTIFICATION_ACCESS_DESC -> "ശുപാർശ ചെയ്യുന്നു, നിങ്ങൾ എപ്പോഴും സന്ദേശങ്ങൾ കൊണ്ടുപോകാതെ ഉള്ളതാക്കുന്നു"
        WATCH_VIDEO -> "വീഡിയോ കാണുക"
        DL_VERIFICATION_FAILED -> "DL പരിശോധന പരാജയപ്പെട്ടു. ദിവസം നൽകി ശ്രമിക്കുക"
        RC_VERIFICATION_FAILED -> "RC പരിശോധന പരാജയപ്പെട്ടു. ദിവസം നൽകി ശ്രമിക്കുക"
        DL_UPLOAD_FAILED -> "DL അപ്ലോഡ് പരാജയപ്പെട്ടു"
        RC_UPLOAD_FAILED -> "RC അപ്ലോഡ് പരാജയപ്പെട്ടു"
        PLEASE_RETRY_THE_UPLOAD_AGAIN -> "ദയവായി അപ്ലോഡ് വീണ്ടും ശ്രമിക്കുക"
        RC_AND_DL_UPLOAD_FAILED -> "RC അനുമതികൾ പരാജയപ്പെട്ടു"
        RC_UPLOAD_LIMIT_REACHED -> "RC അപ്ലോഡ് പരിധി പൂരിപ്പെടുവിച്ചു"
        DL_UPLOAD_LIMIT_REACHED -> "DL അപ്ലോഡ് പരിധി പൂരിപ്പെടുവിച്ചു"
        RETRY_UPLOAD -> "അപ്ലോഡ് വീണ്ടും ശ്രമിക്കുക"
        VEHICLE_REGISTERATON_CERTIFICATE -> "വാഹനം രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ്"
        GRANT_PERMISSIONS -> "അനുമതി നൽകുക"
        SUBSCRIPTION_PLAN_STR _ -> "സബ്സ്ക്രിപ്ഷൻ പ്ലാൻ"
        COMPLETE_AUTOPAY_LATER -> "ശേഷി ഓട്ടോപേ പൂർത്തിയാക്കുക 'എന്റെ പ്ലാൻ' വിഭാഗത്തിൽ ശേഷി ഓട്ടോപേ പൂർത്തിയാക്കുക"
        START_EARNING_IN_FOUR_STEPS -> "{} നാലാംഘട്ടത്തിൽ സംരംഭിക്കാൻ തുടങ്ങുക"
        COMPLETE -> "പൂർത്തിയാക്കുക"
        HOW_TO_UPLOAD -> "അപ്ലോഡ് എങ്ങനെ"
        TAKE_CLEAR_PICTURE_DL -> "ഫ്ലാറ്റ് ഉപരിതലത്തിൽ നിങ്ങളുടെ ഡ്രൈവിംഗ് ലൈസൻസിന്റെ ഫോട്ടോ ഭാഗത്തെ ശുദ്ധമായ ചിത്രം എടുക്കുക"
        ENSURE_ADEQUATE_LIGHT -> "പ്രകാശം പൂർണ്ണമായും എളുപ്പമുള്ളതായിരിക്കണം, എല്ലാ വിശദവിവരങ്ങൾക്കും ശുദ്ധമായി കാണാൻ"
        FIT_DL_CORRECTLY -> "ചിത്രത്തിലുള്ള ഡ്രൈവിംഗ് ലൈസൻസ് ശുദ്ധമായി ചിത്രിക്കുക"
        TAKE_PHOTO -> "ഫോട്ടോ എടുക്കുക"
        FIT_RC_CORRECTLY -> "ചിത്രത്തിലുള്ള രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ് ശുദ്ധമായി ചിത്രിക്കുക"
        TAKE_CLEAR_PICTURE_RC -> "ഫ്ലാറ്റ് ഉപരിതലത്തിൽ നിങ്ങളുടെ രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റിന്റെ ഫോട്ടോ ഭാഗത്തെ ശുദ്ധമായ ചിത്രം എടുക്കുക"
        DL_UPLOADED -> "DL അപ്ലോഡ് ചെയ്തു"
        RC_UPLOADED -> "RC അപ്ലോഡ് ചെയ്തു"
        DL_UPLOADING -> "DL അപ്‌ലോഡ് ചെയ്യുന്നു"
        RC_UPLOADING -> "RC അപ്‌ലോഡ് ചെയ്യുന്നു"
        RETAKE_RC -> "\nRC യുടെ അംശം കൊണ്ട് ദയവായി ഫോട്ടോ പുനഃതെളിക്കുക"
        RETAKE_DL -> "\nDL യുടെ അംശം കൊണ്ട് ദയവായി ഫോട്ടോ പുനഃതെളിക്കുക"
        CONFIRM_AND_UPLOAD -> "സ്ഥിരീകരിക്കുക മറ്റും അപ്ലോഡ് ചെയ്യുക"
        RETAKE_PHOTO-> "ഫോട്ടോ പുനഃതെളിക്കുക"
        LETS_GET_YOU_TRIP_READY -> "നിങ്ങളുടെ യാത്ര തയ്യാറാക്കാം!"
        GOT_AN_OTP -> "ഒരു OTP കിട്ടിയോ?"
        DRIVING_LICENSE_DETAILS -> "ഡ്രൈവിംഗ് ലൈസൻസ് വിശദാംശങ്ങൾ"
        VEHICLE_REGISTRATION_DETAILS -> "വാഹന രജിസ്ട്രേഷൻ വിശദാംശങ്ങൾ"
        UPLOAD_PHOTO -> "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക"
        CLEAR_IMAGE -> "ശുദ്ധമായ ചിത്രം"
        BLURRY_IMAGE -> "കളിമണ്ണിന്റെ ചിത്രം"
        CROPPED_CORRECTLY -> "ശുദ്ധമായി ക്രോപ്പ് ചെയ്തു"
        WRONG_CROPPING -> "തെറ്റായ ക്രോപ്പിംഗ്"
        CHANGE_LOCATION -> "ലൊക്കേഷൻ മാറ്റുക"
        CHANGE_CITY-> "നഗരം മാറ്റുക"
        UPLOAD_REGISTRATION_CERTIFICATE_STR -> "രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ് അപ്ലോഡ് ചെയ്യുക"
        TAKE_A_PHOTO -> "ഒരു പടം എടുക്കു"
        GALLERY -> "ഗാലറി"
        GET_FULL_PAYMENT -> "ക്ലയന്റിനൊപ്പം നിങ്ങൾക്ക് താഴെക്കാണുന്ന രീതിയിൽ പൂർത്തിയാക്കുക"
        SELECT_CITY_STR -> "നഗരം തിരഞ്ഞെടുക്കുക"
        DETECTING_LOCATION -> "ലൊക്കേഷൻ കണ്ടെത്തുന്നു"
        UNABLE_TO_DETECT_YOUR_LOCATION -> "നിങ്ങളുടെ സ്ഥാനം കണ്ടെത്താനായില്ല"
        RC_FAILED_DESC -> "കുറച്ച് സമയത്തിന് ശേഷം RC ചേർക്കാൻ ശ്രമിക്കുക"
        RC_IN_PROGRESS_DESC -> "പരിശോധിച്ചുറപ്പിച്ചുകഴിഞ്ഞാൽ RC നിങ്ങളുടെ പ്രൊഫൈലിലേക്ക് ചേർക്കും"
        RC_VERIFICATION_SUCCESS -> "ആർസി പരിശോധിച്ചുറപ്പിക്കൽ വിജയിച്ചു!"
        RC_VERIFICATION_FAILED_STATUS -> "ആർസി പരിശോധന പരാജയപ്പെട്ടു!"
        RC_VERIFICATION_IN_PROGRESS -> "ആർസി വെരിഫിക്കേഷൻ പുരോഗമിക്കുകയാണ്..."
        WE_ARE_NOT_LIVE_IN_YOUR_AREA -> "ഞങ്ങൾ ഇതുവരെ നിങ്ങളുടെ പ്രദേശത്ത് താമസിക്കുന്നില്ല!\nനിങ്ങളുടെ നഗരത്തിലേക്ക് ഉടൻ വരുന്നു!"
        LOCATION_UNSERVICEABLE -> "ലൊക്കേഷൻ ഉപയോഗയോഗ്യമല്ല"
        UNABLE_TO_GET_YOUR_LOCATION -> "നിങ്ങളുടെ സ്ഥാനം കണ്ടെത്താനായില്ല!"
        TURN_OFF_ANY_MOCK_LOCATION_APP_AND_RESTART -> "നിങ്ങൾ ഉപയോഗിക്കുന്ന ഏതെങ്കിലും മോക്ക് ലൊക്കേഷൻ ആപ്പ് ഓഫാക്കി ആപ്പ് റീസ്റ്റാർട്ട് ചെയ്യുക."
        REFERRAL_CODE_NUMBER -> ""
        WELCOME_TEXT _ -> ""
        ABOUT_TEXT _ -> ""
        CHOOSE_LANGUAGE -> ""
        CORPORATE_ADDRESS _ -> ""
        CORPORATE_ADDRESS_DESCRIPTION _ -> ""
        CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL _ -> ""
        EARNED_ON_APP _ -> ""
        TRAVELLED_ON_APP _ -> ""
        WITH -> ""
        YOU_DONT_HAVE_ANY_PAYMENTS -> ""
        RESUMED_AUTOPAY -> "ഓട്ടോപേ പുനരാരംഭിച്ചു"
        ONETIME -> ""
        FORTNIGHTLY -> ""
        MONTHLY -> ""
        BIMONTHLY -> ""
        QUARTERLY -> ""
        HALFYEARLY -> ""
        YEARLY -> ""
        ASPRESENTED -> ""
        FIRST_FREE_RIDE -> ""
        DAILY_PER_RIDE_DESC -> ""
        JOIN_THE_UNLIMITED_PLAN -> ""
        MAYBE_LATER -> ""
        YOUR_PAYMENT_WAS_UNSUCCESSFUL -> ""
        JOIN_A_PLAN_TO_START_EARNING -> ""
        GO_ONLINE_PROMPT_SUBSCRIBE -> ""
        GO_ONLINE_PROMPT_PAYMENT_PENDING -> ""
        RETRY_AUTOPAY -> ""
        RETRY_STR -> ""
        ONGOING_PAYMENT_EXECUTION -> ""
        CANCEL_ANYWAY -> ""
        VALIDITY_EXPIRED_STR -> ""
        DRIVER_GO_HOME_REQUEST_NOT_PRESENT -> ""
        TOTAL_MONEY_COLLECTED -> ""
        FARE_EARNED_OF_THE_DAY -> ""
        GST_PLUS_PAYABLE -> ""
        TO_CONTINUE_USING_YATRI_SATHI -> ""
        PAY -> ""
        LATER -> ""
        GREAT_JOB -> ""
        FEE_BREAKUP -> ""
        YATRI_SATHI_FEE_PAYABLE_FOR_DATE _ -> ""
        FEE_CORRESPONDING_TO_THE_DISTANCE -> ""
        PLATFORM_FEE -> ""
        GST -> ""
        TOTAL_PAYABLE -> ""
        VIEW_DETAILS -> ""
        PAYMENT_SUCCESSFUL -> ""
        PAYMENT_FAILED -> ""
        PAYMENT_PENDING_DESC -> ""
        PAYMENT_FAILED_DESC _ -> ""
        WE_WILL_NOTIFY_WHEN_PAYMENT_SUCCESS -> ""
        CONTINUE_TAKING_RIDES -> ""
        YOUR_PREVIOUS_PAYMENT_IS_PENDING -> ""
        GOVERMENT_CHARGES -> ""
        ENTER_AADHAAR_DETAILS -> ""
        NO_MOBILE_NUMBER_REGISTERED -> ""
        EXCEED_OTP_GENERATION_LIMIT -> ""
        AADHAAR_NUMBER_NOT_EXIST -> ""
        INVALID_OTP -> ""
        NO_SHARE_CODE -> ""
        WRONG_SHARE_CODE -> ""
        INVALID_SHARE_CODE -> ""
        SESSION_EXPIRED -> ""
        OTP_ATTEMPT_EXCEEDED -> ""
        UPSTREAM_INTERNAL_SERVER_ERROR -> ""
        TRANSACTION_ALREADY_COMPLETED -> ""
        GOTO_YOUR_NEAREST_BOOTH -> ""
        CALL_REQUEST_HAS_BEEN_PLACED -> ""
        YOUR_DUES_DESCRIPTION_MANUAL -> ""
        COMPLETE_PAYMENT_TO_CONTINUE _ -> ""
        BY_CLICKING_NEXT_YOU_WILL_BE_AGREEING_TO_OUR -> ""
        THIS_EXTRA_AMOUNT_THE_CUSTOMER_WILL_PAY -> "നിങ്ങൾ {} മിനിറ്റിലധികം കാത്തിരുന്നതിനാൽ ഉപഭോക്താവ് നിങ്ങൾക്ക് നൽകുന്ന അധിക തുകയാണിത്"
        TEN_DIGIT_MOBILE_NUMBER -> "10 അക്ക മൊബൈൽ നമ്പർ"
        BOOTH_CHARGES -> "ബൂത്ത് ചാർജ്"
        BOOTH_CHARGES_INCLUDED -> "ബൂത്ത് ചാർജുകൾ ഉൾപ്പെടുന്നു: ₹{}"
        TOTAL_AMOUNT -> "മൊത്തം തുക"
        PLEASE_ADD_RC -> "സവാരി ചെയ്യാൻ ദയവായി RC ചേർക്കുക"
        LOCATION_CANNOT_BE_ADDED_WHILE_GOTO_ACTIVE -> "Go-To പ്രവർത്തനക്ഷമമാക്കാത്തപ്പോൾ മാത്രമേ ഓപ്ഷൻ ലഭ്യമാകൂ"
        LOCATION_CANNOT_BE_ADDED_WHILE_ON_RIDE -> "റൈഡ് പുരോഗമിക്കുമ്പോൾ ഓപ്‌ഷൻ ലഭ്യമല്ല"
        ADD_GOTO -> "ഗോ-ടു ചേർക്കുക"
        NO_OPEN_MARKET_RIDES _ -> "റൈഡുകൾ ഇല്ല"
        ACCOUNT_BLOCKED -> "അക്കൗണ്ട് തടഞ്ഞു!"
        YOU_HAVE_BEEN_BLOCKED_FROM_TAKING_RIDES -> "നിങ്ങളെ സവാരി ചെയ്യുന്നതിൽ നിന്ന് തടഞ്ഞിരിക്കുന്നു.\nസഹായത്തിന് പിന്തുണയുമായി ബന്ധപ്പെടുക."
        DISMISS -> "പിരിച്ചുവിടുക"
        EARNINGS -> "വരുമാനം"
        YATRI_COINS -> "യാത്രി നാണയങ്ങൾ"
        YATRI_COINS_STR -> "യാത്രി \nനാണയങ്ങൾ"
        INTRODUCING_YATRI_COINS -> "യാത്രി നാണയങ്ങൾ പരിചയപ്പെടുത്തുന്നു"
        NOW_EARN_COINS_FOR_EVERY_RIDE_AND_REFERRAL_AND_USE_THEM_TO_GET_REWARDS -> "ഇപ്പോൾ എല്ലാ റൈഡുകളും റഫറൽസുകളും നടത്തി നിങ്ങൾക്ക് നാണയങ്ങൾ സമ്പാദിക്കാം. അവയെ പ്രതിഫലങ്ങളുടെ വിനിമയത്തിന് ഉപയോഗിക്കാം"
        PAID_BY_YATRI_COINS -> "യാത്രി നാണയങ്ങൾ വഴി പണമടക്കി"
        YATRI_COINS_USAGE_POPUP -> "യാത്രി നാണയങ്ങൾ നിങ്ങളുടെ സബ്സ്ക്രിപ്ഷൻ പ്ലാൻ വിരുദ്ധമായ ഡിസ്കൗണ്ടുകൾക്ക് മാറും."
        USE_COINS_NOW -> "ഇപ്പോൾ നാണയങ്ങൾ ഉപയോഗിക്കുക"
        BUY_NOW -> "ഇപ്പോൾ വാങ്ങുക"
        SELECT_DATE -> "തീയതി തിരഞ്ഞെടുക്കുക"
        WHAT_WILL_MY_COINS_BE_CONVERTED_TO -> "എന്താകും എന്ന് എന്റെ നാണയങ്ങൾ മാറുകയാണോ?"
        COINS_EXPIRING_IN_THE_NEXT -> "{} ദിവസങ്ങളിൽ കാലാന്തരിച്ചുവരുന്ന {} നാണയങ്ങൾ. അവയ്ക്ക് കാലാന്തരിച്ചതുമായി അവയെ ഉപയോഗിക്കുക."
        DAYS_USE_THEM_BEFORE_THEY_EXPIRE -> "ദിവസങ്ങൾ. അവ കാലഹരണപ്പെടുന്നതിന് മുൻപ് അവയെ ഉപയോഗിക്കുക"
        COINS_EXPIRING -> "കാലഹരണപ്പെടുന്ന നാണയങ്ങൾ"
        NO_COINS_AVAILABLE -> "നാണയങ്ങൾ ലഭ്യമല്ല"
        FAILED_TO_USE_COINS_PLEASE_TRY_AGAIN_LATER -> "നാണയങ്ങൾ ഉപയോഗിക്കാൻ പരാജയപ്പെട്ടു. പിന്നീട് ശ്രമിക്കുക"
        BAD_RATING_BY_CUSTOMER -> "കസ്റ്റമർ ദ്വാരാ മോശം റേറ്റിംഗ്"
        GOOD_RATING_BY_CUSTOMER -> "കസ്റ്റമർ ദ്വാരാ നല്ല റേറ്റിംഗ്"
        RIDE_CANCELLATION -> "റൈഡ് റദ്ദാക്കൽ"
        CUSTOMER_REFERRAL -> "കസ്റ്റമർ റഫറൽ"
        CUSTOMER_SHOULD_COMPLETE_A_VALID_RIDE -> "ഉപഭോക്താവ് സാധുവായ ഒരു റൈഡ് പൂർത്തിയാക്കണം"
        DRIVER_REFERRAL -> "ഡ്രൈവർ റഫറൽ"
        PURPLE_RIDE_COMPLETED -> "പർപ്പിൾ റൈഡ് പൂർത്തിയാക്കി"
        TRAINING_COMPLTED -> "പരിശീലനം പൂർത്തിയാക്കി"
        RIDES_IN_A_DAY ->  "ഒരു ദിവസത്തിൽ റൈഡുകൾ"
        TOP -> "മുകളിൽ"
        IN_WEEKLY_LEADERBOARD -> "ആഴ്ചപ്പട്ടികയിൽ"
        TRIP_EARNINGS -> "ട്രിപ്പ് വരുമാനം"
        EXTRA_EARNINGS -> "അധിക വരുമാനം"
        TRIPS -> "ട്രിപ്പുകൾ"
        VIEW_MORE -> "കൂടുതൽ കാണുക"
        MINIMUM -> "കുറഞ്ഞ"
        COINS_IS_REQUIRED_FOR_CONVERSION -> "നാണയങ്ങൾ മാറ്റാൻ ആവശ്യമായി"
        DISCOUNT -> "ഡിസ്കൗണ്ട്"
        CHECK_NOW -> "ഇപ്പോൾ പരിശോധിക്കുക"
        COIN_BALANCE -> "നാണയങ്ങൾ അവശേഷിക്കുന്നു"
        COINS_BALANCE -> "നാണയങ്ങൾ അവശേഷിക്കുന്നു"
        TOTAL_EARNED -> "ആകെ സമ്പാദിച്ചത്"
        RIDE_HISTORY -> "റൈഡ് ചരിത്രം"
        TRANSACTION_HISTORY -> "ഇടപാട് ചരിത്രം"
        COINS_EARNED -> "സമ്പാദിച്ച നാണയങ്ങൾ"
        NO_RIDES -> "റൈഡുകൾ ഇല്ല"
        COINS_USED -> "ഉപയോഗിച്ച നാണയങ്ങൾ"
        USE_COINS -> "നാണയങ്ങൾ ഉപയോഗിക്കുക"
        INSIGHTS -> "ഉൾക്കാഴ്ചകൾ"
        USAGE_HISTORY -> "ഉപയോഗ ചരിത്രം"
        NO_COINS_EARNED -> "നാണയങ്ങളൊന്നും നേടിയില്ല"
        NO_COINS_USED -> "നാണയങ്ങൾ ഉപയോഗിച്ചിട്ടില്ല"
        EARN_COINS_BY_TAKING_RIDES_AND_REFERRING_THE_APP_TO_OTHERS -> "സവാരി നടത്തി ആപ്പ് മറ്റുള്ളവർക്ക് റഫർ ചെയ്തുകൊണ്ട് നാണയങ്ങൾ സമ്പാദിക്കുക"
        USE_THEM_BEFORE_THEY_EXPIRE -> "കാലഹരണപ്പെടുന്നതിന് മുമ്പ് അവ ഉപയോഗിക്കുക"
        NO_RIDE_HISTORY_AVAILABLE -> "റൈഡ് ചരിത്രമൊന്നും ലഭ്യമല്ല"
        YOU_HAVE_NOT_COMPLETED_A_RIDE_YET -> "നിങ്ങൾ ഇതുവരെ ഒരു റൈഡ് പൂർത്തിയാക്കിയിട്ടില്ല"
        COMPLETE_FIRST_RIDE_TO_UNLOCK_COINS -> "നാണയങ്ങൾ അൺലോക്ക് ചെയ്യാൻ ആദ്യ സവാരി പൂർത്തിയാക്കുക"
        DESTINATION -> "ലക്ഷ്യസ്ഥാനം"
        YOU_DID_NOT_TAKE_ANY_RIDES_ON_PREFIX -> ""
        YOU_DID_NOT_TAKE_ANY_RIDES_ON_SUFFIX -> "നിങ്ങൾ റൈഡുകളൊന്നും നടത്തിയില്ല"
        CONVERT -> "പരിവർത്തനം ചെയ്യുക"
        CONVERT_COINS -> "നാണയങ്ങൾ മാറ്റുക"
        CASH_CONVERTED -> "പണം പരിവർത്തനം ചെയ്തു"
        WILL_BE_ADJUSTED_IN_YOUR_FUTURE_SUBSCRIPTION_DUES -> "₹ {} നിങ്ങളുടെ ഭാവി സബ്‌സ്‌ക്രിപ്‌ഷൻ കുടിശ്ശികയിൽ ക്രമീകരിക്കും"
        HAS_BEEN_ADJUSTED_IN_YOUR_SUBSCRIPTION_DUES -> "₹ {} നിങ്ങളുടെ സബ്‌സ്‌ക്രിപ്‌ഷൻ കുടിശ്ശികയിൽ ക്രമീകരിച്ചു"
        USING_COINS_REQUIRES_AN_ACTIVE_PLAN -> "നാണയങ്ങൾ ഉപയോഗിക്കുന്നതിന് ഒരു സജീവ പ്ലാൻ ആവശ്യമാണ്."
        CHOOSE_A_PLAN_TO_GET_STARTED -> "ആരംഭിക്കാൻ ഒരു പ്ലാൻ തിരഞ്ഞെടുക്കുക!"
        CONVERTED_FROM_COINS -> "നാണയങ്ങളിൽ നിന്ന് പരിവർത്തനം ചെയ്തു"
        YATRI_COINS_FAQS -> "യാത്രി നാണയങ്ങൾ പൊതുവായ ചോദ്യം"
        LEARN_ABOUT_YATRI_COINS -> "യാത്രി നാണയങ്ങൾ കുറിച്ച് അറിയുക"
        YATRI_COINS_FAQS_QUES1 -> "യാത്രി കോയിനുകൾ എന്താണ്?"
        YATRI_COINS_FAQS_QUES1_ANS1 -> "റൈഡുകൾ, റഫറലുകൾ, നല്ല റേറ്റിംഗുകൾ മുതലായവ പോലുള്ള നമ്മ യാത്രയിലെ ദൈനംദിന പ്രവർത്തനങ്ങളിൽ നിന്ന് നിങ്ങൾ നേടുന്ന റിവാർഡുകളാണ് യാത്രി നാണയങ്ങൾ."
        YATRI_COINS_FAQS_QUES1_ANS2 -> "സമ്പാദിച്ച നാണയങ്ങൾ കിഴിവുകൾ ലഭിക്കാൻ ഉപയോഗിക്കാം (ഉദാഹരണം: നാണയങ്ങൾ ഉപയോഗിച്ച് സബ്സ്ക്രിപ്ഷൻ പ്ലാനുകൾ വാങ്ങുന്നതിനുള്ള കിഴിവുകൾ)"
        YATRI_COINS_FAQS_QUES1_ANS3 -> "ഓരോ യാത്രാ നാണയവും രൂപ കിഴിവായി മാറ്റാം. 0.10, സബ്‌സ്‌ക്രിപ്‌ഷൻ പ്ലാനുകളിൽ കിഴിവ് ലഭിക്കുന്നതിന് ഇത് ഉപയോഗിക്കാം. ഡിസ്‌കൗണ്ടുകൾ ലഭിക്കുന്നതിനുള്ള കൂടുതൽ വഴികൾ ഭാവിയിൽ ചേർക്കും."
        YATRI_COINS_FAQS_QUES2 -> "യാത്രി നാണയങ്ങളുടെ സാധുത എന്താണ്?"
        YATRI_COINS_FAQS_QUES2_ANS1 -> "യാത്രി നാണയങ്ങൾ സമ്പാദിച്ച ദിവസം മുതൽ 90 ദിവസത്തേക്ക് സാധുതയുള്ളതാണ്. ഈ കാലയളവിൽ, ആനുകൂല്യങ്ങൾ ലഭിക്കുന്നതിന് നിങ്ങൾക്ക് നാണയങ്ങൾ ഉപയോഗിക്കാം."
        YATRI_COINS_FAQS_QUES2_ANS2 -> "90 ദിവസത്തിനുള്ളിൽ വീണ്ടെടുക്കാത്ത യാത്രി നാണയങ്ങൾ കണ്ടുകെട്ടി"
        YATRI_COINS_FAQS_QUES3 -> "എനിക്ക് എങ്ങനെ യാത്രി നാണയങ്ങൾ സമ്പാദിക്കാം?"
        YATRI_COINS_FAQS_QUES3_ANS1 -> "റൈഡുകൾ, ഉപഭോക്താക്കളെ റഫർ ചെയ്യൽ തുടങ്ങിയ ആപ്പിലെ ദൈനംദിന പ്രവർത്തനങ്ങളിലൂടെയാണ് നാണയങ്ങൾ സമ്പാദിക്കുന്നത്. നിങ്ങൾ വ്യത്യസ്തമായി ഒന്നും ചെയ്യേണ്ടതില്ല."
        YATRI_COINS_FAQS_QUES3_ANS2 -> "കുറഞ്ഞ റദ്ദാക്കലുകൾ, ഉപഭോക്താക്കളിൽ നിന്ന് നല്ല റേറ്റിംഗ് നേടൽ തുടങ്ങിയ നല്ല പെരുമാറ്റം പ്രകടിപ്പിക്കുന്നതിലൂടെ നിങ്ങൾക്ക് കൂടുതൽ നാണയങ്ങൾ നേടാനാകും."
        YATRI_COINS_FAQS_QUES4 -> "ഞാൻ സമ്പാദിച്ച യാത്രി നാണയങ്ങൾ എങ്ങനെ ഉപയോഗിക്കാം?"
        YATRI_COINS_FAQS_QUES4_ANS1 -> "സാധുതയുള്ള കാലയളവിനുള്ളിൽ സബ്‌സ്‌ക്രിപ്‌ഷൻ പ്ലാനുകൾ സൗജന്യമായി വാങ്ങാൻ നിങ്ങൾക്ക് സമ്പാദിച്ച നാണയങ്ങൾ ഉപയോഗിക്കാം."
        YATRI_COINS_FAQS_QUES4_ANS2 -> "ഭാവിയിൽ, യാത്രി നാണയങ്ങൾ ഉപയോഗിക്കുന്നതിന് കൂടുതൽ ഓപ്ഷനുകൾ ചേർക്കും."
        YATRI_COINS_FAQS_QUES4_ANS3 -> "യാത്രി നാണയങ്ങൾ കിഴിവ് ലഭിക്കുന്നതിന് പുറമെ മറ്റ് ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കാൻ കഴിയില്ല"
        YATRI_COINS_FAQS_QUES5 -> "യാത്രി നാണയങ്ങൾ സമ്പാദിക്കാനും ഉപയോഗിക്കാനുമുള്ള യോഗ്യത എന്താണ്?"
        YATRI_COINS_FAQS_QUES5_ANS1 -> "യാത്രി നാണയങ്ങൾ സമ്പാദിക്കാൻ തുടങ്ങാൻ, നമ്മ യാത്രിക്കൊപ്പം നിങ്ങളുടെ ആദ്യ സവാരി പൂർത്തിയാക്കണം."
        YATRI_COINS_FAQS_QUES5_ANS2 -> "നിങ്ങളുടെ ആദ്യ സവാരി പൂർത്തിയാക്കുന്നത് വരെ യാത്രി കോയിൻസ് വിഭാഗം പ്രവർത്തനരഹിതമാക്കും."
        YATRI_COINS_FAQS_QUES6 -> "വിവിധ പ്രവർത്തനങ്ങൾക്കായി എനിക്ക് എത്ര നാണയങ്ങൾ നേടാം അല്ലെങ്കിൽ നഷ്ടപ്പെടും?"
        YATRI_COINS_FAQS_QUES6_ANS1 -> "ഇനിപ്പറയുന്ന പട്ടികയെ അടിസ്ഥാനമാക്കി വിവിധ പ്രവർത്തനങ്ങൾക്കായി നാണയങ്ങൾ നേടുകയോ നഷ്ടപ്പെടുകയോ ചെയ്യുന്നു:"
        TASK_COMPLETED -> "ടാസ്ക് പൂർത്തിയാക്കി"
        RIDES_IN_A_DAY_PREFIX -> "ഒരു ദിവസം "
        RIDES_IN_A_DAY_SUFFIX -> " റൈഡുകൾ"
        STAR_RATING_FOR_THE_TRIP -> "യാത്രയിലേക്കുള്ള 5-നക്ഷത്ര അനുമാനം"
        ONE_TWO_START_RATING -> "യാത്രയിലേക്കുള്ള 1 അല്ലെങ്കിൽ 2-നക്ഷത്ര അനുമാനം"
        BOOKING_CANCELLATION -> "ബുക്കിംഗ് റദ്ദാക്കൽ"
        PAID_BY -> "അടച്ചത്"
        DRIVER_REFERRAL_CODE -> "ഡ്രൈവർ \n റഫറൽ കോഡ്"
        APP_QR_CODE -> "ആപ്പ് QR കോഡ്"
        START_TAKING_RIDES_AND_REFER _-> "നമ്മ യാത്രി ഡ്രൈവർ ആപ്പിൽ സൈൻ അപ്പ് ചെയ്യുന്നതിന് റൈഡുകൾ എടുക്കുകയും ഡ്രൈവർമാരെ റഫർ ചെയ്യുകയും ചെയ്യുക"
        REFERRED_DRIVERS -> "റഫർ ചെയ്ത ഡ്രൈവർമാർ"
        RIDE_LEADERBOARD -> "ലീഡർബോർഡ് ഓടിക്കുക"
        YOUR_RANK -> "നിങ്ങളുടെ റാങ്ക്"
        NOT_AVAILABLE_YET -> "ഇതുവരെ ലഭ്യമല്ല"
        ENTER_REFERRAL_CODE -> "റഫറൽ കോഡ് നൽകുക"
        HAVE_A_REFERRAL_CODE -> "ഒരു റഫറൽ കോഡ് ഉണ്ടോ?"
        COMPLETE_STEPS_TO_APPLY_REFERRAL -> "റഫറൽ കോഡ് പ്രയോഗിക്കുന്നതിന് മുകളിലുള്ള ഘട്ടങ്ങൾ പൂർത്തിയാക്കുക"
        DOWNLOAD_NAMMA_YATRI _-> "നമ്മ യാത്രി ഡൗൺലോഡ് ചെയ്യുക"
        ENTER_CODE -> "കോഡ് നൽകുക"
        COMPLETE_REGISTRATION -> "പൂർണ്ണമായ രജിസ്ട്രേഷൻ"
        CANT_FIND_OPTION -> "ഓപ്ഷൻ കണ്ടെത്താൻ കഴിയുന്നില്ല"
        HELP_FAQ -> "സഹായം"
        BONUS_COINS -> "ബോണസ് നാണയങ്ങൾ"
        MAX -> "പരമാവധി"
        COINS -> "നാണയങ്ങൾ"
        COINS_ADDED -> "നാണയങ്ങൾ ചേർക്കപ്പെട്ടു"
        REFERRAL -> "റഫറൽ"
        BENEFITS -> "പ്രയോജനങ്ങൾ"
        YOUR_DAILY_RANK -> "നിങ്ങളുടെ ദിവസം റാങ്ക്"
        CLICK_TO_EXPAND -> "വികസിപ്പിക്കാൻ\nക്ലിക്കുചെയ്യുക"
        REFERRED -> "റഫറൽ"
        ACTIVATED -> "സജീവമാക്കി"
        REFER_DRIVER -> "ഡ്രൈവർ റഫറൽ"
        REFER_CUSTOMER -> "കസ്റ്റമർ റഫറൽ"
        REFERRED_DRIVERS_INFO _ -> "നമ്മ യാത്രിയിൽ അനുസൃത ഡ്രൈവേഴ്സുകൾ രജിസ്റ്റർ ചെയ്തവർ"
        REFERRED_CUSTOMERS_INFO _ -> "നമ്മ യാത്രിയിൽ അനുസൃത ഗ്രാഹകർ രജിസ്റ്റർ ചെയ്തവർ"
        ACTIVATED_CUSTOMERS_INFO -> "തങ്ങളുടെ ആദ്യ യാത്ര വിജയകരമായി പൂരീകരിച്ചവർ"
        CUSTOMER_REFERRAL_CODE -> "കസ്റ്റമർ \n റഫറൽ കോഡ്"
        ACCEPT_RIDE_TO_ENTER_LEADERBOARD -> "റൈഡുകൾ അംഗീകരിക്കുകയും\nഒരു ശീര്ഷ ഡ്രൈവർ ആകുക"
        CONTACT_SUPPORT_VIA -> "പിന്തുണയുമായി ബന്ധപ്പെടുക"
        YOU_CAN_SHARE_SCREENSHOT -> "മാനുവൽ ഓൺബോർഡിംഗിനായി നിങ്ങൾക്ക് സ്ക്രീൻഷോട്ടുകളും പ്രമാണങ്ങളും പങ്കിടാം"
        PLACE_A_CALL -> "രേഖകൾ പരിശോധിച്ചുറപ്പിക്കുന്നതിനുള്ള ദ്രുത സഹായത്തിനായി ഒരു കോൾ ചെയ്യുക"
