module Resources.Localizable.TA where

import Language.Types (STR(..))

getTA :: STR -> String
getTA stringKey =
    case stringKey of
        INACCURATE_DATE_AND_TIME -> "துல்லியமற்ற தேதி & நேரம்!"
        ADJUST_YOUR_DEVICE_DATE_AND_TIME_AND_TRY_AGAIN -> "உங்கள் அமைப்புகள் பயன்பாட்டிலிருந்து தானியங்கு (நெட்வொர்க் வழங்கிய) தேதி மற்றும் நேர அமைப்பைத் தேர்ந்தெடுக்கவும்."
        THE_CURRENT_DATE_AND_TIME_IS -> "தற்போதைய தேதி மற்றும் நேரம்"
        GO_TO_SETTING -> "அமைப்புகளுக்குச் செல்லவும்"
        LETS_GET_STARTED -> "ஆரம்பிக்கலாம்"
        YOUR_APPLICATION_HAS_BEEN_SUBMITTED_SUCCESSFULLY_AND_IS_UNDER_VERIFICATION -> "உங்கள் விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டு சரிபார்ப்பின் கீழ் உள்ளது"
        VIEW_STATUS -> "நிலையைக் காண்க"
        GO_HOME -> "முகப்பு பக்கத்திற்கு செல்லவும்"
        SELECT_LANGUAGE -> "மொழியை தேர்ந்தெடுங்கள்"
        WHICH_LANGUAGE_DO_YOU_PREFER -> "நீங்கள் எந்த மொழியை விரும்புகிறீர்கள்?"
        NEXT -> "அடுத்தது"
        T_C -> "விதிமுறைகளும் நிபந்தனைகளும்"
        ENTER_MOBILE_NUMBER -> "மொபைல் எண்ணை உள்ளிடவும்"
        BY_CLICKING_CONTINUE_YOU_WILL_BE_AGREEING_TO_OUR -> "தொடரவும் என்பதைக் கிளிக் செய்வதன் மூலம், எங்களுடையதை ஒப்புக்கொள்கிறீர்கள்"
        ENTER_OTP -> "OTP ஐ உள்ளிடவும்"
        DIDNT_RECIEVE_OTP -> "OTP ஐப் பெறவில்லையா? "
        RESEND_OTP -> "OTP ஐ மீண்டும் அனுப்பவும்"
        PLEASE_ENTER_VALID_OTP -> "செல்லுபடியாகும் OTP ஐ உள்ளிடவும்"
        INVALID_MOBILE_NUMBER -> "மொபைல் எண்ணை சரிபார்க்கவும்"
        REGISTER -> "பதிவு"
        MOBILE_NUMBER -> "கைபேசி எண்"
        AUTO_READING_OTP -> "otp தானாக படிக்கப்படுகிறது"
        UPLOAD_DRIVING_LICENSE -> "ஓட்டுநர் உரிமத்தை பதிவேற்றவும்"
        UPLOAD_BACK_SIDE -> "பின் பக்கத்தை பதிவேற்றவும்"
        UPLOAD_FRONT_SIDE -> "உங்கள் ஓட்டுநர் உரிமத்தின் புகைப்படப் பக்கத்தைப் பதிவேற்றவும்"
        BACK_SIDE -> "பின்புறம்"
        FRONT_SIDE -> "உங்கள் ஓட்டுநர் உரிமத்தின் புகைப்பட பக்கம்"
        LICENSE_INSTRUCTION_PICTURE -> "ஓட்டுநர் உரிமத்தின் இருபுறமும் தெளிவான படங்களை பதிவேற்றவும்"
        LICENSE_INSTRUCTION_CLARITY -> "புகைப்படம் மற்றும் அனைத்து விவரங்களும் தெளிவாகத் தெரியும் என்பதை உறுதிப்படுத்தவும்"
        REGISTRATION_STEPS -> "பதிவு படிகள்"
        PROGRESS_SAVED -> "உங்கள் முன்னேற்றம் பதிவு செய்யப்பட்டது, எந்தவொரு தகவலையும் மாற்ற முந்தைய படிகளுக்கும் நீங்கள் செல்லலாம்"
        DRIVING_LICENSE -> "ஓட்டுனர் உரிமம்"
        AADHAR_CARD -> "ஆதார் அட்டை"
        BANK_DETAILS -> "வங்கி விவரங்கள்"
        VEHICLE_DETAILS -> "வாகன விவரங்கள்"
        UPLOAD_FRONT_BACK -> "முன் மற்றும் பின் பக்கத்தைப் பதிவேற்றவும்"
        EARNINGS_WILL_BE_CREDITED -> "உங்கள் வருமானம் இங்கே வரவு வைக்கப்படும்"
        FILL_VEHICLE_DETAILS -> "உங்கள் வாகன விவரங்களை நிரப்பவும்"
        FOLLOW_STEPS -> "பதிவு செய்ய கீழே உள்ள படிகளைப் பின்பற்றவும்"
        REGISTRATION -> "பதிவு"
        UPLOAD_ADHAAR_CARD -> "ஆதார் அட்டையைப் பதிவேற்றவும்"
        ADHAAR_INTRUCTION_PICTURE -> "ஆதார் அட்டையின் இருபுறமும் தெளிவான படங்களை தயவுசெய்து பதிவேற்றவும்"
        ADD_VEHICLE_DETAILS -> "வாகன விவரங்களைச் நிரப்பவும்"
        VEHICLE_REGISTRATION_NUMBER -> "வாகனப் பதிவுச் சான்றிதழ் எண்"
        RE_ENTER_VEHICLE_REGISTRATION_NUMBER -> "வாகனப் பதிவுச் சான்றிதழ் எண்ணை மீண்டும் உள்ளிடவும்"
        ENTER_VEHICLE_NO -> "வாகனம் எண் உள்ளிடவும்."
        VEHICLE_TYPE -> "வாகனம் வகை"
        VEHICLE_MODEL_NAME -> "வாகன மாடல் பெயர்"
        ENTER_MODEL_NAME -> "மாடல் பெயரை உள்ளிடவும்"
        VEHICLE_COLOUR -> "வாகன நிறம்"
        ENTER_VEHICLE_COLOUR -> "வாகன நிறத்தை உள்ளிடவும்"
        UPLOAD_REGISTRATION_CERTIFICATE -> "பதிவு சான்றிதழ் (ஆர்.சி) பதிவேற்றவும்"
        UPLOAD_RC -> "ஆர்.சி. பதிவேற்றவும்"
        PREVIEW -> "முன்னோட்டம்"
        CHOOSE_VEHICLE_TYPE -> "வாகன வகையைத் தேர்வுசெய்க"
        BENIFICIARY_NUMBER -> "பயனாளி கணக்கு எண்"
        RE_ENTER_BENIFICIARY_NUMBER -> "பயனாளி கணக்கு எண்ணை மீண்டும் உள்ளிடவும்."
        IFSC_CODE -> "IFSC குறியீடு"
        SENDING_OTP -> "otp அனுப்பப்படுகிறது"
        PLEASE_WAIT_WHILE_IN_PROGRESS -> "தயவுசெய்து காத்திருங்கள். செயல்பாட்டில் உள்ளது"
        YOUR_REQUEST_HAS_TIMEOUT_TRY_AGAIN -> "உங்கள் கோரிக்கை நேரம் முடிந்தது. மீண்டும் முயற்சிக்கவும்"
        ERROR_OCCURED_PLEASE_TRY_AGAIN_LATER -> "பிழை ஏற்பட்டது, பின்னர் மீண்டும் முயற்சிக்கவும்"
        ENTER_OTP_SENT_TO -> " க்கு அனுப்பப்பட்ட otp ஐ உள்ளிடவும்"
        OTP_SENT_TO -> "க்கு OTP அனுப்பப்பட்டது"
        COUNTRY_CODE_INDIA -> "91"
        ENTER_ACCOUNT_NUMBER -> "வங்கி கணக்கு எண் உள்ளிடவும்"
        ADD_BANK_DETAILS -> "வங்கி விவரங்களைச் சேர்க்கவும்"
        ENTER_IFSC_CODE -> "IFSC குறியீட்டை உள்ளிடவும்"
        SUBMIT -> "படிவம் சமர்ப்பிக்கவும்"
        PERSONAL_DETAILS -> "தங்களின் விவரங்கள்"
        LANGUAGES -> "மொழிகள்"
        HELP_AND_FAQ -> "உதவி & கேள்விகள்"
        ABOUT -> "விவரம்"
        LOGOUT -> "வெளியேறு"
        UPDATE -> "புதுப்பிப்பு"
        EDIT -> "திருத்தவும்"
        AUTO -> "ஆட்டோ"
        NAME -> "பெயர்"
        PRIVACY_POLICY -> "தனியுரிமைக் கொள்கை"
        LOGO -> "லோகோ"
        ABOUT_APP_DESCRIPTION -> "நம்மா யாத்திரி கூட்டாளர் இயக்கிகளை ரைடர்ஸுடன் இணைக்க ஒரு திறந்த தளமாகும். முன்மொழியப்பட்ட விரும்பிய விகிதங்களைக் கொண்ட ரைடர்ஸைக் கண்டுபிடிப்பதை ஓட்டுநர்களுக்கு பயன்பாடு வசதியாக ஆக்குகிறது. சவாரி அடிப்படையிலான கமிஷன் இல்லை, மாதாந்திர சந்தா வடிவத்தில் சிறிய தொகையை செலுத்துங்கள்"
        TERMS_AND_CONDITIONS -> "விதிமுறைகளும் நிபந்தனைகளும்"
        UPDATE_VEHICLE_DETAILS -> "வாகன விவரங்களை புதுப்பிக்கவும்"
        NOTE -> "குறிப்பு:"
        VISIT_MY_RIDES_SCREEN_FOR_SPECIFIC_COMPLAINTS -> "குறிப்பிட்ட புகார்களுக்கு எனது சவாரி பிரிவைப் பார்வையிடவும்"
        THANK_YOU_FOR_WRTITTING_US -> "எங்களுக்கு எழுதியதற்கு நன்றி!"
        WE_HAVE_RECIEVED_YOUR_ISSUE -> "உங்கள் பிரச்சினையை நாங்கள் பெற்றுள்ளோம். நாங்கள் உங்களை அணுகுவோம்."
        GO_TO_HOME -> "முகப்புத் திரைக்குச் செல்லவும்"
        YOUR_RECENT_RIDE -> "உங்கள் சமீபத்திய சவாரி"
        YOUR_RECENT_TRIP -> "Your Recent Trip"
        ALL_TOPICS -> "அனைத்து தலைப்புகளும்"
        REPORT_AN_ISSUE_WITH_THIS_TRIP -> "இந்த பயணத்தில் சிக்கலைப் புகாரளிக்கவும்"
        YOU_RATED -> "நீங்கள் மதிப்பிட்டீர்கள்:"
        VIEW_ALL_RIDES -> "எல்லா சவாரிகளையும் காண்க"
        WRITE_TO_US -> "எங்களுக்கு எழுதுங்கள்"
        SUBJECT -> "பொருள்"
        YOUR_EMAIL_ID -> "உங்கள் மின்னஞ்சல் ஐடி"
        DESCRIBE_YOUR_ISSUE -> "உங்கள் பிரச்சினையை விவரிக்கவும்"
        GETTING_STARTED_AND_FAQ -> "தொடங்குதல் மற்றும் கேள்விகள்"
        FOR_OTHER_ISSUES_WRITE_TO_US -> "பிற சிக்கல்களுக்கு, எங்களுக்கு எழுதுங்கள்"
        CALL_SUPPORT_CENTER -> "அழைப்பு ஆதரவு மையம்"
        YOU_CAN_DESCRIBE_ISSUE_THAT_YOU_FACED_HERE -> "நீங்கள் இங்கே எதிர்கொண்ட சிக்கலை விவரிக்கலாம்"
        REGISTRATION_CERTIFICATE_IMAGE -> "பதிவு சான்றிதழ் (ஆர்.சி) படம்"
        HOME -> "இல்லம்"
        RIDES -> "சவாரி"
        MY_RIDES -> "எனது சவாரிகள்"
        PROFILE -> "சுயவிவரம்"
        ENTER_DRIVING_LICENSE_NUMBER -> "ஓட்டுநர் உரிம எண்ணை உள்ளிடவும்"
        WHERE_IS_MY_LICENSE_NUMBER -> "எனது உரிம எண் எங்கே?"
        TRIP_DETAILS -> "பயண விவரங்கள்"
        BY_CASH -> "பணத்தால்"
        ONLINE_ -> "ஆன்லைன்"
        GO_ONLINE_POPUP -> "<u>போ ஆன்லைன்</u>"
        REPORT_AN_ISSUE -> "சிக்கலைப் புகாரளிக்கவும்"
        DISTANCE -> "தூரம்"
        TIME_TAKEN -> "எடுக்கப்பட்ட நேரம்"
        CALL -> "அழைப்பு"
        START_RIDE -> "சவாரி செய்யத் தொடங்குங்கள்"
        CANCEL_RIDE -> "சவாரி ரத்து செய்ய"
        PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL -> "நீங்கள் ஏன் ரத்து செய்ய விரும்புகிறீர்கள் என்று கூறுங்கள்"
        MANDATORY -> "கட்டாயமாகும்"
        END_RIDE -> "சவாரி முடிக்க"
        RIDE_COMPLETED_WITH -> "வாடிக்கையாளருடன் சவாரி முடிந்தது"
        COLLECT_AMOUNT_IN_CASH -> "தொகையை ரொக்கமாக பெறுங்கள்"
        CASH_COLLECTED -> "பணம் பெறப்பட்டது"
        OFFLINE -> "ஆஃப்லைன்"
        ACCEPT_FOR -> "இதற்கு ஏற்றுக்கொள்:"
        DECLINE -> "நிராகரிக்க"
        REQUEST -> "கோரிக்கை"
        YOU_ARE_OFFLINE -> "நீங்கள் ஆஃப்லைனில் இருக்கிறீர்கள்"
        YOU_ARE_CURRENTLY_BUSY_GO_ONLINE_TO_RECIEVE_TRIP_REQUESTS -> "நீங்கள் தற்போது பிஸியாக இருக்கிறீர்கள். பயண கோரிக்கைகளைப் பெற ஆன்லைனில் செல்லுங்கள்"
        GOING_OFFLINE_WILL_NOT_GET_YOU_ANY_RIDE -> "ஆஃப்லைனில் செல்வது உங்களுக்கு எந்த சவாரிக்கும் கிடைக்காது"
        CANCEL -> "ரத்துசெய்"
        GO_OFFLINE -> "ஆஃப்லைனில் செல்லுங்கள்"
        IS_WAITING_FOR_YOU -> "பிக்கப் போகிறது"
        YOU_ARE_ON_A_RIDE -> "சவாரி தொடங்கியது..."
        PLEASE_ASK_RIDER_FOR_THE_OTP -> "OTP க்கு ரைடரிடம் கேளுங்கள்"
        COMPLETED_ -> "நிறைவு"
        CANCELLED_ -> "ரத்து செய்யப்பட்டது"
        WE_NEED_SOME_ACCESS -> "பின்வரும் அணுகலை எங்களுக்கு வழங்கவும்!"
        ALLOW_ACCESS -> "அணுகலை அனுமதிக்கவும்"
        THANK_YOU_FOR_WRITING_TO_US -> "எங்களுக்கு எழுதியதற்கு நன்றி!"
        RIDER -> "சவாரி"
        TRIP_ID -> "பயண ஐடி"
        NEED_IT_TO_SHOW_YOU_INCOMING_RIDE_REQUEST -> "பயன்பாடு பின்னணியில் இருக்கும்போது உள்வரும் சவாரி கோரிக்கையைப் பெறுங்கள்"
        NEED_IT_TO_DISABLE_BATTERY_OPTIMIZATION_FOR_THE_APP -> "பரிந்துரைக்கப்படுகிறது, பயன்பாட்டை நீண்ட நேரம் பின்னணியில் இயக்க உதவுகிறது"
        NEED_IT_TO_AUTOSTART_YOUR_APP -> "பயன்பாட்டை பின்னணியில் வைத்திருப்பதன் மூலம் உதவுகிறது"
        NEED_IT_TO_ENABLE_LOCATION -> "பயன்பாடு மூடப்பட்டிருந்தாலும் கூட, இயக்கி தற்போதைய இருப்பிடத்தை கண்காணிக்க உங்கள் இருப்பிடத்தைப் பகிர்வதற்கு நம்மா யாத்ரி கூட்டாளர் இருப்பிடத் தரவை சேகரிக்கவும்"
        OVERLAY_TO_DRAW_OVER_APPLICATIONS -> "பயன்பாட்டை அனுமதிக்கவும்"
        BATTERY_OPTIMIZATIONS -> "பேட்டரி தேர்வுமுறை"
        AUTO_START_APPLICATION_IN_BACKGROUND -> "பின்னணியில் ஆட்டோஸ்டார்ட் பயன்பாடு"
        LOCATION_ACCESS -> "இருப்பிட அணுகல்"
        ENTER_RC_NUMBER -> "ஆர்.சி எண்ணை உள்ளிடவும்"
        WHERE_IS_MY_RC_NUMBER -> "எனது ஆர்.சி எண் எங்கே?"
        STEP -> "படி"
        PAID -> "பணம்"
        ENTERED_WRONG_OTP -> "தவறான OTP உள் நுழைந்தது"
        OTP_INVALID_FOR_THIS_VEHICLE_VARIANT ->  "தவறான OTP - சவாரி வகையுடன் வாகன வகை பொருந்தவில்லை"
        COPIED -> "நகலெடுக்கப்பட்டது"
        BANK_NAME -> "வங்கி பெயர்"
        AADHAR_DETAILS -> "ஆதார் விவரங்கள்"
        AADHAR_NUMBER -> "ஆதார் எண்"
        FRONT_SIDE_IMAGE -> "முன் பக்க படம்"
        BACK_SIDE_IMAGE -> "பின் பக்க படம்"
        STILL_NOT_RESOLVED -> "இன்னும் தீர்க்கப்படவில்லை? எங்களை அழைக்கவும்"
        CASE_TWO -> "b) க்கு"
        NON_DISCLOUSER_AGREEMENT -> "ஒப்பந்தம்"
        DATA_COLLECTION_AUTHORITY -> "c) எனது தகவல்களைச் சேகரிக்க ஜஸ்பேவை நான் இதன்மூலம் நியமிக்கிறேன் மற்றும் அங்கீகரிக்கிறேன், தொடர்வதன் மூலம், பயன்பாட்டு விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறேன்."
        SOFTWARE_LICENSE -> "மென்பொருள் உரிமம்"
        LOAD_MORE -> "அதிகமாய் ஏற்று"
        ARE_YOU_SURE_YOU_WANT_TO_LOGOUT -> "நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?"
        GO_BACK -> "திரும்பி செல்"
        THANK_YOU_FOR_REGISTERING_US -> "எங்களுடன் பதிவு செய்ததற்கு நன்றி!"
        UNFORTANUTELY_WE_ARE_NOT_AVAILABLE__YET_FOR_YOU -> "துரதிர்ஷ்டவசமாக, உங்களுக்கான சவாரிகள் எங்களிடம் இல்லை. விரைவில் உங்களுக்கு அறிவிப்போம்."
        ARE_YOU_SURE_YOU_WANT_TO_END_THE_RIDE -> "சவாரி முடிக்க விரும்புகிறீர்களா?"
        EMPTY_RIDES -> "வெற்று சவாரிகள்"
        YOU_HAVE_NOT_TAKEN_A_TRIP_YET -> "நீங்கள் இன்னும் பயணம் எடுக்கவில்லை"
        BOOK_NOW -> "பதிவு"
        RESEND_OTP_IN -> "OTP ஐ மீண்டும் அனுப்பவும்"
        WE_NEED_ACCESS_TO_YOUR_LOCATION -> "உங்கள் இருப்பிடத்திற்கான அணுகல் எங்களுக்கு தேவை!"
        YOUR_LOCATION_HELPS_OUR_SYSTEM _ -> "உங்கள் இருப்பிடம் எங்கள் கணினியை ஆட்டோக்கள் மூலம் அருகிலுள்ள அனைத்து வரைபடத்தையும், விரைவாக சவாரி செய்ய உதவுகிறது."
        NO_INTERNET_CONNECTION -> "இணைய இணைப்பு இல்லை"
        PLEASE_CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN -> "இணைய இணைப்பை சரிபார்த்து மீண்டும் முயற்சிக்கவும்"
        TRY_AGAIN -> "மீண்டும் முயற்சி செய்"
        GRANT_ACCESS -> "அனுமதி வழங்கு"
        YOUR_LIMIT_EXCEEDED_TRY_AGAIN_AFTER_10_MIN -> "நீங்கள் வரம்பை மீறுகிறீர்கள், 10 நிமிடங்களுக்குப் பிறகு மீண்டும் முயற்சிக்கவும்"
        ENTER_REFERRAL_MOBILE_NUMBER -> "பரிந்துரை மொபைல் எண்ணை உள்ளிடவும்"
        APPLY -> "விண்ணப்பிக்கவும்"
        HAVE_A_REFERRAL -> "பரிந்துரை உள்ளதா?"
        ADD_HERE -> "இங்கே சேர்க்கவும்"
        REFERRAL_APPLIED -> "பரிந்துரை குறியீடு பயன்படுத்தப்பட்டது"
        SMALLEDIT -> "திருத்துதல்"
        ADD_DRIVING_LICENSE -> "ஓட்டுநர் உரிமத்தைச் சேர்க்கவும்"
        HELP -> "உதவி?"
        INVALID_DL_NUMBER -> "தவறான டி.எல் எண்"
        DRIVING_LICENSE_NUMBER -> "ஓட்டுநர் உரிம எண்"
        RE_ENTER_DRIVING_LICENSE_NUMBER -> "ஓட்டுநர் உரிம எண்ணை மீண்டும் உள்ளிடவும்"
        ENTER_DL_NUMBER -> "டி.எல் எண்ணை உள்ளிடவும்"
        SELECT_DATE_OF_BIRTH -> "பிறந்த தேதியைத் தேர்ந்தெடுக்கவும்"
        DATE_OF_BIRTH -> "பிறந்த தேதி"
        WATCH_A_TUTORIAL_FOR_EASY_REGISTRATION -> "எளிதான \n பதிவுக்கான டுடோரியலைப் பார்க்கவும்"
        ENTER_MINIMUM_FIFTEEN_CHARACTERS -> "குறைந்தபட்சம் 15 எழுத்துகளை உள்ளிடவும்"
        ADD_YOUR_FRIEND -> "உங்கள் நண்பரைச் சேர்க்கவும்"
        PLEASE_WAIT_WHILE_VALIDATING_THE_IMAGE -> "படத்தை சரிபார்க்கும்போது காத்திருங்கள்"
        VALIDATING -> "சரிபார்ப்பு"
        VERIFICATION_PENDING -> "சரிபார்ப்பு நிலுவையில் உள்ளது"
        VERIFICATION_FAILED -> "சரிபார்ப்பு தோல்வியடைந்தது"
        NO_DOC_AVAILABLE -> "எந்த ஆவணமும் கிடைக்கவில்லை"
        ISSUE_WITH_DL_IMAGE -> "உங்கள் டி.எல் படத்தில் சில சிக்கல்கள் இருப்பதாகத் தெரிகிறது, எங்கள் ஆதரவு குழு விரைவில் உங்களைத் தொடர்பு கொள்ளும்."
        STILL_HAVE_SOME_DOUBT -> "இன்னும் சில சந்தேகங்கள் உள்ளதா?"
        ISSUE_WITH_RC_IMAGE -> "உங்கள் ஆர்.சி படத்தில் சில சிக்கல்கள் இருப்பதாகத் தெரிகிறது, எங்கள் ஆதரவு குழு விரைவில் உங்களைத் தொடர்பு கொள்ளும்."
        PLEASE_CHECK_FOR_IMAGE_IF_VALID_DOCUMENT_IMAGE_OR_NOT -> "செல்லுபடியாகும் ஆவணப் படம் அல்லது இல்லையென்றால் படத்தை சரிபார்க்கவும்"
        OOPS_YOUR_APPLICATION_HAS_BEEN_REJECTED -> "உங்கள் விண்ணப்பம் நிராகரிக்கப்பட்டுள்ளது. தயவுசெய்து மீண்டும் முயற்சி செய்க"
        INVALID_DRIVING_LICENSE -> "தவறான ஓட்டுநர் உரிமம்"
        LIMIT_EXCEEDED_FOR_DL_UPLOAD -> "டி.எல் பதிவேற்றத்திற்கு வரம்பு மீறுகிறது"
        INVALID_VEHICLE_REGISTRATION_CERTIFICATE -> "தவறான வாகன பதிவு சான்றிதழ்"
        LIMIT_EXCEEDED_FOR_RC_UPLOAD -> "ஆர்.சி பதிவேற்றத்திற்கு வரம்பு மீறுகிறது"
        YOUR_DOCUMENTS_ARE_APPROVED -> "உங்கள் ஆவணங்கள் அங்கீகரிக்கப்பட்டுள்ளன. ஆதரவு குழு விரைவில் உங்கள் கணக்கை இயக்கும். உங்கள் கணக்கை இயக்க ஆதரவு குழுவையும் அழைக்கலாம்"
        APPLICATION_STATUS -> "பயன்பாட்டு நிலை"
        FOR_SUPPORT -> "ஆதரவுக்கு"
        CONTACT_US -> "எங்களை தொடர்பு கொள்ள"
        IMAGE_VALIDATION_FAILED -> "படத்தின் சரிபார்ப்பு தோல்வியடைந்தது"
        IMAGE_NOT_READABLE -> "படம் படிக்க முடியாது"
        IMAGE_LOW_QUALITY -> "படத்தின் தரம் நன்றாக இல்லை"
        IMAGE_INVALID_TYPE -> "வழங்கப்பட்ட பட வகை உண்மையான வகையுடன் பொருந்தாது"
        IMAGE_DOCUMENT_NUMBER_MISMATCH -> "இந்த படத்தில் ஆவண எண் உள்ளீட்டுடன் பொருந்தவில்லை"
        IMAGE_EXTRACTION_FAILED -> "படம் பிரித்தெடுத்தல் தோல்வியடைந்தது"
        IMAGE_NOT_FOUND -> "படம் கிடைக்கவில்லை"
        IMAGE_NOT_VALID -> "படம் செல்லுபடியாகாது"
        DRIVER_ALREADY_LINKED -> "மற்ற ஆவணங்கள் ஏற்கனவே டிரைவருடன் இணைக்கப்பட்டுள்ளன"
        DL_ALREADY_UPDATED -> "எந்த நடவடிக்கையும் தேவையில்லை. ஓட்டுநர் உரிமம் ஏற்கனவே டிரைவருடன் இணைக்கப்பட்டுள்ளது"
        RC_ALREADY_LINKED -> "வாகனம் ஆர்.சி கிடைக்கவில்லை. மற்ற டிரைவருடன் இணைக்கப்பட்டுள்ளது"
        RC_ALREADY_UPDATED -> "எந்த நடவடிக்கையும் தேவையில்லை. வாகன ஆர்.சி ஏற்கனவே டிரைவருடன் இணைக்கப்பட்டுள்ளது"
        DL_ALREADY_LINKED -> "ஓட்டுநர் உரிமம் கிடைக்கவில்லை. மற்ற டிரைவருடன் இணைக்கப்பட்டுள்ளது"
        SOMETHING_WENT_WRONG -> "ஏதோ தவறு நடைபெற்றிருக்கிறது"
        PICKUP -> "பிக் அப்"
        TRIP -> "பயணம்"
        CURRENTLY_WE_ALLOW_ONLY_KARNATAKA_REGISTERED_NUMBER _ -> "தற்போது,   கர்நாடகா பதிவு செய்யப்பட்ட எண்ணை மட்டுமே அனுமதிக்கிறோம்"
        UPDATED_AT -> "புதுப்பிக்கப்பட்டது"
        TRIP_COUNT -> "இன்றைய பயணங்கள்"
        TODAYS_EARNINGS -> "வருவாய்"
        BONUS_EARNED ->  "போனஸ் கிடைத்தது"
        GOT_IT ->  "அறிந்துகொண்டேன்!"
        WHAT_IS_NAMMA_YATRI_BONUS _ ->  "போனஸ் என்றால் என்ன?"
        BONUS_PRIMARY_TEXT ->  "நம்ம யாத்ரி போனஸ் என்பது பிக்அப் கட்டணங்கள், வாடிக்கையாளர் உதவிக்குறிப்புகள் மற்றும் ஓட்டுனர் சேர்த்தல் போன்ற வடிவங்களில் மீட்டர் கட்டணத்திற்கு மேல் நீங்கள் பெற்ற கூடுதல் தொகையாகும்."
        BONUS_SECONDARY_TEXT ->  "நம்ம யாத்ரி போனஸ் தொகை உங்கள் மொத்த வருவாயில் ஒரு பகுதியாகும்."
        DATE_OF_REGISTRATION -> "பதிவு செய்த தேதி"
        SELECT_DATE_OF_ISSUE -> "வெளியீட்டு தேதியைத் தேர்ந்தெடுக்கவும்"
        DATE_OF_ISSUE -> "வெளியீட்டு தேதி"
        PROVIDE_DATE_OF_ISSUE_TEXT -> "மன்னிக்கவும், உங்கள் விவரங்களை எங்களால் சரிபார்க்க முடியவில்லை, தயவுசெய்து உங்கள் ஓட்டுநர் உரிமத்தை சரிபார்க்க <b> வெளியீட்டு தேதி </b> ஐ வழங்கவும்."
        PROVIDE_DATE_OF_REGISTRATION_TEXT -> "மன்னிக்கவும், உங்கள் விவரங்களை எங்களால் சரிபார்க்க முடியவில்லை, உங்கள் வாகன விவரங்களை சரிபார்க்க <b> பதிவு தேதி </b> ஐ வழங்கவும்."
        SELECT_DATE_OF_REGISTRATION -> "பதிவு தேதியைத் தேர்ந்தெடுக்கவும்"
        SAME_REENTERED_RC_MESSAGE -> "மீண்டும் உள்ளிடப்பட்ட RC எண்ணும் மேலே கொடுக்கப்பட்டுள்ள RC எண்ணும் ஒன்றே என்பதை உறுதிப்படுத்தவும்"
        SAME_REENTERED_DL_MESSAGE -> "மீண்டும் உள்ளிடப்பட்ட DL எண்ணும் மேலே வழங்கப்பட்ட DL எண்ணும் பொருந்தவில்லை"
        WHERE_IS_MY_ISSUE_DATE -> "வெளியீட்டு தேதி எங்கே?"
        WHERE_IS_MY_REGISTRATION_DATE -> "பதிவு தேதி எங்கே?"
        EARNINGS_CREDITED_IN_ACCOUNT -> "உங்கள் வருவாய் இந்த கணக்கில் வரவு வைக்கப்படும்"
        INVALID_PARAMETERS -> "தவறான அளவுருக்கள்"
        UNAUTHORIZED -> "அங்கீகரிக்கப்படாதது"
        INVALID_TOKEN -> "செல்லுபடியாகாத டோக்கன்"
        SOME_ERROR_OCCURED_IN_OFFERRIDE -> "ஆஃபர் ரைடில் சில பிழை ஏற்பட்டது"
        SELECT_VEHICLE_TYPE -> "வாகன வகையைத் தேர்ந்தெடுக்கவும்"
        RIDE -> "சவாரி"
        NO_LOCATION_UPDATE -> "புதுப்பிப்பு இல்லை"
        GOT_IT_TELL_US_MORE -> "புரிந்தது, மேலும் சொல்லுங்கள்?"
        WRITE_A_COMMENT -> "கருத்தை எழுதுங்கள்"
        HOW_WAS_YOUR_RIDE_WITH -> "உங்கள் சவாரி எப்படி இருந்தது"
        RUDE_BEHAVIOUR -> "முரட்டுத்தனமான நடத்தை"
        LONG_WAITING_TIME -> "நீண்ட காத்திருப்பு நேரம்"
        DIDNT_COME_TO_PICUP_LOCATION -> "பிக்அப் இடத்திற்கு வரவில்லை"
        HELP_US_WITH_YOUR_REASON -> "உங்கள் காரணத்துடன் எங்களுக்கு உதவுங்கள்"
        MAX_CHAR_LIMIT_REACHED -> "அதிகபட்ச எழுத்து வரம்பை அடைந்தது,"
        SHOW_ALL_OPTIONS -> "அனைத்து விருப்பங்களையும் காட்டு"
        UPDATE_REQUIRED -> "புதுப்பித்தல் தேவை"
        PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE -> "சேவையைத் தொடர, பயன்பாட்டைப் புதுப்பிக்கவும்"
        NOT_NOW -> "இப்போது இல்லை"
        OF -> "இல்"
        DROP -> "டிராப்"
        PLEASE_WAIT -> "தயவுசெய்து காத்திருக்கவும்"
        SETTING_YOU_OFFLINE -> "நாங்கள் உங்கள் ஆஃப்லைனை அமைக்கிறோம்"
        SETTING_YOU_ONLINE -> "நாங்கள் உங்களை ஆன்லைனில் அமைக்கிறோம்"
        SETTING_YOU_SILENT -> "நாங்கள் உங்களை சைலன்ட் அமைக்கிறோம்"
        VIEW_BREAKDOWN -> "முறிவைக் காண்க"
        APP_INFO -> "ஆப் அமைப்புகள்"
        OTHER -> "மற்றவை"
        VEHICLE_ISSUE -> "வாகனப் பிரச்சினை"
        FARE_UPDATED -> "கட்டணம் புதுப்பிக்கப்பட்டது"
        FREQUENT_CANCELLATIONS_WILL_LEAD_TO_LESS_RIDES -> "சவாரிகளை அடிக்கடி ரத்து செய்வது குறைவான சவாரிகளுக்கு வழிவகுக்கும் மற்றும் மதிப்பீட்டைக் குறைக்கும்."
        CONTINUE -> "தொடரவும்"
        MORE -> "more"
        LESS -> "less"
        YOU_ARE_AT_PICKUP -> "நீங்கள் பிக்அப் இடத்தில் இருக்கிறீர்கள்"
        WAITING_FOR_CUSTOMER -> "-க்காக காத்திருக்கிறீர்கள்"
        CUSTOMER_NOTIFIED -> "வாடிக்கையாளருக்கு அறிவிக்கப்பட்டது"
        I_ARRIVED -> "வந்துவிட்டேன்"
        ESTIMATED_RIDE_FARE -> "மதிப்பிடப்பட்ட சவாரி கட்டணம்: "
        RIDE_FARE ->  "சவாரி கட்டணம்"
        CONFIRM_PASSWORD -> "கடவுச்சொல்லை உறுதிப்படுத்தவும்"
        DEMO_MODE -> "டெமோ பயன்முறை"
        PASSWORD -> "கடவுச்சொல்லை"
        ENTER_DEMO_MODE_PASSWORD -> "டெமோ பயன்முறை கடவுச்சொல்லை உள்ளிடவும்"
        DEMO_MODE_DISABLED -> "டெமோ பயன்முறை முடக்கப்பட்டது"
        ONLINE_VIA_DEMO_MODE -> "ஆன்லைன் (டெமோ)"
        PICKUP_TOO_FAR -> "பிக்அப் வெகு தொலைவில் உள்ளது"
        CUSTOMER_NOT_PICKING_CALL -> "வாடிக்கையாளர் அழைப்பை எடுக்கவில்லை"
        TRAFFIC_JAM -> "போக்குவரத்து நெரிசல்"
        CUSTOMER_WAS_RUDE -> "வாடிக்கையாளர் முரட்டுத்தனமாக நடந்து கொண்டார்"
        ALL_MESSAGES -> "அனைத்து செய்திகளும்"
        MESSAGES -> "செய்திகள்"
        ADD_A_COMMENT -> "கருத்தைச் சேர்"
        POST_COMMENT -> "கருத்து பதிவு"
        ENTER_YOUR_COMMENT -> "உங்கள் கருத்தை உள்ளிடவும்"
        NO_NOTIFICATIONS_RIGHT_NOW -> "தற்போது அறிவிப்புகள் இல்லை"
        NO_NOTIFICATIONS_RIGHT_NOW_DESC -> "புதிய அறிவிப்புகள் வரும்போது உங்களுக்குத் தெரிவிப்போம்"
        ALERTS -> "அறிவிப்புகள்"
        YOUR_COMMENT -> "தங்கள் கருத்து"
        SHOW_MORE -> "மேலும் காட்ட"
        LOAD_OLDER_ALERTS -> "பழைய எச்சரிக்கைகளை ஏற்றவும்"
        CONTEST -> "போட்டி"
        YOUR_REFERRAL_CODE_IS_LINKED -> "உங்கள் பரிந்துரை குறியீடு இணைக்கப்பட்டுள்ளது!"
        YOU_CAN_NOW_EARN_REWARDS -> "வாடிக்கையாளர்களைப் பரிந்துரைப்பதற்காக நீங்கள் இப்போது வெகுமதிகளைப் பெறலாம்!"
        COMING_SOON -> "விரைவில்!"
        COMING_SOON_DESCRIPTION -> "பரிந்துரை திட்டத்தில் உங்களை சேர்க்க நாங்கள் பணியாற்றி வருகிறோம். மேலும் தகவலுக்கு விழிப்பூட்டல்கள் பக்கத்தைப் பார்க்கவும்."
        REFERRAL_CODE_HINT -> "6 இலக்க பரிந்துரைக் குறியீட்டை உள்ளிடவும்"
        CONFIRM_REFERRAL_CODE -> "பரிந்துரை குறியீட்டை உறுதிப்படுத்தவும்"
        CONFIRM_REFERRAL_CODE_HINT -> "பரிந்துரை குறியீட்டை மீண்டும் உள்ளிடவும்"
        YOUR_REFERRAL_CODE -> "உங்கள் பரிந்துரை குறியீடு"
        FIRST_REFERRAL_SUCCESSFUL -> "முதல் பரிந்துரை வெற்றி!\nரிவார்டு திறக்கப்பட்டது!"
        AWAITING_REFERRAL_RIDE -> "பரிந்துரை சவாரிக்காக காத்திருக்கிறது"
        CHECK_THIS_SPACE_WHEN_YOU_GET_REFERRAL_ALERT -> "பரிந்துரை எச்சரிக்கையைப் பெறும்போது \nஇந்த இடத்தைச் சரிபார்க்கவும்"
        REFERRED_CUSTOMERS -> "பரிந்துரைக்கப்பட்ட வாடிக்கையாளர்கள்"
        ACTIVATED_CUSTOMERS -> "செயல்படுத்தப்பட்ட வாடிக்கையாளர்கள்"
        REFERRAL_CODE_LINKING -> "பரிந்துரை குறியீடு இணைப்பு"
        CONTACT_SUPPORT -> "ஆதரவைத் தொடர்பு கொள்ளவும்"
        CALL_SUPPORT -> "அழைப்பு ஆதரவு"
        YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT _ -> "நீங்கள் நம்ம யாத்ரி ஆதரவுக் குழுவிற்கு அழைப்பு விடுக்க உள்ளீர்கள். தொடர வேண்டுமா?"
        REFERRAL_ENROLMENT -> "பரிந்துரை பதிவு"
        REFERRALS -> "பரிந்துரைகள்"
        LINK_REFERRAL_CODE -> "இணைப்பு பரிந்துரை குறியீடு"
        DRIVER_DETAILS -> "டிரைவர் விவரங்கள்"
        FOR_UPDATES_SEE_ALERTS -> "புதுப்பிப்புகளுக்கு, விழிப்பூட்டல்களைப் பார்க்கவும்"
        SHARE_OPTIONS -> "பகிர்வு விருப்பங்கள்"
        ENTER_PASSWORD -> "கடவுச்சொல்லை உள்ளிடவும்"
        RIDE_DISTANCE ->  "சவாரி தூரம்"
        START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS ->  "இந்த விரைவான அரட்டை பரிந்துரைகளைப் பயன்படுத்தி உங்கள் அரட்டையைத் தொடங்கவும்"
        MESSAGE ->  "செய்தி"
        START_YOUR_CHAT_WITH_THE_DRIVER ->  "டிரைவருடன் உங்கள் அரட்டையைத் தொடங்கவும்"
        I_AM_ON_MY_WAY ->  "வந்து கொண்டிருக்கிறேன்"
        GETTING_DELAYED_PLEASE_WAIT ->  "தாமதமாகிறது, காத்திருக்கவும்"
        UNREACHABLE_PLEASE_CALL_BACK ->  "எனக்கு கால் செய்யுங்கள்"
        ARE_YOU_STARING ->  "வந்து கொண்டிருக்கிறீர்களா?"
        PLEASE_COME_SOON ->  "சீக்கிரம் வாருங்கள்"
        OK_I_WILL_WAIT ->  "நான் காத்திருக்கிறேன்"
        I_HAVE_ARRIVED ->  "நான் வந்துவிட்டேன்"
        PLEASE_COME_FAST_I_AM_WAITING ->  "சீக்கிரம் வாருங்கள்"
        PLEASE_WAIT_I_WILL_BE_THERE ->  "வந்துகொண்டிருக்கிறேன்"
        LOOKING_FOR_YOU_AT_PICKUP ->  "பிக்-அப்பில் உள்ளேன்"
        SILENT ->  "சைலண்ட்"
        TRY_SILENT_MODE ->  "சைலண்ட் பயன்முறையை முயற்சிக்கவா?"
        SILENT_MODE_PROMPT ->  "நீங்கள் தொந்தரவை தவிர்க்க விரும்பினால், நீங்கள் சைலண்ட் பயன்முறைக்கு மாறலாம்"
        GO_SILENT ->  "சைலண்ட் மோடுக்கு செல்லவும்"
        GO_ONLINE ->  "செல்‌!"
        GO_ONLINE_PROMPT ->  "நீங்கள் தற்போது ஆஃப்லைனில் உள்ளீர்கள். \n சவாரிகளைப் பெற, இப்போதே ஆன்லைனில் செல்லுங்கள்!"
        LIVE_DASHBOARD ->  "நேரடி புள்ளிவிவரங்கள் டாஷ்போர்டு"
        CLICK_TO_ACCESS_YOUR_ACCOUNT ->  "உங்கள் சுயவிவரத்தைக் காண இங்கே கிளிக் செய்யவும்"
        ADD_ALTERNATE_NUMBER ->  "மற்றொரு எண்ணைச் சேர்க்கவும்"
        ENTER_ALTERNATE_MOBILE_NUMBER ->  "மற்றொரு மொபைல் எண்ணை உள்ளிடவும்"
        PLEASE_ENTER_A_VALID_10_DIGIT_NUMBER ->  "சரியான 10 இலக்க எண்ணை உள்ளிடவும்"
        ALTERNATE_MOBILE_NUMBER ->  "மற்றொரு மொபைல் எண்"
        REMOVE ->  "அகற்று"
        REMOVE_ALTERNATE_NUMBER ->  "மற்றொரு எண்ணை அகற்று"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_YOUR_ALTERNATE_MOBILE_NUMBER ->  "உங்கள் மற்றொரு மொபைல் எண்ணை நிச்சயமாக அகற்ற விரும்புகிறீர்களா?"
        YES_REMOVE_IT ->  "ஆம், அதை அகற்று"
        NUMBER_REMOVED_SUCCESSFULLY ->  "எண் வெற்றிகரமாக அகற்றப்பட்டது"
        EDIT_ALTERNATE_MOBILE_NUMBER ->  "மற்றொரு மொபைல் எண்ணைத் திருத்தவும்"
        NUMBER_ADDED_SUCCESSFULLY ->  "எண் வெற்றிகரமாக சேர்க்கப்பட்டது"
        NUMBER_EDITED_SUCCESSFULLY ->  "எண் வெற்றிகரமாக புதுப்பிக்கப்பட்டது"
        ALTERNATE_MOBILE_OTP_LIMIT_EXCEED ->  "மற்றொரு மொபைல் எண் OTP வரம்பு மீறப்பட்டுள்ளது"
        WRONG_OTP ->  "சரியான OTP ஐ உள்ளிடவும் "
        ATTEMPTS_LEFT ->  " முயற்சிகள் எஞ்சியுள்ளன"
        OTP_LIMIT_EXCEEDED ->  "OTP வரம்பு மீறப்பட்டது"
        OTP_LIMIT_EXCEEDED_MESSAGE ->  "உங்கள் OTP வரம்பை அடைந்துவிட்டீர்கள். 10 நிமிடங்களுக்குப் பிறகு மீண்டும் முயற்சிக்கவும்."
        TRY_AGAIN_LATER ->  "பின்னர் மீண்டும் முயற்சிக்கவும்"
        ATTEMPT_LEFT ->  " முயற்சி எஞ்சியுள்ளன"
        NUMBER_ALREADY_EXIST_ERROR ->  "மற்றொரு கணக்குடன் எண் இணைக்கப்பட்டது! தயவுசெய்து வேறு எண்ணைப் பயன்படுத்தவும்"
        ADD_ALTERNATE_NUMBER_IN_MEANTIME ->  "இந்தச் செயல்முறை முடிய 2 வேலை நாட்கள் வரை ஆகலாம். இதற்கிடையில், நீங்கள் \nமாற்று மொபைல் எண்ணைச் சேர்க்கலாம்."
        VERIFICATION_IS_TAKING_A_BIT_LONGER ->  "உங்கள் சரிபார்ப்பு \nஎதிர்பார்த்ததை விட சற்று அதிகமாகிறது போல் தெரிகிறது.\nஉங்களுக்கு உதவ நீங்கள் ஆதரவை தொடர்பு கொள்ளலாம்."
        COMPLETE_ONBOARDING ->  "ஆன்போர்டிங்கை முடிக்கவும்"
        PERSON_WITH_THIS_NUMBER_ALREADY_EXISTS ->  "இந்த மொபைல் எண்ணைக் கொண்ட நபர் ஏற்கனவே இருக்கிறார்."
        OTP_ ->  "OTP"
        MAPS -> "Maps"
        DEMO ->  "டெமோ"
        PLEASE_ASK_THE_CUSTOMER_FOR_THE_OTP ->  "OTP ஐ வாடிக்கையாளரிடம் கேளுங்கள்"
        DELETE ->  "அழி"
        VIEW ->  "பார்வை"
        ISSUE_NO ->  "வெளியீடு எண்"
        ADD_VOICE_NOTE ->  "குரல் குறிப்பைச் சேர்க்கவும்"
        VOICE_NOTE_ADDED ->  "குரல் குறிப்பு சேர்க்கப்பட்டது"
        SUBMIT_ISSUE_DETAILS ->  "பிரச்சினை விவரங்களை சமர்ப்பிக்கவும்"
        IMAGE_PREVIEW ->  "பட முன்னோட்டம்"
        RIDE_REPORT_ISSUE ->  "சிக்கலைப் புகாரளிக்க சவாரி என்பதைத் தேர்ந்தெடுக்கவும்"
        ADDED_IMAGES ->  "படங்களைச் சேர்த்தது"
        NO_IMAGES_ADDED ->  "படங்கள் எதுவும் சேர்க்கப்படவில்லை"
        ASK_DETAILS_MESSAGE ->  "மேலும் சில விவரங்களைத் தரவும். மேலும் சிறப்பாக விவரிக்க படங்கள் அல்லது குரல் குறிப்புகளை அனுப்பலாம்."
        ASK_DETAILS_MESSAGE_REVERSED ->  "இழந்த பொருளைப் பற்றிய கூடுதல் விவரங்களைப் பகிரவும். மேலும் சிறப்பாக விவரிக்க படங்கள் அல்லது குரல் குறிப்புகளை அனுப்பலாம்."
        SELECT_OPTION ->  "இவற்றில் ஏதேனும் ஒன்றை நீங்கள் எதிர்கொண்டால் எங்களிடம் கூறுங்கள்"
        SELECT_OPTION_REVERSED ->  "இந்த சிக்கலை எவ்வாறு தீர்க்க விரும்புகிறீர்கள்?"
        ISSUE_SUBMITTED_MESSAGE ->  "பெறப்பட்ட விவரங்கள்! உங்கள் பிரச்சினைக்கு உதவ எங்கள் குழு 24 மணி நேரத்திற்குள் உங்களை அழைக்கும்."
        I_DONT_KNOW_WHICH_RIDE ->  "எந்த சவாரி என்று தெரியவில்லை"
        REPORT_ISSUE_CHAT_PLACEHOLDER _ ->  "உங்கள் பிரச்சினையை விவரிக்கவும். நம்ம யாத்ரி 24 மணி நேரத்திற்குள் அதைத் தீர்க்க முயற்சிக்கும்."
        ADDED_VOICE_NOTE ->  "குரல் குறிப்பு சேர்க்கப்பட்டது"
        NO_VOICE_NOTE_ADDED ->  "குரல் குறிப்பு சேர்க்கப்படவில்லை"
        CALL_CUSTOMER_TITLE ->  "வாடிக்கையாளரை அழைக்கவா"
        CALL_CUSTOMER_DESCRIPTION ->  "வாடிக்கையாளருக்கு அழைப்பை மேற்கொள்ள உள்ளீர்கள். தொடர வேண்டுமா?"
        PLACE_CALL ->  "அழைப்பு"
        ADD_IMAGE ->  "படத்தை சேர்க்க"
        ADD_ANOTHER ->  "இன்னொன்றை சேர்"
        IMAGES_ADDED ->  "படங்கள் சேர்க்கப்பட்டது"
        ISSUE_SUBMITTED_TEXT ->  "பொறுங்கள்! உங்கள் பிரச்சினையைத் தீர்ப்பதில் நாங்கள் பணியாற்றி வருகிறோம்"
        CHOOSE_AN_OPTION ->  "தொடர விருப்பத்தைத் தேர்வு செய்யவும்"
        IMAGE_ADDED ->  "படம் சேர்க்கப்பட்டது"
        DONE ->  "முடிந்தது"
        RECORD_VOICE_NOTE ->  "பதிவு குரல் குறிப்பு"
        HELP_AND_SUPPORT ->  "உதவி மற்றும் ஆதரவு"
        MORE_OPTIONS ->  "மேலும் விருப்பங்கள்"
        ONGOING_ISSUES ->  "தொடர்ந்து பிரச்சினைகள்"
        RESOLVED_ISSUES ->  "தீர்க்கப்பட்ட பிரச்சினைகள்"
        RESOLVED_ISSUE ->  "தீர்க்கப்பட்ட  சிக்கல்கள்"
        ONGOING_ISSUE ->  "தொடரும்  சிக்கல்கள்"
        LOST_ITEM ->  "இழந்த   பொருள்"
        RIDE_RELATED_ISSUE ->  "சவாரி தொடர்பான பிரச்சினை"
        APP_RELATED_ISSUE ->  "பயன்பாடு தொடர்பான சிக்கல்"
        FARE_RELATED_ISSUE ->  "கட்டணம் தொடர்பான பிரச்சினை"
        ISSUE_NUMBER ->  "வெளியீடு   எண்   "
        REMOVE_ISSUE ->  "சிக்கலை   அகற்று" 
        CALL_SUPPORT_NUMBER ->  "ஆதரவைத்  தொடர்பு  கொள்ளவும்"
        YEARS_AGO ->  "ஆண்டுகளுக்கு முன்பு"
        MONTHS_AGO ->  " மாதங்களுக்கு முன்பு"
        DAYS_AGO ->  " நாட்களுக்கு முன்பு"
        HOURS_AGO ->  " மணி நேரத்திற்க்கு முன்பு"
        MIN_AGO ->  " நிமிடத்திற்கு முன்பு"
        SEC_AGO ->  " இரண்டாவது முன்பு"
        LOADING ->  "ஏற்றுகிறது"
        APP_RELATED ->  "பயன்பாடு தொடர்பானது"
        FARE ->  "கட்டணம் தொடர்பானது"
        RIDE_RELATED ->  "சவாரி தொடர்பானது"
        LOST_AND_FOUND ->  "தொலைந்து போனது"
        REPORT_LOST_ITEM ->  "இழந்த பொருளைப் புகாரளிக்கவும"
        MAKE_YOURSELF_AVAILABLE_FOR ->  "பின்வருவனவற்றிற்கு உங்களைக் கிடைக்கச் செய்யுங்கள்"
        CONFIRM_AND_CHANGE ->  "உறுதிப்படுத்தி மாற்றவும்"
        SELECT_YOUR_GENDER -> "உங்கள் பாலினத்தை தேர்வுசெய்யவும்"
        FEMALE -> "பெண்"
        MALE -> "ஆண்"
        PREFER_NOT_TO_SAY -> "சொல்ல வேண்டாம் என்று விருப்பம்"
        GENDER ->  "பாலினம்"
        SET_NOW ->  "இப்போது அமைக்கவும்"
        COMPLETE_YOUR_PROFILE_AND_FIND_MORE_RIDES ->  "உங்கள் சுயவிவரத்தை நிறைவுசெய்து மேலும் சவாரிகளைக் கண்டறியவும்!"
        UPDATE_NOW ->  "இப்பொழுது மேம்படுத்து"
        CORPORATE_ADDRESS _ ->  "கார்ப்பரேட் முகவரி"
        CORPORATE_ADDRESS_DESCRIPTION _ ->  "ஜுஸ்பே டெக்னாலஜிஸ் பிரைவேட் லிமிடெட் <br> கிரிஜா பில்டிங், எண் 817, கணபதி கோயில் சாலை, 8வது பிளாக், கோரமங்களா, பெங்களூரு, கர்நாடகா 560095, இந்தியா."
        CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL _ ->  "இணையதளம் : <u>https://nammayatri.in/</u>"
        REGISTERED_ADDRESS _ ->  "பதிவு செய்யப்பட்ட முகவரி"
        REGISTERED_ADDRESS_DESCRIPTION _ ->  "ஜஸ்பே டெக்னாலஜிஸ் பிரைவேட் லிமிடெட் <br> ஸ்டாலியன் பிசினஸ் சென்டர், எண். 444, 3வது & 4வது தளம், 18வது மெயின், 6வது பிளாக், கோரமங்களா பெங்களூரு, கர்நாடகா- 560095, இந்தியா."
        REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL _ ->  "இணையதளம் : <u>https://nammayatri.in/</u>"
        CONFIRM ->  "உறுதி"
        GENDER_UPDATED ->  "பாலினம் புதுப்பிக்கப்பட்டது"
        ZONE_CANCEL_TEXT_DROP ->  "உங்கள் வாடிக்கையாளர் சரியான நேரத்தில் மெட்ரோ நிலையத்தை அடையும் அவசரத்தில் இருக்கலாம்! \n ரத்து செய்ய வேண்டாம் என்று கேட்டுக்கொள்கிறோம்."
        ZONE_CANCEL_TEXT_PICKUP ->  "உங்கள் வாடிக்கையாளர் தங்கள் இலக்கை அடைவதற்கான அவசரத்தில் இருக்கலாம். \n ரத்து செய்ய வேண்டாம் என்று கேட்டுக்கொள்கிறோம்."
        RANKINGS ->  "தரவரிசை"
        GETTING_THE_LEADERBOARD_READY ->  "லீடர்போர்டை உருவாக்குகிறது!"
        PLEASE_WAIT_WHILE_WE_UPDATE_THE_DETAILS ->  "நாங்கள் விவரங்களைப் புதுப்பிக்கும் வரை காத்திருக்கவும்"
        LAST_UPDATED ->  "கடைசியாக புதுப்பிக்கப்பட்டது: "
        CONGRATULATIONS_YOU_ARE_RANK ->  "வாழ்த்துகள் ! உங்கள் ரேங்க் "
        YOU ->  " (நீங்கள்)"
        DAILY ->  "தினசரி"
        WEEKLY ->  "வாரந்தோறும்"
        ACCEPT_RIDES_TO_ENTER_RANKINGS ->  "தரவரிசையில் நுழைய சவாரிகளை ஏற்கவும்!"
        OTP_HAS_BEEN_RESENT ->  "OTP மீண்டும் அனுப்பப்பட்டது"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_RESENDING_OTP ->  "OTP ஐ உள்ளிடுவதற்கான வரம்பை அடைந்து விட்டது, மீண்டும் OTP ஐ அனுப்ப முயற்சிக்கவும்"
        OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER ->  "OTP மறுபரிசீலனை வரம்பை அடைந்து விட்டது, பிறகு முயற்சிக்கவும்"
        OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN ->  "OTP பக்கம் காலாவதியானது, OTP ஐ மீண்டும் கோரவும்"
        SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN ->  "சில தொழில்நுட்ப சிக்கல் ஏற்பட்டுள்ளது, மீண்டும் முயற்சிக்கவும்"
        INVALID_REFERRAL_CODE ->  "தவறான பரிந்துரை குறியீடு"
        ISSUE_REMOVED_SUCCESSFULLY ->  "சிக்கல் வெற்றிகரமாக தீர்க்கப்பட்டது"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER ->  "OTP உள்ளீட்டு வரம்பை அடைந்து விட்டது, பிறகு முயற்சிக்கவும்"
        TOO_MANY_ATTEMPTS_PLEASE_TRY_AGAIN_LATER ->  "நீங்கள் பல தவறான முயற்சிகளைச் செய்துள்ளீர்கள், பிறகு முயற்சிக்கவும்"
        INVALID_REFERRAL_NUMBER ->  "தவறான பரிந்துரை எண்"
        SOMETHING_WENT_WRONG_TRY_AGAIN_LATER ->  "சில தொழில்நுட்பச் சிக்கல் ஏற்பட்டுள்ளது, பிறகு முயற்சிக்கவும்"
        WAIT_TIME ->  "காத்திருக்கும் நேரம்"
        WAIT_TIMER ->  "காத்திரு டைமர்"
        HOW_LONG_WAITED_FOR_PICKUP ->  "பிக்அப்பில்\nஎவ்வளவு நேரம் காத்திருந்தீர்கள் என்பதைக் காட்டுகிறது."
        CUSTOMER_WILL_PAY_FOR_EVERY_MINUTE ->  "முதல் {} நிமிடங்களுக்குப் பிறகு ஒவ்வொரு நிமிட காத்திருப்பு நேரத்திற்கும் வாடிக்கையாளர் ₹1.5 செலுத்துவார்."
        OTHERS ->  "மற்றவைகள்"
        ENTER_SECOND_SIM_NUMBER ->  "இரண்டாவது சிம் எண்ணை உள்ளிடவும்"
        ALTERNATE_NUMBER ->  "மாற்று எண்"
        OTP_RESEND_LIMIT_EXCEEDED ->  "மீண்டும் OTP அனுப்புவதற்கான வரம்பு மீறப்பட்டது"
        LIMIT_EXCEEDED_FOR_ALTERNATE_NUMBER ->  "பல தவறான முயற்சிகள். பின்னர் மீண்டும் முயற்சிக்கவும்"
        ALTERNATE_NUMBER_CANNOT_BE_ADDED ->  "மற்றொரு எண்ணைச் சேர்க்க முடியாது"
        SELECT_THE_LANGUAGES_YOU_CAN_SPEAK ->  "நீங்கள் பேசக்கூடிய மொழிகளைத் தேர்ந்தெடுக்கவும்"
        OTP_RESENT ->  "OTP மீண்டும் அனுப்பவும்"
        SEDAN ->  "செடான்"
        SUV ->  "SUV"
        HATCHBACK ->  "ஹேட்ச்பேக்"
        AUTO_RICKSHAW ->  "ஆட்டோ ரிக்ஷா"
        TAXI ->  "ஏசி அல்லாத டாக்ஸி"
        TAXI_PLUS ->  "ஏசி டாக்ஸி"
        MY_PROFILE ->  "எனது சுயவிவரம்"
        SETTINGS ->  "அமைப்புகள்"
        REG_NUMBER ->  "பதிவு எண்"
        TYPE ->  "வகை"
        MODEL_NAME ->  "மாடல் பெயர்"
        COLOUR ->  "நிறம்"
        BADGES -> "பேட்ஜ்கள்"
        CALL_CUSTOMER_SUPPORT ->  "வாடிக்கையாளர் ஆதரவை அழைக்கவும்"
        EDIT_RC ->  "RC ஐ திருத்து"
        DELETE_RC ->  "RC ஐ நீக்கு"
        DEACTIVATE_RC ->  "RC ஐ செயலிழக்கச் செய்யவும்"
        ACTIVATE_RC ->  "RC ஐ செயல்படுத்தவும்"
        ACTIVE_RC_ON_ANOTHER_DRIVER ->  " மற்றொரு இயக்கி கணக்கில் செயலில் உள்ளது!"
        CALL_DRIVER_OR_CONTACT_SUPPORT ->  "RC ஐ செயலிழக்க டிரைவரை அழைக்கவும் அல்லது இயக்கியை அணுக முடியவில்லை என்றால் ஆதரவைத் தொடர்பு கொள்ளவும்"
        CALL_DRIVER ->  "டிரைவரை அழைக்கவும்"
        SKIP ->  "தவிர்க்கவும்"
        ACTIVE_STR ->  "செயலில்"
        INACTIVE_RC ->  "செயலற்றது"
        CONFIRMATION_FOR_DELETING_RC ->  "உங்கள் RC ஐ நிச்சயமாக நீக்க விரும்புகிறீர்களா"
        CONFIRMATION_FOR_DEACTIVATING_RC ->  "உங்கள் RC ஐ செயலிழக்கச் செய்ய விரும்புகிறீர்களா?- "
        CONFIRMATION_FOR_ACTIVATING_RC ->  "RC ஐச் செயல்படுத்த விரும்புகிறீர்களா?- "
        YES_DELETE ->  "ஆம், நீக்கு"
        ADD_NEW_RC ->  "RC ஐச் சேர்க்கவும்"
        CONNECT_CALL_ANONYMOUSLY -> "டிரைவருடன் அநாமதேயமாக உங்களை இணைக்க முயற்சிப்போம், RC ஐ செயலிழக்கக் கோரும் முன் உங்களை அறிமுகப்படுத்திக் கொள்ளவும்."
        YES_ACTIVATE ->  "ஆம், செயல்படுத்து"
        YES_DEACTIVATE ->  "ஆம், செயலிழக்கச் செய்"
        THIS_WILL_DEACTIVATE_CURRENTLY_ACTIVE_RC ->  "இது தற்போது செயலில் உள்ள உங்கள் RC ஐ செயலிழக்கச் செய்யும்."
        REMOVED ->  "அகற்றப்பட்டது"
        IS_ACTIVE_NOW ->  " இப்போது செயலில் உள்ளது."
        DEACTIVATED ->  "செயலிழக்கப்பட்டது"
        LANGUAGE_UPDATED ->  "भाषा अद्यतन"
        SINGLE_RC_CANNOT_BE_DELETED ->  "மொழி புதுப்பிக்கப்பட்டது"
        CANCELLATION_RATE ->  "ரத்து விகிதம்"
        RIDES_CANCELLED ->  "ரரத்து செய்யப்பட்ட சவாரிகள்"
        EARNINGS_MISSED ->  "தவறவிட்ட வருவாய்"
        SUMMARY ->  "சுருக்கம்"
        NAMMA_BONUS ->  "நம்ம போனஸ்"
        TRIPS_COMPLETED ->  "முடிந்த பயணங்கள்"
        LATE_NIGHT_TRIPS -> "தாமதமான இரவு பயணங்கள்"
        ABOUT_ME ->  "என்னைப் பற்றி"
        ABOUT_VEHICLE ->  "வாகனம் பற்றி"
        ADD ->  "சேர்"
        YEARS_OLD ->  "வயது"
        HOMETOWN ->  "சொந்த ஊர்"
        MISSED_OPPORTUNITY ->  "தவறவிட்ட வாய்ப்புகள்"
        HOW_OLD_IS_YOUR_VEHICLE ->  "உங்கள் வாகனம் (ஆண்டுகளில்) எவ்வளவு பழையது?"
        ENTER_NAME_OF_VEHICLE ->  "உங்கள் வாகனத்தின் பெயரை உள்ளிடவும்"
        NEW_ ->  "புதியது"
        TODAY ->  "இன்று"
        ENTER_AADHAAR_NUMBER ->  "ஆதார் எண்/யுஐடியை உள்ளிடவும்"
        ENTER_AADHAAR_OTP_ ->  "ஆதார் OTP ஐ உள்ளிடவும்"
        AADHAAR_LINKING_REQUIRED ->  "ஆதார் இணைப்பு தேவை"
        AADHAAR_LINKING_REQUIRED_DESCRIPTION _ ->  "யாத்ரி சதிக்கு வாகனம் ஓட்டத் தொடங்க, தயவுசெய்து \n உங்கள் ஆதார் ஐடியை இணைக்கவும்"
        BY_CLICKING_THIS_YOU_WILL_BE_AGREEING_TO_OUR_TC ->  "தொடரவும் என்பதைக் கிளிக் செய்வதன் மூலம், எங்களின் "
        TERMS_AND_CONDITIONS_SHORT ->  "T&C"
        TC_TAIL ->  "ஐ ஏற்கிறீர்கள்"
        OTP_SENT_TO_AADHAAR_NUMBER -> "OTP உங்கள் ஆதாருடன் இணைக்கப்பட்ட மொபைல் எண்ணுக்கு அனுப்பப்பட்டது"
        ENTER_SIX_DIGIT_OTP ->  "ஆறு இலக்க OTP ஐ உள்ளிடவும்"
        LINK_AADHAAR_ID ->  "ஆதார் ஐடியை இணைக்கவும்"
        NO_MOBILE_NUMBER_REGISTERED ->  "ஆதார் எண்ணில் பதிவு செய்யப்பட்ட மொபைல் எண் இல்லை."
        EXCEED_OTP_GENERATION_LIMIT ->  "அதிகபட்ச OTP உருவாக்க வரம்பை மீறியது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்."
        AADHAAR_NUMBER_NOT_EXIST ->  "ஆதார் எண் இல்லை."
        INVALID_OTP ->  "தவறான OTP"
        NO_SHARE_CODE ->  "பங்கு குறியீடு வழங்கப்படவில்லை"
        WRONG_SHARE_CODE ->  "தவறான பகிர்வு குறியீடு"
        INVALID_SHARE_CODE ->  "தவறான பகிர்வு குறியீடு. நீளம் 4 ஆக இருக்க வேண்டும் மற்றும் எண்களை மட்டுமே கொண்டிருக்க வேண்டும்."
        SESSION_EXPIRED ->  "அமர்வு காலாவதியானது. செயல்முறையை மீண்டும் தொடங்கவும்."
        OTP_ATTEMPT_EXCEEDED ->  "OTP முயற்சிகள் மீறப்பட்டுள்ளன. செயல்முறையை மீண்டும் தொடங்கவும்"
        UPSTREAM_INTERNAL_SERVER_ERROR ->  "அப்ஸ்ட்ரீம் மூல/அரசு மூல உள் சேவையகப் பிழை. செயல்முறையை மீண்டும் தொடங்கவும்."
        TRANSACTION_ALREADY_COMPLETED ->  "பரிவர்த்தனை ஏற்கனவே முடிந்தது. இந்த பரிவர்த்தனையின் மீது மேற்கொண்டு செயல்பட முடியாது."
        AADHAAR_ALREADY_LINKED ->  "ஆதார் ஏற்கனவே இணைக்கப்பட்டுள்ளது"
        OPTIONAL ->  " (விருப்பமானது)"
        DOWNLOAD_STATEMENT ->  "அறிக்கையைப் பதிவிறக்கு"
        SELECT_A_DATE_RANGE ->  "அறிக்கையைப் பதிவிறக்க தேதி வரம்பைத் தேர்ந்தெடுக்கவும்"
        FEE_PAYMENT_HISTORY ->  "கட்டணம் செலுத்திய வரலாறு"
        LANGUAGES_SPOKEN ->  "பேசும் மொழிகள்"
        VIEW_PAYMENT_HISTORY ->  "கட்டண வரலாற்றைக் காண்க"
        RIDE_TYPE ->  "சவாரி வகை"
        RC_STATUS ->  "RC நிலை"
        BOOKING_OPTIONS ->  "முன்பதிவு விருப்பங்கள்"
        RATED_BY_USERS1 ->  ""
        RATED_BY_USERS2 ->  "பயனர்கள் மூலம் மதிப்பிடப்பட்டது"
        MONTHS ->  "மாதங்கள்"
        ENTER_AADHAAR_DETAILS ->  "ஆதார் விவரங்களை உள்ளிடவும்"
        CALL_REQUEST_HAS_BEEN_PLACED ->  "உங்கள் அழைப்பு கோரிக்கை வைக்கப்பட்டுள்ளது"
        RC_ADDED_SUCCESSFULLY ->  "பதிவுச் சான்றிதழ் வெற்றிகரமாக சேர்க்கப்பட்டது"
        PLACE_CALL_REQUEST ->  "அழைப்பு கோரிக்கை கொடுக்க"
        OFFER_APPLIED ->  "சலுகை பயன்படுத்தப்பட்டது"
        YOUR_EARNINGS ->  "உங்கள் வருவாய்"
        NUMBER_OF_RIDES ->  "சவாரிகளின் எண்ணிக்கை"
        FARE_BREAKUP ->  "கட்டண முறிவு"
        MY_PLAN ->  "என் திட்டம்"
        YOUR_DUES ->  "உங்கள் பாக்கிகள்"
        YOUR_DUES_DESCRIPTION ->  "உங்கள் பாக்கிகளை செலுத்த, ஆட்டோ டெபிட் முறையை அமைக்கவேண்டும்‌. உங்கள் பாக்கிகளை தானாக சரியான நேரத்தில் ஆட்டோ டெபிட் மூலமாக செலுத்தப்படுவதை உறுதிசெய்வோம்‌ ."
        CURRENT_DUES ->  "தற்போதைய பாக்கிகள்"
        YOUR_LIMIT ->  "உங்கள் வரம்பு"
        DUE_DETAILS ->  "பாக்கிகளின் விவரங்கள்"
        TRIP_DATE ->  "பயண தேதி"
        AMOUNT ->  "தொகை"
        VIEW_DUE_DETAILS ->  "<u>பாக்கிகளின் விவரங்களைக் காண்க</u>"
        SETUP_AUTOPAY ->  "ஆட்டோ டெபிட் அமைக்க"
        CURRENT_PLAN ->  "தற்போதைய திட்டம்"
        ALTERNATE_PLAN ->  "மாற்றுத் திட்டம்"
        AUTOPAY_DETAILS ->  "ஆட்டோ டெபிட் விவரங்கள்"
        CANCEL_AUTOPAY_STR ->  "<u>ஆட்டோ டெபிட் ரத்துசெய்ய</u>"
        WE_MIGHT_BE_LOST ->  "தொடர்பு துண்டிக்கப்பட்டது"
        EXEPERIENCING_ERROR ->  "பிழையை அனுபவிக்கிறது <Error Code> "
        ENJOY_THESE_BENEFITS ->  "நன்மைகள்‌"
        CHOOSE_YOUR_PLAN _ ->  "திட்டம் தேர்ந்தெடுவீர்‌!"
        SKIP_FOR_NOW ->  "இப்போதைக்கு தவிர்க்கவும்"
        SEVEN_DAY_FREE_TRIAL_ACTIVATED ->  "7 நாள் இலவச சோதனை செயல்படுத்தப்பட்டது!"
        TAKE_UNLIMITED_RIDES_FOR_THE_NEXT_SEVEN_DAYS ->  "முதல் 7 நாட்களுக்கு வரம்பற்ற சவாரி செய்யுங்கள்"
        EVERY_RIDE_AT_ZERO_COMMISSION ->  "ZERO கமிஷனில் ஒவ்வொரு சவாரியும்!"
        EARN_UPTO_PER_DAY ->  "ஒரு நாளைக்கு ₹2500 வரை சம்பாதிக்கவும்!"
        HOW_THIS_WORKS ->  "இது எப்படி வேலை செய்கிறது"
        SIGN_UP_FOR_AUTOPAY_BY_PAYING_JUST ->  "வெறும் ₹1 செலுத்தி தன்னியக்கச் செலுத்துதலுக்குப் பதிவு செய்யவும்"
        GET_REMINDED_ABOUT_YOUR_PLAN_SETUP ->  "உங்கள் திட்ட அமைப்பைப் பற்றி நினைவூட்டுங்கள்"
        FREE_TRIAL_REMINDER ->  "நாள் 5: இலவச சோதனை நினைவூட்டல்"
        PLAN_STARTS ->  "நாள் 7: திட்டம் தொடங்குகிறது"
        EASY_AUTOMATIC_PAYMENTS_START ->  "எளிதான, தானாக பணம் செலுத்துதல் தொடங்கும்"
        FREE_UNTIL ->  " வரை இலவசம்"
        PER_RIDE ->  "ஒரு சவாரிக்கு"
        PER_DAY ->  "ஒரு நாளைக்கு"
        OFFER ->  "சலுகை"
        OFFERS ->  "சலுகைகள்"
        YOU_ARE_ON_THE_FREE_TRIAL ->  "நீங்கள் இலவச சோதனையில் இருக்கிறீர்கள்"
        SETUP_AUTOPAY_BEFORE_THE_TRAIL_PERIOD_EXPIRES ->  "சோதனைக் காலம் காலாவதியாகும் முன் தானாகப் பணம் செலுத்துதலை அமைக்கவும்"
        PAY_TO_JOIN_THIS_PLAN ->  "திட்டத்தில் சேர ₹1 செலுத்தவும்"
        GET_FREE_TRAIL_UNTIL ->  "வரை இலவசம்‌"
        CLEAR_DUES ->  "பாக்கிகளை செலுத்தவும்‌"
        PAYMENT_PENDING_ALERT ->  "⚠️கட்டணம் நிலுவையில் உள்ளது!⚠️"
        PAYMENT_PENDING_ALERT_DESC ->  "நம்ம யாத்ரியில் தொடர்ந்து சவாரி செய்ய, உங்கள் கட்டண பாக்கிகளை செலுத்தவும்‌"
        LOW_ACCOUNT_BALANCE ->  "வங்கி தொகை குறைவாக உள்ளது"
        LOW_ACCOUNT_BALANCE_DESC ->  "வங்கி கணக்கில் தொகை குறைவாக உள்ளது. தடையின்றி சவாரி செய்து மகிழ பணத்தைச் செலுத்தவும்‌."
        OKAY_GOT_IT ->  "சரி, புரிந்தது"
        LIMITED_TIME_OFFER ->  "குறுகிய கால சலுகை!"
        JOIN_NOW ->  "இப்பொழுதே  சேரவும்"
        AUTOMATIC_PAYMENTS_WILL_APPEAR_HERE ->  "ஆட்டோ டெபிட் இங்கே தோன்றும்"
        MANUAL_PAYMENTS ->  "நேரடியாக பணம் செலுத்துதல்"
        MANUAL_PAYMENTS_WILL_APPEAR_HERE ->  "நேரடியாக பணம் செலுத்துவது இங்கே தோன்றும்"
        NO_AUTOMATIC_PAYMENTS_DESC ->  "உங்களின் ஆட்டோ டெபிட்  பரிவர்த்தனை விவரங்கள் வசூலிக்கப்பட்டவுடன் இங்கே தோன்றும்"
        NO_MANUAL_PAYMENTS_DESC ->  "பாக்கிகளை செலுத்த உங்கள் பரிவர்த்தனை விவரங்கள் ஏதேனும் இருந்தால் இங்கே தோன்றும்."
        PAYMENT_HISTORY ->  "கட்டண வரலாறு"
        TAP_A_PLAN_TO_VIEW_DETAILS ->  "விவரங்களைப் பார்க்க ஒரு திட்டத்தைத் அழுத்தவும்"
        HOW_IT_WORKS ->  "இது எப்படி வேலை செய்கிறது"
        ZERO_COMMISION ->  "ஜீரோ கமிஷன்"
        EARN_TODAY_PAY_TOMORROW ->  "இன்று சம்பாதிக்கவும், நாளை செலுத்தவும்"
        PAY_ONLY_IF_YOU_TAKE_RIDES ->  "நீங்கள் சவாரி செய்தால் மட்டும் பணம் செலுத்துங்கள்"
        PLANS ->  "திட்டம்"
        PLAN ->  "திட்டம்"
        DAY ->  "நாள்"
        MANAGE_PLAN ->  "திட்டத்தை நிர்வகிக்க"
        VIEW_AUTOPAY_DETAILS ->  "<u>ஆட்டோ டெபிட் விவரங்களைக் காண்க</u>"
        SWITCH_AND_SAVE ->  "திட்டம் மாறி சேமிக்கவும்"
        SWITCH_AND_SAVE_DESC ->  "இன்று 7 சவாரிகளுக்கு மேல் முடித்துவிட்டீர்கள். டெய்லி அன்லிமிட்டட்‌ திட்டத்திற்கு மாறுவதன் மூலம் ₹10 வரை சேமிக்கலாம்‌"
        SWITCH_NOW ->  "இப்போதே மாறு"
        PAYMENT_MODE_CHANGED_TO_MANUAL ->  "கட்டண முறை நேரடியாக பணம் செலுத்தும் முறைக்கு மாற்றப்பட்டது"
        PAYMENT_MODE_CHANGED_TO_MANUAL_DESC ->  "உங்கள் UPI ஆட்டோ டெபிட் இடைநிறுத்திவிட்டீர்கள். உங்கள் பாக்கிகளை நேரடியாக பணம் செலுத்தலாம்."
        AUTOPAY_PAYMENTS ->  "ஆட்டோ டெபிட் விவரங்கள்‌"
        TRANSACTION_ON ->  "பரிவர்த்தனை  தேதி"
        SUCCESS ->  "வெற்றி"
        RIDES_TAKEN_ON ->  "சவாரி தேதி"
        JOIN_PLAN ->  "திட்டத்தில் சேரவும்"
        JOIN_NAMMAA_YATRI ->  "நம்ம யாத்ரியில் சேரவும்"
        CANCEL_AUTOPAY_AND_PAY_MANUALLY ->  "ஆட்டோ டெபிட் ரத்துசெய்து நேரடியாக பணம் செலுத்த"
        PLAN_ACTIVATED_SUCCESSFULLY ->  "திட்டம் வெற்றிகரமாக செயல்படுத்தப்பட்டது"
        DUES_CLEARED_SUCCESSFULLY ->  "பாக்கிகள் வெற்றிகரமாக பெறப்பட்டது"
        NOT_PLANNING_TO_TAKE_RIDES ->  "சவாரி எடுக்கத் திட்டமிடவில்லையா?"
        RETRY_PAYMENT_STR ->  "மீண்டும் முயற்சிக்கவும்"
        PAUSE_AUTOPAY_STR ->  "ஆட்டோ டெபிட் இடைநிறுத்து"
        SETUP_AUTOPAY_STR ->  "தானாக செலுத்துவதை மீண்டும் தொடங்கு"
        VIEW_RIDE_DETAILS ->  "சவாரி விவரங்களைக் காண்க"
        ACCOUNT ->  "கணக்கு"
        AUTOPAY_IS_NOT_ENABLED_YET ->  "ஆட்டோ டெபிட் இன்னும் செயல்படவில்லை!"
        ENABLE_AUTOPAY_DESC ->  "தொந்தரவு இல்லாமல்‌ கட்டணங்களைத் செலுத்த  ஆட்டோ டெபிட்  முறையை இப்போதே இயக்குங்கள்‌!"
        ENABLE_AUTOPAY_NOW ->  "இப்போது ஆட்டோ டெபிட் செயல்படுத்த"
        AUTOPAY_SETUP_PENDING_STR ->  "தானாகச் செலுத்தும் அமைவு நிலுவையில் உள்ளது!"
        AUTOPAY_PENDING_DESC_STR ->  "காத்திருங்கள் அல்லது பணம் செலுத்த மீண்டும் முயற்சிக்கவும். கூடுதல் கட்டணம் திருப்பித் தரப்படும்."
        REFRESH_STR ->  "புதுப்பிக்க"
        TRANSACTION_DETAILS ->  "பரிவர்த்தனை விவரங்கள்"
        RIDE_DETAILS ->  "சவாரி விவரங்கள்"
        MY_PLAN_TITLE _ ->  "நம்ம யாத்ரி திட்டங்கள்"
        SWITCH_TO ->  "{} திட்டம் மாறவும்"
        PLEASE_TRY_AGAIN ->  "தயவுசெய்து மீண்டும் முயற்சிக்கவும்"
        PLAN_NOT_FOUND ->  "திட்டம் கிடைக்கவில்லை"
        MANDATE_NOT_FOUND ->  "ஆணை கிடைக்கவில்லை"
        ACTIVE_MANDATE_EXISTS ->  "செயலில் உள்ள ஆணை ஏற்கனவே உள்ளது"
        NO_ACTIVE_MANDATE_EXIST ->  "செயலில் உள்ள ஆணை எதுவும் இல்லை"
        NO_PLAN_FOR_DRIVER ->  "திட்டம் எதுவும் கிடைக்கவில்லை"
        INVALID_PAYMENT_MODE ->  "தவறான கட்டண முறை"
        INVALID_AUTO_PAY_STATUS ->  "தவறான தானாகச் செலுத்தும் நிலை"
        MAX_AMOUNT ->  "அதிகபட்ச தொகை"
        FREQUENCY ->  "அதிர்வெண்"
        STATRED_ON ->  "தொடங்கியது"
        EXPIRES_ON ->  "காலாவதியாகும் தேதி"
        SWITCHED_PLAN ->  "மாற்றப்பட்ட திட்டம்"
        ONETIME ->  "ஒரு முறை"
        FORTNIGHTLY ->  "இரண்டு வாரத்திற்கு ஒருமுறை"
        MONTHLY ->  "மாதாந்திர"
        BIMONTHLY ->  "இருமாதம்"
        QUARTERLY ->  "காலாண்டு"
        HALFYEARLY ->  "அரையாண்டு"
        YEARLY ->  "ஆண்டு"
        ASPRESENTED ->  "எப்போது வழங்கினாலும்"
        DAILY_PER_RIDE_DESC ->  "செப்டம்பர் 19 வரை கட்டணம் இல்லை"
        FIRST_FREE_RIDE ->  "முதல் சவாரி இலவசம்"
        JOIN_THE_UNLIMITED_PLAN ->  "சிறப்பு தள்ளுபடியைப் பெற இப்போது டெய்லி அன்லிமிட்டட்‌ திட்டத்தில் சேரவும்"
        MAYBE_LATER ->  "ஒருவேளை பின்னர்"
        YOUR_DUES_DESCRIPTION_MANUAL ->  "தடையின்றி சவாரிகளை தொடர வரம்பை அடையும் முன் உங்கள் நிலுவைத் தொகையைச் செலுத்தவும். எளிதாக, தொந்தரவு இல்லாத கட்டணங்களுக்கு, <b>UPI ஆட்டோபேவை அமைக்கவும்</b>."
        DO_YOU_WANT_TO_CANCEL ->  "நீங்கள் ரத்து செய்ய விரும்புகிறீர்களா?"
        DO_YOU_WANT_TO_CANCEL_DESC ->  "தானாகப் பணம் செலுத்துவதை ரத்து செய்ய உள்ளீர்கள்.\nதானாகப் பணம் செலுத்துவதைத் தொடங்க, தானாகப் பணம் செலுத்துவதை மீண்டும் அமைக்க வேண்டும்."
        YOUR_PAYMENT_WAS_UNSUCCESSFUL ->  "உங்கள் பணம் செலுத்தும் முயற்சி தோல்வியடைந்தது."
        PAYMENT_CANCELLED ->  "உங்களின் UPI தானியங்கு கட்டணத்தை ரத்து செய்துவிட்டீர்கள். உங்கள் நிலுவைத் தொகையை கைமுறையாகச் செலுத்தலாம்"
        UPI_AUTOPAY_S ->  "UPI ஆட்டோ டெபிட்"
        MANUAL_PAYMENT_STR ->  "நேரடியாக பணம் செலுத்துதல்"
        DAILY_UNLIMITED ->  "டெய்லி அன்லிமிட்டட்‌"
        DAILY_PER_RIDE ->  "டெய்லி பர்‌ ரைட்‌"
        DAILY_UNLIMITED_PLAN_DESC ->  "தினமும் அன்லிமிட்டட்‌ சவாரிகள்"
        DAILY_PER_RIDE_PLAN_DESC ->  "ஒரு நாளைக்கு அதிகபட்சம் ₹35 வரை"
        AUTOPAY_CANCELLED ->  "தானியங்கு கட்டணம் ரத்து செய்யப்பட்டது"
        NO ->  "இல்லை"
        YES_CANCEL ->  "ஆம், ரத்துசெய்"
        OFFERS_NOT_APPLICABLE ->  "பூர்த்தி செய்யாத வரை சலுகைகள் பொருந்தாது"
        PAUSED_STR ->  "இடைநிறுத்தப்பட்டது"
        PENDING_STR ->  "நிலுவையில் உள்ளது"
        PLAN_SWITCHED_TO ->  "திட்டம் மாறியது"
        SWITCH_PLAN_STR ->  "ஸ்விட்ச் பிளான்?"
        OFFERS_APPLICABLE_ON_DAILY_UNLIMITED ->  "குறிப்பு: தினசரி வரம்பற்ற திட்டத்தில் மட்டுமே பொருந்தும்"
        DAILY_UNLIMITED_OFFER_NOT_AVAILABLE ->  "குறிப்பு: இந்த திட்டத்தில் தினசரி வரம்பற்ற சலுகைகள் பொருந்தாது!" 
        NO_RIDES_NO_CHARGE ->  " நீங்கள் சவாரி செய்தால் மட்டுமே பணம் செலுத்துங்கள்"
        GET_SPECIAL_OFFERS ->  "சிறப்பு சலுகைகளைப் பெறுங்கள்"
        VALID_ONLY_IF_PAYMENT ->  "பணம் செலுத்தினால் மட்டுமே செல்லுபடியாகும்"
        HELP_STR ->  "உதவி"
        REFRESH_STRING ->  "புதுப்பிப்பு"
        CHAT_FOR_HELP ->  "மெசேஜ்"
        VIEW_FAQs ->  "கேள்விகள்?"
        FIND_HELP_CENTRE ->  "உதவி மையத்தைக் கண்டறியவும்"
        CONTACT ->  "தொடர்பு"
        GO_TO_LOCATION ->  "இங்கே செல்"
        NO_HELP_CENTER_IS_ACTIVE_NOW ->  "தற்போது எந்த உதவி மையமும் செயல்படவில்லை"
        HELP_CENTERS_LOCATION_WILL_APPEAR_HERE_ONCE_THEY_ARE_ACTIVE ->  "உதவி மையங்கள் செயல்பட்டவுடன் அவற்றின் இருப்பிடங்கள் இங்கே தோன்றும்"
        SUPPORT ->  "ஆதரவு"
        NEED_HELP_JOINING_THE_PLAN ->  "திட்டம் அல்லது ஆட்டோ பே இல் சேர உதவி தேவையா?"
        NEED_HELP ->  "திட்டத்தில் சேர உதவி வேண்டுமா?"
        SETUP_AUTOPAY_NOW_TO_GET_SPECIAL_DISCOUNTS -> "சிறப்பு தள்ளுபடியைப் பெற இப்போதே ஆட்டோ பேயை அமைக்கவும்"
        SETUP_NOW ->  "இப்போதே அமைக்கவும்"
        GO_TO_VEHICLE_DETAILS ->  "வாகன விவரங்களுக்குச் செல்லவும்"
        CLOSE -> "மூடு"
        RC_DEACTIVATED ->  "RC செயலிழக்கப்பட்டது"
        RC_DEACTIVATED_DETAILS ->  "உங்கள் RC தற்போது மற்றொரு டிரைவரின் கணக்கில் செயலில் உள்ளது. ரைடுகளைத் தொடங்க RC ஐச் செயல்படுத்தவும்"
        CUSTOMER_HAS_LOW_MOBILITY -> "வாடிக்கையாளருக்கு நகரும் குறைபாடு உள்ளது"
        CUSTOMER_HAS_DISABILITY -> "வாடிக்கையாளருக்கு குறைபாடு உள்ளது"
        CUSTOMER_HAS_LOW_VISION -> "வாடிக்கையாளருக்கு குறைந்த பார்வை உள்ளது"
        CUSTOMER_HAS_HEARING_IMPAIRMENT -> "வாடிக்கையாளருக்கு இயக்கம் குறைவாக உள்ளது"
        HELP_WITH_THEIR_MOBILITY_AID -> "அவர்களின் நடை உபகரணங்களுக்கு உதவுங்கள்"
        PLEASE_ASSIST_THEM_IF_NEEDED -> "தேவைப்பட்டால் அவர்களுக்கு உதவவும்"
        MESSAGE_THEM_AT_PICKUP -> "நீங்கள் பிக்கப்பை அடைந்தவுடன் அவர்களுக்கு செய்தி அனுப்பவும்"
        SOUND_HORN_ONCE_AT_PICKUP -> "பிக்அப்பை அடைந்த பிறகு ஒருமுறை ஹார்ன் அடிக்கவும்"
        PLEASE_CALL_AND_AVOID_CHATS -> "தயவு செய்து செய்திகளை தவிர்க்கவும் மற்றும் தொலைபேசி மூலம் அழைக்கவும்"
        PLEASE_CHAT_AND_AVOID_CALLS -> "தயவுசெய்து செய்தி அனுப்பவும் மற்றும் தொலைபேசி அழைப்புகளைத் தவிர்க்கவும்"
        PLEASE_GO_TO_EXACT_PICKUP -> "சரியான பிக்-அப்பிற்கு செல்லவும்"
        CUSTOMER_HAS_POOR_VISION_SOUND_HORN_AT_PICKUP ->  "வாடிக்கையாளருக்கு பார்வை குறைவாக உள்ளது. பிக்அப் செய்யும் போது ஒருமுறை ஹார்ன் அடிக்கவும்."
        CUSTOMER_HAS_POOR_HEARING_MESSAGE_THEM_AT_PICKUP ->  "சவாரி செய்பவருக்கு செவித்திறன் குறைவாக உள்ளது. பிக்அப்பில் ஒருமுறை அவர்களுக்கு செய்தி அனுப்பவும்."
        CUSTOMER_HAS_LOW_MOBILITY_STORE_THEIR_SUPPORT_AT_PICKUP ->  "வாடிக்கையாளருக்கு குறைந்த நடமாட்டம் உள்ளது. பயணிகள் இருக்கைக்கு பின்னால் தங்கள் உபகரணங்களை சேமிக்க அவர்களுக்கு உதவவும்."
        CUSTOMER_HAS_DISABILITY_PLEASE_ASSIST_THEM ->  "வாடிக்கையாளருக்கு குறைபாடு உள்ளது. உங்களால் முடிந்தவரை அவர்களுக்கு உதவுங்கள்."
        CUSTOMER_MAY_NEED_ASSISTANCE ->  "வாடிக்கையாளருக்கு உதவி தேவைப்படலாம்"
        LEARN_MORE ->  "மேலும் அறிக"
        CUSTOMER_HAS_LOW_MOBILITY_GO_TO_EXACT_LOC ->  "வாடிக்கையாளருக்கு குறைந்த நடமாட்டம் உள்ளது. சரியான பிக் அப் இடத்திற்குச் செல்லவும்."
        CUSTOMER_HAS_POOR_HEARING_CHAT_WITH_THEM_INSTEAD_OF_CALLING ->  "சவாரி செய்பவருக்கு செவித்திறன் குறைவாக உள்ளது. அழைப்பதற்கு பதிலாக அவர்களுக்கு செய்தி அனுப்பவும்."
        CUSTOMER_HAS_LOW_VISION_CALL_THEM_INSTEAD_OF_CHATTING ->  "வாடிக்கையாளருக்கு பார்வை குறைவாக உள்ளது. செய்தி அனுப்புவதற்குப் பதிலாக அவர்களை அழைக்கவும்."
        PLEASE_HELP_THEM_AS_YOU_CAN ->  "தயவுசெய்து உங்களால் முடிந்தவரை அவர்களுக்கு உதவவும்"
        LEARN_HOW_YOU_CAN_HELP_CUSTOMERS_REQUIRING_SPECIAL_ASSISTANCE ->  "சிறப்பு உதவி தேவைப்படும் வாடிக்கையாளர்களுக்கு நீங்கள் எவ்வாறு உதவலாம் என்பதை அறிக"
        ASSISTANCE_REQUIRED ->  "உதவி தேவை"
        SAVED_DUE_TO_ZERO_COMMISSION ->  "ஜீரோ கமிஷனால்\n சேமிக்கப்பட்டது"
        TIP_EARNED_FROM_CUSTOMER ->  "வாடிக்கையாளரிடமிருந்து\nபெறப்பட்ட டிப்"
        COLLECT_VIA_CASE_UPI ->  "பணம்/UPI மூலம் சேகரிக்கவும்"
        FARE_COLLECTED ->   "கட்டணம் வசூலிக்கப்பட்டது"
        RATE_YOUR_RIDE_WITH1 ->  "" 
        RATE_YOUR_RIDE_WITH2 ->  "உங்கள் பயணத்தை மதிப்பிடுங்கள்"
        HELP_US_WITH_YOUR_FEEDBACK ->  "உங்கள் கருத்தை வழங்குவதன் மூலம் எங்களுக்கு உதவுங்கள் (விரும்பினால்)"
        COLLECT_CASH ->  "பணத்தை சேகரிக்கவும்"
        ONLINE_PAYMENT ->  "ஆன்லைன் கட்டணம்"
        RIDE_COMPLETED ->  "சவாரி முடிந்தது"
        SUBMIT_FEEDBACK ->  "கருத்தைச் சமர்ப்பிக்கவும்"
        BADGE_EARNED ->  "பேட்ஜ் பெற்றுள்ளீர்கள்"
        PURPLE_RIDE_CHAMPION ->  "பர்பிள் ரைடு சாம்பியன்"
        PURPLE_RIDE ->  "பர்பிள் சவாரி"
        PROCEED_TO_CHAT ->  "அரட்டையைத் தொடரவும்"
        PLEASE_CONSIDER_CALLING_THEM ->  "அவர்களால் உரையாடலைப் படிக்க முடியாமல் போகலாம். தயவுசெய்து அவர்களை அழைக்கவும்"
        JOIN_A_PLAN_TO_START_EARNING ->  "சம்பாதிப்பதைத் தொடங்க ஒரு திட்டத்தில் சேரவும்!"
        GO_ONLINE_PROMPT_SUBSCRIBE ->  "நீங்கள் தற்போது ஆஃப்லைனில் உள்ளீர்கள்.\nசவாரி செய்வதற்கான திட்டத்தில் சேரவும்"
        GO_ONLINE_PROMPT_PAYMENT_PENDING ->  "நீங்கள் தற்போது ஆஃப்லைனில் உள்ளீர்கள்.\nசவாரி செய்ய உங்கள் திட்ட கட்டணத்தை முடிக்கவும்"
        COMPLETE_PAYMENT_TO_CONTINUE _ ->  "யாத்ரி சாத்தியைத் தொடர்ந்து பயன்படுத்த, உங்கள் கட்டணத்தைச் செலுத்தவும்"
        PENDING_CAPS ->  "நிலுவையில் உள்ளது"
        FAILURE ->  "தோல்வி"
        PAYMENT_MODE ->  "கட்டண முறை"
        TXN_ID ->  "குறிப்பு எண் ஐடி"
        AMOUNT_PAID ->  "செலுத்தப்பட்ட தொகை"
        NOTIFICATION_SCHEDULED ->  "அறிவிப்பு திட்டமிடப்பட்டுள்ளது!"
        MANUAL_DUES ->  "கைமுறை நிலுவைத் தொகை"
        AUTOPAY_IN_PROGRESS ->  "தானாகச் செலுத்துதல் நடந்து கொண்டிருக்கிறது"
        MANUAL_DUE_OVERVIEW ->  "மேனுவல் நிலுவையில் உள்ள கண்ணோட்டம்"
        AUTOPAY_DUE_OVERVIEW ->  "தானாக செலுத்த வேண்டிய நிலுவைத் பார்வை"
        MANUAL_DUE_AS_AUTOPAY_EXECUTION_FAILED ->  "தானாகச் செலுத்த வேண்டிய செயல் தோல்வியடைந்ததால் கைமுறையாக"
        CLEAR_MANUAL_DUES ->  "கைமுறையான நிலுவைத் தொகைகளை அழிக்கவும்"
        DUE_OVERVIEW ->  "கடைசியான மேலோட்டம்"
        MANUAL_DUE_DETAILS ->  "கைமுறையாக நிலுவைத் தொகை விவரங்கள்"
        AUTOPAY_DUE_DETAILS ->  "தானாக செலுத்த வேண்டிய விவரங்கள்"
        SWITCHED_TO_MANUAL ->  "*தானாகச் செலுத்த முடியாததால் பணம் செலுத்தும் முறை கைமுறைக்கு மாறியது"
        SPLIT_PAYMENT ->  "*தானாகச் செலுத்துவதற்கு கட்டணம் பிரிக்கப்பட்டது"
        GST_INCLUDE ->  "(18% GST உட்பட)"
        SCHEDULED_AT ->  "திட்டமிடப்பட்டது"
        PAYMENT_STATUS ->  "கட்டண நிலை"
        NOTIFICATION_ATTEMPTING ->  "அறிவிப்பு முயற்சி"
        EXECUTION_SCHEDULED ->  "செயல்படுத்தல் திட்டமிடப்பட்டது"
        EXECUTION_ATTEMPTING ->  "செயல்படுத்தும் முயற்சி"
        EXECUTION_SUCCESS ->  "செயல்படுத்துதல் வெற்றி"
        SCHEDULED ->  "திட்டமிடப்பட்டது"
        ONE_TIME_SETTLEMENT ->  "ஒருமுறை தீர்வு செய்யுங்கள்"
        PAYMENT_SCHEDULED ->  "கட்டணம் திட்டமிடப்பட்டுள்ளது"
        VIEW_DETAILS ->  "விவரங்களைக் காண்க"
        RETRY_AUTOPAY ->  "தானாகச் செலுத்த மீண்டும் முயற்சிக்கவும்"
        RETRY_STR ->  " மீண்டும் முயற்சிக்கவும் "
        ONGOING_PAYMENT_EXECUTION ->  "தற்போது கைமுறையாக பணம் செலுத்துகிறது தயவு செய்து காத்திருக்கவும்"
        OFFER_CARD_BANNER_TITLE _ ->  "ஆட்டோப்பே அமைத்து {} வரை ₹15/தினம்‌ சலுகை பெறுங்கள்"
        OFFER_CARD_BANNER_DESC ->  "செப் 25க்குள் ஆட்டோபே அமைக்கப்பட்டால்"
        OFFER_CARD_BANNER_ALERT ->  "உங்கள் ஆக்டோபய அமைப்பு நிலுவையில் உள்ளது!"
        OR ->  "அல்லது"
        COLLECT_CASH_DIRECTLY ->  "நேரடியாக பணத்தை பெறுங்கள்‌"
        OR_COLLECT_CASH_DIRECTLY ->  "அல்லது நேரடியாக பணத்தை சேகரிக்கவும்"
        SETUP_AUTOPAY_TO_ACCEPT_PAYMENT ->  "உங்கள் வங்கிக் பணத்தை நேரடியாக பெற, உங்கள் திட்டத்தில் UPI ஆட்டோப்பே அமைக்கவும்"
        DOWNLOAD_QR ->  "QR ஐப் பதிவிறக்கு"
        USE_THIS_QR_TO_COLLECT_PAYMENT ->  "சவாரி முடிந்ததும் பணத்தை நேரடியாக பெற இந்த QR பயன்படுத்தலாம்."
        AMOUNT_WILL_DEPOSITED_TO_BANK_ACCOUNT ->  "UPI ஆட்டோப்பே அமைத்த வங்கிக்கு பணம்‌ டெபாசிட் செய்யப்படும்"
        GET_DIRECTLY_TO_YOUR_BANK_ACCOUNT ->  "UPI ஐடிக்கு நேரடி கட்டணத்தைப் பெறுங்கள்"
        PAYMENT -> "பணம்‌"
        QR_CODE ->  "QR"
        GET_QR_CODE ->  "QR பெற"
        EXECUTION_FAILED ->  "செயல்படுத்தும் தோல்வியடைந்தது"
        NOTIFICATION_FAILED ->  "அறிவிப்பு தோல்வியடைந்தது"
        PAY_NOW ->  "பணம்‌ செலுத்தவும்‌"
        CLEAR_DUES_BANNER_TITLE ->  "இடைவிடாத சவாரிகளை அனுபவிக்க உங்கள் நிலுவைத் தொகையை (₹{}) செலுத்துங்கள்"
        COLLECT_VIA_UPI_QR_OR_CASH ->  "UPI QR அல்லது பணத்தின் மூலம் சேகரிக்கவும்"
        TRANSACTION_DEBITED_ON ->  "பரிவர்த்தனை டெபிட் ஆன்"
        TRANSACTION_ATTEMPTED_ON ->  "பரிவர்த்தனை முயற்சி"
        AUTOPAY_SETUP_AND_PAYMENT_SUCCESSFUL ->  "தானாக செலுத்தும் அமைவு & பணம் செலுத்துதல் வெற்றிகரமாக!"
        AUTOPAY_SETUP_SUCCESSFUL ->  "தானாக செலுத்தும் அமைவு வெற்றி!"
        AUTOPAY_SETUP_AND_PAYMENT_PENDING ->  "தானாக செலுத்தும் அமைவு & கட்டணம் நிலுவையில் உள்ளது!"
        AUTOPAY_SETUP_PENDING ->  "தானாக செலுத்தும் அமைவு நிலுவையில் உள்ளது!"
        AUTOPAY_SETUP_AND_PAYMENT_FAILED ->  "தானாக செலுத்தும் அமைவு & பணம் செலுத்துவதில் தோல்வி!"
        AUTOPAY_SETUP_FAILED ->  "தானாக செலுத்தும் அமைவு தோல்வி!"
        ONE_TIME_REGISTERATION ->  "ஒரு முறை பதிவு"
        CLEARANCE_AND_REGISTERATION ->  "அனுமதி + பதிவு"
        UPI_AUTOPAY_SETUP ->  "UPI தானாகச் செலுத்தும் அமைப்பு"
        WATCH_VIDEO_FOR_HELP ->  "உதவிக்கு வீடியோவைப் பாருங்கள்"
        PAYMENT_PENDING_SOFT_NUDGE ->  "நிலுவைத் தொகை விரைவில் எட்டப்படும்.இடைவிடாத சவாரிகளை அனுபவிக்க தெளிவான நிலுவைத் தொகை"
        CLEAR_YOUR_DUES_EARLY ->  "உங்கள் கடன்களை விரைவில் செலுத்துக"
        DUE_LIMIT_WARNING_BANNER_TITLE ->  "உங்கள் நிலுவைத் தொகையான ₹{} விரைவில் எட்டப்படும்"
        SCHEDULED_ON ->  "துப்பறியும் தேதி"
        ATTEMPTED_ON ->  "முயற்சி தேதி"
        DEBITED_ON ->  "பற்று தேதி"
        FREE_TRIAL_ENDING_IN_2_DAYS -> "இலவச சோதனை 2 நாட்களில் முடிவடைகிறது"
        FREE_TRIAL_ENDING_TOMORROW ->  "இலவச சோதனை நாளை முடிவடைகிறது"
        FREE_TRIAL_ENDS_TONIGHT ->  "இலவச சோதனை இன்று இரவு முடிவடைகிறது"
        JOIN_A_PLAN_TO_CONTINUE_TAKING_RIDES ->  "தொடர்ந்து சவாரி செய்வதற்கான திட்டத்தில் சேரவும்"
        SETUP_AUTOPAY_FOR_EASY_PAYMENTS ->  "எளிதாகப் பணம் செலுத்துவதற்குத் தானாகப் பணம் செலுத்துதலை அமைக்கவும்"
        LOW_DUES_CLEAR_POPUP_DESC ->  "இடைவிடாத சவாரிகளை அனுபவிக்க இப்போது உங்கள் நிலுவைத் தொகையை அழிக்கவும்"
        DUES_PENDING ->  "⚠️ கட்டணம் நிலுவையில் உள்ளது! ⚠️"
        DAYS ->  "நாட்கள்"
        ACTIVE_PLAN ->  "செயலில் உள்ள திட்டம்"
        PAYMENT_PENDING ->  "கொடுப்பனவு நிலுவை"
        DOWNGRADE_AVAILABLE_ONLY_FOR_AC_VEHICLES ->  "குறைவு வாகன விருப்பம் எஸிக் வாகன்களுக்கு மட்டும் கிடைக்கின்றது"
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_1 ->  "உங்கள் வாகனத்தை தரமிறக்கினால் "
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_2 ->  "சவாரிகள் மற்றும்"
        DOWNGRADING_VEHICLE_WILL_ALLOW_YOU_TO_TAKE_BOTH_3 ->  " சவாரிகள் இரண்டிலும் நீங்கள் செல்லலாம்"
        AC_CAB ->  "ஏசி வண்டி"
        AC_SUV ->  "ஏசி எஸ்யூவி"
        DOWNGRADE_VEHICLE ->  "தரமிறக்கும் வாகனம்"
        WHAT_ARE_PURPLE_RIDES ->  "பர்பிள் சவாரிகள் என்றால் என்ன?"
        ECONOMICAL -> "பொருளாதாரம்"
        SPACIOUS -> "விசாலமான"
        COMFY -> "வசதியான"
        PEOPLE -> "மக்கள்"
        GO_TO ->  "கோ-டூ"
        SELECT_ON_MAP ->  "வரைபடத்தில் தேர்ந்தெடு"
        CONFIRM_LOCATION_STR ->  "இருப்பிடத்தை உறுதிப்படுத்து"
        SAVE_LOCATION_STR ->  "இருப்பிடத்தைச் சேமி"
        REMOVE_PREF_LOC ->  "விருப்பமான இடத்தை அகற்றவா "
        CONF_REMOVE_PREF_LOC ->  "விருப்பமான இடத்தை நிச்சயமாக அகற்ற விரும்புகிறீர்களா?"
        YES_REMOVE ->  "ஆம், அகற்று"
        ADD_LOCATION ->  "இருப்பிடத்தைச் சேர்"
        ADD_ANOTHER_LOCATION ->  "மற்றொரு இடத்தைச் சேர்"
        ADD_A_GOTO_LOC ->  "செல்ல இருப்பிடத்தைச் சேர்"
        GOTO_LOC_LEFT ->  "கோ-டூ இடங்கள் மீதமுள்ளன:"
        CURRENT_LOCATION ->  "தற்போதைய இடம்"
        CONF_GOTO_LOC ->  "இருப்பிடம் செல்வதை உறுதிப்படுத்தவும்"
        GOTO_LOCS ->  "இருப்பிடங்களுக்குச் செல்"
        LOCATION_STR ->  "இடம்"
        ADD_TAG ->  "குறியீடு சேர்க்கவும்"
        ONLY_ONE_LOC_CAN_ADDED ->  "(ஒரு இடத்தில் மட்டுமே இந்தக் குறிச்சொல் இருக்கும்)"
        SAVE_AS ->  "இவ்வாறு சேமி"
        NO_GOTO_LOC_ADDED ->  "இன்னும் செல்ல இடம் சேர்க்கப்படவில்லை"
        GOTO_LOC_HELPS_YOU ->  "கோ-டு இருப்பிடங்கள் உங்களுக்குப் பிடித்த இடங்களிலும் அதைச் சுற்றியும் சவாரிகளைக் கண்டறிய உதவுகின்றன"
        YOU_ARE_VERY_CLOSE -> "நீங்கள் “கோ-டூ” இருப்பிடத்திற்கு மிக அருகில் உள்ளீர்கள்"
        GOTO_IS_APPLICABLE_FOR ->  "“கோ-டூ” என்பது உங்கள் தற்போதைய இருப்பிடத்திலிருந்து குறைந்தபட்சம் 3 கிமீ தொலைவில் உள்ள \n இருப்பிடங்களுக்கு பொருந்தும் \n."
        GOTO_MAYBE_REDUCED ->  "“கோ-டூ” குறைக்கப்படலாம்"
        CANCEL_OF_GOTO ->  "“கோ-டூ” சவாரியை ரத்துசெய்வது உங்கள் “கோ-டூ” விருப்பங்களைக் குறைக்கும்! "
        MORE_GOTO_RIDE_COMING ->  "மேலும் “கோ-டூ” சவாரிகள் வருகின்றன!"
        MORE_GOTO_RIDE_COMING_DESC ->  "தயவுசெய்து ஆன்லைனில் இருங்கள்; உங்கள் “கோ-டூ” இருப்பிடத்திற்கான பயணக் கோரிக்கைகளை நாங்கள் பெறுகிறோம்"
        GOTO_REDUCED_TO_ZERO ->  "“கோ-டூ” பூஜ்ஜியமாகக் குறைக்கப்பட்டது"
        DUE_TO_MULTIPLE_CANCELLATIONS ->  "பல கேன்சல்கள் காரணமாக, எண்ணிக்கை துண்டிக்கப்பட்டது"
        OK_GOT_IT ->  "சரி, புரிந்தது"
        GOTO_REDUCED_TO ->  "“கோ-டூ” குறைக்கப்பட்டது"
        VALIDITY_EXPIRED_DESC ->  "உங்கள் 30 நிமிட செல்லுபடியாகும் காலம் காலாவதியாகிவிட்டது. இந்த நேரத்தில் உங்கள் கோரிக்கையை எங்களால் நிறைவேற்ற முடியவில்லை."
        THIS_FEATURE_WILL_BE_APPLICABLE -> "உங்கள் தற்போதைய இருப்பிடத்திலிருந்து குறைந்தது 3 கிமீ தொலைவில் இருக்கும்போது இந்த அம்சம் பொருந்தும்.\n\nஇருப்பிட விருப்பத்தேர்வுகள் செயல்படுத்தப்படும்போது 30 நிமிடங்களுக்கு மட்டுமே செல்லுபடியாகும்."
        GOTO_LOC_ADDED ->  "இருப்பிடம் வெற்றிகரமாக சேர்க்கப்பட்டது"
        GOTO_LOC_REMOVED ->  "கோ-டூ இருப்பிடம் வெற்றிகரமாக அகற்றப்பட்டது"
        GOTO_LOC_UPDATED ->  "“கோ-டூ” இன் இருப்பிடம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது"
        GOTO_LOC_IS_ENABLED ->  "“கோ-டூ” இருப்பிடம் இயக்கப்பட்டது"
        GOTO_LOC_IS_DISABLED ->  "“கோ-டூ” முடக்கப்பட்டுள்ளது"
        GOTO_LOCATIONS ->  "கோ-டூ இடம்"
        CHOOSE_A_GOTO_LOC ->  "ஒரு இலக்கைத் தேர்வுசெய்க"
        YOU_HAVE_ONLY_LEFT_FOR_TODAY ->  "இன்றைக்கு மட்டுமே நீங்கள் கிளம்பியுள்ளீர்கள்"
        YES_ENABLE ->  "ஆம் இயக்கு"
        NO_GOTO_LOCS_ADDED_YET ->  "கோ-டு இடங்கள் எதுவும் இதுவரை சேர்க்கப்படவில்லை"
        GO_TO_CANCELLATION_TITLE ->  "“கோ-டூ” குறைக்கப்படலாம்"
        GO_TO_CANCELLATION_DESC ->  "“கோ-டூ” சவாரியை ரத்துசெய்வது உங்களுக்கான “கோ-டூ” விருப்பங்களைக் குறைக்கும்!"
        ENABLE_GOTO ->  "கோ-டூ என்பதை இயக்கு"
        KNOW_MORE ->  "மேலும் அறியவும்"
        REPORT_ISSUE ->  "புகாரளிக்கவும்"
        YOU_ARE_ALMOST_AT_LOCATION ->  "நீங்கள் கிட்டத்தட்ட இருப்பிடத்திற்குச் சென்றுவிட்டீர்கள்."
        DRIVER_HOME_LOCATION_NOT_FOUND ->  "இடம் கிடைக்கவில்லை"
        DRIVER_HOME_LOCATION_DOES_NOT_EXIST ->  "இருப்பிடம் இல்லை"
        DRIVER_HOME_LOCATION_LIMIT_REACHED ->  "இருப்பிட வரம்பை அடைந்துவிட்டது"
        DRIVER_GO_HOME_REQUEST_NOT_FOUND ->  "கோரிக்கை கிடைக்கவில்லை"
        DRIVER_GO_HOME_REQUEST_DOES_NOT_EXIST ->  "கோரிக்கை இல்லை"
        DRIVER_GO_HOME_REQUEST_DAILY_USAGE_LIMIT_REACHED ->  "தினசரி பயன்பாட்டு வரம்பை எட்டிவிட்டது"
        DRIVER_GO_HOME_REQUEST_ALREADY_ACTIVE ->  "ஏற்கனவே செயலில் உள்ளது"
        DRIVER_HOME_LOCATION_OUTSIDE_SERVICE_AREA ->  "இருப்பிடம் சேவை பகுதிக்கு வெளியே உள்ளது"
        NEW_LOCATION_TOO_CLOSE_TO_PREVIOUS_HOME_LOCATION ->  "இருப்பிடம் முந்தைய இருப்பிடத்திற்கு மிக அருகில் உள்ளது"
        DRIVER_HOME_LOCATION_DOES_NOT_BELONG_TO_DRIVER ->  "இடம் உங்களுக்கு சொந்தமானது அல்ல"
        DRIVER_HOME_LOCATION_DELETE_WHILE_ACTIVE_ERROR ->  "செயலில் இருக்கும்போது இருப்பிடத்தை நீக்க முடியாது"
        DISABLE_GOTO_STR ->  "கோ-டுவை முடக்கவா?"
        YOU_STILL_HAVE_TIME_LEFT ->  "உங்கள் “கோ-டூ” கோரிக்கையில் இன்னும் நேரம் உள்ளது"
        YES_DISABLE ->  "ஆம், முடக்கு"
        DRAG_TO_ADJUST ->  "உங்கள் இருப்பிடத்தை சரிசெய்ய இழுக்கவும்"
        LOCATION_ALREADY_EXISTS ->  "இடம் ஏற்கனவே உள்ளது"
        MIN_LEFT ->  "இன்னும் நிமிடம்"
        GOTO_LOC_REACHED ->  "“கோ-டூ” இருப்பிடத்தை அடைந்தது!"
        GET_READY_FOR_YS_SUBSCRIPTION _ ->  "யாத்ரி சதி திட்டங்களுக்கு தயாராகுங்கள்!"
        SIGNUP_EARLY_FOR_SPECIAL_OFFERS ->  "சிறப்புச் சலுகைகளுக்கு முன்கூட்டியே பதிவுசெய்க"
        GUARANTEED_FIXED_PRICE _ ->  "ஜனவரி 1, 2025 வரை நிலையான விலைக்கு உத்தரவாதம்"
        INTRODUCTORY_OFFER_TO_BE_ANNOUNCED_SOON ->  "அறிமுக சலுகை விரைவில் அறிவிக்கப்படும்!"
        NO_CHARGES_TILL ->  "டிசம்பர் 31 வரை கட்டணம் இல்லை"
        AND -> " மற்றும் "
        DIRECT_PAYMENT_NO_COMMISSIONS -> "நேரடி கட்டணம்.\nகமிஷன் இல்லை"
        CUSTOMER_PAYS_DIRECTLY -> "வாடிக்கையாளர் உங்களுக்கு நேரடியாக \nபணம் அல்லது UPI மூலம் பணம் செலுத்துகிறார்"
        HUNDRED_PERCENT_FARE_GOES_TO_YOU -> "100% கட்டணம்\nஉங்களுக்குச் செல்லும்!"
        FARE_SHOWN_IS_FARE_YOU_GET -> "காட்டப்படும் கட்டணம் நீங்கள் பெறும் கட்டணமாகும்.\nமறைக்கப்பட்ட கட்டணங்கள் இல்லை."
        BE_A_PART_OF_OPEN_MOBILITY_REVOLUTION -> "திறந்த\nமொபிலிட்டி புரட்சியின் ஒரு பகுதியாக இருங்கள்!"
        OUR_DATA_AND_PRODUCT_ARE_TRANSPARENT -> "எங்களின் தரவு மற்றும் தயாரிப்பு வரைபடமானது\nஅனைவருக்கும் வெளிப்படையானது."
        ENABLE_LOCATION_PERMISSION -> "இருப்பிட அனுமதியை இயக்கு"
        PLEASE_ENABLE_LOCATION_PERMISSION_FOR -> "இதற்கு சரியான இடத்தைப் பெறவும்"
        ENABLE_LOCATION -> "இருப்பிடத்தை இயக்கு"
        YOUR_DETECTED_LOCATION_IS -> "உங்கள் கண்டறியப்பட்ட இடம்"
        LANGUAGE_DETECTED -> "மொழி கண்டறியப்பட்டது"
        CHANGE_LANGUAGE_STR -> "மொழியை மாற்றவும்"
        SELECT_LOCATION -> "இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்"
        SELECT_LOCATION_DESC -> "நீங்கள் சவாரி செய்ய விரும்பும் இடத்தைத் தேர்ந்தெடுக்கவும்"
        SELECT_LANGUAGE_DESC -> "நீங்கள் படிக்கக்கூடிய மொழியைத் தேர்ந்தெடுக்கவும்"
        CONFIRM_LANGUAGE -> "மொழியை உறுதிப்படுத்தவும்"
        GET_STARTED -> "தொடங்குங்கள்"
        ENTER_YOUR_MOBILE_NUMBER -> "உங்கள் கைபேசி எண்ணை உள்ளிடவும்"
        NOTIFICATION_ACCESS -> "அறிவிப்பு அணுகல்"
        NOTIFICATION_ACCESS_DESC -> "பரிதாபங்கள் வேறுபாட்டுகளை மிஞ்சாதே என்று பரிந்துரைக்கப்படுகிறது"
        WATCH_VIDEO -> "வீடியோவைக் காண்க"
        DL_VERIFICATION_FAILED -> "டிஎல் சரிபார்க்கல் தோல்வி. தேதி நுழைவை உள்ளிடுங்கள் மீண்டும் முயற்சிக்கவும்"
        RC_VERIFICATION_FAILED -> "ஆர்சி சரிபார்க்கல் தோல்வி. தேதி நுழைவை உள்ளிடுங்கள் மீண்டும் முயற்சிக்கவும்"
        DL_UPLOAD_FAILED -> "டிஎல் பதிவேற்றம் தோல்வி"
        RC_UPLOAD_FAILED -> "ஆர்சி பதிவேற்றம் தோல்வி"
        PLEASE_RETRY_THE_UPLOAD_AGAIN -> "தயவுசெய்து பதிவேற்றத்தை மீண்டும் முயற்சிக்கவும்"
        RC_AND_DL_UPLOAD_FAILED -> "ஆர்சி மற்றும் டிஎல் பதிவேற்றம் தோல்வி"
        RC_UPLOAD_LIMIT_REACHED -> "ஆர்சி பதிவேற்றம் வரம்பு வரம்புக்கு அதிகமாகிவிட்டது"
        DL_UPLOAD_LIMIT_REACHED -> "டிஎல் பதிவேற்றம் வரம்பு வரம்புக்கு அதிகமாகிவிட்டது"
        RETRY_UPLOAD -> "பதிவேற்றத்தை மீண்டும் முயற்சிக்கவும்"
        VEHICLE_REGISTERATON_CERTIFICATE -> "வாகன பதிவு சான்றிதழ்"
        GRANT_PERMISSIONS -> "அனுமதிகள் அளிக்க"
        SUBSCRIPTION_PLAN_STR -> "சந்தா திட்டம்"
        COMPLETE_AUTOPAY_LATER -> "பின்னணி செய்கிறது முழுமையாக 'எனது திட்டம்' பிரிவிலிருந்து."
        START_EARNING_IN_FOUR_STEPS -> "{} எளிய படிகளில் சம்பாதிக்கவும்"
        COMPLETE -> "முழுமையாக"
        HOW_TO_UPLOAD -> "எப்படி பதிவேற்ற வேண்டும்"
        TAKE_CLEAR_PICTURE_DL -> "உங்கள் டிரைவிங் லைசன்ஸின் புகை பக்கத்தை பிளாட் துணையில் தெரிவுசெய்யுங்கள்."
        ENSURE_ADEQUATE_LIGHT -> "ஒளிப்பான்மை போன்றவற்றை உற்பத்தி செய்க மற்றும் அனைத்து விவரங்களும் தெளிவாக காணப்படுகின்றன"
        FIT_DL_CORRECTLY -> "கீழே காட்டப்பட்டபடியாக டிரைவிங் லைசன்ஸை சரியாக இடுங்கள்"
        TAKE_PHOTO -> "புகைப்படம் எடு"
        FIT_RC_CORRECTLY -> "கீழே காட்டப்பட்டபடியாக பதிவு சான்றிதழை சரியாக இடுங்கள்"
        TAKE_CLEAR_PICTURE_RC -> "உங்கள் பதிவு சான்றிதழின் புகை பக்கத்தை பிளாட் துணையில் தெரிவுசெய்யுங்கள்."
        DL_UPLOADED -> "டிஎல் பதிவேற்றப்பட்டது"
        RC_UPLOADED -> "ஆர்சி பதிவேற்றப்பட்டது"
        DL_UPLOADING -> "டிஎல் பதிவேற்றப்படுகிறது"
        RC_UPLOADING -> "ஆர்சி பதிவேற்றப்படுகிறது"
        RETAKE_RC -> "\nதயவுசெய்து ஆர்சி உள்ளிட்ட படத்தை மீண்டும் எடுங்கள்"
        RETAKE_DL -> "\nதயவுசெய்து டிஎல் உள்ளிட்ட படத்தை மீண்டும் எடுங்கள்"
        CONFIRM_AND_UPLOAD -> "உறுதிப்படுத்தி பதிவேற்று"
        RETAKE_PHOTO -> "புகைப்படத்தை மீண்டும் எடு"
        LETS_GET_YOU_TRIP_READY -> "உங்கள் பயணத்தை தயார் செய்வோம்!"
        GOT_AN_OTP -> "OTP கிடைத்ததா?"
        DRIVING_LICENSE_DETAILS -> "ஓட்டுநர் உரிம விவரங்கள்"
        VEHICLE_REGISTRATION_DETAILS -> "வாகனப் பதிவு விவரங்கள்"
        UPLOAD_PHOTO -> "புகைப்படத்தைப் பதிவேற்று"
        CLEAR_IMAGE -> "புகைப்படத்தை தெளிவாக செய்யுங்கள்"
        BLURRY_IMAGE -> "புகைப்படம் தெளிவாக இல்லை"
        CROPPED_CORRECTLY -> "புகைப்படம் சரியாக கட்டப்பட்டது"
        WRONG_CROPPING -> "புகைப்படம் தவறாக கட்டப்பட்டது"
        CHANGE_LOCATION -> "இருப்பிடத்தை மாற்றவும்"
        CHANGE_CITY-> "நகரத்தை மாற்றவும்"
        UPLOAD_REGISTRATION_CERTIFICATE_STR -> "பதிவுச் சான்றிதழைப் பதிவேற்றவும்"
        TAKE_A_PHOTO -> "புகைப்படம் எடு"
        GALLERY -> "கேலரி"
        GET_FULL_PAYMENT -> "வாடிக்கையாளரிடமிருந்து நேரடியாக கட்டணம் பெறுங்கள்"
        SELECT_CITY_STR -> "நகரத்தைத் தேர்ந்தெடுக்கவும்"
        DETECTING_LOCATION -> "இருப்பிடத்தைக் கண்டறிதல்"
        UNABLE_TO_DETECT_YOUR_LOCATION -> "உங்கள் இருப்பிடத்தைக் கண்டறிய முடியவில்லை"
        RC_FAILED_DESC -> "சிறிது நேரம் கழித்து RC ஐச் சேர்க்க முயற்சிக்கவும்"
        RC_IN_PROGRESS_DESC -> "சரிபார்க்கப்பட்டதும் உங்கள் சுயவிவரத்தில் RC சேர்க்கப்படும்"
        RC_VERIFICATION_SUCCESS -> "RC சரிபார்ப்பு வெற்றிகரமாக உள்ளது!"
        RC_VERIFICATION_FAILED_STATUS -> "RC சரிபார்ப்பு தோல்வியடைந்தது!"
        RC_VERIFICATION_IN_PROGRESS -> "ஆர்சி சரிபார்ப்பு நடந்து கொண்டிருக்கிறது..."
        WE_ARE_NOT_LIVE_IN_YOUR_AREA -> "நாங்கள் இன்னும் உங்கள் பகுதியில் வசிக்கவில்லை!\nஉங்கள் நகரத்திற்கு விரைவில் வருவோம்!"
        LOCATION_UNSERVICEABLE -> "இருப்பிடம் சேவை செய்ய முடியாதது"
        UNABLE_TO_GET_YOUR_LOCATION -> "உங்கள் இருப்பிடத்தைப் பெற முடியவில்லை!"
        TURN_OFF_ANY_MOCK_LOCATION_APP_AND_RESTART -> "நீங்கள் பயன்படுத்தக்கூடிய எந்த மாதிரி இருப்பிட பயன்பாட்டையும் முடக்கி, பயன்பாட்டை மறுதொடக்கம் செய்யுங்கள்."
        MAX_IMAGES -> ""
        REFERRAL_CODE_NUMBER -> ""
        WELCOME_TEXT _ -> ""
        ABOUT_TEXT _ -> ""
        CHOOSE_LANGUAGE -> ""
        EARNED_ON_APP _ -> ""
        TRAVELLED_ON_APP _ -> ""
        WITH -> ""
        YOU_DONT_HAVE_ANY_PAYMENTS -> ""
        RESUMED_AUTOPAY -> ""
        CANCEL_ANYWAY -> ""
        VALIDITY_EXPIRED_STR -> ""
        DRIVER_GO_HOME_REQUEST_NOT_PRESENT -> ""
        YOUR_VEHICLE -> ""
        TOTAL_MONEY_COLLECTED -> ""
        FARE_EARNED_OF_THE_DAY -> ""
        GST_PLUS_PAYABLE -> ""
        TO_CONTINUE_USING_YATRI_SATHI -> ""
        PAY -> ""
        LATER -> ""
        GREAT_JOB -> ""
        FEE_BREAKUP -> ""
        YATRI_SATHI_FEE_PAYABLE_FOR_DATE _ -> ""
        FEE_CORRESPONDING_TO_THE_DISTANCE -> ""
        PLATFORM_FEE -> ""
        GST -> ""
        TOTAL_PAYABLE -> ""
        PAYMENT_SUCCESSFUL -> ""
        PAYMENT_FAILED -> ""
        PAYMENT_PENDING_DESC -> ""
        PAYMENT_FAILED_DESC _ -> ""
        WE_WILL_NOTIFY_WHEN_PAYMENT_SUCCESS -> ""
        CONTINUE_TAKING_RIDES -> ""
        YOUR_PREVIOUS_PAYMENT_IS_PENDING -> ""
        GOVERMENT_CHARGES -> ""
        OKAY -> ""
        NO_PAYMENT_HISTORY_AVAILABLE -> ""
        GOTO_YOUR_NEAREST_BOOTH -> ""
        NO_GOTO_LOCS_ADDED_YET_DESC -> ""
        BY_CLICKING_NEXT_YOU_WILL_BE_AGREEING_TO_OUR -> ""
        THIS_EXTRA_AMOUNT_THE_CUSTOMER_WILL_PAY -> "நீங்கள் {} நிமிடங்களுக்கு மேல் காத்திருந்ததால் வாடிக்கையாளர் உங்களுக்குச் செலுத்தும் கூடுதல் தொகை இது"