name: hunit-tests
version: 0.1.0.0
github: "nammayatri/nammayatri"
license: AllRightsReserved
author: "nammayatri"
maintainer: "nammayatri"
copyright: "2023 Juspay Technologies Private Limited"

description: NammaYatri HUnit tests

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- http-conduit
- tasty
- tasty-hunit
- text
- time

default-extensions:
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFunctor
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

library:
  source-dirs: src
  exposed-modules:
  - Dashboard

tests:
  hunit-tests:
    main: Main.hs
    source-dirs: app
    dependencies:
    - hunit-tests