#  @name token

GET {{mock-dunzo/url}}/api/v1/token
content-type: application/json
client-id: mock-client-id
client-secret: mock-client-secret

###

# @name successful_search
GET {{mock-dunzo/url}}/api/v1/quote
  ?category_id=pickup_drop
  &pickup_lat=12.9729391
  &pickup_lng=77.6294794
  &drop_lat=12.9354504
  &drop_lng=77.6146828
content-type: application/json
Authorization: {{token.response.body.token}}
client-id: {{mock-dunzo/client_id}}

###

# @name unserviceable_location
GET {{mock-dunzo/url}}/api/v1/quote
  ?category_id=pickup_drop
  &pickup_lat=12.9729391
  &pickup_lng=77.6294794
  &drop_lat=20.5937
  &drop_lng=78.9629
content-type: application/json
Authorization: {{token.response.body.token}}
client-id: {{mock-dunzo/client_id}}

# should return error:
# {
#   "errorPayload": null,
#   "errorCode": "INVALID_REQUEST",
#   "errorMessage": "Apologies, our services are limited to serviceable areas with in the city only"
# }

###

# @name mock-quote_nearby_location
GET {{mock-dunzo/url}}/api/v1/quote
  ?category_id=pickup_drop
  &pickup_lat=12.9729391
  &pickup_lng=77.6294794
  &drop_lat=12.9729391
  &drop_lng=77.6294794
content-type: application/json
Authorization: {{token.response.body.token}}
client-id: {{mock-dunzo/client_id}}

# should return error:
# {
#   "errorPayload": null,
#   "errorCode": "INVALID_REQUEST",
#   "errorMessage": "Pickup and drop location cannot be same"
# }

###

# @name different_city
GET {{mock-dunzo/url}}/api/v1/quote
  ?category_id=pickup_drop
  &pickup_lat=12.9729391
  &pickup_lng=77.6294794
  &drop_lat=13.0827
  &drop_lng=80.2707
content-type: application/json
Authorization: {{token.response.body.token}}
client-id: {{mock-dunzo/client_id}}

# should return error:
# {
#   "errorPayload": null,
#   "errorCode": "INVALID_REQUEST",
#   "errorMessage": "Apologies, our services are limited to serviceable areas with in the city only"
# }
