name: driver-offer-bpp
version: 0.1.0.0
github: "juspay/beckn"
license: AllRightsReserved
author: "Juspay"
maintainer: "Juspay"
copyright: "2020 Juspay Technologies Private Limited"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://bitbucket.org/juspay/beckn#readme>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - TypeSynonymInstances
  - UndecidableInstances
  - StandaloneDeriving

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - generic-lens
  - bytestring
  - cryptonite
  - containers
  - euler-hs
  - exceptions
  - hspec
  - http-api-data
  - http-client
  - http-types
  - lens
  - mtl
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - text
  - wai
  - wai-extra
  - warp
  - time
  - stm
  - random-strings
  - resource-pool
  - uuid
  - prometheus-client
  - record-hasfield
  - record-dot-preprocessor
  - servant-openapi3
  - openapi3
  - string-conversions
  - either
  - persistent
  - text-conversions

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -fplugin=RecordDotPreprocessor

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -fhide-source-paths
    - -Werror
  dependencies:
    - beckn-core
    - beckn-spec

executables:
  driver-offer-bpp-exe:
    main: Main.hs
    source-dirs: server
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
    dependencies:
      - driver-offer-bpp
      - beckn-core
      - beckn-spec
