CREATE INDEX idx_pg_payment_settlement_report_txn_date ON atlas_app.pg_payment_settlement_report USING brin (txn_date);
CREATE INDEX idx_pg_payment_settlement_report_settlement_date ON atlas_app.pg_payment_settlement_report USING brin (settlement_date);
CREATE INDEX idx_pg_payment_settlement_report_pg_approval_code ON atlas_app.pg_payment_settlement_report USING btree (pg_approval_code);
CREATE INDEX idx_pg_payment_settlement_report_utr ON atlas_app.pg_payment_settlement_report USING btree (utr);
