module Resources.LocalizableV2.OD where

import Prelude
import Resources.LocalizableV2.Types


getOd :: Keymap
getOd = Keymap {
  safety_check_in: "ସୁରକ୍ଷା ଯାଞ୍ଚ"
, safety: "ସୁରକ୍ଷା"
, download_invoice: "ଇନଭୋଇସ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ"
, report_an_issue: "ଏକ ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ"
, submit: "ଦାଖଲ କରନ୍ତୁ"
, view_invoice: "ଇନଭୋଇସ୍ ଦେଖନ୍ତୁ"
, total_amount: "ମୋଟ ରାଶି"
, amount_paid: "ଅଦାନ ରାଶି"
, trip_details_: "ଭ୍ରମଣ ବିବରଣୀ"
, download_pdf: "PDF ଡାଉନଲୋଡ୍ କରନ୍ତୁ"
, cgst: "CGST"
, invoice: "ଇନଭୋଇସ୍"
, trip_charges: "ଭ୍ରମଣ ଖର୍ଚ୍ଚ"
, promotion: "ପ୍ରଚାରଣା"
, driver_demand_extra: "ଡ୍ରାଇଭର ଟୋଲ ପାଇଁ ଅଧିକ ଦାବି କଲେ କି?"
, demand_extra_toll_amount: "ଆପଣଙ୍କ ଡ୍ରାଇଭର ଟୋଲ ପାଇଁ ଅତିରିକ୍ତ ଶୁଳ୍କ ମାଗିଥିଲେ କି, ଯଦିଓ ଏହା ଭଡ଼ା ସହିତ ଯୋଡ଼ା ଯାଇଥିଲା?"
, send_email: "ଇମେଲ୍ ପଠାନ୍ତୁ"
, complete_profile: "ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ"
, you_can_describe_the_issue_you_faced_here: "ଆପଣ ଏଠାରେ ଆପଣଙ୍କ ସମସ୍ୟାକୁ ବିବରଣ କରିପାରିବେ"
, thank_you_for_writing: "ଆମକୁ ଲେଖା ପାଇଁ ଧନ୍ୟବାଦ!"
, we_have_received_your_issue: "ଆମେ ଆପଣଙ୍କ ସମସ୍ୟାକୁ ପ୍ରାପ୍ତ କରିଛୁ। ଆମେ ଆପଣଙ୍କ ସହିତ ସମ୍ପର୍କ କରିବା ପାଇଁ ସମୟ ନେବା।"
, go_home_: "ଘରକୁ ଯାଆନ୍ତୁ"
, logo: "ଲୋଗୋ"
, about_app_description: "{} ଏକ ଖୋଲା ମଞ୍ଚ ଯାହା ରାଇଡରମାନଙ୍କୁ ଡ୍ରାଇଭରଙ୍କ ସହିତ ଯୋଡ଼ିବାକୁ ସୁବିଧା ଯୋଗାଇଥାଏ। ଏହି ଆପ୍ପ ଦ୍ୱାରା ରାଇଡରମାନେ ମିନିମାଲ ଭାଡ଼ାରେ ଯାତ୍ରା ବୁକ କରିପାରିବେ।"
, about: "ବିଷୟରେ"
, privacy_policy: "ଗୋପନୀୟତା ନୀତି"
, set_up_your_account: "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ସେଟ୍ ଅପ୍ କରନ୍ତୁ"
, continue: "ଚାଲୁ ରଖନ୍ତୁ"
, enter_your_name: "ଆପଣଙ୍କ ନାମ ଦିଅନ୍ତୁ"
, full_name: "ପୁରା ନାମ"
, verifying: "ପରୀକ୍ଷା କରାଯାଉଛି"
, referral_code_verified: "ସନ୍ଦର୍ଭ କୋଡ୍ ସତ୍ୟାପିତ ହୋଇଛି!"
, referral_code_failed: "ସନ୍ଦର୍ଭ କୋଡ୍ ବିଫଳ ହୋଇଛି! ଦୟାକରି ପରୀକ୍ଷା କରି ପୁଣିଥରେ ଚେଷ୍ଟା କରନ୍ତୁ।"
, enter_6_digit_referral_code: "6 ଅଙ୍କର ସନ୍ଦର୍ଭ କୋଡ୍ ଦାଖଲ କରନ୍ତୁ"
, not_verified: "ପରୀକ୍ଷା କରାଯାଇନାହିଁ"
, optional_bracketted: "(ଇଚ୍ଛାମୁଳକ)"
, verify: "ପରୀକ୍ଷା କରନ୍ତୁ"
,referral_code : "ରେଫରାଲ୍ କୋଡ୍"
, email: "ଇମେଲ୍"
, welcome_text: "{} କୁ ସ୍ୱାଗତ"
, please_choose_your_preferred_language_to_continue: "ଚାଲୁ ରଖିବା ପାଇଁ ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷା ବାଛନ୍ତୁ।"
, write_to_us: "ଆମକୁ ଲେଖନ୍ତୁ"
, note: "ଟୀକା"
, visit_my_rides_section_for_ride_specific_complaints: "ଭ୍ରମଣ ସମ୍ପର୍କିତ ଅଭିଯୋଗ ପାଇଁ ମୋର ରାଇଡ୍ ଅଂଶକୁ ଯାଆନ୍ତୁ"
, thank_you_for_writing_to_us: "ଆମକୁ ଲେଖିବା ପାଇଁ ଆପଣଙ୍କୁ ଧନ୍ୟବାଦ!"
, we_have_received_your_issue_well_reach_out_to_you_in_sometime: "ଆମେ ଆପଣଙ୍କ ସମସ୍ୟାକୁ ପ୍ରାପ୍ତ କରିଛୁ। ଆମେ ଆପଣଙ୍କ ସହିତ ଶୀଘ୍ର ସମ୍ପର୍କ କରିବା।"
, go_to_home__: "ଘରକୁ ଯାଆନ୍ତୁ"
, subject: "ବିଷୟ"
, your_email_id: "ଆପଣଙ୍କ ଇମେଲ୍ ID"
, describe_your_issue: "ଆପଣଙ୍କ ସମସ୍ୟା ବିବରଣ କରନ୍ତୁ"
, enter_mobile_number: "ମୋବାଇଲ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ"
, by_tapping_continue: "ଚାଲୁ କଲେ ଆପଣ ଆମର ନୀତିକୁ ସ୍ୱୀକାର କରିବେ"
, to_the: "ଆପଣ ସ୍ୱୀକାର କରୁଛନ୍ତି କି"
, enter_otp: "OTP ପ୍ରବେଶ କରନ୍ତୁ"
, resend: "ପୁନଃ ପଠାନ୍ତୁ"
, enter_your_mobile_number: "ଆପଣଙ୍କ ମୋବାଇଲ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ"
, login_using_the_otp_sent_to: "ପଠାଯାଇଥିବା OTP ଦ୍ୱାରା ଲଗଇନ କରନ୍ତୁ"
, your_recent_ride: "ଆପଣଙ୍କ ସମ୍ପ୍ରତି ରାଇଡ୍"
, view_all_rides: "ସମସ୍ତ ରାଇଡ୍ ଦେଖନ୍ତୁ"
, all_topics: "ସମସ୍ତ ବିଷୟ"
, faq: "ସାଧାରଣ ପ୍ରଶ୍ନାବଳୀ"
, report_an_issue_with_this_trip: "ଏହି ଯାତ୍ରା ସହିତ ଏକ ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ"
, you_rated: "ଆପଣ ମୂଲ୍ୟାଂକନ କରିଛନ୍ତି"
, getting_started_and_faqs: "ଆରମ୍ଭ ଏବଂ FAQ"
, for_other_issues_write_to_us: "ଅନ୍ୟ ସମସ୍ୟା ପାଇଁ ଆମକୁ ଲେଖନ୍ତୁ"
, help_and_support: "ସାହାଯ୍ୟ ଏବଂ ସମର୍ଥନ"
, our_suggested_price_for_this_trip_is: "ଏହି ଯାତ୍ରା ପାଇଁ ଆମର ପ୍ରସ୍ତାବିତ ମୂଲ୍ୟ ହେଉଛି"
, drivers_can_charge_between_the_above_range: "*ଡ୍ରାଇଭରମାନେ ଉପରେ ଦିଆଯାଇଥିବା ଦାୟରା ମଧ୍ୟରେ ଚାର୍ଜ କରିପାରନ୍ତି"
, how_this_works: "ଏହା କିପରି କାମ କରେ?"
, finding_rides_near_you: "ଆପଣଙ୍କ ପାଖରେ ରାଇଡ୍ ଖୋଜୁଛି..."
, confirming_the_ride_for_you: "ଆପଣଙ୍କ ପାଇଁ ରାଇଡ୍ ନିଶ୍ଚିତ କରୁଛି..."
, cancel_search: "ସନ୍ଧାନ ବାତିଲ୍ କରନ୍ତୁ"
, your_ride_is_now_complete: "ଆପଣଙ୍କ ଯାତ୍ରା ବର୍ତ୍ତମାନ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଛି!"
, please_pay_the_final_amount_to_the_driver_via_cash: "କିରିଆଣ କରି ଡ୍ରାଇଭରକୁ ଶେଷ ରାଶି ଦିଅନ୍ତୁ"
, where_to: "କେଉଁଠାକୁ?"
, home: "ଘର"
, pick_up_location: "ଉଠାନ୍ତୁ ଅବସ୍ଥାନ"
, request_ride: "ଏକ ଯାତ୍ରା ଅନୁରୋଧ କରନ୍ତୁ"
, name: "ନାମ"
, mobile_number_str: "ମୋବାଇଲ୍ ନମ୍ବର"
, personal_details: "ବ୍ୟକ୍ତିଗତ ବିବରଣୀ"
, your_rides: "ଆପଣଙ୍କ ଯାତ୍ରା"
, you_are_offline: "ଆପଣ ଅଫଲାଇନ ଅଛନ୍ତି"
, check_your_internet_connection_and_try_again: "ଆପଣଙ୍କ ଇଣ୍ଟରନେଟ୍ ସଂଯୋଗ ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ପୁନଃଚେଷ୍ଟା କରନ୍ତୁ"
, try_again: "ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, thank_your_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭରକୁ ଧନ୍ୟବାଦ ଦିଅନ୍ତୁ!"
, hope_your_ride_was_hassle_free: "ଆମେ ଆଶା କରୁଛୁ ଆପଣଙ୍କ ଯାତ୍ରା ସହଜ ଥିଲା"
, how_was_your_ride_with: "ଆପଣଙ୍କ ଯାତ୍ରା କିପରି ଥିଲା?"
, got_it_tell_us_more: "ଠିକ୍ ଅଛି, ଆମକୁ ଅଧିକ କୁହନ୍ତୁ?"
, write_a_comment: "ଏକ ମନ୍ତବ୍ୟ ଲେଖନ୍ତୁ (ଇଛାକୃତ)"
, update: "ଅଦ୍ୟତନ"
, language: "ଭାଷା"
, details: "ବିବରଣୀ"
, otp: "OTP"
, payment_method: "ପେମେଣ୍ଟ ପ୍ରକ୍ରିୟା"
, payment_method_string: "ନକଦ / UPI ଆପ୍ ବ୍ୟବହାର କରନ୍ତୁ"
, payment_method_string_: "ନକଦ / UPI ଆପ୍ ବ୍ୟବହାର କରନ୍ତୁ"
, cancel_ride: "ରାଇଡ୍ ବାତିଲ୍ କରନ୍ତୁ"
, request_edit: "ସମ୍ପାଦନ ଅନୁରୋଧ କରନ୍ତୁ"
, support: "ସମର୍ଥନ"
, pickup_and_drop: "ଉଠା ଏବଂ ଛାଡ଼ିବା"
, cancelled: "ବାତିଲ୍ ହୋଇଛି"
, how_the_pricing_works: "ମୂଲ୍ୟ କିପରି କାମ କରେ?"
, select_an_offer: "ଏକ ପ୍ରସ୍ତାବ ବାଛନ୍ତୁ"
, choose_a_ride_as_per_your_comfort: "ଆପଣଙ୍କ ସୁବିଧା ଅନୁଯାୟୀ ଏକ ରାଇଡ୍ ବାଛନ୍ତୁ"
, it_seems_to_be_a_very_busy_day: "ଆଜି ବହୁତ ବ୍ୟସ୍ତ ଦିନ ଲାଗୁଛି। ଆପଣ ପୁନଃ ରାଇଡ୍ ଦେଖିପାରନ୍ତି"
, sorry_we_couldnt_find_any_rides: "ମାଫ କରନ୍ତୁ, ଆମେ କୌଣସି ରାଇଡ୍ ପାଇପାରିଲୁ ନାହିଁ"
, load_more: "ଅଧିକ ଲୋଡ୍ କରନ୍ତୁ"
, we_need_access_to_your_location: "ଆମେ ଆପଣଙ୍କ ଅବସ୍ଥାନର ଅନୁମତି ଆବଶ୍ୟକ!"
, location_permission_subtitle: "ଆପଣଙ୍କୁ ରାଇଡ୍ ପାଇଁ, ଆମକୁ ଆପଣଙ୍କ ଡିଭାଇସ୍ ଅବସ୍ଥାନ ଆବଶ୍ୟକ।"
, call: "ଫୋନ କରନ୍ତୁ"
, empty_rides: "ଖାଲି ରାଇଡ୍"
, you_havent_taken_a_trip_yet: "ଆପଣ ଏଯାବତ୍ କୌଣସି ଯାତ୍ରା ନେଇନାହାନ୍ତି"
, you_havent_taken_a_trip_yet_in_past_hours: (\hours -> "ଆପଣ ପଛ ଘଣ୍ଟାରେ କୌଣସି ଯାତ୍ରା ନେଇନାହାନ୍ତି " <> hours <> " ଘଣ୍ଟା।")
, book_now: "ବୁକ୍ କରନ୍ତୁ"
, t_and_c_a: "a) ଆପଣ ସମର୍ପିତ ଭାବରେ ବେଟା ପରୀକ୍ଷଣରେ ଅଂଶ ନେବାକୁ ସ୍ୱୀକାର କରନ୍ତୁ ଏବଂ ଜସ୍ପେ କୌଣସି ଦାୟିତ୍ୱ ନେବେ ନାହିଁ"
, terms_and_conditions: "ସର୍ତ୍ତାବଳୀ"
, data_collection_authority: "c) ମୁଁ ଏଵଂ ଆମର ସ୍ୱୀକୃତ ନିତିକୁ ସ୍ୱୀକାର କରିପାରେ।"
, deny_access: "ପ୍ରବେଶକୁ ଅସ୍ୱୀକାର କରନ୍ତୁ"
, please_tell_us_why_you_want_to_cancel: "ଦୟାକରି କାରଣ କୁହନ୍ତୁ"
, mandatory: "ବାଧ୍ୟତାମୂଳକ"
, software_license: "ସଫ୍ଟୱେର ଲାଇସେନ୍ସ"
, logout_: "ଲଗ୍ ଆଉଟ୍"
, request_auto_ride: (\_ -> "ଏକ ଆଟୋ ଯାତ୍ରା ଅନୁରୋଧ କରନ୍ତୁ")
, rate_your_ride: "ଆପଣଙ୍କ ଯାତ୍ରାକୁ ମୂଲ୍ୟାଂକନ କରନ୍ତୁ"
, skip: "ଛାଡନ୍ତୁ"
, error_404: "ତ୍ରୁଟି 404"
, problem_at_our_end: "ଆମ ପକ୍ଷରେ ସମସ୍ୟା ଅଛି। ଆମର ସଚେତନତାରେ ଖବର ପାଇବା ପାଇଁ ଅପେକ୍ଷା କରନ୍ତୁ"
, notify_me: "ମୋତେ ସଚେତନ କରନ୍ତୁ"
, address: "ଠିକଣା"
, change: "ବଦଳାନ୍ତୁ"
, save_as: "ଭାବରେ ସାଜାନ୍ତୁ"
, add_tag: "ଟାଗ୍ ଯୋଗ କରନ୍ତୁ"
, work: "କାମ"
, other: "ଅନ୍ୟ"
, save: "ସେଭ୍"
, add_new_address: "ନୂତନ ଠିକଣା ଯୋଡନ୍ତୁ"
, saved_addresses: "ସଞ୍ଚିତ ଠିକଣା"
, addresses: "ଠିକଣାବଳି"
, no_favourites_saved_yet: "ଏଯାବତ୍ ପସନ୍ଦ ସଞ୍ଚିତ ହୋଇନାହିଁ"
, saved_address_helps_you_keep_your_favourite_places_handy: "ପ୍ରିୟ ଅବସ୍ଥାନରେ ରଖନ୍ତି"
, emergency_contacts: "ଜରୁରୀ ସମ୍ପର୍କ"
, edit_emergency_contacts: "ଜରୁରୀ ସମ୍ପର୍କ ଗୁଡିକ ଦେଖନ୍ତୁ"
, add_emergency_contacts: "ଅନ୍ୟ ଯୋଡନ୍ତୁ"
, add_another_contact: "ଅନ୍ୟ ସମ୍ପର୍କ"
, no_emergency_contacts_set: "ଜରୁରୀ ସଞ୍ଚିତ"
, copied: "କପି"
, trip_id: "ଭ୍ରମଣ ID"
, save_place: "ସାଜାନ୍ତୁ"
, ride_fare: "ରାଇଡ଼ ଦାର"
, ask_for_price: "ମୂଲ୍ୟ"
, ask_for_price_info: "ବେୟସେଟ୍"
, get_estimate_fare: "ଆମକୁ ସ୍ୱୀକାର"
, select_an_offer_from_our_drivers: "ପ୍ରସ୍ତାବ (ଇଚ୍ଛାକୃତ)"
, select_an_offer_from_our_drivers_info: "ଡ୍ରାଇଭର ସହିତ"
, pay_the_driver: "ଡ୍ରାଇଭରକୁ"
, pay_the_driver_info: "ସୁରକ୍ଷା କାମ"
, pay_the_driver_note: "(ପୁନଃ) ସାଜାନ୍ତୁ"
, update_personal_details: "ବିବରଣୀ"
, edit: "ସଂପାଦନ"
, del_account: "ଏକାଉଣ୍ଟ"
, account_deletion_confirmation: "ଆପଣଙ୍କକୁ"
, request_submitted: "ଅନୁରୋଧ"
, we_will_delete_your_account: "ମୋତେ"
, yes_delete_it: "ହଁ, ତାଲିକା"
, request_to_delete_account: "ତାଲିକା"
, cancel_str: "ବାତିଲ୍"
, loading: "ଲୋଡ୍"
, please_wait_while_in_progress: "ପ୍ରସ୍ଥିତ ଥାନ୍ତୁ"
, set_location_on_map: "ନକସାରେ"
, current_location: "ଏବେ"
, previous_fare: "ପୂର୍ବ"
, fare_updated: "ଅନୁରୋଧ"
, please_confirm_with_your_after_requesting: "କାମ"
, previously: "କରନ୍ତି"
, route_and_fare_updated: "ବିବରଣୀ"
, your_driver_might_want_to_go_towards_the_current_drop_kindly_ask_them_to_confirm_after_requesting: "ପାଇଁ"
, actual_fare_was_higher_than_what_was_shown: "ପ୍ରକାଶ"
, delete: "ବାତିଲ୍"
, are_you_sure_you_want_to_logout: "ଆପଣ"
, are_you_sure_you_want_to_cancel: "ଆପଣ"
, you_have_ride_offers_are_you_sure_you_want_to_cancel: "ସୂଚନା"
, go_back_: "ଗତିରେ"
, register_using_different_number: "ଆପଣକୁ"
, yes: "ହଁ"
, no: "ନା"
, cancel_: "ବାତିଲ୍"
, is_on_the_way: "ମାର୍ଗ"
, enter_4_digit_otp: "ଏକ ନମ୍ବର"
, wrong_otp: "ତ୍ରୁଟି"
, grant_access: "ପ୍ରବେଶ"
, enter_a_location: "ଅବସ୍ଥାନ"
, nearby: "ନିକଟ"
, mins_away: "ମିନିଟ"
, paid: "କେବଳ"
, by_cash: "ନକଦ"
, online_: "ଅନଲାଇନ୍"
, user: "ବ୍ୟବହାରକାରୀ"
, email_already_exists: "ତ୍ରୁଟି"
, in': "in"
, verifying_otp: "ସୁରକ୍ଷା"
, track_live_location_using: "ଉପସାରାଣା"
, google_map_: "ଗୁଗଲ୍"
, in_app_tracking: "ସଞ୍ଚିତ"
, quote_expired: "ସାଜାନ୍ତୁ"
, getting_estimates_for_you: "ଆକାଉଣ୍ଟ"
, getting_revised_estimate: "ନାମରେ"
, confirm_pickup_location: "ପରିବର୍ତନ"
, confirm_drop_location: "ପରିବର୍ତ୍ତନ"
, check_revised_fare_and_route: "ପାଠାନ୍ତୁ"
, error_occured_try_again: "ତ୍ରୁଟି"
, asked_for_more_money: "କାମ"
, start_: "ଆରମ୍ଭ"
, ride_not_serviceable: "ରାଇଡ଼"
, app_not_serviceable: "ସଞ୍ଚିତ"
, confirm_for: "ସଞ୍ଚିତ"
, eta_was_too_short: "ପ୍ରସ୍ଥିତ"
, driver_requested_to_cancel: "ତ୍ରୁଟି"
, pick_up_location_incorrect: "ଅବସ୍ଥାନ"
, could_not_connect_to_driver: "ଡ୍ରାଇଭର"
, government_chagres: "ରାଇଡ୍ GST (5%)"
, pay_driver_using_cash_or_upi_: "ନଗଦ କିମ୍ବା UPI ବ୍ୟବହାର କରି ଡ୍ରାଇଭରକୁ ପେ କରନ୍ତୁ"
, eta_was_too_long: "ରାସ୍ତା"
, others: "ସମସ୍ୟା"
, destination_outside_limits: "ଗତିରେ"
, drop_location_far_away: "ଗତିରେ"
, change_drop_location: "ପରିବର୍ତନ"
, you_can_take_a_walk_or_continue_with_ride_booking: "ଆକାଉଣ୍ଟ"
, your_trip_is_too_short_you_are_just: "ରାସ୍ତା"
, meters_away_from_your_destination: "ମିନିଟ"
, book_ride_: "ବୁକ୍"
, cancel_auto_assigning: "ବାତିଲ୍"
, location_unserviceable: "ସଞ୍ଚିତ"
, currently_we_are_live_in_: (\_ -> "ଆକାଉଣ୍ଟ")
, change_location: "ପାଠାନ୍ତୁ"
, auto_accepting_selected_ride: "ତାଲିକା"
, the_trip_is_very_short_and_just_take: "ପ୍ରସ୍ଥିତ"
, if_you_still_wanna_book_ride_click_continue_and_start_booking_the_ride: "ଆକାଉଣ୍ଟ"
, steps_to_complete: "ତାଲିକା"
, help_us_with_your_reason: "ସଞ୍ଚିତ"
, max_char_limit_reached: "ପ୍ରସ୍ଥିତ"
, driver_was_not_reachable: "ଗୁଡିକ"
, show_all_options: "ଗତିରେ"
, expires_in: "ପାଠାନ୍ତୁ"
, pay_directly_to_your_driver_using_cash_upi: "*ଗତିରେ"
, update_required: "ତ୍ରୁଟି"
, please_update_app_to_continue_service: "ପାଠାନ୍ତୁ"
, not_now: "ବାତିଲ୍"
, of': "ରାସ୍ତା"
, lost_something: "କିଛି ହାରାଇଛି କି?"
, try_connecting_with_the_driver: "ଡ୍ରାଇଭର ସହିତ ସମ୍ପର୍କ କରିପାରିବେ"
, call_driver: "ଡ୍ରାଇଭରକୁ ଫୋନ୍ କରନ୍ତୁ"
, no_more_rides: "କୌଣସି ଅଧିକ ରାଇଡ୍ ନାହିଁ"
, contact_support: "ସମର୍ଥନକୁ ସମ୍ପର୍କ କରନ୍ତୁ"
, invalid_mobile_number: "ଅବୈଧ ମୋବାଇଲ୍ ନମ୍ବର"
, ride_completed: "ରାଇଡ୍ ସମାପ୍ତ ହୋଇଛି"
, submit_feedback: "ଅଭିପ୍ରାୟ ଦାଖଲ କରନ୍ତୁ"
, how_was_your_ride_experience: "ଆପଣଙ୍କର ରାଇଡ୍ ଅଭିଜ୍ଞତା କିପରି ଥିଲା?"
, drop: "ଛାଡ଼ିବା"
, rate_your_ride_with: "ଆପଣଙ୍କର ରାଇଡ୍ କୁ ମୂଲ୍ୟାଙ୍କନ କରନ୍ତୁ "
, view_breakdown: "ବିବରଣୀ ଦେଖନ୍ତୁ"
, pay_driver_using_cash_or_upi: "ଡ୍ରାଇଭରକୁ ନକଦ କିମ୍ବା UPI ଦ୍ୱାରା ଭୁଗତା କରନ୍ତୁ"
, rate_your_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭରକୁ ମୂଲ୍ୟାଙ୍କନ କରନ୍ତୁ"
, my_rides: "ମୋର ରାଇଡ୍"
, ride_details: "ରାଇଡ୍ ବିବରଣୀ"
, ride_id: "ରାଇଡ୍ ID"
, select_a_ride: "ବିସ୍ତୃତ ବିବରଣୀ ପାଇଁ ଏକ ରାଇଡ୍ ବାଛନ୍ତୁ"
, confirm_ride_: "ରାଇଡ୍ ନିଶ୍ଚିତ କରନ୍ତୁ"
, you_can_cancel_ride: "ଡ୍ରାଇଭର ଠାରୁ ପ୍ରସ୍ତାବ ମିଳିବା ପରେ ଆପଣ ବାତିଲ୍ କରିପାରିବେ"
, estimates_changed: "ଆପଣଙ୍କ ରାଇଡର ଅନୁମାନ ବଦଳିଛି"
, estimates_revised_to: "ପୁନଃ ଅନୁମାନ ହେଉଛି"
, rate_card: "ମୂଲ୍ୟ ସୂଚୀ"
, night_time_charges: (\from till -> "ରାତିରେ ମୂଲ୍ୟ (" <> from <> " ରୁ " <> till <> ")")
, min_fare_upto: (\val -> "ନିମ୍ନତମ ଭାଡ଼ା " <> val <> " ପର୍ଯ୍ୟନ୍ତ")
, more_than: "ଅଧିକ ହୋଇଥିବା"
, rate_above_min_fare: "ନିମ୍ନତମ ଭାଡ଼ାଠାରୁ ଅଧିକ ମୂଲ୍ୟ"
, driver_pickup_charges: (\_ -> "ଡ୍ରାଇଭର ଉଠାନ୍ତୁ ଚାର୍ଜ")
, daytime_charges_applicable_at_night: (\from till -> "ଦିନକୁ ମୂଲ୍ୟ (" <> from <> " ରୁ " <> till <> ")")
, daytime_charges_applied_at_night: (\percentage from till -> percentage <> " ରାତିରେ ମୂଲ୍ୟ ଲାଗୁହେବା (" <> from <> " ରୁ " <> till <> ")")
, drivers_may_quote_extra_to_cover_for_traffic: "* ତାରିଫିକ ପାଇଁ ଆପେକ୍ଷିତ ଭାଡ଼ା ଚାର୍ଜ କରିପାରେ"
, got_it: "ବୁଝିଲି!"
, day_time_charges: (\from till -> "ଦିନକୁ ମୂଲ୍ୟ ("<> from <> " ରୁ " <> till <> ")")
, share_app: "ଆପ୍ ସେୟାର କରନ୍ତୁ"
, away_c: "ଦୂରେ"
, away: "ଯାଇଥିବା"
, at_pickup: "ଉଠାନ୍ତୁ"
, fare_has_been_updated: "ଭାଡ଼ା ଅଦ୍ୟତନ ହୋଇଛି"
, total_fare_may_change_due_to_change_in_route: "ମୋଟ ଭାଡ଼ା ରାସ୍ତା ଅନୁସାରେ ବଦଳିପାରେ"
, at_drop: "ଛାଡ଼ିବା"
, emergency_help: "ଜରୁରୀ ସାହାଯ୍ୟ"
, also_share_your_ride_status_and_location: "ଆପଣଙ୍କର ଯାତ୍ରା ସ୍ଥିତି ଏବଂ ଅବସ୍ଥାନ ସେୟାର କରନ୍ତୁ"
, share_ride_with_emergency_contacts: "ଜରୁରୀ ସମ୍ପର୍କ ସହିତ ଯାତ୍ରା ସେୟାର କରନ୍ତୁ"
, do_you_need_emergency_help: "ଆପଣଙ୍କୁ ଜରୁରୀ ସାହାଯ୍ୟ ଆବଶ୍ୟକ କି?"
, call_support: "ସମର୍ଥନକୁ ଫୋନ କରନ୍ତୁ"
, you_are_about_to_call_namma_yatri_support: (\_ -> "ଆପଣ ନମ୍ମା ଯାତ୍ରୀ ସମର୍ଥନ ଟିମ୍କୁ ଫୋନ କରିବାକୁ ଯାଉଛନ୍ତି। ଆପଣ ଅଗ୍ରସର ହେବାକୁ ଚାହାନ୍ତି କି?")
, you_are_about_to_call_nearest_emergency_centre: "ଆପଣ ନିକଟତମ ଜରୁରୀ ସେଣ୍ଟରକୁ ଫୋନ କରିବାକୁ ଯାଉଛନ୍ତି। ଆପଣ ଅଗ୍ରସର ହେବାକୁ ଚାହାନ୍ତି କି?"
, dial_112: "112 ଡାଏଲ୍ କରନ୍ତୁ"
, help_us_with_your_feedback_optional: "ଆପଣଙ୍କର ଅଭିପ୍ରାୟ ଦିଅନ୍ତୁ (ଇଚ୍ଛାକୃତ)"
, wait_time: "ଅପେକ୍ଷା ସମୟ"
, favourites: "ପସନ୍ଦଗୁଡିକ"
, add_favourite: "ପସନ୍ଦ ଯୋଡନ୍ତୁ"
, all_favourites: "ସମସ୍ତ ପସନ୍ଦଗୁଡିକ"
, remove: "ବାହାର କରନ୍ତୁ"
, confirm_location: "ଅବସ୍ଥାନ ନିଶ୍ଚିତ କରନ୍ତୁ"
, select_on_map: "ନକସାରେ ଚୟନ କରନ୍ତୁ"
, favourite_location: "ପ୍ରିୟ ଅବସ୍ଥାନ"
, edit_favourite: "ପ୍ରିୟ ସମ୍ପାଦନ କରନ୍ତୁ"
, drag_the_map: "ନକସାକୁ ଟାଣନ୍ତୁ ଏବଂ ଏକ୍ସାକ୍ଟ ସ୍ଥାନକୁ ପିନ୍ ସେଟ୍ କରନ୍ତୁ"
, choose_on_map: "ନକସାରେ ଚୟନ କରନ୍ତୁ"
, use_current_location: "ବର୍ତ୍ତମାନ ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ"
, favourite_your_current_location: "ଆପଣଙ୍କର ବର୍ତ୍ତମାନ ସ୍ଥାନକୁ ପ୍ରିୟ କରନ୍ତୁ"
, location: "ଅବସ୍ଥାନ"
, location_already_exists_as: "ଅବସ୍ଥାନ ଏବେ"
, give_this_location_a_name: "ଏହି ଅବସ୍ଥାନକୁ ଏକ ନାମ ଦିଅନ୍ତୁ"
, favourite: "ପ୍ରିୟ"
, confirm_and_save: "ନିଶ୍ଚିତ କରନ୍ତୁ ଏବଂ ସେଭ୍ କରନ୍ତୁ"
, remove_favourite: "ପ୍ରିୟକୁ ବାହାର କରନ୍ତୁ"
, are_you_sure_you_want_to_remove_favourite_: "ଆପଣ ପ୍ରିୟ ଅବସ୍ଥାନକୁ ବାହାର କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?"
, yes_remove: "ହଁ, ବାହାର କରନ୍ତୁ"
, add_new_favourite: "ନୂତନ ପ୍ରିୟ ଯୋଡନ୍ତୁ"
, select_your_drop: "ଆପଣଙ୍କ ଛାଡ଼ିବା ସ୍ଥାନ ବାଛନ୍ତୁ"
, favourite_removed_successfully: "ପ୍ରିୟ ସଫଳତାର ସହ ହଟାଇଦିଆଯାଇଛି"
, location_already_exists: "ଅବସ୍ଥାନ ଏବେ ଅଛି"
, location_already: "ଅବସ୍ଥାନ ଏବେ"
, exists_as: "ଭାବରେ ଅଛି"
, favourite_added_successfully: "ପ୍ରିୟ ସଫଳତାର ସହ ଯୋଡାଯାଇଛି"
, favourite_updated_successfully: "ପ୍ରିୟ ସଫଳତାର ସହ ଅଦ୍ୟତନ ହୋଇଛି"
, already_exists: "ପୂର୍ବରୁ ଅଛି"
, name_already_in_use: "ନାମ ପୂର୍ବରୁ ବ୍ୟବହାର ହୋଇଛି"
, select_favourite: "ପ୍ରିୟ ବାଛନ୍ତୁ"
, confirm_changes: "ପରିବର୍ତ୍ତନକୁ ନିଶ୍ଚିତ କରନ୍ତୁ"
, add_saved_location_from_settings: "*ଆପଣ ସାଇଡ୍ ମେନୁ > ପ୍ରିୟଗୁଡିକ ଠାରୁ ନୂତନ ପସନ୍ଦ ଯୋଡ଼ିପାରିବେ"
, you_will_be_asked_to_select_contacts: "ଆପଣ ତିନୋଟି ସଂପର୍କ ବାଛିବାକୁ ପାଇଁ ପୃଥକ ହେବେ"
, auto_assign_a_ride: "ସ୍ୱୟଂ ଏକ ରାଇଡ୍ ଆସାଇନ କରନ୍ତୁ"
, is_waiting_at_pickup: "ଉଠାନ୍ତୁ ଅପେକ୍ଷାରେ ଅଛି"
, wait_time_too_long: "ଅପେକ୍ଷା ସମୟ ଅଧିକ"
, got_another_ride_else_where: "ଅନ୍ୟ କାହାରି ଦେଇ ଯାତ୍ରା ପାଇଲି"
, driver_was_rude: "ଡ୍ରାଇଭର ଅଶିଷ୍ଟ ଥିଲେ"
, maybe_later: "ଶାୟଦ ପରେ"
, your_ride_has_started: "ଆପଣଙ୍କ ଯାତ୍ରା ଆରମ୍ଭ ହୋଇଯାଇଛି 🤩"
, enjoy_riding_with_us: "ଆମ ସହିତ ଯାତ୍ରାର ସନ୍ତୋଷକୁ ସେୟାର କରନ୍ତୁ \n ଏବଂ ସମ୍ପର୍କରେ ପ୍ରଚାର କରନ୍ତୁ"
, view_details: "ବିବରଣୀ ଦେଖନ୍ତୁ"
, repeat_ride: "ରାଇଡ୍ ପୁନଃ କରନ୍ତୁ"
, fare_was_high: "ଭାଡ଼ା ଅଧିକ ଥିଲା"
, auto_assign_driver: "ସ୍ୱୟଂ ଏକ ଡ୍ରାଇଭର ଆସାଇନ କରନ୍ତୁ"
, choose_between_multiple_drivers: "ଏକାଧିକ ଡ୍ରାଇଭର ମଧ୍ୟରୁ ବାଛନ୍ତୁ"
, choose_between_multiple_rides: "ଏକାଧିକ ରାଇଡ୍ ବିକଳ୍ପରେ ବାଛନ୍ତୁ"
, enable_this_feature_to_choose_your_ride: "ଆପଣଙ୍କ ପସନ୍ଦର ରାଇଡ୍ ଏବଂ ଭାଡ଼ା ବାଛିବା ପାଇଁ ଏହି ବିଶେଷତାକୁ ସକ୍ରିୟ କରନ୍ତୁ"
, booking_preference: "ବୁକିଂ ପସନ୍ଦ"
, base_fares: "ମୂଲ ଭାଡ଼ା"
, pickup_charge: "ଉଠାନ୍ତୁ ଚାର୍ଜ"
, total_paid: "ମୋଟ ଅଦାନ"
, waiting_charge: "ଅପେକ୍ଷା ଚାର୍ଜ"
, nominal_fare: "ଅପେକ୍ଷା କ୍ଷେତ୍ରରେ ଡ୍ରାଇଭର ଅନୁରୋଧ*"
, customer_cancellation_dues: "କ୍ଷତିପୂରଣ ଦାୟି"
, drivers_can_charge_an_additional_fare_upto: "* ଡ୍ରାଇଭରମାନେ ଚାହିଲେ ମୂଳ ଦରର 10% ଅତିରିକ୍ତ ଆବଦାନ (ନିକଟତମ ରୁ. 10 ରେ ପରିବର୍ତ୍ତିତ) ମାଗିପାରନ୍ତି ଯାହା ଯାତାୟାତର ପରିସ୍ଥିତି, ଫେରାଯାଇବାର ସମ୍ଭାବନା ଇତ୍ୟାଦି ଦ୍ୱାରା କୋରିବାକୁ ସାହାଯ୍ୟ କରେ।"
, waiting_charge_description: "° ପ୍ରଥମ {} ମିନିଟ ପାଇଁ ପ୍ରତିକ୍ଷା ଚାର୍ଜ ଶୂନ୍ୟ। ତାପରେ ଆପଣଙ୍କୁ ପ୍ରତି ମିନିଟ ପାଇଁ ₹{} ଚାର୍ଜ କରାଯିବ।"
, waiting_charge_ratecard_description: (\waitingCharge freeWaitingTime -> "1. ପ୍ରଥମ" <> freeWaitingTime <> " ମିନିଟ ପାଇଁ ପ୍ରତିକ୍ଷା ଚାର୍ଜ ଶୂନ୍ୟ।\n 2. ପରେ ମିନିଟ ପିଛା" <> waitingCharge <> " ଚାର୍ଜ ପ୍ରଯୋଜ୍ୟ ହେବ।")
, waiting_charge_info: (\waitingCharge freeWaitingTime -> "ପ୍ରଥମ " <> freeWaitingTime <> " ମିନିଟ ପରେ ପ୍ରତି ମିନିଟରେ " <> waitingCharge <> " ରେ ପ୍ରଯୋଜ୍ୟ।")
, successful_onboard: (\_ -> "ଆପଣ ସଫଳତାର ସହ ନମ୍ମା ଯାତ୍ରିକୁ ସାଇନ୍ କରିଛନ୍ତି।")
, have_referral_code: "ରେଫେରେଲ କୋଡ୍ ରହିଛି କି?"
, refereal_code_discription: "ଆପଣଙ୍କର ରେଫେରେଲ୍ ଡ୍ରାଇଭର ଲାଭ ପାଇବା ପାଇଁ ଏକ କାରଣ ହୋଇପାରେ!"
, six_digit_referral_code: "ଡ୍ରାଇଭର ଦ୍ୱାରା ଶେୟାର୍ ହେବାକୁ ଥିବା 6 ଦିଗିଟର କୋଡ୍ ପ୍ରବେଶ କରନ୍ତୁ"
, about_referral_program: "ରେଫେରେଲ ପ୍ରୋଗ୍ରାମ କ'ଣ?"
, about_referral_program_discription: (\_ -> "ରେଫେରେଲ ପ୍ରୋଗ୍ରାମ ଡ୍ରାଇଭରମାନେ ଅଧିକ ସେବା ଦେବାକୁ ଏବଂ ଭଲ କାର୍ଯ୍ୟ ପାଇଁ ପୁରସ୍କାର ପ୍ରଦାନ କରେ। ଆପଣ ଡ୍ରାଇଭରଙ୍କର ରେଫେରେଲ କୋଡ୍ ପ୍ରବେଶ କରି ଏବଂ ନମ୍ମା ଯାତ୍ରି ସମୁଦାୟର ଗୁଣବତ୍ତା ଉନ୍ନତ କରିପାରିବେ।")
, you_can_get_referral_code_from_driver: (\_ -> "\nନମ୍ମା ଯାତ୍ରି ଡ୍ରାଇଭରଙ୍କୁ ପଚାରି ଆପଣ ଏକ ରେଫେରେଲ କୋଡ୍ ପାଇପାରିବେ।")
, referral_code_successfull: "ଆପଣ ସଫଳତାର ସହ ରେଫେରେଲ କୋଡ୍ ପ୍ରୟୋଗ କରିଛନ୍ତି"
, referral_code_applied: "ରେଫେରେଲ ପ୍ରୟୋଗ ହୋଇଛି!"
, hey: "ହେଏ"
, invalid_code_please_re_enter: "ଅବୈଧ କୋଡ୍। ଦୟାକରି ପୁନଃ ପ୍ରବେଶ କରନ୍ତୁ।"
, let_try_that_again: "ଆସନ୍ତୁ, ଏଥାରେ ପୁନଃ ଚେଷ୍ଟା କରିବା!"
, contacts_selected: "ସମ୍ପର୍କ ବାଛାଗଲା"
, select_contacts: "ସମ୍ପର୍କ ବାଛନ୍ତୁ"
, confirm_emergency_contacts: "ବିଶ୍ୱସ୍ତ ସମ୍ପର୍କ ସଂପାଦନ କରନ୍ତୁ"
, are_you_sure_you_want_to_remove_contact: "ଆପଣଙ୍କ ନିଶ୍ଚିତ କି ଏହାକୁ ବିଶ୍ୱସ୍ତ ସମ୍ପର୍କରୁ ହଟାଇବାକୁ?"
, search_contacts: "ସମ୍ପର୍କ ଖୋଜନ୍ତୁ"
, call_emergency_contacts: "ବିଶ୍ୱସ୍ତ ସମ୍ପର୍କକୁ ଫୋନ କରନ୍ତୁ"
, live_stats_dashboard: "ସଜୀବ ତଥ୍ୟ ଡ୍ୟାଶବୋର୍ଡ"
, check_out_live_stats: "ସଜୀବ ତଥ୍ୟ ଦେଖନ୍ତୁ"
, trusted_contacs_added_successfully: "ବିଶ୍ୱସ୍ତ ସମ୍ପର୍କ ସଫଳତାର ସହ ଯୋଡାଯାଇଛି"
, no_contacts_left_on_device_to_add: "ଯୋଡିବା ପାଇଁ ଏହାରେ କୌଣସି ସମ୍ପର୍କ ନାହିଁ।"
, percentage_of_nominal_fare: "ମୂଳ ଭଡାର 10%"
, pay_via_cash_or_upi: "ନକଦ କିମ୍ବା UPI ଦ୍ୱାରା ପେମେଣ୍ଟ କରନ୍ତୁ"
, request_callback: "କଲବ୍ୟାକ ଅନୁରୋଧ କରନ୍ତୁ"
, choose_your_ride: "ଆପଣଙ୍କର ରାଇଡ୍ ବାଛନ୍ତୁ"
, board_the_first: "ପ୍ରଥମରେ ବସନ୍ତୁ"
, taxi: "ଟ୍ୟାକ୍ସି"
, ac: "ଏସି"
, non_ac: "ନନ-ଏସି"
, taxi_from_zone: (\key -> "ନିକଟତମ ଯାଏଗାରୁ")
, economical: "ମୂଲ୍ୟସମ୍ବନ୍ଧୀୟ"
, comfy: "ସୁବିଧାଜନକ"
, navigate: "ନାଭିଗେଟ୍ କରନ୍ତୁ"
, and: " ଏବଂ "
, for_every_extra_hour_you_add: "ଆପଣ ପ୍ରତ୍ୟେକ ଅତିରିକ୍ତ ଘଣ୍ଟା ଯୋଡିଲେ, ଆପଣଙ୍କ ପ୍ୟାକେଜ୍ ରେ 10 ଅତିରିକ୍ତ କିଲୋମିଟର ଦୂରତା ଆପଣଙ୍କୁ ଅଲୋଟ୍ କରାଯିବ।"
, service_charges: "ସେବା ଚାର୍ଜସ୍"
, confirm_and_book: "ନିଶ୍ଚିତ କରନ୍ତୁ ଏବଂ ବୁକ୍ କରନ୍ତୁ"
, people: "ଲୋକେ"
, spacious: "ପରିସରରେ ବଡ଼"
, cancel_ongoing_search: "ଆପଣ ଏକ ଅନବରତ ଖୋଜ ରଦ୍ଦ କରିବା ନିଶ୍ଚିତ କି?"
, search_again_with_a_tip: "ଏକ ଟିପ୍ ସହିତ ପୁନଃ ଖୋଜନ୍ତୁ?"
, try_again_with_a_tip: "ଏକ ଟିପ୍ ସହିତ ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ?"
, boost_your_ride_chances_and_help_drivers_with_tips: "ଏହା ଏକ ବହୁତ ବ୍ୟସ୍ତ ଦିନ ଲାଗୁଛି। ରାଇଡ୍ ପାଇବାର ସମ୍ଭାବନା ବଢିବା ପାଇଁ ଏକ ଟିପ୍ ଯୋଡିବାକୁ ଚେଷ୍ଟା କରନ୍ତୁ।"
, try_again_without_tip: "ଟିପ୍ ବିନା ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, search_again_without_a_tip: "ଟିପ୍ ବିନା ପୁନଃ ଖୋଜନ୍ତୁ"
, try_again_with: "ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, search_again_with: "ପୁନଃ ଖୋଜନ୍ତୁ"
, tip: "ଟିପ୍"
, customer_selected_fare: "ଗ୍ରାହକ ଟିପ୍^"
, start_your_chat_using_these_quick_chat_suggestions: "ଏହି ତ୍ରୁଟି ଚାର୍ଟ ସୁପାରିଶଗୁଡ଼ିକ ବ୍ୟବହାର କରି ଆପଣଙ୍କର ଚାର୍ଟ ଆରମ୍ଭ କରନ୍ତୁ"
, message: "ସନ୍ଦେଶ"
, start_your_chat_with_the_driver: "ଡ୍ରାଇଭର ସହ ଆପଣଙ୍କର ଚାର୍ଟ ଆରମ୍ଭ କରନ୍ତୁ"
, i_am_on_my_way: "ମୁଁ ଆସୁଛି"
, getting_delayed_please_wait: "ବିଳମ୍ବିତ ହେଉଛି, ଦୟାକରି ପ୍ରତିକ୍ଷା କରନ୍ତୁ"
, unreachable_please_call_back: "ଅପ୍ରାପ୍ୟ, ଦୟାକରି ଫେରା ସଂକ୍ରମଣ କରନ୍ତୁ"
, are_you_staring: "ଆପଣ ଆରମ୍ଭ କରୁଛନ୍ତି କି?"
, please_come_soon: "ଦୟାକରି ଶୀଘ୍ର ଆସନ୍ତୁ"
, ok_i_will_wait: "ଠିକ ଅଛି, ମୁଁ ପ୍ରତିକ୍ଷା କରିବି"
, i_have_arrived: "ମୁଁ ପହଞ୍ଚିଛି"
, please_come_fast_i_am_waiting: "ଦୟାକରି ଶୀଘ୍ର ଆସନ୍ତୁ, ମୁଁ ପ୍ରତିକ୍ଷା କରୁଛି"
, please_wait_i_will_be_there: "ଦୟାକରି ପ୍ରତିକ୍ଷା କରନ୍ତୁ, ମୁଁ ଆସୁଛି"
, looking_for_you_at_pickup: "ପିକଅପ୍ ସ୍ଥାନରେ ଆପଣଙ୍କୁ ଦେଖୁଛି"
, mobile: "ମୋବାଇଲ"
, how_do_you_identify_yourself: "ଆପଣ ନିଜକୁ କିପରି ପରିଚିତ କରିଛନ୍ତି?"
, select_your_gender: "ଆପଣଙ୍କର ଲିଙ୍ଗ ଚୟନ କରନ୍ତୁ"
, female: "ମହିଳା"
, male: "ପୁରୁଷ"
, prefer_not_to_say: "କହିବାକୁ ଚାହୁଁନି"
, email_id: "ଇମେଲ୍ ଆଇଡି"
, set_now: "ବର୍ତ୍ତମାନ ସେଟ୍ କରନ୍ତୁ"
, add_now: "ବର୍ତ୍ତମାନ ଯୋଡନ୍ତୁ"
, how_should_we_address_you: "ଆମେ କିପରି ଆପଣଙ୍କୁ ଡାକିବାକୁ ଚାହିଁବା?"
, gender_str: "ଲିଙ୍ଗ"
, profile_completion: "ପ୍ରୋଫାଇଲ ସମାପ୍ତ"
, early_end_ride_charges: "ପୂର୍ବରୁ ରାଇଡ୍ ସମାପ୍ତ ଚାର୍ଜସ୍ ^"
, early_end_ride_charges_description: "^ରାଇଡ୍ ଶେଷରେ ଅନତିରିକ୍ତ ଚାର୍ଜ ହାରର ଅର୍ଧରେ ଉପଯୋଗ ହେବ।"
, yes_try_again: "ହଁ, ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, no_dont: "ନାହିଁ, ନା"
, yes_cancel_search: "ହଁ, ସେଇନ୍ ରଦ୍ଦ କରନ୍ତୁ"
, try_looking_for_rides_again: "ଏହା ବହୁତ ବ୍ୟସ୍ତ ଦିନ। ଆପଣ ପୁନଃ ଖୋଜିପାରନ୍ତି"
, no_tip: "କୌଣସି ଟିପ୍ ନାହିଁ"
, customer_tip_description: "^ଗ୍ରାହକଙ୍କ ଦ୍ୱାରା ଯୋଡାଯାଇଛି"
, place_call: "କଲ୍ ରଖନ୍ତୁ"
, direct_call: "ସିଧାସଳକ କଲ୍"
, anonymous_call: "ଗୋପନୀୟ କଲ୍"
, your_number_will_not_be_shown_to_the_driver_the_call_will_be_recorded_for_compliance: "ଆପଣଙ୍କ ନମ୍ବର ଡ୍ରାଇଭରକୁ ଦେଖାଯିବ ନାହିଁ। ନିୟମିତା ପାଇଁ କଲ୍ ରେକର୍ଡ ହେବ।"
, your_number_will_be_visible_to_the_driver_use_if_not_calling_from_registered_number: "ଆପଣଙ୍କ ନମ୍ବର ଡ୍ରାଇଭରକୁ ଦେଖାଯିବ। ଯଦି ଆପଣ ରେଜିଷ୍ଟର୍ କାର୍ ନମ୍ବର ଠାରୁ କଲ୍ କରୁନାହିଁ ତେବେ ଏହା ବ୍ୟବହାର କରନ୍ତୁ।"
, call_driver_using: "ଡ୍ରାଇଭରକୁ କଲ୍ କରନ୍ତୁ"
, was_your_call_successful: "ଆପଣଙ୍କର କଲ୍ ସଫଳ ହୋଇଛି କି?"
, driver_additions: "ଡ୍ରାଇଭର ଅତିରିକ୍ତ ସେବା*"
, fare_update_policy: "ଭଡା ଅପଡେଟ୍ ନୀତି"
, driver_additions_optional: "ଡ୍ରାଇଭର ଅତିରିକ୍ତ ସେବା (ଇଚ୍ଛାନୁସାରେ)"
, the_driver_may_quote_extra_to_cover_for_traffic: "ଡ୍ରାଇଭର ଯାତାୟାତ ଆବଶ୍ୟକତା ପାଇଁ ଅତିରିକ୍ତ ଦାମ ମାଗିପାରନ୍ତି।"
, driver_additions_are_calculated_at_rate: (\_ -> "ଡ୍ରାଇଭର ଅତିରିକ୍ତ ଦାମ ମୂଳ ଭଡାର 10% ହାରରେ ନିକଟତମ ₹10 ପର୍ଯ୍ୟନ୍ତ ଗଣାଯାଇଛି।")
, driver_may_not_charge_this_additional_fare: "ଲକ୍ଷ୍ୟ କରନ୍ତୁ ଡ୍ରାଇଭର ଏହି ଅତିରିକ୍ତ ଦାମ ଚାର୍ଜ୍ କରିବା ନ ହେବ ମାଗିବାକୁ ଥାଏ।"
, you_may_see_an_updated_final_fare_due_to_any_of_the_below_reasons: "ନିମ୍ନଲିଖିତ କାରଣରୁ ଆପଣ ଏକ ଅପଡେଟ୍ ଅନ୍ତିମ ଭଡା ଦେଖିପାରିବେ"
, reason_change_in_route_a: "1. ରୁଟ୍ ରେ ପରିବର୍ତ୍ତନ"
, reason_change_in_route_b: "ରୁଟ୍ ରେ ପରିବର୍ତ୍ତନ ହେବାରେ ମୋଟ ଭଡା ପରିବର୍ତ୍ତିତ ହେବ।"
, go_to_zone: (\_ -> "ପିକଅପ୍ ଜୋନକୁ ଯାଆନ୍ତୁ")
, update_now: "ଏବେ ଅପଡେଟ୍ କରନ୍ତୁ"
, request_received_we_will_call_you_back_soon: "ଅନୁରୋଧ ଗ୍ରହଣ କରାଗଲା। ଆମେ ଆପଣଙ୍କୁ ଶୀଘ୍ର ଫେରା ଫୋନ୍ କରିବୁ।"
, contact_removed_successfully: "ସମ୍ପର୍କ ସଫଳତାର ସହିତ ହଟାଗଲା"
, corporate_address: "କର୍ପୋରେଟ୍ ଠିକଣା"
, corporate_address_description: (\_ -> "ମୁଭିଂ ଟେକ୍ ଇନୋଭେସନ୍ସ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍ <br> ଗିରିଜା ବିଲ୍ଡିଂ, ନମ୍ବର 817, ଗଣପତି ମନ୍ଦିର ରୋଡ୍, 8ଥ୍ ବ୍ଲକ୍, କୋରାମଙ୍ଗଲା, ବେଙ୍ଗାଲୁରୁ, କର୍ନାଟକ 560095, ଭାରତ।")
, corporate_address_description_additional: (\_ -> "ୱେବସାଇଟ୍ <u>https://nammayatri.in/</u>")
, registered_address: "ରେଜିଷ୍ଟର୍ ଠିକଣା"
, registered_address_description: (\_ -> "ମୁଭିଂ ଟେକ୍ ଇନୋଭେସନ୍ସ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍ <br> ଇନ୍ଡିକ୍ୟୁବ୍ ଗାର୍ଡନ୍, ଓଲ୍ଡ ନଂ. 648, ନୂତନ ନଂ. 130, ଗ୍ରେପ୍ ଗାର୍ଡନ୍, 18ଥ୍ ମେନ୍, 1ସ୍ଟ ଏ କ୍ରସ୍, 6ଥ୍ ବ୍ଲକ୍, କୋରାମଙ୍ଗଲା, ବେଙ୍ଗାଲୁରୁ 560095।")
, registered_address_description_additional: (\_ -> "ୱେବସାଇଟ୍ <u>https://nammayatri.in/</u>")
, recommended: "ସୁପାରିଶିତ"
, complete_your_profile_for_a_personalised_ride_experience: "ପ୍ରତ୍ୟକ୍ଷତାରେ ରାଇଡ୍ ଅଭିଜ୍ଞତା ପାଇଁ ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ"
, we_would_appreciate_your_feedback: "ଆମେ ଆପଣଙ୍କର ଆକାଉଣ୍ଟ ଅପରାହରଣ ପାଇଁ କାରଣ ଜାଣିବାକୁ ଚାହୁଁଛୁ"
, reason_for_deleting_account: "ଆକାଉଣ୍ଟ ବାତିଲ କରିବା ପାଇଁ କାରଣ*"
, submit_request: "ଅନୁରୋଧ ପ୍ରଦାନ କରନ୍ତୁ"
, please_enter_a_valid_email: "ଦୟାକରି ଏକ ବୈଧ ଇମେଲ୍ ପ୍ରବେଶ କରନ୍ତୁ"
, we_would_appreciate_your_reasoning: "ଆକାଉଣ୍ଟ ବାତିଲ କରିବାର କାରଣ ଆପଣଙ୍କ ମତାମତ ଆମେ ପ୍ରଶଂସା କରୁ"
, ok_got_it: "ଠିକ ଅଛି, ବୁଝିଲି"
, wait_for_driver: "ଡ୍ରାଇଭର ପାଇଁ ପ୍ରତିକ୍ଷା କରନ୍ତୁ"
, no_longer_require_a_ride_due_to_change_in_plans: "ଯାତ୍ରା ପରିବର୍ତ୍ତନ ହୋଇଯାଇଛି କାରଣ ରାଇଡ୍ ଆବଶ୍ୟକତା ନାହିଁ"
, cancelling_as_i_got_a_ride_on_another_app: "ଏକ ଅନ୍ୟ ଆପରେ ରାଇଡ୍ ପାଇବା ପାଇଁ ବାତିଲ କରିବା"
, driver_location_wasnt_changing_on_the_map: "ମାନଚିତ୍ରରେ ଡ୍ରାଇଭରର ସ୍ଥାନ ପରିବର୍ତ୍ତନ ହୋଇ ନାହିଁ"
, driver_was_taking_too_long_to_reach_the_pickup_location: "ଡ୍ରାଇଭର ପିକଅପ୍ ସ୍ଥାନରେ ପହଞ୍ଚିବାରେ ଅତିରିକ୍ତ ସମୟ ନେଉଥିଲା"
, the_pickup_location_entered_was_wrong: "ପ୍ରବେଶ କରାଯାଇଥିବା ପିକଅପ୍ ସ୍ଥାନ ଭୁଲ୍ ଥିଲା"
, your_driver_is_just: "ଆପଣଙ୍କ ଡ୍ରାଇଭର ମାତ୍ର"
, m_away: "ମିଟର ଦୂର ରହିଛନ୍ତି।"
, driver_has_already_travelled: "ଡ୍ରାଇଭର ପହଞ୍ଚିଛନ୍ତି"
, please_contact_the_driver_before_cancelling: "\nଦୟାକରି ବାତିଲ କରିବା ପୂର୍ବରୁ ଡ୍ରାଇଭରକୁ ସମ୍ପର୍କ କରନ୍ତୁ"
, confirm_with_your_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭର ସହିତ ନିଶ୍ଚିତ କରନ୍ତୁ"
, change_of_plans: "ଯାତ୍ରାରେ ପରିବର୍ତ୍ତନ"
, driver_is_not_moving: "ଡ୍ରାଇଭର ଚାଲିବା ନାହିଁ"
, wrong_pickup_location: "ଭୁଲ୍ ପିକଅପ୍ ସ୍ଥାନ"
, different_vehicle_number: "ଭିନ୍ନ ଯାନ ନମ୍ବର"
, vehicle_number_is_different_from_what_is_shown_in_the_app: "ଆପ୍ରେ ଦେଖାଯାଇଥିବା ଯାନ ନମ୍ବରରୁ ଅନ୍ୟ ଥିବା ଯାନ"
, different_auto: "ଭିନ୍ନ ଅଟୋ"
, different_cab: "ଭିନ୍ନ କ୍ୟାବ୍"
, driver_might_be_taking_alternate_route: "ଡ୍ରାଇଭର ବିକଳ୍ପ ରୁଟ୍ ନେଉଥିବା ସମ୍ଭାବନା ଅଛି।"
, driver_is_not_moving_q: "ଡ୍ରାଇଭର ଚାଲିବା ନାହିଁ?"
, would_you_like_to_check_with_the_driver_before_cancelling: "\nବାତିଲ କରିବା ପୂର୍ବରୁ ଡ୍ରାଇଭର ସହିତ ଚେକ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?"
, driver_is_near_your_location: "ଡ୍ରାଇଭର ଆପଣଙ୍କର ସ୍ଥାନ ନିକଟରେ ଅଛନ୍ତି।"
, some_other_reason: "ଅନ୍ୟ କାରଣ"
, location_permission_subtitle_new_user: "ଆପଣଙ୍କୁ ସ୍ୱାଗତ! \nବୁକିଂ ଆରମ୍ଭ କରିବା ପାଇଁ ଆମକୁ ଅନୁମତି ଦିଅନ୍ତୁ!"
, metro_ride: "ମେଟ୍ରୋ ରାଇଡ୍"
, go_back_text: "ପଛକୁ ଯାଆନ୍ତୁ"
, driver_preferred_your_special_request_and_is_just: "ଡ୍ରାଇଭର ଆପଣଙ୍କର ବିଶେଷ ଅନୁରୋଧ ପସନ୍ଦ କରିଛନ୍ତି ଏବଂ ମାତ୍ର"
, driver_preferred_your_special_request: "ଡ୍ରାଇଭର ଆପଣଙ୍କ ବିଶେଷ ଅନୁରୋଧ ପସନ୍ଦ କରିଛନ୍ତି ଏବଂ ଯାତ୍ରା କରିଛନ୍ତି"
, and_has_travelled: "।"
, please_find_revised_fare_estimate: "ଦୟାକରି ପୁନର୍ବିଚାର ଭଡା ଅନୁମାନ ଦେଖନ୍ତୁ। ରାତି ଚାର୍ଜ 1.5 ଗୁଣା ଦିନ ଚାର୍ଜର ହେବ।"
, fare_estimate: "ଭଡା ଅନୁମାନ"
, tip_selected: "ଟିପ୍ ଚୟନ କରାଯାଇଛି"
, add_a_tip_to_find_a_ride_quicker: "ଏକ ଟିପ୍ ଯୋଡିବା ପାଇଁ ଦ୍ରୁତ ରାଇଡ୍ ପାଇବେ!"
, it_seems_to_be_taking_longer_than_usual: "ଏହା ସାଧାରଣ ତୁଳନାରେ ଅଧିକ ସମୟ ନେଉଛି।"
, continue_search_with: "ଏହା ସହିତ ଖୋଜ ଅଗ୍ରଗତି କରନ୍ତୁ"
, continuing_search_with: "ଏହା ସହିତ ଖୋଜ ଅଗ୍ରଗତି କରୁଛି"
, searching_with: "ଏହା ସହିତ ଖୋଜିବା"
, the_driver_preferred_your_special_request_and_is_already_on_the_way_to_your_location: "ଡ୍ରାଇଭର ଆପଣଙ୍କର ବିଶେଷ ଅନୁରୋଧ ପସନ୍ଦ କରିଛନ୍ତି ଏବଂ ଆପଣଙ୍କ ସ୍ଥାନକୁ ଆସୁଛନ୍ତି।"
, driver_is_already_on_the_way_to_your_location: "ଡ୍ରାଇଭର ଆପଣଙ୍କ ସ୍ଥାନକୁ ଆସୁଛନ୍ତି।"
, allow_location_access: "ଅବସ୍ଥାନ ଅନୁମତି ଦିଅନ୍ତୁ"
, message_from_driver: "ଡ୍ରାଇଭରରୁ ସନ୍ଦେଶ"
, reply: "ପ୍ରତିକ୍ରିୟା"
, name_should_be_more_than_2_characters: "ନାମ ଦୁଇଟାରୁ ଅଧିକ ଅକ୍ଷରରେ ହେବା ଆବଶ୍ୟକ"
, this_field_is_required: "ଏହି ସ୍ଥାନ ଆବଶ୍ୟକ"
, email_exists_already: "ଇମେଲ୍ ପୂର୍ବରୁ ରହିଛି"
, okay_got_it: "ଠିକ ଅଛି, ବୁଝିଲି"
, call_namma_yatri_support: (\_ -> "ନମ୍ମା ଯାତ୍ରି ସମର୍ଥନ କୁ କଲ୍ କରନ୍ତୁ")
, call_112: "112 କୁ କଲ୍ କରନ୍ତୁ"
, call_emergency_centre: "ଆପତ୍କାଳୀନ କେନ୍ଦ୍ରକୁ କଲ୍ କରନ୍ତୁ"
, seats: "ଆସନ"
, driver_addition_limits_are_in_increments: "ଡ୍ରାଇଭର ଅତିରିକ୍ତ ମର୍ଯ୍ୟାଦା ଭାଗରେ ₹20 ରେ ରହିଛି"
, hatchback: "ହାଚବ୍ୟାକ୍"
, suv: "SUV"
, sedan: "ସେଡାନ"
, otp_page_has_been_expired_please_request_otp_again: "OTP ପୃଷ୍ଠା ସମାପ୍ତ ହୋଇଯାଇଛି, ଦୟାକରି ପୁନଃ ଅନୁରୋଧ କରନ୍ତୁ"
, otp_entering_limit_exhausted_please_try_again_later: "OTP ପ୍ରବେଶ ସୀମା ସମାପ୍ତ ହୋଇଯାଇଛି, କ୍ରିପାୟା ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, too_many_login_attempts_please_try_again_later: "ଅଧିକ ଲଗିନ୍ ଚେଷ୍ଟା, କ୍ରିପାୟା ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, something_went_wrong_please_try_again: "କିଛି ଭୁଲ୍ ହେଲା, ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, sorry_limit_exceeded_you_cant_add_any_more_favourites: "ମାଫ କରନ୍ତୁ, ସୀମା ଅତିକ୍ରମିତ। ଆପଣ ଅଧିକ ପ୍ରିୟତମ ଯୋଡିବାକୁ ପାରିବେ ନାହିଁ"
, cancellation_unsuccessfull_please_try_again: "ବାତିଲ ସଫଳ ହୋଇନି, ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, no_driver_available_at_the_moment_please_try_again: "ବର୍ତ୍ତମାନ କୌଣସି ଡ୍ରାଇଭର ଉପଲବ୍ଧ ନାହିଁ, କ୍ରିପାୟା ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, otp_for_the_jatri_sathi_zone_has_been_expired_please_try_looking_again: (\_ -> "ଜାତ୍ରୀ ସାଥୀ ଜୋନ୍ ପାଇଁ OTP ସମାପ୍ତ, ପୁନଃ ଯାତ୍ରା ବୁକ୍ କରନ୍ତୁ")
, no_contacts_found_on_the_device_to_be_added: "ଯୋଡିବାକୁ କୌଣସି ସମ୍ପର୍କ ମିଳିଲା ନାହିଁ"
, please_enable_contacts_permission_to_proceed: "ଅଗ୍ରଗତି କରିବାକୁ ସମ୍ପର୍କ ଅନୁମତି ସକ୍ରିୟ କରନ୍ତୁ"
, limit_reached_3_of_3_emergency_contacts_already_added: "ସୀମା ଅତିକ୍ରମିତ! 3 ରେ 3 ଆପତ୍କାଳୀନ ସମ୍ପର୍କ ଯୋଡାଯାଇଛି"
, invalid_contact_format: "ଅବୈଧ ସମ୍ପର୍କ ଫର୍ମାଟ"
, otp_resent_limit_exhausted_please_try_again_later: "OTP ପୁନଃ ପଠାଣା ସୀମା ସମାପ୍ତ, ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, rate_your_experience: "ଆପଣଙ୍କ ଅଭିଜ୍ଞତା କୁ ରେଟ କରନ୍ତୁ ✨"
, report_issue_: "ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ"
, done: "ସମାପ୍ତ"
, please_tell_us_what_went_wrong: "ଦୟାକରି କହନ୍ତୁ କ’ଣ ଭୁଲ୍ ହୋଇଛି"
, did_you_face_any_issue: "ଆପଣ କୌଣସି ସମସ୍ୟାର ସମ୍ମୁଖୀନ ହେଲେ କି?"
, we_noticed_your_ride_ended_away: "ଆମେ ଲକ୍ଷ୍ୟ କରୁଛୁ ଯେ ଆପଣଙ୍କର ଯାତ୍ରା ଗନ୍ତବ୍ୟରୁ ଅନ୍ୟ ସ୍ଥାନରେ ସମାପ୍ତ ହୋଇଛି।"
, get_callback_from_us: "ଆମ ପାଖରୁ ଏକ ଫେରା କଲ୍ ପାଇବେ"
, driver_was_not_ready_to_go: "ଡ୍ରାଇଭର ପ୍ରସ୍ଥାନ କରିବାକୁ ପ୍ରସ୍ତୁତ ନ ଥିଲା"
, asking_for_more_money: "ଡ୍ରାଇଭର ଅଧିକ ଧନ ମାଗୁଥିଲା"
, vehicle_broken: "ଯାନ ବିଗଡିଯାଇଛି"
, we_will_give_you_callback: "ଆମେ ଆପଣଙ୍କୁ 24 ଘଣ୍ଟା ଭିତରେ ଫେରା କଲ୍ କରିବୁ"
, your_issue_has_been_reported: "ଆପଣଙ୍କର ସମସ୍ୟା ସଫଳତାର ସହିତ ରିପୋର୍ଟ ହୋଇଛି"
, issue_report_already_exists: "ସମସ୍ୟା ରିପୋର୍ଟ ପୂର୍ବରୁ ରହିଛି"
, otp_resent_successfully: "OTP ସଫଳତାର ସହ ପୁନଃ ପଠାଯାଇଛି"
, description_should_be_more_than_10_alphabetic_characters: "ବିବରଣୀ 10 ଅକ୍ଷରରୁ ଅଧିକ ହେବା ଆବଶ୍ୟକ"
, it_seems_like_you_have_an_ongoing_ride_: "ଆପଣଙ୍କର ଏକ ଚାଲୁ ବୁକିଂ ଅଛି, ଦୟାକରି ଆପ୍କୁ ପୁନଃ ଆରମ୍ଭ କରନ୍ତୁ"
, incorrect_otp_please_try_again: "ଭୁଲ୍ OTP, ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ।"
, n_more_attempts_left: " ଅଧିକ ଚେଷ୍ଟା ବାକି ଅଛି"
, go_to_selected_pickup_spot: "ବାଛା ହୋଇଥିବା ପିକଅପ୍ ସ୍ଥାନକୁ ଯାଆନ୍ତୁ"
, go_to_selected_pickup_spot_as_autos_are_restricted: "ପିକଅପ୍ ସ୍ଥାନକୁ ଯାଆନ୍ତୁ କାରଣ ଏହି ସ୍ଥାନରେ ଅଟୋ ରୋଧିତ ଅଛି"
, unprofessional_driver: "ଅପ୍ରବୀଣ ଡ୍ରାଇଭର"
, rash_driving: "ଅସାବଧାନ ଡ୍ରାଇଭିଂ"
, driver_charged_more: "ଡ୍ରାଇଭର ଅଧିକ ଚାର୍ଜ ନେଲେ"
, uncomfortable_auto: "ଅସୁବିଧାଜନକ ଅଟୋ"
, uncomfortable_cab: "ଅସୁବିଧାଜନକ କ୍ୟାବ୍"
, trip_got_delayed: "ଯାତ୍ରା ବିଳମ୍ବିତ ହେଲା"
, felt_unsafe: "ଅନିରାପଦ ଲାଗୁଥିଲା"
, polite_driver: "ନମ୍ର ଡ୍ରାଇଭର"
, expert_driving: "ଦକ୍ଷ ଡ୍ରାଇଭିଂ"
, safe_ride: "ସୁରକ୍ଷିତ ଯାତ୍ରା"
, clean_auto: "ପରିଷ୍କାର ଅଟୋ"
, clean_cab: "ପରିଷ୍କାର କ୍ୟାବ୍"
, on_time: "ସମୟ ରେ"
, skilled_navigator: "ଦକ୍ଷ ନେଭିଗେଟର"
, rude_driver: "ଅଶୀଳ ଡ୍ରାଇଭର"
, too_many_calls: "ବହୁତ ଅଧିକ ଫୋନ"
, reckless_driving: "ଅଜାଣି ଚାଳନା"
, late_drop_off: "ବିଳମ୍ବିତ ଡ୍ରପ୍ ଅଫ୍"
, late_pick_up: "ବିଳମ୍ବିତ ପିକଅପ୍"
, poor_experience: "ଅଶୁଭ ସନ୍ଦର୍ଭ 😕"
, terrible_experience: "ଭୟଙ୍କର ସନ୍ଦର୍ଭ 😠"
, needs_improvement: "ସୁଧାରଣାର ଆବଶ୍ୟକ ଅଛି 😕"
, almost_perfect: "ପ୍ରାୟ ସଫଳ! 🙂"
, amazing: "ଅସାଧାରଣ!!! 🤩"
, asked_for_extra_fare: "ଅତିରିକ୍ତ ଭଡା ମାଗିଲେ"
, anything_that_you_would_like_to_tell_us: "ଆପଣଙ୍କର ମତାମତ ଅଛି କି? (ଇଚ୍ଛାନୁସାରେ)"
, please_wait: "ଦୟାକରି ପ୍ରତିକ୍ଷା କରନ୍ତୁ"
, platform_fee: "ମଞ୍ଚ ଶୁଳ୍କ"
, finding_quotes_text: "କ୍ୟାବ୍ସ ଖୋଜି ଚାଲିଛି"
, faster: "ଶୀଘ୍ରତର"
, new_: "ନୂତନ"
, sgst: "SGST"
, otp_expired: "OTP ସମାପ୍ତ"
, otp_expired_description: "ଆପଣଙ୍କର ରାଇଡ୍ OTP ସମାପ୍ତ ହୋଇଛି। ଏକ ନୂତନ ରାଇଡ୍ ବୁକ୍ କରନ୍ତୁ"
, platform_gst: "କର (GST)"
, misc_waiting_charge: "ପ୍ରତିକ୍ଷା ଚାର୍ଜସ୍"
, ac_taxi: "AC ଟ୍ୟାକ୍ସି"
, non_ac_taxi: "ନନ-AC ଟ୍ୟାକ୍ସି"
, get_otp_via_whatsapp: "WhatsApp ଦ୍ୱାରା OTP ପାଇବା"
, or: "କିମ୍ବା"
, helps_driver_confirm_its_you: "(ଏହା ଡ୍ରାଇଭର କୁ ନିଶ୍ଚିତ କରେ ଯେ ଏହା ଆପଣ)"
, lets_get_you_trip_ready: "ଆପଣଙ୍କ ଯାତ୍ରା ପ୍ରସ୍ତୁତ କରନ୍ତୁ!"
, got_an_otp: "ଏକ OTP ମିଳିଲା କି?"
, just_one_last_thing: "ମାତ୍ର ଏକ ଶେଷ ଜିନିଷ"
, your_feedback_helps_us: (\appName -> "ଆପଣଙ୍କ ମତାମତ ଆମକୁ " <> appName <> " ଅନୁଭବ କୁ ସୁଧାରିବାରେ ସହାୟକ ହୋଇଛି")
, toll_charges_will_be_extra: "ଟୋଲ୍ ଚାର୍ଜସ୍ ଅତିରିକ୍ତ ହେବ"
, auto_rickshaw: "ଅଟୋ ରିକ୍ଶା"
, cabs_available: "କ୍ୟାବ୍ସ ଉପଲବ୍ଧ"
, pi_pointer_1: "ଡ୍ରାଇଭର ଆପଣଙ୍କ ସଠିକ୍ ଅବସ୍ଥାନରେ ପିକଅପ୍ କରିବାକୁ ପ୍ରୋତ୍ସାହିତ ହେବେ।"
, pi_pointer_2: "ଡ୍ରାଇଭର ଆପଣଙ୍କ ଚଳନଶୀଳ ଉପକରଣରେ ସହାୟତା ପ୍ରଦାନ କରିବାକୁ ପ୍ରୋତ୍ସାହିତ ହେବେ।"
, vi_pointer_1: "ଡ୍ରାଇଭର ଫୋନ କରିବାକୁ ପ୍ରୋତ୍ସାହିତ ହେବେ।"
, vi_pointer_2: "ଡ୍ରାଇଭର ପିକଅପ୍ ସ୍ଥାନରେ ଥିବାବେଳେ ହର୍ନ୍ ବାଜେଇବାକୁ ପ୍ରୋତ୍ସାହିତ ହେବେ।"
, hi_pointer_1: "ଡ୍ରାଇଭର ଫୋନ କରିବା ବଦଳରେ ସନ୍ଦେଶ ପଠେଇବେ।"
, hi_pointer_2: "ଡ୍ରାଇଭର ପିକଅପ୍ ସ୍ଥାନରେ ଥିବାବେଳେ ଆପଣଙ୍କୁ ସନ୍ଦେଶ ପଠେଇବେ।"
, did_the_driver_offer_assistance: "ଡ୍ରାଇଭର ସହାୟତା ମାଗିଥିଲା କି?"
, was_the_driver_understanding_of_your_needs: "ଆପଣଙ୍କର ଆବଶ୍ୟକତାକୁ ଡ୍ରାଇଭର ବୁଝିଥିଲା କି?"
, general_disability_description: "ଡ୍ରାଇଭର ଆପଣଙ୍କର ଆବଶ୍ୟକତା ଓ ଅନୁରୋଧକୁ ସାହାଯ୍ୟ କରିବାରେ ସେନ୍ସିଟାଇଜ୍ ହେବେ।"
, accessibility_text: (\_ -> "ନମ୍ମା ଯାତ୍ରି, ଆପଣଙ୍କ ପାଇଁ ଏବେ ବିଶେଷତା କରାଯାଇଛି!")
, to_cater_your_specific_needs: (\_ -> "ଆପଣଙ୍କର ବିଶେଷ ଆବଶ୍ୟକତା ପାଇଁ, ଆମେ କିଛି ବୈଶିଷ୍ଟ୍ୟକୁ କଷ୍ଟମାଇଜ୍ କରିଛୁ।")
, special_assistance: "ବିଶେଷ ସହାୟତା"
, select_the_condition_that_is_applicable: "ଆପଣଙ୍କୁ ପ୍ରୟୋଜନୀୟ ସ୍ଥିତି ବାଛନ୍ତୁ (RPWD ଆଇନ 2016 ଅନୁଯାୟୀ)"
, disability_claimer_text: "ଚାଲୁ ରଖିବାରେ, ଆପଣ RPWD ଆଇନ 2016 ଅନୁସାରେ ଜଣେ ଅସକ୍ଷମ ଥିବା ସ୍ଥିତିକୁ ଘୋଷଣା କରୁଛନ୍ତି"
, are_you_a_person_with_disability: "ଆପଣ ଅସକ୍ଷମ ଥିବା ବ୍ୟକ୍ତି ନା?"
, do_you_neeed_special_assistance: "ଆପଣଙ୍କୁ ବିଶେଷ ସହାୟତା ଆବଶ୍ୟକ ନା?"
, assistance_required: "ସହାୟତା ଆବଶ୍ୟକ (ଅସକ୍ଷମ ବ୍ୟକ୍ତି)"
, no_disability: "କୌଣସି ଅସକ୍ଷମ ନାହିଁ"
, learn_how_text: (\_ -> "ନମ୍ମା ଯାତ୍ରି କିପରି ଆପଣଙ୍କ ଆବଶ୍ୟକତା ପାଇଁ ରଖିଛି ସିଖନ୍ତୁ")
, update_profile: "ପ୍ରୋଫାଇଲ ଅପଡେଟ୍ କରନ୍ତୁ"
, now_get_assisted_rides: "ଏବେ ଯଦି ଆପଣ ଅସକ୍ଷମ ହେଲେ ସହାୟକ ରାଇଡ୍ ପାଇବେ"
, sent_otp_via_whatsapp: "WhatsApp ଦ୍ୱାରା OTP ପଠାଯାଇଛି"
, sent_otp_via_sms: "SMS ଦ୍ୱାରା OTP ପଠାଯାଇଛି"
, enable_location_permission_to: "ରାଇଡ୍ ଖୋଜିବା ପାଇଁ ଅବସ୍ଥାନ ଅନୁମତି ସକ୍ରିୟ କରନ୍ତୁ"
, ac_cab: "AC କ୍ୟାବ୍"
, ac_suv: "AC SUV"
, ride_type: "ରାଇଡ୍ ପ୍ରକାର"
, ernakulam_limit_charge: "ଏର୍ଣ୍ଣାକୁଲମ ମର୍ୟାଦା ବାହାରେ ଥାକିଲେ ଭଡା 1.5x ହେବ"
, select_location_on_map: "ମାନଚିତ୍ରରେ ଅବସ୍ଥାନ ବାଛନ୍ତୁ"
, download_driver_receipt: "ଡ୍ରାଇଭର ରସିଦ ଡାଉନଲୋଡ୍ କରନ୍ତୁ"
, view_driver_receipt: "ଡ୍ରାଇଭର ରସିଦ ଦେଖନ୍ତୁ"
, driver_receipt: "ଡ୍ରାଇଭର ରସିଦ"
, help: "ସହାୟତା"
, fare_info_text: (\_ -> "")
, please_enable_location_permission: (\_ -> "ଦୟାକରି ସେଟିଂସ୍ ଆପରେ ଅବସ୍ଥାନ ଅନୁମତି ସକ୍ରିୟ କରନ୍ତୁ")
, educational_pop_up_slide_1_title: "ଆମେ ସମସ୍ତ ବ୍ୟବହାରକାରୀକୁ ସମାନ ଅନୁଭବ ପ୍ରଦାନ କରିବାକୁ ଚେଷ୍ଟା କରୁଛୁ।"
, educational_pop_up_slide_2_title: "ଅଧିକାଂଶ ଦୃଷ୍ଟି ସମସ୍ୟା ସହିତ ବ୍ୟବହାରକାରୀଙ୍କ ପାଇଁ"
, educational_pop_up_slide_3_title: "ଅଧିକାଂଶ ଶ୍ରବଣ ସମସ୍ୟା ସହିତ ବ୍ୟବହାରକାରୀଙ୍କ ପାଇଁ"
, educational_pop_up_slide_4_title: "ଚଳନଶୀଳ ଅସକ୍ଷମ ସହିତ ବ୍ୟବହାରକାରୀଙ୍କ ପାଇଁ"
, educational_pop_up_slide_5_title: "ଅନ୍ୟ ସହିତ ବିଶେଷ ଆବଶ୍ୟକତାରେ ବ୍ୟବହାରକାରୀଙ୍କ ପାଇଁ"
, educational_pop_up_slide_1_subtitle: ""
, educational_pop_up_slide_2_subtitle: "• ଡ୍ରାଇଭର ଫୋନ କରିବେ <br>   ଓ ସହାଯ୍ୟ ପ୍ରଦାନ କରିବେ <br>   ସମୟରେ ସହାୟକ।"
, educational_pop_up_slide_3_subtitle: "• ଡ୍ରାଇଭର ସନ୍ଦେଶ ପଠେଇବା <br>   ଏବଂ ସହାୟକ ହେବେ। <br>"
, educational_pop_up_slide_4_subtitle: "• ପିକ ଅପ୍ କୁ ଯିବା <br>   ତାଙ୍କ ସହାୟକ ସାଜାଯାଇଛି <br>  "
, educational_pop_up_slide_5_subtitle: "• ଆପଣଙ୍କର ସମସ୍ତର ଆବଶ୍ୟକତା ପୂରା! <br>   ସହାୟକ."
, inclusive_and_accessible: "ସମାବେଶୀକ ଏବଂ ଅନୁପାର୍କକ, ସମସ୍ତଙ୍କ ପାଇଁ!"
, my_tickets: "ମୋ ଟିକେଟସ୍"
, you_can_book_tickets_to_the_zoo_by_clicking_the_button: "ଟିକେଟ୍ ବୁକ୍ କରି ପରିସରରେ ପହଞ୍ଚନ୍ତୁ"
, something_went_wrong_try_again_later: "କିଛି ଭୁଲ୍ ହେଲା, ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ"
, you_seem_to_be_far_from_pick_up: "ଆପଣଙ୍କ ପିକଅପ୍ ଦୂରୀ ଥିଲେ!"
, are_you_sure_you_want_to_proceed_with_the_booking: "ନିଶ୍ଚିତ ନା ଆଗକୁ"
, pay_driver_using_wallet: ""
, charges_applicable_after_3_mins: "ମିନିଟରେ ଚାର୍ଜସ୍"
, reaching_your_destination_in_: "ଗନ୍ତବ୍ୟ"
, waiting_at_pickup: "ପିକଅପ୍"
, pickup: "ପିକଅପ୍"
, pay_by_cash_or_upi: "UPI"
, you_will_pay_for_every_minute: (\freeMinutes chargePerMin -> "Waiting Charge is zero for the first " <> freeMinutes <> " minutes. Waiting Charge of "<> chargePerMin <>"  will be applicable thereafter.")
, wait_timer: "ପ୍ରତିକ୍ଷା"
, how_long_driver_waited_for_pickup: "ପିକଅପ୍"
, chat_with: "ଚାଟ୍"
, namma_safety: "ସୁରକ୍ଷା"
, quick: "ଶୀଘ୍ର"
, chats: "ଚାଟସ୍"
, replies: "ଜବାବ"
, you_sent: "ପଠାଇଛନ୍ତି"
, message_your_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭରକୁ ସନ୍ଦେଶ ପଠାନ୍ତୁ?"
, check_in_with_your_driver: "ଏକ ଶୀଘ୍ର ସନ୍ଦେଶରେ ଆପଣଙ୍କ ଡ୍ରାଇଭର ସହିତ ଯାଞ୍ଚ କରନ୍ତୁ"
, check_in_with_your_em: (\name -> "ଏକ ଶୀଘ୍ର ସନ୍ଦେଶରେ " <> name <> " ସହିତ ଯାଞ୍ଚ କରନ୍ତୁ")
, track_on_google_maps: "ସଜୀବ ଟ୍ରାକିଂ"
, otp_expire_timer: "OTP ସମାପ୍ତ ସମୟ"
, shows_for_how_long_your_otp_: "ଆପଣଙ୍କର OTP କେତେ ସମୟ ପର୍ଯ୍ୟନ୍ତ ମାନ୍ୟ ରହିବାକୁ ଜଣାଇ ଦିଏ।"
, if_your_otp_expires_: "ଯଦି ଆପଣଙ୍କର OTP ସମାପ୍ତ ହୁଏ, ଆପଣକୁ ପୁନଃ ବୁକ୍ କରିବାକୁ ପଡ଼ିବ।"
, you_have_reached_destination: "ଆପଣ ଆପଣଙ୍କ ଗନ୍ତବ୍ୟ ସ୍ଥାନକୁ ପହଞ୍ଚିଛନ୍ତି"
, places_you_might_like_to_go_to: "ଆପଣ ଯିବାକୁ ପସନ୍ଦ କରିପାରନ୍ତିବା ସ୍ଥାନଗୁଡ଼ିକ।"
, discover_awesome_spots_tailored_just_for_you: "କେବଳ ଆପଣଙ୍କ ପାଇଁ ଏକ ଅସାଧାରଣ ସ୍ଥାନ ଖୋଜନ୍ତୁ!"
, suggested_destination: "ପ୍ରସ୍ତାବିତ ଗନ୍ତବ୍ୟ"
, recent_rides: "ସମ୍ପ୍ରତିକ ରାଇଡ୍ଗୁଡ଼ିକ"
, one_click_booking_for_your_favourite_journeys: "ଆପଣଙ୍କ ପସନ୍ଦର ଯାତ୍ରା ପାଇଁ 1 କ୍ଲିକ୍ ବୁକିଂ!"
, view_more: "ଅଧିକ ଦେଖନ୍ତୁ"
, view_less: "କମ୍ ଦେଖନ୍ତୁ"
, have_a_refferal: "ଆପଣଙ୍କ ପାଖରେ କୌଣସି ରେଫରାଲ ଅଛି କି?"
, your_suggested_destinations_and_recent_rides_will_appear_here: "ଆପଣଙ୍କ ପ୍ରସ୍ତାବିତ ଗନ୍ତବ୍ୟ ଏବଂ ସମ୍ପ୍ରତିକ ଯାତ୍ରାଗୁଡ଼ିକ ଏଠାରେ ପ୍ରଦର୍ଶିତ ହେବ।"
, welcome_to_namma_yatri_: "ନମ୍ମା ଯାତ୍ରିରେ ସ୍ୱାଗତ!"
, book_and_move: "ବୁକ୍ କରନ୍ତୁ ଏବଂ ଚାଲନ୍ତୁ,"
, anywhere_in_the_city: "ସହରର ଯେକୌଣସି ସ୍ଥାନକୁ"
, checkout_our_live_stats: "ଆମ ସଜୀବ ପରିସଂଖ୍ୟାନ ଦେଖନ୍ତୁ"
, most_loved_app: (\_ -> "ସର୍ବାଧିକ ପସନ୍ଦର ❤️ ଜିରୋ କମିଶନ ଆପ୍")
, pickup_: "ପିକଅପ୍: "
, past_searches: "ପୂର୍ବ ସନ୍ଧାନ"
, search_results: "ଖୋଜିବାର ଫଳାଫଳ"
, edit_destination: "ଗନ୍ତବ୍ୟ ସମ୍ପାଦନ କରନ୍ତୁ"
, requesting_ride_in: "ରାଇଡ୍ ଅନୁରୋଧ କରିଛି"
, confirm_fare: "ଭଡା ନିଶ୍ଚିତ କରନ୍ତୁ"
, request_change: "ପରିବର୍ତ୍ତନ ଅନୁରୋଧ କରନ୍ତୁ"
, requesting_ride: "ରାଇଡ୍ ଅନୁରୋଧ କରୁଛି"
, tap_here_to_stop_auto_requesting: "ଅଟୋ ଅନୁରୋଧ ବନ୍ଦ କରିବାକୁ ଏଠାରେ ଟ୍ୟାପ୍ କରନ୍ତୁ"
, powered_by: "ଉପରେ ଚାଲୁଛି"
, book_your_ride: "ଆପଣଙ୍କର ରାଇଡ୍ ବୁକ୍ କରନ୍ତୁ"
, fare_updated_with_charges: "ଭଡା ପ୍ରୟାସନୀୟ ପ୍ରତିକ୍ଷା ଚାର୍ଜ ସହିତ ଅଦ୍ୟତନ କରାଯାଇଛି"
, fare_updated_with_shorter_dist: "ଆପଣଙ୍କ ଭଡାକୁ ଅପଡେଟ୍ କରାଯାଇଛି କାରଣ ଆପଣଙ୍କର ଯାତ୍ରା {} km ଛୋଟରେ ଥିଲା"
, fare_updated_with_longer_dist: "ଆପଣଙ୍କ ଭଡାକୁ ଅପଡେଟ୍ କରାଯାଇଛି କାରଣ ଆପଣଙ୍କର ଯାତ୍ରା {} km ବଡ଼ ଥିଲା"
, fare_updated_with_charges_shorter_dist: "ଆପଣଙ୍କ ଭଡା ଅପଡେଟ୍ କରାଯାଇଛି ଯାତ୍ରା {} km କମ୍ ଥିଲା ଏବଂ ପ୍ରତିକ୍ଷା ଚାର୍ଜ ଲାଗୁ ହୋଇଛି"
, fare_updated_with_charges_longer_dist: "ଆପଣଙ୍କ ଭଡା ଅପଡେଟ୍ କରାଯାଇଛି ଯାତ୍ରା {} km ବଡ଼ ଥିଲା ଏବଂ ପ୍ରତିକ୍ଷା ଚାର୍ଜ ଲାଗୁ ହୋଇଛି"
, start_typing_to_search_places: "ସ୍ଥାନ ଖୋଜିବାକୁ ଟାଇପ୍ କରିବା ଆରମ୍ଭ କରନ୍ତୁ"
, did_you_have_a_safe_journey: "ଆପଣ ଏକ ସୁରକ୍ଷିତ ଯାତ୍ରା କଲେ କି?"
, trip_was_safe_and_worry_free: "ଆମେ ଆଶା କରୁଛୁ ଯେ ଆପଣଙ୍କ ଯାତ୍ରା ସୁରକ୍ଷିତ ଏବଂ ଚିନ୍ତାମୁକ୍ତ ଥିଲା।"
, driver_behaved_inappropriately: "ଡ୍ରାଇଭର ଅନୁଚିତ ଆଚରଣ କରିଥିଲେ"
, i_did_not_feel_safe: "ମୁଁ ସୁରକ୍ଷିତ ଲାଗୁ ନଥିଲା"
, looking_for_another_ride: "ଅନ୍ୟ ରାଇଡ୍ ଖୋଜୁଛି..."
, the_ride_had_been_cancelled_we_are_finding_you_another: "ରାଇଡ୍ ବାତିଲ ହୋଇଥିଲା, ଆମେ ଆପଣଙ୍କ ପାଇଁ ଅନ୍ୟ ଖୋଜୁଛୁ"
, enjoy_the_ride: "ଆପଣଙ୍କ ଗନ୍ତବ୍ୟ ସ୍ଥାନକୁ ଯାତ୍ରାର ସମ୍ଭାବନା ଭୋଗ କରନ୍ତୁ!"
, ride_started: "ରାଇଡ୍ ଆରମ୍ଭ ହେଲା"
, one_click: "1 କ୍ଲିକ୍ ବୁକିଂ"
, smart: "ସ୍ମାର୍ଟ"
, not_serviceable: "ସେବା ଅର୍ହତା ନାହିଁ"
, we_are_not_live_in_your_area: "ଆମେ ଆପଣଙ୍କ ଅଞ୍ଚଳରେ ଏଯାବରେ ସେବା ଦେଉନାହିଁ! ଆପଣ ରାଇଡ୍ ଇତିହାସ ଏବଂ ଅନ୍ୟ ଆୟୋଜନାଗୁଡ଼ିକ ଉପରି ଡେକ୍ ମେନୁରୁ ପ୍ରବେଶ କରିପାରିବେ।"
, account_blocked: "ଅକାଉଣ୍ଟ ବନ୍ଦ ହୋଇଛି"
, you_can_still_access: "ଆପଣ ପୂର୍ବ ରାଇଡ୍ ଏବଂ ଅନ୍ୟ ବିକଳ୍ପଗୁଡ଼ିକୁ ପୃଷ୍ଠା ମେନୁରୁ ପ୍ରବେଶ କରିପାରିବେ"
, facing_problem_with_app: "ଆପ୍ ସହିତ ସମସ୍ୟା ସମ୍ମୁଖୀନ ହେଉଛନ୍ତି କି?"
, tap_here_to_report: "<u>ସମସ୍ୟା ରିପୋର୍ଟ କରିବାକୁ ଏଠାରେ ଟାପ୍ କରନ୍ତୁ</u>"
, confirm_your_ride: "ଆପଣଙ୍କର ରାଇଡ୍ ନିଶ୍ଚିତ କରନ୍ତୁ"
, ride_scheduled: "ରାଇଡ୍ ତାଲିକାଭୁକ୍ତ"
, ride_starts_on: "ରାଇଡ୍ ଆରମ୍ଭ ହେବ"
, rental_package: "ଭାଡା ପ୍ୟାକେଜ୍"
, go_home: "ଘରକୁ ଯାଆନ୍ତୁ"
, cancel_rental_booking: "ଭାଡା ବୁକିଂ ବାତିଲ କରନ୍ତୁ"
, add_first_stop: "ପ୍ରଥମ ଥାମିବା ସ୍ଥାନ ଯୋଡନ୍ତୁ"
, driver_will_be_assigned_minutes_before_starting_the_ride: "ରାଇଡ୍ ଆରମ୍ଭ ପୂର୍ବରୁ {} ମିନିଟ୍ ପର୍ଯ୍ୟନ୍ତ ଡ୍ରାଇଭର ନିଯୁକ୍ତ ହେବେ"
, your_reports: "ଆପଣଙ୍କ ରିପୋର୍ଟଗୁଡ଼ିକ"
, view: "ଦେଖନ୍ତୁ"
, issue_no: "ସମସ୍ୟା ନମ୍ବର"
, add_voice_note: "ଭଉସ ନୋଟ୍ ଯୋଡନ୍ତୁ"
, voice_note: "ଭଉସ ନୋଟ୍"
, submit_issue_details: "ସମସ୍ୟା ବିବରଣୀ ପଠାନ୍ତୁ"
, image_preview: "ଛବି ପ୍ରିଭ୍ୟୁ"
, added_images: "ଯୋଡାଯାଇଥିବା ଛବି"
, no_images_added: "କୌଣସି ଛବି ଯୋଡାଯାଇନାହିଁ"
, i_dont_know_which_ride: "ମୁଁ କୁହି ପାରୁନାହିଁ କେଉଁ ରାଇଡ୍"
, added_voice_note: "ଭଉସ ନୋଟ୍ ଯୋଡାଗଲା"
, no_voice_note_added: "କୌଣସି ଭଉସ ନୋଟ୍ ଯୋଡାଯାଇନାହିଁ"
, call_driver_title: "ଡ୍ରାଇଭରକୁ କଲ୍ କରନ୍ତୁ?"
, call_support_title: "ସମର୍ଥନକୁ କଲ୍ କରନ୍ତୁ?"
, call_driver_description: "ଆପଣ ଡ୍ରାଇଭରକୁ କଲ୍ କରିବାକୁ ଯାଉଛନ୍ତି। ଆଗକୁ ବଢିବାକୁ ଚାହୁଁଛନ୍ତି କି?"
, add_image: "ଛବି ଯୋଡନ୍ତୁ"
, add_another: "ଅନ୍ୟକୁ ଯୋଡନ୍ତୁ"
, images: "ଛବିଗୁଡ଼ିକ"
, issue_submitted_text: "ଅପେକ୍ଷା କରନ୍ତୁ! ଆମେ ଆପଣଙ୍କ ସମସ୍ୟାକୁ ସମାଧାନ କରିବାକୁ କାର୍ଯ୍ୟ କରୁଛୁ"
, issue_resolved_text: "ସମସ୍ୟା ସମାଧାନ ହୋଇଛି!"
, choose_an_option: "ଚାଲିବାକୁ ଏକ ବିକଳ୍ପ ବାଛନ୍ତୁ"
, issue_marked_as_resolved: "ସମସ୍ୟାକୁ ସମାଧାନ ଭାବରେ ଚିହ୍ନିତ କରାଗଲା!"
, still_having_issue: "ଆପଣଙ୍କୁ ଏପରି ଥାକିବା ସମସ୍ୟା ଅଛି କି?"
, image: "ଛବି"
, record_voice_note: "ଭଉସ ନୋଟ୍ ରେକର୍ଡ କରନ୍ତୁ"
, cancel_button: "ବାତିଲ"
, max_images: "ଅଧିକତମ 3 ଛବି ଅପଲୋଡ୍ କରାଯାଇପାରେ"
, select_a_ride_to_report: "ରିପୋର୍ଟ ଆପଣଙ୍କରେ ଜଣା ପାଇଁ ରାଇଡ୍ ବାଛନ୍ତୁ"
, ride_related_issue_page_name: "ରାଇଡ୍ ସମ୍ବନ୍ଧିତ ସମସ୍ୟା"
, app_related_issue_page_name: "ଆପ୍ ସମ୍ବନ୍ଧିତ ସମସ୍ୟା"
, driver_related_issue_page_name: "ଡ୍ରାଇଭର ସମ୍ବନ୍ଧିତ ସମସ୍ୟା"
, lost_and_found_issue_page_name: "ହାରାଇଥିବା ବସ୍ତୁର ସମସ୍ୟା"
, years_ago: "ବର୍ଷ ପୂର୍ବେ"
, months_ago: "ମାସ ପୂର୍ବେ"
, days_ago: "ଦିନ ପୂର୍ବେ"
, hours_ago: "ଘଣ୍ଟା ପୂର୍ବେ"
, min_ago: "ମିନିଟ୍ ପୂର୍ବେ"
, sec_ago: "ସେକେଣ୍ଡ ପୂର୍ବେ"
, reported: "ରିପୋର୍ଟ କରାଯାଇଛି"
, resolved: "ସମାଧାନ"
, resolved_issues: "ସମାଧାନ ସମସ୍ୟାଗୁଡିକ"
, reported_issues: "ରିପୋର୍ଟ କରାଯାଇଥିବା ସମସ୍ୟାଗୁଡିକ"
, sos_issue_page_name: "SOS ସମସ୍ୟା"
, fare_discrepancies_issue_page_name: "ଭଡା ସମସ୍ୟା"
, payment_related_issue_page_name: "ପେମେଣ୍ଟ ସମସ୍ୟା"
, account_related_issue_page_name: "ଅକାଉଣ୍ଟ ସମସ୍ୟା"
, payment_and_fare_related_issue_page_name: "ପେମେଣ୍ଟ ଏବଂ ଭଡା ସମସ୍ୟା"
, vehicle_related_issue_page_name: "ଯାନ ସମସ୍ୟା"
, issue: "ସମସ୍ୟା"
, other_issues: "ଅନ୍ୟ ସମସ୍ୟାଗୁଡ଼ିକ"
, report_issue_chat_placeholder: (\_ -> "ଆପଣଙ୍କ ସମସ୍ୟା ବିବରଣୀ ପ୍ରଦାନ କରନ୍ତୁ।")
, call_support_description: (\_ -> "ଆପଣ ସମର୍ଥନ ଦଳକୁ ଫୋନ କରିବାକୁ ଯାଉଛନ୍ତି। ଆଗକୁ ବଢ଼ିବାକୁ ଚାହୁଁଛନ୍ତି କି?")
, cant_find_option: "ବିକଳ୍ପ ପାଇପାରିଲା ନାହିଁ"
, need_help: "ସହାୟତା ଆବଶ୍ୟକ?"
, safety_issue_page_name: "ସୁରକ୍ଷା ସମ୍ବନ୍ଧିତ ସମସ୍ୟା"
, we_hope_the_issue_is_resolved: (\_ -> "ଆମେ ଆଶା କରୁଛୁ ଯେ ସମସ୍ୟା ସମାଧାନ ହେଇଛି!")
, please_select_the_ride_to_call_driver: "ଡ୍ରାଇଭରକୁ କଲ୍ କରିବାକୁ ରାଇଡ୍ ଚୟନ କରନ୍ତୁ"
, add_image_s: "ଛବି ଯୋଡନ୍ତୁ"
, already_have_an_active_ride: "ଆପଣଙ୍କର ଏକ ସକ୍ରିୟ ରାଇଡ୍ ରହିଛି"
, confirm_stop_location: "ଥମିବା ସ୍ଥାନକୁ ସଂପାଦନ କରନ୍ତୁ"
, confirm_drop: "ଡ୍ରପ୍ ସଂପାଦନ କରନ୍ତୁ"
, book_metro_with_ny_now: "ନମ୍ମା ଯାତ୍ରି ସହିତ ମେଟ୍ରୋ ଟିକେଟ୍ ବୁକ୍ କରନ୍ତୁ!"
, complete_your_namma_safety_setup_for_safe_ride_experience: "ସୁରକ୍ଷିତ ଯାତ୍ରା ଅଭିଜ୍ଞତା ପାଇଁ ସୁରକ୍ଷା ମୋଡ୍ ସେଟଅପ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ"
, setup_now: "ଏବେ ସେଟ୍ କରନ୍ତୁ"
, learn_more: "ଅଧିକ ଶିଖନ୍ତୁ"
, learn_about_namma_safety: "ସୁରକ୍ଷା ବିଷୟରେ ଜାଣନ୍ତୁ"
, learn_about_safety_mode: "ସୁରକ୍ଷା ମୋଡ୍ ବିଷୟରେ ଜାଣନ୍ତୁ"
, namma_safety_will_enable_access: "ସୁରକ୍ଷା ମୋଡ୍ ଯାତ୍ରା ବେଳେ ଏହି ବୈଶିଷ୍ଟ୍ୟଗୁଡିକର ଅନୁମତି ଦେବାକୁ ସକ୍ରିୟ ହେବ!"
, activate_namma_safety_will_enable_access: "ସୁରକ୍ଷା ମୋଡ୍ ସକ୍ରିୟ କରିବା ସହିତ ଏହି କାର୍ଯ୍ୟଗୁଡିକ କରାଯାଇବ"
, edit_actions: "କାର୍ଯ୍ୟଗୁଡିକ ସମ୍ପାଦନ କରନ୍ତୁ"
, emergency_actions: "ଆପତ୍କାଳୀନ କାର୍ଯ୍ୟଗୁଡିକ"
, when_you_start_emergency_sos: "ଯେତେବେଳେ ଆପଣ ସୁରକ୍ଷା ମୋଡ୍ ସକ୍ରିୟ କରିବେ, ଆପଣଙ୍କ ଆପ୍ ନିମ୍ନ କାର୍ଯ୍ୟଗୁଡିକ କରିବ"
, emergency_sharing_with_contacts: "SOS ବେଳେ ଆପତ୍କାଳୀନ ସମ୍ପର୍କ ଏବଂ ଅଟୋ କଲ୍"
, sharing_with: "ଏହା ସହିତ ସେୟାର୍ କରିବା:"
, add_a_contact: "ଏକ ସମ୍ପର୍କ ଯୋଡନ୍ତୁ"
, to_ensure_safety_users_should: "ସୁରକ୍ଷା ସୁନିଶ୍ଚିତ କରିବା ପାଇଁ, ବ୍ୟବହାରକାରୀମାନେ ଏହା ଅନୁସରଣ କରିବା ଉଚିତ:"
, about_sos_desc: "ଦୟାକରି ସୁରକ୍ଷା ମୋଡ୍ର ଗୁରୁତ୍ୱକୁ ବୁଝନ୍ତୁ। ଗୁରୁତ୍ତ୍ୱ ନଥିବା ସ୍ଥିତିରେ, ଦୟାକରି <b>ସହାୟତା ଓ ସମର୍ଥନ</b> ବିଭାଗକୁ ବ୍ୟବହାର କରି ଏକ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ।"
, few_examples_of_sos_situations: "କିଛି ଆପତ୍କାଳୀନ ସ୍ଥିତିର ଉଦାହରଣ"
, things_to_do_during_sos_situation: "ଆପତ୍କାଳୀନ ସ୍ଥିତି ବେଳେ କରିବାକୁ ଯୋଗ୍ୟ କିଛି କାର୍ଯ୍ୟଗୁଡିକ"
, emergency_request_sent: "ଆପତ୍କାଳୀନ ଅନୁରୋଧ ପଠାଯାଇଛି!"
, sos_triggered_desc: "ଦୟାକରି ଶାନ୍ତ ରହନ୍ତୁ, ଆପଣଙ୍କର ସଜୀବ ଅବସ୍ଥାନ ଆପତ୍କାଳୀନ ସମ୍ପର୍କଗୁଡିକ ସହିତ ସେୟାର୍ ହେଉଛି।"
, test_emergency_request_sent: "ପରୀକ୍ଷା ଆପତ୍କାଳୀନ ଅନୁରୋଧ ପଠାଯାଇଛି!"
, test_sos_triggered_desc: "ଏକ ବାସ୍ତବ ସ୍ଥିତିରେ, ଆପଣଙ୍କର ଅବସ୍ଥାନ ଆପତ୍କାଳୀନ ସମ୍ପର୍କ ସହିତ ସେୟାର୍ ହେବ।"
, sos_actions: "SOS କାର୍ଯ୍ୟଗୁଡିକ"
, call_police: "ପୋଲିସକୁ\nକଲ୍ କରନ୍ତୁ"
, record_video: "ଭିଡିଓ ରେକର୍ଡ୍ କରନ୍ତୁ"
, stop_and_share_recording: "ରେକର୍ଡ୍ ଥମାନ୍ତୁ ଏବଂ ସେୟାର୍ କରନ୍ତୁ"
, cancel_sharing: "ସେୟାର୍ ବାତିଲ କରନ୍ତୁ"
, start_recording: "ରେକର୍ଡିଂ ଆରମ୍ଭ କରନ୍ତୁ"
, sharing_the_video_in: "ଭିଡିଓ ସେୟାର୍ କରିବାରେ...."
, emergency_info_shared: "ଆପତ୍କାଳୀନ ତଥ୍ୟ ସେୟାର୍ ହୋଇଛି!"
, emergency_info_shared_action: "ଆମ ସମର୍ଥନ ଦଳ ଆପଣଙ୍କ ଅବସ୍ଥାନ ଏବଂ ଭିଡିଓ ପାଇଛି। ଗୁରୁତ୍ତ୍ୱ ଥିବାବେଳେ ପୋଲିସକୁ ଅନୁମୋଦନ କରାଯିବ ଏବଂ ଯୋଗ୍ୟ କାର୍ଯ୍ୟ ଗ୍ରହଣ କରାଯିବ।"
, emergency_info_shared_action_police: "ପୋଲିସ ଅଧିକାରୀମାନେ ଆପଣଙ୍କ ଅବସ୍ଥାନ ଏବଂ ଭିଡିଓ ଗ୍ରହଣ କରିଛନ୍ତି। ସେମାନେ ଆପଣଙ୍କ ସହିତ ଦ୍ରୁତ ସମ୍ପର୍କ କରିବେ ଏବଂ ଆପତ୍କାଳୀନ କାର୍ଯ୍ୟ ଗ୍ରହଣ କରିବେ।"
, set_up_your_personal_safety_settings: "ଆପଣଙ୍କ ବ୍ୟକ୍ତିଗତ ସୁରକ୍ଷା ସେଟିଂସ୍ ସେଟଅପ୍ କରନ୍ତୁ"
, activate_live_video_recording_features: "ସଜୀବ ଭିଡିଓ ରେକର୍ଡିଂ ବୈଶିଷ୍ଟ୍ୟକୁ ସକ୍ରିୟ କରନ୍ତୁ"
, choose_responsive_contacts: "ଆପଣଙ୍କ ଯାତ୍ରା ପାଇଁ ସଂଯୋଗୀ ସମ୍ପର୍କ ବାଛିବାକୁ ଆମ ସୁପାରିଶ ରହିଛି, ଯେପରିକି ଏକ ସ୍ଥାନୀୟ ଅଭିଭାବକ କିମ୍ବା ସହରରେ ଥିବା ଗୋଟିଏ ସାଙ୍ଗ"
, share_location_and_ride_details_emergency_contact: "ଆପଣଙ୍କର ଅବସ୍ଥାନ ଏବଂ ଯାତ୍ରା ବିବରଣୀ ଆପତ୍କାଳୀନ ସମ୍ପର୍କରେ ସେୟାର୍ କରନ୍ତୁ"
, namma_safety_measures: "ସୁରକ୍ଷା ମୋଡ୍ ମାପକାଣ୍ଡ"
, safety_guidelines_for_you: "ଆପଣଙ୍କ ପାଇଁ ସୁରକ୍ଷା ନିର୍ଦ୍ଦେଶାବଳୀ"
, about_sos: "SOS ବିଷୟରେ"
, night_time_safety_checks: "ରାତିର ସୁରକ୍ଷା ଚେକ୍"
, share_info_with_emergency_contacts_title: "SOS କ୍ଲିକ୍ କରିବାକୁ, ତଥ୍ୟ ସେୟାର୍ କରନ୍ତୁ ଏବଂ ଆପତ୍କାଳୀନ ସମ୍ପର୍କ ସହିତ ଅଟୋ କଲ୍ ଆରମ୍ଭ କରନ୍ତୁ?"
, share_info_with_emergency_contacts_desc: "ଆପଣଙ୍କ ଯାତ୍ରା ପାଇଁ ଉତ୍ତରଦାୟୀ ସମ୍ପର୍କ ବାଛନ୍ତୁ, ଯେପରିକି ଏକ ସ୍ଥାନୀୟ ଅଭିଭାବକ କିମ୍ବା ସହରରେ ଥିବା ଗୋଟିଏ ସାଙ୍ଗ।"
, trigger_alert_to_nammayatri_support_title: (\appName -> appName <> " ସମର୍ଥନକୁ ସତର୍କ କରନ୍ତୁ")
, trigger_alert_to_nammayatri_support_desc: "ଆମ ପାଖରେ 24*7 ସମର୍ପିତ ସମର୍ଥନ ଅଛି ଯେଉଁମାନେ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ସତର୍କ ହେବେ"
, enable_night_time_safety_alerts_title: "ରାତିରେ ସୁରକ୍ଷା ଚେକ୍ ସକ୍ରିୟ କରିବେ?"
, enable_night_time_safety_alerts_desc: "ଆପଣଙ୍କ ସୁରକ୍ଷା ସୁନିଶ୍ଚିତ କରିବାକୁ, <b><span style='color:#454545'>9 PM-6AM</span></b>, ଡ୍ରାଇଭରର ରୁଟ୍ ବିପଦ ସନ୍ଦେହ ଆଧାରରେ ସୁରକ୍ଷା ଚେକ୍ ସତର୍କତା ଦିଆଯିବ। ରାସ୍ତା ବିପର୍ୟୟରେ କିମ୍ବା ଯେତେବେଳେ ଯାନ ଚାଲି ନାହିଁ।<br><br>ଏହା ସୁରକ୍ଷା ମୋଡ୍ ସକ୍ରିୟ କରା ଯାଇଥିବା ବେଳେ କରାଯିବ"
, almost_done_title: "ପ୍ରାୟ ସମାପ୍ତ!"
, almost_done_desc: "ଆପତ୍କାଳୀନ ସ୍ଥିତିରେ, ଆପଣ ପୋଲିସ ହେଲ୍ପଲାଇନକୁ ସମ୍ପର୍କ କରିପାରିବେ କିମ୍ବା ସୁରକ୍ଷା ସମସ୍ୟା ରିପୋର୍ଟ କରିପାରିବେ। ଏହା କରିବା ପାଇଁ ଆବଶ୍ୟକ ଅନୁମତି ଦିଅନ୍ତୁ"
, personal_safety_action_1: "ପୋଲିସକୁ କଲ୍ କରନ୍ତୁ (112)"
, personal_safety_action_2: (\appName -> appName <> " ସମର୍ଥନକୁ କଲ୍ କରନ୍ତୁ")
, personal_safety_action_2_police: "ପୋଲିସକୁ ନିରବ SOS ପଠାନ୍ତୁ।"
, personal_safety_action_3: "15 ସେକେଣ୍ଡ ଭିଡିଓ ରେକର୍ଡ୍ କରନ୍ତୁ।"
, personal_safety_settings_permission_request: "(ରେକର୍ଡ୍ କରିବାକୁ ସମ୍ପର୍କିତ ଅନୁମତି ଦିଅନ୍ତୁ)"
, safety_measure_1: "ଡ୍ରାଇଭର ରୁଟ୍ ବିପଦ ସନ୍ଦେହ ଆଧାରରେ ରାତିରେ ସୁରକ୍ଷା ଚେକ୍"
, safety_measure_2: "ସୁରକ୍ଷା ମୋଡ୍ ବଟନ୍।"
, safety_measure_3: "ଡ୍ରାଇଭରମାନେ / ଗ୍ରାହକମାନେ ପାଇଁ ଶୂନ୍ୟ ସହନଶୀଳତା ନୀତି"
, safety_measure_4: "ଗ୍ରାହକର ଗୋପନୀୟତା - ଯାନ ସମାପ୍ତ ହେବା ପରେ ଡ୍ରାଇଭରମାନେ ଯାନର ଠିକଣା ଦେଖିପାରିବେ ନାହିଁ"
, safety_measure_5: (\appName -> "ସମସ୍ତ " <> appName <> " ଡ୍ରାଇଭର ପାଇଁ ସୁରକ୍ଷା ପ୍ରଶିକ୍ଷଣ ଏବଂ ପ୍ରମାଣୀକରଣ")
, safety_measure_6: "ଆପତ୍କାଳୀନ ସ୍ଥିତିରେ ଏକ ସଜୀବ ଭିଡିଓ ରେକର୍ଡିଂ ସେୟାର୍ କରନ୍ତୁ।"
, safety_guidelines_1: "ଡ୍ରାଇଭରଙ୍କ ପରିଚୟ ଯାନ ନମ୍ବର ସହିତ ଯାଞ୍ଚ କରନ୍ତୁ"
, safety_guidelines_2: "ରାସ୍ତାକୁ ଧ୍ୟାନ ରଖନ୍ତୁ"
, safety_guidelines_3: "ବିଶେଷତଃ ରାତିରେ ଯାତ୍ରା ସମୟରେ ସଚେତନ ରୁହନ୍ତୁ"
, safety_guidelines_4: "ଯଦି ଆପଣକୁ ଅସୁବିଧା ଲାଗୁଛି, ଆପତ୍କାଳୀନ ସମ୍ପର୍କରେ ଆପଣଙ୍କ ଯାତ୍ରା ସେୟାର୍ କରନ୍ତୁ"
, safety_guidelines_5: "ବ୍ୟକ୍ତିଗତ ତଥ୍ୟ ସେୟାର୍ କରିବାକୁ ଏଡ଼ାନ୍ତୁ"
, safety_guidelines_6: "ଆପ୍ରେ ଆପତ୍କାଳୀନ ସୁରକ୍ଷା ମୋଡ୍ ବୈଶିଷ୍ଟ୍ୟକୁ ବ୍ୟବହାର କରନ୍ତୁ"
, safety_guidelines_7: "ଏକ ନିର୍ଭରପ୍ରଦ ଏବଂ ସୁରକ୍ଷିତ ସମୁଦାୟ ପ୍ରତି ଯୋଗଦାନ ପାଇଁ ରେଟ ଏବଂ ସମୀକ୍ଷା କରନ୍ତୁ"
, about_sos_1: "ଡ୍ରାଇଭର ଏକ ଭିନ୍ନ ଦୃଶ୍ୟାନ୍ତର ଜଗାକୁ ପୁନର୍ବାସ କରିବାକୁ ଯାଉଛନ୍ତି"
, about_sos_2: "ଡ୍ରାଇଭରଙ୍କ ଦ୍ୱାରା ଅନୁଚିତ ମାନସିକ/ଶାରୀରିକ ଭାବନା"
, about_sos_3: "ଅନ୍ୟ ଯାତ୍ରୀମାନେ ଆପଣଙ୍କ ସହିତ ଯାତ୍ରା କରିବାକୁ ଅନୁମତି ନ ମାଗିଥିଲେ"
, about_sos_4: "ଡ୍ରାଇଭର ଅପ୍ରତ୍ୟାଶିତ ଭାବରେ ଏକ ଅଜ୍ଜ ପ୍ରଦେଶରେ ଥମିଛନ୍ତି"
, about_sos_5: "ଭଡା ସମସ୍ୟା"
, about_sos_6: "ମଦ ପାନ କରି ଯାନ ଚାଲିବା"
, about_sos_7: "ଅସାବଧାନ ଡ୍ରାଇଭିଂ"
, about_sos_8: "ଯାନ ନମ୍ବର ମେଳ ହେଉନାହିଁ"
, about_sos_9: "ସୁରକ୍ଷା ମୋଡ୍ ବଟନ୍ କ୍ଲିକ୍ କରି ସୁରକ୍ଷା ମୋଡ୍ ସକ୍ରିୟ କରନ୍ତୁ"
, about_sos_10: "ଶାନ୍ତ ରହନ୍ତୁ। ଆତଙ୍କିତ ହେବେନାହିଁ।"
, about_sos_11: (\_ -> "ଆପଣଙ୍କ ପରିବାର ଏବଂ ସାଙ୍ଗମାନଙ୍କୁ ଆପତ୍କାଳୀନ ସେୟାର୍ କରନ୍ତୁ।")
, about_sos_12: "ଆପଣ ପୋଲିସ ହେଲ୍ପଲାଇନ (112) କୁ କଲ୍ କରିପାରିବେ"
, about_sos_13: "ସମ୍ଭବ ହେଲେ, ଡ୍ରାଇଭରକୁ ଏକ ନିକଟସ୍ଥ ପ୍ରଦେଶରେ ଥାମିବାକୁ କହନ୍ତୁ"
, the_video_will_be_recorded: "ଭିଡିଓ କେବଳ 15 ସେକେଣ୍ଡ ପାଇଁ ରେକର୍ଡ୍ ହେବ ଏବଂ ଆମ ସମର୍ଥନ ଦଳ ସହିତ ସେୟାର୍ ହେବ"
, emergency_video: "ଆପତ୍କାଳୀନ ଭିଡିଓ"
, namma_safety_is_set_up: "ସୁରକ୍ଷା ମୋଡ୍ ସଫଳତାର ସହିତ ସେଟ୍ ହୋଇଛି"
, activate_namma_safety_popup_title: "ସୁରକ୍ଷା ମୋଡ୍ ସକ୍ରିୟ କରିବାକୁ ଆପଣ ଯାଉଛନ୍ତି"
, activate_namma_safety_popup_desc: "ଆମର ପ୍ରଥମ ପ୍ରାଥମିକତା ଆପଣଙ୍କ ସୁରକ୍ଷା ଅଟେ। କୃପୟା ସତ୍ୟ ସମୟର SOS ବ୍ୟବହାର କରନ୍ତୁ। ଏହାକୁ ଅବୈଧ ବ୍ୟବହାର କରିବା ଆସଲ ସ୍ଥିତିରୁ ସାହାଯ୍ୟ ଉପଲବ୍ଧ କରିବ।"
, activate_namma_safety_popup_action: "ସକ୍ରିୟ କରିବାକୁ ନିଶ୍ଚିତ କରନ୍ତୁ"
, dismiss: "ବାତିଲ କରନ୍ତୁ"
, send_silent_sos_to_police: "ନିରବ SOS ପୋଲିସକୁ ପଠାନ୍ତୁ"
, our_safety_partner: "ଆମ ସୁରକ୍ଷା ସହଭାଗୀ"
, bangaluru_city_police: "ବେଙ୍ଗାଲୁରୁ ସହର ପୋଲିସ"
, get_options_to_directly_call_police: "ପୋଲିସ ହେଲ୍ପଲାଇନକୁ ସିଧାସଳକ କଲ୍ କରିବାକୁ ବିକଳ୍ପ"
, share_sos_silently_with_police: "SOS ନିରବ ଭାବରେ ଯାତ୍ରା ବିବରଣୀ ସହିତ ପୋଲିସ ସହିତ ସେୟାର୍ କରନ୍ତୁ"
, call_and_alert_the_nearest_police_centre: "ସମୀପସ୍ଥ ପୋଲିସ କେନ୍ଦ୍ରକୁ କଲ୍ କରନ୍ତୁ ଏବଂ ସତର୍କ କରନ୍ତୁ।"
, send_a_silent_sos_to_the_police: "ପୋଲିସକୁ ଏକ ନିରବ SOS ମେସେଜ୍ ପଠାନ୍ତୁ।"
, send_a_video_recording_to_police: "ଭିଡିଓ ରେକର୍ଡିଂ ପୋଲିସକୁ ପଠାନ୍ତୁ।"
, send_video_to_police: "ପୋଲିସକୁ 15ସେକେଣ୍ଡର ଭିଡିଓ ପଠାନ୍ତୁ"
, finish_setup: "ସେଟଅପ୍ ସମାପ୍ତ କରନ୍ତୁ"
, activate_sos: "ସକ୍ରିୟ କରନ୍ତୁ"
, mark_ride_as_safe: "ରାଇଡ୍କୁ ସୁରକ୍ଷିତ ଭାବରେ ଚିହ୍ନିତ କରନ୍ତୁ"
, start_setup: "ସେଟଅପ୍ ଆରମ୍ଭ କରନ୍ତୁ"
, call_support_for_safety: (\_ -> "ଆମ ସମର୍ଥନକୁ କଲ୍ କରନ୍ତୁ")
, we_noticed_your_ride_hasnt_moved: "ଆମେ ଲକ୍ଷ୍ୟ କରିଛୁ ଆପଣଙ୍କ ଡ୍ରାଇଭର ଦିର୍ଘ ସମୟ ଧରି ଚାଲିବା ନାହିଁ। ଆପଣ ଯାତ୍ରାରେ ସୁରକ୍ଷିତ ଅଛନ୍ତି କି?"
, we_noticed_your_ride_is_on_different_route: "ଆମେ ଲକ୍ଷ୍ୟ କରିଛୁ ଆପଣଙ୍କ ଡ୍ରାଇଭର ଭିନ୍ନ ରୁଟ୍ ଉପରେ ଅଛନ୍ତି। ଆପଣ ଯାତ୍ରାରେ ସୁରକ୍ଷିତ ଅଛନ୍ତି କି?"
, we_are_here_for_you: "ଆମେ ଆପଣଙ୍କ ପାଇଁ ଅଛୁ!"
, i_need_help: "ମୋତେ ସହାୟତା ଆବଶ୍ୟକ"
, i_feel_safe: "ମୁଁ ସୁରକ୍ଷିତ ଅଛି"
, everything_okay_q: "ସବୁଠିକ ଅଛି?"
, please_remain_calm_you_can_request_an_immediate_call: "ଦୟାକରି ଶାନ୍ତ ରୁହନ୍ତୁ, ଆପଣ ଆବଶ୍ୟକତା ଅନୁସାରେ ତୁରନ୍ତ ଏକ କଲ୍ ଅନୁରୋଧ କରିପାରିବେ। ଆପଣ ସୁରକ୍ଷା+ ବୈଶିଷ୍ଟ୍ୟଗୁଡ଼ିକ ବ୍ୟବହାର କରି ସୁରକ୍ଷା ବୃଦ୍ଧି କରିପାରିବେ।"
, receive_call_from_support: "ସମର୍ଥନରୁ କଲ୍ ଗ୍ରହଣ କରନ୍ତୁ"
, add_contacts: "ସମ୍ପର୍କ ଯୋଡନ୍ତୁ"
, add_contacts_manually: "ମାନେଉଆଲ୍ ଭାବରେ ସମ୍ପର୍କ ଯୋଡନ୍ତୁ"
, video_share_info_to_police: "ଭିଡିଓ କେବଳ 15 ସେକେଣ୍ଡ ପାଇଁ ରେକର୍ଡ୍ ହେବ ଏବଂ ଏହା ପୋଲିସ ଅଧିକାରୀଙ୍କୁ ଓହଲାପରେ ସେୟାର୍ କରାଯିବ"
, call_police_helpline: "ପୋଲିସ ହେଲ୍ପଲାଇନକୁ କଲ୍ କରନ୍ତୁ (112)"
, please_remain_calm_call_police: "ଦୟାକରି ଶାନ୍ତ ରହନ୍ତୁ, ଆପଣ ଆବଶ୍ୟକତା ଅନୁସାରେ ପୋଲିସ ହେଲ୍ପଲାଇନକୁ କଲ୍ କରିପାରିବେ। ଆପଣ ସୁରକ୍ଷା ମୋଡ୍ ବୈଶିଷ୍ଟ୍ୟଗୁଡ଼ିକ ବ୍ୟବହାର କରି ସୁରକ୍ଷା ବୃଦ୍ଧି କରିପାରିବେ।"
, please_allow_camera_and_microphone_permissions: "ଭିଡିଓ ରେକର୍ଡ କରିବା ପାଇଁ କ୍ୟାମେରା ଏବଂ ମାଇକ୍ରୋଫୋନ ଅନୁମତି ଦିଅନ୍ତୁ"
, ride_share_after_six_pm: "ରାତି 9 ଟାରୁ ସକାଳ 6 ପର୍ଯ୍ୟନ୍ତ ଆପତ୍କାଳୀନ ସମ୍ପର୍କରେ ଯାତ୍ରା ସୂଚନା ପଠାନ୍ତୁ"
, who_can_track_your_ride: (\appName -> appName <> " ଆପରେ କିଏ ଆପଣଙ୍କ ଯାତ୍ରା ଟ୍ରାକ୍ କରିପାରିବେ")
, select_preferred_contacts: "ପ୍ରଥମେ କଲ୍ କରିବାକୁ ପସନ୍ଦ କରା ସମ୍ପର୍କ ବାଛନ୍ତୁ:"
, new: "ନୂତନ"
, safety_center: "ସୁରକ୍ଷା କେନ୍ଦ୍ର"
, emergency_sos: "ଆପତ୍କାଳୀନ SOS"
, automatic_call_placed_to_emergency_contacts: "ଆପତ୍କାଳୀନ ସମ୍ପର୍କରେ ସ୍ୱୟଂଚାଳିତ କଲ୍ ପଠାଯାଇଛି"
, emergency_contacts_can_follow: (\appName -> appName <> " ଆପରେ ଆପତ୍କାଳୀନ ସମ୍ପର୍କଗୁଡ଼ିକ ଅନୁସରଣ କରିବେ ଏବଂ ଆପତ୍କାଳୀନ ପ୍ରତିକ୍ରିୟା କାର୍ଯ୍ୟଗୁଡ଼ିକ ଗ୍ରହଣ କରିପାରିବେ")
, alert_safety_team: (\appName -> appName <> " ସୁରକ୍ଷା ଦଳକୁ ସତର୍କ କରନ୍ତୁ")
, option_to_report_a_safety_issue: "ସୁରକ୍ଷା ସମସ୍ୟା ରିପୋର୍ଟ କରିବାକୁ ବିକଳ୍ପ"
, recommend_emergency_contacts_to_install: (\appName -> "ଆପଣଙ୍କର ଆପତ୍କାଳୀନ ସମ୍ପର୍କକୁ " <> appName <> " ଇନସ୍ଟଲ କରିବାକୁ ଆମ ସୁପାରିଶ କରୁଛୁ")
, test_safety_drill: "ସୁରକ୍ଷା ପରୀକ୍ଷା ପ୍ରସ୍ତୁତି"
, start_test_drill: "ସ୍ତରର ପ୍ରସ୍ତୁତି ଆରମ୍ଭ କରନ୍ତୁ"
, report_safety_issue: "ସୁରକ୍ଷା ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ"
, safety_team_will_be_alerted: (\appName -> "SOS ଉପରେ " <> appName <> " ସୁରକ୍ଷା ଦଳକୁ ସତର୍କ କରାଯାଇବ")
, emergency_contacts_can_take_action: (\appName -> appName <> " ଆପରେ ଆପତ୍କାଳୀନ ସମ୍ପର୍କରେ ଅନୁସରଣ ଏବଂ ପ୍ରତିକ୍ରିୟା କାର୍ଯ୍ୟ ଗ୍ରହଣ କରିବାକୁ ସମର୍ଥ")
, share_ride: "ଯାତ୍ରା ସେୟାର୍ କରନ୍ତୁ"
, share_ride_description: (\appName -> "ଏହାକୁ ଚୟନ କଲେ, " <> appName <> " ଆପତ୍କାଳୀନ ସମ୍ପର୍କରେ ଆପ୍ ପୁଶ ସୂଚନା ପଠାଇବେ")
, share_ride_with_contact: (\number -> "ସମ୍ପର୍କ " <> number <> " ସହିତ ସେୟାର୍ କରନ୍ତୁ")
, share_link: "ଲିଙ୍କ ସେୟାର୍ କରନ୍ତୁ"
, glad_to_know_you_are_safe: "ଆପଣ ସୁରକ୍ଷିତ ଥିବାରେ ଆମେ ଖୁସି!"
, please_stay_calm_team_alerted: (\appName -> "ଦୟାକରି ଶାନ୍ତ ରୁହନ୍ତୁ, " <> appName <> " ସୁରକ୍ଷା ଦଳକୁ ସତର୍କ କରାଯାଇଛି!")
, try_another_contact: "ଅନ୍ୟ ଆପତ୍କାଳୀନ ସମ୍ପର୍କ ସହିତ ଯୋଡନ୍ତୁ"
, your_current_location: "ଆପଣଙ୍କର ବର୍ତ୍ତମାନ ସ୍ଥାନ"
, this_is_not_a_real_sos_situation: "ଏହା ବାସ୍ତବ SOS ସ୍ଥିତି ନୁହେଁ"
, your_vehicle_info: "ଆପଣଙ୍କ ଯାନର ବିବରଣୀ"
, police_view_instruction: "ଦୟାକରି ଓପରେଟରକୁ ଆପଣଙ୍କ ସ୍ଥାନ ଦିଅନ୍ତୁ - ଆପ୍ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ସ୍ଥାନ ଅଂଶୀଦାର କରିନାହିଁ।"
, test_sos_activating_in: "ପରୀକ୍ଷା SOS ସକ୍ରିୟ ହେଉଛି..."
, sos: "SOS"
, test_sos: "ପରୀକ୍ଷା\nSOS"
, select_contact_to_call: "କଲ୍ କରିବାକୁ ସମ୍ପର୍କ ଚୟନ କରନ୍ତୁ"
, emergency_sos_activating: "ଆପତ୍କାଳୀନ SOS ସକ୍ରିୟ ହେଉଛି..."
, press_to_start_test_drill: "ପରୀକ୍ଷା SOS ପ୍ରସ୍ତୁତି ପାଇଁ କ୍ଲିକ୍ କରନ୍ତୁ"
, press_in_case_of_emergency: "ଆପତ୍କାଳୀନ ସ୍ଥିତିରେ କ୍ଲିକ୍ କରନ୍ତୁ"
, inform_emergency_contacts: "ଦୟାକରି ଏହି ପରୀକ୍ଷା ପ୍ରସ୍ତୁତି ବାବଦରେ ଆପତ୍କାଳୀନ ସମ୍ପର୍କକୁ ଜଣାନ୍ତୁ ଯାହା ଅନାବଶ୍ୟକ ଆତଙ୍କ ହାରିବ।"
, other_safety_actions: "ଅନ୍ୟ ସୁରକ୍ଷା କାର୍ଯ୍ୟଗୁଡିକ"
, available_in_real_emergency: "ବାସ୍ତବ SOS ସ୍ଥିତିରେ ଉପଲବ୍ଧ"
, disclaimer: "ତ୍ୟାଗପତ୍ର"
, use_only_in_emergency: "କେବଳ ଆପତ୍କାଳୀନ ସ୍ଥିତିରେ ବ୍ୟବହାର କରନ୍ତୁ"
, misuse_may_lead_to_legal_action: "ଦୁର୍ବ୍ୟବହାର କାରଣେ କାନୁନୀ କାର୍ଯ୍ୟ ହୋଇପାରେ"
, use_test_drill: "<span style='color:#2194FF'><u>ପରୀକ୍ଷା ସୁରକ୍ଷା ପ୍ରସ୍ତୁତି</u></span> ବ୍ୟବହାର କରନ୍ତୁ"
, indication_to_emergency_contacts: (\appName -> appName <> " ଆପଣଙ୍କର ଆପତ୍କାଳୀନ ସମ୍ପର୍କକୁ ସୂଚନା ଦିଅଏ ଯେ ଏହା ଏକ ପରୀକ୍ଷା ପ୍ରସ୍ତୁତି, ଯାହା ଆତଙ୍କମୁକ୍ତ ଅଭିଜ୍ଞତାକୁ ସୁନିଶ୍ଚିତ କରିବ।")
, are_you_ready_to_start_drill: "ପରୀକ୍ଷା ସୁରକ୍ଷା ପ୍ରସ୍ତୁତି ଆରମ୍ଭ କରିବାକୁ ଆପଣ ପ୍ରସ୍ତୁତ ତ?"
, test_drill_desc: "ପରୀକ୍ଷା ପ୍ରସ୍ତୁତିରେ ଯୋଗ ଦେବା ଆପଣଙ୍କୁ ବାସ୍ତବ SOS ସ୍ଥିତିରେ କିପରି ଆଚରଣ କରିବାକୁ ଶିଖିବେ। ଏବେ ପରୀକ୍ଷା ପ୍ରସ୍ତୁତି ନିଅନ୍ତୁ, ଆପତ୍କାଳୀନ ସ୍ଥିତିରେ ଆତଙ୍କ ଏଡାଇବା ପାଇଁ।"
, sos_will_be_disabled: "ଦୁର୍ବ୍ୟବହାର ହେଲେ SOS ବୈଶିଷ୍ଟ୍ୟ ଅସକ୍ରିୟ ହେବ"
, dial_now: "ଏବେ ଡାଏଲ୍ କରନ୍ତୁ"
, following: (\name -> "ଅନୁସରଣ କରୁଛି " <> name)
, turn_off_alarm: "ଆଲାର୍ମ ବନ୍ଦ କରନ୍ତୁ"
, choose_a_person_to_follow: "ଅନୁସରଣ କରିବାକୁ ଏକ ବ୍ୟକ୍ତି ବାଛନ୍ତୁ"
, is_in_sos_situation: (\name -> name <> " SOS ସ୍ଥିତିରେ ଅଛନ୍ତି!")
, marked_ride_safe: (\name -> name <> " ଯାତ୍ରାକୁ ସୁରକ୍ଷିତ ଭାବରେ ଚିହ୍ନିତ କରିଛନ୍ତି!")
, stay_calm_keep_tracking: (\name -> "ଶାନ୍ତ ରୁହନ୍ତୁ। " <> name <> " ର ଲୋକେସନ୍ ଟ୍ରାକ୍ କରୁଥିବା ଆବଶ୍ୟକ କାର୍ଯ୍ୟଗୁଡିକ ନିଅନ୍ତୁ")
, you_will_be_notified: "ଯେତେବେଳେ ଯାତ୍ରା ସମାପ୍ତ ହେବ, ଆପଣ ସୂଚିତ ହେବେ"
, tap_here_to_follow: (\name -> name <> " ଙ୍କୁ ଅନୁସରଣ କରିବା ପାଇଁ ଏଠାରେ କ୍ଲିକ୍ କରନ୍ତୁ")
, have_shared_ride_with_you: (\name -> name <> " ଆପଣଙ୍କ ସହିତ ତାଙ୍କର ଯାତ୍ରା ସେୟାର୍ କରିଛନ୍ତି")
, sos_location: "SOS ସ୍ଥାନ"
, this_is_a_test_mock_drill: (\name -> "ଏହା ଏକ ପରୀକ୍ଷା ପ୍ରସ୍ତୁତି " <> name)
, this_is_not_real_drill: "ଏହା ବାସ୍ତବ ପ୍ରସ୍ତୁତି ନୁହେଁ, ଏହା କିପରି ଆପ୍ ପ୍ରତିକ୍ରିୟା କରିବ ଏହାକୁ ଦର୍ଶାଏ।"
, reached_destination_safely: (\name -> name <> " ଗନ୍ତବ୍ୟ ସ୍ଥାନକୁ ସୁରକ୍ଷିତ ଭାବରେ ପହଞ୍ଚିଛନ୍ତି!")
, ride_ended: (\name -> name <> " ରାଇଡ୍ ସମାପ୍ତ")
, complete_your_test_drill: "ଆପଣଙ୍କର ପରୀକ୍ଷା ପ୍ରସ୍ତୁତି ସମାପ୍ତ କରନ୍ତୁ: ସୁରକ୍ଷା ପ୍ରଥମ!"
, test_drill: "ପରୀକ୍ଷା ପ୍ରସ୍ତୁତି"
, ride_shared_with_selected_contacts: "ବାଛାଯାଇଥିବା ସମ୍ପର୍କ ସହିତ ଯାତ୍ରା ସେୟାର୍ କରାଗଲା"
, terms_and_conditions_updated: "ନିୟମ ଏବଂ ପ୍ରାଇଭେସି ନୀତିକୁ ଅପଡେଟ୍ କରାଯାଇଛି"
, okay: "ଠିକ ଅଛି"
, try_later: "ପରେ ଚେଷ୍ଟା କରନ୍ତୁ"
, referral_code_is_applied: "ରେଫରାଲ କୋଡ୍ ଆବେଦନ ହୋଇଛି"
, you_have_already_used_different_referral_code: "ଆପଣ ପୂର୍ବରୁ ଅନ୍ୟ ରେଫରାଲ କୋଡ୍ ବ୍ୟବହାର କରିଛନ୍ତି"
, invalid_referral_code: "ଅବୈଧ ରେଫରାଲ କୋଡ୍"
, stops: "ଥାମିବା"
, green_line: "ଗ୍ରୀନ୍ ଲାଇନ୍"
, blue_line: "ବ୍ଲୁ ଲାଇନ୍"
, red_line: "ରେଡ୍ ଲାଇନ୍"
, view_route_info: "ରୁଟ୍ ବିବରଣୀ ଦେଖନ୍ତୁ"
, valid_until: "ବ valid ଦିନ ପର୍ଯ୍ୟନ୍ତ ମାନ୍ୟ"
, ticket_number: "ଟିକେଟ୍ ନମ୍ବର"
, ticket: "ଟିକେଟ୍"
, tickets: "ଟିକେଟ୍ଗୁଡିକ"
, onword_journey: "ଅଗ୍ରଗତି ଯାତ୍ରା"
, round_trip_str: "ରାଉଣ୍ଡ ଟ୍ରିପ୍"
, tickets_for_chennai_metro: "ଚେନ୍ନାଇ ମେଟ୍ରୋ ପାଇଁ ଟିକେଟ୍"
, active_str: "ସକ୍ରିୟ"
, expired_str: "ସମାପ୍ତ"
, used_str: "ବ୍ୟବହୃତ"
, map_str: "ମାନଚିତ୍ର"
, ticket_details: "ଟିକେଟ୍ ବିବରଣୀ"
, route_details: "ରୁଟ୍ ବିବରଣୀ"
, uncertain_about_metro_routes: "ମେଟ୍ରୋ ରୁଟ୍ ବିଷୟରେ ଅନିଶ୍ଚିତ?"
, see_map: "ମାନଚିତ୍ର ଦେଖନ୍ତୁ"
, chennai_metro_term_1: "ଟିକେଟ୍ ବାତିଲ ହେବ ନାହିଁ"
, chennai_metro_term_2: "ସମସ୍ତ ଦିନରେ 4:30 AM ରୁ 10:30 PM ମଧ୍ୟରେ ଟିକେଟ୍ ବିକ୍ରି ହେବ"
, chennai_metro_term_event: "ବାତିଲ ହୋଇଥିବା ଟିକେଟ୍ ମୁକ୍ତ ଟିକେଟ୍ ପ୍ରସ୍ତାବ ପାଇଁ ଗଣନାରେ ଆସିବ ନାହିଁ"
, free_ticket_cashback: "ମୁକ୍ତ ଟିକେଟ୍ ପ୍ରସ୍ତାବ ପାଇଁ କ୍ୟାଶବ୍ୟାକ୍ ଅଗାମୀ 24 ଘଣ୍ଟାରେ ଜମା ହେବ"
, no_of_passengers: "ଯାତ୍ରୀଙ୍କ ସଂଖ୍ୟା"
, maximum: "ସର୍ବାଧିକ"
, tickets_allowed_per_user: "ପ୍ରତି ବ୍ୟବହାରକାରୀକୁ ଅନୁମତି ଦିଆଯାଇଥିବା ଟିକେଟ୍ ସଂଖ୍ୟା।"
, starting_from: "ଆରମ୍ଭ ହେଉଛି"
, from: "ଠାରୁ"
, to: "କୁ"
, booking_id: "ବୁକିଂ ଆଇଡି"
, please_while_gen_ticket: "ଦୟାକରି ଆମେ ଆପଣଙ୍କ ଟିକେଟ୍ ତିଆରି କରୁଥିବା ବେଳେ ଅପେକ୍ଷା କରନ୍ତୁ"
, payment_received: "ଭୁଗତା ଗ୍ରହଣ କରାଯାଇଛି!"
, please_check_back_few_min: "କିଛି ସମୟ ପରେ ପୁନଃ ଚେକ୍ କରନ୍ତୁ।"
, your_booking_pending: "ଆପଣଙ୍କ ବୁକିଂ ଅପେକ୍ଷାରତ ଅଛି!"
, please_retry_booking: "ଦୟାକରି ବୁକିଂ ପୁନଃଚେଷ୍ଟା କରନ୍ତୁ।"
, booking_failed: "ବୁକିଂ ବିଫଳ!"
, incase_of_fail: "ବିଫଳ ହେଲେ, କ୍ଷୟ କରାଯାଇଥିବା ଅର୍ଥ 5 - 7 କାର୍ଯ୍ୟଦିନ ମଧ୍ୟରେ ପୁନଃ ଫେରତ ଦିଆଯିବ।"
, refresh_status: "ସ୍ଥିତି ସତେଜ କରନ୍ତୁ"
, date: "ତାରିଖ"
, no_of_tickets: "ଟିକେଟ୍ ସଂଖ୍ୟା"
, active_tickets: "କାର୍ଯ୍ୟଶୀଳ ଟିକେଟ୍"
, confirming_str: "ନିଶ୍ଚିତ କରାଯାଉଛି"
, failed_str: "ବିଫଳ"
, confirmed_str: "ନିଶ୍ଚିତ"
, buy_metro_tickets: "ମେଟ୍ରୋ ଟିକେଟ୍ କିଣନ୍ତୁ"
, get_fare: "ଭାଡା ପାଆନ୍ତୁ"
, metro_booking_timings: "ମେଟ୍ରୋ ବୁକିଂ ସମୟସୂଚୀ"
, chennai_metro_time: (\startTime endTime -> "ଚେନ୍ନାଇ ମେଟ୍ରୋ ଦିନ ସମସ୍ତ ଦିନରେ " <> startTime <>" ରୁ " <> endTime <> " ପର୍ଯ୍ୟନ୍ତ QR ଟିକେଟ୍ କିଣିବାକୁ ଅନୁମତି ଦିଅଏ।")
, please_come_back_later_metro: "ଦୟାକରି ଟିକେଟ୍ କିଣିବାକୁ ଯୋଗ୍ୟ ସମୟରେ ପଛକୁ ଫେରନ୍ତୁ।"
, no_qoutes_available: "କୌଣସି ଦର ଉପଲବ୍ଧ ନାହିଁ"
, i_agree_to_the: "ମୁଁ ଏହାକୁ ସମ୍ମତି ଦେଇଛି"
, here_is_metro_ticket: "ଏହା ହେଉଛି ମେଟ୍ରୋ ଟିକେଟ୍!"
, view_ticket: "ଟିକେଟ୍ ଦେଖନ୍ତୁ"
, destination: "ଗନ୍ତବ୍ୟ ସ୍ଥାନ"
, pay: "ପେୟ କରନ୍ତୁ"
, pending_str: "ଅପେକ୍ଷାରତ"
, past_tickets: "ପୂର୍ବ ଟିକେଟ୍"
, one_way_str: "ଏକ ପଥ"
, share_ticket: "ଟିକେଟ୍ ସେୟାର୍ କରନ୍ତୁ"
, ticket_is_non_cancellable: "ଟିକେଟ୍ ବାତିଲ ହୋଇପାରିବ ନାହିଁ"
, cancel_booking: "ବୁକିଂ ବାତିଲ କରିବେ କି?"
, booking_not_cancellable: "ମେଟ୍ରୋ ବୁକିଂ ନୀତି ଅନୁସାରେ ଏହି ବୁକିଂ ବାତିଲ୍ ହେବାର ଅନୁମତି ନାହିଁ"
, bookings_will_be_cancelled: "ଏହି ବୁକିଂ ସହିତ ସମ୍ବନ୍ଧିତ ସମସ୍ତ ଟିକେଟ୍ ବାତିଲ ହେବ।"
, bookings_will_be_cancelled_with_refund: (\number -> "ଏହି ବୁକିଂ ସହିତ ସମ୍ବନ୍ଧିତ ସମସ୍ତ ଟିକେଟ୍ ବାତିଲ ହେବ ଏବଂ ଆପଣ " <> number <> "ର ଫେରତ ପାଇବେ।")
, refund_not_applicable: "ଏହି ବୁକିଂ ପାଇଁ ରିଫଣ୍ଡ ଅନୁମତି ନାହିଁ"
, yes_cancel_booking: "ହଁ, ବୁକିଂ ବାତିଲ କରନ୍ତୁ"
, would_you_like_to_proceed: "ଆପଣ ଆଗେ ଯିବାକୁ ଚାହୁଁଛନ୍ତି କି?"
, booking_cancelled: "ଆପଣଙ୍କ ବୁକିଂ ବାତିଲ ହୋଇଛି"
, refund_is_in_process: "ଆପଣଙ୍କ ଫେରତ ପ୍ରକ୍ରିୟାରେ ଅଛି। ଏହାକୁ ତିନି-ଚାରି କାର୍ଯ୍ୟଦିନ ଲାଗିପାରେ।"
, total_refund: "ମୋଟ ରିଫଣ୍ଡ"
, number_of_tickets: "ଟିକେଟ୍ ସଂଖ୍ୟା"
, cancellation_date: "ବାତିଲ ତାରିଖ"
, tickets_for_kochi_metro: "କୋଚି ମେଟ୍ରୋ ପାଇଁ ଟିକେଟ୍"
, your_booked_tickets: "ଆପଣଙ୍କ ବୁକିଂ ଟିକେଟ୍ ଏଠାରେ ଦେଖାଯିବ"
, plan_your_journey: "ଆପଣଙ୍କ ଯାତ୍ରା ଯୋଜନା କରନ୍ତୁ"
, book_round_trip: "ରାଉଣ୍ଡ ଟ୍ରିପ୍ ବୁକ୍ କରନ୍ତୁ"
, by_proceeding_you_agree: "ଆଗେ ଯିବାରେ, ଆପଣ ଏହାକୁ ସମ୍ମତି ଦେଇଛନ୍ତି "
, terms_and_conditions_full: "ସର୍ତ୍ତାବଳୀ"
, experience_hassle_free_metro_booking: (\appName -> "ସହଜ ଓ ସଂଯୋଗବାହୀ ମେଟ୍ରୋ ବୁକିଂ ଅନୁଭବ କରନ୍ତୁ " <> appName)
, kochi_metro_term_1: "ଟିକେଟ୍ ପ୍ରତ୍ୟେକ ଦିନ 5:00 AM ରୁ 11:45 PM ମଧ୍ୟରେ କ୍ରୟ କରାଯାଇପାରେ।"
, kochi_metro_term_2: "ଏକ ଥାନେ ଭିତରକୁ ପ୍ରବେଶ କରିବା ପରେ ଯାତ୍ରୀମାନେ ଗନ୍ତବ୍ୟ ସ୍ଥାନରୁ 120 ମିନିଟ୍ ମଧ୍ୟରେ ବାହାରୁଅଛି।"
, kochi_metro_time: (\startTime endTime -> "କୋଚି ମେଟ୍ରୋ ପ୍ରତ୍ୟେକ ଦିନ" <> startTime <> " AM ରୁ " <> endTime <> " PM ମଧ୍ୟରେ QR ଟିକେଟ୍ କ୍ରୟ କରିବାକୁ ଅନୁମତି ଦେଇଛି।")
, book_ticket: "ଟିକେଟ୍ ବୁକ୍ କରନ୍ତୁ"
, origin: "ଆରମ୍ଭ ସ୍ଥାନ"
, history: "ଇତିହାସ"
, always: "ସମସ୍ତ ସମୟ"
, always_share_desc: "ସମସ୍ତ ରାଇଡ଼ ପାଇଁ ଆପାତକାଳୀନ ସମ୍ପର୍କକୁ ଯାତ୍ରା ସୂଚନା ପଠାନ୍ତୁ।"
, night_rides_share: "ରାତିରେ ଯାତ୍ରା (ରାତି 9ଟା - ପ୍ରଭାତି 6ଟା)"
, night_rides_desc: "ରାତିରେ ଯାତ୍ରା ପାଇଁ ଆପାତକାଳୀନ ସମ୍ପର୍କକୁ ସୂଚନା ପଠାନ୍ତୁ (ରାତି 9ଟା - ପ୍ରଭାତି 6ଟା)"
, never: "କେବେ ନୁହେଁ"
, never_share_desc: "ଆପାତକାଳୀନ ସମ୍ପର୍କକୁ ଯାତ୍ରା ସୂଚନା ପଠାନ୍ତୁନାହିଁ"
, share_trip_notificatons: "ଯାତ୍ରା ସୂଚନା ସେୟାର କରନ୍ତୁ"
, call_customer_support: "କଷ୍ଟମର ସହାୟତାକୁ କଲ୍ କରନ୍ତୁ"
, yet_to_start: (\name -> name <> " ଏହି ଯାତ୍ରା ଆରମ୍ଭ କରିବାକୁ ବାକି ଅଛି")
, message_from: (\name -> "ମେସେଜ୍ ପ୍ରାପ୍ତ " <> name)
, ride_cancelled: "ରାଇଡ଼ ବାତିଲ୍ ହୋଇଛି"
, track_ride_string: (\appName driverName trackLink vehicleNumber -> "👋 ହେଲୋ,\n\nମୁଁ " <> appName <> " ର ଡ୍ରାଇଭର " <> driverName <> " ସହ ଯାତ୍ରା କରୁଛି! ଏହି ରାଇଡ଼କୁ ଟ୍ରାକ୍ କରନ୍ତୁ: " <> trackLink <> "\n\nଯାନ ସଂଖ୍ୟା: " <> vehicleNumber)
, driver_almost_at_pickup: "ଡ୍ରାଇଭର ଗୋଟିଏ ପିକ୍ଅପ୍ ସ୍ଥାନରେ ଅଛନ୍ତି, ଆପଣ ସେଠାରେ ସଂପର୍କ କରିବାକୁ ପାରନ୍ତି"
, maximum_edit_pickup_attempts_reached: "ଆପଣ ସର୍ବାଧିକ ସମୟ ପାଇଁ ପିକ୍ଅପ୍ ସ୍ଥାନକୁ ବଦଳାଇ ପାରିଛନ୍ତି"
, move_pin_to_the_desired_pickup_point: "ପିନ୍ କୁ ଚଳାନ୍ତୁ ଏବଂ ଆବଶ୍ୟକ ପିକ୍ଅପ୍ ପଏଣ୍ଟକୁ ବଦଳାନ୍ତୁ (ଅଂଚଳ ଅଭିନ୍ତରେ)"
, change_pickup_location: "ପିକ୍ଅପ୍ ସ୍ଥାନ ବଦଳାନ୍ତୁ"
, safety_center_is_disabled: "SOS ବିକଳ୍ପ ସକ୍ରିୟ ହେଇନାହିଁ, ଏହାକୁ ତିନଥର ବ୍ୟବହାର କରାଯାଇଥିବା ନିମନ୍ତେ"
, track_on_google_map: "ଗୁଗୁଲ୍ ମାପ୍ ରେ ଟ୍ରାକ୍ କରନ୍ତୁ >"
, show_walking_direction: "ପିକ୍ଅପ୍ ପାଇଁ ଚାଲିବା ଦିଗ ପ୍ରଦର୍ଶନ କରନ୍ତୁ >"
, special_pickup_zone: "ବିଶେଷ ପିକ୍ଅପ୍ ଅଞ୍ଚଳ"
, special_pickup_zone_ride: "ବିଶେଷ ପିକ୍ଅପ୍ ଅଞ୍ଚଳ ରାଇଡ଼"
, we_will_try_to_connect_you_with_driver_in_closest_pickup_zone: "ଆମେ ଆପଣଙ୍କୁ ନିକଟତମ ପିକ୍ଅପ୍ ଅଞ୍ଚଳରେ ଥିବା ଡ୍ରାଇଭର ସହିତ ସଂଯୋଗ କରିବାକୁ ଚେଷ୍ଟା କରିବା"
, this_provides_you_an_instant_pickup_experience: "ଏହା ଆପଣଙ୍କୁ ଏକ ତତ୍କାଳ ପିକ୍ଅପ୍ ଅନୁଭବ ଦେବ"
, driver_at_pickup_location: "ଆପଣଙ୍କର ଡ୍ରାଇଭର ପିକ୍ଅପ୍ ସ୍ଥାନରେ ଅଛନ୍ତି"
, location_is_too_far: "ସ୍ଥାନ ଅତ୍ୟଧିକ ଦୂର!"
, a_tip_helps_find_a_ride_quicker: "ଟିପ୍ ଏକ ରାଇଡ଼ ଦ୍ରୁତ ପାଇବାରେ ସାହାଯ୍ୟ କରେ!"
, tip_added: "ଟିପ୍ ଯୋଡାଗଲା!"
, continue_search_with_no_tip: "ଟିପ୍ ବିନା ସନ୍ଧାନ ଜାରି ରଖନ୍ତୁ"
, searching_with_no_tip: "ଟିପ୍ ବିନା ସନ୍ଧାନ ଚାଲିଛି"
, search_again: "ପୁନଃ ସନ୍ଧାନ କରନ୍ତୁ"
, driver_is_on_the_way: "ଆପଣଙ୍କ ଡ୍ରାଇଭର ମାର୍ଗରେ ଅଛନ୍ତି"
, driver_is_waiting_at_pickup: "ଆପଣଙ୍କ ଡ୍ରାଇଭର ପିକ୍ଅପ୍ ସ୍ଥାନରେ ଅପେକ୍ଷା କରୁଛନ୍ତି"
, is_at_pickup_location: "ପିକ୍ଅପ୍ ସ୍ଥାନରେ ଅଛି"
, go_to_selected_spot_for_pickup: "ପିକ୍ଅପ୍ ପାଇଁ ନିର୍ଦ୍ଦିଷ୍ଟ ସ୍ଥାନକୁ ଯାଆନ୍ତୁ"
, select_popular_spot_for_hassle_free_pickup: "ସମ୍ଭାବ୍ୟତାର ସହ ସାଧାରଣ ସ୍ଥାନ ବାଛନ୍ତୁ"
, prepare_emergency_contacts: "ଆପାତକାଳୀନ ସମ୍ପର୍କକୁ ପ୍ରସ୍ତୁତ କରନ୍ତୁ"
, emergency_contacts_will_be_notified: "ଆପାତକାଳୀନ ସମ୍ପର୍କକୁ ଅନୁଗମନ ଏବଂ SOS ଦ୍ୱାରା ସଚେତନ କରାଯିବ"
, inform_emergency_contacts_about_test: "ଆପାତକାଳୀନ ସମ୍ପର୍କକୁ ପରୀକ୍ଷା ବିଷୟରେ ସୂଚନା କରନ୍ତୁ"
, recent_ride_issue_desc: "ଆପଣଙ୍କ ପିଛା ଯାତ୍ରା ସମ୍ବନ୍ଧୀୟ ଅସୁବିଧା ଥିଲେ ନିମ୍ନତ ଅବସ୍ଥାନ ବାଛନ୍ତୁ"
, i_need_help_with_my_recent_ride: "ମୁଁ ମୋର ପିଛା ଯାତ୍ରାରେ ସହାୟତା ଚାହୁଁଛି"
, continue_with_safety_settings: "ସୁରକ୍ଷା ସେଟିଙ୍ଗ ସହିତ ଅଗ୍ରଗତି କରନ୍ତୁ"
, tap_where_to_to_book_ride: "'କେଉଁଠାକୁ?' ରେ ଟାପ୍ କରି ଆପଣଙ୍କ ରାଇଡ୍ ବୁକ୍ କରନ୍ତୁ!"
, last_chosen_variant_not_available: "ଶେଷ ଚୟନ ରାଇଡ୍ ପ୍ରକାର ଉପଲବ୍ଧ ନାହିଁ। ଅଲଟର୍ନେଟ ରାଇଡ୍ ବିକଳ୍ପ ଚୟନ କରନ୍ତୁ।"
, toll_charges: "ଟୋଲ୍ ଚାର୍ଜ"
, toll_charges_desc: "ଡ୍ରାଇଭର ଦ୍ୱାରା ଅଧିକ ଚାର୍ଜ ଭାଡ଼ାରେ ଯୋଡାଯାଇଛି"
, toll_charges_including: (\amount -> "ଟୋଲ୍ ଚାର୍ଜ " <> amount <> " ଭାଡାରେ ସମାବିଷ୍ଟ")
, toll_road_changed: "ଟୋଲ୍ ଚାର୍ଜ ଲାଗୁ ହେବ ନାହିଁ"
, parking_charge: "ପାର୍କିଂ ଚାର୍ଜ"
, toll_or_parking_charges: "^ଟୋଲ୍/ ପାର୍କିଂ ଚାର୍ଜ"
, toll_charges_estimated: "ଟୋଲ୍ ଚାର୍ଜ (ଅନୁମାନିତ)^"
, add_tip: "ଟିପ୍ ଯୋଡନ୍ତୁ"
, change_ride_type: "ରାଇଡ୍ ପ୍ରକାର ବଦଳାନ୍ତୁ"
, try_adding_tip_or_change_ride_type: "ଟିପ୍ ଯୋଡିବା କିମ୍ବା ରାଇଡ୍ ପ୍ରକାର ବଦଳାଇବାକୁ ଚେଷ୍ଟା କରନ୍ତୁ"
, applicable_toll_charges: "ଟୋଲ୍ ଚାର୍ଜ ଆପଣଙ୍କ ଭାଡାରେ ସମାବେଶ ହୋଇଛି"
, update_tip_str: "ଟିପ୍ ଅଦ୍ୟତନ କରନ୍ତୁ"
, book: (\name -> "ବୁକ୍ କରନ୍ତୁ " <> name)
, fare_for: (\limit -> "ଭାଡା " <> limit)
, waiting_charge_limit: (\timeLimit -> "ଅପେକ୍ଷା ଚାର୍ଜ (" <> timeLimit <> " ମିନିଟ୍ ପରେ)")
, time_taken: "ଲଗା ସମୟ"
, trip_distance: "ଯାତ୍ରା ଦୂରତା"
, unable_to_cancel_ride: "ରାଇଡ୍ ବାତିଲ୍ କରିବାରେ ବିଫଳ"
, got_a_referral_from_a_driver_or_friend: "କୌଣସି ଡ୍ରାଇଭର କିମ୍ବା ବନ୍ଧୁଙ୍କ ଠାରୁ ଏକ ରେଫେରଲ୍ କୋଡ୍ ପାଇଛନ୍ତି କି?"
, enter_referral_code_: "ରେଫେରଲ୍ କୋଡ୍ ପ୍ରବେଶ କରନ୍ତୁ"
, referred_users: "ରେଫେର କରାଯାଇଥିବା ବ୍ୟବହାରକାରୀ"
, show_app_qr: "ଆପ୍ QR ଦେଖାନ୍ତୁ"
, share_and_refer: "ସେୟାର କରନ୍ତୁ ଏବଂ ରେଫେର୍ କରନ୍ତୁ"
, your_referral_code: "ଆପଣଙ୍କ ରେଫେରଲ୍ କୋଡ୍"
, refer_your_friends: "ଆପଣଙ୍କ ବନ୍ଧୁଙ୍କୁ ରେଫେର୍ କରନ୍ତୁ"
, referrals: "ରେଫେରଲ୍"
, enter_now: "ଏବେ ପ୍ରବେଶ କରନ୍ତୁ"
, what_is_referral_program: "ରେଫେରଲ୍ ପ୍ରୋଗ୍ରାମ୍ କ'ଣ?"
, users_who_download_app_and_complete_their_first_ride_using_referral_code: (\appName -> "ଯେଉଁ ବ୍ୟବହାରକାରୀମାନେ " <> appName <> " ଆପ୍ ଡାଉନଲୋଡ୍ କରି ଏବଂ ତାଙ୍କ ପ୍ରଥମ ରାଇଡ୍ ରେ ରେଫେରଲ୍ କୋଡ୍ ବ୍ୟବହାର କରିଛନ୍ତି, ସେମାନେ ରେଫେର୍ କରାଯାଇଥିବା ବ୍ୟବହାରକାରୀ ଭାବରେ ଗଣାଯିବେ।")
, the_referral_program_incentivises_drivers_to_accept_more_rides: (\appName -> "ରେଫେରଲ୍ ପ୍ରୋଗ୍ରାମ୍ ଡ୍ରାଇଭରମାନଙ୍କୁ ଅଧିକ ରାଇଡ୍ ନିବାରେ ଉତ୍ସାହିତ କରେ ଏବଂ ଆପଣଙ୍କ ଲାଗି ଶ୍ରେଷ୍ଠ ସେବା ସୃଷ୍ଟି କରେ।")
, invalid_code: "ଅବୈଧ କୋଡ୍!"
, enter_6_digit_referral_code_below: "ତଳେ 6 ଆଙ୍କର ରେଫେରଲ୍ କୋଡ୍ ପ୍ରବେଶ କରନ୍ତୁ"
, apply: "ଆବେଦନ କରନ୍ତୁ"
, book_any: "କିଛି ବୁକ୍ କରନ୍ତୁ"
, toll_charges_included: "ଟୋଲ୍ ଚାର୍ଜ ସମାବେଶ"
, one_tap_bookings: "ଏକ କ୍ଲିକ୍ ବୁକିଂ"
, has_your_driver_set_the_ac_as_per_your_preference: "ଆପଣଙ୍କ ଡ୍ରାଇଭର୍ ଆପଣଙ୍କ ଆବଶ୍ୟକତା ଅନୁଯାୟୀ AC ସେଟ୍ କରିଛନ୍ତି କି?"
, no_report_an_issue: "ନାହିଁ, ଅଭିଯୋଗ କରନ୍ତୁ"
, great_enjoy_the_trip: "ଭଲ! ଆପଣଙ୍କ ଯାତ୍ରାର ସୁଖଭୋଗ କରନ୍ତୁ!"
, enjoy_your_budget_friendly_non_ac_ride: "ଆପଣଙ୍କର ଅର୍ଥନୀତି ସହଯୋଗୀ,\nଏକ ଏ.ସି ବିନା ଯାତ୍ରାର ସୁଖ ଉପଭୋଗ କରନ୍ତୁ!"
, ac_is_not_available_on_this_ride: "ଏହି ଯାତ୍ରାରେ AC ଉପଲବ୍ଧ ନାହିଁ"
, ac_not_working_desc: "AC କାମ କରୁନାହିଁ/ଡ୍ରାଇଭର କାମ କରୁନାହିଁ"
, showing_fare_from_multi_provider: "ଏକାଧିକ ପ୍ରଦାନକାରୀଙ୍କରୁ ଭାଡା ଦେଖାଯାଉଛି"
, live_chat: "ଲାଇଭ୍ ଚାଟ୍"
, driver_tip_addition: "ଡ୍ରାଇଭର ଟିପ୍ ଯୋଗ କରିବା"
, live_ride_sharing: "ଲାଇଭ୍ ରାଇଡ୍ ସେୟାରିଂ"
, enhanced_safety: "ଉନ୍ନତ ସୁରକ୍ଷା"
, confirm_provider: "ପ୍ରଦାନକାରୀକୁ ନିଶ୍ଚିତ କରନ୍ତୁ"
, select_a_provider: "ଗୋଟିଏ ପ୍ରଦାନକାରୀ ବାଛନ୍ତୁ"
, confirming_selected_provider: "ନିର୍ବାଚିତ ପ୍ରଦାନକାରୀକୁ ନିଶ୍ଚିତ କରିବା: "
, book_top_provider: "ଶ୍ରେଷ୍ଠ ପ୍ରଦାନକାରୀକୁ ବୁକ୍ କରନ୍ତୁ"
, choose_from_providers: "ସମସ୍ତ ପ୍ରଦାନକାରୀମାନଙ୍କୁ ଚୟନ କରନ୍ତୁ"
, choose_between_providers: "ଏକାଧିକ ପ୍ରଦାନକାରୀ ମଧ୍ୟରୁ ବାଛନ୍ତୁ"
, choose_between_providers_desc: "ସମସ୍ତ ଉପଲବ୍ଧ ପ୍ରଦାନକାରୀରୁ କୋଟ୍ ଦେଖିବାକୁ ଏହି ବୈଶିଷ୍ଟ୍ୟ ସକ୍ରିୟ କରନ୍ତୁ"
, guaranteed_ride: "ଗାରାଣ୍ଟିଡ୍ ରାଇଡ୍"
, this_ride_fulfilled_by: (\provider -> "ଏହି ରାଇଡ୍ ପୂରଣ ହେଉଛି: " <> provider)
, additional_features_on: (\merchantName -> "ଅଧିକ ବୈଶିଷ୍ଟ୍ୟ " <> merchantName)
, notify_your_ec: "ଆପଣଙ୍କ ଆପାତକାଳୀନ ସମ୍ପର୍କକୁ ସୂଚନା କରନ୍ତୁ"
, ec_can_respond: "ଆପାତକାଳୀନ ସମ୍ପର୍କ ଅନୁଗମନ କରି ପ୍ରତିକ୍ରିୟା କରିପାରିବେ"
, quick_support: (\merchantName -> merchantName <> " SOS ସହଯୋଗରୁ ତତ୍କାଳ ସହଯୋଗ")
, learn_about_app_safety_feat: (\merchantName -> merchantName <> " ରେ ବିଶେଷ ସୁରକ୍ଷା ବୈଶିଷ୍ଟ୍ୟ ବିଷୟରେ ଜାଣନ୍ତୁ")
, other_provider_no_receipt: "ଅନ୍ୟ ପ୍ରଦାନକାରୀ ଦ୍ୱାରା ସମାପ୍ତ ଯାତ୍ରା ପାଇଁ ଡ୍ରାଇଭର ରସିଦ ଉପଲବ୍ଧ ନାହିଁ।"
, ride_fulfilled_by: (\merchantName -> "ରାଇଡ୍ ପୂରଣ କରିଛି: " <> merchantName)
, congestion_charges: "ଜନାସ୍ତର ଚାର୍ଜ*"
, tip_can_be_added: (\maxTip -> "ରାଇଡ଼ ଭାଡ଼ାରେ ଅଧିକତମ ₹" <> maxTip <> " ଟିପ୍ ଯୋଗ କରାଯାଇପାରେ")
, congestion_charges_desc: (\charges -> "ଜନାସ୍ତର ଚାର୍ଜ "<> charges <>"% ରେ ଲାଗିଛି କାରଣ ଲୋକମାନଙ୍କର ସମୟକୁ ସଂକୋଚିତ କରି ଦରକାର ଉପଲବ୍ଧ କରିବାକୁ")
, ac_turned_off: "AC ଚାଲୁ ହୋଇନାହିଁ"
, estimates_expiry_error: "ଅନୁମାନ ସମାପ୍ତ ହୋଇଛି। ଦୟାକରି ପୁନଃଚେଷ୍ଟା କରନ୍ତୁ।"
, estimates_expiry_error_and_fetch_again: "ଅନୁମାନ ସମାପ୍ତ ହୋଇଛି। ପୁନଃ ପାଉଥାନ୍ତି, କିଛି ମହୁର୍ତ୍ ପାଖରେ ଚେକ୍ କରନ୍ତୁ"
, quotes_expiry_error_and_fetch_again: "କୋଟ୍ ସମାପ୍ତ ହୋଇଛି। ଦୟାକରି କିଛି ସମୟ ଅପେକ୍ଷା କରନ୍ତୁ"
, pay_your_driver_by_cash_or_upi: "ଆପଣଙ୍କ ଡ୍ରାଇଭରକୁ ନକଦ ଅଥବା UPI ଦ୍ୱାରା ଭୁଗତା କରନ୍ତୁ"
, trip_delayed: "ଯାତ୍ରା ବିଳମ୍ବିତ"
, select_vehicle: "ଯାନ ବାଛନ୍ତୁ"
, book_rental: "ଭଡା ବୁକ୍ କରନ୍ତୁ"
, confirm_rental: "ଭଡାକୁ ନିଶ୍ଚିତ କରନ୍ତୁ"
, rental_ride: "ଭଡା ରାଇଡ୍"
, select_duration: "ସମୟ ଚୟନ କରନ୍ତୁ"
, select_distance: "ଦୂରତା ଚୟନ କରନ୍ତୁ"
, rental_options: "ଭଡା ବିକଳ୍ପଗୁଡିକ"
, booking_on: "ବୁକିଂ ଅନ୍"
, included_kms: "ସମାବିଷ୍ଟ କିମି:"
, base_fare: "ଆଧାର ଭାଡ଼ା:"
, tolls_and_parking_fees: "ଟୋଲ୍ ଏବଂ ପାର୍କିଂ ଶୁଳ୍କ"
, final_fare_description: "ଅନ୍ତିମ ଭାଡା ଆସଲିକ ଯାତ୍ରା ସମୟ ଉପରେ ଆଧାରିତ"
, excess_distance_charge_description: (\charges -> "ଅତିରିକ୍ତ ଦୂରତା ରେ ଚାର୍ଜ " <> charges)
, additional_charges_description: "ଅନ୍ତିମ ଭାଡା ଆସଲିକ ଯାତ୍ରା ସମୟ ଏବଂ ଦୂରତାର ଉପରେ ଆଧାରିତ"
, parking_fees_and_tolls_not_included: "ପାର୍କିଂ ଶୁଳ୍କ , <b> ଟୋଲ୍ ଚାର୍ଜ </b> ଏବଂ ଅନ୍ୟାନ୍ୟ ସର୍ଚାର୍ଜ <b> ଅନ୍ତର୍ଭୁକ୍ତ ନୁହେଁ </b>। ଦୟାକରି ସେଗୁଡ଼ିକ ଡ୍ରାଇଭରକୁ ଆଲଗାଭାବେ ଭୁଗତା କରନ୍ତୁ।"
, night_time_fee_description: "ଏକ ସମତଳ ରାତି ସମୟ ଚାର୍ଜ ଦିଆଯାଇପାରିବ ଯଦି ଆପଣଙ୍କ ଯାତ୍ରା ଆରମ୍ଭ/ଶେଷ ସମୟ 10:00 PM ଏବଂ 5:00 AM ମଧ୍ୟରେ ଅଛି"
, choose_your_rental_ride: "ଆପଣଙ୍କର ଭଡା ରାଇଡ୍ ବାଛନ୍ତୁ"
, first_stop_optional: "ପ୍ରଥମ ବିରାମ (ଇଚ୍ଛାନୁସାରେ)"
, january: "ଜାନୁଆରୀ"
, february: "ଫେବ୍ରୁଆରୀ"
, march: "ମାର୍ଚ୍ଚ"
, april: "ଏପ୍ରିଲ୍"
, may: "ମେ"
, june: "ଜୁନ୍"
, july: "ଜୁଲାଇ"
, august: "ଅଗଷ୍ଟ"
, september: "ସେପ୍ଟେମ୍ବର୍"
, october: "ଅକ୍ଟୋବର୍"
, november: "ନଭେମ୍ବର୍"
, december: "ଡିସେମ୍ବର୍"
, hours: "ଘଣ୍ଟା"
, not_added_yet: "ଏପର୍ଯ୍ୟନ୍ତ ଯୋଡାଯାଇନାହିଁ"
, next_stop: "ପରବର୍ତ୍ତୀ ବିରାମ"
, time: "ସମୟ"
, distance: "ଦୂରତା"
, starting_odo: "ଆରମ୍ଭ ଓଡୋମିଟର୍"
, end_otp: "ଶେଷ OTP"
, only_location_within_city_limits: "ସହର ସୀମା ମଧ୍ୟରେ ଅବସ୍ଥିତ ବିକଳ୍ପମାନଙ୍କ ପାଇଁ ଭଡା ଯାତ୍ରା ଉପଲବ୍ଧ"
, ride_time: "ଯାତ୍ରା ସମୟ"
, ride_distance: "ଯାତ୍ରା ଦୂରତା"
, ride_started_at: "ଯାତ୍ରା ଆରମ୍ଭ"
, ride_ended_at: "ଯାତ୍ରା ଶେଷ"
, estimated_fare: "ଅନୁମାନିତ ଭାଡା"
, extra_time_fare: "ଅତିରିକ୍ତ ସମୟ ଭାଡା"
, total_fare: "ମୋଟ ଭାଡା"
, fare_update: "ଭାଡା ଅଦ୍ୟତନ"
, now: "ବର୍ତ୍ତମାନ"
, date_invalid_message: "ତାରିଖ ଅବୈଧ। ଅନୁମାନିତ ବୁକିଂ ସୀମାବଦ୍ଧ ଦିନ ପର୍ଯ୍ୟନ୍ତ ଉପଲବ୍ଧ"
, edit_pickup: "ପିକ୍ ଅବସ୍ଥାନ ସମ୍ପାଦନା"
, add_stop: "ଏକ ବିରାମ ଯୋଡନ୍ତୁ"
, enter_pickup_loc: "ଉଠା ଅବସ୍ଥାନ ପ୍ରବେଶ କରନ୍ତୁ"
, intercity_options: "ଆନ୍ତରିକ ବିକଳ୍ପଗୁଡିକ"
, proceed: "ଅଗ୍ରଗତି କରନ୍ତୁ"
, schedule_ride_available: "କାର୍ଯ୍ୟକ୍ରମ ଅବଶ୍ୟକତା ପରେ ଅର୍ଥାତ 30 ମିନିଟ୍ ଭିତରେ"
, rental_ride_until: "ଆପଣ ଏକ ଭଡା ଯାତ୍ରାରେ ଅଛନ୍ତି "
, extra_time_charges: "ଅତିରିକ୍ତ ସମୟ ଚାର୍ଜ"
, dist_based_charges: "ଦୂରତା ଆଧାରିତ ଚାର୍ଜ"
, time_based_charges: "ସମୟ ଆଧାରିତ ଚାର୍ଜ"
, rental_policy: "ଭଡା ନୀତି"
, select_package: "ପ୍ୟାକେଜ୍ ବାଛନ୍ତୁ"
, rental_policy_desc: "ପ୍ରତ୍ୟେକ ଘଣ୍ଟାରେ ପ୍ୟାକେଜରେ 10 କିମି ଦିଆଯାଇଥାଏ। ଅତିରିକ୍ତ କିମି ଯୋଡ଼ି ଅଧିକ ମୂଲ୍ୟରେ ସଂରକ୍ଷଣ କରିପାରିବେ।"
, rental_policy_desc_1: "ବୁକିଂ ପ୍ରତ୍ୟାବର୍ତ୍ତନ ପୂର୍ବରୁ ତାରିଫ ପୁନଃପରିକ୍ଷା କରନ୍ତୁ"
, rentals_intercity_available: (\appName -> "ରେଣ୍ଟାଲ୍ ଏବଂ ଆନ୍ତରିକ ଯାତ୍ରା ବର୍ତ୍ତମାନ " <> appName <> "ରେ ଉପଲବ୍ଧ")
, check_it_out: "ଦେଖନ୍ତୁ"
, failed_to_cancel: "ରାଇଡ୍ ବାତିଲ୍ ହେବାରେ ବିଫଳ"
, scheduling_allowed_in_intercity_rental: "ଶେଡ୍ୟୁଲ୍ କେବଳ ଆନ୍ତରିକ କିମ୍ବା ଭଡା ରାଇଡରେ ଅନୁମତି"
, special_zone_intercity_ineligible: "ବିଶେଷ ଅଞ୍ଚଳ ମଧ୍ୟରେ ଆନ୍ତରିକ ଯାତ୍ରାରେ ଅଯୋଗ୍ୟ"
, no_rides_scheduled_yet: "ଏଯାବତ୍ କୌଣସି ଯାତ୍ରା ଶେଡ୍ୟୁଲ୍ ହୋଇନାହିଁ!"
, ride_booking: "ରାଇଡ୍ ବୁକିଂ"
, special_zone_rental_ineligible: "ବିଶେଷ ଅଞ୍ଚଳ ଭିତରରେ ରେଣ୍ଟାଲ ଯାତ୍ରା ଅଯୋଗ୍ୟ"
, services: "ସେବାମାନ"
, you_have_upcoming_rental_booking: (\bookingTime -> "ଆପଣଙ୍କର ଆଗାମୀ ଭଡା ବୁକିଂ ଅଛି <br><b>" <> bookingTime <> "</b>")
, you_have_upcoming_intercity_booking: (\bookingTime -> "ଆପଣଙ୍କର ଆଗାମୀ ଆନ୍ତରିକ ବୁକିଂ <br><b>" <> bookingTime <> "</b>")
, you_have_an_upcoming_booking: (\bookingTime -> "ଆପଣଙ୍କର ଆଗାମୀ ବୁକିଂ <b>" <> bookingTime <> "</b>")
, scheduled: "ଶେଡ୍ୟୁଲ୍ କରାଯାଇଛି"
, upcoming_bookings: "ଆପଣଙ୍କର ଆସନ୍ତା ବୁକିଂ ଅଛି"
, rentals_: "ରେଣ୍ଟାଲ୍"
, inter_city_: "ଆନ୍ତରିକ"
, a_ride_already_exists: "ଏକ ରାଇଡ୍ ପୂର୍ବରୁ ଅଛି"
, you_have_an_ride_from_to_scheduled_from_till: "ଆପଣଙ୍କର {} ରାଇଡ୍ {} ରୁ {} ରେ ଯାଇଛି ଯାହା ଆରମ୍ଭ ହୋଇଛି {} ରୁ {} ପର୍ଯ୍ୟନ୍ତ।"
, you_have_an_ride_from_without_to: "ଆପଣଙ୍କର {} ରାଇଡ୍ ଆରମ୍ଭ ହୋଇଛି {} ରୁ {} ପର୍ଯ୍ୟନ୍ତ।"
, extra_per_km_fare: "ଅତିରିକ୍ତ ପ୍ରତି କିମି ଭାଡ଼ା"
, extra_per_minute_fare: "ଅତିରିକ୍ତ ପ୍ରତି ମିନିଟ୍ ଭାଡ଼ା"
, pickup_charges: "ଉଠାନ୍ତୁ ଚାର୍ଜ"
, waiting_charges_after_3_mins: "ଅପେକ୍ଷା ଚାର୍ଜ (3 ମିନିଟ୍ ପରେ)"
, fare_determined_as_per_karnataka_guidelines: "ଭାଡ଼ା କର୍ଣ୍ଣାଟକ ସରକାର ନୀତି ଅନୁସାରେ ନିର୍ଦ୍ଧାରିତ"
, rental_charges: "ଭଡା ଚାର୍ଜ"
, rental_info_policy_desc: (\inclusiveKms -> " " <> inclusiveKms <> " ପ୍ରତି ଘଣ୍ଟାରେ ଭଡାରେ ଆପଣଙ୍କ ପ୍ୟାକେଜ୍ ମଧ୍ୟରେ ସଂଯୋଜିତ")
, rental_info_policy_desc_: "ଯଦି ଆଧାରିତ ଦୂରତା ପ୍ରର୍ଯ୍ୟାପ୍ତ ନୁହେଁ, ଅଧିକ କିମି ଯୋଡ଼ି ସଂରକ୍ଷଣ କରିପାରିବେ"
, rental_screen_explainer: "ଏହିପରି ଅଧିକ ଦୂରତା ପାଇଁ ଅଧିକ ଚାର୍ଜକୁ ଏଡ଼ାଇପାରିବେ।"
, instant: "ତତ୍କ୍ଷଣାତ୍"
, coming_soon: "ଶୀଘ୍ର ଆସୁଛି"
, cancel_scheduled_ride: "ନିର୍ଦ୍ଧାରିତ ରାଇଡ୍ ବାତିଲ୍ କରନ୍ତୁ"
, cancel_scheduled_ride_desc: "ଆପଣ ନିଶ୍ଚିତ ଯେ ଏହି ରାଇଡ୍ ବାତିଲ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି?<br><br>(ଏକାଧିକ ବାତିଲ୍ ଅନୁରୋଧ କଲେ ଆପଣଙ୍କୁ ଅଧିକ ରାଇଡରୁ ଅବରୋଧ କରାଯାଇପାରେ)"
, confirm_cancellation: "ବାତିଲ କରିବାକୁ ନିଶ୍ଚିତ କରନ୍ତୁ"
, intercity_rides_coming_soon: "ଆନ୍ତରିକ ଯାତ୍ରା ଶୀଘ୍ର ଆସୁଛି!"
, view_fares: "ଭାଡ଼ା ଦେଖନ୍ତୁ"
, excess_time_description: (\charges -> "ଅତିରିକ୍ତ ସମୟ " <> charges)
, estimated_charges: "ଅନୁମାନିତ ଚାର୍ଜ"
, your_cancellation_rate_is_high: "ଆପଣଙ୍କର ବାତିଲକରଣ ହାର ଅଧିକ!"
, avoid_further_cancellations_to_keep_using_app: (\appName -> appName <> " ବ୍ୟବହାର ଜାରି ରଖିବା ପାଇଁ ଆଗକୁ ବାତିଲକରଣକୁ ଏଡାନ୍ତୁ।")
, night_time_fees: "ରାତି ସମୟର ଚାର୍ଜ"
, parking_and_other_charges: "ପାର୍କିଂ ଏବଂ ଅନ୍ୟାନ୍ୟ ଚାର୍ଜ"
, additional_charges: "ଅତିରିକ୍ତ ଚାର୍ଜ"
, estimated_base_fare: "ଅନୁମାନିତ ଆଧାରିତ ଭାଡ଼ା"
, included_distance: "ସଂଯୋଜିତ ଦୂରତା"
, included_time: "ସଂଯୋଜିତ ସମୟ"
, toll_charges_description: "ଟୋଲ୍ ଚାର୍ଜ ଅନ୍ତିମ ଭାଡାରେ ଯୋଡାଯିବ"
, will_be_added_to_final_fare: "ଅନ୍ତିମ ଭାଡାରେ ଯୋଡାଯିବ"
, extra_distance_fare: "ଅତିରିକ୍ତ ଦୂରତା ଭାଡା"
, network_error: "ନେଟୱର୍କ ତ୍ରୁଟି"
, server_error: "ସର୍ଭର ତ୍ରୁଟି"
, unknown_error: "ଅଜଣା ତ୍ରୁଟି"
, connection_refused: "ସଂଯୋଗ ବାରଣ କରାଯାଇଛି"
, timeout: "ସମୟ ସମାପ୍ତ"
, was_toll_exp_smooth: "ଟୋଲ୍ ଅନୁଭବ ସମ୍ଭାବ୍ୟ ଥିଲା କି?"
, was_toll_exp_smooth_desc: "ଟୋଲ୍ ଚାର୍ଜ ହିସାବରେ ନିକୋଟ ସଂଗ୍ରହ କରାଯାଇଛି କି?"
, was_ride_safe: "ଆପଣଙ୍କର ଯାତ୍ରା ସୁରକ୍ଷିତ ଥିଲା କି?"
, was_ride_safe_desc: "ଆପଣଙ୍କ ଯାତ୍ରା ସୁରକ୍ଷିତ ଏବଂ ଚିନ୍ତାମୁକ୍ତ ଥିଲା କି?"
, was_driver_helpful: "ଡ୍ରାଇଭର ସାହାଯ୍ୟକାରୀ ଥିଲେ କି?"
, was_driver_helpful_desc: "ଡ୍ରାଇଭର ଆପଣଙ୍କ ଆବଶ୍ୟକତା ପାଇଁ ଆଶାପୂରଣ ଥିଲେ କି?"
, collect_toll_sep: "କେବଳ ଟୋଲ୍ ଚାର୍ଜ ପ୍ରସଙ୍ଗରେ ଆପଣ ଡ୍ରାଇଭରକୁ ଦେବାକୁ ପଡ଼ିବ"
, final_fare_excludes_toll: "ଅନ୍ତିମ ଭାଡାରେ ଟୋଲ୍ ଚାର୍ଜ ନାହିଁ"
, metro_banner_title: (\appName -> "ବୁକ୍ ମେଟ୍ରୋ ଟିକେଟ୍ " <> appName <> " ସହିତ!")
, view_on_google_maps: "ଗୁଗୁଲ୍ ମାପ୍ ରେ ଦେଖନ୍ତୁ"
, walking_directions_to_pickup: "ଉଠା ଦିଗ ଦେଖନ୍ତୁ"
, explore_city_with_us: (\city -> city <> " ସହିତ ସହର ଅନୁସନ୍ଧାନ")
, go_to_destination: (\destination -> destination <> " ପାଇଁ ଯାଆନ୍ତୁ")
, walk_to: (\address -> "ଟାଳନ୍ତୁ" <> address)
, bangalore: "ବାଙ୍ଗାଲୋର୍"
, kolkata: "କୋଲକାତା"
, paris: "ପ୍ୟାରିସ୍"
, kochi: "କୋଚି"
, delhi: "ଦିଲ୍ଲୀ"
, hyderabad: "ହାଇଦରାବାଦ"
, mumbai: "ମୁମ୍ବାଇ"
, chennai: "ଚେନ୍ନାଇ"
, coimbatore: "କୋଇମ୍ବାଟୋର୍"
, pondicherry: "ପୂଦୁଚେରି"
, goa: "ଗୋଆ"
, pune: "ପୁଣେ"
, mysore: "ମଇସୋର୍"
, tumakuru: "ତୁମକୁରୁ"
, noida: "ନୋଇଡା"
, gurugram: "ଗୁରୁଗ୍ରାମ୍"
, waiting_charges: "ଅପେକ୍ଷା ଚାର୍ଜ"
, place_a_call: "ଏକ କଲ୍ କରନ୍ତୁ"
, you_can_write_to_us_at: "ଆପଣ ଆମକୁ ଏହି ଠାରେ ଲେଖିପାରନ୍ତି"
, chargeable: "ଚାର୍ଜ ଯୋଗ୍ୟ"
, booked: "ବୁକ୍ କରାଯାଇଛି"
, surcharges: "ଅତିରିକ୍ତ ଚାର୍ଜ"
, siliguri: "ସିଲିଗୁରି"
, kozhikode: "କୋଜିକୋଡ୍"
, thrissur: "ଥ୍ରିଶୁର୍"
, metro_free_ticket_event: (\freeTicketInterval -> "ପ୍ରତ୍ୟେକ " <> freeTicketInterval <> " ଟିକେଟ୍ ମାଗଣା!")
, metro_free_ticket_event_desc: (\freeTicketInterval maxFreeTicketCashback -> "ପ୍ରତ୍ୟେକ " <> freeTicketInterval <> " ଟିକେଟ୍ ରେ ମାଗଣା ଟିକେଟ୍ (ଅଧିକତମ ₹" <> maxFreeTicketCashback <> ") ପାନ୍ତି (ONDC ଆଫର)")
, next_free_ticket: "ପରବର୍ତ୍ତୀ ଟିକେଟ୍ କ୍ୟାସବାକ୍ ପାଇଁ ଯୋଗ୍ୟ"
, free_ticket_available: (\maxCashback freeTicketCount -> maxCashback <> " ଟିକେଟରେ ଅଫର ଆବଶ୍ୟକ!")
, additional_charges_will_be_applicable: "ଅଧିକ ଚାର୍ଜ ଲାଗିପାରେ ଡ୍ରାଇଭର ଉଠା ଅବସ୍ଥାନ ପାଖରେ ଥିବା ବେଳେ"
, parking_charges_included: (\amount -> amount <> " ପାର୍କିଂ ଚାର୍ଜ ସମାବେଶ ହୋଇଛି")
, app_toll_charges: "ଟୋଲ୍ ଚାର୍ଜ ସମାବେଶ ହୋଇଛି"
, app_parking_charges: "ପାର୍କିଂ ଚାର୍ଜ ସମାବେଶ ହୋଇଛି"
, app_toll_parking_charges: "ଟୋଲ୍ ଏବଂ ପାର୍କିଂ ଚାର୍ଜ ସମାବେଶ ହୋଇଛି"
, parking_charges_desc: "ପାର୍କିଂ ଚାର୍ଜ ଉଠା ଅବସ୍ଥାନରେ ତାଳିବା ପାଇଁ ଡ୍ରାଇଭରକୁ ଦିଆଯାଉଥିବା ଚାର୍ଜରେ ଆଧାରିତ"
, toll_charges_included_in_fair: "ଟୋଲ୍ ଚାର୍ଜ ଭାଡାରେ ଏବଂ ସମାବେଶ ହୋଇଛି"
, please_do_not_pay_extra_to_driver: "ଅଧିକ ଭୁଗତା ଡ୍ରାଇଭରକୁ କରନ୍ତୁନାହିଁ"
, vellore: "ଭେଲୋର୍"
, hosur: "ହୋସୁର୍"
, madurai: "ମଦୁରାଇ"
, thanjavur: "ଥଞ୍ଜାଭୁର୍"
, tirunelveli: "ତିରୁନେଲଭେଲି"
, salem: "ସାଲେମ୍"
, trichy: "ତ୍ରିଚି"
, davanagere: "ଦାବାନାଗେରେ"
, shivamogga: "ଶିଭମୋଗା"
, hubli: "ହୁବ୍ଲି"
, mangalore: "ମଙ୍ଗାଲୋର୍"
, odisha: "ଓଡ଼ିଶା"
, bhubaneswar: "ଭୁବନେଶ୍ୱର"
, gulbarga: "ଗୁଲବର୍ଗା"
, udupi: "ଉଡୁପି"
, cancel_booking_: "ବୁକିଂ ବାତିଲ୍"
, cancel_intercity_booking: "ଆନ୍ତରିକ ବୁକିଂ ବାତିଲ୍ କରନ୍ତୁ"
, rental_booking: "ଭଡା ବୁକିଂ"
, intercity_booking: "ଆନ୍ତରିକ ବୁକିଂ"
, booking: "ବୁକିଂ"
, by: "ଦ୍ୱାରା"
, customers: "ଗ୍ରାହକମାନେ"
, rating: "ମୂଲ୍ୟାନ୍କନ"
, cancellation: "ବାତିଲ"
, trips: "ଯାତ୍ରାମାନେ"
, i_speak: "ମୁଁ କହେ"
, with_nammayatri_for: (\years -> "ନମ୍ମାଯାତ୍ରୀ ସହିତ " <> years <> "+ ବର୍ଷ")
, years: "ବର୍ଷ"
, vehicle_number: "ଯାନ ନମ୍ବର: "
, what_people_say: "ଲୋକମାନେ କି ରହିଛନ୍ତି"
, star_rating: "ତାରା ମୂଲ୍ୟାନ୍କନ!"
, card_texts: " ଆମ ଗ୍ରାହକମାନଙ୍କ ମନକୁ ଅନୁସାରିତ କରାଯାଇଛି।"
, trainings_i_completed: "ମୁଁ ସମାପ୍ତ କରିଛି"
, i_pledge: "✋🏼  ମୁଁ ପ୍ରତିଞ୍ଜା କରୁଛି"
, clean_bike: "ସଫା ବାଇକ୍"
, uncomfortable_bike: "ଅସୁବିଧାଜନକ ବାଇକ୍"
, driver_available: "ଡ୍ରାଇଭର ଉପଲବ୍ଧ"
, drivers_available: "ଡ୍ରାଇଭରମାନେ ଉପଲବ୍ଧ"
, more_safety_measures: "ଅଧିକ ସୁରକ୍ଷା ପଦକ୍ଷେପ"
, safety_setup: "ସୁରକ୍ଷା ସେଟ୍ ଅପ୍"
, complete: "ସମାପ୍ତ"
, trusted_contact_help: "ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କ କିପରି ସାହାଯ୍ୟ କରିପାରିବ?"
, driver_safety_standards: "ଡ୍ରାଇଭର ସୁରକ୍ଷା ମାନଦଣ୍ଡ"
, trusted_contact_highlight: "✨ ଲାଇଭ୍ ଟ୍ରାକିଂ ଏବଂ ଆପ୍ ଭିତରରେ ଚାଟ୍ ସକ୍ରିୟ କରନ୍ତୁ"
, trusted_contact: "ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କ"
, safety_drill: "ସୁରକ୍ଷା ଅଭ୍ୟାସ"
, default_contact: "ଡିଫଲ୍ଟ ସମ୍ପର୍କ"
, app_call_chat: "ଆପ୍ ଭିତରରେ ଚାଟ୍ ଏବଂ କଲ୍"
, trusted_contact_desc: "ଆପଣଙ୍କ ଯାତ୍ରା ସମୟରେ ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କ ସହିତ ଚାଟ୍ କରନ୍ତୁ"
, enable_live_tracking: "ଲାଇଭ୍ ରାଇଡ୍ ଟ୍ରାକିଂ ସକ୍ରିୟ କରନ୍ତୁ"
, unexpected_event_check: "ଅପେକ୍ଷା ଭିନ୍ନ ଘଟଣା ଯାଞ୍ଚ"
, unexpected_event_check_desc: "ପଥବିଚ୍ୟୁତିରେ ନୋଟିଫିକେସନ୍ ପାନ୍ତି"
, unexpected_event_check_timings: "ଅପେକ୍ଷା ଭିନ୍ନ ଘଟଣା ଯାଞ୍ଚ ସମୟ"
, next: "ପରେ"
, post_ride_check: "ରାଇଡ୍ ପରେ ଯାଞ୍ଚ"
, post_ride_check_desc: "ଆପଣଙ୍କ ଯାତ୍ରା ସମାପ୍ତ ହେଲାପରେ ଯାଞ୍ଚ ନୋଟିଫିକେସନ୍ ପାନ୍ତି। ପ୍ରତିକ୍ରିୟା ନଥିଲେ ଆପମାଟିକ୍ କଲ୍ ହୋଇଥାଏ"
, post_ride_check_timings: "ରାଇଡ୍ ପରେ ଯାଞ୍ଚ ସମୟ"
, safety_team_notification: "ସୁରକ୍ଷା ଟିମ୍ ନୋଟିଫିକେସନ୍"
, notify_safety_team: "ସୁରକ୍ଷା ଟିମ୍କୁ ସୂଚନା କରନ୍ତୁ"
, notify_safety_team_sub: "ସୁରକ୍ଷା ଯାଞ୍ଚରେ କାର୍ଯ୍ୟ ନ ହେଲେ, ସୁରକ୍ଷା ଟିମ୍ ସୂଚନା ପାଇବ।"
, notify_safety_team_note: "ଆପଣଙ୍କ ସୁରକ୍ଷା ପାଇଁ ସୁରକ୍ଷା ଟିମ୍ ଫୋନ୍ କରିପାରନ୍ତି।"
, emergency_sos_new: "ଜରୁରୀ - SOS"
, emergency_sos_sub: "SOS ବଟନ୍ ଆପଣଙ୍କ ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କ, 24/7 ସୁରକ୍ଷା ଟିମ୍ କୁ ସୂଚନା ଦେଇ ସ୍ୱତଃ ସମ୍ପର୍କ କରେ"
, shake_to_activate: "କାମ କରିବା ପାଇଁ ଟାଣିବା"
, shake_to_activate_sub: (\appname -> "ଆପଣ ଯାତ୍ରା ସମୟରେ " <> appname <> " ଆପ୍ ଭିତରେ ଏହାକୁ ଅକ୍ସେସ୍ କରିପାରିବେ।")
, automatic_call_sos: "ଜରୁରୀ ସମୟରେ ସ୍ୱତଃ କଲ୍"
, automatic_call_sos_sub: "ଆପଣକୁ ଏକ ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କ ବାଛିବା ପାଇଁ ସୁବିଧା ପ୍ରଦାନ କରନ୍ତି"
, place_default_call: "ଡିଫଲ୍ଟ ସମ୍ପର୍କରେ କଲ୍"
, default_call_contact: "ଡିଫଲ୍ଟ କଲ୍ ସମ୍ପର୍କ"
, default_contact_desc: "ଆପଣ ସୁରକ୍ଷା ସେଟିଙ୍ଗରୁ ଆପଣଙ୍କ ଡିଫଲ୍ଟ ସମ୍ପର୍କ ବଦଳାଇପାରିବେ"
, more_emergency_actions: "ଅଧିକ ଜରୁରୀ କାର୍ଯ୍ୟଗୁଡିକ"
, siren: "ସାଇରେନ"
, call_police_desc: "ସରାସରି ନିକଟତମ ପୋଲିସ୍ କେନ୍ଦ୍ରକୁ କଲ୍"
, record_audio_desc: "ଯଦି ଏକ ବାଦ ଅବସ୍ଥା କିମ୍ବା ଜରୁରୀ ଘଟଣା ହେଲା, ଅଡିଓ ରେକର୍ଡ କରିପାରିବେ"
, siren_desc: "ଉଚ୍ଚ ଶବ୍ଦ ସାଧନ କରି ଜନସମୁଦାୟକୁ ଆଲର୍ଟ୍ କରନ୍ତୁ"
, call_safety_team_desc: "କଲ୍ କରନ୍ତୁ 24/7 ସୁରକ୍ଷା ଟିମ୍"
, safety_drill_desc: "ଅଗାମୀ ସ୍କ୍ରିନରେ ସମସ୍ତ ଜରୁରୀ କାର୍ଯ୍ୟଗୁଡିକ ଟେଷ୍ଟ କରିପାରିବେ।"
, safety_drill_sub: "<i>‘ପୋଲିସ୍ କଲ୍ କରନ୍ତୁ’</i> ଏବଂ <i>‘ସୁରକ୍ଷା ଟିମ୍କୁ କଲ୍ କରନ୍ତୁ’</i> ଟେଷ୍ଟ ପାଇଁ ଅକ୍ଷମ ରହିଛି"
, safety_drill_note: "ଯାତ୍ରା ସୁରକ୍ଷା ପରୀକ୍ଷା ଭିତରେ ଆପଣଙ୍କର ଜରୁରୀ ସମ୍ପର୍କକୁ ସୂଚନା ଦିଅନ୍ତୁ"
, ride_actions: "ରାଇଡ୍ କାର୍ଯ୍ୟଗୁଡିକ"
, ride_actions_sub: "ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କ ଭାବରେ, ଆପଣ ସମସ୍ତ ସେୟାର ଯାତ୍ରାରେ ଏହି କାର୍ଯ୍ୟଗୁଡିକ କରିପାରିବେ"
, live_tracking: "ଲାଇଭ୍ ଟ୍ରାକିଂ"
, live_tracking_sub: "ଆପଣଙ୍କ ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କ ଯାତ୍ରା ଆରମ୍ଭ କଲେ ଏବଂ ଲାଇଭ୍ ଟ୍ରାକିଂ କରନ୍ତୁ"
, chat_with_rider: "ଯାତ୍ରୀ ସହିତ ଚାଟ୍ କରନ୍ତୁ"
, chat_with_rider_sub: "ଆପ୍ ଭିତରରେ ଚାଟ୍ କରି ଯାତ୍ରୀ ସହିତ ସମ୍ପର୍କରେ ରହିପାରନ୍ତି"
, emergency_actions_sub: "SOS ସକ୍ରିୟତାରେ ଜରୁରୀ କାର୍ଯ୍ୟଗୁଡିକ କରିପାରନ୍ତି"
, current_initiatives: "ସମକାଲୀନ ପ୍ରୟାସଗୁଡିକ"
, current_initiatives_sub: "ଏକାଧିକ ପଦକ୍ଷେପ ମାଧ୍ୟମରେ ଆମେ ସୁରକ୍ଷା ସୁନିଶ୍ଚିତ କରୁଛୁ।"
, driver_verification: "ଡ୍ରାଇଭର ଭେରିଫିକେସନ୍"
, driver_verification_sub: "ସମସ୍ତ ଡ୍ରାଇଭରମାନେ ପୋଲିସ୍ ସହିତ ତଥ୍ୟଗତ ଭେରିଫିକେସନ୍ ପାଇଥାନ୍ତି।"
, safety_feedback: "ସୁରକ୍ଷା ପ୍ରତିକ୍ରିୟା"
, safety_feedback_sub: "SOS ସ୍ଥିତିରେ ଆମେ ଦିଆଯାଇଥିବା ଅଭିଯୋଗ ଗୁଡିକୁ ଗୁରୁତ୍ଵ ଦିଅନ୍ତୁ।"
, safety_training: "ସୁରକ୍ଷା ପ୍ରଶିକ୍ଷଣ"
, safety_training_sub: "ଡ୍ରାଇଭରମାନେ ଆବଶ୍ୟକ ପ୍ରଶିକ୍ଷଣ ଏବଂ ଲାଇଭ୍ ସୁରକ୍ଷା ଏବଂ ସେବା ନୀତି ମେଟାକରନ୍ତି।"
, driver_id_check: "ଡ୍ରାଇଭର ଆଇଡି ଯାଞ୍ଚ"
, driver_id_check_sub: "ଏକାଧିକ ସମୟରେ ଡ୍ରାଇଭରଙ୍କୁ ତାଙ୍କର ଚିହ୍ନ ପରୀକ୍ଷା କରାଯାଇପାରିବ।"
, data_privacy: "ତଥ୍ୟ ଗୋପନୀୟତା"
, data_privacy_sub: "ଡ୍ରାଇଭର ଆପଣଙ୍କ ଫୋନ୍ ନମ୍ବର ନାହିଁ, ଆପଣ ଆଜିବା ବେଳେ ତାଙ୍କରେ ଏକ ଅନାମିକା ବନାଇପାରନ୍ତି।"
, favourite_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭରକୁ ପ୍ରିୟ କରନ୍ତୁ"
, favourite_driver_sub: "ଆପଣ ତାଙ୍କୁ ଆସନ୍ତା କାର୍ଯ୍ୟଗୁଡିକରେ ପ୍ରାଥମିକତା ଦେବାକୁ ପାଇଁ ପ୍ରିୟ କରିପାରନ୍ତି।"
, women_drivers: "ମହିଳା ଡ୍ରାଇଭରମାନେ"
, women_drivers_sub: "ଏକ ବିକଳ୍ପ ଦେବାକୁ ମହିଳା ଯାତ୍ରୀମାନେ ମହିଳା ଡ୍ରାଇଭର ଚୟନ କରିପାରିବେ।"
, dashcam: "ଡ୍ୟାଶକ୍ୟାମ୍"
, dashcam_sub: "ଅଧିକ ସଂଖ୍ୟାରେ ଡ୍ୟାଶକ୍ୟାମ୍ ଯୋଗାଯୋଗ କରିପାରନ୍ତି।"
, never_share_ln: "ଅନ୍ୟ ସମୟରେ"
, always_share_ln: "ସମସ୍ତ ଯାତ୍ରାରେ"
, share_with_time_constraints_ln: "କେବଳ ରାତିରେ ଯାତ୍ରାରେ (9PM - 6AM)"
, never_share_em: "ମୁଁ ମାନେ ସ୍ୱୟଂ ସେୟାର କରିବି"
, always_share_em: "ସମସ୍ତ ଯାତ୍ରା ସ୍ୱୟଂ ସେୟାର କରାଯାଇଛି"
, share_with_time_constraints_em: "ସମସ୍ତ ରାତିରେ ସେୟାର (9PM - 6AM)"
, live_ride_tracking: "ଲାଇଭ୍ ରାଇଡ୍ ଟ୍ରାକିଂ"
, live_ride_tracking_desc: "ଆପଣ ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କକୁ ସେୟାର କରିବା ପାଇଁ ଟ୍ରାକିଂ ଏକ ଲିଙ୍କ ଆରମ୍ଭ କରନ୍ତୁ"
, upcoming_initiatives: "ଆସନ୍ତା ପଦକ୍ଷେପଗୁଡିକ"
, upcoming_initiatives_desc: "ଉପରୁପାୟ ସୁରକ୍ଷା ପାଇଁ ଆମେ ଆଗେଇବା ଉଦ୍ଦେଶ୍ୟରେ"
, receive_call_from_safety_team: "24/7 ସୁରକ୍ଷା ଟିମ୍ ଠାରୁ ଫୋନ୍ ହେବ"
, notify_all_emergency_contacts: "ସମସ୍ତ ଜରୁରୀ ସମ୍ପର୍କକୁ ସୂଚନା କରନ୍ତୁ"
, record_audio: "ଅଡିଓ ରେକର୍ଡ କରନ୍ତୁ"
, call_safety_team: "ସୁରକ୍ଷା ଟିମ୍କୁ କଲ୍ କରନ୍ତୁ"
, safety_team_callback_requested: "24/7 ସୁରକ୍ଷା ଟିମ୍ ଠାରୁ ଫୋନ୍ ହୋଇଥାଏ"
, emergency_contacts_notified: "ଜରୁରୀ ସମ୍ପର୍କ ସୂଚନା ପାଇଛି"
, call_placed: "କଲ୍ ସଂପର୍କ ସଂକ୍ଳନ କରାଯାଇଛି"
, emergency_sos_activated: "ଜରୁରୀ SOS ସକ୍ରିୟ ହୋଇଛି!"
, tap_to_call_other_emergency_contacts: "ଅନ୍ୟ ଜରୁରୀ ସମ୍ପର୍କକୁ କଲ୍ କରନ୍ତୁ"
, recording_audio: "ଅଡିଓ ରେକର୍ଡ କରୁଛି"
, recorded_audio: "ରେକର୍ଡ କରାଯାଇଥିବା ଅଡିଓ"
, share_with_safety_team: "ସୁରକ୍ଷା ଟିମ୍ ସହ ସେୟାର କରନ୍ତୁ"
, emergency: "ଜରୁରୀ"
, manual_live_tracking: "ମାନୁଆଲ୍ ଲାଇଭ୍ ଟ୍ରାକିଂ"
, manual_live_tracking_desc: "କାହା ସହିତ ଲାଇଭ୍ ଟ୍ରାକିଂ ଲିଙ୍କ ସେୟାର କରନ୍ତୁ"
, automatic_live_tracking: "ସ୍ୱତଃ ଲାଇଭ୍ ଟ୍ରାକିଂ"
, automatic_live_tracking_desc: "ଭରସାଯୋଗ୍ୟ ସମ୍ପର୍କ ସହିତ ରାଇଡ୍ ଟ୍ରାକିଂ ସେୟାର କରନ୍ତୁ"
, tracking_no_setup: "ଆପଣ ଏବେ ପର୍ଯ୍ୟନ୍ତ ଅଟୋମେଟିକ୍ ଲାଇଭ୍ ଟ୍ରାକିଂ ସେଟ୍ ଅପ୍ କରିନାହାନ୍ତି"
, following_str: "ଅନୁଗମନ କରୁଛି"
, dialing_police_in_time: (\time -> time <> " ରେ ପୋଲିସ୍ କୁ କଲ୍ କରାଯାଉଛି...")
, reached_destination: (\time -> "ହାଁ! ଗନ୍ତବ୍ୟ ସ୍ଥାନରେ ପହଞ୍ଚିଗଲା " <> time)
, mins: " ମିନିଟ୍"
, updated_fare: "ଭାଡ଼ା ଅଦ୍ୟତନ ହୋଇଛି"
, how's_trip: "ଆଜି ଆପଣଙ୍କ ଯାତ୍ରା କିପରି ଥିଲା?"
, provided_feedback: "ଅଭିପ୍ରାୟ ଦିଅନ୍ତୁ"
, favourite_your_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭରକୁ ପ୍ରିୟ କରନ୍ତୁ"
, prefer_driver: "ଏହି ଡ୍ରାଇଭରକୁ ଆପଣଙ୍କ ପରବର୍ତ୍ତୀ ବୁକିଂରେ ପ୍ରାଥମିକତା ଦିଅନ୍ତୁ।"
, write_review: "ଏକ ସମୀକ୍ଷା ଲେଖନ୍ତୁ"
, transit: "ଯାତ୍ରା"
, intercity_str: "ଆନ୍ତରିକ ଯାତ୍ରା"
, rental_str: "ଭଡା"
, intercity_bus: "ଆନ୍ତରିକ ବସ୍"
, where_are_you_going: "ଆପଣ କେଉଁଠାକୁ ଯାଉଛନ୍ତି?"
, tap_to_follow: "ଅନୁସରଣ କରିବାକୁ ଟାପ୍ କରନ୍ତୁ"
, has_shared_a_ride_with_you: (\name -> name <> " ଏକ ରାଇଡ୍ ସେୟାର କରିଛନ୍ତି। ଅନୁସରଣ କରିବାକୁ ଟାପ୍ କରନ୍ତୁ")
, test_sos_activated: "ଟେଷ୍ଟ SOS ସକ୍ରିୟ!"
, choose_from_contacts: "ସମ୍ପର୍କ ଠାରୁ ବାଛନ୍ତୁ"
, add_manually: "ମାନୁଆଲ୍ ଯୋଗ କରନ୍ତୁ"
, default_contact_not_set: "ଡିଫଲ୍ଟ ସମ୍ପର୍କ ସେଟ୍ ହୋଇନାହିଁ"
, driver: "ଡ୍ରାଇଭର"
, recommend_share_manually: "ଆପଣ ଶେୟାର କରିପାରନ୍ତି"
, more_about_me: "ମୋ ବିଷୟରେ ଅଧିକ"
, driving_since: "ଗତି କରୁଛି"
, driver_section_card: "ଏହି ସୂଚୀରେ ସମସ୍ତ ପ୍ରିୟ ଡ୍ରାଇଭର ଅଛନ୍ତି।"
, know_your_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭର କୁ ଜାଣନ୍ତୁ >"
, rated: "ମୂଲ୍ୟାନ୍କନ କରାଯାଇଛି"
, drivers: "ଡ୍ରାଇଭରମାନେ"
, locations: "ଅବସ୍ଥାନଗୁଡିକ"
, knows_your_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭରକୁ ଜାଣନ୍ତୁ"
, last_trip: "ଶେଷ ଯାତ୍ରା "
, rupees: "ରୁପିଆ"
, paid_by_cash: "ନକଦ ଦ୍ୱାରା ଅଦାନ କରାଯାଇଛି"
, remove_from_favourite: "ପ୍ରିୟ ଠାରୁ ବାହାର କରନ୍ତୁ"
, cannot_add_own_number: "ଆପଣଙ୍କ ନମ୍ବରକୁ ଜରୁରୀ ସମ୍ପର୍କ ଭାବରେ ଯୋଡି ପାରିବେ ନାହିଁ।"
, clean_vehicle: "ସଫା ଯାନ"
, ac_not_turned_on: "ଏ.ସି. ଚାଲୁ କରାଯାଇନାହିଁ"
, late_pick_up_arrival: "ଉଠା ଅବସରରେ ବିଲମ୍ବ"
, asked_for_more_fare: "ଅଧିକ ଭାଡ଼ା ଦାବି କରାଗଲା"
, unhygienic_vehicle: "ଅସ୍ୱଚ୍ଛ ଯାନ"
, training: "ଶିକ୍ଷା"
, financial: "ଆର୍ଥିକ"
, kids_education: "ଶିଶୁମାନଙ୍କ ଶିକ୍ଷା"
, buy_new_vehicle: "ନୂତନ ଯାନ କିଣନ୍ତୁ"
, failed_to_remove_driver: "ପ୍ରିୟ ଡ୍ରାଇଭରକୁ ବାହାର କରିବାରେ ବିଫଳ ହେଲା"
, not_available: "ଏହି ସମୟରେ ଉପଲବ୍ଧ ନାହିଁ"
, buy_new_home: "ନୂତନ ଘର କିଣନ୍ତୁ"
, you_favourited: "ଆପଣ ପ୍ରିୟ କରିଛନ୍ତି"
, favorite_your_driver: "ଆପଣଙ୍କ ଡ୍ରାଇଭରମାନଙ୍କୁ ପ୍ରିୟ କରନ୍ତୁ!"
, favourite_driver_preference: "ପ୍ରିୟ ଡ୍ରାଇଭରମାନେ ଆପଣଙ୍କ ପରବର୍ତ୍ତୀ ସନ୍ଧାନରେ ପସନ୍ଦ କରାଯିବେ।"
, ride_type_with_favourite_driver: "ଶୀଘ୍ର ଆପଣ ଆପଣଙ୍କ ପ୍ରିୟ ଡ୍ରାଇଭର ସହିତ ଆନ୍ତରିକ ରାସ୍ତା, ଭଡା ବା ପୁନରାବୃତ୍ତି ଯାତ୍ରା ସଜାଡ଼ିପାରିବେ"
, gotit: "ବୁଝିଲି"
, no_favourite_yet: "ଏଯାବତ୍ କୌଣସି ପ୍ରିୟ ଡ୍ରାଇଭର ନାହିଁ!"
, favourite_appear_here: "ଆପଣ ଯେ ଡ୍ରାଇଭରମାନଙ୍କୁ ପ୍ରିୟ କରିଛନ୍ତି ସେମାନେ ଏଠାରେ ଦେଖାଯିବେ"
, confirm_pickup_and_drop_location: "ଉଠା ଏବଂ ଛାଡ଼ିବା ଅବସ୍ଥାନ ନିଶ୍ଚିତ କରନ୍ତୁ"
, confirm_your_delivery: "ଆପଣଙ୍କ ବିତରଣକୁ ନିଶ୍ଚିତ କରନ୍ତୁ"
, payment_at_receiving_end: "ପ୍ରାପ୍ତ କରନ୍ତାଙ୍କ ପାଇଁ ଭୁଗତା"
, payment_at_receiving_end_desc: "ଛାଡ଼ିବା ସ୍ଥାନରେ ପାର୍ଟନର ସହିତ ଭୁଗତା ସମାପ୍ତ କରାଯିବ"
, sender: "ପ୍ରେଷକ"
, receiver: "ଗ୍ରାହକ"
, phone: (\str -> str <> " ଫୋନ୍")
, building_or_flat: (\str -> str <> " ବିଲ୍ଡିଙ୍ଗ/ଫ୍ଲାଟ୍ ନମ୍ବର")
, optional_instruction: "ନିର୍ଦ୍ଦେଶାବଳୀ (ଇଚ୍ଛାକୃତ)"
, help_us_provide_smooth_pickup: "ଆପଣଙ୍କୁ ସୁବିଧାପୂର୍ଣ୍ଣ ଉଠା ସେବା ଯୋଗାଇବାରେ ସାହାଯ୍ୟ କରନ୍ତୁ"
, help_us_provide_smooth_drop: "ଆପଣଙ୍କୁ ସୁବିଧାପୂର୍ଣ୍ଣ ଛାଡ଼ିବା ସେବା ଯୋଗାଇବାରେ ସାହାଯ୍ୟ କରନ୍ତୁ"
, i_am_the_sender: "ମୁଁ ପ୍ରେଷକ"
, i_am_the_receiver: "ମୁଁ ଗ୍ରାହକ"
, reckless_handling: "ଅବିବେକପୂର୍ଣ୍ଣ ହାତଲିଙ୍ଗ"
, delivery_delayed: "ବିତରଣ ବିଳମ୍ବ ହୋଇଛି"
, items_missing: "ବସ୍ତୁମାନ ନାହିଁ"
, polite_attitude: "ଶିଷ୍ଟ ଆଚରଣ"
, smooth_experience: "ସୁମଧୁର ଅନୁଭବ"
, secure_delivery: "ନିରାପଦ ବିତରଣ"
, minimal_calling: "ନିମ୍ନତମ ଫୋନ୍ କରିବା"
, rude_behaviour: "ଅଶିଷ୍ଟ ଆଚରଣ"
, package_photo_and_otp: "ପାକେଜ୍ ଫୋଟୋ ଏବଂ OTP"
, send_now: "ବର୍ତ୍ତମାନ ପଠାନ୍ତୁ"
, book_for: "ବୁକିଂ ପାଇଁ"
, delivery_details: "ବିତରଣ ବିବରଣୀ"
, delivery_guidelines: "ବିତରଣ ନିର୍ଦ୍ଦେଶାବଳୀ"
, view_all_guidelines: "ସମସ୍ତ ନିର୍ଦ୍ଦେଶାବଳୀ ଦେଖନ୍ତୁ"
, items_should_fit_in_backpack: (\str -> "ବସ୍ତାରେ ସମାବେଶ ହେବା ଉଚିତ (ଅଧିକତମ: " <> str <> "କିଲୋଗ୍ରାମ୍)")
, avoid_sending_high_value_items: "ଉଚ୍ଚ ମୂଲ୍ୟ ଏବଂ ଛୁଚ୍ଚରା ବସ୍ତୁ ପଠାଇବାକୁ ଏଡ଼ାନ୍ତୁ"
, illegal_items_prohibited: "ଅବୈଧ ଆଇଟମ୍ ମନା ରହିଛି"
, pickup_instruction: "ଉଠା ନିର୍ଦ୍ଦେଶାବଳୀ"
, edit_your_pickup_location_instead: "ଆପଣଙ୍କ ରାଇଡକୁ ବାତିଲ୍ କରିବା ପ୍ରତିବାଦରେ ଆପଣଙ୍କ ଉଠା ଅବସ୍ଥାନକୁ ସମ୍ପାଦନ କରନ୍ତୁ"
, round_trip_invalid_message: "ରାଉଣ୍ଡ ଟ୍ରିପ୍ ଅନୁମାନିତ ଯାତ୍ରା ସମୟରେ କମି ହୋଇପାରେନି"
, pickup_time_not_selected: "ଉଠା ସମୟ ବାଛନ୍ତୁ"
, booking_duration_invalid: "ବୁକିଂ କେବଳ ଦୁଇ ଦିନ ପର୍ଯ୍ୟନ୍ତ ଅନୁମତି ରହିଛି।"
, return: "ପୁନରାଗମନ"
, pickup_input: "ଉଠା ସମୟ ପ୍ରବେଶ କରନ୍ତୁ"
, return_input: "ପୁନରାଗମନ ସମୟ ପ୍ରବେଶ କରନ୍ତୁ"
, book_a_round_trip: "ସମଗ୍ର ବୁକିଂ ପାଇଁ କ୍ୟାବ୍ ଏବଂ ଡ୍ରାଇଭର ସେବା ରହିବେ।"
, total_ride_duration: "ମୋଟ ବୁକିଂ ସମୟ"
, total_ride_distance: "ମୋଟ ବୁକିଂ ଦୂରତା"
, ride: "ରାଇଡ୍"
, toll_charges_maybe_applicable: "ଟୋଲ୍ ଚାର୍ଜ ଲାଗିପାରେ"
, accept: "ସ୍ୱୀକାର କରନ୍ତୁ"
, pass: "ପାସ୍"
, term_1a: "1. ମୋଟ ଭାଡ଼ା ଆସଲିକ ପରିବେଶ ଉପରେ ଅଭିନିର୍ଣ୍ଣୟ କରାଯିବ।"
, term_2a: "2. ଟୋଲ୍ ଚାର୍ଜ କେବଳ ଟୋଲ୍ ରୋଡ଼ ଗ୍ରହଣ କଲେ ଲାଗିପାରେ।"
, term_3a: "3. କୌଣସି ପାର୍କିଂ ଚାର୍ଜ ଥାକିଲେ ଆଲଗାଭାବେ ଡ୍ରାଇଭର ସହିତ ସମାଧାନ କରିବାକୁ ପଡ଼ିବ।"
, term_1b: "1. ନିର୍ଦ୍ଧାରିତ ଯାତ୍ରାରେ ଆରମ୍ଭ ପୂର୍ବରୁ 1 ଘଣ୍ଟା ମଧ୍ୟରେ ବାତିଲ୍ କଲେ ଶିକାର କରିବାକୁ ପଡ଼ିବ।"
, term_2b: "2. ନିର୍ଦ୍ଧାରିତ ଯାତ୍ରା ଆରମ୍ଭ ପୂର୍ବରୁ 45 ମିନିଟ୍ ଅଗ୍ରଗତି ରହିବ।"
, term_3b: "3. ନିର୍ଦ୍ଧାରିତ ଯାତ୍ରା ସମୟରୁ 15 ମିନିଟ୍ ପୂର୍ବରୁ ଗ୍ରାହକ ଉଠା ଅବସ୍ଥାନକୁ ପହଞ୍ଚନ୍ତୁ।"
, excluded_charges: "ବାହାର କରାଯାଇଥିବା ଚାର୍ଜ"
, tolls: "ଟୋଲ୍"
, state_permit: "ରାଜ୍ୟ ଅନୁମତି"
, excluded_footer: "ଏହି ଚାର୍ଜଗୁଡିକୁ ଡ୍ରାଇଭରକୁ ଆଲଗାଭାବେ ଦିଅନ୍ତୁ।"
, included_charges: "ଅନ୍ତର୍ଭୁକ୍ତ ଚାର୍ଜ"
, inc_1: "*ଅଧିକ ଦୂରତା କିମ୍ବା ସମୟ ହେଲେ ଅଧିକ ଚାର୍ଜ ଲାଗିବ।"
, inc_2a: "ରାତିରେ ଭାଡ଼ା: ରାତି 10:00 ପମ୍ ରୁ 5:00 ଆମ୍ ପର୍ଯ୍ୟନ୍ତ ଆନ୍ତିମ ଭାଡ଼ାରେ ଅଧିକ ଲାଗିବ।"
, inc_2b: "ରାତି ଭାଡ଼ା: ନିର୍ଦ୍ଧାରିତ ସମୟ ମଧ୍ୟରେ ଭାଡ଼ାରେ ନିର୍ଦ୍ଧାରିତ ଚାର୍ଜ ଜୋଡାଯାଇବ।"
, pickup_drop: "ଉଠା ଏବଂ ଛାଡ଼ିବା"
, intercity_tc_1: "ଆପଣଙ୍କର ଭାଡ଼ା ଆସିବାକୁ ଅଧିକ ଦୂରତା ଥାକିଲେ ଅଧିକ ଲାଗିବ।"
, intercity_tc_2: "କୌଣସି ଆଇନସବୁରୁ ଦେୟ ଅଛି କି ସେମାନଙ୍କୁ ଡ୍ରାଇଭର ସହିତ ସମାଧାନ କରିବାକୁ ଏକ ଦାୟିତ୍ୱ ରହିଛି।"
, round_trip_policy_card_1: "ଧାରଣ କରାଯାଇଥିବା ସମୟ ସହିତ ଆପଣଙ୍କ ବୁକିଂରେ 1 ଘଣ୍ଟା ଯୋଡାଯାଇଛି।"
, round_trip_policy_card_2: "ପ୍ରତ୍ୟେକ ଅତିରିକ୍ତ ଘଣ୍ଟା ପାଇଁ ଆପଣଙ୍କର ପ୍ୟାକେଜ୍ ମଧ୍ୟରେ 10 କିଲୋମିଟର ଦୂରତା ଯୋଡାଯାଇବ।"
, round_trip_policy: "ରାଉଣ୍ଡ ଟ୍ରିପ୍ ନୀତି"
, distance_fare: "ଦୂରତା ଭାଡ଼ା"
, driver_allowance_: "ଡ୍ରାଇଭର ଭତ୍ତା*"
, night_charges: "ରାତିରେ ଚାର୍ଜ"
, night_charges_description: "ରାତିରେ ଭାଡ଼ାରେ ନିର୍ଦ୍ଧାରିତ ଚାର୍ଜ ହିସାବରେ ଜୋଡାଯାଇଥାଏ ଯାହାକି ଗ୍ରାହକ ତୁଳନାରେ ଏକ ଆବଶ୍ୟକ।"
, state_charges_description: "ରାଜ୍ୟ ଆଗମନ ଅନୁମତି ନୀତି ଭାଡ଼ାରେ ନାହିଁ, ଏହାକୁ ଗ୍ରାହକ ଡ୍ରାଇଭରକୁ ଦେବାକୁ ହେବ।"
, parking_charges_description: "ଯାତ୍ରା ଦୂରନ୍ତରେ ଜରିମାନା ଦେୟ ଥାକିଲେ ଗ୍ରାହକ ସଂକ୍ଷିପ୍ତରେ କରିବାକୁ ଦେବାକୁ ହେବ।"
, toll_and_parking_charges_description: "ଟୋଲ୍ ଚାର୍ଜ ନୀତିରେ ନାହିଁ, ଏହାକୁ ଆଲଗାଭାବେ ଗ୍ରାହକ ଡ୍ରାଇଭରକୁ ଦେବାକୁ ହେବ।"
, state_permit_charges: "ରାଜ୍ୟ ଅନୁମତି ଚାର୍ଜ"
, driver_allowance_description: (\driverAllowance driverMaxAllowance -> "ପ୍ରତ୍ୟେକ ଘଣ୍ଟାରେ ଡ୍ରାଇଭର ଭତ୍ତାରେ "<>driverAllowance<>" ଦିଆଯାଇଥାଏ। ସାଧାରଣ ଭତ୍ତା ସିମାକୁ ପ୍ରତ୍ୟେକ 24 ଘଣ୍ଟାରେ ରଖାଯାଇଥାଏ।")
, driver_allowance_required: "ଡ୍ରାଇଭର ଭତ୍ତା*"
, toll_and_parking_charges: "ଟୋଲ୍/ପାର୍କିଂ ଏବଂ ଅନୁମତି ଚାର୍ଜ"
, night_shift_charges: "ରାତି ସ୍ଥାନାନ୍ତରଣ ଚାର୍ଜ"
, round_trip_explainer: "(ଆପଣଙ୍କର ଆରମ୍ଭ ସ୍ଥାନରେ ପୁନଃ ଛାଡ଼ିବା ହେବ)"
, reserve: "ସଂରକ୍ଷଣ କରନ୍ତୁ"
, leave_now: "ଏବେ ଯାନ୍ତୁ"
, is_your_driver: "ଆପଣଙ୍କର ଡ୍ରାଇଭର"
, your_driver_will_be: "ଆପଣଙ୍କର ଡ୍ରାଇଭର 30 ମିନିଟ୍ ପୂର୍ବରୁ ଆସାଇନ କରାଯିବ।"
, ride_summary: "ରାଇଡ୍ ସାରାଂଶ"
, trip_inclusions: "ଯାତ୍ରାର ଅନ୍ତର୍ଭୁକ୍ତତା"
, please_pay_parking_or_other: "ଜରିମାନା କିମ୍ବା ଅନ୍ୟ ଚାର୍ଜଗୁଡ଼ିକୁ ଡ୍ରାଇଭରକୁ ଦେବାକୁ ପଡ଼ିବ।"
, toll_and_state_permit: "ଟୋଲ୍ ଏବଂ ରାଜ୍ୟ ଅନୁମତି ଆଲଗାଭାବେ ଦେବାକୁ ପଡ଼ିବ।"
, trip_exclusion: "ଯାତ୍ରା ବାହାର ରହିଥାଏ"
, confirm: "ନିଶ୍ଚିତ କରନ୍ତୁ"
, by_default_one_hour: "ଧାରଣ କରାଯାଇଥିବା ସମୟ ସହିତ ଆପଣଙ୍କ ବୁକିଂରେ 1 ଘଣ୍ଟା ଯୋଡାଯାଇଛି।"
, addon_km_charge: "ଅତିରିକ୍ତ କିମି ଚାର୍ଜ"
, time_fare: "ସମୟ ଭାଡ଼ା"
, trip_fare_includes: "ଯାତ୍ରା ଭାଡ଼ାରେ ଅନ୍ତର୍ଭୁକ୍ତ ହୋଇଥାଏ"
, trip_fare_excludes: "ଯାତ୍ରା ଭାଡ଼ାରେ ବାହାରକରାଯାଇଥିବା"
, extras_will_be_charged_at: "ଅତିରିକ୍ତ ବ୍ୟବହାର ରେ ଚାର୍ଜ ହେବ"
, fixed_charges: "ନିର୍ଦ୍ଧାରିତ ଚାର୍ଜ"
, pickup_date_and_time: "ଉଠା ତାରିଖ ଏବଂ ସମୟ"
, drop_back_in_at: (\cityName -> "ବ୍ୟବସ୍ଥା ସହିତ ପ୍ରତି ସମୟରେ " <> cityName <>"")
, per_km: "ପ୍ରତି କିମି"
, per_min: "ପ୍ରତି ମିନିଟ୍"
, hour: "ଘଣ୍ଟା"
, sec: "ସେକେଣ୍ଡ"
, bike_taxi: "ବାଇକ୍ ଟ୍ୟାକ୍ସି"
, trivandrum: "ତିରୁଅନ୍ତପୁରମ"
, phone_number_permission: "ଫୋନ୍ ନମ୍ବର ଅନୁମତି"
, phone_number_permission_desc: "ରେଡ୍ ବସରେ ଆପଣଙ୍କର ନମ୍ମା ଯାତ୍ରୀ ଫୋନ୍ ନମ୍ବର ବ୍ୟବହାର କରି ଖାସ ସୁବିଧା ପାଇବେ"
, deny: "ଅସ୍ୱୀକାର କରନ୍ତୁ"
, allow: "ସ୍ୱୀକାର"
, driver_assigned: "ଡ୍ରାଇଭର ନିଯୁକ୍ତ"
, explore: "ଅନୁସନ୍ଧାନ"
, tickets_for_delhi_metro: "ଦିଲ୍ଲୀ ମେଟ୍ରୋ ପାଇଁ ଟିକେଟ୍"
, delhi_metro_time: (\startTime endTime -> "ଦିଲ୍ଲୀ ମେଟ୍ରୋରେ QR ଟିକେଟ୍ କିଣିବା "<>startTime<>"ରୁ "<>endTime<>" ପର୍ଯ୍ୟନ୍ତ ସମସ୍ତ ଦିନ ଉପଲବ୍ଧ ଅଛି।")
, book_for_: (\name -> "ବୁକ୍ କରନ୍ତୁ " <> name)
, sort_by: "କ୍ରମଗତ କରନ୍ତୁ"
, customer: "ଗ୍ରାହକ"
, sender_name: "ପ୍ରେଷକର ନାମ*"
, sender_phone: "ପ୍ରେଷକର ଫୋନ୍*"
, senders_building_flat: "ପ୍ରେଷକର ଆପାର୍ଟମେଣ୍ଟ/ଫ୍ଲାଟ୍ ନମ୍ବର*"
, pickup_instructions: "ଉଠାଇବାର ନିର୍ଦ୍ଦେଶ (ଆବଶ୍ୟକ ନୁହେଁ)"
, receiver_name: "ଗ୍ରାହକର ନାମ*"
, receiver_phone: "ଗ୍ରାହକର ଫୋନ୍*"
, receivers_building_flat: "ଗ୍ରାହକର ଆପାର୍ଟମେଣ୍ଟ/ଫ୍ଲାଟ୍ ନମ୍ବର*"
, drop_instructions: "ଛାଡ଼ାର ନିର୍ଦ୍ଦେଶ (ଆବଶ୍ୟକ ନୁହେଁ)"
, out_for_delivery: "ଡିଲିଭରି ପାଇଁ ବାହାରିଲା"
, pickup_in_progress: "ଉଠାଇବା ପ୍ରଗତିରେ"
, arrived_at_drop: "ଛାଡ଼ା ସ୍ଥଳରେ ପହଞ୍ଚିଲା"
, out_for_pickup: "ଉଠାଇବା ପାଇଁ ବାହାରିଲା"
, confirm_pickup: "ଉଠାଇବା ନିଶ୍ଚିତ କରନ୍ତୁ"
, rate_your_delivery_with: "ଆପଣଙ୍କ ଡିଲିଭରିର ମୂଲ୍ୟାଙ୍କନ କରନ୍ତୁ"
, delivery_completed: "ଡିଲିଭରି ସମ୍ପନ୍ନ"
, estimated_arrival_by: "ଅନୁମାନିତ ପହଞ୍ଚିବା ସମୟ"
, metro_tickets : "ମେଟ୍ରୋ ଟିକେଟ୍‌"
, offers : "ଅଫରସ୍‌"
, back: "ପଛକୁ"
, photo_not_taken_yet: "ଏପର୍ଯ୍ୟନ୍ତ ଫଟୋ ନିଆଯାଇନାହିଁ"
, please_refresh_once_driver_takes_photo: "ଡ୍ରାଇଭର ଫଟୋ ନେଲେ ପରେ ଫ୍ରେସ କରନ୍ତୁ"
, package_photo_desc: "ପାର୍ସେଲ୍ ଫଟୋ ଠିକ୍ ଅଛି ବୋଲି ନିଶ୍ଚିତ କରନ୍ତୁ। ତ୍ରୁଟି ଥିଲେ ଡ୍ରାଇଭରଙ୍କୁ ଜଣାନ୍ତୁ।"
, start_otp: "ଆରମ୍ଭ OTP"
, package_photo: "ପାର୍ସେଲ୍ ଫଟୋ"
, refresh: "ରିଫ୍ରେସ୍"
, drop_instruction: "ଛାଡ଼ା ନିର୍ଦ୍ଦେଶ"
, quick_delivery_with: (\str -> str <> " ସହ ତ୍ୱରିତ ସେବା")
, step: "ପଦକ୍ଷେପ"
, booking_cannot_proceed_one_party_has_active_booking: "ଏକ ପକ୍ଷର ସକ୍ରିୟ ଯାତ୍ରା ଅଛି। ଦୟାକରି ପରେ ଚେଷ୍ଟା କରନ୍ତୁ!"
, please_enter_a_valid_mobile_number: "ଦୟାକରି ଏକ ବୈଧ ମୋବାଇଲ୍ ନମ୍ବର ଦିଆନ୍ତୁ"
, please_enter_a_valid_address: "ଦୟାକରି ଏକ ବୈଧ ଠିକଣା ଦିଆନ୍ତୁ"
, please_enter_a_valid_name: "ଦୟାକରି ଏକ ବୈଧ ନାମ ଦିଆନ୍ତୁ"
, enter_a_name: "ଏକ ନାମ ଦିଆନ୍ତୁ"
, enter_a_address: "ଏକ ଠିକଣା ଦିଆନ୍ତୁ"
, delivered_in_just: (\time -> "ବସ! କେବଳ " <> time <> " ମଧ୍ୟରେ ପହଞ୍ଚିଲା")
, different_bike: "ଭିନ୍ନ ବାଇକ୍"
, limit_reached: "ସୀମା ପୂରଣ ହୋଇଛି!"
, confirm_contacts: "ସମ୍ପର୍କ ସାମ୍ବନ୍ଧିକ ନିଶ୍ଚିତ କରନ୍ତୁ"
, max_parcel_size: (\l b h -> "ସର୍ବାଧିକ ପାର୍ସେଲ୍ ଆକାର: " <> l <> " ସେ.ମି x " <> b <> " ସେ.ମି x " <> h <> " ସେ.ମି")
, boost_search_instantly: "ତୁରନ୍ତ ଖୋଜିବା ବୃଦ୍ଧି କରନ୍ତୁ!"
, add_a_tip: "ଏକ ପରିପୁର୍ଣ୍ଣ ପରିକଳ୍ପନା ଯୋଗ କରନ୍ତୁ"
, updated_fare_str: "ନବୀକୃତ ଭାଡ଼ା"
, book_any_details: "ଯେକଉଣସି ବିବରଣୀ ବୁକ୍ କରନ୍ତୁ"
, boost_search: "ଖୋଜ ବୃଦ୍ଧି କରନ୍ତୁ"
, delivery_str: "Delivery"
, bus__ : "ବସ୍"  
, tickets_for_chennai_bus : "ଚେନ୍ନାଇ ବସ୍ ଟିକେଟ୍"  
, buy_bus_tickets : "ବସ୍ ଟିକେଟ୍ କିଣନ୍ତୁ"  
, book_and_pay : "ବୁକ୍ କରନ୍ତୁ ଏବଂ ଦେୟ କରନ୍ତୁ"  
, bus_ticket : "ବସ୍ ଟିକେଟ୍"  
, check_spelling_and_try_again : "ଅଫସ! ଦୟାକରି ନିଜର ଭାଷା ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ପୁନର୍ବାର ଖୋଜନ୍ତୁ"  
, book_bus_ticket : "ବସ୍ ଟିକେଟ୍ ବୁକ୍ କରନ୍ତୁ"  
, book_a_one_way_instant_bus_ticket : "ଏକ-ଦିଗର ତୁରନ୍ତ ବସ୍ ଟିକେଟ୍ ବୁକ୍ କରନ୍ତୁ"  
, recent_ticket : "ସମ୍ପ୍ରତିର ଟିକେଟ୍"  
, experience_hassle_free_bus_bookings_with : "ଆମ ସହ ଅତ୍ୟନ୍ତ ସୁବିଧାଜନକ ବସ୍ ବୁକିଂ ଅଭିଜ୍ଞତା ନିଆନ୍ତୁ"  
, enter_bus_number_or_destination : "ବସ୍ ନମ୍ବର କିମ୍ବା ଗନ୍ତବ୍ୟ ସ୍ଥାନ ପ୍ରବେଶ କରନ୍ତୁ"  
, destination_stop : "ଗନ୍ତବ୍ୟ ଷ୍ଟପ୍"  
, route_bus_number : "ପଥ/ବସ୍ ନମ୍ବର"  
, pickup_stop : "ପିକ୍ଅପ୍ ଷ୍ଟପ୍"  
, tickets_for_kolkata_bus : "କଲକାତା ବସ୍ ଟିକେଟ୍"  
, ticket_validity_30_minutes : "ଟିକେଟ୍ ବୁକିଂ ପରଠାରୁ ୩୦ ମିନିଟ୍ ପର୍ଯ୍ୟନ୍ତ ମାତ୍ର ପ୍ରାମାଣିକ ହେବ"  
, fare_commission_free_wbtc : "ଭାଡା ଦାଲାଲ ମୁକ୍ତ ଏବଂ ଏହା WBTC ଦ୍ୱାରା ନିର୍ଦ୍ଧାରିତ"  
, select_route_number : "ପଥ ସଂଖ୍ୟା ଚୟନ କରନ୍ତୁ"  
, pickup_and_destination_stop : "ପିକ୍ଅପ୍ ଏବଂ ଗନ୍ତବ୍ୟ ଷ୍ଟପ୍"  
, bus_boarded_confirmation : "ଦୟାକରି ନିଶ୍ଚିତ କରନ୍ତୁ ଯେ ଆପଣ ବସ୍ ଭିତରେ ଅଛନ୍ତି କି?"  
, towards_station : (\s -> "ସ୍ଥାନାନ୍ତର ମୁଖେ " <> s)  
, bus_no : (\s -> "ବସ୍ ନମ୍ବର: " <> s)  
, verified : "ପ୍ରମାଣିତ"  
, experience_our_pilot_launch_for_bus_ticketing_in_prime_routes : (\s -> "ଆମ ପାଇଲଟ୍ ପ୍ରବର୍ତ୍ତନକୁ ଅନୁଭବ କରନ୍ତୁ " <> s <> " ମୁଖ୍ୟ ପଥଗୁଡିକରେ। ସିଗ୍ରହ ସବୁ ଆସୁଛି!")  
, note_your_ticket_is_only_valid_for : (\s -> "ଧ୍ୟାନ ଦିଅନ୍ତୁ: ଆପଣଙ୍କ ଟିକେଟ୍ କେବଳ " <> s <> " ପାଇଁ ପ୍ରାମାଣିକ ଅଟେ। ସ୍ଥାନୀୟ ପରିସ୍ଥିତି ଅନୁସାରେ ବସ୍ ସମୟ ପରିବର୍ତ୍ତିତ ହୋଇପାରେ, ସେପରି ଷ୍ଟପ୍ରେ ବସ୍ ବୁକିଂ କରିବା ସମୟରେ ଥାନ୍ତୁ")  
, here_is_bus_ticket : "ଏହା ଆପଣଙ୍କର ବସ୍ ଟିକେଟ୍"
,a_c : "ଏସି"
,no_oxygen : "ଅକ୍ସିଜେନ୍ ନାହିଁ"
,oxygen : "ଅକ୍ସିଜେନ୍"
,ventilator : "ଭେଣ୍ଟିଲେଟର୍"
,ambulance_ : "ଆମ୍ବୁଲାନ୍ସ"
,uncomfortable_ambulance : "ଅସୁବିଧାଜନକ ଆମ୍ବୁଲାନ୍ସ"
,clean_ambulance : "ପରିଷ୍କାର ଆମ୍ବୁଲାନ୍ସ"
,ambulance_booking_disclaimer : "ଯାତ୍ରୀ ସାଥୀ କେବଳ ଏକ ପ୍ଲାଟଫର୍ମ ଯାହା ଆମ୍ବୁଲେନ୍ସ ସେବା ପ୍ରଦାତାମାନେ ଗ୍ରାହକଙ୍କ ସହିତ ସଂଯୋଗ କରେ। ଆମ୍ବୁଲେନ୍ସ ପକ୍ଷ ଦ୍ୱାରା ଦିଆଯାଇଥିବା ସୂଚନା ପାଇଁ ଆମେ ଦାୟୀ ନୁହେଁ।"
, no_remaining_tickets : "କୌଣସି ଅବଶିଷ୍ଟ ଟିକେଟ୍ ନାହିଁ" 
    , your_earnings_will_be_credited_to_this_account: "ଆପଣଙ୍କ ଆୟ ଏହି ଖାତାରେ ଜମା ହେବ"
    , transaction_history: "ଲେନଦେନ ଇତିହାସ"
    , total_earned: "ମୋଟ ଆର୍ଜନ"
    , took_cab_ride_using_referral_code: "ରେଫେରେଲ୍ କୋଡ୍ ବ୍ୟବହାର କରି କ୍ୟାବ୍ ରାଇଡ୍ ନେଇଛନ୍ତି"
    , success: "ସଫଳତା"
    , invite_and_earn_: "ଆମନ୍ତ୍ରଣ କରନ୍ତୁ ଏବଂ ଅର୍ଜନ କରନ୍ତୁ!"
    , enjoy_extra_kekkadha_rides: "& ଅତିରିକ୍ତ କେକ୍କଦା ରାଇଡ୍ ଉପଭୋଗ କରନ୍ତୁ!"
    , your_invite_code: "ଆପଣଙ୍କ ଆମନ୍ତ୍ରଣ କୋଡ୍"
    , share: "ଭାଗ କରନ୍ତୁ"
    , you_get: "ଆପଣ ପାଇବେ"
    , they_get: "ସେମାନେ ପାଇବେ"
    , credited_to_the_referees_account_when_the_referee__use_your_referral_code_for_app_installation_and_then_takes_a_valid_ride: "ରେଫେରେଲ୍ କୋଡ୍ ବ୍ୟବହାର କରି ଆପ୍‌ ଇନ୍‌ସ୍ଟଲ୍ କରି ଏବଂ ବୈଧ ଯାତ୍ରା କରିବା ପରେ ରେଫେରୀଙ୍କ ଖାତାରେ ଜମା ହେବ।"
    , credited_to_your_account_when_your_referee_uses_your_referral_code_for_app_installation_and_uses_the_app_for_taking_a_valid_ride: "ଆପଣଙ୍କ ରେଫେରେଲ୍ କୋଡ୍ ବ୍ୟବହାର କରି ଏକ ବୈଧ ଯାତ୍ରା କରିବା ପରେ ଆପଣଙ୍କ ଖାତାରେ ଜମା ହେବ।"
    , have_questions: "ପ୍ରଶ୍ନ ଅଛି?"
    , _view_the_faqs: "ସାଧାରଣ ପ୍ରଶ୍ନଗୁଡ଼ିକ ଦେଖନ୍ତୁ"
    , referral_faqs: "ରେଫେରେଲ୍ FAQs"
    , to_get_the_referral_reward_new_user_should_install_the_app_and_enter_the_referral_code_before_taking_their_first_ride: "ରେଫେରେଲ୍ ପୁରସ୍କାର ପାଇବାକୁ, ନୂତନ ଉପଯୋଗକାରୀ ଆପ୍‌ଟି ଇନ୍‌ସ୍ଟଲ୍ କରି, ପ୍ରଥମ ଯାତ୍ରା ପୂର୍ବରୁ ରେଫେରେଲ୍ କୋଡ୍ ଦିଅନ୍ତୁ।"
    , the_referral_reward_will_be_given_only_for_the_first_ride_post_checking_the_ride_validity: "ଯାତ୍ରାର ବୈଧତା ପରୀକ୍ଷା କରିବା ପରେ କେବଳ ପ୍ରଥମ ଯାତ୍ରା ପାଇଁ ରେଫେରେଲ୍ ପୁରସ୍କାର ଦିଆଯିବ।"
    , the_referral_reward_program_is_a_time_bound_program_and_can_be_stopped_at_any_time_without_prior_intimation: "ରେଫେରେଲ୍ ପୁରସ୍କାର କାର୍ଯ୍ୟକ୍ରମ ଏକ ସମୟସୀମିତ କାର୍ଯ୍ୟକ୍ରମ ଏବଂ ଯେକୌଣସି ସମୟରେ ପୂର୍ବ ଅବଗତି ବିନା ବନ୍ଦ ହୋଇପାରେ।"
    , namma_yatri_reserves_the_right_to_determine_the_eligibility_of_a_customer_to_be_valid_for_referral_reward_or_not: "ରେଫେରେଲ୍ ପୁରସ୍କାର ପାଇଁ ଏକ ଗ୍ରାହକ ଯୋଗ୍ୟ କି ନୁହେଁ ବୋଲି ନିର୍ଦ୍ଧାରଣ କରିବାର ଅଧିକାର ନମ୍ମା ଯାତ୍ରିରେ ଅଛି।"
    , collect_referral_earnings: "ରେଫେରେଲ୍ ଆର୍ଜନ ସଂଗ୍ରହ କରନ୍ତୁ"
    , verify_your_upi_id_to_receive_your_referral_earnings: "ଆପଣଙ୍କ ରେଫେରେଲ୍ ଆର୍ଜନ ପାଇଁ UPI ID ପରୀକ୍ଷା କରନ୍ତୁ"
    , upi_id_verified: "UPI ID ସଂଯୋଗ ହୋଇଯାଇଛି!"
    , enter_upi_id_in_the_format_numberbankname: "“ସଂଖ୍ୟା@ବ୍ୟାଙ୍କନାମ” ଫର୍ମାଟ୍‌ରେ UPI ID ଦିଅନ୍ତୁ"
    , upi_id_is_invalid_please_check_and_reenter: "UPI ID ଅବୈଧ। ଦୟାକରି ଯାଞ୍ଚ କରି ପୁନଃ ଭରଣ କରନ୍ତୁ"
    , go_back: "ପଛକୁ ଯାଆନ୍ତୁ"
    , yay_you_have_referral_earnings: "ଯେ! ଆପଣଙ୍କ ପାଖରେ ରେଫେରେଲ୍ ଆର୍ଜନ ଅଛି"
    , your_earnings_n_: "ଆପଣଙ୍କ ଆୟ \n ₹"
    , collect_now: "ଏବେ ସଂଗ୍ରହ କରନ୍ତୁ"
    , submitted: "ଦାଖଲ ହୋଇଛି"
    , updated: "ଅଦ୍ୟତିତ ହୋଇଛି!"
    , pendingamount_will_be_credited_soon_to_n_statedatavpa: \ a b -> a  <> "  ଶୀଘ୍ର " <> b <> " କୁ ଜମା ହେବ"
    , amount: "Amount"
    , downlaod_app: "Downlaod App"
    , scan_qr_code_to_download_the_app_and_apply_your_invite_code_automatically: "Scan QR code to download the app and apply your invite code automatically"
    , earn_:  \a ->  "₹" <> a <> " ଉପାର୍ଜନ କରନ୍ତୁ"
    ,  collect_:  \a ->  "₹" <> a <> " ସଂଗ୍ରହ କରନ୍ତୁ"
}