INSERT INTO atlas_app.notification_sounds_config
    (merchant_id, merchant_operating_city_id, notification_type, default_sound, blind_sound)
SELECT
    city.merchant_id,
    city.id,
    event.notification_type,
    event.default_sound,
    event.blind_sound
FROM
    (VALUES
        ('REGISTRATION_APPROVED', 'default', 'default'),
        ('EXPIRED_CASE', 'default', 'default'),
        ('CANCELLED_PRODUCT', 'cancel_notification_sound.mp3', 'you_have_cancelled_the_ride.mp3'),
        ('CANCELLED_PRODUCT_DRIVER', 'cancel_notification_sound.mp3', 'ride_cancelled_by_driver.mp3'),
        ('CANCELLED_PRODUCT_USER', 'cancel_notification_sound.mp3', 'you_have_cancelled_the_ride.mp3'),
        ('REALLOCATE_PRODUCT', 'cancel_notification_sound.mp3', 'ride_cancelled_by_driver.mp3'),
        ('DRIVER_ASSIGNMENT', 'ride_assigned.mp3', 'ride_assigned_talkback.mp3'),
        ('TRIP_STARTED', 'ride_started.mp3', 'ride_started_talkback.mp3'),
        ('TRIP_FINISHED', 'default', 'ride_completed_talkback.mp3'),
        ('ALLOCATION_REQUEST', 'default', 'default'),
        ('ALLOCATION_REQUEST_UNASSIGNED', 'default', 'default'),
        ('ACCOUNT_DISABLED', 'default', 'default'),
        ('TRIGGER_SERVICE', 'default', 'default'),
        ('FARE_POLICY_CHANGED', 'default', 'default'),
        ('DISCOUNT_CHANGED', 'default', 'default'),
        ('QUOTE_RECEIVED', 'default', 'default'),
        ('NEW_RIDE_AVAILABLE', 'default', 'default'),
        ('DRIVER_QUOTE_INCOMING', 'default', 'default'),
        ('DRIVER_ON_THE_WAY', 'default', 'default'),
        ('DRIVER_HAS_REACHED', 'driver_arrived.mp3', 'driver_arrived.mp3'),
        ('CLEARED_FARE', 'default', 'default'),
        ('CANCELLED_SEARCH_REQUEST', 'default', 'default'),
        ('NEW_MESSAGE', 'default', 'default'),
        ('REFERRAL_ACTIVATED', 'default', 'default'),
        ('CHAT_MESSAGE', 'default', 'default'),
        ('PAYMENT_PENDING', 'default', 'default'),
        ('PAYMENT_OVERDUE', 'default', 'default'),
        ('PAYMENT_FAILED', 'default', 'default'),
        ('PAYMENT_SUCCESS', 'default', 'default'),
        ('PAYMENT_MODE_MANUAL', 'default', 'default'),
        ('PAYMENT_NUDGE', 'default', 'default'),
        ('DRIVER_NOTIFY', 'default', 'default'),
        ('SAFETY_ALERT', 'default', 'default'),
        ('DRIVER_BIRTHDAY', 'default', 'default'),
        ('EDIT_LOCATION', 'default', 'default'),
        ('ADD_STOP', 'default', 'default'),
        ('EDIT_STOP', 'default', 'default'),
        ('STOP_REACHED', 'default', 'default'),
        ('COINS_SUCCESS', 'default', 'default'),
        ('FOLLOW_RIDE', 'default', 'default'),
        ('SHARE_RIDE', 'default', 'default'),
        ('SOS_TRIGGERED', 'ny_ic_sos_danger.mp3', 'ny_ic_sos_danger.mp3'),
        ('SOS_MOCK_DRILL', 'default', 'default'),
        ('SOS_RESOLVED', 'ny_ic_sos_safe.mp3', 'ny_ic_sos_safe.mp3'),
        ('EMERGENCY_CONTACT_ADDED', 'default', 'default')
    ) AS event(notification_type, default_sound, blind_sound),
    atlas_app.merchant_operating_city AS city;