UPDATE atlas_app.issue_message
SET message = 'Estimated → Final Fare: <br> <b> {#ESTIMATED_FARE#} → {#FINAL_FARE#} <span style="color:#2194FF"> ({#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> Estimated → Final Distance: <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> Driver Pickup Charges: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> Driver Additions: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> Toll Charges Incurred: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> Tip Added: <br> <b> {#TIP_ADDED#} </b> <br> <br> The fare estimate is only an indicative figure. The final fare is subject to change based on the actual distance travelled. For more info, please view the detailed fare policy. <br>',
label = 'FARE_BREAKUP_MESSAGE'
WHERE id = 'bimt3gzi-9n2t-ox6o-c88g-kam2nn3fjue5';

INSERT INTO atlas_app.issue_translation VALUES ('mi30uqhu-rgve-4lhk-se80-jya4ggi1z67s','Estimated → Final Fare: <br> <b> {#ESTIMATED_FARE#} → {#FINAL_FARE#} <span style="color:#2194FF"> ({#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> Estimated → Final Distance: <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> Driver Pickup Charges: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> Driver Additions: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> Toll Charges Incurred: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> Tip Added: <br> <b> {#TIP_ADDED#} </b> <br> <br> The fare estimate is only an indicative figure. The final fare is subject to change based on the actual distance travelled. For more info, please view the detailed fare policy. <br>','Estimated → Final Fare: <br> <b> {#ESTIMATED_FARE#} → {#FINAL_FARE#} <span style="color:#2194FF"> ({#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> Estimated → Final Distance: <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> Driver Pickup Charges: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> Driver Additions: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> Toll Charges Incurred: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> Tip Added: <br> <b> {#TIP_ADDED#} </b> <br> <br> The fare estimate is only an indicative figure. The final fare is subject to change based on the actual distance travelled. For more info, please view the detailed fare policy. <br>','ENGLISH');

INSERT INTO atlas_app.issue_translation VALUES ('su9pwblt-0jiq-xzxl-d91t-i7iitzq0o4rj','Estimated → Final Fare: <br> <b> {#ESTIMATED_FARE#} → {#FINAL_FARE#} <span style="color:#2194FF"> ({#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> Estimated → Final Distance: <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> Driver Pickup Charges: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> Driver Additions: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> Toll Charges Incurred: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> Tip Added: <br> <b> {#TIP_ADDED#} </b> <br> <br> The fare estimate is only an indicative figure. The final fare is subject to change based on the actual distance travelled. For more info, please view the detailed fare policy. <br>','ಅಂದಾಜಿಸಲಾಗಿದೆ → ಅಂತಿಮ ಶುಲ್ಕ: <br> <b> ₹{#ESTIMATED_FARE#} → ₹{#FINAL_FARE#} <span style="color:#2194FF"> (₹{#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> ಅಂದಾಜಿಸಲಾಗಿದೆ → ಅಂತಿಮ ದೂರ: <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> ಚಾಲಕ ಪಿಕಪ್ ಶುಲ್ಕಗಳು: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> ಚಾಲಕ ಸೇರ್ಪಡೆಗಳು: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> ಟೋಲ್ ಶುಲ್ಕಗಳು: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> ಸಲಹೆ ಸೇರಿಸಲಾಗಿದೆ: <br> <b> {#TIP_ADDED#} </b> <br> <br>  ದರದ ಅಂದಾಜು ಕೇವಲ ಸೂಚಕ ಅಂಕಿಯಾಗಿದೆ. ಪ್ರಯಾಣದ ನಿಜವಾದ ದೂರದ ಆಧಾರದ ಮೇಲೆ ಅಂತಿಮ ದರವು ಬದಲಾವಣೆಗೆ ಒಳಪಟ್ಟಿರುತ್ತದೆ. ಹೆಚ್ಚಿನ ಮಾಹಿತಿಗಾಗಿ, ದಯವಿಟ್ಟು ವಿವರವಾದ ದರ ನೀತಿಯನ್ನು ವೀಕ್ಷಿಸಿ. <br>','KANNADA');

INSERT INTO atlas_app.issue_translation VALUES ('fbcgkkju-6ghb-50kw-kxye-qi4kv5drea93','Estimated → Final Fare: <br> <b> {#ESTIMATED_FARE#} → {#FINAL_FARE#} <span style="color:#2194FF"> ({#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> Estimated → Final Distance: <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> Driver Pickup Charges: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> Driver Additions: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> Toll Charges Incurred: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> Tip Added: <br> <b> {#TIP_ADDED#} </b> <br> <br> The fare estimate is only an indicative figure. The final fare is subject to change based on the actual distance travelled. For more info, please view the detailed fare policy. <br>','மதிப்பிடப்பட்டுள்ளது → இறுதி கட்டணம்: <br> <b> {#ESTIMATED_FARE#} → {#FINAL_FARE#} <span style="color:#2194FF"> ({#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> மதிப்பிடப்பட்டுள்ளது → இறுதி தூரம்: <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> டிரைவர் பிக்அப் கட்டணம்: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> இயக்கி சேர்த்தல்: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> டோல் கட்டணம் விதிக்கப்பட்டது: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> குறிப்பு சேர்க்கப்பட்டது: <br> <b> {#TIP_ADDED#} </b> <br> <br> கட்டண மதிப்பீடு ஒரு குறிப்பான எண்ணிக்கை மட்டுமே. உண்மையான பயண தூரத்தின் அடிப்படையில் இறுதிக் கட்டணம் மாற்றத்திற்கு உட்பட்டது. மேலும் தகவலுக்கு, விரிவான கட்டணக் கொள்கையைப் பார்க்கவும். <br>','TAMIL');

INSERT INTO atlas_app.issue_translation VALUES ('2nqp03he-z9j9-fcec-ljwo-x1z9lr2uwov6','Estimated → Final Fare: <br> <b> {#ESTIMATED_FARE#} → {#FINAL_FARE#} <span style="color:#2194FF"> ({#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> Estimated → Final Distance: <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> Driver Pickup Charges: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> Driver Additions: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> Toll Charges Incurred: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> Tip Added: <br> <b> {#TIP_ADDED#} </b> <br> <br> The fare estimate is only an indicative figure. The final fare is subject to change based on the actual distance travelled. For more info, please view the detailed fare policy. <br>','अनुमानित → अंतिम किराया : <br> <b> ₹{#ESTIMATED_FARE#} → ₹{#FINAL_FARE#} <span style="color:#2194FF"> (₹{#FARE_DIFFERENCE#}{#FARE_ARROW#}) </span> </b> <br> <br> अनुमानित → अंतिम दूरी : <br> <b> {#ESTIMATED_DISTANCE#} km → {#FINAL_DISTANCE#} km <span style="color:#2194FF"> ({#DISTANCE_DIFFERENCE#} km{#DISTANCE_ARROW#}) </span> </b> <br> <br> ड्राइवर पिकअप शुल्क: <br> <b> {#DRIVER_PICKUP_CHARGES#} </b> <br> <br> ड्राइवर परिवर्धन: <br> <b> {#DRIVER_ADDITIONS#} </b> <br> <br> टोल शुल्क: <br> <b> {#TOLL_CHARGES#} </b> <br> <br> टिप जोड़ी गई: <br> <b> {#TIP_ADDED#} </b> <br> <br> किराये का अनुमान केवल सांकेतिक आंकड़ा है| अंतिम किराया यात्रा की गई वास्तविक दूरी के आधार पर परिवर्तन के अधीन है। अधिक जानकारी के लिए कृपया विस्तृत किराया नीति देखें। <br>','HINDI');














