
@driver-offer-bpp-host = http://localhost:8016
@token = {{app-token}}

# @name healthcheck
GET {{driver-offer-bpp-host}}/ui

###

@currentTime = 2022-03-03T23:37

# @name updateInitial
POST {{driver-offer-bpp-host}}/ui/driver/location
token: {{driver-token}}
content-type: application/json

[
    {
        "pt": {
            "lon": 76.31742659311804,
            "lat": 10.041437092019764
        },
        "ts": "{{currentTime}}:01.114244Z"
    }
]

###

# @name setActive
POST {{driver-offer-bpp-host}}/ui/driver/setActivity?active=true
content-type: application/json
token: {{driver-token}}
###

###

# @name search
POST {{app-host}}/rideSearch
content-type: application/json
token: {{token}}

{
  "fareProductType" : "ONE_WAY",
  "contents" : {
    "origin": {
      "address": {
          "street": "Edapally Metro Station",
          "state": "Kerala",
          "door": "",
          "country": "India",
          "city": "Kochi",
          "building": " ",
          "areaCode": "",
          "area": "Edappally"
      },
      "gps": {
          "lon": 76.31642659311804,
          "lat": 10.041437092019764
      }
    },
    "destination": {
      "address": {
              "street": "Ambattukavu",
              "state": "Kerala",
              "door": "",
              "country": "India",
              "city": "Aluva",
              "building": "Ambattukavu metro station",
              "areaCode": "",
              "area": "Choornikkara"
          },
      "gps": {
          "lon": 76.3388894,
          "lat": 10.0792806
      }
    }
  }
}

###

@searchId = {{search.response.body.searchId}}

# @name quotes
GET {{app-host}}/rideSearch/{{searchId}}/quotes
content-type: application/json
token: {{token}}

###

# @name select
@quoteId = {{quotes.response.body.quotes[0].onDemandCab.id}}

POST {{app-host}}/rideSearch/quotes/{{quoteId}}/select HTTP/1.1
content-type: application/json
token: {{token}}

###

# @name nearbySearchRequest
GET {{driver-offer-bpp-host}}/ui/driver/nearbyRideRequest
token: {{driver-token}}

###

# @name offerQuote
POST {{driver-offer-bpp-host}}/ui/driver/searchRequest/quote/offer
token: {{driver-token}}
content-type: application/json

{
    "offeredFare": 30.5,
    "searchRequestId": "{{nearbySearchRequest.response.body.searchRequests[0].searchRequestId}}"
}

###

# @name selectedQuotes
GET {{app-host}}/rideSearch/quotes/{{quoteId}}/select/list
content-type: application/json
token: {{token}}

###

# @name initQuote
@selectedQuoteId = {{selectedQuotes.response.body.selectedQuotes[0].id}}

POST {{app-host}}/rideInit
content-type: application/json
token: {{token}}

{
  "selected": true,
  "quoteId": "{{selectedQuoteId}}"
}

###
# @name confirmQuote
@bookingId = {{initQuote.response.body.bookingId}}

POST {{app-host}}/rideSearch/confirm
content-type: application/json
token: {{token}}

{
  "bookingId": "{{bookingId}}",
  "fromLocation": {
    "door": "2"
  },
  "toLocation": {
    "door": "3"
  }
}

###

# @name list2
GET {{app-host}}/rideBooking/list
  ?offset=0
  &limit=50
  &onlyActive=false
content-type: application/json
token: {{token}}

###
# @name driverList
GET {{driver-offer-bpp-host}}/v2/driver/ride/list?limit=100&offset=0
token: {{driver-token}}

###
@rideId = {{driverList.response.body.list[0].id}}
@otp = {{list2.response.body.list[0].rideList[0].rideOtp}}

# @name startRide
POST {{driver-offer-bpp-host}}/v2/driver/ride/{{rideId}}/start
token: {{driver-token}}
content-type: application/json

{
    "rideOtp": "{{otp}}",
    "point": {
            "lon": 76.308364,
            "lat": 10.025263
    }
}

# 76.308364, 10.025263
###

@currentTime = 2022-03-03T23:37

# @name update1
POST {{driver-offer-bpp-host}}/v2/driver/location
token: {{driver-token}}
content-type: application/json

[
    {
        "pt": {
            "lon": 76.308364,
            "lat": 10.025263
        },
        "ts": "{{currentTime}}:01.114244Z"
    },
    {
        "pt": {
            "lat": 10.036754844278509,
            "lon": 76.31406568451686
        },
        "ts": "{{currentTime}}:10.114244Z",
        "aux": "Pathadippalam metro"
    },
    {
        "pt": {
            "lat": 10.047446731143813,
            "lon": 76.3182331061409
        },
        "ts": "{{currentTime}}:19.114244Z",
        "aux": "Cochi university metro"
    },
    {
        "pt": {
            "lat": 10.059363529228063,
            "lon": 76.32187725922056
        },
        "ts": "{{currentTime}}:28.114244Z",
        "aux": "Kalamassery metro"
    }
]

###

# @name update2
POST {{driver-offer-bpp-host}}/v2/driver/location
token: {{driver-token}}
content-type: application/json

[
    {
        "pt": {
            "lat": 10.072808633266954,
            "lon": 76.33348375279246
        },
        "ts": "{{currentTime}}:38.114244Z",
        "aux": "Muttom metro"
    },
    {
        "pt": {
            "lat": 10.080241882783683,
            "lon": 76.33893232031218
        },
        "ts": "{{currentTime}}:49.114244Z",
        "aux": "Ambattukavu metro"
    }
]

###

# @name rideEnd
POST {{driver-offer-bpp-host}}/v2/driver/ride/{{rideId}}/end
token: {{driver-token}}
content-type: application/json

{
  "point": {
    "lat": 10.080241882783683,
    "lon": 76.33893232031218
  }
}

###
# @name cancel
POST {{app-host}}/rideBooking/{{bookingId}}/cancel
content-type: application/json
token: {{token}}

{
  "reasonCode": "OTHER",
  "reasonStage": "OnAssign",
  "additionalInfo": "driver is too fat"
}

### OnSearch | OnConfirm | OnAssign
###

@bapRideId = {{list2.response.body.list[0].rideList[0].id}}

# @name feedback
POST {{app-host}}/feedback/rateRide
token: {{token}}
content-type: application/json

{
  "rideId": "{{bapRideId}}",
  "rating" : 5
}
