@token1 = {{driver-offer-bpp-auto-token1}}
@token2 = {{driver-offer-bpp-auto-token2}}
@driver-offer-bpp-host = http://localhost:8016

# @name healthcheck
GET {{driver-offer-bpp-host}}/ui

###

# @name healthcheck
GET {{app-host}}

###

# @name updateInitial
POST {{driver-offer-bpp-host}}/ui/driver/location
token: {{token1}}
content-type: application/json

[
    {
        "pt": {
            "lon": 77.6245,
            "lat": 12.9352
        },
        "ts": "{{$localDatetime iso8601}}"
    }
]

###

# @name setActive
POST {{driver-offer-bpp-host}}/ui/driver/setActivity?active=false
content-type: application/json
token: {{token1}}

###

# @name createDriver
POST {{driver-offer-bpp-host}}/ui/org/driver
content-type: application/json
token: ea37f941-427a-4085-a7d0-96240f166672

{
  "person" : {
    "firstName": "Jonh",
    "middleName": " Maybeext",
    "lastName": "Maybext",
    "mobileNumber": "9602580675",
    "mobileCountryCode": "+7"
  },
  "vehicle" : {
    "category": "CAR",
    "model": "Ford",
    "variant": "SEDAN",
    "color": "White",
    "registrationNo": "6001",
    "capacity": 120
  }
}

###

# @name search
POST {{app-host}}/rideSearch
content-type: application/json
token: {{app-token}}

{
  "fareProductType" : "ONE_WAY",
  "contents" : {
    "origin": {
      "address": {
          "street": "Edapally Metro Station",
          "state": "Kerala",
          "door": "",
          "country": "India",
          "city": "Kochi",
          "building": " ",
          "areaCode": "",
          "area": "Edappally"
      },
      "gps": {
          "lon": 77.6245,
          "lat": 12.9352
      }
    },
    "destination": {
      "address": {
              "street": "Ambattukavu",
              "state": "Kerala",
              "door": "",
              "country": "India",
              "city": "Aluva",
              "building": "Ambattukavu metro station",
              "areaCode": "",
              "area": "Choornikkara"
          },
      "gps": {
          "lon": 77.5857,
          "lat": 12.9063
      }
    }
  }
}

###

@searchId = {{search.response.body.searchId}}

# @name quotes
GET {{app-host}}/rideSearch/{{searchId}}/results
content-type: application/json
token: {{app-token}}

###

# @name select
@estimateId = {{quotes.response.body.estimates[0].id}}

POST {{app-host}}/estimate/{{estimateId}}/select HTTP/1.1
content-type: application/json
token: {{app-token}}

###

# @name nearbySearchRequest
GET {{driver-offer-bpp-host}}/ui/driver/nearbyRideRequest
token: {{token1}}

###

# @name offerQuote
POST {{driver-offer-bpp-host}}/ui/driver/searchRequest/quote/offer
token: {{token1}}
content-type: application/json

{
    "offeredFare": 30,
    "searchRequestId": "{{nearbySearchRequest.response.body.searchRequestsForDriver[0].searchRequestId}}"
}

###

# @name selectedQuotes
GET {{app-host}}/estimate/{{estimateId}}/quotes
content-type: application/json
token: {{app-token}}

###

@selectedQuoteId = {{selectedQuotes.response.body.selectedQuotes[0].id}}

# @name confirmQuote

POST {{app-host}}/rideSearch/quotes/{{selectedQuoteId}}/confirm
content-type: application/json
token: {{app-token}}

{
  "selected": true,
  "fromLocation": {
    "door": "2"
  },
  "toLocation": {
    "door": "3"
  }
}

###
@bookingId = {{confirmQuote.response.body.bookingId}}

# @name list2
GET {{app-host}}/rideBooking/list
  ?offset=0
  &limit=50
  &onlyActive=false
content-type: application/json
token: {{app-token}}

###

# @name listOfCompleted
GET {{app-host}}/rideBooking/list
  ?offset=0
  &limit=50
  &filterByBookingStatus="COMPLETED"
content-type: application/json
token: {{app-token}}

###

# @name driverList
GET {{driver-offer-bpp-host}}/ui/driver/ride/list?limit=100&offset=0
token: {{token1}}

###

@rideId = {{driverList.response.body.list[0].id}}
@otp = {{list2.response.body.list[0].rideList[0].rideOtp}}

# @name startRide
POST {{driver-offer-bpp-host}}/ui/driver/ride/{{rideId}}/start
token: {{token1}}
content-type: application/json

{
    "rideOtp": "{{otp}}",
    "point": {
            "lon": 76.308364,
            "lat": 10.025263
    }
}

# 76.308364, 10.025263
###

# @name update1
POST {{driver-offer-bpp-host}}/ui/driver/location
token: {{token1}}
content-type: application/json

[
    {
        "pt": {
            "lon": 76.308364,
            "lat": 10.025263
        },
        "ts": "{{$localDatetime iso8601}}"
    },
    {
        "pt": {
            "lat": 10.036754844278509,
            "lon": 76.31406568451686
        },
        "ts": "{{$localDatetime iso8601}}",
        "aux": "Pathadippalam metro"
    },
    {
        "pt": {
            "lat": 10.047446731143813,
            "lon": 76.3182331061409
        },
        "ts": "{{$localDatetime iso8601}}",
        "aux": "Cochi university metro"
    },
    {
        "pt": {
            "lat": 10.059363529228063,
            "lon": 76.32187725922056
        },
        "ts": "{{$localDatetime iso8601}}",
        "aux": "Kalamassery metro"
    }
]

###

# @name update2
POST {{driver-offer-bpp-host}}/ui/driver/location
token: {{token1}}
content-type: application/json

[
    {
        "pt": {
            "lat": 10.072808633266954,
            "lon": 76.33348375279246
        },
        "ts": "{{$localDatetime iso8601}}",
        "aux": "Muttom metro"
    },
    {
        "pt": {
            "lat": 10.080241882783683,
            "lon": 76.33893232031218
        },
        "ts": "{{$localDatetime iso8601}}",
        "aux": "Ambattukavu metro"
    }
]

###

# for testing thresholds specific for bpp, run
# INSERT INTO atlas_driver_offer_bpp.transporter_config (organization_id, pickup_loc_threshold, drop_loc_threshold, created_at, updated_at) VALUES
# 	('favorit0-0000-0000-0000-00000favorit', 500, 500, '2022-04-12 15:15:42.233691+00', '2022-04-12 15:15:42.233691+00'),
# 	('nearest-drivers-testing-organization', 500, 500, '2022-04-12 15:15:42.233691+00', '2022-04-12 15:15:42.233691+00');

# @name rideEnd
POST {{driver-offer-bpp-host}}/ui/driver/ride/{{rideId}}/end
token: {{token1}}
content-type: application/json

{
  "point": {
    "lat": 10.0812806,
    "lon": 76.3388894
  }
}

###

# @name cancel
POST {{app-host}}/rideBooking/{{bookingId}}/cancel
content-type: application/json
token: {{app-token}}

{
  "reasonCode": "OTHER",
  "reasonStage": "OnAssign",
  "additionalInfo": "driver is too fat"
}

### OnSearch | OnConfirm | OnAssign
###

@bapRideId = {{list2.response.body.list[0].rideList[0].id}}

# @name feedback
POST {{app-host}}/feedback/rateRide
token: {{app-token}}
content-type: application/json

{
  "rideId": "{{bapRideId}}",
  "rating" : 5,
  "feedbackDetails": "The driver is so cute"
}
