FROM fpco/stack-build:lts-16.31
RUN mkdir /opt/build
WORKDIR /opt/build

# Updating confluence public key:
RUN sudo apt-key del 41468433 \
  && wget -qO - https://packages.confluent.io/deb/5.5/archive.key | sudo apt-key add -

# GHC dynamically links its compilation targets to lib gmp
RUN apt-get update \
  && apt-get download libgmp10 \
  && apt-get install -y \
  openssh-client \
  librdkafka-dev
RUN mv libgmp*.deb libgmp.deb

# Dependencies for checks
RUN stack install --resolver lts-17.6 hlint ormolu

# Docker build should not use cached layer if any of these is modified
COPY . /opt/build/

COPY ./.ssh/id_rsa /root/.ssh/id_rsa
RUN chmod 400 /root/.ssh/id_rsa
RUN ssh-keyscan -H "bitbucket.org" >> ~/.ssh/known_hosts

RUN stack build --system-ghc --dependencies-only

# Remove src code to avoid caching it
RUN ls | grep -vE ".stack|libgmp.deb" | xargs rm -rf

RUN rm -f /root/.ssh/id_rsa