FROM fpco/stack-build:lts-15.15
RUN mkdir /opt/build
WORKDIR /opt/build

# GHC dynamically links its compilation targets to lib gmp
RUN apt-get update \
  && apt-get download libgmp10 \
  && apt-get install -y \
      openssh-client
RUN mv libgmp*.deb libgmp.deb

# Dependencies for checks
RUN stack install --resolver lts-16.3 hlint ormolu

# Docker build should not use cached layer if any of these is modified
COPY . /opt/build/

COPY ./.ssh/id_rsa /root/.ssh/id_rsa
RUN chmod 400 /root/.ssh/id_rsa
RUN ssh-keyscan -H "bitbucket.org" >> ~/.ssh/known_hosts

ARG BUILD_ARGS

RUN stack build --system-ghc --dependencies-only ${BUILD_ARGS}

# Remove src code to avoid caching it
RUN ls | grep -vE ".stack|libgmp.deb" | xargs rm -rf

RUN rm -f /root/.ssh/id_rsa
