CREATE TABLE atlas_driver_offer_bpp.rewards (
   id CHARACTER(36) PRIMARY KEY NOT NULL,
   name CHARACTER VARYING(255),
   provider CHARACTER VARYING(255),
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);