DELETE FROM atlas_driver_offer_bpp.merchant_overlay;

INSERT INTO atlas_driver_offer_bpp.merchant_overlay (id, merchant_id, language, overlay_key, udf1, image_url, title, description, ok_button_text, cancel_button_text, actions, link) VALUES
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'PAYMENT_FAILED_AUTOPAY', 'Z9', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_low_account_balance.png', 'Low Account Balance', 'Your bank account balance is low. Add ₹ {#dueAmount#} now to enjoy uninterrupted rides.', 'I’ll add money in my bank', null, '{}', null),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'PAYMENT_FAILED_AUTOPAY', 'Z9', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_low_account_balance.png', 'खाते में कम धनराशि', 'आपके बैंक खाते का शेष बहुत कम है। अब ₹ {#dueAmount#} जोड़ें और निरंतर राइड का आनंद लें।', 'मैं अपने खाते में पैसे जमा कर दूंगा/दूंगी।', null, '{}', null),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'PAYMENT_FAILED_AUTOPAY', 'Z9', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_low_account_balance.png', 'குறைந்த கணக்கு இருப்பு', 'உங்கள் வங்கி கணக்கில் இருப்பு குறைவாக உள்ளது. தடையின்றி சவாரி செய்து மகிழ இப்போதே ₹ {#dueAmount#} சேர்க்கவும்.', 'நான் எனது வங்கியில் பணம் சேர்ப்பேன்', null, '{}', null),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'PAYMENT_FAILED_AUTOPAY', 'Z9', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_low_account_balance.png', 'ಕಡಿಮೆ ಖಾತೆ ಬ್ಯಾಲೆನ್ಸ್', 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯ ಬ್ಯಾಲೆನ್ಸ್ ಕಡಿಮೆಯಾಗಿದೆ. ತಡೆರಹಿತ ಸವಾರಿಗಳನ್ನು ಆನಂದಿಸಲು ಈಗ ₹ {#dueAmount#} ಸೇರಿಸಿ.', 'ನಾನು ನನ್ನ ಬ್ಯಾಂಕ್‌ನಲ್ಲಿ ಹಣವನ್ನು ಸೇರಿಸುತ್ತೇನೆ', null, '{}', null),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'PAYMENT_FAILED_AUTOPAY', null, 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_autopay_payment_failed.png', 'Autopay Payment Failed', 'Clear your Manual dues for non-stop rides!', 'Clear Manual Dues (₹{#dueAmount#})', null, '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'PAYMENT_FAILED_AUTOPAY', null, 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_autopay_payment_failed.png', 'ऑटोपे भुगतान असफल', 'नॉन-स्टॉप सवारी के लिए अपना मैन्युअल शेष चुकाएँ!', 'मैन्युअल शेष चुकाएँ (₹{#dueAmount#})', null, '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'PAYMENT_FAILED_AUTOPAY', null, 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_autopay_payment_failed.png', 'ஆட்டோ பே வழியாக பணம் செலுத்த முடியவில்லை', 'இடைவிடாத சவாரிகளுக்கு உங்கள் நிலுவைத் தொகையைச் செலுத்துங்கள்!', 'கைமுறை நிலுவைத் தொகையை அழிக்கவும் (₹{#dueAmount#})', null, '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'PAYMENT_FAILED_AUTOPAY', null, 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_autopay_payment_failed.png', 'ಆಟೋಪೇ ವಿಫಲವಾಗಿದೆ', 'ತಡೆರಹಿತ ಸವಾರಿ‌ಗಳಿಗಾಗಿ ನಿಮ್ಮ ಮಾನ್ಯುಯಲ್ ಬಾಕಿಯನ್ನು ತೆರವುಗೊಳಿಸಿ!', 'ಮಾನ್ಯುಯಲ್ ಬಾಕಿಯನ್ನು ತೆರವುಗೊಳಿಸಿ (₹{#dueAmount#})', null, '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'PAYMENT_FAILED_MANUAL', 'Z9', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed.png', 'Payment Failed', 'Low account balance. Please add ₹ {#dueAmount#} in your bank account and retry payment.', 'I’ll add money in my bank', null, '{}', null),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'PAYMENT_FAILED_MANUAL', 'Z9', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed.png', 'भुगतान असफल', 'खाते में कम धनराशि| कृपया अपने बैंक खाते में ₹ {#dueAmount#} जमा करे और भुगतान का पुनः प्रयास करें।', 'मैं अपने खाते में पैसे जमा कर दूंगा/दूंगी।', null, '{}', null),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'PAYMENT_FAILED_MANUAL', 'Z9', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed.png', 'பணம் செலுத்த முடியவில்லை', 'வங்கிக் கணக்கில் பணம் குறைவாக உள்ளது. உங்கள் வங்கிக் கணக்கில் ₹ {#dueAmount#} சேர்த்து மீண்டும் பணம் செலுத்த முயற்சிக்கவும்.', 'நான் எனது வங்கியில் பணம் சேர்ப்பேன்', null, '{}', null),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'PAYMENT_FAILED_MANUAL', 'Z9', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed.png', 'ಪಾವತಿ ವಿಫಲವಾಗಿದೆ', 'ಕಡಿಮೆ ಖಾತೆಯ ಬ್ಯಾಲೆನ್ಸ್. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯಲ್ಲಿ ₹ {#dueAmount#} ಸೇರಿಸಿ ಮತ್ತು ಪಾವತಿಯನ್ನು ಮರುಪ್ರಯತ್ನಿಸಿ.', 'ನಾನು ನನ್ನ ಬ್ಯಾಂಕ್‌ನಲ್ಲಿ ಹಣವನ್ನು ಸೇರಿಸುತ್ತೇನೆ', null, '{}', null),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'PAYMENT_FAILED_MANUAL', null, 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed.png', 'Payment Failed', 'Clear your Manual dues for non-stop rides!', 'Clear Manual Dues (₹{#dueAmount#})', null, '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'PAYMENT_FAILED_MANUAL', null, 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed.png', 'भुगतान असफल', 'नॉन-स्टॉप सवारी के लिए अपना मैन्युअल शेष चुकाएँ!', 'मैन्युअल शेष चुकाएँ (₹{#dueAmount#})', null, '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'PAYMENT_FAILED_MANUAL', null, 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed.png', 'பணம் செலுத்த முடியவில்லை', 'இடைவிடாத சவாரிகளுக்கு உங்கள் நிலுவைத் தொகையைச் செலுத்துங்கள்!', 'கைமுறை நிலுவைத் தொகையை அழிக்கவும் (₹{#dueAmount#})', null, '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'PAYMENT_FAILED_MANUAL', null, 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed.png', 'ಪಾವತಿ ವಿಫಲವಾಗಿದೆ', 'ತಡೆರಹಿತ ಸವಾರಿ‌ಗಳಿಗಾಗಿ ನಿಮ್ಮ ಮಾನ್ಯುಯಲ್ ಬಾಕಿಯನ್ನು ತೆರವುಗೊಳಿಸಿ!', 'ಮಾನ್ಯುಯಲ್ ಬಾಕಿಯನ್ನು ತೆರವುಗೊಳಿಸಿ (₹{#dueAmount#})', null, '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'PAYMENT_PENDING', 'AUTOPAY', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending.png', 'Payment Pending', 'To continue taking rides on Namma Yatri, clear your payment dues', 'Clear Dues (₹{#dueAmount#})', 'Cancel', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'PAYMENT_PENDING', 'AUTOPAY', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending.png', 'भुगतान प्रलंबित', 'नम्मा यात्री पर यात्रा जारी रखने के लिए, अपना शेष भुगतान चुकाएँ', 'शेष राशि चुकाएँ (₹{#dueAmount#})', 'Cancel', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'PAYMENT_PENDING', 'AUTOPAY', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending.png', 'கட்டணம் நிலுவையில் உள்ளது', 'நம்ம யாத்ரியில் தொடர்ந்து சவாரி செய்ய, உங்கள் நிலுவைத் தொகையைச் செலுத்துங்கள்', 'நிலுவைத் தொகையை செலுத்துங்கள் (₹{#dueAmount#})', 'Cancel', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'PAYMENT_PENDING', 'AUTOPAY', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending.png', 'ಪಾವತಿ ಬಾಕಿಯಿದೆ', 'ನಮ್ಮ ಯಾತ್ರಿಯಲ್ಲಿ ಸವಾರಿ ಮಾಡುವುದನ್ನು ಮುಂದುವರಿಸಲು, ನಿಮ್ಮ ಪಾವತಿಯ ಬಾಕಿಯನ್ನು ತೆರವುಗೊಳಿಸಿ', 'ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ (₹{#dueAmount#})', 'Cancel', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'PAYMENT_PENDING', 'MANUAL', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending.png', 'Payment Pending', 'To continue taking rides on Namma Yatri, clear your payment dues', 'Clear Dues (₹{#dueAmount#})', 'Cancel', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'PAYMENT_PENDING', 'MANUAL', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending.png', 'भुगतान प्रलंबित', 'नम्मा यात्री पर यात्रा जारी रखने के लिए, अपना शेष भुगतान चुकाएँ', 'शेष राशि चुकाएँ (₹{#dueAmount#})', 'Cancel', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'PAYMENT_PENDING', 'MANUAL', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending.png', 'கட்டணம் நிலுவையில் உள்ளது', 'நம்ம யாத்ரியில் தொடர்ந்து சவாரி செய்ய, உங்கள் நிலுவைத் தொகையைச் செலுத்துங்கள்', 'நிலுவைத் தொகையை செலுத்துங்கள் (₹{#dueAmount#})', 'Cancel', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'PAYMENT_PENDING', 'MANUAL', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending.png', 'ಪಾವತಿ ಬಾಕಿಯಿದೆ', 'ನಮ್ಮ ಯಾತ್ರಿಯಲ್ಲಿ ಸವಾರಿ ಮಾಡುವುದನ್ನು ಮುಂದುವರಿಸಲು, ನಿಮ್ಮ ಪಾವತಿಯ ಬಾಕಿಯನ್ನು ತೆರವುಗೊಳಿಸಿ', 'ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ (₹{#dueAmount#})', 'Cancel', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'INVOICE_GENERATED_AUTOPAY', 'AUTOPAY', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_notification.png', 'Invoice Generated', 'Invoice generated for yesterday. Keep enough account balance!', 'View Due Details', 'Got It', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'INVOICE_GENERATED_AUTOPAY', 'AUTOPAY', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_notification.png', 'बिल तैयार हो गया', 'कल के लिए चालान उत्पन्न हुआ। पर्याप्त रकम खाते में शेष रखें!', 'देय विवरण देखें', 'समझ गया', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'INVOICE_GENERATED_AUTOPAY', 'AUTOPAY', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_notification.png', 'விலைப்பட்டியல் உருவாக்கப்பட்டது', 'நேற்றைய விலைப்பட்டியல் உருவாக்கப்பட்டது. போதுமான கணக்கு இருப்பை வைத்திருங்கள்!', 'உரிய விவரங்களைக் காண்க', 'அறிந்துகொண்டேன்', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'INVOICE_GENERATED_AUTOPAY', 'AUTOPAY', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_notification.png', 'ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಲಾಗಿದೆ', 'ನಿನ್ನೆಯ ಸರಕುಪಟ್ಟಿ ರಚಿಸಲಾಗಿದೆ. ಸಾಕಷ್ಟು ಖಾತೆ ಬ್ಯಾಲೆನ್ಸ್ ಇರಿಸಿ!', 'ಬಾಕಿಯ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ', 'ಅರ್ಥವಾಯಿತು', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'INVOICE_GENERATED_MANUAL', 'MANUAL', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_notification.png', 'Clear your dues', 'Invoice generated for yesterday. Clear dues early for non-stop rides!', 'Clear Dues (₹{#dueAmount#})', 'Maybe Later', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'INVOICE_GENERATED_MANUAL', 'MANUAL', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_notification.png', 'अपना शेष चुकाएँ!', 'कल के लिए चालान उत्पन्न हुआ है। नॉन-स्टॉप सवारी के लिए शेष राशि का शीघ्र भुगतान करें!', 'शेष राशि चुकाएँ (₹{#dueAmount#})', 'शायद बाद में', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'INVOICE_GENERATED_MANUAL', 'MANUAL', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_notification.png', 'உங்கள் நிலுவைத் தொகையை செலுத்துங்கள்', 'நேற்றைய விலைப்பட்டியல் உருவாக்கப்பட்டது. இடைவிடாத சவாரிகளுக்கான நிலுவைத் தொகையை முன்கூட்டியே செலுத்தவும்!', 'நிலுவைத் தொகையை செலுத்துங்கள் (₹{#dueAmount#})', 'பின்னர்', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'INVOICE_GENERATED_MANUAL', 'MANUAL', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_notification.png', 'ನಿಮ್ಮ ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ', 'ನಿನ್ನೆಯ ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಲಾಗಿದೆ. ತಡೆರಹಿತ ಸವಾರಿ‌ಗಳಿಗಾಗಿ ಮುಂಚಿತವಾಗಿ ಬಾಕಿಯನ್ನು ತೆರವುಗೊಳಿಸಿ!', 'ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ (₹{#dueAmount#})', 'ಬಹುಶಃ ನಂತರ', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'FREE_TRIAL_DAYS_LEFT_3', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_2_days_left.png', 'Free trial ending in 2 days!', 'Setup Autopay for easy payments', 'Setup Autopay', 'Not Now', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'FREE_TRIAL_DAYS_LEFT_3', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_2_days_left.png', 'नि:शुल्क परीक्षण 2 दिनों में समाप्त हो रहा है!', 'आसान भुगतान के लिए ऑटोपे सेटअप करें', 'ऑटोपे सेटअप करें', 'अभी नहीं', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'FREE_TRIAL_DAYS_LEFT_3', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_2_days_left.png', 'இலவச சவாரிகள் 2 நாட்களில் முடிவடைகிறது!', 'எளிதாகப் பணம் செலுத்துவதற்குத் ஆட்டோ பே -வை  அமைக்கவும்', 'ஆட்டோ பே -வை  அமைக்கவும்', 'இப்போது இல்லை', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'FREE_TRIAL_DAYS_LEFT_3', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_2_days_left.png', 'ಫ್ರೀ ಟ್ರಯಲ್ 2 ದಿನಗಳಲ್ಲಿ ಮುಗಿಯುತ್ತದೆ!', 'ಸುಲಭ ಪಾವತಿಗಳಿಗಾಗಿ ಆಟೋಪೇ ಸೆಟಪ್ ಮಾಡಿ', 'ಸೆಟಪ್ ಆಟೋಪೇ', 'ಈಗ ಸಾಧ್ಯವಿಲ್ಲ', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'FREE_TRIAL_DAYS_LEFT_2', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_1_days_left.png', 'Free trial ending tomorrow!', 'Setup Autopay for easy payments', 'Setup Autopay', 'Not Now', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'FREE_TRIAL_DAYS_LEFT_2', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_1_days_left.png', 'नि:शुल्क परीक्षण कल समाप्त हो रहा है!', 'आसान भुगतान के लिए ऑटोपे सेटअप करें', 'ऑटोपे सेटअप करें', 'अभी नहीं', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'FREE_TRIAL_DAYS_LEFT_2', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_1_days_left.png', 'இலவச சவாரிகள் நாளை முடிவடைகிறது!', 'எளிதாகப் பணம் செலுத்துவதற்குத் ஆட்டோ பே -வை  அமைக்கவும்', 'ஆட்டோ பே -வை  அமைக்கவும்', 'இப்போது இல்லை', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'FREE_TRIAL_DAYS_LEFT_2', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_1_days_left.png', 'ಫ್ರೀ ಟ್ರಯಲ್ ನಾಳೆ ಮುಗಿಯುತ್ತದೆ!', 'ಸುಲಭ ಪಾವತಿಗಳಿಗಾಗಿ ಆಟೋಪೇ ಸೆಟಪ್ ಮಾಡಿ', 'ಸೆಟಪ್ ಆಟೋಪೇ', 'ಈಗ ಸಾಧ್ಯವಿಲ್ಲ', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'FREE_TRIAL_DAYS_LEFT_1', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_offer_ends_tonight.png', 'Free trial ends tonight!', 'Setup Autopay for easy payments', 'Setup Autopay', 'Not Now', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'FREE_TRIAL_DAYS_LEFT_1', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_offer_ends_tonight.png', 'नि:शुल्क परीक्षण आज रात समाप्त हो रहा है!', 'आसान भुगतान के लिए ऑटोपे सेटअप करें', 'ऑटोपे सेटअप करें', 'अभी नहीं', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'FREE_TRIAL_DAYS_LEFT_1', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_offer_ends_tonight.png', 'இலவச சவாரிகள் இன்று இரவு முடிவடைகிறது!', 'எளிதாகப் பணம் செலுத்துவதற்குத் ஆட்டோ பே -வை  அமைக்கவும்', 'ஆட்டோ பே -வை  அமைக்கவும்', 'இப்போது இல்லை', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'FREE_TRIAL_DAYS_LEFT_1', 'AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_offer_ends_tonight.png', 'ಫ್ರೀ ಟ್ರಯಲ್ ಇಂದು ರಾತ್ರಿ ಮುಗಿಯುತ್ತದೆ!', 'ಸುಲಭ ಪಾವತಿಗಳಿಗಾಗಿ ಆಟೋಪೇ ಸೆಟಪ್ ಮಾಡಿ', 'ಸೆಟಪ್ ಆಟೋಪೇ', 'ಈಗ ಸಾಧ್ಯವಿಲ್ಲ', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'FREE_TRIAL_DAYS_LEFT_3', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_2_days_left.png', 'Free trial ending in 2 days!', 'Join a plan to continue taking rides', 'Join Now', 'Not Now', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'FREE_TRIAL_DAYS_LEFT_3', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_2_days_left.png', 'नि:शुल्क परीक्षण 2 दिनों में समाप्त हो रहा है!', 'सवारी लेना जारी रखने की योजना में शामिल हों', 'अब शामिल हों', 'अभी नहीं', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'FREE_TRIAL_DAYS_LEFT_3', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_2_days_left.png', 'இலவச சவாரிகள் 2 நாட்களில் முடிவடைகிறது!', 'தொடர்ந்து சவாரி செய்வதற்கான திட்டத்தில் சேரவும்', 'இப்போது சேரவும்', 'இப்போது இல்லை', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'FREE_TRIAL_DAYS_LEFT_3', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_2_days_left.png', 'ಫ್ರೀ ಟ್ರಯಲ್ 2 ದಿನಗಳಲ್ಲಿ ಮುಗಿಯುತ್ತದೆ!', 'ಸವಾರಿಗಳನ್ನು ಮುಂದುವರಿಸಲು ಪ್ಲಾನ್‌ಗೆ ಸೇರಿಕೊಳ್ಳಿ', 'ಈಗಲೇ ಸೇರಿ', 'ಈಗ ಸಾಧ್ಯವಿಲ್ಲ', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'FREE_TRIAL_DAYS_LEFT_2', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_1_days_left.png', 'Free trial ending tomorrow!', 'Join a plan to continue taking rides', 'Join Now', 'Not Now', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'FREE_TRIAL_DAYS_LEFT_2', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_1_days_left.png', 'नि:शुल्क परीक्षण कल समाप्त हो रहा है!', 'सवारी लेना जारी रखने की योजना में शामिल हों', 'अब शामिल हों', 'अभी नहीं', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'FREE_TRIAL_DAYS_LEFT_2', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_1_days_left.png', 'இலவச சவாரிகள் நாளை முடிவடைகிறது!', 'தொடர்ந்து சவாரி செய்வதற்கான திட்டத்தில் சேரவும்', 'இப்போது சேரவும்', 'இப்போது இல்லை', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'FREE_TRIAL_DAYS_LEFT_2', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_1_days_left.png', 'ಫ್ರೀ ಟ್ರಯಲ್ ನಾಳೆ ಮುಗಿಯುತ್ತದೆ!', 'ಸವಾರಿಗಳನ್ನು ಮುಂದುವರಿಸಲು ಪ್ಲಾನ್‌ಗೆ ಸೇರಿಕೊಳ್ಳಿ','ಈಗಲೇ ಸೇರಿ', 'ಈಗ ಸಾಧ್ಯವಿಲ್ಲ', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),

    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'ENGLISH', 'FREE_TRIAL_DAYS_LEFT_1', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_offer_ends_tonight.png', 'Free trial ends tonight!', 'Join a plan to continue taking rides', 'Join Now', 'Not Now', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'HINDI', 'FREE_TRIAL_DAYS_LEFT_1', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_offer_ends_tonight.png', 'नि:शुल्क परीक्षण आज रात समाप्त हो रहा है!', 'सवारी लेना जारी रखने की योजना में शामिल हों', 'अब शामिल हों', 'अभी नहीं', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'TAMIL', 'FREE_TRIAL_DAYS_LEFT_1', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_offer_ends_tonight.png', 'இலவச சவாரிகள் இன்று இரவு முடிவடைகிறது!', 'தொடர்ந்து சவாரி செய்வதற்கான திட்டத்தில் சேரவும்', 'இப்போது சேரவும்', 'இப்போது இல்லை', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans'),
    (atlas_driver_offer_bpp.uuid_generate_v4(), 'favorit0-0000-0000-0000-00000favorit', 'KANNADA', 'FREE_TRIAL_DAYS_LEFT_1', 'PLAN_NOT_SELECTED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_offer_ends_tonight.png', 'ಫ್ರೀ ಟ್ರಯಲ್ ಇಂದು ರಾತ್ರಿ ಮುಗಿಯುತ್ತದೆ!', 'ಸವಾರಿಗಳನ್ನು ಮುಂದುವರಿಸಲು ಪ್ಲಾನ್‌ಗೆ ಸೇರಿಕೊಳ್ಳಿ', 'ಈಗಲೇ ಸೇರಿ', 'ಈಗ ಸಾಧ್ಯವಿಲ್ಲ', '{"OPEN_LINK"}', 'https://nammayatri.in/p/?vp=plans');


    -- please change the merchantId to the merchantId of nammayatri