ALTER TABLE atlas_driver_offer_bpp.vehicle_registration_certificate ADD COLUMN manufacturer_model text;
ALTER TABLE atlas_driver_offer_bpp.vehicle_registration_certificate ADD COLUMN review_required boolean;
ALTER TABLE atlas_driver_offer_bpp.vehicle_registration_certificate ADD COLUMN reviewed_at timestamp with time zone;