insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, '' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type != 'RCInsurance');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, '' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type != 'RCInsurance');

update atlas_driver_offer_bpp.document_verification_config set title = 'Vehicle Registration Certificate', document_type = 'VehicleRegistrationCertificate', is_mandatory = true where document_type = 'RC';

update atlas_driver_offer_bpp.document_verification_config set title = 'Driving License', document_type = 'DriverLicense', is_mandatory = true where document_type = 'DL';

-- VEHICLE PERMIT
insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, 'RC is Mandatory' as disable_warning, 'VehiclePermit' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Vehicle Permit' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, 'RC is Mandatory' as disable_warning, 'VehiclePermit' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Vehicle Permit' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

-- VEHICLE PUC
insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, 'RC is Mandatory' as disable_warning, 'VehiclePUC' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Vehicle PUC Certificate' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, 'RC is Mandatory' as disable_warning, 'VehiclePUC' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Vehicle PUC Certificate' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

-- VehicleFitnessCertificate
insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, 'RC is Mandatory' as disable_warning, 'VehicleFitnessCertificate' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Fitness Certificate (FC)' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, 'RC is Mandatory' as disable_warning, 'VehicleFitnessCertificate' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Fitness Certificate (FC)' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

-- VehicleInsurance
insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, 'RC is Mandatory' as disable_warning, 'VehicleInsurance' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Vehicle Insurance' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, 'RC is Mandatory' as disable_warning, 'VehicleInsurance' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Vehicle Insurance' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

-- Permissions
insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, 'Permissions' as document_type, false as is_disabled, false as is_hidden, true as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Grant Permissions' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, 'Permissions' as document_type, false as is_disabled, false as is_hidden, true as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Grant Permissions' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

-- AadhaarCard
insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, 'AadhaarCard' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Aadhaar Card' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, 'AadhaarCard' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Aadhaar Card' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');


-- PanCard
insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, 'PanCard' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'PAN Card' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, 'PanCard' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'PAN Card' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

-- ProfilePhoto
insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, 'ProfilePhoto' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Profile Photo' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{}' as dependency_document_type, null as description, '' as disable_warning, 'ProfilePhoto' as document_type, false as is_disabled, false as is_hidden, false as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, 'Profile Photo' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.onboarding_document_configs where document_type = 'RC');


-- ONLY RUN THESE AFTER UI RELEASE
-- update atlas_driver_offer_bpp.document_verification_config set is_mandatory = true where document_type in ('VehiclePermit', 'VehiclePUC', 'VehicleInsurance', 'VehicleFitnessCertificate') and vehicle_category = 'CAR';

-- update atlas_driver_offer_bpp.document_verification_config set is_mandatory = true where document_type in ('PanCard', 'AadhaarCard', 'ProfilePhoto') and vehicle_category = 'CAR';

-- RUN IT AFTER THE RELEASE
DROP TABLE atlas_driver_offer_bpp.onboarding_document_configs;

  -- | SubscriptionPlan
  -- | ProfilePhoto
  -- | AadhaarCard
  -- | PanCard
  -- | NO_OPTION