insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'ENGLISH' , 'Vehicle Registration Certificate' ,  'VehicleRegistrationCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ವಾಹನ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ',  'VehicleRegistrationCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'வாகனப் பதிவுச் சான்றிதழ்' ,  'VehicleRegistrationCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'വാഹന രജിസ്‌ട്രേഷൻ സർട്ടിഫിക്കറ്റ്',  'VehicleRegistrationCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'HINDI' , 'दस्तावेज़ समीक्षा में..' ,  'VehicleRegistrationCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'వెహికల్ రిజిస్ట్రేషన్ సర్టిఫికెట్' ,  'VehicleRegistrationCertificate_Title', now());

insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'డ్రైవర్ లైసెన్స్', 'DriverLicense_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'ప్రొఫైల్ ఫోటో', 'ProfilePhoto_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'పాన్ కార్డు', 'PanCard_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'ఆధార్ కార్డు', 'AadhaarCard_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'వెహికల్ పర్మిట్', 'VehiclePermit_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'వెహికల్ ఇన్సురంచె', 'VehicleInsurance_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'వెహికల్ PUC', 'VehiclePUC_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'వెహికల్ ఫిట్నెస్ సర్టిఫికెట్', 'VehicleFitnessCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'గ్రాంట్ పర్మిషన్', 'Permissions_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TELUGU' , 'నమ్మ యాత్రి ప్లన్స్', 'SubscriptionPlan_Title', now());

insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ಚಾಲಕ ಪರವಾನಗಿ', 'DriverLicense_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ', 'ProfilePhoto_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ಪ್ಯಾನ್ ಕಾರ್ಡ್', 'PanCard_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ಆಧಾರ್ ಕಾರ್ಡ್', 'AadhaarCard_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ವಾಹನ ಪರವಾನಗಿ', 'VehiclePermit_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ವಾಹನ ವಿಮೆ', 'VehicleInsurance_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ವಾಹನ ಪಿಯುಸಿ', 'VehiclePUC_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ವಾಹನದ ಫಿಟ್ನೆಸ್ ಪ್ರಮಾಣಪತ್ರ', 'VehicleFitnessCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ಅನುಮತಿ ನೀಡಿ', 'Permissions_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'KANNADA' , 'ನಮ್ಮ ಯಾತ್ರಿ ಯೋಜನೆಗಳು', 'SubscriptionPlan_Title', now());

insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'வாகனப் பதிவுச் சான்றிதழ்', 'Vehicle RegistrationCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'வாகன ஒட்டி உரிமம்', 'DriverLicense_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'சுயவிவரப் புகைப்படம்', 'ProfilePhoto_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'பான் கார்டு', 'PanCard_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'ஆதார் அட்டை', 'AadhaarCard_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'வாகன அனுமதி', 'VehiclePermit_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'வாகன காப்பீடு', 'VehicleInsurance_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'வாகன பியுசி', 'VehiclePUC_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'வாகனத் தகுதிச் சான்றிதழ்', 'VehicleFitnessCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'அனுமதி வழங்கவும்', 'Permissions_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now(), atlas_driver_offer_bpp.uuid_generate_v4() ,'TAMIL' , 'நம்ம யாத்ரி திட்டங்கள்', 'SubscriptionPlan_Title', now());

insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'ഡ്രൈവർ ലൈസൻസ്', 'DriverLicense_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'പ്രൊഫൈൽ ഫോട്ടോ', 'ProfilePhoto_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'പാൻ കാർഡ്', 'PanCard_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'ആധാർ കാർഡ്', 'AadhaarCard_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'വാഹന പെർമിറ്റ്', 'VehiclePermit_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'വാഹന ഇൻഷ്യൂറൻസ്', 'VehicleInsurance_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'വാഹന പി യൂ സി', 'VehiclePUC_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'വാഹന ഫിറ്റ്നസ് സർട്ടിഫിക്കറ്റ്', 'VehicleFitnessCertificate_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'അനുമതി നൽകുക', 'Permissions_Title', now());
insert into atlas_driver_offer_bpp.translations(created_at, id, language, message, message_key, updated_at) VALUES (now() , atlas_driver_offer_bpp.uuid_generate_v4() ,'MALAYALM' , 'നമ്മ യാത്രി പ്ലാൻസ്', 'SubscriptionPlan_Title', now());

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, '' as disable_warning, 'SubscriptionPlan' as document_type, false as is_disabled, false as is_hidden, true as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, json_build_array() as supported_vehicle_classes_json, 'Namma Yatri Plans' as title, 'AUTO_CATEGORY' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.document_verification_config where document_type = 'VehicleRegistrationCertificate' and vehicle_category = 'AUTO_CATEGORY' and merchant_operating_city_id in ('c3ef0121-1e35-4782-b1d3-d39e398b0382', 'f067bccf-5b34-fb51-a5a3-9d6fa6baac26', 'c98da615-0515-4d93-8e12-1253e5b369a2'));

insert into atlas_driver_offer_bpp.document_verification_config (check_expiry, check_extraction, dependency_document_type, description, disable_warning, document_type, is_disabled, is_hidden, is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, supported_vehicle_classes_json, title, vehicle_category, vehicle_class_check_type, created_at, updated_at)
(select check_expiry, false as check_extraction, '{VehicleRegistrationCertificate}' as dependency_document_type, null as description, '' as disable_warning, 'SubscriptionPlan' as document_type, false as is_disabled, false as is_hidden, true as is_mandatory, max_retry_count, merchant_id, merchant_operating_city_id, rc_number_prefix_list, json_build_array() as supported_vehicle_classes_json, 'Yatri Plans' as title, 'CAR' as vehicle_category, vehicle_class_check_type, now() as created_at, now() as updated_at from atlas_driver_offer_bpp.document_verification_config where document_type = 'VehicleRegistrationCertificate' and vehicle_category = 'CAR' and merchant_operating_city_id in ('e35f2a66-58fe-be6e-cafd-38e67165fd84'));