INSERT INTO atlas_driver_offer_bpp.driver_pool_config (
    actual_distance_threshold,
    created_at,
    distance_based_batch_split,
    driver_batch_size,
    driver_position_info_expiry,
    driver_quote_limit,
    driver_request_count_limit,
    driver_to_destination_distance_threshold,
    driver_to_destination_duration,
    id,
    max_driver_quotes_required,
    max_number_of_batches,
    max_parallel_search_requests,
    max_radius_of_search,
    merchant_id,
    merchant_operating_city_id,
    min_radius_of_search,
    pool_sorting_type,
    radius_shrink_value_for_drivers_on_ride,
    radius_step_size,
    schedule_try_times,
    single_batch_process_time,
    threshold_to_ignore_actual_distance_threshold,
    trip_category,
    trip_distance,
    updated_at,
    vehicle_variant,
    area,
    time_bound
)
SELECT
    2000,
    now(),
    '{"BatchSplitByPickupDistance {batchSplitSize = 4, batchSplitDelay = 0 }","BatchSplitByPickupDistance { batchSplitSize = 4, batchSplitDelay = 3 }"}',
    12,
    null,
    2,
    2,
    300,
    10,
    atlas_driver_offer_bpp.uuid_generate_v4(),
    1,
    6,
    3,
    5000,
    m.merchant_id,
    m.id,
    1000,
    'Random',
    300,
    1000,
    '{1800,900,300}',
    25,
    null,
    'InterCity_OnDemandStaticOffer',
    50000,
    now(),
    'SEDAN',
    'Default',
    'BoundedPeaks {monday = [(7:00:01,23:00:00)], tuesday = [(7:00:01,23:00:00)], wednesday = [(7:00:01,23:00:00)], thursday = [(7:00:01,23:00:00)], friday = [(7:00:01,23:00:00)], saturday = [(7:00:01,23:00:00)], sunday = [(7:00:01,23:00:00)]}'
FROM
    atlas_driver_offer_bpp.merchant_operating_city m
WHERE
    m.merchant_short_id = 'NAMMA_YATRI_PARTNER';

INSERT INTO atlas_driver_offer_bpp.driver_pool_config (
    actual_distance_threshold,
    created_at,
    distance_based_batch_split,
    driver_batch_size,
    driver_position_info_expiry,
    driver_quote_limit,
    driver_request_count_limit,
    driver_to_destination_distance_threshold,
    driver_to_destination_duration,
    id,
    max_driver_quotes_required,
    max_number_of_batches,
    max_parallel_search_requests,
    max_radius_of_search,
    merchant_id,
    merchant_operating_city_id,
    min_radius_of_search,
    pool_sorting_type,
    radius_shrink_value_for_drivers_on_ride,
    radius_step_size,
    schedule_try_times,
    single_batch_process_time,
    threshold_to_ignore_actual_distance_threshold,
    trip_category,
    trip_distance,
    updated_at,
    vehicle_variant,
    area,
    time_bound
)
SELECT
    2000,
    now(),
    '{"BatchSplitByPickupDistance {batchSplitSize = 4, batchSplitDelay = 0 }","BatchSplitByPickupDistance { batchSplitSize = 4, batchSplitDelay = 3 }"}',
    12,
    null,
    2,
    2,
    300,
    10,
    atlas_driver_offer_bpp.uuid_generate_v4(),
    1,
    6,
    3,
    5000,
    m.merchant_id,
    m.id,
    1000,
    'Random',
    300,
    1000,
    '{3600,1800,900,300}',
    25,
    null,
    'InterCity_OnDemandStaticOffer',
    100000,
    now(),
    'SEDAN',
    'Default',
    'BoundedPeaks {monday = [(7:00:01,23:00:00)], tuesday = [(7:00:01,23:00:00)], wednesday = [(7:00:01,23:00:00)], thursday = [(7:00:01,23:00:00)], friday = [(7:00:01,23:00:00)], saturday = [(7:00:01,23:00:00)], sunday = [(7:00:01,23:00:00)]}'
FROM
    atlas_driver_offer_bpp.merchant_operating_city m
WHERE
    m.merchant_short_id = 'NAMMA_YATRI_PARTNER';

-- Todo: Similarly add other configs