-- STANDARD plan
INSERT INTO atlas_driver_offer_bpp.plan (
    id,
    merchant_id,
    payment_mode,
    frequency,
    plan_base_amount,
    name,
    description,
    max_amount,
    registration_amount,
    is_offer_applicable,
    max_credit_limit,
    free_ride_count,
    plan_type,
    cgst_percentage,
    max_mandate_amount,
    merchant_op_city_id,
    sgst_percentage,
    billing_type,
    validity_in_days,
    service_name,
    vehicle_category,
    allow_strike_off,
    is_fleet_owner_plan
)
SELECT
    atlas_driver_offer_bpp.uuid_generate_v4(),
    m.merchant_id,
    'MANUAL',
    'FLEXIBLE',
    'RECHARGE_5000.0',
    'STANDARD',
    'Enjoy rides worth 5K in 500!',
    0,
    500,
    TRUE,
    0,
    0,
    'SUBSCRIPTION',
    0.09,
    0.0,
    m.id,
    0.09,
    'PREPAID',
    365,
    'PREPAID_SUBSCRIPTION',
    'CAR',
    TRUE,
    TRUE
FROM atlas_driver_offer_bpp.merchant_operating_city AS m
WHERE m.city = 'Delhi'
  AND m.merchant_short_id = 'MSIL_PARTNER';

-- ECONOMY plan
INSERT INTO atlas_driver_offer_bpp.plan (
    id,
    merchant_id,
    payment_mode,
    frequency,
    plan_base_amount,
    name,
    description,
    max_amount,
    registration_amount,
    is_offer_applicable,
    max_credit_limit,
    free_ride_count,
    plan_type,
    cgst_percentage,
    max_mandate_amount,
    merchant_op_city_id,
    sgst_percentage,
    billing_type,
    validity_in_days,
    service_name,
    vehicle_category,
    allow_strike_off,
    is_fleet_owner_plan
)
SELECT
    atlas_driver_offer_bpp.uuid_generate_v4(),
    m.merchant_id,
    'MANUAL',
    'FLEXIBLE',
    'RECHARGE_500.0',
    'ECONOMY',
    'Enjoy rides worth 500 in 50!',
    0,
    50,
    TRUE,
    0,
    0,
    'SUBSCRIPTION',
    0.09,
    0.0,
    m.id,
    0.09,
    'PREPAID',
    365,
    'PREPAID_SUBSCRIPTION',
    'CAR',
    TRUE,
    TRUE
FROM atlas_driver_offer_bpp.merchant_operating_city AS m
WHERE m.city = 'Delhi'
  AND m.merchant_short_id = 'MSIL_PARTNER';
