CREATE INDEX IF NOT EXISTS idx_pg_payment_settlement_report_txn_date ON atlas_driver_offer_bpp.pg_payment_settlement_report USING brin (txn_date);
CREATE INDEX IF NOT EXISTS idx_pg_payment_settlement_report_settlement_date ON atlas_driver_offer_bpp.pg_payment_settlement_report USING brin (settlement_date);
CREATE INDEX IF NOT EXISTS idx_pg_payment_settlement_report_reference_id ON atlas_driver_offer_bpp.pg_payment_settlement_report USING btree (reference_id);
CREATE INDEX IF NOT EXISTS idx_pg_payment_settlement_report_order_id ON atlas_driver_offer_bpp.pg_payment_settlement_report USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_pg_payment_settlement_report_settlement_id ON atlas_driver_offer_bpp.pg_payment_settlement_report USING btree (settlement_id);
CREATE INDEX IF NOT EXISTS idx_pg_payment_settlement_report_pg_approval_code ON atlas_driver_offer_bpp.pg_payment_settlement_report USING btree (pg_approval_code);
CREATE INDEX IF NOT EXISTS idx_pg_payment_settlement_report_utr ON atlas_driver_offer_bpp.pg_payment_settlement_report USING btree (utr);
