name: mock-payment
version: 0.1.0.0
github: "nammayatri/nammayatri"
license: AllRightsReserved
author: "nammayatri"
maintainer: "nammayatri"
copyright: "2024 Juspay Technologies Private Limited"

flags:
  Local:
    description: Enable this flag for faster compile times
    manual: true
    default: false

description: Mock Payment Server for local testing

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - TypeSynonymInstances
  - UndecidableInstances

dependencies:
  - base >= 4.7 && < 5
  - euler-hs
  - record-hasfield
  - record-dot-preprocessor

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wunused-imports
  - -Werror
  - -fplugin=RecordDotPreprocessor

library:
  source-dirs: src
  ghc-options:
    - -Wincomplete-uni-patterns
    - -Wwarn=ambiguous-fields
  when:
    - condition: flag(Local)
      then:
        ghc-options:
          - -O0
          - -funfolding-use-threshold20
          - -fno-cse
          - -fmax-simplifier-iterations1
          - -fno-specialise-aggressively
          - -j4
      else:
        ghc-options:
          - -O2
          - -j4
  dependencies:
    - aeson
    - mobility-core
    - bytestring
    - containers
    - http-client
    - http-client-tls
    - http-types
    - servant
    - servant-server
    - servant-client
    - servant-client-core
    - text
    - time
    - wai
    - warp
    - payment
    - hedis
    - unordered-containers
    - uuid

executables:
  mock-payment-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
      - -Wincomplete-uni-patterns
    when:
    - condition: flag(Local)
      then:
        ghc-options:
          - -O0
          - -funfolding-use-threshold20
          - -fno-cse
          - -fmax-simplifier-iterations1
          - -fno-specialise-aggressively
          - -j4
      else:
        ghc-options:
          - -O2
          - -j4
    dependencies:
      - mock-payment
      - mobility-core
