name: mock-registry
version: 0.1.0.0
github: "juspay/beckn"
license: AllRightsReserved
author: "Juspay"
maintainer: "Juspay"
copyright: "2020 Juspay Technologies Private Limited"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://bitbucket.org/juspay/beckn#readme>

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - FlexibleInstances
  - MultiParamTypeClasses
  - GADTs
  - UndecidableInstances
  - DeriveAnyClass
  - DeriveGeneric
  - TypeOperators
  - DuplicateRecordFields
  - RecordWildCards
  - OverloadedStrings
  - TypeApplications

dependencies:
  - base >= 4.7 && < 5
  - euler-hs
  - record-hasfield
  - record-dot-preprocessor
  - servant-server
  - warp
  - time

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -fplugin=RecordDotPreprocessor

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -fhide-source-paths
    - -Wno-unrecognised-pragmas
    - -Werror
  dependencies:
    - beckn-core

executables:
  mock-registry:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mock-registry
