-- Notification-preference feature: classifies existing atlas_app.merchant_push_notification
-- rows into the new user-facing notification_category bucket
-- (RIDE_RELATED | PROMOTIONAL | OFFERS | PAYMENTS | SAFETY | ACCOUNT), based on their
-- existing fcm_notification_type (Kernel.External.Notification.Interface.Types.Category).
--
-- Idempotent: only touches rows that haven't been classified yet, so re-running after a
-- manual dashboard reclassification of some rows will not clobber those.
--
-- This is a best-effort default mapping — review before/after running in an environment
-- and adjust categories per product intent. New notification keys added after this
-- migration land as RIDE_RELATED by default (Storage.Queries.MerchantPushNotification
-- fromTType) until explicitly classified here or via the dashboard.

UPDATE atlas_app.merchant_push_notification
SET notification_category = CASE fcm_notification_type
  -- Account / onboarding / compliance
  WHEN 'REGISTRATION_APPROVED' THEN 'ACCOUNT'
  WHEN 'ACCOUNT_DISABLED' THEN 'ACCOUNT'
  WHEN 'ACCOUNT_DELETED' THEN 'ACCOUNT'
  WHEN 'DOCUMENT_INVALID' THEN 'ACCOUNT'
  WHEN 'DOCUMENT_EXPIRY_REMINDER' THEN 'ACCOUNT'
  WHEN 'FLEET_REQUEST_APPROVED' THEN 'ACCOUNT'
  WHEN 'FLEET_REQUEST_REJECTED' THEN 'ACCOUNT'
  WHEN 'FLEET_CONSENT' THEN 'ACCOUNT'
  WHEN 'OPERATOR_CONSENT' THEN 'ACCOUNT'
  WHEN 'DRIVER_UNLINK_FROM_FLEET' THEN 'ACCOUNT'
  WHEN 'DRIVER_UNLINK_FROM_OPERATOR' THEN 'ACCOUNT'
  WHEN 'FLEET_UNLINK_FROM_OPERATOR' THEN 'ACCOUNT'
  WHEN 'DRIVER_UNBLOCKED' THEN 'ACCOUNT'
  WHEN 'FILE_UPLOADED' THEN 'ACCOUNT'
  WHEN 'TRAINING_VIDEO' THEN 'ACCOUNT'
  WHEN 'DRIVER_INSPECTION' THEN 'ACCOUNT'
  WHEN 'VEHICLE_INSPECTION' THEN 'ACCOUNT'

  -- Safety
  WHEN 'SAFETY_ALERT_DEVIATION' THEN 'SAFETY'
  WHEN 'SAFETY_ALERT_RIDE_STOPPAGE' THEN 'SAFETY'
  WHEN 'FOLLOW_RIDE' THEN 'SAFETY'
  WHEN 'SHARE_RIDE' THEN 'SAFETY'
  WHEN 'SOS_TRIGGERED' THEN 'SAFETY'
  WHEN 'SOS_MOCK_DRILL' THEN 'SAFETY'
  WHEN 'SOS_MOCK_DRILL_NOTIFY' THEN 'SAFETY'
  WHEN 'SOS_RESOLVED' THEN 'SAFETY'
  WHEN 'EMERGENCY_CONTACT_ADDED' THEN 'SAFETY'
  WHEN 'POST_RIDE_SOS_ALERT' THEN 'SAFETY'
  WHEN 'POST_RIDE_SAFETY_CHECK' THEN 'SAFETY'
  WHEN 'EKD_LIVE_CALL_FEEDBACK' THEN 'SAFETY'
  WHEN 'DRUNK_AND_DRIVE_VIOLATION_WARNING' THEN 'SAFETY'

  -- Payments / payouts / refunds
  WHEN 'PAYMENT_PENDING' THEN 'PAYMENTS'
  WHEN 'PAYMENT_OVERDUE' THEN 'PAYMENTS'
  WHEN 'PAYMENT_FAILED' THEN 'PAYMENTS'
  WHEN 'PAYMENT_SUCCESS' THEN 'PAYMENTS'
  WHEN 'PAYMENT_MODE_MANUAL' THEN 'PAYMENTS'
  WHEN 'PAYMENT_NUDGE' THEN 'PAYMENTS'
  WHEN 'PAYOUT_VPA_REMINDER' THEN 'PAYMENTS'
  WHEN 'PAYOUT_INITIATED' THEN 'PAYMENTS'
  WHEN 'PAYOUT_FAILED' THEN 'PAYMENTS'
  WHEN 'PAYOUT_COMPLETED' THEN 'PAYMENTS'
  WHEN 'PREPAID_RECHARGE_SUCCESS' THEN 'PAYMENTS'
  WHEN 'PREPAID_BALANCE_UPDATE' THEN 'PAYMENTS'
  WHEN 'REFUND_PENDING' THEN 'PAYMENTS'
  WHEN 'REFUND_SUCCESS' THEN 'PAYMENTS'
  WHEN 'REFUND_FAILED' THEN 'PAYMENTS'
  WHEN 'REFUND_REQUEST_APPROVED' THEN 'PAYMENTS'
  WHEN 'REFUND_REQUEST_REJECTED' THEN 'PAYMENTS'

  -- Offers / rewards / coins / passes
  WHEN 'DISCOUNT_CHANGED' THEN 'OFFERS'
  WHEN 'COINS_SUCCESS' THEN 'OFFERS'
  WHEN 'PAYOUT_REWARD' THEN 'OFFERS'
  WHEN 'TO_METRO_COINS' THEN 'OFFERS'
  WHEN 'FROM_METRO_COINS' THEN 'OFFERS'
  WHEN 'END_RIDE_OFFERS' THEN 'OFFERS'
  WHEN 'PASS_RELATED' THEN 'OFFERS'

  -- Promotional / engagement / marketing
  WHEN 'REFERRAL_ACTIVATED' THEN 'PROMOTIONAL'
  WHEN 'REFERRAL_FLOW' THEN 'PROMOTIONAL'
  WHEN 'DRIVER_BIRTHDAY' THEN 'PROMOTIONAL'
  WHEN 'FIRST_RIDE_EVENT' THEN 'PROMOTIONAL'
  WHEN 'MARKETING_EVENTS' THEN 'PROMOTIONAL'
  WHEN 'FEEDBACK_BADGE_PN' THEN 'PROMOTIONAL'

  -- Everything else is ride-lifecycle / operational — safe default
  ELSE 'RIDE_RELATED'
END
WHERE notification_category IS NULL;
