{-# LANGUAGE ApplicativeDo #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-orphans #-}

module Domain.Types.Extra.MerchantMessage where

import qualified Data.Aeson as A
import Data.Default.Class
import Data.OpenApi (ToSchema (..))
import qualified Data.Text as T
import qualified Database.Beam as B
import Database.Beam.Backend
import Database.Beam.Postgres (Postgres)
import Database.PostgreSQL.Simple.FromField (FromField (..))
import Kernel.Prelude

data MerchantMessageDefaultDataJSON = MerchantMessageDefaultDataJSON
  { var1 :: Maybe Text,
    var2 :: Maybe Text,
    var3 :: Maybe Text
  }
  deriving (Generic, ToJSON, FromJSON, Show, ToSchema)

instance Default MerchantMessageDefaultDataJSON where
  def =
    MerchantMessageDefaultDataJSON
      { var1 = Nothing,
        var2 = Nothing,
        var3 = Nothing
      }

data MessageKey
  = INVITE_TO_UNEXISTENT_EMERGENCY_NUMBER
  | SET_AS_RIDE_EMERGENCY_NUMBER
  | SET_AS_DEFAULT_EMERGENCY_NUMBER
  | SEND_OTP
  | SEND_BOOKING_OTP
  | SEND_BOOKING_OTP_RENTAL
  | SEND_BOOKING_OTP_INTERCITY
  | SEND_RIDE_END_OTP
  | SEND_SOS_ALERT
  | MARK_RIDE_AS_SAFE
  | FOLLOW_RIDE
  | ADDED_AS_EMERGENCY_CONTACT
  | TICKET_BOOKING_CANCELLED
  | POST_RIDE_SOS
  | SMS_DELIVERY_DETAILS_SENDER
  | SMS_DELIVERY_DETAILS_RECEIVER
  | POST_DELIVERY_SENDER
  | PRE_PICKUP_DELIVERY_RECEIVER
  | SEND_SCHEDULED_RIDE_DETAILS
  | SCHEDULED_RIDE_OTP
  | WHATSAPP_CALL_BOOKING_FLOW_DETAILS_MESSAGE
  | WHATSAPP_CALL_BOOKING_REALLOCATED_RIDE_DETAILS_MESSAGE
  | WHATSAPP_CALL_BOOKING_CANCELLED_RIDE_MESSAGE
  | METRO_TICKET_BOOKING_CANCELLED
  | METRO_TICKET_BOOKED
  | TICKET_MERCHANT_AGREEMENT_TEMPLATE
  | TICKET_MERCHANT_SNLTR_TEMPLATE
  | PARTNER_ORG_FRFS_TICKET_CANCEL_OTP
  | PASS_PURCHASED_MESSAGE
  | SPECIAL_ZONE_BOOKING_INVOICE
  | SEND_TOTP
  | SPECIAL_ZONE_BOOKING_INVOICE_TITLE
  | WHATSAPP_REWARD_UNLOCK
  | WHATSAPP_BUS_TRIP_STARTED
  | WHATSAPP_SHUTTLE_BOOKING_CONFIRMED
  | WHATSAPP_FRFS_TRIP_DETAILS_UPDATED
  | CustomMessageKey Text
  deriving (Eq, Ord, Generic)

knownMessageKeys :: [MessageKey]
knownMessageKeys =
  [ INVITE_TO_UNEXISTENT_EMERGENCY_NUMBER,
    SET_AS_RIDE_EMERGENCY_NUMBER,
    SET_AS_DEFAULT_EMERGENCY_NUMBER,
    SEND_OTP,
    SEND_BOOKING_OTP,
    SEND_BOOKING_OTP_RENTAL,
    SEND_BOOKING_OTP_INTERCITY,
    SEND_RIDE_END_OTP,
    SEND_SOS_ALERT,
    MARK_RIDE_AS_SAFE,
    FOLLOW_RIDE,
    ADDED_AS_EMERGENCY_CONTACT,
    TICKET_BOOKING_CANCELLED,
    POST_RIDE_SOS,
    SMS_DELIVERY_DETAILS_SENDER,
    SMS_DELIVERY_DETAILS_RECEIVER,
    POST_DELIVERY_SENDER,
    PRE_PICKUP_DELIVERY_RECEIVER,
    SEND_SCHEDULED_RIDE_DETAILS,
    SCHEDULED_RIDE_OTP,
    WHATSAPP_CALL_BOOKING_FLOW_DETAILS_MESSAGE,
    WHATSAPP_CALL_BOOKING_REALLOCATED_RIDE_DETAILS_MESSAGE,
    WHATSAPP_CALL_BOOKING_CANCELLED_RIDE_MESSAGE,
    METRO_TICKET_BOOKING_CANCELLED,
    METRO_TICKET_BOOKED,
    TICKET_MERCHANT_AGREEMENT_TEMPLATE,
    TICKET_MERCHANT_SNLTR_TEMPLATE,
    PARTNER_ORG_FRFS_TICKET_CANCEL_OTP,
    PASS_PURCHASED_MESSAGE,
    SPECIAL_ZONE_BOOKING_INVOICE,
    SEND_TOTP,
    SPECIAL_ZONE_BOOKING_INVOICE_TITLE,
    WHATSAPP_REWARD_UNLOCK,
    WHATSAPP_BUS_TRIP_STARTED,
    WHATSAPP_SHUTTLE_BOOKING_CONFIRMED,
    WHATSAPP_FRFS_TRIP_DETAILS_UPDATED
  ]

messageKeyToText :: MessageKey -> Text
messageKeyToText = \case
  INVITE_TO_UNEXISTENT_EMERGENCY_NUMBER -> "INVITE_TO_UNEXISTENT_EMERGENCY_NUMBER"
  SET_AS_RIDE_EMERGENCY_NUMBER -> "SET_AS_RIDE_EMERGENCY_NUMBER"
  SET_AS_DEFAULT_EMERGENCY_NUMBER -> "SET_AS_DEFAULT_EMERGENCY_NUMBER"
  SEND_OTP -> "SEND_OTP"
  SEND_BOOKING_OTP -> "SEND_BOOKING_OTP"
  SEND_BOOKING_OTP_RENTAL -> "SEND_BOOKING_OTP_RENTAL"
  SEND_BOOKING_OTP_INTERCITY -> "SEND_BOOKING_OTP_INTERCITY"
  SEND_RIDE_END_OTP -> "SEND_RIDE_END_OTP"
  SEND_SOS_ALERT -> "SEND_SOS_ALERT"
  MARK_RIDE_AS_SAFE -> "MARK_RIDE_AS_SAFE"
  FOLLOW_RIDE -> "FOLLOW_RIDE"
  ADDED_AS_EMERGENCY_CONTACT -> "ADDED_AS_EMERGENCY_CONTACT"
  TICKET_BOOKING_CANCELLED -> "TICKET_BOOKING_CANCELLED"
  POST_RIDE_SOS -> "POST_RIDE_SOS"
  SMS_DELIVERY_DETAILS_SENDER -> "SMS_DELIVERY_DETAILS_SENDER"
  SMS_DELIVERY_DETAILS_RECEIVER -> "SMS_DELIVERY_DETAILS_RECEIVER"
  POST_DELIVERY_SENDER -> "POST_DELIVERY_SENDER"
  PRE_PICKUP_DELIVERY_RECEIVER -> "PRE_PICKUP_DELIVERY_RECEIVER"
  SEND_SCHEDULED_RIDE_DETAILS -> "SEND_SCHEDULED_RIDE_DETAILS"
  SCHEDULED_RIDE_OTP -> "SCHEDULED_RIDE_OTP"
  WHATSAPP_CALL_BOOKING_FLOW_DETAILS_MESSAGE -> "WHATSAPP_CALL_BOOKING_FLOW_DETAILS_MESSAGE"
  WHATSAPP_CALL_BOOKING_REALLOCATED_RIDE_DETAILS_MESSAGE -> "WHATSAPP_CALL_BOOKING_REALLOCATED_RIDE_DETAILS_MESSAGE"
  WHATSAPP_CALL_BOOKING_CANCELLED_RIDE_MESSAGE -> "WHATSAPP_CALL_BOOKING_CANCELLED_RIDE_MESSAGE"
  METRO_TICKET_BOOKING_CANCELLED -> "METRO_TICKET_BOOKING_CANCELLED"
  METRO_TICKET_BOOKED -> "METRO_TICKET_BOOKED"
  TICKET_MERCHANT_AGREEMENT_TEMPLATE -> "TICKET_MERCHANT_AGREEMENT_TEMPLATE"
  TICKET_MERCHANT_SNLTR_TEMPLATE -> "TICKET_MERCHANT_SNLTR_TEMPLATE"
  PARTNER_ORG_FRFS_TICKET_CANCEL_OTP -> "PARTNER_ORG_FRFS_TICKET_CANCEL_OTP"
  PASS_PURCHASED_MESSAGE -> "PASS_PURCHASED_MESSAGE"
  SPECIAL_ZONE_BOOKING_INVOICE -> "SPECIAL_ZONE_BOOKING_INVOICE"
  SEND_TOTP -> "SEND_TOTP"
  SPECIAL_ZONE_BOOKING_INVOICE_TITLE -> "SPECIAL_ZONE_BOOKING_INVOICE_TITLE"
  WHATSAPP_REWARD_UNLOCK -> "WHATSAPP_REWARD_UNLOCK"
  WHATSAPP_BUS_TRIP_STARTED -> "WHATSAPP_BUS_TRIP_STARTED"
  WHATSAPP_SHUTTLE_BOOKING_CONFIRMED -> "WHATSAPP_SHUTTLE_BOOKING_CONFIRMED"
  WHATSAPP_FRFS_TRIP_DETAILS_UPDATED -> "WHATSAPP_FRFS_TRIP_DETAILS_UPDATED"
  CustomMessageKey t -> t

messageKeyFromText :: Text -> MessageKey
messageKeyFromText = \case
  "INVITE_TO_UNEXISTENT_EMERGENCY_NUMBER" -> INVITE_TO_UNEXISTENT_EMERGENCY_NUMBER
  "SET_AS_RIDE_EMERGENCY_NUMBER" -> SET_AS_RIDE_EMERGENCY_NUMBER
  "SET_AS_DEFAULT_EMERGENCY_NUMBER" -> SET_AS_DEFAULT_EMERGENCY_NUMBER
  "SEND_OTP" -> SEND_OTP
  "SEND_BOOKING_OTP" -> SEND_BOOKING_OTP
  "SEND_BOOKING_OTP_RENTAL" -> SEND_BOOKING_OTP_RENTAL
  "SEND_BOOKING_OTP_INTERCITY" -> SEND_BOOKING_OTP_INTERCITY
  "SEND_RIDE_END_OTP" -> SEND_RIDE_END_OTP
  "SEND_SOS_ALERT" -> SEND_SOS_ALERT
  "MARK_RIDE_AS_SAFE" -> MARK_RIDE_AS_SAFE
  "FOLLOW_RIDE" -> FOLLOW_RIDE
  "ADDED_AS_EMERGENCY_CONTACT" -> ADDED_AS_EMERGENCY_CONTACT
  "TICKET_BOOKING_CANCELLED" -> TICKET_BOOKING_CANCELLED
  "POST_RIDE_SOS" -> POST_RIDE_SOS
  "SMS_DELIVERY_DETAILS_SENDER" -> SMS_DELIVERY_DETAILS_SENDER
  "SMS_DELIVERY_DETAILS_RECEIVER" -> SMS_DELIVERY_DETAILS_RECEIVER
  "POST_DELIVERY_SENDER" -> POST_DELIVERY_SENDER
  "PRE_PICKUP_DELIVERY_RECEIVER" -> PRE_PICKUP_DELIVERY_RECEIVER
  "SEND_SCHEDULED_RIDE_DETAILS" -> SEND_SCHEDULED_RIDE_DETAILS
  "SCHEDULED_RIDE_OTP" -> SCHEDULED_RIDE_OTP
  "WHATSAPP_CALL_BOOKING_FLOW_DETAILS_MESSAGE" -> WHATSAPP_CALL_BOOKING_FLOW_DETAILS_MESSAGE
  "WHATSAPP_CALL_BOOKING_REALLOCATED_RIDE_DETAILS_MESSAGE" -> WHATSAPP_CALL_BOOKING_REALLOCATED_RIDE_DETAILS_MESSAGE
  "WHATSAPP_CALL_BOOKING_CANCELLED_RIDE_MESSAGE" -> WHATSAPP_CALL_BOOKING_CANCELLED_RIDE_MESSAGE
  "METRO_TICKET_BOOKING_CANCELLED" -> METRO_TICKET_BOOKING_CANCELLED
  "METRO_TICKET_BOOKED" -> METRO_TICKET_BOOKED
  "TICKET_MERCHANT_AGREEMENT_TEMPLATE" -> TICKET_MERCHANT_AGREEMENT_TEMPLATE
  "TICKET_MERCHANT_SNLTR_TEMPLATE" -> TICKET_MERCHANT_SNLTR_TEMPLATE
  "PARTNER_ORG_FRFS_TICKET_CANCEL_OTP" -> PARTNER_ORG_FRFS_TICKET_CANCEL_OTP
  "PASS_PURCHASED_MESSAGE" -> PASS_PURCHASED_MESSAGE
  "SPECIAL_ZONE_BOOKING_INVOICE" -> SPECIAL_ZONE_BOOKING_INVOICE
  "SEND_TOTP" -> SEND_TOTP
  "SPECIAL_ZONE_BOOKING_INVOICE_TITLE" -> SPECIAL_ZONE_BOOKING_INVOICE_TITLE
  "WHATSAPP_REWARD_UNLOCK" -> WHATSAPP_REWARD_UNLOCK
  "WHATSAPP_BUS_TRIP_STARTED" -> WHATSAPP_BUS_TRIP_STARTED
  "WHATSAPP_SHUTTLE_BOOKING_CONFIRMED" -> WHATSAPP_SHUTTLE_BOOKING_CONFIRMED
  "WHATSAPP_FRFS_TRIP_DETAILS_UPDATED" -> WHATSAPP_FRFS_TRIP_DETAILS_UPDATED
  t -> CustomMessageKey t

instance Show MessageKey where
  showsPrec _ k = showString (T.unpack (messageKeyToText k))

instance Read MessageKey where
  readsPrec _ s = case lex s of
    [(tok, rest)] | not (null tok) -> [(messageKeyFromText (T.pack tok), rest)]
    _ -> []

instance ToJSON MessageKey where
  toJSON = A.String . messageKeyToText

instance FromJSON MessageKey where
  parseJSON = A.withText "MessageKey" (pure . messageKeyFromText)

instance ToSchema MessageKey where
  declareNamedSchema _ = declareNamedSchema (Proxy :: Proxy Text)

instance HasSqlValueSyntax be Text => HasSqlValueSyntax be MessageKey where
  sqlValueSyntax = sqlValueSyntax . messageKeyToText

instance BeamSqlBackend be => B.HasSqlEqualityCheck be MessageKey

instance FromField MessageKey where
  fromField f mbValue = messageKeyFromText <$> fromField f mbValue

instance FromBackendRow Postgres MessageKey
