# access tokens with different roles
@customer = {{bap-dashboard/token/YATRI/customer}}
@driver = {{bap-dashboard/token/YATRI/driver}}
@juspay_ops = {{bap-dashboard/token/YATRI/juspay_ops}}
@juspay_admin = {{bap-dashboard/token/YATRI/juspay_admin}}
@customer_service = {{bap-dashboard/token/YATRI/customer_service}}

# @name healthcheck
GET {{bap-dashboard-host}}

###

# @name stuckBookingsCancel

POST {{bap-dashboard-host}}/bap/YATRI/booking/cancel/allStuck
token: {{customer_service}}
content-type: application/json

{
    "bookingIds" : [
        "0dad7bf0-7472-41c3-86c9-b886f1088848",
        "0b7c2b71-9e98-41f0-976e-5e11a9f4d537"
        ]
}

###

# @name multipleBookingSync

# UPDATE atlas_app.beckn_config SET status_ttl_sec=30
# UPDATE atlas_driver_offer_bpp.booking SET payment_method_id=null

POST {{bap-dashboard-host}}/bap/YATRI/booking/sync
token: {{customer_service}}
content-type: application/json

{
    "bookings" :
    [
        {"bookingId" : "967c177c-882a-4906-8df1-9086b0f46073"},
        {"bookingId" : "fakeBookingId"}
    ]
}
