CREATE TABLE atlas_app.gate_info ();

ALTER TABLE atlas_app.gate_info ADD COLUMN address text ;
ALTER TABLE atlas_app.gate_info ADD COLUMN can_queue_up_on_gate boolean NOT NULL;
ALTER TABLE atlas_app.gate_info ADD COLUMN created_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.gate_info ADD COLUMN default_demand_threshold integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN default_driver_extra integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN default_max_driver_threshold integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN default_min_driver_threshold integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN demand_thresholds_json text ;
ALTER TABLE atlas_app.gate_info ADD COLUMN enable_queue_filter text ;
ALTER TABLE atlas_app.gate_info ADD COLUMN entry_fee_amount double precision ;
ALTER TABLE atlas_app.gate_info ADD COLUMN gate_tags text[] ;
ALTER TABLE atlas_app.gate_info ADD COLUMN gate_type text NOT NULL;
ALTER TABLE atlas_app.gate_info ADD COLUMN geom_geo_json text ;
ALTER TABLE atlas_app.gate_info ADD COLUMN id character varying(36) NOT NULL;
ALTER TABLE atlas_app.gate_info ADD COLUMN max_driver_thresholds_json text ;
ALTER TABLE atlas_app.gate_info ADD COLUMN max_ride_skips_before_queue_removal integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN merchant_id text ;
ALTER TABLE atlas_app.gate_info ADD COLUMN merchant_operating_city_id text ;
ALTER TABLE atlas_app.gate_info ADD COLUMN min_driver_thresholds_json text ;
ALTER TABLE atlas_app.gate_info ADD COLUMN name text NOT NULL;
ALTER TABLE atlas_app.gate_info ADD COLUMN notification_active_till_in_sec integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN notification_cooldown_in_sec integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN pickup_request_response_timeout_in_sec integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN pickup_zone_arrival_timeout_in_sec integer ;
ALTER TABLE atlas_app.gate_info ADD COLUMN point text NOT NULL;
ALTER TABLE atlas_app.gate_info ADD COLUMN special_location_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.gate_info ADD COLUMN updated_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.gate_info ADD COLUMN walk_description text ;
ALTER TABLE atlas_app.gate_info ADD PRIMARY KEY ( id);
