CREATE TABLE atlas_app.merchant_service_usage_config ();

ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN aadhaar_verification_service character varying(30) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN auto_complete character varying(30) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN created_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN enable_dashboard_sms boolean NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN get_distances character varying(30) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN get_distances_for_cancel_ride text NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN get_exophone character varying (255) NOT NULL default 'Exotel';
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN get_pickup_routes text NOT NULL default 'Google';
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN get_place_details character varying(30) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN get_place_name character varying(30) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN get_routes character varying(30) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN get_trip_routes text NOT NULL default 'Google';
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN initiate_call character varying(30) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN issue_ticket_service character varying(30) NOT NULL default 'Kapture';
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN merchant_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN merchant_operating_city_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN notify_person text NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN sms_providers_priority_list text[] NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN snap_to_road character varying(30) NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN updated_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN use_fraud_detection boolean NOT NULL default False;
ALTER TABLE atlas_app.merchant_service_usage_config ADD COLUMN whatsapp_providers_priority_list text[] NOT NULL;
ALTER TABLE atlas_app.merchant_service_usage_config ADD PRIMARY KEY ( merchant_operating_city_id);