CREATE TABLE atlas_app.shared_ride ();

ALTER TABLE atlas_app.shared_ride ADD COLUMN bpp_shared_ride_id text NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN chargeable_distance_value double precision ;
ALTER TABLE atlas_app.shared_ride ADD COLUMN created_at timestamptz NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.shared_ride ADD COLUMN driver_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN id character varying(36) NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN merchant_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN merchant_operating_city_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN ride_end_time timestamptz ;
ALTER TABLE atlas_app.shared_ride ADD COLUMN ride_ids uuid[] NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN ride_start_time timestamptz ;
ALTER TABLE atlas_app.shared_ride ADD COLUMN shared_booking_id uuid NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN status character varying(255) NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN total_fare numeric(30,10) ;
ALTER TABLE atlas_app.shared_ride ADD COLUMN tracking_url character varying(255) ;
ALTER TABLE atlas_app.shared_ride ADD COLUMN traveled_distance_value double precision ;
ALTER TABLE atlas_app.shared_ride ADD COLUMN updated_at timestamptz NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.shared_ride ADD COLUMN vehicle_model character varying(255) NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN vehicle_number character varying(255) NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN vehicle_service_tier_type character varying(255) ;
ALTER TABLE atlas_app.shared_ride ADD COLUMN vehicle_variant character varying(60) NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD COLUMN waypoints jsonb NOT NULL;
ALTER TABLE atlas_app.shared_ride ADD PRIMARY KEY ( id);
