CREATE TABLE atlas_app.shared_estimate ();

ALTER TABLE atlas_app.shared_estimate ADD COLUMN bpp_shared_estimate_id text NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN created_at timestamptz NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN estimate_ids uuid[] NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN distance_unit character varying(255) ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN estimated_distance double precision ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN estimated_distance_value double precision ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN estimated_duration integer ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN estimated_total_fare numeric(30,10) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN id character varying(36) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN merchant_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN merchant_operating_city_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN night_shift_charge numeric(30,2) ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN night_shift_charge_amount numeric(30,10) ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN night_shift_end time ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN night_shift_start time ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN old_night_shift_charge numeric(10,2) ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN provider_id character varying(255) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN provider_name character varying(255) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN provider_url character varying(255) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN service_tier_name text ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN shared_search_request_id uuid NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN status character varying(255) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN total_fare_range_max numeric(30,10) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN total_fare_range_min numeric(30,10) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN trip_category character varying(255) ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN updated_at timestamptz NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN valid_till timestamptz NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN vehicle_service_tier_seating_capacity integer ;
ALTER TABLE atlas_app.shared_estimate ADD COLUMN vehicle_variant character varying(255) NOT NULL;
ALTER TABLE atlas_app.shared_estimate ADD PRIMARY KEY ( id);
