CREATE TABLE atlas_app.user_preferred_route ();

ALTER TABLE atlas_app.user_preferred_route ADD COLUMN created_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_area character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_area_code character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_building character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_city character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_country character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_door character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_extras text ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_instructions text ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_place_id text ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_state character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_street character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_title text ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_ward character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_location_lat double precision NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN from_location_lon double precision NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN id character varying(36) NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN person_id character varying(36) NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN priority integer NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN route_name character varying(255) NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_area character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_area_code character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_building character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_city character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_country character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_door character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_extras text ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_instructions text ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_place_id text ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_state character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_street character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_title text ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_ward character varying(255) ;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_location_lat double precision NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN to_location_lon double precision NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN updated_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_app.user_preferred_route ADD COLUMN usage_count integer NOT NULL;
ALTER TABLE atlas_app.user_preferred_route ADD PRIMARY KEY ( id);
