@bpp-dashboard-host = http://localhost:8018

# access tokens with different roles
@customer = 512e0a7b-e521-4d6b-a0c4-8713ae345bf2
@driver = 223ed551-c9f8-4bae-b49a-30a696424b7f
@juspay_ops = e789b47f-2e39-47a2-b297-33f8fd4b87d0
@juspay_admin = 0f3378e2-da5b-4eac-a0f6-397ca48358de
@customer_service = 07ef2a2a-b014-4a86-b1c0-e453e8b0b66e

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# @name driverList

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/list
?verified=true
&enabled=true
&limit=10
&offset=0
# &phone=6666666666
token: {{customer_service}}

###

# @name driverActivity

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/activity
token: {{customer_service}}

###

# @name enableDriver

@driverId1 = 001b93df-4f7c-440f-bada-4d46c396d7d0
@driverId2 = 002b93df-4f7c-440f-bada-4d46c396d7d0
@driverId3 = driver-not-found-0000000000000000000

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/enable
token: {{juspay_ops}}
content-type: application/json

###
# @name disableDriver

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/disable
token: {{juspay_ops}}
content-type: application/json

###

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/location
token: {{customer_service}}
content-type: application/json

{
    "driverIds": ["{{driverId1}}", "{{driverId2}}", "{{driverId3}}"]
}

###

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/info?mobileNumber=6666666666
token: {{customer_service}}
content-type: application/json

###

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/info?vehicleNumber=3211
token: {{customer_service}}
content-type: application/json

###

DELETE {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId2}}/permanentlyDelete
token: {{juspay_admin}}
content-type: application/json

###

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/unlinkVehicle
 token: {{juspay_admin}}
 content-type: application/json

###

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/updatePhoneNumber
token: {{juspay_admin}}
content-type: application/json

{
    "newPhoneNumber": "7777777777",
    "newCountryCode": "+91"
}

###

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/addVehicle
token: {{juspay_admin}}
content-type: application/json

{
    "variant" : "SEDAN",
    "registrationNo" : "777IN",
    "vehicleClass" : "vehicleClass",
    "capacity" : 5,
    "colour" : "Red",
    "energyType" : "PETROL",
    "model" : "VAZ",
    "make" : "make",
    "driverName" : "Krishna"
}
