@bpp-dashboard-host = http://localhost:8018

# access tokens with different roles
@customer = 512e0a7b-e521-4d6b-a0c4-8713ae345bf2
@driver = 223ed551-c9f8-4bae-b49a-30a696424b7f
@juspay_ops = e789b47f-2e39-47a2-b297-33f8fd4b87d0
@juspay_admin = 0f3378e2-da5b-4eac-a0f6-397ca48358de
@customer_service = 07ef2a2a-b014-4a86-b1c0-e453e8b0b66e

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# @name driverList

GET {{bpp-dashboard-host}}/bpp/beckn-transport/driver/list?verified=true&limit=10&offset=0&phone=66
token: {{customer_service}}

###

# @name driverActivity

@driverId = 001b93df-4f7c-440f-bada-4d46c396d7d0

GET {{bpp-dashboard-host}}/bpp/beckn-transport/driver/activity
token: {{customer_service}}

###

# @name enableDrivers

@driverId1e = 001b93df-4f7c-440f-bada-4d46c396d7d0
@driverId2e = 002b93df-4f7c-440f-bada-4d46c396d7d0

@driverId3e = driver-not-found-0000000000000000000

PUT {{bpp-dashboard-host}}/bpp/beckn-transport/driver/enable
token: {{juspay_ops}}
content-type: application/json


{
    "driverIds": ["{{driverId1e}}", "{{driverId2e}}", "{{driverId3e}}"]
}

###
# @name disableDrivers

@driverId1d = 001b93df-4f7c-440f-bada-4d46c396d7d0
@driverId2d = 002b93df-4f7c-440f-bada-4d46c396d7d0

@driverId3d = driver-not-found-0000000000000000000

PUT {{bpp-dashboard-host}}/bpp/beckn-transport/driver/disable
token: {{juspay_ops}}
content-type: application/json

{
    "driverIds": ["{{driverId1d}}", "{{driverId2d}}", "{{driverId3d}}"]
}

###

GET {{bpp-dashboard-host}}/bpp/beckn-transport/driver/location
token: {{customer_service}}
content-type: application/json

{
    "driverIds": ["{{driverId1e}}", "{{driverId2e}}", "{{driverId3e}}"]
}

