@bpp-dashboard-host = http://localhost:8018

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# use this creds for testing different roles:
# name = customer, driver, juspay_ops, juspay_admin, customer_service
# email = name@dashboard.com, password = name

# @name login

POST {{bpp-dashboard-host}}/dashboard/login
content-type: application/json

{
  "email" : "juspay_admin@dashboard.com",
  "password" : "juspay_admin",
  "merchantId" : "YATRI_PARTNER"
}

###

# @name personList

@token = {{login.response.body.authToken}}

GET {{bpp-dashboard-host}}/dashboard/admin/person/list
  ?limit=10
  &offset=0
  # &searchString=customer
  # &searchString=7777777781
content-type: application/json
token: {{token}}

###

# @name getAccessMatrix

GET {{bpp-dashboard-host}}/dashboard/admin/accessMatrix
  ?limit=10
  &offset=0
content-type: application/json
token: {{token}}

###

# @name getAccessMatrixByRole

@roleId = {{getAccessMatrix.response.body.accessMatrix[0].role.id}}

GET {{bpp-dashboard-host}}/dashboard/admin/accessMatrix/role/{{roleId}}
content-type: application/json
token: {{token}}

###

# @name createRole

POST {{bpp-dashboard-host}}/dashboard/admin/roles/create
content-type: application/json
token: {{token}}

{ "name" : "DEVELOPER",
  "description" : "developer"
}

###

# @name assignRole

# assign new "DEVELOPER" role to person with name "customer"
@personId = {{personList.response.body.list[0].id}}

@developerRoleId = {{createRole.response.body.id}}

POST {{bpp-dashboard-host}}/dashboard/admin/person/{{personId}}/assignRole/{{developerRoleId}}
content-type: application/json
token: {{token}}

###

# @name assignAccessLevel

POST {{bpp-dashboard-host}}/dashboard/admin/roles/{{developerRoleId}}/assignAccessLevel
content-type: application/json
token: {{token}}

{ "apiEntity" : "DRIVERS",
  "userAccessType" : "USER_FULL_ACCESS"
}

###

# @name resetMerchantAccess

POST {{bpp-dashboard-host}}/dashboard/admin/person/{{personId}}/resetMerchantAccess
content-type: application/json
token: {{token}}

{
  "merchantId" : "NAMMA_YATRI_PARTNER"
}

###

# @name assignMerchantAccess

POST {{bpp-dashboard-host}}/dashboard/admin/person/{{personId}}/assignMerchantAccess
content-type: application/json
token: {{token}}

{
  "merchantId" : "NAMMA_YATRI_PARTNER"
}

###

# @name profile

@customerToken = 512e0a7b-e521-4d6b-a0c4-8713ae345bf2

GET {{bpp-dashboard-host}}/dashboard/person/profile
content-type: application/json
token: {{customerToken}}

###

# @name driverOfferCustomerLogin

# name = customer, driver, juspay_ops, juspay_admin, customer_service
@customerLogin = customer_service

POST {{bpp-dashboard-host}}/dashboard/login
content-type: application/json

{
  "email" : "{{customerLogin}}@dashboard.com",
  "password" : "{{customerLogin}}",
  "merchantId" : "NAMMA_YATRI_PARTNER"
}

###

# @name getCurrentMerchant

@driverOfferCustomerToken = {{driverOfferCustomerLogin.response.body.authToken}}

GET {{bpp-dashboard-host}}/dashboard/person/getCurrentMerchant
content-type: application/json
token: {{driverOfferCustomerToken}}

###

# check access level for new role "DEVELOPER"

# @name driverList

GET {{bpp-dashboard-host}}/bpp/driver-offer/driver/list
  ?limit=10
  &offset=0
content-type: application/json
token: {{driverOfferCustomerToken}}

###

# @name logout

# this endpoint should remove only one token for APP_BACKEND_YATRI server

@becknTransportCustomerToken = 512e0a7b-e521-4d6b-a0c4-8713ae345bf2

POST {{bpp-dashboard-host}}/dashboard/logout
content-type: application/json
token: {{becknTransportCustomerToken}}

###

# @name logoutAllServers

# this endpoint should remove all tokens for customer

POST {{bpp-dashboard-host}}/dashboard/logoutAllServers
content-type: application/json
token: {{driverOfferCustomerToken}}
