
@driver-offer-bpp-host = http://localhost:8016
@token = 503d9b3b-18ef-4101-a68c-0bac45e3406e

@today = {{$localDatetime 'YYYY-MM-DD'}}

# @name setActive
POST {{driver-offer-bpp-host}}/ui/driver/setActivity?active=true
content-type: application/json
token: {{token}}

###

# @name createDriver
POST {{driver-offer-bpp-host}}/ui/org/driver
content-type: application/json
token: {{token}}

{
  "person" : {
    "firstName": "Jonh",
    "middleName": " Maybeext",
    "lastName": "Maybext",
    "mobileNumber": "9602580676",
    "mobileCountryCode": "+7"
  },
  "vehicle" : {
    "category": "CAR",
    "model": "Ford",
    "variant": "SEDAN",
    "color": "White",
    "registrationNo": "6002",
    "capacity": 120
  }
}
###

# @name deleteDriver
DELETE  {{driver-offer-bpp-host}}/ui/org/driver/984e3bb5-d200-4dcc-8f6c-abb09ce68d6a
content-type: application/json
token: {{token}}

###

# @name authDriver
POST {{driver-offer-bpp-host}}/ui/auth
content-type: application/json
x-bundle-version: 1.0.0
x-client-version: 1.0.0

{
  "mobileNumber" : "6666666666",
  "mobileCountryCode": "+91",
  "merchantId": "favorit0-0000-0000-0000-00000favorit"
}

###

# @name onboardDriver
POST {{driver-offer-bpp-host}}/ui/driver/register
content-type: application/json
token: {{token}}

{
  "driverLicenseNumber" : "KA0219980008798",
  "operatingCity" : "BANGALORE",
  "driverDateOfBirth" : "2000-04-12 15:15:42.233691+00",
  "vehicleRegistrationCertNumber" : "KA502922"
}

###

# @name getStats
GET {{driver-offer-bpp-host}}/ui/driver/profile/stats?day={{today}}
content-type: application/json
# token: = favorit-auto1-0000000000000000-token
token: {{token}}

###

# @name verifyDriver
POST {{driver-offer-bpp-host}}/ui/auth/6c6d5f17-e79a-43f2-9dd1-46a6bf280ebe/verify
content-type: application/json

{
  "otp" : "7891",
  "deviceToken": "+91"
}

###