@driver-offer-bpp-host = http://localhost:8016
@adminToken = favorit-admin-0000000000000000-token

###
# @name profile
GET {{driver-offer-bpp-host}}/ui/orgAdmin/profile
token: {{adminToken}}

###
# @name listFarePolicies
GET {{driver-offer-bpp-host}}/ui/org/farePolicy
token: {{adminToken}}

###
@farePolicyToUpdate = {{listFarePolicies.response.body.oneWayFarePolicies[0].id}}


# @name updateSuv
POST {{driver-offer-bpp-host}}/ui/org/farePolicy/{{farePolicyToUpdate}}
Content-Type: application/json
token: {{adminToken}}

{
    "baseFare" : 100,
    "baseDistancePerKmFare": 11,
    "perExtraKmRate" : 111,
    "baseDistance": 450,
    "extraKmFare": 13,
    "deadKmFare": 10,
    "driverMinExtraFee" : 12,
    "driverMaxExtraFee" : 15
}

###
# @name updateSuv2
POST {{driver-offer-bpp-host}}/ui/org/farePolicy/{{farePolicyToUpdate}}
Content-Type: application/json
token: {{adminToken}}

{
    "baseDistancePerKmFare": 13,
    "baseDistance": 4000,
    "extraKmFare": 30,
    "deadKmFare": 130,
    "driverExtraFeeList": [11, 21, 41]
}