ALTER TABLE atlas_bpp_dashboard.transaction DROP CONSTRAINT IF EXISTS transaction_requestor_id_fkey;
ALTER TABLE atlas_bpp_dashboard.transaction DROP CONSTRAINT IF EXISTS transaction_merchant_id_fkey;
