@bap-dashboard-host = http://localhost:8017

# @name healthcheck
GET {{bap-dashboard-host}}

###

# use this creds for testing different roles:
# name = customer, driver, juspay_ops, juspay_admin, customer_service
# email = name@dashboard.com, password = name

# @name login

POST {{bap-dashboard-host}}/dashboard/login
content-type: application/json

{
  "email" : "juspay_admin@dashboard.com",
  "password" : "juspay_admin",
  "merchantId" : "YATRI"
}

###

# @name personList

@token = {{login.response.body.authToken}}

GET {{bap-dashboard-host}}/dashboard/admin/person/list
  ?limit=10
  &offset=0
  # &searchString=customer
  # &searchString=7777777781
content-type: application/json
token: {{token}}

###

# @name getAccessMatrix

GET {{bap-dashboard-host}}/dashboard/admin/accessMatrix
  ?limit=10
  &offset=0
content-type: application/json
token: {{token}}

###

# @name getAccessMatrixByRole

@roleId = {{getAccessMatrix.response.body.accessMatrix[0].role.id}}

GET {{bap-dashboard-host}}/dashboard/admin/accessMatrix/role/{{roleId}}
content-type: application/json
token: {{token}}

###

# @name createRole

POST {{bap-dashboard-host}}/dashboard/admin/roles/create
content-type: application/json
token: {{token}}

{ "name" : "DEVELOPER",
  "description" : "developer"
}

###

# @name assignRole

# assign new "DEVELOPER" role to person with name "customer"
@personId = {{personList.response.body.list[0].id}}

@developerRoleId = {{createRole.response.body.id}}

POST {{bap-dashboard-host}}/dashboard/admin/person/{{personId}}/assignRole/{{developerRoleId}}
content-type: application/json
token: {{token}}

###

# @name assignAccessLevel

POST {{bap-dashboard-host}}/dashboard/admin/roles/{{developerRoleId}}/assignAccessLevel
content-type: application/json
token: {{token}}

{ "apiEntity" : "CUSTOMERS",
  "userAccessType" : "USER_FULL_ACCESS"
}

###

# @name assignMerchantAccess

POST {{bap-dashboard-host}}/dashboard/admin/person/{{personId}}/assignMerchantAccess
content-type: application/json
token: {{token}}

{
  "merchantId" : "NAMMA_YATRI"
}

###

# @name profile

@customerToken = 512e0a7b-e521-4d6b-a0c4-8713ae345bf2

GET {{bap-dashboard-host}}/dashboard/person/profile
content-type: application/json
token: {{customerToken}}

###


# @name arduCustomerLogin

POST {{bap-dashboard-host}}/dashboard/login
content-type: application/json

{
  "email" : "customer@dashboard.com",
  "password" : "customer",
  "merchantId" : "NAMMA_YATRI"
}

###

# @name getCurrentMerchant

@arduCustomerToken = {{arduCustomerLogin.response.body.authToken}}

GET {{bap-dashboard-host}}/dashboard/person/getCurrentMerchant
content-type: application/json
token: {{arduCustomerToken}}

###

# check access level for new role "DEVELOPER"

# @name customerList

# we don't have NAMMA_YATRI merchant in local-testing-data, so for testing this api you should add it:

# INSERT INTO atlas_app.merchant (id, short_id, exo_phone, exo_phone_country_code, fcm_url, fcm_json_path, fcm_redis_token_key_prefix, origin_restriction, destination_restriction, registry_url, gateway_url, name) VALUES
# ('da4e23a5-3ce6-4c37-8b9b-41377c3c1a52', 'NAMMA_YATRI', '8047108594', '+91', 'http://localhost:4545/', 'dummy-fcm.json', 'da4e23a5-3ce6-4c37-8b9b-41377c3c1a52', '{Ernakulam}', '{Ernakulam,Kerala}', 'http://localhost:8020', 'http://localhost:8015/v1', 'NAMMA_YATRI');

POST {{bap-dashboard-host}}/bap/NAMMA_YATRI/customer/111/update
content-type: application/json
token: {{arduCustomerToken}}

"request"

###

# @name resetMerchantAccess

POST {{bap-dashboard-host}}/dashboard/admin/person/{{personId}}/resetMerchantAccess
content-type: application/json
token: {{token}}

{
  "merchantId" : "NAMMA_YATRI"
}

###

# @name logout

# this endpoint should remove only one token for APP_BACKEND_YATRI server

@yatriCustomerToken = 512e0a7b-e521-4d6b-a0c4-8713ae345bf2

POST {{bap-dashboard-host}}/dashboard/logout
content-type: application/json
token: {{yatriCustomerToken}}

###

# @name logoutAllServers

# this endpoint should remove all tokens for customer
# INVALID_TOKEN

POST {{bap-dashboard-host}}/dashboard/logoutAllServers
content-type: application/json
token: {{arduCustomerToken}}
