@bap-dashboard-host = http://localhost:8017

# @name healthcheck
GET {{bap-dashboard-host}}

###

# use this creds for testing different roles:
# name = customer, driver, juspay_ops, juspay_admin, customer_service
# email = name@dashboard.com, password = name

# @name login

POST {{bap-dashboard-host}}/dashboard/login
content-type: application/json

{
  "email" : "juspay_admin@dashboard.com",
  "password" : "juspay_admin"
}

###

# @name logout

@token = {{login.response.body.authToken}}

POST {{bap-dashboard-host}}/dashboard/logout
content-type: application/json
token: {{token}}

###

# @name personList

GET {{bap-dashboard-host}}/dashboard/person/list
  ?limit=5
  &offset=0
  # &searchString=customer
  # &searchString=7777777781
content-type: application/json
token: {{token}}

###

# @name getAccessMatrix

GET {{bap-dashboard-host}}/dashboard/accessMatrix
  ?roleId=e5a69a26-d165-455a-a711-33a41e0d47c6
content-type: application/json
token: {{token}}
