# @name login

@client-id = {{fmd/client-id}}
@client-secret = {{fmd/client-secret}}
@host = https://apis-staging.dunzo.in/api/v1

GET {{host}}/token
client-id: {{client-id}}
client-secret: {{client-secret}}

###

@token = {{login.response.body.token}}

GET {{host}}/quote
    ?pickup_lat=12.9729391
    &pickup_lng=77.6294794
    &drop_lat=12.9354504
    &drop_lng=77.6146828
    &category_id=pickup_drop
client-id: {{client-id}}
Authorization: {{token}}

###

# @name task

POST {{host}}/tasks?test=true
client-id: {{client-id}}
Authorization: {{token}}

{
    "request_id": "{{$guid}}",
    "pickup_details": {
        "lat": 12.9729391,
        "lng": 77.6294794,
        "address": {
            "street_address_1": "200 Block 4, Suncity Apartments",
            "street_address_2": "Bellandur",
            "city": "Bangalore",
            "state": "Karnataka",
            "pincode": "560103",
            "country": "India"
        }
    },
    "drop_details": {
        "lat": 12.9354504,
        "lng": 77.6146828,
        "address": {
            "street_address_1": "203 Block 5, Suncity Apartments",
            "street_address _2": "Bellandur",
            "city": "Bangalore",
            "state": "Karnataka",
            "pincode": "560103",
            "country": "India"
        }
    },
    "sender_details": {
        "name": "Mr X",
        "phone_number": "9988990053"
    },
    "receiver_details": {
        "name": "Mr Y",
        "phone_number": "9988990099"
    },
    "package_content": [
        "Documents | Books",
        "Clothes | Accessories",
        "Electronic Items"
    ],
    "package_approx_value": 250,
    "special_instructions": "Fragile items. Handle with great care!!"
}

###

@task_id = {{task.response.body.task_id}}

GET {{host}}/tasks/{{task_id}}/status?test=true
client-id: {{client-id}}
Authorization: {{token}}

###


# This API returns an error, but changes task status
POST {{host}}/test/tasks/{{task_id}}/next_state?test=true
client-id: {{client-id}}
Authorization: {{token}}
