ALTER TABLE atlas_driver_offer_bpp.quote_special_zone add column vehicle_service_tier_name text;
ALTER TABLE atlas_driver_offer_bpp.quote_special_zone add column driver_min_fee Int;
ALTER TABLE atlas_driver_offer_bpp.quote_special_zone add column driver_max_fee Int;
ALTER TABLE atlas_driver_offer_bpp.quote_special_zone add column driver_pick_up_charge Int;