ALTER TABLE atlas_driver_offer_bpp.issue_message DROP CONSTRAINT issue_message_reference_category_id_fkey;

ALTER TABLE atlas_driver_offer_bpp.issue_message
ADD CONSTRAINT issue_message_reference_category_id_fkey
FOREIGN KEY (reference_category_id)
REFERENCES atlas_driver_offer_bpp.issue_category(id);