ALTER TABLE atlas_driver_offer_bpp.fare_policy_inter_city_details ADD COLUMN free_wating_time integer;
ALTER TABLE atlas_driver_offer_bpp.fare_policy_inter_city_details ADD COLUMN waiting_charge JSON;
