ALTER TABLE atlas_driver_offer_bpp.fare_policy_progressive_details ADD COLUMN pickup_charges_min integer;
ALTER TABLE atlas_driver_offer_bpp.fare_policy_progressive_details ADD COLUMN pickup_charges_max integer;
ALTER TABLE atlas_driver_offer_bpp.fare_policy_progressive_details ADD COLUMN pickup_charges_min_amount double precision;
ALTER TABLE atlas_driver_offer_bpp.fare_policy_progressive_details ADD COLUMN pickup_charges_max_amount double precision;

