alter table atlas_driver_offer_bpp.fare_policy add column driver_cancellation_not_allowed boolean;
alter table atlas_driver_offer_bpp.fare_parameters add column driver_cancellation_not_allowed boolean;
