{ dbUserId = "atlas"
, dbPassword = "atlas"
, cronAutKey = "zzzzzz"
, nsdlUsername = "username"
, nsdlPassword = "password"
, smsOtpHash = "xxxxxxx"
, sesIssuesFrom = "aaa@aaa.com"
, sesIssuesTo = "aaa@aaa.com"
, sesIssuesReplyTo = "aaa@aaa.com"
, sesIssuesRegion = "eu-west-1"
}
