#!/usr/bin/env bash
# build-caddyfile.sh — Generate data/Caddyfile from resolved (or base) ports.
#
# Reads data/ports-resolved.nix (generated by resolve-ports.sh) or falls back
# to Backend/nix/services/ports.nix, extracts service→port mappings, and writes
# a Caddyfile to <repo-root>/data/Caddyfile.
#
# The Caddyfile provides a single reverse-proxy entry point so developers on the
# devbox (via Tailscale) only need to know one port to reach any backend service.
#
# Usage:
#   ./build-caddyfile.sh           # generate data/Caddyfile
#   ./build-caddyfile.sh --print   # print to stdout, don't write
#
# Called automatically before `, run-mobility-stack-dev`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
RESOLVED_PORTS_FILE="$REPO_ROOT/data/ports-resolved.nix"
BASE_PORTS_FILE="$SCRIPT_DIR/ports.nix"
CADDYFILE="$REPO_ROOT/data/Caddyfile"

PRINT_ONLY=false
if [[ "${1:-}" == "--print" ]]; then
  PRINT_ONLY=true
fi

# Pick the best available ports file
if [[ -f "$RESOLVED_PORTS_FILE" ]]; then
  PORTS_FILE="$RESOLVED_PORTS_FILE"
else
  PORTS_FILE="$BASE_PORTS_FILE"
fi

# --- Extract port values from the nix file ---
# Parses lines like `  service-name = 12345;` into an associative array.
declare -A ports
while IFS= read -r line; do
  if [[ "$line" =~ ^[[:space:]]*([a-zA-Z][a-zA-Z0-9_-]*)[[:space:]]*=[[:space:]]*([0-9]+)[[:space:]]*\; ]]; then
    ports["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
  fi
done < "$PORTS_FILE"

# --- Helper: get port with fallback ---
get_port() {
  local name="$1"
  echo "${ports[$name]:-}"
}

# --- Build the Caddyfile ---
caddy_port=$(get_port "caddy-reverse-proxy")
if [[ -z "$caddy_port" ]]; then
  echo "ERROR: caddy-reverse-proxy port not found in $PORTS_FILE" >&2
  exit 1
fi

# Services to expose via reverse proxy.
# Format: "path-prefix  service-name-in-ports.nix"
# The path prefix is stripped before forwarding (handle_path).
SERVICE_ROUTES=(
  "/rider-app                   rider-app"
  "/driver-app                  dynamic-offer-driver-app"
  "/rider-dashboard             rider-dashboard"
  "/provider-dashboard          provider-dashboard"
  "/beckn-gateway               beckn-gateway"
  "/mock-registry               mock-registry"
  "/location-tracking-service   location-tracking-service"
  "/notification-service        notification-service-http"
  "/mock-server                 mock-server"
  "/mock-fcm                    mock-fcm"
  "/mock-sms                    mock-sms"
  "/mock-idfy                   mock-idfy"
  "/mock-google                 mock-google"
  "/test-context-api            test-context-api"
  "/metabase                    metabase"
)

# Start building output
output=""
output+='{
	auto_https off
	admin off
}

'
output+="http://:${caddy_port} {
	bind 0.0.0.0

	handle /__caddy_health {
		respond \"ok\" 200
	}
"

for entry in "${SERVICE_ROUTES[@]}"; do
  # Split entry into path and service name
  path=$(echo "$entry" | awk '{print $1}')
  svc=$(echo "$entry" | awk '{print $2}')
  port=$(get_port "$svc")

  if [[ -z "$port" ]]; then
    echo "  WARN: skipping $svc — not found in ports file" >&2
    continue
  fi

  output+="
	handle_path ${path}/* {
		reverse_proxy 127.0.0.1:${port}
	}
"
done

output+='
	log {
		output stderr
		format console
	}
}
'

# --- Output ---
if [[ "$PRINT_ONLY" == true ]]; then
  echo "$output"
else
  mkdir -p "$(dirname "$CADDYFILE")"
  echo "$output" > "$CADDYFILE"
  echo "Generated Caddyfile at $CADDYFILE (listening on :${caddy_port})"
fi
