# process-compose module for running the nammayatri stack
ny:
{ config, pkgs, lib, ... }:
let
  inherit (lib) types;
  # Read resolved ports from data/ports-resolved.nix (generated by resolve-ports.nix).
  # Falls back to the base ports.nix if the resolved file doesn't exist yet.
  #
  # Nix flakes exclude gitignored files from the source tree copy, so we can't
  # use a relative path to data/ports-resolved.nix. Instead, the calling script
  # (mission-control's run-mobility-stack-dev) writes ports-resolved.nix and the
  # Caddyfile first, then sets PORTS_RESOLVED_FILE to the absolute path and
  # invokes `nix run --impure` so builtins.getEnv works. Without --impure,
  # getEnv returns "" → safe fallback to the checked-in template.
  resolvedPortsPath = builtins.getEnv "PORTS_RESOLVED_FILE";
  resolvedPortsExists = resolvedPortsPath != "" && builtins.pathExists (/. + resolvedPortsPath);
  ports =
    if resolvedPortsExists
    then import (/. + resolvedPortsPath)
    else if resolvedPortsPath != ""
    then throw "PORTS_RESOLVED_FILE=${resolvedPortsPath} set but file not found — run resolve-ports before evaluating this flake."
    else import ./ports.nix;
  pcLib = import ny.inputs.common.inputs.process-compose-flake.lib { inherit lib; };
  # Which Haskell package contains the given cabal executable?
  cabalTargetForExe = lib.listToAttrs (lib.flatten (lib.mapAttrsToList
    (name: info: map (exe: lib.nameValuePair exe "${name}:exe:${exe}") (lib.attrNames info.exes))
    ny.config.haskellProjects.default.outputs.packages));
  accumulateProcessEnv = envVar: processes:
    lib.filter (x: x != null)
      (builtins.map
        (p:
          pcLib.lookupEnv envVar (p.environment or null))
        (lib.attrValues processes));
in
{
  options = {
    services.nammayatri = lib.mkOption {
      type = types.submodule {
        options = {
          enable = lib.mkEnableOption "Enable nammayatri stack";
          useCabal = lib.mkEnableOption "Use cabal instead of Nix";
          profile = lib.mkOption {
            type = types.enum [ "full" "backend" "testDashboard" ];
            default = "full";
            description = ''
              Which subset of the stack to launch:
                full           — backend (ny + tools) + all test processes (default).
                backend        — backend (ny + tools) + test-context-api + mock-server;
                                 no test-dashboard / test-local-api processes.
                testDashboard  — only test-dashboard + test-local-api; assumes the backend
                                 stack (including test-context-api) runs locally or remotely.
            '';
          };
        };
      };
    };
  };

  imports = [
    ny.inputs.services-flake.processComposeModules.default
    ny.inputs.passetto.processComposeModules.default
    ./postgres-with-replica.nix
  ];

  config =
    let
      inherit (ny) inputs self' inputs';
      cfg = config.services.nammayatri;

      # Metabase plugin JARs — deterministic, store-backed.
      #
      # Metabase OSS bundles the Postgres, MySQL, SQLite, and H2 drivers, which is
      # all atlas_dev needs. Without any extras, this evaluates to an empty
      # directory and Metabase falls back to its built-ins. To add e.g. Snowflake
      # later, append an entry below — `nix-prefetch-url <url>` gives the sha256:
      #
      #   { name = "snowflake"; version = "1.0.0"; url = "https://github.com/.../snowflake.metabase-driver.jar"; sha256 = "..."; }
      #
      # Pinned URLs + hashes mean no first-run downloads and no cache leakage
      # into the repo (which is what `Backend/plugins/` was before).
      metabaseDrivers = [ ];
      metabasePluginsDir = pkgs.linkFarm "metabase-plugins" (map
        (d: {
          name = "${d.name}.metabase-driver.jar";
          path = pkgs.fetchurl { inherit (d) url sha256; };
        })
        metabaseDrivers);

      # Metabase declarative config — applied on every startup via MB_CONFIG_FILE_PATH.
      # Bootstraps the admin user and registers atlas_dev as a Postgres data source so
      # the UI is usable on first launch without manual setup wizard clicks.
      # Docs: https://www.metabase.com/docs/latest/configuring-metabase/config-file
      metabaseConfigFile = pkgs.writeText "metabase-config.yml" ''
        version: 1
        config:
          users:
            - first_name: Admin
              last_name: Dev
              password: metabase123
              email: admin@nammayatri.local
          databases:
            - name: atlas_dev
              engine: postgres
              details:
                host: localhost
                port: ${toString ports.db-primary}
                user: atlas_superuser
                password: ""
                dbname: atlas_dev
                ssl: false
            - name: atlas_driver_offer_bpp_clickhouse
              engine: clickhouse
              details:
                host: localhost
                port: ${toString ports.clickhouse}
                user: default
                password: ""
                dbname: atlas_driver_offer_bpp
                ssl: false
            - name: atlas_app_clickhouse
              engine: clickhouse
              details:
                host: localhost
                port: ${toString ports.clickhouse}
                user: default
                password: ""
                dbname: atlas_app
                ssl: false
            - name: atlas_kafka_clickhouse
              engine: clickhouse
              details:
                host: localhost
                port: ${toString ports.clickhouse}
                user: default
                password: ""
                dbname: atlas_kafka
                ssl: false
            - name: app_monitor_clickhouse
              engine: clickhouse
              details:
                host: localhost
                port: ${toString ports.clickhouse}
                user: default
                password: ""
                dbname: app_monitor
                ssl: false
      '';

      # Skip the /setup wizard entirely. config_file (above) creates the admin
      # user, but doesn't mark the instance "set up", so Metabase still shows
      # the wizard on a fresh metabase.db. MB_USER_DEFAULTS fills + submits
      # the setup form programmatically on first launch.
      # Docs: https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_user_defaults
      metabaseUserDefaults = builtins.toJSON {
        token = "ny-local-dev-setup-token";
        user = {
          first_name = "Admin";
          last_name = "Dev";
          email = "admin@nammayatri.local";
          password = "metabase123";
          site_name = "Nammayatri";
        };
      };

      common = { name, ... }: {
        working_dir = "Backend";
        namespace = "ny";
        log_location = "${name}.log";
        environment = {
          # All Haskell services read these to override hardcoded ports in
          # their dhall configs with the resolved ports from ports-resolved.nix
          # (which may differ on shared devbox).
          REDIS_PORT = toString ports.redis;
          REDIS_CLUSTER_PORT = toString ports.redis-cluster-n1;
          REDIS_SECONDARY_CLUSTER_PORT = toString ports.redis-cluster-n2;
          DB_PRIMARY_PORT = toString ports.db-primary;
          DB_PRIMARY_REPLICA_PORT = toString ports.db-primary-replica;
          CLICKHOUSE_PORT = toString ports.clickhouse;
          KAFKA_PORT = toString ports.kafka;
          KAFKA_BROKER_PORT = toString ports.kafka;
          PASSETTO_SERVICE_PORT = toString ports.passetto-service;
          MOCK_SERVER_PORT = toString ports.mock-server;
          MOCK_SMS_PORT = toString ports.mock-sms;
          MOCK_GOOGLE_PORT = toString ports.mock-google;
          MOCK_FCM_PORT = toString ports.mock-fcm;
          MOCK_IDFY_PORT = toString ports.mock-idfy;
          MOCK_REGISTRY_PORT = toString ports.mock-registry;
          LOCATION_TRACKING_SERVICE_PORT = toString ports.location-tracking-service;
          RIDER_APP_PORT = toString ports.rider-app;
          DRIVER_APP_PORT = toString ports.dynamic-offer-driver-app;
          DRIVER_APP_INTERNAL_PORT = toString ports.dynamic-offer-driver-app-internal;
          BECKN_GATEWAY_PORT = toString ports.beckn-gateway;
          UNIFIED_DASHBOARD_PORT = toString ports.unified-dashboard;
          PROVIDER_DASHBOARD_PORT = toString ports.provider-dashboard;
          RIDER_DASHBOARD_PORT = toString ports.rider-dashboard;
        } // lib.optionalAttrs pkgs.stdenv.isLinux {
          # On non-NixOS Linux (remote devbox), Nix-built binaries need
          # LOCALE_ARCHIVE to find the system locale data.
          LOCALE_ARCHIVE = "/usr/lib/locale/locale-archive";
          # Force UTF-8 so Haskell's hGetContents can read migration SQL files
          # that contain non-ASCII characters (e.g. × in comments). Without
          # this, a devbox with LC_ALL=C (ASCII-only) raises:
          #   hGetContents: invalid argument (invalid byte sequence)
          # Redis processes override this back to LC_ALL=C via localeEnv.
          LC_ALL = "C.UTF-8";
        };
      };

      # The cabal executables we want to run as part of the nammayatri service
      # group.
      cabalExecutables = [
        "rider-app-exe"
        "dynamic-offer-driver-app-exe"
        "rider-dashboard-exe"
        "provider-dashboard-exe"
        "rider-app-drainer-exe"
        "dynamic-offer-driver-drainer-exe"
        "driver-offer-allocator-exe"
        "rider-app-scheduler-exe"
        "producer-exe"
        "kafka-consumers-exe"
      ];

      # In non-backend profiles (e.g. testDashboard) every haskell process is
      # disabled — but referencing `cabal run` / the nix-built exe path here
      # still forces evaluation of every haskell derivation, which kicks off
      # a full cabal build at `, run-local-test-dashboard` time. Short-circuit
      # to a noop command in those profiles so the derivation graph stays slim.
      # Wrap a cabal command in a mount namespace so GHC sees CI paths.
      # Reads .ci-project-root / .ci-cabal-dir written by cache-restore.
      # If those files don't exist, runs the command normally.
      wrapInCiNamespace = cmd: ''
        if [ -f .ci-project-root ]; then
          CI_PROJECT_ROOT=$(cat .ci-project-root)
          CI_CABAL_DIR=$(cat .ci-cabal-dir 2>/dev/null || echo "")
          LOCAL_ROOT=$(pwd)
          CI_HOME=$(echo "$CI_PROJECT_ROOT" | cut -d/ -f1-3)
          GHC_VER=$(ghc --numeric-version)
          # Overlay individual .a files from CI tarball over nix store.
          # Must bind-mount FILES not directories — mounting a directory hides
          # all other files (shared libs, .conf) that ghc-pkg needs.
          NIX_OVERLAY=""
          if [ -d "$LOCAL_ROOT/.nix-deps/nix/store" ]; then
            while IFS= read -r dep_file; do
              rel="''${dep_file#"$LOCAL_ROOT"/.nix-deps}"
              if [ -f "$rel" ]; then
                NIX_OVERLAY="$NIX_OVERLAY mount --bind /tmp/ns-root/.nix-deps$rel $rel &&"
              fi
            done < <(find "$LOCAL_ROOT/.nix-deps/nix/store" -name "*.a" -type f 2>/dev/null)
          fi
          unshare --user --mount --map-root-user bash -c "
            set -e
            export LC_ALL=C
            # Save local root before tmpfs hides /home
            mkdir -p /tmp/ns-root
            mount --bind $LOCAL_ROOT /tmp/ns-root
            mount -t tmpfs tmpfs /home
            mkdir -p $CI_HOME
            mkdir -p $CI_PROJECT_ROOT
            mount --bind /tmp/ns-root $CI_PROJECT_ROOT
            if [ -n '$CI_CABAL_DIR' ]; then
              mkdir -p $CI_CABAL_DIR
              if [ -d /tmp/ns-root/.cabal-dir ]; then
                mount --bind /tmp/ns-root/.cabal-dir $CI_CABAL_DIR
                mkdir -p $CI_CABAL_DIR/store/ghc-$GHC_VER
                ghc-pkg init $CI_CABAL_DIR/store/ghc-$GHC_VER/package.db 2>/dev/null || true
              else
                mkdir -p $CI_CABAL_DIR/store/ghc-$GHC_VER
                ghc-pkg init $CI_CABAL_DIR/store/ghc-$GHC_VER/package.db 2>/dev/null || true
              fi
              export CABAL_DIR=$CI_CABAL_DIR
            fi
            $NIX_OVERLAY true
            cd $CI_PROJECT_ROOT
            ${cmd}
          "
        else
          ${cmd}
        fi
      '';

      haskellProcessFor = name:
        if cfg.profile != "full" && cfg.profile != "backend"
        then { command = ":"; }
        else if cfg.useCabal
        then {
          command = "set -x; pwd; " + wrapInCiNamespace "cabal run ${cabalTargetForExe.${name}}";
          environment.CABAL_TARGET = cabalTargetForExe.${name};
        }
        else {
          command = "set -x; pwd; ${ny.config.haskellProjects.default.outputs.apps.${name}.program}";
        };

      # Run every cabal executable strictly sequentially. Each one waits for
      # the previous entry in `cabalExecutables` so only one process at a
      # time is in its early-startup window. This avoids the
      # `stripConcurrentlyForLocal` race in mobility-core where multiple
      # services concurrently `removePathForcibly` the shared
      # `/tmp/.../ny-migrations` staging dir and one fails with ENOTEMPTY.
      #
      # Chain rules:
      #   - First exe in the list depends only on init + mock-registry.
      #   - Every subsequent exe adds `<prev>.<cond>` where:
      #       * cond = `process_healthy` if `<prev>` has a readiness probe
      #         (the BAP/BPP servers — rider-app-exe, dynamic-offer-driver-app-exe).
      #         These have to be fully up before the next service starts so
      #         downstream services hit a real, working API.
      #       * cond = `process_started` otherwise (services without probes).
      #         `process_started` fires post-fork, by which time the previous
      #         service is already past its migration window.
      probeBackedExecutables = [
        "rider-app-exe"
        "dynamic-offer-driver-app-exe"
      ];
      prevChainCondition = prev:
        if builtins.elem prev probeBackedExecutables
        then "process_healthy"
        else "process_started";

      haskellProcesses.processes =
        lib.listToAttrs (lib.imap0
          (idx: name: {
            inherit name;
            value = {
              imports = [
                common
                (haskellProcessFor name)
              ];
              depends_on =
                {
                  "nammayatri-init".condition = "process_completed_successfully";
                  "mock-registry".condition = "process_healthy";
                } // (
                  if idx == 0 then { }
                  else
                    let prev = builtins.elemAt cabalExecutables (idx - 1); in
                    { ${prev}.condition = prevChainCondition prev; }
                );
              shutdown.signal = 9;
            };
          })
          cabalExecutables);

      inBackend = cfg.profile == "full" || cfg.profile == "backend";
      inTestDash = cfg.profile == "full" || cfg.profile == "testDashboard";
      backendProcs =
        cabalExecutables ++ [
          "rider-producer-exe"
          "nammayatri-init"
          "log-cleaner"
          "cache-restore"
          "cabal-build"
          "beckn-gateway"
          "mock-registry"
          "location-tracking-service"
          "notification-service"
          "osrm-server"
          "driver-proxy"
          "caddy-reverse-proxy"
          "metabase"
          "metabase-setup"
          "redis-commander"
          "mock-server"
          "test-context-api"
          "victoria-metrics"
        ];
      # Force-disable a process: also clobber its command + depends_on with
      # mkForce. Clobbering the command matters because the original command
      # often interpolates `${ny.config.haskellProjects…finalPackages.X}`,
      # which would otherwise force the haskell derivation to build even
      # though the process never runs.
      disableAll = names: lib.listToAttrs (map
        (n: lib.nameValuePair n {
          disabled = lib.mkForce true;
          depends_on = lib.mkForce { };
          command = lib.mkForce ":";
        })
        names);
    in
    {
      settings = {

        # Local Haskell processes
        imports = [ haskellProcesses ];

        processes = lib.mkMerge [
          (lib.mkIf (!inBackend) (disableAll backendProcs))
          (lib.mkIf (!inTestDash) (disableAll [ "test-local-api" "test-dashboard" "config-sync-server" ]))
          # When the backend slice is disabled, the test-dashboard / test-local-api
          # processes would otherwise wait on disabled backend processes
          # (nammayatri-init, rider-app-exe, …) — process-compose treats that as
          # a hard failure rather than auto-satisfying. Clear those depends_on
          # entries so the dashboard slice runs standalone.
          (lib.mkIf (!inBackend) {
            test-local-api.depends_on = lib.mkForce { };
            test-dashboard.depends_on = lib.mkForce { };
            config-sync-server.depends_on = lib.mkForce { };
          })
          # kafka should start only after zookeeper is healthy
          (lib.mkIf inBackend { kafka.depends_on."zookeeper".condition = "process_healthy"; })
          # On non-NixOS Linux (e.g. remote devbox), Nix-built binaries can't find
          # the system locale data without LOCALE_ARCHIVE. Redis-cluster nodes fail
          # with "Failed to configure LOCALE" if this is missing. Harmless on macOS
          # (glibc isn't used) and on NixOS (set globally).
          (lib.mkIf (pkgs.stdenv.isLinux && inBackend) (
            let
              localeEnv = {
                environment.LOCALE_ARCHIVE = "/usr/lib/locale/locale-archive";
                # Force a known-good locale so Redis doesn't fail with
                # "Failed to configure LOCALE for invalid locale name"
                # when the devbox LANG/LC_ALL is set to something not installed.
                environment.LC_ALL = "C";
              };
            in
            {
              "redis" = localeEnv;
              "cluster1-n1" = localeEnv;
              "cluster1-n2" = localeEnv;
              "cluster1-n3" = localeEnv;
              "cluster1-n4" = localeEnv;
              "cluster1-n5" = localeEnv;
              "cluster1-n6" = localeEnv;
              "cluster1-cluster-create" = localeEnv;
            }
          ))
          # Ensure all infrastructure services get SIGKILL on shutdown so
          # ports are freed immediately. Without this, SIGTERM-ignoring
          # processes linger and block port reuse on stack restarts.
          (lib.mkIf inBackend {
            "redis".shutdown.signal = 9;
            "cluster1-n1".shutdown.signal = 9;
            "cluster1-n2".shutdown.signal = 9;
            "cluster1-n3".shutdown.signal = 9;
            "cluster1-n4".shutdown.signal = 9;
            "cluster1-n5".shutdown.signal = 9;
            "cluster1-n6".shutdown.signal = 9;
            "cluster1-cluster-create".shutdown.signal = 9;
            "kafka".shutdown.signal = 9;
            "zookeeper".shutdown.signal = 9;
            "db-primary".shutdown.signal = lib.mkForce 9;
            "db-primary-replica".shutdown.signal = lib.mkForce 9;
          })
          (lib.mkIf (cfg.profile == "backend") (
            let excluded = [ "caddy-reverse-proxy" "nammayatri-init" "cabal-build" "cache-restore" "osrm-server" ];
            in lib.listToAttrs (map
              (n: lib.nameValuePair n {
                depends_on."caddy-reverse-proxy".condition = "process_healthy";
              })
              (lib.filter (n: !(lib.elem n excluded)) backendProcs))
          ))
          # Override passetto-service startup: skip passetto-init (keys are seeded via passetto-seed.sql).
          # The upstream process-compose.nix runs `passetto-init $password $keys` on every boot,
          # which unconditionally appends keys — causing pool growth across restarts.
          (lib.mkIf inBackend {
            passetto-service.command = lib.mkForce (pkgs.writeShellApplication {
              name = "passetto-service";
              runtimeInputs = [ inputs'.passetto.packages.passetto-service ];
              text = ''
                set -x
                MASTER_PASSWORD=1 passetto-server
              '';
            });
          })
          {
            # Rider producer: same binary as producer-exe, different env vars
            rider-producer-exe = {
              imports = [
                common
                (haskellProcessFor "producer-exe")
              ];
              environment = {
                PRODUCER_TYPE = "Rider";
                GET_MY_SCHEMA = "atlas_app";
                METRICS_PORT = toString ports.rider-producer-metrics;
                PRODUCER_HEALTHCHECK_PORT = toString ports.rider-producer-healthcheck;
              };
              depends_on = {
                "nammayatri-init".condition = "process_completed_successfully";
                "rider-app-exe".condition = "process_healthy";
                "dynamic-offer-driver-app-exe".condition = "process_healthy";
                "mock-registry".condition = "process_healthy";
              };
              shutdown.signal = 9;
            };

            # Things to do before local Haskell processes are started
            nammayatri-init = {
              imports = [ common ];
              depends_on = {
                # Services
                "db-primary".condition = "process_healthy";
                "kafka".condition = "process_healthy";
                "redis".condition = "process_healthy";
                # "redis-cluster".condition = "process_healthy";
                "nginx".condition = "process_healthy";
                "osrm-server".condition = "process_started";
                "passetto-service".condition = "process_started";
              } // lib.optionalAttrs cfg.useCabal {
                # Compile Haskell code
                "cabal-build".condition = "process_completed_successfully";
              };
              command = pkgs.writeShellApplication {
                name = "run-mobility-stack-init";
                runtimeInputs = with pkgs; [
                  redis
                ];
                text = ''
                  set -x
                  pwd
                  rm -f ./*.log # Clean up the log files
                  redis-cli -p ${toString ports.redis-cluster-n1} -c XGROUP CREATE Available_Jobs_Rider myGroup_Rider  0 MKSTREAM # TODO: remove this once cluster funtions from euler are fixed
                  redis-cli -p ${toString ports.redis-cluster-n1} -c XGROUP CREATE Available_Jobs myGroup  0 MKSTREAM # TODO: remove this once cluster funtions from euler are fixed
                  redis-cli -p ${toString ports.redis-cluster-n1} -c XGROUP CREATE Available_Chakras myGroup_Chakras  0 MKSTREAM # TODO: remove this once cluster funtions from euler are fixed
                  redis-cli -p ${toString ports.redis} XGROUP CREATE Available_Jobs_Rider myGroup_Rider 0 MKSTREAM
                  redis-cli -p ${toString ports.redis} XGROUP CREATE Available_Jobs myGroup 0 MKSTREAM
                  redis-cli -p ${toString ports.redis} XGROUP CREATE Available_Chakras myGroup_Chakras 0 MKSTREAM
                '';
              };
            };

            # Periodic log cleaner: truncates .log files exceeding 100MB
            # Covers process-compose logs (./*.log) and dhall/app logs (/tmp/*.log)
            log-cleaner = {
              imports = [ common ];
              command = pkgs.writeShellApplication {
                name = "log-cleaner";
                runtimeInputs = with pkgs; [ coreutils findutils procps ];
                text = ''
                  # Stale-instance reaper. Each previous `run-mobility-stack-dev`
                  # leaves its log-cleaner alive across stack restarts (the
                  # outgoing process-compose doesn't always reap children, and
                  # the loop below has no signal handler that exits cleanly).
                  # Result: after a few launches you accumulate 3–5 stale
                  # cleaners running OLD nix-store versions of this script
                  # (different size thresholds, different sleep cadences) — we
                  # observed +1G/sleep 300 ghosts still active after the source
                  # had moved to +100M/sleep 5. They all race on truncate, but
                  # the older +1G ones win the "what's oversized" check and
                  # producer logs balloon to 1.5GB+ before any truncation.
                  #
                  # Match by argv[0] = "<store-path>/bin/log-cleaner" — that
                  # token is unique to this script and present in every prior
                  # nix build, regardless of the threshold/sleep values inside.
                  # Exclude our own pid so we don't kill ourselves.
                  self_pid=$$
                  stale=$(pgrep -f '/log-cleaner/bin/log-cleaner' | grep -vx "$self_pid" || true)
                  if [ -n "$stale" ]; then
                    echo "log-cleaner: reaping stale instances: $stale"
                    # shellcheck disable=SC2086
                    kill -TERM $stale 2>/dev/null || true
                    sleep 1
                    # Anything still alive after SIGTERM gets SIGKILL — old
                    # cleaners ignore SIGTERM if they're mid-`find` syscall.
                    still=$(pgrep -f '/log-cleaner/bin/log-cleaner' | grep -vx "$self_pid" || true)
                    if [ -n "$still" ]; then
                      # shellcheck disable=SC2086
                      kill -KILL $still 2>/dev/null || true
                    fi
                  fi
                  while true; do
                    find .. -maxdepth 1 -name '*.log' -size +10M -exec truncate -s 0 {} \;
                    find /tmp -maxdepth 1 -name '*.log' -size +10M -exec truncate -s 0 {} \;
                    sleep 1
                  done
                '';
              };
              shutdown.signal = 9;
            };

            # Restore dist-newstyle cache from MinIO before building.
            # Finds the nearest ancestor commit on main that has a cached
            # dist-newstyle tarball, downloads it, and extracts it so that
            # cabal-build only rebuilds the delta.
            cache-restore = {
              imports = [ common ];
              disabled = !cfg.useCabal || cfg.profile != "backend";
              command = pkgs.writeShellApplication {
                name = "cache-restore";
                runtimeInputs = with pkgs; [ coreutils gnutar gnugrep gnused git jq minio-client zstd findutils binutils ];
                text = ''
                  set -euo pipefail

                  DIST_DIR="dist-newstyle"

                  # ── Skip download if local build already has HIE files ──
                  # After a full build, local dist-newstyle has HIE files.
                  # Re-downloading the CI cache would lose them and trigger a
                  # full rebuild. Only download when HIE files are missing.
                  if [ -d "$DIST_DIR/build" ]; then
                    HIE_FILE=$(find -L . -name "*.hie" -path "*/.hie/*" -print -quit 2>/dev/null || true)
                    if [ -n "$HIE_FILE" ]; then
                      echo "cache-restore: .hie files found, skipping download"
                      exit 0
                    fi
                  fi

                  # ── MinIO credentials ──
                  # Prefer /etc/service_discovery.json (written by github-runner daemon);
                  # fall back to chicken's local IP for devbox use.
                  MINIO_ENDPOINT=""
                  MINIO_ACCESS_KEY=""
                  MINIO_SECRET_KEY=""
                  if [ -f /etc/service_discovery.json ]; then
                    MINIO_ENDPOINT=$(jq -r '.minio_endpoint // empty' /etc/service_discovery.json)
                    MINIO_ACCESS_KEY=$(jq -r '.minio_access_key // empty' /etc/service_discovery.json)
                    MINIO_SECRET_KEY=$(jq -r '.minio_secret_key // empty' /etc/service_discovery.json)
                  fi
                  if [ -z "$MINIO_ENDPOINT" ]; then
                    MINIO_ENDPOINT="http://192.168.10.120:9000"
                    MINIO_ACCESS_KEY="minioadmin"
                    MINIO_SECRET_KEY="MinioAdmin@123"
                  fi

                  # Set up the alias (just saves config, doesn't test connectivity).
                  mc alias set nycache "$MINIO_ENDPOINT" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" || true
                  # Actually test connectivity by listing the bucket.
                  if ! mc ls nycache/haskell-cache/ >/dev/null 2>&1; then
                    echo "cache-restore: cannot reach MinIO at $MINIO_ENDPOINT, skipping"
                    exit 0
                  fi
                  echo "cache-restore: connected to MinIO at $MINIO_ENDPOINT"

                  # ── Pick the commit whose dist-newstyle cache to restore ──
                  # The dev's Mac (which has .git) computes the single nearest
                  # 'minio-pushed'-tagged commit and drops it in .ci-cache-sha.
                  # This lets deploys skip .git entirely — no git history here.
                  # Empty file (no tagged ancestor) or not-in-MinIO => build from
                  # scratch.
                  FOUND_SHA=$(tr -d '[:space:]' < .ci-cache-sha 2>/dev/null || true)
                  if [ -z "$FOUND_SHA" ]; then
                    echo "cache-restore: no minio-pushed cache commit in .ci-cache-sha, building from scratch"
                    exit 0
                  fi
                  if ! mc stat "nycache/haskell-cache/cabal-build/$FOUND_SHA/dist-newstyle.tar.zst" >/dev/null 2>&1; then
                    echo "cache-restore: cache commit $FOUND_SHA not in MinIO, building from scratch"
                    exit 0
                  fi
                  echo "cache-restore: found cache for commit $FOUND_SHA"

                  # ── Download and extract ──
                  TMPFILE=$(mktemp /tmp/dist-newstyle-XXXXXX.tar.zst)
                  trap 'rm -f "$TMPFILE"' EXIT

                  echo "cache-restore: downloading dist-newstyle.tar.zst from MinIO..."
                  if ! mc cp "nycache/haskell-cache/cabal-build/$FOUND_SHA/dist-newstyle.tar.zst" "$TMPFILE" 2>/dev/null; then
                    echo "cache-restore: download failed, skipping"
                    exit 0
                  fi

                  echo "cache-restore: extracting..."
                  rm -rf "$DIST_DIR"
                  tar -I 'zstd -T0' -xf "$TMPFILE" -C .
                  if [ ! -d "$DIST_DIR" ]; then
                    echo "cache-restore: ERROR — tar extraction did not create $DIST_DIR"
                    echo "cache-restore: tar contents:" && tar -I 'zstd -T0' -tf "$TMPFILE" | head -5
                    echo "cache-restore: cwd=$(pwd), ls:" && ls -la
                    exit 1
                  fi
                  echo "cache-restore: extracted $DIST_DIR ($(du -sh "$DIST_DIR" | cut -f1))"

                  # ── Link HIE dirs from tarball ──
                  # CI includes hie/ in the tarball alongside dist-newstyle.
                  # Set up .hie symlinks so GHC finds them and skips
                  # [HIE file is out of date] recompilation.
                  if [ -d "hie" ]; then
                    grep -E '^[[:space:]]+(app|lib|test)' cabal.project 2>/dev/null | awk '{print $1}' | while read -r pkg; do
                      [ -d "$pkg" ] || continue
                      if [ -d "hie/$pkg" ]; then
                        rm -rf "$pkg/.hie"
                        ln -sfn "$(pwd)/hie/$pkg" "$pkg/.hie"
                      fi
                    done
                    echo "cache-restore: linked .hie dirs from CI cache"
                  else
                    echo "cache-restore: no hie/ in tarball (older cache), HIE files will be rebuilt"
                  fi

                  # ── Detect CI's GHC derivation from the cache ──
                  # The cache was built with a specific ghc-9.2.7-with-packages
                  # derivation. We must use the SAME one for incremental builds,
                  # otherwise GHC sees [.a changed] on every module because
                  # different derivations have different package libraries.
                  #
                  # Extract GHC path from setup-config (small ~20KB file) instead
                  # of scanning the entire 6GB+ build directory.
                  CI_GHC=""
                  SETUP_CFG_GHC=""
                  SETUP_CFG_GHC=$(find "$DIST_DIR" -name "setup-config" -type f -print -quit 2>/dev/null || true)
                  if [ -n "$SETUP_CFG_GHC" ]; then
                    CI_GHC=$(strings "$SETUP_CFG_GHC" \
                      | grep -m1 -oE '/nix/store/[a-z0-9]+-ghc-[0-9.]+-with-packages/bin/ghc' || true)
                  fi

                  if [ -n "$CI_GHC" ] && [ -x "$CI_GHC" ]; then
                    echo "$CI_GHC" > "$DIST_DIR/.ci-ghc-path"
                    CURRENT_GHC=$(command -v ghc || echo "")
                    if [ "$CI_GHC" != "$CURRENT_GHC" ]; then
                      echo "cache-restore: CI used $CI_GHC"
                      echo "cache-restore: shell has $CURRENT_GHC"
                      echo "cache-restore: cabal-build will use CI's GHC for incremental build"
                    else
                      echo "cache-restore: GHC derivation matches current shell — perfect"
                    fi
                  elif [ -n "$CI_GHC" ]; then
                    echo "cache-restore: WARNING — found CI GHC at $CI_GHC but it is not executable"
                    echo "cache-restore: check if NFS mount from chicken includes this derivation"
                  else
                    echo "cache-restore: WARNING — could not detect CI's GHC derivation from cache"
                    echo "cache-restore: incremental build may recompile everything"
                  fi

                  # ── Read CI's project root and cabal-dir from MinIO ──
                  # CI pushes build-path.txt and cabal-dir-path.txt alongside the tarball.
                  CI_PROJECT_ROOT=""
                  CI_CABAL_DIR=""
                  BUILD_PATH_TMP=$(mktemp /tmp/build-path-XXXXXX.txt)
                  CABAL_DIR_TMP=$(mktemp /tmp/cabal-dir-path-XXXXXX.txt)
                  if mc cp "nycache/haskell-cache/cabal-build/$FOUND_SHA/build-path.txt" "$BUILD_PATH_TMP" 2>/dev/null; then
                    CI_PROJECT_ROOT="$(cat "$BUILD_PATH_TMP")/Backend"
                  fi
                  if mc cp "nycache/haskell-cache/cabal-build/$FOUND_SHA/cabal-dir-path.txt" "$CABAL_DIR_TMP" 2>/dev/null; then
                    CI_CABAL_DIR="$(cat "$CABAL_DIR_TMP")"
                  fi
                  rm -f "$BUILD_PATH_TMP" "$CABAL_DIR_TMP"

                  if [ -n "$CI_PROJECT_ROOT" ]; then
                    echo "$CI_PROJECT_ROOT" > .ci-project-root
                    echo "cache-restore: CI project root: $CI_PROJECT_ROOT"
                  fi
                  if [ -n "$CI_CABAL_DIR" ]; then
                    echo "$CI_CABAL_DIR" > .ci-cabal-dir
                    echo "cache-restore: CI CABAL_DIR: $CI_CABAL_DIR"
                  fi

                  echo "cache-restore: done — dist-newstyle restored from $FOUND_SHA"
                '';
              };
            };

            # Run 'cabal build' for all local Haskell processes.
            # Uses unshare + mount --bind to make the ENTIRE Backend directory
            # appear at CI's original project root path, then cd into it.
            # This way cabal sees the exact same project root, builddir, and
            # source paths as CI — no reconfiguration, no fingerprint mismatch.
            # Multiple users can build simultaneously because each unshare
            # creates an isolated mount namespace.
            cabal-build = {
              imports = [ common ];
              disabled = !cfg.useCabal;
              depends_on = lib.optionalAttrs (cfg.profile == "backend") {
                "cache-restore".condition = "process_completed";
              };
              command = pkgs.writeShellApplication {
                name = "cabal-build";
                runtimeInputs = lib.optionals pkgs.stdenv.isLinux [ pkgs.util-linux ];
                text = ''
                  GHC_FLAG=""
                  if [ -f dist-newstyle/.ci-ghc-path ]; then
                    CI_GHC=$(cat dist-newstyle/.ci-ghc-path)
                    if [ -x "$CI_GHC" ]; then
                      GHC_FLAG="-w $CI_GHC"
                      echo "cabal-build: using CI's GHC: $CI_GHC"
                    else
                      echo "cabal-build: CI GHC not found at $CI_GHC, using shell GHC"
                    fi
                  fi

                  TARGETS="${builtins.concatStringsSep " " (accumulateProcessEnv "CABAL_TARGET" config.settings.processes)}"

                  # If .ci-project-root doesn't exist but dist-newstyle has CI
                  # paths (from a previous cache-restore), detect them from
                  # setup-config so we still use the namespace.
                  if [ ! -f .ci-project-root ] && [ -d dist-newstyle/build ]; then
                    SETUP_CFG=$(find dist-newstyle -name "setup-config" -type f -print -quit 2>/dev/null || true)
                    if [ -n "$SETUP_CFG" ]; then
                      DETECTED_ROOT=$(strings "$SETUP_CFG" \
                        | grep -m1 -oE '/[^ "]+/nammayatri/Backend' \
                        | sed 's|/Backend.*|/Backend|' || true)
                      if [ -n "$DETECTED_ROOT" ] && [ "$DETECTED_ROOT" != "$(pwd)" ]; then
                        echo "$DETECTED_ROOT" > .ci-project-root
                        # Detect cabal-dir too
                        DETECTED_STORE_DB=$(strings "$SETUP_CFG" \
                          | grep -oE '/[^ "]+/store/ghc-[0-9.]+/package\.db' \
                          | grep -v '/nix/store/' | head -1 || true)
                        if [ -n "$DETECTED_STORE_DB" ]; then
                          echo "''${DETECTED_STORE_DB%%/store/*}" > .ci-cabal-dir
                        fi
                        echo "cabal-build: auto-detected CI project root from setup-config: $DETECTED_ROOT"
                      fi
                    fi
                  fi

                  if [ -f .ci-project-root ]; then
                    CI_PROJECT_ROOT=$(cat .ci-project-root)
                    CI_CABAL_DIR=$(cat .ci-cabal-dir 2>/dev/null || echo "")
                    LOCAL_ROOT=$(pwd)
                    echo "cabal-build: local root:  $LOCAL_ROOT"
                    echo "cabal-build: CI root:     $CI_PROJECT_ROOT"
                    echo "cabal-build: CI cabal-dir: $CI_CABAL_DIR"

                    # Derive CI user's home (/home/<user>) from the project root.
                    # We mount tmpfs there so we can create both the project root
                    # and cabal-dir directories inside the namespace.
                    CI_HOME=$(echo "$CI_PROJECT_ROOT" | cut -d/ -f1-3)
                    GHC_VER=$(ghc --numeric-version)

                    # Build overlay commands in the outer shell to avoid
                    # escaping issues inside bash -c "...".
                    # Overlays non-reproducible .a files from CI tarball over
                    # the nix store so GHC's addDependentFile fingerprint matches.
                    # Uses /tmp/ns-root reference — LOCAL_ROOT is hidden after tmpfs /home.
                    # Overlay individual .a files from CI tarball over nix store.
                    # Must bind-mount FILES not directories — mounting a directory
                    # hides all other files (shared libs, .conf) that ghc-pkg needs.
                    NIX_OVERLAY=""
                    if [ -d "$LOCAL_ROOT/.nix-deps/nix/store" ]; then
                      while IFS= read -r dep_file; do
                        rel="''${dep_file#"$LOCAL_ROOT"/.nix-deps}"
                        if [ -f "$rel" ]; then
                          NIX_OVERLAY="$NIX_OVERLAY mount --bind /tmp/ns-root/.nix-deps$rel $rel &&"
                          echo "cabal-build: will overlay file $rel"
                        else
                          echo "cabal-build: WARNING — $rel not found on this machine, cannot overlay"
                        fi
                      done < <(find "$LOCAL_ROOT/.nix-deps/nix/store" -name "*.a" -type f 2>/dev/null)
                    fi

                    # shellcheck disable=SC2086
                    unshare --user --mount --map-root-user bash -c "
                      set -e
                      export LC_ALL=C
                      # Save local root before tmpfs hides /home
                      mkdir -p /tmp/ns-root
                      mount --bind $LOCAL_ROOT /tmp/ns-root
                      mount -t tmpfs tmpfs /home
                      mkdir -p $CI_HOME
                      mkdir -p $CI_PROJECT_ROOT
                      mount --bind /tmp/ns-root $CI_PROJECT_ROOT

                      if [ -n '$CI_CABAL_DIR' ]; then
                        mkdir -p $CI_CABAL_DIR
                        if [ -d /tmp/ns-root/.cabal-dir ]; then
                          mount --bind /tmp/ns-root/.cabal-dir $CI_CABAL_DIR
                          # Create empty store (excluded from tarball to avoid
                          # stale package registrations from CI runners)
                          mkdir -p $CI_CABAL_DIR/store/ghc-$GHC_VER
                          ghc-pkg init $CI_CABAL_DIR/store/ghc-$GHC_VER/package.db 2>/dev/null || true
                          echo cabal-build: bind-mounted CI cabal-dir from cache
                        else
                          mkdir -p $CI_CABAL_DIR/store/ghc-$GHC_VER
                          ghc-pkg init $CI_CABAL_DIR/store/ghc-$GHC_VER/package.db 2>/dev/null || true
                          echo cabal-build: created empty cabal-dir '(no .cabal-dir in cache)'
                        fi
                        export CABAL_DIR=$CI_CABAL_DIR
                        echo cabal-build: CABAL_DIR=$CI_CABAL_DIR
                      fi

                      $NIX_OVERLAY true

                      cd $CI_PROJECT_ROOT
                      echo cabal-build: pwd=\$(pwd)
                      cabal build $GHC_FLAG $TARGETS 2>&1
                    "
                  else
                    echo "cabal-build: no CI project root detected, building normally"
                    # Don't use CI's GHC without the namespace — it references
                    # CI runner paths (/home/khuzema/...) that don't exist here.
                    # shellcheck disable=SC2086
                    cabal build $TARGETS
                  fi
                '';
              };
            };


            # Processes from other repos in nammayatri GitHub org
            beckn-gateway = {
              imports = [ common ];
              command = ny.config.haskellProjects.default.outputs.finalPackages.beckn-gateway;
              environment = {
                SERVICE_PORT = toString ports.beckn-gateway;
                METRICS_PORT = toString ports.beckn-gateway-metrics;
              };
            };
            mock-registry = {
              imports = [ common ];
              command = ny.config.haskellProjects.default.outputs.finalPackages.mock-registry;
              environment = {
                SERVICE_PORT = toString ports.mock-registry;
              };
              depends_on."nammayatri-init".condition = "process_completed_successfully";
              readiness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.mock-registry;
                  path = "/";
                };
              };
              # Mirrors readiness_probe → if /:${toString ports.mock-registry} stays unhealthy past the
              # failure_threshold window, process-compose kills the proc and
              # availability.restart brings it back. (Readiness alone never
              # triggers a restart in process-compose.)
              liveness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.mock-registry;
                  path = "/";
                };
                initial_delay_seconds = 30;
                period_seconds = 10;
                failure_threshold = 6;
                timeout_seconds = 5;
              };
              availability = {
                restart = "always";
                backoff_seconds = 20;
                max_restarts = 50;
              };
            };
            location-tracking-service = {
              imports = [ common ];
              command = ny.inputs.location-tracking-service.packages.${pkgs.system}.default;
              environment = {
                BYPASS_LTS_S3_AND_GCP = "true";
                SERVICE_PORT = toString ports.location-tracking-service;
                RIDER_APP_PORT = toString ports.rider-app;
                DRIVER_APP_PORT = toString ports.dynamic-offer-driver-app;
              };
              availability = {
                restart = "on_failure";
                backoff_seconds = 20;
                max_restarts = 50;
              };
            };
            notification-service = {
              imports = [ common ];
              command = ny.inputs.notification-service.packages.${pkgs.system}.default;
              environment = {
                SERVICE_PORT = toString ports.notification-service-grpc;
                GRPC_PORT = toString ports.notification-service-grpc;
                HTTP_SERVER_PORT = toString ports.notification-service;
                DRIVER_APP_PORT = toString ports.dynamic-offer-driver-app;
              };
              availability = {
                restart = "on_failure";
                backoff_seconds = 20;
                max_restarts = 50;
              };
            };
            osrm-server = {
              imports = [ common ];
              command = self'.packages.osrm-server;
            };

            kafka-consumers-exe = {
              environment = {
                CONSUMER_TYPE = "LOCATION_UPDATE";
              };
            };

            # Local Prometheus-compatible TSDB for integration-test metrics.
            # The dashboard's Metrics panel and context-api's push_suite_metrics
            # both target this. Falls back gracefully if disabled (push_metrics
            # logs "VictoriaMetrics unreachable" and the runner keeps going).
            victoria-metrics = {
              imports = [ common ];
              command = pkgs.writeShellApplication {
                name = "victoria-metrics";
                runtimeInputs = [ pkgs.victoriametrics ];
                text = ''
                  set -x
                  DATA_DIR="$(mkdir -p ../data/victoria-metrics && cd ../data/victoria-metrics && pwd)"
                  exec victoria-metrics \
                    -httpListenAddr=127.0.0.1:${toString ports.victoria-metrics} \
                    -storageDataPath="$DATA_DIR" \
                    -retentionPeriod=30d
                '';
              };
              namespace = lib.mkForce "test";
              readiness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.victoria-metrics;
                  path = "/health";
                };
                initial_delay_seconds = 2;
                period_seconds = 2;
                failure_threshold = 30;
                timeout_seconds = 3;
              };
              availability = {
                restart = "on_failure";
                backoff_seconds = 10;
                max_restarts = 30;
              };
            };

            # Test tools — dashboard, mock servers, context API
            # Unified mock server for Juspay, Stripe, PayTM, Acko, SOS, WhatsApp, CMRL, CRIS, etc.
            mock-server = {
              imports = [ common ];
              command = "${pkgs.python3.withPackages (ps: [ ps.pynacl ps.psycopg2 ])}/bin/python3 dev/mock-servers/server.py --port ${toString ports.mock-server}";
              namespace = lib.mkForce "test";
              depends_on."nammayatri-init".condition = "process_completed_successfully";
              availability = {
                restart = "on_failure";
                backoff_seconds = 20;
                max_restarts = 30;
              };
            };
            test-context-api = {
              imports = [ common ];
              # Hosts the config-sync trigger (replaces the old `config-sync` process), so it needs
              # the same python deps as config_transfer.py: psycopg2, requests, python-dotenv, rich, websockets.
              command = "${pkgs.python3.withPackages (ps: with ps; [ psycopg2 requests python-dotenv rich websockets ])}/bin/python3 dev/test-tool/context-api/server.py --port ${toString ports.test-context-api}";
              namespace = lib.mkForce "test";
              # Push integration-test metrics into the locally-running VictoriaMetrics.
              # The dashboard then reads them back via /api/metrics/query.
              environment.VICTORIA_METRICS_URL = "http://127.0.0.1:${toString ports.victoria-metrics}/api/v1/import/prometheus";
              environment.VICTORIA_METRICS_QUERY_URL = "http://127.0.0.1:${toString ports.victoria-metrics}";
              # Start once infra is up. The startup config-sync runs in a background thread,
              # so we DON'T block on dashboards — if a dashboard is still settling, the API
              # is still serving and the config-sync will succeed against the DB regardless.
              # The post-sync restart step targets rider-app-exe / dynamic-offer-driver-app-exe /
              # mock-registry, which we wait on so those PIDs exist when we try to kill them.
              depends_on = {
                "db-primary".condition = "process_healthy";
                "redis".condition = "process_healthy";
                "kafka".condition = "process_healthy";
                "passetto-service".condition = "process_started";
                "rider-app-exe".condition = "process_healthy";
                "rider-dashboard-exe".condition = "process_healthy";
                "provider-dashboard-exe".condition = "process_healthy";
                "dynamic-offer-driver-app-exe".condition = "process_healthy";
                "mock-registry".condition = "process_healthy";
                "victoria-metrics".condition = "process_healthy";
              };
              availability = {
                restart = "on_failure";
                backoff_seconds = 20;
                max_restarts = 30;
              };
            };
            test-local-api = {
              imports = [ common ];
              command = "${pkgs.python3.withPackages (ps: with ps; [ pyyaml ])}/bin/python3 dev/test-tool/local-api/server.py";
              namespace = lib.mkForce "test";
              depends_on."nammayatri-init".condition = "process_completed_successfully";
              availability = {
                restart = "on_failure";
                backoff_seconds = 20;
                max_restarts = 30;
              };
            };
            test-dashboard = {
              imports = [ common ];
              command = pkgs.writeShellApplication {
                name = "test-dashboard";
                runtimeInputs = [ pkgs.nodejs ];
                text = ''
                  cd dev/test-tool/dashboard
                  npm install
                  export NODE_ENV=development
                  export PORT=7070
                  export BROWSER=none
                  npm start
                '';
              };
              namespace = lib.mkForce "test";
              depends_on."rider-app-exe".condition = "process_healthy";
              availability = {
                restart = "on_failure";
                backoff_seconds = 20;
                max_restarts = 30;
              };
            };
            # Thin HTTP wrapper around config_transfer.cmd_export / cmd_patch so the
            # test-dashboard's Config Sync panel can trigger export+patch via REST.
            # Same python deps as test-context-api plus boto3 for --s3 uploads.
            # passetto-service is on PATH so the patch step can spawn its own
            # throwaway passetto-server against test_dashboard_<to>.
            config-sync-server = {
              imports = [ common ];
              command = pkgs.writeShellApplication {
                name = "config-sync-server";
                runtimeInputs = [
                  (pkgs.python3.withPackages (ps: with ps; [ psycopg2 requests python-dotenv boto3 ]))
                  inputs'.passetto.packages.passetto-service
                ];
                text = ''
                  exec python3 dev/config-sync/server.py
                '';
              };
              namespace = lib.mkForce "test";
              availability = {
                restart = "on_failure";
                backoff_seconds = 20;
                max_restarts = 30;
              };
            };
            metabase = {
              imports = [ common ];
              command = pkgs.writeShellApplication {
                name = "metabase";
                runtimeInputs = [ pkgs.metabase ];
                text = ''
                  set -x
                  # Working_dir for this service is `Backend/` (set in `common`).
                  # `../data/metabase` resolves to <repo-root>/data/metabase,
                  # the same convention postgres/kafka/passetto use.
                  MB_WORK="$(mkdir -p ../data/metabase && cd ../data/metabase && pwd)"
                  MB_PLUGINS="$MB_WORK/plugins"
                  mkdir -p "$MB_PLUGINS"
                  # Seed the writable plugins dir from our pinned nix-store
                  # linkFarm. Metabase needs MB_PLUGINS_DIR to be writable
                  # because it extracts its built-in drivers there on first
                  # launch; the read-only store path alone won't work.
                  # `cp -fL` deref's the linkFarm symlinks so the JARs land
                  # as real files. With an empty driver list, the loop is
                  # a no-op and only built-in drivers are used.
                  for jar in ${metabasePluginsDir}/*.jar; do
                    [ -e "$jar" ] || break
                    cp -fL "$jar" "$MB_PLUGINS/"
                  done
                  export MB_DB_FILE="$MB_WORK/metabase.db"
                  export MB_JETTY_HOST=0.0.0.0
                  export MB_JETTY_PORT=${toString ports.metabase}
                  export MB_CONFIG_FILE_PATH=${metabaseConfigFile}
                  # Auto-complete the /setup wizard on first launch — see comment
                  # next to `metabaseUserDefaults` in nammayatri.nix.
                  export MB_USER_DEFAULTS=${lib.escapeShellArg metabaseUserDefaults}
                  export MB_PLUGINS_DIR="$MB_PLUGINS"
                  # Pin CWD to the data dir so any stray writes (e.g. the H2
                  # sample DB) stay there, not in the repo's Backend/ dir.
                  cd "$MB_WORK"
                  exec metabase
                '';
              };
              namespace = lib.mkForce "tools";
              depends_on."db-primary".condition = "process_healthy";
              readiness_probe = {
                # Metabase exposes /api/health as soon as the DB is migrated
                # and Jetty is bound. metabase-setup waits on this.
                http_get = {
                  host = "127.0.0.1";
                  port = ports.metabase;
                  path = "/api/health";
                };
                initial_delay_seconds = 10;
                period_seconds = 5;
                failure_threshold = 60;
                timeout_seconds = 3;
              };
              # Mirror readiness with a slower-cadence liveness so persistent
              # failure of /api/health → kill+restart. Metabase first-boot
              # migration can take ~30s; give it a 60s grace period before
              # liveness starts checking.
              liveness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.metabase;
                  path = "/api/health";
                };
                initial_delay_seconds = 60;
                period_seconds = 15;
                failure_threshold = 4;
                timeout_seconds = 5;
              };
              availability = {
                restart = "always";
                backoff_seconds = 50;
                max_restarts = 30;
              };
            };

            metabase-setup = {
              imports = [ common ];
              command = pkgs.writeShellApplication {
                name = "metabase-setup";
                runtimeInputs = [ pkgs.curl pkgs.jq ];
                text = ''
                  set -uo pipefail
                  MB="http://127.0.0.1:${toString ports.metabase}"
                  EMAIL="admin@nammayatri.local"
                  PASS="metabase123"

                  # 1. Try to log in. Success => setup-token clears automatically.
                  login_body=$(jq -n --arg u "$EMAIL" --arg p "$PASS" \
                    '{username: $u, password: $p}')
                  login_code=$(curl -sS -o /tmp/mb-login.json -w "%{http_code}" \
                    -X POST "$MB/api/session" \
                    -H 'Content-Type: application/json' \
                    -d "$login_body" || echo 000)
                  if [ "$login_code" = "200" ]; then
                    echo "metabase: admin login OK — setup token cleared."
                    exit 0
                  fi
                  echo "metabase: login returned $login_code, falling back to /api/setup"

                  # 2. Fall back to /api/setup with the current setup-token.
                  token=$(curl -fsS "$MB/api/session/properties" \
                    | jq -r '."setup-token" // empty')
                  if [ -z "$token" ]; then
                    # No token => already set up by something else; don't fail.
                    echo "metabase: no setup-token — assuming already set up."
                    exit 0
                  fi
                  payload=$(jq -n --arg token "$token" --arg email "$EMAIL" --arg pass "$PASS" '{
                    token: $token,
                    user: {
                      first_name: "Admin",
                      last_name: "Dev",
                      email: $email,
                      password: $pass,
                      site_name: "Nammayatri"
                    },
                    prefs: {
                      site_name: "Nammayatri",
                      site_locale: "en",
                      allow_tracking: false
                    },
                    database: {
                      engine: "postgres",
                      name: "atlas_dev",
                      details: {
                        host: "localhost",
                        port: ${toString ports.db-primary},
                        user: "atlas_superuser",
                        password: "",
                        dbname: "atlas_dev",
                        ssl: false
                      }
                    }
                  }')
                  setup_code=$(curl -sS -o /tmp/mb-setup.json -w "%{http_code}" \
                    -X POST "$MB/api/setup" \
                    -H 'Content-Type: application/json' \
                    -d "$payload" || echo 000)
                  if [ "$setup_code" = "200" ]; then
                    echo "metabase: setup complete via /api/setup."
                    exit 0
                  fi
                  echo "metabase: /api/setup returned $setup_code (response: $(cat /tmp/mb-setup.json 2>/dev/null || echo '?'))"
                  # Best-effort: exit 0 so the dev stack stays green even if setup
                  # is in some odd partial state. Worst case: visit /setup once.
                  exit 0
                '';
              };
              namespace = lib.mkForce "tools";
              depends_on."metabase".condition = "process_healthy";
              availability = {
                restart = "no";
                max_restarts = 5;
              };
            };

            redis-commander = {
              imports = [ common ];
              command = pkgs.writeShellApplication {
                name = "redis-commander";
                runtimeInputs = [ pkgs.nodejs ];
                text = ''
                  set -x  # debug output
                  # Same convention as metabase: persist under <repo-root>/data/
                  # (gitignored) instead of ~/.cache. working_dir is `Backend/`.
                  RC_WORK="$(mkdir -p ../data/redis-commander && cd ../data/redis-commander && pwd)"
                  RC_PKG="$RC_WORK/node_modules/redis-commander"

                  # Install only if not already present
                  if [ ! -d "$RC_PKG" ]; then
                    mkdir -p "$RC_WORK"
                    cd "$RC_WORK"
                    npm init -y
                    npm install redis-commander@0.9.0
                  fi

                  # Always rewrite default.json with our connections (idempotent).
                  # redis-commander reads TOP-LEVEL config.connections — not config.redis.connections!
                  node <<NODE_SCRIPT
                  const fs = require('fs');
                  const p = '$RC_PKG/config/default.json';
                  const c = JSON.parse(fs.readFileSync(p, 'utf8'));
                  c.connections = [
                    { label: 'standalone', host: '127.0.0.1', port: ${toString ports.redis}, dbIndex: 0 },
                    { label: 'cluster',    host: '127.0.0.1', port: ${toString ports.redis-cluster-n1}, dbIndex: 0, isCluster: true, clusterNoTlsValidation: true }
                  ];
                  c.server.address = '0.0.0.0';
                  c.server.port = ${toString ports.redis-commander};
                  fs.writeFileSync(p, JSON.stringify(c, null, 2));
                  console.log('Patched default.json top-level connections:', c.connections.length);
                  NODE_SCRIPT

                  cd "$RC_PKG"
                  exec node bin/redis-commander.js --noauth
                '';
              };
              namespace = lib.mkForce "tools";
              depends_on = {
                "redis".condition = "process_healthy";
                "cluster1-cluster-create".condition = "process_completed_successfully";
              };
              availability = {
                restart = "on_failure";
                backoff_seconds = 50;
                max_restarts = 50;
              };
            };

            dynamic-offer-driver-app-exe = {
              environment = {
                SERVICE_PORT = toString ports.dynamic-offer-driver-app-internal;
                METRICS_PORT = toString ports.driver-app-metrics;
                RIDER_APP_PORT = toString ports.rider-app;
                DRIVER_APP_PORT = toString ports.dynamic-offer-driver-app;
              };
              # Probes hit ${toString ports.dynamic-offer-driver-app-internal} (the actual app port) so process_healthy
              # reflects the app itself, not the driver-proxy on ${toString ports.dynamic-offer-driver-app}.
              readiness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.dynamic-offer-driver-app-internal;
                  path = "/ui";
                };
                initial_delay_seconds = 30;
                period_seconds = 5;
                failure_threshold = 30;
                timeout_seconds = 5;
              };
              # Tightened: ~60s of consecutive failures past initial_delay → kill
              # + restart (was ~210s). Haskell + migrations get a 90s startup
              # window before liveness starts checking.
              liveness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.dynamic-offer-driver-app-internal;
                  path = "/ui";
                };
                initial_delay_seconds = 90;
                period_seconds = 10;
                failure_threshold = 6;
                timeout_seconds = 5;
              };
              availability = {
                restart = "always";
                backoff_seconds = 20;
                max_restarts = 50;
              };
              # Driver-proxy must own port 8016 before the app starts so any
              # consumer dialing localhost:8016 sees a working endpoint by the
              # time dynamic-offer-driver-app-exe is healthy. Merges with the
              # depends_on chain set by haskellProcesses (nammayatri-init,
              # mock-registry, and the previous cabalExecutable in the chain).
              depends_on."driver-proxy".condition = "process_healthy";
            };

            # Reverse proxy fronting the driver-app on its public port.
            # Caddyfile is inlined here (no separate file) — routing is:
            #   localhost:8016/ui/driver/location* -> localhost:8081 (LTS)
            #   localhost:8016/<anything else>     -> localhost:8116 (driver-app)
            #   localhost:8016/__driver_proxy_health -> 200 inline (probe)
            # Starts BEFORE dynamic-offer-driver-app-exe so the public port is
            # always reachable by the time the app is healthy.
            driver-proxy = {
              imports = [ common ];
              command =
                let
                  caddyfile = pkgs.writeText "driver-proxy.Caddyfile" ''
                    {
                    	auto_https off
                    	admin off
                    }

                    http://:${toString ports.dynamic-offer-driver-app} {
                    	# Port-only site address (no host), so this block matches
                    	# any Host header — 127.0.0.1:${toString ports.dynamic-offer-driver-app}, localhost:${toString ports.dynamic-offer-driver-app}, the
                    	# simulator's host alias, etc. With `http://127.0.0.1:${toString ports.dynamic-offer-driver-app}`
                    	# Caddy would only match Host=127.0.0.1:${toString ports.dynamic-offer-driver-app} and fall through
                    	# to its default empty 200 response for Host=localhost
                    	# requests (which is what the app sends).
                    	bind 127.0.0.1 ::1

                    	handle /__driver_proxy_health {
                    		respond "ok" 200
                    	}

                    	handle /ui/driver/location* {
                    		reverse_proxy 127.0.0.1:${toString ports.location-tracking-service}
                    	}

                    	handle {
                    		reverse_proxy 127.0.0.1:${toString ports.dynamic-offer-driver-app-internal}
                    	}

                    	log {
                    		output stderr
                    		format console
                    	}
                    }
                  '';
                in
                pkgs.writeShellApplication {
                  name = "driver-proxy";
                  runtimeInputs = [ pkgs.caddy ];
                  text = ''
                    exec caddy run --config ${caddyfile} --adapter caddyfile
                  '';
                };
              depends_on = {
                "nammayatri-init".condition = "process_completed_successfully";
              };
              readiness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.dynamic-offer-driver-app;
                  path = "/__driver_proxy_health";
                };
                initial_delay_seconds = 1;
                period_seconds = 2;
                failure_threshold = 5;
                timeout_seconds = 2;
              };
              availability = {
                restart = "always";
                backoff_seconds = 5;
                max_restarts = 50;
              };
              shutdown.signal = 9;
            };

            # Single reverse-proxy entry point for devbox access (via Tailscale).
            # Reads data/Caddyfile generated by build-caddyfile.sh.
            # Routes: /rider-app/*, /driver-app/*, /rider-dashboard/*, etc.
            caddy-reverse-proxy = {
              imports = [ common ];
              command = pkgs.writeShellApplication {
                name = "caddy-reverse-proxy";
                runtimeInputs = [ pkgs.caddy ];
                text = ''
                  CADDYFILE="''${FLAKE_ROOT:-..}/data/Caddyfile"
                  if [ ! -f "$CADDYFILE" ]; then
                    echo "ERROR: $CADDYFILE not found. Run build-caddyfile.sh first." >&2
                    exit 1
                  fi
                  echo "caddy-reverse-proxy: listening on :${toString ports.caddy-reverse-proxy}"
                  exec caddy run --config "$CADDYFILE" --adapter caddyfile
                '';
              };
              depends_on = {
                "nammayatri-init".condition = "process_completed_successfully";
              };
              readiness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.caddy-reverse-proxy;
                  path = "/__caddy_health";
                };
                initial_delay_seconds = 2;
                period_seconds = 3;
                failure_threshold = 5;
                timeout_seconds = 2;
              };
              availability = {
                restart = "always";
                backoff_seconds = 5;
                max_restarts = 50;
              };
              shutdown.signal = 9;
            };

            rider-app-exe = {
              environment.SERVICE_PORT = toString ports.rider-app;
              environment.METRICS_PORT = toString ports.rider-app-metrics;
              readiness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.rider-app;
                  path = "/v2";
                };
                initial_delay_seconds = 30;
                period_seconds = 5;
                failure_threshold = 30;
                timeout_seconds = 5;
              };
              # Same tightened liveness as dynamic-offer-driver-app-exe.
              liveness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.rider-app;
                  path = "/v2";
                };
                initial_delay_seconds = 90;
                period_seconds = 10;
                failure_threshold = 6;
                timeout_seconds = 5;
              };
              availability = {
                restart = "always";
                backoff_seconds = 20;
                max_restarts = 50;
              };
            };

            rider-dashboard-exe = {
              environment = {
                SERVICE_PORT = toString ports.rider-dashboard;
                METRICS_PORT = toString ports.rider-dashboard-metrics;
                RIDER_APP_PORT = toString ports.rider-app;
              };
              readiness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.rider-dashboard;
                  path = "/";
                };
                initial_delay_seconds = 15;
                period_seconds = 5;
                failure_threshold = 30;
                timeout_seconds = 3;
              };
              # Mirrors readiness so persistent failure → restart. Dashboards
              # boot fast, so a short window is fine.
              liveness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.rider-dashboard;
                  path = "/";
                };
                initial_delay_seconds = 30;
                period_seconds = 10;
                failure_threshold = 6;
                timeout_seconds = 5;
              };
              availability = {
                restart = "always";
                backoff_seconds = 15;
                max_restarts = 50;
              };
            };

            provider-dashboard-exe = {
              environment = {
                SERVICE_PORT = toString ports.provider-dashboard;
                METRICS_PORT = toString ports.provider-dashboard-metrics;
                RIDER_APP_PORT = toString ports.rider-app;
                DRIVER_APP_PORT = toString ports.dynamic-offer-driver-app;
              };
              readiness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.provider-dashboard;
                  path = "/";
                };
                initial_delay_seconds = 15;
                period_seconds = 5;
                failure_threshold = 30;
                timeout_seconds = 3;
              };
              liveness_probe = {
                http_get = {
                  host = "127.0.0.1";
                  port = ports.provider-dashboard;
                  path = "/";
                };
                initial_delay_seconds = 30;
                period_seconds = 10;
                failure_threshold = 6;
                timeout_seconds = 5;
              };
              availability = {
                restart = "always";
                backoff_seconds = 20;
                max_restarts = 50;
              };
            };

            rider-app-scheduler-exe = {
              environment.SERVICE_PORT = toString ports.rider-app-scheduler;
              environment.METRICS_PORT = toString ports.rider-app-scheduler-metrics;
              availability = {
                restart = "always";
                backoff_seconds = 20;
                max_restarts = 50;
              };
            };

            driver-offer-allocator-exe = {
              environment.SERVICE_PORT = toString ports.driver-offer-allocator;
              environment.METRICS_PORT = toString ports.driver-offer-allocator-metrics;
              availability = {
                restart = "always";
                backoff_seconds = 20;
                max_restarts = 50;
              };
            };

            producer-exe = {
              environment = {
                METRICS_PORT = toString ports.producer-metrics;
                PRODUCER_HEALTHCHECK_PORT = toString ports.producer-healthcheck;
              };
            };
          }
        ];
      };

      # External services
      services = lib.mkMerge [
        # When the backend slice is disabled, the infra services (db / redis /
        # kafka / clickhouse / nginx / passetto) are expected to live on
        # another host or terminal — turn them off here so this profile is a
        # pure consumer.
        (lib.mkIf (cfg.profile == "testDashboard") {
          postgres-with-replica.db-primary.enable = lib.mkForce false;
          redis."redis".enable = lib.mkForce false;
          redis-cluster."cluster1".enable = lib.mkForce false;
          zookeeper."zookeeper".enable = lib.mkForce false;
          apache-kafka."kafka".enable = lib.mkForce false;
          nginx."nginx".enable = lib.mkForce false;
          passetto.enable = lib.mkForce false;
          clickhouse."clickhouse-db".enable = lib.mkForce false;
        })
        {
          postgres-with-replica.db-primary = {
            enable = true;
            extraMasterDBSettings = { name, ... }: {
              # Unix socket length is supposed to be under 108 chars, see: https://linux.die.net/man/7/unix
              socketDir = "$HOME/NY/socket/${name}";
              extensions = extensions: [
                extensions.postgis
              ];
              initialDatabases = [
                {
                  name = "atlas_dev";
                  # Schema-only initialization. local-testing-data/*.sql is NOT loaded here
                  # because dev/ddl-migrations and feature-migrations need to run on empty tables
                  # (so SET NOT NULL / FK validations pass). After dev/ddl-migrations + feature-migrations
                  # complete, test-context-api applies dev/local-testing-data/*.sql.
                  schemas = [
                    ../../dev/sql-seed/pre-init.sql
                    ../../dev/sql-seed/rider-app-seed.sql
                    ../../dev/sql-seed/public-transport-rider-platform-seed.sql
                    ../../dev/sql-seed/mock-registry-seed.sql
                    ../../dev/sql-seed/dynamic-offer-driver-app-seed.sql
                    ../../dev/sql-seed/rider-dashboard-seed.sql
                    ../../dev/sql-seed/provider-dashboard-seed.sql
                    ../../dev/sql-seed/unified-dashboard-seed.sql
                    ../../dev/sql-seed/safety-dashboard-seed.sql
                    ../../dev/sql-seed/special-zone-seed.sql
                    ../../dev/sql-seed/kaal-chakra-seed.sql
                  ];
                }
              ];
              initialScript.before = ''
                CREATE USER repl_user replication;
                CREATE USER atlas WITH PASSWORD 'atlas';
              '';
              port = ports.db-primary;
            };
            extraReplicaDBSettings = { name, ... }: {
              socketDir = "$HOME/NY/socket/${name}";
              port = ports.db-primary-replica;
            };
          };

          redis."redis" = {
            enable = true;
            port = ports.redis;
          };

          redis-cluster."cluster1" = {
            enable = true;
            nodes = {
              "n1" = { port = ports.redis-cluster-n1; };
              "n2" = { port = ports.redis-cluster-n2; };
              "n3" = { port = ports.redis-cluster-n3; };
              "n4" = { port = ports.redis-cluster-n4; };
              "n5" = { port = ports.redis-cluster-n5; };
              "n6" = { port = ports.redis-cluster-n6; };
            };
          };

          zookeeper."zookeeper" = {
            enable = true;
            port = ports.zookeeper;
          };

          apache-kafka."kafka" = {
            enable = true;
            port = ports.kafka;
            settings = {
              # Since the available brokers are only 1
              "offsets.topic.replication.factor" = 1;
              "zookeeper.connect" = [ "localhost:${toString ports.zookeeper}" ];
            };
          };


          nginx."nginx" = {
            enable = true;
            port = ports.nginx;
          };

          passetto = {
            enable = true;
            port = ports.passetto-service;
            extraDbSettings = { name, ... }: {
              port = ports.passetto-db;
              socketDir = "$HOME/NY/socket/${name}";
            };
            package = inputs'.passetto.packages.passetto-service;
          };

          clickhouse."clickhouse-db" = {
            enable = true;
            port = 9000; # clickhouse native TCP port — not in ports.nix (internal only)
            extraConfig.http_port = ports.clickhouse;
            initialDatabases = [
              {
                name = "atlas_kafka";
                schemas = [
                  ../../dev/clickhouse/sql-seed/atlas-kafka-seed.sql
                  ../../dev/clickhouse/local-testing-data/atlas-kafka.sql
                ];
              }
              {
                name = "atlas_driver_offer_bpp";
                schemas = [
                  ../../dev/clickhouse/sql-seed/atlas-driver-offer-bpp-seed.sql
                  ../../dev/clickhouse/local-testing-data/atlas-driver-offer-bpp.sql
                ];
              }
              {
                name = "app_monitor";
                schemas = [
                  ../../dev/clickhouse/sql-seed/app-monitor-seed.sql
                ];
              }
              {
                name = "atlas_app";
                schemas = [
                  ../../dev/clickhouse/sql-seed/atlas-app-seed.sql
                ];
              }
            ];
          };
        }
      ];
    };
}
