@registry-host = {{rg/url}}

POST {{registry-host}}/lookup
content-type: application/json

{
    "type": "BAP",
    "domain": "{{fmd/domain}}"
}

###

POST {{registry-host}}/create
content-type: application/json

{
    "ukId": "test-bap-unique-key-id",
    "subscriber_id": "test-bap-id",
    "subscriber_url": "https://test-bap-id",
    "type": "BAP",
    "domain": "nic2004:55204",
    "signing_public_key": "kCa4OlmRVfCPcvzjPPGik0Ljei5dRYuuj/2K6upaf1E=",
    "status": "SUBSCRIBED",
    "created": "{{$datetime iso8601}}",
    "updated": "{{$datetime iso8601}}"
}

###

POST {{registry-host}}/delete
    ?unique_key_id=test-bap-unique-key-id
    &subscriber_id=test-bap-id
content-type: application/json

{

}