// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapillary.proto
// Protobuf Java Version: 4.26.1

public final class Mapillary {
  private Mapillary() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Mapillary.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageLayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageLayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    java.util.List<Mapillary.ImageLayer.Image> 
        getImagesList();
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    Mapillary.ImageLayer.Image getImages(int index);
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    int getImagesCount();
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    java.util.List<? extends Mapillary.ImageLayer.ImageOrBuilder> 
        getImagesOrBuilderList();
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    Mapillary.ImageLayer.ImageOrBuilder getImagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ImageLayer}
   */
  public static final class ImageLayer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ImageLayer)
      ImageLayerOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ImageLayer.class.getName());
    }
    // Use ImageLayer.newBuilder() to construct.
    private ImageLayer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ImageLayer() {
      images_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Mapillary.internal_static_ImageLayer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Mapillary.internal_static_ImageLayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Mapillary.ImageLayer.class, Mapillary.ImageLayer.Builder.class);
    }

    public interface ImageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ImageLayer.Image)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 captured_at = 1;</code>
       * @return The capturedAt.
       */
      long getCapturedAt();

      /**
       * <code>int32 compass_angle = 2;</code>
       * @return The compassAngle.
       */
      int getCompassAngle();

      /**
       * <code>int32 creator_id = 3;</code>
       * @return The creatorId.
       */
      int getCreatorId();

      /**
       * <code>int32 id = 4;</code>
       * @return The id.
       */
      int getId();

      /**
       * <code>string sequence_id = 5;</code>
       * @return The sequenceId.
       */
      java.lang.String getSequenceId();
      /**
       * <code>string sequence_id = 5;</code>
       * @return The bytes for sequenceId.
       */
      com.google.protobuf.ByteString
          getSequenceIdBytes();

      /**
       * <code>int32 organization_id = 6;</code>
       * @return The organizationId.
       */
      int getOrganizationId();

      /**
       * <code>bool is_pano = 7;</code>
       * @return The isPano.
       */
      boolean getIsPano();
    }
    /**
     * Protobuf type {@code ImageLayer.Image}
     */
    public static final class Image extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:ImageLayer.Image)
        ImageOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          Image.class.getName());
      }
      // Use Image.newBuilder() to construct.
      private Image(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private Image() {
        sequenceId_ = "";
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Mapillary.internal_static_ImageLayer_Image_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Mapillary.internal_static_ImageLayer_Image_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Mapillary.ImageLayer.Image.class, Mapillary.ImageLayer.Image.Builder.class);
      }

      public static final int CAPTURED_AT_FIELD_NUMBER = 1;
      private long capturedAt_ = 0L;
      /**
       * <code>int64 captured_at = 1;</code>
       * @return The capturedAt.
       */
      @java.lang.Override
      public long getCapturedAt() {
        return capturedAt_;
      }

      public static final int COMPASS_ANGLE_FIELD_NUMBER = 2;
      private int compassAngle_ = 0;
      /**
       * <code>int32 compass_angle = 2;</code>
       * @return The compassAngle.
       */
      @java.lang.Override
      public int getCompassAngle() {
        return compassAngle_;
      }

      public static final int CREATOR_ID_FIELD_NUMBER = 3;
      private int creatorId_ = 0;
      /**
       * <code>int32 creator_id = 3;</code>
       * @return The creatorId.
       */
      @java.lang.Override
      public int getCreatorId() {
        return creatorId_;
      }

      public static final int ID_FIELD_NUMBER = 4;
      private int id_ = 0;
      /**
       * <code>int32 id = 4;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }

      public static final int SEQUENCE_ID_FIELD_NUMBER = 5;
      @SuppressWarnings("serial")
      private volatile java.lang.Object sequenceId_ = "";
      /**
       * <code>string sequence_id = 5;</code>
       * @return The sequenceId.
       */
      @java.lang.Override
      public java.lang.String getSequenceId() {
        java.lang.Object ref = sequenceId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sequenceId_ = s;
          return s;
        }
      }
      /**
       * <code>string sequence_id = 5;</code>
       * @return The bytes for sequenceId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSequenceIdBytes() {
        java.lang.Object ref = sequenceId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sequenceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ORGANIZATION_ID_FIELD_NUMBER = 6;
      private int organizationId_ = 0;
      /**
       * <code>int32 organization_id = 6;</code>
       * @return The organizationId.
       */
      @java.lang.Override
      public int getOrganizationId() {
        return organizationId_;
      }

      public static final int IS_PANO_FIELD_NUMBER = 7;
      private boolean isPano_ = false;
      /**
       * <code>bool is_pano = 7;</code>
       * @return The isPano.
       */
      @java.lang.Override
      public boolean getIsPano() {
        return isPano_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (capturedAt_ != 0L) {
          output.writeInt64(1, capturedAt_);
        }
        if (compassAngle_ != 0) {
          output.writeInt32(2, compassAngle_);
        }
        if (creatorId_ != 0) {
          output.writeInt32(3, creatorId_);
        }
        if (id_ != 0) {
          output.writeInt32(4, id_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sequenceId_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 5, sequenceId_);
        }
        if (organizationId_ != 0) {
          output.writeInt32(6, organizationId_);
        }
        if (isPano_ != false) {
          output.writeBool(7, isPano_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (capturedAt_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, capturedAt_);
        }
        if (compassAngle_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, compassAngle_);
        }
        if (creatorId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, creatorId_);
        }
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, id_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sequenceId_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(5, sequenceId_);
        }
        if (organizationId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, organizationId_);
        }
        if (isPano_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(7, isPano_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Mapillary.ImageLayer.Image)) {
          return super.equals(obj);
        }
        Mapillary.ImageLayer.Image other = (Mapillary.ImageLayer.Image) obj;

        if (getCapturedAt()
            != other.getCapturedAt()) return false;
        if (getCompassAngle()
            != other.getCompassAngle()) return false;
        if (getCreatorId()
            != other.getCreatorId()) return false;
        if (getId()
            != other.getId()) return false;
        if (!getSequenceId()
            .equals(other.getSequenceId())) return false;
        if (getOrganizationId()
            != other.getOrganizationId()) return false;
        if (getIsPano()
            != other.getIsPano()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CAPTURED_AT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCapturedAt());
        hash = (37 * hash) + COMPASS_ANGLE_FIELD_NUMBER;
        hash = (53 * hash) + getCompassAngle();
        hash = (37 * hash) + CREATOR_ID_FIELD_NUMBER;
        hash = (53 * hash) + getCreatorId();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + SEQUENCE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSequenceId().hashCode();
        hash = (37 * hash) + ORGANIZATION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getOrganizationId();
        hash = (37 * hash) + IS_PANO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsPano());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Mapillary.ImageLayer.Image parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Mapillary.ImageLayer.Image parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Mapillary.ImageLayer.Image parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Mapillary.ImageLayer.Image parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Mapillary.ImageLayer.Image parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Mapillary.ImageLayer.Image parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Mapillary.ImageLayer.Image parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static Mapillary.ImageLayer.Image parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static Mapillary.ImageLayer.Image parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static Mapillary.ImageLayer.Image parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Mapillary.ImageLayer.Image parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static Mapillary.ImageLayer.Image parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Mapillary.ImageLayer.Image prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ImageLayer.Image}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ImageLayer.Image)
          Mapillary.ImageLayer.ImageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Mapillary.internal_static_ImageLayer_Image_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Mapillary.internal_static_ImageLayer_Image_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Mapillary.ImageLayer.Image.class, Mapillary.ImageLayer.Image.Builder.class);
        }

        // Construct using Mapillary.ImageLayer.Image.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          capturedAt_ = 0L;
          compassAngle_ = 0;
          creatorId_ = 0;
          id_ = 0;
          sequenceId_ = "";
          organizationId_ = 0;
          isPano_ = false;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Mapillary.internal_static_ImageLayer_Image_descriptor;
        }

        @java.lang.Override
        public Mapillary.ImageLayer.Image getDefaultInstanceForType() {
          return Mapillary.ImageLayer.Image.getDefaultInstance();
        }

        @java.lang.Override
        public Mapillary.ImageLayer.Image build() {
          Mapillary.ImageLayer.Image result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public Mapillary.ImageLayer.Image buildPartial() {
          Mapillary.ImageLayer.Image result = new Mapillary.ImageLayer.Image(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(Mapillary.ImageLayer.Image result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.capturedAt_ = capturedAt_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.compassAngle_ = compassAngle_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.creatorId_ = creatorId_;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.id_ = id_;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            result.sequenceId_ = sequenceId_;
          }
          if (((from_bitField0_ & 0x00000020) != 0)) {
            result.organizationId_ = organizationId_;
          }
          if (((from_bitField0_ & 0x00000040) != 0)) {
            result.isPano_ = isPano_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Mapillary.ImageLayer.Image) {
            return mergeFrom((Mapillary.ImageLayer.Image)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Mapillary.ImageLayer.Image other) {
          if (other == Mapillary.ImageLayer.Image.getDefaultInstance()) return this;
          if (other.getCapturedAt() != 0L) {
            setCapturedAt(other.getCapturedAt());
          }
          if (other.getCompassAngle() != 0) {
            setCompassAngle(other.getCompassAngle());
          }
          if (other.getCreatorId() != 0) {
            setCreatorId(other.getCreatorId());
          }
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (!other.getSequenceId().isEmpty()) {
            sequenceId_ = other.sequenceId_;
            bitField0_ |= 0x00000010;
            onChanged();
          }
          if (other.getOrganizationId() != 0) {
            setOrganizationId(other.getOrganizationId());
          }
          if (other.getIsPano() != false) {
            setIsPano(other.getIsPano());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  capturedAt_ = input.readInt64();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 16: {
                  compassAngle_ = input.readInt32();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
                case 24: {
                  creatorId_ = input.readInt32();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                case 32: {
                  id_ = input.readInt32();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 32
                case 42: {
                  sequenceId_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000010;
                  break;
                } // case 42
                case 48: {
                  organizationId_ = input.readInt32();
                  bitField0_ |= 0x00000020;
                  break;
                } // case 48
                case 56: {
                  isPano_ = input.readBool();
                  bitField0_ |= 0x00000040;
                  break;
                } // case 56
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private long capturedAt_ ;
        /**
         * <code>int64 captured_at = 1;</code>
         * @return The capturedAt.
         */
        @java.lang.Override
        public long getCapturedAt() {
          return capturedAt_;
        }
        /**
         * <code>int64 captured_at = 1;</code>
         * @param value The capturedAt to set.
         * @return This builder for chaining.
         */
        public Builder setCapturedAt(long value) {

          capturedAt_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>int64 captured_at = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCapturedAt() {
          bitField0_ = (bitField0_ & ~0x00000001);
          capturedAt_ = 0L;
          onChanged();
          return this;
        }

        private int compassAngle_ ;
        /**
         * <code>int32 compass_angle = 2;</code>
         * @return The compassAngle.
         */
        @java.lang.Override
        public int getCompassAngle() {
          return compassAngle_;
        }
        /**
         * <code>int32 compass_angle = 2;</code>
         * @param value The compassAngle to set.
         * @return This builder for chaining.
         */
        public Builder setCompassAngle(int value) {

          compassAngle_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>int32 compass_angle = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearCompassAngle() {
          bitField0_ = (bitField0_ & ~0x00000002);
          compassAngle_ = 0;
          onChanged();
          return this;
        }

        private int creatorId_ ;
        /**
         * <code>int32 creator_id = 3;</code>
         * @return The creatorId.
         */
        @java.lang.Override
        public int getCreatorId() {
          return creatorId_;
        }
        /**
         * <code>int32 creator_id = 3;</code>
         * @param value The creatorId to set.
         * @return This builder for chaining.
         */
        public Builder setCreatorId(int value) {

          creatorId_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>int32 creator_id = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearCreatorId() {
          bitField0_ = (bitField0_ & ~0x00000004);
          creatorId_ = 0;
          onChanged();
          return this;
        }

        private int id_ ;
        /**
         * <code>int32 id = 4;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
          return id_;
        }
        /**
         * <code>int32 id = 4;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {

          id_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>int32 id = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000008);
          id_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object sequenceId_ = "";
        /**
         * <code>string sequence_id = 5;</code>
         * @return The sequenceId.
         */
        public java.lang.String getSequenceId() {
          java.lang.Object ref = sequenceId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            sequenceId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string sequence_id = 5;</code>
         * @return The bytes for sequenceId.
         */
        public com.google.protobuf.ByteString
            getSequenceIdBytes() {
          java.lang.Object ref = sequenceId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            sequenceId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string sequence_id = 5;</code>
         * @param value The sequenceId to set.
         * @return This builder for chaining.
         */
        public Builder setSequenceId(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          sequenceId_ = value;
          bitField0_ |= 0x00000010;
          onChanged();
          return this;
        }
        /**
         * <code>string sequence_id = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearSequenceId() {
          sequenceId_ = getDefaultInstance().getSequenceId();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
          return this;
        }
        /**
         * <code>string sequence_id = 5;</code>
         * @param value The bytes for sequenceId to set.
         * @return This builder for chaining.
         */
        public Builder setSequenceIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          sequenceId_ = value;
          bitField0_ |= 0x00000010;
          onChanged();
          return this;
        }

        private int organizationId_ ;
        /**
         * <code>int32 organization_id = 6;</code>
         * @return The organizationId.
         */
        @java.lang.Override
        public int getOrganizationId() {
          return organizationId_;
        }
        /**
         * <code>int32 organization_id = 6;</code>
         * @param value The organizationId to set.
         * @return This builder for chaining.
         */
        public Builder setOrganizationId(int value) {

          organizationId_ = value;
          bitField0_ |= 0x00000020;
          onChanged();
          return this;
        }
        /**
         * <code>int32 organization_id = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearOrganizationId() {
          bitField0_ = (bitField0_ & ~0x00000020);
          organizationId_ = 0;
          onChanged();
          return this;
        }

        private boolean isPano_ ;
        /**
         * <code>bool is_pano = 7;</code>
         * @return The isPano.
         */
        @java.lang.Override
        public boolean getIsPano() {
          return isPano_;
        }
        /**
         * <code>bool is_pano = 7;</code>
         * @param value The isPano to set.
         * @return This builder for chaining.
         */
        public Builder setIsPano(boolean value) {

          isPano_ = value;
          bitField0_ |= 0x00000040;
          onChanged();
          return this;
        }
        /**
         * <code>bool is_pano = 7;</code>
         * @return This builder for chaining.
         */
        public Builder clearIsPano() {
          bitField0_ = (bitField0_ & ~0x00000040);
          isPano_ = false;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ImageLayer.Image)
      }

      // @@protoc_insertion_point(class_scope:ImageLayer.Image)
      private static final Mapillary.ImageLayer.Image DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Mapillary.ImageLayer.Image();
      }

      public static Mapillary.ImageLayer.Image getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Image>
          PARSER = new com.google.protobuf.AbstractParser<Image>() {
        @java.lang.Override
        public Image parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Image> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Image> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public Mapillary.ImageLayer.Image getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int IMAGES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<Mapillary.ImageLayer.Image> images_;
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    @java.lang.Override
    public java.util.List<Mapillary.ImageLayer.Image> getImagesList() {
      return images_;
    }
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Mapillary.ImageLayer.ImageOrBuilder> 
        getImagesOrBuilderList() {
      return images_;
    }
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    @java.lang.Override
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    @java.lang.Override
    public Mapillary.ImageLayer.Image getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated .ImageLayer.Image images = 1;</code>
     */
    @java.lang.Override
    public Mapillary.ImageLayer.ImageOrBuilder getImagesOrBuilder(
        int index) {
      return images_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < images_.size(); i++) {
        output.writeMessage(1, images_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < images_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, images_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Mapillary.ImageLayer)) {
        return super.equals(obj);
      }
      Mapillary.ImageLayer other = (Mapillary.ImageLayer) obj;

      if (!getImagesList()
          .equals(other.getImagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getImagesCount() > 0) {
        hash = (37 * hash) + IMAGES_FIELD_NUMBER;
        hash = (53 * hash) + getImagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Mapillary.ImageLayer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mapillary.ImageLayer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mapillary.ImageLayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mapillary.ImageLayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mapillary.ImageLayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mapillary.ImageLayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mapillary.ImageLayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Mapillary.ImageLayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Mapillary.ImageLayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Mapillary.ImageLayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Mapillary.ImageLayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Mapillary.ImageLayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Mapillary.ImageLayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImageLayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageLayer)
        Mapillary.ImageLayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Mapillary.internal_static_ImageLayer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Mapillary.internal_static_ImageLayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Mapillary.ImageLayer.class, Mapillary.ImageLayer.Builder.class);
      }

      // Construct using Mapillary.ImageLayer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (imagesBuilder_ == null) {
          images_ = java.util.Collections.emptyList();
        } else {
          images_ = null;
          imagesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Mapillary.internal_static_ImageLayer_descriptor;
      }

      @java.lang.Override
      public Mapillary.ImageLayer getDefaultInstanceForType() {
        return Mapillary.ImageLayer.getDefaultInstance();
      }

      @java.lang.Override
      public Mapillary.ImageLayer build() {
        Mapillary.ImageLayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Mapillary.ImageLayer buildPartial() {
        Mapillary.ImageLayer result = new Mapillary.ImageLayer(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Mapillary.ImageLayer result) {
        if (imagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            images_ = java.util.Collections.unmodifiableList(images_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.images_ = images_;
        } else {
          result.images_ = imagesBuilder_.build();
        }
      }

      private void buildPartial0(Mapillary.ImageLayer result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Mapillary.ImageLayer) {
          return mergeFrom((Mapillary.ImageLayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Mapillary.ImageLayer other) {
        if (other == Mapillary.ImageLayer.getDefaultInstance()) return this;
        if (imagesBuilder_ == null) {
          if (!other.images_.isEmpty()) {
            if (images_.isEmpty()) {
              images_ = other.images_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureImagesIsMutable();
              images_.addAll(other.images_);
            }
            onChanged();
          }
        } else {
          if (!other.images_.isEmpty()) {
            if (imagesBuilder_.isEmpty()) {
              imagesBuilder_.dispose();
              imagesBuilder_ = null;
              images_ = other.images_;
              bitField0_ = (bitField0_ & ~0x00000001);
              imagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getImagesFieldBuilder() : null;
            } else {
              imagesBuilder_.addAllMessages(other.images_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                Mapillary.ImageLayer.Image m =
                    input.readMessage(
                        Mapillary.ImageLayer.Image.parser(),
                        extensionRegistry);
                if (imagesBuilder_ == null) {
                  ensureImagesIsMutable();
                  images_.add(m);
                } else {
                  imagesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<Mapillary.ImageLayer.Image> images_ =
        java.util.Collections.emptyList();
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          images_ = new java.util.ArrayList<Mapillary.ImageLayer.Image>(images_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Mapillary.ImageLayer.Image, Mapillary.ImageLayer.Image.Builder, Mapillary.ImageLayer.ImageOrBuilder> imagesBuilder_;

      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public java.util.List<Mapillary.ImageLayer.Image> getImagesList() {
        if (imagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(images_);
        } else {
          return imagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public int getImagesCount() {
        if (imagesBuilder_ == null) {
          return images_.size();
        } else {
          return imagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Mapillary.ImageLayer.Image getImages(int index) {
        if (imagesBuilder_ == null) {
          return images_.get(index);
        } else {
          return imagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder setImages(
          int index, Mapillary.ImageLayer.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.set(index, value);
          onChanged();
        } else {
          imagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder setImages(
          int index, Mapillary.ImageLayer.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.set(index, builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder addImages(Mapillary.ImageLayer.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.add(value);
          onChanged();
        } else {
          imagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder addImages(
          int index, Mapillary.ImageLayer.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.add(index, value);
          onChanged();
        } else {
          imagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder addImages(
          Mapillary.ImageLayer.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.add(builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder addImages(
          int index, Mapillary.ImageLayer.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.add(index, builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder addAllImages(
          java.lang.Iterable<? extends Mapillary.ImageLayer.Image> values) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, images_);
          onChanged();
        } else {
          imagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder clearImages() {
        if (imagesBuilder_ == null) {
          images_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          imagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Builder removeImages(int index) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.remove(index);
          onChanged();
        } else {
          imagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Mapillary.ImageLayer.Image.Builder getImagesBuilder(
          int index) {
        return getImagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Mapillary.ImageLayer.ImageOrBuilder getImagesOrBuilder(
          int index) {
        if (imagesBuilder_ == null) {
          return images_.get(index);  } else {
          return imagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public java.util.List<? extends Mapillary.ImageLayer.ImageOrBuilder> 
           getImagesOrBuilderList() {
        if (imagesBuilder_ != null) {
          return imagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(images_);
        }
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Mapillary.ImageLayer.Image.Builder addImagesBuilder() {
        return getImagesFieldBuilder().addBuilder(
            Mapillary.ImageLayer.Image.getDefaultInstance());
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public Mapillary.ImageLayer.Image.Builder addImagesBuilder(
          int index) {
        return getImagesFieldBuilder().addBuilder(
            index, Mapillary.ImageLayer.Image.getDefaultInstance());
      }
      /**
       * <code>repeated .ImageLayer.Image images = 1;</code>
       */
      public java.util.List<Mapillary.ImageLayer.Image.Builder> 
           getImagesBuilderList() {
        return getImagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Mapillary.ImageLayer.Image, Mapillary.ImageLayer.Image.Builder, Mapillary.ImageLayer.ImageOrBuilder> 
          getImagesFieldBuilder() {
        if (imagesBuilder_ == null) {
          imagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Mapillary.ImageLayer.Image, Mapillary.ImageLayer.Image.Builder, Mapillary.ImageLayer.ImageOrBuilder>(
                  images_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          images_ = null;
        }
        return imagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ImageLayer)
    }

    // @@protoc_insertion_point(class_scope:ImageLayer)
    private static final Mapillary.ImageLayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Mapillary.ImageLayer();
    }

    public static Mapillary.ImageLayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageLayer>
        PARSER = new com.google.protobuf.AbstractParser<ImageLayer>() {
      @java.lang.Override
      public ImageLayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImageLayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageLayer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Mapillary.ImageLayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageLayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ImageLayer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageLayer_Image_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ImageLayer_Image_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017mapillary.proto\"\304\001\n\nImageLayer\022!\n\006imag" +
      "es\030\001 \003(\0132\021.ImageLayer.Image\032\222\001\n\005Image\022\023\n" +
      "\013captured_at\030\001 \001(\003\022\025\n\rcompass_angle\030\002 \001(" +
      "\005\022\022\n\ncreator_id\030\003 \001(\005\022\n\n\002id\030\004 \001(\005\022\023\n\013seq" +
      "uence_id\030\005 \001(\t\022\027\n\017organization_id\030\006 \001(\005\022" +
      "\017\n\007is_pano\030\007 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImageLayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImageLayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ImageLayer_descriptor,
        new java.lang.String[] { "Images", });
    internal_static_ImageLayer_Image_descriptor =
      internal_static_ImageLayer_descriptor.getNestedTypes().get(0);
    internal_static_ImageLayer_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ImageLayer_Image_descriptor,
        new java.lang.String[] { "CapturedAt", "CompassAngle", "CreatorId", "Id", "SequenceId", "OrganizationId", "IsPano", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
