# access tokens with different roles
@customer = {{bap-dashboard/token/YATRI/customer}}
@driver = {{bap-dashboard/token/YATRI/driver}}
@juspay_ops = {{bap-dashboard/token/YATRI/juspay_ops}}
@juspay_admin = {{bap-dashboard/token/YATRI/juspay_admin}}
@customer_service = {{bap-dashboard/token/YATRI/customer_service}}

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# @name stuckBookingsCancel

POST {{bap-dashboard-host}}/bap/YATRI/booking/cancel/allStuck
token: {{customer_service}}
content-type: application/json

{
    "bookingIds" : [
        "decf30d4-09ec-410c-a016-0da387728a25",
        "f621af6e-be7a-4e63-b18a-f85258b7bc1a"
        ]
}

###

# @name multipleBookingSync

POST {{bap-dashboard-host}}/bap/YATRI/booking/sync
token: {{customer_service}}
content-type: application/json

{
    "bookings" :
    [
        {"bookingId" : "9a6de4cd-1764-47f0-beea-30d2d1e27f22"},
        {"bookingId" : "eaf87a90-50b5-456c-a15d-c9a01cd1450a"}
    ]
}
