# access tokens with different roles
@customer = {{bap-dashboard/token/YATRI/customer}}
@driver = {{bap-dashboard/token/YATRI/driver}}
@juspay_ops = {{bap-dashboard/token/YATRI/juspay_ops}}
@juspay_admin = {{bap-dashboard/token/YATRI/juspay_admin}}
@customer_service = {{bap-dashboard/token/YATRI/customer_service}}

# @name healthcheck
GET {{bap-dashboard-host}}

###

# @name merchantUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/update
token: {{juspay_admin}}
content-type: application/json

{ "name" : "YATRI",
  "exoPhones" :
    [
      { "primaryPhone" : "+918035272984",
        "backupPhone" :  "+804710859599"
      },
      { "primaryPhone" : "+918069457996",
        "backupPhone" :  "+918069457986"
      },
      { "primaryPhone" : "+918069457991",
        "backupPhone" :  "+918069457981"
      },
      { "primaryPhone" : "+918069457992",
        "backupPhone" :  "+918069457982"
      }
    ],
  "fcmConfig" :
    { "fcmUrl" : "http://localhost:4545/someUrl/",
      "fcmServiceAccount" : "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAianAtYmVja24tZGV2IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAieHh4eHh4eHh4eHh4eHh4eHh4eCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLXh4eHh4eHh4eHh4eHh4eHh4eHgtLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiYmVja24tZmNtQGpwLWJlY2tuLWRldi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICJ4eHh4eHh4eHh4IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9iZWNrbi1mY20lNDBqcC1iZWNrbi1kZXYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0="
    },
  "gatewayUrl" : "http://localhost:8015/v1",
  "registryUrl" : "http://localhost:8020"
}

###

# @name merchanServiceUsageConfig

GET {{bap-dashboard-host}}/bap/YATRI/merchant/serviceUsageConfig
token: {{juspay_admin}}
content-type: application/json

###

# @name merchantGoogleConfigUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/serviceConfig/maps/update
token: {{juspay_admin}}
content-type: application/json

{ "serviceName" : "Google",
  "serviceConfig" : {
      "googleMapsUrl" : "http://localhost:8019/",
      "googleRoadsUrl" : "http://localhost:8019/",
      "googleKey" : "mock-google-key"
  }
}

###

# @name merchantRealGoogleConfigUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/serviceConfig/maps/update
token: {{juspay_admin}}
content-type: application/json

{ "serviceName" : "Google",
  "serviceConfig" : {
      "googleMapsUrl" : "https://maps.googleapis.com/maps/api/",
      "googleRoadsUrl" : "https://roads.googleapis.com/",
      "googleKey" : "{{google-key}}"
  }
}

###

# @name merchantOSRMConfigUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/serviceConfig/maps/update
token: {{juspay_admin}}
content-type: application/json

{ "serviceName" : "OSRM",
  "serviceConfig" : {
      "osrmUrl" : "osrmUrl",
      "radiusDeviation" : 30
  }
}

###

# @name merchantMMIConfigUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/serviceConfig/maps/update
token: {{juspay_admin}}
content-type: application/json

{ "serviceName" : "MMI",
  "serviceConfig" : {
    "mmiAuthUrl" : "mmiAuthUrl",
    "mmiAuthId" : "mmiAuthId",
    "mmiAuthSecret" : "mmiAuthSecret",
    "mmiApiKey" : "mmiApiKey",
    "mmiKeyUrl" : "mmiKeyUrl",
    "mmiNonKeyUrl" : "mmiNonKeyUrl"
  }
}

###

# @name mapsServiceUsageConfigUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/serviceUsageConfig/maps/update
token: {{juspay_admin}}
content-type: application/json

{ "getDistances" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 11,
      "osrmPercentage" : 19,
      "mmiPercentage" : 70,
      "nextBillionPercentage" : null
    },
  "getDistancesForCancelRide" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 12,
      "osrmPercentage" : 18,
      "mmiPercentage" : 70,
      "nextBillionPercentage" : null
    },
  "getRoutes" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 94,
      "osrmPercentage" : 1,
      "mmiPercentage" : 0,
      "nextBillionPercentage" : 5
    },
  "getPickupRoutes" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 11,
      "osrmPercentage" : null,
      "mmiPercentage" : 84,
      "nextBillionPercentage" : 5
    },
  "getTripRoutes" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 95,
      "osrmPercentage" : 0,
      "mmiPercentage" : 0,
      "nextBillionPercentage" : 5
    },
  "snapToRoad" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 99,
      "osrmPercentage" : 1,
      "mmiPercentage" : 0,
      "nextBillionPercentage" : null
    },
  "getPlaceName" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 90,
      "osrmPercentage" : null,
      "mmiPercentage" : 10,
      "nextBillionPercentage" : null
    },
  "getPlaceDetails" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 95,
      "osrmPercentage" : null,
      "mmiPercentage" : 5,
      "nextBillionPercentage" : null
    },
  "autoComplete" :
    { "mapsService" : "Google",
      "usePercentage" : true,
      "googlePercentage" : 95,
      "osrmPercentage" : null,
      "mmiPercentage" : 5,
      "nextBillionPercentage" : null
    }
}

###

# @name merchantMyValueFirstConfigUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/serviceConfig/sms/update
token: {{juspay_admin}}
content-type: application/json

{ "serviceName" : "MyValueFirst",
  "serviceConfig" : {
      "username" : "username",
      "password" : "password",
      "url" : "http://localhost:4343/someUrl/"
  }
}

###

# @name merchantExotelSmsConfigUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/serviceConfig/sms/update
token: {{juspay_admin}}
content-type: application/json

{ "serviceName" : "ExotelSms",
  "serviceConfig" : {
      "apiKey" : "apiKey",
      "apiToken" : "apiToken",
      "sid" : "sid",
      "url" : "url"
  }
}

###

# @name smsServiceUsageConfigUpdate

POST {{bap-dashboard-host}}/bap/YATRI/merchant/serviceUsageConfig/sms/update
token: {{juspay_admin}}
content-type: application/json

{ "smsProvidersPriorityList" : ["ExotelSms","MyValueFirst"]
}
