# access tokens with different roles
@customer_service = {{bap-dashboard/token/YATRI/customer_service}}

# @name healthcheck
GET {{bap-dashboard-host}}

###

# @name rideList

GET {{bap-dashboard-host}}/bap/YATRI/ride/list
?bookingStatus="RCOMPLETED"
# &customerPhoneNo=9999999999
# &limit=10
# &offset=0

###

# @name multipleRideSync

@rideId = {{rideList.response.body.rides[0].rideId}}

POST {{bap-dashboard-host}}/bap/YATRI/ride/sync
token: {{customer_service}}
content-type: application/json

{
    "rides" :
    [
        {"rideId" : "{{rideId}}"},
        {"rideId" : "faa88413-8e75-434d-a81e-f176232029a5"}
    ]
}
