# @name healthcheck
GET {{bap-dashboard-host}}

###

# use this creds for testing different roles:
# name = customer, driver, juspay_ops, juspay_admin, customer_service
# email = name@dashboard.com, password = name

# @name login

POST {{bap-dashboard-host}}/user/login
content-type: application/json

{
  "email" : "juspay_admin@dashboard.com",
  "password" : "juspay_admin",
  "merchantId" : "YATRI"
}

###

# @name createPerson

POST {{bap-dashboard-host}}/admin/person/create
content-type: application/json
token: {{token}}

{
  "firstName" : "unknown",
  "lastName" : "known",
  "roleId" : "508a0bac-258d-44a6-ac55-aef57ab87a76",
  "email" : "xyz@gmail.com",
  "mobileNumber" : "9876543200",
  "mobileCountryCode" : "+91",
  "passwordHash" : "juspay@adminadad"
}


###

# @name personList

@token = {{login.response.body.authToken}}

GET {{bap-dashboard-host}}/admin/person/list
  ?limit=10
  &offset=0
  # &searchString=customer
  # &searchString=7777777781
content-type: application/json
token: {{token}}

###

# @name getAccessMatrix

GET {{bap-dashboard-host}}/admin/accessMatrix
  ?limit=10
  &offset=0
content-type: application/json
token: {{token}}

###

# @name getAccessMatrixByRole

@roleId = {{getAccessMatrix.response.body.accessMatrix[0].role.id}}

GET {{bap-dashboard-host}}/admin/accessMatrix/role/{{roleId}}
content-type: application/json
token: {{token}}

###

# @name createRole

POST {{bap-dashboard-host}}/admin/roles/create
content-type: application/json
token: {{token}}

{ "name" : "DEVELOPER",
  "description" : "developer"
}

###

# @name assignRole

# assign new "DEVELOPER" role to person with name "customer"
@customerPersonId = 25e77f37-75e5-4665-8ed0-4be2af35940a

@developerRoleId = {{createRole.response.body.id}}

POST {{bap-dashboard-host}}/admin/person/{{customerPersonId}}/assignRole/{{developerRoleId}}
content-type: application/json
token: {{token}}

###

# @name assignAccessLevel

POST {{bap-dashboard-host}}/admin/roles/{{developerRoleId}}/assignAccessLevel
content-type: application/json
token: {{token}}

{ "apiEntity" : "CUSTOMERS",
  "userAccessType" : "USER_FULL_ACCESS"
}

###

# @name roleslist

GET {{bap-dashboard-host}}/admin/roles/list
  ?searchString=ADMIN
  &limit=5
  &offset=0
content-type: application/json
token: {{token}}

###

# @name assignMerchantAccess

POST {{bap-dashboard-host}}/admin/person/{{customerPersonId}}/assignMerchantAccess
content-type: application/json
token: {{token}}

{
  "merchantId" : "NAMMA_YATRI"
}

###

# @name profile

@yatriCustomerToken = {{bap-dashboard/token/YATRI/customer}}

GET {{bap-dashboard-host}}/user/profile
content-type: application/json
token: {{yatriCustomerToken}}

###

# @name resetMerchantAccess

POST {{bap-dashboard-host}}/admin/person/{{customerPersonId}}/resetMerchantAccess
content-type: application/json
token: {{token}}

{
  "merchantId" : "NAMMA_YATRI"
}

###

# @name assignMerchantAccess2

POST {{bap-dashboard-host}}/admin/person/{{customerPersonId}}/assignMerchantAccess
content-type: application/json
token: {{token}}

{
  "merchantId" : "NAMMA_YATRI"
}

###

# @name arduCustomerLogin

POST {{bap-dashboard-host}}/user/login
content-type: application/json

{
  "email" : "customer@dashboard.com",
  "password" : "customer",
  "merchantId" : "NAMMA_YATRI"
}

###

# @name getCurrentMerchant

@arduCustomerToken = {{arduCustomerLogin.response.body.authToken}}

GET {{bap-dashboard-host}}/user/getCurrentMerchant
content-type: application/json
token: {{arduCustomerToken}}

###

# check access level for new role "DEVELOPER"

# @name customerList

# we don't have NAMMA_YATRI merchant in local-testing-data, so for testing this api you should add it:

# INSERT INTO atlas_app.merchant (id, short_id, exo_phone, exo_phone_country_code, fcm_url, fcm_json_path, fcm_redis_token_key_prefix, origin_restriction, destination_restriction, registry_url, gateway_url, name) VALUES
# ('da4e23a5-3ce6-4c37-8b9b-41377c3c1a52', 'NAMMA_YATRI', '8047108594', '+91', 'http://localhost:4545/', 'dummy-fcm.json', 'da4e23a5-3ce6-4c37-8b9b-41377c3c1a52', '{Ernakulam}', '{Ernakulam,Kerala}', 'http://localhost:8020', 'http://localhost:8015/v1', 'NAMMA_YATRI');

POST {{bap-dashboard-host}}/bap/NAMMA_YATRI/customer/111/update
content-type: application/json
token: {{arduCustomerToken}}

"request"

###

# @name logout

# this endpoint should remove only one token for YATRI merchant

POST {{bap-dashboard-host}}/user/logout
content-type: application/json
token: {{yatriCustomerToken}}

###

# @name logoutAllMerchants

# this endpoint should remove all tokens for customer

POST {{bap-dashboard-host}}/user/logoutAllMerchants
content-type: application/json
token: {{arduCustomerToken}}

###

# @name listTransactions

GET {{bap-dashboard-host}}/listTransactions
  ?limit=10
  &offset=0
  &endpoint=RIDER_MANAGEMENT/BOOKING/POST_BOOKING_CANCEL_ALL_STUCK
content-type: application/json
token: {{arduCustomerToken}}
