# access tokens with different roles
@customer = {{bap-dashboard/token/YATRI/customer}}
@driver = {{bap-dashboard/token/YATRI/driver}}
@juspay_ops = {{bap-dashboard/token/YATRI/juspay_ops}}
@juspay_admin = {{bap-dashboard/token/YATRI/juspay_admin}}
@customer_service = {{bap-dashboard/token/YATRI/customer_service}}

# @name healthcheck
GET {{bap-dashboard-host}}

###

# @name PersonFlowStatusAPI

@customerId = 00000000-0000-0000-0000-000000000001

GET {{bap-dashboard-host}}/bap/YATRI/rideBooking/frontend/flowStatus/{{customerId}}
content-type: application/json
token: {{juspay_admin}}
