# access tokens with different roles
@customer = {{bap-dashboard/token/YATRI/customer}}
@driver = {{bap-dashboard/token/YATRI/driver}}
@juspay_ops = {{bap-dashboard/token/YATRI/juspay_ops}}
@juspay_admin = {{bap-dashboard/token/YATRI/juspay_admin}}
@customer_service = {{bap-dashboard/token/YATRI/customer_service}}

# @name healthcheck
GET {{bap-dashboard-host}}

###

# @name customerList

GET {{bap-dashboard-host}}/bap/YATRI/customer/list
  ?limit=10
  &offset=0
content-type: application/json
token: {{customer_service}}

###

# You have no access to this operation.
# @name updateCustomer

POST {{bap-dashboard-host}}/bap/NAMMA_YATRI/customer/111/update
content-type: application/json
token: {{juspay_ops}}

"request"
###

# @name updateCustomer

curl -XGET http://localhost:4000/posts?author=Poli&title=Blood
