
# @name updateDefaultEmergencyNumbers
POST {{app-host}}/profile/defaultEmergencyNumbers
content-type: application/json
token: {{app-token}}

{
  "defaultEmergencyNumbers" : [{
      "name": "Bob",
      "mobileCountryCode": "+91",
      "mobileNumber": "8005553535"
  }]
}

###

# @name getDefaultEmergencyNumbers
GET {{app-host}}/profile/defaultEmergencyNumbers
content-type: application/json
token: {{app-token}}

###