{-
 Copyright 2022-23, Juspay India Pvt Ltd

 This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License

 as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program

 is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY

 or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details. You should have received a copy of

 the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
-}

module Domain.Types.FareBreakupTitle
  ( FareBreakupTitle (..),
    toDomainFBTitle,
    toBecknQBTitle,
  )
where

import qualified BecknV2.OnDemand.Enums as Spec
import Data.Aeson
import EulerHS.Prelude (Hashable)
import Kernel.Prelude

data FareBreakupTitle
  = BASE_FARE
  | DISTANCE_FARE
  | CANCELLATION_CHARGES
  | TOLL_CHARGES
  | CONGESTION_CHARGE
  | SERVICE_CHARGE
  | DEAD_KILOMETER_FARE
  | DRIVER_SELECTED_FARE
  | CUSTOMER_SELECTED_FARE
  | TOTAL_FARE
  | WAITING_OR_PICKUP_CHARGES
  | PARKING_CHARGE
  | EXTRA_TIME_FARE
  | NIGHT_SHIFT_CHARGE
  | FIXED_GOVERNMENT_RATE
  | SGST
  | CGST
  | PLATFORM_FEE
  | TIME_BASED_FARE
  | DIST_BASED_FARE
  | EXTRA_DISTANCE_FARE
  | RIDE_DURATION_FARE
  | INSURANCE_CHARGES
  | CARD_CHARGES_ON_FARE
  | CARD_CHARGES_FIXED
  deriving (Show, Read, Eq, Generic, ToJSON, FromJSON, Hashable)

toDomainFBTitle :: Spec.QuoteBreakupTitle -> FareBreakupTitle
toDomainFBTitle = \case
  Spec.BASE_FARE -> BASE_FARE
  Spec.DISTANCE_FARE -> DISTANCE_FARE
  Spec.CANCELLATION_CHARGES -> CANCELLATION_CHARGES
  Spec.TOLL_CHARGES -> TOLL_CHARGES
  Spec.CONGESTION_CHARGE -> CONGESTION_CHARGE
  Spec.SERVICE_CHARGE -> SERVICE_CHARGE
  Spec.DEAD_KILOMETER_FARE -> DEAD_KILOMETER_FARE
  Spec.DRIVER_SELECTED_FARE -> DRIVER_SELECTED_FARE
  Spec.CUSTOMER_SELECTED_FARE -> CUSTOMER_SELECTED_FARE
  Spec.TOTAL_FARE -> TOTAL_FARE
  Spec.WAITING_OR_PICKUP_CHARGES -> WAITING_OR_PICKUP_CHARGES
  Spec.PARKING_CHARGE -> PARKING_CHARGE
  Spec.EXTRA_TIME_FARE -> EXTRA_TIME_FARE
  Spec.NIGHT_SHIFT_CHARGE -> NIGHT_SHIFT_CHARGE
  Spec.FIXED_GOVERNMENT_RATE -> FIXED_GOVERNMENT_RATE
  Spec.SGST -> SGST
  Spec.CGST -> CGST
  Spec.PLATFORM_FEE -> PLATFORM_FEE
  Spec.TIME_BASED_FARE -> TIME_BASED_FARE
  Spec.DIST_BASED_FARE -> DIST_BASED_FARE
  Spec.EXTRA_DISTANCE_FARE -> EXTRA_DISTANCE_FARE
  Spec.RIDE_DURATION_FARE -> RIDE_DURATION_FARE
  Spec.INSURANCE_CHARGES -> INSURANCE_CHARGES
  Spec.CARD_CHARGES_ON_FARE -> CARD_CHARGES_ON_FARE
  Spec.CARD_CHARGES_FIXED -> CARD_CHARGES_FIXED

toBecknQBTitle :: FareBreakupTitle -> Spec.QuoteBreakupTitle
toBecknQBTitle = \case
  BASE_FARE -> Spec.BASE_FARE
  DISTANCE_FARE -> Spec.DISTANCE_FARE
  CANCELLATION_CHARGES -> Spec.CANCELLATION_CHARGES
  TOLL_CHARGES -> Spec.TOLL_CHARGES
  CONGESTION_CHARGE -> Spec.CONGESTION_CHARGE
  SERVICE_CHARGE -> Spec.SERVICE_CHARGE
  DEAD_KILOMETER_FARE -> Spec.DEAD_KILOMETER_FARE
  DRIVER_SELECTED_FARE -> Spec.DRIVER_SELECTED_FARE
  CUSTOMER_SELECTED_FARE -> Spec.CUSTOMER_SELECTED_FARE
  TOTAL_FARE -> Spec.TOTAL_FARE
  WAITING_OR_PICKUP_CHARGES -> Spec.WAITING_OR_PICKUP_CHARGES
  PARKING_CHARGE -> Spec.PARKING_CHARGE
  EXTRA_TIME_FARE -> Spec.EXTRA_TIME_FARE
  NIGHT_SHIFT_CHARGE -> Spec.NIGHT_SHIFT_CHARGE
  FIXED_GOVERNMENT_RATE -> Spec.FIXED_GOVERNMENT_RATE
  SGST -> Spec.SGST
  CGST -> Spec.CGST
  PLATFORM_FEE -> Spec.PLATFORM_FEE
  TIME_BASED_FARE -> Spec.TIME_BASED_FARE
  DIST_BASED_FARE -> Spec.DIST_BASED_FARE
  EXTRA_DISTANCE_FARE -> Spec.EXTRA_DISTANCE_FARE
  RIDE_DURATION_FARE -> Spec.RIDE_DURATION_FARE
  INSURANCE_CHARGES -> Spec.INSURANCE_CHARGES
  CARD_CHARGES_ON_FARE -> Spec.CARD_CHARGES_ON_FARE
  CARD_CHARGES_FIXED -> Spec.CARD_CHARGES_FIXED
