#  Set `disableSignatureAuth = True` in both:
# /dhall-configs/dev/beckn-gateway.dhall
# /dhall-configs/dev/fmd-wrapper.dhall
# 
# Run apps 
#
# Use https://beeceptor.com/console/fmd-test for callback inspection

### @name healh-checking
GET {{fmd-wrapper/url}}

### @name beeceptor-test
POST {{fmd-bap/beeceptor/url}}
content-type: application/json

{
  "data": "Hello Beeceptor"
}
