# @name search

@transaction_id = 64422824-5a93-11ec-8001-7085c22b52e7
@action = search
POST {{gw/url}}/{{action}}
content-type: application/json
Authorization: Signature keyId="{{fmd-bap/subscriber-id}}|{{fmd-bap/unique-key}}|ed25519",algorithm="ed25519",created=1639662887,expires=1639663487,headers="(created) (expires) digest",signature="fake"

{
  "context": {
    "country": "IND",
    "domain": "{{fmd/domain}}",
    "transaction_id": "{{transaction_id}}",
    "action": "{{action}}",
    "message_id": "{{transaction_id}}",
    "city": "Bangalore",
    "bap_uri": "{{fmd-bap/beeceptor/url}}",
    "timestamp": "2021-12-11T15:02:43.040019543Z",
    "core_version": "0.9.3",
    "bap_id": "{{fmd-bap/beeceptor/url}}"
  },
  "message": {
    "intent": {
      "fulfillment": {
        "start": {
          "location": {
            "gps": "12.9729391, 77.6294794"
          }
        },
        "end": {
          "location": {
            "gps": "12.9354504, 77.6146828"
          }
        }
      }
    }
  }
}
