ALTER TABLE atlas_driver_offer_bpp.transporter_config ADD COLUMN ride_travelled_dist_threshold_when_pickup_or_dest_is_same bigint;
UPDATE atlas_driver_offer_bpp.transporter_config SET ride_travelled_dist_threshold_when_pickup_or_dest_is_same = 700;
ALTER TABLE atlas_driver_offer_bpp.transporter_config RENAME COLUMN ride_travelled_distance_threshold TO ride_travelled_dist_threshold_when_pickup_and_dest_is_diff;
UPDATE atlas_driver_offer_bpp.transporter_config SET ride_travelled_dist_threshold_when_pickup_and_dest_is_diff = 1200;
