#!/bin/bash

for MODULE in $(ls Backend/dev/migrations); do
  MIGRATION_DIR="Backend/dev/migrations/${MODULE}"
  if [ $(ls ${MIGRATION_DIR} | cut -c-4 | uniq | wc -l) != $(ls ${MIGRATION_DIR} | wc -l) ]; then
    echo "There are overlapping migration indices in ${MODULE}"
    FAIL="true"
  fi
done

if [ -n "$FAIL" ]; then
  exit 1
else
  exit 0
fi
