module Screens.Handlers (module UI) where

import Screens.AboutUsScreen.Handler (aboutUsScreen) as UI
import Screens.AccountSetUpScreen.Handler (accountSetUpScreen) as UI
import Screens.AddNewAddressScreen.Handler (addNewAddressScreen) as UI
import Screens.AppUpdatePopUp.Handler (handleAppUpdatePopUp) as UI
import Screens.ChooseLanguageScreen.Handler (chooseLanguageScreen) as UI
import Screens.ContactUsScreen.Handler (contactUsScreen) as UI
import Screens.EnterMobileNumberScreen.Handler (enterMobileNumberScreen) as UI
import Screens.HelpAndSupportScreen.Handler (helpAndSupportScreen) as UI
import Screens.HomeScreen.Handler (homeScreen) as UI
import Screens.InvoiceScreen.Handler (invoiceScreen) as UI
import Screens.MyProfileScreen.Handler (myProfileScreen) as UI
import Screens.MyRidesScreen.Handler (myRidesScreen) as UI
import Screens.PermissionScreen.Handler (permissionScreen) as UI
import Screens.ReferralScreen.Handler (referralScreen) as UI
import Screens.SavedLocationScreen.Handler (savedLocationScreen) as UI
import Screens.SelectLanguageScreen.Handler (selectLanguageScreen) as UI
import Screens.SplashScreen.Handler (splashScreen) as UI
import Screens.TripDetailsScreen.Handler (tripDetailsScreen) as UI
import Screens.SuccessScreen.Handler (successScreen) as UI
