# access tokens with different roles
@customer = {{bpp-dashboard/token/YATRI_PARTNER/customer}}
@driver = {{bpp-dashboard/token/YATRI_PARTNER/driver}}
@juspay_ops = {{bpp-dashboard/token/YATRI_PARTNER/juspay_ops}}
@juspay_admin = {{bpp-dashboard/token/YATRI_PARTNER/juspay_admin}}
@customer_service = {{bpp-dashboard/token/YATRI_PARTNER/customer_service}}

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# @name driverList

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/list
?verified=true
&enabled=true
&limit=10
&offset=0
# &phone=6666666666
token: {{customer_service}}

###

# @name driverActivity

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/activity
token: {{customer_service}}

###

# @name enableDriver

@driverId1 = 001b93df-4f7c-440f-bada-4d46c396d7d0
@driverId2 = 002b93df-4f7c-440f-bada-4d46c396d7d0
@driverId3 = driver-not-found-0000000000000000000

@driverId4 = 6bc4bc84-2c43-425d-8853-22f47driver2

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/enable
token: {{juspay_ops}}
content-type: application/json

###
# @name disableDriver

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/disable
token: {{juspay_ops}}
content-type: application/json

###

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/location
token: {{customer_service}}
content-type: application/json

{
    "driverIds": ["{{driverId1}}", "{{driverId2}}", "{{driverId3}}"]
}

###

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/info?mobileNumber=6666666666
token: {{customer_service}}
content-type: application/json

###

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/info?vehicleNumber=3211
token: {{customer_service}}
content-type: application/json

###

DELETE {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId2}}/permanentlyDelete
token: {{juspay_admin}}
content-type: application/json

###

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId4}}/unlinkVehicle
 token: {{juspay_admin}}
 content-type: application/json

###

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/updatePhoneNumber
token: {{juspay_admin}}
content-type: application/json

{
    "newPhoneNumber": "7777777777",
    "newCountryCode": "+91"
}

###

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/driver/{{driverId1}}/addVehicle
token: {{juspay_admin}}
content-type: application/json

{
    "variant" : "SEDAN",
    "registrationNo" : "777IN",
    "vehicleClass" : "vehicleClass",
    "capacity" : 5,
    "colour" : "Red",
    "energyType" : "PETROL",
    "model" : "VAZ",
    "make" : "make",
    "driverName" : "Krishna"
}
