# access tokens with different roles
@customer = {{bpp-dashboard/token/YATRI_PARTNER/customer}}
@driver = {{bpp-dashboard/token/YATRI_PARTNER/driver}}
@juspay_ops = {{bpp-dashboard/token/YATRI_PARTNER/juspay_ops}}
@juspay_admin = {{bpp-dashboard/token/YATRI_PARTNER/juspay_admin}}
@customer_service = {{bpp-dashboard/token/YATRI_PARTNER/customer_service}}

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# @name rideList

# FIXME ?bookingStatus=COMPLETED
GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/ride/list
?bookingStatus="COMPLETED"
# &rideShortId=b5Rw09fZSe
&customerPhoneNo=9999999999
&driverPhoneNo=6666666666
&limit=10
&offset=0
token: {{customer_service}}

###

# @name rideStart

@ride1Id = 2b0910b7-acef-454f-8004-ef4b098e4366

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/ride/{{ride1Id}}/start
token: {{customer_service}}
content-type: application/json

{
    "point": {
            "lon": 76.308364,
            "lat": 10.025263
    }
}

###

# @name rideEnd

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/ride/{{ride1Id}}/end
token: {{customer_service}}
content-type: application/json

{
    "point": {
            "lon": 76.318364,
            "lat": 10.025263
    }
}

###

# @name rideCancel

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/ride/{{ride1Id}}/cancel
content-type: application/json
token: {{customer_service}}

{
  "reasonCode": "OTHER",
  "additionalInfo": "driver is too skinny"
}

###

# @name rideInfo

@rideId = {{rideList.response.body.rides[0].rideId}}

GET {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/ride/{{rideId}}/info
token: {{customer_service}}

###

# @name rideSync

@rideId = 8f76beb3-bb3e-4c20-affc-2fd19650de70

POST {{bpp-dashboard-host}}/bpp/beckn-transport/YATRI_PARTNER/ride/{{rideId}}/sync
token: {{customer_service}}
