imports:
  Text: Data.Text
  Value: Data.Aeson
  Area: Lib.Types.SpecialLocation
  MerchantOperatingCity: Domain.Types.MerchantOperatingCity
  Merchant: Domain.Types.Merchant

PayoutSplitConfig:
  tableName: payout_split_config

  fields:
    id : Id PayoutSplitConfig
    vendorId : Text
    bankDetails : Value
    area: Maybe Area

