#!/bin/bash

# Adding hooks to prepare commit message.
# This hook triggers Jira input modules.
# Helps in maintaining code compatblity.

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

if [[ $BRANCH_NAME != *"no branch"* ]]
then
  exec < /dev/tty && ./../node_modules/.bin/git-cz --hook || true
fi