{-# LANGUAGE ApplicativeDo #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-orphans #-}

module Domain.Types.Extra.MerchantMessage where

import qualified Data.Aeson as A
import Data.Default.Class
import Data.OpenApi (ToSchema (..))
import qualified Data.Text as T
import qualified Database.Beam as B
import Database.Beam.Backend
import Database.Beam.Postgres (Postgres)
import Database.PostgreSQL.Simple.FromField (FromField (..))
import Kernel.Prelude

data MerchantMessageDefaultDataJSON = MerchantMessageDefaultDataJSON
  { var1 :: Maybe Text,
    var2 :: Maybe Text,
    var3 :: Maybe Text
  }
  deriving (Generic, ToJSON, FromJSON, Show, ToSchema, Eq)

instance Default MerchantMessageDefaultDataJSON where
  def =
    MerchantMessageDefaultDataJSON
      { var1 = Nothing,
        var2 = Nothing,
        var3 = Nothing
      }

data MessageKey
  = SEND_OTP
  | WELCOME_TO_PLATFORM
  | ALTERNATE_NUMBER_OTP
  | ONBOARD_SUPPORT_SMS_TEMPLATE
  | END_RIDE_MESSAGE
  | ONBOARDING_YATRI_MESSAGE
  | BOOKING_MESSAGE
  | CASH_COLLECTED_MESSAGE
  | SEND_PAYMENT_LINK
  | WHATSAPP_CLEAR_DUES_CALL_MISSED_MESSAGE
  | WHATSAPP_CLEAR_DUES_MESSAGE
  | WHATSAPP_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS
  | WHATSAPP_SETUP_AUTOPAY_MESSAGE
  | WHATSAPP_SWITCH_PLAN_MESSAGE
  | WHATSAPP_HOW_IT_WORKS_MESSAGE
  | SMS_CLEAR_DUES_CALL_MISSED_MESSAGE
  | SMS_CLEAR_DUES_MESSAGE
  | SMS_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS
  | SMS_SETUP_AUTOPAY_MESSAGE
  | SMS_SWITCH_PLAN_MESSAGE
  | SMS_HOW_IT_WORKS_MESSAGE
  | WHATSAPP_SETUP_MANDATE_MESSAGE
  | WHATSAPP_VEHICLE_UNLINKED_MESSAGE
  | WHATSAPP_VEHICLE_LINKED_MESSAGE
  | YATRI_RENTAL_PAUSE
  | YATRI_RENTAL_RESUME
  | WHATSAPP_SEND_MANUAL_PAYMENT_LINK
  | SMS_TO_GO_ONLINE_IN_SCHEDULED_RIDE
  | FLEET_JOINING_MESSAGE
  | FLEET_JOIN_AND_DOWNLOAD_APP_MESSAGE
  | WHATSAPP_SEND_ONE_TIME_SECURITY_PAYMENT_LINK
  | WHATSAPP_MANUAL_PAYMENT_LINK
  | FLEET_CONSENT_DEEPLINK_MESSAGE
  | SEND_FARE_RECEIPT_MESSAGE
  | WAIVE_OFF_ENABLED_FOR_SUBSCRIPTION
  | OPERATOR_CONSENT_DEEPLINK_MESSAGE
  | OPERATOR_JOINING_MESSAGE
  | OPERATOR_JOIN_AND_DOWNLOAD_APP_MESSAGE
  | FLEET_LINK_SUCCESS_MESSAGE
  | FLEET_UNLINK_SUCCESS_MESSAGE
  | DOCUMENT_INVALID
  | DRIVER_PAYOUT
  | SEND_SOS_ALERT
  | POST_RIDE_SOS
  | DOCUMENT_EXPIRY_REMINDER_SMS
  | VEHICLE_INSPECTION_SMS
  | DRIVER_INSPECTION_SMS
  | TRAINING_VIDEO_SMS
  | FLEET_COMMUNICATION_SMS
  | FLEET_COMMUNICATION_WHATSAPP
  | SEND_TOTP
  | DOCUMENT_VALID
  | DRIVER_ONBOARDING_DEEPLINK_MESSAGE
  | FLEET_CONSENT_AND_ONBOARDING_DEEPLINK_MESSAGE
  | ONBOARDING_APPROVED
  | VEHICLE_APPROVED
  | CustomMessageKey Text
  deriving (Eq, Ord, Generic)

knownMessageKeys :: [MessageKey]
knownMessageKeys =
  [ SEND_OTP,
    WELCOME_TO_PLATFORM,
    ALTERNATE_NUMBER_OTP,
    ONBOARD_SUPPORT_SMS_TEMPLATE,
    END_RIDE_MESSAGE,
    ONBOARDING_YATRI_MESSAGE,
    BOOKING_MESSAGE,
    CASH_COLLECTED_MESSAGE,
    SEND_PAYMENT_LINK,
    WHATSAPP_CLEAR_DUES_CALL_MISSED_MESSAGE,
    WHATSAPP_CLEAR_DUES_MESSAGE,
    WHATSAPP_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS,
    WHATSAPP_SETUP_AUTOPAY_MESSAGE,
    WHATSAPP_SWITCH_PLAN_MESSAGE,
    WHATSAPP_HOW_IT_WORKS_MESSAGE,
    SMS_CLEAR_DUES_CALL_MISSED_MESSAGE,
    SMS_CLEAR_DUES_MESSAGE,
    SMS_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS,
    SMS_SETUP_AUTOPAY_MESSAGE,
    SMS_SWITCH_PLAN_MESSAGE,
    SMS_HOW_IT_WORKS_MESSAGE,
    WHATSAPP_SETUP_MANDATE_MESSAGE,
    WHATSAPP_VEHICLE_UNLINKED_MESSAGE,
    WHATSAPP_VEHICLE_LINKED_MESSAGE,
    YATRI_RENTAL_PAUSE,
    YATRI_RENTAL_RESUME,
    WHATSAPP_SEND_MANUAL_PAYMENT_LINK,
    SMS_TO_GO_ONLINE_IN_SCHEDULED_RIDE,
    FLEET_JOINING_MESSAGE,
    FLEET_JOIN_AND_DOWNLOAD_APP_MESSAGE,
    WHATSAPP_SEND_ONE_TIME_SECURITY_PAYMENT_LINK,
    WHATSAPP_MANUAL_PAYMENT_LINK,
    FLEET_CONSENT_DEEPLINK_MESSAGE,
    SEND_FARE_RECEIPT_MESSAGE,
    WAIVE_OFF_ENABLED_FOR_SUBSCRIPTION,
    OPERATOR_CONSENT_DEEPLINK_MESSAGE,
    OPERATOR_JOINING_MESSAGE,
    OPERATOR_JOIN_AND_DOWNLOAD_APP_MESSAGE,
    FLEET_LINK_SUCCESS_MESSAGE,
    FLEET_UNLINK_SUCCESS_MESSAGE,
    DOCUMENT_INVALID,
    DRIVER_PAYOUT,
    SEND_SOS_ALERT,
    POST_RIDE_SOS,
    DOCUMENT_EXPIRY_REMINDER_SMS,
    VEHICLE_INSPECTION_SMS,
    DRIVER_INSPECTION_SMS,
    TRAINING_VIDEO_SMS,
    FLEET_COMMUNICATION_SMS,
    FLEET_COMMUNICATION_WHATSAPP,
    SEND_TOTP,
    DOCUMENT_VALID,
    DRIVER_ONBOARDING_DEEPLINK_MESSAGE,
    FLEET_CONSENT_AND_ONBOARDING_DEEPLINK_MESSAGE,
    ONBOARDING_APPROVED,
    VEHICLE_APPROVED
  ]

messageKeyToText :: MessageKey -> Text
messageKeyToText = \case
  SEND_OTP -> "SEND_OTP"
  WELCOME_TO_PLATFORM -> "WELCOME_TO_PLATFORM"
  ALTERNATE_NUMBER_OTP -> "ALTERNATE_NUMBER_OTP"
  ONBOARD_SUPPORT_SMS_TEMPLATE -> "ONBOARD_SUPPORT_SMS_TEMPLATE"
  END_RIDE_MESSAGE -> "END_RIDE_MESSAGE"
  ONBOARDING_YATRI_MESSAGE -> "ONBOARDING_YATRI_MESSAGE"
  BOOKING_MESSAGE -> "BOOKING_MESSAGE"
  CASH_COLLECTED_MESSAGE -> "CASH_COLLECTED_MESSAGE"
  SEND_PAYMENT_LINK -> "SEND_PAYMENT_LINK"
  WHATSAPP_CLEAR_DUES_CALL_MISSED_MESSAGE -> "WHATSAPP_CLEAR_DUES_CALL_MISSED_MESSAGE"
  WHATSAPP_CLEAR_DUES_MESSAGE -> "WHATSAPP_CLEAR_DUES_MESSAGE"
  WHATSAPP_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS -> "WHATSAPP_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS"
  WHATSAPP_SETUP_AUTOPAY_MESSAGE -> "WHATSAPP_SETUP_AUTOPAY_MESSAGE"
  WHATSAPP_SWITCH_PLAN_MESSAGE -> "WHATSAPP_SWITCH_PLAN_MESSAGE"
  WHATSAPP_HOW_IT_WORKS_MESSAGE -> "WHATSAPP_HOW_IT_WORKS_MESSAGE"
  SMS_CLEAR_DUES_CALL_MISSED_MESSAGE -> "SMS_CLEAR_DUES_CALL_MISSED_MESSAGE"
  SMS_CLEAR_DUES_MESSAGE -> "SMS_CLEAR_DUES_MESSAGE"
  SMS_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS -> "SMS_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS"
  SMS_SETUP_AUTOPAY_MESSAGE -> "SMS_SETUP_AUTOPAY_MESSAGE"
  SMS_SWITCH_PLAN_MESSAGE -> "SMS_SWITCH_PLAN_MESSAGE"
  SMS_HOW_IT_WORKS_MESSAGE -> "SMS_HOW_IT_WORKS_MESSAGE"
  WHATSAPP_SETUP_MANDATE_MESSAGE -> "WHATSAPP_SETUP_MANDATE_MESSAGE"
  WHATSAPP_VEHICLE_UNLINKED_MESSAGE -> "WHATSAPP_VEHICLE_UNLINKED_MESSAGE"
  WHATSAPP_VEHICLE_LINKED_MESSAGE -> "WHATSAPP_VEHICLE_LINKED_MESSAGE"
  YATRI_RENTAL_PAUSE -> "YATRI_RENTAL_PAUSE"
  YATRI_RENTAL_RESUME -> "YATRI_RENTAL_RESUME"
  WHATSAPP_SEND_MANUAL_PAYMENT_LINK -> "WHATSAPP_SEND_MANUAL_PAYMENT_LINK"
  SMS_TO_GO_ONLINE_IN_SCHEDULED_RIDE -> "SMS_TO_GO_ONLINE_IN_SCHEDULED_RIDE"
  FLEET_JOINING_MESSAGE -> "FLEET_JOINING_MESSAGE"
  FLEET_JOIN_AND_DOWNLOAD_APP_MESSAGE -> "FLEET_JOIN_AND_DOWNLOAD_APP_MESSAGE"
  WHATSAPP_SEND_ONE_TIME_SECURITY_PAYMENT_LINK -> "WHATSAPP_SEND_ONE_TIME_SECURITY_PAYMENT_LINK"
  WHATSAPP_MANUAL_PAYMENT_LINK -> "WHATSAPP_MANUAL_PAYMENT_LINK"
  FLEET_CONSENT_DEEPLINK_MESSAGE -> "FLEET_CONSENT_DEEPLINK_MESSAGE"
  SEND_FARE_RECEIPT_MESSAGE -> "SEND_FARE_RECEIPT_MESSAGE"
  WAIVE_OFF_ENABLED_FOR_SUBSCRIPTION -> "WAIVE_OFF_ENABLED_FOR_SUBSCRIPTION"
  OPERATOR_CONSENT_DEEPLINK_MESSAGE -> "OPERATOR_CONSENT_DEEPLINK_MESSAGE"
  OPERATOR_JOINING_MESSAGE -> "OPERATOR_JOINING_MESSAGE"
  OPERATOR_JOIN_AND_DOWNLOAD_APP_MESSAGE -> "OPERATOR_JOIN_AND_DOWNLOAD_APP_MESSAGE"
  FLEET_LINK_SUCCESS_MESSAGE -> "FLEET_LINK_SUCCESS_MESSAGE"
  FLEET_UNLINK_SUCCESS_MESSAGE -> "FLEET_UNLINK_SUCCESS_MESSAGE"
  DOCUMENT_INVALID -> "DOCUMENT_INVALID"
  DRIVER_PAYOUT -> "DRIVER_PAYOUT"
  SEND_SOS_ALERT -> "SEND_SOS_ALERT"
  POST_RIDE_SOS -> "POST_RIDE_SOS"
  DOCUMENT_EXPIRY_REMINDER_SMS -> "DOCUMENT_EXPIRY_REMINDER_SMS"
  VEHICLE_INSPECTION_SMS -> "VEHICLE_INSPECTION_SMS"
  DRIVER_INSPECTION_SMS -> "DRIVER_INSPECTION_SMS"
  TRAINING_VIDEO_SMS -> "TRAINING_VIDEO_SMS"
  FLEET_COMMUNICATION_SMS -> "FLEET_COMMUNICATION_SMS"
  FLEET_COMMUNICATION_WHATSAPP -> "FLEET_COMMUNICATION_WHATSAPP"
  SEND_TOTP -> "SEND_TOTP"
  DOCUMENT_VALID -> "DOCUMENT_VALID"
  DRIVER_ONBOARDING_DEEPLINK_MESSAGE -> "DRIVER_ONBOARDING_DEEPLINK_MESSAGE"
  FLEET_CONSENT_AND_ONBOARDING_DEEPLINK_MESSAGE -> "FLEET_CONSENT_AND_ONBOARDING_DEEPLINK_MESSAGE"
  ONBOARDING_APPROVED -> "ONBOARDING_APPROVED"
  VEHICLE_APPROVED -> "VEHICLE_APPROVED"
  CustomMessageKey t -> t

messageKeyFromText :: Text -> MessageKey
messageKeyFromText = \case
  "SEND_OTP" -> SEND_OTP
  "WELCOME_TO_PLATFORM" -> WELCOME_TO_PLATFORM
  "ALTERNATE_NUMBER_OTP" -> ALTERNATE_NUMBER_OTP
  "ONBOARD_SUPPORT_SMS_TEMPLATE" -> ONBOARD_SUPPORT_SMS_TEMPLATE
  "END_RIDE_MESSAGE" -> END_RIDE_MESSAGE
  "ONBOARDING_YATRI_MESSAGE" -> ONBOARDING_YATRI_MESSAGE
  "BOOKING_MESSAGE" -> BOOKING_MESSAGE
  "CASH_COLLECTED_MESSAGE" -> CASH_COLLECTED_MESSAGE
  "SEND_PAYMENT_LINK" -> SEND_PAYMENT_LINK
  "WHATSAPP_CLEAR_DUES_CALL_MISSED_MESSAGE" -> WHATSAPP_CLEAR_DUES_CALL_MISSED_MESSAGE
  "WHATSAPP_CLEAR_DUES_MESSAGE" -> WHATSAPP_CLEAR_DUES_MESSAGE
  "WHATSAPP_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS" -> WHATSAPP_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS
  "WHATSAPP_SETUP_AUTOPAY_MESSAGE" -> WHATSAPP_SETUP_AUTOPAY_MESSAGE
  "WHATSAPP_SWITCH_PLAN_MESSAGE" -> WHATSAPP_SWITCH_PLAN_MESSAGE
  "WHATSAPP_HOW_IT_WORKS_MESSAGE" -> WHATSAPP_HOW_IT_WORKS_MESSAGE
  "SMS_CLEAR_DUES_CALL_MISSED_MESSAGE" -> SMS_CLEAR_DUES_CALL_MISSED_MESSAGE
  "SMS_CLEAR_DUES_MESSAGE" -> SMS_CLEAR_DUES_MESSAGE
  "SMS_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS" -> SMS_CLEAR_DUES_MESSAGE_TO_BLOCKED_DRIVERS
  "SMS_SETUP_AUTOPAY_MESSAGE" -> SMS_SETUP_AUTOPAY_MESSAGE
  "SMS_SWITCH_PLAN_MESSAGE" -> SMS_SWITCH_PLAN_MESSAGE
  "SMS_HOW_IT_WORKS_MESSAGE" -> SMS_HOW_IT_WORKS_MESSAGE
  "WHATSAPP_SETUP_MANDATE_MESSAGE" -> WHATSAPP_SETUP_MANDATE_MESSAGE
  "WHATSAPP_VEHICLE_UNLINKED_MESSAGE" -> WHATSAPP_VEHICLE_UNLINKED_MESSAGE
  "WHATSAPP_VEHICLE_LINKED_MESSAGE" -> WHATSAPP_VEHICLE_LINKED_MESSAGE
  "YATRI_RENTAL_PAUSE" -> YATRI_RENTAL_PAUSE
  "YATRI_RENTAL_RESUME" -> YATRI_RENTAL_RESUME
  "WHATSAPP_SEND_MANUAL_PAYMENT_LINK" -> WHATSAPP_SEND_MANUAL_PAYMENT_LINK
  "SMS_TO_GO_ONLINE_IN_SCHEDULED_RIDE" -> SMS_TO_GO_ONLINE_IN_SCHEDULED_RIDE
  "FLEET_JOINING_MESSAGE" -> FLEET_JOINING_MESSAGE
  "FLEET_JOIN_AND_DOWNLOAD_APP_MESSAGE" -> FLEET_JOIN_AND_DOWNLOAD_APP_MESSAGE
  "WHATSAPP_SEND_ONE_TIME_SECURITY_PAYMENT_LINK" -> WHATSAPP_SEND_ONE_TIME_SECURITY_PAYMENT_LINK
  "WHATSAPP_MANUAL_PAYMENT_LINK" -> WHATSAPP_MANUAL_PAYMENT_LINK
  "FLEET_CONSENT_DEEPLINK_MESSAGE" -> FLEET_CONSENT_DEEPLINK_MESSAGE
  "SEND_FARE_RECEIPT_MESSAGE" -> SEND_FARE_RECEIPT_MESSAGE
  "WAIVE_OFF_ENABLED_FOR_SUBSCRIPTION" -> WAIVE_OFF_ENABLED_FOR_SUBSCRIPTION
  "OPERATOR_CONSENT_DEEPLINK_MESSAGE" -> OPERATOR_CONSENT_DEEPLINK_MESSAGE
  "OPERATOR_JOINING_MESSAGE" -> OPERATOR_JOINING_MESSAGE
  "OPERATOR_JOIN_AND_DOWNLOAD_APP_MESSAGE" -> OPERATOR_JOIN_AND_DOWNLOAD_APP_MESSAGE
  "FLEET_LINK_SUCCESS_MESSAGE" -> FLEET_LINK_SUCCESS_MESSAGE
  "FLEET_UNLINK_SUCCESS_MESSAGE" -> FLEET_UNLINK_SUCCESS_MESSAGE
  "DOCUMENT_INVALID" -> DOCUMENT_INVALID
  "DRIVER_PAYOUT" -> DRIVER_PAYOUT
  "SEND_SOS_ALERT" -> SEND_SOS_ALERT
  "POST_RIDE_SOS" -> POST_RIDE_SOS
  "DOCUMENT_EXPIRY_REMINDER_SMS" -> DOCUMENT_EXPIRY_REMINDER_SMS
  "VEHICLE_INSPECTION_SMS" -> VEHICLE_INSPECTION_SMS
  "DRIVER_INSPECTION_SMS" -> DRIVER_INSPECTION_SMS
  "TRAINING_VIDEO_SMS" -> TRAINING_VIDEO_SMS
  "FLEET_COMMUNICATION_SMS" -> FLEET_COMMUNICATION_SMS
  "FLEET_COMMUNICATION_WHATSAPP" -> FLEET_COMMUNICATION_WHATSAPP
  "SEND_TOTP" -> SEND_TOTP
  "DOCUMENT_VALID" -> DOCUMENT_VALID
  "DRIVER_ONBOARDING_DEEPLINK_MESSAGE" -> DRIVER_ONBOARDING_DEEPLINK_MESSAGE
  "FLEET_CONSENT_AND_ONBOARDING_DEEPLINK_MESSAGE" -> FLEET_CONSENT_AND_ONBOARDING_DEEPLINK_MESSAGE
  "ONBOARDING_APPROVED" -> ONBOARDING_APPROVED
  "VEHICLE_APPROVED" -> VEHICLE_APPROVED
  t -> CustomMessageKey t

instance Show MessageKey where
  showsPrec _ k = showString (T.unpack (messageKeyToText k))

instance Read MessageKey where
  readsPrec _ s = case lex s of
    [(tok, rest)] | not (null tok) -> [(messageKeyFromText (T.pack tok), rest)]
    _ -> []

instance ToJSON MessageKey where
  toJSON = A.String . messageKeyToText

instance FromJSON MessageKey where
  parseJSON = A.withText "MessageKey" (pure . messageKeyFromText)

instance ToSchema MessageKey where
  declareNamedSchema _ = declareNamedSchema (Proxy :: Proxy Text)

instance HasSqlValueSyntax be Text => HasSqlValueSyntax be MessageKey where
  sqlValueSyntax = sqlValueSyntax . messageKeyToText

instance BeamSqlBackend be => B.HasSqlEqualityCheck be MessageKey

instance FromField MessageKey where
  fromField f mbValue = messageKeyFromText <$> fromField f mbValue

instance FromBackendRow Postgres MessageKey
