-- File auto generated by purescript-bridge! --
module Beckn.Types.Storage.Blacklist where

import Beckn.Types.App (BlacklistId, TenantOrganizationId, UserId)
import Beckn.Types.Common (EntityType)
import Data.Lens (Iso', Lens', Prism', lens, prism')
import Data.Lens.Iso.Newtype (_Newtype)
import Data.Lens.Record (prop)
import Data.Maybe (Maybe, Maybe(..))
import Data.Newtype (class Newtype)
import Data.Symbol (SProxy(SProxy))
import Data.Time.LocalTime.Internal.LocalTime (LocalTime)
import Prim (String)

import Prelude
import Data.Generic (class Generic)

newtype BlacklistT Identity =
    Blacklist {
      _id :: BlacklistId
    , __BlacklistedBy :: UserId
    , __TenantOrganizationId :: Maybe TenantOrganizationId
    , _remarks :: String
    , __EntityId :: String
    , _entityType :: EntityType
    , _startTime :: LocalTime
    , _endTime :: LocalTime
    , _info :: Maybe String
    , _createdAt :: LocalTime
    , _updatedAt :: LocalTime
    }

derive instance genericBlacklistT :: Generic (BlacklistT Identity)
derive instance newtypeBlacklistT :: Newtype (BlacklistT Identity) _

--------------------------------------------------------------------------------
_Blacklist :: forall Identity. Iso' (BlacklistT Identity) { _id :: BlacklistId, __BlacklistedBy :: UserId, __TenantOrganizationId :: Maybe TenantOrganizationId, _remarks :: String, __EntityId :: String, _entityType :: EntityType, _startTime :: LocalTime, _endTime :: LocalTime, _info :: Maybe String, _createdAt :: LocalTime, _updatedAt :: LocalTime}
_Blacklist = _Newtype

id :: forall Identity. Lens' (BlacklistT Identity) BlacklistId
id = _Newtype <<< prop (SProxy :: SProxy "_id")

_BlacklistedBy :: forall Identity. Lens' (BlacklistT Identity) UserId
_BlacklistedBy = _Newtype <<< prop (SProxy :: SProxy "__BlacklistedBy")

_TenantOrganizationId :: forall Identity. Lens' (BlacklistT Identity) (Maybe TenantOrganizationId)
_TenantOrganizationId = _Newtype <<< prop (SProxy :: SProxy "__TenantOrganizationId")

remarks :: forall Identity. Lens' (BlacklistT Identity) String
remarks = _Newtype <<< prop (SProxy :: SProxy "_remarks")

_EntityId :: forall Identity. Lens' (BlacklistT Identity) String
_EntityId = _Newtype <<< prop (SProxy :: SProxy "__EntityId")

entityType :: forall Identity. Lens' (BlacklistT Identity) EntityType
entityType = _Newtype <<< prop (SProxy :: SProxy "_entityType")

startTime :: forall Identity. Lens' (BlacklistT Identity) LocalTime
startTime = _Newtype <<< prop (SProxy :: SProxy "_startTime")

endTime :: forall Identity. Lens' (BlacklistT Identity) LocalTime
endTime = _Newtype <<< prop (SProxy :: SProxy "_endTime")

info :: forall Identity. Lens' (BlacklistT Identity) (Maybe String)
info = _Newtype <<< prop (SProxy :: SProxy "_info")

createdAt :: forall Identity. Lens' (BlacklistT Identity) LocalTime
createdAt = _Newtype <<< prop (SProxy :: SProxy "_createdAt")

updatedAt :: forall Identity. Lens' (BlacklistT Identity) LocalTime
updatedAt = _Newtype <<< prop (SProxy :: SProxy "_updatedAt")

--------------------------------------------------------------------------------
