module Resources.Localizable.EN where

import Language.Types (STR(..))

getEN :: STR -> String
getEN stringKey =
    case stringKey of
        ABOUT -> "About"
        ABOUT_APP_DESCRIPTION (stringForConfig) -> "Namma Yatri is an open platform to connect riders with drivers. The app makes it convenient for riders to book a ride with meter rate hence minimal fare."
        ABOUT_REFERRAL_PROGRAM -> "What is the Referral Program?"
        ABOUT_REFERRAL_PROGRAM_DISCRIPTION (stringForConfig) -> "The referral program incentivises drivers to accept more rides, cancel less and serve you better by recognising and rewarding worthy drivers. \n\n You can help out by entering the driver’s referral code  and improve the quality of rides for the Namma Yatri Community!"
        AC -> "AC"
        AC_CAB -> "AC Cab"
        AC_SUV -> "AC SUV"
        AC_TAXI -> "AC Taxi"
        ACCESSIBILITY_TEXT (stringForConfig) -> "Namma Yatri, now customised for you!"
        ACCOUNT_DELETION_CONFIRMATION -> "Are you sure you want to delete your account? All your personal data will be lost"
        ACTUAL_FARE_WAS_HIGHER_THAN_WHAT_WAS_SHOWN -> "Actual fare was higher than what was shown"
        ADD_A_TIP_TO_FIND_A_RIDE_QUICKER -> "Add a tip to find a ride quicker!"
        ADD_ANOTHER_CONTACT -> "Add Another Contact"
        ADD_EMERGENCY_CONTACTS -> "Add Emergency Contacts"
        ADD_FAVOURITE -> "Add Favourite"
        ADD_NEW_ADDRESS -> "Add New Address"
        ADD_NEW_FAVOURITE -> "Add New Favourite"
        ADD_NOW -> "Add now"
        ADD_SAVED_LOCATION_FROM_SETTINGS -> "*You can add new favourites from Side menu > Favourites"
        ADD_TAG -> "Add Tag"
        ADDRESS -> "Address"
        ADDRESSES -> "Addresses"
        ALL_FAVOURITES -> "All Favourites"
        ALL_TOPICS -> "All Topics"
        ALLOW_LOCATION_ACCESS -> "Allow Location Access"
        ALMOST_PERFECT -> "Almost Perfect! 🙂"
        ALREADY_EXISTS -> "Already Exists"
        ALSO_SHARE_YOUR_RIDE_STATUS_AND_LOCATION -> "Also shares your ride status and location"
        AMAZING -> "Amazing!!! 🤩"
        AMOUNT_PAID -> "Amount Paid"
        AND_HAS_TRAVELLED -> "."
        ANONYMOUS_CALL -> "Anonymous Call"
        ANYTHING_THAT_YOU_WOULD_LIKE_TO_TELL_US -> "Anything that you would like to tell us? (Optional)"
        ANYWHERE_IN_THE_CITY -> "anywhere in the city"
        APP_NOT_SERVICEABLE -> "Not Serviceable"
        ARE_YOU_A_PERSON_WITH_DISABILITY -> "Are you a person with disability?"
        ARE_YOU_STARING -> "Are you starting?"
        ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "Are you sure you want to Cancel?"
        ARE_YOU_SURE_YOU_WANT_TO_LOGOUT -> "Are you sure you want to logout?"
        ARE_YOU_SURE_YOU_WANT_TO_PROCEED_WITH_THE_BOOKING -> "Are you sure you want to proceed with the booking?"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_CONTACT -> "Are you sure you want to remove them from your emergency contacts?"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_FAVOURITE_ -> "Are you sure you want to remove a \n favourite location?"
        ASK_FOR_PRICE -> "Ask for a price"
        ASK_FOR_PRICE_INFO -> "You will receive a fare based on <b> government set </b> base price , with an additional <b> Rs.10 </b> nominal fee for the <b> pick-up distance </b> traveled by the drivers. Some drivers may request nominal tips solely at their discretion to cover factors like traffic, chances of return trip etc."
        ASKED_FOR_EXTRA_FARE -> "Asked for Extra Fare"
        ASKED_FOR_MORE_MONEY -> "Asked for more money"
        ASKING_FOR_MORE_MONEY -> "Driver was asking for more money"
        ASSISTANCE_REQUIRED -> "Assistance Required (Person with Disability)"
        AT_DROP -> "At Drop"
        AT_PICKUP -> "At Pickup"
        AUTO_ACCEPTING_SELECTED_RIDE -> "Auto accepting in"
        AUTO_ASSIGN_A_RIDE -> "Auto-assign a ride"
        AUTO_ASSIGN_DRIVER -> "Auto-assign a driver"
        AUTO_BROKEN -> "Auto broke down"
        AUTO_RICKSHAW -> "Auto Rickshaw"
        AWAY -> "away"
        AWAY_C -> "Away"
        BASE_FARES -> "Base Fare "
        BOARD_THE_FIRST -> "Board the first "
        BOOK_AND_MOVE -> "Book and move,"
        BOOK_NOW -> "Book Now"
        BOOK_RIDE_ -> "Book Ride"
        BOOK_YOUR_RIDE -> "Book Your Ride"
        BOOKING_PREFERENCE -> "Booking Preference"
        BOOST_YOUR_RIDE_CHANCES_AND_HELP_DRIVERS_WITH_TIPS -> "It seems to be a very busy day. You may try adding a tip to increase chances of getting a ride."
        BY_CASH -> "by Cash"
        BY_TAPPING_CONTINUE -> "By clicking Continue, you agree to our"
        CABS_AVAILABLE -> "cabs available"
        CALL -> "Call"
        CALL_112 -> "Call 112"
        CALL_DRIVER -> "Call Driver"
        CALL_DRIVER_USING -> "Call Driver using"
        CALL_EMERGENCY_CENTRE -> "Call Emergency Centre"
        CALL_EMERGENCY_CONTACTS -> "Call Emergency Contacts"
        CALL_NAMMA_YATRI_SUPPORT (stringForConfig) -> "Call Namma Yatri Support"
        CALL_POLICE -> "Call Police"
        CALL_SUPPORT -> "Call Support"
        CANCEL_ -> "Cancel"
        CANCEL_AUTO_ASSIGNING -> "Cancel Auto Assigning"
        CANCEL_ONGOING_SEARCH -> "Are you sure you want to continue with cancelling an ongoing search?"
        CANCEL_RIDE -> "Cancel Ride"
        CANCEL_SEARCH -> "Cancel Search"
        CANCEL_STR -> "Cancel"
        CANCELLATION_UNSUCCESSFULL_PLEASE_TRY_AGAIN -> "Cancellation unsuccessfull, please try again"
        CANCELLED -> "Cancelled"
        CANCELLING_AS_I_GOT_A_RIDE_ON_ANOTHER_APP -> "Cancelling as I got a ride on another app"
        CGST -> "CGST"
        CHANGE -> "Change"
        CHANGE_DROP_LOCATION -> "Change Drop Location"
        CHANGE_LOCATION -> "Change Location"
        CHANGE_OF_PLANS -> "Change of plans"
        CHARGES_APPLICABLE_AFTER_3_MINS -> "Charges applicable after 3 mins"
        CHAT_WITH -> "Chat with"
        CHATS -> "Chats"
        CHECK_IN_WITH_YOUR_DRIVER -> "Check in on your driver with a quick chat"
        CHECK_OUT_LIVE_STATS -> "Check out live stats"
        CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN -> "Check your internet connection and try again"
        CHECKOUT_OUR_LIVE_STATS -> "Checkout our Live Stats"
        CHOOSE_A_RIDE_AS_PER_YOUR_COMFORT -> "Choose a ride as per your comfort "
        CHOOSE_BETWEEN_MULTIPLE_DRIVERS -> "Choose between multiple drivers"
        CHOOSE_BETWEEN_MULTIPLE_RIDES -> "Choose between multiple ride options"
        CHOOSE_ON_MAP -> "Choose on map"
        CHOOSE_YOUR_RIDE -> "Choose Your Ride"
        CLEAN_AUTO -> "Clean Auto"
        COMFY -> "Comfy"
        COMPLETE_YOUR_PROFILE_FOR_A_PERSONALISED_RIDE_EXPERIENCE -> "Complete your profile for a personalised ride experience"
        CONFIRM_AND_BOOK -> "Confirm & Book"
        CONFIRM_AND_SAVE -> "Confirm & Save"
        CONFIRM_CHANGES -> "Confirm Changes"
        CONFIRM_DROP_LOCATION -> "Confirm Drop Location"
        CONFIRM_EMERGENCY_CONTACTS -> "Confirm Emergency Contacts"
        CONFIRM_FOR -> "Confirm for"
        CONFIRM_LOCATION -> "Confirm Location"
        CONFIRM_PICKUP_LOCATION -> "Confirm Pickup Location"
        CONFIRM_RIDE_ -> "Confirm Ride"
        CONFIRMING_THE_RIDE_FOR_YOU -> "Confirming the ride for you..."
        CONTACT_REMOVED_SUCCESSFULLY -> "Contact Removed Successfully"
        CONTACT_SUPPORT -> "Contact Support"
        CONTACTS_SELECTED -> "Contacts Selected"
        CONTINUE -> "Continue"
        CONTINUE_SEARCH_WITH -> "Continue Search with"
        CONTINUING_SEARCH_WITH -> "Continuing search with"
        COPIED -> "Copied"
        CORPORATE_ADDRESS -> "Corporate Address"
        CORPORATE_ADDRESS_DESCRIPTION (stringForConfig) -> "Juspay Technologies Private Limited <br> Girija Building, Number 817, Ganapathi Temple Rd, 8th Block, Koramangala, Bengaluru, Karnataka 560095, India."
        CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL (stringForConfig) -> "Website :  <u>https://nammayatri.in/</u>"
        COULD_NOT_CONNECT_TO_DRIVER -> "I could not connect to driver."
        CURRENT_LOCATION -> "Current Location"
        CURRENTLY_WE_ARE_LIVE_IN_ (stringForConfig) -> "We are not live in your area yet! \n You can access ride history and other settings from the menu"
        CUSTOMER_SELECTED_FARE -> "Customer Tip^"
        CUSTOMER_TIP_DESCRIPTION -> "^Extra amount added by the customer to increase the chances of getting a ride."
        DATA_COLLECTION_AUTHORITY -> "c ) I hereby appoint and authorize Juspay to collect my information and by continuing, I agree to the Terms of Use and Privacy Policy."
        DAY_TIME_CHARGES -> "Daytime Charges (5 AM to 10 PM)"
        DAY_TIMES_OF -> ""
        DAYTIME_CHARGES_APPLICABLE_AT_NIGHT -> "x of daytime charges applicable at night from 10 PM to 5 AM"
        DAYTIME_CHARGES_APPLIED_AT_NIGHT -> "x of daytime charges applied to fare at night (🌙) from 10 PM to 5 AM"
        DEL_ACCOUNT -> "Delete Account"
        DELETE -> "Delete"
        DENY_ACCESS -> "Deny Access"
        DESCRIBE_YOUR_ISSUE -> "Describe your Issue"
        DESCRIPTION_SHOULD_BE_MORE_THAN_10_ALPHABETIC_CHARACTERS -> "Description should be more than 10 alphabetic characters"
        DESTINATION_OUTSIDE_LIMITS -> "Destination Entered is outside city limits"
        DIAL_112 -> "Dial 112"
        DID_THE_DRIVER_OFFER_ASSISTANCE -> "Did the driver offer assistance?"
        DID_YOU_FACE_ANY_ISSUE -> "Did you face any issue?"
        DID_YOU_HAVE_A_SAFE_JOURNEY -> "Did you have a safe journey?"
        DIRECT_CALL -> "Direct Call"
        DISABILITY_CLAIMER_TEXT -> "By continuing, you are declaring your status as a person with disability under the RPWD act of 2016"
        DO_YOU_NEED_EMERGENCY_HELP -> "Do you need Emergency Help ?"
        DO_YOU_NEEED_SPECIAL_ASSISTANCE -> "Do you require special assistance (Person With Disability)?"
        DONE -> "Done"
        DOWNLOAD_DRIVER_RECEIPT -> "Download Driver Receipt"
        DOWNLOAD_INVOICE -> "Download Invoice"
        DOWNLOAD_PDF -> "Download PDF"
        DRAG_THE_MAP -> "Drag the map & set pin to exact location"
        DRIVER_ADDITION_LIMITS_ARE_IN_INCREMENTS -> "Driver addition limits are in increments of ₹20"
        DRIVER_ADDITIONS -> "Driver Additions*"
        DRIVER_ADDITIONS_ARE_CALCULATED_AT_RATE (stringForConfig) -> "Driver addition limits are calculated at 10% of the base fare rounded off to the nearest ₹10"
        DRIVER_ADDITIONS_OPTIONAL -> "Driver Additions (Optional)"
        DRIVER_BEHAVED_INAPPROPRIATELY -> "The driver behaved inappropriately"
        DRIVER_CHARGED_MORE -> "Driver charged more"
        DRIVER_HAS_ALREADY_TRAVELLED -> "Driver has already travelled "
        DRIVER_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION -> "Driver is already on the way to your location."
        DRIVER_IS_NEAR_YOUR_LOCATION -> "Driver is near your location."
        DRIVER_IS_NOT_MOVING -> "Driver is not moving"
        DRIVER_IS_NOT_MOVING_Q -> "Driver is not moving?"
        DRIVER_LOCATION_WASNT_CHANGING_ON_THE_MAP -> "Driver location wasn`t changing on the map"
        DRIVER_MAY_NOT_CHARGE_THIS_ADDITIONAL_FARE -> "Note :  The driver may/may not charge this additional fare"
        DRIVER_MIGHT_BE_TAKING_ALTERNATE_ROUTE -> "Driver might be taking an alternate route."
        DRIVER_PICKUP_CHARGES (stringForConfig) -> "Driver Pickup Charges"
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST -> "The driver preferred your special request and has travelled "
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_JUST -> "The driver preferred your special request and is just "
        DRIVER_RECEIPT -> "Driver Receipt"
        DRIVER_REQUESTED_TO_CANCEL -> "Driver requested me to cancel"
        DRIVER_WAS_NOT_REACHABLE -> "Driver wasn't reachable"
        DRIVER_WAS_NOT_READY_TO_GO -> "The driver was not to ready to go"
        DRIVER_WAS_RUDE -> "Driver was rude"
        DRIVER_WAS_TAKING_TOO_LONG_TO_REACH_THE_PICKUP_LOCATION -> "Driver was taking too long to reach the pickup location"
        DRIVERS_CAN_CHARGE_AN_ADDITIONAL_FARE_UPTO -> "* Drivers may optionally request 10% of base fare (rounded to nearest Rs.10) to cover other factors like traffic, chances of return trip etc."
        DRIVERS_CAN_CHARGE_BETWEEN_THE_ABOVE_RANGE -> "*Drivers can charge between the above range"
        DRIVERS_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "* Driver may optionally request 10% of base fare (rounded to nearest Rs.10) to cover for traffic, chance of return trip etc."
        DROP -> "Drop"
        DROP_LOCATION_FAR_AWAY -> "Your drop location is too far away"
        EARLY_END_RIDE_CHARGES -> "Early Ride End Charges^"
        EARLY_END_RIDE_CHARGES_DESCRIPTION -> "^Ending a ride early incurs additional charges amounting to half the fare of the untravelled distance (max. ₹50)"
        ECONOMICAL -> "Economical"
        EDIT -> "Edit"
        EDIT_FAVOURITE -> "Edit favourite"
        EDUCATIONAL_POP_UP_SLIDE_1_SUBTITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_1_TITLE -> "We strive to provide all our users \n an even & equal experience."
        EDUCATIONAL_POP_UP_SLIDE_2_SUBTITLE -> "&#8226; Drivers will be prompted to call instead <br> &ensp; of texting. <br> &#8226; Drivers will be prompted to sound horn <br> &ensp;  once at the pickup. <br> &#8226; Drivers will be sensitised to help them with <br> &ensp;  their needs and requests."
        EDUCATIONAL_POP_UP_SLIDE_2_TITLE -> "For users with poor vision"
        EDUCATIONAL_POP_UP_SLIDE_3_SUBTITLE -> "&#8226; Drivers will be prompted to text instead <br> &ensp;  of calling. <br> &#8226; Drivers will be prompted to message them <br> &ensp;  once at the pickup. <br> &#8226; Drivers will be sensitised to help them with <br> &ensp; their needs and requests."
        EDUCATIONAL_POP_UP_SLIDE_3_TITLE -> "For users with poor hearing"
        EDUCATIONAL_POP_UP_SLIDE_4_SUBTITLE -> "&#8226; Drivers will be prompted to come to their <br> &ensp;  exact location for pickup. <br> &#8226; Drivers will be prompted to help them <br> &ensp;  with their mobility aid. <br>&#8226; Drivers will be sensitised to help them with <br> &ensp; their needs and requests."
        EDUCATIONAL_POP_UP_SLIDE_4_TITLE -> "For users with locomotor disability"
        EDUCATIONAL_POP_UP_SLIDE_5_SUBTITLE -> "&#8226; We will be collecting other types of <br> &ensp; disabilities and shall be incorporating them <br> &ensp; among the list of disabilities available <br> &ensp; as needed."
        EDUCATIONAL_POP_UP_SLIDE_5_TITLE -> "For users with other special needs"
        EMAIL -> "Email"
        EMAIL_ALREADY_EXISTS -> "Failed to update email. Email already exists."
        EMAIL_EXISTS_ALREADY -> "Email already exists"
        EMAIL_ID -> "Email ID"
        EMERGENCY_CONTACS_ADDED_SUCCESSFULLY -> "Emergency Contacts Added Successfully"
        EMERGENCY_CONTACTS -> "Emergency Contacts"
        EMERGENCY_CONTACTS_SCREEN_DESCRIPTION -> "You can share your ride status in case of an emergency with upto 3 emergency contacts."
        EMERGENCY_HELP -> "Emergency Help"
        EMPTY_RIDES -> "Empty Rides"
        ENABLE_LOCATION_PERMISSION_TO -> "Enable Location Permission to Search for Rides ,"
        ENABLE_THIS_FEATURE_TO_CHOOSE_YOUR_RIDE -> "Enable this feature to choose your preferred ride & fare"
        ENJOY_RIDING_WITH_US -> "Enjoying riding with us? Spread the \n word and share the cheer"
        ENTER_4_DIGIT_OTP -> "Enter 4 digit OTP"
        ENTER_A_LOCATION -> "Enter a location"
        ENTER_MOBILE_NUMBER -> "Enter Mobile number"
        ENTER_OTP -> "Enter OTP"
        ENTER_YOUR_MOBILE_NUMBER -> "Enter your Mobile Number "
        ENTER_YOUR_NAME -> "Enter Your Name"
        ERNAKULAM_LIMIT_CHARGE -> "Fare will be 1.5x if the pickup or destination lies outside Ernakulam corporation limits"
        ERROR_404 -> "Error 404"
        ERROR_OCCURED_TRY_AGAIN -> "Error Occured. Try Again"
        ESTIMATES_CHANGED -> "The estimate for your ride has changed now"
        ESTIMATES_REVISED_TO -> "The revised estimate is"
        ETA_WAS_TOO_LONG -> "ETA was too long."
        ETA_WAS_TOO_SHORT -> "ETA was too short."
        EXISTS_AS -> "exists as"
        EXPERT_DRIVING -> "Expert Driving"
        EXPIRES_IN -> "Expires in"
        FAQ -> "FAQ"
        FARE_ESTIMATE -> "Fare Estimate"
        FARE_INFO_TEXT (stringForConfig) -> ""
        FARE_POLICY_WAITING_CHARGES -> "Applicable @ ₹1.5 per minute after the first 3 minutes of waiting"
        FARE_UPDATE_POLICY -> "Fare Update Policy"
        FARE_UPDATED -> "Fare updated"
        FARE_UPDATED_WITH_CHARGES -> "Fare has been updated to include applicable waiting charges"
        FARE_UPDATED_WITH_CHARGES_LONGER_DIST -> "Your fare has been updated as your ride was {} km longer and wait time charges incurred"
        FARE_UPDATED_WITH_CHARGES_SHORTER_DIST  -> "Your fare has been updated as your ride was {} km shorter and wait time charges incurred"
        FARE_UPDATED_WITH_LONGER_DIST  -> "Your fare has been updated as your ride was {} km longer"
        FARE_UPDATED_WITH_SHORTER_DIST  -> "Your fare has been updated as your ride was {} km shorter"
        FARE_WAS_HIGH -> "Fare was high"
        FASTER -> "Faster"
        FAVOURITE -> "Favourite"
        FAVOURITE_ADDED_SUCCESSFULLY -> "Favourite Added Successfully"
        FAVOURITE_LOCATION -> "Favourite Location"
        FAVOURITE_REMOVED_SUCCESSFULLY -> "Favourite Removed Successfully"
        FAVOURITE_UPDATED_SUCCESSFULLY -> "Favourite Updated Successfully"
        FAVOURITE_YOUR_CURRENT_LOCATION -> "Favourite your current location"
        FAVOURITES -> "Favourites"
        FELT_UNSAFE -> "Felt Unsafe"
        FEMALE -> "Female"
        FINDING_QUOTES_TEXT -> "Searching for cabs around"
        FINDING_RIDES_NEAR_YOU -> "Finding rides near you..."
        FOR_OTHER_ISSUES_WRITE_TO_US -> "For other issues, write to us"
        FULL_NAME -> "Full Name"
        GENDER_STR -> "Gender"
        GENERAL_DISABILITY_DESCRIPTION -> "Drivers will be sensitised to help you with your needs and requests."
        GET_CALLBACK_FROM_US -> "Get a callback from us"
        GET_ESTIMATE_FARE -> "Get estimate fare"
        GET_OTP_VIA_WHATSAPP -> "Get OTP via WhatsApp"
        GETTING_DELAYED_PLEASE_WAIT -> "Getting delayed, please wait"
        GETTING_ESTIMATES_FOR_YOU -> "Getting estimates for you..."
        GETTING_STARTED_AND_FAQS -> "Getting started and FAQs"
        GIVE_THIS_LOCATION_A_NAME -> "Give this location a name"
        GO_BACK_ -> "Go Back"
        GO_BACK_TEXT -> "Go Back"
        GO_HOME_ -> "Go Home"
        GO_TO_HOME__ -> "Go To Home"
        GO_TO_SELECTED_PICKUP_SPOT -> "Go to selected pickup spot"
        GO_TO_SELECTED_PICKUP_SPOT_AS_AUTOS_ARE_RESTRICTED -> "Go to the suggested pickup spot as Autos are restricted inside this area"
        GO_TO_ZONE (stringForConfig) -> "Go to your nearest zone"
        GOOGLE_MAP_ -> "Google Map"
        GOT_AN_OTP -> "Got an OTP?"
        GOT_ANOTHER_RIDE_ELSE_WHERE -> "Got another ride elsewhere"
        GOT_IT -> "Got It!"
        GOT_IT_TELL_US_MORE -> "Got it, Tell us more?"
        GOVERNMENT_CHAGRES -> "Ride GST (5%)"
        GRANT_ACCESS -> "Grant Location Access"
        HATCHBACK -> "Hatchback"
        HAVE_A_REFFERAL -> "Have a Referral?"
        HAVE_REFERRAL_CODE -> "Have a Referral Code?"
        HELP -> "Help"
        HELP_AND_SUPPORT -> "Help and Support"
        HELP_US_WITH_YOUR_FEEDBACK_OPTIONAL -> "Help us with your feedback (Optional)"
        HELP_US_WITH_YOUR_REASON -> "Help us with your reason"
        HELPS_DRIVER_CONFIRM_ITS_YOU -> "(Helps driver confirm it is you)"
        HEY -> "Hey"
        HI_POINTER_1 -> "Drivers will be prompted to text instead of calling."
        HI_POINTER_2 -> " Drivers will be prompted to message you once at the pickup."
        HOME -> "Home"
        HOPE_YOUR_RIDE_WAS_HASSLE_FREE -> "We hope your ride was hassle free"
        HOW_DO_YOU_IDENTIFY_YOURSELF -> "How do you identify yourself as?"
        HOW_LONG_DRIVER_WAITED_FOR_PICKUP -> "Shows you how long the driver has waited at pickup."
        HOW_SHOULD_WE_ADDRESS_YOU -> "How should we address you?"
        HOW_THE_PRICING_WORKS -> "How the pricing works?"
        HOW_THIS_WORKS -> "How this works?"
        HOW_WAS_YOUR_RIDE_EXPERIENCE -> "How was your ride experience?"
        HOW_WAS_YOUR_RIDE_WITH -> "How was your ride with "
        I_AM_ON_MY_WAY -> "I'm on my way"
        I_DID_NOT_FEEL_SAFE -> "I did not feel safe"
        I_HAVE_ARRIVED -> "I've arrived"
        IF_YOU_STILL_WANNA_BOOK_RIDE_CLICK_CONTINUE_AND_START_BOOKING_THE_RIDE -> "if you still want to book, click continue and start booking the ride"
        IF_YOUR_OTP_EXPIRES_ -> "If your OTP expires, you will need to book again."
        IN -> "in"
        IN_APP_TRACKING -> "In app tracking"
        INCLUSIVE_AND_ACCESSIBLE -> "Inclusive and Accessible, for everyone!"
        INCORRECT_OTP_PLEASE_TRY_AGAIN -> "Incorrect OTP, please try again."
        INVALID_CODE_PLEASE_RE_ENTER -> "Invalid Code. Please Re-enter"
        INVALID_CONTACT_FORMAT -> "Invalid contact format"
        INVALID_MOBILE_NUMBER -> "Invalid mobile number"
        INVOICE -> "Invoice"
        IS_ON_THE_WAY -> "is on the way.."
        IS_WAITING_AT_PICKUP -> "is waiting at pick up"
        IT_SEEMS_LIKE_YOU_HAVE_AN_ONGOING_RIDE_ -> "It seems that you have an on-going booking, please restart the app to view it"
        IT_SEEMS_TO_BE_A_VERY_BUSY_DAY -> "It seems to be a very busy day. You may try looking for rides again"
        IT_SEEMS_TO_BE_TAKING_LONGER_THAN_USUAL -> "It seems to be taking longer than usual."
        JUST_ONE_LAST_THING -> "Just one last thing"
        LANGUAGE -> "Language"
        LATE_DROP_OFF -> "Late Drop Off"
        LATE_PICK_UP -> "Late Pick Up"
        LEARN_HOW_TEXT (stringForConfig) -> "Learn how Namma Yatri caters to your needs"
        LEARN_MORE -> "Learn more"
        LET_TRY_THAT_AGAIN -> "Let's try that again..."
        LETS_GET_YOU_TRIP_READY -> "Let’s get you trip-ready!"
        LIMIT_REACHED_3_OF_3_EMERGENCY_CONTACTS_ALREADY_ADDED -> "Limit reached! 3 of 3 Emergency contacts already added"
        LIVE_STATS_DASHBOARD -> "Live Stats Dashboard"
        LOAD_MORE -> "Load More"
        LOADING -> "Loading"
        LOCATION -> "Location"
        LOCATION_ALREADY -> "Location already"
        LOCATION_ALREADY_EXISTS -> "location already exists"
        LOCATION_ALREADY_EXISTS_AS -> "Location already exists as"
        LOCATION_PERMISSION_SUBTITLE -> "To get you rides, we require your device location."
        LOCATION_PERMISSION_SUBTITLE_NEW_USER (stringForConfig) -> "Welcome to Namma Yatri! \n To start booking rides, we require your device location."
        LOCATION_UNSERVICEABLE -> "Location unserviceable"
        LOGIN_USING_THE_OTP_SENT_TO -> "Login using the OTP sent to"
        LOGO -> "Logo"
        LOGOUT_ -> "Logout"
        LOOKING_FOR_ANOTHER_RIDE -> "Looking for another ride..."
        LOOKING_FOR_YOU_AT_PICKUP -> "Looking for you at pick-up"
        LOST_SOMETHING -> "Lost Something?"
        M_AWAY -> " m away."
        MALE -> "Male"
        MANDATORY -> "Mandatory"
        MAX_CHAR_LIMIT_REACHED -> "Max character limit reached , "
        MAYBE_LATER -> "Maybe Later"
        MESSAGE -> "Message"
        MESSAGE_FROM_DRIVER -> "Message from Driver"
        MESSAGE_YOUR_DRIVER -> "Message your Driver?"
        METERS_AWAY_FROM_YOUR_DESTINATION -> "m away!"
        METRO_RIDE -> "Metro Ride"
        MIN_FARE_UPTO -> "Min. Fare upto"
        MINS_AWAY -> "mins Away"
        MISC_WAITING_CHARGE -> "Misc. (including Waiting Charges)"
        MOBILE -> "Mobile"
        MOBILE_NUMBER_STR -> "Mobile Number"
        MORE_THAN -> "More than"
        MOST_LOVED_APP (stringForConfig) -> "Bengaluru's most ❤️ Auto app"
        MY_RIDES -> "My Rides"
        MY_TICKETS -> "My Tickets"
        N_MORE_ATTEMPTS_LEFT -> " more attempts left"
        NAME -> "Name"
        NAME_ALREADY_IN_USE -> "Name already in-use"
        NAME_SHOULD_BE_MORE_THAN_2_CHARACTERS -> "Name should be more than 2 characters"
        NAMMA_SAFETY -> "Namma Safety"
        NAVIGATE -> "Navigate"
        NEARBY -> "Nearby"
        NEEDS_IMPROVEMENT -> "Needs Improvement 😕"
        NEW_ -> "New"
        NIGHT_TIME_CHARGES -> "Night-time Charges (10 PM to 5 AM)"
        NIGHT_TIMES_OF -> ""
        NO -> "No"
        NO_CONTACTS_FOUND_ON_THE_DEVICE_TO_BE_ADDED -> "No contacts found on the device to be added"
        NO_CONTACTS_LEFT_ON_DEVICE_TO_ADD -> "No contacts left on device to add"
        NO_DISABILITY -> "No Disability"
        NO_DONT -> "No, Don’t"
        NO_DRIVER_AVAILABLE_AT_THE_MOMENT_PLEASE_TRY_AGAIN -> "No drivers available at the moment, please try again"
        NO_EMERGENCY_CONTACTS_SET -> "No Emergency Contacts Set"
        NO_FAVOURITES_SAVED_YET -> "No favourites saved yet"
        NO_LONGER_REQUIRE_A_RIDE_DUE_TO_CHANGE_IN_PLANS -> "No longer require a ride due to change in plans"
        NO_MORE_RIDES -> "No more rides"
        NO_TIP -> "₹0 Tip"
        NOMINAL_FARE -> "Optional Driver Request*"
        NON_AC -> "Non-AC"
        NON_AC_TAXI -> "Non AC Taxi"
        NOT_NOW -> "Not Now"
        NOTE -> "Note :  "
        NOTIFY_ME -> "Notify me"
        NOW_GET_ASSISTED_RIDES -> "Now get assisted rides if you are a person with disability" 
        OF -> "of"
        OK_GOT_IT -> "Ok, Got it"
        OK_I_WILL_WAIT -> "Ok, I'll wait"
        OKAY_GOT_IT -> "Ok, Got it"
        ON_TIME -> "On Time"
        ONE_CLICK_BOOKING_FOR_YOUR_FAVOURITE_JOURNEYS -> "One click booking for your favourite journeys"
        ONLINE_ -> "Online"
        OR -> "Or"
        OTHER -> "Other"
        OTHERS -> "Others"
        OTP -> "OTP"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER -> "OTP entering limit exhausted, please try again later"
        OTP_EXPIRE_TIMER -> "OTP Expire Timer"
        OTP_EXPIRED -> "Otp Expired"
        OTP_EXPIRED_DESCRIPTION -> "Your ride OTP expired. Please book again to get a ride"
        OTP_FOR_THE_JATRI_SATHI_ZONE_HAS_BEEN_EXPIRED_PLEASE_TRY_LOOKING_AGAIN (stringForConfig) -> "OTP for the Jatri Sathi zone has been expired, please try booking again"
        OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN -> "OTP page has been expired, please request OTP again"
        OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER -> "OTP resend limit exhausted, please try again later"
        OTP_RESENT_SUCCESSFULLY -> "OTP resent successfully"
        OUR_SUGGESTED_PRICE_FOR_THIS_TRIP_IS -> "Our suggested price for this trip is"
        PAID -> "Paid"
        PAST_SEARCHES -> "Past Searches"
        PAY_BY_CASH_OR_UPI -> "Pay by Cash / UPI"
        PAY_DIRECTLY_TO_YOUR_DRIVER_USING_CASH_UPI -> "*Pay directly to your driver using Cash / UPI"
        PAY_DRIVER_USING_CASH_OR_UPI -> "Pay Driver using Cash/UPI"
        PAY_DRIVER_USING_CASH_OR_UPI_ -> "Pay Driver using Cash/UPI"
        PAY_DRIVER_USING_WALLET -> ""
        PAY_THE_DRIVER -> "Pay the driver"
        PAY_THE_DRIVER_INFO -> "Pay the driver directly, the price that was confirmed by you"
        PAY_THE_DRIVER_NOTE -> "(Total fare may change if ride distance changes)"
        PAY_VIA_CASH_OR_UPI -> "Pay via Cash / UPI"
        PAYMENT_METHOD -> "Payment Method"
        PAYMENT_METHOD_STRING -> "Cash / Use UPI app"
        PAYMENT_METHOD_STRING_ -> "Cash / Use UPI app"
        PEOPLE -> "people"
        PERCENTAGE_OF_NOMINAL_FARE -> "10% of base fare"
        PERSONAL_DETAILS -> "Personal Details"
        PI_POINTER_1 -> "Drivers will be prompted to come to your exact location for pickup."
        PI_POINTER_2 -> "Drivers will be prompted to help you with your mobility aid."
        PICK_UP_LOCATION -> "Pick Up Location"
        PICK_UP_LOCATION_INCORRECT -> "The pickup location was incorrect."
        PICKUP -> "Pickup"
        PICKUP_ -> "Pickup: "
        PICKUP_AND_DROP -> "Pickup and Drop"
        PICKUP_CHARGE -> "Driver Pickup Charges"
        PLACE_CALL -> "Place Call"
        PLACES_YOU_MIGHT_LIKE_TO_GO_TO -> "Places you might like to go to."
        PLATFORM_FEE -> "Platform Fee"
        PLATFORM_GST -> "Taxes (GST)"
        PLEASE_CHOOSE_YOUR_PREFERRED_LANGUAGE_TO_CONTINUE -> "Please choose your preferred language to continue."
        PLEASE_COME_FAST_I_AM_WAITING -> "Please come fast, I'm waiting"
        PLEASE_COME_SOON -> "Please come soon"
        PLEASE_CONTACT_THE_DRIVER_BEFORE_CANCELLING -> "\n Please contact the driver before cancelling"
        PLEASE_ENABLE_CONTACTS_PERMISSION_TO_PROCEED -> "Please enable contacts permission to proceed"
        PLEASE_ENABLE_LOCATION_PERMISSION (stringForConfig) -> "Please enable location permissions from the settings app to start looking for rides."
        PLEASE_ENTER_A_VALID_EMAIL -> "Please enter a valid email"
        PLEASE_FIND_REVISED_FARE_ESTIMATE -> "Please find the Revised Estimated Fare. Night charges are 1.5 times the day charges."
        PLEASE_PAY_THE_FINAL_AMOUNT_TO_THE_DRIVER_VIA_CASH -> "Please pay the final amount to the driver directly"
        PLEASE_TELL_US_WHAT_WENT_WRONG -> "Please tell us what went wrong"
        PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL -> "Please tell us why you want to cancel"
        PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE -> "We're excited to announce that there's a new update available for our app. This update includes a fresh new design and several new features to make your experience even better."
        PLEASE_WAIT -> "Please wait"
        PLEASE_WAIT_I_WILL_BE_THERE -> "Please wait, I'll be there"
        PLEASE_WAIT_WHILE_IN_PROGRESS -> "Please wait while in progress"
        POLITE_DRIVER -> "Polite Driver"
        POOR_EXPERIENCE -> "Poor Experience 😕"
        POWERED_BY -> "Powered By"
        PREFER_NOT_TO_SAY -> "Prefer not to say"
        PRIVACY_POLICY -> "Privacy Policy"
        PROBLEM_AT_OUR_END -> "There seems to be a problem at our end. Get notified when we are up again"
        PROFILE_COMPLETION -> "Profile Completion"
        PROMOTION -> "Promotion"
        QUICK -> "Quick"
        QUOTE_EXPIRED -> "Quote Expired"
        RASH_DRIVING -> "Rash Driving"
        RATE_ABOVE_MIN_FARE -> "Rate above Min. Fare"
        RATE_CARD -> "Rate Card"
        RATE_YOUR_DRIVER -> "Rate Your Driver"
        RATE_YOUR_EXPERIENCE -> "Rate your experience ✨"
        RATE_YOUR_RIDE -> "Rate your ride"
        RATE_YOUR_RIDE_WITH -> "Rate your ride with "
        REACHING_YOUR_DESTINATION_IN_ -> "Arriving at your destination in "
        REASON_CHANGE_IN_ROUTE_A -> "1.Change in Route :  "
        REASON_CHANGE_IN_ROUTE_B -> "Total fare may change due to change in route"
        REASON_FOR_DELETING_ACCOUNT -> "Reason for deleting account*"
        RECENT_RIDES -> "Recent Rides"
        RECKLESS_DRIVING -> "Reckless Driving"
        RECOMMENDED -> "Recommended"
        REFEREAL_CODE_DISCRIPTION -> "Your referral might just be the reason for \n a driver to be rewarded!"
        REFERRAL_CODE_APPLIED -> "Referral Applied!"
        REFERRAL_CODE_SUCCESSFULL -> "You have successfully applied \n the referral code!"
        REGISTER_USING_DIFFERENT_NUMBER -> "Do you want to register using a different mobile number?"
        REGISTERED_ADDRESS -> "Registered Address"
        REGISTERED_ADDRESS_DESCRIPTION (stringForConfig) -> "Juspay Technologies Private Limited <br> Stallion Business Centre, No. 444, 3rd & 4th Floor, 18th Main, 6th Block, Koramangala Bengaluru, Karnataka- 560095, India."
        REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL (stringForConfig) -> "Website :  <u>https://nammayatri.in/</u>"
        REMOVE -> "Remove"
        REMOVE_FAVOURITE -> "Remove Favourite"
        REPEAT_RIDE -> "Repeat Ride"
        REPLIES -> "Replies"
        REPLY -> "Reply"
        REPORT_AN_ISSUE -> "Report an Issue"
        REPORT_AN_ISSUE_WITH_THIS_TRIP -> "Report an issue with this Trip"
        REPORT_ISSUE_ -> "Report Issue"
        REQUEST_AUTO_RIDE (stringForConfig) -> "Request Auto Ride"
        REQUEST_CALLBACK -> "Request Callback"
        REQUEST_RECEIVED_WE_WILL_CALL_YOU_BACK_SOON -> "Request received. We will call you back soon"
        REQUEST_RIDE -> "Request Ride"
        REQUEST_SUBMITTED -> "Request Submitted"
        REQUEST_TO_DELETE_ACCOUNT -> "Request to delete account"
        REQUESTING_RIDE -> "Requesting ride"
        REQUESTING_RIDE_IN -> "Requesting ride in"
        RESEND -> "Resend"
        RIDE_COMPLETED -> "Ride Completed"
        RIDE_DETAILS -> "Ride Details"
        RIDE_FARE -> "Ride Fare"
        RIDE_ID -> "Ride ID"
        RIDE_NOT_SERVICEABLE -> "Ride Not Serviceable"
        RIDE_TYPE -> "Ride Type"
        RUDE_DRIVER -> "Rude Driver"
        SAFE_RIDE -> "Safe Ride"
        SAVE -> "Save"
        SAVE_AS -> "Save as"
        SAVE_PLACE -> "Save Place"
        SAVED_ADDRESS_HELPS_YOU_KEEP_YOUR_FAVOURITE_PLACES_HANDY -> "Favourite location helps in keeping your frequently visited places handy"
        SAVED_ADDRESSES -> "Saved Addresses"
        SEARCH_AGAIN_WITH -> "Search Again With"
        SEARCH_AGAIN_WITH_A_TIP -> "Search again with a tip?"
        SEARCH_AGAIN_WITHOUT_A_TIP -> "Search Again Without Tip"
        SEARCH_CONTACTS -> "Search Contacts"
        SEARCH_RESULTS -> "Search Results"
        SEARCHING_WITH -> "Searching with"
        SEATS -> "Seats"
        SEDAN -> "Sedan"
        SELECT_A_RIDE -> "Select a ride for more details"
        SELECT_AN_OFFER -> "Select an Offer"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS -> "Select an offer (Optional)"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS_INFO -> "By default, when “<b>Auto-assign a ride</b>” is enabled, you are assigned a driver who accepts the request first, within the estimate range. Instead, if you wish to choose a driver offer, you can disable and proceed."
        SELECT_CONTACTS -> "Select Contacts"
        SELECT_FAVOURITE -> "Select Favourite"
        SELECT_LOCATION_ON_MAP -> "Select location on map"
        SELECT_ON_MAP -> "Select on map"
        SELECT_THE_CONDITION_THAT_IS_APPLICABLE -> "Select the condition that is applicable to you \n (As per RPWD act 2016)"
        SELECT_YOUR_DROP -> "Select your drop"
        SELECT_YOUR_GENDER -> "Select Your Gender"
        SEND_EMAIL -> "Send Email"
        SENT_OTP_VIA_SMS -> "OTP Sent via SMS"
        SENT_OTP_VIA_WHATSAPP -> "OTP Sent via Whatsapp ,"
        SERVICE_CHARGES -> "Service Charges"
        SET_LOCATION_ON_MAP -> "Set location on map"
        SET_NOW -> "Set now"
        SET_UP_YOUR_ACCOUNT -> "Set up your account"
        SGST -> "SGST"
        SHARE_APP -> "Share App"
        SHARE_RIDE_WITH_EMERGENCY_CONTACTS -> "Share Ride with Emergency Contacts"
        SHOW_ALL_OPTIONS -> "Show all options"
        SHOWS_FOR_HOW_LONG_YOUR_OTP_ -> "Shows for how long your OTP will remain valid to start the ride."
        SIX_DIGIT_REFERRAL_CODE -> "Enter 6 digit code shared by driver"
        SKILLED_NAVIGATOR -> "Skilled Navigator"
        SKIP -> "Skip"
        SOFTWARE_LICENSE -> "Software license"
        SOME_OTHER_REASON -> "Some other reason."
        SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN -> "Something went wrong, please try again"
        SOMETHING_WENT_WRONG_TRY_AGAIN_LATER -> "Something went wrong, please try again later"
        SORRY_LIMIT_EXCEEDED_YOU_CANT_ADD_ANY_MORE_FAVOURITES -> "Sorry, limit exceeded. You can't add any more favourites"
        SORRY_WE_COULDNT_FIND_ANY_RIDES -> "Sorry, we couldn’t find any rides"
        SORT_BY -> "Sort By"
        SPACIOUS -> "Spacious"
        SPECIAL_ASSISTANCE -> "Special Assistance"
        START_ -> "Start"
        START_TYPING_TO_SEARCH_PLACES -> "Start typing to search for places"
        START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS -> "Start your chat using these quick chat suggestions"
        START_YOUR_CHAT_WITH_THE_DRIVER -> "Start your chat with the driver"
        STEPS_TO_COMPLETE -> "Steps to complete"
        SUBJECT -> "Subject"
        SUBMIT -> "Submit"
        SUBMIT_FEEDBACK -> "Submit Feedback"
        SUBMIT_REQUEST -> "Submit Request"
        SUCCESSFUL_ONBOARD (stringForConfig) -> "You have successfully signed on to \n Namma Yatri"
        SUGGESTED_DESTINATION -> "Suggested Destinations"
        SUPPORT -> "Support"
        SUV -> "SUV"
        T_AND_C_A -> "a) You agree that you are a willing participant of the beta testing and Juspay shall have no liability against you in any respect"
        TAP_HERE_TO_STOP_AUTO_REQUESTING -> "Tap here to stop auto requesting"
        TAXI -> "taxi" 
        TAXI_FROM_ZONE (stringForConfig) -> "from your nearest Zone"
        TERMS_AND_CONDITIONS -> "T&C"
        TERRIBLE_EXPERIENCE -> "Terrible Experience 😠"
        THANK_YOU_FOR_WRITING -> "Thank You for writing to us!"
        THANK_YOU_FOR_WRITING_TO_US -> "Thank You for writing to us!"
        THANK_YOUR_DRIVER -> "Thank your Driver!"
        THE_DRIVER_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "The Driver may quote extra to cover for traffic, chance of return trip etc."
        THE_DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION -> "The driver preferred your special request and is already on the way to your location."
        THE_PICKUP_LOCATION_ENTERED_WAS_WRONG -> "The pickup location entered was wrong"
        THE_RIDE_HAD_BEEN_CANCELLED_WE_ARE_FINDING_YOU_ANOTHER -> "The ride had to be cancelled, we’re finding you another"
        THE_TRIP_IS_VERY_SHORT_AND_JUST_TAKE -> "The trip is very short and just take"
        THIS_FIELD_IS_REQUIRED -> "This field is required"
        TIP -> "Tip"
        TIP_SELECTED -> "Tip Selected"
        TO_CATER_YOUR_SPECIFIC_NEEDS (stringForConfig) -> "To cater to your specific needs, we have customised certain features of Namma Yatri."
        TO_THE -> "You agree that you are accepting the "
        TOLL_CHARGES_WILL_BE_EXTRA -> "Toll/Parking charges will be additional"
        TOO_MANY_CALLS -> "Too Many Calls"
        TOO_MANY_LOGIN_ATTEMPTS_PLEASE_TRY_AGAIN_LATER -> "Too many login attempts, please try again later"
        TOTAL_AMOUNT -> "Total Amount"
        TOTAL_FARE_MAY_CHANGE_DUE_TO_CHANGE_IN_ROUTE -> "Total fare may change due to change in route"
        TOTAL_PAID -> "Total Paid"
        TRACK_LIVE_LOCATION_USING -> "Track live location using"
        TRACK_ON_GOOGLE_MAPS -> "Track on Google Maps"
        TRIP_CHARGES -> "Trip Charges"
        TRIP_DETAILS_ -> "Trip Details"
        TRIP_GOT_DELAYED -> "Trip Got Delayed"
        TRIP_ID -> "Trip Id"
        TRIP_WAS_SAFE_AND_WORRY_FREE -> "We would like to ensure that your trip was safe and worry free."
        TRY_AGAIN -> "Try again"
        TRY_AGAIN_WITH -> "Try Again With"
        TRY_AGAIN_WITH_A_TIP -> "Try again with a tip?"
        TRY_AGAIN_WITHOUT_TIP -> "Try Again Without Tip"
        TRY_CONNECTING_WITH_THE_DRIVER -> "You can request a callback from driver"
        TRY_LOOKING_FOR_RIDES_AGAIN -> "It seems to be a very busy day. You may try looking for rides again"
        UNCOMFORTABLE_AUTO -> "Uncomfortable Auto"
        UNPROFESSIONAL_DRIVER -> "Unprofessional Driver"
        UNREACHABLE_PLEASE_CALL_BACK -> "Unreachable, Please call back"
        UPDATE -> "Update"
        UPDATE_NOW -> "Update Now"
        UPDATE_PERSONAL_DETAILS -> "Update Personal Details"
        UPDATE_PROFILE -> "Update Profile"
        UPDATE_REQUIRED -> "Update Required"
        USE_CURRENT_LOCATION -> "Use current location"
        USER -> "User"
        VERIFYING_OTP -> "Verifying OTP"
        VI_POINTER_1 -> "Drivers will be prompted to call instead of texting."
        VI_POINTER_2 -> "Drivers will be prompted to sound horn once at the pickup."
        VIEW_ALL_RIDES -> "View All Rides"
        VIEW_BREAKDOWN -> "View Breakdown"
        VIEW_DETAILS -> "View Details"
        VIEW_DRIVER_RECEIPT -> "View Driver Receipt"
        VIEW_INVOICE -> "View Invoice"
        VIEW_LESS -> "View Less"
        VIEW_MORE -> "View More"
        VISIT_MY_RIDES_SECTION_FOR_RIDE_SPECIFIC_COMPLAINTS -> "Visit My rides section for ride specific complaints"
        WAIT_FOR_DRIVER -> "Wait For Driver"
        WAIT_TIME -> "Wait Time"
        WAIT_TIME_TOO_LONG -> "Wait time too long"
        WAIT_TIMER -> "Wait Timer"
        WAITING_AT_PICKUP -> "is waiting at pickup"
        WAITING_CHARGE -> "Waiting Charges**"
        WAITING_CHARGE_DESCRIPTION -> "°Waiting charge is zero for the first 3 minutes. You will be charged ₹1.5 per minute of wait time after that."
        WAITING_CHARGE_RATECARD_DESCRIPTION -> "Waiting Charge is zero for the first 3 minutes.\n Waiting Charge of ₹1.5 per minute will be applicable thereafter."
        WAS_THE_DRIVER_UNDERSTANDING_OF_YOUR_NEEDS -> "Was your driver understanding of your needs and accomodate them on the journey?"
        WAS_YOUR_CALL_SUCCESSFUL -> "Was Your Call Successful"
        WE_HAVE_RECEIVED_YOUR_ISSUE -> "We have received your issue. We’ll reach out to you in sometime."
        WE_HAVE_RECEIVED_YOUR_ISSUE_WELL_REACH_OUT_TO_YOU_IN_SOMETIME -> "We have received your issue. We’ll reach out to you in sometime."
        WE_NEED_ACCESS_TO_YOUR_LOCATION -> "We need access to your location!"
        WE_NOTICED_YOUR_RIDE_ENDED_AWAY -> "We noticed  that your ride ended away from your original destination."
        WE_WILL_DELETE_YOUR_ACCOUNT -> "We are sorry to see you leave our platform. Your account will be deleted within the next 30 days. Meanwhile if you wish to retain your account, please call to our customer support number"
        WE_WILL_GIVE_YOU_CALLBACK -> "We will give you a callback within 24 hrs"
        WE_WOULD_APPRECIATE_YOUR_FEEDBACK -> "We would appreciate your reasoning behind account deletion"
        WE_WOULD_APPRECIATE_YOUR_REASONING -> "We would appreciate your feedback on your reasoning behind account deletion"
        WELCOME_TEXT (stringForConfig) -> "Welcome to Namma Yatri"
        WELCOME_TO_NAMMA_YATRI_ -> "Welcome to Namma Yatri!"
        WHERE_TO -> "Where to?"
        WORK -> "Work"
        WOULD_YOU_LIKE_TO_CHECK_WITH_THE_DRIVER_BEFORE_CANCELLING -> "\n Would you like to check with the driver before cancelling?"
        WRITE_A_COMMENT -> "Write a comment (Optional)"
        WRITE_TO_US -> "Write to Us"
        WRONG_OTP -> "Wrong OTP"
        WRONG_PICKUP_LOCATION -> "Wrong pickup location"
        YES -> "Yes"
        YES_CANCEL_SEARCH -> "Yes, Cancel Search"
        YES_DELETE_IT -> "Yes, Delete It"
        YES_REMOVE -> "Yes, Remove"
        YES_TRY_AGAIN -> "Yes, Try Again"
        YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT (stringForConfig) -> "You are about to place a call to the Namma Yatri Support Team. Do you want to proceed?"
        YOU_ARE_ABOUT_TO_CALL_NEAREST_EMERGENCY_CENTRE -> "You are about to place a call to the nearest Emergency Centre. Do you want to proceed?"
        YOU_ARE_OFFLINE -> "You're Offline"
        YOU_CAN_BOOK_TICKETS_TO_THE_ZOO_BY_CLICKING_THE_BUTTON -> "You can book tickets to the Zoo by clicking the button."
        YOU_CAN_CANCEL_RIDE -> "You can cancel once you get offers from drivers"
        YOU_CAN_DESCRIBE_THE_ISSUE_YOU_FACED_HERE -> "You can describe the issue you faced here"
        YOU_CAN_GET_REFERRAL_CODE_FROM_DRIVER (stringForConfig) -> "\n You can get a referral code by asking your Namma Yatri Driver."
        YOU_CAN_TAKE_A_WALK_OR_CONTINUE_WITH_RIDE_BOOKING -> "You may wish to walk or continue with the ride booking"
        YOU_HAVE_REACHED_DESTINATION -> "You have arrived at your destination"
        YOU_HAVE_RIDE_OFFERS_ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "You have ride offers, are you sure you want to cancel?"
        YOU_HAVENT_TAKEN_A_TRIP_YET -> "You haven't taken a trip yet !"
        YOU_MAY_SEE_AN_UPDATED_FINAL_FARE_DUE_TO_ANY_OF_THE_BELOW_REASONS -> "You may see an updated final fare due to any of the below reasons : "
        YOU_RATED -> "You Rated : "
        YOU_SEEM_TO_BE_FAR_FROM_PICK_UP -> "You seem to be far from the pickup location!"
        YOU_SENT -> "You Sent"
        YOU_WILL_BE_ASKED_TO_SELECT_CONTACTS -> "You will be asked to select upto 3  contacts"
        YOU_WILL_PAY_FOR_EVERY_MINUTE -> "Waiting charge is zero for the first 3 minutes. You will be charged for ₹1.5 per minute of wait time after that."
        YOUR_DRIVER_IS_JUST -> "Your Driver is just "
        YOUR_EMAIL_ID -> "Your email ID"
        YOUR_FEEDBACK_HELPS_US (stringForConfig) -> "Your feedback helps us improve the app experience"
        YOUR_ISSUE_HAS_BEEN_REPORTED -> "Your issue has been reported successfully"
        YOUR_NUMBER_WILL_BE_VISIBLE_TO_THE_DRIVER_USE_IF_NOT_CALLING_FROM_REGISTERED_NUMBER -> "Your number will be visible to the driver. Use if not calling from registered number."
        YOUR_NUMBER_WILL_NOT_BE_SHOWN_TO_THE_DRIVER_THE_CALL_WILL_BE_RECORDED_FOR_COMPLIANCE -> "Your number will not be shown to the driver. The call will be recorded for compliance."
        YOUR_RECENT_RIDE -> "Your Recent Ride"
        YOUR_RIDE_HAS_STARTED -> "Yay! Your ride has started 🤩"
        YOUR_RIDE_IS_NOW_COMPLETE -> "Your Ride is now complete!"
        YOUR_RIDES -> "Your Rides"
        YOUR_SUGGESTED_DESTINATIONS_AND_RECENT_RIDES_WILL_APPEAR_HERE -> "Your Suggested Destinations and Recent Rides will appear here"
        YOUR_TRIP_IS_TOO_SHORT_YOU_ARE_JUST -> "Your trip distance is too short. Destination is just "
