module Resources.Localizable.EN where

import Prelude ((<>))
import Language.Types (STR(..))
import Prelude ((<>))

getEN :: STR -> String
getEN stringKey =
    case stringKey of
        DOWNLOAD_INVOICE -> "Download Invoice"
        REPORT_AN_ISSUE -> "Report an Issue"
        SUBMIT -> "Submit"
        VIEW_INVOICE -> "View Invoice"
        TOTAL_AMOUNT -> "Total Amount"
        AMOUNT_PAID -> "Amount Paid"
        TRIP_DETAILS_ -> "Trip Details"
        DOWNLOAD_PDF -> "Download PDF"
        CGST -> "CGST"
        INVOICE -> "Invoice"
        TRIP_CHARGES -> "Trip Charges"
        PROMOTION -> "Promotion"
        SEND_EMAIL -> "Send Email"
        YOU_CAN_DESCRIBE_THE_ISSUE_YOU_FACED_HERE -> "You can describe the issue you faced here"
        THANK_YOU_FOR_WRITING -> "Thank You for writing to us!"
        WE_HAVE_RECEIVED_YOUR_ISSUE -> "We have received your issue. We’ll reach out to you in sometime."
        GO_HOME_ -> "Go Home"
        LOGO -> "Logo"
        ABOUT_APP_DESCRIPTION _ -> "Namma Yatri is an open platform to connect riders with drivers. The app makes it convenient for riders to book a ride with meter rate hence minimal fare."
        ABOUT -> "About"
        PRIVACY_POLICY -> "Privacy Policy"
        SET_UP_YOUR_ACCOUNT -> "Set up your account"
        CONTINUE -> "Continue"
        ENTER_YOUR_NAME -> "Enter Your Name"
        FULL_NAME -> "Full Name"
        EMAIL -> "Email"
        WELCOME_TEXT _ -> "Welcome to Namma Yatri"
        PLEASE_CHOOSE_YOUR_PREFERRED_LANGUAGE_TO_CONTINUE -> "Please choose your preferred language to continue."
        WRITE_TO_US -> "Write to Us"
        NOTE -> "Note "
        VISIT_MY_RIDES_SECTION_FOR_RIDE_SPECIFIC_COMPLAINTS -> "Visit My rides section for ride specific complaints"
        THANK_YOU_FOR_WRITING_TO_US -> "Thank You for writing to us!"
        WE_HAVE_RECEIVED_YOUR_ISSUE_WELL_REACH_OUT_TO_YOU_IN_SOMETIME -> "We have received your issue. We’ll reach out to you in sometime."
        GO_TO_HOME__ -> "Go To Home"
        SUBJECT -> "Subject"
        YOUR_EMAIL_ID -> "Your email ID"
        DESCRIBE_YOUR_ISSUE -> "Describe your Issue"
        ENTER_MOBILE_NUMBER -> "Enter Mobile number"
        BY_TAPPING_CONTINUE -> "By clicking Continue, you agree to our"
        TO_THE -> "You agree that you are accepting the "
        ENTER_OTP -> "Enter OTP"
        RESEND -> "Resend"
        ENTER_YOUR_MOBILE_NUMBER -> "Enter your Mobile Number "
        LOGIN_USING_THE_OTP_SENT_TO -> "Login using the OTP sent to"
        YOUR_RECENT_RIDE -> "Your Recent Ride"
        VIEW_ALL_RIDES -> "View All Rides"
        ALL_TOPICS -> "All Topics"
        FAQ -> "FAQ"
        REPORT_AN_ISSUE_WITH_THIS_TRIP -> "Report an issue with this Trip"
        YOU_RATED -> "You Rated"
        GETTING_STARTED_AND_FAQS -> "Getting started and FAQs"
        FOR_OTHER_ISSUES_WRITE_TO_US -> "For other issues, write to us"
        HELP_AND_SUPPORT -> "Help and Support"
        OUR_SUGGESTED_PRICE_FOR_THIS_TRIP_IS -> "Our suggested price for this trip is"
        DRIVERS_CAN_CHARGE_BETWEEN_THE_ABOVE_RANGE -> "*Drivers can charge between the above range"
        HOW_THIS_WORKS -> "How this works?"
        FINDING_RIDES_NEAR_YOU -> "Finding rides near you..."
        CONFIRMING_THE_RIDE_FOR_YOU -> "Confirming the ride for you..."
        CANCEL_SEARCH -> "Cancel Search"
        YOUR_RIDE_IS_NOW_COMPLETE -> "Your Ride is now complete!"
        PLEASE_PAY_THE_FINAL_AMOUNT_TO_THE_DRIVER_VIA_CASH -> "Please pay the final amount to the driver directly"
        WHERE_TO -> "Where to?"
        HOME -> "Home"
        PICK_UP_LOCATION -> "Pick Up Location"
        REQUEST_RIDE -> "Request Ride"
        NAME -> "Name"
        MOBILE_NUMBER_STR -> "Mobile Number"
        PERSONAL_DETAILS -> "Personal Details"
        YOUR_RIDES -> "Your Rides"
        YOU_ARE_OFFLINE -> "You're Offline"
        CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN -> "Check your internet connection and try again"
        TRY_AGAIN -> "Try again"
        THANK_YOUR_DRIVER -> "Thank your Driver!"
        HOPE_YOUR_RIDE_WAS_HASSLE_FREE -> "We hope your ride was hassle free"
        HOW_WAS_YOUR_RIDE_WITH -> "How was your ride with "
        GOT_IT_TELL_US_MORE -> "Got it, Tell us more?"
        WRITE_A_COMMENT -> "Write a comment (Optional)"
        UPDATE -> "Update"
        LANGUAGE -> "Language"
        OTP -> "OTP"
        PAYMENT_METHOD -> "Payment Method"
        PAYMENT_METHOD_STRING -> "Cash / Use UPI app"
        PAYMENT_METHOD_STRING_ -> "Cash / Use UPI app"
        CANCEL_RIDE -> "Cancel Ride"
        SUPPORT -> "Support"
        PICKUP_AND_DROP -> "Pickup and Drop"
        CANCELLED -> "Cancelled"
        HOW_THE_PRICING_WORKS -> "How the pricing works?"
        SELECT_AN_OFFER -> "Select an Offer"
        CHOOSE_A_RIDE_AS_PER_YOUR_COMFORT -> "Choose a ride as per your comfort "
        IT_SEEMS_TO_BE_A_VERY_BUSY_DAY -> "It seems to be a very busy day. You may try looking for rides again"
        SORT_BY -> "Sort By"
        SORRY_WE_COULDNT_FIND_ANY_RIDES -> "Sorry, we couldn’t find any rides"
        LOAD_MORE -> "Load More"
        WE_NEED_ACCESS_TO_YOUR_LOCATION -> "We need access to your location!"
        LOCATION_PERMISSION_SUBTITLE -> "To get you rides, we require your device location."
        CALL -> "Call"
        EMPTY_RIDES -> "Empty Rides"
        YOU_HAVENT_TAKEN_A_TRIP_YET -> "You haven't taken a trip yet"
        BOOK_NOW -> "Book Now"
        T_AND_C_A -> "a) You agree that you are a willing participant of the beta testing and Juspay shall have no liability against you in any respect"
        TERMS_AND_CONDITIONS -> "T&C"
        DATA_COLLECTION_AUTHORITY -> "c) I hereby appoint and authorize Juspay to collect my information and by continuing, I agree to the Terms of Use and Privacy Policy."
        DENY_ACCESS -> "Deny Access"
        PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL -> "Please tell us why you want to cancel"
        MANDATORY -> "Mandatory"
        SOFTWARE_LICENSE -> "Software license"
        LOGOUT_ -> "Logout"
        REQUEST_AUTO_RIDE _-> "Request Auto Ride"
        RATE_YOUR_RIDE -> "Rate your ride"
        SKIP -> "Skip"
        ERROR_404 -> "Error 404"
        PROBLEM_AT_OUR_END -> "There seems to be a problem at our end. Get notified when we are up again"
        NOTIFY_ME -> "Notify me"
        ADDRESS -> "Address"
        CHANGE -> "Change"
        SAVE_AS -> "Save as"
        ADD_TAG -> "Add Tag"
        WORK -> "Work"
        OTHER -> "Other"
        SAVE -> "Save"
        ADD_NEW_ADDRESS -> "Add New Address"
        SAVED_ADDRESSES -> "Saved Addresses"
        ADDRESSES -> "Addresses"
        NO_FAVOURITES_SAVED_YET -> "No favourites saved yet"
        SAVED_ADDRESS_HELPS_YOU_KEEP_YOUR_FAVOURITE_PLACES_HANDY -> "Favourite location helps in keeping your frequently visited places handy"
        EMERGENCY_CONTACTS -> "Emergency Contacts"
        EDIT_EMERGENCY_CONTACTS -> "Edit Emergency Contacts"
        ADD_EMERGENCY_CONTACTS -> "Add Emergency Contacts"
        ADD_ANOTHER_CONTACT -> "Add Another Contact"
        NO_EMERGENCY_CONTACTS_SET -> "No Emergency Contacts Set"
        COPIED -> "Copied"
        TRIP_ID -> "Trip Id"
        SAVE_PLACE -> "Save Place"
        RIDE_FARE -> "Ride Fare"
        ASK_FOR_PRICE -> "Ask for a price"
        ASK_FOR_PRICE_INFO -> "You will receive a fare based on <b> government set </b> base price , with an additional <b> Rs.10 </b> nominal fee for the <b> pick-up distance </b> traveled by the drivers. Some drivers may request nominal tips solely at their discretion to cover factors like traffic, chances of return trip etc."
        GET_ESTIMATE_FARE -> "Get estimate fare"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS -> "Select an offer (Optional)"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS_INFO -> "By default, when “<b>Auto-assign a ride</b>” is enabled, you are assigned a driver who accepts the request first, within the estimate range. Instead, if you wish to choose a driver offer, you can disable and proceed."
        PAY_THE_DRIVER -> "Pay the driver"
        PAY_THE_DRIVER_INFO -> "Pay the driver directly, the price that was confirmed by you"
        PAY_THE_DRIVER_NOTE -> "(Total fare may change if ride distance changes)"
        UPDATE_PERSONAL_DETAILS -> "Update Personal Details"
        EDIT -> "Edit"
        DEL_ACCOUNT -> "Delete Account"
        ACCOUNT_DELETION_CONFIRMATION -> "Are you sure you want to delete your account? All your personal data will be lost"
        REQUEST_SUBMITTED -> "Request Submitted"
        WE_WILL_DELETE_YOUR_ACCOUNT -> "We are sorry to see you leave our platform. Your account will be deleted within the next 30 days. Meanwhile if you wish to retain your account, please call to our customer support number"
        YES_DELETE_IT -> "Yes, Delete It"
        REQUEST_TO_DELETE_ACCOUNT -> "Request to delete account"
        CANCEL_STR -> "Cancel"
        LOADING -> "Loading"
        PLEASE_WAIT_WHILE_IN_PROGRESS -> "Please wait while in progress"
        SET_LOCATION_ON_MAP -> "Set location on map"
        CURRENT_LOCATION -> "Current Location"
        ACTUAL_FARE_WAS_HIGHER_THAN_WHAT_WAS_SHOWN -> "Actual fare was higher than what was shown"
        DELETE -> "Delete"
        ARE_YOU_SURE_YOU_WANT_TO_LOGOUT -> "Are you sure you want to logout?"
        ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "Are you sure you want to Cancel?"
        YOU_HAVE_RIDE_OFFERS_ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "You have ride offers, are you sure you want to cancel?"
        GO_BACK_ -> "Go Back"
        REGISTER_USING_DIFFERENT_NUMBER -> "Do you want to register using a different mobile number?"
        YES -> "Yes"
        NO -> "No"
        CANCEL_ -> "Cancel"
        IS_ON_THE_WAY -> "is on the way"
        ENTER_4_DIGIT_OTP -> "Enter 4 digit OTP"
        WRONG_OTP -> "Wrong OTP"
        GRANT_ACCESS -> "Grant Location Access"
        ENTER_A_LOCATION -> "Enter a location"
        NEARBY -> "Nearby"
        MINS_AWAY -> "mins Away"
        PAID -> "Paid"
        BY_CASH -> "by Cash"
        ONLINE_ -> "Online"
        USER -> "User"
        EMAIL_ALREADY_EXISTS -> "Failed to update email. Email already exists."
        IN -> "in"
        VERIFYING_OTP -> "Verifying OTP"
        TRACK_LIVE_LOCATION_USING -> "Track live location using"
        GOOGLE_MAP_ -> "Google Map"
        IN_APP_TRACKING -> "In app tracking"
        QUOTE_EXPIRED -> "Quote Expired"
        GETTING_ESTIMATES_FOR_YOU -> "Getting estimates for you..."
        CONFIRM_PICKUP_LOCATION -> "Confirm Pickup Location"
        CONFIRM_DROP_LOCATION -> "Confirm Drop Location"
        ERROR_OCCURED_TRY_AGAIN -> "Error Occured. Try Again"
        ASKED_FOR_MORE_MONEY -> "Asked for more money"
        START_ -> "Start"
        RIDE_NOT_SERVICEABLE -> "Ride Not Serviceable"
        APP_NOT_SERVICEABLE -> "Not Serviceable"
        CONFIRM_FOR -> "Confirm for"
        ETA_WAS_TOO_SHORT -> "ETA was too short."
        DRIVER_REQUESTED_TO_CANCEL -> "Driver requested me to cancel"
        PICK_UP_LOCATION_INCORRECT -> "The pickup location was incorrect."
        COULD_NOT_CONNECT_TO_DRIVER -> "I could not connect to driver."
        ETA_WAS_TOO_LONG -> "ETA was too long."
        OTHERS -> "Others"
        DESTINATION_OUTSIDE_LIMITS -> "Destination Entered is outside city limits"
        DROP_LOCATION_FAR_AWAY -> "Your drop location is too far away"
        CHANGE_DROP_LOCATION -> "Change Drop Location"
        YOU_CAN_TAKE_A_WALK_OR_CONTINUE_WITH_RIDE_BOOKING -> "You may wish to walk or continue with the ride booking"
        YOUR_TRIP_IS_TOO_SHORT_YOU_ARE_JUST -> "Your trip distance is too short. Destination is just "
        METERS_AWAY_FROM_YOUR_DESTINATION -> "m away!"
        BOOK_RIDE_ -> "Book Ride"
        CANCEL_AUTO_ASSIGNING -> "Cancel Auto Assigning"
        LOCATION_UNSERVICEABLE -> "Location unserviceable"
        CURRENTLY_WE_ARE_LIVE_IN_ _  -> "We are not live in your area yet!\nYou can access ride history and other settings from the menu"
        CHANGE_LOCATION -> "Change Location"
        AUTO_ACCEPTING_SELECTED_RIDE -> "Auto accepting in"
        THE_TRIP_IS_VERY_SHORT_AND_JUST_TAKE -> "The trip is very short and just take"
        IF_YOU_STILL_WANNA_BOOK_RIDE_CLICK_CONTINUE_AND_START_BOOKING_THE_RIDE -> "if you still want to book, click continue and start booking the ride"
        STEPS_TO_COMPLETE -> "Steps to complete"
        HELP_US_WITH_YOUR_REASON -> "Help us with your reason"
        MAX_CHAR_LIMIT_REACHED -> "Max character limit reached,"
        DRIVER_WAS_NOT_REACHABLE -> "Driver wasn't reachable"
        SHOW_ALL_OPTIONS -> "Show all options"
        EXPIRES_IN -> "Expires in"
        PAY_DIRECTLY_TO_YOUR_DRIVER_USING_CASH_UPI -> "*Pay directly to your driver using Cash / UPI"
        UPDATE_REQUIRED -> "Update Required"
        PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE -> "We're excited to announce that there's a new update available for our app. This update includes a fresh new design and several new features to make your experience even better."
        NOT_NOW -> "Not Now"
        OF -> "of"
        LOST_SOMETHING -> "Lost Something?"
        TRY_CONNECTING_WITH_THE_DRIVER -> "You can request a callback from driver"
        CALL_DRIVER -> "Call Driver"
        NO_MORE_RIDES -> "No more rides"
        CONTACT_SUPPORT -> "Contact Support"
        INVALID_MOBILE_NUMBER -> "Invalid mobile number"
        RIDE_COMPLETED -> "Ride Completed"
        SUBMIT_FEEDBACK -> "Submit Feedback"
        HOW_WAS_YOUR_RIDE_EXPERIENCE -> "How was your ride experience?"
        DROP -> "Drop"
        RATE_YOUR_RIDE_WITH -> "Rate your ride with "
        VIEW_BREAKDOWN -> "View Breakdown"
        PAY_DRIVER_USING_CASH_OR_UPI -> "Pay Driver using Cash/UPI"
        PAY_DRIVER_USING_CASH_OR_UPI_ -> "Pay Driver using Cash/UPI"
        RATE_YOUR_DRIVER -> "Rate Your Driver"
        MY_RIDES -> "My Rides"
        RIDE_DETAILS -> "Ride Details"
        RIDE_ID -> "Ride ID"
        SELECT_A_RIDE -> "Select a ride for more details"
        CONFIRM_RIDE_ -> "Confirm Ride"
        YOU_CAN_CANCEL_RIDE -> "You can cancel once you get offers from drivers"
        ESTIMATES_CHANGED -> "The estimate for your ride has changed now"
        ESTIMATES_REVISED_TO -> "The revised estimate is"
        RATE_CARD -> "Rate Card"
        NIGHT_TIME_CHARGES -> "Night-time Charges (10 PM to 5 AM)"
        MIN_FARE_UPTO -> "Min. Fare upto"
        MORE_THAN -> "More than"
        RATE_ABOVE_MIN_FARE -> "Rate above Min. Fare"
        DRIVER_PICKUP_CHARGES _ -> "Driver Pickup Charges"
        DAY_TIMES_OF -> ""
        DAYTIME_CHARGES_APPLICABLE_AT_NIGHT -> "x of daytime charges applicable at night from 10 PM to 5 AM"
        NIGHT_TIMES_OF -> ""
        DAYTIME_CHARGES_APPLIED_AT_NIGHT -> "x of daytime charges applied to fare at night (🌙) from 10 PM to 5 AM"
        DRIVERS_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "* Driver may optionally request 10% of base fare (rounded to nearest Rs.10) to cover for traffic, chance of return trip etc."
        GOT_IT -> "Got It!"
        DAY_TIME_CHARGES -> "Daytime Charges (5 AM to 10 PM)"
        SHARE_APP -> "Share App"
        AWAY_C -> "Away"
        AWAY -> "away"
        AT_PICKUP -> "At Pickup"
        FARE_UPDATED -> "Fare has been updated"
        TOTAL_FARE_MAY_CHANGE_DUE_TO_CHANGE_IN_ROUTE -> "Total fare may change due to change in route"
        AT_DROP -> "At Drop"
        EMERGENCY_HELP -> "Emergency Help"
        ALSO_SHARE_YOUR_RIDE_STATUS_AND_LOCATION -> "Also shares your ride status and location"
        SHARE_RIDE_WITH_EMERGENCY_CONTACTS -> "Share Ride with Emergency Contacts"
        DO_YOU_NEED_EMERGENCY_HELP -> "Do you need Emergency Help ?"
        CALL_SUPPORT -> "Call Support"
        YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT _  -> "You are about to place a call to the Namma Yatri Support Team. Do you want to proceed?"
        YOU_ARE_ABOUT_TO_CALL_NEAREST_EMERGENCY_CENTRE -> "You are about to place a call to the nearest Emergency Centre. Do you want to proceed?"
        DIAL_112 -> "Dial 112"
        HELP_US_WITH_YOUR_FEEDBACK_OPTIONAL -> "Help us with your feedback (Optional)"
        WAIT_TIME -> "Wait Time"
        FAVOURITES -> "Favourites"
        ADD_FAVOURITE -> "Add Favourite"
        ALL_FAVOURITES -> "All Favourites"
        REMOVE -> "Remove"
        CONFIRM_LOCATION -> "Confirm Location"
        SELECT_ON_MAP -> "Select on map"
        FAVOURITE_LOCATION -> "Favourite Location"
        EDIT_FAVOURITE -> "Edit favourite"
        DRAG_THE_MAP -> "Drag the map & set pin to exact location"
        CHOOSE_ON_MAP -> "Choose on map"
        USE_CURRENT_LOCATION -> "Use current location"
        FAVOURITE_YOUR_CURRENT_LOCATION -> "Favourite your current location"
        LOCATION -> "Location"
        LOCATION_ALREADY_EXISTS_AS -> "Location already exists as"
        GIVE_THIS_LOCATION_A_NAME -> "Give this location a name"
        FAVOURITE -> "Favourite"
        CONFIRM_AND_SAVE -> "Confirm & Save"
        REMOVE_FAVOURITE -> "Remove Favourite"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_FAVOURITE_ -> "Are you sure you want to remove a \n favourite location?"
        YES_REMOVE -> "Yes, Remove"
        ADD_NEW_FAVOURITE -> "Add New Favourite"
        SELECT_YOUR_DROP -> "Select your drop"
        FAVOURITE_REMOVED_SUCCESSFULLY -> "Favourite Removed Successfully"
        LOCATION_ALREADY_EXISTS -> "location already exists"
        LOCATION_ALREADY -> "Location already"
        EXISTS_AS -> "exists as"
        FAVOURITE_ADDED_SUCCESSFULLY -> "Favourite Added Successfully"
        FAVOURITE_UPDATED_SUCCESSFULLY -> "Favourite Updated Successfully"
        ALREADY_EXISTS -> "Already Exists"
        NAME_ALREADY_IN_USE -> "Name already in-use"
        SELECT_FAVOURITE -> "Select Favourite"
        CONFIRM_CHANGES -> "Confirm Changes"
        ADD_SAVED_LOCATION_FROM_SETTINGS -> "*You can add new favourites from Side menu > Favourites"
        YOU_WILL_BE_ASKED_TO_SELECT_CONTACTS -> "You will be asked to select upto 3  contacts"
        AUTO_ASSIGN_A_RIDE -> "Auto-assign a ride"
        IS_WAITING_AT_PICKUP -> "is waiting at pick up"
        WAIT_TIME_TOO_LONG -> "Wait time too long"
        GOT_ANOTHER_RIDE_ELSE_WHERE -> "Got another ride elsewhere"
        DRIVER_WAS_RUDE -> "Driver was rude"
        MAYBE_LATER -> "Maybe Later"
        YOUR_RIDE_HAS_STARTED -> "Yay! Your ride has started 🤩"
        ENJOY_RIDING_WITH_US -> "Enjoying riding with us? Spread the \n word and share the cheer"
        VIEW_DETAILS -> "View Details"
        REPEAT_RIDE -> "Repeat Ride"
        FARE_WAS_HIGH -> "Fare was high"
        AUTO_ASSIGN_DRIVER -> "Auto-assign a driver"
        CHOOSE_BETWEEN_MULTIPLE_DRIVERS -> "Choose between multiple drivers"
        CHOOSE_BETWEEN_MULTIPLE_RIDES -> "Choose between multiple ride options"
        ENABLE_THIS_FEATURE_TO_CHOOSE_YOUR_RIDE -> "Enable this feature to choose your preferred ride & fare"
        BOOKING_PREFERENCE -> "Booking Preference"
        BASE_FARES -> "Base Fare "
        PICKUP_CHARGE -> "Driver Pickup Charges"
        TOTAL_PAID -> "Total Paid"
        WAITING_CHARGE -> "Waiting Charges"
        NOMINAL_FARE -> "Optional Driver Request*"
        CUSTOMER_CANCELLATION_DUES -> "Cancellation Dues"
        DRIVERS_CAN_CHARGE_AN_ADDITIONAL_FARE_UPTO -> "* Drivers may optionally request 10% of base fare (rounded to nearest Rs.10) to cover other factors like traffic, chances of return trip etc."
        WAITING_CHARGE_DESCRIPTION -> "°Waiting charge is zero for the first 3 minutes. You will be charged ₹1.5 per minute of wait time after that."
        WAITING_CHARGE_RATECARD_DESCRIPTION -> "1. Waiting Charge is zero for the first 3 minutes.\n 2. Waiting Charge of ₹1.5 per minute will be applicable thereafter."
        FARE_POLICY_WAITING_CHARGES -> "Applicable @ ₹1.5 per minute after the first 3 minutes of waiting"
        SUCCESSFUL_ONBOARD _ -> "You have successfully signed on to \nNamma Yatri"
        HAVE_REFERRAL_CODE -> "Have a Referral Code?"
        REFEREAL_CODE_DISCRIPTION -> "Your referral might just be the reason for \n a driver to be rewarded!"
        SIX_DIGIT_REFERRAL_CODE -> "Enter 6 digit code shared by driver"
        ABOUT_REFERRAL_PROGRAM -> "What is the Referral Program?"
        ABOUT_REFERRAL_PROGRAM_DISCRIPTION _ -> "The referral program incentivises drivers to accept more rides, cancel less and serve you better by recognising and rewarding worthy drivers. \n\n You can help out by entering the driver’s referral code  and improve the quality of rides for the Namma Yatri Community!"
        YOU_CAN_GET_REFERRAL_CODE_FROM_DRIVER _ -> "\nYou can get a referral code by asking your Namma Yatri Driver."
        REFERRAL_CODE_SUCCESSFULL -> "You have successfully applied \nthe referral code!"
        REFERRAL_CODE_APPLIED -> "Referral Applied!"
        HEY -> "Hey"
        INVALID_CODE_PLEASE_RE_ENTER -> "Invalid Code. Please Re-enter"
        LET_TRY_THAT_AGAIN -> "Let's try that again..."
        CONTACTS_SELECTED -> "Contacts Selected"
        SELECT_CONTACTS -> "Select Contacts"
        CONFIRM_EMERGENCY_CONTACTS -> "Confirm Emergency Contacts"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_CONTACT -> "Are you sure you want to remove them from your emergency contacts?"
        SEARCH_CONTACTS -> "Search Contacts"
        CALL_EMERGENCY_CONTACTS -> "Call Emergency Contacts"
        LIVE_STATS_DASHBOARD -> "Live Stats Dashboard"
        CHECK_OUT_LIVE_STATS -> "Check out live stats"
        EMERGENCY_CONTACS_ADDED_SUCCESSFULLY -> "Emergency Contacts Added Successfully"
        NO_CONTACTS_LEFT_ON_DEVICE_TO_ADD -> "No contacts left on device to add"
        PERCENTAGE_OF_NOMINAL_FARE -> "10% of base fare"
        PAY_VIA_CASH_OR_UPI -> "Pay via Cash / UPI"
        REQUEST_CALLBACK -> "Request Callback"
        CHOOSE_YOUR_RIDE -> "Choose your ride"
        BOARD_THE_FIRST -> "Board the first "
        TAXI -> "taxi" 
        AC -> "AC"
        NON_AC -> "Non-AC"
        TAXI_FROM_ZONE key -> "from your nearest Zone"
        ECONOMICAL -> "Economical"
        COMFY -> "Comfy"
        NAVIGATE -> "Navigate"
        GOVERNMENT_CHAGRES -> "Ride GST (5%)"
        SERVICE_CHARGES -> "Service Charges"
        CONFIRM_AND_BOOK -> "Confirm & Book"
        PEOPLE -> "people"
        SPACIOUS -> "Spacious"
        CANCEL_ONGOING_SEARCH -> "Are you sure you want to continue with cancelling an ongoing search?"
        SEARCH_AGAIN_WITH_A_TIP -> "Search again with a tip?"
        TRY_AGAIN_WITH_A_TIP -> "Try again with a tip?"
        BOOST_YOUR_RIDE_CHANCES_AND_HELP_DRIVERS_WITH_TIPS -> "It seems to be a very busy day. You may try adding a tip to increase chances of getting a ride."
        TRY_AGAIN_WITHOUT_TIP -> "Try Again Without Tip"
        SEARCH_AGAIN_WITHOUT_A_TIP -> "Search Again Without Tip"
        TRY_AGAIN_WITH -> "Try Again With"
        SEARCH_AGAIN_WITH -> "Search Again With"
        TIP -> "Tip"
        CUSTOMER_SELECTED_FARE -> "Customer Tip^"
        START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS -> "Start your chat using these quick chat suggestions"
        MESSAGE -> "Message"
        START_YOUR_CHAT_WITH_THE_DRIVER -> "Start your chat with the driver"
        I_AM_ON_MY_WAY -> "I'm on my way"
        GETTING_DELAYED_PLEASE_WAIT -> "Getting delayed, please wait"
        UNREACHABLE_PLEASE_CALL_BACK -> "Unreachable, Please call back"
        ARE_YOU_STARING -> "Are you starting?"
        PLEASE_COME_SOON -> "Please come soon"
        OK_I_WILL_WAIT -> "Ok, I'll wait"
        I_HAVE_ARRIVED -> "I've arrived"
        PLEASE_COME_FAST_I_AM_WAITING -> "Please come fast, I'm waiting"
        PLEASE_WAIT_I_WILL_BE_THERE -> "Please wait, I'll be there"
        LOOKING_FOR_YOU_AT_PICKUP -> "Looking for you at pick-up"
        MOBILE -> "Mobile"
        HOW_DO_YOU_IDENTIFY_YOURSELF -> "How do you identify yourself as?"
        SELECT_YOUR_GENDER -> "Select Your Gender"
        FEMALE -> "Female"
        MALE -> "Male"
        PREFER_NOT_TO_SAY -> "Prefer not to say"
        EMAIL_ID -> "Email ID"
        SET_NOW -> "Set now"
        ADD_NOW -> "Add now"
        HOW_SHOULD_WE_ADDRESS_YOU -> "How should we address you?"
        GENDER_STR -> "Gender"
        PROFILE_COMPLETION -> "Profile Completion"
        EARLY_END_RIDE_CHARGES -> "Early Ride End Charges^"
        EARLY_END_RIDE_CHARGES_DESCRIPTION -> "^Ending a ride early incurs additional charges amounting to half the fare of the untravelled distance (max. ₹50)"
        YES_TRY_AGAIN -> "Yes, Try Again"
        NO_DONT -> "No, Don’t"
        YES_CANCEL_SEARCH -> "Yes, Cancel Search"
        TRY_LOOKING_FOR_RIDES_AGAIN -> "It seems to be a very busy day. You may try looking for rides again"
        NO_TIP -> "₹0 Tip"
        CUSTOMER_TIP_DESCRIPTION -> "^Extra amount added by the customer to increase the chances of getting a ride."
        PLACE_CALL -> "Place Call"
        DIRECT_CALL -> "Direct Call"
        ANONYMOUS_CALL -> "Anonymous Call"
        YOUR_NUMBER_WILL_NOT_BE_SHOWN_TO_THE_DRIVER_THE_CALL_WILL_BE_RECORDED_FOR_COMPLIANCE -> "Your number will not be shown to the driver. The call will be recorded for compliance."
        YOUR_NUMBER_WILL_BE_VISIBLE_TO_THE_DRIVER_USE_IF_NOT_CALLING_FROM_REGISTERED_NUMBER -> "Your number will be visible to the driver. Use if not calling from registered number."
        CALL_DRIVER_USING -> "Call Driver using"
        WAS_YOUR_CALL_SUCCESSFUL -> "Was Your Call Successful"
        DRIVER_ADDITIONS -> "Driver Additions*"
        FARE_UPDATE_POLICY -> "Fare Update Policy"
        DRIVER_ADDITIONS_OPTIONAL -> "Driver Additions (Optional)"
        THE_DRIVER_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "The Driver may quote extra to cover for traffic, chance of return trip etc."
        DRIVER_ADDITIONS_ARE_CALCULATED_AT_RATE _ -> "Driver addition limits are calculated at 10% of the base fare rounded off to the nearest ₹10"
        DRIVER_MAY_NOT_CHARGE_THIS_ADDITIONAL_FARE -> "Note The driver may/may not charge this additional fare"
        YOU_MAY_SEE_AN_UPDATED_FINAL_FARE_DUE_TO_ANY_OF_THE_BELOW_REASONS -> "You may see an updated final fare due to any of the below reasons"
        REASON_CHANGE_IN_ROUTE_A -> "1.Change in Route "
        REASON_CHANGE_IN_ROUTE_B -> "Total fare may change due to change in route"
        GO_TO_ZONE _ -> "Navigate to pickup zone"
        UPDATE_NOW -> "Update Now"
        REQUEST_RECEIVED_WE_WILL_CALL_YOU_BACK_SOON -> "Request received. We will call you back soon"
        CONTACT_REMOVED_SUCCESSFULLY -> "Contact Removed Successfully"
        CORPORATE_ADDRESS -> "Corporate Address"
        CORPORATE_ADDRESS_DESCRIPTION _ -> "Juspay Technologies Private Limited <br> Girija Building, Number 817, Ganapathi Temple Rd, 8th Block, Koramangala, Bengaluru, Karnataka 560095, India."
        CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL _ ->  "Website <u>https://nammayatri.in/</u>"
        REGISTERED_ADDRESS -> "Registered Address"
        REGISTERED_ADDRESS_DESCRIPTION _ -> "Juspay Technologies Private Limited <br> Stallion Business Centre, No. 444, 3rd & 4th Floor, 18th Main, 6th Block, Koramangala Bengaluru, Karnataka- 560095, India."
        REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL _ -> "Website <u>https://nammayatri.in/</u>"
        RECOMMENDED -> "Recommended"
        COMPLETE_YOUR_PROFILE_FOR_A_PERSONALISED_RIDE_EXPERIENCE -> "Complete your profile for a personalised ride experience"
        WE_WOULD_APPRECIATE_YOUR_FEEDBACK -> "We would appreciate your reasoning behind account deletion"
        REASON_FOR_DELETING_ACCOUNT -> "Reason for deleting account*"
        SUBMIT_REQUEST -> "Submit Request"
        PLEASE_ENTER_A_VALID_EMAIL -> "Please enter a valid email"
        WE_WOULD_APPRECIATE_YOUR_REASONING -> "We would appreciate your feedback on your reasoning behind account deletion"
        OK_GOT_IT -> "Ok, Got it"
        WAIT_FOR_DRIVER -> "Wait For Driver"
        NO_LONGER_REQUIRE_A_RIDE_DUE_TO_CHANGE_IN_PLANS -> "No longer require a ride due to change in plans"
        CANCELLING_AS_I_GOT_A_RIDE_ON_ANOTHER_APP -> "Cancelling as I got a ride on another app"
        DRIVER_LOCATION_WASNT_CHANGING_ON_THE_MAP -> "Driver location wasn`t changing on the map"
        DRIVER_WAS_TAKING_TOO_LONG_TO_REACH_THE_PICKUP_LOCATION -> "Driver was taking too long to reach the pickup location"
        THE_PICKUP_LOCATION_ENTERED_WAS_WRONG -> "The pickup location entered was wrong"
        YOUR_DRIVER_IS_JUST -> "Your Driver is just "
        M_AWAY -> " m away."
        DRIVER_HAS_ALREADY_TRAVELLED -> "Driver has already travelled "
        PLEASE_CONTACT_THE_DRIVER_BEFORE_CANCELLING -> "\nPlease contact the driver before cancelling"
        CHANGE_OF_PLANS -> "Change of plans"
        DRIVER_IS_NOT_MOVING -> "Driver is not moving"
        WRONG_PICKUP_LOCATION -> "Wrong pickup location"
        DRIVER_MIGHT_BE_TAKING_ALTERNATE_ROUTE -> "Driver might be taking an alternate route."
        DRIVER_IS_NOT_MOVING_Q -> "Driver is not moving?"
        WOULD_YOU_LIKE_TO_CHECK_WITH_THE_DRIVER_BEFORE_CANCELLING -> "\nWould you like to check with the driver before cancelling?"
        DRIVER_IS_NEAR_YOUR_LOCATION -> "Driver is near your location."
        SOME_OTHER_REASON -> "Some other reason."
        LOCATION_PERMISSION_SUBTITLE_NEW_USER _ -> "Welcome to Namma Yatri! \nTo start booking rides, we require your device location."
        METRO_RIDE -> "Metro Ride"
        GO_BACK_TEXT -> "Go Back"
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_JUST -> "The driver preferred your special request and is just "
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST -> "The driver preferred your special request and has travelled "
        AND_HAS_TRAVELLED -> "."
        PLEASE_FIND_REVISED_FARE_ESTIMATE -> "Please find the Revised Estimated Fare. Night charges are 1.5 times the day charges."
        FARE_ESTIMATE -> "Fare Estimate"
        TIP_SELECTED -> "Tip Selected"
        ADD_A_TIP_TO_FIND_A_RIDE_QUICKER -> "Add a tip to find a ride quicker!"
        IT_SEEMS_TO_BE_TAKING_LONGER_THAN_USUAL -> "It seems to be taking longer than usual."
        CONTINUE_SEARCH_WITH -> "Continue Search with"
        CONTINUING_SEARCH_WITH -> "Continuing search with"
        SEARCHING_WITH -> "Searching with"
        THE_DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION -> "The driver preferred your special request and is already on the way to your location."
        DRIVER_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION -> "Driver is already on the way to your location."
        ALLOW_LOCATION_ACCESS -> "Allow Location Access"
        MESSAGE_FROM_DRIVER -> "Message from Driver"
        REPLY -> "Reply"
        NAME_SHOULD_BE_MORE_THAN_2_CHARACTERS -> "Name should be more than 2 characters"
        THIS_FIELD_IS_REQUIRED -> "This field is required"
        EMAIL_EXISTS_ALREADY -> "Email already exists"
        OKAY_GOT_IT -> "Ok, Got it"
        CALL_NAMMA_YATRI_SUPPORT _ -> "Call Namma Yatri Support"
        CALL_112 -> "Call 112"
        CALL_EMERGENCY_CENTRE -> "Call Emergency Centre"
        SEATS -> "Seats"
        DRIVER_ADDITION_LIMITS_ARE_IN_INCREMENTS -> "Driver addition limits are in increments of ₹20"
        HATCHBACK -> "Hatchback"
        SUV -> "SUV"
        SEDAN -> "Sedan"
        OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN -> "OTP page has been expired, please request OTP again"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER -> "OTP entering limit exhausted, please try again later"
        TOO_MANY_LOGIN_ATTEMPTS_PLEASE_TRY_AGAIN_LATER -> "Too many login attempts, please try again later"
        SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN -> "Something went wrong, please try again"
        SORRY_LIMIT_EXCEEDED_YOU_CANT_ADD_ANY_MORE_FAVOURITES -> "Sorry, limit exceeded. You can't add any more favourites"
        CANCELLATION_UNSUCCESSFULL_PLEASE_TRY_AGAIN -> "Cancellation unsuccessfull, please try again"
        NO_DRIVER_AVAILABLE_AT_THE_MOMENT_PLEASE_TRY_AGAIN -> "No drivers available at the moment, please try again"
        OTP_FOR_THE_JATRI_SATHI_ZONE_HAS_BEEN_EXPIRED_PLEASE_TRY_LOOKING_AGAIN _ -> "OTP for the Jatri Sathi zone has been expired, please try booking again"
        NO_CONTACTS_FOUND_ON_THE_DEVICE_TO_BE_ADDED -> "No contacts found on the device to be added"
        PLEASE_ENABLE_CONTACTS_PERMISSION_TO_PROCEED -> "Please enable contacts permission to proceed"
        LIMIT_REACHED_3_OF_3_EMERGENCY_CONTACTS_ALREADY_ADDED -> "Limit reached! 3 of 3 Emergency contacts already added"
        INVALID_CONTACT_FORMAT -> "Invalid contact format"
        OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER -> "OTP resend limit exhausted, please try again later"
        RATE_YOUR_EXPERIENCE -> "Rate your experience ✨"
        REPORT_ISSUE_ -> "Report Issue"
        DONE -> "Done"
        PLEASE_TELL_US_WHAT_WENT_WRONG -> "Please tell us what went wrong"
        DID_YOU_FACE_ANY_ISSUE -> "Did you face any issue?"
        WE_NOTICED_YOUR_RIDE_ENDED_AWAY -> "We noticed  that your ride ended away from your original destination."
        GET_CALLBACK_FROM_US -> "Get a callback from us"
        DRIVER_WAS_NOT_READY_TO_GO -> "The driver was not to ready to go"
        ASKING_FOR_MORE_MONEY -> "Driver was asking for more money"
        AUTO_BROKEN -> "Auto broke down"
        WE_WILL_GIVE_YOU_CALLBACK -> "We will give you a callback within 24 hrs"
        YOUR_ISSUE_HAS_BEEN_REPORTED -> "Your issue has been reported successfully"
        OTP_RESENT_SUCCESSFULLY -> "OTP resent successfully"
        DESCRIPTION_SHOULD_BE_MORE_THAN_10_ALPHABETIC_CHARACTERS -> "Description should be more than 10 alphabetic characters"
        IT_SEEMS_LIKE_YOU_HAVE_AN_ONGOING_RIDE_ -> "It seems that you have an on-going booking, please restart the app to view it"
        INCORRECT_OTP_PLEASE_TRY_AGAIN -> "Incorrect OTP, please try again."
        N_MORE_ATTEMPTS_LEFT -> " more attempts left"
        GO_TO_SELECTED_PICKUP_SPOT -> "Go to selected pickup spot"
        GO_TO_SELECTED_PICKUP_SPOT_AS_AUTOS_ARE_RESTRICTED -> "Go to the suggested pickup spot as Autos are restricted inside this area"
        UNPROFESSIONAL_DRIVER -> "Unprofessional Driver"
        RASH_DRIVING -> "Rash Driving"
        DRIVER_CHARGED_MORE -> "Driver charged more"
        UNCOMFORTABLE_AUTO -> "Uncomfortable Auto"
        TRIP_GOT_DELAYED -> "Trip Got Delayed"
        FELT_UNSAFE -> "Felt Unsafe"
        POLITE_DRIVER -> "Polite Driver"
        EXPERT_DRIVING -> "Expert Driving"
        SAFE_RIDE -> "Safe Ride"
        CLEAN_AUTO -> "Clean Auto"
        ON_TIME -> "On Time"
        SKILLED_NAVIGATOR -> "Skilled Navigator"
        RUDE_DRIVER -> "Rude Driver"
        TOO_MANY_CALLS -> "Too Many Calls"
        RECKLESS_DRIVING -> "Reckless Driving"
        LATE_DROP_OFF -> "Late Drop Off"
        LATE_PICK_UP -> "Late Pick Up"
        POOR_EXPERIENCE -> "Poor Experience 😕"
        TERRIBLE_EXPERIENCE -> "Terrible Experience 😠"
        NEEDS_IMPROVEMENT -> "Needs Improvement 😕"
        ALMOST_PERFECT -> "Almost Perfect! 🙂"
        AMAZING -> "Amazing!!! 🤩"
        ASKED_FOR_EXTRA_FARE ->  "Asked for Extra Fare"
        ANYTHING_THAT_YOU_WOULD_LIKE_TO_TELL_US -> "Anything that you would like to tell us? (Optional)"
        PLEASE_WAIT -> "Please wait"
        PLATFORM_FEE -> "Platform Fee"
        FINDING_QUOTES_TEXT -> "Searching for cabs around"
        FASTER -> "Faster"
        NEW_ -> "New"
        SGST -> "SGST"
        OTP_EXPIRED -> "Otp Expired"
        OTP_EXPIRED_DESCRIPTION -> "Your ride OTP expired. Please book again to get a ride"
        PLATFORM_GST -> "Taxes (GST)"
        MISC_WAITING_CHARGE -> "Waiting Charges"
        AC_TAXI -> "AC Taxi"
        NON_AC_TAXI -> "Non AC Taxi"
        GET_OTP_VIA_WHATSAPP -> "Get OTP via WhatsApp"
        OR -> "Or"
        HELPS_DRIVER_CONFIRM_ITS_YOU -> "(Helps driver confirm it is you)"
        LETS_GET_YOU_TRIP_READY -> "Let’s get you trip-ready!"
        GOT_AN_OTP -> "Got an OTP?"
        JUST_ONE_LAST_THING -> "Just one last thing"
        YOUR_FEEDBACK_HELPS_US _ -> "Your feedback helps us improve the app experience"
        TOLL_CHARGES_WILL_BE_EXTRA -> "Toll/Parking charges will be additional"
        AUTO_RICKSHAW -> "Auto Rickshaw"
        CABS_AVAILABLE -> "cabs available"
        PI_POINTER_1 -> "Drivers will be prompted to come to your exact location for pickup."
        PI_POINTER_2 -> "Drivers will be prompted to help you with your mobility aid."
        VI_POINTER_1 -> "Drivers will be prompted to call instead of texting."
        VI_POINTER_2 -> "Drivers will be prompted to sound horn once at the pickup."
        HI_POINTER_1 -> "Drivers will be prompted to text instead of calling."
        HI_POINTER_2 -> " Drivers will be prompted to message you once at the pickup."
        DID_THE_DRIVER_OFFER_ASSISTANCE -> "Did the driver offer assistance?"
        WAS_THE_DRIVER_UNDERSTANDING_OF_YOUR_NEEDS -> "Was your driver understanding of your needs and accomodate them on the journey?"
        GENERAL_DISABILITY_DESCRIPTION -> "Drivers will be sensitised to help you with your needs and requests."
        ACCESSIBILITY_TEXT _-> "Namma Yatri, now customised for you!"
        TO_CATER_YOUR_SPECIFIC_NEEDS _ -> "To cater to your specific needs, we have customised certain features of Namma Yatri."
        SPECIAL_ASSISTANCE -> "Special Assistance"
        SELECT_THE_CONDITION_THAT_IS_APPLICABLE -> "Select the condition that is applicable to you\n(As per RPWD act 2016)"
        DISABILITY_CLAIMER_TEXT -> "By continuing, you are declaring your status as a person with disability under the RPWD act of 2016"
        ARE_YOU_A_PERSON_WITH_DISABILITY -> "Are you a person with disability?"
        DO_YOU_NEEED_SPECIAL_ASSISTANCE -> "Do you require special assistance (Person With Disability)?"
        ASSISTANCE_REQUIRED -> "Assistance Required (Person with Disability)"
        NO_DISABILITY -> "No Disability"
        LEARN_HOW_TEXT _ -> "Learn how Namma Yatri caters to your needs"
        UPDATE_PROFILE -> "Update Profile"
        NOW_GET_ASSISTED_RIDES -> "Now get assisted rides if you are a person with disability" 
        SENT_OTP_VIA_WHATSAPP -> "OTP Sent via Whatsapp"
        SENT_OTP_VIA_SMS -> "OTP Sent via SMS"
        ENABLE_LOCATION_PERMISSION_TO -> "Enable Location Permission to Search for Rides"
        AC_CAB -> "AC Cab"
        AC_SUV -> "AC SUV"
        RIDE_TYPE -> "Ride Type"
        ERNAKULAM_LIMIT_CHARGE -> "Fare will be 1.5x if the pickup or destination lies outside Ernakulam corporation limits"
        SELECT_LOCATION_ON_MAP -> "Select location on map"
        DOWNLOAD_DRIVER_RECEIPT -> "Download Driver Receipt"
        VIEW_DRIVER_RECEIPT -> "View Driver Receipt"
        DRIVER_RECEIPT -> "Driver Receipt"
        HELP -> "Help"
        FARE_INFO_TEXT _ -> ""
        PLEASE_ENABLE_LOCATION_PERMISSION _ -> "Please enable location permissions from the settings app to start looking for rides."
        EDUCATIONAL_POP_UP_SLIDE_1_TITLE -> "We strive to provide all our users \nan even & equal experience."
        EDUCATIONAL_POP_UP_SLIDE_2_TITLE -> "For users with poor vision"
        EDUCATIONAL_POP_UP_SLIDE_3_TITLE -> "For users with poor hearing"
        EDUCATIONAL_POP_UP_SLIDE_4_TITLE -> "For users with locomotor disability"
        EDUCATIONAL_POP_UP_SLIDE_5_TITLE -> "For users with other special needs"
        EDUCATIONAL_POP_UP_SLIDE_1_SUBTITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_2_SUBTITLE -> "&#8226; Drivers will be prompted to call instead <br> &ensp; of texting. <br> &#8226; Drivers will be prompted to sound horn <br> &ensp;  once at the pickup. <br> &#8226; Drivers will be sensitised to help them with <br> &ensp;  their needs and requests."
        EDUCATIONAL_POP_UP_SLIDE_3_SUBTITLE -> "&#8226; Drivers will be prompted to text instead <br> &ensp;  of calling. <br> &#8226; Drivers will be prompted to message them <br> &ensp;  once at the pickup. <br> &#8226; Drivers will be sensitised to help them with <br> &ensp; their needs and requests."
        EDUCATIONAL_POP_UP_SLIDE_4_SUBTITLE -> "&#8226; Drivers will be prompted to come to their <br> &ensp;  exact location for pickup. <br> &#8226; Drivers will be prompted to help them <br> &ensp;  with their mobility aid. <br>&#8226; Drivers will be sensitised to help them with <br> &ensp; their needs and requests."
        EDUCATIONAL_POP_UP_SLIDE_5_SUBTITLE -> "&#8226; We will be collecting other types of <br> &ensp; disabilities and shall be incorporating them <br> &ensp; among the list of disabilities available <br> &ensp; as needed."
        INCLUSIVE_AND_ACCESSIBLE -> "Inclusive and Accessible, for everyone!"
        MY_TICKETS -> "My Tickets"
        YOU_CAN_BOOK_TICKETS_TO_THE_ZOO_BY_CLICKING_THE_BUTTON -> "You can book tickets to the Zoo by clicking the button."
        SOMETHING_WENT_WRONG_TRY_AGAIN_LATER -> "Something went wrong, please try again later"
        YOU_SEEM_TO_BE_FAR_FROM_PICK_UP -> "You seem to be far from the pickup location!"
        ARE_YOU_SURE_YOU_WANT_TO_PROCEED_WITH_THE_BOOKING -> "Are you sure you want to proceed with the booking?"
        PAY_DRIVER_USING_WALLET -> ""
        CHARGES_APPLICABLE_AFTER_3_MINS -> "Charges applicable after 3 mins"
        REACHING_YOUR_DESTINATION_IN_ -> "Arriving at your destination in "
        WAITING_AT_PICKUP -> "is waiting at pickup "
        PICKUP -> "Pickup"
        PAY_BY_CASH_OR_UPI -> "Pay by Cash / UPI "
        YOU_WILL_PAY_FOR_EVERY_MINUTE -> "Waiting Charge is zero for the first 3 minutes. Waiting Charge of ₹1.5 per minute will be applicable thereafter."
        WAIT_TIMER -> "Wait Timer"
        HOW_LONG_DRIVER_WAITED_FOR_PICKUP -> "Shows you how long the driver has waited at pickup."
        CHAT_WITH -> "Chat with"
        NAMMA_SAFETY -> "Safety"
        QUICK -> "Quick"
        CHATS -> "Chats"
        REPLIES -> "Replies"
        YOU_SENT -> "You Sent"
        MESSAGE_YOUR_DRIVER -> "Message your Driver?"
        CHECK_IN_WITH_YOUR_DRIVER -> "Check in on your driver with a quick chat"
        TRACK_ON_GOOGLE_MAPS -> "Real Time Tracking" 
        OTP_EXPIRE_TIMER -> "OTP Expire Timer"
        SHOWS_FOR_HOW_LONG_YOUR_OTP_ -> "Shows for how long your OTP will remain valid to start the ride."
        IF_YOUR_OTP_EXPIRES_ -> "If your OTP expires, you will need to book again."
        YOU_HAVE_REACHED_DESTINATION -> "You have arrived at your destination"
        PLACES_YOU_MIGHT_LIKE_TO_GO_TO -> "Places you might like to go to."
        DISCOVER_AWESOME_SPOTS_TAILORED_JUST_FOR_YOU -> "Discover awesome spots tailored just for you!"
        SUGGESTED_DESTINATION -> "Suggested Destinations"
        RECENT_RIDES -> "Recent Rides"
        ONE_CLICK_BOOKING_FOR_YOUR_FAVOURITE_JOURNEYS -> "One click booking for your favourite journeys!"
        VIEW_MORE -> "View More"
        VIEW_LESS -> "View Less"
        HAVE_A_REFFERAL -> "Have a Referral?"
        YOUR_SUGGESTED_DESTINATIONS_AND_RECENT_RIDES_WILL_APPEAR_HERE -> "Your Suggested Destinations and Recent Rides will appear here"
        WELCOME_TO_NAMMA_YATRI_ -> "Welcome to Namma Yatri!"
        BOOK_AND_MOVE -> "Book and move,"
        ANYWHERE_IN_THE_CITY -> "anywhere in the city"
        CHECKOUT_OUR_LIVE_STATS -> "Checkout our Live Stats"
        MOST_LOVED_APP _ -> "Most ❤️ Auto app"
        PICKUP_ -> "Pickup: "
        PAST_SEARCHES -> "Past Searches"
        SEARCH_RESULTS -> "Search Results"
        REQUESTING_RIDE_IN -> "Requesting ride in"
        REQUESTING_RIDE -> "Requesting ride"
        TAP_HERE_TO_STOP_AUTO_REQUESTING -> "Tap here to stop auto requesting"
        POWERED_BY -> "Powered By"
        BOOK_YOUR_RIDE -> "Book Your Ride"
        FARE_UPDATED_WITH_CHARGES -> "Fare has been updated to include applicable waiting charges"
        FARE_UPDATED_WITH_SHORTER_DIST -> "Your fare has been updated as your ride was {} km shorter"
        FARE_UPDATED_WITH_LONGER_DIST -> "Your fare has been updated as your ride was {} km longer"
        FARE_UPDATED_WITH_CHARGES_SHORTER_DIST -> "Your fare has been updated as your ride was {} km shorter and wait time charges incurred"
        FARE_UPDATED_WITH_CHARGES_LONGER_DIST -> "Your fare has been updated as your ride was {} km longer and wait time charges incurred"
        START_TYPING_TO_SEARCH_PLACES -> "Start typing to search for places"
        DID_YOU_HAVE_A_SAFE_JOURNEY -> "Did you have a safe journey?"
        TRIP_WAS_SAFE_AND_WORRY_FREE -> "We would like to ensure that your trip was safe and worry free."
        DRIVER_BEHAVED_INAPPROPRIATELY -> "The driver behaved inappropriately"
        I_DID_NOT_FEEL_SAFE -> "I did not feel safe"
        LOOKING_FOR_ANOTHER_RIDE -> "Looking for another ride..."
        THE_RIDE_HAD_BEEN_CANCELLED_WE_ARE_FINDING_YOU_ANOTHER -> "The ride had to be cancelled, we’re finding you another"
        ENJOY_THE_RIDE -> "Enjoy the ride to your destination!"
        RIDE_STARTED -> "Ride started"
        ONE_CLICK -> "1 Click"
        SMART -> "Smart"
        NOT_SERVICEABLE -> "Not Serviceable"
        WE_ARE_NOT_LIVE_IN_YOUR_AREA -> "We are not live in your area yet! \nYou can access ride history and other \nsettings from the menu on the top left."
        FACING_PROBLEM_WITH_APP -> "Facing problems with the app?"
        TAP_HERE_TO_REPORT -> "<u>Tap here to report issue</u>"
        CONFIRM_YOUR_RIDE  -> "Confirm your ride"
        RIDE_SCHEDULED -> "Ride Scheduled"
        RIDE_STARTS_ON -> "Ride Starts on"
        RENTAL_PACKAGE -> "Rental Package"
        GO_HOME -> "Go Home"
        CANCEL_RENTAL_BOOKING -> "Cancel Rental Booking"
        ADD_FIRST_STOP -> "Add First Stop"
        DRIVER_WILL_BE_ASSIGNED_MINUTES_BEFORE_STARTING_THE_RIDE -> "Driver will be assigned {} minutes before starting the ride"
        YOUR_REPORTS -> "Your Reports"
        VIEW -> "View"
        ISSUE_NO -> "Issue No"
        ADD_VOICE_NOTE -> "Add Voice Note"
        VOICE_NOTE -> "Voice Note"
        SUBMIT_ISSUE_DETAILS -> "Submit Issue Details"
        IMAGE_PREVIEW -> "Image Preview"
        ADDED_IMAGES -> "Added Images"
        NO_IMAGES_ADDED -> "No Images Added"
        I_DONT_KNOW_WHICH_RIDE -> "I don't know which ride"
        ADDED_VOICE_NOTE -> "Added Voice Note"
        NO_VOICE_NOTE_ADDED -> "No Voice Note Added"
        CALL_DRIVER_TITLE -> "Call Driver?"
        CALL_SUPPORT_TITLE -> "Call Support?"
        CALL_DRIVER_DESCRIPTION -> "You are about to place a call to the Driver. Do you want to proceed?"
        ADD_IMAGE -> "Add Image"
        ADD_ANOTHER -> "Add Another"
        IMAGES -> "Images"
        ISSUE_SUBMITTED_TEXT -> "Hold on! We are working on solving your issue"
        ISSUE_RESOLVED_TEXT -> "Issue Resolved!"
        CHOOSE_AN_OPTION -> "Choose an option to continue"
        ISSUE_MARKED_AS_RESOLVED -> "Issue marked as resolved!"
        STILL_HAVING_ISSUE -> "Still have an issue?"
        IMAGE -> "Image"
        RECORD_VOICE_NOTE -> "Record Voice Note"
        CANCEL_BUTTON -> "Cancel"
        MAX_IMAGES -> "Maximum 3 images can be uploaded"
        SELECT_A_RIDE_TO_REPORT -> "Select ride to report issue on"
        RIDE_RELATED_ISSUE_PAGE_NAME -> "Ride Related Issue"
        APP_RELATED_ISSUE_PAGE_NAME -> "App Related Issue"
        DRIVER_RELATED_ISSUE_PAGE_NAME -> "Driver Related Issue"
        LOST_AND_FOUND_ISSUE_PAGE_NAME -> "Report Lost Item"
        YEARS_AGO -> "years ago"
        MONTHS_AGO -> "months ago"
        DAYS_AGO -> "days ago"
        HOURS_AGO -> "hrs ago"
        MIN_AGO -> "mins ago"
        SEC_AGO -> "seconds ago"
        REPORTED -> "Reported"
        RESOLVED -> "Resolved"
        RESOLVED_ISSUES -> "Resolved Issues"
        REPORTED_ISSUES -> "Reported Issues"
        SOS_ISSUE_PAGE_NAME -> "SOS Issue"
        FARE_DISCREPANCIES_ISSUE_PAGE_NAME -> "Fare Related Issue"
        PAYMENT_RELATED_ISSUE_PAGE_NAME -> "Payment Related Issue"
        ACCOUNT_RELATED_ISSUE_PAGE_NAME -> "Account Related Issue"
        OTHER_ISSUES -> "Other Issues"
        REPORT_ISSUE_CHAT_PLACEHOLDER _ -> "Describe your issue."
        CALL_SUPPORT_DESCRIPTION _ -> "You are about to place a call to Support team. Do you want to proceed?"
        CANT_FIND_OPTION -> "Can't find option"
        NEED_HELP -> "Need Help?"
        SAFETY_ISSUE_PAGE_NAME -> "Safety Related Issue"
        WE_HOPE_THE_ISSUE_IS_RESOLVED _ -> "We hope the issue is resolved!"
        PLEASE_SELECT_THE_RIDE_TO_CALL_DRIVER -> "Please select the ride to call the driver"
        ADD_IMAGE_S -> "Add Image(s)"
        ALREADY_HAVE_AN_ACTIVE_RIDE -> "You already have an active ride"
        CONFIRM_STOP_LOCATION -> "Confirm Stop Location"
        CONFIRM_DROP -> "Confirm Drop"
        BOOK_METRO_WITH_NY_NOW -> "Book metro tickets with \nNamma Yatri Now!"
        COMPLETE_YOUR_NAMMA_SAFETY_SETUP_FOR_SAFE_RIDE_EXPERIENCE -> "Complete your Safety mode setup for safe ride experience"
        SETUP_NOW -> "Setup Now"
        LEARN_MORE -> "Learn More"
        LEARN_ABOUT_NAMMA_SAFETY -> "Learn about safety"
        LEARN_ABOUT_SAFETY_MODE -> "Learn about Safety mode"
        NAMMA_SAFETY_WILL_ENABLE_ACCESS -> "Safety mode will enable access to the following features during a ride!"
        ACTIVATE_NAMMA_SAFETY_WILL_ENABLE_ACCESS -> "Activating Safety mode will perform the following actions"
        EDIT_ACTIONS -> "Edit Actions"
        EMERGENCY_ACTIONS -> "Emergency Actions"
        WHEN_YOU_START_EMERGENCY_SOS -> "When you activate Safety mode, your app will perform the below actions"
        EMERGENCY_SHARING_WITH_CONTACTS -> "Emergency Sharing and auto calling with contacts"
        SHARING_WITH -> "Sharing With:"
        ADD_A_CONTACT -> "Add a contact"
        TO_ENSURE_SAFETY_USERS_SHOULD -> "To ensure their safety, users should:"
        ABOUT_SOS_DESC -> "Kindly understand the criticality of Safety mode. For non-critical situations, kindly use the <b>Help & Support</b> section to raise a complaint."
        FEW_EXAMPLES_OF_SOS_SITUATIONS -> "Few examples of Emergency situations"
        THINGS_TO_DO_DURING_SOS_SITUATION -> "Things to do during Emergency situation"
        EMERGENCY_REQUEST_SENT -> "Emergency request Sent!"
        SOS_TRIGGERED_DESC -> "Please stay calm, Your real time location is being shared with your emergency contacts."
        TEST_EMERGENCY_REQUEST_SENT -> "Test Emergency request Sent!"
        TEST_SOS_TRIGGERED_DESC -> "In a real situation, your location will be shared with your emergency contacts. "
        SOS_ACTIONS -> "SOS Actions"
        CALL_POLICE -> "Call Police"
        RECORD_VIDEO -> "Record\nVideo"
        STOP_AND_SHARE_RECORDING -> "Stop and Share Recording"
        CANCEL_SHARING -> "Cancel Sharing"
        START_RECORDING -> "Start Recording"
        SHARING_THE_VIDEO_IN -> "Sharing the video in...."
        EMERGENCY_INFO_SHARED -> "Emergency info shared!"
        EMERGENCY_INFO_SHARED_ACTION -> "Our support team has your location and video.\nUpon critical situations the police will be intimated and appropriate action will be taken."
        EMERGENCY_INFO_SHARED_ACTION_POLICE -> "The Police authorities have received your location and video. They will reach out to you soon and will take emergency action(s)."
        SET_UP_YOUR_PERSONAL_SAFETY_SETTINGS -> "Set up your personal safety settings"
        ACTIVATE_LIVE_VIDEO_RECORDING_FEATURES -> "Activate live video recording feature"
        CHOOSE_RESPONSIVE_CONTACTS -> "We recommend you to select responsive contacts for your ride, such as a local guardian or a friend in the same city."
        SHARE_LOCATION_AND_RIDE_DETAILS_EMERGENCY_CONTACT -> "Share location and ride details with your emergency contacts"
        NAMMA_SAFETY_MEASURES -> "Safety mode Measures"
        SAFETY_GUIDELINES_FOR_YOU -> "Safety Guidelines for you"
        ABOUT_SOS -> "About Safety mode"
        NIGHT_TIME_SAFETY_CHECKS -> "Night Time Safety Checks"
        SHARE_INFO_WITH_EMERGENCY_CONTACTS_TITLE -> "Share Information and Initiate Automatic Call with Emergency Contacts?"
        SHARE_INFO_WITH_EMERGENCY_CONTACTS_DESC -> "Choose responsive contacts for your ride, like a local guardian or a city friend."
        TRIGGER_ALERT_TO_NAMMAYATRI_SUPPORT_TITLE _ -> "Trigger alert to Namma Yatri support"
        TRIGGER_ALERT_TO_NAMMAYATRI_SUPPORT_DESC -> "We have 24*7 dedicated support who will be alerted automatically"
        ENABLE_NIGHT_TIME_SAFETY_ALERTS_TITLE -> "Enable night time safety checks?"
        ENABLE_NIGHT_TIME_SAFETY_ALERTS_DESC -> "To ensure your safety, from <b><span style='color:#454545'>9 PM-6AM</span></b>, we would send safety check alerts basis anomaly detection of driver’s route. In cases of route-deviation or when vehicle is not moving.<br><br>This will happen regardless of whether Safety mode is activated"
        ALMOST_DONE_TITLE -> "Almost Done!"
        ALMOST_DONE_DESC -> "During an emergency, you can also contact the police helpline or report safety issue. To do this, please provide the necessary permissions"
        PERSONAL_SAFETY_ACTION_1 -> "Call Police (112)"
        PERSONAL_SAFETY_ACTION_2 _ -> "Call Namma Yatri support"
        PERSONAL_SAFETY_ACTION_2_POLICE -> "Send Silent SOS to Police."
        PERSONAL_SAFETY_ACTION_3 -> "Record a short 15 second video."
        PERSONAL_SAFETY_SETTINGS_PERMISSION_REQUEST -> "(Please give relevant permissions to record)"
        SAFETY_MEASURE_1 -> "Night-time safety check based on driver route anomaly detection"
        SAFETY_MEASURE_2 -> "Safety mode button."
        SAFETY_MEASURE_3 -> "Zero tolerance policy for drivers/customers"
        SAFETY_MEASURE_4 -> "Customer privacy - drivers can't view the exact address of the ride once completed"
        SAFETY_MEASURE_5 _ -> "Safety Training and Certification for all Namma Yatri Drivers"
        SAFETY_MEASURE_6 -> "Share a live video recording at the time of emergency."
        SAFETY_GUIDELINES_1 -> "Check Driver’s identification with vehicle number"
        SAFETY_GUIDELINES_2 -> "Keep an eye on the route"
        SAFETY_GUIDELINES_3 -> "Stay alert especially during night rides"
        SAFETY_GUIDELINES_4 -> "If you feel uncomfortable, share your ride with emergency contacts"
        SAFETY_GUIDELINES_5 -> "Avoid sharing personal information"
        SAFETY_GUIDELINES_6 -> "Use In-App emergency Safety mode feature"
        SAFETY_GUIDELINES_7 -> "Rate and Review to help maintain a reliable and safe community"
        ABOUT_SOS_1 -> "Driver re-routing to different remote locations"
        ABOUT_SOS_2 -> "Inappropriate verbal/physical cues from the driver"
        ABOUT_SOS_3 -> "Other passengers asked to join ride without your consent"
        ABOUT_SOS_4 -> "Driver stopped unsolicited, at a remote area"
        ABOUT_SOS_5 -> "Fare issues"
        ABOUT_SOS_6 -> "Drunk driving"
        ABOUT_SOS_7 -> "Rash driving"
        ABOUT_SOS_8 -> "Vehicle number mismatch"
        ABOUT_SOS_9 -> "Activate Safety mode by tapping on the Safety mode button during the ride"
        ABOUT_SOS_10 -> "Remain Calm. Do not panic."
        ABOUT_SOS_11 _ -> "Inform your family & friends by emergency sharing."
        ABOUT_SOS_12 -> "You can choose to Call the Police Helpline (112)"
        ABOUT_SOS_13 -> "If possible, ask the driver to stop the vehicle at a nearby populated area"
        THE_VIDEO_WILL_BE_RECORDED -> "The video will be recorded for 15 sec only and will be shared as to our support team"
        EMERGENCY_VIDEO -> "Emergency Video"
        NAMMA_SAFETY_IS_SET_UP -> "Safety mode is successfully set up"
        ACTIVATE_NAMMA_SAFETY_POPUP_TITLE -> "You are about to activate\nSafety mode"
        ACTIVATE_NAMMA_SAFETY_POPUP_DESC -> "Your safety is our top priority. Use Safety mode only during genuine emergencies. Misuse may divert resources from real critical situations"
        ACTIVATE_NAMMA_SAFETY_POPUP_ACTION -> "Confirm Activation"
        DISMISS -> "Dismiss"
        SEND_SILENT_SOS_TO_POLICE -> "Send Silent\nSOS to Police"
        OUR_SAFETY_PARTNER -> "Our Safety\nPartner"
        BANGALURU_CITY_POLICE -> "Bengaluru\nCity Police"
        GET_OPTIONS_TO_DIRECTLY_CALL_POLICE -> "Option to directly call the Police Helpline"
        SHARE_SOS_SILENTLY_WITH_POLICE -> "Share SOS silently with ride details to Police"
        CALL_AND_ALERT_THE_NEAREST_POLICE_CENTRE -> "Call and alert the nearest police centre."
        SEND_A_SILENT_SOS_TO_THE_POLICE -> "Send a silent SOS message to the police."
        SEND_A_VIDEO_RECORDING_TO_POLICE -> "Send a video recording to the police."
        SEND_VIDEO_TO_POLICE -> "Send 15s video\nto police"
        FINISH_SETUP -> "Finish Setup"
        ACTIVATE_SOS -> "Activate"
        MARK_RIDE_AS_SAFE -> "Mark Ride As Safe"
        START_SETUP -> "Start Setup"
        CALL_SUPPORT_FOR_SAFETY _ -> "Call Our\nSupport"
        WE_NOTICED_YOUR_RIDE_HASNT_MOVED -> "We noticed your driver hasn't moved for a while. Are you feeling safe on your trip?"
        WE_NOTICED_YOUR_RIDE_IS_ON_DIFFERENT_ROUTE -> "We noticed your driver is on a different route. Are you feeling safe on your trip?"
        WE_ARE_HERE_FOR_YOU -> "We`re here for you!"
        I_NEED_HELP -> "I need help"
        I_FEEL_SAFE -> "I feel safe"
        EVERYTHING_OKAY_Q -> "Everything Okay?"
        PLEASE_REMAIN_CALM_YOU_CAN_REQUEST_AN_IMMEDIATE_CALL -> "Please remain calm, you can request an immediate call from us if required.\n\nYou can also use the safety+ features at the top right for added safety."
        RECEIVE_CALL_FROM_SUPPORT -> "Receive Call from Support"
        ADD_CONTACTS -> "Add Contacts"
        VIDEO_SHARE_INFO_TO_POLICE -> "The video will be recorded for 15 sec only and will be shared to the Police Authorities via Whatsapp"
        CALL_POLICE_HELPLINE -> "Call Police Helpline (112)"
        PLEASE_REMAIN_CALM_CALL_POLICE -> "Please remain calm, you can call the Police Helpline if required.\n\nYou can also use the Safety mode features at the top right for added safety."
        PLEASE_ALLOW_CAMERA_AND_MICROPHONE_PERMISSIONS -> "Please allow camera and microphone permissions to record video"
        RIDE_SHARE_AFTER_SIX_PM -> "Send trip notifications to emergency contacts from 9pm - 6am"
        WHO_CAN_TRACK_YOUR_RIDE _ -> "Who can follow your ride on Namma Yatri App"
        SELECT_PREFERRED_CONTACTS -> "Select the preferred contact to call first:"
        NEW -> "NEW"
        SAFETY_CENTER -> "Safety Center"
        EMERGENCY_SOS -> "Emergency SOS"
        AUTOMATIC_CALL_PLACED_TO_EMERGENCY_CONTACTS -> "Automatic call placed to the emergency contacts"
        EMERGENCY_CONTACTS_CAN_FOLLOW _ -> "Emergency contacts on Namma Yatri app can follow and take emergency response actions"
        ALERT_SAFETY_TEAM _ -> "Alert Namma Yatri Safety Team"
        OPTION_TO_REPORT_A_SAFETY_ISSUE -> "Option to Report a Safety Issue"
        RECOMMEND_EMERGENCY_CONTACTS_TO_INSTALL _ -> "We recommend emergency contacts to install Namma Yatri for an enhanced tracking experience"
        TEST_SAFETY_DRILL -> "Test Safety Drill"
        START_TEST_DRILL -> "Start Test Drill"
        REPORT_SAFETY_ISSUE -> "Report Safety Issue"
        SAFETY_TEAM_WILL_BE_ALERTED _ -> "Upon SOS  Namma Yatri safety team will be notified"
        EMERGENCY_CONTACTS_CAN_TAKE_ACTION -> "Emergency Contacts can follow/ take emergency response actions on Namma Yatri App"
        SHARE_RIDE -> "Share Ride"
        SHARE_RIDE_DESCRIPTION _ -> "On choosing this, Namma Yatri will send app push notification to the emergency contacts"
        SHARE_RIDE_WITH_CONTACT number -> "Share with "<> number <>" contact"
        SHARE_LINK -> "Share Link"
        GLAD_TO_KNOW_YOU_ARE_SAFE -> "Glad to know that you are safe!"
        PLEASE_STAY_CALM_TEAM_ALERTED _ -> "Please stay calm, Namma Yatri safety team is alerted!"
        TRY_ANOTHER_CONTACT -> "Try connecting with another Emergency Contact"
        YOUR_CURRENT_LOCATION -> "Your Current Location"
        THIS_IS_NOT_A_REAL_SOS_SITUATION -> "This is not a real SOS situation"
        YOUR_VEHICLE_INFO -> "Your Vehicle Info"
        POLICE_VIEW_INSTRUCTION -> "Please give the operator your location - The app doesn’t share the location automatically."
        TEST_SOS_ACTIVATING_IN -> "Test SOS is getting activated in..."
        SOS -> "SOS"
        TEST_SOS -> "Test\nSOS"
        SELECT_CONTACT_TO_CALL -> "Select the contact to be called"
        EMERGENCY_SOS_ACTIVATING -> "Emergency SOS is getting activated in..."
        PRESS_TO_START_TEST_DRILL -> "Press the below button to start the\nTest SOS Drill"
        PRESS_THE_BUTTON_ON_EMERGENCY -> "Press the button on emergency"
        INFORM_EMERGENCY_CONTACTS -> "Please inform your emergency contacts about this test drill to prevent any unnecessary panic"
        OTHER_SAFETY_ACTIONS -> "Other Safety Actions"
        AVAILABLE_IN_REAL_EMERGENCY -> "Available only during a real SOS situation"
        DISCLAIMER -> "Disclaimer"
        USE_ONLY_IN_EMERGENCY -> "Use only in emergencies"
        MISUSE_MAY_LEAD_TO_LEGAL_ACTION -> "Misuse may result in legal action"
        USE_TEST_DRILL -> "Use <span style='color:#2194FF'><u>Test safety drill</u></span> for testing"
        INDICATION_TO_EMERGENCY_CONTACTS _ -> "Namma Yatri will indicate to your emergency contacts that this is a test drill, ensuring a stress-free experience."
        ARE_YOU_READY_TO_START_DRILL -> "Are you ready to start the drill?"
        TEST_DRILL_DESC -> "Taking part in the test drill helps you to understand how to act in a real emergency. Take the test drill now, to avoid panic during an emergency."
        SOS_WILL_BE_DISABLED -> "SOS feature will be disabled if misused thrice"
        DIAL_NOW -> "Dial Now"
        FOLLOWING name -> "Following " <> name
        TURN_OFF_ALARM -> "Turn off the alarm"
        CHOOSE_A_PERSON_TO_FOLLOW -> "Choose a person to follow"
        IS_IN_SOS_SITUATION name -> name <> " is in a SOS Situation!"
        MARKED_RIDE_SAFE name -> name <> " marked the ride Safe!"
        STAY_CALM_KEEP_TRACKING name -> "Stay calm. Keep tracking " <> name <> "'s location Take necessary actions if needed"
        YOU_WILL_BE_NOTIFIED -> "You'll be notified once the ride is completed"
        TAP_HERE_TO_FOLLOW name ->  "Tap here to follow " <> name
        HAVE_SHARED_RIDE_WITH_YOU name -> name <> " have shared their rides with you"
        SOS_LOCATION -> "SOS Location"
        THIS_IS_A_TEST_MOCK_DRILL name -> "This is a Test Drill for " <> name
        THIS_IS_NOT_REAL_DRILL -> "This is NOT a real drill, it simply illustrates how the app will respond in emergency situations."
        REACHED_DESTINATION_SAFELY name -> name <> " has reached the destination safely!"
        RIDE_ENDED name -> name <> "'s ride has ended"
        COMPLETE_YOUR_TEST_DRILL -> "Complete Your Test Safety Drill: Safety First!"
        TEST_DRILL -> "Test Drill"
        RIDE_SHARED_WITH_SELECTED_CONTACTS -> "Ride shared with selected contacts"
        STOPS -> "Stops"
        GREEN_LINE -> "Green Line"
        BLUE_LINE -> "Blue Line"
        RED_LINE -> "Red Line"
        VIEW_ROUTE_INFO -> "View Route Information"
        VALID_UNTIL -> "Valid Until"
        TICKET_NUMBER -> "Ticket Number"
        TICKET -> "Ticket"
        TICKETS -> "Tickets"
        ONWORD_JOURNEY -> "Onward Journey"
        ROUND_TRIP_STR -> "Round Trip"
        TICKETS_FOR_CHENNAI_METRO -> "Tickets for Chennai Metro"
        ACTIVE_STR -> "Active"
        EXPIRED_STR -> "Expired"
        USED_STR -> "Used"
        MAP_STR -> "Map"
        TICKET_DETAILS -> "Ticket Details"
        ROUTE_DETAILS -> "Route Details"
        UNCERTAIN_ABOUT_METRO_ROUTES -> "Uncertain about Metro Routes?"
        SEE_MAP -> "See Map" 
        METRO_TERM_1 -> "Cancellation of tickets is not applicable"
        METRO_TERM_2 -> "The tickets can be purchased between 4:30 AM to 10:30 PM on all days."
        NO_OF_PASSENGERS -> "No of Passengers"
        MAXIMUM -> "Maximum"
        TICKETS_ALLOWED_PER_USER -> "tickets are allowed per user."
        STARTING_FROM -> "Starting From"
        FROM -> "From"
        TO -> "To"
        TRANSACTION_ID -> "Transaction ID"
        PLEASE_WHILE_GEN_TICKET -> "Please wait while we generate your ticket"
        PAYMENT_RECEIVED -> "Payment Received!"
        PLEASE_CHECK_BACK_FEW_MIN -> "Please check back in a few minutes."
        YOUR_BOOKING_PENDING -> "Your booking is Pending!"
        PLEASE_RETRY_BOOKING -> "Please retry booking."
        BOOKING_FAILED -> "Booking Failed!"
        INCASE_OF_FAIL -> "Incase of failure, any money debited will be refunded within 5 - 7 working days."
        REFRESH_STATUS -> "Refresh Status"
        DATE -> "Date"
        NO_OF_TICKETS -> "No of Tickets"
        ACTIVE_TICKETS -> "Active Tickets"
        CONFIRMING_STR -> "Confirming"
        FAILED_STR -> "Failed"
        CONFIRMED_STR -> "Confirmed"
        BUY_METRO_TICKETS -> "Buy Metro Tickets"
        GET_FARE -> "Get Fare"
        METRO_BOOKING_TIMINGS -> "Metro Booking Timings"
        CHENNAI_METRO_TIME -> "Chennai Metro allows QR ticket purchase from 4:30 AM to 10:30 PM on all days. "
        PLEASE_COME_BACK_LATER_METRO -> "Please come back later during the eligible time to purchase tickets."
        NO_QOUTES_AVAILABLE -> "No quotes available"
        I_AGREE_TO_THE -> "I agree to the"
        HERE_IS_METRO_TICKET -> "Here is metro ticket!"
        VIEW_TICKET -> "View Ticket"
        DESTINATION -> "Destination"
        PAY -> "Pay"
        PENDING_STR -> "Pending"
        PAST_TICKETS -> "Past Tickets"
        ONE_WAY_STR -> "One Way"
