module Resources.Localizable.FR where

import Language.Types (STR(..))

getFR :: STR -> String
getFR stringKey =
    case stringKey of
        DOWNLOAD_INVOICE -> "Télécharger facture"
        REPORT_AN_ISSUE -> "Signaler un problème"
        SUBMIT -> "Soumettre"
        VIEW_INVOICE -> "Voir la facture"
        TOTAL_AMOUNT -> "Montant total"
        AMOUNT_PAID -> "Montant payé"
        TRIP_DETAILS_ -> "Détails du voyage"
        DOWNLOAD_PDF -> "Télécharger le PDF"
        INVOICE -> "Facture"
        TRIP_CHARGES -> "Frais de voyage"
        PROMOTION -> "Promotion"
        SEND_EMAIL -> "Envoyer un e-mail"
        YOU_CAN_DESCRIBE_THE_ISSUE_YOU_FACED_HERE -> "Vous pouvez décrire le problème auquel vous avez été confronté ici"
        THANK_YOU_FOR_WRITING -> "Merci de nous avoir écrit!"
        WE_HAVE_RECEIVED_YOUR_ISSUE -> "Nous avons bien reçu votre problème. Nous vous contacterons prochainement"
        GO_HOME_ -> "Rentrer soi"
        LOGO -> "Logo"
        ABOUT_APP_DESCRIPTION _ -> "Namma Yatri est une plate-forme ouverte pour connecter les utilisateurs avec les conducteurs. L'application rend pratique pour les utilisateurs de réserver un trajet avec un tarif de compteur, d'où un prix minimal."
        ABOUT -> "À propos de"
        PRIVACY_POLICY -> "Politique de confidentialité"
        SET_UP_YOUR_ACCOUNT -> "Configurez votre compte"
        CONTINUE -> "Continuer"
        ENTER_YOUR_NAME -> "Entrez votre nom"
        FULL_NAME -> "Nom et prénom"
        EMAIL -> "E-mail"
        WELCOME_TEXT _ -> "Bienvenue à Namma Yatri"
        PLEASE_CHOOSE_YOUR_PREFERRED_LANGUAGE_TO_CONTINUE -> "Veuillez choisir votre langue préférée pour continuer."
        WRITE_TO_US -> "Écrivez-nous"
        NOTE -> "Note: "
        VISIT_MY_RIDES_SECTION_FOR_RIDE_SPECIFIC_COMPLAINTS -> "Visitez la section des manèges pour des plaintes spécifiques à la conduite"
        THANK_YOU_FOR_WRITING_TO_US -> "Merci de nous avoir écrit!"
        WE_HAVE_RECEIVED_YOUR_ISSUE_WELL_REACH_OUT_TO_YOU_IN_SOMETIME -> "Nous avons bien reçu votre problème. Nous vous contacterons prochainement."
        GO_TO_HOME__ -> "aller à la maison"
        SUBJECT -> "Sujet"
        YOUR_EMAIL_ID -> "Votre identifiant de messagerie"
        DESCRIBE_YOUR_ISSUE -> "Décrivez votre problème"
        ENTER_MOBILE_NUMBER -> "Entrez le numéro de mobile"
        BY_TAPPING_CONTINUE -> "En appuyant sur Continuer"
        TO_THE -> "Vous acceptez que vous acceptez le"
        ENTER_OTP -> "Entrez OTP"
        RESEND -> "Renvoyer"
        ENTER_YOUR_MOBILE_NUMBER -> "Entrez votre numéro de mobile "
        LOGIN_USING_THE_OTP_SENT_TO -> "Connectez-vous en utilisant l'OTP envoyé à"
        YOUR_RECENT_RIDE -> "Votre récent tour"
        VIEW_ALL_RIDES -> "Afficher tous les manèges"
        ALL_TOPICS -> "Tous les sujets"
        FAQ -> "FAQ"
        REPORT_AN_ISSUE_WITH_THIS_TRIP -> "Signaler un problème avec ce voyage"
        YOU_RATED -> "Vous avez évalué:"
        GETTING_STARTED_AND_FAQS -> "Démarrage et foire aux questions"
        FOR_OTHER_ISSUES_WRITE_TO_US -> "Pour d'autres problèmes, écrivez-nous"
        HELP_AND_SUPPORT -> "Aide et soutien"
        OUR_SUGGESTED_PRICE_FOR_THIS_TRIP_IS -> "Notre prix suggéré pour ce voyage est"
        DRIVERS_CAN_CHARGE_BETWEEN_THE_ABOVE_RANGE -> "*Les conducteurs peuvent charger entre les fourchettes ci-dessus"
        HOW_THIS_WORKS -> "Comment cela fonctionne?"
        FINDING_RIDES_NEAR_YOU -> "Trouver des manèges près de chez vous..."
        CONFIRMING_THE_RIDE_FOR_YOU -> "Je confirme le trajet pour vous..."
        CANCEL_SEARCH -> "Annuler la recherche"
        YOUR_RIDE_IS_NOW_COMPLETE -> "Votre balade est maintenant complète!"
        PLEASE_PAY_THE_FINAL_AMOUNT_TO_THE_DRIVER_VIA_CASH -> "Veuillez payer directement le montant final au conducteur"
        WHERE_TO -> "Pour aller où ?"
        HOME -> "Maison"
        PICK_UP_LOCATION -> "Lieu de ramassage"
        REQUEST_RIDE -> "Demande de trajet"
        NAME -> "Nom"
        MOBILE_NUMBER_STR -> "Numéro de portable"
        PERSONAL_DETAILS -> "Détails personnels"
        YOUR_RIDES -> "Vos manèges"
        YOU_ARE_OFFLINE -> "Tu es hors ligne"
        CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN -> "Vérifiez votre connexion Internet et réessayez"
        TRY_AGAIN -> "Essayer à nouveau"
        THANK_YOUR_DRIVER -> "Merci votre chauffeur!"
        HOPE_YOUR_RIDE_WAS_HASSLE_FREE -> "Nous espérons que votre balade était sans tracas"
        HOW_WAS_YOUR_RIDE_WITH -> "Comment était votre balade avec"
        GOT_IT_TELL_US_MORE -> "Compris, dites-nous en plus ?"
        WRITE_A_COMMENT -> "Écrivez un commentaire (facultatif)"
        UPDATE -> "Mise à jour"
        LANGUAGE -> "Langue"
        OTP -> "OTP"
        PAYMENT_METHOD -> "Mode de paiement"
        PAYMENT_METHOD_STRING -> "Cash / Utilisez n'importe quelle application UPI"
        PAYMENT_METHOD_STRING_ -> "Cash / Utilisez n'importe quelle application UPI"
        CANCEL_RIDE -> "Annuler le trajet"
        SUPPORT -> "Soutien"
        PICKUP_AND_DROP -> "Pick-up and Drop"
        CANCELLED -> "Annulé"
        HOW_THE_PRICING_WORKS -> "Comment fonctionne la tarification ?"
        SELECT_AN_OFFER -> "Sélectionnez une offre"
        CHOOSE_A_RIDE_AS_PER_YOUR_COMFORT -> "Choisissez une balade selon votre confort"
        IT_SEEMS_TO_BE_A_VERY_BUSY_DAY -> "Cela semble être une journée très chargée. Vous pouvez essayer de chercher à nouveau des trajets"
        SORT_BY -> "Trier par"
        SORRY_WE_COULDNT_FIND_ANY_RIDES -> "Désolé, nous ne pouvions pas trouver de manèges"
        LOAD_MORE -> "Charger plus"
        WE_NEED_ACCESS_TO_YOUR_LOCATION -> "Nous avons besoin d'accéder à votre emplacement!"
        CALL -> "Appel"
        EMPTY_RIDES -> "Les trajets à vide"
        YOU_HAVENT_TAKEN_A_TRIP_YET -> "Vous n'avez pas encore fait de voyage"
        BOOK_NOW -> "Reserve maintenant"
        T_AND_C_A -> "A) Vous acceptez que vous êtes un participant volontaire des tests bêta et que Juspay n'aura aucune responsabilité à tous égards"
        TERMS_AND_CONDITIONS -> "T&C"
        DATA_COLLECTION_AUTHORITY -> "c) Je nomme et autorise Juspay à collecter mes informations et, en continuant, j'accepte les conditions d'utilisation et la politique de confidentialité."
        DENY_ACCESS -> "Refuser l'accès"
        PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL -> "Veuillez nous dire pourquoi vous voulez annuler"
        MANDATORY -> "Obligatoire"
        SOFTWARE_LICENSE -> "Licence logicielle"
        LOGOUT_ -> "Se déconnecter"
        REQUEST_AUTO_RIDE _-> "Demande de trajet"
        RATE_YOUR_RIDE -> "Évaluez votre balade"
        SKIP -> "Sauter"
        ERROR_404 -> "Erreur 404"
        PROBLEM_AT_OUR_END -> "Il semble y avoir un problème à notre fin. Soyez avisé lorsque nous sommes à nouveau"
        NOTIFY_ME -> "Prévenez moi"
        ADDRESS -> "Adresse"
        CHANGE -> "Changement"
        SAVE_AS -> "Enregistrer sous"
        ADD_TAG -> "Ajouter une étiquette"
        WORK -> "Travail"
        OTHER -> "Autre"
        SAVE -> "Sauvegarder"
        ADD_NEW_ADDRESS -> "Ajouter une nouvelle adresse"
        SAVED_ADDRESSES -> "Adresses enregistrées"
        ADDRESSES -> "Adresses"
        NO_FAVOURITES_SAVED_YET -> "Aucun favori sauvé"
        SAVED_ADDRESS_HELPS_YOU_KEEP_YOUR_FAVOURITE_PLACES_HANDY -> "Les lieux favoris permettent de garder à portée de main les endroits que l'on visite fréquemment."
        EMERGENCY_CONTACTS -> "Contacts d'urgence"
        ADD_EMERGENCY_CONTACTS -> "Ajouter des contacts d'urgence"
        ADD_ANOTHER_CONTACT -> "Ajouter un autre contact"
        NO_EMERGENCY_CONTACTS_SET -> "Aucun contact d'urgence défini"
        EMERGENCY_CONTACTS_SCREEN_DESCRIPTION -> "Vous pouvez partager votre statut de conduite en cas d'urgence \n avec jusqu'à 3 contacts d'urgence."
        COPIED -> "Copié"
        TRIP_ID -> "ID de voyage"
        SAVE_PLACE -> "Save Place"
        RIDE_FARE -> "Tarif de conduite"
        ASK_FOR_PRICE -> "Demandez un prix"
        ASK_FOR_PRICE_INFO -> "Vous recevrez un tarif basé sur le prix de base <b>défini par le gouvernement</b>, avec des frais nominaux supplémentaires de <b>Rs.10</b> pour la distance de <b>prise en charge</b> parcourue par les conducteurs. Certains conducteurs peuvent demander des pourboires nominaux à leur discrétion pour couvrir des facteurs tels que le trafic, les chances de trajet de retour, etc."
        GET_ESTIMATE_FARE -> "Obtenir une estimation du tarif"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS -> "Sélectionnez une offre (facultative)"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS_INFO -> "Par défaut, lorsque l'option <b>Attribution automatique d'une course</b> est activée, vous êtes attribué à un conducteur qui accepte la demande en premier, dans la fourchette estimée. Si vous souhaitez plutôt choisir une offre de conducteur, vous pouvez la désactiver et procéder."
        PAY_THE_DRIVER -> "Payer le conducteur"
        PAY_THE_DRIVER_INFO -> "Payez directement au conducteur le prix que vous avez confirmé."
        PAY_THE_DRIVER_NOTE -> "(Total des tarifs peut changer si la distance de trajet change)"
        UPDATE_PERSONAL_DETAILS -> "Mettre à jour les détails personnels"
        EDIT -> "Modifier"
        DEL_ACCOUNT -> "Supprimer le compte"
        ACCOUNT_DELETION_CONFIRMATION -> "Êtes-vous sûr de vouloir supprimer votre compte? Toutes vos données personnelles seront perdues"
        REQUEST_SUBMITTED -> "Demande soumise"
        WE_WILL_DELETE_YOUR_ACCOUNT -> "Nous sommes désolés de vous voir quitter notre plateforme. Nous supprimerons votre compte dans les 30 prochains jours. Si vous souhaitez conserver votre compte, veuillez nous appeler au numéro de support."
        YES_DELETE_IT -> "Oui, supprimez-le"
        REQUEST_TO_DELETE_ACCOUNT -> "Demande de supprimer le compte"
        CANCEL_STR -> "Annuler"
        LOADING -> "Chargement"
        PLEASE_WAIT_WHILE_IN_PROGRESS -> "Veuillez patienter pendant que cela est en cours."
        SET_LOCATION_ON_MAP -> "Définir l'emplacement sur la carte"
        CURRENT_LOCATION -> "Localisation actuelle"
        DELETE -> "Supprimer"
        ARE_YOU_SURE_YOU_WANT_TO_LOGOUT -> "Êtes-vous sûr de vouloir vous déconnecter ?"
        ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "Es-tu sûre de vouloir annuler?"
        YOU_HAVE_RIDE_OFFERS_ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "Vous avez des offres de transport, êtes-vous sûr de vouloir annuler ?"
        GO_BACK_ -> "Retourner"
        REGISTER_USING_DIFFERENT_NUMBER -> "Voulez-vous vous inscrire à l'aide d'un autre numéro de mobile?"
        YES -> "Oui"
        NO -> "Non"
        CANCEL_ -> "Annuler"
        IS_ON_THE_WAY -> "est sur le chemin"
        ENTER_4_DIGIT_OTP -> "Entrez à 4 chiffres OTP"
        WRONG_OTP -> "Mauvais OTP"
        GRANT_ACCESS -> "Accès des subventions"
        ENTER_A_LOCATION -> "Entrez un emplacement"
        NEARBY -> "Proche"
        MINS_AWAY -> "minutes à l'écart"
        PAID -> "Payé"
        BY_CASH -> "en espèces"
        ONLINE_ -> "En ligne"
        USER -> "Utilisateur"
        EMAIL_ALREADY_EXISTS -> "Impossible de mettre à jour le courrier électronique. Le courrier électronique existe déjà."
        IN -> "dans"
        VERIFYING_OTP -> "Vérification de l'OTP"
        TRACK_LIVE_LOCATION_USING -> "Track live emplacement en utilisant"
        GOOGLE_MAP_ -> "Google Map"
        IN_APP_TRACKING -> "Dans le suivi des applications"
        QUOTE_EXPIRED -> "Citation expirée"
        GETTING_ESTIMATES_FOR_YOU -> "Obtiens des estimations pour vous..."
        CONFIRM_PICKUP_LOCATION -> "Confirmer l'emplacement de ramassage"
        CONFIRM_DROP_LOCATION -> "Confirmer l'emplacement de la chute"
        ERROR_OCCURED_TRY_AGAIN -> "Erreur s'est produite. Ressayez"
        ASKED_FOR_MORE_MONEY -> "A demandé plus d'argent"
        START_ -> "Commencer"
        RIDE_NOT_SERVICEABLE -> "Service de transport non disponible"
        APP_NOT_SERVICEABLE-> "Non réparable"
        CONFIRM_FOR -> "Confirmer pour"
        ETA_WAS_TOO_SHORT -> "Eta était trop courte."
        DRIVER_REQUESTED_TO_CANCEL -> "Le chauffeur m'a demandé d'annuler"
        PICK_UP_LOCATION_INCORRECT -> "L'emplacement de ramassage était incorrect."
        COULD_NOT_CONNECT_TO_DRIVER -> "Je n'ai pas pu me connecter au pilote."
        ETA_WAS_TOO_LONG -> "Eta était trop longue."
        OTHERS -> "Autres"
        DESTINATION_OUTSIDE_LIMITS -> "La destination entrée est en dehors des limites de la ville"
        DROP_LOCATION_FAR_AWAY -> "Votre emplacement de chute est trop loin"
        CHANGE_DROP_LOCATION -> "Changer l'emplacement de la chute"
        YOU_CAN_TAKE_A_WALK_OR_CONTINUE_WITH_RIDE_BOOKING -> "Vous pouvez choisir de marcher ou de continuer à réserver."
        YOUR_TRIP_IS_TOO_SHORT_YOU_ARE_JUST -> "La distance de votre voyage est trop courte. La destination est juste "
        METERS_AWAY_FROM_YOUR_DESTINATION -> "mètres de distance !"
        BOOK_RIDE_ -> "Book Ride"
        CANCEL_AUTO_ASSIGNING -> "Annuler l'attribution automatique"
        LOCATION_UNSERVICEABLE -> "Emplacement inutilisable"
        CURRENTLY_WE_ARE_LIVE_IN_ _  -> "Nous ne sommes pas encore en ligne dans votre région !\n Vous pouvez accéder à l'historique des trajets et à d'autres paramètres à partir du menu"
        CHANGE_LOCATION -> "Changer de lieu"
        AUTO_ACCEPTING_SELECTED_RIDE -> "Auto acceptant dans"
        THE_TRIP_IS_VERY_SHORT_AND_JUST_TAKE -> "Le voyage est très court et prend juste"
        IF_YOU_STILL_WANNA_BOOK_RIDE_CLICK_CONTINUE_AND_START_BOOKING_THE_RIDE -> "Si vous voulez toujours réserver, cliquez sur Continuer et commencez à réserver le trajet"
        STEPS_TO_COMPLETE -> "Étapes à terminer"
        HELP_US_WITH_YOUR_REASON -> "Aidez-nous avec votre raison"
        MAX_CHAR_LIMIT_REACHED -> "La limite de caractère maximale atteint,"
        DRIVER_WAS_NOT_REACHABLE -> "Le chauffeur n'était pas joignable"
        SHOW_ALL_OPTIONS -> "Afficher toutes les options"
        EXPIRES_IN -> "Expire dans"
        PAY_DIRECTLY_TO_YOUR_DRIVER_USING_CASH_UPI -> "* Payez directement à votre chauffeur à l'aide de Cash / UPI"
        UPDATE_REQUIRED -> "Mise à jour requise"
        PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE -> "Nous sommes ravis d'annoncer qu'il existe une nouvelle mise à jour disponible pour notre application. Cette mise à jour comprend un nouveau design et plusieurs nouvelles fonctionnalités pour rendre votre expérience encore meilleure."
        NOT_NOW -> "Pas maintenant"
        OF -> "de"
        LOST_SOMETHING -> "Vous avez perdu quelque chose?"
        TRY_CONNECTING_WITH_THE_DRIVER -> "Vous pouvez demander un rappel au chauffeur"
        CALL_DRIVER -> "Appeler le conducteur"
        NO_MORE_RIDES -> "Plus de manèges"
        CONTACT_SUPPORT -> "Contactez le support"
        INVALID_MOBILE_NUMBER -> "Numéro de portable invalide"
        RIDE_COMPLETED -> "Ride terminée"
        SUBMIT_FEEDBACK -> "Soumettre des commentaires"
        HOW_WAS_YOUR_RIDE_EXPERIENCE -> "Comment s'est déroulée votre expérience de conduite ?"
        DROP -> "Goutte"
        RATE_YOUR_RIDE_WITH -> "Notez votre trajet avec "
        VIEW_BREAKDOWN -> "Voir la panne"
        PAY_DRIVER_USING_CASH_OR_UPI -> "Payer le conducteur en espèces au UPI"
        PAY_DRIVER_USING_CASH_OR_UPI_ -> "Payer le conducteur en espèces au UPI"
        RATE_YOUR_DRIVER -> "Évaluez votre conducteur"
        MY_RIDES -> "Mes manèges"
        RIDE_DETAILS -> "Détails de conduite"
        RIDE_ID -> "Ride Id"
        SELECT_A_RIDE -> "Sélectionnez un trajet pour plus de détails"
        CONFIRM_RIDE_ -> "Confirmer Ride"
        YOU_CAN_CANCEL_RIDE -> "Vous pouvez annuler une fois que vous avez reçu des offres de la part des conducteurs."
        ESTIMATES_CHANGED -> "L'estimation de votre trajet a changé maintenant"
        ESTIMATES_REVISED_TO -> "L'estimation révisée est"
        RATE_CARD -> "Carte tarifaire"
        NIGHT_TIME_CHARGES -> "Charges nocturnes (22 h à 5 h)"
        MIN_FARE_UPTO -> "Min. Tarif jusqu'à 2 km"
        RATE_ABOVE_MIN_FARE -> "Taux supérieur au tarif minimum"
        DRIVER_PICKUP_CHARGES _ -> "Frais de ramassage des conducteurs"
        DAY_TIMES_OF -> ""
        DAYTIME_CHARGES_APPLICABLE_AT_NIGHT -> "X des frais diurnes applicables la nuit de 22 h à 5 h"
        NIGHT_TIMES_OF -> ""
        DAYTIME_CHARGES_APPLIED_AT_NIGHT -> "x des frais de jour appliqués au tarif de nuit (🌙) de 22 heures à 5 heures du matin"
        DRIVERS_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "* Le conducteur peut éventuellement demander 10% des tarifs de base (arrondi à Rs.10 le plus proche) pour couvrir le trafic, les chances de retour, etc."
        GOT_IT -> "J'ai compris!"
        DAY_TIME_CHARGES -> "Frais diurnes (de 5 h à 22 h)"
        SHARE_APP -> "Partager l'application"
        AWAY_C -> "Loin"
        AWAY -> "loin"
        AT_PICKUP -> "A l'enlèvement"
        FARE_UPDATED -> "Tarif mis à jour"
        TOTAL_FARE_MAY_CHANGE_DUE_TO_CHANGE_IN_ROUTE -> "Les tarifs totaux peuvent changer en raison du changement de route"
        AT_DROP -> "au point de chute"
        EMERGENCY_HELP -> "Aide d'urgence"
        CALL_POLICE -> "Appelez la police"
        ALSO_SHARE_YOUR_RIDE_STATUS_AND_LOCATION -> "Partage également l'état de votre trajet et votre position"
        SHARE_RIDE_WITH_EMERGENCY_CONTACTS -> "Partagez le trajet avec les contacts d'urgence"
        DO_YOU_NEED_EMERGENCY_HELP -> "Avez-vous besoin d'une aide d'urgence?"
        CALL_SUPPORT -> "Call Assistance"
        YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT _  -> "Vous êtes sur le point de passer un appel à l'équipe de soutien Pass culture. Voulez-vous continuer?"
        WAIT_TIME -> "Temps d'attente"
        FAVOURITES -> "Favoris"
        ADD_FAVOURITE -> "Ajouter le favori"
        ALL_FAVOURITES -> "Tous les favoris"
        REMOVE -> "Retirer"
        CONFIRM_LOCATION -> "Confirmer l'emplacement"
        SELECT_ON_MAP -> "Sélectionnez sur la carte"
        FAVOURITE_LOCATION -> "Emplacement préféré"
        EDIT_FAVOURITE -> "Modifier le favori"
        DRAG_THE_MAP -> "Faites glisser la carte et réglez la broche à l'emplacement exact"
        CHOOSE_ON_MAP -> "Choisissez sur la carte"
        USE_CURRENT_LOCATION -> "Utiliser l'emplacement actuel"
        FAVOURITE_YOUR_CURRENT_LOCATION -> "Favoriser votre emplacement actuel"
        LOCATION -> "Emplacement"
        LOCATION_ALREADY_EXISTS_AS -> "L'emplacement existe déjà comme"
        GIVE_THIS_LOCATION_A_NAME -> "Donnez un nom à cet emplacement"
        FAVOURITE -> "Favoris"
        CONFIRM_AND_SAVE -> "Confirmer et sauver"
        REMOVE_FAVOURITE -> "Supprimer le favori"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_FAVOURITE_ -> "Êtes-vous sûr de vouloir supprimer un emplacement préféré?"
        YES_REMOVE -> "Oui, supprimer"
        ADD_NEW_FAVOURITE -> "Ajouter un nouveau favori"
        SELECT_YOUR_DROP -> "Sélectionnez votre goutte"
        FAVOURITE_REMOVED_SUCCESSFULLY -> "Favoris a supprimé avec succès"
        LOCATION_ALREADY_EXISTS -> "L'emplacement existe déjà"
        LOCATION_ALREADY -> "Emplacement déjà"
        EXISTS_AS -> "existe comme"
        FAVOURITE_ADDED_SUCCESSFULLY -> "Le favori a ajouté avec succès"
        FAVOURITE_UPDATED_SUCCESSFULLY -> "Favorite mis à jour avec succès"
        ALREADY_EXISTS -> "Existe déjà"
        NAME_ALREADY_IN_USE -> "Nom déjà à usage"
        SELECT_FAVOURITE -> "Sélectionner le favori"
        CONFIRM_CHANGES -> "Confirmer les modifications"
        ADD_SAVED_LOCATION_FROM_SETTINGS -> "* Vous pouvez ajouter de nouveaux favoris du menu latéral> Favoris"
        YOU_WILL_BE_ASKED_TO_SELECT_CONTACTS -> "Il vous sera demandé de sélectionner jusqu'à 3 contacts"
        AUTO_ASSIGN_A_RIDE -> "Assignant automatiquement un trajet"
        IS_WAITING_AT_PICKUP -> "Attend au ramassage"
        WAIT_TIME_TOO_LONG -> "Temps d'attente trop long"
        GOT_ANOTHER_RIDE_ELSE_WHERE -> "a trouvé un transport ailleurs"
        DRIVER_WAS_RUDE -> "Le conducteur était impoli"
        MAYBE_LATER -> "Peut-être plus tard"
        YOUR_RIDE_HAS_STARTED -> "Ouais! Votre balade a commencé 🤩"
        ENJOY_RIDING_WITH_US -> "Aimer de rouler avec nous? Passé le mot \n et partager la joie"
        VIEW_DETAILS -> "Voir les détails"
        REPEAT_RIDE -> "Répéter le trajet"
        FARE_WAS_HIGH -> "Le tarif était élevé"
        AUTO_ASSIGN_DRIVER -> "Assignation automatique"
        CHOOSE_BETWEEN_MULTIPLE_DRIVERS -> "Choisissez entre plusieurs pilotes"
        CHOOSE_BETWEEN_MULTIPLE_RIDES -> "Choisir entre plusieurs options de transport"
        ENABLE_THIS_FEATURE_TO_CHOOSE_YOUR_RIDE -> "Activez cette fonction pour choisir votre trajet et votre tarif préférés."
        BOOKING_PREFERENCE -> "Préférence de réservation"
        BASE_FARES -> "Tarif de base "
        PICKUP_CHARGE -> "Frais de ramassage des conducteurs"
        TOTAL_PAID -> "Total payé"
        WAITING_CHARGE -> "Frais d'attente"
        NOMINAL_FARE -> "Demande de pilote facultative *"
        CUSTOMER_CANCELLATION_DUES -> "Frais d'annulation"
        DRIVERS_CAN_CHARGE_AN_ADDITIONAL_FARE_UPTO -> "* Les conducteurs peuvent éventuellement demander 10% des tarifs de base (arrondi à Rs.10 le plus proche) pour couvrir d'autres facteurs tels que le trafic, les chances de retour de retour, etc."
        WAITING_CHARGE_DESCRIPTION -> "** Frais d'attente: 1 / min - après 3 minutes d'arrivée des conducteurs"
        WAITING_CHARGE_RATECARD_DESCRIPTION -> ""
        FARE_POLICY_WAITING_CHARGES -> ""
        SUCCESSFUL_ONBOARD _ -> "Vous vous êtes connecté avec succès à \n nnamma yatri"
        HAVE_REFERRAL_CODE -> "Vous avez un code de référence?"
        REFEREAL_CODE_DISCRIPTION -> "Votre référence pourrait bien être la raison pour laquelle un conducteur est récompensé!"
        SIX_DIGIT_REFERRAL_CODE -> "Entrez le code à 6 chiffres partagé par le pilote"
        ABOUT_REFERRAL_PROGRAM -> "Qu'est-ce que le programme de référence?"
        ABOUT_REFERRAL_PROGRAM_DISCRIPTION _ -> "Le programme de référence incite les conducteurs à accepter plus de manèges, à annuler moins et à mieux vous servir en reconnaissant et en récompensant les conducteurs dignes. \n Vous pouvez aider en entrant dans le code de référence du conducteur et en améliorant la qualité des manèges pour la communauté Namma Yatri! "
        YOU_CAN_GET_REFERRAL_CODE_FROM_DRIVER _ -> "Vous pouvez obtenir un code de référence en demandant à votre chauffeur Namma Yatri."
        REFERRAL_CODE_SUCCESSFULL -> "Vous avez appliqué avec succès le code de référence \nthe !"
        REFERRAL_CODE_APPLIED -> "La référence appliquée!"
        HEY -> "Hé"
        INVALID_CODE_PLEASE_RE_ENTER -> "Code invalide. Veuillez le saisir à nouveau."
        LET_TRY_THAT_AGAIN -> "Essayons à nouveau ..."
        CONTACTS_SELECTED -> "Contacts sélectionnés"
        SELECT_CONTACTS -> "Sélectionnez les contacts"
        CONFIRM_EMERGENCY_CONTACTS -> "Confirmer les contacts d'urgence"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_CONTACT -> "Êtes-vous sûr de vouloir les retirer de vos contacts d'urgence?"
        SEARCH_CONTACTS -> "Rechercher des contacts"
        CALL_EMERGENCY_CONTACTS -> "Appelez les contacts d'urgence"
        LIVE_STATS_DASHBOARD -> "Tableau de bord en direct"
        CHECK_OUT_LIVE_STATS -> "Découvrez les statistiques en direct"
        EMERGENCY_CONTACS_ADDED_SUCCESSFULLY -> "Les contacts d'urgence ont ajouté avec succès"
        NO_CONTACTS_LEFT_ON_DEVICE_TO_ADD -> "Aucun contact laissé sur l'appareil à ajouter"
        PERCENTAGE_OF_NOMINAL_FARE -> "10% des tarifs de base"
        PAY_VIA_CASH_OR_UPI -> "Payer via Cash / UPI"
        REQUEST_CALLBACK -> "Demandez le rappel"
        CHOOSE_YOUR_RIDE -> "Choisissez votre balade"
        TAXI -> "taxi"
        BOARD_THE_FIRST-> "Montez à bord du premier"
        AC -> "AC"
        NON_AC -> "Non-AC"
        TAXI_FROM_ZONE _ -> "depuis la zone Yatri Sathi"
        ECONOMICAL -> "Économique"
        COMFY -> "Confortable"
        NAVIGATE -> "Naviguer"
        GOVERNMENT_CHAGRES -> "Charges du gouvernement"
        SERVICE_CHARGES -> "Frais de service"
        CONFIRM_AND_BOOK -> "Confirmer et réserver"
        PEOPLE -> "personnes"
        SPACIOUS -> "Spacieux"
        CANCEL_ONGOING_SEARCH -> "Êtes-vous sûr de vouloir continuer à annuler une recherche en cours?"
        SEARCH_AGAIN_WITH_A_TIP -> "Recherchez à nouveau avec un conseil?"
        TRY_AGAIN_WITH_A_TIP -> "Essayez à nouveau avec un pourboire?"
        BOOST_YOUR_RIDE_CHANCES_AND_HELP_DRIVERS_WITH_TIPS -> "Un pourboire pourrait aider à augmenter les chances de faire un tour. Aide le conducteur pendant les heures de pointe / compenser les voyages de retour vides"
        TRY_AGAIN_WITHOUT_TIP -> "Essayez à nouveau sans astuce"
        SEARCH_AGAIN_WITHOUT_A_TIP -> "Recherchez à nouveau sans astuce"
        TRY_AGAIN_WITH -> "Réessayez avec"
        SEARCH_AGAIN_WITH -> "Recherchez à nouveau avec"
        TIP -> "Conseil"
        CUSTOMER_SELECTED_FARE -> "Astuce du client ^"
        START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS -> "Commencez votre chat en utilisant ces suggestions de chat rapides"
        MESSAGE -> "Message"
        START_YOUR_CHAT_WITH_THE_DRIVER -> "Commencez votre conversation avec le conducteur"
        I_AM_ON_MY_WAY -> "Je suis en route"
        GETTING_DELAYED_PLEASE_WAIT -> "Retardé, veuillez patienter"
        UNREACHABLE_PLEASE_CALL_BACK -> "Injoignable, veuillez rappeler"
        ARE_YOU_STARING -> "Vous commencez?"
        PLEASE_COME_SOON -> "S'il vous plait venez bientot"
        OK_I_WILL_WAIT -> "D'accord, je vais attendre"
        I_HAVE_ARRIVED -> "Je suis arrivé"
        PLEASE_COME_FAST_I_AM_WAITING -> "S'il te plaît, viens vite, j'attends"
        PLEASE_WAIT_I_WILL_BE_THERE -> "Veuillez attendre, je serai là"
        LOOKING_FOR_YOU_AT_PICKUP -> "Vous cherchez au ramassage"
        MOBILE -> "Mobile"
        HOW_DO_YOU_IDENTIFY_YOURSELF -> "Comment vous identifiez-vous comme?"
        SELECT_YOUR_GENDER -> "Sélectionnez votre sexe"
        FEMALE -> "Femme"
        MALE -> "Homme"
        PREFER_NOT_TO_SAY -> "Je préfère ne pas le dire"
        EMAIL_ID -> "ID de messagerie"
        SET_NOW -> "Set maintenant"
        ADD_NOW -> "Ajouter maintenant"
        HOW_SHOULD_WE_ADDRESS_YOU -> "Comment devrions-nous nous adresser à vous?"
        GENDER_STR -> "Genre"
        PROFILE_COMPLETION -> "Complétion du profil"
        EARLY_END_RIDE_CHARGES -> "Charges de fin de trajet précoce ^"
        EARLY_END_RIDE_CHARGES_DESCRIPTION -> "^ La fin d'un trajet précoce précoce des charges supplémentaires s'élevant à la moitié du prix de la distance non travée (max. 50 ₹)"
        YES_TRY_AGAIN -> "Oui, réessayez"
        NO_DONT -> "Non, pas"
        YES_CANCEL_SEARCH -> "Oui, annulez la recherche"
        TRY_LOOKING_FOR_RIDES_AGAIN -> "Il semble que la journée soit très chargée. Vous pouvez essayer de chercher des manèges à nouveau"
        NO_TIP -> "Aucun conseil"
        CUSTOMER_TIP_DESCRIPTION -> "^ Montant supplémentaire ajouté par le client pour augmenter les chances d'obtenir un trajet."
        PLACE_CALL -> "Place Call"
        DIRECT_CALL -> "Appel direct"
        ANONYMOUS_CALL -> "Appel anonyme"
        YOUR_NUMBER_WILL_NOT_BE_SHOWN_TO_THE_DRIVER_THE_CALL_WILL_BE_RECORDED_FOR_COMPLIANCE -> "Votre numéro ne sera pas montré au chauffeur. L'appel sera enregistré pour conformité."
        YOUR_NUMBER_WILL_BE_VISIBLE_TO_THE_DRIVER_USE_IF_NOT_CALLING_FROM_REGISTERED_NUMBER -> "Votre numéro sera visible pour le conducteur. Utilisez si vous n'appelez pas à partir du numéro enregistré"
        CALL_DRIVER_USING -> "Appeler le chauffeur en utilisant :"
        WAS_YOUR_CALL_SUCCESSFUL -> "Votre appel a-t-il réussi"
        DRIVER_ADDITIONS -> "Ajouts de conducteur*"
        FARE_UPDATE_POLICY -> "Politique de mise à jour des tarifs"
        DRIVER_ADDITIONS_OPTIONAL -> "Ajouts de conducteur (optionnels)"
        THE_DRIVER_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "Le chauffeur peut proposer un montant supplémentaire pour couvrir les frais liés à la circulation, aux chances de trajet de retour, etc."
        DRIVER_ADDITIONS_ARE_CALCULATED_AT_RATE _ -> "Les limites d'ajouts de conducteur sont calculées à 10 % du tarif de base, arrondies au multiple de ₹10 le plus proche."
        DRIVER_MAY_NOT_CHARGE_THIS_ADDITIONAL_FARE -> "Note : Le chauffeur peut ou non facturer ce tarif supplémentaire."
        YOU_MAY_SEE_AN_UPDATED_FINAL_FARE_DUE_TO_ANY_OF_THE_BELOW_REASONS -> "Vous pourriez voir un tarif final mis à jour en raison de l'une des raisons suivantes :"
        REASON_CHANGE_IN_ROUTE_A -> "1. Changement en route:"
        REASON_CHANGE_IN_ROUTE_B -> "Le tarif total peut changer en raison d'un changement en route"
        GO_TO_ZONE _-> "Accédez à la zone de retrait"
        REQUEST_RECEIVED_WE_WILL_CALL_YOU_BACK_SOON -> "Demande reçue. Nous vous rappellerons bientôt"
        CONTACT_REMOVED_SUCCESSFULLY -> "Contact supprimé avec succès"
        CORPORATE_ADDRESS -> "Adresse de l'entreprise"
        CORPORATE_ADDRESS_DESCRIPTION _ -> "Juspay Technologies Private Limited <br> Girija Building, numéro 817, Ganapathi Temple Rd, 8th Block, Koramangala, Bengaluru, Karnataka 560095, Inde."
        CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL _-> "Site Web: <u> https://nammayatri.in/ </u>"
        REGISTERED_ADDRESS -> "Adresse enregistrée"
        REGISTERED_ADDRESS_DESCRIPTION _ -> "Juspay Technologies Private Limited <br>Stallion Business Centre, numero 444, 3e et 4e étage, 18e Main, 6e bloc, Koramangala Bengaluru, Karnataka- 560095, Inde."
        REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL _ -> "Site Web: <u> https://nammayatri.in/ </u>"
        FINDING_QUOTES_TEXT-> "chercher des taxis dans les environs"
        PLEASE_WAIT-> "S'il vous plaît, attendez!"
        RECOMMENDED-> "Recommandé"
        FASTER -> "Plus rapide"
        NEW_ -> "Nouvelle"
        METRO_RIDE-> "Balade en métro"
        DRIVER_IS_NEAR_YOUR_LOCATION -> "Le chauffeur est près de chez vous."
        PLEASE_CONTACT_THE_DRIVER_BEFORE_CANCELLING -> "\nVeuillez contacter le chauffeur avant d'annuler"
        CHANGE_OF_PLANS -> "Changement de plan"
        NO_LONGER_REQUIRE_A_RIDE_DUE_TO_CHANGE_IN_PLANS -> "Ne nécessite plus de trajet en raison d'un changement de plans"
        CANCELLING_AS_I_GOT_A_RIDE_ON_ANOTHER_APP -> "Annulation car j'ai fait un tour sur une autre application"
        DRIVER_IS_NOT_MOVING -> "Le conducteur ne bouge pas"
        DRIVER_LOCATION_WASNT_CHANGING_ON_THE_MAP -> "L'emplacement du conducteur ne changeait pas sur la carte"
        WRONG_PICKUP_LOCATION -> "Mauvais lieu de prise en charge"
        THE_PICKUP_LOCATION_ENTERED_WAS_WRONG -> "Le lieu de prise en charge saisi était erroné"
        SOME_OTHER_REASON -> "Une autre raison."
        WAIT_FOR_DRIVER -> "Attendre le chauffeur"
        DRIVER_WAS_TAKING_TOO_LONG_TO_REACH_THE_PICKUP_LOCATION -> "Le chauffeur mettait trop de temps à atteindre le lieu de prise en charge"
        ALLOW_LOCATION_ACCESS-> "Autoriser l'accès à la position"
        CALL_NAMMA_YATRI_SUPPORT _ -> "Prise en charge de la culture de passe d'appel"
        CALL_112-> "Appelez le 112"
        CALL_EMERGENCY_CENTRE-> "Appeler le centre d'urgence"
        DIAL_112-> "Composez le 112 ?"
        YOU_ARE_ABOUT_TO_CALL_NEAREST_EMERGENCY_CENTRE-> "Vous êtes sur le point d'appeler le centre d'urgence le plus proche. Voulez-vous poursuivre?"
        AC_TAXI -> "AC Taxi"
        NON_AC_TAXI -> "Taxi non climatisé"
        GET_OTP_VIA_WHATSAPP -> "Obtenez OTP via WhatsApp"
        OR -> "ou"
        HELPS_DRIVER_CONFIRM_ITS_YOU-> "(Aide le conducteur à confirmer qu'il s'agit bien de vous)"
        LETS_GET_YOU_TRIP_READY-> "Préparons-nous pour le voyage!"
        GOT_AN_OTP-> "Vous avez un OTP?"
        JUST_ONE_LAST_THING-> "Juste une dernière chose"
        TOLL_CHARGES_WILL_BE_EXTRA -> "Les frais de péage/stationnement seront en supplément"
        AUTO_RICKSHAW -> "Pousse-pousse automatique"
        CABS_AVAILABLE -> "cabines disponibles"
        SENT_OTP_VIA_WHATSAPP -> "OTP envoyé par WhatsApp"
        SENT_OTP_VIA_SMS -> "OTP envoyé par SMS"
        ENABLE_LOCATION_PERMISSION_TO-> "Activer l'autorisation de localisation pour rechercher des courses"
        AC_CAB -> "Cabine AC"
        AC_SUV -> "SUV climatisé"
        RIDE_TYPE -> "Type de trajet"
        ERNAKULAM_LIMIT_CHARGE -> "Le tarif sera de 1.5 x si la prise en charge ou la destination se situe en dehors des limites de la société Ernakulam"
        SELECT_LOCATION_ON_MAP -> "sélectionner l'emplacement sur la carte"
        PLEASE_ENABLE_LOCATION_PERMISSION _ -> "Veuillez activer les autorisations de localisation depuis l'application des paramètres pour commencer à rechercher des courses."
        YOU_SEEM_TO_BE_FAR_FROM_PICK_UP -> "Vous semblez être loin du lieu de prise en charge !"
        ARE_YOU_SURE_YOU_WANT_TO_PROCEED_WITH_THE_BOOKING -> "Êtes-vous sûr de vouloir procéder à la réservation ?"
        SOMETHING_WENT_WRONG_TRY_AGAIN_LATER -> "Quelque chose c'est mal passé. Merci d'essayer plus tard"
        MY_TICKETS -> "Mes billets"
        YOU_CAN_BOOK_TICKETS_TO_THE_ZOO_BY_CLICKING_THE_BUTTON -> ""
        DRIVER_ADDITION_LIMITS_ARE_IN_INCREMENTS -> ""
        CGST -> ""
        HATCHBACK -> ""
        HELP_US_WITH_YOUR_FEEDBACK_OPTIONAL -> ""
        ACTUAL_FARE_WAS_HIGHER_THAN_WHAT_WAS_SHOWN -> ""
        MORE_THAN -> ""
        SUV -> ""
        SEDAN -> ""
        LOCATION_PERMISSION_SUBTITLE -> ""
        COMPLETE_YOUR_PROFILE_FOR_A_PERSONALISED_RIDE_EXPERIENCE -> ""
        UPDATE_NOW -> ""
        WE_WOULD_APPRECIATE_YOUR_FEEDBACK -> ""
        REASON_FOR_DELETING_ACCOUNT -> ""
        SUBMIT_REQUEST -> ""
        PLEASE_ENTER_A_VALID_EMAIL -> ""
        WE_WOULD_APPRECIATE_YOUR_REASONING -> ""
        OK_GOT_IT -> ""
        YOUR_DRIVER_IS_JUST -> ""
        M_AWAY -> ""
        DRIVER_HAS_ALREADY_TRAVELLED -> ""
        DRIVER_MIGHT_BE_TAKING_ALTERNATE_ROUTE -> ""
        DRIVER_IS_NOT_MOVING_Q -> ""
        WOULD_YOU_LIKE_TO_CHECK_WITH_THE_DRIVER_BEFORE_CANCELLING -> ""
        LOCATION_PERMISSION_SUBTITLE_NEW_USER _ -> ""
        GO_BACK_TEXT -> ""
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_JUST -> ""
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST -> ""
        AND_HAS_TRAVELLED -> ""
        PLEASE_FIND_REVISED_FARE_ESTIMATE -> ""
        FARE_ESTIMATE -> ""
        TIP_SELECTED -> ""
        ADD_A_TIP_TO_FIND_A_RIDE_QUICKER -> ""
        IT_SEEMS_TO_BE_TAKING_LONGER_THAN_USUAL -> ""
        CONTINUE_SEARCH_WITH -> ""
        CONTINUING_SEARCH_WITH -> ""
        SEARCHING_WITH -> ""
        THE_DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION -> ""
        DRIVER_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION -> ""
        MESSAGE_FROM_DRIVER -> ""
        REPLY -> ""
        NAME_SHOULD_BE_MORE_THAN_2_CHARACTERS -> ""
        THIS_FIELD_IS_REQUIRED -> ""
        EMAIL_EXISTS_ALREADY -> ""
        OKAY_GOT_IT -> ""
        SEATS -> ""
        OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN -> ""
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER -> ""
        TOO_MANY_LOGIN_ATTEMPTS_PLEASE_TRY_AGAIN_LATER -> ""
        SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN -> ""
        SORRY_LIMIT_EXCEEDED_YOU_CANT_ADD_ANY_MORE_FAVOURITES -> ""
        IT_SEEMS_LIKE_YOU_HAVE_AN_ONGOING_RIDE_ -> ""
        CANCELLATION_UNSUCCESSFULL_PLEASE_TRY_AGAIN -> ""
        NO_DRIVER_AVAILABLE_AT_THE_MOMENT_PLEASE_TRY_AGAIN -> ""
        OTP_FOR_THE_JATRI_SATHI_ZONE_HAS_BEEN_EXPIRED_PLEASE_TRY_LOOKING_AGAIN _ -> ""
        NO_CONTACTS_FOUND_ON_THE_DEVICE_TO_BE_ADDED -> ""
        PLEASE_ENABLE_CONTACTS_PERMISSION_TO_PROCEED -> ""
        LIMIT_REACHED_3_OF_3_EMERGENCY_CONTACTS_ALREADY_ADDED -> ""
        INVALID_CONTACT_FORMAT -> ""
        OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER -> ""
        RATE_YOUR_EXPERIENCE -> ""
        REPORT_ISSUE_ -> ""
        DONE -> ""
        PLEASE_TELL_US_WHAT_WENT_WRONG -> ""
        YOUR_FEEDBACK_HELPS_US _ -> ""
        DID_YOU_FACE_ANY_ISSUE -> ""
        WE_NOTICED_YOUR_RIDE_ENDED_AWAY -> ""
        GET_CALLBACK_FROM_US -> ""
        DRIVER_WAS_NOT_READY_TO_GO -> ""
        ASKING_FOR_MORE_MONEY -> ""
        AUTO_BROKEN -> ""
        WE_WILL_GIVE_YOU_CALLBACK -> ""
        YOUR_ISSUE_HAS_BEEN_REPORTED -> ""
        OTP_RESENT_SUCCESSFULLY -> ""
        DESCRIPTION_SHOULD_BE_MORE_THAN_10_ALPHABETIC_CHARACTERS -> ""
        INCORRECT_OTP_PLEASE_TRY_AGAIN -> ""
        N_MORE_ATTEMPTS_LEFT -> ""
        GO_TO_SELECTED_PICKUP_SPOT -> ""
        GO_TO_SELECTED_PICKUP_SPOT_AS_AUTOS_ARE_RESTRICTED -> ""
        UNPROFESSIONAL_DRIVER -> ""
        RASH_DRIVING -> ""
        DRIVER_CHARGED_MORE -> ""
        UNCOMFORTABLE_AUTO -> ""
        TRIP_GOT_DELAYED -> ""
        FELT_UNSAFE -> ""
        POLITE_DRIVER -> ""
        EXPERT_DRIVING -> ""
        SAFE_RIDE -> ""
        CLEAN_AUTO -> ""
        ON_TIME -> ""
        SKILLED_NAVIGATOR -> ""
        RUDE_DRIVER -> ""
        TOO_MANY_CALLS -> ""
        RECKLESS_DRIVING -> ""
        LATE_DROP_OFF -> ""
        LATE_PICK_UP -> ""
        POOR_EXPERIENCE -> ""
        TERRIBLE_EXPERIENCE -> ""
        NEEDS_IMPROVEMENT -> ""
        AMAZING -> ""
        ALMOST_PERFECT -> ""
        ASKED_FOR_EXTRA_FARE -> ""
        ANYTHING_THAT_YOU_WOULD_LIKE_TO_TELL_US -> ""
        PLATFORM_FEE -> ""
        PAY_DRIVER_USING_WALLET -> ""
        SGST -> ""
        OTP_EXPIRED -> ""
        OTP_EXPIRED_DESCRIPTION -> ""
        PLATFORM_GST -> ""
        MISC_WAITING_CHARGE -> ""
        GENERAL_DISABILITY_DESCRIPTION -> ""
        PI_POINTER_1 -> ""
        PI_POINTER_2 -> ""
        VI_POINTER_1 -> ""
        VI_POINTER_2 -> ""
        HI_POINTER_1 -> ""
        HI_POINTER_2 -> ""
        DID_THE_DRIVER_OFFER_ASSISTANCE -> "Le chauffeur a-t-il proposé de l'aide ?"
        WAS_THE_DRIVER_UNDERSTANDING_OF_YOUR_NEEDS -> "Votre chauffeur a-t-il compris vos besoins et les a-t-il accueillis pendant le voyage ?"
        ACCESSIBILITY_TEXT _-> ""
        TO_CATER_YOUR_SPECIFIC_NEEDS _ -> ""
        SPECIAL_ASSISTANCE -> ""
        SELECT_THE_CONDITION_THAT_IS_APPLICABLE -> ""
        DISABILITY_CLAIMER_TEXT -> ""
        ARE_YOU_A_PERSON_WITH_DISABILITY -> ""
        DO_YOU_NEEED_SPECIAL_ASSISTANCE -> ""
        ASSISTANCE_REQUIRED -> ""
        NO_DISABILITY -> ""
        LEARN_HOW_TEXT _ -> ""
        UPDATE_PROFILE -> ""
        NOW_GET_ASSISTED_RIDES -> ""
        DOWNLOAD_DRIVER_RECEIPT -> ""
        VIEW_DRIVER_RECEIPT -> ""
        DRIVER_RECEIPT -> ""
        HELP -> ""
        FARE_INFO_TEXT _ -> ""
        EDUCATIONAL_POP_UP_SLIDE_1_TITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_2_TITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_3_TITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_4_TITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_5_TITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_1_SUBTITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_2_SUBTITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_3_SUBTITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_4_SUBTITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_5_SUBTITLE -> ""
        INCLUSIVE_AND_ACCESSIBLE -> ""
        WAIT_TIMER ->"Temporisateur d'attente"
        CHARGES_APPLICABLE_AFTER_3_MINS -> "Frais applicables après 3 minutes"
        REACHING_YOUR_DESTINATION_IN_ -> "Arriver à destination dans "
        WAITING_AT_PICKUP -> " en attente au ramassage "
        LEARN_MORE -> "En savoir plus"
        PICKUP -> "ramasser"
        PAY_BY_CASH_OR_UPI -> "Payer en espèces / UPI "
        YOU_WILL_PAY_FOR_EVERY_MINUTE -> "Les frais d'attente sont nuls pendant les 3 premières minutes. Vous serez payé pour 1.5 ₹ par minute de temps d'attente après cela."
        HOW_LONG_DRIVER_WAITED_FOR_PICKUP ->"Vous indique combien de temps le chauffeur a attendu lors de la prise en charge."
        CHAT_WITH -> "Parler avec"
        NAMMA_SAFETY -> "Notre sécurité"
        QUICK -> "rapide"
        CHATS -> "Discussions"
        REPLIES -> "réponses"
        YOU_SENT -> "tu as envoyé"
        MESSAGE_YOUR_DRIVER -> "Envoyez un message à votre chauffeur ?"
        CHECK_IN_WITH_YOUR_DRIVER -> "Enregistrez votre chauffeur avec un chat rapide"
        TRACK_ON_GOOGLE_MAPS -> "Suivre sur Google Maps"
        OTP_EXPIRE_TIMER -> "Minuterie d'expiration OTP"
        SHOWS_FOR_HOW_LONG_YOUR_OTP_ -> "Indique combien de temps votre OTP restera valide pour démarrer le trajet."
        IF_YOUR_OTP_EXPIRES_ -> "Si votre OTP expire, vous devrez réserver à nouveau."
        YOU_HAVE_REACHED_DESTINATION -> "Vous êtes arrivé à destination"
        PLACES_YOU_MIGHT_LIKE_TO_GO_TO-> "Les endroits que vous pourriez aimer visiter"
        SUGGESTED_DESTINATION-> "Destinations suggérées"
        RECENT_RIDES-> "Trajets récents"
        ONE_CLICK_BOOKING_FOR_YOUR_FAVOURITE_JOURNEYS-> "Réservation en un clic pour vos voyages préférés"
        VIEW_MORE-> "Voir plus"
        VIEW_LESS-> "Voir moins"
        HAVE_A_REFFERAL-> "Vous avez un code de référence?"
        YOUR_SUGGESTED_DESTINATIONS_AND_RECENT_RIDES_WILL_APPEAR_HERE -> "Vos destinations suggérées et vos trajets récents apparaîtront ici"
        WELCOME_TO_NAMMA_YATRI_ -> "Bienvenue à Namma Yatri!"
        BOOK_AND_MOVE -> "Réservez et déplacez-vous"
        ANYWHERE_IN_THE_CITY -> "Partout dans la ville"
        CHECKOUT_OUR_LIVE_STATS -> "Découvrez nos statistiques en direct"
        MOST_LOVED_APP _ -> "L'application automobile la plus ❤️ de Bengaluru"
        PICKUP_ -> "Ramasser-> "
        PAST_SEARCHES -> "Recherches passées"
        SEARCH_RESULTS -> "Résultats de la recherche"
        REQUESTING_RIDE_IN -> "Demande de trajet dans"
        REQUESTING_RIDE -> "Demande de trajet"
        TAP_HERE_TO_STOP_AUTO_REQUESTING -> "Appuyez ici pour arrêter la demande automatique"
        POWERED_BY -> "Alimenté par"
        BOOK_YOUR_RIDE -> "Réservez votre trajet"
        FARE_UPDATED_WITH_CHARGES -> "Le tarif a été mis à jour pour inclure les frais d'attente applicables"
        FARE_UPDATED_WITH_SHORTER_DIST -> "Votre tarif a été mis à jour car votre trajet était plus court de {} km"
        FARE_UPDATED_WITH_LONGER_DIST -> "Votre tarif a été mis à jour car votre trajet était plus long de {} km"
        FARE_UPDATED_WITH_CHARGES_SHORTER_DIST -> "Votre tarif a été mis à jour car votre trajet était plus court de {} km et des frais de temps d'attente ont été engagés"
        FARE_UPDATED_WITH_CHARGES_LONGER_DIST -> "Votre tarif a été mis à jour car votre trajet était plus long de {} km et des frais de temps d'attente ont été engagés"
        START_TYPING_TO_SEARCH_PLACES -> "Commencez à taper pour rechercher des lieux"
        DID_YOU_HAVE_A_SAFE_JOURNEY -> "Avez-vous fait un bon voyage ?"
        TRIP_WAS_SAFE_AND_WORRY_FREE -> "Nous aimerions nous assurer que votre voyage se déroule en toute sécurité et sans souci."
        DRIVER_BEHAVED_INAPPROPRIATELY -> "Le conducteur s'est comporté de manière inappropriée"
        I_DID_NOT_FEEL_SAFE -> "je ne me sentais pas en sécurité"
        LOOKING_FOR_ANOTHER_RIDE -> "À la recherche d'une autre course..."
        THE_RIDE_HAD_BEEN_CANCELLED_WE_ARE_FINDING_YOU_ANOTHER -> "Le trajet a dû être annulé, nous vous en trouvons un autre"
        ENJOY_THE_RIDE -> "Bon voyage jusqu'à votre destination !"
        RIDE_STARTED -> "Le trajet a commencé"
        DISCOVER_AWESOME_SPOTS_TAILORED_JUST_FOR_YOU -> "Découvrez des endroits géniaux adaptés à vos besoins"
        ONE_CLICK -> "1 clic"
        SMART -> "Intelligent"
        NOT_SERVICEABLE -> "Non réparable"
        WE_ARE_NOT_LIVE_IN_YOUR_AREA -> "Nous ne sommes pas encore en ligne dans votre région ! \nVous pouvez accéder à l'historique des courses et à d'autres \nparamètres à partir du menu en haut à gauche."
        FACING_PROBLEM_WITH_APP -> "Vous rencontrez des problèmes avec l'application ?"
        TAP_HERE_TO_REPORT -> "<u>Appuyez ici pour signaler un problème</u>"
        CONFIRM_YOUR_RIDE  -> "Confirmez votre trajet"
        RIDE_SCHEDULED -> "Trajet programmé"
        RIDE_STARTS_ON -> "Le trajet commence le"
        RENTAL_PACKAGE -> "Forfait location"
        GO_HOME -> "Rentrer chez soi"
        CANCEL_RENTAL_BOOKING -> "Annuler la réservation de location"
        ADD_FIRST_STOP -> "Ajouter le premier arrêt"
        DRIVER_WILL_BE_ASSIGNED_MINUTES_BEFORE_STARTING_THE_RIDE -> "Le chauffeur sera assigné {} minutes avant le début du trajet"
        YOUR_REPORTS -> "Vos rapports"
        VIEW -> "Voir"
        ISSUE_NO -> "Émettre aucune."
        ADD_VOICE_NOTE -> "Ajouter une note vocale"
        VOICE_NOTE -> "Note vocale"
        SUBMIT_ISSUE_DETAILS -> "Soumettre les détails du problème"
        IMAGE_PREVIEW -> "Aperçu de l'image"
        ADDED_IMAGES -> "Images ajoutées"
        NO_IMAGES_ADDED -> "Aucune image ajoutée"
        I_DONT_KNOW_WHICH_RIDE -> "Je ne sais pas quel trajet"
        ADDED_VOICE_NOTE -> "Note vocale ajoutée"
        NO_VOICE_NOTE_ADDED -> "Aucune note vocale ajoutée"
        CALL_DRIVER_TITLE -> "Appeler le chauffeur ?"
        CALL_SUPPORT_TITLE -> "Appeler l'assistance ?"
        CALL_DRIVER_DESCRIPTION -> "Vous êtes sur le point d'appeler le chauffeur. Voulez-vous poursuivre?"
        ADD_IMAGE -> "Ajouter une image"
        ADD_ANOTHER -> "Ajouter un autre"
        IMAGES -> "Images"
        ISSUE_SUBMITTED_TEXT -> "Attendez! Nous travaillons à résoudre votre problème"
        ISSUE_RESOLVED_TEXT -> "Problème résolu!"
        CHOOSE_AN_OPTION -> "Choisissez une option pour continuer"
        ISSUE_MARKED_AS_RESOLVED -> "Problème marqué comme résolu !"
        STILL_HAVING_ISSUE -> "Vous avez toujours un problème ?"
        IMAGE -> "Image"
        RECORD_VOICE_NOTE -> "Enregistrer une note vocale"
        CANCEL_BUTTON -> "Annuler"
        MAX_IMAGES -> "Un maximum de 3 images peuvent être téléchargées"
        SELECT_A_RIDE_TO_REPORT -> "Sélectionnez le trajet sur lequel signaler le problème"
        RIDE_RELATED_ISSUE_PAGE_NAME -> "Problème lié au trajet"
        APP_RELATED_ISSUE_PAGE_NAME -> "Problème lié à l'application"
        DRIVER_RELATED_ISSUE_PAGE_NAME -> "Problème lié au pilote"
        LOST_AND_FOUND_ISSUE_PAGE_NAME -> "Signaler un objet perdu"
        YEARS_AGO -> "il y a des années"
        MONTHS_AGO -> "il y a des mois"
        DAYS_AGO -> "il y a quelques jours"
        HOURS_AGO -> "il y a des heures"
        MIN_AGO -> "il y a quelques minutes"
        SEC_AGO -> "il y a quelques instants"
        REPORTED -> "Signalé"
        RESOLVED -> "Résolu"
        RESOLVED_ISSUES -> "Problèmes résolus"
        REPORTED_ISSUES -> "Problèmes signalés"
        OTHER_ISSUES -> "Autres questions"
        SOS_ISSUE_PAGE_NAME -> "Problème SOS"
        FARE_DISCREPANCIES_ISSUE_PAGE_NAME -> "Problème lié au tarif"
        PAYMENT_RELATED_ISSUE_PAGE_NAME -> "Problème lié au paiement"
        ACCOUNT_RELATED_ISSUE_PAGE_NAME -> "Problème lié au compte"
        REPORT_ISSUE_CHAT_PLACEHOLDER _ -> "Décrivez votre problème."
        CALL_SUPPORT_DESCRIPTION _ -> "Vous êtes sur le point d'appeler l'équipe d'assistance. Voulez-vous continuer ?"
        CANT_FIND_OPTION -> "Impossible de trouver l'option"
        NEED_HELP ->  "Besoin d'aide?"
        SAFETY_ISSUE_PAGE_NAME -> "Problème de sécurité"
        WE_HOPE_THE_ISSUE_IS_RESOLVED _ -> "Nous espérons que le problème est résolu"
        PLEASE_SELECT_THE_RIDE_TO_CALL_DRIVER -> "Veuillez sélectionner le trajet pour appeler le chauffeur"
        ADD_IMAGE_S -> "Ajouter une image"
        ALREADY_HAVE_AN_ACTIVE_RIDE -> "Vous avez déjà un trajet actif"
        CONFIRM_STOP_LOCATION -> "Confirm stop location"
        CONFIRM_DROP -> "Confirm Drop"
        SELECT_VEHICLE -> "Sélectionner un véhicule"
        BOOK_RENTAL -> "Réserver la location"
        CONFIRM_RENTAL -> "Confirmer la location"
        RENTAL_RIDE -> "Trajet en location"
        SELECT_DURATION -> "Sélectionner la durée"
        SELECT_DISTANCE -> "Sélectionner la distance"
        RENTAL_OPTIONS -> "Options de location"
        BOOKING_ON -> "Réservation le"
        INCLUDED_KMS -> "Kms inclus :"
        BASE_FARE -> "Tarif de base :"
        TOLLS_AND_PARKING_FEES -> "Péages et frais de stationnement"
        FINAL_FARE_DESCRIPTION -> "Le tarif final sera basé sur la durée réelle du trajet arrondie à l'heure suivante ou la durée du trajet sélectionnée (selon laquelle est la plus élevée)."
        EXCESS_DISTANCE_CHARGE_DESCRIPTION -> "Toute distance parcourue en excès des kms inclus sera facturée à"
        ADDITIONAL_CHARGES_DESCRIPTION -> "Des frais supplémentaires seront facturés après la fin de votre trajet."
        PARKING_FEES_AND_TOLLS_NOT_INCLUDED -> "Les frais de stationnement et les péages ne sont pas inclus. Veuillez les payer séparément au conducteur."
        NIGHT_TIME_FEE_DESCRIPTION -> "Des frais de nuit de {} seront facturés si votre trajet commence/se termine à n'importe quel moment entre 22h et 5h"
        CHOOSE_YOUR_RENTAL_RIDE -> "Choisissez votre trajet de location"
        FIRST_STOP_OPTIONAL -> "Premier arrêt (facultatif)"
        JANUARY -> "janvier"
        FEBRUARY -> "février"
        MARCH -> "mars"
        APRIL -> "avril"
        MAY -> "mai"
        JUNE -> "juin"
        JULY -> "juillet"
        AUGUST -> "août"
        SEPTEMBER -> "septembre"
        OCTOBER -> "octobre"
        NOVEMBER -> "novembre"
        DECEMBER -> "décembre"
        HOURS -> "heures"
        NOT_ADDED_YET -> "Pas encore ajouté"
        NEXT_STOP -> "Prochain arrêt"
        TIME -> "Temps"
        DISTANCE -> "Distance"
        STARTING_ODO -> "Départ ODO"
        END_OTP -> "Fin OTP"
        ONLY_LOCATION_WITHIN_CITY_LIMITS -> "Seuls les emplacements à l'intérieur des limites de la ville sont éligibles pour les locations."
        RIDE_TIME -> "Durée du trajet"
        RIDE_DISTANCE -> "Distance du trajet"
        RIDE_STARTED_AT -> "Le trajet a commencé à"
        RIDE_ENDED_AT -> "Le trajet s'est terminé à"
        ESTIMATED_FARE -> "Tarif estimé"
        EXTRA_TIME_PRICE -> "Prix du temps supplémentaire"
        TOTAL_FARE -> "Tarif total"
        FARE_UPDATE -> "Mise à jour du tarif"
        NOW -> "Maintenant"
        DATE_INVALID_MESSAGE -> "Date invalide. La réservation est disponible uniquement jusqu'à {} jours à l'avance"
        EDIT_PICKUP -> "Modifier la prise en charge"
        ADD_STOP -> "Ajouter un arrêt"
        ENTER_PICKUP_LOC ->  "Entrer l'emplacement de prise en charge"
        
