module Resources.Localizable.HI where

import Language.Types (STR(..))
import Prelude ((<>))
import Prelude ((<>))

getHI :: STR -> String
getHI stringKey =
    case stringKey of
        DOWNLOAD_INVOICE -> "इनवाइस को डाउनलोड करें"
        REPORT_AN_ISSUE -> "मामले की रिपोर्ट दर्ज करें"
        SUBMIT -> "जमा करें"
        VIEW_INVOICE -> "बिल देखें"
        YOU_RATED -> "आपकी रेटिंग"
        TOTAL_AMOUNT -> "कुल राशि"
        AMOUNT_PAID -> "राशि का भुगतान"
        TRIP_DETAILS_ -> "यात्रा विवरण"
        DOWNLOAD_PDF -> "डाउनलोड पीडीऍफ़"
        CGST -> "सीजीएसटी"
        INVOICE -> "बिल"
        TRIP_CHARGES -> "यात्रा शुल्क"
        PROMOTION -> "पदोन्नति"
        SEND_EMAIL -> "ईमेल भेजें"
        YOU_CAN_DESCRIBE_THE_ISSUE_YOU_FACED_HERE -> "आप यहां इस मुद्दे का वर्णन कर सकते हैं"
        THANK_YOU_FOR_WRITING -> "हमें सूचित करने के लिए धन्यवाद!"
        WE_HAVE_RECEIVED_YOUR_ISSUE -> "हमें आपका मुद्दा मिल गया है। हम कुछ समय में आप तक पहुंचेंगे."
        GO_HOME_ -> "गो होम"
        LOGO -> "प्रतीक चिन्ह"
        ABOUT_APP_DESCRIPTION -> "{} ड्राइवरों के साथ सवारों को जोड़ने के लिए एक खुला मंच है। ऐप सवारों के लिए मीटर दर के साथ एक सवारी बुक करने के लिए सुविधाजनक बनाता है इसलिए न्यूनतम किराया"
        TERMS_AND_CONDITIONS -> "टी & सी"
        ABOUT -> "एप के बारे में"
        PRIVACY_POLICY -> "गोपनीयता नीति"
        SET_UP_YOUR_ACCOUNT -> "अपना खाता स्थापित करें"
        CONTINUE -> "जारी रखें"
        ENTER_YOUR_NAME -> "अपना नाम दर्ज करें"
        FULL_NAME -> "पूरा नाम"
        EMAIL -> "ईमेल"
        WELCOME_TEXT -> "{} में आपका स्वागत है"
        PLEASE_CHOOSE_YOUR_PREFERRED_LANGUAGE_TO_CONTINUE -> "जारी रखने के लिए कृपया अपनी पसंदीदा भाषा चुनें।"
        WRITE_TO_US -> "हमे संपर्क करे"
        NOTE -> "टिप्पणी: "
        VISIT_MY_RIDES_SECTION_FOR_RIDE_SPECIFIC_COMPLAINTS -> "विशिष्ट शिकायतों के लिए मेरी सवारी विकल्प पर जाएँ"
        THANK_YOU_FOR_WRITING_TO_US -> "हमें सूचित करने के लिए धन्यवाद!"
        WE_HAVE_RECEIVED_YOUR_ISSUE_WELL_REACH_OUT_TO_YOU_IN_SOMETIME -> "हमें आपका मुद्दा मिला है। हम कुछ समय में आपके पास पहुंचेंगे।"
        GO_TO_HOME__ -> "होम"
        SUBJECT -> "विषय"
        YOUR_EMAIL_ID -> "आपकी ईमेल आईडी"
        DESCRIBE_YOUR_ISSUE -> "अपनी समस्या का वर्णन करें"
        ENTER_MOBILE_NUMBER -> "मोबाइल नंबर दर्ज करें"
        BY_TAPPING_CONTINUE -> "जारी रखें पर क्लिक करके, आप हमारी सहमति देते हैं"
        TO_THE -> "आप सहमत हैं कि आप स्वीकार कर रहे हैं"
        ENTER_OTP -> "OTP दर्ज करें"
        RESEND -> "पुन: भेजें"
        ENTER_YOUR_MOBILE_NUMBER -> "अपना मोबाइल नंबर दर्ज करें"
        LOGIN_USING_THE_OTP_SENT_TO -> "भेजे गए OTP का उपयोग करके लॉगिन करें"
        YOUR_RECENT_RIDE -> "आपकी हालिया सवारी"
        VIEW_ALL_RIDES -> "सभी सवारी देखें"
        ALL_TOPICS -> "सभी विषय"
        FAQ -> "सामान्य प्रश्न"
        REPORT_AN_ISSUE_WITH_THIS_TRIP -> "इस यात्रा के साथ एक मुद्दे की रिपोर्ट करें"
        GETTING_STARTED_AND_FAQS -> "आरंभ करना और अक्सर पूछे जाने वाले प्रश्न"
        FOR_OTHER_ISSUES_WRITE_TO_US -> "अन्य मुद्दों के लिए, हमें लिखें"
        HELP_AND_SUPPORT -> "सहायता और समर्थन"
        OUR_SUGGESTED_PRICE_FOR_THIS_TRIP_IS -> "इस यात्रा के लिए हमारी सुझाई गई कीमत है"
        DRIVERS_CAN_CHARGE_BETWEEN_THE_ABOVE_RANGE -> "*ड्राइवर उपरोक्त सीमा के बीच चार्ज कर सकते हैं"
        HOW_THIS_WORKS -> "यह कैसे काम करता है?"
        FINDING_RIDES_NEAR_YOU -> "आप के पास सवारी ढूंढना ..."
        CONFIRMING_THE_RIDE_FOR_YOU -> "आप के लिए सवारी की पुष्टि ..."
        CANCEL_SEARCH -> "खोज रद्द करें"
        YOUR_RIDE_IS_NOW_COMPLETE -> "आपकी सवारी अब पूरी हो गई है!"
        PLEASE_PAY_THE_FINAL_AMOUNT_TO_THE_DRIVER_VIA_CASH -> "कृपया ड्राइवर को सीधे अंतिम राशि का भुगतान करें"
        WHERE_TO -> "कहाँ ?"
        HOME -> "घर"
        PICK_UP_LOCATION -> "पिकअप करने की जगह"
        REQUEST_RIDE -> "अनुरोध सवारी"
        NAME -> "नाम"
        MOBILE_NUMBER_STR -> "मोबाइल नंबर"
        PERSONAL_DETAILS -> "व्यक्तिगत विवरण"
        YOUR_RIDES -> "आपकी सवारी"
        YOU_ARE_OFFLINE -> "आप ऑफ़लाइन हो"
        CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN -> "अपने इंटरनेट कनेक्शन की जाँच करें और पुनः प्रयास करें"
        TRY_AGAIN -> "पुनः प्रयास करें"
        THANK_YOUR_DRIVER -> "🙏 धन्यवाद ड्राइवर!"
        HOPE_YOUR_RIDE_WAS_HASSLE_FREE -> "आशा है कि आपकी सवारी परेशानी मुक्त थी"
        HOW_WAS_YOUR_RIDE_WITH -> " के साथ आपकी सवारी कैसी थी?"
        GOT_IT_TELL_US_MORE -> " समझ गये, हमे और सुचना दे"
        WRITE_A_COMMENT -> "एक टिप्पणी लिखें (वैकल्पिक)"
        UPDATE -> "अपडेट"
        LANGUAGE -> "भाषा"
        OTP -> "ओटीपी"
        PAYMENT_METHOD -> "भुगतान का तरीका"
        PAYMENT_METHOD_STRING -> "कैश / यूपीआई ऐप का इस्तेमाल करें"
        PAYMENT_METHOD_STRING_ -> "कैश / यूपीआई ऐप का इस्तेमाल करें"
        CANCEL_RIDE -> "मेरी राइड रद्द करें"
        REQUEST_EDIT -> "संपादन का अनुरोध करें"
        SUPPORT -> "सहायता"
        PICKUP_AND_DROP -> "पिकअप और ड्रॉप"
        CANCELLED -> "रद्द"
        HOW_THE_PRICING_WORKS -> "मूल्य निर्धारण कैसे काम करता है?"
        SELECT_AN_OFFER -> "एक प्रस्ताव का चयन करें"
        CHOOSE_A_RIDE_AS_PER_YOUR_COMFORT -> "अपने आराम के अनुसार एक सवारी चुनें"
        IT_SEEMS_TO_BE_A_VERY_BUSY_DAY -> "यह बहुत व्यस्त दिन लगता है। आप फिर से सवारी की तलाश कर सकते हैं"
        SORT_BY -> "इसके अनुसार क्रमबद्ध करें"
        SORRY_WE_COULDNT_FIND_ANY_RIDES -> "क्षमा करें, हमें कोई सवारी नहीं मिली"
        LOAD_MORE -> "और लोड करें"
        WE_NEED_ACCESS_TO_YOUR_LOCATION -> "हमें आपके स्थान तक पहुंच की आवश्यकता है!"
        LOCATION_PERMISSION_SUBTITLE -> "आपको राइड दिलाने के लिए, हमें आपके डिवाइस की लोकेशन की आवश्यकता होती है।"
        CALL -> "कॉल"
        EMPTY_RIDES -> "खाली सवारी सूची"
        YOU_HAVENT_TAKEN_A_TRIP_YET -> "आपने अभी तक कोई यात्रा नहीं की है!"
        BOOK_NOW -> "अभी बुक करें"
        T_AND_C_A -> "ए) आप इस बात से सहमत हैं कि आप बीटा परीक्षण के इच्छुक प्रतिभागी हैं और जुसपे का किसी भी संबंध में आपके खिलाफ कोई दायित्व नहीं होगा"
        DATA_COLLECTION_AUTHORITY -> "सी) मैं अपनी जानकारी एकत्र करने के लिए Juspay को नियुक्त और अधिकृत करता हूं, और जारी रखने से, मैं उपयोग की शर्तों और गोपनीयता नीति से सहमत हूं।"
        DENY_ACCESS -> "अस्वीकार करें"
        PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL -> "कृपया हमें बताएं कि आप रद्द क्यों करना चाहते हैं"
        MANDATORY -> "अनिवार्य"
        SOFTWARE_LICENSE -> "सॉफ़्टवेयर लाइसेंस"
        LOGOUT_ -> "लॉग आउट"
        REQUEST_AUTO_RIDE _-> "ऑटो राइड बुक करें"
        RATE_YOUR_RIDE -> "अपनी सवारी का मूल्यांकन करें"
        SKIP -> "स्किप करें"
        ERROR_404 -> "त्रुटि 404"
        PROBLEM_AT_OUR_END -> "हमारे अंत में एक समस्या प्रतीत होती है। जब हम फिर से उपलब्ध हों तो सूचित करें"
        NOTIFY_ME -> "मुझे सूचित करो"
        ADDRESS -> "पता"
        CHANGE -> "परिवर्तन"
        SAVE_AS -> "इस प्रप में सहेजें"
        ADD_TAG -> "टैग जोड़ो"
        WORK -> "काम"
        OTHER -> "अन्य"
        SAVE -> "सहेजें"
        ADD_NEW_ADDRESS -> "नया पता जोड़ें"
        SAVED_ADDRESSES -> "सहेजा गया पता"
        ADDRESSES -> "पतों"
        NO_FAVOURITES_SAVED_YET -> "अभी तक कोई पसंदीदा सहेजा नहीं गया है"
        SAVED_ADDRESS_HELPS_YOU_KEEP_YOUR_FAVOURITE_PLACES_HANDY -> "पसंदीदा स्थान आपके अक्सर देखे जाने वाले स्थानों को आसान रखने में मदद करता है"
        EMERGENCY_CONTACTS -> "आपातकालीन संपर्क"
        EDIT_EMERGENCY_CONTACTS -> "आपातकालीन संपर्क संपादित करें"
        ADD_EMERGENCY_CONTACTS -> "आपातकालीन संपर्क जोड़ें"
        NO_EMERGENCY_CONTACTS_SET -> "कोई आपातकालीन संपर्क सेट नहीं"
        COPIED -> "कॉपी किया गया"
        TRIP_ID -> "ट्रिप आईडी"
        SAVE_PLACE -> "स्थान सहेजें"
        RIDE_FARE -> "यात्रा राशि"
        ASK_FOR_PRICE -> "कीमत पूछे"
        ASK_FOR_PRICE_INFO -> "आपको ड्राइवरों द्वारा तय की गई पिक-अप दूरी के लिए अतिरिक्त 10 रुपये के मामूली शुल्क के साथ सरकार द्वारा निर्धारित आधार मूल्य के आधार पर किराया मिलेगा। कुछ ड्राइवर अतिरिक्त कारकों जैसे ट्रैफ़िक, वापसी यात्रा की संभावना आदि को कवर करने के लिए केवल अपने विवेक पर नाममात्र बख्शीश का अनुरोध कर सकते हैं।"
        GET_ESTIMATE_FARE -> "अनुमानित किराया प्राप्त करें"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS -> "एक प्रस्ताव का चयन करें (वैकल्पिक)"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS_INFO -> "डिफ़ॉल्ट रूप से, जब  “राइड को ऑटो-असाइन करें” चयनित होता है, तो आपको एक ड्राइवर असाइन किया जाएगा जो अनुमान सीमा के भीतर पहले स्वीकार करता है। इसके बजाय, यदि आप ड्राइवर ऑफ़र चुनना चाहते हैं, तो आप इस सुविधा का उपयोग करने के लिए अचयनित कर सकते हैं।"
        PAY_THE_DRIVER -> "ड्राइवर को भुगतान करें"
        PAY_THE_DRIVER_INFO -> "ड्राइवर को उस कीमत का भुगतान करें जिसकी आपने पुष्टि की थी।. "
        PAY_THE_DRIVER_NOTE -> "(सवारी की दूरी बदलने पर कुल किराया बदल सकता है)"
        UPDATE_PERSONAL_DETAILS -> "व्यक्तिगत विवरण अपडेट करें"
        EDIT -> "संपादन करना"
        DEL_ACCOUNT -> "खाता हटा दो"
        ACCOUNT_DELETION_CONFIRMATION -> "क्या आप इस खाते को हटाने के लिए सुनिश्चित हैं? आपके सभी व्यक्तिगत डेटा खो जाएंगे"
        REQUEST_SUBMITTED -> "अनुरोध सबमिट किया गया"
        WE_WILL_DELETE_YOUR_ACCOUNT -> "हमें यह देखकर खेद है कि आपने हमारे मंच को छोड़ दिया। आपका खाता अगले 30 दिनों के भीतर हटा दिया जाएगा। इस बीच यदि आप अपना खाता बनाए रखना चाहते हैं, तो कृपया हमारे ग्राहक सहायता नंबर पर कॉल करें"
        YES_DELETE_IT -> "हाँ, इसे हटा दें"
        REQUEST_TO_DELETE_ACCOUNT -> "खाता हटाने का अनुरोध करें"
        CANCEL_STR -> "रद्द करें"
        LOADING -> "लोड हो रहा है"
        PLEASE_WAIT_WHILE_IN_PROGRESS -> "कृपया प्रगति के दौरान प्रतीक्षा करें"
        SET_LOCATION_ON_MAP -> "मानचित्र पर स्थान निर्धारित करें"
        CURRENT_LOCATION -> "वर्तमान स्थान"
        PREVIOUS_FARE -> "पिछला किराया"
        FARE_UPDATED -> "नया किराया"
        PLEASE_CONFIRM_WITH_YOUR_AFTER_REQUESTING -> "अनुरोध के बाद कृपया ड्राइवर से पुष्टि करें"
        PREVIOUSLY -> "पहले"
        ROUTE_AND_FARE_UPDATED -> "संशोधित मार्ग और किराया"
        YOUR_DRIVER_MIGHT_WANT_TO_GO_TOWARDS_THE_CURRENT_DROP_KINDLY_ASK_THEM_TO_CONFIRM_AFTER_REQUESTING -> "आपका ड्राइवर वर्तमान ड्रॉप की ओर जाना चाहता है। अनुरोध करने के बाद कृपया उनसे पुष्टि करने के लिए कहें।"
        ACTUAL_FARE_WAS_HIGHER_THAN_WHAT_WAS_SHOWN -> "वास्तविक किराया जो दिखाया गया था उससे अधिक था।"
        DELETE -> "मिटायें"
        ARE_YOU_SURE_YOU_WANT_TO_LOGOUT -> "क्या आप लॉग आउट करना चाहते हैं ?"
        ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "क्या आप रद्द करना चाहते हैं ?"
        YOU_HAVE_RIDE_OFFERS_ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "आपके पास राइड ऑफ़र हैं, क्या आप वाकई रद्द करना चाहते हैं?"
        GO_BACK_ -> "वापस जाओ"
        REGISTER_USING_DIFFERENT_NUMBER -> "क्या आप किसी भिन्न मोबाइल नंबर का उपयोग करके पंजीकरण करना चाहते हैं?"
        YES -> "हाँ"
        NO -> "नहीं"
        CANCEL_ -> "रद्द करें"
        IS_ON_THE_WAY -> "रास्ते मे है"
        ENTER_4_DIGIT_OTP -> "4 अंकों का ओटीपी दर्ज करें"
        WRONG_OTP -> "गलत ओटीपी"
        GRANT_ACCESS -> "पहुँच प्रदान करें"
        ENTER_A_LOCATION -> "एक स्थान दर्ज करें"
        NEARBY -> "नज़दीक"
        MINS_AWAY -> "मिनट दूर"
        PAID -> "प्रदत्त"
        BY_CASH -> "नकद द्वारा"
        ONLINE_ -> "ऑनलाइन"
        USER -> "उपयोगकर्ता"
        EMAIL_ALREADY_EXISTS -> "ईमेल अपडेट करने में विफल. ईमेल पहले से मौजूद है।"
        IN -> "में"
        VERIFYING_OTP -> "सत्यापन ओटीपी"
        TRACK_LIVE_LOCATION_USING -> "लाइव स्थान का उपयोग करके ट्रैक करें"
        GOOGLE_MAP_ -> "गूगल मेप"
        IN_APP_TRACKING -> "ऐप ट्रैकिंग में"
        QUOTE_EXPIRED -> "भाव समाप्त"
        GETTING_ESTIMATES_FOR_YOU -> "आपके लिए अनुमान प्राप्त किए जा रहे हैं..."
        GETTING_REVISED_ESTIMATE -> "संशोधित अनुमान प्राप्त किया जा रहा है"
        CONFIRM_PICKUP_LOCATION -> "पिकअप स्थान की पुष्टि करें"
        CONFIRM_DROP_LOCATION -> "ड्रॉप स्थान की पुष्टि करें"
        CHECK_REVISED_FARE_AND_ROUTE -> "संशोधित किराया और मार्ग जांचें"
        ERROR_OCCURED_TRY_AGAIN -> "त्रुटि हुई। पुनः प्रयास करें"
        ASKED_FOR_MORE_MONEY -> "और पैसे मांगे"
        START_ -> "प्रारंभ"
        RIDE_NOT_SERVICEABLE -> "सवारी सेवा योग्य नहीं"
        APP_NOT_SERVICEABLE -> "ऐप सेवा योग्य नहीं है"
        CONFIRM_FOR -> "के लिए पुष्टि करें"
        ETA_WAS_TOO_SHORT -> "ईटीए बहुत छोटा था।"
        DRIVER_REQUESTED_TO_CANCEL -> "ड्राइवर ने मुझे रद्द करने का अनुरोध किया"
        PICK_UP_LOCATION_INCORRECT -> "पिकअप का स्थान गलत था।"
        COULD_NOT_CONNECT_TO_DRIVER -> "मैं ड्राइवर से कनेक्ट नहीं हो सका।"
        ETA_WAS_TOO_LONG -> "ईटीए बहुत लंबा था।"
        OTHERS -> "अन्य"
        DESTINATION_OUTSIDE_LIMITS -> "दर्ज किया गया गंतव्य शहर की सीमा के बाहर है"
        DROP_LOCATION_FAR_AWAY -> "आपका ड्रॉप स्थान बहुत दूर है"
        CHANGE_DROP_LOCATION -> "ड्रॉप स्थान बदलें"
        YOU_CAN_TAKE_A_WALK_OR_CONTINUE_WITH_RIDE_BOOKING -> "आप पैदल चलकर जा सकते हैं या सवारी बुकिंग जारी रख सकते हैं"
        YOUR_TRIP_IS_TOO_SHORT_YOU_ARE_JUST -> "आपकी यात्रा बहुत छोटी है। आप अपने गंतव्य से सिर्फ "
        METERS_AWAY_FROM_YOUR_DESTINATION -> " मीटर दूर हैं!"
        BOOK_RIDE_ -> "सवारी बुक करें"
        LOCATION_UNSERVICEABLE -> "स्थान अनुपयोगी"
        CURRENTLY_WE_ARE_LIVE_IN_ _  -> "हम अभी तक आपके क्षेत्र में नहीं हैं!\nआप मेनू से सवारी इतिहास और अन्य सेटिंग्स तक पहुंच सकते हैं"
        CHANGE_LOCATION -> "स्थान बदलें"
        IF_YOU_STILL_WANNA_BOOK_RIDE_CLICK_CONTINUE_AND_START_BOOKING_THE_RIDE -> "यदि आप अभी भी सवारी बुक करना चाहते हैं तो जारी रखें पर क्लिक करें और सवारी की बुकिंग शुरू करें"
        THE_TRIP_IS_VERY_SHORT_AND_JUST_TAKE -> "यात्रा बहुत छोटी है और इसे पूरा करने के लिए केवल "
        STEPS_TO_COMPLETE -> " चरणों की आवश्यकता है"
        CANCEL_AUTO_ASSIGNING -> "ऑटो असाइनिंग रद्द करें"
        AUTO_ACCEPTING_SELECTED_RIDE -> " में ऑटो स्वीकार"
        HELP_US_WITH_YOUR_REASON -> "अपने कारण से हमारी मदद करें"
        MAX_CHAR_LIMIT_REACHED -> "अधिकतम वर्ण सीमा पूरी हुई,"
        DRIVER_WAS_NOT_REACHABLE -> "ड्राइवर उपलब्ध नहीं था"
        SHOW_ALL_OPTIONS -> "सभी विकल्प दिखाएं"
        EXPIRES_IN -> "  में समाप्त "
        PAY_DIRECTLY_TO_YOUR_DRIVER_USING_CASH_UPI -> "*Cash/UPI का उपयोग करके सीधे अपने ड्राइवर को भुगतान करें"
        UPDATE_REQUIRED -> "अद्यतन आवश्यक है"
        PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE -> "कृपया सेवा जारी रखने के लिए ऐप को अपडेट करें"
        NOT_NOW -> "अभी नहीं"
        OF -> "में से"
        LOST_SOMETHING -> "क्या आपने कुछ खोया है?"
        TRY_CONNECTING_WITH_THE_DRIVER -> "आप ड्राइवर से कॉलबैक का अनुरोध कर सकते हैं"
        CALL_DRIVER -> "ड्राइवर से संपर्क करें"
        NO_MORE_RIDES -> "कोई और सवारी नहीं"
        CONTACT_SUPPORT -> "सहयोग टीम से संपर्क करें"
        INVALID_MOBILE_NUMBER -> "गलत मोबाइल नंबर"
        CONFIRM_LOCATION -> "स्थान की पुष्टि करें"
        RIDE_COMPLETED -> "सवारी पूरी हुई"
        SUBMIT_FEEDBACK -> "प्रतिपुष्टि दें"
        HOW_WAS_YOUR_RIDE_EXPERIENCE -> "आपकी सवारी का अनुभव कैसा रहा?"
        DROP -> "ड्रॉप"
        RATE_YOUR_RIDE_WITH -> " के साथ अपनी राइड को रेट करें"
        VIEW_BREAKDOWN -> "ब्रेकडाउन देखें"
        PAY_DRIVER_USING_CASH_OR_UPI -> "Cash/UPI का उपयोग कर ड्राइवर को भुगतान करें"
        PAY_DRIVER_USING_CASH_OR_UPI_ -> "Cash/UPI का उपयोग कर ड्राइवर को भुगतान करें"
        RATE_YOUR_DRIVER -> "अपने ड्राइवर को रेट करें"
        MY_RIDES -> "मेरी सवारी"
        RIDE_ID -> "सवारी आईडी"
        RIDE_DETAILS -> "सवारी विवरण"
        SELECT_A_RIDE -> "ज़्यादा जानकारी के लिए कोई राइड चुनें"
        CONFIRM_RIDE_ -> "सवारी की पुष्टि करें"
        YOU_CAN_CANCEL_RIDE -> "ड्राइवर पार्टनर से ऑफ़र मिलने के बाद आप रद्द कर सकते हैं"
        ESTIMATES_CHANGED -> "आपकी राइड की अनुमानित कीमत अब बदल गई है "
        ESTIMATES_REVISED_TO -> "संशोधित अनुमानित कीमत है"
        RATE_CARD -> "रेट कार्ड"
        NIGHT_TIME_CHARGES from till -> "रात के समय का शुल्क"
        MIN_FARE_UPTO val -> "न्यूनतम किराया " <> val <>" तक"
        MORE_THAN -> "किलोमीटर से अधिक"
        RATE_ABOVE_MIN_FARE -> "न्यूनतम किराए से ऊपर की दर"
        DRIVER_PICKUP_CHARGES _ -> "ड्राइवर के आने का शुल्क"
        DAYTIME_CHARGES_APPLICABLE_AT_NIGHT from till-> " गुना शुल्क से रात "<> from <> " से सुबह " <> till <>" तक"
        DAYTIME_CHARGES_APPLIED_AT_NIGHT percentage from till -> from <> " बजे से "<> till <>" बजे तक रात (🌙) में डेटाइम चार्जेस के "<> percentage <>"x लागू"
        DRIVERS_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "* चालक वैकल्पिक रूप से यातायात, वापसी यात्रा की संभावना आदि को कवर करने के लिए आधार किराए के 10% (निकटतम रु.10 तक) का अनुरोध कर सकता है।"
        GOT_IT -> "समझ गया!"
        DAY_TIME_CHARGES from till -> "दिन के समय शुल्क"
        SHARE_APP -> "ऐप शेयर करें"
        AWAY_C -> "दूर"
        AWAY -> "दूर"
        AT_PICKUP -> "At Pickup"
        FARE_HAS_BEEN_UPDATED -> "किराया अपडेट किया"
        TOTAL_FARE_MAY_CHANGE_DUE_TO_CHANGE_IN_ROUTE -> "रूट में बदलाव के कारण कुल किराए में बदलाव हो सकता है"
        AT_DROP -> "At Drop"
        EMERGENCY_HELP -> "आपातकालीन सहायता"
        ALSO_SHARE_YOUR_RIDE_STATUS_AND_LOCATION -> "आपकी सवारी की स्थिति और स्थान भी साझा करे"
        SHARE_RIDE_WITH_EMERGENCY_CONTACTS -> "आपातकालीन संपर्कों के साथ राइड शेयर करें"
        DO_YOU_NEED_EMERGENCY_HELP -> "क्या आपको आपातकालीन सहायता की आवश्यकता है ?"
        CALL_SUPPORT -> "हमारे समर्थन को कॉल करें"
        YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT _  -> "आप नम्मा यात्री सपोर्ट टीम को कॉल करने वाले हैं। क्या आप आगे बढ़ना चाहते हैं?"
        YOU_ARE_ABOUT_TO_CALL_NEAREST_EMERGENCY_CENTRE -> "आप निकटतम आपातकालीन केंद्र पर कॉल करने वाले हैं। क्या आप आगे बढ़ना चाहते हैं?"
        DIAL_112 -> "डायल 112"
        HELP_US_WITH_YOUR_FEEDBACK_OPTIONAL -> "अपने फीडबैक से हमारी सहायता करें (वैकल्पिक)"
        WAIT_TIME -> "प्रतीक्षा समय"
        FAVOURITES -> "पसंदीदा"
        ADD_FAVOURITE -> "पसंदीदा जोड़ें"
        ALL_FAVOURITES -> "सभी पसंदीदा"
        REMOVE -> "हटाएं"
        SELECT_ON_MAP -> "मानचित्र पर चयन करें"
        FAVOURITE_LOCATION -> "पसंदीदा स्थान"
        EDIT_FAVOURITE -> "पसंदीदा संपादित करें"
        DRAG_THE_MAP -> "मानचित्र को खींचें और पिन को सटीक स्थान पर सेट करें"
        CHOOSE_ON_MAP -> "मानचित्र पर चुनें"
        USE_CURRENT_LOCATION -> "वर्तमान स्थान का प्रयोग करें"
        FAVOURITE_YOUR_CURRENT_LOCATION -> "अपने वर्तमान स्थान को पसंदीदा बनाएं"
        LOCATION -> "जगह"
        LOCATION_ALREADY_EXISTS_AS -> "पहले से ही मौजूद है"
        GIVE_THIS_LOCATION_A_NAME -> "इस स्थान को एक नाम दें"
        FAVOURITE -> "पसंदीदा"
        CONFIRM_AND_SAVE -> "कन्फर्म & सेव"
        REMOVE_FAVOURITE -> "पसंदीदा हटाएं"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_FAVOURITE_ -> "क्या आप वाकई पसंदीदा को हटाना \n चाहते हैं?"
        YES_REMOVE -> "हाँ, हटाओ"
        ADD_NEW_FAVOURITE -> "नया पसंदीदा जोड़ें"
        SELECT_YOUR_DROP -> "अपना ड्रॉप चुनें"
        FAVOURITE_REMOVED_SUCCESSFULLY -> "पसंदीदा सफलतापूर्वक निकाला गया"
        LOCATION_ALREADY_EXISTS -> "लोकेशन पहले से मौजूद है"
        LOCATION_ALREADY -> "स्थान पहले से ही"
        EXISTS_AS -> "के रूप में मौजूद है"
        FAVOURITE_ADDED_SUCCESSFULLY -> "पसंदीदा सफलतापूर्वक जोड़ा गया"
        FAVOURITE_UPDATED_SUCCESSFULLY -> "पसंदीदा सफलतापूर्वक अपडेट किया गया"
        ALREADY_EXISTS -> "पहले से ही मौजूद है"
        NAME_ALREADY_IN_USE -> "नाम पहले से उपयोग में है"
        SELECT_FAVOURITE -> "पसंदीदा चुनें"
        CONFIRM_CHANGES -> "परिवर्तनों की पुष्टि करें"
        ADD_SAVED_LOCATION_FROM_SETTINGS -> "*आप साइड मेनू > पसंदीदा से नया पसंदीदा जोड़ सकते हैं"
        YOU_WILL_BE_ASKED_TO_SELECT_CONTACTS -> "आपको अधिकतम 3 संपर्कों का चयन करने के लिए कहा जाएगा"
        AUTO_ASSIGN_A_RIDE -> "राइड को ऑटो-असाइन करें"
        IS_WAITING_AT_PICKUP -> "लेने का इंतज़ार कर रहा है"
        WAIT_TIME_TOO_LONG -> "प्रतीक्षा समय बहुत लंबा है"
        GOT_ANOTHER_RIDE_ELSE_WHERE -> "दूसरी सवारी मिली"
        DRIVER_WAS_RUDE -> "ड्राइवर बदतमीजी कर रहा था"
        MAYBE_LATER -> "शायद बाद में"
        YOUR_RIDE_HAS_STARTED -> "वाह! आपकी राइड शुरू हो गई है 🤩"
        ENJOY_RIDING_WITH_US -> "हमारे साथ सवारी का आनंद ले रहे हैं? शब्द \n और खुशियाँ शेयर करें"
        VIEW_DETAILS -> "विवरण देखें"
        REPEAT_RIDE -> "रिपीट राइड"
        FARE_WAS_HIGH -> "किराया अधिक था"
        AUTO_ASSIGN_DRIVER -> "ड्राइवर को ऑटो-असाइन करें"
        CHOOSE_BETWEEN_MULTIPLE_DRIVERS -> "एकाधिक ड्राइवरों के बीच चुनें"
        CHOOSE_BETWEEN_MULTIPLE_RIDES -> "एक से अधिक राइड के बीच चुनें"
        ENABLE_THIS_FEATURE_TO_CHOOSE_YOUR_RIDE -> "अपनी राइड का चयन करने के लिए इस विशेषता को सक्षम करें"
        BOOKING_PREFERENCE -> "बुकिंग वरीयता"
        BASE_FARES -> "बेस किराया"
        PICKUP_CHARGE -> "पिकअप शुल्क"
        TOTAL_PAID -> "पूर्ण भुगतान"
        WAITING_CHARGE -> "प्रतीक्षा प्रभार"
        NOMINAL_FARE -> "वैकल्पिक ड्राइवर का अनुरोध*"
        CUSTOMER_CANCELLATION_DUES -> "रद्दीकरण बकाया"
        DRIVERS_CAN_CHARGE_AN_ADDITIONAL_FARE_UPTO -> "* ड्राइवर वैकल्पिक रूप से ट्रैफ़िक, वापसी यात्रा की संभावना आदि जैसे अन्य कारकों को कवर करने के लिए बेस फेयर के 10% (निकटतम रु. 10 तक) का अनुरोध कर सकते हैं।"
        WAITING_CHARGE_DESCRIPTION -> "°प्रतीक्षा शुल्क पहले {} मिनट के लिए शून्य है। उसके बाद आपसे प्रति मिनट प्रतीक्षा समय के लिए ₹{} शुल्क लिया जाएगा।"
        WAITING_CHARGE_RATECARD_DESCRIPTION waitingCharge freeWaitingTime -> "1. पहले 3 मिनट के लिए वेटिंग चार्ज शून्य है।\n 2. इसके बाद प्रति मिनट 1.5 रुपये का प्रतीक्षा शुल्क लागू होगा।"
        WAITING_CHARGE_INFO waitingCharge freeWaitingTime ->  "प्रतीक्षा के पहले "<> freeWaitingTime <>" मिनट के बाद " <> waitingCharge <>" प्रति मिनट की दर से लागू"
        SUCCESSFUL_ONBOARD _ -> "आपने नम्मा यात्री में सफलतापूर्वक साइन इन कर लिया है"
        HAVE_REFERRAL_CODE -> "रेफरल कोड है?"
        REFEREAL_CODE_DISCRIPTION -> "आपका रेफ़रल किसी ड्राइवर को पुरस्कृत किए जाने \n का कारण हो सकता है!"
        SIX_DIGIT_REFERRAL_CODE -> "ड्राइवर द्वारा साझा किया गया 6 अंकों का कोड दर्ज करें"
        ABOUT_REFERRAL_PROGRAM -> "रेफरल प्रोग्राम क्या है?"
        ABOUT_REFERRAL_PROGRAM_DISCRIPTION _ -> "रेफ़रल कार्यक्रम ड्राइवरों को अधिक सवारी स्वीकार करने,सवारी कम रद्द करने और योग्य ड्राइवरों को पहचानने और पुरस्कृत करके आपको बेहतर सेवा देने के लिए प्रोत्साहित करता है। \nआप ड्राइवर का रेफरल कोड डालकर मदद कर सकते हैं और नम्मा यात्री समुदाय के लिए सवारी की गुणवत्ता में सुधार कर सकते हैं!"
        YOU_CAN_GET_REFERRAL_CODE_FROM_DRIVER _ -> "\nआप अपने नम्मा यात्री ड्राइवर से पूछकर एक रेफरल कोड प्राप्त कर सकते हैं।"
        REFERRAL_CODE_SUCCESSFULL -> "आपने रेफ़रल कोड सफलतापूर्वक लागू कर दिया है"
        REFERRAL_CODE_APPLIED -> "रेफ़रल लागू!"
        HEY -> "नमस्ते"
        INVALID_CODE_PLEASE_RE_ENTER -> "अवैध कोड। कृपया पुनः दर्ज करें"
        LET_TRY_THAT_AGAIN -> "आइए फिर से कोशिश करें..."
        CONTACTS_SELECTED -> "संपर्क चयनित"
        SELECT_CONTACTS -> "संपर्क चुनें"
        CONFIRM_EMERGENCY_CONTACTS -> "आपके आपातकालीन संपर्क की पुष्टि करें"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_CONTACT -> "क्या आप वाकई उन्हें अपने आपातकालीन संपर्कों से हटाना चाहते हैं?"
        SEARCH_CONTACTS -> "संपर्क खोजें"
        CALL_EMERGENCY_CONTACTS -> "आपातकालीन संपर्कों को कॉल करें"
        LIVE_STATS_DASHBOARD -> "लाइव आँकड़े डैशबोर्ड"
        CHECK_OUT_LIVE_STATS -> "लाइव आंकड़े देखें"
        ADD_ANOTHER_CONTACT -> "अन्य संपर्क जोड़ें"
        EMERGENCY_CONTACS_ADDED_SUCCESSFULLY -> "आपातकालीन संपर्क सफलतापूर्वक जोड़े गए हैं।"
        NO_CONTACTS_LEFT_ON_DEVICE_TO_ADD -> "जोड़ने के लिए कोई संपर्क नहीं बचा है।"
        PERCENTAGE_OF_NOMINAL_FARE -> "~ बेस फेयर का 10%"
        PAY_VIA_CASH_OR_UPI -> "नकद / यूपीआई के माध्यम से भुगतान करें"
        REQUEST_CALLBACK -> "कॉलबैक का अनुरोध करें"
        TAXI_FROM_ZONE _ -> "टैक्सी में सवार हों"
        BOARD_THE_FIRST -> "यात्री साथी अंचल से पहली"
        TAXI -> "टैक्सी" 
        AC -> "एसी"
        NON_AC -> "नॉन-एसी"
        CHOOSE_YOUR_RIDE -> "अपनी सवारी चुनें"
        ECONOMICAL -> "किफ़ायती"
        COMFY -> "आरामदायक"
        NAVIGATE -> "नेविगेट"
        GOVERNMENT_CHAGRES -> "सवारी जीएसटी (5%)"
        SERVICE_CHARGES -> "सेवा शुल्क"
        CONFIRM_AND_BOOK -> "पुष्टि करें और बुक करें"
        PEOPLE -> "लोग"
        SPACIOUS -> "विशाल"
        SEARCH_AGAIN_WITH_A_TIP -> "टिप के साथ फिर से खोजें?"
        TRY_AGAIN_WITH_A_TIP -> "टिप के साथ पुन: प्रयास करें?"
        BOOST_YOUR_RIDE_CHANCES_AND_HELP_DRIVERS_WITH_TIPS -> "ऐसा लगता है कि यह बहुत ही व्यस्त दिन है। सवारी मिलने की संभावना बढ़ाने के लिए आप बख्शीश जोड़ने की कोशिश कर सकते हैं।"
        TRY_AGAIN_WITHOUT_TIP -> "टिप के बिना पुन: प्रयास करें"
        SEARCH_AGAIN_WITHOUT_A_TIP -> "टिप के बिना फिर से खोजें"
        TRY_AGAIN_WITH -> "दुबारा कोशिश करें"
        SEARCH_AGAIN_WITH -> "दोबारा सर्च करे"
        TIP -> "टिप"
        START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS -> "इन त्वरित चैट सुझावों का उपयोग करके अपनी चैट प्रारंभ करें"
        MESSAGE -> "संदेश"
        I_AM_ON_MY_WAY -> "मैं रास्ते में हूं|"
        GETTING_DELAYED_PLEASE_WAIT -> "देरी हो रही है। प्रतीक्षा करें|"
        UNREACHABLE_PLEASE_CALL_BACK -> "पहुंच योग्य नहीं है, वापस कॉल करें।"
        ARE_YOU_STARING -> "क्या आप आ रहे हैं?"
        PLEASE_COME_SOON -> "कृपया जल्दी आ जाएँ|"
        OK_I_WILL_WAIT -> "मैं इंतज़ार करूंगा|"
        I_HAVE_ARRIVED -> "मैं पहूंच गया हूं|"
        PLEASE_COME_FAST_I_AM_WAITING -> "जल्दी आइए, मैं इंतजार कर रहा हूं।"
        PLEASE_WAIT_I_WILL_BE_THERE -> "कृपया प्रतीक्षा करें, मैं आ रहा हूँ|"
        LOOKING_FOR_YOU_AT_PICKUP -> "मैं पिकअप पर हूँ|"
        START_YOUR_CHAT_WITH_THE_DRIVER -> "ड्राइवर के साथ अपनी चैट शुरू करें|"
        MOBILE -> "मोबाइल"
        HOW_DO_YOU_IDENTIFY_YOURSELF -> "आप अपने आप को कैसे पहचानते हैं?"
        SELECT_YOUR_GENDER -> "अपना लिंग चुनें"
        FEMALE -> "महिला"
        MALE -> "पुरुष"
        PREFER_NOT_TO_SAY -> "चुप रहना पसंद करूंगा"
        EMAIL_ID -> "ईमेल आईडी"
        SET_NOW -> "अभी सेट करें"
        ADD_NOW -> "अभी जोड़ें"
        HOW_SHOULD_WE_ADDRESS_YOU -> "हमें आपको कैसे संबोधित करना चाहिए?"
        GENDER_STR -> "लिंग"
        PROFILE_COMPLETION -> "प्रोफ़ाइल पूर्णता"
        EARLY_END_RIDE_CHARGES -> "जल्दी सवारी खत्म करने का शुल्क^"
        EARLY_END_RIDE_CHARGES_DESCRIPTION -> "^जल्दी सवारी खत्म करने पर अतिरिक्त शुल्क लगता है जो तय नहीं की गई दूरी का आधा किराया होता है (अधिकतम ₹50)।"
        CANCEL_ONGOING_SEARCH -> "क्या आप वाकई चल रही खोज को रद्द करना जारी रखना चाहते हैं?"
        YES_TRY_AGAIN -> "हाँ, पुन: प्रयास करें"
        NO_DONT -> "नहीं"
        YES_CANCEL_SEARCH -> "हाँ, खोज रद्द करें"
        TRY_LOOKING_FOR_RIDES_AGAIN -> "ऐसा लगता है कि यह बहुत ही व्यस्त दिन है। आप फिर से राइड खोजने की कोशिश कर सकते हैं"
        NO_TIP -> "कोई टिप नहीं"
        CUSTOMER_SELECTED_FARE -> "ग्राहक टिप^"
        CUSTOMER_TIP_DESCRIPTION -> "^राइड मिलने की संभावना बढ़ाने के लिए ग्राहक द्वारा जोड़ी गई अतिरिक्त राशि।"
        PLACE_CALL -> "फोन करें"
        DIRECT_CALL -> "प्रत्यक्ष कॉल"
        ANONYMOUS_CALL -> "अनाम कॉल"
        YOUR_NUMBER_WILL_NOT_BE_SHOWN_TO_THE_DRIVER_THE_CALL_WILL_BE_RECORDED_FOR_COMPLIANCE -> "आपका नंबर ड्राइवर पार्टनर को नहीं दिखाया जाएगा। अनुपालन के लिए कॉल रिकॉर्ड की जाएगी।"
        YOUR_NUMBER_WILL_BE_VISIBLE_TO_THE_DRIVER_USE_IF_NOT_CALLING_FROM_REGISTERED_NUMBER -> "आपका नंबर ड्राइवर को दिखाई देगा। अगर रजिस्टर्ड नंबर से कॉल नहीं कर रहे हैं तो इस्तेमाल करें"
        CALL_DRIVER_USING -> "ड्राइवर को कॉल करें"
        WAS_YOUR_CALL_SUCCESSFUL -> "क्या आपका कॉल सक्सेसफुल था"
        DRIVER_ADDITIONS -> "चालक जोड़*"
        FARE_UPDATE_POLICY -> "किराया अपडेट नीति"
        DRIVER_ADDITIONS_OPTIONAL -> "चालक जोड़ (वैकल्पिक)"
        THE_DRIVER_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "चालक यातायात को कवर करने, वापसी यात्रा की संभावना आदि के लिए अतिरिक्त बोली लगा सकता है"
        DRIVER_ADDITIONS_ARE_CALCULATED_AT_RATE _ -> "ड्राइवर द्वारा अतिरिक्त सीमा की गणना बेस फेयर के 10% पर की जाती है, जिसे निकटतम ₹10 में राउंड किया जाता है"
        DRIVER_MAY_NOT_CHARGE_THIS_ADDITIONAL_FARE -> "ध्यान दें: ड्राइवर पार्टनर यह अतिरिक्त किराया चार्ज कर सकते हैं या नहीं भी कर सकते हैं।"
        YOU_MAY_SEE_AN_UPDATED_FINAL_FARE_DUE_TO_ANY_OF_THE_BELOW_REASONS -> "आप नीचे दिए गए किसी भी कारण से अपडेटेड अंतिम किराया देख सकते हैं:"
        REASON_CHANGE_IN_ROUTE_A -> "1.मार्ग में परिवर्तन: "
        REASON_CHANGE_IN_ROUTE_B -> "मार्ग में बदलाव के कारण कुल किराए में बदलाव हो सकता है"
        REQUEST_RECEIVED_WE_WILL_CALL_YOU_BACK_SOON -> "अनुरोध प्राप्त हुआ है। हम जल्द ही आपसे संपर्क करेंगे"
        CONTACT_REMOVED_SUCCESSFULLY -> "संपर्क सफलतापूर्वक निकाला गया"
        CORPORATE_ADDRESS -> "कॉर्पोरेट पता"
        CORPORATE_ADDRESS_DESCRIPTION _ -> "मूविंग टेक इनोवेशन प्राइवेट लिमिटेड <br> गिरिजा बिल्डिंग, नंबर 817, गणपति मंदिर रोड, 8वां ब्लॉक, कोरमंगला, बेंगलुरु, कर्नाटक 560095, भारत।"
        CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL _-> "वेबसाइट: <u>https://nammayatri.in/</u>"
        REGISTERED_ADDRESS -> "पंजीकृत पता"
        REGISTERED_ADDRESS_DESCRIPTION _ -> "मूविंग टेक इनोवेशन प्राइवेट लिमिटेड <br> इंडीक्यूब गार्डन, पुराना नंबर। 648, नया नंबर 130, ग्रेप गार्डन, 18वां मुख्य, पहला ए क्रॉस, 6वां ब्लॉक, कोरमंगला, बैंगलोर 560095।"
        REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL _ -> "वेबसाइट: <u>https://nammayatri.in/</u>"
        RECOMMENDED -> "अनुशंसित"
        COMPLETE_YOUR_PROFILE_FOR_A_PERSONALISED_RIDE_EXPERIENCE -> "वैयक्तिकृत सवारी अनुभव के लिए अपनी प्रोफ़ाइल पूर्ण करें"
        UPDATE_NOW -> "अभी अपडेट करे"
        WE_WOULD_APPRECIATE_YOUR_FEEDBACK -> "खाता हटाने के पीछे आपके तर्क की हम सराहना करेंगे"
        REASON_FOR_DELETING_ACCOUNT -> "खाता हटाने का कारण*"
        SUBMIT_REQUEST -> "अनुरोध सबमिट करें"
        PLEASE_ENTER_A_VALID_EMAIL -> "कृपया एक मान्य ईमेल दर्ज करें"
        WE_WOULD_APPRECIATE_YOUR_REASONING -> "खाता हटाने के पीछे आपके तर्क पर हम आपकी प्रतिक्रिया की सराहना करेंगे"
        OK_GOT_IT -> "ठीक, समझ गया"
        WAIT_FOR_DRIVER -> "ड्राइवर की प्रतीक्षा करें"
        NO_LONGER_REQUIRE_A_RIDE_DUE_TO_CHANGE_IN_PLANS -> "मुझे दूसरी ऐप पर सवारी मिल चुकी है।"
        CANCELLING_AS_I_GOT_A_RIDE_ON_ANOTHER_APP -> "मुझे दूसरी ऐप पर सवारी मिल चुकी है।"
        DRIVER_LOCATION_WASNT_CHANGING_ON_THE_MAP -> "ड्राइवर की लोकेशन मैप पर नहीं बदल रही थी।"
        DRIVER_WAS_TAKING_TOO_LONG_TO_REACH_THE_PICKUP_LOCATION -> "ड्राइवर को पिकअप लोकेशन तक पहुंचने में काफी समय लग रहा था।"
        THE_PICKUP_LOCATION_ENTERED_WAS_WRONG -> "दर्ज किया गया पिकअप स्थान गलत था।"
        YOUR_DRIVER_IS_JUST -> "आपका ड्राइवर बस"
        M_AWAY -> " m दूर है।"
        DRIVER_HAS_ALREADY_TRAVELLED -> "ड्राइवर "
        PLEASE_CONTACT_THE_DRIVER_BEFORE_CANCELLING -> "\nकृपया कैंसिल करने से पहले ड्राइवर से संपर्क करें।"
        CONFIRM_WITH_YOUR_DRIVER -> "अपने ड्राइवर के साथ पुष्टि करे"
        CHANGE_OF_PLANS -> "प्लान में परिवर्तन"
        DRIVER_IS_NOT_MOVING -> "ड्राइवर एक स्थान पर ठहरा हुआ है।"
        WRONG_PICKUP_LOCATION -> "गलत पिकअप स्थान"
        DRIVER_MIGHT_BE_TAKING_ALTERNATE_ROUTE -> "हो सकता है ड्राइवर किसी और रास्ते से आ रहा हो।"
        DRIVER_IS_NOT_MOVING_Q -> "कया आपका ड्राइवर स्थिर है?"
        WOULD_YOU_LIKE_TO_CHECK_WITH_THE_DRIVER_BEFORE_CANCELLING -> "\nक्या आप कैंसिल करने से पहले ड्राइवर से बात करना चाहेंगे?"
        DRIVER_IS_NEAR_YOUR_LOCATION -> "ड्राइवर आपकी लोकशन पर पहुँच चुका है।"
        SOME_OTHER_REASON -> "कोई और कारण।"
        LOCATION_PERMISSION_SUBTITLE_NEW_USER -> "{} में आपका स्वागत है! \nराइड बुक करना शुरू करने के लिए, हमें आपके डिवाइस की लोकेशन की आवश्यकता होती है।"
        METRO_RIDE -> "मेट्रो की सवारी"
        GO_BACK_TEXT -> "पीछे जाएं"
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_JUST -> "ड्राइवर ने आपके विशेष अनुरोध को प्राथमिकता दी और वह केवल "
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST -> "ड्राइवर ने आपके विशेष अनुरोध को प्राथमिकता दी और पहले ही "
        AND_HAS_TRAVELLED -> " की यात्रा कर चुका है।"
        PLEASE_FIND_REVISED_FARE_ESTIMATE -> "कृपया संशोधित अनुमानित किराया ज्ञात करें। रात का शुल्क दिन के शुल्क का 1.5 गुना है।"
        GO_TO_ZONE _-> "पिकअप ज़ोन पर नेविगेट करें"
        FARE_ESTIMATE -> "किराया अनुमान" 
        TIP_SELECTED -> "टिप चयनित"
        ADD_A_TIP_TO_FIND_A_RIDE_QUICKER -> "तेजी से सवारी खोजने के लिए एक टिप जोड़ें!"
        IT_SEEMS_TO_BE_TAKING_LONGER_THAN_USUAL -> "ऐसा लगता है कि इसमें सामान्य से ज़्यादा समय लग रहा है।"
        CONTINUE_SEARCH_WITH -> "के साथ खोज जारी रखें"
        CONTINUING_SEARCH_WITH -> "से तलाश जारी है"
        SEARCHING_WITH -> "से खोज रहे हैं"
        THE_DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION -> "ड्राइवर ने आपके विशेष अनुरोध को प्राथमिकता दी और वह आपके स्थान के रास्ते पर है।"
        DRIVER_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION -> "ड्राइवर आपके स्थान के रास्ते पर है।"
        ALLOW_LOCATION_ACCESS -> "स्थान पहुंच की अनुमति दें"
        MESSAGE_FROM_DRIVER -> "ड्राइवर का संदेश"
        REPLY -> "जवाब"
        NAME_SHOULD_BE_MORE_THAN_2_CHARACTERS -> "नाम 2 अक्षर से अधिक होना चाहिए"
        OKAY_GOT_IT -> "ठीक है समझ आ गया"
        CALL_NAMMA_YATRI_SUPPORT _ -> "नम्मा यात्री सहायता को कॉल करें"
        CALL_112 -> "112 पर कॉल करें"
        CALL_EMERGENCY_CENTRE -> "आपातकालीन केंद्र को कॉल करें"
        SEATS -> "सीटें"
        DRIVER_ADDITION_LIMITS_ARE_IN_INCREMENTS -> "ड्राइवर जोड़ने की सीमा ₹20 की वृद्धि में है"
        HATCHBACK -> "हैचबैक"
        SUV -> "एसयूवी"
        SEDAN -> "सेडान"
        OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN -> "ओटीपी पेज की समय सीमा समाप्त हो गई है, कृपया ओटीपी के लिए फिर से अनुरोध करें"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER -> "OTP डालने की सीमा समाप्त हो गई है, कृपया बाद में पुनः प्रयास करें"
        TOO_MANY_LOGIN_ATTEMPTS_PLEASE_TRY_AGAIN_LATER -> "आपने बहुत से अमान्य प्रयास किए हैं, कृपया बाद में पुनः प्रयास करें"
        SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN -> "कुछ तकनीकी समस्या हुई है, कृपया पुनः प्रयास करें"
        SORRY_LIMIT_EXCEEDED_YOU_CANT_ADD_ANY_MORE_FAVOURITES -> "क्षमा करें, सीमा पार हो गई है। आप कोई और पसंदीदा नंबर नहीं जोड़ सकते हैं"
        CANCELLATION_UNSUCCESSFULL_PLEASE_TRY_AGAIN -> "रद्द करना असफल, कृपया पुन: प्रयास करें"
        NO_DRIVER_AVAILABLE_AT_THE_MOMENT_PLEASE_TRY_AGAIN -> "इस समय कोई ड्राइवर उपलब्ध नहीं है, कृपया पुनः प्रयास करें"
        OTP_FOR_THE_JATRI_SATHI_ZONE_HAS_BEEN_EXPIRED_PLEASE_TRY_LOOKING_AGAIN _ -> "जत्री साथी क्षेत्र के लिए ओटीपी की समय सीमा समाप्त हो चुकी है, कृपया बुकिंग के लिए फिर से प्रयास करें"
        NO_CONTACTS_FOUND_ON_THE_DEVICE_TO_BE_ADDED -> "डिवाइस पर कोई संपर्क नहीं मिला"
        PLEASE_ENABLE_CONTACTS_PERMISSION_TO_PROCEED -> "आगे बढ़ने के लिए कृपया संपर्क अनुमति सक्षम करें"
        LIMIT_REACHED_3_OF_3_EMERGENCY_CONTACTS_ALREADY_ADDED -> "सीमा पार हो गई! 3 में से 3 आपातकालीन संपर्क पहले ही जोड़े जा चुके हैं"
        INVALID_CONTACT_FORMAT -> "अमान्य संपर्क फ़ॉर्मेट"
        OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER -> "OTP पुनः भेजने की सीमा समाप्त हो गई है, कृपया बाद में पुनः प्रयास करें"
        THIS_FIELD_IS_REQUIRED -> "यह फ़ील्ड आवश्यक है"
        EMAIL_EXISTS_ALREADY -> "ईमेल पहले से ही मौजूद है"
        RATE_YOUR_EXPERIENCE -> "अपने अनुभव को रेट करें"
        REPORT_ISSUE_ -> "मुद्दा प्रतिवेदन"
        DONE -> "पूर्ण"
        PLEASE_TELL_US_WHAT_WENT_WRONG -> "कृपया हमें बताएं कि क्या गलत हुआ"
        DID_YOU_FACE_ANY_ISSUE -> "क्या आपको किसी समस्या का सामना करना पड़ा?"
        WE_NOTICED_YOUR_RIDE_ENDED_AWAY -> "हमने देखा है कि आपकी राइड आपके मूल गंतव्य से दूर जाकर समाप्त हुई"
        GET_CALLBACK_FROM_US -> "हमसे कॉलबैक प्राप्त करें"
        DRIVER_WAS_NOT_READY_TO_GO -> "चालक जाने को तैयार नहीं था"
        ASKING_FOR_MORE_MONEY -> "ड्राइवर और पैसे मांग रहा था"
        VEHICLE_BROKEN -> "वाहन खराब हो गया"
        WE_WILL_GIVE_YOU_CALLBACK -> "हम आपको 24 घंटे के भीतर कॉलबैक देंगे"
        YOUR_ISSUE_HAS_BEEN_REPORTED -> "आपकी समस्या की सफलतापूर्वक रिपोर्ट कर दी गई है"
        OTP_RESENT_SUCCESSFULLY -> "OTP सफलतापूर्वक पुनः भेजा गया"
        DESCRIPTION_SHOULD_BE_MORE_THAN_10_ALPHABETIC_CHARACTERS -> "विवरण 10 से अधिक वर्णमाला वर्ण का होना चाहिए"
        IT_SEEMS_LIKE_YOU_HAVE_AN_ONGOING_RIDE_ -> "ऐसा लगता है कि आपकी कोई बुकिंग चल रही है, कृपया इसे देखने के लिए ऐप को पुनरारंभ करें"
        INCORRECT_OTP_PLEASE_TRY_AGAIN -> "गलत OTP, कृपया पुन: प्रयास करें।"
        N_MORE_ATTEMPTS_LEFT -> " और प्रयास शेष हैं"
        GO_TO_SELECTED_PICKUP_SPOT -> "चयनित पिकअप स्थान पर जाएं"
        GO_TO_SELECTED_PICKUP_SPOT_AS_AUTOS_ARE_RESTRICTED -> "सुझाए गए पिकअप स्थान पर जाएं क्योंकि इस क्षेत्र के अंदर ऑटो प्रतिबंधित हैं"
        UNPROFESSIONAL_DRIVER -> "अव्यवसायिक चालक"
        RASH_DRIVING -> "लापरवाही से गाड़ी चलाई"
        DRIVER_CHARGED_MORE -> "ड्राइवर ने अधिक चार्ज किया"
        UNCOMFORTABLE_AUTO -> "असुविधाजनक ऑटो"
        UNCOMFORTABLE_CAB -> "असुविधाजनक कैब"
        TRIP_GOT_DELAYED -> "यात्रा में देरी हुई"
        FELT_UNSAFE -> "असुरक्षित महसूस हुआ"
        POLITE_DRIVER -> "शिष्ट चालक"
        EXPERT_DRIVING -> "विशेषज्ञ ड्राइविंग"
        SAFE_RIDE -> "सुरक्षित सवारी"
        CLEAN_AUTO -> "स्वच्छ ऑटो"
        CLEAN_CAB -> "स्वच्छ कैब"
        ON_TIME -> "समय पर"
        SKILLED_NAVIGATOR -> "प्रवीण नेविगेटर"
        RUDE_DRIVER -> "असभ्य ड्राइवर"
        TOO_MANY_CALLS -> "बहुत सारे कॉल्स"
        RECKLESS_DRIVING -> "लापरवाह ड्राइविंग"
        LATE_DROP_OFF -> "देरी से ड्रॉप ऑफ"
        LATE_PICK_UP -> "देरी से पिक अप"
        POOR_EXPERIENCE -> "खराब अनुभव 😕"
        TERRIBLE_EXPERIENCE -> "भयानक अनुभव 😠"
        NEEDS_IMPROVEMENT -> "सुधार की आवश्यकता है 😕"
        ALMOST_PERFECT -> "लगभग पूर्ण! 🙂"
        AMAZING -> "अद्भुत!!! 🤩"
        ASKED_FOR_EXTRA_FARE -> "अतिरिक्त किराया मांगा"
        ANYTHING_THAT_YOU_WOULD_LIKE_TO_TELL_US -> "कुछ भी जो आप हमें बताना चाहेंगे? (वैकल्पिक)"
        PLEASE_WAIT -> "कृपया प्रतीक्षा करें"
        PLATFORM_FEE -> "प्लेटफार्म शुल्क"
        SGST -> "एसजीएसटी"
        OTP_EXPIRED -> "ओटीपी समाप्त हो गया"
        OTP_EXPIRED_DESCRIPTION -> "आपकी सवारी ओटीपी समाप्त हो गई है। सवारी पाने के लिए कृपया दोबारा बुकिंग करें"
        PLATFORM_GST -> "कर (जीएसटी)"
        MISC_WAITING_CHARGE -> "विविध (प्रतीक्षा शुल्क सहित)"
        AC_TAXI -> "एसी टैक्सी"
        NON_AC_TAXI -> "नॉन-एसी टैक्सी"
        GET_OTP_VIA_WHATSAPP -> "व्हाट्सएप के माध्यम से ओटीपी प्राप्त करें"
        OR -> "या"
        HELPS_DRIVER_CONFIRM_ITS_YOU -> "(ड्राइवर को यह पुष्टि करने में मदद करता है कि यह आप ही हैं)"
        LETS_GET_YOU_TRIP_READY -> "आइए हम आपको यात्रा के लिए तैयार करें!"
        GOT_AN_OTP -> "एक OTP मिला?"
        JUST_ONE_LAST_THING -> "बस एक आखिरी चीज़"
        TOLL_CHARGES_WILL_BE_EXTRA -> "टोल शुल्क शामिल हैं"
        AUTO_RICKSHAW -> "ऑटो रिक्शा"
        CABS_AVAILABLE -> "कैब उपलब्ध हैं"
        GENERAL_DISABILITY_DESCRIPTION -> "ड्राइवर्स को आपकी आवश्यकताओं और अनुरोधों के साथ मदद करने के लिए संवेदनशील बनाया जाएगा।"
        PI_POINTER_1 -> "ड्राइवर्स को आपके सटीक स्थान पर पिकअप के लिए प्रॉम्प्ट किया जाएगा।"
        PI_POINTER_2 -> "ड्राइवर्स को आपके संचालन सहायक साधना के साथ मदद करने के लिए प्रॉम्प्ट किया जाएगा।"
        VI_POINTER_1 -> "ड्राइवर्स को मैसेज करने के बजाय कॉल करने के लिए प्रॉम्प्ट किया जाएगा। "
        VI_POINTER_2 -> "पिकअप के समय एक बार हॉर्न बजाने के लिए ड्राइवर्स को प्रॉम्प्ट किया जाएगा।"
        HI_POINTER_1 -> "ड्राइवर्स को कॉल करने के बजाय मैसेज करने के लिए प्रॉम्प्ट किया जाएगा।"
        HI_POINTER_2 -> "पिकअप के समय एक बार आपको मैसेज करने के लिए ड्राइवर्स को प्रॉम्प्ट किया जाएगा।"
        DID_THE_DRIVER_OFFER_ASSISTANCE -> "क्या ड्राइवर ने सहायता की पेशकश की?"
        WAS_THE_DRIVER_UNDERSTANDING_OF_YOUR_NEEDS -> "क्या आपका ड्राइवर आपकी ज़रूरतों को समझ रहा था और यात्रा के दौरान उनकी मदद कर रहा था?"
        ACCESSIBILITY_TEXT _-> "नम्मा यात्री, अब आपके लिए अनुकूलित!"
        TO_CATER_YOUR_SPECIFIC_NEEDS _ -> "आपकी विशिष्ट आवश्यकताओं को पूरा करने के लिए, हमने नम्मा यात्री की कुछ विशेषताओं को अनुकूलित किया है।"
        SPECIAL_ASSISTANCE -> "विशेष सहायता"
        SELECT_THE_CONDITION_THAT_IS_APPLICABLE -> "वह शर्त चुनें जो आप पर लागू हो\n(आरपीडब्ल्यूडी अधिनियम 2016 के अनुसार)"
        DISABILITY_CLAIMER_TEXT -> "जारी रखकर, आप आरपीडब्ल्यूडी अधिनियम 2016 के तहत विकलांग व्यक्ति के रूप में अपनी स्थिति घोषित कर रहे हैं"
        ARE_YOU_A_PERSON_WITH_DISABILITY -> "क्या आप विकलांग व्यक्ति हैं?"
        DO_YOU_NEEED_SPECIAL_ASSISTANCE -> "क्या आपको विशेष सहायता (विकलांग व्यक्ति) की आवश्यकता है?"
        ASSISTANCE_REQUIRED -> "आवश्यक सहायता (विकलांग व्यक्ति)"
        NO_DISABILITY -> "कोई विकलांगता नहीं"
        LEARN_HOW_TEXT _ -> "जानें कि नम्मा यात्री आपकी आवश्यकताओं को कैसे पूरा करता है"
        UPDATE_PROFILE -> "प्रोफ़ाइल अपडेट करें"
        NOW_GET_ASSISTED_RIDES -> "यदि आप विकलांग व्यक्ति हैं तो अब सहायता प्राप्त सवारी प्राप्त करें"
        ENABLE_LOCATION_PERMISSION_TO -> "सवारी खोजने के लिए स्थान अनुमति सक्षम करें"
        AC_CAB -> "एसी कैब"
        AC_SUV -> "एसी एसयूवी"
        RIDE_TYPE -> "सवारी का प्रकार"
        SENT_OTP_VIA_WHATSAPP -> "व्हाट्सएप के माध्यम से ओटीपी भेजा गया है"
        SENT_OTP_VIA_SMS -> "ओटीपी एसएमएस के माध्यम से भेजा गया है"
        ERNAKULAM_LIMIT_CHARGE -> "यदि पिकअप या गंतव्य एर्नाकुलम निगम सीमा के बाहर है तो किराया 1.5 गुना होगा"
        SELECT_LOCATION_ON_MAP -> "मानचित्र पर स्थान चुनें"
        DOWNLOAD_DRIVER_RECEIPT -> "ड्राइवर रसीद डाउनलोड करें"
        VIEW_DRIVER_RECEIPT -> "ड्राइवर रसीद देखें"
        DRIVER_RECEIPT -> "ड्राइवर रसीद"
        HELP -> "सहायता"
        FARE_INFO_TEXT _ -> ""
        FASTER -> "और तेज"
        PLEASE_ENABLE_LOCATION_PERMISSION _ -> "सवारी की तलाश शुरू करने के लिए कृपया सेटिंग ऐप से स्थान अनुमतियां सक्षम करें।"
        EDUCATIONAL_POP_UP_SLIDE_1_TITLE -> "हम अपने सभी उपयोगकर्ताओं को एक समान \n और समान अनुभव प्रदान करने का प्रयास \n करते हैं"
        EDUCATIONAL_POP_UP_SLIDE_2_TITLE -> "ख़राब दृष्टि वाले उपयोगकर्ताओं के लिए"
        EDUCATIONAL_POP_UP_SLIDE_3_TITLE -> "कम सुनने वाले उपयोगकर्ताओं के लिए"
        EDUCATIONAL_POP_UP_SLIDE_4_TITLE -> "लोकोमोटर विकलांगता वाले उपयोगकर्ताओं के लिए"
        EDUCATIONAL_POP_UP_SLIDE_5_TITLE -> "अन्य विशेष आवश्यकताओं वाले उपयोगकर्ताओं के लिए"
        EDUCATIONAL_POP_UP_SLIDE_1_SUBTITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_2_SUBTITLE -> "&#8226; ड्राइवरों को टेक्स्टिंग के बजाय कॉल करने <br> &ensp;  के लिए प्रेरित किया जाएगा। <br> &#8226; ड्राइवरों को पिकअप पर एक बार हॉर्न <br> &ensp; बजाने के लिए प्रेरित किया जाएगा।  <br> &#8226; ड्राइवरों को उनकी ज़रूरतों और अनुरोधों में मदद  <br> &ensp; करने के लिए संवेदनशील बनाया जाएगा।"
        EDUCATIONAL_POP_UP_SLIDE_3_SUBTITLE -> "&#8226; ड्राइवरों को कॉल करने के बजाय संदेश भेजने <br> &ensp;  के लिए प्रेरित किया जाएगा। <br> &#8226; पिकअप के समय ड्राइवरों को एक बार संदेश <br> &ensp;  भेजने के लिए प्रेरित किया जाएगा। <br> &#8226; ड्राइवरों को उनकी ज़रूरतों और अनुरोधों में मदद <br> &ensp; करने के लिए संवेदनशील बनाया जाएगा।"
        EDUCATIONAL_POP_UP_SLIDE_4_SUBTITLE -> "&#8226; ड्राइवरों को पिकअप के लिए उनके सटीक स्थान पर आने <br> &ensp; के लिए प्रेरित किया जाएगा। <br> &#8226; ड्राइवरों को उनकी गतिशीलता सहायता में <br> &ensp; मदद करने के लिए प्रेरित किया जाएगा। <br>&#8226; ड्राइवरों को उनकी ज़रूरतों और अनुरोधों में मदद <br> &ensp; करने के लिए संवेदनशील बनाया जाएगा।"
        EDUCATIONAL_POP_UP_SLIDE_5_SUBTITLE -> "&#8226; हम अन्य प्रकार की विकलांगताओं को <br> &ensp; एकत्रित करेंगे और आवश्यकतानुसार उन्हें उपलब्ध <br> &ensp; विकलांगताओं की सूची में शामिल करेंगे।"
        INCLUSIVE_AND_ACCESSIBLE -> "सभी के लिए समावेशी और सुलभ!"
        SOMETHING_WENT_WRONG_TRY_AGAIN_LATER -> "कुछ तकनीकी समस्या हुई है, कृपया बाद में दोबारा प्रयास करें"
        YOU_SEEM_TO_BE_FAR_FROM_PICK_UP -> "ऐसा लगता है कि आप पिकअप स्थान से बहुत दूर हैं!"
        ARE_YOU_SURE_YOU_WANT_TO_PROCEED_WITH_THE_BOOKING -> "क्या आप वाकई बुकिंग जारी रखना चाहते हैं?"
        MY_TICKETS -> "मेरी टिकटें"
        YOU_CAN_BOOK_TICKETS_TO_THE_ZOO_BY_CLICKING_THE_BUTTON -> "बटन पर क्लिक करके आप चिड़ीयाघर के लिए टिकटें बुक कर सकते हैं।"
        YOUR_FEEDBACK_HELPS_US appName -> "आपकी प्रतिक्रिया हमें " <> appName <> " अनुभव को सुधारने में मदद करती है"
        FINDING_QUOTES_TEXT -> "कैब्स खोज रहा है"
        NEW_ -> "नया"
        PAY_DRIVER_USING_WALLET -> ""
        CHARGES_APPLICABLE_AFTER_3_MINS -> "3 मिनट के बाद शुल्क लागू"
        REACHING_YOUR_DESTINATION_IN_ -> "में अपने गंतव्य पर पहुंच रहा हूं "
        WAITING_AT_PICKUP -> "पिकअप की प्रतीक्षा में"
        PICKUP -> "पिकअप"
        PAY_BY_CASH_OR_UPI -> "भुगतान नकद / UPI द्वारा करें "
        YOU_WILL_PAY_FOR_EVERY_MINUTE freeMinutes chargePerMin -> "पहले "<> freeMinutes <>" मिनट के लिए वेटिंग चार्ज शून्य है।. इसके बाद "<> chargePerMin <> " का प्रतीक्षा शुल्क लागू होगा।"
        WAIT_TIMER -> "प्रतीक्षा टाइमर"
        HOW_LONG_DRIVER_WAITED_FOR_PICKUP -> "आपको दिखाता है कि ड्राइवर ने पिकअप के लिए कितनी देर तक इंतजार किया है।"
        CHAT_WITH -> "से बातचीत"
        QUICK -> "जल्दी"
        CHATS -> "चैट"
        REPLIES -> "जवाब"
        YOU_SENT -> "तुम्हें भेजा"
        MESSAGE_YOUR_DRIVER -> "अपने ड्राइवर को संदेश भेजें?"
        CHECK_IN_WITH_YOUR_DRIVER -> "त्वरित चैट के साथ अपने ड्राइवर के बारे में पता करें"
        CHECK_IN_WITH_YOUR_EM name -> "त्वरित चैट के साथत्वरित चैट के साथ " <> name <> " पर चेक इन क"
        TRACK_ON_GOOGLE_MAPS -> "वास्तविक समय ट्रैकिंग"
        OTP_EXPIRE_TIMER -> "ओटीपी समाप्ति टाइमर"
        SHOWS_FOR_HOW_LONG_YOUR_OTP_ -> "दिखाता है कि यात्रा शुरू करने के लिए आपका ओटीपी कितने समय तक वैध रहेगा।"
        IF_YOUR_OTP_EXPIRES_ -> "यदि आपका ओटीपी समाप्त हो जाता है, तो आपको फिर से बुकिंग करनी होगी।"
        YOU_HAVE_REACHED_DESTINATION -> "आप अपने गंतव्य पर पहुंच गए हैं"
        PLACES_YOU_MIGHT_LIKE_TO_GO_TO -> "वे स्थान जहाँ आप जाना पसंद कर सकते हैं।"
        SUGGESTED_DESTINATION -> "सुझाए गए गंतव्य"
        RECENT_RIDES -> "हाल की सवारी"
        ONE_CLICK_BOOKING_FOR_YOUR_FAVOURITE_JOURNEYS -> "आपकी पसंदीदा यात्राओं के लिए एक क्लिक बुकिंग!"
        VIEW_MORE -> "और देखें"
        VIEW_LESS -> "कम देखें"
        HAVE_A_REFFERAL -> "क्या आपके पास रेफरल है?"
        YOUR_SUGGESTED_DESTINATIONS_AND_RECENT_RIDES_WILL_APPEAR_HERE -> "आपके सुझाए गए गंतव्य और हाल की सवारियां यहां दिखाई देंगी"
        WELCOME_TO_NAMMA_YATRI_ -> "नम्मा यात्री में आपका स्वागत है!"
        BOOK_AND_MOVE -> "बुक करें और चलें"
        ANYWHERE_IN_THE_CITY -> "शहर में कहीं भी"
        CHECKOUT_OUR_LIVE_STATS -> "हमारे लाइव आँकड़े देखें"
        MOST_LOVED_APP _ -> "सबसे ❤️ जीरो कमीशन ऐप"
        PICKUP_ -> "पिक अप-> "
        PAST_SEARCHES -> "पिछली खोजें"
        SEARCH_RESULTS -> "खोज परिणाम"
        EDIT_DESTINATION -> "गंतव्य संपादित करें"
        REQUESTING_RIDE_IN -> "सवारी का अनुरोध"
        CONFIRM_FARE -> "नए किराए की पुष्टि करें"
        REQUEST_CHANGE -> "परिवर्तन का अनुरोध करें"
        REQUESTING_RIDE -> "सवारी का अनुरोध"
        TAP_HERE_TO_STOP_AUTO_REQUESTING -> "ऑटो अनुरोध करना बंद करने के लिए यहां टैप करें"
        POWERED_BY -> "द्वारा संचालित"
        BOOK_YOUR_RIDE -> "अपनी सवारी बुक करें"
        FARE_UPDATED_WITH_CHARGES -> "लागू प्रतीक्षा शुल्क शामिल करने के लिए किराया अद्यतन किया गया है"
        FARE_UPDATED_WITH_SHORTER_DIST -> "आपका किराया अपडेट कर दिया गया है क्योंकि आपकी सवारी {} किमी छोटी थी"
        FARE_UPDATED_WITH_LONGER_DIST -> "आपका किराया अपडेट कर दिया गया है क्योंकि आपकी सवारी {} किमी लंबी थी"
        FARE_UPDATED_WITH_CHARGES_SHORTER_DIST -> "आपका किराया अपडेट कर दिया गया है क्योंकि आपकी सवारी {} किमी छोटी थी और प्रतीक्षा समय का शुल्क लगा था"
        FARE_UPDATED_WITH_CHARGES_LONGER_DIST -> "आपका किराया अपडेट कर दिया गया है क्योंकि आपकी सवारी {} किमी लंबी थी और प्रतीक्षा समय का शुल्क लगा था"
        START_TYPING_TO_SEARCH_PLACES -> "स्थान खोजने के लिए टाइप करना प्रारंभ करें"
        DID_YOU_HAVE_A_SAFE_JOURNEY -> "क्या आपकी यात्रा सुरक्षित रही?"
        TRIP_WAS_SAFE_AND_WORRY_FREE -> "हम यह सुनिश्चित करना चाहेंगे कि आपकी यात्रा सुरक्षित और चिंता मुक्त हो।"
        DRIVER_BEHAVED_INAPPROPRIATELY -> "ड्राइवर ने अनुचित व्यवहार किया"
        I_DID_NOT_FEEL_SAFE -> "मैं सुरक्षित महसूस नहीं कर रहा था"
        LOOKING_FOR_ANOTHER_RIDE -> "एक और सफर ढूंढ़ रहे हैं..."
        THE_RIDE_HAD_BEEN_CANCELLED_WE_ARE_FINDING_YOU_ANOTHER -> "यात्रा को रद्द कर दिया गया था, हम आपके लिए एक और ढूंढ़ रहे हैं"
        ENJOY_THE_RIDE -> "अपने गंतव्य तक यात्रा का आनंद लें!"
        RIDE_STARTED -> "सवारी शुरू हुई"
        DISCOVER_AWESOME_SPOTS_TAILORED_JUST_FOR_YOU -> "आपके लिए विशेष रूप से तैयार किए गए शानदार स्पॉट खोजें"
        ONE_CLICK -> "1 क्लिक बुकिंग"
        SMART -> "स्मार्ट"
        NOT_SERVICEABLE -> "सेवा योग्य नहीं"
        WE_ARE_NOT_LIVE_IN_YOUR_AREA -> "हम अभी तक आपके क्षेत्र में नहीं रहते हैं! \nआप ऊपर बाईं ओर मेनू से सवारी इतिहास और अन्य \nसेटिंग्स तक पहुंच सकते हैं।"
        FACING_PROBLEM_WITH_APP -> "ऐप के साथ समस्याओं का सामना करना पड़ रहा है?"
        TAP_HERE_TO_REPORT -> "<u>समस्या की रिपोर्ट करने के लिए यहां टैप करें</u>"
        CONFIRM_YOUR_RIDE  -> "अपनी सवारी की पुष्टि करें"
        RIDE_SCHEDULED -> "सवारी निर्धारित"
        RIDE_STARTS_ON -> "सवारी शुरू होती है"
        RENTAL_PACKAGE -> "किराये का पैकेज"
        GO_HOME -> "घर जाओ"
        CANCEL_RENTAL_BOOKING -> "रेंटल बुकिंग रद्द करें"
        ADD_FIRST_STOP -> "पहला पड़ाव जोड़ें"
        DRIVER_WILL_BE_ASSIGNED_MINUTES_BEFORE_STARTING_THE_RIDE -> "{} मिनट पहले ड्राइवर नियुक्त किया जाएगा"
        YOUR_REPORTS -> "आपकी रिपोर्ट"
        VIEW -> "देखना"
        ISSUE_NO -> "निर्गत संख्या।"
        ADD_VOICE_NOTE -> "वॉइस नोट जोड़ें"
        VOICE_NOTE -> "आवाज को ध्यान देना"
        SUBMIT_ISSUE_DETAILS -> "मुद्दे का विवरण जमा करें"
        IMAGE_PREVIEW -> "छवि पूर्वावलोकन"
        ADDED_IMAGES -> "छवियाँ जोड़ी गईं"
        NO_IMAGES_ADDED -> "कोई छवियाँ नहीं जोड़ी गईं"
        I_DONT_KNOW_WHICH_RIDE -> "मुझे नहीं पता कि कौन सी सवारी है"
        ADDED_VOICE_NOTE -> "वॉइस नोट जोड़ा गया"
        NO_VOICE_NOTE_ADDED -> "कोई वॉइस नोट नहीं जोड़ा गया"
        CALL_DRIVER_TITLE -> "ड्राइवर को बुलाओ?"
        CALL_SUPPORT_TITLE -> "समर्थन को कॉल करें?"
        CALL_DRIVER_DESCRIPTION -> "आप ड्राइवर को कॉल करने वाले हैं। क्या आपकी आगे बढ़ने की इच्छा है?"
        ADD_IMAGE -> "चित्र डालें"
        ADD_ANOTHER -> "एक और जोड़ें"
        IMAGES -> "इमेजिस"
        ISSUE_SUBMITTED_TEXT -> "पकड़ना! हम आपकी समस्या का समाधान करने पर काम कर रहे हैं"
        ISSUE_RESOLVED_TEXT -> "मसला हल हो गया!"
        CHOOSE_AN_OPTION -> "जारी रखने के लिए कोई विकल्प चुनें"
        ISSUE_MARKED_AS_RESOLVED -> "समस्या हल हो गई के रूप में चिह्नित!"
        STILL_HAVING_ISSUE -> "अभी भी कोई समस्या है?"
        IMAGE -> "छवि"
        RECORD_VOICE_NOTE -> "वॉयस नोट रिकॉर्ड करें"
        CANCEL_BUTTON -> "रद्द करना"
        MAX_IMAGES -> "अधिकतम 3 छवियाँ अपलोड की जा सकती हैं"
        SELECT_A_RIDE_TO_REPORT -> "समस्या की रिपोर्ट करने के लिए सवारी का चयन करें"
        RIDE_RELATED_ISSUE_PAGE_NAME -> "सवारी संबंधी मुद्दा"
        APP_RELATED_ISSUE_PAGE_NAME -> "ऐप संबंधित समस्या"
        DRIVER_RELATED_ISSUE_PAGE_NAME -> "ड्राइवर संबंधी समस्या"
        LOST_AND_FOUND_ISSUE_PAGE_NAME -> "खोई हुई वस्तु की रिपोर्ट करें"
        YEARS_AGO -> "साल पहले"
        MONTHS_AGO -> "महीने पहले"
        DAYS_AGO -> "दिन पहले"
        HOURS_AGO -> "घंटे पहले"
        MIN_AGO -> "मिनट पहले"
        SEC_AGO -> "सेकंड पहले"
        REPORTED -> "रिपोर्ट की गई"
        RESOLVED -> "हल किया"
        RESOLVED_ISSUES -> "सुलझे हुए मुद्दे"
        REPORTED_ISSUES -> "रिपोर्ट किए गए मुद्दे"
        OTHER_ISSUES -> "अन्य समस्या"
        SOS_ISSUE_PAGE_NAME -> "समस्या SOS"
        FARE_DISCREPANCIES_ISSUE_PAGE_NAME -> "सहमति की भंग समस्या"
        PAYMENT_RELATED_ISSUE_PAGE_NAME -> "भुगतान संबंधित समस्या"
        ACCOUNT_RELATED_ISSUE_PAGE_NAME -> "खाता संबंधित समस्या"
        REPORT_ISSUE_CHAT_PLACEHOLDER _ -> "अपनी समस्या का वर्णन करें।"
        CALL_SUPPORT_DESCRIPTION _ -> "आप सहायता टीम को कॉल करने वाले हैं। क्या आप आगे बढ़ना चाहते हैं?"
        CANT_FIND_OPTION -> "विकल्प नहीं मिल सका"
        NEED_HELP ->  "मदद की ज़रूरत है?" 
        SAFETY_ISSUE_PAGE_NAME -> "सुरक्षित सवारी संबंधी समस्या"
        WE_HOPE_THE_ISSUE_IS_RESOLVED _ -> "हम आशा करते हैं कि समस्या हल हो गई है।"
        PLEASE_SELECT_THE_RIDE_TO_CALL_DRIVER -> "ड्राइवर को कॉल करने के लिए सवारी का चयन करें"
        ADD_IMAGE_S -> "छवि जोड़ें" 
        ALREADY_HAVE_AN_ACTIVE_RIDE -> "पहले से ही एक सक्रिय सवारी है"
        CONFIRM_STOP_LOCATION -> "क्या आप वाकई यहां रुकना चाहते हैं?"
        CONFIRM_DROP -> "गिरावट की पुष्टि करें"
        BOOK_METRO_WITH_NY_NOW -> "नम्मा यात्री के साथ अभी \nमेट्रो टिकट बुक करें!"
        FOLLOWING name -> name <> " का अनुसरण कर रहा हूँ"
        TURN_OFF_ALARM -> "अलार्म बंद करें"
        CHOOSE_A_PERSON_TO_FOLLOW -> "अनुसरण करने के लिए एक व्यक्ति चुनें"
        IS_IN_SOS_SITUATION name -> name <> " एसओएस स्थिति में है!"
        MARKED_RIDE_SAFE name -> name <> " सवारी को सुरक्षित चिह्नित किया गया!"
        STAY_CALM_KEEP_TRACKING name -> "शांत रहें। " <> name <> " के स्थान को ट्रैक करते रहें, यदि आवश्यक हो तो आवश्यक कार्रवाई करें"
        YOU_WILL_BE_NOTIFIED -> "सवारी पूरी होने पर आपको सूचित किया जाएगा"
        TAP_HERE_TO_FOLLOW name ->  name <> " को फ़ॉलो करने के लिए यहां टैप करें"
        HAVE_SHARED_RIDE_WITH_YOU name -> name <> " ने आपके साथ अपनी यात्राएँ साझा की हैं"
        SOS_LOCATION -> "एसओएस स्थान"
        THIS_IS_A_TEST_MOCK_DRILL name -> "यह " <> name <> " के लिए एक परीक्षण ड्रिल है"
        THIS_IS_NOT_REAL_DRILL -> "यह कोई वास्तविक ड्रिल नहीं है, यह बस यह दर्शाता है कि ऐप आपातकालीन स्थितियों में कैसे प्रतिक्रिया देगा।"
        REACHED_DESTINATION_SAFELY name -> name <> " सुरक्षित पहुंच गया मंजिल पर!"
        LEARN_MORE -> "और जानें"
        LEARN_ABOUT_NAMMA_SAFETY -> "सुरक्षा मोड के बारे में जानें"
        NAMMA_SAFETY_WILL_ENABLE_ACCESS -> "सुरक्षा मोड सवारी के दौरान निम्नलिखित सुविधाओं का उपयोग करने की सुविधा प्रदान करेगा!"
        EDIT_ACTIONS -> "कार्रवाई संपादित करें"
        EMERGENCY_ACTIONS -> "आपातकालीन कार्रवाई"
        WHEN_YOU_START_EMERGENCY_SOS -> "सुरक्षा मोड को सक्रिय करने पर, आपका ऐप निम्नलिखित कार्रवाई करेगा"
        EMERGENCY_SHARING_WITH_CONTACTS -> "आपातकालीन साझा करना और एसओएस के दौरान संपर्कों के साथ ऑटो कॉलिंग।"
        SHARING_WITH -> "साझा कर रहे हैं:"
        ADD_A_CONTACT -> "संपर्क जोड़ें"
        TO_ENSURE_SAFETY_USERS_SHOULD -> "सुनिश्चित करने के लिए, उपयोगकर्ताओं को यह करना चाहिए:"
        ABOUT_SOS_DESC -> "कृपया सुरक्षा मोड की महत्वाकांक्षा समझें। गैर-महत्वपूर्ण परिस्थितियों के लिए, कृपया एक शिकायत दर्ज करने के लिए <b>मदद और समर्थन</b> अनुभाग का उपयोग करें।"
        FEW_EXAMPLES_OF_SOS_SITUATIONS -> "आपातकालीन परिस्थितियों के कुछ उदाहरण"
        THINGS_TO_DO_DURING_SOS_SITUATION -> "आपातकालीन परिस्थिति के दौरान करने वाली चीजें"
        EMERGENCY_REQUEST_SENT -> "आपातकालीन अनुरोध भेजा गया!"
        SOS_TRIGGERED_DESC -> "कृपया शांत रहें, आपकी वास्तविक समय स्थान आपके आपातकालीन संपर्कों के साथ साझा की जा रही है।"
        SOS_ACTIONS -> "आपातकालीन कार्रवाई"
        CALL_POLICE -> "पुलिस को कॉल करें"
        CALL_SUPPORT -> "हमारे समर्थन को कॉल करें"
        RECORD_VIDEO -> "वीडियो रिकॉर्ड करें\n"
        STOP_AND_SHARE_RECORDING -> "रिकॉर्डिंग बंद करें और साझा करें"
        CANCEL_SHARING -> "साझा करना रद्द करें"
        START_RECORDING -> "रिकॉर्डिंग शुरू करें"
        SHARING_THE_VIDEO_IN -> "वीडियो साझा कर रहा है...."
        EMERGENCY_INFO_SHARED -> "आपातकालीन जानकारी साझा की गई!"
        EMERGENCY_INFO_SHARED_ACTION -> "आपके आपातकालीन संपर्कों और हमारी समर्थन टीम के पास आपका स्थान और वीडियो है।\nमहत्वपूर्ण स्थितियों पर पुलिस को सूचित किया जाएगा और उचित कार्रवाई की जाएगी।"
        SET_UP_YOUR_PERSONAL_SAFETY_SETTINGS -> "अपनी व्यक्तिगत सुरक्षा सेटिंग्स सेट करें"
        ACTIVATE_LIVE_VIDEO_RECORDING_FEATURES -> "लाइव वीडियो रिकॉर्डिंग सुविधाएं सक्रिय करें"
        CHOOSE_RESPONSIVE_CONTACTS -> "हम आपको अपनी सवारी के लिए सक्रिय संपर्क चयन करने की सिफारिश करते हैं, जैसे स्थानीय संरक्षक या एक शहर का दोस्त।"
        SHARE_LOCATION_AND_RIDE_DETAILS_EMERGENCY_CONTACT -> "अपने आपातकालीन संपर्कों के साथ स्थान और सवारी विवरण साझा करें"
        NAMMA_SAFETY_MEASURES -> "सुरक्षा मोड के उपाय"
        SAFETY_GUIDELINES_FOR_YOU -> "आपके लिए सुरक्षा दिशानिर्देश"
        ABOUT_SOS -> "सुरक्षा मोड के बारे में"
        NIGHT_TIME_SAFETY_CHECKS -> "रात के समय सुरक्षा जांच"
        SHARE_INFO_WITH_EMERGENCY_CONTACTS_TITLE -> "एसओएस क्लिक पर, सूचना साझा करें और आपात संपर्कों के साथ स्वचालित कॉल प्रारंभ करें?"
        SHARE_INFO_WITH_EMERGENCY_CONTACTS_DESC -> "अपनी सवारी के लिए सक्रिय संपर्क चुनें, जैसे स्थानीय संरक्षक या शहर का दोस्त।"
        TRIGGER_ALERT_TO_NAMMAYATRI_SUPPORT_TITLE _ -> "नम्म यात्री समर्थन को सतर्क करें"
        TRIGGER_ALERT_TO_NAMMAYATRI_SUPPORT_DESC -> "हमारे पास 24*7 विशेष समर्थन है जो स्वचालित रूप से चेतावनी दी जाएगी"
        ENABLE_NIGHT_TIME_SAFETY_ALERTS_TITLE -> "रात के समय सुरक्षा चेतावनियों को सक्षम करें?"
        ENABLE_NIGHT_TIME_SAFETY_ALERTS_DESC -> "आपकी सुरक्षा सुनिश्चित करने के लिए, <b><span style='color:#454545'>9 PM-6 AM</span></b> के बीच, हम ड्राइवर के मार्ग की अनौपचारिकता की आधारित सुरक्षा जाँच अलर्ट भेजेंगे। मार्ग-विचलन या जब वाहन नहीं चल रहा है के मामलों में। <br><br>यह होगा चाहे सेफ्टी मोड सक्रिय हो या न हो।"
        ALMOST_DONE_TITLE -> "लगभग हो गया है!"
        ALMOST_DONE_DESC -> "आपातकाल में, आप पुलिस हेल्पलाइन से संपर्क कर सकते हैं या सुरक्षा समस्या की रिपोर्ट कर सकते हैं। इसे करने के लिए, कृपया आवश्यक अनुमतियाँ प्रदान करें।"
        PERSONAL_SAFETY_SETTINGS_PERMISSION_REQUEST -> "(कृपया रिकॉर्ड करने के लिए संबंधित अनुमतियाँ दें)"
        SAFETY_MEASURE_1 -> "ड्राइवर मार्ग विचारण अनैमली डिटेक्शन पर नाइट-टाइम सुरक्षा जांच"
        SAFETY_MEASURE_2 -> "सुरक्षा मोड बटन।"
        SAFETY_MEASURE_3 -> "ड्राइवर / ग्राहकों के लिए शून्य सहिष्णुता नीति"
        SAFETY_MEASURE_4 -> "ग्राहक गोपनीयता - ड्राइवर संपन्न होने के बाद यात्रा का सटीक पता नहीं देख सकते"
        SAFETY_MEASURE_5 _ -> "सभी नम्म यात्री ड्राइवरों के लिए सुरक्षा प्रशिक्षण और प्रमाणीकरण"
        SAFETY_MEASURE_6 -> "आपातकाल के समय एक लाइव वीडियो रिकॉर्डिंग साझा करें।"
        SAFETY_GUIDELINES_1 -> "ड्राइवर की पहचान की जांच वाहन संख्या के साथ"
        SAFETY_GUIDELINES_2 -> "मार्ग पर नजर रखें"
        SAFETY_GUIDELINES_3 -> "खासकर रात की सवारी के दौरान सतर्क रहें"
        SAFETY_GUIDELINES_4 -> "अगर आपको असहज लग रहा है, तो आप आपातकालीन संपर्कों के साथ अपनी सवारी साझा करें"
        SAFETY_GUIDELINES_5 -> "व्यक्तिगत जानकारी साझा करने से बचें"
        SAFETY_GUIDELINES_6 -> "इन-ऐप आपातकालीन सुरक्षा सुविधा का उपयोग करें"
        SAFETY_GUIDELINES_7 -> "एक विश्वसनीय और सुरक्षित समुदाय बनाए रखने में मदद करने के लिए मूल्यांकन और समीक्षा करें"
        ABOUT_SOS_1 -> "ड्राइवर विभिन्न दूरस्थ स्थानों पर पुनर्निर्देशन"
        ABOUT_SOS_2 -> "ड्राइवर से अनुचित मौखिक / शारीरिक संकेत"
        ABOUT_SOS_3 -> "आपकी सहमति के बिना अन्य पुरुष सवारी में शामिल होने के लिए कहे गए"
        ABOUT_SOS_4 -> "ड्राइवर ने अनैतिक तरीके से एक दूरस्थ क्षेत्र पर रुक गया"
        ABOUT_SOS_5 -> "किराया मुद्दे"
        ABOUT_SOS_6 -> "नशे में चलाना"
        ABOUT_SOS_7 -> "असावधान चाल"
        ABOUT_SOS_8 -> "वाहन संख्या मेल नहीं खाती"
        ABOUT_SOS_9 -> "सुरक्षा मोड को सक्षम करने के लिए राइड के दौरान सुरक्षा मोड बटन पर टैप करें"
        ABOUT_SOS_10 -> "शांत रहें। घबराएं नहीं।"
        ABOUT_SOS_11 _ -> "आपके परिवार और दोस्तों / नम्म यात्री समर्थन को आपातकालीन साझा करके सूचित करें।"
        ABOUT_SOS_12 -> "आप पुलिस हेल्पलाइन (112) पर कॉल करने का विकल्प चुन सकते हैं"
        ABOUT_SOS_13 -> "यदि संभव हो, तो ड्राइवर से वाहन को निकटवर्ती आबादी वाले क्षेत्र पर रोकने के लिए कहें"
        THE_VIDEO_WILL_BE_RECORDED -> "वीडियो केवल 15 सेकंड के लिए रिकॉर्ड किया जाएगा और आपकी सेटिंग के अनुसार साझा किया जाएगा"
        EMERGENCY_VIDEO -> "आपातकालीन वीडियो"
        NAMMA_SAFETY_IS_SET_UP -> "सुरक्षा मोड सफलतापूर्वक सेटअप किया गया है"
        ACTIVATE_NAMMA_SAFETY_POPUP_TITLE -> "आप सुरक्षा मोड को सक्रिय करने जा रहे हैं"
        ACTIVATE_NAMMA_SAFETY_POPUP_DESC -> "आपकी सुरक्षा हमारी प्राथमिकता है। कृपया सुरक्षा मोड को केवल वास्तविक आपातकाल में ही उपयोग करें। दुरुपयोग वास्तविक महत्वपूर्ण स्थितियों से संसाधनों को भटका सकता है"
        ACTIVATE_NAMMA_SAFETY_POPUP_ACTION -> "सक्रियण की पुष्टि करें"
        DISMISS -> "खारिज करें"
        SEND_SILENT_SOS_TO_POLICE -> "पुलिस को चुपके से एसओएस भेजें"
        OUR_SAFETY_PARTNER -> "हमारे सुरक्षा\nसाथी"
        BANGALURU_CITY_POLICE -> "बैंगलोर शहर\nपुलिस"
        GET_OPTIONS_TO_DIRECTLY_CALL_POLICE -> "पुलिस को सीधे कॉल करने के विकल्प प्राप्त करें"
        SHARE_SOS_SILENTLY_WITH_POLICE -> "पुलिस के साथ चुपके से एसओएस साझा करें"
        CALL_AND_ALERT_THE_NEAREST_POLICE_CENTRE -> "कॉल करें और निकटतम पुलिस केंद्र को सचेत करें।"
        SEND_A_SILENT_SOS_TO_THE_POLICE -> "पुलिस को एक मूक एसओएस संदेश भेजें।"
        SEND_A_VIDEO_RECORDING_TO_POLICE -> "पुलिस को एक वीडियो रिकॉर्डिंग भेजें।"
        SEND_VIDEO_TO_POLICE -> "15s वीडियो\nपुलिस को भेजें"
        FINISH_SETUP -> "सेटअप समाप्त करें"
        ACTIVATE_SOS -> "सक्रिय करें"
        MARK_RIDE_AS_SAFE -> "सवारी को सुरक्षित चिह्नित करें"
        EMERGENCY_INFO_SHARED_ACTION_POLICE -> "पुलिस अधिकारियों को आपका स्थान और वीडियो प्राप्त हो गया है। वे जल्द ही आप तक पहुंचेंगे और आपातकालीन कार्रवाई करेंगे।"
        START_SETUP -> "सेटअप शुरू करें"
        SETUP_NOW -> "अभी सेटअप करें"
        NAMMA_SAFETY -> "सुरक्षा"
        COMPLETE_YOUR_NAMMA_SAFETY_SETUP_FOR_SAFE_RIDE_EXPERIENCE -> "सुरक्षा मोड सेटअप पूरा करें"
        CALL_SUPPORT_FOR_SAFETY _ -> "हमारे हेल्पलाइन \nको कॉल करें"
        WE_NOTICED_YOUR_RIDE_HASNT_MOVED -> "हमने देखा है कि कुछ समय से आपका चालक कहीं नहीं गया है। क्या आप अपनी यात्रा में सुरक्षित महसूस कर रहे हैं?"
        WE_NOTICED_YOUR_RIDE_IS_ON_DIFFERENT_ROUTE -> "हमने देखा है कि आपका चालक एक अलग रूट पर है। क्या आप अपनी यात्रा में सुरक्षित महसूस कर रहे हैं?"
        WE_ARE_HERE_FOR_YOU -> "हम आपके लिए यहाँ हैं!"
        I_NEED_HELP -> "मुझे मदद की ज़रूरत है"
        I_FEEL_SAFE -> "मै सुरक्षित महसूस करता हूँ"
        EVERYTHING_OKAY_Q -> "सब कुछ ठीक है?"
        PLEASE_REMAIN_CALM_YOU_CAN_REQUEST_AN_IMMEDIATE_CALL -> "कृपया शांत रहें, यदि आवश्यक हो तो आप हमसे तत्काल कॉल का अनुरोध कर सकते हैं।\n\nअतिरिक्त सुरक्षा के लिए आप शीर्ष दाईं ओर आपातकालीन एसओएस सुविधाओं का भी उपयोग कर सकते हैं।"
        RECEIVE_CALL_FROM_SUPPORT -> "समर्थन से कॉल प्राप्त करें"
        ADD_CONTACTS -> "संपर्क जोड़ें"
        VIDEO_SHARE_INFO_TO_POLICE -> "वीडियो केवल 15 सेकेंड के लिए रिकॉर्ड किया जाएगा और इसे व्हाट्सएप के माध्यम से पुलिस प्राधिकृतियों के साथ साझा किया जाएगा।"
        CALL_POLICE_HELPLINE -> "पुलिस हेल्पलाइन को कॉल करें(112)"
        PLEASE_REMAIN_CALM_CALL_POLICE -> "कृपया शांत रहें, आप आवश्यक होने पर पुलिस हेल्पलाइन को कॉल कर सकते हैं। अतिरिक्त सुरक्षा के लिए आप ऊपर दाएं कोने में सेफ्टी मोड का उपयोग भी कर सकते हैं।"
        PLEASE_ALLOW_CAMERA_AND_MICROPHONE_PERMISSIONS -> "कृपया कैमरा और माइक्रोफोन अनुमतियों को अनुमति दें"
        PERSONAL_SAFETY_ACTION_1 -> "पुलिस हेल्पलाइन को कॉल करें(112)"
        PERSONAL_SAFETY_ACTION_2 _ -> "हमारे समर्थन को कॉल करें"
        PERSONAL_SAFETY_ACTION_2_POLICE -> "पुलिस को साइलेंट एसओएस भेजें"
        PERSONAL_SAFETY_ACTION_3 -> "एक छोटा 15 सेकंड का वीडियो रिकॉर्ड करें।"
        ACTIVATE_NAMMA_SAFETY_WILL_ENABLE_ACCESS -> "सुरक्षा मोड सक्रिय करने से निम्नलिखित सुविधाएं सक्षम हो जाएंगी!"
        RIDE_SHARE_AFTER_SIX_PM -> "9 PM से 6 AM तक आपके यातायात सूचनाएं आपके आपात संपर्कों को भेजी जाएगी।"
        SELECT_PREFERRED_CONTACTS -> "आपातकालीन संपर्कों को प्राथमिक रूप से कॉल करने के लिए चुनें:"
        NEW -> "नया"
        EMERGENCY_SOS -> "आपातकालीन साझा करें"
        SAFETY_CENTER -> "सुरक्षा केंद्र"
        AUTOMATIC_CALL_PLACED_TO_EMERGENCY_CONTACTS -> "आपातकालीन संपर्कों को स्वचालित रूप से कॉल किया गया"
        OPTION_TO_REPORT_A_SAFETY_ISSUE -> "सुरक्षा समस्या की सूचना देने का विकल्प"
        TEST_SAFETY_DRILL -> "सुरक्षा ड्रिल टेस्ट करें"
        START_TEST_DRILL -> "टेस्ट ड्रिल शुरू करें"
        REPORT_SAFETY_ISSUE -> "सुरक्षा की समस्या रिपोर्ट करें"
        SHARE_RIDE -> "सवारी साझा करें"
        SHARE_RIDE_WITH_CONTACT number -> number <> " संपर्क के साथ साझा करें"
        SHARE_LINK -> "लिंक साझा करें"
        GLAD_TO_KNOW_YOU_ARE_SAFE -> "आप सुरक्षित हैं यह जानकर खुशी हुई!"
        TRY_ANOTHER_CONTACT -> "कृपया एक और आपातकालीन संपर्क से संपर्क करने का प्रयास करें"
        YOUR_CURRENT_LOCATION -> "आपका वर्तमान स्थान"
        THIS_IS_NOT_A_REAL_SOS_SITUATION -> "यह एक वास्तविक आपातकालीन स्थिति नहीं है"
        YOUR_VEHICLE_INFO -> "आपकी वाहन सूचना"
        POLICE_VIEW_INSTRUCTION -> "कृपया ऑपरेटर को अपना स्थान बताएं - एप्लिकेशन स्वच्छंद रूप से स्थान साझा नहीं करता है।"
        TEST_SOS_ACTIVATING_IN -> "परीक्षण एसओएस सक्रिय हो रहा है..."
        SOS -> "एसओएस"
        TEST_SOS -> "परीक्षण\nएसओएस"
        SELECT_CONTACT_TO_CALL -> "बुलाए जाने वाले संपर्क को चुनें"
        EMERGENCY_SOS_ACTIVATING -> "आपातकालीन एसओएस क्रियाशील हो रहा है..."
        PRESS_TO_START_TEST_DRILL -> "टेस्ट ड्रिल शुरू\nकरने के लिए दबाएं"
        PRESS_THE_BUTTON_ON_EMERGENCY -> "आपातकालीन स्थिति में बटन दबाएं"
        INFORM_EMERGENCY_CONTACTS -> "कृपया अपने आपातकालीन संपर्कों को इस परीक्षण ड्रिल के बारे में सूचित करें ताकि कोई अनावश्यक पैनिक न हो"
        OTHER_SAFETY_ACTIONS -> "अन्य सुरक्षा कार्रवाई"
        AVAILABLE_IN_REAL_EMERGENCY -> "वास्तविक आपातकाल में उपलब्ध"
        DISCLAIMER -> "अस्वीकरण"
        USE_ONLY_IN_EMERGENCY -> "केवल आपातकाल में उपयोग करें"
        MISUSE_MAY_LEAD_TO_LEGAL_ACTION -> "गलत उपयोग कानूनी कार्रवाई के लिए कारण बन सकता है"
        USE_TEST_DRILL -> "परीक्षण के लिए <span style='color:#2194FF'><u>टेस्ट सुरक्षा ड्रिल</u></span> का उपयोग करें"
        ARE_YOU_READY_TO_START_DRILL -> "क्या आप इस परीक्षण ड्रिल को शुरू करने के लिए तैयार हैं?"
        TEST_DRILL_DESC -> "यह एक परीक्षण है जो आपको एक आपातकालीन स्थिति के लिए तैयार करेगा। यह एक तनाव-मुक्त अनुभव सुनिश्चित करने के लिए आपके आपातकालीन संपर्कों को सूचित करेगा।"
        LEARN_ABOUT_SAFETY_MODE -> "सुरक्षा मोड के बारे में जानें"
        TEST_EMERGENCY_REQUEST_SENT -> "परीक्षण आपातकालीन अनुरोध भेजा गया"
        TEST_SOS_TRIGGERED_DESC -> "एक वास्तविक स्थिति में, आपका स्थान आपके आपातकालीन संपर्कों के साथ साझा किया जाएगा।"
        SOS_WILL_BE_DISABLED -> "यदि तीन बार दुरुपयोग होता है तो एसओएस सुविधा अक्षम कर दी जाएगी।"
        DIAL_NOW -> "अभी डायल करें"
        COMPLETE_YOUR_TEST_DRILL -> "अपने टेस्ट सुरक्षा ड्रिल को पूरा करें: सुरक्षा पहले!"
        TEST_DRILL -> "परीक्षण ड्रिल पूरा करें"
        RIDE_ENDED name -> name <> " की सवारी समाप्त हो गई"
        RIDE_SHARED_WITH_SELECTED_CONTACTS -> "चयनित संपर्कों के साथ यात्रा साझा की गई"
        TERMS_AND_CONDITIONS_UPDATED -> "नियम एवं शर्तें और गोपनीयता नीति अद्यतन कर दी गई है"
        OKAY ->  "ठीक है"
        TRY_LATER -> "बाद में प्रयास करें"
        REFERRAL_CODE_IS_APPLIED -> "रेफरल कोड लागू किया गया"
        YOU_HAVE_ALREADY_USED_DIFFERENT_REFERRAL_CODE -> "आपने पहले ही एक अलग रेफरल कोड का उपयोग किया है"
        INVALID_REFERRAL_CODE -> "अवैध रेफरल कोड"
        STOPS -> "स्थान"
        GREEN_LINE -> "हरित रेखा"
        BLUE_LINE -> "नीली रेखा"
        RED_LINE -> "लाल रेखा"
        VIEW_ROUTE_INFO -> "मार्ग जानकारी देखें"
        VALID_UNTIL -> "वैध जब तक"
        TICKET_NUMBER -> "टिकट नंबर"
        TICKET -> "टिकट"
        TICKETS -> "टिकटें"
        ONWORD_JOURNEY -> "आगे की यात्रा"
        ROUND_TRIP_STR -> "राउंड ट्रिप"
        TICKETS_FOR_CHENNAI_METRO -> "चेन्नई मेट्रो के लिए टिकटें"
        ACTIVE_STR -> "सक्रिय"
        EXPIRED_STR -> "समाप्त"
        USED_STR -> "उपयुक्त"
        MAP_STR -> "नक्शा"
        TICKET_DETAILS -> "टिकट विवरण"
        ROUTE_DETAILS -> "मार्ग विवरण"
        UNCERTAIN_ABOUT_METRO_ROUTES -> "मेट्रो के मार्गों के बारे में अनिश्चित हैं?"
        SEE_MAP -> "नक्शा देखें"
        CHENNAI_METRO_TERM_1 -> "टिकट का नामंजूर करना लागू नहीं है"
        CHENNAI_METRO_TERM_2 -> "टिकटें सभी दिनों 4:30 बजे से 10:30 बजे तक खरीदी जा सकती हैं।"
        CHENNAI_METRO_TERM_EVENT -> "रद्द टिकट मुफ्त टिकट प्रस्ताव की गणना में शामिल नहीं होंगी"
        FREE_TICKET_CASHBACK -> "मुफ़्त टिकट ऑफ़र के लिए कैशबैक 24 घंटे के भीतर जमा कर दिया जाएगा"
        NO_OF_PASSENGERS -> "यात्री की संख्या"
        MAXIMUM -> "अधिकतम"
        TICKETS_ALLOWED_PER_USER -> "प्रति उपयोगकर्ता को अनुमति दी जाती है।"
        STARTING_FROM -> "से शुरू होता है"
        FROM -> "से"
        TO -> "तक"
        BOOKING_ID -> "बुकिंग आईडी"
        PLEASE_WHILE_GEN_TICKET -> "कृपया प्रतीक्षा करें जब हम आपका टिकट तैयार कर रहे हैं"
        PAYMENT_RECEIVED -> "भुगतान प्राप्त हुआ!"
        PLEASE_CHECK_BACK_FEW_MIN -> "कृपया कुछ मिनटों बाद जाँचें।"
        YOUR_BOOKING_PENDING -> "आपकी बुकिंग लंबित है!"
        PLEASE_RETRY_BOOKING -> "कृपया पुनः प्रयास करें।"
        BOOKING_FAILED -> "बुकिंग विफल हुई!"
        INCASE_OF_FAIL -> "असफल होने पर, कोई भी रुपया 5 - 7 कामकाजी दिनों में वापस किया जाएगा।"
        REFRESH_STATUS -> "स्थिति ताजगी दें"
        DATE -> "तारीख"
        NO_OF_TICKETS -> "टिकटों की संख्या"
        ACTIVE_TICKETS -> "सक्रिय टिकटें"
        CONFIRMING_STR -> "पुष्टि हो रही है"
        FAILED_STR -> "विफल"
        CONFIRMED_STR -> "पुष्टि हो गई"
        BUY_METRO_TICKETS -> "मेट्रो टिकट खरीदें"
        GET_FARE -> "किराया प्राप्त करें"
        METRO_BOOKING_TIMINGS -> "मेट्रो बुकिंग समय"
        CHENNAI_METRO_TIME startTime endTime -> "चेन्नई मेट्रो "<> startTime<>" से "<> endTime <> " तक क्यूआर टिकट खरीद करने की अनुमति देता है।"
        PLEASE_COME_BACK_LATER_METRO -> "कृपया समय पर वापस आएं टिकट खरीदने के लिए।"
        NO_QOUTES_AVAILABLE -> "कोट्स उपलब्ध नहीं हैं"
        I_AGREE_TO_THE -> "मैं सहमत हूँ"
        HERE_IS_METRO_TICKET -> "यहाँ मेट्रो टिकट है!"
        VIEW_TICKET -> "टिकट देखें"
        DESTINATION -> "गंतव्य"
        PAY -> "भुगतान करें"
        PENDING_STR -> "लंबित"
        PAST_TICKETS -> "पिछले टिकट"
        ONE_WAY_STR -> "एक तरफा"
        SHARE_TICKET -> "टिकट साझा करें"
        TICKET_IS_NON_CANCELLABLE -> "टिकट रद्द नहीं किया जा सकता"
        CANCEL_BOOKING -> "बुकिंग रद्द करें?"
        BOOKING_NOT_CANCELLABLE -> "मेट्रो बुकिंग नीति के अनुसार यह बुकिंग रद्द नहीं की जा सकती"
        BOOKINGS_WILL_BE_CANCELLED -> "इस बुकिंग से जुड़े सभी टिकट रद्द कर दिए जाएंगे।"
        BOOKINGS_WILL_BE_CANCELLED_WITH_REFUND number -> "इस बुकिंग से जुड़े सभी टिकट रद्द कर दिए जाएंगे, और आपको " <> number <> " का रिफंड प्राप्त होगा"
        REFUND_NOT_APPLICABLE -> "इस बुकिंग के लिए रिफंड लागू नहीं है"
        YES_CANCEL_BOOKING -> "हां, बुकिंग रद्द करें"
        WOULD_YOU_LIKE_TO_PROCEED -> "क्या तुम कार्यवाही को जारी रखना चाहते हैं?"
        BOOKING_CANCELLED -> "आपकी बुकिंग रद्द कर दी गई है"
        REFUND_IS_IN_PROCESS -> "आपका रिफंड प्रक्रिया में है। रिफंड में 3-4 कार्यदिवस लगेंगे।"
        TOTAL_REFUND -> "कुल रिफंड"
        NUMBER_OF_TICKETS -> "टिकटों की संख्या"
        CANCELLATION_DATE -> "रद्दीकरण तिथि"
        TICKETS_FOR_KOCHI_METRO -> "कोच्चि मेट्रो के लिए टिकट"
        YOUR_BOOKED_TICKETS -> "आपके बुक किए गए टिकट यहां दिखाई देंगे"
        PLAN_YOUR_JOURNEY -> "अपनी यात्रा की योजना बनाएं"
        BOOK_ROUND_TRIP -> "राउंड ट्रिप बुक करें"
        BY_PROCEEDING_YOU_AGREE -> "आगे बढ़ते हुए, आप इससे सहमत हैं "
        TERMS_AND_CONDITIONS_FULL -> "नियम एवं शर्तें"
        EXPERIENCE_HASSLE_FREE_METRO_BOOKING appName -> appName <> " पर हैसल-फ्री मेट्रो बुकिंग का अनुभव"
        KOCHI_METRO_TERM_1 -> "टिकट सभी दिन सुबह 5:00 बजे से रात 11:45 बजे के बीच खरीदे जा सकते हैं।"
        KOCHI_METRO_TERM_2 -> "एक बार प्रवेश हो जाने के बाद, यात्रियों को गंतव्य से 120 मिनट के भीतर बाहर निकल जाना चाहिए।"
        KOCHI_METRO_TIME -> "कोच्चि मेट्रो सभी दिन सुबह 5:00 बजे से रात 11:45 बजे तक क्यूआर टिकट खरीदने की अनुमति देता है।"
        BOOK_TICKET -> "टिकट नियुक्त करें"
        ORIGIN -> "मूल"
        HISTORY -> "इतिहास"
        ALWAYS -> "हमेशा"
        ALWAYS_SHARE_DESC -> "सभी यात्राओं के लिए जरूरी संपर्क के लिए यात्रा सूचनाएँ भेजें।"
        NIGHT_RIDES_SHARE -> "रात की यात्राएँ (9 बजे - 6 बजे)"
        NIGHT_RIDES_DESC -> "रात की यात्राओं (9 बजे - 6 बजे) के लिए जरूरी संपर्क के लिए यात्रा सूचनाएँ भेजें"
        NEVER -> "कभी नहीं"
        NEVER_SHARE_DESC -> "जरूरी संपर्क के लिए कभी भी यात्रा सूचना न भेजें"
        SHARE_TRIP_NOTIFICATONS -> "यात्रा सूचनाएँ साझा करें"
        CALL_CUSTOMER_SUPPORT -> "ग्राहक सहायता को कॉल करें"
        YET_TO_START name -> name <> " का सफर अभी तक शुरू नहीं हुआ है।"
        MESSAGE_FROM name -> name <> " की तरफ से संदेश"
        RIDE_CANCELLED -> "सफर रद्द कर दिया गया है"
        TRACK_RIDE_STRING appName driverName trackLink vehicleNumber -> "👋 नमस्ते, मैं" <> appName <> "ड्राइवर," <> driverName <> "के साथ सवारी कर रहा हूँ! इस सवारी का ट्रैकिंग करें:" <> trackLink <> "वाहन नंबर:" <> vehicleNumber        
        SAFETY_CENTER_IS_DISABLED -> "एसओएस सुविधा तीन बार दुरुपयोग की वजह से अक्षम की गई है"
        TRACK_ON_GOOGLE_MAP -> "Google मैप पर ट्रैक करें >"
        SHOW_WALKING_DIRECTION -> "पैदल चलने के निर्देश दिखाएं >"
        SPECIAL_PICKUP_ZONE -> "विशेष पिकअप जोन"
        SPECIAL_PICKUP_ZONE_RIDE -> "विशेष पिकअप जोन राइड"
        WE_WILL_TRY_TO_CONNECT_YOU_WITH_DRIVER_IN_CLOSEST_PICKUP_ZONE -> "हम आपको निकटतम विशेष पिकअप जोन में ड्राइवर से जोड़ने की कोशिश करेंगे।"
        THIS_PROVIDES_YOU_AN_INSTANT_PICKUP_EXPERIENCE -> "यह आपको तत्काल पिकअप अनुभव प्रदान करता है।"
        DRIVER_AT_PICKUP_LOCATION -> "आपका ड्राइवर पिकअप स्थान पर है"
        A_TIP_HELPS_FIND_A_RIDE_QUICKER -> "टिप्स तेजी से सवारी ढूंढने में मदद करते हैं!"
        TIP_ADDED -> "टिप जोड़ी गई!"
        CONTINUE_SEARCH_WITH_NO_TIP -> "बिना किसी टिप के खोज जारी रखें"
        SEARCHING_WITH_NO_TIP -> "बिना टिप के खोज रहे हैं"
        SEARCH_AGAIN -> "फिर से खोजो"
        DRIVER_IS_ON_THE_WAY -> "आपका ड्राइवर रास्ते में है"
        DRIVER_IS_WAITING_AT_PICKUP -> "आपका ड्राइवर पिकअप का इंतजार कर रहा है"
        IS_AT_PICKUP_LOCATION -> "पिकअप स्थान पर है"
        GO_TO_SELECTED_SPOT_FOR_PICKUP -> "पिकअप के लिए चयनित स्थान पर जाएं"
        SELECT_POPULAR_SPOT_FOR_HASSLE_FREE_PICKUP -> "परेशानी मुक्त पिकअप के लिए लोकप्रिय स्थान का चयन करें"
        PREPARE_EMERGENCY_CONTACTS -> "असली आपातकालीन स्थितियों के लिए तैयार असंतुष्ट संपर्क को शक्तिशाली बनाना!"
        EMERGENCY_CONTACTS_WILL_BE_NOTIFIED -> "आपके आपातकालीन संपर्क चिंगारी पर कार्रवाई करने के लिए सूचित किए जाएंगे और अलार्म किया जाएगा।"
        INFORM_EMERGENCY_CONTACTS_ABOUT_TEST -> "अनावश्यक घबराहट से बचने के लिए अपने आपातकालीन संपर्कों को सूचित करें।"
        RECENT_RIDE_ISSUE_DESC -> "यदि आपके हाल के सवारी में समस्याएं हैं तो कृपया नीचे दिए गए विकल्प का चयन करें।"
        I_NEED_HELP_WITH_MY_RECENT_RIDE -> "मुझे मेरी हाल की सवारी में मदद चाहिए"
        CONTINUE_WITH_SAFETY_SETTINGS -> "सुरक्षा सेटिंग्स के साथ जारी रखें"
        TAP_WHERE_TO_TO_BOOK_RIDE -> "राइड बुक करने के लिए 'कहाँ जाना है?' टैप करें!"
        LAST_CHOSEN_VARIANT_NOT_AVAILABLE -> "अंतिम चयनित यात्रा प्रकार उपलब्ध नहीं है। कृपया कोई वैकल्पिक यात्रा विकल्प चुनें।"
        TOLL_CHARGES -> "टोल शुल्क"
        TOLL_CHARGES_DESC -> "ड्राइवर द्वारा किया गया पार्किंग/टोल शुल्क किराए में जोड़ा जाता है"
        TOLL_CHARGES_INCLUDING amount -> "टोल शुल्क " <> amount <> "किराया में शामिल"
        TOLL_ROAD_CHANGED -> "टोल शुल्क लागू नहीं"
        PARKING_CHARGE-> "पार्किंग शुल्क"
        TOLL_OR_PARKING_CHARGES -> "^टोल/पार्किंग शुल्क"
        TOLL_CHARGES_ESTIMATED -> "टोल शुल्क (अनुमानित)^"
        ADD_TIP -> "टिप जोड़ें"
        CHANGE_RIDE_TYPE -> "राइड प्रकार बदलें"
        TRY_ADDING_TIP_OR_CHANGE_RIDE_TYPE -> "टिप जोड़ने का प्रयास करें या राइड प्रकार बदलें"
        APPLICABLE_TOLL_CHARGES -> "टोल शुल्क भाड़ों में शामिल हैं"
        UPDATE_TIP_STR -> "टिप अपडेट करें"
        WHO_CAN_TRACK_YOUR_RIDE appName -> appName <>" ऐप पर आपकी राइड को कौन फ़ॉलो कर सकता है"
        EMERGENCY_CONTACTS_CAN_FOLLOW appName -> appName <>" एप्लिकेशन पर आपके इमरजेंसी संपर्क आपकी राइड को फ़ॉलो कर सकते हैं और इमरजेंसी प्रतिक्रिया कार्रवाई कर सकते हैं"
        ALERT_SAFETY_TEAM appName -> appName <>" सुरक्षा टीम को चेतावनी दें"
        RECOMMEND_EMERGENCY_CONTACTS_TO_INSTALL appName -> "हम अनुशंसा करते हैं कि आप इमरजेंसी संपर्कों को बेहतर ट्रैकिंग अनुभव के लिए "<> appName <>" इंस्टॉल करें"
        SAFETY_TEAM_WILL_BE_ALERTED appName -> "SOS के चलते "<> appName <>" सुरक्षा टीम को सूचित किया जाएगा"
        EMERGENCY_CONTACTS_CAN_TAKE_ACTION appName -> appName <>" ऐप पर आपके इमरजेंसी संपर्क कार्रवाई कर सकते हैं / ले सकते हैं"
        SHARE_RIDE_DESCRIPTION appName -> "इसको चुनने पर "<> appName <>" आपके इमरजेंसी संपर्क को ऐप पुश सूचना भेजेगा"
        PLEASE_STAY_CALM_TEAM_ALERTED appName -> "कृपया शांत रहें, "<> appName <>" सुरक्षा टीम को सूचित किया गया है!"
        INDICATION_TO_EMERGENCY_CONTACTS appName -> appName <>" आपके इमरजेंसी संपर्क को इसे एक परीक्षण ड्रिल बताएगा, जिससे उन्हें तनावमुक्त अनुभव होगा।"
        BOOK name -> name <> " बुक करें"
        FARE_FOR limit -> limit <> " के लिए किराया"
        WAITING_CHARGE_LIMIT timeLimit -> "इंतजार शुल्क ("<> timeLimit <>" मिनट के बाद)"
        TIME_TAKEN -> "सवारी की अवधि"
        TRIP_DISTANCE -> "यात्रा की दूरी"
        UNABLE_TO_CANCEL_RIDE -> "आप इस सवारी को रद्द नहीं कर सकते"
        GOT_A_REFERRAL_FROM_A_DRIVER_OR_FRIEND -> "क्या आपको किसी ड्राइवर या दोस्त से रेफ़ेरल कोड मिला है?"
        ENTER_REFERRAL_CODE_ -> "रेफ़ेरल कोड दर्ज करें"
        REFERRED_USERS -> "रेफ़ेरल किए गए उपयोगकर्ता"
        SHOW_APP_QR -> "एप्लिकेशन QR दिखाएं"
        SHARE_AND_REFER -> "शेयर और रेफ़ेर करें"
        YOUR_REFERRAL_CODE -> "आपका रेफ़ेरल कोड"
        REFER_YOUR_FRIENDS -> "अपने दोस्तों को रेफ़ेर करें"
        REFERRALS -> "रेफ़ेरल्स"
        ENTER_NOW -> "अब दर्ज करें"
        WHAT_IS_REFERRAL_PROGRAM -> "रेफ़ेरल प्रोग्राम क्या है?"
        USERS_WHO_DOWNLOAD_APP_AND_COMPLETE_THEIR_FIRST_RIDE_USING_REFERRAL_CODE appName -> "उन उपयोगकर्ताओं को जो " <> appName <> " ऐप डाउनलोड करते हैं और अपने पहले राइड को पूरा करते हैं, उन्हें रेफ़ेरल किए गए उपयोगकर्ता के रूप में गिना जाएगा। <br><br> <i>रेफ़ेरल कोड साइन अप करते समय दर्ज किया जा सकता है।</i>"
        THE_REFERRAL_PROGRAM_INCENTIVISES_DRIVERS_TO_ACCEPT_MORE_RIDES appName -> "रेफ़ेरल प्रोग्राम ड्राइवरों को अधिक राइड स्वीकार करने, कम राइड रद्द करने और आपको बेहतर सेवा प्रदान करने के लिए प्रोत्साहित करता है और प्रमुख ड्राइवरों को पहचानता और पुरस्कृत करता है। <br><br> आप ड्राइवर के रेफ़ेरल कोड दर्ज करके सहायक बन सकते हैं और " <> appName <> " समुदाय के लिए राइड की गुणवत्ता को बेहतर बना सकते हैं! <br><br> <i>आप " <> appName <> " ड्राइवर या उपयोगकर्ता से एक रेफ़ेरल कोड प्राप्त कर सकते हैं।</i>"
        INVALID_CODE -> "अमान्य कोड!"
        ENTER_6_DIGIT_REFERRAL_CODE_BELOW -> "नीचे 6 अंकों का रेफ़ेरल कोड दर्ज करें"
        APPLY -> "लागू करें"
        BOOK_ANY -> "बुक कोई भी"
        TOLL_CHARGES_INCLUDED -> "टोल शुल्क समाहित"
        ONE_TAP_BOOKINGS -> "वन-टैप बुकिंग"
        HAS_YOUR_DRIVER_SET_THE_AC_AS_PER_YOUR_PREFERENCE -> "क्या आपके ड्राइवर ने एसी को आपकी पसंद के अनुसार सेट किया है?"
        NO_REPORT_AN_ISSUE -> "नहीं, समस्या रिपोर्ट करें"
        GREAT_ENJOY_THE_TRIP -> "बढ़िया, सफर का आनंद लें!"
        ENJOY_YOUR_BUDGET_FRIENDLY_NON_AC_RIDE -> "अपनी बजट फ्रेंडली,\nनॉन-एसी यात्रा का आनंद लें!"
        AC_IS_NOT_AVAILABLE_ON_THIS_RIDE -> "इस राइड पर एसी उपलब्ध नहीं है"
        AC_NOT_WORKING_DESC -> "एसी काम नहीं कर रहा / ड्राइवर ने ऑन करने से मना कर दिया"
        SHOWING_FARE_FROM_MULTI_PROVIDER -> "एकाधिक प्रदाताओं से किराए दिखाए जा रहे हैं"
        LIVE_CHAT -> "लाइव चैट"
        DRIVER_TIP_ADDITION -> "ड्राइवर टिप जोड़"
        LIVE_RIDE_SHARING -> "लाइव राइड शेयरिंग"
        ENHANCED_SAFETY -> "उन्नत सुरक्षा"
        CONFIRM_PROVIDER -> "प्रदाता की पुष्टि करें"
        SELECT_A_PROVIDER -> "एक प्रदाता चुनें"
        CONFIRMING_SELECTED_PROVIDER -> "चयनित प्रदाता की पुष्टि की जा रही है:"
        BOOK_TOP_PROVIDER -> "बुक टॉप प्रदाता"
        CHOOSE_FROM_PROVIDERS -> "सभी उपलब्ध प्रदाताओं में से चुनें"
        CHOOSE_BETWEEN_PROVIDERS -> "एकाधिक प्रदाताओं में से चुनें"
        CHOOSE_BETWEEN_PROVIDERS_DESC -> "सभी उपलब्ध प्रदाताओं के उद्धरण देखने के लिए इस सुविधा को सक्षम करें।"
        GUARANTEED_RIDE -> "गारंटीयुक्त सवारी"
        THIS_RIDE_FULFILLED_BY provider -> "यह सवारी पूरी होती है:" <> provider
        ADDITIONAL_FEATURES_ON merchantName -> merchantName <> " पर अतिरिक्त सुविधाएं"
        NOTIFY_YOUR_EC -> "अपने व्यक्तिगत आपातकालीन संपर्कों को सूचित करें"
        EC_CAN_RESPOND -> "आपातकालीन संपर्क आपातकालीन प्रतिक्रिया कार्रवाइयां कर सकते हैं/कर सकते हैं"
        QUICK_SUPPORT merchantName-> "त्वरित समर्थन" <> merchantName<> "एसओएस समर्थन"
        LEARN_ABOUT_APP_SAFETY_FEAT merchantName -> "विशेष सुरक्षा सुविधाओं के बारे में जानें" <> merchantName
        OTHER_PROVIDER_NO_RECEIPT -> "अन्य प्रदाताओं द्वारा पूरी की गई सवारी के लिए ड्राइवर रसीद अभी तक उपलब्ध नहीं है।"
        RIDE_FULFILLED_BY merchantName-> "सवारी इसके द्वारा पूरी की गई:" <> merchantName
        CONGESTION_CHARGES -> "भीड़भाड़ शुल्क*"
        TIP_CAN_BE_ADDED maxTip -> "राइड किराये में उपेक्ष्य ₹" <> maxTip <> " तक की टिप जोड़ी जा सकती है।"
        CONGESTION_CHARGES_DESC charges -> "*वर्तमान में आपकी सवारी पर "<> charges <>"% का भीड़भाड़ शुल्क लागू है ताकि ड्राइवर के उच्च ट्रैफिक में समय की भरपाई की जा सके या आपके लिए अधिक ड्राइवर उपलब्ध कराए जा सकें।"
        AC_TURNED_OFF -> "एसी बंद था"
        ESTIMATES_EXPIRY_ERROR -> "अनुमान समाप्त हो गया है। कृपया पुनः प्रयास करें।"
        ESTIMATES_EXPIRY_ERROR_AND_FETCH_AGAIN -> "अनुमान समाप्त हो गया है। फिर से ले रहे हैं, कृपया कुछ क्षण"
        QUOTES_EXPIRY_ERROR_AND_FETCH_AGAIN -> "कोट्स की अवधि समाप्त हो गई है। पुनः प्राप्त किया जा रहा है, कृपया एक क्षण प्रतीक्षा करें और पुनः जांचें।"
        PAY_YOUR_DRIVER_BY_CASH_OR_UPI -> "कैश या UPI से अपने ड्राइवर को भुगतान करें"
        TRIP_DELAYED -> "सफर में देरी हो गई"
        SELECT_VEHICLE -> "वाहन चुनें"
        BOOK_RENTAL -> "रेंटल बुक करें"
        CONFIRM_RENTAL -> "रेंटल की पुष्टि करें"
        RENTAL_RIDE -> "रेंटल राइड"
        SELECT_DURATION -> "समय चुनें"
        SELECT_DISTANCE -> "दूरी चुनें"
        RENTAL_OPTIONS -> "रेंटल विकल्प"
        BOOKING_ON -> "बुकिंग पर"
        INCLUDED_KMS -> "शामिल किए गए किलोमीटर:"
        BASE_FARE -> "बेस किराया:"
        TOLLS_AND_PARKING_FEES -> "टोल और पार्किंग फीस"
        FINAL_FARE_DESCRIPTION -> "अंतिम किराया वास्तविक यात्रा की अवधि पर आधारित होगा, जो आगे की घंटे के लिए बदल दी जाएगी या ट्रिप की चयनित अवधि के लिए (जो कि ज्यादा है)।"
        EXCESS_DISTANCE_CHARGE_DESCRIPTION charges -> "अतिरिक्त दूरी के लिए " <> charges <> " शुल्क लिया जाएगा"
        ADDITIONAL_CHARGES_DESCRIPTION -> "अंतिम किराया वास्तविक यात्रा की अवधि और दूरी पर आधारित होगा"
        PARKING_FEES_AND_TOLLS_NOT_INCLUDED -> "पार्किंग शुल्क, <b> टोल शुल्क </b> और अन्य अधिभार <b> शामिल नहीं हैं </b>। कृपया इनका भुगतान अलग से ड्राइवर को करें।"
        NIGHT_TIME_FEE_DESCRIPTION -> "यदि आपकी यात्रा का कोई भी हिस्सा रात 10:00 बजे से सुबह 5:00 बजे के बीच होता है, तो आपकी सवारी पर एक समान नाइट टाइम शुल्क {} लागू किया जाएगा।"
        CHOOSE_YOUR_RENTAL_RIDE -> "अपनी रेंटल राइड चुनें"
        FIRST_STOP_OPTIONAL -> "पहला स्टॉप (ऐच्छिक)"
        JANUARY -> "जनवरी"
        FEBRUARY -> "फरवरी"
        MARCH -> "मार्च"
        APRIL -> "अप्रैल"
        MAY -> "मई"
        JUNE -> "जून"
        JULY -> "जुलाई"
        AUGUST -> "अगस्त"
        SEPTEMBER -> "सितंबर"
        OCTOBER -> "अक्टूबर"
        NOVEMBER -> "नवंबर"
        DECEMBER -> "दिसंबर"
        HOURS -> "घंटे"
        NOT_ADDED_YET -> "अभी तक नहीं जोड़ा गया है"
        NEXT_STOP -> "अगला स्टॉप"
        TIME -> "समय"
        DISTANCE -> "दूरत्व"
        STARTING_ODO -> "शुरुआती ODO"
        END_OTP -> "समाप्त OTP"
        ONLY_LOCATION_WITHIN_CITY_LIMITS -> "शहर सीमा के अंदर के स्थानों को ही किराए पर लेने के लिए योग्य माना जाएगा।"
        RIDE_TIME -> "राइड समय"
        RIDE_DISTANCE -> "राइड दूरी"
        RIDE_STARTED_AT -> "राइड शुरू हुआ था"
        RIDE_ENDED_AT -> "राइड समाप्त हुआ था"
        ESTIMATED_FARE -> "अनुमानित किराया"
        EXTRA_TIME_FARE -> "अतिरिक्त समय कीमत"
        TOTAL_FARE -> "कुल किराया"
        FARE_UPDATE -> "किराया अपडेट"
        NOW -> "अब"
        DATE_INVALID_MESSAGE -> "तारीख अवैध है। बुकिंग केवल {} दिन से पहले ही उपलब्ध है"
        EDIT_PICKUP -> "पिकअप संपादित करें"
        ADD_STOP ->  "स्थान जोड़ें"
        ENTER_PICKUP_LOC ->  "पिकअप स्थान दर्ज करें"
        INTERCITY_OPTIONS -> "इंटरसिटी विकल्प"
        PROCEED -> "आगे बढ़ें"
        SCHEDULE_RIDE_AVAILABLE -> "स्केड्यूल राइड केवल 30 मिनट के बाद उपलब्ध है"
        RENTAL_RIDE_UNTIL -> "आप रेंटल राइड पर हैं जब तक"
        EXTRA_TIME_CHARGES -> "अतिरिक्त समय शुल्क"
        DIST_BASED_CHARGES -> "दूरी आधारित शुल्क"
        TIME_BASED_CHARGES -> "समय आधारित शुल्क"
        RENTAL_POLICY -> "किराये की नीति"
        SELECT_PACKAGE -> "पैकेज चुनें"
        RENTAL_POLICY_DESC -> "हर घंटे आपको पैकेज में 10 किलोमीटर मिलते हैं। आप एक सीमा तक अतिरिक्त किलोमीटर की योजना बना सकते हैं और यदि आप आधार दूरी से अधिक हो जाते हैं तो अतिरिक्त लागत बचा सकते हैं।"
        RENTAL_POLICY_DESC_1 -> "बुकिंग की पुष्टि करने से पहले अगली स्क्रीन पर किराया की समीक्षा करें"
        RENTALS_INTERCITY_AVAILABLE appName -> "रेंटल और इंटरसिटी ट्रिप, अब " <> appName <> " पर उपलब्ध"
        CHECK_IT_OUT -> "इसे चेक करें"
        FAILED_TO_CANCEL -> "यात्रा रद्द करने में विफल रहा"
        SCHEDULING_ALLOWED_IN_INTERCITY_RENTAL -> "अंतरशहरी या किराये की सवारियों में ही शेड्यूलिंग की अनुमति है।"
        SPECIAL_ZONE_INTERCITY_INELIGIBLE -> "विशेष क्षेत्र के भीतर के स्थान अंतरशहरी सवारियों के लिए अयोग्य हैं।"
        NO_RIDES_SCHEDULED_YET -> "अभी तक कोई सवारियाँ शेड्यूल नहीं की गई हैं!"
        RIDE_BOOKING -> "राइड बुकिंग।"
        SPECIAL_ZONE_RENTAL_INELIGIBLE -> "विशेष क्षेत्र के भीतर के स्थान किराये की सवारियों के लिए अयोग्य हैं।"
        SERVICES -> "सेवाएं"
        YOU_HAVE_UPCOMING_RENTAL_BOOKING bookingTime -> "आपके पास <b>" <> bookingTime <> "</b> को आगामी किराये की बुकिंग हैं।"
        YOU_HAVE_UPCOMING_INTERCITY_BOOKING bookingTime -> "आपके पास <b>" <> bookingTime <> "</b> को आगामी इंटरसिटी बुकिंग हैं।"
        SCHEDULED -> "शेड्यूल किया गया"
        UPCOMING_BOOKINGS -> "आपके पास आने वाली बुकिंगें हैं"
        RENTALS_ -> "किराया"
        INTER_CITY_ -> "इंटरसिटी"
        A_RIDE_ALREADY_EXISTS -> "एक सवारी पहले से मौजूद है।"
        YOU_HAVE_AN_RIDE_FROM_TO_SCHEDULED_FROM_TILL -> "आपके पास एक {} राइड {} से {} तक है जो {} से {} तक निर्धारित किया गया है। आप सामान्य राइड्स ले सकते हैं या यहाँ तक कि यह पहले से ही निर्धारित राइड की टाइमलाइन के साथ संघर्ष नहीं करता है तब तक एक और राइड निर्धारित कर सकते हैं।"
        EXTRA_PER_KM_FARE -> "प्रति किलोमीटर अतिरिक्त किराया"
        EXTRA_PER_MINUTE_FARE -> "प्रति मिनट अतिरिक्त किराया"
        PICKUP_CHARGES -> "पिकअप शुल्क"
        WAITING_CHARGES_AFTER_3_MINS -> "3 मिनट के बाद प्रतीक्षा शुल्क"
        FARE_DETERMINED_AS_PER_KARNATAKA_GUIDELINES -> "कर्नाटक राज्य सरकार के निर्देशानुसार निर्धारित किराया"
        RENTAL_CHARGES -> "किराये की लागत"
        RENTAL_INFO_POLICY_DESC inclusiveKms -> "प्रत्येक घंटे की रेंटल बुकिंग के लिए " <> inclusiveKms <> " किमी आपके पैकेज में शामिल है।"
        RENTAL_INFO_POLICY_DESC_ -> "यदि बुनियादी दूरी पर्याप्त नहीं है, तो आप अतिरिक्त किलोमीटर जोड़ने और अतिरिक्त लागतों की बचत करने का विकल्प चुन सकते हैं।"
        RENTAL_SCREEN_EXPLAINER -> "आप अब रियायती दर पर अतिरिक्त किलोमीटर जोड़ सकते हैं। इस तरह, आप बाद में उपयोग किए गए अतिरिक्त दूरी के लिए अधिक शुल्क से बच सकते हैं।"
        INSTANT -> "तुरंत"
        COMING_SOON -> "जल्द ही!"
        CANCEL_SCHEDULED_RIDE -> "निर्धारित सवारी रद्द करें"
        CANCEL_SCHEDULED_RIDE_DESC -> "क्या आप वाकई इस सवारी को रद्द करना चाहते हैं?<br><br>(एक से अधिक बार रद्दीकरण के कारण आपको अधिक किराये की सवारी का अनुरोध करने से रोका जा सकता है)"
        CONFIRM_CANCELLATION -> "रद्दीकरण की पुष्टि करें"
        INTERCITY_RIDES_COMING_SOON -> "इंटरसिटी सवारी जल्द ही आ रही है!"
        VIEW_FARES -> "किराया देखें"
        EXCESS_TIME_DESCRIPTION charges -> "अतिरिक्त समय के लिए " <> charges <> "लिया जाएगा"
        ESTIMATED_CHARGES -> "अनुमानित शुल्क"
        NIGHT_TIME_FEES -> "रात के समय का शुल्क"
        PARKING_AND_OTHER_CHARGES -> "पार्किंग और अन्य शुल्क"
        ADDITIONAL_CHARGES -> "अतिरिक्त शुल्क"
        ESTIMATED_BASE_FARE -> "अनुमानित मूलधन भाड़ा"
        INCLUDED_DISTANCE -> "शामिल दूरी"
        INCLUDED_TIME -> "शामिल किया गया समय"
        TOLL_CHARGES_DESCRIPTION -> "लागू टोल शुल्क अंतिम किराये में जोड़ा जाएगा"
        WILL_BE_ADDED_TO_FINAL_FARE -> "अंतिम किराये में जोड़ा जाएगा"
        EXTRA_DISTANCE_FARE -> "अतिरिक्त दूरी का किराया"
        NETWORK_ERROR -> "नेटवर्क त्रुटि"
        SERVER_ERROR -> "सर्वर त्रुटि"
        UNKNOWN_ERROR -> "अज्ञात त्रुटि"
        CONNECTION_REFUSED -> "कनेक्शन नहीं हो सका"
        TIMEOUT -> "समय समाप्त"
        WAS_TOLL_EXP_SMOOTH -> "क्या आपका टोल अनुभव सुचारू था?"
        WAS_TOLL_EXP_SMOOTH_DESC -> "क्या टोल शुल्क की गणना और वसूली सही ढंग से की गई थी?"
        WAS_RIDE_SAFE -> "क्या आपकी यात्रा सुरक्षित रही?"
        WAS_RIDE_SAFE_DESC -> "क्या आपकी सवारी संतोषजनक ढंग से सुरक्षित और चिंता मुक्त थी?"
        WAS_DRIVER_HELPFUL -> "क्या ड्राइवर ने सहायता की पेशकश की?"
        WAS_DRIVER_HELPFUL_DESC -> "क्या आपका ड्राइवर आपकी ज़रूरतों को समझ रहा था\nऔर उन्हें यात्रा के दौरान समायोजित कर रहा था?"
        COLLECT_TOLL_SEP -> "कृपया ड्राइवर को इसका भुगतान अलग से करें <b>केवल तभी जब टोल पार किया गया हो</b>"
        FINAL_FARE_EXCLUDES_TOLL -> "अंतिम किराये में टोल शुल्क शामिल नहीं है"
        TOLL_CHARGES_MAYBE_APPLICABLE -> "टोल शुल्क लागू हो सकता है"
        METRO_BANNER_TITLE appName -> "अब मेट्रो टिकट बुक करें \n" <> appName <> " से!"
        VIEW_ON_GOOGLE_MAPS -> "गूगल मैप्स पर देखें"
        WALKING_DIRECTIONS_TO_PICKUP -> "पिकअप के लिए पैदल दिशानिर्देश"
        EXPLORE_CITY_WITH_US city -> city <> " में हमारे साथ यात्रा करें"
        GO_TO_DESTINATION destination -> destination <> " पर जाएं"
        WALK_TO address -> address <> " पर चलें"
        BANGALORE -> "बेंगलुरु"
        KOLKATA -> "कोलकाता"
        PARIS -> "पेरिस"
        KOCHI -> "कोच्चि"
        DELHI -> "दिल्ली"
        HYDERABAD -> "हैदराबाद"
        MUMBAI -> "मुंबई"
        CHENNAI -> "चेन्नई"
        COIMBATORE -> "कोयंबटूर"
        PONDICHERRY -> "पुदुचेरी"
        GOA -> "गोवा"
        PUNE -> "पुणे"
        MYSORE -> "मैसूर"
        TUMAKURU -> "तुमकूरु"
        NOIDA -> "नोएडा"
        GURUGRAM -> "गुरुग्राम"
        WAITING_CHARGES -> "प्रतीक्षा शुल्क"
        PLACE_A_CALL -> "कॉल करें"
        YOU_CAN_WRITE_TO_US_AT -> "आप हमें लिख सकते हैं"
        CHARGEABLE -> "चार्ज योग्य"
        BOOKED -> "बुक किया गया"
        SURCHARGES -> "अधिभार"
        SILIGURI -> "सिलीगुड़ी"
        KOZHIKODE -> "कोझिकोड"
        THRISSUR -> "त्रिशूर"
        TRIVANDRUM -> "तिरुवनंतपुरम"        
        METRO_FREE_TICKET_EVENT freeTicketInterval -> "हर " <> freeTicketInterval <> " टिकट मुफ्त है!"
        METRO_FREE_TICKET_EVENT_DESC freeTicketInterval maxFreeTicketCashback -> "हर " <> freeTicketInterval <> " टिकट पर मुफ्त टिकट प्राप्त करें (अधिकतम ₹" <> maxFreeTicketCashback <> ") (ONDC Offer)"
        NEXT_FREE_TICKET -> "अगली टिकट मुफ्त है"
        FREE_TICKET_AVAILABLE maxCashback freeTicketCount -> "अनलॉक करें कैशबैक (अधिकतम ₹" <> maxCashback <> ") पर " <> freeTicketCount <> " टिकट!"
        ADDITIONAL_CHARGES_WILL_BE_APPLICABLE -> "अतिरिक्त शुल्क तब लागू हो सकता है जब ड्राइवर पिकअप स्थान के पास हो।"
        TRIVANDRUM -> "तिरुवनंतपुरम"
        PARKING_CHARGES_INCLUDED amount -> amount <> " पार्किंग शुल्क शामिल"
        APP_TOLL_CHARGES -> "लागू टोल शुल्क किराए में शामिल हैं"
        APP_PARKING_CHARGES -> "लागू पार्किंग शुल्क किराए में शामिल हैं"
        APP_TOLL_PARKING_CHARGES -> "लागू टोल और पार्किंग शुल्क किराए में शामिल हैं"
        PARKING_CHARGES_DESC -> "पार्किंग शुल्क पिकअप स्थान पर ड्राइवर से लिए गए शुल्क पर निर्भर है"
        TOLL_CHARGES_INCLUDED_IN_FAIR -> "टोल शुल्क किराए में शामिल हैं"
        PLEASE_DO_NOT_PAY_EXTRA_TO_DRIVER -> "कृपया ड्राइवर को अतिरिक्त भुगतान न करें"
        VELLORE -> "वेल्लोर"
        HOSUR -> "होसुर"
        MADURAI -> "मदुराई"
        THANJAVUR -> "थंजावुर"
        TIRUNELVELI -> "तिरुनेलवेली"
        SALEM -> "सलेम"
        TRICHY -> "त्रिची"
        DAVANAGERE -> "दावणगेरे"
        SHIVAMOGGA -> "शिवमोगा"
        HUBLI -> "हुबली"
        MANGALORE -> "मंगलौर"
        GULBARGA -> "गुलबर्गा"
        UDUPI -> "उडुपी"
        CANCEL_BOOKING_ -> "बुकिंग रद्द करें"
        CANCEL_INTERCITY_BOOKING -> "इंटरसिटी बुकिंग रद्द करें"
        RENTAL_BOOKING -> "रेंटल बुकिंग"
        INTERCITY_BOOKING -> "इंटरसिटी बुकिंग"
        BOOKING -> "बुकिंग"
        TRANSIT -> "पारगमन"
        INTERCITY_STR -> "नगरों के बीच का"  
        RENTAL_STR -> "किराये"
        DELIVERY -> "वितरण"
        INTERCITY_BUS -> "इंटरसिटी बस"
        WHERE_ARE_YOU_GOING -> "आप कहां जा रहे हैं?"
        TAP_TO_FOLLOW -> "फ़ॉलो करने के लिए टैप करें"
        HAS_SHARED_A_RIDE_WITH_YOU name -> name <> " ने आपके साथ एक यात्रा साझा की है। फ़ॉलो करने के लिए टैप करें"