module Resources.Localizable.ML where

import Language.Types (STR(..))
import Prelude ((<>))

getML :: STR -> String
getML stringKey =
    case stringKey of
        DOWNLOAD_INVOICE -> "ഇൻവോയ്സ് ഡൗൺലോഡ് ചെയ്യുക"
        REPORT_AN_ISSUE -> "ഒരു പ്രശ്നം റിപ്പോർട്ടുചെയ്യുക"
        SUBMIT -> "സമർപ്പിക്കുക"
        VIEW_INVOICE -> "ഇൻവോയ്സ് കാണുക"
        TOTAL_AMOUNT -> "മൊത്തം തുക"
        AMOUNT_PAID -> "അടച്ച തുക"
        TRIP_DETAILS_ -> "യാത്ര വിശദാംശങ്ങൾ"
        DOWNLOAD_PDF -> "PDF ഡൗൺലോഡുചെയ്യുക"
        INVOICE -> "ഇൻവോയ്സ്"
        TRIP_CHARGES -> "യാത്ര ചാർജുകൾ"
        PROMOTION -> "പ്രമോഷൻ"
        SEND_EMAIL -> "ഇമെയിൽ അയയ്ക്കുക"
        YOU_CAN_DESCRIBE_THE_ISSUE_YOU_FACED_HERE -> "പ്രശ്നം ഇവിടെ വിവരിക്കാം"
        THANK_YOU_FOR_WRITING -> "ഞങ്ങൾക്ക് എഴുതിയതിന് നന്ദി!"
        WE_HAVE_RECEIVED_YOUR_ISSUE -> "നിങ്ങളുടെ പ്രശ്നം ഞങ്ങൾക്ക് ലഭിച്ചു. ഞങ്ങൾ കുറച്ച് സമയത്തിനുള്ളിൽ നിങ്ങളെ സമീപിക്കും."
        GO_HOME_ -> "വീട്ടിലേക്ക് പോകുക"
        LOGO -> "ലോഗോ"
        ABOUT_APP_DESCRIPTION -> "യാത്രക്കാരെ ഡ്രൈവർമാരുമായി ബന്ധിപ്പിക്കുന്നതിനുള്ള ഒരു ഓപ്പൺ പ്ലാറ്റ്‌ഫോമാണ് {}. ഈ ആപ്പ് റൈഡർമാർക്ക് മീറ്റർ നിരക്കിൽ റൈഡുകൾ ബുക്ക് ചെയ്യാൻ സൗകര്യപ്രദമാക്കുന്നു, അതിനാൽ നിരക്ക് കുറഞ്ഞിരിക്കും."
        ABOUT -> "ആപ്പിനെ കുറിച്ച്"
        PRIVACY_POLICY -> "സ്വകാര്യതാ നയം"
        SET_UP_YOUR_ACCOUNT -> "നിങ്ങളുടെ അക്കൗണ്ട് സജ്ജമാക്കുക"
        CONTINUE -> "തുടരുക"
        ENTER_YOUR_NAME -> "നിങ്ങളുടെ പേര് നൽകുക"
        FULL_NAME -> "പൂർണ്ണമായ പേര്"
        EMAIL -> "ഇമെയിൽ"
        PLEASE_CHOOSE_YOUR_PREFERRED_LANGUAGE_TO_CONTINUE -> "നിങ്ങൾ ഇഷ്ടപ്പെടുന്ന ഭാഷ തിരഞ്ഞെടുക്കുക."
        WRITE_TO_US -> "ഞങ്ങൾക്ക് എഴുതുക"
        NOTE -> "കുറിപ്പ്:"
        VISIT_MY_RIDES_SECTION_FOR_RIDE_SPECIFIC_COMPLAINTS -> " റൈഡ് അനുബന്ധമായ പരാതികൾക്കായി ‘എന്റെ റൈഡുകൾ’ വിഭാഗം സന്ദർശിക്കുക"
        THANK_YOU_FOR_WRITING_TO_US -> "ഞങ്ങൾക്ക് എഴുതിയതിന് നന്ദി!"
        WE_HAVE_RECEIVED_YOUR_ISSUE_WELL_REACH_OUT_TO_YOU_IN_SOMETIME -> "ഞങ്ങൾക്ക് നിങ്ങളുടെ പ്രശ്നം ലഭിച്ചു. ഞങ്ങൾ എപ്പോഴെങ്കിലും നിങ്ങളിലേക്ക് എത്തിച്ചേരും."
        GO_TO_HOME__ -> "വീട്ടിലേക്ക് പോകൂ"
        SUBJECT -> "വിഷയം"
        YOUR_EMAIL_ID -> "നിങ്ങളുടെ ഇമെയിൽ ഐഡി"
        DESCRIBE_YOUR_ISSUE -> "നിങ്ങളുടെ പ്രശ്നം വിവരിക്കുക"
        ENTER_MOBILE_NUMBER -> "മൊബൈൽ നമ്പർ നൽകുക"
        BY_TAPPING_CONTINUE -> "‘തുടരുക’ ടാപ്പ് ചെയ്യുന്നതിലൂടെ"
        TO_THE -> "നിങ്ങൾ സ്വീകരിക്കുന്നുവെന്ന് നിങ്ങൾ സമ്മതിക്കുന്നു"
        ENTER_OTP -> "OTP നൽകുക"
        RESEND -> "വീണ്ടും അയയ്ക്കുക"
        ENTER_YOUR_MOBILE_NUMBER -> "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക"
        LOGIN_USING_THE_OTP_SENT_TO -> "അയച്ച OTP ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക"
        YOUR_RECENT_RIDE -> "യുവർ റീസെന്റ് റൈഡ്"
        VIEW_ALL_RIDES -> "വ്യൂ ഓൾ റൈറ്റ്സ്"
        ALL_TOPICS -> "എല്ലാ വിഷയങ്ങളും"
        FAQ -> "പതിവുചോദ്യങ്ങൾ"
        REPORT_AN_ISSUE_WITH_THIS_TRIP -> "ഈ യാത്രയിൽ ഒരു പ്രശ്നം റിപ്പോർട്ടുചെയ്യുക"
        YOU_RATED -> "യു റേറ്റഡ്:"
        GETTING_STARTED_AND_FAQS -> "ആരംഭിക്കുക, പതിവുചോദ്യങ്ങൾ"
        FOR_OTHER_ISSUES_WRITE_TO_US -> "മറ്റ് പ്രശ്നങ്ങൾക്ക്, ഞങ്ങൾക്ക് എഴുതുക"
        HELP_AND_SUPPORT -> "സഹായസഹകരണങ്ങൾ"
        OUR_SUGGESTED_PRICE_FOR_THIS_TRIP_IS -> "ഈ യാത്രയ്ക്കുള്ള ഞങ്ങളുടെ നിർദ്ദേശിച്ച വില"
        DRIVERS_CAN_CHARGE_BETWEEN_THE_ABOVE_RANGE -> "*ഡ്രൈവർമാർക്ക് മേല്പറഞ്ഞ പരിധിക്കിടയിൽ ചാർജ് ചെയ്യാം"
        HOW_THIS_WORKS -> "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു?"
        FINDING_RIDES_NEAR_YOU -> "നിങ്ങളുടെ അടുത്തുള്ള റൈഡുകൾ കണ്ടെത്തുന്നു ..."
        CONFIRMING_THE_RIDE_FOR_YOU -> "നിങ്ങൾക്കായി സവാരി സ്ഥിരീകരിക്കുന്നു ..."
        CANCEL_SEARCH -> "തിരയൽ റദ്ദാക്കുക"
        YOUR_RIDE_IS_NOW_COMPLETE -> "നിങ്ങളുടെ സവാരി ഇപ്പോൾ പൂർത്തിയായി!"
        PLEASE_PAY_THE_FINAL_AMOUNT_TO_THE_DRIVER_VIA_CASH -> "അവസാന തുക ഡ്രൈവർക്ക് നേരിട്ട് നൽകുക"
        WHERE_TO -> "പോകേണ്ട സ്ഥലം"
        HOME -> "വീട്"
        PICK_UP_LOCATION -> "പിക്കപ്പ് ലൊക്കേഷൻ"
        REQUEST_RIDE -> "റൈഡ് അഭ്യർത്ഥിക്കുക"
        NAME -> "പേര്"
        MOBILE_NUMBER_STR -> "മൊബൈൽ നമ്പർ"
        PERSONAL_DETAILS -> "പ്രൊഫൈൽ"
        YOUR_RIDES -> "നിങ്ങളുടെ റൈഡുകൾ"
        YOU_ARE_OFFLINE -> "നിങ്ങൾ ഓഫ്ലൈനാണ്"
        CHECK_YOUR_INTERNET_CONNECTION_AND_TRY_AGAIN -> "നിങ്ങളുടെ ഇന്റർനെറ്റ് കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക"
        TRY_AGAIN -> "വീണ്ടും ശ്രമിക്കുക"
        THANK_YOUR_DRIVER -> "ഡ്രൈവറോട് നന്ദി രേഖപ്പെടുത്തുക!"
        HOPE_YOUR_RIDE_WAS_HASSLE_FREE -> "നിങ്ങളുടെ യാത്ര തടസ്സരഹിതമായിരുന്നുവെന്ന് പ്രതീക്ഷിക്കുന്നു"
        HOW_WAS_YOUR_RIDE_WITH -> "നിങ്ങളുടെ സവാരി എങ്ങനെ ഉണ്ടായിരുന്നു"
        GOT_IT_TELL_US_MORE -> "ഓക്കേ, കൂടുതൽ പറയാൻ ആഗ്രഹിക്കുന്നുവോ?"
        WRITE_A_COMMENT -> "ഒരു അഭിപ്രായം എഴുതുക (ഓപ്ഷണൽ)"
        UPDATE -> "അപ്ഡേറ്റ് ചെയ്യുക"
        LANGUAGE -> "ഭാഷ"
        OTP -> "OTP"
        PAYMENT_METHOD -> "പണമടയ്ക്കൽ രീതി"
        PAYMENT_METHOD_STRING -> "പണം / UPI ആപ്പ് ഉപയോഗിക്കുക"
        PAYMENT_METHOD_STRING_ -> "പണം / UPI ആപ്പ് ഉപയോഗിക്കുക"
        CANCEL_RIDE -> "എന്റെ റൈഡ് റദ്ദാക്കുക"
        REQUEST_EDIT -> "തിരുത്തൽ അഭ്യർത്ഥിക്കുക"
        SUPPORT -> "സപ്പോർട്ട്"
        PICKUP_AND_DROP -> "പിക്കപ്പ്, ഡ്രോപ്പ്"
        CANCELLED -> "റദ്ദാക്കി"
        HOW_THE_PRICING_WORKS -> "വിലനിർണ്ണയം എങ്ങനെ പ്രവർത്തിക്കുന്നു?"
        SELECT_AN_OFFER -> "ഒരു ഓഫർ തിരഞ്ഞെടുക്കുക"
        CHOOSE_A_RIDE_AS_PER_YOUR_COMFORT -> "നിങ്ങളുടെ സൗകര്യത്തിനനുസരിച്ച് ഒരു റൈഡ് തിരഞ്ഞെടുക്കുക "
        IT_SEEMS_TO_BE_A_VERY_BUSY_DAY -> "വളരെ തിരക്കുള്ള ദിവസമാണെന്ന് തോന്നുന്നു. നിങ്ങൾക്ക് വീണ്ടും റൈഡുകൾ തിരയാൻ ശ്രമിക്കാം"
        SORT_BY -> "ക്രമത്തിൽ അടുക്കുക"
        SORRY_WE_COULDNT_FIND_ANY_RIDES -> "ക്ഷമിക്കണം, ഞങ്ങൾക്ക് ഒരു റൈഡുകളും കണ്ടെത്താൻ കഴിഞ്ഞില്ല"
        LOAD_MORE -> "കൂടുതൽ ലോഡുചെയ്യുക"
        WE_NEED_ACCESS_TO_YOUR_LOCATION -> "ഞങ്ങൾക്ക് നിങ്ങളുടെ ലൊക്കേഷനിലേക്ക് ആക്സസ് ആവശ്യമാണ്!"
        CALL -> "കാൾ"
        EMPTY_RIDES -> "റൈഡുകൾ ഇതുവരെ ഇല്ല"
        YOU_HAVENT_TAKEN_A_TRIP_YET -> "നിങ്ങൾ ഇതു വരെ ഒരു യാത്രയും നടത്തിയിട്ടില്ല"
        BOOK_NOW -> "ബുക്ക് ചെയ്യുക"
        T_AND_C_A -> "എ) നിങ്ങൾ ബീറ്റ ടെസ്റ്റിന് പങ്കെടുക്കാൻ സമ്മതം രേഖപെടുത്തുന്നു. ജസ്പേയ്ക്ക് യാതൊരു വിധ ബാധ്യതയുമില്ലെന്ന് നിങ്ങൾ സമ്മതിക്കുന്നു"
        TERMS_AND_CONDITIONS -> "ടി & സി"
        DATA_COLLECTION_AUTHORITY -> "സി) എന്റെ വിവരങ്ങൾ ശേഖരിക്കുന്നതിനും തുടരുന്നതിലൂടെയും ഞാൻ ഇതിനാൽ ജസ്റ്റ്പേയെ നിയമിക്കുകയും അംഗീകാരം നൽകുകയും ചെയ്യുന്നു, ഉപയോഗ നിബന്ധനകളും സ്വകാര്യതാ നയവും ഞാൻ അംഗീകരിക്കുന്നു."
        DENY_ACCESS -> "പ്രവേശനം നിഷേധിക്കുക"
        PLEASE_TELL_US_WHY_YOU_WANT_TO_CANCEL -> "എന്തുകൊണ്ടാണ് നിങ്ങൾ റദ്ദാക്കാൻ ആഗ്രഹിക്കുന്നതെന്ന് ഞങ്ങളോട് പറയുക"
        MANDATORY -> "നിർബന്ധമാണ്"
        SOFTWARE_LICENSE -> "സോഫ്റ്റ്വെയർ ലൈസൻസ്"
        LOGOUT_ -> "ലോഗൗട്ട്"
        REQUEST_AUTO_RIDE _-> "ഓട്ടോ റൈഡ് അഭ്യർത്ഥിക്കുക"
        RATE_YOUR_RIDE -> "നിങ്ങളുടെ സവാരി റേറ്റുചെയ്യുക"
        SKIP -> "ഒഴിവാക്കുക"
        ERROR_404 -> "എറർ 404"
        PROBLEM_AT_OUR_END -> "ഞങ്ങളുടെ ഭാഗത്ത് ഒരു പ്രശ്നമുണ്ടെന്ന് തോന്നുന്നു. പ്രശ്നം പരിഹരിക്കപ്പെടുമ്പോൾ അറിയിക്കപ്പെടുക"
        NOTIFY_ME -> "എന്നെ അറിയിക്കു"
        ADDRESS -> "വിലാസം"
        CHANGE -> "മാറ്റുക"
        SAVE_AS -> "ഈ പേരിൽ  സേവ് ചെയ്യുക"
        ADD_TAG -> "ടാഗ് ചേർക്കുക"
        WORK -> "ജോലിസ്ഥലം"
        OTHER -> "മറ്റേതായ"
        SAVE -> "സേവ് ചെയ്യുക"
        ADD_NEW_ADDRESS -> "പുതിയ വിലാസം ചേർക്കുക"
        SAVED_ADDRESSES -> "വിലാസങ്ങൾ സേവ് ചെയ്യുക"
        ADDRESSES -> "വിലാസങ്ങൾ"
        NO_FAVOURITES_SAVED_YET -> "ഫേവറൈറ്സ് ഒന്നും സേവ് ചെയ്തിട്ടില്ല"
        SAVED_ADDRESS_HELPS_YOU_KEEP_YOUR_FAVOURITE_PLACES_HANDY -> "നിങ്ങൾ പതിവായി സന്ദർശിക്കുന്ന സ്ഥലങ്ങിലേക്കു എളുപ്പത്തിൽ റൈഡ് ബുക്ക് ചെയ്യുവാനായി ഫേവറൈറ്സ് സഹായിക്കുന്നു"
        COPIED -> "പകർന്നു"
        TRIP_ID -> "യാത്രാ ഐഡി"
        SAVE_PLACE -> "ഈ സ്ഥലം സേവ് ചെയ്യുക"
        RIDE_FARE -> "സവാരി നിരക്ക്"
        ASK_FOR_PRICE -> "ഒരു വില ആവശ്യപ്പെടുക"
        ASK_FOR_PRICE_INFO -> "<B> സർക്കാർ നിശ്ചയിച്ച വിലയെ അടിസ്ഥാനമാക്കിയുള്ള ഒരു നിരക്ക് നിങ്ങൾക്ക് ലഭിക്കും, കൂടെ ഡ്രൈവർ സഞ്ചരിക്കുന്ന പിക്ക്-അപ്പ് ദൂരത്തിന് 10 രൂപ ചാർജ് ഈടാക്കും. ഗതാഗത കുരുക്ക്, റിട്ടേൺ ട്രിപ്പ് കിട്ടാനുള്ള സാധ്യത എന്നിങ്ങനെ ഉള്ള കാര്യങ്ങളെ ആസ്പദമാക്കി ചില ഡ്രൈവർമാർ നാമമാത്രമായ ടിപ്സ് ആവശ്യപ്പെട്ടേക്കാം."
        GET_ESTIMATE_FARE -> "എസ്റ്റിമേറ്റ് നിരക്ക് നേടുക"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS -> "ഒരു ഓഫർ തിരഞ്ഞെടുക്കുക (ഓപ്ഷണൽ)"
        SELECT_AN_OFFER_FROM_OUR_DRIVERS_INFO -> "റൈഡ് ഓട്ടോ അസൈൻ ചെയ്യുമ്പോൾ, എസ്റ്റിമേറ്റ് പരിധിക്കുള്ളിൽ ആദ്യം അഭ്യർത്ഥന സ്വീകരിക്കുന്ന ഒരു ഡ്രൈവറെ നിങ്ങൾക്ക് നിയോഗിക്കും. പകരം, നിങ്ങൾ ഒരു ഡ്രൈവർ ഓഫർ തിരഞ്ഞെടുക്കാൻ ആഗ്രഹിക്കുന്നുവെങ്കിൽ, നിങ്ങൾക്ക് ഓട്ടോ അസൈൻ വേണ്ടെന്നു വെയ്ക്കാം."
        PAY_THE_DRIVER -> "ഡ്രൈവർക്ക് പണം നൽകുക"
        PAY_THE_DRIVER_INFO -> "നിങ്ങൾ സ്ഥിരീകരിച്ച നിരക്ക് ഡ്രൈവർക്ക് നേരിട്ട് നൽകുക"
        PAY_THE_DRIVER_NOTE -> "റൈഡ് ദൂരം മാറിയാൽ മൊത്തം നിരക്കിൽ മാറ്റം വന്നേക്കാം)"
        UPDATE_PERSONAL_DETAILS -> "വ്യക്തിഗത വിശദാംശങ്ങൾ അപ്ഡേറ്റുചെയ്യുക"
        EDIT -> "എഡിറ്റ്"
        DEL_ACCOUNT -> "അക്കൗണ്ട് ഡിലീറ്റ് ചെയ്യുക"
        ACCOUNT_DELETION_CONFIRMATION -> "നിങ്ങളുടെ അക്കൗണ്ട് ഡിലീറ്റ് ചെയ്യണമെന്ന് തീർച്ചയാണോ? നിങ്ങളുടെ എല്ലാ സ്വകാര്യ ഡാറ്റയും നഷ്ടപ്പെടും"
        REQUEST_SUBMITTED -> "അഭ്യർത്ഥന സമർപ്പിച്ചു"
        WE_WILL_DELETE_YOUR_ACCOUNT -> "നിങ്ങൾ ഞങ്ങളുടെ പ്ലാറ്റ്‌ഫോം വിട്ടുപോകുന്നതിൽ ഞങ്ങൾക്ക് ഖേദമുണ്ട്. അടുത്ത 30 ദിവസത്തിനുള്ളിൽ നിങ്ങളുടെ അക്കൗണ്ട് ഇല്ലാതാക്കപ്പെടും. അതേസമയം, നിങ്ങളുടെ അക്കൗണ്ട് നിലനിർത്താൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുവെങ്കിൽ, ഞങ്ങളുടെ ഉപഭോക്തൃ പിന്തുണ നമ്പറിലേക്ക് വിളിക്കുക"
        YES_DELETE_IT -> "അതെ, ഡിലീറ്റ് ചെയ്യുക"
        REQUEST_TO_DELETE_ACCOUNT -> "അക്കൗണ്ട് ഡിലീറ്റ് ചെയ്യാനുള്ള അഭ്യർത്ഥന"
        CANCEL_STR -> "റദ്ദാക്കുക"
        LOADING -> "ലോഡിംഗ്"
        PLEASE_WAIT_WHILE_IN_PROGRESS -> "പുരോഗമിക്കുമ്പോൾ ദയവായി കാത്തിരിക്കുക"
        SET_LOCATION_ON_MAP -> "മാപ്പിൽ ലൊക്കേഷൻ ഉറപ്പിക്കുക"
        CURRENT_LOCATION -> "ഇപ്പോഴുള്ള സ്ഥലം"
        PREVIOUS_FARE -> "പഴയ നിരക്ക്"
        FARE_UPDATED -> "നിരക്ക് പുതുക്കി"
        PREVIOUSLY -> "മുമ്പ്"
        PLEASE_CONFIRM_WITH_YOUR_AFTER_REQUESTING -> "അഭ്യർത്ഥിച്ച ശേഷം ദയവായി ഡ്രൈവറുമായി സ്ഥിരീകരിക്കുക"
        ROUTE_AND_FARE_UPDATED -> "പരിഷ്കരിച്ച മാർഗ്ഗവും നിരക്കും"
        YOUR_DRIVER_MIGHT_WANT_TO_GO_TOWARDS_THE_CURRENT_DROP_KINDLY_ASK_THEM_TO_CONFIRM_AFTER_REQUESTING -> "നിങ്ങളുടെ ഡ്രൈവർ നിലവിലെ ഡ്രോപ്പിലേക്ക് പോകാൻ ആഗ്രഹിക്കാം. അഭ്യർത്ഥിച്ച ശേഷം ദയവായി അവരോട് സ്ഥിരീകരിക്കാൻ പറയുക"
        ACTUAL_FARE_WAS_HIGHER_THAN_WHAT_WAS_SHOWN -> "യഥാർത്ഥ നിരക്ക് കാണിച്ചതിനേക്കാൾ കൂടുതലായിരുന്നു."
        DELETE -> "ഡിലീറ്റ്"
        ARE_YOU_SURE_YOU_WANT_TO_LOGOUT -> "നിങ്ങൾ ലോഗൗട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?"
        ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "റദ്ദാക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?"
        YOU_HAVE_RIDE_OFFERS_ARE_YOU_SURE_YOU_WANT_TO_CANCEL -> "നിങ്ങൾക്ക് റൈഡ് ഓഫറുകൾ ഉണ്ട്, നിങ്ങൾ റദ്ദാക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?"
        GO_BACK_ -> "മടങ്ങിപ്പോവുക"
        REGISTER_USING_DIFFERENT_NUMBER -> "മറ്റൊരു മൊബൈൽ നമ്പർ ഉപയോഗിച്ച് രജിസ്റ്റർ ചെയ്യാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?"
        YES -> "സമ്മതം"
        NO -> "ഇല്ല"
        CANCEL_ -> "റദ്ദാക്കുക"
        IS_ON_THE_WAY -> "വന്നുകൊണ്ടിരിക്കുകയാണ്"
        ENTER_4_DIGIT_OTP -> "4 അക്ക OTP നൽകുക"
        WRONG_OTP -> "തെറ്റായ OTP"
        GRANT_ACCESS -> "ഗ്രാന്റ് ആക്സസ്"
        ENTER_A_LOCATION -> "ഒരു ലൊക്കേഷൻ എന്റർ ചെയ്യുക"
        NEARBY -> "അടുത്തുള്ള"
        MINS_AWAY -> "മിനിറ്റ് അകലെ"
        PAID -> "തുക അടച്ചു"
        BY_CASH -> "പണമായി"
        ONLINE_ -> "ഓൺലൈൻ"
        USER -> "ഉപയോക്താവ്"
        EMAIL_ALREADY_EXISTS -> "ഇമെയിൽ അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു. ഇമെയില് നേരത്തെ ഉള്ളതാണ്."
        IN -> "... ഇല്"
        VERIFYING_OTP -> "OTP പരിശോധിക്കുന്നു"
        TRACK_LIVE_LOCATION_USING -> "ഉപയോഗിച്ച് തത്സമയ സ്ഥാനം ട്രാക്കുചെയ്യുക"
        GOOGLE_MAP_ -> "ഗൂഗിൾ മാപ്പ്"
        IN_APP_TRACKING -> "അപ്പിനുള്ളിലൂടെയുള്ള ട്രാക്കിംഗ്"
        GETTING_ESTIMATES_FOR_YOU -> "വിലനിരക്ക് നിർണയിക്കുന്നു ..."
        GETTING_REVISED_ESTIMATE -> "പരിഷ്കരിച്ച വിലയിരുത്തൽ നേടുന്നു"
        CONFIRM_PICKUP_LOCATION -> "പിക്കപ്പ് സ്ഥിരീകരിക്കുക"
        CONFIRM_DROP_LOCATION -> "ഡ്രോപ്പ് സ്ഥാനം സ്ഥിരീകരിക്കുക"
        CHECK_REVISED_FARE_AND_ROUTE -> "പരിഷ്കരിച്ച നിരക്കും മാർഗ്ഗവും പരിശോധിക്കുക"
        ERROR_OCCURED_TRY_AGAIN -> "പിശക് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക"
        ASKED_FOR_MORE_MONEY -> "കൂടുതൽ പണം ആവശ്യപ്പെട്ടു"
        START_ -> "ആരംഭം"
        RIDE_NOT_SERVICEABLE -> "റൈഡ് സേവനയോഗ്യമല്ല"
        APP_NOT_SERVICEABLE -> "ആപ്പ് സേവനയോഗ്യമല്ല"
        CONFIRM_FOR -> "സ്ഥിരീകരിക്കുക"
        ETA_WAS_TOO_SHORT -> "ETA വളരെ ചെറുതായിരുന്നു."
        DRIVER_REQUESTED_TO_CANCEL -> "റദ്ദാക്കാൻ ഡ്രൈവർ എന്നോട് അഭ്യർത്ഥിച്ചു"
        PICK_UP_LOCATION_INCORRECT -> "പിക്കപ്പ് സ്ഥാനം തെറ്റാണ്."
        COULD_NOT_CONNECT_TO_DRIVER -> "എനിക്ക് ഡ്രൈവറുമായി ബന്ധപ്പെടാൻ കഴിഞ്ഞില്ല."
        ETA_WAS_TOO_LONG -> "ETA വളരെ ദൈർഘ്യമേറിയതായിരുന്നു."
        OTHERS -> "മറ്റുള്ളവ"
        DESTINATION_OUTSIDE_LIMITS -> "നൽകിയ ലക്ഷ്യസ്ഥാനം സിറ്റി പരിധിക്ക് പുറത്താണ്"
        DROP_LOCATION_FAR_AWAY -> "നിങ്ങളുടെ ഡ്രോപ്പ് സ്ഥാനം വളരെ അകലെയാണ്"
        CHANGE_DROP_LOCATION -> "ഡ്രോപ്പ് സ്ഥാനം മാറ്റുക"
        YOU_CAN_TAKE_A_WALK_OR_CONTINUE_WITH_RIDE_BOOKING -> "നിങ്ങൾ നടന്നു പോകുകയോ അല്ലെങ്കിൽ റൈഡ് ബുക്കിംഗ് തുടരുകയോ ചെയ്യാം"
        YOUR_TRIP_IS_TOO_SHORT_YOU_ARE_JUST -> "നിങ്ങളുടെ യാത്ര ദൂരം വളരെ ചെറുതാണ്. ലക്ഷ്യസ്ഥാനം വെറും"
        METERS_AWAY_FROM_YOUR_DESTINATION -> "m അകലെ!"
        BOOK_RIDE_ -> "റൈഡ് ബുക്ക് ചെയ്യുക"
        CANCEL_AUTO_ASSIGNING -> "ഓട്ടോ അസൈൻ ചെയ്യുന്നത് റദ്ദാക്കുക"
        LOCATION_UNSERVICEABLE -> "ലൊക്കേഷൻ ഉപയോഗയോഗ്യമല്ല"
        CURRENTLY_WE_ARE_LIVE_IN_ _  -> "ഞങ്ങൾ ഇതുവരെ നിങ്ങളുടെ പ്രദേശത്ത് താമസിക്കുന്നില്ല!\nനിങ്ങൾക്ക് മെനുവിൽ നിന്ന് റൈഡ് ചരിത്രവും മറ്റ് ക്രമീകരണങ്ങളും ആക്‌സസ് ചെയ്യാൻ കഴിയും"
        CHANGE_LOCATION -> "സ്ഥാനം മാറ്റുക"
        AUTO_ACCEPTING_SELECTED_RIDE -> "ഓട്ടോമാറ്റിക്കായി ഉറപ്പിക്കുന്നു"
        THE_TRIP_IS_VERY_SHORT_AND_JUST_TAKE -> "യാത്ര വളരെ ചെറുതാണ്, മാത്രമല്ല"
        IF_YOU_STILL_WANNA_BOOK_RIDE_CLICK_CONTINUE_AND_START_BOOKING_THE_RIDE -> "നിങ്ങൾക്ക് ഇപ്പോഴും ബുക്ക് ചെയ്യണമെങ്കിൽ തുടരുക ക്ലിക്കുചെയ്ത് സവാരി ബുക്ക് ചെയ്യാൻ ആരംഭിക്കുക"
        STEPS_TO_COMPLETE -> "പൂർത്തിയാക്കാനുള്ള ഘട്ടങ്ങൾ"
        HELP_US_WITH_YOUR_REASON -> "കാരണം രേഖപ്പെടുത്തി ഞങ്ങളെ സഹായിക്കൂ"
        MAX_CHAR_LIMIT_REACHED -> "അക്ഷരങ്ങളുടെ പരിധി എത്തിയിരിക്കുന്നു,"
        DRIVER_WAS_NOT_REACHABLE -> "ഡ്രൈവറെ ബന്ധപ്പെടാനായില്ല"
        SHOW_ALL_OPTIONS -> "എല്ലാ ഓപ്ഷനുകളും കാണിക്കുക"
        EXPIRES_IN -> "കാലഹരണപ്പെടും"
        PAY_DIRECTLY_TO_YOUR_DRIVER_USING_CASH_UPI -> "*ക്യാഷ്/യുപിഐ ഉപയോഗിച്ച് നിങ്ങളുടെ ഡ്രൈവർക്ക് നേരിട്ട് പണം നൽകുക"
        UPDATE_REQUIRED -> "അപ്ഡേറ്റ് ആവശ്യമാണ്"
        PLEASE_UPDATE_APP_TO_CONTINUE_SERVICE -> "ഞങ്ങളുടെ ആപ്പിനായി ഒരു പുതിയ അപ്‌ഡേറ്റ് ലഭ്യമാണെന്ന് അറിയിക്കുന്നതിൽ ഞങ്ങൾക്ക് സന്തോഷമുണ്ട്. ഈ അപ്‌ഡേറ്റിൽ നിങ്ങളുടെ അനുഭവം കൂടുതൽ മികച്ചതാക്കുന്നതിന് പുതിയ ഡിസൈനും നിരവധി പുതിയ ഫീച്ചറുകളും ഉൾപ്പെടുന്നു"
        NOT_NOW -> "ഇപ്പോൾ വേണ്ട"
        OF -> "ന്റെ"
        LOST_SOMETHING -> "എന്തെങ്കിലും നഷ്ടപ്പെട്ടോ?"
        TRY_CONNECTING_WITH_THE_DRIVER -> "നിങ്ങൾക്ക് ഡ്രൈവറിൽ നിന്ന് ഒരു കോൾബാക്ക് അഭ്യർത്ഥിക്കാം"
        CALL_DRIVER -> "ഡ്രൈവറെ വിളിക്കുക"
        NO_MORE_RIDES -> "ഇതിൽ കൂടുതൽ റൈഡുകൾ നിലവിൽ ഇല്ല"
        CONTACT_SUPPORT -> "സപ്പോർട്ട് ടീമുമായി ബന്ധപെടുക"
        INVALID_MOBILE_NUMBER -> "അസാധുവായ മൊബൈൽ നമ്പർ"
        RIDE_COMPLETED -> "സവാരി പൂർത്തിയായി"
        SUBMIT_FEEDBACK -> "സമർപ്പിക്കുക"
        HOW_WAS_YOUR_RIDE_EXPERIENCE -> "നിങ്ങളുടെ റൈഡ് അനുഭവം എങ്ങനെയുണ്ടായിരുന്നു?"
        DROP -> "ഡ്രോപ്പ്"
        RATE_YOUR_RIDE_WITH -> "ഉപയോഗിച്ച് നിങ്ങളുടെ യാത്ര റേറ്റുചെയ്യുക"
        VIEW_BREAKDOWN -> "വിഘടിച്ചു കാണുക"
        PAY_DRIVER_USING_CASH_OR_UPI -> "ക്യാഷ്/യുപിഐ ഉപയോഗിച്ച് ഡ്രൈവർക്ക് പണം നൽകുക"
        PAY_DRIVER_USING_CASH_OR_UPI_ -> "ക്യാഷ്/യുപിഐ ഉപയോഗിച്ച് ഡ്രൈവർക്ക് പണം നൽകുക"
        RATE_YOUR_DRIVER -> "റേറ്റ് ചെയ്യുക"
        MY_RIDES -> "എന്റെ റൈഡുകൾ"
        RIDE_DETAILS -> "റൈഡിന്റെ വിശദാംശങ്ങൾ"
        RIDE_ID -> "റൈഡ് ഐഡി"
        SELECT_A_RIDE -> "ഒരു സവാരി തിരഞ്ഞെടുക്കുക"
        CONFIRM_RIDE_ -> "സവാരി സ്ഥിരീകരിക്കുക"
        YOU_CAN_CANCEL_RIDE -> "ഡ്രൈവർമാരിൽ നിന്ന് ഓഫർ ലഭിച്ചുകഴിഞ്ഞാൽ നിങ്ങൾക്ക് റദ്ദാക്കാം"
        ESTIMATES_CHANGED -> "നിങ്ങളുടെ റൈഡിന്റെ എസ്റ്റിമേറ്റ് ഇപ്പോൾ മാറിയിരിക്കുന്നു"
        ESTIMATES_REVISED_TO -> "പുതുക്കിയ എസ്റ്റിമേറ്റ്"
        RATE_CARD -> "റേറ്റ് കാർഡ്"
        NIGHT_TIME_CHARGES from till -> "രാത്രികാല ചാർജുകൾ"
        MIN_FARE_UPTO val -> "നിരക്ക് " <> val <> " വരെ"
        MORE_THAN  -> "കിലോമീറ്ററിലധികം"
        RATE_ABOVE_MIN_FARE -> "മിനിമം നിരക്കിന് മുകളിലുള്ള നിരക്ക്"
        DRIVER_PICKUP_CHARGES _ -> "ഡ്രൈവർ പിക്കപ്പ് നിരക്കുകൾ"
        NOMINAL_FARE -> "നാമമാത്ര നിരക്ക്*"
        CUSTOMER_CANCELLATION_DUES -> "കുടിശ്ശിക റദ്ദാക്കൽ"
        DAYTIME_CHARGES_APPLICABLE_AT_NIGHT from till -> "പകൽ സമയ നിരക്കുകൾ, രാത്രിയിൽ ബാധകമാണ് - "<> from <> " മുതൽ " <> till <> "വരെ"
        DRIVERS_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC -> "* ഗതാഗത കുരുക്ക്, റിട്ടേൺ ട്രിപ്പ് കിട്ടാനുള്ള സാധ്യത എന്നിങ്ങനെ ഉള്ള കാര്യങ്ങളെ ആസ്പദമാക്കി ഡ്രൈവർ ഒരു നാമമാത്ര തുക അധികമായി ക്വോട്ട് ചെയ്തേക്കാം."
        GOT_IT -> "മനസ്സിലായി!"
        DAY_TIME_CHARGES from till -> "പകൽ നിരക്കുകൾ"
        SHARE_APP -> "ആപ്പ് ഷെയർ ചെയ്യുക"
        AWAY_C -> "ദൂരെ"
        AWAY -> "ദൂരെ"
        AT_PICKUP -> "പിക്കപ്പ് ലൊക്കേഷനിൽ"
        FARE_HAS_BEEN_UPDATED -> "നിരക്ക് മാറി"
        AT_DROP -> "ഡ്രോപ്പ് ലൊക്കേഷനിൽ"
        EMERGENCY_HELP -> "അടിയന്തര സഹായം"
        ALSO_SHARE_YOUR_RIDE_STATUS_AND_LOCATION -> "കൂടാതെ, നിങ്ങളുടെ റൈഡിന്റെ  സ്റ്റാറ്റസും ലൊക്കേഷനും പങ്കിടപെടും"
        SHARE_RIDE_WITH_EMERGENCY_CONTACTS -> "അടിയന്തിര കോണ്ടാക്ടുമായി റൈഡ് വിവരം പങ്കിടുക"
        DO_YOU_NEED_EMERGENCY_HELP -> "നിങ്ങൾക്ക് അടിയന്തിര സഹായം ആവശ്യമുണ്ടോ?"
        CALL_SUPPORT -> "സപ്പോർട്ട് ടീമിനെ വിളിക്കുക"
        YOU_ARE_ABOUT_TO_CALL_NAMMA_YATRI_SUPPORT _  -> "നിങ്ങൾ നമ്മ യാത്രി സപ്പോർട്ട് ടീമിനെ കാൾ ചെയ്യാൻ പോകുകയാണ്. തുടരണോ?"
        YOU_ARE_ABOUT_TO_CALL_NEAREST_EMERGENCY_CENTRE -> "നിങ്ങൾ അടുത്തുള്ള എമർജൻസി സെന്ററിലേക്ക് വിളിക്കാൻ പോകുകയാണ്. നിങ്ങൾക്ക് തുടരണോ?"
        DIAL_112 -> "112 ഡയൽ ചെയ്യണോ"
        HELP_US_WITH_YOUR_FEEDBACK_OPTIONAL -> "നിങ്ങളുടെ പ്രതികരണം  രേഖപ്പെടുത്തി ഞങ്ങളെ സഹായിക്കൂ (ഓപ്ഷണൽ)"
        WAIT_TIME -> "കാത്തിരിപ്പ്"
        FAVOURITES -> "ഫേവറൈറ്സ്"
        ADD_FAVOURITE -> "ഫേവറൈറ് ചേർക്കുക"
        ALL_FAVOURITES -> "ഫേവറിറ്റ്സ്"
        REMOVE -> "നീക്കംചെയ്യുക"
        CONFIRM_LOCATION -> "ലൊക്കേഷൻ സ്ഥിരീകരിക്കുക"
        SELECT_ON_MAP -> "മാപ്പിൽ തിരഞ്ഞെടുക്കുക"
        FAVOURITE_LOCATION -> "ഫേവറൈറ് സ്ഥലം  "
        EDIT_FAVOURITE -> "ഫേവറൈറ് എഡിറ്റു ചെയ്യുക"
        DRAG_THE_MAP -> "മാപ്പ് നീക്കുക"
        CHOOSE_ON_MAP -> "മാപ്പിൽ തിരഞ്ഞെടുക്കുക"
        USE_CURRENT_LOCATION -> "നിലവിലെ ലൊക്കേഷൻ ഉപയോഗിക്കുക"
        FAVOURITE_YOUR_CURRENT_LOCATION -> "നിങ്ങളുടെ നിലവിലെ ലൊക്കേഷൻ ഫേവറൈറ് ആക്കുക"
        LOCATION -> "ലൊക്കേഷൻ"
        LOCATION_ALREADY_EXISTS_AS -> "ലൊക്കേഷൻ നിലവിൽ ഈ പേരിൽ ഉണ്ട്: "
        GIVE_THIS_LOCATION_A_NAME -> "ഈ ലൊക്കേഷന് ഒരു പേര് നൽകുക"
        FAVOURITE -> "ഫേവറൈറ്"
        CONFIRM_AND_SAVE -> "സ്ഥിരീകരിച്ചു സേവ് ചെയ്യുക"
        REMOVE_FAVOURITE -> "ഫേവറൈറ് നീക്കംചെയ്യുക"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_FAVOURITE_ -> " ഫേവറൈറ് നീക്കം ചെയ്യാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?"
        YES_REMOVE -> "നീക്കം ചെയ്യുക"
        ADD_NEW_FAVOURITE -> "പുതിയ ഫേവറൈറ് ചേർക്കുക"
        SELECT_YOUR_DROP -> "നിങ്ങളുടെ ഡ്രോപ്പ് സ്ഥാനം തിരഞ്ഞെടുക്കുക"
        FAVOURITE_REMOVED_SUCCESSFULLY -> "ഫേവറൈറ് വിജയകരമായി നീക്കംചെയ്തു"
        LOCATION_ALREADY_EXISTS -> "ലൊക്കേഷൻ നിലവിലുണ്ട്"
        LOCATION_ALREADY -> "ലൊക്കേഷൻ നിലവിൽ"
        EXISTS_AS -> "ഈ പേരിൽ ഉണ്ട്: "
        FAVOURITE_ADDED_SUCCESSFULLY -> "ഫേവറൈറ് വിജയകരമായി ചേർത്തു"
        FAVOURITE_UPDATED_SUCCESSFULLY -> "ഫേവറൈറ് വിജയകരമായി അപ്ഡേറ്റു ചെയ്തു"
        ALREADY_EXISTS -> " നിലവിൽ സ്ഥിതി ചെയ്യുന്നു"
        NAME_ALREADY_IN_USE -> "പേര് നിലവിൽ ഉപയോഗത്തിലുണ്ട്"
        SELECT_FAVOURITE -> "ഫേവറൈറ് തിരഞ്ഞെടുക്കുക"
        CONFIRM_CHANGES -> "മാറ്റങ്ങൾ സ്ഥിരീകരിക്കുക"
        ADD_SAVED_LOCATION_FROM_SETTINGS -> "നിങ്ങൾക്ക് സൈഡ് മെനുവിൽ നിന്ന് ഫേവറൈറ്സ് ചേർക്കാൻ കഴിയും"
        YOU_WILL_BE_ASKED_TO_SELECT_CONTACTS -> "3 കോൺടാക്റ്റുകൾ വരെ തിരഞ്ഞെടുക്കാൻ നിങ്ങളോട് ആവശ്യപ്പെടും"
        AUTO_ASSIGN_A_RIDE -> "ഒരു റൈഡ് ഓട്ടോമാറ്റിക് ആയി അസൈൻ ചെയ്യുക "
        IS_WAITING_AT_PICKUP -> "എടുക്കാൻ കാത്തിരിക്കുന്നു"
        WAIT_TIME_TOO_LONG -> "ദൈർഖ്യം ഏറിയ കാത്തിരിപ്പു"
        GOT_ANOTHER_RIDE_ELSE_WHERE -> "മറ്റെവിടെ നിന്നോ വേറെ ഒരു റൈഡ് ലഭിച്ചു "
        DRIVER_WAS_RUDE -> "ഡ്രൈവർ അപമര്യാദയോടെ പെരുമാറി"
        MAYBE_LATER -> "ഒരുപക്ഷെ പിന്നീട്"
        YOUR_RIDE_HAS_STARTED -> "നിങ്ങളുടെ റൈഡ് ആരംഭിച്ചു"
        ENJOY_RIDING_WITH_US -> "ഞങ്ങളോടൊപ്പം റൈഡ് ചെയ്യുന്നത് ആസ്വദിക്കൂ"
        VIEW_DETAILS -> "കാണുക"
        REPEAT_RIDE -> "റിപീറ് റൈഡ് "
        FARE_WAS_HIGH -> "നിരക്ക് ഉയർന്നതായിരുന്നു"
        AUTO_ASSIGN_DRIVER -> "ഡ്രൈവറെ ഓട്ടോമാറ്റിക്കായി \n നിശ്ചയിക്കുക"
        CHOOSE_BETWEEN_MULTIPLE_DRIVERS -> "പല ഡ്രൈവർമാരിൽ \n നിന്നും തിരഞ്ഞെടുക്കുക"
        CHOOSE_BETWEEN_MULTIPLE_RIDES -> "ഒന്നിലധികം റൈഡുകളിൽ നിന്നും തിരഞ്ഞെടുക്കുക "
        ENABLE_THIS_FEATURE_TO_CHOOSE_YOUR_RIDE -> "നിങ്ങളുടെ ഇഷ്ടപ്രകാരമുള്ള റൈഡും നിരക്കും തിരഞ്ഞെടുക്കുന്നതിന് ഈ സവിശേഷത എനേബിൾ ചെയ്യുക"
        BOOKING_PREFERENCE -> "ബുക്കിംഗ് മുൻഗണന"
        BASE_FARES -> "അടിസ്ഥാന നിരക്ക്"
        PICKUP_CHARGE -> "പിക്കപ്പ് ചാർജുകൾ"
        TOTAL_PAID -> "ആകെ നൽകിയ പണം"
        WAITING_CHARGE -> "കാത്തിരിപ്പ് ചാർജുകൾ"
        DRIVERS_CAN_CHARGE_AN_ADDITIONAL_FARE_UPTO -> "* ഡ്രൈവർമാർക്ക് റിട്ടേൺ യാത്ര ലഭിക്കാനുള്ള സാധ്യത, ട്രാഫിക് തുടങ്ങിയ മറ്റ് ഘടകങ്ങൾ ഉൾകോള്ളിച്ചുകൊണ്ട് ₹20 വരെ കൂടുതൽ അഭ്യർത്ഥിക്കാം."
        WAITING_CHARGE_DESCRIPTION -> "°ആദ്യ {} മിനിറ്റിൽ വെയ്റ്റിംഗ് ചാർജ് പൂജ്യമാണ്. അതിനുശേഷം കാത്തിരിപ്പ് സമയത്തിന് ഒരു മിനിറ്റിന് ₹{} ഈടാക്കും."
        WAITING_CHARGE_RATECARD_DESCRIPTION waitingCharge freeWaitingTime -> "1. ആദ്യ 3 മിനിറ്റിൽ വെയിറ്റിംഗ് ചാർജ് പൂജ്യമാണ്.\n 2. ഒരു മിനിറ്റിന് ₹1.5 വെയിറ്റിംഗ് ചാർജ് അതിനുശേഷം ബാധകമാകും."
        WAITING_CHARGE_INFO waitingCharge freeWaitingTime -> "കാത്തിരിപ്പിന്റെ ആദ്യ "<> freeWaitingTime <>" മിനിറ്റിന് ശേഷം മിനിറ്റിന് "<>waitingCharge<>" ബാധകം"
        SUCCESSFUL_ONBOARD _ -> "നിങ്ങൾ വിജയകരമായി \n നമ്മ യാത്രിയിലേക്ക് പ്രവേശിച്ചിരിക്കുന്നു"
        HAVE_REFERRAL_CODE -> "റഫറൽ കോഡ് ഉണ്ടോ?"
        REFEREAL_CODE_DISCRIPTION -> "ഒരു ഡ്രൈവർക്ക് റഫറൽ പ്രതിഫലം ലഭിക്കാനുള്ള കാരണം ഒരുപക്ഷേ നിങ്ങൾ ആയേക്കാം!"
        SIX_DIGIT_REFERRAL_CODE -> "ഡ്രൈവർ പങ്കിട്ട 6 അക്ക കോഡ് നൽകുക"
        ABOUT_REFERRAL_PROGRAM -> "റഫറൽ പ്രോഗ്രാമിനെക്കുറിച്ച് കൂടുതലറിയുക"
        ABOUT_REFERRAL_PROGRAM_DISCRIPTION _ -> "യോഗ്യരായ ഡ്രൈവർമാരെ കണ്ടെത്തി അവരെ അഭിനന്ദിക്കുകയും, തക്ക പ്രതിഫലം നൽകുകയും അതിലൂടെ കൂടുതൽ റൈഡറുകൾ സ്വീകരിക്കാനും, ക്യാൻസല്ലേഷൻസ് കുറക്കാനും, അതുവഴി നിങ്ങളെ മെച്ചപ്പെട്ട രീതിയിൽ സേവിക്കുവാനും ഡ്രൈവർമാരെ പ്രോത്സാഹിപ്പിക്കുകയും ചെയ്യാൻ ഉതകുന്ന ഒരു പദ്ധതി ആണ് റഫറൽ പ്രോഗ്രാം. ഡ്രൈവറുടെ റെഫെറൽ കോഡ് എന്റർ ചെയ്യുന്നതിലൂടെ നിങ്ങൾക്കും, നമ്മ യാത്രി കൂട്ടായ്മയ്ക്ക് വേണ്ടി റൈഡ്കളുടെ നിലവാരം പൊതുവെ മെച്ചപ്പെടുത്താൻ സഹായിക്കാവുന്നതാണ്!"
        YOU_CAN_GET_REFERRAL_CODE_FROM_DRIVER _ -> "നിങ്ങളുടെ നമ്മ യാത്രി ഡ്രൈവറോട് ചോദിച്ചാൽ ഒരു റഫറൽ കോഡ് ലഭിക്കും."
        REFERRAL_CODE_SUCCESSFULL -> "നിങ്ങൾ റഫറൽ കോഡ് വിജയകരമായി ഉപയോഗിച്ചു"
        REFERRAL_CODE_APPLIED -> "റഫറൽ ഉപയോഗിച്ചു!"
        HEY -> "നമസ്കാരം"
        INVALID_CODE_PLEASE_RE_ENTER -> "തെറ്റായ കോഡ്. ദയവായി വീണ്ടും നൽകുക"
        LET_TRY_THAT_AGAIN -> "നമുക്ക് വീണ്ടും ശ്രമിക്കാം ..."
        EMERGENCY_CONTACTS -> "അടിയന്തര കോൺടാക്റ്റുകൾ"
        EDIT_EMERGENCY_CONTACTS -> "അടിയന്തര കോൺടാക്റ്റുകൾ എഡിറ്റു ചെയ്യുക"
        NO_EMERGENCY_CONTACTS_SET -> "അടിയന്തര കോൺടാക്‌റ്റുകളൊന്നും സജ്ജീകരിച്ചിട്ടില്ല"
        ADD_EMERGENCY_CONTACTS -> "അടിയന്തര കോൺടാക്റ്റുകൾ ചേർക്കുക"
        DAYTIME_CHARGES_APPLIED_AT_NIGHT percentage from till -> till <> " നും "<> from <>" വരെയുള്ള രാത്രി (🌙) ടൈംഫോനെയിലെ ചാര്‍ജുകളിലേക്ക് "<> percentage <>"x പ്രയോഗിക്കുന്നു"
        TOTAL_FARE_MAY_CHANGE_DUE_TO_CHANGE_IN_ROUTE -> "റൂട്ടിലെ മാറ്റം കാരണം മൊത്തം നിരക്ക് മാറിയേക്കാം"
        CONTACTS_SELECTED -> "കോൺടാക്റ്റുകൾ തിരഞ്ഞെടുത്തു"
        SELECT_CONTACTS -> "കോൺടാക്റ്റുകൾ തിരഞ്ഞെടുക്കുക"
        CONFIRM_EMERGENCY_CONTACTS -> "എമർജൻസി കോൺടാക്റ്റുകൾ സ്ഥിരീകരിക്കുക"
        ARE_YOU_SURE_YOU_WANT_TO_REMOVE_CONTACT -> "നിങ്ങളുടെ എമർജൻസി കോൺടാക്റ്റുകളിൽ നിന്ന് അവരെ നീക്കം ചെയ്യണമെന്ന് തീർച്ചയാണോ?"
        SEARCH_CONTACTS -> "കോൺടാക്റ്റുകൾ തിരയുക"
        CALL_EMERGENCY_CONTACTS -> "അടിയന്തര കോൺടാക്റ്റുകളെ വിളിക്കുക"
        LIVE_STATS_DASHBOARD -> "തത്സമയ സ്ഥിതിവിവരക്കണക്ക് ഡാഷ്‌ബോർഡ്"
        CHECK_OUT_LIVE_STATS -> "തത്സമയ സ്ഥിതിവിവരക്കണക്കുകൾ പരിശോധിക്കുക"
        ADD_ANOTHER_CONTACT -> "റ്റൊരു കോൺടാക്റ്റ് ചേർക്കുക"
        EMERGENCY_CONTACS_ADDED_SUCCESSFULLY -> "അടിയന്തര കോൺടാക്റ്റുകൾ വിജയകരമായി ചേർത്തു"
        NO_CONTACTS_LEFT_ON_DEVICE_TO_ADD -> "ചേർക്കാൻ ഉപകരണത്തിൽ കോൺടാക്‌റ്റുകളൊന്നും അവശേഷിക്കുന്നില്ല"
        PERCENTAGE_OF_NOMINAL_FARE -> "അടിസ്ഥാന നിരക്കിന്റെ ~10%"
        CHOOSE_YOUR_RIDE  -> "നിങ്ങളുടെ റൈഡ് തിരഞ്ഞെടുക്കുക"
        ECONOMICAL  -> "സാമ്പത്തിക"
        PEOPLE  -> "പേർ"
        CONFIRM_AND_BOOK  -> "സ്ഥിരീകരിച്ച് ബുക്ക് ചെയ്യുക"
        REQUEST_CALLBACK  -> "തിരികെ വിളിക്കാൻ അഭ്യർത്ഥിക്കുക"
        PAY_VIA_CASH_OR_UPI -> "പണം / യുപിഐ വഴി പണമടയ്ക്കുക"
        BOARD_THE_FIRST -> "യാത്രി സതി സോണിൽ നിന്നുള്ള ആദ്യ"
        TAXI  -> "ടാക്സിയിൽ" 
        AC  -> "എസി"
        NON_AC  -> "നോൺ-എസി"
        TAXI_FROM_ZONE _ -> "കയറുക"
        COMFY  -> "സുഖപ്രദമായ"
        NAVIGATE  -> "നാവിഗേറ്റ് ചെയ്യുക"
        GOVERNMENT_CHAGRES  -> "റൈഡ് ജിഎസ്ടി (5%)"
        SERVICE_CHARGES  -> "സേവന നിരക്കുകൾ"
        SPACIOUS  -> "വിശാലമായത്"
        CANCEL_ONGOING_SEARCH -> "ഇപ്പോൾ പുരോഗമിച്ചുകൊണ്ടിരിക്കുന്ന സെർച്ച് റദ്ദു ചെയ്യണമെന്ന് ഉറപ്പാണോ?"
        SEARCH_AGAIN_WITH_A_TIP -> "ടിപ്പ് ഉൾപ്പെടുത്തി സെർച്ച് ചെയ്യണമോ?"
        TRY_AGAIN_WITH_A_TIP -> "ടിപ്പ് ഉൾപ്പെടുത്തി വീണ്ടും ശ്രമിക്കണമോ?"
        BOOST_YOUR_RIDE_CHANCES_AND_HELP_DRIVERS_WITH_TIPS ->  "വളരെ തിരക്കുള്ള ദിവസമാണെന്ന് തോന്നുന്നു. യാത്ര ചെയ്യാനുള്ള സാധ്യത വർദ്ധിപ്പിക്കാൻ നിങ്ങൾക്ക് ഒരു നുറുങ്ങ് ചേർക്കാൻ ശ്രമിക്കാം."
        TRY_AGAIN_WITHOUT_TIP  -> "ടിപ്പ് ഉൾപ്പെടുത്താതെ വീണ്ടും ശ്രമിക്കുക"
        SEARCH_AGAIN_WITHOUT_A_TIP  -> "ടിപ്പ് ഉൾപ്പെടുത്താതെ വീണ്ടും തിരയുക"
        TRY_AGAIN_WITH  -> "വീണ്ടും ശ്രമിക്കുക:"
        SEARCH_AGAIN_WITH  -> "വീണ്ടും സെർച്ച് ചെയ്യുക:"
        TIP  -> "ടിപ്പ്"
        CUSTOMER_SELECTED_FARE  -> "കസ്റ്റമർ ടിപ്പ്^"
        START_YOUR_CHAT_USING_THESE_QUICK_CHAT_SUGGESTIONS  -> "ചുവടെ കാണുന്ന ക്വിക്ക് ചാറ്റ് ഓപ്ഷനുകൾ ഉപയോഗിച്ച് നിങ്ങൾക്കു ചാറ്റ് ആരംഭിക്കാവുന്നതാണ്" 
        MESSAGE  -> "സന്ദേശം"
        START_YOUR_CHAT_WITH_THE_DRIVER  -> "ഡ്രൈവറുമായി നിങ്ങളുടെ ചാറ്റ് ആരംഭിക്കുക"
        I_AM_ON_MY_WAY  -> "ഞാൻ എത്തിക്കൊണ്ടിരിക്കുകയാണ്"
        GETTING_DELAYED_PLEASE_WAIT  -> "ഞാൻ അല്പം വൈകും, ദയവായി കാത്തിരിക്കുക"
        UNREACHABLE_PLEASE_CALL_BACK  -> "പരിധിക്ക് പുറത്താണ്, ദയവായി തിരികെ വിളിക്കുക"
        ARE_YOU_STARING  -> "നിങ്ങൾ ആരംഭിക്കുകയാണോ?"
        PLEASE_COME_SOON  -> "ദയവായി വേഗം വരിക"
        OK_I_WILL_WAIT  -> "ഒക്കെ, ഞാൻ കാത്തിരിക്കാം"
        I_HAVE_ARRIVED  -> "ഞാൻ എത്തി"
        PLEASE_COME_FAST_I_AM_WAITING  -> "ദയവായി വേഗം വരിക, ഞാൻ കാത്തിരിക്കുകയാണ്"
        PLEASE_WAIT_I_WILL_BE_THERE  -> "ദയവായി കാത്തിരിക്കൂ, ഞാൻ അവിടെ ഉണ്ടാകും"
        LOOKING_FOR_YOU_AT_PICKUP  -> "പിക്കപ്പിൽ നിങ്ങളെ തിരയുന്നു"
        MOBILE  -> "മൊബൈൽ"
        HOW_DO_YOU_IDENTIFY_YOURSELF  -> "നിങ്ങളുടെ ലിംഗഭേദം തിരഞ്ഞെടുക്കുക"
        SELECT_YOUR_GENDER  -> "നിങ്ങളുടെ ലിംഗഭേദം തിരഞ്ഞെടുക്കുക"
        FEMALE  -> "സ്ത്രീ"
        MALE  -> "പുരുഷൻ"
        PREFER_NOT_TO_SAY  -> "പറയാൻ ആഗ്രഹിക്കുന്നില്ല"
        EMAIL_ID  -> "ഇമെയിൽ ഐഡി"
        SET_NOW  -> "സെറ്റ് ചെയ്യുക"
        ADD_NOW  -> "ആഡ് ചെയ്യുക "
        HOW_SHOULD_WE_ADDRESS_YOU  -> "താങ്കളെ എങ്ങനെ അഭിസംബോധന ചെയ്യണം?"
        GENDER_STR  -> "ലിംഗം"
        PROFILE_COMPLETION  -> "പ്രൊഫൈൽ പൂർത്തീകരണം"
        EARLY_END_RIDE_CHARGES  -> "യാത്ര നേരത്തെ അവസാനിപ്പിച്ചാൽ ബാധകമാകുന്ന നിരക്ക് "
        EARLY_END_RIDE_CHARGES_DESCRIPTION  -> "^ഒരു ട്രിപ്പ് നേരത്തെ അവസാനിപ്പിക്കുമ്പോൾ, ബാക്കിയായ ദൂരത്തിന്റെ പകുതി നിരക്ക് അധികമായി നൽകേണ്ടതുണ്ട് (പരമാവധി ₹50)"
        YES_TRY_AGAIN  -> "അതെ, വീണ്ടും ശ്രമിക്കുക"
        NO_DONT  -> "വേണ്ട"
        YES_CANCEL_SEARCH  -> "അതെ, സെർച്ച് റദ്ദാക്കുക"
        TRY_LOOKING_FOR_RIDES_AGAIN  -> "ഇന്നൊരു തിരക്കേറിയ ദിവസമാണെന്ന് തോന്നുന്നു. താങ്കൾക് വീണ്ടും റൈഡുകൾ തിരയാൻ ശ്രമിക്കാം"
        NO_TIP  -> "ടിപ്പ് ഇല്ല"
        CUSTOMER_TIP_DESCRIPTION  -> "^റൈഡ് ലഭിക്കാനുള്ള സാധ്യത വർധിപ്പിക്കാനായി ഉപഭോക്താവ് അധികമായി ചേർത്ത തുക."
        PLACE_CALL  -> "ഒരു കാൾ ചെയ്യുക"
        DIRECT_CALL  -> "നേരിട്ടുള്ള കോൾ"
        ANONYMOUS_CALL  -> "അജ്ഞാത കോൾ"
        YOUR_NUMBER_WILL_NOT_BE_SHOWN_TO_THE_DRIVER_THE_CALL_WILL_BE_RECORDED_FOR_COMPLIANCE  -> "നിങ്ങളുടെ നമ്പർ ഡ്രൈവർക്ക് കാണിക്കില്ല. കോൾ പാലിക്കുന്നതിനായി റെക്കോർഡ് ചെയ്യും."
        YOUR_NUMBER_WILL_BE_VISIBLE_TO_THE_DRIVER_USE_IF_NOT_CALLING_FROM_REGISTERED_NUMBER  -> "നിങ്ങളുടെ നമ്പർ ഡ്രൈവർക്ക് ദൃശ്യമാകും. രജിസ്റ്റർ ചെയ്ത നമ്പറിൽ നിന്ന് വിളിക്കുന്നില്ലെങ്കിൽ ഉപയോഗിക്കുക"
        CALL_DRIVER_USING  -> "ഇതുപയോഗിച്ച് ഡ്രൈവറെ വിളിക്കുക"
        WAS_YOUR_CALL_SUCCESSFUL  -> "നിങ്ങളുടെ കോൾ വിജയിച്ചോ"
        REQUEST_RECEIVED_WE_WILL_CALL_YOU_BACK_SOON  -> "അഭ്യർത്ഥന ലഭിച്ചു. ഞങ്ങൾ നിങ്ങളെ ഉടൻ ബന്ധപ്പെടും"
        CONTACT_REMOVED_SUCCESSFULLY  -> "കോൺടാക്‌റ്റ് നീക്കം ചെയ്‌തു"
        CORPORATE_ADDRESS  -> "പരാതികളും ആവലാതികളും"
        CORPORATE_ADDRESS_DESCRIPTION _  -> "മൂവിംഗ് ടെക് ഇന്നൊവേഷൻസ് പ്രൈവറ്റ് ലിമിറ്റഡ് <br> ഗിരിജ ബിൽഡിംഗ്, നമ്പർ 817, ഗണപതി ടെംപിൾ റോഡ്, എട്ടാം ബ്ലോക്ക്, കോറമംഗല, ബെംഗളൂരു, കർണാടക 560095, ഇന്ത്യ."
        CORPORATE_ADDRESS_DESCRIPTION_ADDITIONAL _ -> "പരാതികൾ പരിഹരിക്കുന്നതിന്, ഞങ്ങളുടെ <u>സ്വകാര്യതാ നയം</u> പരിശോധിക്കുക"
        REGISTERED_ADDRESS  -> "രേഖപ്പെടുത്തിയ വിലാസം"
        REGISTERED_ADDRESS_DESCRIPTION _  -> "മൂവിംഗ് ടെക് ഇന്നൊവേഷൻസ് പ്രൈവറ്റ് ലിമിറ്റഡ് <br> ഇൻഡിക്യൂബ് ഗാർഡൻ, പഴയ നമ്പർ. 648, പുതിയ നമ്പർ. 130, ഗ്രേപ്പ് ഗാർഡൻ, 18-ാം മെയിൻ, ഒന്നാം എ ക്രോസ്, ആറാം ബ്ലോക്ക്, കോറമംഗല, ബാംഗ്ലൂർ 560095."
        REGISTERED_ADDRESS_DESCRIPTION_ADDITIONAL _  -> "സ്റ്റാലിയൻ ബിസിനസ് സെന്റർ, നമ്പർ 444, 3rd & 4th നിലകൾ, 18th മെയിൻ, 6th ബ്ലോക്ക്, കോറമംഗല, ബെംഗളൂരു, കർണാടക- 560095, ഇന്ത്യ"
        DRIVER_ADDITIONS -> "ഡ്രൈവർ കൂട്ടിച്ചേർക്കലുകൾ*"
        FARE_UPDATE_POLICY -> "നിരക്ക് അപ്ഡേറ്റ് നയം"
        DRIVER_ADDITIONS_OPTIONAL  -> "ഡ്രൈവർ കൂട്ടിച്ചേർക്കലുകൾ (ഓപ്ഷണൽ)"
        THE_DRIVER_MAY_QUOTE_EXTRA_TO_COVER_FOR_TRAFFIC  -> "ഡ്രൈവർ ട്രാഫിക്ക്, റിട്ടേൺ ട്രിപ്പിനുള്ള സാധ്യത തുടങ്ങിയവയ്ക്കായി അധികമായി ഉദ്ധരിക്കാം."
        DRIVER_ADDITIONS_ARE_CALCULATED_AT_RATE _  -> "ഡ്രൈവർ കൂട്ടിച്ചേർക്കൽ പരിധികൾ അടിസ്ഥാന നിരക്കിന്റെ 10% കണക്കാക്കി, ഏറ്റവും അടുത്തുള്ള ₹10 ആയി കണക്കാക്കുന്നു"
        DRIVER_MAY_NOT_CHARGE_THIS_ADDITIONAL_FARE  -> "ശ്രദ്ധിക്കുക: ഡ്രൈവർ ഈ അധിക നിരക്ക് ഈടാക്കാം/അല്ലായിരിക്കാം"
        YOU_MAY_SEE_AN_UPDATED_FINAL_FARE_DUE_TO_ANY_OF_THE_BELOW_REASONS -> "ചുവടെയുള്ള ഏതെങ്കിലും കാരണത്താൽ നിങ്ങൾക്ക് അപ്‌ഡേറ്റ് ചെയ്‌ത അന്തിമ നിരക്ക് കണ്ടേക്കാം:"
        REASON_CHANGE_IN_ROUTE_A -> "1. റൂട്ടിലെ മാറ്റം: "
        REASON_CHANGE_IN_ROUTE_B -> "റൂട്ടിലെ മാറ്റം കാരണം മൊത്തം നിരക്ക് മാറിയേക്കാം"
        RECOMMENDED  -> "ശുപാർശ ചെയ്ത"
        COMPLETE_YOUR_PROFILE_FOR_A_PERSONALISED_RIDE_EXPERIENCE  -> "വ്യക്തിഗതമാക്കിയ റൈഡ് അനുഭവത്തിനായി നിങ്ങളുടെ പ്രൊഫൈൽ പൂർത്തിയാക്കുക"
        UPDATE_NOW  -> "ഇപ്പോൾ തന്നെ നവീകരിക്കുക"
        WE_WOULD_APPRECIATE_YOUR_FEEDBACK  -> "അക്കൗണ്ട് ഇല്ലാതാക്കുന്നതിന് പിന്നിലെ നിങ്ങളുടെ ന്യായവാദത്തെ ഞങ്ങൾ അഭിനന്ദിക്കുന്നു"
        REASON_FOR_DELETING_ACCOUNT  -> "അക്കൗണ്ട് ഇല്ലാതാക്കാനുള്ള കാരണം*"
        SUBMIT_REQUEST  -> "അഭ്യർത്ഥന സമർപ്പിക്കുക"
        PLEASE_ENTER_A_VALID_EMAIL  -> "സാധുവായ ഒരു ഇമെയിൽ നൽകുക"
        WE_WOULD_APPRECIATE_YOUR_REASONING  -> "അക്കൗണ്ട് ഇല്ലാതാക്കുന്നതിന് പിന്നിലെ നിങ്ങളുടെ ന്യായവാദത്തെക്കുറിച്ചുള്ള നിങ്ങളുടെ പ്രതികരണത്തെ ഞങ്ങൾ അഭിനന്ദിക്കുന്നു"
        OK_GOT_IT  -> "മനസ്സിലായി"
        WAIT_FOR_DRIVER  -> "ഡ്രൈവർക്കായി കാത്തിരിക്കുക"
        NO_LONGER_REQUIRE_A_RIDE_DUE_TO_CHANGE_IN_PLANS  -> "പ്ലാനുകളിലെ മാറ്റം കാരണം ഇനി ഒരു റൈഡ് ആവശ്യമില്ല"
        CANCELLING_AS_I_GOT_A_RIDE_ON_ANOTHER_APP  -> "മറ്റൊരു ആപ്പിൽ യാത്ര ചെയ്തതിനാൽ റദ്ദാക്കുന്നു"
        DRIVER_LOCATION_WASNT_CHANGING_ON_THE_MAP  -> "മാപ്പിൽ ഡ്രൈവർ ലൊക്കേഷൻ മാറുന്നില്ല"
        DRIVER_WAS_TAKING_TOO_LONG_TO_REACH_THE_PICKUP_LOCATION  -> "ഡ്രൈവർ പിക്കപ്പ് ലൊക്കേഷനിൽ എത്താൻ വളരെയധികം സമയമെടുത്തു"
        THE_PICKUP_LOCATION_ENTERED_WAS_WRONG  -> "നൽകിയ പിക്കപ്പ് ലൊക്കേഷൻ തെറ്റാണ്"
        YOUR_DRIVER_IS_JUST  -> "നിങ്ങളുടെ ഡ്രൈവർ വെറും "
        M_AWAY  -> " മീ ദൂരെ."
        DRIVER_HAS_ALREADY_TRAVELLED  -> "ഡ്രൈവർ ഇതിനകം "
        PLEASE_CONTACT_THE_DRIVER_BEFORE_CANCELLING  -> "\nറദ്ദാക്കുന്നതിന് മുമ്പ് ഡ്രൈവറെ ബന്ധപ്പെടുക"
        CONFIRM_WITH_YOUR_DRIVER -> "നിങ്ങളുടെ ഡ്രൈവറുമായി സ്ഥിരീകരിക്കുക"
        CHANGE_OF_PLANS  -> "പദ്ധതികളുടെ മാറ്റം"
        DRIVER_IS_NOT_MOVING  -> "ഡ്രൈവർ നീങ്ങുന്നില്ല"
        WRONG_PICKUP_LOCATION  -> "തെറ്റായ പിക്കപ്പ് ലൊക്കേഷൻ"
        DRIVER_MIGHT_BE_TAKING_ALTERNATE_ROUTE  -> "ഡ്രൈവർ ഒരു ഇതര റൂട്ട് എടുക്കുന്നുണ്ടാകാം."
        DRIVER_IS_NOT_MOVING_Q  -> "ഡ്രൈവർ നീങ്ങുന്നില്ല?"
        WOULD_YOU_LIKE_TO_CHECK_WITH_THE_DRIVER_BEFORE_CANCELLING  -> "\nറദ്ദാക്കുന്നതിന് മുമ്പ് ഡ്രൈവറുമായി പരിശോധിക്കാൻ നിങ്ങൾക്ക് താൽപ്പര്യമുണ്ടോ?"
        DRIVER_IS_NEAR_YOUR_LOCATION  -> "ഡ്രൈവർ നിങ്ങളുടെ സ്ഥലത്തിനടുത്താണ്."
        SOME_OTHER_REASON  -> "മറ്റെന്തെങ്കിലും കാരണം."
        METRO_RIDE  -> "മെട്രോ റൈഡ്"
        GO_BACK_TEXT -> "മടങ്ങിപ്പോവുക"
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_JUST -> "ഡ്രൈവർ നിങ്ങളുടെ പ്രത്യേക അഭ്യർത്ഥന തിരഞ്ഞെടുത്തു, അത് "
        DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST -> "ড্ഡ്രൈവർ നിങ്ങളുടെ പ്രത്യേക അഭ്യർത്ഥനയ്ക്ക് മുൻഗണന നൽകി, ഇതിനകം "
        AND_HAS_TRAVELLED -> " യാത്ര ചെയ്തിട്ടുണ്ട്."
        PLEASE_FIND_REVISED_FARE_ESTIMATE -> "പുതുക്കിയ കണക്കാക്കിയ നിരക്ക് ദയവായി കണ്ടെത്തുക. രാത്രി നിരക്കുകൾ പകലിന്റെ 1.5 ഇരട്ടിയാണ്."
        GO_TO_ZONE _ -> "പിക്കപ്പ് സോണിലേക്ക് നാവിഗേറ്റ് ചെയ്യുക"
        FARE_ESTIMATE  -> "നിരക്ക് എസ്റ്റിമേറ്റ്" 
        TIP_SELECTED  -> "നുറുങ്ങ് തിരഞ്ഞെടുത്തു"
        ADD_A_TIP_TO_FIND_A_RIDE_QUICKER  -> "വേഗത്തിലുള്ള സവാരി കണ്ടെത്താൻ ഒരു നുറുങ്ങ് ചേർക്കുക!"
        IT_SEEMS_TO_BE_TAKING_LONGER_THAN_USUAL  -> "ഇതിന് പതിവിലും കൂടുതൽ സമയമെടുക്കുന്നതായി തോന്നുന്നു."
        CONTINUE_SEARCH_WITH  -> "ഉപയോഗിച്ച് തിരയൽ തുടരുക"
        CONTINUING_SEARCH_WITH  -> "ഉപയോഗിച്ച് തിരയൽ തുടരുന്നു"
        SEARCHING_WITH  -> "ഉപയോഗിച്ച് തിരയുന്നു"
        THE_DRIVER_PREFERRED_YOUR_SPECIAL_REQUEST_AND_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION  -> "താങ്കളുടെ പ്രത്യേക റിക്വസ്റ്റ് സ്വീകരിച്ചു, ഡ്രൈവർ നിങ്ങളുടെ ലൊക്കേഷനിലേക്ക് വരികയാണ്."
        ALLOW_LOCATION_ACCESS -> "ലൊക്കേഷൻ ആക്സസ് അനുവദിക്കുക"
        MESSAGE_FROM_DRIVER -> "ഡ്രൈവറിൽ നിന്നുള്ള സന്ദേശം"
        REPLY -> "മറുപടി"
        NAME_SHOULD_BE_MORE_THAN_2_CHARACTERS  -> "പേര് 2 പ്രതീകങ്ങളിൽ കൂടുതലായിരിക്കണം"
        OKAY_GOT_IT  -> "ശരി മനസ്സിലായി"
        CALL_NAMMA_YATRI_SUPPORT _ -> "നമ്മ യാത്രി സപ്പോർട്ടിലേക്ക് വിളിക്കുക"
        CALL_112 -> "വിളിക്കുക 112"
        CALL_EMERGENCY_CENTRE -> "എമർജൻസി സെന്ററിലേക്ക് വിളിക്കുക"
        DRIVER_ADDITION_LIMITS_ARE_IN_INCREMENTS -> "ഡ്രൈവർ കൂട്ടിച്ചേർക്കൽ പരിധികൾ ₹20 ഇൻക്രിമെന്റിലാണ്"
        SEATS  -> "സീറ്റുകൾ"
        HATCHBACK  -> "ഹാച്ച്ബാക്ക്"
        SUV  -> "സ്ഉവി"
        SEDAN  -> "സെഡാൻ"
        DRIVER_IS_ALREADY_ON_THE_WAY_TO_YOUR_LOCATION  -> "ഡ്രൈവർ നിങ്ങളുടെ ലൊക്കേഷനിലേക്കുള്ള വഴിയിലാണ്."
        OTP_PAGE_HAS_BEEN_EXPIRED_PLEASE_REQUEST_OTP_AGAIN  -> "OTP പേജ് കാലഹരണപ്പെട്ടു, ദയവായി OTP വീണ്ടും അഭ്യർത്ഥിക്കുക"
        OTP_ENTERING_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER  -> "OTP ഇൻപുട്ട് പരിധി എത്തിയിരിക്കുന്നു, ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക"
        TOO_MANY_LOGIN_ATTEMPTS_PLEASE_TRY_AGAIN_LATER  -> "നിങ്ങൾ വളരെയധികം അസാധുവായ ശ്രമങ്ങൾ നടത്തി, ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക"
        SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN  -> "ചില സാങ്കേതിക പ്രശ്നം സംഭവിച്ചു, വീണ്ടും ശ്രമിക്കുക"
        SORRY_LIMIT_EXCEEDED_YOU_CANT_ADD_ANY_MORE_FAVOURITES  -> "ക്ഷമിക്കണം, പരിധി കവിഞ്ഞു. നിങ്ങൾക്ക് കൂടുതൽ പ്രിയപ്പെട്ട നമ്പറുകൾ ചേർക്കാൻ കഴിയില്ല"
        CANCELLATION_UNSUCCESSFULL_PLEASE_TRY_AGAIN  -> "റദ്ദാക്കൽ പരാജയപ്പെട്ടു, വീണ്ടും ശ്രമിക്കുക"
        NO_DRIVER_AVAILABLE_AT_THE_MOMENT_PLEASE_TRY_AGAIN  -> "ഇപ്പോൾ ഡ്രൈവറുകളൊന്നും ലഭ്യമല്ല, ദയവായി വീണ്ടും ശ്രമിക്കുക"
        OTP_FOR_THE_JATRI_SATHI_ZONE_HAS_BEEN_EXPIRED_PLEASE_TRY_LOOKING_AGAIN _  -> "ജാത്രി സാത്തി ഏരിയയുടെ OTP കാലഹരണപ്പെട്ടു, ബുക്കിംഗിനായി വീണ്ടും ശ്രമിക്കുക"
        NO_CONTACTS_FOUND_ON_THE_DEVICE_TO_BE_ADDED  -> "ഉപകരണത്തിൽ കോൺടാക്‌റ്റുകളൊന്നും കണ്ടെത്തിയില്ല"
        PLEASE_ENABLE_CONTACTS_PERMISSION_TO_PROCEED  -> "തുടരാൻ കോൺടാക്‌റ്റുകളുടെ അനുമതി പ്രവർത്തനക്ഷമമാക്കുക"
        LIMIT_REACHED_3_OF_3_EMERGENCY_CONTACTS_ALREADY_ADDED  -> "പരിധി കവിഞ്ഞു! 3-ൽ 3 എമർജൻസി കോൺടാക്റ്റുകൾ ഇതിനകം ചേർത്തിട്ടുണ്ട്"
        INVALID_CONTACT_FORMAT  -> "അസാധുവായ കോൺടാക്റ്റ് ഫോർമാറ്റ്"
        OTP_RESENT_LIMIT_EXHAUSTED_PLEASE_TRY_AGAIN_LATER  -> "OTP വീണ്ടും അയയ്ക്കുന്നതിനുള്ള പരിധി എത്തിയിരിക്കുന്നു, ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക"
        THIS_FIELD_IS_REQUIRED  -> "ഈ ഫീൽഡ് പൂരിപ്പിക്കേണ്ടതുണ്ട്"
        EMAIL_EXISTS_ALREADY  -> "ഇമെയില് നേരത്തെ ഉള്ളതാണ്"
        RATE_YOUR_EXPERIENCE  -> "നിങ്ങളുടെ അനുഭവം വിലയിരുത്തുക"
        REPORT_ISSUE_  -> "റിപ്പോർട്ട് പ്രശ്നം"
        DONE  -> "ചെയ്തു"
        PLEASE_TELL_US_WHAT_WENT_WRONG  -> "എന്താണ് തെറ്റ് സംഭവിച്ചതെന്ന് ഞങ്ങളോട് പറയൂ"
        DID_YOU_FACE_ANY_ISSUE  -> "നിങ്ങൾ എന്തെങ്കിലും പ്രശ്നം നേരിട്ടിട്ടുണ്ടോ?"
        WE_NOTICED_YOUR_RIDE_ENDED_AWAY  -> "നിങ്ങളുടെ റൈഡ് നിങ്ങളുടെ യഥാർത്ഥ ലക്ഷ്യസ്ഥാനത്ത് നിന്ന് അകലെ അവസാനിച്ചതായി ഞങ്ങൾ ശ്രദ്ധിച്ചു"
        GET_CALLBACK_FROM_US  -> "ഞങ്ങളിൽ നിന്ന് ഒരു കോൾബാക്ക് നേടുക"
        DRIVER_WAS_NOT_READY_TO_GO  -> "ഡ്രൈവർ പോകാൻ തയ്യാറായില്ല"
        ASKING_FOR_MORE_MONEY  -> "ഡ്രൈവർ കൂടുതൽ പണം ആവശ്യപ്പെടുകയായിരുന്നു"
        VEHICLE_BROKEN  -> "വാഹനം തകരാറിലായി"
        WE_WILL_GIVE_YOU_CALLBACK  -> "24 മണിക്കൂറിനുള്ളിൽ ഞങ്ങൾ നിങ്ങൾക്ക് ഒരു കോൾബാക്ക് നൽകും"
        YOUR_ISSUE_HAS_BEEN_REPORTED  -> "നിങ്ങളുടെ പ്രശ്നം വിജയകരമായി റിപ്പോർട്ട് ചെയ്തു"
        OTP_RESENT_SUCCESSFULLY  -> "OTP വീണ്ടും അയച്ചു"
        DESCRIPTION_SHOULD_BE_MORE_THAN_10_ALPHABETIC_CHARACTERS  -> "വിവരണം 10 അക്ഷരമാലയിൽ കൂടുതലായിരിക്കണം"
        IT_SEEMS_LIKE_YOU_HAVE_AN_ONGOING_RIDE_  -> "നിങ്ങൾക്ക് ഒരു ബുക്കിംഗ് നടക്കുന്നുണ്ടെന്ന് തോന്നുന്നു, അത് കാണുന്നതിന് ദയവായി ആപ്പ് പുനരാരംഭിക്കുക"
        INCORRECT_OTP_PLEASE_TRY_AGAIN  -> "തെറ്റായ OTP, വീണ്ടും ശ്രമിക്കുക."
        N_MORE_ATTEMPTS_LEFT  -> " കൂടുതൽ ശ്രമങ്ങൾ അവശേഷിക്കുന്നു"
        GO_TO_SELECTED_PICKUP_SPOT  -> "തിരഞ്ഞെടുത്ത പിക്കപ്പ് സ്ഥലത്തേക്ക് പോകുക"
        GO_TO_SELECTED_PICKUP_SPOT_AS_AUTOS_ARE_RESTRICTED  -> "ഈ പ്രദേശത്ത് ഓട്ടോകൾ നിയന്ത്രിച്ചിരിക്കുന്നതിനാൽ നിർദ്ദേശിച്ച പിക്കപ്പ് ലൊക്കേഷനിലേക്ക് ഡ്രൈവ് ചെയ്യുക"
        UNPROFESSIONAL_DRIVER -> "അലക്ഷ്യമായ ഡ്രൈവർ"
        RASH_DRIVING -> "അലക്ഷ്യമായ ഡ്രൈവിംഗ്"
        DRIVER_CHARGED_MORE -> "അധിക പണം ആവശ്യപ്പെട്ടു"
        UNCOMFORTABLE_AUTO -> "അസുഖകരമായ യാത്ര"
        UNCOMFORTABLE_CAB -> "അസുഖകരമായ യാത്ര"
        TRIP_GOT_DELAYED -> "യാത്ര വൈകിപ്പോയി"
        FELT_UNSAFE -> "സുരക്ഷിതമല്ല"
        POLITE_DRIVER -> "സൗമ്യനായ ഡ്രൈവർ"
        EXPERT_DRIVING -> "വിദഗ്‌ദ്ധ ഡ്രൈവിംഗ്"
        SAFE_RIDE -> "സുരക്ഷിത യാത്ര"
        CLEAN_AUTO -> "ശുചിത്വം ഉള്ള വാഹനം"
        CLEAN_CAB -> "ശുചിത്വം ഉള്ള വാഹനം"
        ON_TIME -> "സമയനിഷ്ഠ"
        SKILLED_NAVIGATOR -> "വിദഗ്ധ നാവിഗേഷൻ"
        RUDE_DRIVER -> "മര്യാദക്കുറവ്"
        TOO_MANY_CALLS -> "അധിക കാൾസ്"
        RECKLESS_DRIVING -> "അലക്ഷ്യ ഡ്രൈവിംഗ്"
        LATE_DROP_OFF -> "വൈകിയ ഡ്രോപ്പ്"
        LATE_PICK_UP -> "വൈകിയ പിക്ക് അപ്പ്"
        POOR_EXPERIENCE -> "അപൂർണ്ണ അനുഭവം 😕"
        TERRIBLE_EXPERIENCE -> "ഭയങ്കര അനുഭവം 😠"
        NEEDS_IMPROVEMENT -> "മോശമായിരിക്കുന്നു 😕"
        ALMOST_PERFECT -> "പ്രായപൂർണ്ണമാണ്! 🙂"
        AMAZING -> "അത്ഭുതകരം!!! 🤩"
        ASKED_FOR_EXTRA_FARE -> "അധിക കൂലി ചോദിച്ചു"
        ANYTHING_THAT_YOU_WOULD_LIKE_TO_TELL_US  -> "നിങ്ങൾ ഞങ്ങളോട് പറയാൻ ആഗ്രഹിക്കുന്ന എന്തെങ്കിലും? (ഓപ്ഷണൽ)"
        PLEASE_WAIT  -> "കാത്തിരിക്കൂ"
        PLATFORM_FEE  -> "പ്ലാറ്റ്ഫോം ഫീസ്"
        SGST  -> "SGST"
        CGST  -> "CGST"
        OTP_EXPIRED  -> "OTP കാലഹരണപ്പെട്ടു"
        OTP_EXPIRED_DESCRIPTION  -> "നിങ്ങളുടെ റൈഡ് OTP കാലഹരണപ്പെട്ടു. ഒരു സവാരി ലഭിക്കാൻ ദയവായി വീണ്ടും ബുക്ക് ചെയ്യുക"
        PLATFORM_GST  -> "നികുതികൾ (ജിഎസ്ടി)"
        MISC_WAITING_CHARGE  -> "മറ്റ്. (വെയിറ്റിംഗ് ചാർജുകൾ ഉൾപ്പെടെ)"
        AC_TAXI  -> "AC ടാക്സി"
        NON_AC_TAXI -> "എസി ടാക്സി ഇല്ല"
        AUTO_RICKSHAW  -> "ഓട്ടോ റിക്ഷ"
        GET_OTP_VIA_WHATSAPP  -> "വാട്ട്‌സ്ആപ്പ് വഴി OTP നേടുക"
        OR  -> "അഥവാ"
        HELPS_DRIVER_CONFIRM_ITS_YOU  -> "(ഇത് നിങ്ങളാണെന്ന് സ്ഥിരീകരിക്കാൻ ഡ്രൈവറെ സഹായിക്കുന്നു)"
        LETS_GET_YOU_TRIP_READY  -> "നിങ്ങളെ യാത്ര-തയ്യാറാക്കാം!"
        GOT_AN_OTP  -> "ഒരു OTP കിട്ടിയോ?"
        JUST_ONE_LAST_THING  -> "അവസാനമായി ഒരു കാര്യം മാത്രം"
        TOLL_CHARGES_WILL_BE_EXTRA  -> "ടോൾ ചാർജുകൾ ഉൾപ്പെടുത്തിയിട്ടുണ്ട്"
        CABS_AVAILABLE  -> "ക്യാബുകൾ ലഭ്യമാണ്"
        GENERAL_DISABILITY_DESCRIPTION  -> "നിങ്ങളുടെ ആവശ്യങ്ങളും അഭ്യർത്ഥനകളും നിങ്ങളെ സഹായിക്കാൻ ഡ്രൈവർമാരെ ബോധവൽക്കരിക്കും."
        PI_POINTER_1  -> "പിക്കപ്പിനായി നിങ്ങളുടെ കൃത്യമായ സ്ഥലത്തേക്ക് വരാൻ ഡ്രൈവർമാരോട് ആവശ്യപ്പെടും."
        PI_POINTER_2  -> "നിങ്ങളുടെ മൊബിലിറ്റി സഹായവുമായി നിങ്ങളെ സഹായിക്കാൻ ഡ്രൈവർമാരോട് ആവശ്യപ്പെടും. "
        VI_POINTER_1  -> "ടെക്‌സ്‌റ്റ് അയയ്‌ക്കുന്നതിന് പകരം വിളിക്കാൻ ഡ്രൈവർമാരെ പ്രേരിപ്പിക്കും."
        VI_POINTER_2  -> "പിക്കപ്പിൽ ഒരു തവണ ഹോൺ മുഴക്കാൻ ഡ്രൈവർമാരെ പ്രേരിപ്പിക്കും. "
        HI_POINTER_1  -> "വിളിക്കുന്നതിന് പകരം ടെക്‌സ്‌റ്റ് അയയ്‌ക്കാൻ ഡ്രൈവർമാരെ പ്രേരിപ്പിക്കും."
        HI_POINTER_2  -> " പിക്കപ്പിൽ ഒരിക്കൽ നിങ്ങൾക്ക് സന്ദേശം അയയ്‌ക്കാൻ ഡ്രൈവർമാരെ പ്രേരിപ്പിക്കും."
        DID_THE_DRIVER_OFFER_ASSISTANCE -> "ഡ്രൈവർ സഹായം വാഗ്ദാനം ചെയ്തോ?"
        WAS_THE_DRIVER_UNDERSTANDING_OF_YOUR_NEEDS -> "നിങ്ങളുടെ ഡ്രൈവർ നിങ്ങളുടെ ആവശ്യങ്ങൾ മനസ്സിലാക്കുകയും യാത്രയിൽ അവരെ ഉൾക്കൊള്ളുകയും ചെയ്തിരുന്നോ?"
        ACCESSIBILITY_TEXT _ -> "നമ്മ യാത്രി, ഇപ്പോൾ നിങ്ങൾക്കായി ഇഷ്‌ടാനുസൃതമാക്കി!"
        TO_CATER_YOUR_SPECIFIC_NEEDS _  -> "നിങ്ങളുടെ പ്രത്യേക ആവശ്യങ്ങൾ നിറവേറ്റുന്നതിനായി, നമ്മ യാത്രിയുടെ ചില സവിശേഷതകൾ ഞങ്ങൾ ഇഷ്ടാനുസൃതമാക്കിയിട്ടുണ്ട്."
        SPECIAL_ASSISTANCE  -> "പ്രത്യേക സഹായം"
        SELECT_THE_CONDITION_THAT_IS_APPLICABLE  -> "നിങ്ങൾക്ക് ബാധകമായ വ്യവസ്ഥ തിരഞ്ഞെടുക്കുക\n(RPWD ആക്ട് 2016 പ്രകാരം)"
        DISABILITY_CLAIMER_TEXT  -> "തുടരുന്നതിലൂടെ, 2016-ലെ RPWD ആക്ട് പ്രകാരം വൈകല്യമുള്ള ഒരു വ്യക്തിയെന്ന നിലയിൽ നിങ്ങൾ നിങ്ങളുടെ പദവി പ്രഖ്യാപിക്കുകയാണ്."
        ARE_YOU_A_PERSON_WITH_DISABILITY  -> "നിങ്ങൾ വൈകല്യമുള്ള ഒരു വ്യക്തിയാണോ?"
        DO_YOU_NEEED_SPECIAL_ASSISTANCE  -> "നിങ്ങൾക്ക് പ്രത്യേക സഹായം ആവശ്യമുണ്ടോ (വൈകല്യമുള്ള വ്യക്തി)?"
        ASSISTANCE_REQUIRED  -> "സഹായം ആവശ്യമാണ് (വൈകല്യമുള്ള വ്യക്തി)"
        NO_DISABILITY  -> "വൈകല്യമില്ല"
        LEARN_HOW_TEXT _  -> "നമ്മ യാത്രി നിങ്ങളുടെ ആവശ്യങ്ങൾ എങ്ങനെ നിറവേറ്റുന്നുവെന്ന് അറിയുക"
        UPDATE_PROFILE  -> "പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്യുക"
        NOW_GET_ASSISTED_RIDES  -> "നിങ്ങൾ വൈകല്യമുള്ള ആളാണെങ്കിൽ ഇപ്പോൾ അസിസ്റ്റന്റ് റൈഡുകൾ നേടൂ"
        SENT_OTP_VIA_WHATSAPP  -> "ഒടിപി വാട്ട്‌സ്ആപ്പ് വഴി അയച്ചു"
        SENT_OTP_VIA_SMS  -> "എസ്എംഎസ് വഴി OTP അയച്ചു"
        ENABLE_LOCATION_PERMISSION_TO  -> "റൈഡുകൾക്കായി തിരയാൻ ലൊക്കേഷൻ അനുമതി പ്രവർത്തനക്ഷമമാക്കുക"
        AC_CAB -> "എസി ക്യാബ്"
        AC_SUV -> "എസി എസ്‌യുവി"
        RIDE_TYPE  -> "റൈഡ് തരം"
        ERNAKULAM_LIMIT_CHARGE -> "പിക്കപ്പ് /ലക്ഷ്യസ്ഥാനം എറണാകുളം കോർപ്പറേഷൻ പരിധിക്ക് പുറത്താണെങ്കിൽ നിരക്ക് 1.5 മടങ്ങ് ആയിരിക്കും."
        SELECT_LOCATION_ON_MAP -> "മാപ്പിൽ ലൊക്കേഷൻ തിരഞ്ഞെടുക്കുക"
        DOWNLOAD_DRIVER_RECEIPT -> "ഡ്രൈവർ രസീത് ഡൗൺലോഡ് ചെയ്യുക"
        VIEW_DRIVER_RECEIPT -> "ഡ്രൈവർ രസീത് കാണുക"
        DRIVER_RECEIPT  -> "ഡ്രൈവർ രസീത്"
        HELP -> "സഹായം"
        FARE_INFO_TEXT _ -> ""
        FASTER -> "വേഗത്തിൽ"
        PLEASE_ENABLE_LOCATION_PERMISSION _ -> "റൈഡുകൾക്കായി തിരയാൻ ക്രമീകരണ ആപ്പിൽ നിന്ന് ലൊക്കേഷൻ അനുമതികൾ പ്രാപ്തമാക്കുക."
        EDUCATIONAL_POP_UP_SLIDE_1_TITLE -> "ഞങ്ങളുടെ എല്ലാ ഉപയോക്താക്കൾക്കും തുല്യവും \n തുല്യവുമായ അനുഭവം നൽകാൻ ഞങ്ങൾ ശ്രമിക്കുന്നു"
        EDUCATIONAL_POP_UP_SLIDE_2_TITLE -> "മോശം കാഴ്ചയുള്ള \n ഉപയോക്താക്കൾക്ക്"
        EDUCATIONAL_POP_UP_SLIDE_3_TITLE -> "മോശം കേൾവിയുള്ള \n ഉപയോക്താക്കൾക്കായി"
        EDUCATIONAL_POP_UP_SLIDE_4_TITLE -> "ലോക്കോമോട്ടർ വൈകല്യമുള്ള ഉപയോക്താക്കൾക്ക്"
        EDUCATIONAL_POP_UP_SLIDE_5_TITLE -> "മറ്റ് പ്രത്യേക ആവശ്യങ്ങളുള്ള ഉപയോക്താക്കൾക്ക്"
        EDUCATIONAL_POP_UP_SLIDE_1_SUBTITLE -> ""
        EDUCATIONAL_POP_UP_SLIDE_2_SUBTITLE -> "&#8226; സന്ദേശമയയ്‌ക്കുന്നതിന് പകരം വിളിക്കാൻ <br> &ensp; ഡ്രൈവർമാരെ പ്രേരിപ്പിക്കും.  <br> &#8226; പിക്കപ്പിൽ ഒരു തവണ ഹോൺ <br> &ensp; മുഴക്കാൻ ഡ്രൈവർമാരെ പ്രേരിപ്പിക്കും. <br> &#8226; അവരുടെ ആവശ്യങ്ങളും അഭ്യർത്ഥനകളും അവരെ <br> &ensp; സഹായിക്കാൻ ഡ്രൈവർമാർക്ക് ബോധവൽക്കരണം <br> &ensp; നൽകും."
        EDUCATIONAL_POP_UP_SLIDE_3_SUBTITLE -> "&#8226; വിളിക്കുന്നതിന് പകരം ടെക്‌സ്‌റ്റ് അയയ്‌ക്കാൻ  <br> &ensp; ഡ്രൈവർമാരെ പ്രേരിപ്പിക്കും. <br> &#8226; പിക്കപ്പിൽ ഒരു തവണ മെസേജ് ചെയ്യാൻ <br> &ensp; ഡ്രൈവർമാരെ പ്രേരിപ്പിക്കും. <br> &#8226; അവരുടെ ആവശ്യങ്ങളും അഭ്യർത്ഥനകളും അവരെ  <br> &ensp; സഹായിക്കാൻ ഡ്രൈവർമാർക്ക് ബോധവൽക്കരണം <br> &ensp;  നൽകും."
        EDUCATIONAL_POP_UP_SLIDE_4_SUBTITLE -> "&#8226; പിക്കപ്പിനായി ഡ്രൈവർമാരെ അവരുടെ കൃത്യമായ <br> &ensp; സ്ഥലത്തേക്ക് വരാൻ ആവശ്യപ്പെടും. <br> &#8226; ഡ്രൈവർമാരെ അവരുടെ മൊബിലിറ്റി <br> &ensp; സഹായവുമായി സഹായിക്കാൻ <br> &ensp; ആവശ്യപ്പെടും. <br> &#8226; അവരുടെ ആവശ്യങ്ങളും അഭ്യർത്ഥനകളും അവരെ <br> &ensp; സഹായിക്കാൻ ഡ്രൈവർമാർക്ക് ബോധവൽക്കരണം <br> &ensp; നൽകും."
        EDUCATIONAL_POP_UP_SLIDE_5_SUBTITLE -> "&#8226; ഞങ്ങൾ മറ്റ് തരത്തിലുള്ള വൈകല്യങ്ങൾ <br> &ensp; ശേഖരിക്കുകയും ആവശ്യാനുസരണം ലഭ്യമായ <br> &ensp; വൈകല്യങ്ങളുടെ പട്ടികയിൽ അവയെ <br> &ensp; ഉൾപ്പെടുത്തുകയും ചെയ്യും"
        INCLUSIVE_AND_ACCESSIBLE  -> "എല്ലാവർക്കുമായി ഉൾക്കൊള്ളുന്നതും ആക്സസ് ചെയ്യാവുന്നതും!"
        SOMETHING_WENT_WRONG_TRY_AGAIN_LATER -> "ചില സാങ്കേതിക പ്രശ്നം സംഭവിച്ചു, ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക"
        YOU_SEEM_TO_BE_FAR_FROM_PICK_UP -> "നിങ്ങൾ പിക്കപ്പ് ലൊക്കേഷനിൽ നിന്ന് വളരെ അകലെയാണെന്ന് തോന്നുന്നു!"
        ARE_YOU_SURE_YOU_WANT_TO_PROCEED_WITH_THE_BOOKING -> "ബുക്കിംഗുമായി മുന്നോട്ട് പോകണമെന്ന് തീർച്ചയാണോ?"
        MY_TICKETS -> "എന്റെ ടിക്കറ്റുകൾ"
        YOU_CAN_BOOK_TICKETS_TO_THE_ZOO_BY_CLICKING_THE_BUTTON -> "ബട്ടൺ ക്ലിക്ക് ചെയ്ത് നിങ്ങൾ സ്വന്തമായി ചിഡിയാഘരത്തിനുള്ള ടിക്കറ്റുകൾ ബുക്ക് ചെയ്യാൻ കഴിയും."
        QUOTE_EXPIRED -> "ত্রুটি ঘটেছে"
        WELCOME_TEXT -> "{} আপনাকে স্বাগতম"
        LOCATION_PERMISSION_SUBTITLE -> "നിങ്ങളുടെ യാത്രകളിനായി, ഞങ്ങളുടെ നിങ്ങളുടെ ഡിവൈസ് സ്ഥാനം ആവശ്യമാണ്."
        LOCATION_PERMISSION_SUBTITLE_NEW_USER -> "{} എന്നാൽ സ്വാഗതമാണ്! \nറൈഡുകൾ ബുക്ക് ചെയ്വാൻ, ഞങ്ങളുടെ നിങ്ങളുടെ ഡിവൈസ് സ്ഥാനം ആവശ്യമാണ്."
        YOUR_FEEDBACK_HELPS_US appName -> appName <> " അനുഭവം മെച്ചപ്പെടുത്താൻ നിങ്ങളുടെ ഫീഡ്‌ബാക്ക് ഞങ്ങളെ സഹായിക്കുന്നു"
        FINDING_QUOTES_TEXT -> "ക്യാബുകൾ കണ്ടെത്താൻ"
        NEW_ -> "പുതിയ"
        PAY_DRIVER_USING_WALLET -> ""
        CHARGES_APPLICABLE_AFTER_3_MINS -> "3 മിനിറ്റിന് ശേഷം നിരക്കുകൾ ബാധകം"
        REACHING_YOUR_DESTINATION_IN_ -> "നിങ്ങളുടെ ലക്ഷ്യസ്ഥാനത്ത് എത്തിച്ചേരുന്നു "
        WAITING_AT_PICKUP -> " പിക്കപ്പിൽ കാത്തിരിക്കുന്നു "
        PICKUP -> "പുരോഗമിക്കുക"
        PAY_BY_CASH_OR_UPI -> "പണമായി അടയ്ക്കുക / UPI "
        YOU_WILL_PAY_FOR_EVERY_MINUTE freeMinutes chargePerMin -> "ആദ്യ " <> freeMinutes <> " മിനിറ്റിന് കാത്തിരിക്കല്‍ ചാര്‍ജ് സുന്നം. പിന്നിട്ട് "<> chargePerMin <>" കാത്തിരിക്കല്‍ ചാര്‍ജ് പ്രയോജനപ്പെടും."
        WAIT_TIMER -> "വെയ്റ്റ് ടൈമർ"
        HOW_LONG_DRIVER_WAITED_FOR_PICKUP -> "പിക്കപ്പിൽ ഡ്രൈവർ എത്ര നേരം കാത്തിരുന്നുവെന്ന് കാണിക്കുന്നു."
        CHAT_WITH -> "ചാറ്റ് ചെയ്യുക"
        QUICK -> "വേഗം"
        CHATS -> "ചാറ്റുകൾ"
        REPLIES -> "മറുപടികൾ"
        YOU_SENT -> "നീ അയച്ചു"
        MESSAGE_YOUR_DRIVER -> "നിങ്ങളുടെ ഡ്രൈവർക്ക് സന്ദേശം അയക്കണോ?"
        CHECK_IN_WITH_YOUR_DRIVER -> "ഒരു ദ്രുത ചാറ്റ് ഉപയോഗിച്ച് നിങ്ങളുടെ ഡ്രൈവർ പരിശോധിക്കുക"
        CHECK_IN_WITH_YOUR_EM name -> "ഒരു ദ്രുത ചാറ്റ് ഉപയോഗിച്ച് " <> name <> " ചെക്ക് ഇൻ ചെയ്യുക"
        TRACK_ON_GOOGLE_MAPS -> "തത്സമയ ട്രാക്കിംഗ്"
        OTP_EXPIRE_TIMER -> "OTP കാലഹരണപ്പെടുന്ന ടൈമർ"
        SHOWS_FOR_HOW_LONG_YOUR_OTP_ -> "റൈഡ് ആരംഭിക്കാൻ നിങ്ങളുടെ OTP എത്ര കാലത്തേക്ക് സാധുവായി തുടരുമെന്ന് കാണിക്കുന്നു."
        IF_YOUR_OTP_EXPIRES_ -> "നിങ്ങളുടെ OTP കാലഹരണപ്പെടുകയാണെങ്കിൽ, നിങ്ങൾ വീണ്ടും ബുക്ക് ചെയ്യേണ്ടതുണ്ട്."
        YOU_HAVE_REACHED_DESTINATION -> "നിങ്ങൾ നിങ്ങളുടെ ലക്ഷ്യസ്ഥാനത്ത് എത്തിയിരിക്കുന്നു"
        PLACES_YOU_MIGHT_LIKE_TO_GO_TO-> "നിനക്ക് ഇഷ്ടപ്പെടുകയായ സ്ഥലങ്ങൾ"
        SUGGESTED_DESTINATION-> "സൂചിപ്പിച്ച ഗോളാഭ്യന്തരങ്ങൾ"
        RECENT_RIDES-> "ഏറ്റവും പുതിയ സൈക്കിൾകൾ"
        ONE_CLICK_BOOKING_FOR_YOUR_FAVOURITE_JOURNEYS-> "നിനക്ക് ഇഷ്ടപ്പെട്ട യാത്രകളിനോട് ഒരു ക്ലിക്ക് ബുക്കിംഗ്!"
        VIEW_MORE-> "കൂടുതൽ കാണുക"
        VIEW_LESS-> "കുറഞ്ഞ കാണുക"
        HAVE_A_REFFERAL-> "ഒരു റഫറൽ കോഡ് ഉണ്ടോ?"
        YOUR_SUGGESTED_DESTINATIONS_AND_RECENT_RIDES_WILL_APPEAR_HERE -> "നിങ്ങളുടെ സൂചിപ്പിച്ച ഗോളാഭ്യന്തരങ്ങൾ അവിടെ കാണാൻ കഴിയും"
        WELCOME_TO_NAMMA_YATRI_ -> "നമ്മ യാത്രിയിലേക്ക് സ്വാഗതം!"
        BOOK_AND_MOVE -> "ബുക്ക് ചെയ്യുക മാറുക"
        ANYWHERE_IN_THE_CITY -> "നഗരത്തിലെത്തിയാൽ എല്ലാവർക്കും സൗകര്യമായി"
        CHECKOUT_OUR_LIVE_STATS -> "ഞങ്ങളുടെ ലൈവ് സ്റ്റാറ്റിസ്റ്റികൾ ചെക്കൗട്ട് ചെയ്യുക"
        MOST_LOVED_APP _ -> "ഏറ്റവും ❤️ സീറോ കമ്മീഷൻ ആപ്പ്"
        PICKUP_ -> "പുരോഗമിക്കുക-> "
        PAST_SEARCHES -> "പഴയ തിരയലുകൾ"
        SEARCH_RESULTS -> "തിരയൽ ഫലങ്ങൾ"
        EDIT_DESTINATION -> "ലക്ഷ്യസ്ഥാനം തിരുത്തുക"
        REQUESTING_RIDE_IN -> "യാത്ര അഭ്യർത്ഥിക്കുന്നു"
        CONFIRM_FARE -> "നിരക്ക് സ്ഥിരീകരിക്കുക"
        REQUEST_CHANGE -> "മാറ്റം അഭ്യർത്ഥിക്കുക"
        REQUESTING_RIDE -> "യാത്ര അഭ്യർത്ഥിക്കുന്നു"
        TAP_HERE_TO_STOP_AUTO_REQUESTING -> "ഓട്ടോ അഭ്യർത്ഥന നിർത്താൻ ഇവിടെ ടാപ്പ് ചെയ്യുക"
        POWERED_BY -> "പവർഡ് ബൈ"
        BOOK_YOUR_RIDE -> "നിങ്ങളുടെ യാത്ര ബുക്ക് ചെയ്യുക"
        FARE_UPDATED_WITH_CHARGES -> "ബാധകമായ കാത്തിരിപ്പ് നിരക്കുകൾ ഉൾപ്പെടുത്തുന്നതിന് നിരക്ക് അപ്ഡേറ്റ് ചെയ്തിട്ടുണ്ട്"
        FARE_UPDATED_WITH_SHORTER_DIST -> "നിങ്ങളുടെ സവാരി {} കി.മീ കുറവായതിനാൽ നിങ്ങളുടെ നിരക്ക് അപ്‌ഡേറ്റ് ചെയ്‌തു"
        FARE_UPDATED_WITH_LONGER_DIST -> "നിങ്ങളുടെ സവാരി {} കി.മീ ദൈർഘ്യമുള്ളതിനാൽ നിങ്ങളുടെ നിരക്ക് പുതുക്കി"
        FARE_UPDATED_WITH_CHARGES_SHORTER_DIST -> "നിങ്ങളുടെ സവാരി {} കി.മീ കുറവായതിനാലും കാത്തിരിപ്പ് സമയ നിരക്കുകളുള്ളതിനാലും നിങ്ങളുടെ നിരക്ക് അപ്ഡേറ്റ് ചെയ്തിട്ടുണ്ട്"
        FARE_UPDATED_WITH_CHARGES_LONGER_DIST -> "നിങ്ങളുടെ സവാരിക്ക് {} കിലോമീറ്റർ ദൈർഘ്യമുള്ളതിനാൽ നിങ്ങളുടെ നിരക്ക് അപ്‌ഡേറ്റ് ചെയ്‌തു, കൂടാതെ കാത്തിരിപ്പ് സമയ നിരക്കുകളും"
        START_TYPING_TO_SEARCH_PLACES -> "സ്ഥലങ്ങൾ തിരയാൻ ടൈപ്പ് ചെയ്യാൻ ആരംഭിക്കുക"
        DID_YOU_HAVE_A_SAFE_JOURNEY -> "നിങ്ങൾക്ക് സുരക്ഷിതമായ ഒരു യാത്ര ഉണ്ടായിരുന്നോ?"
        TRIP_WAS_SAFE_AND_WORRY_FREE -> "നിങ്ങളുടെ യാത്ര സുരക്ഷിതവും വിഷമരഹിതവുമാണെന്ന് ഉറപ്പാക്കാൻ ഞങ്ങൾ ആഗ്രഹിക്കുന്നു."
        DRIVER_BEHAVED_INAPPROPRIATELY -> "ഡ്രൈവർ അപമര്യാദയായി പെരുമാറി"
        I_DID_NOT_FEEL_SAFE -> "എനിക്ക് സുരക്ഷിതത്വം തോന്നിയില്ല"
        LOOKING_FOR_ANOTHER_RIDE -> "മറ്റൊരു യാത്രയില്‍ തിരഞ്ഞെടുക്കുന്നു..."
        THE_RIDE_HAD_BEEN_CANCELLED_WE_ARE_FINDING_YOU_ANOTHER -> "യാത്ര റൈഡ് റദ്ദാക്കപ്പെട്ടു, നാം നിനക്ക് മറ്റൊരു യാത്ര തിരിച്ചെത്തുന്നു"
        ENJOY_THE_RIDE -> "നിങ്ങളുടെ ലക്ഷ്യസ്ഥാനത്തേക്കുള്ള യാത്ര ആസ്വദിക്കൂ!"
        RIDE_STARTED -> "സവാരി തുടങ്ങി"
        DISCOVER_AWESOME_SPOTS_TAILORED_JUST_FOR_YOU -> "നിങ്ങളുടെ ആവശ്യങ്ങളും ആസ്വദിക്കാൻ നിങ്ങളുടെ പ്രിയപ്പെട്ട സ്ഥലങ്ങൾ കണ്ടെത്തുക"
        ONE_CLICK -> "1 ക്ലിക്ക് ബുക്കിംഗ്"
        SMART -> "സ്മാർട്ട്"
        NOT_SERVICEABLE -> "സേവനയോഗ്യമല്ല"
        WE_ARE_NOT_LIVE_IN_YOUR_AREA -> "ഞങ്ങൾ ഇതുവരെ നിങ്ങളുടെ പ്രദേശത്ത് താമസിക്കുന്നില്ല! \nനിങ്ങൾക്ക് മുകളിൽ ഇടതുവശത്തുള്ള മെനുവിൽ നിന്ന് റൈഡ് ചരിത്രവും മറ്റ് \nsക്രമീകരണങ്ങളും ആക്സസ് ചെയ്യാൻ കഴിയും."
        FACING_PROBLEM_WITH_APP -> "അപ്ലിക്കേഷനിൽ പ്രശ്നങ്ങൾ നേരിടുന്നുണ്ടോ?"
        TAP_HERE_TO_REPORT -> "<u>പ്രശ്നം റിപ്പോർട്ടുചെയ്യാൻ ഇവിടെ ടാപ്പുചെയ്യുക</u>"
        CONFIRM_YOUR_RIDE  -> "നിങ്ങളുടെ യാത്ര സ്ഥിരീകരിക്കുക"
        RIDE_SCHEDULED -> "റൈഡ് ഷെഡ്യൂൾ ചെയ്തു"
        RIDE_STARTS_ON -> "സവാരി ആരംഭിക്കുന്നു"
        RENTAL_PACKAGE -> "വാടക പാക്കേജ്"
        GO_HOME -> "വീട്ടിലേക്ക് പോകുക"
        CANCEL_RENTAL_BOOKING -> "വാടക ബുക്കിംഗ് റദ്ദാക്കുക"
        ADD_FIRST_STOP -> "ആദ്യ സ്റ്റോപ്പ് ചേർക്കുക"
        DRIVER_WILL_BE_ASSIGNED_MINUTES_BEFORE_STARTING_THE_RIDE -> "റൈഡ് ആരംഭിക്കുന്നതിന് {} മിനിറ്റ് മുമ്പ് ഡ്രൈവറെ നിയോഗിക്കും"
        YOUR_REPORTS -> "നിങ്ങളുടെ റിപ്പോർട്ടുകൾ"
        VIEW -> "കാണുക"
        ISSUE_NO -> "പ്രശ്നം നം."
        ADD_VOICE_NOTE -> "വോയ്സ് നോട്ട് ചേർക്കുക"
        VOICE_NOTE -> "വോയ്സ് നോട്ട്"
        SUBMIT_ISSUE_DETAILS -> "പ്രശ്നം വിശദീകരിക്കുക"
        IMAGE_PREVIEW -> "ചിത്രത്തിന്റെ പ്രിവ്യൂ"
        ADDED_IMAGES -> "ചേർത്ത ചിത്രങ്ങൾ"
        NO_IMAGES_ADDED -> "ചിത്രങ്ങളൊന്നും ചേർത്തിട്ടില്ല"
        I_DONT_KNOW_WHICH_RIDE -> "ഏത് റൈഡാണെന്ന് എനിക്കറിയില്ല"
        ADDED_VOICE_NOTE -> "വോയ്സ് നോട്ട് ചേർത്തു"
        NO_VOICE_NOTE_ADDED -> "വോയിസ് നോട്ടൊന്നും ചേർത്തിട്ടില്ല"
        CALL_DRIVER_TITLE -> "ഡ്രൈവറെ വിളിക്കണോ?"
        CALL_SUPPORT_TITLE -> "സപ്പോർട്ടിനെ വിളിക്കണോ?"
        CALL_DRIVER_DESCRIPTION -> "നിങ്ങൾ ഡ്രൈവറെ വിളിക്കാൻ പോകുകയാണ്. തുടരണോ?"
        ADD_IMAGE -> "ചിത്രം ചേർക്കുക"
        ADD_ANOTHER -> "മറ്റൊന്ന് ചേർക്കുക"
        IMAGES -> "ചിത്രങ്ങൾ"
        ISSUE_SUBMITTED_TEXT -> "നിങ്ങളുടെ പ്രശ്നം പരിഹരിക്കാൻ ഞങ്ങൾ പ്രവർത്തിച്ചുകൊണ്ടിരിക്കുക"
        ISSUE_RESOLVED_TEXT -> "പ്രശ്നം പരിഹരിച്ചിരിക്കുന്നു!"
        CHOOSE_AN_OPTION -> "തുടരാൻ ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക"
        ISSUE_MARKED_AS_RESOLVED -> "പ്രശ്നം പരിഹരിച്ചതായി അടയാളപ്പെടുത്തി!"
        STILL_HAVING_ISSUE -> "ഇപ്പോഴും പ്രശ്നമുണ്ടോ?"
        IMAGE -> "ചിത്രം"
        RECORD_VOICE_NOTE -> "വോയ്സ് നോട്ട് റെക്കോർഡ്‌ ചെയ്യുക"
        CANCEL_BUTTON -> "റദ്ദാക്കുക"
        MAX_IMAGES -> "പരമാവധി 3 ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യാം"
        SELECT_A_RIDE_TO_REPORT -> "പ്രശ്നവുമായി ബന്ധപ്പെട്ട റൈഡ് തിരഞ്ഞെടുക്കുക"
        RIDE_RELATED_ISSUE_PAGE_NAME -> "റൈഡുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        APP_RELATED_ISSUE_PAGE_NAME -> "ആപ്പുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        DRIVER_RELATED_ISSUE_PAGE_NAME -> "ഡ്രൈവറുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        LOST_AND_FOUND_ISSUE_PAGE_NAME -> "നഷ്ടപ്പെട്ട വസ്തു റിപ്പോർട്ട് ചെയ്യുക"
        YEARS_AGO -> "വർഷങ്ങൾക്ക് മുമ്പ്"
        MONTHS_AGO -> "മാസങ്ങൾക്ക് മുമ്പ്"
        DAYS_AGO -> "ദിവസങ്ങൾക്ക് മുമ്പ്"
        HOURS_AGO -> "മണിക്കൂർ മുമ്പ്"
        MIN_AGO -> "മിനിറ്റ് മുമ്പ്"
        SEC_AGO -> "സെക്കന്റ് മുമ്പ്"
        RESOLVED_ISSUES -> "പരിഹരിച്ച പ്രശ്നങ്ങൾ"
        OTHER_ISSUES -> "മറ്റ് പ്രശ്നങ്ങൾ"
        SOS_ISSUE_PAGE_NAME -> "SOS പ്രശ്നം"
        FARE_DISCREPANCIES_ISSUE_PAGE_NAME -> "യാത്രക്കൂലിയുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        PAYMENT_RELATED_ISSUE_PAGE_NAME -> "പേയ്‌മെന്റുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        ACCOUNT_RELATED_ISSUE_PAGE_NAME -> "അക്കൗണ്ടുമായി ബന്ധപ്പെട്ട പ്രശ്നം"
        REPORTED -> "റിപ്പോർട്ട് ചെയ്തു"
        RESOLVED -> "പരിഹരിച്ചത്"
        REPORTED_ISSUES ->  "റിപ്പോർട്ടുചെയ്ത പ്രശ്നങ്ങൾ"
        REPORT_ISSUE_CHAT_PLACEHOLDER _ -> "നിങ്ങളുടെ പ്രശ്നം വിവരിക്കുക."
        CALL_SUPPORT_DESCRIPTION _ -> "നിങ്ങൾ പിന്തുണാ ടീമിലേക്ക് ഒരു കോൾ വിളിക്കാൻ പോകുകയാണ്. നിങ്ങൾക്ക് തുടരണോ?"
        CANT_FIND_OPTION -> "ഓപ്ഷൻ കണ്ടെത്താൻ കഴിയുന്നില്ല"
        NEED_HELP ->  "സഹായം ആവശ്യമുണ്ട്?"
        SAFETY_ISSUE_PAGE_NAME -> "സുരക്ഷാ സംബന്ധിച്ച പ്രശ്നം"
        WE_HOPE_THE_ISSUE_IS_RESOLVED _ -> "പ്രശ്നം പരിഹരിച്ചതായി ആശംസിക്കുന്നു"
        PLEASE_SELECT_THE_RIDE_TO_CALL_DRIVER -> "ഡ്രൈവർ വിളിക്കാൻ റൈഡ് തിരഞ്ഞെടുക്കുക"
        ADD_IMAGE_S -> "ചിത്രം ചേർക്കുക"
        ALREADY_HAVE_AN_ACTIVE_RIDE -> "ഇതിനകം നിങ്ങളുടെ റൈഡ് പ്രവർത്തിക്കുന്നു"
        BOOK_METRO_WITH_NY_NOW -> "നമ്മ യാത്രി ഉപയോഗിച്ച് \nമെട്രോ ടിക്കറ്റുകൾ ബുക്ക് ചെയ്യുക!"
        CONFIRM_STOP_LOCATION -> "സ്റ്റോപ്പ് ലൊക്കേഷൻ സ്ഥിരീകരിക്കുക"
        CONFIRM_DROP -> "ഡ്രോപ്പ് സ്ഥിരീകരിക്കുക"
        LEARN_MORE -> "കൂടുതല്‍ അറിയുക"
        LEARN_ABOUT_NAMMA_SAFETY -> "നമ്മ സുരക്ഷാ പദ്ധതിയെ അറിയുക"
        NAMMA_SAFETY_WILL_ENABLE_ACCESS -> "സുരക്ഷാ മോഡ് നിശ്ചയിക്കും സമയത്തു പ്രയോഗിക്കാം"
        EDIT_ACTIONS -> "പ്രവർത്തനങ്ങൾ എഡിറ്റുചെയ്യുക"
        EMERGENCY_ACTIONS -> "അപകട പ്രവർത്തനങ്ങൾ"
        WHEN_YOU_START_EMERGENCY_SOS -> "സുരക്ഷാ മോഡ് സജീവമാക്കുമ്പോൾ, നിങ്ങളുടെ ആപ്പ് താഴെപ്പോകുന്ന പ്രവർത്തനങ്ങൾ നടത്തും"
        EMERGENCY_SHARING_WITH_CONTACTS -> "ആപത്ത് പങ്കിടുകയും എസ്‌ഒഎസ് സമയത്ത് ആടോ കോളിംഗ് സംരംഭം"
        SHARING_WITH -> "പങ്കിടുകയും:"
        ADD_A_CONTACT -> "ഒരു ബന്ധം ചേർക്കുക"
        TO_ENSURE_SAFETY_USERS_SHOULD -> "സുരക്ഷയെ ഉറപ്പാക്കാൻ, ഉപയോക്താക്കൾ ചെയ്യണം:"
        ABOUT_SOS_DESC -> "സുരക്ഷാ മോഡിന്റെ ക്രിറ്റിക്കലിറ്റി ഉണരുക. അപ്രാധാന്യ സന്ദര്‍ഭങ്ങളില്‍, ദയവായി <b>സഹായവും പിന്തുണയും</b> വിഭാഗം ഉപയോഗിക്കാൻ പരിഹാരപ്പെടുക."
        FEW_EXAMPLES_OF_SOS_SITUATIONS -> "അപകട സന്ദേശങ്ങളുടെ ചില ഉദാഹരണങ്ങൾ"
        THINGS_TO_DO_DURING_SOS_SITUATION -> "അപകട സന്ദേശത്തിനുള്ളിലേക്കുള്ള പ്രവർത്തനങ്ങൾ"
        EMERGENCY_REQUEST_SENT -> "അപകട അഭ്യർത്ഥന അയച്ചു!"
        SOS_TRIGGERED_DESC -> "ദയവായി ശാന്തമാകുക, നിങ്ങളുടെ പ്രത്യക്ഷ ലൊക്കേഷൻ നിങ്ങളുടെ അപകട ബന്ധുക്കൾക്ക് പങ്കിടുന്നു."
        SOS_ACTIONS -> "എസ്‌ഓ്‌എസ് പ്രവർത്തനങ്ങൾ"
        CALL_POLICE -> "പോലീസ് വിളിക്കുക"
        CALL_SUPPORT -> "ഞങ്ങളുടെ\nപിന്തുണ"
        RECORD_VIDEO -> "വീഡിയോ റെക്കോർഡ് ചെയ്യുക"
        STOP_AND_SHARE_RECORDING -> "റെക്കോർഡിംഗ് നിർത്തുകയും പങ്കിടുകയും ചെയ്യുക"
        CANCEL_SHARING -> "പങ്കിടൽ റദ്ദാക്കുക"
        START_RECORDING -> "റെക്കോർഡ് ആരംഭിക്കുക"
        SHARING_THE_VIDEO_IN -> "വീഡിയോ പങ്കിടുകയും ...."
        EMERGENCY_INFO_SHARED -> "അപകട വിവരങ്ങൾ പങ്കിടുക!"
        EMERGENCY_INFO_SHARED_ACTION -> "നിങ്ങളുടെ അപകട ബന്ധുക്കൾ ഞങ്ങളും നമ്മ പിന്തുണ ടീമും നിങ്ങളുടെ ലൊക്കേഷനും വീഡിയോ ഉണ്ട്.\nക്രിറ്റിക്കൽ സന്ദര്‍ഭങ്ങളിൽ പോലീസ് യാത്രിയെ അറിയ്ക്കുന്നതിലേക്ക് എന്തെങ്കിലും ചെയ്യപ്പെടും."
        SET_UP_YOUR_PERSONAL_SAFETY_SETTINGS -> "നിങ്ങളുടെ വ്യക്തിഗത സുരക്ഷാ ക്രമങ്ങൾ സജീവമാക്കുക"
        ACTIVATE_LIVE_VIDEO_RECORDING_FEATURES -> "പ്രത്യക്ഷ വീഡിയോ റെക്കോർഡിംഗ് സജീവമാക്കുക"
        CHOOSE_RESPONSIVE_CONTACTS -> "നിനക്ക് പ്രതിസാധിക്കുന്ന സംരക്ഷണക്കാരുടെ നമ്പർ അല്ലെങ്കിൽ ഒരു സിറ്റി സുഹൃത്തിനെ തിരഞ്ഞെടുക്കുന്നതിന്, നഗരത്തിൽ ഒരു സുഹൃത്തായി നിനക്ക് സൂചിപ്പിക്കുന്നു."
        SHARE_LOCATION_AND_RIDE_DETAILS_EMERGENCY_CONTACT -> "നിങ്ങളുടെ അടിമ സംവാദികളുമായി ലൊക്കേഷൻ ഉം യാത്ര വിശദാംശങ്ങൾ പങ്കിടുക"
        NAMMA_SAFETY_MEASURES -> "സുരക്ഷാ മോഡ് മൊത്തം"
        SAFETY_GUIDELINES_FOR_YOU -> "നിങ്ങൾക്ക് സുരക്ഷാ ദിശകൾ"
        ABOUT_SOS -> "സുരക്ഷാ മോഡ് കുറിച്ച്"
        NIGHT_TIME_SAFETY_CHECKS -> "രാത്രിയുടെ സുരക്ഷാ പരിശോധനകൾ"
        SHARE_INFO_WITH_EMERGENCY_CONTACTS_TITLE -> "SOS ക്ലിക്ക്, വിവരങ്ങള്‍ പങ്കിടുക മറ്റുള്ളവരെ അപ്രത്യക്ഷ കരുതലുകൾ ആരംഭിക്കുക?"
        SHARE_INFO_WITH_EMERGENCY_CONTACTS_DESC -> "നിനക്ക് പ്രതിസാധിക്കുന്ന സംരക്ഷണക്കാരുടെ നമ്പർ അല്ലെങ്കിൽ ഒരു സിറ്റി സുഹൃത്തിനെ നിര്‍ബന്ധമായി തിരഞ്ഞെടുക്കുക."
        TRIGGER_ALERT_TO_NAMMAYATRI_SUPPORT_TITLE _ -> "നമ്മ യാത്രി പിന്തുണയ്ക്ക് അലേർട്ട് തുടങ്ങുക"
        TRIGGER_ALERT_TO_NAMMAYATRI_SUPPORT_DESC -> "24 * 7 ഡെഡികേറ്റഡ് പിന്തുണയ്ക്ക് ഞങ്ങൾ ഓട്ടോമാറ്റിക്കായി അലേർട്ട് നൽകും"
        ENABLE_NIGHT_TIME_SAFETY_ALERTS_TITLE -> "രാത്രി സമയത്ത് സുരക്ഷാ അലേർട്ടുകൾ പ്രാപ്തമാക്കുക?"
        ENABLE_NIGHT_TIME_SAFETY_ALERTS_DESC -> "നിങ്ങളുടെ സുരക്ഷയെ ഉറപ്പാക്കാൻ, <b><span style='color:#454545'>9 PM-6AM</span></b> വരെ, ഞങ്ങൾ ഡ്രൈവർമാർഗത്തിന്റെ അനോമലി കണക്ഷൻ അനുസരിച്ച് സുരക്ഷാ പരിശോധനാ അലർട്ടുകൾ അയയ്ക്കുകയാണ്। മാർഗ-വികൽപ്പന അല്ലെങ്കിൽ വാഹനം ചലിക്കുന്നില്ലാത്ത കാരണങ്ങളിൽ.<br><br>ഇത് സുരക്ഷാ മോഡ് സജീവമാണോ ഇല്ലാതെയോ അനുസരിച്ച് സംഭവിക്കും।"
        ALMOST_DONE_TITLE -> "പ്രായമേയുള്ളൂ!"
        ALMOST_DONE_DESC -> "ആകാശദർശനം സംഭാഷണത്തിലും, നിങ്ങൾ പോലീസ് ഹെൽ‌പ്ലൈൻകൊണ്ടൊഴുകുക അല്ലെങ്കിൽ സുരക്ഷാ സമസ്യ റിപ്പോർട്ട് ചെയ്യുക. ഇത് ചെയ്യേണ്ടതിനുള്ള അനുമതികൾ അനുവദിക്കുകയും"
        PERSONAL_SAFETY_SETTINGS_PERMISSION_REQUEST -> "(റെക്കോർഡുചെയ്യാനുള്ള സംബന്ധിയായ അനുമതി നൽകുക)"
        SAFETY_MEASURE_1 -> "ഡ്രൈവർ റൂട്ട് അനോമാലി ഡിറ്റക്ഷനിൽ അടിമ സമയത്തെ സുരക്ഷാ പരിശോധന"
        SAFETY_MEASURE_2 -> "സുരക്ഷ മോഡ് ബട്ടൺ."
        SAFETY_MEASURE_3 -> "ഡ്രൈവർ / കസ്റ്റമേഴ്സിനുള്ള പൂർണ പ്രതിസന്ധി നീതി"
        SAFETY_MEASURE_4 -> "കസ്റ്റമർ സ്വകാര്യത - ഡ്രൈവർമാര് യാത്ര പൂർണമായും കാണാൻ കഴിയില്ല"
        SAFETY_MEASURE_5 _ -> "എല്ലാ നമ്മ യാത്രി ഡ്രൈവേഴ്സിനെയും സുരക്ഷാ പ്രശിക്ഷണവും സർട്ടിഫിക്കറും"
        SAFETY_MEASURE_6 -> "ആപത്കാലത്തിനുള്ളിൽ ഒരു ലൈവ് വീഡിയോ റെക്കോർഡിംഗ് പങ്കെടുക്കുക."
        SAFETY_GUIDELINES_1 -> "ഡ്രൈവറുടെ അടിമത്തിനുള്ള ശരിയായ അടെന്റിഫിക്കേഷൻ പരിശോധിക്കുക"
        SAFETY_GUIDELINES_2 -> "റൂട്ടിനു കണ്ണ് തുറക്കുക"
        SAFETY_GUIDELINES_3 -> "രാത്രി യാത്രകളിൽ പ്രതിജ്ഞാപിക്കുക"
        SAFETY_GUIDELINES_4 -> "നിങ്ങൾ അസ്വസ്ഥമായാൽ, നിങ്ങളുടെ യാത്ര അടിമ സംവാദികൾക്കും പങ്കിടുക"
        SAFETY_GUIDELINES_5 -> "വ്യക്തിഗത വിവരങ്ങൾ പങ്കിടുകയില്ല"
        SAFETY_GUIDELINES_6 -> "ഇൻ-ആപ്പ് അടിമ സുരക്ഷാ ഫീച്ചർ ഉപയോഗിക്കുക"
        SAFETY_GUIDELINES_7 -> "ഒരു വിശ്വസനീയ സുരക്ഷിത കമ്മ്യൂണിറ്റി പരിപാലിക്കുവാനും അവലോകനം ചെയ്യിക്കുവാനും റേറ്റുചെയ്യുക"
        ABOUT_SOS_1 -> "ഡ്രൈവർ വ്യത്യസ്തമായ ദൂര സ്ഥലങ്ങളിലേക്ക് റീ-റൂട്ടിംഗ് ചെയ്യുക"
        ABOUT_SOS_2 -> "ഡ്രൈവർമാരുടെ അനുചിത/ഭൌതിക സൂചനകൾ"
        ABOUT_SOS_3 -> "നിങ്ങളുടെ സമ്മതമില്ലാതെ മറ്റ് പുരുഷ യാത്രകാരൻമാർ യാത്രയിൽ ചേർക്കുന്നു"
        ABOUT_SOS_4 -> "ഡ്രൈവർ അപ്രതീക്ഷിതമായി ഒരു ദൂര പ്രദേശത്ത് നിൽക്കുന്നു"
        ABOUT_SOS_5 -> "നാണയ പ്രശ്നങ്ങൾ"
        ABOUT_SOS_6 -> "മത്തപാനം ഡ്രൈവിംഗ്"
        ABOUT_SOS_7 -> "തുരക്കിംഗ് ഡ്രൈവിംഗ്"
        ABOUT_SOS_8 -> "വാഹന നമ്പർ പരിപാലിക്കൽ ചെയ്യരുത്"
        ABOUT_SOS_9 -> "യാത്രയിൽ സുരക്ഷാ മോഡ് ബട്ടൺ ടാപ്പ് ചെയ്യിക്കുകയാണ് സുരക്ഷാ മോഡ് സജീവമാക്കുക"
        ABOUT_SOS_10 -> "ശാന്തമായി ഉള്ളിൽക്കുക. ഭയക്കരുതുക"
        ABOUT_SOS_11 _ -> "അടിമ പങ്കിടുകയും, നിങ്ങളുടെ കുടുംബവും സുഹൃത്തുക്കളും / നമ്മ യാത്രി പിന്തുണയ്ക്ക് അറിയിക്കുക"
        ABOUT_SOS_12 -> "പോലീസ് ഹെൽപ്ലൈൻ (112) അറിയാൻ നിങ്ങൾക്ക് അവസാനം ചെയ്യാം"
        ABOUT_SOS_13 -> "സാധ്യമായാൽ, ഡ്രൈവർക്ക് അടിക്കുന്നതിനായി നക്ഷത്രപൂർണമായ പ്രദേശത്ത് വാഹനം നിൽക്കാനും അവൻറെ മനോഭാവത്തിനും സാധനങ്ങളിലൂടെ അവനെ അറിയിക്കാനും വാദിക്കാം"
        THE_VIDEO_WILL_BE_RECORDED -> "വീഡിയോ 15 സെക്കൻഡ് മാത്രം റെക്കോർഡുചെയ്യപ്പെടും, നിങ്ങളുടെ ക്രമീകരണങ്ങൾക്ക് പ്രകാരം പങ്കിടുകയും ചെയ്യും"
        EMERGENCY_VIDEO -> "അടിമ വീഡിയോ"
        NAMMA_SAFETY_IS_SET_UP -> "സുരക്ഷാ മോഡ് വിജയകരമായി സജീവമാക്കിയിരിക്കുന്നു"
        ACTIVATE_NAMMA_SAFETY_POPUP_TITLE -> "സുരക്ഷാ മോഡ്\n സജീവമാക്കുന്നതിന് താങ്കൾ തയ്യാറാണ്"
        ACTIVATE_NAMMA_SAFETY_POPUP_DESC -> "താങ്കളുടെ സുരക്ഷ ഞങ്ങളുടെ പ്രധാനമാണ്. നിലവിൽ അസ്വസ്ഥത കാരണമായ സാധ്യതകളിൽ മാത്രം സുരക്ഷ മോഡ് ഉപയോഗിക്കുക. ചൂടിനും അതിരുകളിലേക്കും തിരിച്ചറിയാന്‍ അതിന്റെ വ്യയം വേണ്ടിയാണ്"
        ACTIVATE_NAMMA_SAFETY_POPUP_ACTION -> "സജീവമാക്കുക സ്ഥിരീകരിക്കുക"
        DISMISS -> "നിരാകരിക്കുക"
        SEND_SILENT_SOS_TO_POLICE -> "പോലീസ് ഹെൽപ്പ്ലൈൻ സൈലന്റ് അപകട സന്ദേശം അയയ്ക്കുക"
        OUR_SAFETY_PARTNER -> "നമ്മുടെ സുരക്ഷാ\nപങ്കാളി"
        BANGALURU_CITY_POLICE -> "ബംഗളൂര് സിറ്റി\nപോലീസ്"
        GET_OPTIONS_TO_DIRECTLY_CALL_POLICE -> "പോലീസ് റിപ്പോർട്ട് നോക്കാൻ ഓപ്ഷനുകൾ ലഭിക്കും"
        SHARE_SOS_SILENTLY_WITH_POLICE -> "പോലീസ് ഹെൽപ്പ്ലൈൻ സൈലന്റ് അപകട സന്ദേശം അയയ്ക്കുക"
        CALL_AND_ALERT_THE_NEAREST_POLICE_CENTRE -> "അടുത്തുള്ള പോലീസ് കേന്ദ്രത്തിൽ വിളിച്ച് അറിയിക്കുക."
        SEND_A_SILENT_SOS_TO_THE_POLICE -> "പോലീസിന് ഒരു നിശബ്ദ എസ് ഒ എസ് സന്ദേശം അയയ്ക്കുക."
        SEND_A_VIDEO_RECORDING_TO_POLICE -> "പോലീസിന് ഒരു വീഡിയോ റെക്കോർഡിംഗ് അയയ്ക്കുക."
        SEND_VIDEO_TO_POLICE -> "15s വീഡിയോ\nപോലീസിന് അയക്കുക"
        FINISH_SETUP -> "സജ്ജീകരണം പൂർത്തിയാക്കുക"
        ACTIVATE_SOS -> "സജീവമാക്കുക"
        MARK_RIDE_AS_SAFE -> "റൈഡ് സുരക്ഷിതമാണെന്ന് അടയാളപ്പെടുത്തുക"
        EMERGENCY_INFO_SHARED_ACTION_POLICE -> "പോലീസ് അധികാരികൾക്ക് നിങ്ങളുടെ ലൊക്കേഷനും വീഡിയോയും ലഭിച്ചു. അവർ ഉടൻ തന്നെ നിങ്ങളെ ബന്ധപ്പെടുകയും അടിയന്തര നടപടി(കൾ) സ്വീകരിക്കുകയും ചെയ്യും."
        START_SETUP -> "സജ്ജീകരണം ആരംഭിക്കുക"
        SETUP_NOW -> "ഇപ്പോൾ സജ്ജീകരിക്കുക"
        NAMMA_SAFETY -> "സുരക്ഷ"
        COMPLETE_YOUR_NAMMA_SAFETY_SETUP_FOR_SAFE_RIDE_EXPERIENCE -> "സുരക്ഷ സജ്ജീകരണം പൂർത്തിയാക്കുക"
        CALL_SUPPORT_FOR_SAFETY _ -> "സുരക്ഷയിലേക്ക് പിന്തുണ\nവിഭാഗത്തിലേക്ക് വിളിക്കുക"
        WE_NOTICED_YOUR_RIDE_HASNT_MOVED -> "അനേകം സമയം നിങ്ങളുടെ ഡ്രൈവർ ഒരു സ്ഥലത്തിലേക്ക് സഞ്ചരിക്കാതെയിരുന്നു. നിങ്ങൾക്ക് പ്രയാണത്തിൽ ഭയമുണ്ടോ?"
        WE_NOTICED_YOUR_RIDE_IS_ON_DIFFERENT_ROUTE -> "നിങ്ങളുടെ ഡ്രൈവർ വ്യത്യസ്ത റൂട്ടിൽ സഞ്ചരിക്കുന്നതെന്ന് ഞങ്ങൾ കണ്ടെത്തിയുണ്ട്. നിങ്ങൾക്ക് സുരക്ഷിതമായ യാത്ര അനുഭവിക്കുന്നുണ്ടോ?"
        WE_ARE_HERE_FOR_YOU -> "ഞങ്ങൾ നിങ്ങൾക്കായി ഇവിടെയുണ്ട്!"
        I_NEED_HELP -> "എനിക്ക് സഹായം ആവശ്യമാണ്"
        I_FEEL_SAFE -> "എനിക്ക് സുരക്ഷിതത്വം തോന്നുന്നു"
        EVERYTHING_OKAY_Q -> "എല്ലാം ശരിയാണോ?"
        PLEASE_REMAIN_CALM_YOU_CAN_REQUEST_AN_IMMEDIATE_CALL -> "ദയവായി ശാന്തത പാലിക്കുക, ആവശ്യമെങ്കിൽ ഞങ്ങളിൽ നിന്ന് ഒരു അടിയന്തര കോൾ തിരികെ അഭ്യർത്ഥിക്കാം.\n\nകൂടുതൽ സുരക്ഷയ്ക്കായി നിങ്ങൾക്ക് മുകളിൽ വലതുവശത്തുള്ള എമർജൻസി എസ് ഒ എസ് ഫീച്ചറുകളും ഉപയോഗിക്കാം."
        RECEIVE_CALL_FROM_SUPPORT -> "പിന്തുണയിൽ നിന്ന് കോൾ സ്വീകരിക്കുക"
        ADD_CONTACTS -> "കോണ്ടാക്റ്റുകൾ ചേർക്കുക"
        VIDEO_SHARE_INFO_TO_POLICE -> "വീഡിയോ കേവിൻ സെക്കൻഡ് മാത്രമേ റെക്കോർഡ് ചെയ്യപ്പെടുകയുള്ളൂ, അത് വാട്സ്ആപ്പിൽ അരങ്ങേയും പോലീസ് അധികാരികൾക്ക് പങ്കുചേരാൻ ഉപയോഗിക്കുന്നു."
        CALL_POLICE_HELPLINE -> "പോലീസ് ഹെൽപ്പ് ലൈൻ വിളിക്കുക (112)"
        PLEASE_REMAIN_CALM_CALL_POLICE -> "ദയവായി ശാന്തമാകുക, ആവശ്യമെങ്കിൽ നിങ്ങൾക്ക് പോലീസ് ഹെൽ‌പ്‌ലൈൻ കൊണ്ട് കാൽ ചെയ്യാനാകും. കൂടുതൽ സുരക്ഷയിലുള്ളതായി നിങ്ങൾ സുരക്ഷാ മോഡ് സവിശേഷതകൾ ഉപയോഗിക്കാവുന്നതും തല വലിയ ഭാഗത്ത് ലഭ്യമാണ്."
        PLEASE_ALLOW_CAMERA_AND_MICROPHONE_PERMISSIONS -> "ദയവായി ക്യാമറ മറ്റും മൈക്രോഫോൺ അനുമതിപ്പെടുകയും അവയുടെ ഉപയോഗത്തിന് അനുവദിക്കുക."
        PERSONAL_SAFETY_ACTION_1 -> "പോലീസിനെ വിളിക്കുക (112)"
        PERSONAL_SAFETY_ACTION_2 _ -> "നമ്മ യാത്രി പിന്തുണയ്ക്ക് അറിയുക"
        PERSONAL_SAFETY_ACTION_2_POLICE -> "പോലീസിന് സൈലന്റ് എസ് ഒ എസ് അയയ്‌ക്കുക"
        PERSONAL_SAFETY_ACTION_3 -> "15 സെക്കൻഡ് ദൈർഘ്യമുള്ള ഒരു ചെറിയ വീഡിയോ റെക്കോർഡ് ചെയ്യുക."
        ACTIVATE_NAMMA_SAFETY_WILL_ENABLE_ACCESS -> "സുരക്ഷ സജീവമാക്കാൻ താങ്കൾ തയ്യാറാണ്. നിലവിൽ അസ്വസ്ഥത കാരണമായ സാധ്യതകളിൽ മാത്രം സുരക്ഷ മോഡ് ഉപയോഗിക്കുക. ചൂടിനും അതിരുകളിലേക്കും തിരിച്ചറിയാന്‍ അതിന്റെ വ്യയം വേണ്ടിയാണ്"
        RIDE_SHARE_AFTER_SIX_PM -> "9 PM മുതൽ 6 AM വരെ നിങ്ങളുടെ സഞ്ചാര അറിയിപ്പുകൾ ആപത്കാല കൊണ്ട് അയച്ചുകൊള്ളി."
        SELECT_PREFERRED_CONTACTS -> "പ്രിഫറുകളായ കോണ്ടാക്റ്റുകൾ തിരഞ്ഞെടുക്കുക"
        NEW -> "പുതിയത്"
        EMERGENCY_SOS -> "എസ് ഒ എസ്"
        SAFETY_CENTER -> "സുരക്ഷാ കേന്ദ്രം"
        AUTOMATIC_CALL_PLACED_TO_EMERGENCY_CONTACTS -> "ആപത്കാല കൊണ്ടാട്ടങ്ങൾക്ക് സ്വയം കോൾ ചെയ്തു വച്ചു."
        OPTION_TO_REPORT_A_SAFETY_ISSUE -> "സുരക്ഷ ഇഷ്യൂ റിപ്പോർട്ട് ചെയ്യാൻ ഒപ്ഷൻ"
        TEST_SAFETY_DRILL -> "സുരക്ഷ ഡ്രിൽ ടെസ്റ്റ് ചെയ്യുക"
        START_TEST_DRILL -> "ടെസ്റ്റ് ഡ്രിൽ ആരംഭിക്കുക"
        REPORT_SAFETY_ISSUE -> "സുരക്ഷ ഇഷ്യു റിപ്പോർട്ട് ചെയ്യുക"
        SHARE_RIDE -> "റൈഡ് പങ്കിടുക"
        SHARE_RIDE_WITH_CONTACT number -> number <> " കൊണ്ട് പങ്കാളികളോട് പങ്കാളികളോട് പങ്കാളികളോട്"
        SHARE_LINK -> "ലിങ്ക് പങ്കിടുക"
        GLAD_TO_KNOW_YOU_ARE_SAFE -> "നിങ്ങൾ സുരക്ഷിതരാണെന്ന് അറിയിക്കാൻ സന്തോഷം"
        TRY_ANOTHER_CONTACT -> "മറ്റൊരു ആപത്കാലിന കൊണ്ട് ബന്ധപ്പെടാന്‍ ശ്രമിക്കുക"
        YOUR_CURRENT_LOCATION -> "നിലവിലെ ലൊക്കേഷൻ"
        THIS_IS_NOT_A_REAL_SOS_SITUATION -> "ഇത് ഒരു പ്രതികരണം അല്ല"
        YOUR_VEHICLE_INFO -> "നിങ്ങളുടെ വാഹന വിവരങ്ങൾ"
        POLICE_VIEW_INSTRUCTION -> "ദയവായി ഓപ്പറേറ്ററിനെ നിങ്ങളുടെ സ്ഥാനം കൊടുക്കുക - ആപ്ലിക്കേഷൻ സ്വയംഭാവമായി സ്ഥാനം പങ്കുവെച്ചേക്കുന്നില്ല."
        TEST_SOS_ACTIVATING_IN -> "ടെസ്റ്റ് എസ്‌ഒഎസ് സജീവമാകുന്നു..."
        SOS -> "എസ് ഒ എസ്"
        TEST_SOS -> "ടെസ്റ്റ് എസ്\nഒ എസ്"
        SELECT_CONTACT_TO_CALL -> "വിളിക്കപ്പെടേണ്ട കോൺടാക്ട് തിരഞ്ഞെടുക്കുക"
        EMERGENCY_SOS_ACTIVATING -> "ആപത്കാല എസ് ഒ എസ് സജീവമാക്കുന്നു"
        PRESS_TO_START_TEST_DRILL -> "ടെസ്റ്റ് ഡ്രിൽ ആരംഭിക്കാൻ\nഅമർത്തുക"
        PRESS_THE_BUTTON_ON_EMERGENCY -> "ആപത്കാല എസ് ഒ എസ് സജീവമാക്കാൻ\nഅമർത്തുക"
        INFORM_EMERGENCY_CONTACTS -> "എന്നിടത്ത് അനാവശ്യകമായ ഹത്താരം പ്രതിരോധിക്കാനായി ദയവായി നിങ്ങളുടെ ആപത്കാലിന്‍ സംപർക്കങ്ങളെ അറിയിച്ചു പറയൂ"
        OTHER_SAFETY_ACTIONS -> "മറ്റു സുരക്ഷാ നടപടികൾ"
        AVAILABLE_IN_REAL_EMERGENCY -> "ആപത്കാലത്ത് ലഭ്യമാണ്"
        DISCLAIMER -> "ഡിസ്ക്ലൈമർ"
        USE_ONLY_IN_EMERGENCY -> "ആപത്കാലത്ത് മാത്രം ഉപയോഗിക്കുക"
        MISUSE_MAY_LEAD_TO_LEGAL_ACTION -> "അപകടപ്പെടുത്തിയാൽ നിങ്ങൾക്ക് നിയമപ്രകാരം ശിക്ഷിക്കപ്പെടാവുന്നതാണ്"
        USE_TEST_DRILL -> "ടെസ്റ്റ് ചെയ്യാൻ <span style='color:#2194FF'><u>ടെസ്റ്റ് സുരക്ഷാ ഡ്രിൽ</u></span> ഉപയോഗിക്കുക"
        ARE_YOU_READY_TO_START_DRILL -> "നിങ്ങൾ ഡ്രിൽ ആരംഭിക്കാൻ തയ്യാറാണോ?"
        TEST_DRILL_DESC -> "നിങ്ങൾ ഡ്രിൽ ആരംഭിക്കുന്നതിന് തയ്യാറാണോ? നിങ്ങൾ ആപത്കാല ബന്ധങ്ങൾക്ക് നമ്മായാത്രി ഇൻസ്റ്റാൾ ചെയ്യുന്നതിന് ശേഷം ഒരു വരുന്നത് എന്നെന്നേക്കും സുഗമമാക്കാനാണ് നങ്ങൾ സിഫറെ ചെയ്യുന്നത്"
        LEARN_ABOUT_SAFETY_MODE -> "സുരക്ഷ മോഡ് കുറിച്ച് അറിയുക"
        TEST_EMERGENCY_REQUEST_SENT -> "ടെസ്റ്റ് ആപത്കാല അഭ്യർത്ഥന അയയ്ക്കുന്നു"
        TEST_SOS_TRIGGERED_DESC -> "ഒരു വസ്തുതാക്കാർ സന്ദർശനത്തിൽ, നിങ്ങളുടെ സ്ഥാനം നിങ്ങളുടെ ആപത്കാല കൊൾസണോടു പങ്കെടുക്കുന്നു।"
        SOS_WILL_BE_DISABLED -> "മൂന്ന് തീയതി ദുരിതാശയായാല്‍ എസ്ഓഎസ് സുവിധ അക്ഷമമാകും."
        DIAL_NOW -> "ഇപ്പോൾ വിളിക്കുക"
        FOLLOWING name -> name <> "യെ പിന്തുടരുന്നു"
        TURN_OFF_ALARM -> "അലാറം ഓഫാക്കുക"
        CHOOSE_A_PERSON_TO_FOLLOW -> "പിന്തുടരാൻ ഒരാളെ തിരഞ്ഞെടുക്കുക"
        IS_IN_SOS_SITUATION name -> name <> " ഒരു SOS സാഹചര്യത്തിലാണ്!"
        MARKED_RIDE_SAFE name -> name <> " യാത്ര സുരക്ഷിതമായി അടയാളപ്പെടുത്തി!"
        STAY_CALM_KEEP_TRACKING name -> "ശാന്തത പാലിക്കുക. " <> name <> "ന്റെ സ്ഥാനം ട്രാക്ക് ചെയ്യുന്നത് തുടരുക, ആവശ്യമെങ്കിൽ ആവശ്യമായ നടപടികൾ കൈക്കൊള്ളുക"
        YOU_WILL_BE_NOTIFIED -> "റൈഡ് പൂർത്തിയാകുമ്പോൾ നിങ്ങളെ അറിയിക്കും"
        TAP_HERE_TO_FOLLOW name ->  name <> " പിന്തുടരാൻ ഇവിടെ ടാപ്പ് ചെയ്യുക"
        HAVE_SHARED_RIDE_WITH_YOU name -> name <> " അവരുടെ റൈഡുകൾ നിങ്ങളുമായി പങ്കിട്ടു"
        SOS_LOCATION -> "SOS ലൊക്കേഷൻ"
        THIS_IS_A_TEST_MOCK_DRILL name -> "ഇത് " <> name <> " ഒരു ടെസ്റ്റ് ഡ്രില്ലാണ്"
        THIS_IS_NOT_REAL_DRILL -> "ഇതൊരു യഥാർത്ഥ ഡ്രിൽ അല്ല, അടിയന്തിര സാഹചര്യങ്ങളിൽ ആപ്പ് എങ്ങനെ പ്രതികരിക്കുമെന്ന് ഇത് ലളിതമായി ചിത്രീകരിക്കുന്നു."
        REACHED_DESTINATION_SAFELY name -> name <> " സുരക്ഷിതമായി ലക്ഷ്യസ്ഥാനത്തെത്തി!"
        COMPLETE_YOUR_TEST_DRILL -> "നിങ്ങളുടെ ടെസ്റ്റ് ഡ്രിൽ പൂർത്തിയാക്കുക"
        TEST_DRILL -> "ടെസ്റ്റ് ഡ്രിൽ"
        RIDE_ENDED name -> name <> " യാത്ര അവസാനിച്ചു"
        RIDE_SHARED_WITH_SELECTED_CONTACTS -> "നിങ്ങളുടെ യാത്ര തിരഞ്ഞെടുത്ത കോണ്ടാക്റ്റുകൾക്ക് പങ്കിട്ടു"
        TERMS_AND_CONDITIONS_UPDATED -> "ടി&സിയും സ്വകാര്യതാ നയവും അപ്ഡേറ്റ് ചെയ്തിട്ടുണ്ട്"
        OKAY -> "ശരി ശരി"
        TRY_LATER -> "പിന്നീട് ശ്രമിക്കുക"
        REFERRAL_CODE_IS_APPLIED -> "റെഫറൽ കോഡ് പ്രയോഗിച്ചു"
        YOU_HAVE_ALREADY_USED_DIFFERENT_REFERRAL_CODE -> "നിനക്ക് ഇതിനകം ഒരു വ്യത്യസ്ത റെഫറൽ കോഡ് ഉപയോഗിച്ചിരി"
        INVALID_REFERRAL_CODE -> "അസാധുവായ റെഫറൽ കോഡ്"
        STOPS -> "നിരത്തികള്‍"
        GREEN_LINE -> "പച്ച വഴി"
        BLUE_LINE -> "നീല വഴി"
        RED_LINE -> "ചുവപ്പ് വഴി"
        VIEW_ROUTE_INFO -> "റൂട്ട് വിവരം കാണുക"
        VALID_UNTIL -> "ചെലവ് ചെയ്യേണ്ട തീയതി"
        TICKET_NUMBER -> "ടിക്കറ്റ് നമ്പർ"
        TICKET -> "ടിക്കറ്റ്"
        TICKETS -> "ടിക്കറ്റുകൾ"
        ONWORD_JOURNEY -> "മുന്നിൽ യാത്ര"
        ROUND_TRIP_STR -> "റൗണ്ട് ട്രിപ്പ്"
        TICKETS_FOR_CHENNAI_METRO -> "ചെന്നൈ മെട്രോക്കാർഡിനുള്ള ടിക്കറ്റുകൾ"
        ACTIVE_STR -> "സജീവം"
        EXPIRED_STR -> "കാലാവധി കഴിഞ്ഞു"
        USED_STR -> "ഉപയോഗിച്ചു"
        MAP_STR -> "മാപ്പ്"
        TICKET_DETAILS -> "ടിക്കറ്റ് വിവരങ്ങൾ"
        ROUTE_DETAILS -> "റൂട്ട് വിവരങ്ങൾ"
        UNCERTAIN_ABOUT_METRO_ROUTES -> "മെട്രോ റൂട്ടുകൾ കുറച്ചു താൽപ്പര്യപ്പെടുന്നുണ്ടോ?"
        SEE_MAP -> "മാപ്പ് കാണുക"
        CHENNAI_METRO_TERM_1 -> "ടിക്കറ്റ് റദ്ദാക്കൽ അനുവദനീയമല്ല"
        CHENNAI_METRO_TERM_2 -> "എല്ലാ ദിവസവും രാത്രി 4:30 മുതൽ 10:30 വരെ ടിക്കറ്റുകൾ വാങ്ങാൻ കഴിയും."
        NO_OF_PASSENGERS -> "യാത്രക്കാർക്കുള്ള എണ്ണം"
        MAXIMUM -> "പരമാവധി"
        TICKETS_ALLOWED_PER_USER -> "ഉപയോക്താവിന് അനുവദനീയമായ ടിക്കറ്റുകൾ."
        STARTING_FROM -> "ഇതിൽ നിന്ന്"
        FROM -> "നിന്ന്"
        TO -> "വരെ"
        BOOKING_ID -> "ബുക്കിംഗ് ഐഡി"
        PLEASE_WHILE_GEN_TICKET -> "ദയവായി നിന്ന് ഞങ്ങളുടെ ടിക്കറ്റ് സൃഷ്ടിക്കുന്നതിനു കാത്തിരിക്കുക"
        PAYMENT_RECEIVED -> "പേയ്മെന്റ് സ്വീകൃതം!"
        PLEASE_CHECK_BACK_FEW_MIN -> "ദയവായി കുറഞ്ഞതോളം മിനിറ്റ് ശേഖരിക്കുക."
        YOUR_BOOKING_PENDING -> "നിനക്ക് ബുക്കിംഗ് പാക്കറ്റിന് കാത്തിരിക്കുന്നു!"
        PLEASE_RETRY_BOOKING -> "ദയവായി ബുക്കിംഗ് പുനരാരംഭിക്കുക."
        BOOKING_FAILED -> "ബുക്കിംഗ് പരാജയപ്പെട്ടു!"
        INCASE_OF_FAIL -> "പരാജയപ്പെട്ടാൽ, 5 - 7 പ്രവർത്തന ദിനങ്ങൾ ക്രമേണ രിഫണ്ട് ചെയ്യപ്പെടും."
        REFRESH_STATUS -> "പുതുക്കുക സ്ഥിതി"
        DATE -> "തീയതി"
        NO_OF_TICKETS -> "ടിക്കറ്റുകൾക്കായി എണ്ണം"
        ACTIVE_TICKETS -> "സജീവ ടിക്കറ്റുകൾ"
        CONFIRMING_STR -> "സ്ഥിരീകരിക്കുന്നു"
        FAILED_STR -> "പരാജയപ്പെട്ടു"
        CONFIRMED_STR -> "സ്ഥിരീകരിച്ചു"
        BUY_METRO_TICKETS -> "മെട്രോ ടിക്കറ്റുകൾ വാങ്ങുക"
        GET_FARE -> "കടപ്പാട് ലഭ്യമാക്കുക"
        METRO_BOOKING_TIMINGS -> "മെട്രോ ബുക്കിംഗ് സമയം"
        CHENNAI_METRO_TIME startTime endTime  -> "ചെന്നൈ മെട്രോ 4:30 ബജി മുതൽ 10:30 ബജി വരെ ക്യൂആർ ടിക്കറ്റ് വാങ്ങാൻ അനുമതിക്കുന്നു."
        PLEASE_COME_BACK_LATER_METRO -> "ദയവായി പുനരാരംഭിക്കുക, ടിക്കറ്റ് വാങ്ങാൻ അനുമതിക്കുന്ന സമയത്തിൽ തിരികെ വാ."
        NO_QOUTES_AVAILABLE -> "ഉദ്ധാരണികൾ ലഭ്യമില്ല"
        I_AGREE_TO_THE -> "ഞാൻ അംഗീകരിക്കുന്നു"
        HERE_IS_METRO_TICKET -> "ഇതാണ് മെട്രോ ടിക്കറ്റ്!"
        VIEW_TICKET -> "ടിക്കറ്റ് കാണുക"
        DESTINATION -> "ലക്ഷ്യസ്ഥാനം"
        PAY -> "പേയ്‌മെന്റ്"
        PENDING_STR -> "പരിഹാരം കാത്തിരിക്കുന്നു"
        PAST_TICKETS -> "കഴിഞ്ഞ ടിക്കറ്റുകൾ"
        ONE_WAY_STR -> "ഒരു വഴി"
        SHARE_TICKET -> "ടിക്കറ്റ് പങ്കിടുക"
        TICKET_IS_NON_CANCELLABLE -> "ടിക്കറ്റ് റദ്ദാക്കാനാകില്ല"
        CANCEL_BOOKING -> "ബുക്കിംഗ് റദ്ദാക്കണോ?"
        BOOKING_NOT_CANCELLABLE -> "മെട്രോ ബുക്കിംഗ് നയം അനുസരിച്ച് ഈ ബുക്കിംഗ് റദ്ദാക്കാനാകില്ല"
        BOOKINGS_WILL_BE_CANCELLED -> "ഈ ബുക്കിംഗുമായി ബന്ധപ്പെട്ട എല്ലാ ടിക്കറ്റുകളും റദ്ദാക്കപ്പെടും."
        BOOKINGS_WILL_BE_CANCELLED_WITH_REFUND number -> "ഈ ബുക്കിംഗുമായി ബന്ധപ്പെട്ട എല്ലാ ടിക്കറ്റുകളും റദ്ദാക്കപ്പെടും, നിങ്ങൾക്ക് " <> number <> " റീഫണ്ട് ലഭിക്കും" 
        REFUND_NOT_APPLICABLE -> "ഈ ബുക്കിംഗിന് റീഫണ്ട് ബാധകമല്ല"
        YES_CANCEL_BOOKING -> "അതെ, ബുക്കിംഗ് റദ്ദാക്കുക"
        WOULD_YOU_LIKE_TO_PROCEED -> "നീ മുന്നോട്ട് പോകണോ?"
        BOOKING_CANCELLED -> "നിങ്ങളുടെ ബുക്കിംഗ് റദ്ദാക്കി"
        REFUND_IS_IN_PROCESS -> "നിങ്ങളുടെ റീഫണ്ട് പ്രക്രിയയിലാണ്. റീഫണ്ട് 3-4 പ്രവൃത്തി ദിവസങ്ങൾ വരെ എടുക്കും."
        TOTAL_REFUND -> "മൊത്തം റീഫണ്ട്"
        NUMBER_OF_TICKETS -> "ടിക്കറ്റുകളുടെ എണ്ണം"
        CANCELLATION_DATE -> "റദ്ദാക്കൽ തീയതി"
        TICKETS_FOR_KOCHI_METRO -> "കൊച്ചി മെട്രോയുടെ ടിക്കറ്റുകൾ"
        YOUR_BOOKED_TICKETS -> "നിങ്ങളുടെ ബുക്ക് ചെയ്ത ടിക്കറ്റുകൾ ഇവിടെ ദൃശ്യമാകും"
        PLAN_YOUR_JOURNEY -> "നിങ്ങളുടെ യാത്ര ആസൂത്രണം ചെയ്യുക"
        BOOK_ROUND_TRIP -> "ബുക്ക് റൗണ്ട് ട്രിപ്പ്"
        BY_PROCEEDING_YOU_AGREE -> "തുടർന്നുകൊണ്ട്, നിങ്ങൾ അംഗീകരിക്കുന്നു "
        TERMS_AND_CONDITIONS_FULL -> "നിബന്ധനകളും വ്യവസ്ഥകളും"
        EXPERIENCE_HASSLE_FREE_METRO_BOOKING appName -> "ഹാസിൽ-ഫ്രീ മെട്രോ ബുക്കിംഗ് അനുഭവിക്കുക " <> appName
        KOCHI_METRO_TERM_1 -> "എല്ലാ ദിവസവും രാവിലെ 5:00 മുതൽ 11:45 PM വരെ ടിക്കറ്റുകൾ വാങ്ങാം."
        KOCHI_METRO_TERM_2 -> "പ്രവേശനം ചെയ്തുകഴിഞ്ഞാൽ, യാത്രക്കാർ ലക്ഷ്യസ്ഥാനത്ത് നിന്ന് 120 മിനിറ്റിനുള്ളിൽ പുറത്തുകടക്കണം."
        KOCHI_METRO_TIME -> "എല്ലാ ദിവസവും രാവിലെ 5:00 മുതൽ രാത്രി 11:45 വരെ QR ടിക്കറ്റ് വാങ്ങാൻ കൊച്ചി മെട്രോ അനുവദിക്കുന്നു."
        BOOK_TICKET -> "ടിക്കറ്റ് ബുക്ക് ചെയ്യുക"
        ORIGIN -> "ഉത്ഭവം"
        HISTORY -> "ചരിത്രം"
        ALWAYS -> "എല്ലാ സമയങ്ങളിലും"
        ALWAYS_SHARE_DESC -> "എല്ലാ യാത്രകളിലും പരിചയസംബന്ധിയായ എന്നിട്ട് സഹായസംബന്ധിയായ പുനഃപ്രയോഗം സൃഷ്ടിക്കാൻ ട്രിപ്പ് നോട്ടീസുകൾ അയയ്ക്കുക."
        NIGHT_RIDES_SHARE -> "രാത്രിയിലുള്ള യാത്രകൾ (9 വരെ - 6 വരെ)"
        NIGHT_RIDES_DESC -> "രാത്രിയിലുള്ള യാത്രകൾക്ക് (9 വരെ - 6 വരെ) പരിചയസംബന്ധിയായ സഹായസംബന്ധിയായ പുനഃപ്രയോഗം സൃഷ്ടിക്കുക"
        NEVER -> "എന്തോനെങ്കിലും"
        NEVER_SHARE_DESC -> "എന്തോനെങ്കിലും യാത്രയുടെ അറിയിപ്പുകൾ അയയ്ക്കരുത്"
        SHARE_TRIP_NOTIFICATONS -> "യാത്ര നോട്ടീസുകൾ പങ്കിടുക"
        CALL_CUSTOMER_SUPPORT -> "കസ്റ്റമർ സപ്പോർട്ട് അറിയിക്കുക"
        YET_TO_START name -> name <> " ഇതുവരെ യാത്ര ആരംഭിക്കാതെ കിട്ടിയില്ല"
        MESSAGE_FROM name -> name <> " നിന്ന് സന്ദേശം"
        RIDE_CANCELLED -> "യാത്ര റദ്ദാക്കി"
        TRACK_RIDE_STRING appName driverName trackLink vehicleNumber -> "👋 ഹലോ,\n\nഞാൻ " <> appName <> " ഡ്രൈവർ " <> driverName <> " നും സഹായിക്കാൻ പോകുന്നു! ഈ റൈഡ് ട്രാക്കുചെയ്യുവാൻ: " <> trackLink <> "\n\nവാഹന നമ്പർ: " <> vehicleNumber        
        SAFETY_CENTER_IS_DISABLED -> "SOS സവിശേഷത മൂലം മികച്ചത് തർത്തി അപ്രയോഗിച്ചിരിക്കുന്നു"
        TRACK_ON_GOOGLE_MAP -> "Google മാപ്പിൽ ട്രാക്ക് ചെയ്യുക >"
        SHOW_WALKING_DIRECTION -> "നടക്കൽ മാർഗ്ഗസൂചി കാണിക്കുക >"
        SPECIAL_PICKUP_ZONE -> "പ്രത്യേക പിക്കപ്പ് പേരിന്"
        SPECIAL_PICKUP_ZONE_RIDE -> "പ്രത്യേക പിക്കപ്പ് പേരിന് റൈഡ്"
        WE_WILL_TRY_TO_CONNECT_YOU_WITH_DRIVER_IN_CLOSEST_PICKUP_ZONE -> "നികടത്തിൽ പ്രത്യേക പിക്കപ്പ് പേരിന് നിലവിലെ ചാലകനുമായി നാം നിങ്ങൾക്ക് കണക്ട് ചെയ്യാനോട് ശ്രമിക്കുകയും ചെയ്യും."
        THIS_PROVIDES_YOU_AN_INSTANT_PICKUP_EXPERIENCE -> "ഇത് നിങ്ങൾക്ക് തത്കാലം പിക്കപ്പ് അനുഭവം നൽകുന്നു."        
        DRIVER_AT_PICKUP_LOCATION -> "പിക്കപ്പ് സ്ഥലത്തില്‍ ഉള്ളു"        
        A_TIP_HELPS_FIND_A_RIDE_QUICKER -> "ഒരു നുറുങ്ങ് വേഗത്തിൽ ഒരു സവാരി കണ്ടെത്താൻ സഹായിക്കുന്നു!"
        TIP_ADDED -> "നുറുങ്ങ് ചേർത്തു!"
        CONTINUE_SEARCH_WITH_NO_TIP -> "നുറുങ്ങില്ലാതെ തിരയൽ തുടരുക"
        SEARCHING_WITH_NO_TIP -> "നുറുങ്ങില്ലാതെ തിരയുന്നു"
        SEARCH_AGAIN -> "വീണ്ടും തിരയുക"
        DRIVER_AT_PICKUP_LOCATION -> "നിങ്ങളുടെ ഡ്രൈവർ പിക്കപ്പ് സ്ഥലത്താണ്"
        DRIVER_IS_ON_THE_WAY -> "നിങ്ങളുടെ ഡ്രൈവർ വഴിയിലാണ്"
        DRIVER_IS_WAITING_AT_PICKUP -> "നിങ്ങളുടെ ഡ്രൈവർ പിക്കപ്പിൽ കാത്തിരിക്കുന്നു"
        IS_AT_PICKUP_LOCATION -> "പിക്കപ്പ് സ്ഥലത്തില്‍ ഉള്ളു"
        GO_TO_SELECTED_SPOT_FOR_PICKUP -> "പിക്കപ്പിന് തിരഞ്ഞെടുത്ത സ്ഥലത്തിലേക്ക് പോകുക"
        SELECT_POPULAR_SPOT_FOR_HASSLE_FREE_PICKUP -> "തിരഞ്ഞെടുത്ത വിശേഷിപ്പിച്ച പിക്കപ്പിന് കൊടുങ്കല്ല് ഒരു പ്രശസ്ത സ്ഥലം തിരഞ്ഞെടുക്കുക"
        THIS_PROVIDES_YOU_AN_INSTANT_PICKUP_EXPERIENCE -> "ഇത് നിങ്ങൾക്ക് തത്കാലം പിക്കപ്പ് അനുഭവം നൽകുന്നു."
        IS_AT_PICKUP_LOCATION -> "പിക്കപ്പ് സ്ഥലത്തില്‍ ഉള്ളു"
        PREPARE_EMERGENCY_CONTACTS -> "യഥാർത്ഥ ആപത്തികളിൽ പുരോഗമിക്കാൻ അടുത്ത തിരിച്ചറിയുക!"
        EMERGENCY_CONTACTS_WILL_BE_NOTIFIED -> "ആപത്തു ബട്ടൺ ക്ലിക്ക് ചെയ്താൽ എസ്ഒഎസ് ക്ലിക്ക് ചെയ്തുപോലും എന്നെത്തിക്കുന്നതിനും അലാർമുചെയ്യപ്പെടും."
        INFORM_EMERGENCY_CONTACTS_ABOUT_TEST -> "അനാവശ്യകമായ ഹത്താരം പ്രതിരോധിക്കാനായി ദയവായി നിങ്ങളുടെ ആപത്കാലിന്‍ സംപർക്കങ്ങളെ അറിയിച്ചു പറയൂ"
        RECENT_RIDE_ISSUE_DESC -> "നിങ്ങളുടെ അടുത്ത റൈഡിൽ സമസ്യകൾ ഉണ്ടെങ്കിൽ, താഴെയുള്ള ഓപ്ഷനുകൾ തിരഞ്ഞെടുക്കുക."
        I_NEED_HELP_WITH_MY_RECENT_RIDE -> "എനിക്ക് എന്റെ അടുത്ത റൈഡിൽ സഹായം ആവശ്യമുണ്ട്"
        CONTINUE_WITH_SAFETY_SETTINGS -> "സുരക്ഷ ക്രമീകരണങ്ങൾ തുടരുക"
        TAP_WHERE_TO_TO_BOOK_RIDE -> "നിങ്ങളുടെ റൈഡ് ബുക്ക് ചെയ്യാൻ 'എവിടെയാണ്?' ടാപ്പ് ചെയ്യുക!"
        LAST_CHOSEN_VARIANT_NOT_AVAILABLE -> "അവസാനം തെരഞ്ഞെടുത്ത റൈഡ് തരം ലഭ്യമല്ല. ദയവായി മറ്റ് റൈഡ് ഓപ്ഷനുകൾ തിരഞ്ഞെടുക്കുക"
        TOLL_CHARGES -> "ടോൾ ചാർജുകൾ"
        TOLL_CHARGES_DESC -> "യാത്രയ്ക്കിടെ ഉണ്ടാകുന്ന ഏതൊരു ടോൾ ചാർജും നിങ്ങളുടെ നിരക്കിൽ ഉൾപ്പെടുത്തിയിട്ടുണ്ട്."
        TOLL_CHARGES_INCLUDING amount -> "ടോൾ ചാർജുകൾ " <> amount <> " നിരക്കിൽ ഉൾപ്പെടുത്തിയിട്ടുണ്ട്"
        TOLL_ROAD_CHANGED -> "ടോൾ നിരക്കുകൾ ബാധകമല്ല"
        PARKING_CHARGES -> "പാർക്കിംഗ് ചാർജുകൾ"
        PARKING_CHARGES_DESC -> "ഡ്രൈവർ ഈടാക്കുന്ന പാർക്കിംഗ് നിരക്കുകൾ നിരക്കിൽ ഉൾപ്പെടുത്തിയിട്ടില്ല. ഇത് ഡ്രൈവറും യാത്രക്കാരനും തമ്മിലുള്ള യാത്രയ്ക്ക് ശേഷം തീർപ്പാക്കേണ്ടതാണ്."
        TOLL_OR_PARKING_CHARGES -> "^ടോൾ/ പാർക്കിംഗ് ചാർജുകൾ"
        TOLL_CHARGES_ESTIMATED -> "ടോൾ ചാർജുകൾ (കണക്കാക്കിയത്)^"
        ADD_TIP -> "നുറുങ്ങ് ചേർക്കുക"
        CHANGE_RIDE_TYPE -> "റൈഡ് തരം മാറ്റുക"
        TRY_ADDING_TIP_OR_CHANGE_RIDE_TYPE -> "നുറുങ്ങ് ചേർക്കുക അല്ലെങ്കിൽ റൈഡ് തരം മാറ്റുക"
        APPLICABLE_TOLL_CHARGES -> "പ്രയോജ്യമായ ടോൾ ശുല്കങ്ങൾ നിരക്കുകളിൽ ഉൾപ്പെടുത്തപ്പെട്ടിട്ടുള്ളൂ"
        UPDATE_TIP_STR -> "നുറുങ്ങ് അപ്ഡേറ്റ് ചെയ്യുക"
        WHO_CAN_TRACK_YOUR_RIDE appName -> appName <>" ആപ്പിൽ ആരും നിങ്ങളുടെ റൈഡ് ട്രാക്ക് ചെയ്യാവുന്നുണ്ടോ?"
        EMERGENCY_CONTACTS_CAN_FOLLOW appName -> appName <>" ആപ്പിൽ നിങ്ങളുടെ എമർജൻസി കോൺടാക്റ്റുകൾ നിങ്ങളുടെ റൈഡ് അനുസരിക്കാനും എമർജൻസി പ്രതിക്രിയ നൽകാനും കഴിയും"
        ALERT_SAFETY_TEAM appName -> appName <>" സുരക്ഷാ ടീമിനെ അറിയിക്കുക"
        RECOMMEND_EMERGENCY_CONTACTS_TO_INSTALL appName -> "നിങ്ങളുടെ എമർജൻസി കോൺടാക്റ്റുകൾക്ക് ഹൈക്കോളായ ട്രാക്കിംഗ് അനുഭവത്തിനായി "<> appName <>" ഇൻസ്റ്റാൾ ചെയ്യാൻ ഞങ്ങൾ ശിഫാരസിക്കുന്നു"
        SAFETY_TEAM_WILL_BE_ALERTED appName -> "SOS വഴി "<> appName <>" സുരക്ഷ ടീമിന് അറിയിക്കപ്പെടും"
        EMERGENCY_CONTACTS_CAN_TAKE_ACTION appName -> appName <>" ആപ്പിൽ നിങ്ങളുടെ എമർജൻസി കോൺടാക്റ്റുകൾ പ്രതിക്രിയ നൽകാം"
        SHARE_RIDE_DESCRIPTION appName -> "ഇത് തിരഞ്ഞെടുത്താല്‍ "<> appName <>" നിങ്ങളുടെ എമർജൻസി കോൺടാക്റ്റുകളിലേക്ക് അപ്ലിക്കേഷൻ പുഷ് നോടിഫിക്കേഷൻ അയയ്ക്കും"
        PLEASE_STAY_CALM_TEAM_ALERTED appName -> "ദയവായി ശാന്തമായി ഇരുക്കുക, "<> appName <>" സുരക്ഷ ടീമ് അറിയിക്കപ്പെടുന്നു!"
        INDICATION_TO_EMERGENCY_CONTACTS appName -> appName <>" നിങ്ങളുടെ എമർജൻസി കോൺടാക്റ്റുകൾക്ക് ഇത് ഒരു പരീക്ഷണ പരിശീലനമായി ഇരിക്കുന്നുവെന്ന് സൂചിപ്പിക്കുന്നു."
        BOOK name -> "ബുക്ക് " <> name
        FARE_FOR limit -> limit <> " കോടതി"
        WAITING_CHARGE_LIMIT timeLimit -> "കാത്തിരിക്കൽ ചാർജുകൾ ("<> timeLimit <>" മിനിറ്റ് ശേഷം)"
        TIME_TAKEN -> "മൊത്തം സമയം"
        TRIP_DISTANCE -> "യാത്ര ദൂരം"
        UNABLE_TO_CANCEL_RIDE -> "റൈഡ് റദ്ദാക്കാനായി കഴിയില്ല"
        GOT_A_REFERRAL_FROM_A_DRIVER_OR_FRIEND -> "ഡ്രൈവറോ അല്ലെങ്കിൽ സുഹൃത്തോ നിങ്ങളുടെ റെഫറൽ കോഡ് ലഭിച്ചു?"
        ENTER_REFERRAL_CODE_ -> "റെഫറൽ കോഡ് നൽകുക"
        REFERRED_USERS -> "റെഫറൽ ചെയ്ത ഉപയോക്താക്കൾ"
        SHOW_APP_QR -> "ആപ്ലിക്കേഷൻ QR കാണിക്കുക"
        SHARE_AND_REFER -> "പങ്കിടുകയും റെഫറൽ ചെയ്യുകയും"
        YOUR_REFERRAL_CODE -> "നിങ്ങളുടെ റെഫറൽ കോഡ്"
        REFER_YOUR_FRIENDS -> "നിങ്ങളുടെ സുഹൃത്തുക്കളെ റെഫറൽ ചെയ്യുക"
        REFERRALS -> "റെഫറൽ‌സ്"
        ENTER_NOW -> "ഇപ്പോൾ നൽകുക"
        WHAT_IS_REFERRAL_PROGRAM -> "റെഫറൽ പ്രോഗ്രാം എന്താണ്?"
        USERS_WHO_DOWNLOAD_APP_AND_COMPLETE_THEIR_FIRST_RIDE_USING_REFERRAL_CODE appName -> "നിങ്ങൾക്ക് " <> appName <> " ആപ്പ് ഡൗൺലോഡ് ചെയ്യുന്ന ഉപയോക്താക്കൾക്ക് ആദ്യ റൈഡ് പൂർത്തിയാക്കി ഉപയോക്താവായി റെഫറൽ കോഡ് ഉപയോഗിച്ച് ചെയ്യുന്ന ഉപയോക്താക്കൾ എണ്ണം ചെയ്യപ്പെടും. <br><br> <i>റെഫറൽ കോഡ് സൈൻ അപ്പ് ചെയ്യുമ്പോൾ നല്കാം.</i>"
        THE_REFERRAL_PROGRAM_INCENTIVISES_DRIVERS_TO_ACCEPT_MORE_RIDES appName -> "റെഫറൽ പ്രോഗ്രാം ഡ്രൈവറുകൾക്ക് കൂടുതൽ റൈഡുകൾ സ്വീകരിക്കാൻ പ്രചോദിപ്പിക്കുന്നു, കുറവ് റൈഡുകൾ റദ്ദ് ചെയ്യാൻ അവർക്ക് അവകാശമുണ്ടാക്കുക, യോഗ്യതാരും പ്രതിഫലിക്കുന്നതിനായി മറ്റുള്ള ഡ്രൈവറുകളെ ഗ്രഹിക്കാനും നിങ്ങളുടെ ഡ്രൈവറിന്റെ റെഫറൽ കോഡ് നൽകി " <> appName <> " സമുദായത്തിന് റൈഡുകളുടെ ഗുണമടുക്കാനാകും! <br><br> <i>നിങ്ങൾ " <> appName <> " ഡ്രൈവറും ഉപയോക്താവും ഒരു റെഫറൽ കോഡ് നൽകി ലഭിക്കാം.</i>"
        INVALID_CODE -> "അസാധുവായ കോഡ്!"
        ENTER_6_DIGIT_REFERRAL_CODE_BELOW -> "താഴെ 6 അക്കം റെഫറൽ കോഡ് നൽകുക"
        APPLY -> "അപേക്ഷിക്കുക"
        TOLL_CHARGES_INCLUDED -> "ടോൾ ചാർജുകൾ ഉൾപ്പെടുത്തിയിട്ടുണ്ട്"
        ONE_CLICK_BOOKINGS -> "ഒരു ക്ലിക്ക് ബുക്കിംഗുകൾ"
        HAS_YOUR_DRIVER_SET_THE_AC_AS_PER_YOUR_PREFERENCE -> "നിങ്ങളുടെ ഡ്രൈവർ എന്തുപോലെ ആസ്വദിക്കുന്നത് പുനഃപ്രയോഗിച്ചുകൊണ്ടാണ്?"
        NO_REPORT_AN_ISSUE -> "ഇല്ല, ഒരു സമസ്യ റിപ്പോർട്ട് ചെയ്യുക"
        GREAT_ENJOY_THE_TRIP -> "വളരെ നന്ദി! യാത്ര ആസ്വദിക്കുക"
        ENJOY_YOUR_BUDGET_FRIENDLY_NON_AC_RIDE -> "നിങ്ങളുടെ ബജറ്റ് സൗഹൃദമായ\nനോൺ-AC റൈഡ് ആസ്വദിക്കുക"
        AC_IS_NOT_AVAILABLE_ON_THIS_RIDE -> "ഈ റൈഡിൽ എസി ലഭ്യമല്ല"
        AC_NOT_WORKING_DESC -> "എസി പ്രവർത്തിക്കുന്നില്ല / ഡ്രൈവർ ഓണ് ചെയ്യാനായി നിരാകരിച്ചു"
        SHOWING_FARE_FROM_MULTI_PROVIDER -> "ഒന്നിലധികം ദാതാക്കളിൽ നിന്നുള്ള നിരക്കുകൾ കാണിക്കുന്നു"
        LIVE_CHAT -> "തത്സമയ ചാറ്റ്"
        DRIVER_TIP_ADDITION -> "ഡ്രൈവർ നുറുങ്ങ് കൂട്ടിച്ചേർക്കൽ"
        LIVE_RIDE_SHARING -> "തത്സമയ റൈഡ് പങ്കിടൽ"
        ENHANCED_SAFETY -> "മെച്ചപ്പെടുത്തിയ സുരക്ഷ"
        CONFIRM_PROVIDER -> "ദാതാവിനെ സ്ഥിരീകരിക്കുക"
        SELECT_A_PROVIDER -> "ഒരു ദാതാവിനെ തിരഞ്ഞെടുക്കുക"
        CONFIRMING_SELECTED_PROVIDER -> "ഇതിൽ തിരഞ്ഞെടുത്ത ദാതാവിനെ സ്ഥിരീകരിക്കുന്നു: "
        BOOK_TOP_PROVIDER -> "ബുക്ക് ടോപ്പ് പ്രൊവൈഡർ"
        CHOOSE_FROM_PROVIDERS -> "ലഭ്യമായ എല്ലാ ദാതാക്കളിൽ നിന്നും തിരഞ്ഞെടുക്കുക"
        CHOOSE_BETWEEN_PROVIDERS -> "ഒന്നിലധികം ദാതാക്കൾക്കിടയിൽ തിരഞ്ഞെടുക്കുക"
        CHOOSE_BETWEEN_PROVIDERS_DESC -> "ലഭ്യമായ എല്ലാ ദാതാക്കളിൽ നിന്നും ഉദ്ധരണികൾ കാണുന്നതിന് ഈ സവിശേഷത പ്രവർത്തനക്ഷമമാക്കുക."
        GUARANTEED_RIDE -> "ഗ്യാരണ്ടിഡ് റൈഡ്"
        THIS_RIDE_FULFILLED_BY provider -> "ഈ റൈഡ് പൂർത്തിയാക്കിയത്: " <> provider
        ADDITIONAL_FEATURES_ON merchantName -> merchantName <> " ഉപയോഗിച്ച് അധിക പ്രയോജനങ്ങൾ അനുഭവിക്കുക"
        NOTIFY_YOUR_EC -> "നിങ്ങളുടെ സ്വകാര്യ അടിയന്തര കോൺടാക്റ്റുകളെ അറിയിക്കുക"
        EC_CAN_RESPOND -> "അടിയന്തര കോൺടാക്റ്റുകൾക്ക് പിന്തുടരാം/അടിയന്തര പ്രതികരണ നടപടികൾ സ്വീകരിക്കാം"
        QUICK_SUPPORT merchantName -> "" <> merchantName <> " SOS പിന്തുണയിൽ നിന്നുള്ള ദ്രുത പിന്തുണ"
        LEARN_ABOUT_APP_SAFETY_FEAT merchantName -> "" <> merchantName <> "ലെ സവിശേഷമായ സുരക്ഷാ ഫീച്ചറുകളെ കുറിച്ച് അറിയുക"
        OTHER_PROVIDER_NO_RECEIPT -> "മറ്റ് ദാതാക്കൾ നിറവേറ്റിയ റൈഡുകളുടെ ഡ്രൈവർ രസീത് ഇതുവരെ ലഭ്യമല്ല."
        RIDE_FULFILLED_BY merchantName-> "റൈഡ് പൂർത്തിയാക്കിയത്: " <> merchantName
        CONGESTION_CHARGES -> "തിരക്ക് ചാർജ്*"
        TIP_CAN_BE_ADDED maxTip -> "റൈഡ് ഫേയിർക്കുള്ള ടിപ്പ് അപ്ടിൽ ₹" <> maxTip <> " വരെ ചേർത്തുകൂടാവുന്നു"
        CONGESTION_CHARGES_DESC charges -> "*നിങ്ങളുടെ യാത്രയിൽ നിലവിൽ "<> charges <>"% തിരക്ക് ചാർജ് ബാധകമാണ്, ഡ്രൈവറുടെ സമയത്തിന് തിരക്കുള്ള സമയം പ്രതിപൂരിപ്പിക്കുന്നതിനോ നിങ്ങൾക്കായി കൂടുതൽ ഡ്രൈവർമാരെ ലഭ്യമാക്കുന്നതിനോ."
        AC_TURNED_OFF -> "എസി ഓഫ് ചെയ്തു"
        BOOK_ANY -> "ബുക്ക് ഏതെങ്കിലും"
        ESTIMATES_EXPIRY_ERROR -> "എസ്റ്റിമേറ്റുകൾ കാലഹരണപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക."
        ESTIMATES_EXPIRY_ERROR_AND_FETCH_AGAIN -> "എസ്റ്റിമേറ്റുകൾ കാലഹരണപ്പെട്ടു. വീണ്ടും നേടുക, ദയവായി ക്ഷണം കാത്തുകൊണ്ട് വീണ്ടും പരിശോധിക്കുക."
        QUOTES_EXPIRY_ERROR_AND_FETCH_AGAIN -> "ക്വോട്ടുകൾ കാലഹരണപ്പെട്ടു. വീണ്ടും കൊണ്ടുവരുന്നു, ദയവായി ഒരു നിമിഷം കാത്തിരിക്കുക വീണ്ടും പരിശോധിക്കുക."
        PAY_YOUR_DRIVER_BY_CASH_OR_UPI -> "നിങ്ങളുടെ ഡ്രൈവറിനെ നിക്ഷേപം അല്ലെങ്കിൽ UPI ഉപയോഗിച്ച് പണം നൽകുക"
        TRIP_DELAYED -> "യാത്ര വിലക്കിയിരിക്കുന്നു"
        SELECT_VEHICLE -> "വാഹനം തിരഞ്ഞെടുക്കുക"
        BOOK_RENTAL -> "റെന്റല്‍ ബുക്ക് ചെയ്യുക"
        CONFIRM_RENTAL -> "റെന്റല്‍ സ്ഥിരീകരിക്കുക"
        RENTAL_RIDE -> "റെന്റല്‍ റൈഡ്"
        SELECT_DURATION -> "കാലാവധി തിരഞ്ഞെടുക്കുക"
        SELECT_DISTANCE -> "ദൂരം തിരഞ്ഞെടുക്കുക"
        RENTAL_OPTIONS -> "റെന്റൽ ഓപ്ഷനുകൾ"
        BOOKING_ON -> "ബുക്കിങ് ഓൺ"
        INCLUDED_KMS -> "അംഗീകൃതമായ കിലോമീറ്റർ:"
        BASE_FARE -> "ബേസ് ഫെയർ:"
        TOLLS_AND_PARKING_FEES -> "ടോൾസ് ആൻഡ് പാർക്കിങ്ങ് ഫീസ്"
        FINAL_FARE_DESCRIPTION -> "അവസാന കിരായ യാത്രാ അവധി തെളിഞ്ഞവയായ പോലെ എണ്ണമുടക്കിയ പുതിയ അല്ലെങ്കിൽ ആരംഭിച്ച സമയ അവധിക്ക് അനുയോജ്യമായതോ (എന്നാൽ ഏതേനെങ്കിലും ഉച്ചമായതോ) അവസാന കിരായ ആകുന്നു."
        EXCESS_DISTANCE_CHARGE_DESCRIPTION charges -> "അധിക ദൂരത്തിന് " <> charges <> " എന്ന നിരക്കിൽ നിരക്ക് ഈടാക്കും"
        ADDITIONAL_CHARGES_DESCRIPTION -> "അവസാന ഫെയർ വാസ്തവയിലുള്ള യാത്രാ അവധിയും ദൂരവും അടിയന്തരമായി അടിസ്ഥാനമാകും"
        PARKING_FEES_AND_TOLLS_NOT_INCLUDED -> "പാർക്കിംഗ് ഫീസ്, <b> ടോൾ ചാർജുകൾ </b> മറ്റ് അധിക ചിലവുകൾ <b> ഉൾപ്പെടുത്തിയിട്ടില്ല </b>. ദയവായി ഇവ ഡ്രൈവർക്ക് പ്രത്യേകം അടയ്ക്കുക."
        NIGHT_TIME_FEE_DESCRIPTION -> "നിങ്ങളുടെ യാത്രയുടെ ഏതെങ്കിലും ഭാഗം രാത്രി 10:00 നും 5:00 AM നും ഇടയിൽ സംഭവിക്കുകയാണെങ്കിൽ, {} എന്ന ഫ്ലാറ്റ് നൈറ്റ് ടൈം ഫീസ് നിങ്ങളുടെ റൈഡിന് ബാധകമാകും."
        CHOOSE_YOUR_RENTAL_RIDE -> "നിനക്ക് നിനക്ക് വാഹനം തിരഞ്ഞെടുക്കുക"
        FIRST_STOP_OPTIONAL -> "ആദ്യ സ്റ്റോപ്പ് (ഐച്ഛികം)"
        JANUARY -> "ജനുവരി"
        FEBRUARY -> "ഫെബ്രുവരി"
        MARCH -> "മാർച്ച്"
        APRIL -> "ഏപ്രിൽ"
        MAY -> "മേയ്"
        JUNE -> "ജൂൺ"
        JULY -> "ജൂലൈ"
        AUGUST -> "ആഗസ്റ്റ്"
        SEPTEMBER -> "സെപ്റ്റംബർ"
        OCTOBER -> "ഒക്ടോബർ"
        NOVEMBER -> "നവംബർ"
        DECEMBER -> "ഡിസംബർ"
        HOURS -> "മണിക്കൂർ"
        NOT_ADDED_YET -> "ഇനിയും ചേർക്കാൻ പറ്റിയില്ല"
        NEXT_STOP -> "അടുത്ത സ്റ്റോപ്പ്"
        TIME -> "സമയം"
        DISTANCE -> "ദൂരം"
        STARTING_ODO -> "ആരംഭ ODO"
        END_OTP -> "അവസാന OTP"
        ONLY_LOCATION_WITHIN_CITY_LIMITS -> "നഗര പരിമിതിക്കുള്ളിലെ സ്ഥാനങ്ങളാണ് കാർ ഉപയോഗിക്കാൻ യോഗ്യത."
        RIDE_TIME -> "സവാരാ സമയം"
        RIDE_DISTANCE -> "സവാരാ ദൂരം"
        RIDE_STARTED_AT -> "സവാരാ ആരംഭിച്ചു"
        RIDE_ENDED_AT -> "സവാരാ അവസാനിച്ചു"
        ESTIMATED_FARE -> "അനുമാനിച്ച നിരക്ക്"
        EXTRA_TIME_FARE -> "അതിരുക്കാനുള്ള സമയ വില"
        TOTAL_FARE -> "ആകെ നിരക്ക്"
        FARE_UPDATE -> "നിരക്ക് അപ്ഡേറ്റ്"
        NOW -> "ഇപ്പോൾ"
        DATE_INVALID_MESSAGE -> "തീയതി അസാധുവാണ്. ബുക്കിംഗ് നിശ്ചയമായി {} ദിവസങ്ങളേക്ക് മുന്നോട്ടു മാത്രം ലഭ്യമാണ്"
        EDIT_PICKUP -> "പിക്കപ്പ് എഡിറ്റ് ചെയ്യുക"
        ADD_STOP ->  "സ്റ്റോപ്പ് ചേർക്കുക"
        ENTER_PICKUP_LOC ->  "പിക്കപ്പ് സ്ഥാനം നമുക്ക് പ്രവേശിപ്പിക്കുക"
        INTERCITY_OPTIONS -> "ഇന്റർസിറ്റി ഓപ്ഷനുകൾ"
        PROCEED -> "പുരോഗമിക്കുക"
        SCHEDULE_RIDE_AVAILABLE -> "ഇപ്പോൾ മാത്രമേ 30 മിനിറ്റിൽ ലഭ്യമായി റൈഡ് ഷെഡ്യൂൽ ചെയ്യാവുന്നു"
        RENTAL_RIDE_UNTIL -> "നിങ്ങൾ രെന്റൽ റൈഡിൽ ഉണ്ടെന്ന്"
        EXTRA_TIME_CHARGES -> "അതിരിക്കാനുള്ള സമയ ചാർജ്"
        DIST_BASED_CHARGES -> "ദൂരം അടിസ്ഥാന ചാർജുകൾ"
        TIME_BASED_CHARGES ->  "സമയ അടിസ്ഥാന ചാർജുകൾ"
        RENTAL_POLICY -> "വാടക നയം"
        SELECT_PACKAGE -> "പാക്കേജ് തിരഞ്ഞെടുക്കുക"
        RENTAL_POLICY_DESC -> "ഓരോ മണിക്കൂറിലും നിങ്ങൾക്ക് 10 കിലോമീറ്റർ പാക്കേജിൽ ലഭിക്കും. നിങ്ങൾക്ക് ഒരു പരിധി വരെ അധിക കിലോമീറ്ററുകൾ പ്ലാൻ ചെയ്യാനും അടിസ്ഥാന ദൂരം കവിയുകയാണെങ്കിൽ അധിക ചിലവുകൾ ലാഭിക്കാനും കഴിയും."
        RENTAL_POLICY_DESC_1 -> "ബുക്കിംഗ് സ്ഥിരീകരിക്കുന്നതിന് മുമ്പ് അടുത്ത സ്ക്രീനിൽ നിരക്ക് അവലോകനം ചെയ്യുക"
        RENTALS_INTERCITY_AVAILABLE appName -> "റെന്റലുകൾ മറ്റ് ഇന്റർസിറ്റി ട്രിപ്പുകൾ, ഇപ്പോൾ " <> appName <> " യിൽ ലഭ്യമാണ്"
        CHECK_IT_OUT -> "അത് ചെക്ക് ചെയ്യുക"
        FAILED_TO_CANCEL -> "പയന്നതിന്‌ പരാജയപ്പെട്ടു"
        SCHEDULING_ALLOWED_IN_INTERCITY_RENTAL -> "അന്തർനഗര അല്ലെങ്കിൽ വാടക യാത്രകളിൽ മാത്രമേ ഷെഡ്യൂലിംഗ് അനുവദനീയമാണ്."
        SPECIAL_ZONE_INTERCITY_INELIGIBLE -> "പ്രത്യേക മേഖലയിലുള്ള സ്ഥലങ്ങൾ അന്തർനഗര യാത്രകൾക്ക് അയോഗ്യമാണ്."
        NO_RIDES_SCHEDULED_YET -> "ഇതുവരെ യാതൊരു യാത്രകളും ഷെഡ്യൂൾ ചെയ്തിട്ടില്ല!"
        RIDE_BOOKING -> "റൈഡ് ബുക്കിംഗ്."
        SPECIAL_ZONE_RENTAL_INELIGIBLE -> "പ്രത്യേക മേഖലയിലുള്ള സ്ഥലങ്ങൾ വാടക യാത്രകൾക്ക് അയോഗ്യമാണ്."
        SERVICES -> "സേവനങ്ങള്"
        YOU_HAVE_UPCOMING_RENTAL_BOOKING bookingTime -> "നിങ്ങൾക്ക് <b>" <> bookingTime <> "</b>-ന് വരാനിരിക്കുന്ന വാടക ബുക്കിംഗ് ഉണ്ട്"
        YOU_HAVE_UPCOMING_INTERCITY_BOOKING bookingTime -> "നിങ്ങൾക്ക് <b>" <> bookingTime <> "</b>-ന് വരാനിരിക്കുന്ന അന്തർനഗര ബുക്കിംഗ് ഉണ്ട്"
        SCHEDULED -> "ഷെഡ്യൂൽ ചെയ്തിട്ടുണ്ട്"
        UPCOMING_BOOKINGS -> "നിങ്ങൾക്ക് അടിയന്തരാവക ബുക്കിങ്ങുകൾ ഉണ്ട്"
        RENTALS_ -> "വാടകകൾ"
        INTER_CITY_ -> "അന്തർനഗരം"
        A_RIDE_ALREADY_EXISTS -> "ഒരു റൈഡ് ഇതായിരിക്കുന്നു."
        YOU_HAVE_AN_RIDE_FROM_TO_SCHEDULED_FROM_TILL -> "നിങ്ങൾക്ക് {} റൈഡ് {} നും {} വരെ നിര്‍ധാരിച്ച നിലവാരം {} നു തന്നെ {} വരെ ഷെഡ്യൂൾ ചെയ്യപ്പെട്ടിരിക്കുന്നു. നിങ്ങൾക്ക് സാധാരണ റൈഡുകൾ എടുക്കാം അല്ലെങ്കിൽ ഇതിനൊക്കെ ഇതിനായി പുതിയ റൈഡുകൾ ഷെഡ്യൂൽ ചെയ്യാൻ നിങ്ങൾക്ക് അനുവാദമുണ്ട്, ഇത് മികച്ചതായ സമയം താഴെയുള്ള ഷെഡ്യൂൾ ചെയ്ത റൈഡുകളുമായി അവസാനിച്ചിട്ടില്ലെങ്കിൽ മാത്രമേ അന്യ റൈഡുകൾ ഷെഡ്യൂൾ ചെയ്യാനോ അല്ലെങ്കിൽ അവയുടെ സമയപട്ടി പുനർനിയമിക്കാൻ സാധിക്കും."
        EXTRA_PER_KM_FARE -> "ഓരോ കിലോമീറ്ററിനും അധിക നിരക്ക്"
        EXTRA_PER_MINUTE_FARE -> "ഓരോ മിനിറ്റിനും അധിക നിരക്ക്"
        PICKUP_CHARGES -> "പിക്കപ്പ് ചാർജുകൾ"
        WAITING_CHARGES_AFTER_3_MINS -> "3 മിനിറ്റ് ശേഷം കാത്തിരിക്കലുള്ള ചാർജുകൾ"
        FARE_DETERMINED_AS_PER_KARNATAKA_GUIDELINES -> "കർണാടക സർക്കാർ മാർഗനിർദേശങ്ങൾ പ്രകാരം നിശ്ചയിക്കപ്പെട്ട നിരക്ക്"
        RENTAL_CHARGES -> "വാടക ചാർജുകൾ"
        RENTAL_INFO_POLICY_DESC inclusiveKms -> "ഓരോ മണിക്കൂർ വാടക ബുക്കിംഗിനും " <> inclusiveKms <> " കിലോമീറ്റർ നിങ്ങളുടെ പാക്കേജിൽ ഉൾപ്പെടുത്തിയിരിക്കുന്നു."
        RENTAL_INFO_POLICY_DESC_ -> "അടിസ്ഥാന ദൂരം മതിയായില്ലെങ്കിൽ, നിങ്ങൾക്ക് അധിക കിലോമീറ്ററുകൾ ചേർക്കാം കൂടാതെ അധിക ചെലവുകളിൽ നിന്നും ലാഭിക്കാം."
        RENTAL_SCREEN_EXPLAINER -> "നിങ്ങൾക്ക് ഇപ്പോൾ കിഴിവ് നിരക്കിൽ അധിക കിലോമീറ്ററുകൾ ചേർക്കാം. ഇങ്ങനെ, നിങ്ങൾക്ക് പിന്നീട് ഉപയോഗിക്കുന്ന അധിക ദൂരത്തിനുള്ള ഉയർന്ന നിരക്കുകൾ ഒഴിവാക്കാം."
        INSTANT -> "തൽക്ഷണം"
        COMING_SOON -> "ഉടൻ!"
        CANCEL_SCHEDULED_RIDE -> "ഷെഡ്യൂൾ ചെയ്ത റൈഡ് റദ്ദാക്കുക"
        CANCEL_SCHEDULED_RIDE_DESC -> "ഈ റൈഡ് റദ്ദാക്കണമെന്ന് തീർച്ചയാണോ?<br><br>(ഒന്നിലധികം റദ്ദാക്കലുകൾ നിങ്ങളെ കൂടുതൽ വാടക റൈഡുകൾ അഭ്യർത്ഥിക്കുന്നതിൽ നിന്ന് തടഞ്ഞേക്കാം)"
        CONFIRM_CANCELLATION -> "റദ്ദാക്കൽ സ്ഥിരീകരിക്കുക"
        INTERCITY_RIDES_COMING_SOON -> "ഇൻ്റർസിറ്റി റൈഡുകൾ ഉടൻ വരുന്നു!"
        VIEW_FARES -> "നിരക്കുകൾ കാണുക"
        EXCESS_TIME_DESCRIPTION charges -> "അധിക സമയം " <> charges <> " നിരക്കിൽ ഈടാക്കും"
        ESTIMATED_CHARGES -> "കണക്കാക്കിയ നിരക്കുകൾ"
        NIGHT_TIME_FEES -> "രാത്രിയിലെ സമയ ചാര്ജുകൾ"
        PARKING_AND_OTHER_CHARGES -> "പാർക്കിംഗ് മറ്റ് ചാര്ജുകൾ"
        ADDITIONAL_CHARGES -> "അതിരിക്കുന്ന ചാര്ജുകൾ"
        ESTIMATED_BASE_FARE -> "അനുമാനിക്കുന്ന ബേസ് ഫെയർ"
        INCLUDED_DISTANCE -> "അടിസ്ഥാന ദൂരം"
        INCLUDED_TIME -> "അടിസ്ഥാന സമയം"
        TOLL_CHARGES_DESCRIPTION -> "പ്രയോഗിക്കുന്ന ടോൾ ചാർജുകൾ അവസാന ഫെയർക്ക് ചേർക്കപ്പെടും"
        WILL_BE_ADDED_TO_FINAL_FARE -> "അവസാന ഫെയർക്ക് ചേർക്കപ്പെടും"
        EXTRA_DISTANCE_FARE -> "അധിക ദൂരം നിരക്ക്"
        NETWORK_ERROR -> "നെറ്റ്‌വർക്ക് പിശക്"
        SERVER_ERROR -> "സെർവർ തകരാർ"
        UNKNOWN_ERROR -> "അജ്ഞാത പിശക്"
        CONNECTION_REFUSED -> "കണക്ഷൻ നിരസിച്ചു"
        TIMEOUT -> "ടൈം ഔട്ട്"
        WAS_TOLL_EXP_SMOOTH -> "നിങ്ങളുടെ ടോൾ അനുഭവം സുഗമമായിരുന്നോ?"
        WAS_TOLL_EXP_SMOOTH_DESC -> "ടോൾ ചാർജ്ജുകൾ കണക്കാക്കി\nശരിയായിരുന്നുവോ ?"
        WAS_RIDE_SAFE -> "നിങ്ങൾക്ക് സുരക്ഷിതമായ യാത്ര ഉണ്ടായിരുന്നോ?"
        WAS_RIDE_SAFE_DESC -> "നിങ്ങളുടെ യാത്ര തൃപ്തികരമായി സുരക്ഷിതവും\nവിഷമരഹിതവുമായിരുന്നു?"
        WAS_DRIVER_HELPFUL -> "ഡ്രൈവർ സഹായം വാഗ്ദാനം ചെയ്തോ?"
        WAS_DRIVER_HELPFUL_DESC -> "നിങ്ങളുടെ ഡ്രൈവർ നിങ്ങളുടെ ആവശ്യങ്ങൾ മനസ്സിലാക്കുകയും യാത്രയിൽ അവരെ ഉൾക്കൊള്ളുകയും ചെയ്തിരുന്നോ?"
        COLLECT_TOLL_SEP -> "ദയവായി <b>ഒരു ടോൾ മറികടന്നാൽ മാത്രം</b> ഡ്രൈവർക്ക് അത് പ്രത്യേകം നൽകൂ"
        FINAL_FARE_EXCLUDES_TOLL -> "അന്തിമ നിരക്ക് ടോൾ നിരക്കുകൾ ഒഴിവാക്കുന്നു"
        TOLL_CHARGES_MAYBE_APPLICABLE -> "ടോൾ നിരക്കുകൾ ബാധകമായേക്കാം"
        METRO_BANNER_TITLE appName -> "മെട്രോ ടിക്കറ്റുകൾ ബുക്ക് ചെയ്യുക \n" <> appName <> " ഇപ്പോൾ!"
        VIEW_ON_GOOGLE_MAPS -> "ഗൂഗിൾ മാപ്പിൽ കാണുക"
        WALKING_DIRECTIONS_TO_PICKUP -> "പിക്കപ്പിനേയ്ക്ക് നടപടികൾ"
        EXPLORE_CITY_WITH_US city -> "ഞങ്ങളോടൊപ്പം " <> city <> " അന്വേഷിക്കുക"
        GO_TO_DESTINATION destination -> "ഗോ ടു " <> destination
        WALK_TO address -> address <> " ലേക്ക് നടക്കുക"
        BANGALORE -> "ബെംഗളൂരു"
        KOLKATA -> "കൊല്‍ക്കത്ത"
        PARIS -> "പാരിസ്"
        KOCHI -> "കൊച്ചി"
        DELHI -> "ഡെല്‍ഹി"
        HYDERABAD -> "ഹൈദരാബാദ്"
        MUMBAI -> "മുംബൈ"
        CHENNAI -> "ചെന്നൈ"
        COIMBATORE -> "കോയമ്പത്തൂര്"
        PONDICHERRY -> "പുതുച്ചേരി"
        GOA -> "ഗോവ"
        PUNE -> "പൂന"
        MYSORE -> "മൈസൂരു"
        TUMAKURU -> "തുമകൂരു"
        NOIDA -> "നോയിഡ"
        GURUGRAM -> "ഗുരുഗ്രാം"
        WAITING_CHARGES -> "കാത്തിരിക്കൽ ചാർജുകൾ"
        SILIGURI -> "സിലിഗുരി"
