
# @name check-mock-bpp
GET {{mock-parking-bpp-host}}

###
# @name check-bap
GET {{parking-bap-host}}

###

# @name search
POST {{parking-bap-host}}/parking/search
content-type: application/json
token: {{app-token}}

{
    "location": {
      "lat": "20",
      "lon": "20"
    },
    "toDate": "2021-12-10T18:00:00Z",
    "fromDate": "2021-12-11T09:00:00Z"
}

###
@searchId = {{search.response.body.searchId}}

# @name quotes
GET {{parking-bap-host}}/parking/{{searchId}}/quotes
token: {{app-token}}

###
@quoteId = {{quotes.response.body.quotes[0].id}}
@quoteIdFail = {{quotes.response.body.quotes[1].id}}

# @name confirm
POST {{parking-bap-host}}/parking/quotes/{{quoteIdFail}}/confirm
content-type: application/json
token: {{app-token}}

{
    "requestorNumber": "1234",
    "vehicleNumber": "vehnum",
    "requestorName": "Pavsikakiy"
}

###
@bookingId = {{confirm.response.body.bookingId}}

# @name booking

GET {{parking-bap-host}}/parking/booking/{{bookingId}}
token: {{app-token}}

