@parking-bpp-host = http://localhost:9090

# @name health-check

GET {{parking-bpp-host}}/health

###

# @name check-bpp
POST {{parking-bpp-host}}/search
Content-Type: application/json

{
    "msg": "hello"
}